# Project 2
Mitchell Morrison and Christian Gould

We have decided to use the COVID 19 dataset in pair with a dataset of holidays and their dates around the world. We plan on enriching the COVID dataset by showing the relationship between the period following a holiday and the level of covid in the country celebrating. The COVID dataset was gathered for the purpose of testing it in conjunction with holiday data. 

Dataset links:
1. https://www.kaggle.com/sandhyakrishnan02/latest-covid-19-dataset-worldwide
2. https://www.kaggle.com/vbmokin/covid19-holidays-of-countries?select=holidays_df_of_70_countries_for_covid_19.csv

# Part 1 - Getting Started
Import libraries
Load original Data (which ever one you chose from the provided list) into a data frame.
Load your additional data set(s) into a data frame.
In a markdown cell, provide a brief description of your the data sets you've chosen to work with.
Develop a list of 3 - 4 questions that you hope to be able to answer after the exploration of the data and write them in this section.

# Part 2 - Data Inspection
Write some code to summarize the datasets. Think about the following questions:

What type of data is each variable? (think like a data scientist here, not a computer scientist)<br>
What is the total size of the data sets?<br>
What time boundaries are there in the dataset? IOW, what time frame do they span?<br>
Are there any missing values in any of the variables?<br>
Do this with Intentionality. Don't skimp.<br>

In [2]:
import numpy as np
import pandas as pd

## Understanding our datasets

### Holidays dataset

In [3]:
holidays = pd.read_csv('datasets/holidays_df_of_70_countries_for_covid_19.csv')
holidays.head()

,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
0,2020-02-24,Día de Carnaval [Carnival's Day],2020-03-02,Argentina,AR,Argentine Republic,-3,3,10,https://github.com/dr-prodigy/python-holidays
1,2020-02-25,Día de Carnaval [Carnival's Day],2020-03-03,Argentina,AR,Argentine Republic,-3,3,10,https://github.com/dr-prodigy/python-holidays
2,2020-03-24,Día Nacional de la Memoria por la Verdad y la ...,2020-03-31,Argentina,AR,Argentine Republic,-3,3,10,https://github.com/dr-prodigy/python-holidays
3,2020-04-09,Semana Santa (Jueves Santo) [Holy day (Holy T...,2020-04-16,Argentina,AR,Argentine Republic,-3,3,10,https://github.com/dr-prodigy/python-holidays
4,2020-04-10,Semana Santa (Viernes Santo) [Holy day (Holy ...,2020-04-17,Argentina,AR,Argentine Republic,-3,3,10,https://github.com/dr-prodigy/python-holidays

In [4]:
holidays.columns

Index(['ds_holidays', 'holiday', 'ds', 'country', 'code',
       'country_official_name', 'lower_window', 'upper_window', 'prior_scale',
       'source'],
      dtype='object')

In [5]:
holidays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806 entries, 0 to 805
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ds_holidays            806 non-null    object
 1   holiday                806 non-null    object
 2   ds                     806 non-null    object
 3   country                806 non-null    object
 4   code                   806 non-null    object
 5   country_official_name  806 non-null    object
 6   lower_window           806 non-null    int64
 7   upper_window           806 non-null    int64
 8   prior_scale            806 non-null    int64
 9   source                 806 non-null    object
dtypes: int64(3), object(7)
memory usage: 63.1+ KB

All holidays are in a Date string format and the countries and country codes are all strings. The lower and upper window variables are ints.

In [6]:
holidays.describe()

       lower_window  upper_window  prior_scale
count         806.0         806.0        806.0
mean           -3.0           3.0         10.0
std             0.0           0.0          0.0
min            -3.0           3.0         10.0
25%            -3.0           3.0         10.0
50%            -3.0           3.0         10.0
75%            -3.0           3.0         10.0
max            -3.0           3.0         10.0

This .describe means nothing to us because all the columns of interest are categorical. We are really only using this table to gather the holidays dates and the corresponding country where the holiday is celebrated.

In [7]:
min(holidays.ds), max(holidays.ds)

('2020-01-28', '2021-01-07')

The holidays dataset ranges in dates from Jan 28th 2020 to Jan 7th 2021.

### COVID 19 dataset

In [46]:
covid = pd.read_csv('datasets/owid-covid-data.csv')
covid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [47]:
columnsOfInterest = ['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
        'new_cases_smoothed', 'total_deaths', 'new_deaths', 'total_cases_per_million',
        'new_cases_per_million', 'new_cases_smoothed_per_million']
covid[columnsOfInterest]

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,0.126,0.126,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,0.126,0.000,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,0.126,0.000,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,0.126,0.000,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,0.126,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
153167,ZWE,Africa,Zimbabwe,2022-01-04,217678.0,1591.0,1447.143,5078.0,31.0,14423.240,105.419,95.887
153168,ZWE,Africa,Zimbabwe,2022-01-05,219057.0,1379.0,1644.143,5092.0,14.0,14514.612,91.372,108.940
153169,ZWE,Africa,Zimbabwe,2022-01-06,220178.0,1121.0,1207.143,5108.0,16.0,14588.889,74.277,79.985
153170,ZWE,Africa,Zimbabwe,2022-01-07,221282.0,1104.0,1146.286,5136.0,28.0,14662.039,73.151,75.952
153171,ZWE,Africa,Zimbabwe,2022-01-08,221918.0,636.0,1100.571,5148.0,12.0,14704.180,42.141,72.923

In [48]:
covid = covid[columnsOfInterest]

In [49]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153172 entries, 0 to 153171
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   iso_code                        153172 non-null  object
 1   continent                       143944 non-null  object
 2   location                        153172 non-null  object
 3   date                            153172 non-null  object
 4   total_cases                     150522 non-null  float64
 5   new_cases                       150431 non-null  float64
 6   new_cases_smoothed              149280 non-null  float64
 7   total_deaths                    133279 non-null  float64
 8   new_deaths                      133441 non-null  float64
 9   total_cases_per_million         149820 non-null  float64
 10  new_cases_per_million           149729 non-null  float64
 11  new_cases_smoothed_per_million  148583 non-null  float64
dtypes: float64(8), object(4)
memory usage: 14.0+ MB

In [50]:
covid.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million
count,1.505220e+05,1.504310e+05,1.492800e+05,1.332790e+05,133441.000000,149820.000000,149729.000000,148583.000000
mean,2.140423e+06,8.514960e+03,8.362923e+03,5.286023e+04,170.514032,23484.220297,107.848851,104.305831
std,1.268426e+07,5.147776e+04,4.782771e+04,2.779311e+05,831.031112,38303.228732,376.402439,253.818949
min,1.000000e+00,-7.434700e+04,-6.223000e+03,1.000000e+00,-1918.000000,0.001000,-3125.829000,-272.971000
25%,1.581250e+03,1.000000e+00,5.857000e+00,6.800000e+01,0.000000,514.036750,0.023000,1.444000
50%,2.077650e+04,7.000000e+01,9.200000e+01,6.770000e+02,2.000000,4015.258000,10.076000,15.922000
75%,2.566742e+05,9.250000e+02,9.758927e+02,6.467500e+03,19.000000,30741.449500,86.812000,99.436000
max,3.051916e+08,2.879121e+06,2.265658e+06,5.484782e+06,18062.000000,341391.525000,51427.491000,7842.850000

This .describe function explains to us many variables related to the cases counts in many locations. However, this data does not give light to many of the different countries and the scale of the differences in their values.

In [51]:
min(covid.date), max(covid.date)

('2020-01-01', '2022-01-08')

In [52]:
covid.isna().sum()

iso_code                              0
continent                          9228
location                              0
date                                  0
total_cases                        2650
new_cases                          2741
new_cases_smoothed                 3892
total_deaths                      19893
new_deaths                        19731
total_cases_per_million            3352
new_cases_per_million              3443
new_cases_smoothed_per_million     4589
dtype: int64

In [53]:
covid[covid["location"] == "Albania"].head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million
1381,ALB,Europe,Albania,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,ALB,Europe,Albania,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383,ALB,Europe,Albania,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1384,ALB,Europe,Albania,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1385,ALB,Europe,Albania,2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

TODO: Make comments about empty nesss

## Questions to answer
1. Is there a relationship between a country's holidays and COVID cases the week following?
2. Based on the previous question, which countries are best at mitigating new cases following holidays?
3. How long after holidays until cases return to normal?
4. Which holidays have the worst effect of COVID cases?

## Merging our datasets
### We will merge these two dataframes using a left join on the COVID table with the country and date attributes
It may also work to use an inner join to only keep days that are holidays and the window of transmission that we are interested in

# Part 3

* Create a data description (data dictionary) for your data sets.
* Describe each variable
* If categorical, what levels are present? If the levels are encoded, what do the codes mean?
* If numeric, provide min, max, median and any other univariate stats you'd like to add in.
* Where appropriate, provide histograms or other visualizations to characterize each variable.

### What are our variables from the holiday dataset?

* ds_holidays - date of the holiday
* date format - YYYY-MM-DD
* holiday - name of the holiday
    ex. Christmas
* ds - ds_holidays plus time delta of 7 days
* country - country of holiday
* code - conutry abbreviation
* country_official_name - formal country name
* lower_window - ds minus time delta of 3 days (early COVID onset boundary)
* upper_window - ds plus time delta of 3 days (late COVID onset boundary)
* prior_scale -
* source - where holiday data is retrieved from

Of these, we are only interested in: country, ds, ds_holidays

This is because we are only interested in the dates of the holidays and the country that the holiday is in. ds is not necessary, but is helpful in order for us to check dates that are a week away from the holiday.
Here is the range of the dates in the holiday set:

### Variables from COVID dataset

Wow, our COVID dataset has a ton of columns!! Lets narrow it down to only columns that are related to transmission and testing results. <br>
These columns are:
<list>
    <li> iso_code - country code
    <li> continent - exactly what you think
    <li> location - country name
    <li> date - date of record for instance
    <li> total_cases - total covid cases for the country
    <li> new_cases - new cases this day
    <li> new_cases_smoothed - new cases smoothed over 7 day period
    <li> total_deaths - total deaths for the country
    <li> new_deaths - new deaths this day
    <li> total_cases_per_million - ratio of total cases to million of population
    <li> new_cases_per_million - ratio of new cases today to million of population
    <li> new_cases_smoothed_per_million - ratio of new cases smoothed over 7 day period to million of population
    <li> reproduction_rate - real time estimate of transmission factor of covid

# Part 4 - Merging

To merge our COVID 19 and Holiday datasets, we need to know what columns will be used to join upon and what type of join we should use depending on the Key columns. In our case the COVID 19 dataset uses attributes location and date as the unique identifiers for each instance of data. Similarly, the Holidays dataset uses the country and ds_holidays to indicate unique holidays for each country and the date(s) it falls on.

Since we will be using the COVID dataset in conjunction with holidays and more specifically, the covid data following holidays, we want to keep all instances of COVID data even if a holiday does not fall on that day of the row exactly. And since every holiday must fall on a day of the year, all of the rows in holidays will be joined on their respective row in the COVID dataset. Given that we want to keep all the COVID data, we are using a left join on the COVID table. This will however mean that there will be lots of NaN values in the holiday related columns of the new merged dataset because there is far more days in a year than holidays in a year. After all, holidays wouldn't be special if they were every day.

In [42]:
merged_df = pd.merge(covid, holidays,  how='left', left_on=['location','date'], right_on = ['country','ds_holidays'])

In [43]:
merged_df.head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AFG,Asia,Afghanistan,2020-02-29,5.0,0.0,0.714,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AFG,Asia,Afghanistan,2020-03-01,5.0,0.0,0.714,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,AFG,Asia,Afghanistan,2020-03-02,5.0,0.0,0.000,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,AFG,Asia,Afghanistan,2020-03-03,5.0,0.0,0.000,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AFG,Asia,Afghanistan,2020-03-04,5.0,0.0,0.000,NaN,NaN,0.126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
merged_df[merged_df["location"] == "Albania"].head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
1381,ALB,Europe,Albania,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,ALB,Europe,Albania,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383,ALB,Europe,Albania,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1384,ALB,Europe,Albania,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1385,ALB,Europe,Albania,2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
negative_cases = merged_df[merged_df["new_cases"] < 0]
negative_cases[negative_cases["iso_code"] == "GBR"]

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
144530,GBR,Europe,United Kingdom,2021-04-09,4369512.0,-4860.0,1684.857,127126.0,60.0,64062.409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144569,GBR,Europe,United Kingdom,2021-05-18,4454451.0,-2364.0,1529.000,127777.0,7.0,65307.718,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
GBR_data = merged_df[merged_df["iso_code"] == "GBR"] 
GBR_data[GBR_data["date"].between("2021-04-01", "2021-04-11")]

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
144522,GBR,Europe,United Kingdom,2021-04-01,4354316.0,4479.0,4448.857,126850.0,51.0,63839.616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144523,GBR,Europe,United Kingdom,2021-04-02,4357718.0,3402.0,4051.000,126902.0,52.0,63889.494,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144524,GBR,Europe,United Kingdom,2021-04-03,4361141.0,3423.0,3987.857,126912.0,10.0,63939.679,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144525,GBR,Europe,United Kingdom,2021-04-04,4363438.0,2297.0,3764.286,126922.0,10.0,63973.356,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144526,GBR,Europe,United Kingdom,2021-04-05,4366200.0,2762.0,3494.000,126948.0,26.0,64013.851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144527,GBR,Europe,United Kingdom,2021-04-06,4368580.0,2380.0,3256.429,126968.0,20.0,64048.744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144528,GBR,Europe,United Kingdom,2021-04-07,4371342.0,2762.0,3072.143,127013.0,45.0,64089.239,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144529,GBR,Europe,United Kingdom,2021-04-08,4374372.0,3030.0,2865.143,127066.0,53.0,64133.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144530,GBR,Europe,United Kingdom,2021-04-09,4369512.0,-4860.0,1684.857,127126.0,60.0,64062.409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144531,GBR,Europe,United Kingdom,2021-04-10,4372096.0,2584.0,1565.000,127166.0,40.0,64100.293,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144532,GBR,Europe,United Kingdom,2021-04-11,4373826.0,1730.0,1484.000,127173.0,7.0,64125.657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Part 5 - Explore Bivariate relationships

* Choose a reasoned set of variables to explore further. You don't have to explore all possible pairs of variables, nor do we want to grade that much. Choose 7 - 9 variables. One should be a variable that you'd like to predict (target variable) using the others (predictor variables).
* List your predictor variables
* List your target variable
* Briefly describe why you have chosen these.
* Use any of the available visualizations from Seaborn to explore the relationships between the variables. Explore the relationships among the predictor variables as well as the relationship between each predictor variable and the target variable. Which of the predictor variables are most strongly related? Are there any interesting relationships between categorical predictors and numeric predictors? If there are any dichotomous variables, does that influence any of the relationships? Are the relationships positive or negative?

Below each plot, you should provide a description and interpretation of the plot. Make sure to include why the variables in that plot were chosen and what you hope the reader would gain from it as well.

To explore the relationships between our variables and to answer the questions we have defined in part 1, we need to define what our prdictor and target variables are.

Out target variables are the columns new_cases and new_cases_per_million. This is because we are trying to uncover relationships between our other variables and the COVID cases the following week. Using new_cases_per_million as a target variable will let us more accurately compare results across different countries since their sizes/populations are different. We will also just use new_cases because this will also give us meaningful information (with respect to the country that the data belongs).

We will use the holiday dates from the holiday dataset as our main relationship variable. This is because we are trying to explore the relationship between holidays and COVID spikes following that day. Other predictor variables include the country and previous new_cases. Our variables are not predictors, we are trying to explore the relationship between these target and "predictors".

We have chosen the date of the holiday and the country as the predictors because these variables are specific to the COVID data we have been given and thus can only explore the relationship we see between dates, country, and cases. From the last few years, it has become clear that we cannot predict COVID just using the previous new_cases data, similar to how stocks cannot be predicted using historical prices.

### We need to reduce our tables to usable data

We need to get rid of all instances of country COVID data that do not exist in the holiday table.

In [64]:
countryGroups = merged_df.groupby('location')
for k, v in countryGroups:
    if all(v["holiday"].isnull()):
        merged_df.drop(merged_df[merged_df['location'] == k].index, inplace = True)
merged_df["location"].unique()

array(['Albania', 'Argentina', 'Australia', 'Austria', 'Bangladesh',
       'Belarus', 'Belgium', 'Brazil', 'Bulgaria', 'Burundi', 'Canada',
       'Chile', 'China', 'Colombia', 'Croatia', 'Czechia', 'Denmark',
       'Dominican Republic', 'Egypt', 'Estonia', 'Finland', 'France',
       'Georgia', 'Germany', 'Greece', 'Honduras', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Kenya', 'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Mexico',
       'Moldova', 'Morocco', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Nigeria', 'Norway', 'Pakistan', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Romania', 'Serbia', 'Singapore', 'Slovakia',
       'Slovenia', 'South Africa', 'Spain', 'Sweden', 'Switzerland',
       'Thailand', 'Turkey', 'Ukraine', 'United Kingdom', 'United States'],
      dtype=object)

We also need to drop rows that do not have COVID case data

In [61]:
merged_df.dropna(subset=["new_cases"], inplace=True)

In [62]:
merged_df[merged_df["location"] == "Albania"].head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds_holidays,holiday,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source
1394,ALB,Europe,Albania,2020-03-09,2.0,2.0,NaN,NaN,NaN,0.696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1395,ALB,Europe,Albania,2020-03-10,10.0,8.0,NaN,NaN,NaN,3.481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,ALB,Europe,Albania,2020-03-11,12.0,2.0,NaN,1.0,1.0,4.177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1397,ALB,Europe,Albania,2020-03-12,23.0,11.0,NaN,1.0,0.0,8.006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1398,ALB,Europe,Albania,2020-03-13,33.0,10.0,NaN,1.0,0.0,11.487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1399,ALB,Europe,Albania,2020-03-14,38.0,5.0,5.429,1.0,0.0,13.227,...,2020-03-14,Summer Day,2020-03-21,Albania,AL,Republic of Albania,-3.0,3.0,10.0,https://en.wikipedia.org/wiki/Public_holidays_...
1400,ALB,Europe,Albania,2020-03-15,42.0,4.0,6.000,1.0,0.0,14.619,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1401,ALB,Europe,Albania,2020-03-16,51.0,9.0,7.000,1.0,0.0,17.752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1402,ALB,Europe,Albania,2020-03-17,55.0,4.0,6.429,1.0,0.0,19.144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1403,ALB,Europe,Albania,2020-03-18,59.0,4.0,6.714,2.0,1.0,20.536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### First relationship exploration - Holidays and COVID cases 7 days later

First we will explore how holidays and COVID cases are related 7 days later for each country.

In [81]:
from datetime import timedelta

merged_df["7_days_later"] = merged_df["date"].shift(-7)
merged_df["7_days_later_cases"] = np.nan

merged_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source,7_days_later,7_days_later_cases
1394,ALB,Europe,Albania,2020-03-09,2.0,2.0,NaN,NaN,NaN,0.696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-16,NaN
1395,ALB,Europe,Albania,2020-03-10,10.0,8.0,NaN,NaN,NaN,3.481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-17,NaN
1396,ALB,Europe,Albania,2020-03-11,12.0,2.0,NaN,1.0,1.0,4.177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-18,NaN
1397,ALB,Europe,Albania,2020-03-12,23.0,11.0,NaN,1.0,0.0,8.006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-19,NaN
1398,ALB,Europe,Albania,2020-03-13,33.0,10.0,NaN,1.0,0.0,11.487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN

In [111]:
%time
for row in merged_df.iterrows():
#     print(row)
    new_cases = merged_df.loc[merged_df["date"] == row[1]["7_days_later"]]
    new_cases = new_cases.loc[merged_df["location"] == row[1]["location"]]
#     print(row[0], new_cases["new_cases"])
    if (new_cases["new_cases"].dtype is float):
        merged_df.at[row[0], "7_days_later_cases"] = new_cases["new_cases"] 
merged_df.new_cases.fillna(0, inplace=True)

merged_df.head(15)

1394 1401    9.0
Name: new_cases, dtype: float64
1395 1402    4.0
Name: new_cases, dtype: float64
1396 1403    4.0
Name: new_cases, dtype: float64
1397 1404    5.0
Name: new_cases, dtype: float64
1398 1405    6.0
Name: new_cases, dtype: float64
1399 1406    6.0
Name: new_cases, dtype: float64
1400 1407    13.0
Name: new_cases, dtype: float64
1401 1408    15.0
Name: new_cases, dtype: float64
1402 1409    19.0
Name: new_cases, dtype: float64
1403 1410    23.0
Name: new_cases, dtype: float64
1404 1411    28.0
Name: new_cases, dtype: float64
1405 1412    12.0
Name: new_cases, dtype: float64
1406 1413    11.0
Name: new_cases, dtype: float64
1407 1414    15.0
Name: new_cases, dtype: float64
1408 1415    11.0
Name: new_cases, dtype: float64
1409 1416    20.0
Name: new_cases, dtype: float64
1410 1417    16.0
Name: new_cases, dtype: float64
1411 1418    18.0
Name: new_cases, dtype: float64
1412 1419    27.0
Name: new_cases, dtype: float64
1413 1420    29.0
Name: new_cases, dtype: float64
1414 1421    28.0
Name: new_cases, dtype: float64
1415 1422    16.0
Name: new_cases, dtype: float64
1416 1423    6.0
Name: new_cases, dtype: float64
1417 1424    17.0
Name: new_cases, dtype: float64
1418 1425    9.0
Name: new_cases, dtype: float64
1419 1426    7.0
Name: new_cases, dtype: float64
1420 1427    17.0
Name: new_cases, dtype: float64
1421 1428    13.0
Name: new_cases, dtype: float64
1422 1429    21.0
Name: new_cases, dtype: float64
1423 1430    8.0
Name: new_cases, dtype: float64
1424 1431    19.0
Name: new_cases, dtype: float64
1425 1432    24.0
Name: new_cases, dtype: float64
1426 1433    21.0
Name: new_cases, dtype: float64
1427 1434    9.0
Name: new_cases, dtype: float64
1428 1435    14.0
Name: new_cases, dtype: float64
1429 1436    22.0
Name: new_cases, dtype: float64
1430 1437    25.0
Name: new_cases, dtype: float64
1431 1438    25.0
Name: new_cases, dtype: float64
1432 1439    29.0
Name: new_cases, dtype: float64
1433 1440    15.0
Name: new_cases, dtype: float64
1434 1441    34.0
Name: new_cases, dtype: float64
1435 1442    14.0
Name: new_cases, dtype: float64
1436 1443    10.0
Name: new_cases, dtype: float64
1437 1444    14.0
Name: new_cases, dtype: float64
1438 1445    16.0
Name: new_cases, dtype: float64
1439 1446    7.0
Name: new_cases, dtype: float64
1440 1447    9.0
Name: new_cases, dtype: float64
1441 1448    7.0
Name: new_cases, dtype: float64
1442 1449    6.0
Name: new_cases, dtype: float64
1443 1450    8.0
Name: new_cases, dtype: float64
1444 1451    17.0
Name: new_cases, dtype: float64
1445 1452    12.0
Name: new_cases, dtype: float64
1446 1453    10.0
Name: new_cases, dtype: float64
1447 1454    8.0
Name: new_cases, dtype: float64
1448 1455    6.0
Name: new_cases, dtype: float64
1449 1456    12.0
Name: new_cases, dtype: float64
1450 1457    4.0
Name: new_cases, dtype: float64
1451 1458    4.0
Name: new_cases, dtype: float64
1452 1459    4.0
Name: new_cases, dtype: float64
1453 1460    18.0
Name: new_cases, dtype: float64
1454 1461    18.0
Name: new_cases, dtype: float64
1455 1462    17.0
Name: new_cases, dtype: float64
1456 1463    13.0
Name: new_cases, dtype: float64
1457 1464    2.0
Name: new_cases, dtype: float64
1458 1465    1.0
Name: new_cases, dtype: float64
1459 1466    15.0
Name: new_cases, dtype: float64
1460 1467    5.0
Name: new_cases, dtype: float64
1461 1468    12.0
Name: new_cases, dtype: float64
1462 1469    8.0
Name: new_cases, dtype: float64
1463 1470    9.0
Name: new_cases, dtype: float64
1464 1471    6.0
Name: new_cases, dtype: float64
1465 1472    25.0
Name: new_cases, dtype: float64
1466 1473    21.0
Name: new_cases, dtype: float64
1467 1474    26.0
Name: new_cases, dtype: float64
1468 1475    23.0
Name: new_cases, dtype: float64
1469 1476    23.0
Name: new_cases, dtype: float64
1470 1477    15.0
Name: new_cases, dtype: float64
1471 1478    6.0
Name: new_cases, dtype: float64
1472 1479    21.0
Name: new_cases, dtype: float64
1473 1480    20.0
Name: new_cases, dtype: float64
1474 1481    13.0
Name: new_cases, dtype: float64
1475 1482    15.0
Name: new_cases, dtype: float64
1476 1483    20.0
Name: new_cases, dtype: float64
1477 1484    14.0
Name: new_cases, dtype: float64
1478 1485    17.0
Name: new_cases, dtype: float64
1479 1486    36.0
Name: new_cases, dtype: float64
1480 1487    42.0
Name: new_cases, dtype: float64
1481 1488    44.0
Name: new_cases, dtype: float64
1482 1489    31.0
Name: new_cases, dtype: float64
1483 1490    48.0
Name: new_cases, dtype: float64
1484 1491    57.0
Name: new_cases, dtype: float64
1485 1492    69.0
Name: new_cases, dtype: float64
1486 1493    82.0
Name: new_cases, dtype: float64
1487 1494    50.0
Name: new_cases, dtype: float64
1488 1495    66.0
Name: new_cases, dtype: float64
1489 1496    50.0
Name: new_cases, dtype: float64
1490 1497    53.0
Name: new_cases, dtype: float64
1491 1498    71.0
Name: new_cases, dtype: float64
1492 1499    33.0
Name: new_cases, dtype: float64
1493 1500    52.0
Name: new_cases, dtype: float64
1494 1501    67.0
Name: new_cases, dtype: float64
1495 1502    78.0
Name: new_cases, dtype: float64
1496 1503    77.0
Name: new_cases, dtype: float64
1497 1504    61.0
Name: new_cases, dtype: float64
1498 1505    72.0
Name: new_cases, dtype: float64
1499 1506    64.0
Name: new_cases, dtype: float64
1500 1507    69.0
Name: new_cases, dtype: float64
1501 1508    45.0
Name: new_cases, dtype: float64
1502 1509    82.0
Name: new_cases, dtype: float64
1503 1510    90.0
Name: new_cases, dtype: float64
1504 1511    67.0
Name: new_cases, dtype: float64
1505 1512    74.0
Name: new_cases, dtype: float64
1506 1513    71.0
Name: new_cases, dtype: float64
1507 1514    74.0
Name: new_cases, dtype: float64
1508 1515    68.0
Name: new_cases, dtype: float64
1509 1516    82.0
Name: new_cases, dtype: float64
1510 1517    90.0
Name: new_cases, dtype: float64
1511 1518    93.0
Name: new_cases, dtype: float64
1512 1519    83.0
Name: new_cases, dtype: float64
1513 1520    117.0
Name: new_cases, dtype: float64
1514 1521    96.0
Name: new_cases, dtype: float64
1515 1522    85.0
Name: new_cases, dtype: float64
1516 1523    99.0
Name: new_cases, dtype: float64
1517 1524    55.0
Name: new_cases, dtype: float64
1518 1525    102.0
Name: new_cases, dtype: float64
1519 1526    82.0
Name: new_cases, dtype: float64
1520 1527    81.0
Name: new_cases, dtype: float64
1521 1528    119.0
Name: new_cases, dtype: float64
1522 1529    68.0
Name: new_cases, dtype: float64
1523 1530    108.0
Name: new_cases, dtype: float64
1524 1531    104.0
Name: new_cases, dtype: float64
1525 1532    67.0
Name: new_cases, dtype: float64
1526 1533    126.0
Name: new_cases, dtype: float64
1527 1534    117.0
Name: new_cases, dtype: float64
1528 1535    117.0
Name: new_cases, dtype: float64
1529 1536    108.0
Name: new_cases, dtype: float64
1530 1537    92.0
Name: new_cases, dtype: float64
1531 1538    79.0
Name: new_cases, dtype: float64
1532 1539    120.0
Name: new_cases, dtype: float64
1533 1540    123.0
Name: new_cases, dtype: float64
1534 1541    101.0
Name: new_cases, dtype: float64
1535 1542    130.0
Name: new_cases, dtype: float64
1536 1543    139.0
Name: new_cases, dtype: float64
1537 1544    127.0
Name: new_cases, dtype: float64
1538 1545    135.0
Name: new_cases, dtype: float64
1539 1546    124.0
Name: new_cases, dtype: float64
1540 1547    136.0
Name: new_cases, dtype: float64
1541 1548    125.0
Name: new_cases, dtype: float64
1542 1549    140.0
Name: new_cases, dtype: float64
1543 1550    141.0
Name: new_cases, dtype: float64
1544 1551    154.0
Name: new_cases, dtype: float64
1545 1552    146.0
Name: new_cases, dtype: float64
1546 1553    143.0
Name: new_cases, dtype: float64
1547 1554    120.0
Name: new_cases, dtype: float64
1548 1555    119.0
Name: new_cases, dtype: float64
1549 1556    155.0
Name: new_cases, dtype: float64
1550 1557    158.0
Name: new_cases, dtype: float64
1551 1558    155.0
Name: new_cases, dtype: float64
1552 1559    152.0
Name: new_cases, dtype: float64
1553 1560    156.0
Name: new_cases, dtype: float64
1554 1561    152.0
Name: new_cases, dtype: float64
1555 1562    178.0
Name: new_cases, dtype: float64
1556 1563    154.0
Name: new_cases, dtype: float64
1557 1564    168.0
Name: new_cases, dtype: float64
1558 1565    156.0
Name: new_cases, dtype: float64
1559 1566    112.0
Name: new_cases, dtype: float64
1560 1567    84.0
Name: new_cases, dtype: float64
1561 1568    101.0
Name: new_cases, dtype: float64

1562 1569    133.0
Name: new_cases, dtype: float64
1563 1570    93.0
Name: new_cases, dtype: float64
1564 1571    122.0
Name: new_cases, dtype: float64
1565 1572    116.0
Name: new_cases, dtype: float64
1566 1573    123.0
Name: new_cases, dtype: float64
1567 1574    135.0
Name: new_cases, dtype: float64
1568 1575    153.0
Name: new_cases, dtype: float64
1569 1576    151.0
Name: new_cases, dtype: float64
1570 1577    147.0
Name: new_cases, dtype: float64
1571 1578    151.0
Name: new_cases, dtype: float64
1572 1579    156.0
Name: new_cases, dtype: float64
1573 1580    161.0
Name: new_cases, dtype: float64
1574 1581    164.0
Name: new_cases, dtype: float64
1575 1582    168.0
Name: new_cases, dtype: float64
1576 1583    167.0
Name: new_cases, dtype: float64
1577 1584    152.0
Name: new_cases, dtype: float64
1578 1585    144.0
Name: new_cases, dtype: float64
1579 1586    132.0
Name: new_cases, dtype: float64
1580 1587    125.0
Name: new_cases, dtype: float64
1581 1588    153.0
Name: new_cases, dtype: float64
1582 1589    159.0
Name: new_cases, dtype: float64
1583 1590    150.0
Name: new_cases, dtype: float64
1584 1591    131.0
Name: new_cases, dtype: float64
1585 1592    121.0
Name: new_cases, dtype: float64
1586 1593    134.0
Name: new_cases, dtype: float64
1587 1594    124.0
Name: new_cases, dtype: float64
1588 1595    108.0
Name: new_cases, dtype: float64
1589 1596    106.0
Name: new_cases, dtype: float64
1590 1597    132.0
Name: new_cases, dtype: float64
1591 1598    127.0
Name: new_cases, dtype: float64
1592 1599    131.0
Name: new_cases, dtype: float64
1593 1600    157.0
Name: new_cases, dtype: float64
1594 1601    159.0
Name: new_cases, dtype: float64
1595 1602    152.0
Name: new_cases, dtype: float64
1596 1603    149.0
Name: new_cases, dtype: float64
1597 1604    144.0
Name: new_cases, dtype: float64
1598 1605    158.0
Name: new_cases, dtype: float64
1599 1606    162.0
Name: new_cases, dtype: float64
1600 1607    169.0
Name: new_cases, dtype: float64
1601 1608    167.0
Name: new_cases, dtype: float64
1602 1609    165.0
Name: new_cases, dtype: float64
1603 1610    168.0
Name: new_cases, dtype: float64
1604 1611    171.0
Name: new_cases, dtype: float64
1605 1612    182.0
Name: new_cases, dtype: float64
1606 1613    203.0
Name: new_cases, dtype: float64
1607 1614    257.0
Name: new_cases, dtype: float64
1608 1615    289.0
Name: new_cases, dtype: float64
1609 1616    273.0
Name: new_cases, dtype: float64
1610 1617    281.0
Name: new_cases, dtype: float64
1611 1618    295.0
Name: new_cases, dtype: float64
1612 1619    301.0
Name: new_cases, dtype: float64
1613 1620    297.0
Name: new_cases, dtype: float64
1614 1621    302.0
Name: new_cases, dtype: float64
1615 1622    306.0
Name: new_cases, dtype: float64
1616 1623    302.0
Name: new_cases, dtype: float64
1617 1624    299.0
Name: new_cases, dtype: float64
1618 1625    288.0
Name: new_cases, dtype: float64
1619 1626    284.0
Name: new_cases, dtype: float64
1620 1627    311.0
Name: new_cases, dtype: float64
1621 1628    275.0
Name: new_cases, dtype: float64
1622 1629    319.0
Name: new_cases, dtype: float64
1623 1630    241.0
Name: new_cases, dtype: float64
1624 1631    327.0
Name: new_cases, dtype: float64
1625 1632    321.0
Name: new_cases, dtype: float64
1626 1633    381.0
Name: new_cases, dtype: float64
1627 1634    396.0
Name: new_cases, dtype: float64
1628 1635    421.0
Name: new_cases, dtype: float64
1629 1636    489.0
Name: new_cases, dtype: float64
1630 1637    495.0
Name: new_cases, dtype: float64
1631 1638    501.0
Name: new_cases, dtype: float64
1632 1639    525.0
Name: new_cases, dtype: float64
1633 1640    563.0
Name: new_cases, dtype: float64
1634 1641    507.0
Name: new_cases, dtype: float64
1635 1642    410.0
Name: new_cases, dtype: float64
1636 1643    490.0
Name: new_cases, dtype: float64
1637 1644    532.0
Name: new_cases, dtype: float64
1638 1645    597.0
Name: new_cases, dtype: float64
1639 1646    602.0
Name: new_cases, dtype: float64
1640 1647    694.0
Name: new_cases, dtype: float64
1641 1648    711.0
Name: new_cases, dtype: float64
1642 1649    786.0
Name: new_cases, dtype: float64
1643 1650    836.0
Name: new_cases, dtype: float64
1644 1651    737.0
Name: new_cases, dtype: float64
1645 1652    565.0
Name: new_cases, dtype: float64
1646 1653    795.0
Name: new_cases, dtype: float64
1647 1654    744.0
Name: new_cases, dtype: float64
1648 1655    644.0
Name: new_cases, dtype: float64
1649 1656    656.0
Name: new_cases, dtype: float64
1650 1657    645.0
Name: new_cases, dtype: float64
1651 1658    545.0
Name: new_cases, dtype: float64
1652 1659    835.0
Name: new_cases, dtype: float64
1653 1660    557.0
Name: new_cases, dtype: float64
1654 1661    832.0
Name: new_cases, dtype: float64
1655 1662    705.0
Name: new_cases, dtype: float64
1656 1663    782.0
Name: new_cases, dtype: float64
1657 1664    801.0
Name: new_cases, dtype: float64
1658 1665    846.0
Name: new_cases, dtype: float64
1659 1666    840.0
Name: new_cases, dtype: float64
1660 1667    695.0
Name: new_cases, dtype: float64
1661 1668    753.0
Name: new_cases, dtype: float64
1662 1669    752.0
Name: new_cases, dtype: float64
1663 1670    873.0
Name: new_cases, dtype: float64
1664 1671    802.0
Name: new_cases, dtype: float64
1665 1672    879.0
Name: new_cases, dtype: float64
1666 1673    788.0
Name: new_cases, dtype: float64
1667 1674    661.0
Name: new_cases, dtype: float64
1668 1675    809.0
Name: new_cases, dtype: float64
1669 1676    637.0
Name: new_cases, dtype: float64
1670 1677    787.0
Name: new_cases, dtype: float64
1671 1678    580.0
Name: new_cases, dtype: float64
1672 1679    538.0
Name: new_cases, dtype: float64
1673 1680    461.0
Name: new_cases, dtype: float64
1674 1681    422.0
Name: new_cases, dtype: float64
1675 1682    389.0
Name: new_cases, dtype: float64
1676 1683    503.0
Name: new_cases, dtype: float64
1677 1684    510.0
Name: new_cases, dtype: float64
1678 1685    553.0
Name: new_cases, dtype: float64
1679 1686    375.0
Name: new_cases, dtype: float64
1680 1687    499.0
Name: new_cases, dtype: float64
1681 1688    318.0
Name: new_cases, dtype: float64
1682 1689    574.0
Name: new_cases, dtype: float64
1683 1690    581.0
Name: new_cases, dtype: float64
1684 1691    589.0
Name: new_cases, dtype: float64
1685 1692    0.0
Name: new_cases, dtype: float64
1686 1693    675.0
Name: new_cases, dtype: float64
1687 1694    447.0
Name: new_cases, dtype: float64
1688 1695    185.0
Name: new_cases, dtype: float64
1689 1696    660.0
Name: new_cases, dtype: float64
1690 1697    725.0
Name: new_cases, dtype: float64
1691 1698    697.0
Name: new_cases, dtype: float64
1692 1699    673.0
Name: new_cases, dtype: float64
1693 1700    655.0
Name: new_cases, dtype: float64
1694 1701    562.0
Name: new_cases, dtype: float64
1695 1702    376.0
Name: new_cases, dtype: float64
1696 1703    656.0
Name: new_cases, dtype: float64
1697 1704    707.0
Name: new_cases, dtype: float64
1698 1705    660.0
Name: new_cases, dtype: float64
1699 1706    641.0
Name: new_cases, dtype: float64
1700 1707    581.0
Name: new_cases, dtype: float64
1701 1708    474.0
Name: new_cases, dtype: float64
1702 1709    292.0
Name: new_cases, dtype: float64
1703 1710    586.0
Name: new_cases, dtype: float64
1704 1711    670.0
Name: new_cases, dtype: float64
1705 1712    678.0
Name: new_cases, dtype: float64
1706 1713    739.0
Name: new_cases, dtype: float64
1707 1714    786.0
Name: new_cases, dtype: float64
1708 1715    833.0
Name: new_cases, dtype: float64
1709 1716    538.0
Name: new_cases, dtype: float64
1710 1717    879.0
Name: new_cases, dtype: float64
1711 1718    876.0
Name: new_cases, dtype: float64
1712 1719    887.0
Name: new_cases, dtype: float64
1713 1720    896.0
Name: new_cases, dtype: float64
1714 1721    901.0
Name: new_cases, dtype: float64
1715 1722    876.0
Name: new_cases, dtype: float64
1716 1723    865.0
Name: new_cases, dtype: float64
1717 1724    942.0
Name: new_cases, dtype: float64
1718 1725    1007.0
Name: new_cases, dtype: float64
1719 1726    1052.0
Name: new_cases, dtype: float64
1720 1727    1089.0
Name: new_cases, dtype: float64
1721 1728    1130.0
Name: new_cases, dtype: float64
1722 1729    1124.0
Name: new_cases, dtype: float64
1723 1730    953.0
Name: new_cases, dtype: float64
1724 1731    1239.0
Name: new_cases, dtype: float64
1725 1732    1143.0
Name: new_cases, dtype: float64
1726 1733    1105.0
Name: new_cases, dtype: float64

1727 1734    1059.0
Name: new_cases, dtype: float64
1728 1735    1152.0
Name: new_cases, dtype: float64
1729 1736    1088.0
Name: new_cases, dtype: float64
1730 1737    775.0
Name: new_cases, dtype: float64
1731 1738    801.0
Name: new_cases, dtype: float64
1732 1739    1075.0
Name: new_cases, dtype: float64
1733 1740    1112.0
Name: new_cases, dtype: float64
1734 1741    1071.0
Name: new_cases, dtype: float64
1735 1742    1153.0
Name: new_cases, dtype: float64
1736 1743    1184.0
Name: new_cases, dtype: float64
1737 1744    1039.0
Name: new_cases, dtype: float64
1738 1745    1021.0
Name: new_cases, dtype: float64
1739 1746    1021.0
Name: new_cases, dtype: float64
1740 1747    986.0
Name: new_cases, dtype: float64
1741 1748    916.0
Name: new_cases, dtype: float64
1742 1749    986.0
Name: new_cases, dtype: float64
1743 1750    952.0
Name: new_cases, dtype: float64
1744 1751    764.0
Name: new_cases, dtype: float64
1745 1752    892.0
Name: new_cases, dtype: float64
1746 1753    851.0
Name: new_cases, dtype: float64
1747 1754    847.0
Name: new_cases, dtype: float64
1748 1755    780.0
Name: new_cases, dtype: float64
1749 1756    777.0
Name: new_cases, dtype: float64
1750 1757    819.0
Name: new_cases, dtype: float64
1751 1758    683.0
Name: new_cases, dtype: float64
1752 1759    629.0
Name: new_cases, dtype: float64
1753 1760    631.0
Name: new_cases, dtype: float64
1754 1761    602.0
Name: new_cases, dtype: float64
1755 1762    681.0
Name: new_cases, dtype: float64
1756 1763    698.0
Name: new_cases, dtype: float64
1757 1764    653.0
Name: new_cases, dtype: float64
1758 1765    543.0
Name: new_cases, dtype: float64
1759 1766    475.0
Name: new_cases, dtype: float64
1760 1767    446.0
Name: new_cases, dtype: float64
1761 1768    590.0
Name: new_cases, dtype: float64
1762 1769    494.0
Name: new_cases, dtype: float64
1763 1770    519.0
Name: new_cases, dtype: float64
1764 1771    659.0
Name: new_cases, dtype: float64
1765 1772    344.0
Name: new_cases, dtype: float64
1766 1773    303.0
Name: new_cases, dtype: float64
1767 1774    448.0
Name: new_cases, dtype: float64
1768 1775    472.0
Name: new_cases, dtype: float64
1769 1776    449.0
Name: new_cases, dtype: float64
1770 1777    425.0
Name: new_cases, dtype: float64
1771 1778    493.0
Name: new_cases, dtype: float64
1772 1779    285.0
Name: new_cases, dtype: float64
1773 1780    304.0
Name: new_cases, dtype: float64
1774 1781    434.0
Name: new_cases, dtype: float64
1775 1782    349.0
Name: new_cases, dtype: float64
1776 1783    336.0
Name: new_cases, dtype: float64
1777 1784    341.0
Name: new_cases, dtype: float64
1778 1785    348.0
Name: new_cases, dtype: float64
1779 1786    264.0
Name: new_cases, dtype: float64
1780 1787    141.0
Name: new_cases, dtype: float64
1781 1788    256.0
Name: new_cases, dtype: float64
1782 1789    317.0
Name: new_cases, dtype: float64
1783 1790    286.0
Name: new_cases, dtype: float64
1784 1791    360.0
Name: new_cases, dtype: float64
1785 1792    238.0
Name: new_cases, dtype: float64
1786 1793    125.0
Name: new_cases, dtype: float64
1787 1794    234.0
Name: new_cases, dtype: float64
1788 1795    207.0
Name: new_cases, dtype: float64
1789 1796    169.0
Name: new_cases, dtype: float64
1790 1797    179.0
Name: new_cases, dtype: float64
1791 1798    149.0
Name: new_cases, dtype: float64
1792 1799    138.0
Name: new_cases, dtype: float64
1793 1800    100.0
Name: new_cases, dtype: float64
1794 1801    148.0
Name: new_cases, dtype: float64
1795 1802    138.0
Name: new_cases, dtype: float64
1796 1803    134.0
Name: new_cases, dtype: float64
1797 1804    156.0
Name: new_cases, dtype: float64
1798 1805    139.0
Name: new_cases, dtype: float64
1799 1806    128.0
Name: new_cases, dtype: float64
1800 1807    69.0
Name: new_cases, dtype: float64
1801 1808    130.0
Name: new_cases, dtype: float64
1802 1809    123.0
Name: new_cases, dtype: float64
1803 1810    118.0
Name: new_cases, dtype: float64
1804 1811    108.0
Name: new_cases, dtype: float64
1805 1812    100.0
Name: new_cases, dtype: float64
1806 1813    53.0
Name: new_cases, dtype: float64
1807 1814    38.0
Name: new_cases, dtype: float64
1808 1815    51.0
Name: new_cases, dtype: float64
1809 1816    92.0
Name: new_cases, dtype: float64
1810 1817    91.0
Name: new_cases, dtype: float64
1811 1818    67.0
Name: new_cases, dtype: float64
1812 1819    89.0
Name: new_cases, dtype: float64
1813 1820    57.0
Name: new_cases, dtype: float64
1814 1821    30.0
Name: new_cases, dtype: float64
1815 1822    50.0
Name: new_cases, dtype: float64
1816 1823    42.0
Name: new_cases, dtype: float64
1817 1824    45.0
Name: new_cases, dtype: float64
1818 1825    49.0
Name: new_cases, dtype: float64
1819 1826    39.0
Name: new_cases, dtype: float64
1820 1827    37.0
Name: new_cases, dtype: float64
1821 1828    17.0
Name: new_cases, dtype: float64
1822 1829    39.0
Name: new_cases, dtype: float64
1823 1830    24.0
Name: new_cases, dtype: float64
1824 1831    23.0
Name: new_cases, dtype: float64
1825 1832    35.0
Name: new_cases, dtype: float64
1826 1833    23.0
Name: new_cases, dtype: float64
1827 1834    33.0
Name: new_cases, dtype: float64
1828 1835    6.0
Name: new_cases, dtype: float64
1829 1836    14.0
Name: new_cases, dtype: float64
1830 1837    15.0
Name: new_cases, dtype: float64
1831 1838    20.0
Name: new_cases, dtype: float64
1832 1839    21.0
Name: new_cases, dtype: float64
1833 1840    12.0
Name: new_cases, dtype: float64
1834 1841    12.0
Name: new_cases, dtype: float64
1835 1842    6.0
Name: new_cases, dtype: float64
1836 1843    22.0
Name: new_cases, dtype: float64
1837 1844    14.0
Name: new_cases, dtype: float64
1838 1845    9.0
Name: new_cases, dtype: float64
1839 1846    12.0
Name: new_cases, dtype: float64
1840 1847    2.0
Name: new_cases, dtype: float64
1841 1848    5.0
Name: new_cases, dtype: float64
1842 1849    5.0
Name: new_cases, dtype: float64
1843 1850    13.0
Name: new_cases, dtype: float64
1844 1851    18.0
Name: new_cases, dtype: float64
1845 1852    11.0
Name: new_cases, dtype: float64
1846 1853    11.0
Name: new_cases, dtype: float64
1847 1854    12.0
Name: new_cases, dtype: float64
1848 1855    10.0
Name: new_cases, dtype: float64
1849 1856    2.0
Name: new_cases, dtype: float64
1850 1857    8.0
Name: new_cases, dtype: float64
1851 1858    7.0
Name: new_cases, dtype: float64
1852 1859    5.0
Name: new_cases, dtype: float64
1853 1860    3.0
Name: new_cases, dtype: float64
1854 1861    4.0
Name: new_cases, dtype: float64
1855 1862    2.0
Name: new_cases, dtype: float64
1856 1863    0.0
Name: new_cases, dtype: float64
1857 1864    6.0
Name: new_cases, dtype: float64
1858 1865    1.0
Name: new_cases, dtype: float64
1859 1866    2.0
Name: new_cases, dtype: float64
1860 1867    7.0
Name: new_cases, dtype: float64
1861 1868    3.0
Name: new_cases, dtype: float64
1862 1869    3.0
Name: new_cases, dtype: float64
1863 1870    1.0
Name: new_cases, dtype: float64
1864 1871    1.0
Name: new_cases, dtype: float64
1865 1872    7.0
Name: new_cases, dtype: float64
1866 1873    2.0
Name: new_cases, dtype: float64
1867 1874    3.0
Name: new_cases, dtype: float64
1868 1875    8.0
Name: new_cases, dtype: float64
1869 1876    1.0
Name: new_cases, dtype: float64
1870 1877    2.0
Name: new_cases, dtype: float64
1871 1878    7.0
Name: new_cases, dtype: float64
1872 1879    13.0
Name: new_cases, dtype: float64
1873 1880    8.0
Name: new_cases, dtype: float64
1874 1881    15.0
Name: new_cases, dtype: float64
1875 1882    7.0
Name: new_cases, dtype: float64
1876 1883    5.0
Name: new_cases, dtype: float64
1877 1884    5.0
Name: new_cases, dtype: float64
1878 1885    11.0
Name: new_cases, dtype: float64
1879 1886    8.0
Name: new_cases, dtype: float64
1880 1887    13.0
Name: new_cases, dtype: float64
1881 1888    18.0
Name: new_cases, dtype: float64
1882 1889    18.0
Name: new_cases, dtype: float64
1883 1890    21.0
Name: new_cases, dtype: float64
1884 1891    11.0
Name: new_cases, dtype: float64
1885 1892    43.0
Name: new_cases, dtype: float64
1886 1893    23.0
Name: new_cases, dtype: float64
1887 1894    34.0
Name: new_cases, dtype: float64
1888 1895    31.0
Name: new_cases, dtype: float64
1889 1896    25.0
Name: new_cases, dtype: float64
1890 1897    22.0
Name: new_cases, dtype: float64
1891 1898    16.0
Name: new_cases, dtype: float64
1892 1899    31.0
Name: new_cases, dtype: float64
1893 1900    30.0
Name: new_cases, dtype: float64

1894 1901    47.0
Name: new_cases, dtype: float64
1895 1902    37.0
Name: new_cases, dtype: float64
1896 1903    45.0
Name: new_cases, dtype: float64
1897 1904    40.0
Name: new_cases, dtype: float64
1898 1905    25.0
Name: new_cases, dtype: float64
1899 1906    65.0
Name: new_cases, dtype: float64
1900 1907    99.0
Name: new_cases, dtype: float64
1901 1908    132.0
Name: new_cases, dtype: float64
1902 1909    149.0
Name: new_cases, dtype: float64
1903 1910    139.0
Name: new_cases, dtype: float64
1904 1911    182.0
Name: new_cases, dtype: float64
1905 1912    69.0
Name: new_cases, dtype: float64
1906 1913    220.0
Name: new_cases, dtype: float64
1907 1914    286.0
Name: new_cases, dtype: float64
1908 1915    274.0
Name: new_cases, dtype: float64
1909 1916    379.0
Name: new_cases, dtype: float64
1910 1917    410.0
Name: new_cases, dtype: float64
1911 1918    397.0
Name: new_cases, dtype: float64
1912 1919    200.0
Name: new_cases, dtype: float64
1913 1920    451.0
Name: new_cases, dtype: float64
1914 1921    477.0
Name: new_cases, dtype: float64
1915 1922    522.0
Name: new_cases, dtype: float64
1916 1923    535.0
Name: new_cases, dtype: float64
1917 1924    658.0
Name: new_cases, dtype: float64
1918 1925    534.0
Name: new_cases, dtype: float64
1919 1926    397.0
Name: new_cases, dtype: float64
1920 1927    800.0
Name: new_cases, dtype: float64
1921 1928    844.0
Name: new_cases, dtype: float64
1922 1929    888.0
Name: new_cases, dtype: float64
1923 1930    921.0
Name: new_cases, dtype: float64
1924 1931    905.0
Name: new_cases, dtype: float64
1925 1932    768.0
Name: new_cases, dtype: float64
1926 1933    486.0
Name: new_cases, dtype: float64
1927 1934    1054.0
Name: new_cases, dtype: float64
1928 1935    982.0
Name: new_cases, dtype: float64
1929 1936    853.0
Name: new_cases, dtype: float64
1930 1937    895.0
Name: new_cases, dtype: float64
1931 1938    984.0
Name: new_cases, dtype: float64
1932 1939    896.0
Name: new_cases, dtype: float64
1933 1940    502.0
Name: new_cases, dtype: float64
1934 1941    740.0
Name: new_cases, dtype: float64
1935 1942    1079.0
Name: new_cases, dtype: float64
1936 1943    998.0
Name: new_cases, dtype: float64
1937 1944    977.0
Name: new_cases, dtype: float64
1938 1945    869.0
Name: new_cases, dtype: float64
1939 1946    864.0
Name: new_cases, dtype: float64
1940 1947    410.0
Name: new_cases, dtype: float64
1941 1948    995.0
Name: new_cases, dtype: float64
1942 1949    992.0
Name: new_cases, dtype: float64
1943 1950    942.0
Name: new_cases, dtype: float64
1944 1951    959.0
Name: new_cases, dtype: float64
1945 1952    849.0
Name: new_cases, dtype: float64
1946 1953    780.0
Name: new_cases, dtype: float64
1947 1954    451.0
Name: new_cases, dtype: float64
1948 1955    872.0
Name: new_cases, dtype: float64
1949 1956    820.0
Name: new_cases, dtype: float64
1950 1957    768.0
Name: new_cases, dtype: float64
1951 1958    826.0
Name: new_cases, dtype: float64
1952 1959    664.0
Name: new_cases, dtype: float64
1953 1960    539.0
Name: new_cases, dtype: float64
1954 1961    295.0
Name: new_cases, dtype: float64
1955 1962    594.0
Name: new_cases, dtype: float64
1956 1963    680.0
Name: new_cases, dtype: float64
1957 1964    669.0
Name: new_cases, dtype: float64
1958 1965    647.0
Name: new_cases, dtype: float64
1959 1966    549.0
Name: new_cases, dtype: float64
1960 1967    467.0
Name: new_cases, dtype: float64
1961 1968    0.0
Name: new_cases, dtype: float64
1962 1969    824.0
Name: new_cases, dtype: float64
1963 1970    572.0
Name: new_cases, dtype: float64
1964 1971    533.0
Name: new_cases, dtype: float64
1965 1972    445.0
Name: new_cases, dtype: float64
1966 1973    475.0
Name: new_cases, dtype: float64
1967 1974    325.0
Name: new_cases, dtype: float64
1968 1975    195.0
Name: new_cases, dtype: float64
1969 1976    501.0
Name: new_cases, dtype: float64
1970 1977    508.0
Name: new_cases, dtype: float64
1971 1978    495.0
Name: new_cases, dtype: float64
1972 1979    441.0
Name: new_cases, dtype: float64
1973 1980    428.0
Name: new_cases, dtype: float64
1974 1981    435.0
Name: new_cases, dtype: float64
1975 1982    217.0
Name: new_cases, dtype: float64
1976 1983    616.0
Name: new_cases, dtype: float64
1977 1984    659.0
Name: new_cases, dtype: float64
1978 1985    566.0
Name: new_cases, dtype: float64
1979 1986    594.0
Name: new_cases, dtype: float64
1980 1987    629.0
Name: new_cases, dtype: float64
1981 1988    444.0
Name: new_cases, dtype: float64
1982 1989    264.0
Name: new_cases, dtype: float64
1983 1990    650.0
Name: new_cases, dtype: float64
1984 1991    672.0
Name: new_cases, dtype: float64
1985 1992    591.0
Name: new_cases, dtype: float64
1986 1993    467.0
Name: new_cases, dtype: float64
1987 1994    547.0
Name: new_cases, dtype: float64
1988 1995    413.0
Name: new_cases, dtype: float64
1989 1996    197.0
Name: new_cases, dtype: float64
1990 1997    725.0
Name: new_cases, dtype: float64
1991 1998    571.0
Name: new_cases, dtype: float64
1992 1999    570.0
Name: new_cases, dtype: float64
1993 2000    631.0
Name: new_cases, dtype: float64
1994 2001    0.0
Name: new_cases, dtype: float64
1995 2002    1131.0
Name: new_cases, dtype: float64
1996 2003    230.0
Name: new_cases, dtype: float64
1997 2004    770.0
Name: new_cases, dtype: float64
1998 2005    690.0
Name: new_cases, dtype: float64
1999 2006    625.0
Name: new_cases, dtype: float64
2000 2007    573.0
Name: new_cases, dtype: float64
2001 2008    587.0
Name: new_cases, dtype: float64
2002 2009    475.0
Name: new_cases, dtype: float64
2003 2010    194.0
Name: new_cases, dtype: float64
2004 2011    587.0
Name: new_cases, dtype: float64
2005 2012    616.0
Name: new_cases, dtype: float64
2006 2013    549.0
Name: new_cases, dtype: float64
2007 2014    502.0
Name: new_cases, dtype: float64
2008 2015    465.0
Name: new_cases, dtype: float64
2009 2016    0.0
Name: new_cases, dtype: float64
2010 2017    623.0
Name: new_cases, dtype: float64
2011 2018    556.0
Name: new_cases, dtype: float64
2012 2019    609.0
Name: new_cases, dtype: float64
2013 2020    516.0
Name: new_cases, dtype: float64
2014 2021    440.0
Name: new_cases, dtype: float64
2015 2022    405.0
Name: new_cases, dtype: float64
2016 2023    418.0
Name: new_cases, dtype: float64
2017 2024    195.0
Name: new_cases, dtype: float64
2018 2025    195.0
Name: new_cases, dtype: float64
2019 2026    228.0
Name: new_cases, dtype: float64
2020 2027    466.0
Name: new_cases, dtype: float64
2021 2028    406.0
Name: new_cases, dtype: float64
2022 2029    357.0
Name: new_cases, dtype: float64
2023 2030    328.0
Name: new_cases, dtype: float64
2024 2031    172.0
Name: new_cases, dtype: float64
2025 2032    393.0
Name: new_cases, dtype: float64
2026 2033    346.0
Name: new_cases, dtype: float64
2027 2034    222.0
Name: new_cases, dtype: float64
2028 2035    352.0
Name: new_cases, dtype: float64
2029 2036    309.0
Name: new_cases, dtype: float64
2030 2037    263.0
Name: new_cases, dtype: float64
2031 2038    138.0
Name: new_cases, dtype: float64
2032 2039    376.0
Name: new_cases, dtype: float64
2033 2040    326.0
Name: new_cases, dtype: float64
2034 2041    301.0
Name: new_cases, dtype: float64
2035 2042    296.0
Name: new_cases, dtype: float64
2036 2043    325.0
Name: new_cases, dtype: float64
2037 2044    228.0
Name: new_cases, dtype: float64
2038 2045    120.0
Name: new_cases, dtype: float64
2039 2046    376.0
Name: new_cases, dtype: float64
2040 2047    343.0
Name: new_cases, dtype: float64
2041 2048    319.0
Name: new_cases, dtype: float64
2042 2049    286.0
Name: new_cases, dtype: float64
2043 2050    321.0
Name: new_cases, dtype: float64
2044 2051    167.0
Name: new_cases, dtype: float64
2045 2052    0.0
Name: new_cases, dtype: float64
2046 2053    643.0
Name: new_cases, dtype: float64
2047 2054    547.0
Name: new_cases, dtype: float64
2048 2055    0.0
Name: new_cases, dtype: float64
2049 2056    1325.0
Name: new_cases, dtype: float64
2050 2057    0.0
Name: new_cases, dtype: float64
2051 2058    661.0
Name: new_cases, dtype: float64
2052 2059    0.0
Name: new_cases, dtype: float64
2053 2060    1136.0
Name: new_cases, dtype: float64
2054 2061    0.0
Name: new_cases, dtype: float64
2055 2062    1236.0
Name: new_cases, dtype: float64
2056 2063    1648.0
Name: new_cases, dtype: float64
2057 Series([], Name: new_cases, dtype: float64)
2058 Series([], Name: new_cases, dtype: float64)
2059 Series([], Name: new_cases, dtype: float64)
2060 Series([], Name: new_cases, dtype: float64)
2061 Series([], Name: new_cases, dtype: float64)
2062 Series([], Name: new_cases, dtype: float64)
2063 1394    2.0
Name: new_cases, dtype: float64
5468 5475    5.0
Name: new_cases, dtype: float64
5469 5476    2.0
Name: new_cases, dtype: float64
5470 5477    0.0
Name: new_cases, dtype: float64
5471 5478    12.0
Name: new_cases, dtype: float64

5472 5479    3.0
Name: new_cases, dtype: float64
5473 5480    11.0
Name: new_cases, dtype: float64
5474 5481    11.0
Name: new_cases, dtype: float64
5475 5482    12.0
Name: new_cases, dtype: float64
5476 5483    11.0
Name: new_cases, dtype: float64
5477 5484    18.0
Name: new_cases, dtype: float64
5478 5485    31.0
Name: new_cases, dtype: float64
5479 5486    30.0
Name: new_cases, dtype: float64
5480 5487    108.0
Name: new_cases, dtype: float64
5481 5488    35.0
Name: new_cases, dtype: float64
5482 5489    86.0
Name: new_cases, dtype: float64
5483 5490    0.0
Name: new_cases, dtype: float64
5484 5491    115.0
Name: new_cases, dtype: float64
5485 5492    87.0
Name: new_cases, dtype: float64
5486 5493    101.0
Name: new_cases, dtype: float64
5487 5494    55.0
Name: new_cases, dtype: float64
5488 5495    75.0
Name: new_cases, dtype: float64
5489 5496    234.0
Name: new_cases, dtype: float64
5490 5497    0.0
Name: new_cases, dtype: float64
5491 5498    79.0
Name: new_cases, dtype: float64
5492 5499    132.0
Name: new_cases, dtype: float64
5493 5500    186.0
Name: new_cases, dtype: float64
5494 5501    0.0
Name: new_cases, dtype: float64
5495 5502    103.0
Name: new_cases, dtype: float64
5496 5503    74.0
Name: new_cases, dtype: float64
5497 5504    87.0
Name: new_cases, dtype: float64
5498 5505    80.0
Name: new_cases, dtype: float64
5499 5506    180.0
Name: new_cases, dtype: float64
5500 5507    0.0
Name: new_cases, dtype: float64
5501 5508    167.0
Name: new_cases, dtype: float64
5502 5509    66.0
Name: new_cases, dtype: float64
5503 5510    69.0
Name: new_cases, dtype: float64
5504 5511    166.0
Name: new_cases, dtype: float64
5505 5512    128.0
Name: new_cases, dtype: float64
5506 5513    98.0
Name: new_cases, dtype: float64
5507 5514    89.0
Name: new_cases, dtype: float64
5508 5515    81.0
Name: new_cases, dtype: float64
5509 5516    102.0
Name: new_cases, dtype: float64
5510 5517    90.0
Name: new_cases, dtype: float64
5511 5518    113.0
Name: new_cases, dtype: float64
5512 5519    291.0
Name: new_cases, dtype: float64
5513 5520    172.0
Name: new_cases, dtype: float64
5514 5521    173.0
Name: new_cases, dtype: float64
5515 5522    112.0
Name: new_cases, dtype: float64
5516 5523    111.0
Name: new_cases, dtype: float64
5517 5524    124.0
Name: new_cases, dtype: float64
5518 5525    158.0
Name: new_cases, dtype: float64
5519 5526    143.0
Name: new_cases, dtype: float64
5520 5527    104.0
Name: new_cases, dtype: float64
5521 5528    149.0
Name: new_cases, dtype: float64
5522 5529    102.0
Name: new_cases, dtype: float64
5523 5530    104.0
Name: new_cases, dtype: float64
5524 5531    133.0
Name: new_cases, dtype: float64
5525 5532    188.0
Name: new_cases, dtype: float64
5526 5533    163.0
Name: new_cases, dtype: float64
5527 5534    240.0
Name: new_cases, dtype: float64
5528 5535    165.0
Name: new_cases, dtype: float64
5529 5536    258.0
Name: new_cases, dtype: float64
5530 5537    244.0
Name: new_cases, dtype: float64
5531 5538    285.0
Name: new_cases, dtype: float64
5532 5539    316.0
Name: new_cases, dtype: float64
5533 5540    255.0
Name: new_cases, dtype: float64
5534 5541    345.0
Name: new_cases, dtype: float64
5535 5542    326.0
Name: new_cases, dtype: float64
5536 5543    263.0
Name: new_cases, dtype: float64
5537 5544    303.0
Name: new_cases, dtype: float64
5538 5545    438.0
Name: new_cases, dtype: float64
5539 5546    474.0
Name: new_cases, dtype: float64
5540 5547    648.0
Name: new_cases, dtype: float64
5541 5548    718.0
Name: new_cases, dtype: float64
5542 5549    704.0
Name: new_cases, dtype: float64
5543 5550    723.0
Name: new_cases, dtype: float64
5544 5551    552.0
Name: new_cases, dtype: float64
5545 5552    600.0
Name: new_cases, dtype: float64
5546 5553    705.0
Name: new_cases, dtype: float64
5547 5554    769.0
Name: new_cases, dtype: float64
5548 5555    717.0
Name: new_cases, dtype: float64
5549 5556    795.0
Name: new_cases, dtype: float64
5550 5557    637.0
Name: new_cases, dtype: float64
5551 5558    564.0
Name: new_cases, dtype: float64
5552 5559    904.0
Name: new_cases, dtype: float64
5553 5560    949.0
Name: new_cases, dtype: float64
5554 5561    929.0
Name: new_cases, dtype: float64
5555 5562    840.0
Name: new_cases, dtype: float64
5556 5563    983.0
Name: new_cases, dtype: float64
5557 5564    774.0
Name: new_cases, dtype: float64
5558 5565    826.0
Name: new_cases, dtype: float64
5559 5566    1141.0
Name: new_cases, dtype: float64
5560 5567    1226.0
Name: new_cases, dtype: float64
5561 5568    1386.0
Name: new_cases, dtype: float64
5562 5569    1391.0
Name: new_cases, dtype: float64
5563 5570    1531.0
Name: new_cases, dtype: float64
5564 5571    1282.0
Name: new_cases, dtype: float64
5565 5572    1208.0
Name: new_cases, dtype: float64
5566 5573    1374.0
Name: new_cases, dtype: float64
5567 5574    1393.0
Name: new_cases, dtype: float64
5568 5575    1958.0
Name: new_cases, dtype: float64
5569 5576    2060.0
Name: new_cases, dtype: float64
5570 5577    1634.0
Name: new_cases, dtype: float64
5571 5578    1581.0
Name: new_cases, dtype: float64
5572 5579    2146.0
Name: new_cases, dtype: float64
5573 5580    2272.0
Name: new_cases, dtype: float64
5574 5581    2648.0
Name: new_cases, dtype: float64
5575 5582    2606.0
Name: new_cases, dtype: float64
5576 5583    2886.0
Name: new_cases, dtype: float64
5577 5584    2401.0
Name: new_cases, dtype: float64
5578 5585    2189.0
Name: new_cases, dtype: float64
5579 5586    2335.0
Name: new_cases, dtype: float64
5580 5587    2262.0
Name: new_cases, dtype: float64
5581 5588    2667.0
Name: new_cases, dtype: float64
5582 5589    2744.0
Name: new_cases, dtype: float64
5583 5590    2845.0
Name: new_cases, dtype: float64
5584 5591    2590.0
Name: new_cases, dtype: float64
5585 5592    2439.0
Name: new_cases, dtype: float64
5586 5593    2632.0
Name: new_cases, dtype: float64
5587 5594    2979.0
Name: new_cases, dtype: float64
5588 5595    3604.0
Name: new_cases, dtype: float64
5589 5596    3663.0
Name: new_cases, dtype: float64
5590 5597    3367.0
Name: new_cases, dtype: float64
5591 5598    3449.0
Name: new_cases, dtype: float64
5592 5599    2657.0
Name: new_cases, dtype: float64
5593 5600    3099.0
Name: new_cases, dtype: float64
5594 5601    3645.0
Name: new_cases, dtype: float64
5595 5602    4236.0
Name: new_cases, dtype: float64
5596 5603    3637.0
Name: new_cases, dtype: float64
5597 5604    4518.0
Name: new_cases, dtype: float64
5598 5605    3223.0
Name: new_cases, dtype: float64
5599 5606    4231.0
Name: new_cases, dtype: float64
5600 5607    4019.0
Name: new_cases, dtype: float64
5601 5608    5344.0
Name: new_cases, dtype: float64
5602 5609    5782.0
Name: new_cases, dtype: float64
5603 5610    6127.0
Name: new_cases, dtype: float64
5604 5611    5493.0
Name: new_cases, dtype: float64
5605 5612    4814.0
Name: new_cases, dtype: float64
5606 5613    4192.0
Name: new_cases, dtype: float64
5607 5614    4890.0
Name: new_cases, dtype: float64
5608 5615    5939.0
Name: new_cases, dtype: float64
5609 5616    5641.0
Name: new_cases, dtype: float64
5610 5617    6377.0
Name: new_cases, dtype: float64
5611 5618    5929.0
Name: new_cases, dtype: float64
5612 5619    5241.0
Name: new_cases, dtype: float64
5613 5620    5376.0
Name: new_cases, dtype: float64
5614 5621    4824.0
Name: new_cases, dtype: float64
5615 5622    6792.0
Name: new_cases, dtype: float64
5616 5623    7147.0
Name: new_cases, dtype: float64
5617 5624    7513.0
Name: new_cases, dtype: float64
5618 5625    7482.0
Name: new_cases, dtype: float64
5619 5626    6134.0
Name: new_cases, dtype: float64
5620 5627    4688.0
Name: new_cases, dtype: float64
5621 5628    7369.0
Name: new_cases, dtype: float64
5622 5629    7043.0
Name: new_cases, dtype: float64
5623 5630    7663.0
Name: new_cases, dtype: float64
5624 5631    7498.0
Name: new_cases, dtype: float64
5625 5632    6365.0
Name: new_cases, dtype: float64
5626 5633    6663.0
Name: new_cases, dtype: float64
5627 5634    5469.0
Name: new_cases, dtype: float64
5628 5635    4557.0
Name: new_cases, dtype: float64
5629 5636    6840.0
Name: new_cases, dtype: float64
5630 5637    6693.0
Name: new_cases, dtype: float64
5631 5638    8225.0
Name: new_cases, dtype: float64
5632 5639    8159.0
Name: new_cases, dtype: float64
5633 5640    7759.0
Name: new_cases, dtype: float64
5634 5641    5352.0
Name: new_cases, dtype: float64
5635 5642    8713.0
Name: new_cases, dtype: float64

5636 5643    8771.0
Name: new_cases, dtype: float64
5637 5644    10550.0
Name: new_cases, dtype: float64
5638 5645    10104.0
Name: new_cases, dtype: float64
5639 5646    11717.0
Name: new_cases, dtype: float64
5640 5647    9230.0
Name: new_cases, dtype: float64
5641 5648    7187.0
Name: new_cases, dtype: float64
5642 5649    9309.0
Name: new_cases, dtype: float64
5643 5650    10504.0
Name: new_cases, dtype: float64
5644 5651    10933.0
Name: new_cases, dtype: float64
5645 5652    12026.0
Name: new_cases, dtype: float64
5646 5653    10684.0
Name: new_cases, dtype: float64
5647 5654    9924.0
Name: new_cases, dtype: float64
5648 5655    6986.0
Name: new_cases, dtype: float64
5649 5656    9215.0
Name: new_cases, dtype: float64
5650 5657    12027.0
Name: new_cases, dtype: float64
5651 5658    12259.0
Name: new_cases, dtype: float64
5652 5659    11905.0
Name: new_cases, dtype: float64
5653 5660    11507.0
Name: new_cases, dtype: float64
5654 5661    10776.0
Name: new_cases, dtype: float64
5655 5662    9056.0
Name: new_cases, dtype: float64
5656 5663    9909.0
Name: new_cases, dtype: float64
5657 5664    11892.0
Name: new_cases, dtype: float64
5658 5665    11674.0
Name: new_cases, dtype: float64
5659 5666    12701.0
Name: new_cases, dtype: float64
5660 5667    11945.0
Name: new_cases, dtype: float64
5661 5668    9276.0
Name: new_cases, dtype: float64
5662 5669    8431.0
Name: new_cases, dtype: float64
5663 5670    8782.0
Name: new_cases, dtype: float64
5664 5671    12027.0
Name: new_cases, dtype: float64
5665 5672    12625.0
Name: new_cases, dtype: float64
5666 5673    13467.0
Name: new_cases, dtype: float64
5667 5674    12969.0
Name: new_cases, dtype: float64
5668 5675    11249.0
Name: new_cases, dtype: float64
5669 5676    8841.0
Name: new_cases, dtype: float64
5670 5677    11807.0
Name: new_cases, dtype: float64
5671 5678    13477.0
Name: new_cases, dtype: float64
5672 5679    14392.0
Name: new_cases, dtype: float64
5673 5680    14001.0
Name: new_cases, dtype: float64
5674 5681    14687.0
Name: new_cases, dtype: float64
5675 5682    11129.0
Name: new_cases, dtype: float64
5676 5683    7668.0
Name: new_cases, dtype: float64
5677 5684    11242.0
Name: new_cases, dtype: float64
5678 5685    14740.0
Name: new_cases, dtype: float64
5679 5686    16447.0
Name: new_cases, dtype: float64
5680 5687    15454.0
Name: new_cases, dtype: float64
5681 5688    15099.0
Name: new_cases, dtype: float64
5682 5689    12414.0
Name: new_cases, dtype: float64
5683 5690    10324.0
Name: new_cases, dtype: float64
5684 5691    9524.0
Name: new_cases, dtype: float64
5685 5692    13305.0
Name: new_cases, dtype: float64
5686 5693    14932.0
Name: new_cases, dtype: float64
5687 5694    17096.0
Name: new_cases, dtype: float64
5688 5695    16546.0
Name: new_cases, dtype: float64
5689 5696    13510.0
Name: new_cases, dtype: float64
5690 5697    10561.0
Name: new_cases, dtype: float64
5691 5698    12982.0
Name: new_cases, dtype: float64
5692 5699    16337.0
Name: new_cases, dtype: float64
5693 5700    18326.0
Name: new_cases, dtype: float64
5694 5701    16325.0
Name: new_cases, dtype: float64
5695 5702    15718.0
Name: new_cases, dtype: float64
5696 5703    11968.0
Name: new_cases, dtype: float64
5697 5704    9253.0
Name: new_cases, dtype: float64
5698 5705    11712.0
Name: new_cases, dtype: float64
5699 5706    14308.0
Name: new_cases, dtype: float64
5700 5707    13924.0
Name: new_cases, dtype: float64
5701 5708    13267.0
Name: new_cases, dtype: float64
5702 5709    13379.0
Name: new_cases, dtype: float64
5703 5710    9745.0
Name: new_cases, dtype: float64
5704 5711    6609.0
Name: new_cases, dtype: float64
5705 5712    9598.0
Name: new_cases, dtype: float64
5706 5713    12145.0
Name: new_cases, dtype: float64
5707 5714    10652.0
Name: new_cases, dtype: float64
5708 5715    11100.0
Name: new_cases, dtype: float64
5709 5716    11786.0
Name: new_cases, dtype: float64
5710 5717    8037.0
Name: new_cases, dtype: float64
5711 5718    5331.0
Name: new_cases, dtype: float64
5712 5719    8317.0
Name: new_cases, dtype: float64
5713 5720    11977.0
Name: new_cases, dtype: float64
5714 5721    10880.0
Name: new_cases, dtype: float64
5715 5722    11163.0
Name: new_cases, dtype: float64
5716 5723    11859.0
Name: new_cases, dtype: float64
5717 5724    8468.0
Name: new_cases, dtype: float64
5718 5725    5645.0
Name: new_cases, dtype: float64
5719 5726    7893.0
Name: new_cases, dtype: float64
5720 5727    10621.0
Name: new_cases, dtype: float64
5721 5728    10332.0
Name: new_cases, dtype: float64
5722 5729    10097.0
Name: new_cases, dtype: float64
5723 5730    9608.0
Name: new_cases, dtype: float64
5724 5731    7140.0
Name: new_cases, dtype: float64
5725 5732    4184.0
Name: new_cases, dtype: float64
5726 5733    4265.0
Name: new_cases, dtype: float64
5727 5734    7164.0
Name: new_cases, dtype: float64
5728 5735    8593.0
Name: new_cases, dtype: float64
5729 5736    9043.0
Name: new_cases, dtype: float64
5730 5737    7846.0
Name: new_cases, dtype: float64
5731 5738    6098.0
Name: new_cases, dtype: float64
5732 5739    5432.0
Name: new_cases, dtype: float64
5733 5740    5726.0
Name: new_cases, dtype: float64
5734 5741    8037.0
Name: new_cases, dtype: float64
5735 5742    7533.0
Name: new_cases, dtype: float64
5736 5743    7629.0
Name: new_cases, dtype: float64
5737 5744    6899.0
Name: new_cases, dtype: float64
5738 5745    5201.0
Name: new_cases, dtype: float64
5739 5746    3278.0
Name: new_cases, dtype: float64
5740 5747    3199.0
Name: new_cases, dtype: float64
5741 5748    3610.0
Name: new_cases, dtype: float64
5742 5749    5303.0
Name: new_cases, dtype: float64
5743 5750    6994.0
Name: new_cases, dtype: float64
5744 5751    7112.0
Name: new_cases, dtype: float64
5745 5752    5274.0
Name: new_cases, dtype: float64
5746 5753    3558.0
Name: new_cases, dtype: float64
5747 5754    5062.0
Name: new_cases, dtype: float64
5748 5755    6981.0
Name: new_cases, dtype: float64
5749 5756    6843.0
Name: new_cases, dtype: float64
5750 5757    7326.0
Name: new_cases, dtype: float64
5751 5758    7002.0
Name: new_cases, dtype: float64
5752 5759    5795.0
Name: new_cases, dtype: float64
5753 5760    4116.0
Name: new_cases, dtype: float64
5754 5761    5853.0
Name: new_cases, dtype: float64
5755 5762    8141.0
Name: new_cases, dtype: float64
5756 5763    8586.0
Name: new_cases, dtype: float64
5757 5764    0.0
Name: new_cases, dtype: float64
5758 5765    10689.0
Name: new_cases, dtype: float64
5759 5766    3713.0
Name: new_cases, dtype: float64
5760 5767    5030.0
Name: new_cases, dtype: float64
5761 5768    7216.0
Name: new_cases, dtype: float64
5762 5769    11650.0
Name: new_cases, dtype: float64
5763 5770    11765.0
Name: new_cases, dtype: float64
5764 5771    11586.0
Name: new_cases, dtype: float64
5765 5772    4080.0
Name: new_cases, dtype: float64
5766 5773    5240.0
Name: new_cases, dtype: float64
5767 5774    5884.0
Name: new_cases, dtype: float64
5768 5775    8222.0
Name: new_cases, dtype: float64
5769 5776    13790.0
Name: new_cases, dtype: float64
5770 5777    13441.0
Name: new_cases, dtype: float64
5771 5778    13835.0
Name: new_cases, dtype: float64
5772 5779    13346.0
Name: new_cases, dtype: float64
5773 5780    11057.0
Name: new_cases, dtype: float64
5774 5781    7808.0
Name: new_cases, dtype: float64
5775 5782    8704.0
Name: new_cases, dtype: float64
5776 5783    13783.0
Name: new_cases, dtype: float64
5777 5784    12725.0
Name: new_cases, dtype: float64
5778 5785    13286.0
Name: new_cases, dtype: float64
5779 5786    12332.0
Name: new_cases, dtype: float64
5780 5787    8932.0
Name: new_cases, dtype: float64
5781 5788    7264.0
Name: new_cases, dtype: float64
5782 5789    8185.0
Name: new_cases, dtype: float64
5783 5790    12141.0
Name: new_cases, dtype: float64
5784 5791    12112.0
Name: new_cases, dtype: float64
5785 5792    11396.0
Name: new_cases, dtype: float64
5786 5793    10753.0
Name: new_cases, dtype: float64
5787 5794    8362.0
Name: new_cases, dtype: float64
5788 5795    5031.0
Name: new_cases, dtype: float64
5789 5796    7578.0
Name: new_cases, dtype: float64
5790 5797    10409.0
Name: new_cases, dtype: float64
5791 5798    10843.0
Name: new_cases, dtype: float64
5792 5799    9471.0
Name: new_cases, dtype: float64
5793 5800    9838.0
Name: new_cases, dtype: float64
5794 5801    6902.0
Name: new_cases, dtype: float64
5795 5802    4975.0
Name: new_cases, dtype: float64
5796 5803    6614.0
Name: new_cases, dtype: float64
5797 5804    9695.0
Name: new_cases, dtype: float64

5798 5805    9196.0
Name: new_cases, dtype: float64
5799 5806    8891.0
Name: new_cases, dtype: float64
5800 5807    8374.0
Name: new_cases, dtype: float64
5801 5808    6680.0
Name: new_cases, dtype: float64
5802 5809    3658.0
Name: new_cases, dtype: float64
5803 5810    5154.0
Name: new_cases, dtype: float64
5804 5811    7794.0
Name: new_cases, dtype: float64
5805 5812    7739.0
Name: new_cases, dtype: float64
5806 5813    7311.0
Name: new_cases, dtype: float64
5807 5814    7151.0
Name: new_cases, dtype: float64
5808 5815    6057.0
Name: new_cases, dtype: float64
5809 5816    4245.0
Name: new_cases, dtype: float64
5810 5817    3259.0
Name: new_cases, dtype: float64
5811 5818    4003.0
Name: new_cases, dtype: float64
5812 5819    6064.0
Name: new_cases, dtype: float64
5813 5820    7671.0
Name: new_cases, dtype: float64
5814 5821    7886.0
Name: new_cases, dtype: float64
5815 5822    5944.0
Name: new_cases, dtype: float64
5816 5823    3709.0
Name: new_cases, dtype: float64
5817 5824    5417.0
Name: new_cases, dtype: float64
5818 5825    7477.0
Name: new_cases, dtype: float64
5819 5826    8183.0
Name: new_cases, dtype: float64
5820 5827    8234.0
Name: new_cases, dtype: float64
5821 5828    5083.0
Name: new_cases, dtype: float64
5822 5829    5469.0
Name: new_cases, dtype: float64
5823 5830    3168.0
Name: new_cases, dtype: float64
5824 5831    4658.0
Name: new_cases, dtype: float64
5825 5832    6653.0
Name: new_cases, dtype: float64
5826 5833    7855.0
Name: new_cases, dtype: float64
5827 5834    7432.0
Name: new_cases, dtype: float64
5828 5835    7891.0
Name: new_cases, dtype: float64
5829 5836    4860.0
Name: new_cases, dtype: float64
5830 5837    2922.0
Name: new_cases, dtype: float64
5831 5838    5058.0
Name: new_cases, dtype: float64
5832 5839    7307.0
Name: new_cases, dtype: float64
5833 5840    7693.0
Name: new_cases, dtype: float64
5834 5841    8204.0
Name: new_cases, dtype: float64
5835 5842    7849.0
Name: new_cases, dtype: float64
5836 5843    6278.0
Name: new_cases, dtype: float64
5837 5844    3697.0
Name: new_cases, dtype: float64
5838 5845    6164.0
Name: new_cases, dtype: float64
5839 5846    8235.0
Name: new_cases, dtype: float64
5840 5847    8304.0
Name: new_cases, dtype: float64
5841 5848    8328.0
Name: new_cases, dtype: float64
5842 5849    8160.0
Name: new_cases, dtype: float64
5843 5850    6826.0
Name: new_cases, dtype: float64
5844 5851    4032.0
Name: new_cases, dtype: float64
5845 5852    6401.0
Name: new_cases, dtype: float64
5846 5853    9405.0
Name: new_cases, dtype: float64
5847 5854    8300.0
Name: new_cases, dtype: float64
5848 5855    8238.0
Name: new_cases, dtype: float64
5849 5856    12936.0
Name: new_cases, dtype: float64
5850 5857    10338.0
Name: new_cases, dtype: float64
5851 5858    7208.0
Name: new_cases, dtype: float64
5852 5859    14014.0
Name: new_cases, dtype: float64
5853 5860    10154.0
Name: new_cases, dtype: float64
5854 5861    16056.0
Name: new_cases, dtype: float64
5855 5862    14430.0
Name: new_cases, dtype: float64
5856 5863    9902.0
Name: new_cases, dtype: float64
5857 5864    10384.0
Name: new_cases, dtype: float64
5858 5865    9955.0
Name: new_cases, dtype: float64
5859 5866    13667.0
Name: new_cases, dtype: float64
5860 5867    20870.0
Name: new_cases, dtype: float64
5861 5868    22039.0
Name: new_cases, dtype: float64
5862 5869    23683.0
Name: new_cases, dtype: float64
5863 5870    24130.0
Name: new_cases, dtype: float64
5864 5871    19419.0
Name: new_cases, dtype: float64
5865 5872    15262.0
Name: new_cases, dtype: float64
5866 5873    19437.0
Name: new_cases, dtype: float64
5867 5874    27001.0
Name: new_cases, dtype: float64
5868 5875    25157.0
Name: new_cases, dtype: float64
5869 5876    24999.0
Name: new_cases, dtype: float64
5870 5877    29472.0
Name: new_cases, dtype: float64
5871 5878    19119.0
Name: new_cases, dtype: float64
5872 5879    16267.0
Name: new_cases, dtype: float64
5873 5880    20461.0
Name: new_cases, dtype: float64
5874 5881    29145.0
Name: new_cases, dtype: float64
5875 5882    25932.0
Name: new_cases, dtype: float64
5876 5883    27216.0
Name: new_cases, dtype: float64
5877 5884    27884.0
Name: new_cases, dtype: float64
5878 5885    21220.0
Name: new_cases, dtype: float64
5879 5886    15012.0
Name: new_cases, dtype: float64
5880 5887    18793.0
Name: new_cases, dtype: float64
5881 5888    25495.0
Name: new_cases, dtype: float64
5882 5889    23718.0
Name: new_cases, dtype: float64
5883 5890    26053.0
Name: new_cases, dtype: float64
5884 5891    22420.0
Name: new_cases, dtype: float64
5885 5892    16502.0
Name: new_cases, dtype: float64
5886 5893    11394.0
Name: new_cases, dtype: float64
5887 5894    15920.0
Name: new_cases, dtype: float64
5888 5895    26238.0
Name: new_cases, dtype: float64
5889 5896    24079.0
Name: new_cases, dtype: float64
5890 5897    24086.0
Name: new_cases, dtype: float64
5891 5898    22552.0
Name: new_cases, dtype: float64
5892 5899    18024.0
Name: new_cases, dtype: float64
5893 5900    11582.0
Name: new_cases, dtype: float64
5894 5901    17381.0
Name: new_cases, dtype: float64
5895 5902    25976.0
Name: new_cases, dtype: float64
5896 5903    24475.0
Name: new_cases, dtype: float64
5897 5904    26531.0
Name: new_cases, dtype: float64
5898 5905    27363.0
Name: new_cases, dtype: float64
5899 5906    21469.0
Name: new_cases, dtype: float64
5900 5907    16350.0
Name: new_cases, dtype: float64
5901 5908    28680.0
Name: new_cases, dtype: float64
5902 5909    35543.0
Name: new_cases, dtype: float64
5903 5910    39652.0
Name: new_cases, dtype: float64
5904 5911    35884.0
Name: new_cases, dtype: float64
5905 5912    35468.0
Name: new_cases, dtype: float64
5906 5913    32171.0
Name: new_cases, dtype: float64
5907 5914    24801.0
Name: new_cases, dtype: float64
5908 5915    22651.0
Name: new_cases, dtype: float64
5909 5916    24601.0
Name: new_cases, dtype: float64
5910 5917    35399.0
Name: new_cases, dtype: float64
5911 5918    41080.0
Name: new_cases, dtype: float64
5912 5919    39207.0
Name: new_cases, dtype: float64
5913 5920    29841.0
Name: new_cases, dtype: float64
5914 5921    21346.0
Name: new_cases, dtype: float64
5915 5922    28175.0
Name: new_cases, dtype: float64
5916 5923    35355.0
Name: new_cases, dtype: float64
5917 5924    35017.0
Name: new_cases, dtype: float64
5918 5925    32291.0
Name: new_cases, dtype: float64
5919 5926    30950.0
Name: new_cases, dtype: float64
5920 5927    23627.0
Name: new_cases, dtype: float64
5921 5928    16415.0
Name: new_cases, dtype: float64
5922 5929    22195.0
Name: new_cases, dtype: float64
5923 5930    31137.0
Name: new_cases, dtype: float64
5924 5931    29757.0
Name: new_cases, dtype: float64
5925 5932    27628.0
Name: new_cases, dtype: float64
5926 5933    26934.0
Name: new_cases, dtype: float64
5927 5934    18057.0
Name: new_cases, dtype: float64
5928 5935    13043.0
Name: new_cases, dtype: float64
5929 5936    21292.0
Name: new_cases, dtype: float64
5930 5937    27260.0
Name: new_cases, dtype: float64
5931 5938    25878.0
Name: new_cases, dtype: float64
5932 5939    23780.0
Name: new_cases, dtype: float64
5933 5940    20363.0
Name: new_cases, dtype: float64
5934 5941    15631.0
Name: new_cases, dtype: float64
5935 5942    10395.0
Name: new_cases, dtype: float64
5936 5943    8606.0
Name: new_cases, dtype: float64
5937 5944    21387.0
Name: new_cases, dtype: float64
5938 5945    27319.0
Name: new_cases, dtype: float64
5939 5946    24463.0
Name: new_cases, dtype: float64
5940 5947    24023.0
Name: new_cases, dtype: float64
5941 5948    18555.0
Name: new_cases, dtype: float64
5942 5949    12105.0
Name: new_cases, dtype: float64
5943 5950    18389.0
Name: new_cases, dtype: float64
5944 5951    24065.0
Name: new_cases, dtype: float64
5945 5952    22673.0
Name: new_cases, dtype: float64
5946 5953    21177.0
Name: new_cases, dtype: float64
5947 5954    20888.0
Name: new_cases, dtype: float64
5948 5955    14034.0
Name: new_cases, dtype: float64
5949 5956    9000.0
Name: new_cases, dtype: float64
5950 5957    17277.0
Name: new_cases, dtype: float64
5951 5958    21590.0
Name: new_cases, dtype: float64
5952 5959    19423.0
Name: new_cases, dtype: float64
5953 5960    19256.0
Name: new_cases, dtype: float64
5954 5961    14518.0
Name: new_cases, dtype: float64
5955 5962    11561.0
Name: new_cases, dtype: float64
5956 5963    8850.0
Name: new_cases, dtype: float64
5957 5964    14989.0
Name: new_cases, dtype: float64
5958 5965    20023.0
Name: new_cases, dtype: float64

5959 5966    19697.0
Name: new_cases, dtype: float64
5960 5967    17295.0
Name: new_cases, dtype: float64
5961 5968    17261.0
Name: new_cases, dtype: float64
5962 5969    12230.0
Name: new_cases, dtype: float64
5963 5970    6935.0
Name: new_cases, dtype: float64
5964 5971    12764.0
Name: new_cases, dtype: float64
5965 5972    15077.0
Name: new_cases, dtype: float64
5966 5973    14632.0
Name: new_cases, dtype: float64
5967 5974    13500.0
Name: new_cases, dtype: float64
5968 5975    15622.0
Name: new_cases, dtype: float64
5969 5976    11136.0
Name: new_cases, dtype: float64
5970 5977    7506.0
Name: new_cases, dtype: float64
5971 5978    12555.0
Name: new_cases, dtype: float64
5972 5979    16757.0
Name: new_cases, dtype: float64
5973 5980    15883.0
Name: new_cases, dtype: float64
5974 5981    14115.0
Name: new_cases, dtype: float64
5975 5982    13483.0
Name: new_cases, dtype: float64
5976 5983    10356.0
Name: new_cases, dtype: float64
5977 5984    6083.0
Name: new_cases, dtype: float64
5978 5985    11183.0
Name: new_cases, dtype: float64
5979 5986    14850.0
Name: new_cases, dtype: float64
5980 5987    13736.0
Name: new_cases, dtype: float64
5981 5988    13786.0
Name: new_cases, dtype: float64
5982 5989    13549.0
Name: new_cases, dtype: float64
5983 5990    9803.0
Name: new_cases, dtype: float64
5984 5991    6141.0
Name: new_cases, dtype: float64
5985 5992    10180.0
Name: new_cases, dtype: float64
5986 5993    12412.0
Name: new_cases, dtype: float64
5987 5994    11397.0
Name: new_cases, dtype: float64
5988 5995    13369.0
Name: new_cases, dtype: float64
5989 5996    8472.0
Name: new_cases, dtype: float64
5990 5997    6183.0
Name: new_cases, dtype: float64
5991 5998    3727.0
Name: new_cases, dtype: float64
5992 5999    3636.0
Name: new_cases, dtype: float64
5993 6000    8172.0
Name: new_cases, dtype: float64
5994 6001    9764.0
Name: new_cases, dtype: float64
5995 6002    10596.0
Name: new_cases, dtype: float64
5996 6003    8160.0
Name: new_cases, dtype: float64
5997 6004    5889.0
Name: new_cases, dtype: float64
5998 6005    2979.0
Name: new_cases, dtype: float64
5999 6006    6135.0
Name: new_cases, dtype: float64
6000 6007    8119.0
Name: new_cases, dtype: float64
6001 6008    6994.0
Name: new_cases, dtype: float64
6002 6009    6847.0
Name: new_cases, dtype: float64
6003 6010    5807.0
Name: new_cases, dtype: float64
6004 6011    3725.0
Name: new_cases, dtype: float64
6005 6012    2073.0
Name: new_cases, dtype: float64
6006 6013    5358.0
Name: new_cases, dtype: float64
6007 6014    6731.0
Name: new_cases, dtype: float64
6008 6015    5328.0
Name: new_cases, dtype: float64
6009 6016    4653.0
Name: new_cases, dtype: float64
6010 6017    4318.0
Name: new_cases, dtype: float64
6011 6018    2486.0
Name: new_cases, dtype: float64
6012 6019    1397.0
Name: new_cases, dtype: float64
6013 6020    3893.0
Name: new_cases, dtype: float64
6014 6021    4106.0
Name: new_cases, dtype: float64
6015 6022    3531.0
Name: new_cases, dtype: float64
6016 6023    3661.0
Name: new_cases, dtype: float64
6017 6024    2816.0
Name: new_cases, dtype: float64
6018 6025    1795.0
Name: new_cases, dtype: float64
6019 6026    930.0
Name: new_cases, dtype: float64
6020 6027    2297.0
Name: new_cases, dtype: float64
6021 6028    3017.0
Name: new_cases, dtype: float64
6022 6029    2510.0
Name: new_cases, dtype: float64
6023 6030    2493.0
Name: new_cases, dtype: float64
6024 6031    2308.0
Name: new_cases, dtype: float64
6025 6032    1451.0
Name: new_cases, dtype: float64
6026 6033    622.0
Name: new_cases, dtype: float64
6027 6034    2162.0
Name: new_cases, dtype: float64
6028 6035    1837.0
Name: new_cases, dtype: float64
6029 6036    2034.0
Name: new_cases, dtype: float64
6030 6037    1733.0
Name: new_cases, dtype: float64
6031 6038    1849.0
Name: new_cases, dtype: float64
6032 6039    993.0
Name: new_cases, dtype: float64
6033 6040    562.0
Name: new_cases, dtype: float64
6034 6041    1538.0
Name: new_cases, dtype: float64
6035 6042    1825.0
Name: new_cases, dtype: float64
6036 6043    1496.0
Name: new_cases, dtype: float64
6037 6044    1641.0
Name: new_cases, dtype: float64
6038 6045    1564.0
Name: new_cases, dtype: float64
6039 6046    886.0
Name: new_cases, dtype: float64
6040 6047    386.0
Name: new_cases, dtype: float64
6041 6048    981.0
Name: new_cases, dtype: float64
6042 6049    1216.0
Name: new_cases, dtype: float64
6043 6050    1284.0
Name: new_cases, dtype: float64
6044 6051    1086.0
Name: new_cases, dtype: float64
6045 6052    753.0
Name: new_cases, dtype: float64
6046 6053    470.0
Name: new_cases, dtype: float64
6047 6054    331.0
Name: new_cases, dtype: float64
6048 6055    416.0
Name: new_cases, dtype: float64
6049 6056    1064.0
Name: new_cases, dtype: float64
6050 6057    1314.0
Name: new_cases, dtype: float64
6051 6058    1350.0
Name: new_cases, dtype: float64
6052 6059    1358.0
Name: new_cases, dtype: float64
6053 6060    790.0
Name: new_cases, dtype: float64
6054 6061    400.0
Name: new_cases, dtype: float64
6055 6062    912.0
Name: new_cases, dtype: float64
6056 6063    1303.0
Name: new_cases, dtype: float64
6057 6064    1218.0
Name: new_cases, dtype: float64
6058 6065    1541.0
Name: new_cases, dtype: float64
6059 6066    1385.0
Name: new_cases, dtype: float64
6060 6067    908.0
Name: new_cases, dtype: float64
6061 6068    540.0
Name: new_cases, dtype: float64
6062 6069    1227.0
Name: new_cases, dtype: float64
6063 6070    1415.0
Name: new_cases, dtype: float64
6064 6071    1485.0
Name: new_cases, dtype: float64
6065 6072    1589.0
Name: new_cases, dtype: float64
6066 6073    1373.0
Name: new_cases, dtype: float64
6067 6074    812.0
Name: new_cases, dtype: float64
6068 6075    548.0
Name: new_cases, dtype: float64
6069 6076    1138.0
Name: new_cases, dtype: float64
6070 6077    1340.0
Name: new_cases, dtype: float64
6071 6078    1264.0
Name: new_cases, dtype: float64
6072 6079    1440.0
Name: new_cases, dtype: float64
6073 6080    1271.0
Name: new_cases, dtype: float64
6074 6081    928.0
Name: new_cases, dtype: float64
6075 6082    593.0
Name: new_cases, dtype: float64
6076 6083    1288.0
Name: new_cases, dtype: float64
6077 6084    1349.0
Name: new_cases, dtype: float64
6078 6085    1567.0
Name: new_cases, dtype: float64
6079 6086    1460.0
Name: new_cases, dtype: float64
6080 6087    1614.0
Name: new_cases, dtype: float64
6081 6088    1092.0
Name: new_cases, dtype: float64
6082 6089    591.0
Name: new_cases, dtype: float64
6083 6090    1417.0
Name: new_cases, dtype: float64
6084 6091    1622.0
Name: new_cases, dtype: float64
6085 6092    1553.0
Name: new_cases, dtype: float64
6086 6093    1755.0
Name: new_cases, dtype: float64
6087 6094    1518.0
Name: new_cases, dtype: float64
6088 6095    1095.0
Name: new_cases, dtype: float64
6089 6096    646.0
Name: new_cases, dtype: float64
6090 6097    641.0
Name: new_cases, dtype: float64
6091 6098    1644.0
Name: new_cases, dtype: float64
6092 6099    2234.0
Name: new_cases, dtype: float64
6093 6100    2260.0
Name: new_cases, dtype: float64
6094 6101    1912.0
Name: new_cases, dtype: float64
6095 6102    1521.0
Name: new_cases, dtype: float64
6096 6103    888.0
Name: new_cases, dtype: float64
6097 6104    1968.0
Name: new_cases, dtype: float64
6098 6105    2332.0
Name: new_cases, dtype: float64
6099 6106    1881.0
Name: new_cases, dtype: float64
6100 6107    2681.0
Name: new_cases, dtype: float64
6101 6108    2382.0
Name: new_cases, dtype: float64
6102 6109    1690.0
Name: new_cases, dtype: float64
6103 6110    1294.0
Name: new_cases, dtype: float64
6104 6111    2477.0
Name: new_cases, dtype: float64
6105 6112    3089.0
Name: new_cases, dtype: float64
6106 6113    1881.0
Name: new_cases, dtype: float64
6107 6114    2744.0
Name: new_cases, dtype: float64
6108 6115    3573.0
Name: new_cases, dtype: float64
6109 6116    2445.0
Name: new_cases, dtype: float64
6110 6117    1570.0
Name: new_cases, dtype: float64
6111 6118    3512.0
Name: new_cases, dtype: float64
6112 6119    4555.0
Name: new_cases, dtype: float64
6113 6120    4819.0
Name: new_cases, dtype: float64
6114 6121    5301.0
Name: new_cases, dtype: float64
6115 6122    5648.0
Name: new_cases, dtype: float64
6116 6123    4163.0
Name: new_cases, dtype: float64
6117 6124    3254.0
Name: new_cases, dtype: float64
6118 6125    5337.0
Name: new_cases, dtype: float64

6119 6126    9336.0
Name: new_cases, dtype: float64
6120 6127    11121.0
Name: new_cases, dtype: float64
6121 6128    13456.0
Name: new_cases, dtype: float64
6122 6129    16279.0
Name: new_cases, dtype: float64
6123 6130    7183.0
Name: new_cases, dtype: float64
6124 6131    7623.0
Name: new_cases, dtype: float64
6125 6132    20263.0
Name: new_cases, dtype: float64
6126 6133    33902.0
Name: new_cases, dtype: float64
6127 6134    42032.0
Name: new_cases, dtype: float64
6128 6135    50506.0
Name: new_cases, dtype: float64
6129 6136    47663.0
Name: new_cases, dtype: float64
6130 6137    20020.0
Name: new_cases, dtype: float64
6131 6138    20502.0
Name: new_cases, dtype: float64
6132 6139    44396.0
Name: new_cases, dtype: float64
6133 6140    81210.0
Name: new_cases, dtype: float64
6134 6141    95159.0
Name: new_cases, dtype: float64
6135 6142    109608.0
Name: new_cases, dtype: float64
6136 6143    110533.0
Name: new_cases, dtype: float64
6137 6144    101689.0
Name: new_cases, dtype: float64
6138 Series([], Name: new_cases, dtype: float64)
6139 Series([], Name: new_cases, dtype: float64)
6140 Series([], Name: new_cases, dtype: float64)
6141 Series([], Name: new_cases, dtype: float64)
6142 Series([], Name: new_cases, dtype: float64)
6143 Series([], Name: new_cases, dtype: float64)
6144 Series([], Name: new_cases, dtype: float64)
8209 8216    0.0
Name: new_cases, dtype: float64
8210 8217    0.0
Name: new_cases, dtype: float64
8211 8218    1.0
Name: new_cases, dtype: float64
8212 8219    0.0
Name: new_cases, dtype: float64
8213 8220    1.0
Name: new_cases, dtype: float64
8214 8221    1.0
Name: new_cases, dtype: float64
8215 8222    0.0
Name: new_cases, dtype: float64
8216 8223    0.0
Name: new_cases, dtype: float64
8217 8224    0.0
Name: new_cases, dtype: float64
8218 8225    0.0
Name: new_cases, dtype: float64
8219 8226    0.0
Name: new_cases, dtype: float64
8220 8227    0.0
Name: new_cases, dtype: float64
8221 8228    0.0
Name: new_cases, dtype: float64
8222 8229    0.0
Name: new_cases, dtype: float64
8223 8230    0.0
Name: new_cases, dtype: float64
8224 8231    0.0
Name: new_cases, dtype: float64
8225 8232    0.0
Name: new_cases, dtype: float64
8226 8233    0.0
Name: new_cases, dtype: float64
8227 8234    0.0
Name: new_cases, dtype: float64
8228 8235    0.0
Name: new_cases, dtype: float64
8229 8236    0.0
Name: new_cases, dtype: float64
8230 8237    0.0
Name: new_cases, dtype: float64
8231 8238    0.0
Name: new_cases, dtype: float64
8232 8239    0.0
Name: new_cases, dtype: float64
8233 8240    0.0
Name: new_cases, dtype: float64
8234 8241    0.0
Name: new_cases, dtype: float64
8235 8242    0.0
Name: new_cases, dtype: float64
8236 8243    10.0
Name: new_cases, dtype: float64
8237 8244    2.0
Name: new_cases, dtype: float64
8238 8245    3.0
Name: new_cases, dtype: float64
8239 8246    9.0
Name: new_cases, dtype: float64
8240 8247    13.0
Name: new_cases, dtype: float64
8241 8248    3.0
Name: new_cases, dtype: float64
8242 8249    5.0
Name: new_cases, dtype: float64
8243 8250    3.0
Name: new_cases, dtype: float64
8244 8251    13.0
Name: new_cases, dtype: float64
8245 8252    15.0
Name: new_cases, dtype: float64
8246 8253    16.0
Name: new_cases, dtype: float64
8247 8254    21.0
Name: new_cases, dtype: float64
8248 8255    0.0
Name: new_cases, dtype: float64
8249 8256    72.0
Name: new_cases, dtype: float64
8250 8257    50.0
Name: new_cases, dtype: float64
8251 8258    47.0
Name: new_cases, dtype: float64
8252 8259    80.0
Name: new_cases, dtype: float64
8253 8260    75.0
Name: new_cases, dtype: float64
8254 8261    116.0
Name: new_cases, dtype: float64
8255 8262    113.0
Name: new_cases, dtype: float64
8256 8263    110.0
Name: new_cases, dtype: float64
8257 8264    280.0
Name: new_cases, dtype: float64
8258 8265    478.0
Name: new_cases, dtype: float64
8259 8266    133.0
Name: new_cases, dtype: float64
8260 8267    362.0
Name: new_cases, dtype: float64
8261 8268    320.0
Name: new_cases, dtype: float64
8262 8269    446.0
Name: new_cases, dtype: float64
8263 8270    333.0
Name: new_cases, dtype: float64
8264 8271    497.0
Name: new_cases, dtype: float64
8265 8272    344.0
Name: new_cases, dtype: float64
8266 8273    377.0
Name: new_cases, dtype: float64
8267 8274    198.0
Name: new_cases, dtype: float64
8268 8275    303.0
Name: new_cases, dtype: float64
8269 8276    254.0
Name: new_cases, dtype: float64
8270 8277    214.0
Name: new_cases, dtype: float64
8271 8278    220.0
Name: new_cases, dtype: float64
8272 8279    137.0
Name: new_cases, dtype: float64
8273 8280    110.0
Name: new_cases, dtype: float64
8274 8281    98.0
Name: new_cases, dtype: float64
8275 8282    115.0
Name: new_cases, dtype: float64
8276 8283    98.0
Name: new_cases, dtype: float64
8277 8284    107.0
Name: new_cases, dtype: float64
8278 8285    88.0
Name: new_cases, dtype: float64
8279 8286    12.0
Name: new_cases, dtype: float64
8280 8287    36.0
Name: new_cases, dtype: float64
8281 8288    64.0
Name: new_cases, dtype: float64
8282 8289    25.0
Name: new_cases, dtype: float64
8283 8290    22.0
Name: new_cases, dtype: float64
8284 8291    60.0
Name: new_cases, dtype: float64
8285 8292    46.0
Name: new_cases, dtype: float64
8286 8293    42.0
Name: new_cases, dtype: float64
8287 8294    13.0
Name: new_cases, dtype: float64
8288 8295    22.0
Name: new_cases, dtype: float64
8289 8296    7.0
Name: new_cases, dtype: float64
8290 8297    10.0
Name: new_cases, dtype: float64
8291 8298    15.0
Name: new_cases, dtype: float64
8292 8299    17.0
Name: new_cases, dtype: float64
8293 8300    20.0
Name: new_cases, dtype: float64
8294 8301    7.0
Name: new_cases, dtype: float64
8295 8302    23.0
Name: new_cases, dtype: float64
8296 8303    8.0
Name: new_cases, dtype: float64
8297 8304    14.0
Name: new_cases, dtype: float64
8298 8305    12.0
Name: new_cases, dtype: float64
8299 8306    21.0
Name: new_cases, dtype: float64
8300 8307    23.0
Name: new_cases, dtype: float64
8301 8308    25.0
Name: new_cases, dtype: float64
8302 8309    28.0
Name: new_cases, dtype: float64
8303 8310    19.0
Name: new_cases, dtype: float64
8304 8311    19.0
Name: new_cases, dtype: float64
8305 8312    5.0
Name: new_cases, dtype: float64
8306 8313    21.0
Name: new_cases, dtype: float64
8307 8314    9.0
Name: new_cases, dtype: float64
8308 8315    22.0
Name: new_cases, dtype: float64
8309 8316    10.0
Name: new_cases, dtype: float64
8310 8317    9.0
Name: new_cases, dtype: float64
8311 8318    30.0
Name: new_cases, dtype: float64
8312 8319    16.0
Name: new_cases, dtype: float64
8313 8320    9.0
Name: new_cases, dtype: float64
8314 8321    10.0
Name: new_cases, dtype: float64
8315 8322    14.0
Name: new_cases, dtype: float64
8316 8323    4.0
Name: new_cases, dtype: float64
8317 8324    9.0
Name: new_cases, dtype: float64
8318 8325    14.0
Name: new_cases, dtype: float64
8319 8326    4.0
Name: new_cases, dtype: float64
8320 8327    15.0
Name: new_cases, dtype: float64
8321 8328    0.0
Name: new_cases, dtype: float64
8322 8329    12.0
Name: new_cases, dtype: float64
8323 8330    13.0
Name: new_cases, dtype: float64
8324 8331    11.0
Name: new_cases, dtype: float64
8325 8332    15.0
Name: new_cases, dtype: float64
8326 8333    19.0
Name: new_cases, dtype: float64
8327 8334    8.0
Name: new_cases, dtype: float64
8328 8335    10.0
Name: new_cases, dtype: float64
8329 8336    19.0
Name: new_cases, dtype: float64
8330 8337    8.0
Name: new_cases, dtype: float64
8331 8338    11.0
Name: new_cases, dtype: float64
8332 8339    7.0
Name: new_cases, dtype: float64
8333 8340    5.0
Name: new_cases, dtype: float64
8334 8341    7.0
Name: new_cases, dtype: float64
8335 8342    6.0
Name: new_cases, dtype: float64
8336 8343    2.0
Name: new_cases, dtype: float64
8337 8344    7.0
Name: new_cases, dtype: float64
8338 8345    11.0
Name: new_cases, dtype: float64
8339 8346    4.0
Name: new_cases, dtype: float64
8340 8347    5.0
Name: new_cases, dtype: float64
8341 8348    26.0
Name: new_cases, dtype: float64
8342 8349    15.0
Name: new_cases, dtype: float64
8343 8350    12.0
Name: new_cases, dtype: float64
8344 8351    23.0
Name: new_cases, dtype: float64
8345 8352    21.0
Name: new_cases, dtype: float64
8346 8353    18.0
Name: new_cases, dtype: float64
8347 8354    2.0
Name: new_cases, dtype: float64
8348 8355    50.0
Name: new_cases, dtype: float64
8349 8356    13.0
Name: new_cases, dtype: float64
8350 8357    18.0
Name: new_cases, dtype: float64
8351 8358    29.0
Name: new_cases, dtype: float64
8352 8359    37.0
Name: new_cases, dtype: float64
8353 8360    37.0
Name: new_cases, dtype: float64

8354 8361    6.0
Name: new_cases, dtype: float64
8355 8362    85.0
Name: new_cases, dtype: float64
8356 8363    78.0
Name: new_cases, dtype: float64
8357 8364    70.0
Name: new_cases, dtype: float64
8358 8365    86.0
Name: new_cases, dtype: float64
8359 8366    81.0
Name: new_cases, dtype: float64
8360 8367    65.0
Name: new_cases, dtype: float64
8361 8368    194.0
Name: new_cases, dtype: float64
8362 8369    183.0
Name: new_cases, dtype: float64
8363 8370    140.0
Name: new_cases, dtype: float64
8364 8371    172.0
Name: new_cases, dtype: float64
8365 8372    131.0
Name: new_cases, dtype: float64
8366 8373    170.0
Name: new_cases, dtype: float64
8367 8374    318.0
Name: new_cases, dtype: float64
8368 8375    179.0
Name: new_cases, dtype: float64
8369 8376    244.0
Name: new_cases, dtype: float64
8370 8377    183.0
Name: new_cases, dtype: float64
8371 8378    271.0
Name: new_cases, dtype: float64
8372 8379    236.0
Name: new_cases, dtype: float64
8373 8380    323.0
Name: new_cases, dtype: float64
8374 8381    423.0
Name: new_cases, dtype: float64
8375 8382    208.0
Name: new_cases, dtype: float64
8376 8383    361.0
Name: new_cases, dtype: float64
8377 8384    267.0
Name: new_cases, dtype: float64
8378 8385    359.0
Name: new_cases, dtype: float64
8379 8386    466.0
Name: new_cases, dtype: float64
8380 8387    408.0
Name: new_cases, dtype: float64
8381 8388    293.0
Name: new_cases, dtype: float64
8382 8389    355.0
Name: new_cases, dtype: float64
8383 8390    453.0
Name: new_cases, dtype: float64
8384 8391    532.0
Name: new_cases, dtype: float64
8385 8392    368.0
Name: new_cases, dtype: float64
8386 8393    279.0
Name: new_cases, dtype: float64
8387 8394    716.0
Name: new_cases, dtype: float64
8388 8395    605.0
Name: new_cases, dtype: float64
8389 8396    377.0
Name: new_cases, dtype: float64
8390 8397    615.0
Name: new_cases, dtype: float64
8391 8398    423.0
Name: new_cases, dtype: float64
8392 8399    412.0
Name: new_cases, dtype: float64
8393 8400    715.0
Name: new_cases, dtype: float64
8394 8401    445.0
Name: new_cases, dtype: float64
8395 8402    382.0
Name: new_cases, dtype: float64
8396 8403    426.0
Name: new_cases, dtype: float64
8397 8404    386.0
Name: new_cases, dtype: float64
8398 8405    313.0
Name: new_cases, dtype: float64
8399 8406    316.0
Name: new_cases, dtype: float64
8400 8407    414.0
Name: new_cases, dtype: float64
8401 8408    231.0
Name: new_cases, dtype: float64
8402 8409    384.0
Name: new_cases, dtype: float64
8403 8410    293.0
Name: new_cases, dtype: float64
8404 8411    252.0
Name: new_cases, dtype: float64
8405 8412    271.0
Name: new_cases, dtype: float64
8406 8413    215.0
Name: new_cases, dtype: float64
8407 8414    216.0
Name: new_cases, dtype: float64
8408 8415    247.0
Name: new_cases, dtype: float64
8409 8416    171.0
Name: new_cases, dtype: float64
8410 8417    195.0
Name: new_cases, dtype: float64
8411 8418    209.0
Name: new_cases, dtype: float64
8412 8419    104.0
Name: new_cases, dtype: float64
8413 8420    138.0
Name: new_cases, dtype: float64
8414 8421    151.0
Name: new_cases, dtype: float64
8415 8422    118.0
Name: new_cases, dtype: float64
8416 8423    126.0
Name: new_cases, dtype: float64
8417 8424    99.0
Name: new_cases, dtype: float64
8418 8425    123.0
Name: new_cases, dtype: float64
8419 8426    76.0
Name: new_cases, dtype: float64
8420 8427    73.0
Name: new_cases, dtype: float64
8421 8428    104.0
Name: new_cases, dtype: float64
8422 8429    126.0
Name: new_cases, dtype: float64
8423 8430    87.0
Name: new_cases, dtype: float64
8424 8431    71.0
Name: new_cases, dtype: float64
8425 8432    71.0
Name: new_cases, dtype: float64
8426 8433    43.0
Name: new_cases, dtype: float64
8427 8434    52.0
Name: new_cases, dtype: float64
8428 8435    92.0
Name: new_cases, dtype: float64
8429 8436    59.0
Name: new_cases, dtype: float64
8430 8437    40.0
Name: new_cases, dtype: float64
8431 8438    43.0
Name: new_cases, dtype: float64
8432 8439    44.0
Name: new_cases, dtype: float64
8433 8440    41.0
Name: new_cases, dtype: float64
8434 8441    47.0
Name: new_cases, dtype: float64
8435 8442    39.0
Name: new_cases, dtype: float64
8436 8443    35.0
Name: new_cases, dtype: float64
8437 8444    48.0
Name: new_cases, dtype: float64
8438 8445    24.0
Name: new_cases, dtype: float64
8439 8446    13.0
Name: new_cases, dtype: float64
8440 8447    14.0
Name: new_cases, dtype: float64
8441 8448    30.0
Name: new_cases, dtype: float64
8442 8449    30.0
Name: new_cases, dtype: float64
8443 8450    8.0
Name: new_cases, dtype: float64
8444 8451    20.0
Name: new_cases, dtype: float64
8445 8452    16.0
Name: new_cases, dtype: float64
8446 8453    24.0
Name: new_cases, dtype: float64
8447 8454    4.0
Name: new_cases, dtype: float64
8448 8455    11.0
Name: new_cases, dtype: float64
8449 8456    23.0
Name: new_cases, dtype: float64
8450 8457    18.0
Name: new_cases, dtype: float64
8451 8458    13.0
Name: new_cases, dtype: float64
8452 8459    12.0
Name: new_cases, dtype: float64
8453 8460    14.0
Name: new_cases, dtype: float64
8454 8461    13.0
Name: new_cases, dtype: float64
8455 8462    25.0
Name: new_cases, dtype: float64
8456 8463    8.0
Name: new_cases, dtype: float64
8457 8464    25.0
Name: new_cases, dtype: float64
8458 8465    20.0
Name: new_cases, dtype: float64
8459 8466    18.0
Name: new_cases, dtype: float64
8460 8467    19.0
Name: new_cases, dtype: float64
8461 8468    22.0
Name: new_cases, dtype: float64
8462 8469    25.0
Name: new_cases, dtype: float64
8463 8470    27.0
Name: new_cases, dtype: float64
8464 8471    20.0
Name: new_cases, dtype: float64
8465 8472    14.0
Name: new_cases, dtype: float64
8466 8473    7.0
Name: new_cases, dtype: float64
8467 8474    12.0
Name: new_cases, dtype: float64
8468 8475    9.0
Name: new_cases, dtype: float64
8469 8476    6.0
Name: new_cases, dtype: float64
8470 8477    38.0
Name: new_cases, dtype: float64
8471 8478    15.0
Name: new_cases, dtype: float64
8472 8479    18.0
Name: new_cases, dtype: float64
8473 8480    19.0
Name: new_cases, dtype: float64
8474 8481    18.0
Name: new_cases, dtype: float64
8475 8482    12.0
Name: new_cases, dtype: float64
8476 8483    14.0
Name: new_cases, dtype: float64
8477 8484    14.0
Name: new_cases, dtype: float64
8478 8485    12.0
Name: new_cases, dtype: float64
8479 8486    14.0
Name: new_cases, dtype: float64
8480 8487    6.0
Name: new_cases, dtype: float64
8481 8488    10.0
Name: new_cases, dtype: float64
8482 8489    6.0
Name: new_cases, dtype: float64
8483 8490    9.0
Name: new_cases, dtype: float64
8484 8491    12.0
Name: new_cases, dtype: float64
8485 8492    8.0
Name: new_cases, dtype: float64
8486 8493    14.0
Name: new_cases, dtype: float64
8487 8494    8.0
Name: new_cases, dtype: float64
8488 8495    6.0
Name: new_cases, dtype: float64
8489 8496    7.0
Name: new_cases, dtype: float64
8490 8497    4.0
Name: new_cases, dtype: float64
8491 8498    2.0
Name: new_cases, dtype: float64
8492 8499    4.0
Name: new_cases, dtype: float64
8493 8500    1.0
Name: new_cases, dtype: float64
8494 8501    6.0
Name: new_cases, dtype: float64
8495 8502    29.0
Name: new_cases, dtype: float64
8496 8503    38.0
Name: new_cases, dtype: float64
8497 8504    9.0
Name: new_cases, dtype: float64
8498 8505    19.0
Name: new_cases, dtype: float64
8499 8506    8.0
Name: new_cases, dtype: float64
8500 8507    7.0
Name: new_cases, dtype: float64
8501 8508    14.0
Name: new_cases, dtype: float64
8502 8509    15.0
Name: new_cases, dtype: float64
8503 8510    13.0
Name: new_cases, dtype: float64
8504 8511    9.0
Name: new_cases, dtype: float64
8505 8512    10.0
Name: new_cases, dtype: float64
8506 8513    12.0
Name: new_cases, dtype: float64
8507 8514    8.0
Name: new_cases, dtype: float64
8508 8515    13.0
Name: new_cases, dtype: float64
8509 8516    6.0
Name: new_cases, dtype: float64
8510 8517    10.0
Name: new_cases, dtype: float64
8511 8518    10.0
Name: new_cases, dtype: float64
8512 8519    11.0
Name: new_cases, dtype: float64
8513 8520    16.0
Name: new_cases, dtype: float64
8514 8521    10.0
Name: new_cases, dtype: float64
8515 8522    7.0
Name: new_cases, dtype: float64
8516 8523    9.0
Name: new_cases, dtype: float64
8517 8524    7.0
Name: new_cases, dtype: float64
8518 8525    15.0
Name: new_cases, dtype: float64
8519 8526    6.0
Name: new_cases, dtype: float64
8520 8527    7.0
Name: new_cases, dtype: float64
8521 8528    11.0
Name: new_cases, dtype: float64
8522 8529    14.0
Name: new_cases, dtype: float64
8523 8530    5.0
Name: new_cases, dtype: float64
8524 8531    7.0
Name: new_cases, dtype: float64
8525 8532    11.0
Name: new_cases, dtype: float64
8526 8533    12.0
Name: new_cases, dtype: float64
8527 8534    12.0
Name: new_cases, dtype: float64
8528 8535    21.0
Name: new_cases, dtype: float64

8529 8536    33.0
Name: new_cases, dtype: float64
8530 8537    42.0
Name: new_cases, dtype: float64
8531 8538    30.0
Name: new_cases, dtype: float64
8532 8539    21.0
Name: new_cases, dtype: float64
8533 8540    18.0
Name: new_cases, dtype: float64
8534 8541    25.0
Name: new_cases, dtype: float64
8535 8542    12.0
Name: new_cases, dtype: float64
8536 8543    23.0
Name: new_cases, dtype: float64
8537 8544    11.0
Name: new_cases, dtype: float64
8538 8545    29.0
Name: new_cases, dtype: float64
8539 8546    12.0
Name: new_cases, dtype: float64
8540 8547    32.0
Name: new_cases, dtype: float64
8541 8548    24.0
Name: new_cases, dtype: float64
8542 8549    20.0
Name: new_cases, dtype: float64
8543 8550    35.0
Name: new_cases, dtype: float64
8544 8551    24.0
Name: new_cases, dtype: float64
8545 8552    20.0
Name: new_cases, dtype: float64
8546 8553    13.0
Name: new_cases, dtype: float64
8547 8554    19.0
Name: new_cases, dtype: float64
8548 8555    10.0
Name: new_cases, dtype: float64
8549 8556    25.0
Name: new_cases, dtype: float64
8550 8557    11.0
Name: new_cases, dtype: float64
8551 8558    13.0
Name: new_cases, dtype: float64
8552 8559    19.0
Name: new_cases, dtype: float64
8553 8560    20.0
Name: new_cases, dtype: float64
8554 8561    16.0
Name: new_cases, dtype: float64
8555 8562    10.0
Name: new_cases, dtype: float64
8556 8563    9.0
Name: new_cases, dtype: float64
8557 8564    20.0
Name: new_cases, dtype: float64
8558 8565    19.0
Name: new_cases, dtype: float64
8559 8566    13.0
Name: new_cases, dtype: float64
8560 8567    10.0
Name: new_cases, dtype: float64
8561 8568    9.0
Name: new_cases, dtype: float64
8562 8569    9.0
Name: new_cases, dtype: float64
8563 8570    6.0
Name: new_cases, dtype: float64
8564 8571    5.0
Name: new_cases, dtype: float64
8565 8572    6.0
Name: new_cases, dtype: float64
8566 8573    11.0
Name: new_cases, dtype: float64
8567 8574    3.0
Name: new_cases, dtype: float64
8568 8575    6.0
Name: new_cases, dtype: float64
8569 8576    8.0
Name: new_cases, dtype: float64
8570 8577    5.0
Name: new_cases, dtype: float64
8571 8578    7.0
Name: new_cases, dtype: float64
8572 8579    5.0
Name: new_cases, dtype: float64
8573 8580    7.0
Name: new_cases, dtype: float64
8574 8581    5.0
Name: new_cases, dtype: float64
8575 8582    6.0
Name: new_cases, dtype: float64
8576 8583    9.0
Name: new_cases, dtype: float64
8577 8584    4.0
Name: new_cases, dtype: float64
8578 8585    6.0
Name: new_cases, dtype: float64
8579 8586    3.0
Name: new_cases, dtype: float64
8580 8587    6.0
Name: new_cases, dtype: float64
8581 8588    3.0
Name: new_cases, dtype: float64
8582 8589    11.0
Name: new_cases, dtype: float64
8583 8590    8.0
Name: new_cases, dtype: float64
8584 8591    8.0
Name: new_cases, dtype: float64
8585 8592    5.0
Name: new_cases, dtype: float64
8586 8593    6.0
Name: new_cases, dtype: float64
8587 8594    2.0
Name: new_cases, dtype: float64
8588 8595    5.0
Name: new_cases, dtype: float64
8589 8596    6.0
Name: new_cases, dtype: float64
8590 8597    1.0
Name: new_cases, dtype: float64
8591 8598    6.0
Name: new_cases, dtype: float64
8592 8599    2.0
Name: new_cases, dtype: float64
8593 8600    6.0
Name: new_cases, dtype: float64
8594 8601    4.0
Name: new_cases, dtype: float64
8595 8602    7.0
Name: new_cases, dtype: float64
8596 8603    2.0
Name: new_cases, dtype: float64
8597 8604    8.0
Name: new_cases, dtype: float64
8598 8605    10.0
Name: new_cases, dtype: float64
8599 8606    8.0
Name: new_cases, dtype: float64
8600 8607    5.0
Name: new_cases, dtype: float64
8601 8608    8.0
Name: new_cases, dtype: float64
8602 8609    8.0
Name: new_cases, dtype: float64
8603 8610    10.0
Name: new_cases, dtype: float64
8604 8611    11.0
Name: new_cases, dtype: float64
8605 8612    14.0
Name: new_cases, dtype: float64
8606 8613    8.0
Name: new_cases, dtype: float64
8607 8614    5.0
Name: new_cases, dtype: float64
8608 8615    12.0
Name: new_cases, dtype: float64
8609 8616    15.0
Name: new_cases, dtype: float64
8610 8617    13.0
Name: new_cases, dtype: float64
8611 8618    16.0
Name: new_cases, dtype: float64
8612 8619    12.0
Name: new_cases, dtype: float64
8613 8620    10.0
Name: new_cases, dtype: float64
8614 8621    5.0
Name: new_cases, dtype: float64
8615 8622    13.0
Name: new_cases, dtype: float64
8616 8623    7.0
Name: new_cases, dtype: float64
8617 8624    17.0
Name: new_cases, dtype: float64
8618 8625    12.0
Name: new_cases, dtype: float64
8619 8626    17.0
Name: new_cases, dtype: float64
8620 8627    9.0
Name: new_cases, dtype: float64
8621 8628    4.0
Name: new_cases, dtype: float64
8622 8629    10.0
Name: new_cases, dtype: float64
8623 8630    5.0
Name: new_cases, dtype: float64
8624 8631    10.0
Name: new_cases, dtype: float64
8625 8632    9.0
Name: new_cases, dtype: float64
8626 8633    9.0
Name: new_cases, dtype: float64
8627 8634    13.0
Name: new_cases, dtype: float64
8628 8635    7.0
Name: new_cases, dtype: float64
8629 8636    17.0
Name: new_cases, dtype: float64
8630 8637    20.0
Name: new_cases, dtype: float64
8631 8638    8.0
Name: new_cases, dtype: float64
8632 8639    18.0
Name: new_cases, dtype: float64
8633 8640    11.0
Name: new_cases, dtype: float64
8634 8641    8.0
Name: new_cases, dtype: float64
8635 8642    7.0
Name: new_cases, dtype: float64
8636 8643    9.0
Name: new_cases, dtype: float64
8637 8644    8.0
Name: new_cases, dtype: float64
8638 8645    14.0
Name: new_cases, dtype: float64
8639 8646    6.0
Name: new_cases, dtype: float64
8640 8647    5.0
Name: new_cases, dtype: float64
8641 8648    6.0
Name: new_cases, dtype: float64
8642 8649    9.0
Name: new_cases, dtype: float64
8643 8650    14.0
Name: new_cases, dtype: float64
8644 8651    10.0
Name: new_cases, dtype: float64
8645 8652    21.0
Name: new_cases, dtype: float64
8646 8653    19.0
Name: new_cases, dtype: float64
8647 8654    15.0
Name: new_cases, dtype: float64
8648 8655    15.0
Name: new_cases, dtype: float64
8649 8656    20.0
Name: new_cases, dtype: float64
8650 8657    14.0
Name: new_cases, dtype: float64
8651 8658    23.0
Name: new_cases, dtype: float64
8652 8659    20.0
Name: new_cases, dtype: float64
8653 8660    18.0
Name: new_cases, dtype: float64
8654 8661    44.0
Name: new_cases, dtype: float64
8655 8662    15.0
Name: new_cases, dtype: float64
8656 8663    10.0
Name: new_cases, dtype: float64
8657 8664    17.0
Name: new_cases, dtype: float64
8658 8665    37.0
Name: new_cases, dtype: float64
8659 8666    33.0
Name: new_cases, dtype: float64
8660 8667    23.0
Name: new_cases, dtype: float64
8661 8668    25.0
Name: new_cases, dtype: float64
8662 8669    13.0
Name: new_cases, dtype: float64
8663 8670    13.0
Name: new_cases, dtype: float64
8664 8671    14.0
Name: new_cases, dtype: float64
8665 8672    12.0
Name: new_cases, dtype: float64
8666 8673    15.0
Name: new_cases, dtype: float64
8667 8674    19.0
Name: new_cases, dtype: float64
8668 8675    9.0
Name: new_cases, dtype: float64
8669 8676    13.0
Name: new_cases, dtype: float64
8670 8677    16.0
Name: new_cases, dtype: float64
8671 8678    9.0
Name: new_cases, dtype: float64
8672 8679    7.0
Name: new_cases, dtype: float64
8673 8680    8.0
Name: new_cases, dtype: float64
8674 8681    9.0
Name: new_cases, dtype: float64
8675 8682    2.0
Name: new_cases, dtype: float64
8676 8683    7.0
Name: new_cases, dtype: float64
8677 8684    11.0
Name: new_cases, dtype: float64
8678 8685    3.0
Name: new_cases, dtype: float64
8679 8686    5.0
Name: new_cases, dtype: float64
8680 8687    9.0
Name: new_cases, dtype: float64
8681 8688    3.0
Name: new_cases, dtype: float64
8682 8689    4.0
Name: new_cases, dtype: float64
8683 8690    4.0
Name: new_cases, dtype: float64
8684 8691    4.0
Name: new_cases, dtype: float64
8685 8692    12.0
Name: new_cases, dtype: float64
8686 8693    10.0
Name: new_cases, dtype: float64
8687 8694    17.0
Name: new_cases, dtype: float64
8688 8695    17.0
Name: new_cases, dtype: float64
8689 8696    11.0
Name: new_cases, dtype: float64
8690 8697    9.0
Name: new_cases, dtype: float64
8691 8698    13.0
Name: new_cases, dtype: float64
8692 8699    9.0
Name: new_cases, dtype: float64
8693 8700    13.0
Name: new_cases, dtype: float64
8694 8701    6.0
Name: new_cases, dtype: float64
8695 8702    13.0
Name: new_cases, dtype: float64
8696 8703    4.0
Name: new_cases, dtype: float64

8697 8704    16.0
Name: new_cases, dtype: float64
8698 8705    16.0
Name: new_cases, dtype: float64
8699 8706    18.0
Name: new_cases, dtype: float64
8700 8707    14.0
Name: new_cases, dtype: float64
8701 8708    5.0
Name: new_cases, dtype: float64
8702 8709    15.0
Name: new_cases, dtype: float64
8703 8710    3.0
Name: new_cases, dtype: float64
8704 8711    6.0
Name: new_cases, dtype: float64
8705 8712    14.0
Name: new_cases, dtype: float64
8706 8713    14.0
Name: new_cases, dtype: float64
8707 8714    11.0
Name: new_cases, dtype: float64
8708 8715    13.0
Name: new_cases, dtype: float64
8709 8716    15.0
Name: new_cases, dtype: float64
8710 8717    8.0
Name: new_cases, dtype: float64
8711 8718    13.0
Name: new_cases, dtype: float64
8712 8719    9.0
Name: new_cases, dtype: float64
8713 8720    24.0
Name: new_cases, dtype: float64
8714 8721    11.0
Name: new_cases, dtype: float64
8715 8722    14.0
Name: new_cases, dtype: float64
8716 8723    24.0
Name: new_cases, dtype: float64
8717 8724    20.0
Name: new_cases, dtype: float64
8718 8725    33.0
Name: new_cases, dtype: float64
8719 8726    42.0
Name: new_cases, dtype: float64
8720 8727    29.0
Name: new_cases, dtype: float64
8721 8728    32.0
Name: new_cases, dtype: float64
8722 8729    42.0
Name: new_cases, dtype: float64
8723 8730    41.0
Name: new_cases, dtype: float64
8724 8731    41.0
Name: new_cases, dtype: float64
8725 8732    50.0
Name: new_cases, dtype: float64
8726 8733    19.0
Name: new_cases, dtype: float64
8727 8734    51.0
Name: new_cases, dtype: float64
8728 8735    27.0
Name: new_cases, dtype: float64
8729 8736    30.0
Name: new_cases, dtype: float64
8730 8737    42.0
Name: new_cases, dtype: float64
8731 8738    48.0
Name: new_cases, dtype: float64
8732 8739    64.0
Name: new_cases, dtype: float64
8733 8740    85.0
Name: new_cases, dtype: float64
8734 8741    121.0
Name: new_cases, dtype: float64
8735 8742    102.0
Name: new_cases, dtype: float64
8736 8743    106.0
Name: new_cases, dtype: float64
8737 8744    84.0
Name: new_cases, dtype: float64
8738 8745    113.0
Name: new_cases, dtype: float64
8739 8746    145.0
Name: new_cases, dtype: float64
8740 8747    128.0
Name: new_cases, dtype: float64
8741 8748    117.0
Name: new_cases, dtype: float64
8742 8749    104.0
Name: new_cases, dtype: float64
8743 8750    146.0
Name: new_cases, dtype: float64
8744 8751    160.0
Name: new_cases, dtype: float64
8745 8752    156.0
Name: new_cases, dtype: float64
8746 8753    171.0
Name: new_cases, dtype: float64
8747 8754    165.0
Name: new_cases, dtype: float64
8748 8755    164.0
Name: new_cases, dtype: float64
8749 8756    184.0
Name: new_cases, dtype: float64
8750 8757    207.0
Name: new_cases, dtype: float64
8751 8758    253.0
Name: new_cases, dtype: float64
8752 8759    183.0
Name: new_cases, dtype: float64
8753 8760    221.0
Name: new_cases, dtype: float64
8754 8761    253.0
Name: new_cases, dtype: float64
8755 8762    229.0
Name: new_cases, dtype: float64
8756 8763    224.0
Name: new_cases, dtype: float64
8757 8764    253.0
Name: new_cases, dtype: float64
8758 8765    302.0
Name: new_cases, dtype: float64
8759 8766    307.0
Name: new_cases, dtype: float64
8760 8767    353.0
Name: new_cases, dtype: float64
8761 8768    277.0
Name: new_cases, dtype: float64
8762 8769    302.0
Name: new_cases, dtype: float64
8763 8770    380.0
Name: new_cases, dtype: float64
8764 8771    367.0
Name: new_cases, dtype: float64
8765 8772    372.0
Name: new_cases, dtype: float64
8766 8773    416.0
Name: new_cases, dtype: float64
8767 8774    493.0
Name: new_cases, dtype: float64
8768 8775    439.0
Name: new_cases, dtype: float64
8769 8776    518.0
Name: new_cases, dtype: float64
8770 8777    482.0
Name: new_cases, dtype: float64
8771 8778    677.0
Name: new_cases, dtype: float64
8772 8779    747.0
Name: new_cases, dtype: float64
8773 8780    707.0
Name: new_cases, dtype: float64
8774 8781    891.0
Name: new_cases, dtype: float64
8775 8782    907.0
Name: new_cases, dtype: float64
8776 8783    894.0
Name: new_cases, dtype: float64
8777 8784    834.0
Name: new_cases, dtype: float64
8778 8785    971.0
Name: new_cases, dtype: float64
8779 8786    1115.0
Name: new_cases, dtype: float64
8780 8787    976.0
Name: new_cases, dtype: float64
8781 8788    1119.0
Name: new_cases, dtype: float64
8782 8789    1321.0
Name: new_cases, dtype: float64
8783 8790    1355.0
Name: new_cases, dtype: float64
8784 8791    1257.0
Name: new_cases, dtype: float64
8785 8792    1225.0
Name: new_cases, dtype: float64
8786 8793    1467.0
Name: new_cases, dtype: float64
8787 8794    1648.0
Name: new_cases, dtype: float64
8788 8795    1741.0
Name: new_cases, dtype: float64
8789 8796    1670.0
Name: new_cases, dtype: float64
8790 8797    1536.0
Name: new_cases, dtype: float64
8791 8798    1466.0
Name: new_cases, dtype: float64
8792 8799    1696.0
Name: new_cases, dtype: float64
8793 8800    1725.0
Name: new_cases, dtype: float64
8794 8801    1870.0
Name: new_cases, dtype: float64
8795 8802    2075.0
Name: new_cases, dtype: float64
8796 8803    1616.0
Name: new_cases, dtype: float64
8797 8804    1720.0
Name: new_cases, dtype: float64
8798 8805    1578.0
Name: new_cases, dtype: float64
8799 8806    1643.0
Name: new_cases, dtype: float64
8800 8807    1856.0
Name: new_cases, dtype: float64
8801 8808    1800.0
Name: new_cases, dtype: float64
8802 8809    1856.0
Name: new_cases, dtype: float64
8803 8810    1572.0
Name: new_cases, dtype: float64
8804 8811    1500.0
Name: new_cases, dtype: float64
8805 8812    1582.0
Name: new_cases, dtype: float64
8806 8813    1659.0
Name: new_cases, dtype: float64
8807 8814    1809.0
Name: new_cases, dtype: float64
8808 8815    1764.0
Name: new_cases, dtype: float64
8809 8816    1865.0
Name: new_cases, dtype: float64
8810 8817    1752.0
Name: new_cases, dtype: float64
8811 8818    1472.0
Name: new_cases, dtype: float64
8812 8819    1880.0
Name: new_cases, dtype: float64
8813 8820    1812.0
Name: new_cases, dtype: float64
8814 8821    2400.0
Name: new_cases, dtype: float64
8815 8822    2058.0
Name: new_cases, dtype: float64
8816 8823    2335.0
Name: new_cases, dtype: float64
8817 8824    1872.0
Name: new_cases, dtype: float64
8818 8825    2023.0
Name: new_cases, dtype: float64
8819 8826    2389.0
Name: new_cases, dtype: float64
8820 8827    2026.0
Name: new_cases, dtype: float64
8821 8828    2216.0
Name: new_cases, dtype: float64
8822 8829    2524.0
Name: new_cases, dtype: float64
8823 8830    2515.0
Name: new_cases, dtype: float64
8824 8831    2390.0
Name: new_cases, dtype: float64
8825 8832    2096.0
Name: new_cases, dtype: float64
8826 8833    1848.0
Name: new_cases, dtype: float64
8827 8834    2029.0
Name: new_cases, dtype: float64
8828 8835    2744.0
Name: new_cases, dtype: float64
8829 8836    2532.0
Name: new_cases, dtype: float64
8830 8837    2311.0
Name: new_cases, dtype: float64
8831 8838    2173.0
Name: new_cases, dtype: float64
8832 8839    2059.0
Name: new_cases, dtype: float64
8833 8840    2038.0
Name: new_cases, dtype: float64
8834 8841    2097.0
Name: new_cases, dtype: float64
8835 8842    2544.0
Name: new_cases, dtype: float64
8836 8843    2547.0
Name: new_cases, dtype: float64
8837 8844    1883.0
Name: new_cases, dtype: float64
8838 8845    2174.0
Name: new_cases, dtype: float64
8839 8846    1684.0
Name: new_cases, dtype: float64
8840 8847    1786.0
Name: new_cases, dtype: float64
8841 8848    1850.0
Name: new_cases, dtype: float64
8842 8849    2038.0
Name: new_cases, dtype: float64
8843 8850    1886.0
Name: new_cases, dtype: float64
8844 8851    1589.0
Name: new_cases, dtype: float64
8845 8852    1185.0
Name: new_cases, dtype: float64
8846 8853    1466.0
Name: new_cases, dtype: float64
8847 8854    1135.0
Name: new_cases, dtype: float64
8848 8855    1111.0
Name: new_cases, dtype: float64
8849 8856    1537.0
Name: new_cases, dtype: float64
8850 8857    1580.0
Name: new_cases, dtype: float64
8851 8858    1534.0
Name: new_cases, dtype: float64
8852 8859    1387.0
Name: new_cases, dtype: float64
8853 8860    1264.0
Name: new_cases, dtype: float64
8854 8861    1292.0
Name: new_cases, dtype: float64
8855 8862    1201.0
Name: new_cases, dtype: float64
8856 8863    1556.0
Name: new_cases, dtype: float64
8857 8864    1414.0
Name: new_cases, dtype: float64
8858 8865    1452.0
Name: new_cases, dtype: float64
8859 8866    1115.0
Name: new_cases, dtype: float64
8860 8867    995.0
Name: new_cases, dtype: float64
8861 8868    1014.0
Name: new_cases, dtype: float64
8862 8869    1228.0
Name: new_cases, dtype: float64
8863 8870    1267.0
Name: new_cases, dtype: float64

8864 8871    1505.0
Name: new_cases, dtype: float64
8865 8872    1360.0
Name: new_cases, dtype: float64
8866 8873    1465.0
Name: new_cases, dtype: float64
8867 8874    1207.0
Name: new_cases, dtype: float64
8868 8875    1002.0
Name: new_cases, dtype: float64
8869 8876    1464.0
Name: new_cases, dtype: float64
8870 8877    1527.0
Name: new_cases, dtype: float64
8871 8878    1627.0
Name: new_cases, dtype: float64
8872 8879    1480.0
Name: new_cases, dtype: float64
8873 8880    1235.0
Name: new_cases, dtype: float64
8874 8881    1155.0
Name: new_cases, dtype: float64
8875 8882    1099.0
Name: new_cases, dtype: float64
8876 8883    1417.0
Name: new_cases, dtype: float64
8877 8884    1702.0
Name: new_cases, dtype: float64
8878 8885    1522.0
Name: new_cases, dtype: float64
8879 8886    1708.0
Name: new_cases, dtype: float64
8880 8887    1249.0
Name: new_cases, dtype: float64
8881 8888    1285.0
Name: new_cases, dtype: float64
8882 8889    1434.0
Name: new_cases, dtype: float64
8883 8890    1705.0
Name: new_cases, dtype: float64
8884 8891    1654.0
Name: new_cases, dtype: float64
8885 8892    1711.0
Name: new_cases, dtype: float64
8886 8893    1757.0
Name: new_cases, dtype: float64
8887 8894    1543.0
Name: new_cases, dtype: float64
8888 8895    1843.0
Name: new_cases, dtype: float64
8889 8896    1970.0
Name: new_cases, dtype: float64
8890 8897    2809.0
Name: new_cases, dtype: float64
8891 8898    3423.0
Name: new_cases, dtype: float64
8892 8899    3802.0
Name: new_cases, dtype: float64
8893 8900    4017.0
Name: new_cases, dtype: float64
8894 8901    3862.0
Name: new_cases, dtype: float64
8895 8902    4031.0
Name: new_cases, dtype: float64
8896 8903    4492.0
Name: new_cases, dtype: float64
8897 8904    5531.0
Name: new_cases, dtype: float64
8898 8905    8357.0
Name: new_cases, dtype: float64
8899 8906    8218.0
Name: new_cases, dtype: float64
8900 8907    9855.0
Name: new_cases, dtype: float64
8901 8908    9459.0
Name: new_cases, dtype: float64
8902 8909    9884.0
Name: new_cases, dtype: float64
8903 8910    11797.0
Name: new_cases, dtype: float64
8904 8911    17678.0
Name: new_cases, dtype: float64
8905 8912    21369.0
Name: new_cases, dtype: float64
8906 8913    33811.0
Name: new_cases, dtype: float64
8907 8914    7816.0
Name: new_cases, dtype: float64
8908 8915    60006.0
Name: new_cases, dtype: float64
8909 8916    29608.0
Name: new_cases, dtype: float64
8910 8917    44745.0
Name: new_cases, dtype: float64
8911 8918    71495.0
Name: new_cases, dtype: float64
8912 8919    75426.0
Name: new_cases, dtype: float64
8913 8920    78229.0
Name: new_cases, dtype: float64
8914 8921    98092.0
Name: new_cases, dtype: float64
8915 8922    111907.0
Name: new_cases, dtype: float64
8916 8239    0.0
Name: new_cases, dtype: float64
8917 8240    0.0
Name: new_cases, dtype: float64
8918 8241    0.0
Name: new_cases, dtype: float64
8919 8242    0.0
Name: new_cases, dtype: float64
8920 8243    10.0
Name: new_cases, dtype: float64
8921 8244    2.0
Name: new_cases, dtype: float64
8922 8245    3.0
Name: new_cases, dtype: float64
8923 8930    3.0
Name: new_cases, dtype: float64
8924 8931    8.0
Name: new_cases, dtype: float64
8925 8932    12.0
Name: new_cases, dtype: float64
8926 8933    14.0
Name: new_cases, dtype: float64
8927 8934    24.0
Name: new_cases, dtype: float64
8928 8935    25.0
Name: new_cases, dtype: float64
8929 8936    27.0
Name: new_cases, dtype: float64
8930 8937    51.0
Name: new_cases, dtype: float64
8931 8938    64.0
Name: new_cases, dtype: float64
8932 8939    56.0
Name: new_cases, dtype: float64
8933 8940    202.0
Name: new_cases, dtype: float64
8934 8941    151.0
Name: new_cases, dtype: float64
8935 8942    205.0
Name: new_cases, dtype: float64
8936 8943    158.0
Name: new_cases, dtype: float64
8937 8944    314.0
Name: new_cases, dtype: float64
8938 8945    314.0
Name: new_cases, dtype: float64
8939 8946    367.0
Name: new_cases, dtype: float64
8940 8947    375.0
Name: new_cases, dtype: float64
8941 8948    426.0
Name: new_cases, dtype: float64
8942 8949    768.0
Name: new_cases, dtype: float64
8943 8950    892.0
Name: new_cases, dtype: float64
8944 8951    809.0
Name: new_cases, dtype: float64
8945 8952    305.0
Name: new_cases, dtype: float64
8946 8953    1321.0
Name: new_cases, dtype: float64
8947 8954    748.0
Name: new_cases, dtype: float64
8948 8955    614.0
Name: new_cases, dtype: float64
8949 8956    517.0
Name: new_cases, dtype: float64
8950 8957    830.0
Name: new_cases, dtype: float64
8951 8958    562.0
Name: new_cases, dtype: float64
8952 8959    531.0
Name: new_cases, dtype: float64
8953 8960    418.0
Name: new_cases, dtype: float64
8954 8961    395.0
Name: new_cases, dtype: float64
8955 8962    257.0
Name: new_cases, dtype: float64
8956 8963    270.0
Name: new_cases, dtype: float64
8957 8964    246.0
Name: new_cases, dtype: float64
8958 8965    342.0
Name: new_cases, dtype: float64
8959 8966    303.0
Name: new_cases, dtype: float64
8960 8967    302.0
Name: new_cases, dtype: float64
8961 8968    311.0
Name: new_cases, dtype: float64
8962 8969    251.0
Name: new_cases, dtype: float64
8963 8970    139.0
Name: new_cases, dtype: float64
8964 8971    96.0
Name: new_cases, dtype: float64
8965 8972    185.0
Name: new_cases, dtype: float64
8966 8973    110.0
Name: new_cases, dtype: float64
8967 8974    140.0
Name: new_cases, dtype: float64
8968 8975    119.0
Name: new_cases, dtype: float64
8969 8976    76.0
Name: new_cases, dtype: float64
8970 8977    78.0
Name: new_cases, dtype: float64
8971 8978    46.0
Name: new_cases, dtype: float64
8972 8979    78.0
Name: new_cases, dtype: float64
8973 8980    52.0
Name: new_cases, dtype: float64
8974 8981    77.0
Name: new_cases, dtype: float64
8975 8982    69.0
Name: new_cases, dtype: float64
8976 8983    77.0
Name: new_cases, dtype: float64
8977 8984    77.0
Name: new_cases, dtype: float64
8978 8985    49.0
Name: new_cases, dtype: float64
8979 8986    83.0
Name: new_cases, dtype: float64
8980 8987    45.0
Name: new_cases, dtype: float64
8981 8988    50.0
Name: new_cases, dtype: float64
8982 8989    79.0
Name: new_cases, dtype: float64
8983 8990    27.0
Name: new_cases, dtype: float64
8984 8991    39.0
Name: new_cases, dtype: float64
8985 8992    24.0
Name: new_cases, dtype: float64
8986 8993    29.0
Name: new_cases, dtype: float64
8987 8994    34.0
Name: new_cases, dtype: float64
8988 8995    68.0
Name: new_cases, dtype: float64
8989 8996    22.0
Name: new_cases, dtype: float64
8990 8997    59.0
Name: new_cases, dtype: float64
8991 8998    38.0
Name: new_cases, dtype: float64
8992 8999    11.0
Name: new_cases, dtype: float64
8993 9000    79.0
Name: new_cases, dtype: float64
8994 9001    36.0
Name: new_cases, dtype: float64
8995 9002    61.0
Name: new_cases, dtype: float64
8996 9003    51.0
Name: new_cases, dtype: float64
8997 9004    92.0
Name: new_cases, dtype: float64
8998 9005    41.0
Name: new_cases, dtype: float64
8999 9006    27.0
Name: new_cases, dtype: float64
9000 9007    52.0
Name: new_cases, dtype: float64
9001 9008    32.0
Name: new_cases, dtype: float64
9002 9009    51.0
Name: new_cases, dtype: float64
9003 9010    32.0
Name: new_cases, dtype: float64
9004 9011    50.0
Name: new_cases, dtype: float64
9005 9012    17.0
Name: new_cases, dtype: float64
9006 9013    36.0
Name: new_cases, dtype: float64
9007 9014    18.0
Name: new_cases, dtype: float64
9008 9015    34.0
Name: new_cases, dtype: float64
9009 9016    37.0
Name: new_cases, dtype: float64
9010 9017    27.0
Name: new_cases, dtype: float64
9011 9018    30.0
Name: new_cases, dtype: float64
9012 9019    46.0
Name: new_cases, dtype: float64
9013 9020    2.0
Name: new_cases, dtype: float64
9014 9021    26.0
Name: new_cases, dtype: float64
9015 9022    12.0
Name: new_cases, dtype: float64
9016 9023    34.0
Name: new_cases, dtype: float64
9017 9024    38.0
Name: new_cases, dtype: float64
9018 9025    55.0
Name: new_cases, dtype: float64
9019 9026    4.0
Name: new_cases, dtype: float64
9020 9027    66.0
Name: new_cases, dtype: float64
9021 9028    11.0
Name: new_cases, dtype: float64
9022 9029    26.0
Name: new_cases, dtype: float64
9023 9030    29.0
Name: new_cases, dtype: float64
9024 9031    30.0
Name: new_cases, dtype: float64
9025 9032    14.0
Name: new_cases, dtype: float64
9026 9033    31.0
Name: new_cases, dtype: float64
9027 9034    26.0
Name: new_cases, dtype: float64
9028 9035    54.0
Name: new_cases, dtype: float64
9029 9036    14.0
Name: new_cases, dtype: float64
9030 9037    20.0
Name: new_cases, dtype: float64
9031 9038    48.0
Name: new_cases, dtype: float64

9032 9039    52.0
Name: new_cases, dtype: float64
9033 9040    18.0
Name: new_cases, dtype: float64
9034 9041    39.0
Name: new_cases, dtype: float64
9035 9042    28.0
Name: new_cases, dtype: float64
9036 9043    41.0
Name: new_cases, dtype: float64
9037 9044    28.0
Name: new_cases, dtype: float64
9038 9045    45.0
Name: new_cases, dtype: float64
9039 9046    58.0
Name: new_cases, dtype: float64
9040 9047    74.0
Name: new_cases, dtype: float64
9041 9048    69.0
Name: new_cases, dtype: float64
9042 9049    43.0
Name: new_cases, dtype: float64
9043 9050    107.0
Name: new_cases, dtype: float64
9044 9051    68.0
Name: new_cases, dtype: float64
9045 9052    109.0
Name: new_cases, dtype: float64
9046 9053    115.0
Name: new_cases, dtype: float64
9047 9054    115.0
Name: new_cases, dtype: float64
9048 9055    85.0
Name: new_cases, dtype: float64
9049 9056    56.0
Name: new_cases, dtype: float64
9050 9057    92.0
Name: new_cases, dtype: float64
9051 9058    102.0
Name: new_cases, dtype: float64
9052 9059    94.0
Name: new_cases, dtype: float64
9053 9060    74.0
Name: new_cases, dtype: float64
9054 9061    114.0
Name: new_cases, dtype: float64
9055 9062    51.0
Name: new_cases, dtype: float64
9056 9063    73.0
Name: new_cases, dtype: float64
9057 9064    133.0
Name: new_cases, dtype: float64
9058 9065    116.0
Name: new_cases, dtype: float64
9059 9066    169.0
Name: new_cases, dtype: float64
9060 9067    134.0
Name: new_cases, dtype: float64
9061 9068    82.0
Name: new_cases, dtype: float64
9062 9069    88.0
Name: new_cases, dtype: float64
9063 9070    84.0
Name: new_cases, dtype: float64
9064 9071    102.0
Name: new_cases, dtype: float64
9065 9072    170.0
Name: new_cases, dtype: float64
9066 9073    115.0
Name: new_cases, dtype: float64
9067 9074    124.0
Name: new_cases, dtype: float64
9068 9075    134.0
Name: new_cases, dtype: float64
9069 9076    86.0
Name: new_cases, dtype: float64
9070 9077    119.0
Name: new_cases, dtype: float64
9071 9078    173.0
Name: new_cases, dtype: float64
9072 9079    105.0
Name: new_cases, dtype: float64
9073 9080    175.0
Name: new_cases, dtype: float64
9074 9081    82.0
Name: new_cases, dtype: float64
9075 9082    92.0
Name: new_cases, dtype: float64
9076 9083    81.0
Name: new_cases, dtype: float64
9077 9084    96.0
Name: new_cases, dtype: float64
9078 9085    85.0
Name: new_cases, dtype: float64
9079 9086    130.0
Name: new_cases, dtype: float64
9080 9087    141.0
Name: new_cases, dtype: float64
9081 9088    82.0
Name: new_cases, dtype: float64
9082 9089    114.0
Name: new_cases, dtype: float64
9083 9090    73.0
Name: new_cases, dtype: float64
9084 9091    139.0
Name: new_cases, dtype: float64
9085 9092    194.0
Name: new_cases, dtype: float64
9086 9093    155.0
Name: new_cases, dtype: float64
9087 9094    282.0
Name: new_cases, dtype: float64
9088 9095    303.0
Name: new_cases, dtype: float64
9089 9096    191.0
Name: new_cases, dtype: float64
9090 9097    164.0
Name: new_cases, dtype: float64
9091 9098    295.0
Name: new_cases, dtype: float64
9092 9099    255.0
Name: new_cases, dtype: float64
9093 9100    347.0
Name: new_cases, dtype: float64
9094 9101    331.0
Name: new_cases, dtype: float64
9095 9102    300.0
Name: new_cases, dtype: float64
9096 9103    191.0
Name: new_cases, dtype: float64
9097 9104    242.0
Name: new_cases, dtype: float64
9098 9105    211.0
Name: new_cases, dtype: float64
9099 9106    327.0
Name: new_cases, dtype: float64
9100 9107    328.0
Name: new_cases, dtype: float64
9101 9108    229.0
Name: new_cases, dtype: float64
9102 9109    395.0
Name: new_cases, dtype: float64
9103 9110    181.0
Name: new_cases, dtype: float64
9104 9111    272.0
Name: new_cases, dtype: float64
9105 9112    204.0
Name: new_cases, dtype: float64
9106 9113    327.0
Name: new_cases, dtype: float64
9107 9114    403.0
Name: new_cases, dtype: float64
9108 9115    357.0
Name: new_cases, dtype: float64
9109 9116    358.0
Name: new_cases, dtype: float64
9110 9117    184.0
Name: new_cases, dtype: float64
9111 9118    290.0
Name: new_cases, dtype: float64
9112 9119    520.0
Name: new_cases, dtype: float64
9113 9120    502.0
Name: new_cases, dtype: float64
9114 9121    664.0
Name: new_cases, dtype: float64
9115 9122    580.0
Name: new_cases, dtype: float64
9116 9123    869.0
Name: new_cases, dtype: float64
9117 9124    463.0
Name: new_cases, dtype: float64
9118 9125    382.0
Name: new_cases, dtype: float64
9119 9126    764.0
Name: new_cases, dtype: float64
9120 9127    768.0
Name: new_cases, dtype: float64
9121 9128    780.0
Name: new_cases, dtype: float64
9122 9129    808.0
Name: new_cases, dtype: float64
9123 9130    813.0
Name: new_cases, dtype: float64
9124 9131    621.0
Name: new_cases, dtype: float64
9125 9132    563.0
Name: new_cases, dtype: float64
9126 9133    645.0
Name: new_cases, dtype: float64
9127 9134    681.0
Name: new_cases, dtype: float64
9128 9135    832.0
Name: new_cases, dtype: float64
9129 9136    684.0
Name: new_cases, dtype: float64
9130 9137    714.0
Name: new_cases, dtype: float64
9131 9138    662.0
Name: new_cases, dtype: float64
9132 9139    556.0
Name: new_cases, dtype: float64
9133 9140    609.0
Name: new_cases, dtype: float64
9134 9141    772.0
Name: new_cases, dtype: float64
9135 9142    873.0
Name: new_cases, dtype: float64
9136 9143    688.0
Name: new_cases, dtype: float64
9137 9144    1058.0
Name: new_cases, dtype: float64
9138 9145    714.0
Name: new_cases, dtype: float64
9139 9146    750.0
Name: new_cases, dtype: float64
9140 9147    923.0
Name: new_cases, dtype: float64
9141 9148    1029.0
Name: new_cases, dtype: float64
9142 9149    1209.0
Name: new_cases, dtype: float64
9143 9150    1131.0
Name: new_cases, dtype: float64
9144 9151    1235.0
Name: new_cases, dtype: float64
9145 9152    896.0
Name: new_cases, dtype: float64
9146 9153    979.0
Name: new_cases, dtype: float64
9147 9154    1028.0
Name: new_cases, dtype: float64
9148 9155    1346.0
Name: new_cases, dtype: float64
9149 9156    1552.0
Name: new_cases, dtype: float64
9150 9157    1163.0
Name: new_cases, dtype: float64
9151 9158    1747.0
Name: new_cases, dtype: float64
9152 9159    1672.0
Name: new_cases, dtype: float64
9153 9160    1121.0
Name: new_cases, dtype: float64
9154 9161    1524.0
Name: new_cases, dtype: float64
9155 9162    1958.0
Name: new_cases, dtype: float64
9156 9163    2435.0
Name: new_cases, dtype: float64
9157 9164    2571.0
Name: new_cases, dtype: float64
9158 9165    3614.0
Name: new_cases, dtype: float64
9159 9166    2782.0
Name: new_cases, dtype: float64
9160 9167    2456.0
Name: new_cases, dtype: float64
9161 9168    2835.0
Name: new_cases, dtype: float64
9162 9169    3394.0
Name: new_cases, dtype: float64
9163 9170    4453.0
Name: new_cases, dtype: float64
9164 9171    5627.0
Name: new_cases, dtype: float64
9165 9172    5349.0
Name: new_cases, dtype: float64
9166 9173    4956.0
Name: new_cases, dtype: float64
9167 9174    4135.0
Name: new_cases, dtype: float64
9168 9175    4182.0
Name: new_cases, dtype: float64
9169 9176    6901.0
Name: new_cases, dtype: float64
9170 9177    7416.0
Name: new_cases, dtype: float64
9171 9178    6464.0
Name: new_cases, dtype: float64
9172 9179    8241.0
Name: new_cases, dtype: float64
9173 9180    5933.0
Name: new_cases, dtype: float64
9174 9181    5593.0
Name: new_cases, dtype: float64
9175 9182    6120.0
Name: new_cases, dtype: float64
9176 9183    7514.0
Name: new_cases, dtype: float64
9177 9184    9262.0
Name: new_cases, dtype: float64
9178 9185    9586.0
Name: new_cases, dtype: float64
9179 9186    7063.0
Name: new_cases, dtype: float64
9180 9187    5665.0
Name: new_cases, dtype: float64
9181 9188    4657.0
Name: new_cases, dtype: float64
9182 9189    5984.0
Name: new_cases, dtype: float64
9183 9190    7091.0
Name: new_cases, dtype: float64
9184 9191    6995.0
Name: new_cases, dtype: float64
9185 9192    6668.0
Name: new_cases, dtype: float64
9186 9193    6611.0
Name: new_cases, dtype: float64
9187 9194    5226.0
Name: new_cases, dtype: float64
9188 9195    3145.0
Name: new_cases, dtype: float64
9189 9196    4377.0
Name: new_cases, dtype: float64
9190 9197    5802.0
Name: new_cases, dtype: float64
9191 9198    5526.0
Name: new_cases, dtype: float64
9192 9199    4954.0
Name: new_cases, dtype: float64
9193 9200    4669.0
Name: new_cases, dtype: float64
9194 9201    4047.0
Name: new_cases, dtype: float64
9195 9202    2748.0
Name: new_cases, dtype: float64
9196 9203    3033.0
Name: new_cases, dtype: float64

9197 9204    3972.0
Name: new_cases, dtype: float64
9198 9205    3969.0
Name: new_cases, dtype: float64
9199 9206    3815.0
Name: new_cases, dtype: float64
9200 9207    3444.0
Name: new_cases, dtype: float64
9201 9208    2741.0
Name: new_cases, dtype: float64
9202 9209    2263.0
Name: new_cases, dtype: float64
9203 9210    2377.0
Name: new_cases, dtype: float64
9204 9211    2932.0
Name: new_cases, dtype: float64
9205 9212    2686.0
Name: new_cases, dtype: float64
9206 9213    2893.0
Name: new_cases, dtype: float64
9207 9214    3241.0
Name: new_cases, dtype: float64
9208 9215    2641.0
Name: new_cases, dtype: float64
9209 9216    2588.0
Name: new_cases, dtype: float64
9210 9217    2628.0
Name: new_cases, dtype: float64
9211 9218    2664.0
Name: new_cases, dtype: float64
9212 9219    2485.0
Name: new_cases, dtype: float64
9213 9220    2085.0
Name: new_cases, dtype: float64
9214 9221    2296.0
Name: new_cases, dtype: float64
9215 9222    1645.0
Name: new_cases, dtype: float64
9216 9223    1519.0
Name: new_cases, dtype: float64
9217 9224    1853.0
Name: new_cases, dtype: float64
9218 9225    2131.0
Name: new_cases, dtype: float64
9219 9226    2847.0
Name: new_cases, dtype: float64
9220 9227    1851.0
Name: new_cases, dtype: float64
9221 9228    1429.0
Name: new_cases, dtype: float64
9222 9229    1408.0
Name: new_cases, dtype: float64
9223 9230    1592.0
Name: new_cases, dtype: float64
9224 9231    1868.0
Name: new_cases, dtype: float64
9225 9232    2550.0
Name: new_cases, dtype: float64
9226 9233    2913.0
Name: new_cases, dtype: float64
9227 9234    2096.0
Name: new_cases, dtype: float64
9228 9235    1391.0
Name: new_cases, dtype: float64
9229 9236    1466.0
Name: new_cases, dtype: float64
9230 9237    1642.0
Name: new_cases, dtype: float64
9231 9238    2311.0
Name: new_cases, dtype: float64
9232 9239    2469.0
Name: new_cases, dtype: float64
9233 9240    2540.0
Name: new_cases, dtype: float64
9234 9241    2063.0
Name: new_cases, dtype: float64
9235 9242    2278.0
Name: new_cases, dtype: float64
9236 9243    1651.0
Name: new_cases, dtype: float64
9237 9244    1536.0
Name: new_cases, dtype: float64
9238 9245    1575.0
Name: new_cases, dtype: float64
9239 9246    1917.0
Name: new_cases, dtype: float64
9240 9247    3510.0
Name: new_cases, dtype: float64
9241 9248    1528.0
Name: new_cases, dtype: float64
9242 9249    1723.0
Name: new_cases, dtype: float64
9243 9250    1267.0
Name: new_cases, dtype: float64
9244 9251    1161.0
Name: new_cases, dtype: float64
9245 9252    1486.0
Name: new_cases, dtype: float64
9246 9253    1671.0
Name: new_cases, dtype: float64
9247 9254    1702.0
Name: new_cases, dtype: float64
9248 9255    2088.0
Name: new_cases, dtype: float64
9249 9256    1626.0
Name: new_cases, dtype: float64
9250 9257    1202.0
Name: new_cases, dtype: float64
9251 9258    1009.0
Name: new_cases, dtype: float64
9252 9259    1417.0
Name: new_cases, dtype: float64
9253 9260    1641.0
Name: new_cases, dtype: float64
9254 9261    1449.0
Name: new_cases, dtype: float64
9255 9262    1500.0
Name: new_cases, dtype: float64
9256 9263    1478.0
Name: new_cases, dtype: float64
9257 9264    1190.0
Name: new_cases, dtype: float64
9258 9265    1124.0
Name: new_cases, dtype: float64
9259 9266    1241.0
Name: new_cases, dtype: float64
9260 9267    1520.0
Name: new_cases, dtype: float64
9261 9268    1518.0
Name: new_cases, dtype: float64
9262 9269    1388.0
Name: new_cases, dtype: float64
9263 9270    1333.0
Name: new_cases, dtype: float64
9264 9271    1317.0
Name: new_cases, dtype: float64
9265 9272    1057.0
Name: new_cases, dtype: float64
9266 9273    1197.0
Name: new_cases, dtype: float64
9267 9274    1469.0
Name: new_cases, dtype: float64
9268 9275    1577.0
Name: new_cases, dtype: float64
9269 9276    1731.0
Name: new_cases, dtype: float64
9270 9277    1433.0
Name: new_cases, dtype: float64
9271 9278    1184.0
Name: new_cases, dtype: float64
9272 9279    1225.0
Name: new_cases, dtype: float64
9273 9280    1427.0
Name: new_cases, dtype: float64
9274 9281    1735.0
Name: new_cases, dtype: float64
9275 9282    1967.0
Name: new_cases, dtype: float64
9276 9283    1818.0
Name: new_cases, dtype: float64
9277 9284    1877.0
Name: new_cases, dtype: float64
9278 9285    1838.0
Name: new_cases, dtype: float64
9279 9286    1270.0
Name: new_cases, dtype: float64
9280 9287    1727.0
Name: new_cases, dtype: float64
9281 9288    2005.0
Name: new_cases, dtype: float64
9282 9289    2391.0
Name: new_cases, dtype: float64
9283 9290    2093.0
Name: new_cases, dtype: float64
9284 9291    2457.0
Name: new_cases, dtype: float64
9285 9292    2123.0
Name: new_cases, dtype: float64
9286 9293    1409.0
Name: new_cases, dtype: float64
9287 9294    1920.0
Name: new_cases, dtype: float64
9288 9295    2553.0
Name: new_cases, dtype: float64
9289 9296    2324.0
Name: new_cases, dtype: float64
9290 9297    2668.0
Name: new_cases, dtype: float64
9291 9298    2557.0
Name: new_cases, dtype: float64
9292 9299    2199.0
Name: new_cases, dtype: float64
9293 9300    1910.0
Name: new_cases, dtype: float64
9294 9301    2411.0
Name: new_cases, dtype: float64
9295 9302    2528.0
Name: new_cases, dtype: float64
9296 9303    2997.0
Name: new_cases, dtype: float64
9297 9304    3126.0
Name: new_cases, dtype: float64
9298 9305    3023.0
Name: new_cases, dtype: float64
9299 9306    2503.0
Name: new_cases, dtype: float64
9300 9307    1896.0
Name: new_cases, dtype: float64
9301 9308    2425.0
Name: new_cases, dtype: float64
9302 9309    3335.0
Name: new_cases, dtype: float64
9303 9310    3357.0
Name: new_cases, dtype: float64
9304 9311    3515.0
Name: new_cases, dtype: float64
9305 9312    3344.0
Name: new_cases, dtype: float64
9306 9313    2713.0
Name: new_cases, dtype: float64
9307 9314    2412.0
Name: new_cases, dtype: float64
9308 9315    3415.0
Name: new_cases, dtype: float64
9309 9316    3289.0
Name: new_cases, dtype: float64
9310 9317    3124.0
Name: new_cases, dtype: float64
9311 9318    3895.0
Name: new_cases, dtype: float64
9312 9319    3498.0
Name: new_cases, dtype: float64
9313 9320    2679.0
Name: new_cases, dtype: float64
9314 9321    3076.0
Name: new_cases, dtype: float64
9315 9322    3001.0
Name: new_cases, dtype: float64
9316 9323    3687.0
Name: new_cases, dtype: float64
9317 9324    3363.0
Name: new_cases, dtype: float64
9318 9325    3137.0
Name: new_cases, dtype: float64
9319 9326    3283.0
Name: new_cases, dtype: float64
9320 9327    2743.0
Name: new_cases, dtype: float64
9321 9328    2217.0
Name: new_cases, dtype: float64
9322 9329    1935.0
Name: new_cases, dtype: float64
9323 9330    3101.0
Name: new_cases, dtype: float64
9324 9331    2906.0
Name: new_cases, dtype: float64
9325 9332    2702.0
Name: new_cases, dtype: float64
9326 9333    3139.0
Name: new_cases, dtype: float64
9327 9334    2252.0
Name: new_cases, dtype: float64
9328 9335    1943.0
Name: new_cases, dtype: float64
9329 9336    2313.0
Name: new_cases, dtype: float64
9330 9337    2942.0
Name: new_cases, dtype: float64
9331 9338    2678.0
Name: new_cases, dtype: float64
9332 9339    2416.0
Name: new_cases, dtype: float64
9333 9340    2048.0
Name: new_cases, dtype: float64
9334 9341    2076.0
Name: new_cases, dtype: float64
9335 9342    2117.0
Name: new_cases, dtype: float64
9336 9343    2026.0
Name: new_cases, dtype: float64
9337 9344    2523.0
Name: new_cases, dtype: float64
9338 9345    2405.0
Name: new_cases, dtype: float64
9339 9346    2329.0
Name: new_cases, dtype: float64
9340 9347    2131.0
Name: new_cases, dtype: float64
9341 9348    2025.0
Name: new_cases, dtype: float64
9342 9349    1566.0
Name: new_cases, dtype: float64
9343 9350    1625.0
Name: new_cases, dtype: float64
9344 9351    2340.0
Name: new_cases, dtype: float64
9345 9352    2229.0
Name: new_cases, dtype: float64
9346 9353    2131.0
Name: new_cases, dtype: float64
9347 9354    1615.0
Name: new_cases, dtype: float64
9348 9355    1625.0
Name: new_cases, dtype: float64
9349 9356    1091.0
Name: new_cases, dtype: float64
9350 9357    1394.0
Name: new_cases, dtype: float64
9351 9358    1644.0
Name: new_cases, dtype: float64
9352 9359    1245.0
Name: new_cases, dtype: float64
9353 9360    1333.0
Name: new_cases, dtype: float64
9354 9361    1233.0
Name: new_cases, dtype: float64
9355 9362    1026.0
Name: new_cases, dtype: float64
9356 9363    820.0
Name: new_cases, dtype: float64
9357 9364    870.0
Name: new_cases, dtype: float64
9358 9365    1194.0
Name: new_cases, dtype: float64
9359 9366    933.0
Name: new_cases, dtype: float64
9360 9367    887.0
Name: new_cases, dtype: float64
9361 9368    644.0
Name: new_cases, dtype: float64
9362 9369    673.0
Name: new_cases, dtype: float64
9363 9370    476.0
Name: new_cases, dtype: float64
9364 9371    582.0
Name: new_cases, dtype: float64
9365 9372    899.0
Name: new_cases, dtype: float64
9366 9373    562.0
Name: new_cases, dtype: float64
9367 9374    677.0
Name: new_cases, dtype: float64
9368 9375    583.0
Name: new_cases, dtype: float64
9369 9376    504.0
Name: new_cases, dtype: float64
9370 9377    360.0
Name: new_cases, dtype: float64
9371 9378    398.0
Name: new_cases, dtype: float64
9372 9379    445.0
Name: new_cases, dtype: float64
9373 9380    585.0
Name: new_cases, dtype: float64
9374 9381    541.0
Name: new_cases, dtype: float64
9375 9382    498.0
Name: new_cases, dtype: float64

9376 9383    379.0
Name: new_cases, dtype: float64
9377 9384    229.0
Name: new_cases, dtype: float64
9378 9385    337.0
Name: new_cases, dtype: float64
9379 9386    400.0
Name: new_cases, dtype: float64
9380 9387    282.0
Name: new_cases, dtype: float64
9381 9388    333.0
Name: new_cases, dtype: float64
9382 9389    271.0
Name: new_cases, dtype: float64
9383 9390    362.0
Name: new_cases, dtype: float64
9384 9391    279.0
Name: new_cases, dtype: float64
9385 9392    243.0
Name: new_cases, dtype: float64
9386 9393    366.0
Name: new_cases, dtype: float64
9387 9394    283.0
Name: new_cases, dtype: float64
9388 9395    216.0
Name: new_cases, dtype: float64
9389 9396    200.0
Name: new_cases, dtype: float64
9390 9397    233.0
Name: new_cases, dtype: float64
9391 9398    112.0
Name: new_cases, dtype: float64
9392 9399    117.0
Name: new_cases, dtype: float64
9393 9400    153.0
Name: new_cases, dtype: float64
9394 9401    179.0
Name: new_cases, dtype: float64
9395 9402    128.0
Name: new_cases, dtype: float64
9396 9403    136.0
Name: new_cases, dtype: float64
9397 9404    131.0
Name: new_cases, dtype: float64
9398 9405    94.0
Name: new_cases, dtype: float64
9399 9406    58.0
Name: new_cases, dtype: float64
9400 9407    117.0
Name: new_cases, dtype: float64
9401 9408    77.0
Name: new_cases, dtype: float64
9402 9409    94.0
Name: new_cases, dtype: float64
9403 9410    176.0
Name: new_cases, dtype: float64
9404 9411    69.0
Name: new_cases, dtype: float64
9405 9412    63.0
Name: new_cases, dtype: float64
9406 9413    29.0
Name: new_cases, dtype: float64
9407 9414    59.0
Name: new_cases, dtype: float64
9408 9415    62.0
Name: new_cases, dtype: float64
9409 9416    95.0
Name: new_cases, dtype: float64
9410 9417    93.0
Name: new_cases, dtype: float64
9411 9418    75.0
Name: new_cases, dtype: float64
9412 9419    80.0
Name: new_cases, dtype: float64
9413 9420    84.0
Name: new_cases, dtype: float64
9414 9421    107.0
Name: new_cases, dtype: float64
9415 9422    120.0
Name: new_cases, dtype: float64
9416 9423    163.0
Name: new_cases, dtype: float64
9417 9424    162.0
Name: new_cases, dtype: float64
9418 9425    159.0
Name: new_cases, dtype: float64
9419 9426    192.0
Name: new_cases, dtype: float64
9420 9427    218.0
Name: new_cases, dtype: float64
9421 9428    332.0
Name: new_cases, dtype: float64
9422 9429    306.0
Name: new_cases, dtype: float64
9423 9430    341.0
Name: new_cases, dtype: float64
9424 9431    411.0
Name: new_cases, dtype: float64
9425 9432    323.0
Name: new_cases, dtype: float64
9426 9433    263.0
Name: new_cases, dtype: float64
9427 9434    316.0
Name: new_cases, dtype: float64
9428 9435    431.0
Name: new_cases, dtype: float64
9429 9436    452.0
Name: new_cases, dtype: float64
9430 9437    392.0
Name: new_cases, dtype: float64
9431 9438    349.0
Name: new_cases, dtype: float64
9432 9439    332.0
Name: new_cases, dtype: float64
9433 9440    312.0
Name: new_cases, dtype: float64
9434 9441    367.0
Name: new_cases, dtype: float64
9435 9442    552.0
Name: new_cases, dtype: float64
9436 9443    503.0
Name: new_cases, dtype: float64
9437 9444    514.0
Name: new_cases, dtype: float64
9438 9445    538.0
Name: new_cases, dtype: float64
9439 9446    452.0
Name: new_cases, dtype: float64
9440 9447    364.0
Name: new_cases, dtype: float64
9441 9448    390.0
Name: new_cases, dtype: float64
9442 9449    592.0
Name: new_cases, dtype: float64
9443 9450    505.0
Name: new_cases, dtype: float64
9444 9451    563.0
Name: new_cases, dtype: float64
9445 9452    607.0
Name: new_cases, dtype: float64
9446 9453    553.0
Name: new_cases, dtype: float64
9447 9454    450.0
Name: new_cases, dtype: float64
9448 9455    601.0
Name: new_cases, dtype: float64
9449 9456    902.0
Name: new_cases, dtype: float64
9450 9457    850.0
Name: new_cases, dtype: float64
9451 9458    1005.0
Name: new_cases, dtype: float64
9452 9459    951.0
Name: new_cases, dtype: float64
9453 9460    891.0
Name: new_cases, dtype: float64
9454 9461    774.0
Name: new_cases, dtype: float64
9455 9462    866.0
Name: new_cases, dtype: float64
9456 9463    1221.0
Name: new_cases, dtype: float64
9457 9464    1226.0
Name: new_cases, dtype: float64
9458 9465    1258.0
Name: new_cases, dtype: float64
9459 9466    1328.0
Name: new_cases, dtype: float64
9460 9467    1121.0
Name: new_cases, dtype: float64
9461 9468    1077.0
Name: new_cases, dtype: float64
9462 9469    1002.0
Name: new_cases, dtype: float64
9463 9470    1574.0
Name: new_cases, dtype: float64
9464 9471    1438.0
Name: new_cases, dtype: float64
9465 9472    1602.0
Name: new_cases, dtype: float64
9466 9473    1322.0
Name: new_cases, dtype: float64
9467 9474    1415.0
Name: new_cases, dtype: float64
9468 9475    1120.0
Name: new_cases, dtype: float64
9469 9476    1229.0
Name: new_cases, dtype: float64
9470 9477    1848.0
Name: new_cases, dtype: float64
9471 9478    1510.0
Name: new_cases, dtype: float64
9472 9479    1753.0
Name: new_cases, dtype: float64
9473 9480    1715.0
Name: new_cases, dtype: float64
9474 9481    1774.0
Name: new_cases, dtype: float64
9475 9482    605.0
Name: new_cases, dtype: float64
9476 9483    1438.0
Name: new_cases, dtype: float64
9477 9484    2268.0
Name: new_cases, dtype: float64
9478 9485    2356.0
Name: new_cases, dtype: float64
9479 9486    2341.0
Name: new_cases, dtype: float64
9480 9487    2260.0
Name: new_cases, dtype: float64
9481 9488    1857.0
Name: new_cases, dtype: float64
9482 9489    1543.0
Name: new_cases, dtype: float64
9483 9490    1696.0
Name: new_cases, dtype: float64
9484 9491    2624.0
Name: new_cases, dtype: float64
9485 9492    2198.0
Name: new_cases, dtype: float64
9486 9493    2364.0
Name: new_cases, dtype: float64
9487 9494    1902.0
Name: new_cases, dtype: float64
9488 9495    1678.0
Name: new_cases, dtype: float64
9489 9496    1399.0
Name: new_cases, dtype: float64
9490 9497    1240.0
Name: new_cases, dtype: float64
9491 9498    2022.0
Name: new_cases, dtype: float64
9492 9499    1707.0
Name: new_cases, dtype: float64
9493 9500    1754.0
Name: new_cases, dtype: float64
9494 9501    2145.0
Name: new_cases, dtype: float64
9495 9502    1588.0
Name: new_cases, dtype: float64
9496 9503    1312.0
Name: new_cases, dtype: float64
9497 9504    1561.0
Name: new_cases, dtype: float64
9498 9505    2283.0
Name: new_cases, dtype: float64
9499 9506    2049.0
Name: new_cases, dtype: float64
9500 9507    1869.0
Name: new_cases, dtype: float64
9501 9508    1416.0
Name: new_cases, dtype: float64
9502 9509    2445.0
Name: new_cases, dtype: float64
9503 9510    1404.0
Name: new_cases, dtype: float64
9504 9511    910.0
Name: new_cases, dtype: float64
9505 9512    2693.0
Name: new_cases, dtype: float64
9506 9513    1965.0
Name: new_cases, dtype: float64
9507 9514    1878.0
Name: new_cases, dtype: float64
9508 9515    1868.0
Name: new_cases, dtype: float64
9509 9516    1675.0
Name: new_cases, dtype: float64
9510 9517    1320.0
Name: new_cases, dtype: float64
9511 9518    1390.0
Name: new_cases, dtype: float64
9512 9519    2614.0
Name: new_cases, dtype: float64
9513 9520    2169.0
Name: new_cases, dtype: float64
9514 9521    2432.0
Name: new_cases, dtype: float64
9515 9522    2397.0
Name: new_cases, dtype: float64
9516 9523    2242.0
Name: new_cases, dtype: float64
9517 9524    1897.0
Name: new_cases, dtype: float64
9518 9525    2590.0
Name: new_cases, dtype: float64
9519 9526    3727.0
Name: new_cases, dtype: float64
9520 9527    3648.0
Name: new_cases, dtype: float64
9521 9528    3582.0
Name: new_cases, dtype: float64
9522 9529    3756.0
Name: new_cases, dtype: float64
9523 9530    3624.0
Name: new_cases, dtype: float64
9524 9531    2850.0
Name: new_cases, dtype: float64
9525 9532    3369.0
Name: new_cases, dtype: float64
9526 9533    4261.0
Name: new_cases, dtype: float64
9527 9534    4248.0
Name: new_cases, dtype: float64
9528 9535    5861.0
Name: new_cases, dtype: float64
9529 9536    6102.0
Name: new_cases, dtype: float64
9530 9537    5684.0
Name: new_cases, dtype: float64
9531 9538    4523.0
Name: new_cases, dtype: float64
9532 9539    5398.0
Name: new_cases, dtype: float64
9533 9540    6506.0
Name: new_cases, dtype: float64
9534 9541    8594.0
Name: new_cases, dtype: float64
9535 9542    9388.0
Name: new_cases, dtype: float64
9536 9543    9943.0
Name: new_cases, dtype: float64
9537 9544    8554.0
Name: new_cases, dtype: float64
9538 9545    8178.0
Name: new_cases, dtype: float64
9539 9546    7712.0
Name: new_cases, dtype: float64
9540 9547    11398.0
Name: new_cases, dtype: float64
9541 9548    11975.0
Name: new_cases, dtype: float64
9542 9549    11798.0
Name: new_cases, dtype: float64
9543 9550    13152.0
Name: new_cases, dtype: float64
9544 9551    11552.0
Name: new_cases, dtype: float64
9545 9552    11889.0
Name: new_cases, dtype: float64
9546 9553    10363.0
Name: new_cases, dtype: float64
9547 9554    14416.0
Name: new_cases, dtype: float64
9548 9555    15145.0
Name: new_cases, dtype: float64
9549 9556    15809.0
Name: new_cases, dtype: float64
9550 9557    15297.0
Name: new_cases, dtype: float64
9551 9558    14042.0
Name: new_cases, dtype: float64
9552 9559    13806.0
Name: new_cases, dtype: float64
9553 9560    9513.0
Name: new_cases, dtype: float64
9554 9561    15365.0
Name: new_cases, dtype: float64
9555 9562    13592.0
Name: new_cases, dtype: float64

9556 9563    12245.0
Name: new_cases, dtype: float64
9557 9564    11671.0
Name: new_cases, dtype: float64
9558 9565    10478.0
Name: new_cases, dtype: float64
9559 9566    8526.0
Name: new_cases, dtype: float64
9560 9567    8186.0
Name: new_cases, dtype: float64
9561 9568    10367.0
Name: new_cases, dtype: float64
9562 9569    8882.0
Name: new_cases, dtype: float64
9563 9570    6738.0
Name: new_cases, dtype: float64
9564 9571    7304.0
Name: new_cases, dtype: float64
9565 9572    5192.0
Name: new_cases, dtype: float64
9566 9573    4625.0
Name: new_cases, dtype: float64
9567 9574    4233.0
Name: new_cases, dtype: float64
9568 9575    5663.0
Name: new_cases, dtype: float64
9569 9576    4437.0
Name: new_cases, dtype: float64
9570 9577    3659.0
Name: new_cases, dtype: float64
9571 9578    4460.0
Name: new_cases, dtype: float64
9572 9579    2479.0
Name: new_cases, dtype: float64
9573 9580    4170.0
Name: new_cases, dtype: float64
9574 9581    2859.0
Name: new_cases, dtype: float64
9575 9582    4224.0
Name: new_cases, dtype: float64
9576 9583    3046.0
Name: new_cases, dtype: float64
9577 9584    2899.0
Name: new_cases, dtype: float64
9578 9585    2167.0
Name: new_cases, dtype: float64
9579 9586    2242.0
Name: new_cases, dtype: float64
9580 9587    1792.0
Name: new_cases, dtype: float64
9581 9588    2528.0
Name: new_cases, dtype: float64
9582 9589    2269.0
Name: new_cases, dtype: float64
9583 9590    2147.0
Name: new_cases, dtype: float64
9584 9591    2374.0
Name: new_cases, dtype: float64
9585 9592    2085.0
Name: new_cases, dtype: float64
9586 9593    1717.0
Name: new_cases, dtype: float64
9587 9594    1550.0
Name: new_cases, dtype: float64
9588 9595    2416.0
Name: new_cases, dtype: float64
9589 9596    3251.0
Name: new_cases, dtype: float64
9590 9597    3225.0
Name: new_cases, dtype: float64
9591 9598    3624.0
Name: new_cases, dtype: float64
9592 9599    3608.0
Name: new_cases, dtype: float64
9593 9600    3283.0
Name: new_cases, dtype: float64
9594 9601    3319.0
Name: new_cases, dtype: float64
9595 9602    5496.0
Name: new_cases, dtype: float64
9596 9603    9761.0
Name: new_cases, dtype: float64
9597 9604    8853.0
Name: new_cases, dtype: float64
9598 9605    8786.0
Name: new_cases, dtype: float64
9599 9606    7405.0
Name: new_cases, dtype: float64
9600 8935    25.0
Name: new_cases, dtype: float64
9601 8936    27.0
Name: new_cases, dtype: float64
9602 8937    51.0
Name: new_cases, dtype: float64
9603 8938    64.0
Name: new_cases, dtype: float64
9604 8939    56.0
Name: new_cases, dtype: float64
9605 8940    202.0
Name: new_cases, dtype: float64
9606 8941    151.0
Name: new_cases, dtype: float64
11640 11647    2.0
Name: new_cases, dtype: float64
11641 11648    3.0
Name: new_cases, dtype: float64
11642 11649    2.0
Name: new_cases, dtype: float64
11643 11650    4.0
Name: new_cases, dtype: float64
11644 11651    3.0
Name: new_cases, dtype: float64
11645 11652    3.0
Name: new_cases, dtype: float64
11646 11653    5.0
Name: new_cases, dtype: float64
11647 11654    2.0
Name: new_cases, dtype: float64
11648 11655    6.0
Name: new_cases, dtype: float64
11649 11656    6.0
Name: new_cases, dtype: float64
11650 11657    0.0
Name: new_cases, dtype: float64
11651 11658    5.0
Name: new_cases, dtype: float64
11652 11659    4.0
Name: new_cases, dtype: float64
11653 11660    0.0
Name: new_cases, dtype: float64
11654 11661    0.0
Name: new_cases, dtype: float64
11655 11662    1.0
Name: new_cases, dtype: float64
11656 11663    2.0
Name: new_cases, dtype: float64
11657 11664    3.0
Name: new_cases, dtype: float64
11658 11665    2.0
Name: new_cases, dtype: float64
11659 11666    5.0
Name: new_cases, dtype: float64
11660 11667    9.0
Name: new_cases, dtype: float64
11661 11668    18.0
Name: new_cases, dtype: float64
11662 11669    35.0
Name: new_cases, dtype: float64
11663 11670    41.0
Name: new_cases, dtype: float64
11664 11671    54.0
Name: new_cases, dtype: float64
11665 11672    112.0
Name: new_cases, dtype: float64
11666 11673    94.0
Name: new_cases, dtype: float64
11667 11674    58.0
Name: new_cases, dtype: float64
11668 11675    139.0
Name: new_cases, dtype: float64
11669 11676    182.0
Name: new_cases, dtype: float64
11670 11677    209.0
Name: new_cases, dtype: float64
11671 11678    219.0
Name: new_cases, dtype: float64
11672 11679    341.0
Name: new_cases, dtype: float64
11673 11680    266.0
Name: new_cases, dtype: float64
11674 11681    306.0
Name: new_cases, dtype: float64
11675 11682    312.0
Name: new_cases, dtype: float64
11676 11683    492.0
Name: new_cases, dtype: float64
11677 11684    434.0
Name: new_cases, dtype: float64
11678 11685    390.0
Name: new_cases, dtype: float64
11679 11686    414.0
Name: new_cases, dtype: float64
11680 11687    503.0
Name: new_cases, dtype: float64
11681 11688    309.0
Name: new_cases, dtype: float64
11682 11689    418.0
Name: new_cases, dtype: float64
11683 11690    497.0
Name: new_cases, dtype: float64
11684 11691    549.0
Name: new_cases, dtype: float64
11685 11692    641.0
Name: new_cases, dtype: float64
11686 11693    564.0
Name: new_cases, dtype: float64
11687 11694    571.0
Name: new_cases, dtype: float64
11688 11695    552.0
Name: new_cases, dtype: float64
11689 11696    665.0
Name: new_cases, dtype: float64
11690 11697    688.0
Name: new_cases, dtype: float64
11691 11698    786.0
Name: new_cases, dtype: float64
11692 11699    790.0
Name: new_cases, dtype: float64
11693 11700    706.0
Name: new_cases, dtype: float64
11694 11701    709.0
Name: new_cases, dtype: float64
11695 11702    636.0
Name: new_cases, dtype: float64
11696 11703    887.0
Name: new_cases, dtype: float64
11697 11704    1034.0
Name: new_cases, dtype: float64
11698 11705    969.0
Name: new_cases, dtype: float64
11699 11706    1162.0
Name: new_cases, dtype: float64
11700 11707    1041.0
Name: new_cases, dtype: float64
11701 11708    1202.0
Name: new_cases, dtype: float64
11702 11709    930.0
Name: new_cases, dtype: float64
11703 11710    1273.0
Name: new_cases, dtype: float64
11704 11711    1602.0
Name: new_cases, dtype: float64
11705 11712    1251.0
Name: new_cases, dtype: float64
11706 11713    1617.0
Name: new_cases, dtype: float64
11707 11714    1773.0
Name: new_cases, dtype: float64
11708 11715    1694.0
Name: new_cases, dtype: float64
11709 11716    1873.0
Name: new_cases, dtype: float64
11710 11717    1532.0
Name: new_cases, dtype: float64
11711 11718    1975.0
Name: new_cases, dtype: float64
11712 11719    1166.0
Name: new_cases, dtype: float64
11713 11720    1541.0
Name: new_cases, dtype: float64
11714 11721    2029.0
Name: new_cases, dtype: float64
11715 11722    2523.0
Name: new_cases, dtype: float64
11716 11723    1764.0
Name: new_cases, dtype: float64
11717 11724    2545.0
Name: new_cases, dtype: float64
11718 11725    2381.0
Name: new_cases, dtype: float64
11719 11726    2911.0
Name: new_cases, dtype: float64
11720 11727    2695.0
Name: new_cases, dtype: float64
11721 11728    2423.0
Name: new_cases, dtype: float64
11722 11729    2828.0
Name: new_cases, dtype: float64
11723 11730    2635.0
Name: new_cases, dtype: float64
11724 11731    2743.0
Name: new_cases, dtype: float64
11725 11732    2735.0
Name: new_cases, dtype: float64
11726 11733    3171.0
Name: new_cases, dtype: float64
11727 11734    3190.0
Name: new_cases, dtype: float64
11728 11735    3187.0
Name: new_cases, dtype: float64
11729 11736    3471.0
Name: new_cases, dtype: float64
11730 11737    2856.0
Name: new_cases, dtype: float64
11731 11738    3141.0
Name: new_cases, dtype: float64
11732 11739    3099.0
Name: new_cases, dtype: float64
11733 11740    3862.0
Name: new_cases, dtype: float64
11734 11741    4008.0
Name: new_cases, dtype: float64
11735 11742    3803.0
Name: new_cases, dtype: float64
11736 11743    3243.0
Name: new_cases, dtype: float64
11737 11744    3240.0
Name: new_cases, dtype: float64
11738 11745    3531.0
Name: new_cases, dtype: float64
11739 11746    3480.0
Name: new_cases, dtype: float64
11740 11747    3412.0
Name: new_cases, dtype: float64
11741 11748    3462.0
Name: new_cases, dtype: float64
11742 11749    3946.0
Name: new_cases, dtype: float64
11743 11750    3868.0
Name: new_cases, dtype: float64
11744 11751    3504.0
Name: new_cases, dtype: float64
11745 11752    3809.0
Name: new_cases, dtype: float64
11746 11753    4014.0
Name: new_cases, dtype: float64
11747 11754    3682.0
Name: new_cases, dtype: float64
11748 11755    3775.0
Name: new_cases, dtype: float64
11749 11756    4019.0
Name: new_cases, dtype: float64
11750 11757    3114.0
Name: new_cases, dtype: float64
11751 11758    3288.0
Name: new_cases, dtype: float64
11752 11759    2738.0
Name: new_cases, dtype: float64
11753 11760    3201.0
Name: new_cases, dtype: float64
11754 11761    3027.0
Name: new_cases, dtype: float64
11755 11762    3489.0
Name: new_cases, dtype: float64
11756 11763    3360.0
Name: new_cases, dtype: float64
11757 11764    2949.0
Name: new_cases, dtype: float64
11758 11765    2686.0
Name: new_cases, dtype: float64
11759 11766    2666.0
Name: new_cases, dtype: float64

11760 11767    3099.0
Name: new_cases, dtype: float64
11761 11768    3163.0
Name: new_cases, dtype: float64
11762 11769    3533.0
Name: new_cases, dtype: float64
11763 11770    2733.0
Name: new_cases, dtype: float64
11764 11771    3034.0
Name: new_cases, dtype: float64
11765 11772    2709.0
Name: new_cases, dtype: float64
11766 11773    2459.0
Name: new_cases, dtype: float64
11767 11774    2928.0
Name: new_cases, dtype: float64
11768 11775    3057.0
Name: new_cases, dtype: float64
11769 11776    2744.0
Name: new_cases, dtype: float64
11770 11777    2856.0
Name: new_cases, dtype: float64
11771 11778    2548.0
Name: new_cases, dtype: float64
11772 11779    2520.0
Name: new_cases, dtype: float64
11773 11780    2275.0
Name: new_cases, dtype: float64
11774 11781    2772.0
Name: new_cases, dtype: float64
11775 11782    2960.0
Name: new_cases, dtype: float64
11776 11783    3009.0
Name: new_cases, dtype: float64
11777 11784    2695.0
Name: new_cases, dtype: float64
11778 11785    2772.0
Name: new_cases, dtype: float64
11779 11786    2199.0
Name: new_cases, dtype: float64
11780 11787    886.0
Name: new_cases, dtype: float64
11781 11788    1356.0
Name: new_cases, dtype: float64
11782 11789    1918.0
Name: new_cases, dtype: float64
11783 11790    2654.0
Name: new_cases, dtype: float64
11784 11791    2977.0
Name: new_cases, dtype: float64
11785 11792    2851.0
Name: new_cases, dtype: float64
11786 11793    2611.0
Name: new_cases, dtype: float64
11787 11794    2487.0
Name: new_cases, dtype: float64
11788 11795    2907.0
Name: new_cases, dtype: float64
11789 11796    2996.0
Name: new_cases, dtype: float64
11790 11797    2995.0
Name: new_cases, dtype: float64
11791 11798    2617.0
Name: new_cases, dtype: float64
11792 11799    2766.0
Name: new_cases, dtype: float64
11793 11800    2644.0
Name: new_cases, dtype: float64
11794 11801    2024.0
Name: new_cases, dtype: float64
11795 11802    2595.0
Name: new_cases, dtype: float64
11796 11803    3200.0
Name: new_cases, dtype: float64
11797 11804    2747.0
Name: new_cases, dtype: float64
11798 11805    2868.0
Name: new_cases, dtype: float64
11799 11806    2401.0
Name: new_cases, dtype: float64
11800 11807    2265.0
Name: new_cases, dtype: float64
11801 11808    1973.0
Name: new_cases, dtype: float64
11802 11809    2485.0
Name: new_cases, dtype: float64
11803 11810    2545.0
Name: new_cases, dtype: float64
11804 11811    2519.0
Name: new_cases, dtype: float64
11805 11812    2436.0
Name: new_cases, dtype: float64
11806 11813    2211.0
Name: new_cases, dtype: float64
11807 11814    2131.0
Name: new_cases, dtype: float64
11808 11815    1897.0
Name: new_cases, dtype: float64
11809 11816    2174.0
Name: new_cases, dtype: float64
11810 11817    1950.0
Name: new_cases, dtype: float64
11811 11818    2582.0
Name: new_cases, dtype: float64
11812 11819    2158.0
Name: new_cases, dtype: float64
11813 11820    1929.0
Name: new_cases, dtype: float64
11814 11821    1950.0
Name: new_cases, dtype: float64
11815 11822    1592.0
Name: new_cases, dtype: float64
11816 11823    2202.0
Name: new_cases, dtype: float64
11817 11824    1892.0
Name: new_cases, dtype: float64
11818 11825    1827.0
Name: new_cases, dtype: float64
11819 11826    1892.0
Name: new_cases, dtype: float64
11820 11827    1792.0
Name: new_cases, dtype: float64
11821 11828    1282.0
Name: new_cases, dtype: float64
11822 11829    1476.0
Name: new_cases, dtype: float64
11823 11830    1812.0
Name: new_cases, dtype: float64
11824 11831    1724.0
Name: new_cases, dtype: float64
11825 11832    1615.0
Name: new_cases, dtype: float64
11826 11833    1593.0
Name: new_cases, dtype: float64
11827 11834    1541.0
Name: new_cases, dtype: float64
11828 11835    1567.0
Name: new_cases, dtype: float64
11829 11836    1546.0
Name: new_cases, dtype: float64
11830 11837    1703.0
Name: new_cases, dtype: float64
11831 11838    1557.0
Name: new_cases, dtype: float64
11832 11839    1666.0
Name: new_cases, dtype: float64
11833 11840    1540.0
Name: new_cases, dtype: float64
11834 11841    1383.0
Name: new_cases, dtype: float64
11835 11842    1106.0
Name: new_cases, dtype: float64
11836 11843    1275.0
Name: new_cases, dtype: float64
11837 11844    1407.0
Name: new_cases, dtype: float64
11838 11845    1488.0
Name: new_cases, dtype: float64
11839 11846    1436.0
Name: new_cases, dtype: float64
11840 11847    1508.0
Name: new_cases, dtype: float64
11841 11848    1396.0
Name: new_cases, dtype: float64
11842 11849    1182.0
Name: new_cases, dtype: float64
11843 11850    1125.0
Name: new_cases, dtype: float64
11844 11851    1442.0
Name: new_cases, dtype: float64
11845 11852    1499.0
Name: new_cases, dtype: float64
11846 11853    1520.0
Name: new_cases, dtype: float64
11847 11854    1441.0
Name: new_cases, dtype: float64
11848 11855    1278.0
Name: new_cases, dtype: float64
11849 11856    1203.0
Name: new_cases, dtype: float64
11850 11857    1193.0
Name: new_cases, dtype: float64
11851 11858    1472.0
Name: new_cases, dtype: float64
11852 11859    1537.0
Name: new_cases, dtype: float64
11853 11860    1684.0
Name: new_cases, dtype: float64
11854 11861    1600.0
Name: new_cases, dtype: float64
11855 11862    1527.0
Name: new_cases, dtype: float64
11856 11863    1209.0
Name: new_cases, dtype: float64
11857 11864    1274.0
Name: new_cases, dtype: float64
11858 11865    1637.0
Name: new_cases, dtype: float64
11859 11866    1380.0
Name: new_cases, dtype: float64
11860 11867    1545.0
Name: new_cases, dtype: float64
11861 11868    1696.0
Name: new_cases, dtype: float64
11862 11869    1586.0
Name: new_cases, dtype: float64
11863 11870    1094.0
Name: new_cases, dtype: float64
11864 11871    1308.0
Name: new_cases, dtype: float64
11865 11872    1436.0
Name: new_cases, dtype: float64
11866 11873    1335.0
Name: new_cases, dtype: float64
11867 11874    1493.0
Name: new_cases, dtype: float64
11868 11875    1681.0
Name: new_cases, dtype: float64
11869 11876    1604.0
Name: new_cases, dtype: float64
11870 11877    1320.0
Name: new_cases, dtype: float64
11871 11878    1568.0
Name: new_cases, dtype: float64
11872 11879    1736.0
Name: new_cases, dtype: float64
11873 11880    1659.0
Name: new_cases, dtype: float64
11874 11881    1517.0
Name: new_cases, dtype: float64
11875 11882    1842.0
Name: new_cases, dtype: float64
11876 11883    1469.0
Name: new_cases, dtype: float64
11877 11884    1289.0
Name: new_cases, dtype: float64
11878 11885    1474.0
Name: new_cases, dtype: float64
11879 11886    1683.0
Name: new_cases, dtype: float64
11880 11887    1699.0
Name: new_cases, dtype: float64
11881 11888    1733.0
Name: new_cases, dtype: float64
11882 11889    1845.0
Name: new_cases, dtype: float64
11883 11890    1767.0
Name: new_cases, dtype: float64
11884 11891    1531.0
Name: new_cases, dtype: float64
11885 11892    1837.0
Name: new_cases, dtype: float64
11886 11893    2139.0
Name: new_cases, dtype: float64
11887 11894    2212.0
Name: new_cases, dtype: float64
11888 11895    2111.0
Name: new_cases, dtype: float64
11889 11896    2364.0
Name: new_cases, dtype: float64
11890 11897    2275.0
Name: new_cases, dtype: float64
11891 11898    1847.0
Name: new_cases, dtype: float64
11892 11899    2060.0
Name: new_cases, dtype: float64
11893 11900    2419.0
Name: new_cases, dtype: float64
11894 11901    2230.0
Name: new_cases, dtype: float64
11895 11902    2156.0
Name: new_cases, dtype: float64
11896 11903    2292.0
Name: new_cases, dtype: float64
11897 11904    2273.0
Name: new_cases, dtype: float64
11898 11905    1908.0
Name: new_cases, dtype: float64
11899 11906    1788.0
Name: new_cases, dtype: float64
11900 11907    2525.0
Name: new_cases, dtype: float64
11901 11908    2293.0
Name: new_cases, dtype: float64
11902 11909    2198.0
Name: new_cases, dtype: float64
11903 11910    2316.0
Name: new_cases, dtype: float64
11904 11911    2252.0
Name: new_cases, dtype: float64
11905 11912    1798.0
Name: new_cases, dtype: float64
11906 11913    1756.0
Name: new_cases, dtype: float64
11907 11914    2198.0
Name: new_cases, dtype: float64
11908 11915    2202.0
Name: new_cases, dtype: float64
11909 11916    2159.0
Name: new_cases, dtype: float64
11910 11917    1861.0
Name: new_cases, dtype: float64
11911 11918    1884.0
Name: new_cases, dtype: float64
11912 11919    1329.0
Name: new_cases, dtype: float64
11913 11920    1355.0
Name: new_cases, dtype: float64
11914 11921    1799.0
Name: new_cases, dtype: float64
11915 11922    1877.0
Name: new_cases, dtype: float64
11916 11923    1632.0
Name: new_cases, dtype: float64
11917 11924    1134.0
Name: new_cases, dtype: float64
11918 11925    1318.0
Name: new_cases, dtype: float64
11919 11926    1267.0
Name: new_cases, dtype: float64

11920 11927    1153.0
Name: new_cases, dtype: float64
11921 11928    1470.0
Name: new_cases, dtype: float64
11922 11929    1318.0
Name: new_cases, dtype: float64
11923 11930    1367.0
Name: new_cases, dtype: float64
11924 11931    1234.0
Name: new_cases, dtype: float64
11925 11932    1163.0
Name: new_cases, dtype: float64
11926 11933    834.0
Name: new_cases, dtype: float64
11927 11934    1049.0
Name: new_cases, dtype: float64
11928 11935    932.0
Name: new_cases, dtype: float64
11929 11936    1181.0
Name: new_cases, dtype: float64
11930 11937    1235.0
Name: new_cases, dtype: float64
11931 11938    1014.0
Name: new_cases, dtype: float64
11932 11939    990.0
Name: new_cases, dtype: float64
11933 11940    684.0
Name: new_cases, dtype: float64
11934 11941    835.0
Name: new_cases, dtype: float64
11935 11942    910.0
Name: new_cases, dtype: float64
11936 11943    991.0
Name: new_cases, dtype: float64
11937 11944    978.0
Name: new_cases, dtype: float64
11938 11945    1007.0
Name: new_cases, dtype: float64
11939 11946    785.0
Name: new_cases, dtype: float64
11940 11947    692.0
Name: new_cases, dtype: float64
11941 11948    1071.0
Name: new_cases, dtype: float64
11942 11949    849.0
Name: new_cases, dtype: float64
11943 11950    718.0
Name: new_cases, dtype: float64
11944 11951    890.0
Name: new_cases, dtype: float64
11945 11952    813.0
Name: new_cases, dtype: float64
11946 11953    762.0
Name: new_cases, dtype: float64
11947 11954    578.0
Name: new_cases, dtype: float64
11948 11955    569.0
Name: new_cases, dtype: float64
11949 11956    697.0
Name: new_cases, dtype: float64
11950 11957    702.0
Name: new_cases, dtype: float64
11951 11958    656.0
Name: new_cases, dtype: float64
11952 11959    584.0
Name: new_cases, dtype: float64
11953 11960    619.0
Name: new_cases, dtype: float64
11954 11961    436.0
Name: new_cases, dtype: float64
11955 11962    473.0
Name: new_cases, dtype: float64
11956 11963    602.0
Name: new_cases, dtype: float64
11957 11964    515.0
Name: new_cases, dtype: float64
11958 11965    528.0
Name: new_cases, dtype: float64
11959 11966    509.0
Name: new_cases, dtype: float64
11960 11967    454.0
Name: new_cases, dtype: float64
11961 11968    363.0
Name: new_cases, dtype: float64
11962 11969    369.0
Name: new_cases, dtype: float64
11963 11970    443.0
Name: new_cases, dtype: float64
11964 11971    525.0
Name: new_cases, dtype: float64
11965 11972    438.0
Name: new_cases, dtype: float64
11966 11973    485.0
Name: new_cases, dtype: float64
11967 11974    435.0
Name: new_cases, dtype: float64
11968 11975    305.0
Name: new_cases, dtype: float64
11969 11976    292.0
Name: new_cases, dtype: float64
11970 11977    316.0
Name: new_cases, dtype: float64
11971 11978    387.0
Name: new_cases, dtype: float64
11972 11979    388.0
Name: new_cases, dtype: float64
11973 11980    378.0
Name: new_cases, dtype: float64
11974 11981    444.0
Name: new_cases, dtype: float64
11975 11982    291.0
Name: new_cases, dtype: float64
11976 11983    326.0
Name: new_cases, dtype: float64
11977 11984    446.0
Name: new_cases, dtype: float64
11978 11985    396.0
Name: new_cases, dtype: float64
11979 11986    443.0
Name: new_cases, dtype: float64
11980 11987    391.0
Name: new_cases, dtype: float64
11981 11988    406.0
Name: new_cases, dtype: float64
11982 11989    350.0
Name: new_cases, dtype: float64
11983 11990    327.0
Name: new_cases, dtype: float64
11984 11991    366.0
Name: new_cases, dtype: float64
11985 11992    399.0
Name: new_cases, dtype: float64
11986 11993    428.0
Name: new_cases, dtype: float64
11987 11994    410.0
Name: new_cases, dtype: float64
11988 11995    470.0
Name: new_cases, dtype: float64
11989 11996    407.0
Name: new_cases, dtype: float64
11990 11997    385.0
Name: new_cases, dtype: float64
11991 11998    585.0
Name: new_cases, dtype: float64
11992 11999    515.0
Name: new_cases, dtype: float64
11993 12000    614.0
Name: new_cases, dtype: float64
11994 12001    619.0
Name: new_cases, dtype: float64
11995 12002    635.0
Name: new_cases, dtype: float64
11996 12003    540.0
Name: new_cases, dtype: float64
11997 12004    606.0
Name: new_cases, dtype: float64
11998 12005    845.0
Name: new_cases, dtype: float64
11999 12006    912.0
Name: new_cases, dtype: float64
12000 12007    1018.0
Name: new_cases, dtype: float64
12001 12008    1051.0
Name: new_cases, dtype: float64
12002 12009    1066.0
Name: new_cases, dtype: float64
12003 12010    1014.0
Name: new_cases, dtype: float64
12004 12011    1159.0
Name: new_cases, dtype: float64
12005 12012    1773.0
Name: new_cases, dtype: float64
12006 12013    1719.0
Name: new_cases, dtype: float64
12007 12014    1865.0
Name: new_cases, dtype: float64
12008 12015    2187.0
Name: new_cases, dtype: float64
12009 12016    1899.0
Name: new_cases, dtype: float64
12010 12017    1868.0
Name: new_cases, dtype: float64
12011 12018    2172.0
Name: new_cases, dtype: float64
12012 12019    2809.0
Name: new_cases, dtype: float64
12013 12020    3554.0
Name: new_cases, dtype: float64
12014 12021    3567.0
Name: new_cases, dtype: float64
12015 12022    3587.0
Name: new_cases, dtype: float64
12016 12023    3737.0
Name: new_cases, dtype: float64
12017 12024    3674.0
Name: new_cases, dtype: float64
12018 12025    3908.0
Name: new_cases, dtype: float64
12019 12026    5181.0
Name: new_cases, dtype: float64
12020 12027    5042.0
Name: new_cases, dtype: float64
12021 12028    5358.0
Name: new_cases, dtype: float64
12022 12029    6469.0
Name: new_cases, dtype: float64
12023 12030    6830.0
Name: new_cases, dtype: float64
12024 12031    5683.0
Name: new_cases, dtype: float64
12025 12032    7087.0
Name: new_cases, dtype: float64
12026 12033    7075.0
Name: new_cases, dtype: float64
12027 12034    7213.0
Name: new_cases, dtype: float64
12028 12035    7626.0
Name: new_cases, dtype: float64
12029 12036    6854.0
Name: new_cases, dtype: float64
12030 12037    7462.0
Name: new_cases, dtype: float64
12031 12038    5343.0
Name: new_cases, dtype: float64
12032 12039    5819.0
Name: new_cases, dtype: float64
12033 12040    7201.0
Name: new_cases, dtype: float64
12034 12041    6028.0
Name: new_cases, dtype: float64
12035 12042    5185.0
Name: new_cases, dtype: float64
12036 12043    4192.0
Name: new_cases, dtype: float64
12037 12044    4417.0
Name: new_cases, dtype: float64
12038 12045    3473.0
Name: new_cases, dtype: float64
12039 12046    3698.0
Name: new_cases, dtype: float64
12040 12047    4271.0
Name: new_cases, dtype: float64
12041 12048    4559.0
Name: new_cases, dtype: float64
12042 12049    4280.0
Name: new_cases, dtype: float64
12043 12050    4014.0
Name: new_cases, dtype: float64
12044 12051    3629.0
Name: new_cases, dtype: float64
12045 12052    2697.0
Name: new_cases, dtype: float64
12046 12053    2922.0
Name: new_cases, dtype: float64
12047 12054    3306.0
Name: new_cases, dtype: float64
12048 12055    3031.0
Name: new_cases, dtype: float64
12049 12056    2955.0
Name: new_cases, dtype: float64
12050 12057    2341.0
Name: new_cases, dtype: float64
12051 12058    2177.0
Name: new_cases, dtype: float64
12052 12059    1452.0
Name: new_cases, dtype: float64
12053 12060    1359.0
Name: new_cases, dtype: float64
12054 12061    1739.0
Name: new_cases, dtype: float64
12055 12062    1914.0
Name: new_cases, dtype: float64
12056 12063    1742.0
Name: new_cases, dtype: float64
12057 12064    1822.0
Name: new_cases, dtype: float64
12058 12065    1682.0
Name: new_cases, dtype: float64
12059 12066    1285.0
Name: new_cases, dtype: float64
12060 12067    1386.0
Name: new_cases, dtype: float64
12061 12068    1514.0
Name: new_cases, dtype: float64
12062 12069    1230.0
Name: new_cases, dtype: float64
12063 12070    1140.0
Name: new_cases, dtype: float64
12064 12071    1290.0
Name: new_cases, dtype: float64
12065 12072    848.0
Name: new_cases, dtype: float64
12066 12073    261.0
Name: new_cases, dtype: float64
12067 12074    363.0
Name: new_cases, dtype: float64
12068 12075    698.0
Name: new_cases, dtype: float64
12069 12076    1272.0
Name: new_cases, dtype: float64
12070 12077    1608.0
Name: new_cases, dtype: float64
12071 12078    1457.0
Name: new_cases, dtype: float64
12072 12079    1504.0
Name: new_cases, dtype: float64
12073 12080    1028.0
Name: new_cases, dtype: float64
12074 12081    1354.0
Name: new_cases, dtype: float64
12075 12082    1441.0
Name: new_cases, dtype: float64
12076 12083    1675.0
Name: new_cases, dtype: float64
12077 12084    1497.0
Name: new_cases, dtype: float64
12078 12085    1292.0
Name: new_cases, dtype: float64
12079 12086    1358.0
Name: new_cases, dtype: float64

12080 12087    1043.0
Name: new_cases, dtype: float64
12081 12088    1444.0
Name: new_cases, dtype: float64
12082 12089    1710.0
Name: new_cases, dtype: float64
12083 12090    1765.0
Name: new_cases, dtype: float64
12084 12091    1988.0
Name: new_cases, dtype: float64
12085 12092    1687.0
Name: new_cases, dtype: float64
12086 12093    1887.0
Name: new_cases, dtype: float64
12087 12094    1447.0
Name: new_cases, dtype: float64
12088 12095    1676.0
Name: new_cases, dtype: float64
12089 12096    1970.0
Name: new_cases, dtype: float64
12090 12097    2322.0
Name: new_cases, dtype: float64
12091 12098    2537.0
Name: new_cases, dtype: float64
12092 12099    2576.0
Name: new_cases, dtype: float64
12093 12100    2454.0
Name: new_cases, dtype: float64
12094 12101    1637.0
Name: new_cases, dtype: float64
12095 12102    2436.0
Name: new_cases, dtype: float64
12096 12103    3050.0
Name: new_cases, dtype: float64
12097 12104    3319.0
Name: new_cases, dtype: float64
12098 12105    3956.0
Name: new_cases, dtype: float64
12099 12106    3840.0
Name: new_cases, dtype: float64
12100 12107    3883.0
Name: new_cases, dtype: float64
12101 12108    3057.0
Name: new_cases, dtype: float64
12102 12109    3641.0
Name: new_cases, dtype: float64
12103 12110    4636.0
Name: new_cases, dtype: float64
12104 12111    4846.0
Name: new_cases, dtype: float64
12105 12112    5727.0
Name: new_cases, dtype: float64
12106 12113    6058.0
Name: new_cases, dtype: float64
12107 12114    5869.0
Name: new_cases, dtype: float64
12108 12115    4334.0
Name: new_cases, dtype: float64
12109 12116    5268.0
Name: new_cases, dtype: float64
12110 12117    8364.0
Name: new_cases, dtype: float64
12111 12118    7666.0
Name: new_cases, dtype: float64
12112 12119    8822.0
Name: new_cases, dtype: float64
12113 12120    8301.0
Name: new_cases, dtype: float64
12114 12121    8483.0
Name: new_cases, dtype: float64
12115 12122    6214.0
Name: new_cases, dtype: float64
12116 12123    8661.0
Name: new_cases, dtype: float64
12117 12124    9964.0
Name: new_cases, dtype: float64
12118 12125    11525.0
Name: new_cases, dtype: float64
12119 12126    11162.0
Name: new_cases, dtype: float64
12120 12127    11651.0
Name: new_cases, dtype: float64
12121 12128    11324.0
Name: new_cases, dtype: float64
12122 12129    8772.0
Name: new_cases, dtype: float64
12123 12130    11874.0
Name: new_cases, dtype: float64
12124 12131    13768.0
Name: new_cases, dtype: float64
12125 12132    12198.0
Name: new_cases, dtype: float64
12126 12133    12383.0
Name: new_cases, dtype: float64
12127 12134    12236.0
Name: new_cases, dtype: float64
12128 12135    12148.0
Name: new_cases, dtype: float64
12129 12136    8489.0
Name: new_cases, dtype: float64
12130 12137    11578.0
Name: new_cases, dtype: float64
12131 12138    13321.0
Name: new_cases, dtype: float64
12132 12139    11579.0
Name: new_cases, dtype: float64
12133 12140    7614.0
Name: new_cases, dtype: float64
12134 12141    3697.0
Name: new_cases, dtype: float64
12135 12142    6364.0
Name: new_cases, dtype: float64
12136 12143    6780.0
Name: new_cases, dtype: float64
12137 12144    11291.0
Name: new_cases, dtype: float64
12138 12145    15192.0
Name: new_cases, dtype: float64
12139 12146    14925.0
Name: new_cases, dtype: float64
12140 12147    16230.0
Name: new_cases, dtype: float64
12141 12148    15271.0
Name: new_cases, dtype: float64
12142 12149    13862.0
Name: new_cases, dtype: float64
12143 12150    9369.0
Name: new_cases, dtype: float64
12144 12151    14844.0
Name: new_cases, dtype: float64
12145 12152    15989.0
Name: new_cases, dtype: float64
12146 12153    15776.0
Name: new_cases, dtype: float64
12147 12154    13817.0
Name: new_cases, dtype: float64
12148 12155    12744.0
Name: new_cases, dtype: float64
12149 12156    12606.0
Name: new_cases, dtype: float64
12150 12157    8136.0
Name: new_cases, dtype: float64
12151 12158    10299.0
Name: new_cases, dtype: float64
12152 12159    11463.0
Name: new_cases, dtype: float64
12153 12160    11164.0
Name: new_cases, dtype: float64
12154 12161    10420.0
Name: new_cases, dtype: float64
12155 12162    10126.0
Name: new_cases, dtype: float64
12156 12163    8465.0
Name: new_cases, dtype: float64
12157 12164    6885.0
Name: new_cases, dtype: float64
12158 12165    6684.0
Name: new_cases, dtype: float64
12159 12166    6959.0
Name: new_cases, dtype: float64
12160 12167    7535.0
Name: new_cases, dtype: float64
12161 12168    7248.0
Name: new_cases, dtype: float64
12162 12169    6566.0
Name: new_cases, dtype: float64
12163 12170    5993.0
Name: new_cases, dtype: float64
12164 12171    3991.0
Name: new_cases, dtype: float64
12165 12172    4804.0
Name: new_cases, dtype: float64
12166 12173    5717.0
Name: new_cases, dtype: float64
12167 12174    5249.0
Name: new_cases, dtype: float64
12168 12175    4966.0
Name: new_cases, dtype: float64
12169 12176    4698.0
Name: new_cases, dtype: float64
12170 12177    3525.0
Name: new_cases, dtype: float64
12171 12178    3436.0
Name: new_cases, dtype: float64
12172 12179    3948.0
Name: new_cases, dtype: float64
12173 12180    3724.0
Name: new_cases, dtype: float64
12174 12181    3357.0
Name: new_cases, dtype: float64
12175 12182    3062.0
Name: new_cases, dtype: float64
12176 12183    3436.0
Name: new_cases, dtype: float64
12177 12184    3167.0
Name: new_cases, dtype: float64
12178 12185    1743.0
Name: new_cases, dtype: float64
12179 12186    2430.0
Name: new_cases, dtype: float64
12180 12187    2710.0
Name: new_cases, dtype: float64
12181 12188    2639.0
Name: new_cases, dtype: float64
12182 12189    2497.0
Name: new_cases, dtype: float64
12183 12190    2588.0
Name: new_cases, dtype: float64
12184 12191    2325.0
Name: new_cases, dtype: float64
12185 12192    1327.0
Name: new_cases, dtype: float64
12186 12193    1871.0
Name: new_cases, dtype: float64
12187 12194    1953.0
Name: new_cases, dtype: float64
12188 12195    2074.0
Name: new_cases, dtype: float64
12189 12196    1901.0
Name: new_cases, dtype: float64
12190 12197    1862.0
Name: new_cases, dtype: float64
12191 12198    1907.0
Name: new_cases, dtype: float64
12192 12199    1190.0
Name: new_cases, dtype: float64
12193 12200    1383.0
Name: new_cases, dtype: float64
12194 12201    1555.0
Name: new_cases, dtype: float64
12195 12202    1562.0
Name: new_cases, dtype: float64
12196 12203    1376.0
Name: new_cases, dtype: float64
12197 12204    1144.0
Name: new_cases, dtype: float64
12198 12205    1233.0
Name: new_cases, dtype: float64
12199 12206    818.0
Name: new_cases, dtype: float64
12200 12207    980.0
Name: new_cases, dtype: float64
12201 12208    1212.0
Name: new_cases, dtype: float64
12202 12209    1310.0
Name: new_cases, dtype: float64
12203 12210    1178.0
Name: new_cases, dtype: float64
12204 12211    860.0
Name: new_cases, dtype: float64
12205 12212    847.0
Name: new_cases, dtype: float64
12206 12213    589.0
Name: new_cases, dtype: float64
12207 12214    617.0
Name: new_cases, dtype: float64
12208 12215    794.0
Name: new_cases, dtype: float64
12209 12216    694.0
Name: new_cases, dtype: float64
12210 12217    703.0
Name: new_cases, dtype: float64
12211 12218    663.0
Name: new_cases, dtype: float64
12212 12219    645.0
Name: new_cases, dtype: float64
12213 12220    415.0
Name: new_cases, dtype: float64
12214 12221    481.0
Name: new_cases, dtype: float64
12215 12222    599.0
Name: new_cases, dtype: float64
12216 12223    543.0
Name: new_cases, dtype: float64
12217 12224    518.0
Name: new_cases, dtype: float64
12218 12225    466.0
Name: new_cases, dtype: float64
12219 12226    396.0
Name: new_cases, dtype: float64
12220 12227    293.0
Name: new_cases, dtype: float64
12221 12228    314.0
Name: new_cases, dtype: float64
12222 12229    339.0
Name: new_cases, dtype: float64
12223 12230    469.0
Name: new_cases, dtype: float64
12224 12231    368.0
Name: new_cases, dtype: float64
12225 12232    243.0
Name: new_cases, dtype: float64
12226 12233    232.0
Name: new_cases, dtype: float64
12227 12234    278.0
Name: new_cases, dtype: float64
12228 12235    275.0
Name: new_cases, dtype: float64
12229 12236    289.0
Name: new_cases, dtype: float64
12230 12237    276.0
Name: new_cases, dtype: float64
12231 12238    306.0
Name: new_cases, dtype: float64
12232 12239    294.0
Name: new_cases, dtype: float64
12233 12240    305.0
Name: new_cases, dtype: float64
12234 12241    166.0
Name: new_cases, dtype: float64
12235 12242    211.0
Name: new_cases, dtype: float64
12236 12243    214.0
Name: new_cases, dtype: float64
12237 12244    229.0
Name: new_cases, dtype: float64

12238 12245    256.0
Name: new_cases, dtype: float64
12239 12246    247.0
Name: new_cases, dtype: float64
12240 12247    0.0
Name: new_cases, dtype: float64
12241 12248    350.0
Name: new_cases, dtype: float64
12242 12249    178.0
Name: new_cases, dtype: float64
12243 12250    215.0
Name: new_cases, dtype: float64
12244 12251    206.0
Name: new_cases, dtype: float64
12245 12252    235.0
Name: new_cases, dtype: float64
12246 12253    237.0
Name: new_cases, dtype: float64
12247 12254    221.0
Name: new_cases, dtype: float64
12248 12255    151.0
Name: new_cases, dtype: float64
12249 12256    223.0
Name: new_cases, dtype: float64
12250 12257    234.0
Name: new_cases, dtype: float64
12251 12258    213.0
Name: new_cases, dtype: float64
12252 12259    266.0
Name: new_cases, dtype: float64
12253 12260    244.0
Name: new_cases, dtype: float64
12254 12261    253.0
Name: new_cases, dtype: float64
12255 12262    178.0
Name: new_cases, dtype: float64
12256 12263    199.0
Name: new_cases, dtype: float64
12257 12264    264.0
Name: new_cases, dtype: float64
12258 12265    284.0
Name: new_cases, dtype: float64
12259 12266    312.0
Name: new_cases, dtype: float64
12260 12267    237.0
Name: new_cases, dtype: float64
12261 12268    239.0
Name: new_cases, dtype: float64
12262 12269    155.0
Name: new_cases, dtype: float64
12263 12270    205.0
Name: new_cases, dtype: float64
12264 12271    227.0
Name: new_cases, dtype: float64
12265 12272    273.0
Name: new_cases, dtype: float64
12266 12273    282.0
Name: new_cases, dtype: float64
12267 12274    261.0
Name: new_cases, dtype: float64
12268 12275    243.0
Name: new_cases, dtype: float64
12269 12276    0.0
Name: new_cases, dtype: float64
12270 12277    373.0
Name: new_cases, dtype: float64
12271 12278    277.0
Name: new_cases, dtype: float64
12272 12279    291.0
Name: new_cases, dtype: float64
12273 12280    277.0
Name: new_cases, dtype: float64
12274 12281    262.0
Name: new_cases, dtype: float64
12275 12282    269.0
Name: new_cases, dtype: float64
12276 12283    177.0
Name: new_cases, dtype: float64
12277 12284    329.0
Name: new_cases, dtype: float64
12278 12285    385.0
Name: new_cases, dtype: float64
12279 12286    295.0
Name: new_cases, dtype: float64
12280 12287    297.0
Name: new_cases, dtype: float64
12281 12288    257.0
Name: new_cases, dtype: float64
12282 12289    191.0
Name: new_cases, dtype: float64
12283 12290    122.0
Name: new_cases, dtype: float64
12284 12291    211.0
Name: new_cases, dtype: float64
12285 12292    260.0
Name: new_cases, dtype: float64
12286 12293    291.0
Name: new_cases, dtype: float64
12287 12294    352.0
Name: new_cases, dtype: float64
12288 12295    382.0
Name: new_cases, dtype: float64
12289 12296    342.0
Name: new_cases, dtype: float64
12290 12297    275.0
Name: new_cases, dtype: float64
12291 12298    268.0
Name: new_cases, dtype: float64
12292 12299    373.0
Name: new_cases, dtype: float64
12293 12300    397.0
Name: new_cases, dtype: float64
12294 12301    495.0
Name: new_cases, dtype: float64
12295 12302    509.0
Name: new_cases, dtype: float64
12296 12303    512.0
Name: new_cases, dtype: float64
12297 12304    370.0
Name: new_cases, dtype: float64
12298 12305    557.0
Name: new_cases, dtype: float64
12299 12306    674.0
Name: new_cases, dtype: float64
12300 12307    775.0
Name: new_cases, dtype: float64
12301 12308    892.0
Name: new_cases, dtype: float64
12302 12309    1140.0
Name: new_cases, dtype: float64
12303 12310    1146.0
Name: new_cases, dtype: float64
12304 12311    1116.0
Name: new_cases, dtype: float64
12305 Series([], Name: new_cases, dtype: float64)
12306 Series([], Name: new_cases, dtype: float64)
12307 Series([], Name: new_cases, dtype: float64)
12308 Series([], Name: new_cases, dtype: float64)
12309 Series([], Name: new_cases, dtype: float64)
12310 Series([], Name: new_cases, dtype: float64)
12311 Series([], Name: new_cases, dtype: float64)
12975 12982    0.0
Name: new_cases, dtype: float64
12976 12983    0.0
Name: new_cases, dtype: float64
12977 12984    0.0
Name: new_cases, dtype: float64
12978 12985    0.0
Name: new_cases, dtype: float64
12979 12986    3.0
Name: new_cases, dtype: float64
12980 12987    0.0
Name: new_cases, dtype: float64
12981 12988    3.0
Name: new_cases, dtype: float64
12982 12989    15.0
Name: new_cases, dtype: float64
12983 12990    0.0
Name: new_cases, dtype: float64
12984 12991    0.0
Name: new_cases, dtype: float64
12985 12992    9.0
Name: new_cases, dtype: float64
12986 12993    0.0
Name: new_cases, dtype: float64
12987 12994    15.0
Name: new_cases, dtype: float64
12988 12995    0.0
Name: new_cases, dtype: float64
12989 12996    18.0
Name: new_cases, dtype: float64
12990 12997    7.0
Name: new_cases, dtype: float64
12991 12998    0.0
Name: new_cases, dtype: float64
12992 12999    5.0
Name: new_cases, dtype: float64
12993 13000    0.0
Name: new_cases, dtype: float64
12994 13001    5.0
Name: new_cases, dtype: float64
12995 13002    0.0
Name: new_cases, dtype: float64
12996 13003    8.0
Name: new_cases, dtype: float64
12997 13004    0.0
Name: new_cases, dtype: float64
12998 13005    0.0
Name: new_cases, dtype: float64
12999 13006    58.0
Name: new_cases, dtype: float64
13000 13007    0.0
Name: new_cases, dtype: float64
13001 13008    11.0
Name: new_cases, dtype: float64
13002 13009    141.0
Name: new_cases, dtype: float64
13003 13010    47.0
Name: new_cases, dtype: float64
13004 13011    89.0
Name: new_cases, dtype: float64
13005 13012    122.0
Name: new_cases, dtype: float64
13006 13013    138.0
Name: new_cases, dtype: float64
13007 13014    161.0
Name: new_cases, dtype: float64
13008 13015    205.0
Name: new_cases, dtype: float64
13009 13016    420.0
Name: new_cases, dtype: float64
13010 13017    495.0
Name: new_cases, dtype: float64
13011 13018    245.0
Name: new_cases, dtype: float64
13012 13019    352.0
Name: new_cases, dtype: float64
13013 13020    341.0
Name: new_cases, dtype: float64
13014 13021    362.0
Name: new_cases, dtype: float64
13015 13022    447.0
Name: new_cases, dtype: float64
13016 13023    476.0
Name: new_cases, dtype: float64
13017 13024    575.0
Name: new_cases, dtype: float64
13018 13025    518.0
Name: new_cases, dtype: float64
13019 13026    510.0
Name: new_cases, dtype: float64
13020 13027    457.0
Name: new_cases, dtype: float64
13021 13028    459.0
Name: new_cases, dtype: float64
13022 13029    558.0
Name: new_cases, dtype: float64
13023 13030    741.0
Name: new_cases, dtype: float64
13024 13031    751.0
Name: new_cases, dtype: float64
13025 13032    817.0
Name: new_cases, dtype: float64
13026 13033    873.0
Name: new_cases, dtype: float64
13027 13034    826.0
Name: new_cases, dtype: float64
13028 13035    919.0
Name: new_cases, dtype: float64
13029 13036    973.0
Name: new_cases, dtype: float64
13030 13037    846.0
Name: new_cases, dtype: float64
13031 13038    890.0
Name: new_cases, dtype: float64
13032 13039    911.0
Name: new_cases, dtype: float64
13033 13040    877.0
Name: new_cases, dtype: float64
13034 13041    784.0
Name: new_cases, dtype: float64
13035 13042    861.0
Name: new_cases, dtype: float64
13036 13043    905.0
Name: new_cases, dtype: float64
13037 13044    913.0
Name: new_cases, dtype: float64
13038 13045    933.0
Name: new_cases, dtype: float64
13039 13046    951.0
Name: new_cases, dtype: float64
13040 13047    921.0
Name: new_cases, dtype: float64
13041 13048    933.0
Name: new_cases, dtype: float64
13042 13049    967.0
Name: new_cases, dtype: float64
13043 13050    952.0
Name: new_cases, dtype: float64
13044 13051    947.0
Name: new_cases, dtype: float64
13045 13052    958.0
Name: new_cases, dtype: float64
13046 13053    951.0
Name: new_cases, dtype: float64
13047 13054    969.0
Name: new_cases, dtype: float64
13048 13055    922.0
Name: new_cases, dtype: float64
13049 13056    936.0
Name: new_cases, dtype: float64
13050 13057    918.0
Name: new_cases, dtype: float64
13051 13058    945.0
Name: new_cases, dtype: float64
13052 13059    932.0
Name: new_cases, dtype: float64
13053 13060    941.0
Name: new_cases, dtype: float64
13054 13061    954.0
Name: new_cases, dtype: float64
13055 13062    946.0
Name: new_cases, dtype: float64
13056 13063    915.0
Name: new_cases, dtype: float64
13057 13064    897.0
Name: new_cases, dtype: float64
13058 13065    902.0
Name: new_cases, dtype: float64
13059 13066    906.0
Name: new_cases, dtype: float64
13060 13067    894.0
Name: new_cases, dtype: float64

13061 13068    898.0
Name: new_cases, dtype: float64
13062 13069    847.0
Name: new_cases, dtype: float64
13063 13070    852.0
Name: new_cases, dtype: float64
13064 13071    861.0
Name: new_cases, dtype: float64
13065 13072    865.0
Name: new_cases, dtype: float64
13066 13073    887.0
Name: new_cases, dtype: float64
13067 13074    883.0
Name: new_cases, dtype: float64
13068 13075    879.0
Name: new_cases, dtype: float64
13069 13076    823.0
Name: new_cases, dtype: float64
13070 13077    812.0
Name: new_cases, dtype: float64
13071 13078    801.0
Name: new_cases, dtype: float64
13072 13079    750.0
Name: new_cases, dtype: float64
13073 13080    704.0
Name: new_cases, dtype: float64
13074 13081    721.0
Name: new_cases, dtype: float64
13075 13082    732.0
Name: new_cases, dtype: float64
13076 13083    707.0
Name: new_cases, dtype: float64
13077 13084    689.0
Name: new_cases, dtype: float64
13078 13085    663.0
Name: new_cases, dtype: float64
13079 13086    625.0
Name: new_cases, dtype: float64
13080 13087    676.0
Name: new_cases, dtype: float64
13081 13088    603.0
Name: new_cases, dtype: float64
13082 13089    569.0
Name: new_cases, dtype: float64
13083 13090    518.0
Name: new_cases, dtype: float64
13084 13091    464.0
Name: new_cases, dtype: float64
13085 13092    458.0
Name: new_cases, dtype: float64
13086 13093    437.0
Name: new_cases, dtype: float64
13087 13094    331.0
Name: new_cases, dtype: float64
13088 13095    382.0
Name: new_cases, dtype: float64
13089 13096    380.0
Name: new_cases, dtype: float64
13090 13097    315.0
Name: new_cases, dtype: float64
13091 13098    328.0
Name: new_cases, dtype: float64
13092 13099    306.0
Name: new_cases, dtype: float64
13093 13100    274.0
Name: new_cases, dtype: float64
13094 13101    299.0
Name: new_cases, dtype: float64
13095 13102    273.0
Name: new_cases, dtype: float64
13096 13103    284.0
Name: new_cases, dtype: float64
13097 13104    250.0
Name: new_cases, dtype: float64
13098 13105    199.0
Name: new_cases, dtype: float64
13099 13106    221.0
Name: new_cases, dtype: float64
13100 13107    187.0
Name: new_cases, dtype: float64
13101 13108    193.0
Name: new_cases, dtype: float64
13102 13109    163.0
Name: new_cases, dtype: float64
13103 13110    165.0
Name: new_cases, dtype: float64
13104 13111    182.0
Name: new_cases, dtype: float64
13105 13112    155.0
Name: new_cases, dtype: float64
13106 13113    174.0
Name: new_cases, dtype: float64
13107 13114    180.0
Name: new_cases, dtype: float64
13108 13115    159.0
Name: new_cases, dtype: float64
13109 13116    171.0
Name: new_cases, dtype: float64
13110 13117    142.0
Name: new_cases, dtype: float64
13111 13118    118.0
Name: new_cases, dtype: float64
13112 13119    135.0
Name: new_cases, dtype: float64
13113 13120    173.0
Name: new_cases, dtype: float64
13114 13121    167.0
Name: new_cases, dtype: float64
13115 13122    158.0
Name: new_cases, dtype: float64
13116 13123    156.0
Name: new_cases, dtype: float64
13117 13124    130.0
Name: new_cases, dtype: float64
13118 13125    119.0
Name: new_cases, dtype: float64
13119 13126    115.0
Name: new_cases, dtype: float64
13120 13127    152.0
Name: new_cases, dtype: float64
13121 13128    147.0
Name: new_cases, dtype: float64
13122 13129    143.0
Name: new_cases, dtype: float64
13123 13130    138.0
Name: new_cases, dtype: float64
13124 13131    121.0
Name: new_cases, dtype: float64
13125 13132    99.0
Name: new_cases, dtype: float64
13126 13133    84.0
Name: new_cases, dtype: float64
13127 13134    126.0
Name: new_cases, dtype: float64
13128 13135    127.0
Name: new_cases, dtype: float64
13129 13136    111.0
Name: new_cases, dtype: float64
13130 13137    124.0
Name: new_cases, dtype: float64
13131 13138    112.0
Name: new_cases, dtype: float64
13132 13139    97.0
Name: new_cases, dtype: float64
13133 13140    58.0
Name: new_cases, dtype: float64
13134 13141    97.0
Name: new_cases, dtype: float64
13135 13142    101.0
Name: new_cases, dtype: float64
13136 13143    105.0
Name: new_cases, dtype: float64
13137 13144    0.0
Name: new_cases, dtype: float64
13138 13145    208.0
Name: new_cases, dtype: float64
13139 13146    73.0
Name: new_cases, dtype: float64
13140 13147    84.0
Name: new_cases, dtype: float64
13141 13148    128.0
Name: new_cases, dtype: float64
13142 13149    149.0
Name: new_cases, dtype: float64
13143 13150    161.0
Name: new_cases, dtype: float64
13144 13151    174.0
Name: new_cases, dtype: float64
13145 13152    183.0
Name: new_cases, dtype: float64
13146 13153    177.0
Name: new_cases, dtype: float64
13147 13154    82.0
Name: new_cases, dtype: float64
13148 13155    247.0
Name: new_cases, dtype: float64
13149 13156    191.0
Name: new_cases, dtype: float64
13150 13157    181.0
Name: new_cases, dtype: float64
13151 13158    177.0
Name: new_cases, dtype: float64
13152 13159    164.0
Name: new_cases, dtype: float64
13153 13160    156.0
Name: new_cases, dtype: float64
13154 13161    119.0
Name: new_cases, dtype: float64
13155 13162    179.0
Name: new_cases, dtype: float64
13156 13163    161.0
Name: new_cases, dtype: float64
13157 13164    183.0
Name: new_cases, dtype: float64
13158 13165    178.0
Name: new_cases, dtype: float64
13159 13166    196.0
Name: new_cases, dtype: float64
13160 13167    172.0
Name: new_cases, dtype: float64
13161 13168    177.0
Name: new_cases, dtype: float64
13162 13169    194.0
Name: new_cases, dtype: float64
13163 13170    189.0
Name: new_cases, dtype: float64
13164 13171    193.0
Name: new_cases, dtype: float64
13165 13172    191.0
Name: new_cases, dtype: float64
13166 13173    198.0
Name: new_cases, dtype: float64
13167 13174    187.0
Name: new_cases, dtype: float64
13168 13175    192.0
Name: new_cases, dtype: float64
13169 13176    211.0
Name: new_cases, dtype: float64
13170 13177    224.0
Name: new_cases, dtype: float64
13171 13178    243.0
Name: new_cases, dtype: float64
13172 13179    231.0
Name: new_cases, dtype: float64
13173 13180    213.0
Name: new_cases, dtype: float64
13174 13181    224.0
Name: new_cases, dtype: float64
13175 13182    206.0
Name: new_cases, dtype: float64
13176 13183    253.0
Name: new_cases, dtype: float64
13177 13184    294.0
Name: new_cases, dtype: float64
13178 13185    306.0
Name: new_cases, dtype: float64
13179 13186    332.0
Name: new_cases, dtype: float64
13180 13187    320.0
Name: new_cases, dtype: float64
13181 13188    337.0
Name: new_cases, dtype: float64
13182 13189    314.0
Name: new_cases, dtype: float64
13183 13190    371.0
Name: new_cases, dtype: float64
13184 13191    388.0
Name: new_cases, dtype: float64
13185 13192    402.0
Name: new_cases, dtype: float64
13186 13193    431.0
Name: new_cases, dtype: float64
13187 13194    0.0
Name: new_cases, dtype: float64
13188 13195    844.0
Name: new_cases, dtype: float64
13189 13196    394.0
Name: new_cases, dtype: float64
13190 13197    415.0
Name: new_cases, dtype: float64
13191 13198    477.0
Name: new_cases, dtype: float64
13192 13199    489.0
Name: new_cases, dtype: float64
13193 13200    0.0
Name: new_cases, dtype: float64
13194 13201    1063.0
Name: new_cases, dtype: float64
13195 13202    464.0
Name: new_cases, dtype: float64
13196 13203    526.0
Name: new_cases, dtype: float64
13197 13204    597.0
Name: new_cases, dtype: float64
13198 13205    613.0
Name: new_cases, dtype: float64
13199 13206    658.0
Name: new_cases, dtype: float64
13200 13207    671.0
Name: new_cases, dtype: float64
13201 13208    635.0
Name: new_cases, dtype: float64
13202 13209    592.0
Name: new_cases, dtype: float64
13203 13210    619.0
Name: new_cases, dtype: float64
13204 13211    733.0
Name: new_cases, dtype: float64
13205 13212    738.0
Name: new_cases, dtype: float64
13206 13213    787.0
Name: new_cases, dtype: float64
13207 13214    811.0
Name: new_cases, dtype: float64
13208 13215    845.0
Name: new_cases, dtype: float64
13209 13216    884.0
Name: new_cases, dtype: float64
13210 13217    902.0
Name: new_cases, dtype: float64
13211 13218    936.0
Name: new_cases, dtype: float64
13212 13219    984.0
Name: new_cases, dtype: float64
13213 13220    970.0
Name: new_cases, dtype: float64
13214 13221    983.0
Name: new_cases, dtype: float64
13215 13222    977.0
Name: new_cases, dtype: float64
13216 13223    941.0
Name: new_cases, dtype: float64
13217 13224    929.0
Name: new_cases, dtype: float64
13218 13225    984.0
Name: new_cases, dtype: float64
13219 13226    982.0
Name: new_cases, dtype: float64
13220 13227    991.0
Name: new_cases, dtype: float64
13221 13228    997.0
Name: new_cases, dtype: float64
13222 13229    996.0
Name: new_cases, dtype: float64
13223 13230    983.0
Name: new_cases, dtype: float64

13224 13231    1038.0
Name: new_cases, dtype: float64
13225 13232    1057.0
Name: new_cases, dtype: float64
13226 13233    1098.0
Name: new_cases, dtype: float64
13227 13234    1167.0
Name: new_cases, dtype: float64
13228 13235    1248.0
Name: new_cases, dtype: float64
13229 13236    1315.0
Name: new_cases, dtype: float64
13230 13237    1263.0
Name: new_cases, dtype: float64
13231 13238    1251.0
Name: new_cases, dtype: float64
13232 13239    1309.0
Name: new_cases, dtype: float64
13233 13240    1382.0
Name: new_cases, dtype: float64
13234 13241    1457.0
Name: new_cases, dtype: float64
13235 13242    1588.0
Name: new_cases, dtype: float64
13236 13243    1564.0
Name: new_cases, dtype: float64
13237 13244    1483.0
Name: new_cases, dtype: float64
13238 13245    1471.0
Name: new_cases, dtype: float64
13239 13246    1496.0
Name: new_cases, dtype: float64
13240 13247    1563.0
Name: new_cases, dtype: float64
13241 13248    1621.0
Name: new_cases, dtype: float64
13242 13249    1691.0
Name: new_cases, dtype: float64
13243 13250    1684.0
Name: new_cases, dtype: float64
13244 13251    1639.0
Name: new_cases, dtype: float64
13245 13252    1572.0
Name: new_cases, dtype: float64
13246 13253    1689.0
Name: new_cases, dtype: float64
13247 13254    1701.0
Name: new_cases, dtype: float64
13248 13255    1774.0
Name: new_cases, dtype: float64
13249 13256    1896.0
Name: new_cases, dtype: float64
13250 13257    1878.0
Name: new_cases, dtype: float64
13251 13258    1796.0
Name: new_cases, dtype: float64
13252 13259    1649.0
Name: new_cases, dtype: float64
13253 13260    1851.0
Name: new_cases, dtype: float64
13254 13261    1939.0
Name: new_cases, dtype: float64
13255 13262    1967.0
Name: new_cases, dtype: float64
13256 13263    1975.0
Name: new_cases, dtype: float64
13257 13264    1961.0
Name: new_cases, dtype: float64
13258 13265    1853.0
Name: new_cases, dtype: float64
13259 13266    1911.0
Name: new_cases, dtype: float64
13260 13267    1838.0
Name: new_cases, dtype: float64
13261 13268    1834.0
Name: new_cases, dtype: float64
13262 13269    1917.0
Name: new_cases, dtype: float64
13263 13270    1931.0
Name: new_cases, dtype: float64
13264 13271    1944.0
Name: new_cases, dtype: float64
13265 13272    1893.0
Name: new_cases, dtype: float64
13266 13273    1858.0
Name: new_cases, dtype: float64
13267 13274    1922.0
Name: new_cases, dtype: float64
13268 13275    1917.0
Name: new_cases, dtype: float64
13269 13276    1893.0
Name: new_cases, dtype: float64
13270 13277    1916.0
Name: new_cases, dtype: float64
13271 13278    1825.0
Name: new_cases, dtype: float64
13272 13279    1841.0
Name: new_cases, dtype: float64
13273 13280    1816.0
Name: new_cases, dtype: float64
13274 13281    1957.0
Name: new_cases, dtype: float64
13275 13282    1923.0
Name: new_cases, dtype: float64
13276 13283    1939.0
Name: new_cases, dtype: float64
13277 13284    1902.0
Name: new_cases, dtype: float64
13278 13285    1837.0
Name: new_cases, dtype: float64
13279 13286    1869.0
Name: new_cases, dtype: float64
13280 13287    1273.0
Name: new_cases, dtype: float64
13281 13288    1854.0
Name: new_cases, dtype: float64
13282 13289    1838.0
Name: new_cases, dtype: float64
13283 13290    1805.0
Name: new_cases, dtype: float64
13284 13291    1767.0
Name: new_cases, dtype: float64
13285 13292    1833.0
Name: new_cases, dtype: float64
13286 13293    1792.0
Name: new_cases, dtype: float64
13287 13294    1731.0
Name: new_cases, dtype: float64
13288 13295    1972.0
Name: new_cases, dtype: float64
13289 13296    1967.0
Name: new_cases, dtype: float64
13290 13297    1941.0
Name: new_cases, dtype: float64
13291 13298    1933.0
Name: new_cases, dtype: float64
13292 13299    1924.0
Name: new_cases, dtype: float64
13293 13300    1899.0
Name: new_cases, dtype: float64
13294 13301    1356.0
Name: new_cases, dtype: float64
13295 13302    1778.0
Name: new_cases, dtype: float64
13296 13303    1804.0
Name: new_cases, dtype: float64
13297 13304    1813.0
Name: new_cases, dtype: float64
13298 13305    1748.0
Name: new_cases, dtype: float64
13299 13306    1752.0
Name: new_cases, dtype: float64
13300 13307    1024.0
Name: new_cases, dtype: float64
13301 13308    847.0
Name: new_cases, dtype: float64
13302 13309    1651.0
Name: new_cases, dtype: float64
13303 13310    1718.0
Name: new_cases, dtype: float64
13304 13311    1867.0
Name: new_cases, dtype: float64
13305 13312    1852.0
Name: new_cases, dtype: float64
13306 13313    1766.0
Name: new_cases, dtype: float64
13307 13314    959.0
Name: new_cases, dtype: float64
13308 13315    699.0
Name: new_cases, dtype: float64
13309 13316    1711.0
Name: new_cases, dtype: float64
13310 13317    1708.0
Name: new_cases, dtype: float64
13311 13318    1759.0
Name: new_cases, dtype: float64
13312 13319    1787.0
Name: new_cases, dtype: float64
13313 13320    1732.0
Name: new_cases, dtype: float64
13314 13321    808.0
Name: new_cases, dtype: float64
13315 13322    561.0
Name: new_cases, dtype: float64
13316 13323    1799.0
Name: new_cases, dtype: float64
13317 13324    1692.0
Name: new_cases, dtype: float64
13318 13325    1733.0
Name: new_cases, dtype: float64
13319 13326    1745.0
Name: new_cases, dtype: float64
13320 13327    1658.0
Name: new_cases, dtype: float64
13321 13328    1100.0
Name: new_cases, dtype: float64
13322 13329    1134.0
Name: new_cases, dtype: float64
13323 13330    1352.0
Name: new_cases, dtype: float64
13324 13331    1386.0
Name: new_cases, dtype: float64
13325 13332    1663.0
Name: new_cases, dtype: float64
13326 13333    1668.0
Name: new_cases, dtype: float64
13327 13334    1322.0
Name: new_cases, dtype: float64
13328 13335    1144.0
Name: new_cases, dtype: float64
13329 13336    972.0
Name: new_cases, dtype: float64
13330 13337    1279.0
Name: new_cases, dtype: float64
13331 13338    1191.0
Name: new_cases, dtype: float64
13332 13339    1602.0
Name: new_cases, dtype: float64
13333 13340    1459.0
Name: new_cases, dtype: float64
13334 13341    1347.0
Name: new_cases, dtype: float64
13335 13342    961.0
Name: new_cases, dtype: float64
13336 13343    869.0
Name: new_cases, dtype: float64
13337 13344    1311.0
Name: new_cases, dtype: float64
13338 13345    1174.0
Name: new_cases, dtype: float64
13339 13346    1482.0
Name: new_cases, dtype: float64
13340 13347    1329.0
Name: new_cases, dtype: float64
13341 13348    1079.0
Name: new_cases, dtype: float64
13342 13349    930.0
Name: new_cases, dtype: float64
13343 13350    1073.0
Name: new_cases, dtype: float64
13344 13351    609.0
Name: new_cases, dtype: float64
13345 13352    837.0
Name: new_cases, dtype: float64
13346 13353    1186.0
Name: new_cases, dtype: float64
13347 13354    1182.0
Name: new_cases, dtype: float64
13348 13355    995.0
Name: new_cases, dtype: float64
13349 13356    947.0
Name: new_cases, dtype: float64
13350 13357    876.0
Name: new_cases, dtype: float64
13351 13358    1124.0
Name: new_cases, dtype: float64
13352 13359    1254.0
Name: new_cases, dtype: float64
13353 13360    1414.0
Name: new_cases, dtype: float64
13354 13361    1355.0
Name: new_cases, dtype: float64
13355 13362    1152.0
Name: new_cases, dtype: float64
13356 13363    983.0
Name: new_cases, dtype: float64
13357 13364    1046.0
Name: new_cases, dtype: float64
13358 13365    1378.0
Name: new_cases, dtype: float64
13359 13366    1141.0
Name: new_cases, dtype: float64
13360 13367    1425.0
Name: new_cases, dtype: float64
13361 13368    1213.0
Name: new_cases, dtype: float64
13362 13369    1050.0
Name: new_cases, dtype: float64
13363 13370    918.0
Name: new_cases, dtype: float64
13364 13371    995.0
Name: new_cases, dtype: float64
13365 13372    1213.0
Name: new_cases, dtype: float64
13366 13373    1236.0
Name: new_cases, dtype: float64
13367 13374    1651.0
Name: new_cases, dtype: float64
13368 13375    1371.0
Name: new_cases, dtype: float64
13369 13376    1239.0
Name: new_cases, dtype: float64
13370 13377    986.0
Name: new_cases, dtype: float64
13371 13378    968.0
Name: new_cases, dtype: float64
13372 13379    1278.0
Name: new_cases, dtype: float64
13373 13380    1272.0
Name: new_cases, dtype: float64
13374 13381    1622.0
Name: new_cases, dtype: float64
13375 13382    1433.0
Name: new_cases, dtype: float64
13376 13383    1175.0
Name: new_cases, dtype: float64
13377 13384    843.0
Name: new_cases, dtype: float64
13378 13385    754.0
Name: new_cases, dtype: float64
13379 13386    1166.0
Name: new_cases, dtype: float64
13380 13387    1222.0
Name: new_cases, dtype: float64
13381 13388    1516.0
Name: new_cases, dtype: float64
13382 13389    1384.0
Name: new_cases, dtype: float64
13383 13390    1300.0
Name: new_cases, dtype: float64
13384 13391    887.0
Name: new_cases, dtype: float64
13385 13392    888.0
Name: new_cases, dtype: float64
13386 13393    1318.0
Name: new_cases, dtype: float64

13387 13394    1170.0
Name: new_cases, dtype: float64
13388 13395    1735.0
Name: new_cases, dtype: float64
13389 13396    1453.0
Name: new_cases, dtype: float64
13390 13397    1276.0
Name: new_cases, dtype: float64
13391 13398    896.0
Name: new_cases, dtype: float64
13392 13399    823.0
Name: new_cases, dtype: float64
13393 13400    1255.0
Name: new_cases, dtype: float64
13394 13401    1309.0
Name: new_cases, dtype: float64
13395 13402    1505.0
Name: new_cases, dtype: float64
13396 13403    1244.0
Name: new_cases, dtype: float64
13397 13404    1081.0
Name: new_cases, dtype: float64
13398 13405    834.0
Name: new_cases, dtype: float64
13399 13406    697.0
Name: new_cases, dtype: float64
13400 13407    1138.0
Name: new_cases, dtype: float64
13401 13408    1219.0
Name: new_cases, dtype: float64
13402 13409    1354.0
Name: new_cases, dtype: float64
13403 13410    1369.0
Name: new_cases, dtype: float64
13404 13411    1214.0
Name: new_cases, dtype: float64
13405 13412    879.0
Name: new_cases, dtype: float64
13406 13413    742.0
Name: new_cases, dtype: float64
13407 13414    896.0
Name: new_cases, dtype: float64
13408 13415    837.0
Name: new_cases, dtype: float64
13409 13416    1109.0
Name: new_cases, dtype: float64
13410 13417    1363.0
Name: new_cases, dtype: float64
13411 13418    1627.0
Name: new_cases, dtype: float64
13412 13419    1191.0
Name: new_cases, dtype: float64
13413 13420    1179.0
Name: new_cases, dtype: float64
13414 13421    1378.0
Name: new_cases, dtype: float64
13415 13422    1457.0
Name: new_cases, dtype: float64
13416 13423    1756.0
Name: new_cases, dtype: float64
13417 13424    1471.0
Name: new_cases, dtype: float64
13418 13425    1252.0
Name: new_cases, dtype: float64
13419 13426    953.0
Name: new_cases, dtype: float64
13420 13427    840.0
Name: new_cases, dtype: float64
13421 13428    1169.0
Name: new_cases, dtype: float64
13422 13429    1216.0
Name: new_cases, dtype: float64
13423 13430    1434.0
Name: new_cases, dtype: float64
13424 13431    992.0
Name: new_cases, dtype: float64
13425 13432    1178.0
Name: new_cases, dtype: float64
13426 13433    632.0
Name: new_cases, dtype: float64
13427 13434    636.0
Name: new_cases, dtype: float64
13428 13435    915.0
Name: new_cases, dtype: float64
13429 13436    879.0
Name: new_cases, dtype: float64
13430 13437    1183.0
Name: new_cases, dtype: float64
13431 13438    857.0
Name: new_cases, dtype: float64
13432 13439    943.0
Name: new_cases, dtype: float64
13433 13440    570.0
Name: new_cases, dtype: float64
13434 13441    597.0
Name: new_cases, dtype: float64
13435 13442    834.0
Name: new_cases, dtype: float64
13436 13443    966.0
Name: new_cases, dtype: float64
13437 13444    1026.0
Name: new_cases, dtype: float64
13438 13445    895.0
Name: new_cases, dtype: float64
13439 13446    923.0
Name: new_cases, dtype: float64
13440 13447    697.0
Name: new_cases, dtype: float64
13441 13448    501.0
Name: new_cases, dtype: float64
13442 13449    887.0
Name: new_cases, dtype: float64
13443 13450    873.0
Name: new_cases, dtype: float64
13444 13451    764.0
Name: new_cases, dtype: float64
13445 13452    711.0
Name: new_cases, dtype: float64
13446 13453    582.0
Name: new_cases, dtype: float64
13447 13454    475.0
Name: new_cases, dtype: float64
13448 13455    398.0
Name: new_cases, dtype: float64
13449 13456    802.0
Name: new_cases, dtype: float64
13450 13457    786.0
Name: new_cases, dtype: float64
13451 13458    813.0
Name: new_cases, dtype: float64
13452 13459    778.0
Name: new_cases, dtype: float64
13453 13460    609.0
Name: new_cases, dtype: float64
13454 13461    441.0
Name: new_cases, dtype: float64
13455 13462    495.0
Name: new_cases, dtype: float64
13456 13463    914.0
Name: new_cases, dtype: float64
13457 13464    1023.0
Name: new_cases, dtype: float64
13458 13465    1118.0
Name: new_cases, dtype: float64
13459 13466    1076.0
Name: new_cases, dtype: float64
13460 13467    944.0
Name: new_cases, dtype: float64
13461 13468    614.0
Name: new_cases, dtype: float64
13462 13469    557.0
Name: new_cases, dtype: float64
13463 13470    998.0
Name: new_cases, dtype: float64
13464 13471    1035.0
Name: new_cases, dtype: float64
13465 13472    1250.0
Name: new_cases, dtype: float64
13466 13473    1082.0
Name: new_cases, dtype: float64
13467 13474    1020.0
Name: new_cases, dtype: float64
13468 13475    689.0
Name: new_cases, dtype: float64
13469 13476    586.0
Name: new_cases, dtype: float64
13470 13477    940.0
Name: new_cases, dtype: float64
13471 13478    991.0
Name: new_cases, dtype: float64
13472 13479    1276.0
Name: new_cases, dtype: float64
13473 13480    1021.0
Name: new_cases, dtype: float64
13474 13481    953.0
Name: new_cases, dtype: float64
13475 13482    658.0
Name: new_cases, dtype: float64
13476 13483    600.0
Name: new_cases, dtype: float64
13477 13484    975.0
Name: new_cases, dtype: float64
13478 13485    1069.0
Name: new_cases, dtype: float64
13479 13486    1103.0
Name: new_cases, dtype: float64
13480 13487    1061.0
Name: new_cases, dtype: float64
13481 13488    880.0
Name: new_cases, dtype: float64
13482 13489    648.0
Name: new_cases, dtype: float64
13483 13490    525.0
Name: new_cases, dtype: float64
13484 13491    950.0
Name: new_cases, dtype: float64
13485 13492    1033.0
Name: new_cases, dtype: float64
13486 13493    1184.0
Name: new_cases, dtype: float64
13487 13494    992.0
Name: new_cases, dtype: float64
13488 13495    958.0
Name: new_cases, dtype: float64
13489 13496    756.0
Name: new_cases, dtype: float64
13490 13497    581.0
Name: new_cases, dtype: float64
13491 13498    967.0
Name: new_cases, dtype: float64
13492 13499    1143.0
Name: new_cases, dtype: float64
13493 13500    1295.0
Name: new_cases, dtype: float64
13494 13501    1213.0
Name: new_cases, dtype: float64
13495 13502    979.0
Name: new_cases, dtype: float64
13496 13503    742.0
Name: new_cases, dtype: float64
13497 13504    607.0
Name: new_cases, dtype: float64
13498 13505    966.0
Name: new_cases, dtype: float64
13499 13506    1175.0
Name: new_cases, dtype: float64
13500 13507    1425.0
Name: new_cases, dtype: float64
13501 13508    1151.0
Name: new_cases, dtype: float64
13502 13509    1305.0
Name: new_cases, dtype: float64
13503 13510    894.0
Name: new_cases, dtype: float64
13504 13511    597.0
Name: new_cases, dtype: float64
13505 13512    1061.0
Name: new_cases, dtype: float64
13506 13513    1355.0
Name: new_cases, dtype: float64
13507 13514    1738.0
Name: new_cases, dtype: float64
13508 13515    1467.0
Name: new_cases, dtype: float64
13509 13516    1302.0
Name: new_cases, dtype: float64
13510 13517    918.0
Name: new_cases, dtype: float64
13511 13518    860.0
Name: new_cases, dtype: float64
13512 13519    1357.0
Name: new_cases, dtype: float64
13513 13520    1551.0
Name: new_cases, dtype: float64
13514 13521    1862.0
Name: new_cases, dtype: float64
13515 13522    1636.0
Name: new_cases, dtype: float64
13516 13523    1405.0
Name: new_cases, dtype: float64
13517 13524    1058.0
Name: new_cases, dtype: float64
13518 13525    1168.0
Name: new_cases, dtype: float64
13519 13526    1699.0
Name: new_cases, dtype: float64
13520 13527    1836.0
Name: new_cases, dtype: float64
13521 13528    1950.0
Name: new_cases, dtype: float64
13522 13529    1946.0
Name: new_cases, dtype: float64
13523 13530    1963.0
Name: new_cases, dtype: float64
13524 13531    1473.0
Name: new_cases, dtype: float64
13525 13532    1419.0
Name: new_cases, dtype: float64
13526 13533    1760.0
Name: new_cases, dtype: float64
13527 13534    1842.0
Name: new_cases, dtype: float64
13528 13535    1859.0
Name: new_cases, dtype: float64
13529 13536    1887.0
Name: new_cases, dtype: float64
13530 13537    1907.0
Name: new_cases, dtype: float64
13531 13538    1888.0
Name: new_cases, dtype: float64
13532 13539    1630.0
Name: new_cases, dtype: float64
13533 13540    1923.0
Name: new_cases, dtype: float64
13534 13541    1967.0
Name: new_cases, dtype: float64
13535 13542    1979.0
Name: new_cases, dtype: float64
13536 13543    1986.0
Name: new_cases, dtype: float64
13537 13544    1982.0
Name: new_cases, dtype: float64
13538 13545    1941.0
Name: new_cases, dtype: float64
13539 13546    1917.0
Name: new_cases, dtype: float64
13540 13547    1989.0
Name: new_cases, dtype: float64
13541 13548    1973.0
Name: new_cases, dtype: float64
13542 13549    1994.0
Name: new_cases, dtype: float64
13543 13550    1987.0
Name: new_cases, dtype: float64
13544 13551    1974.0
Name: new_cases, dtype: float64
13545 13552    1946.0
Name: new_cases, dtype: float64
13546 13553    1955.0
Name: new_cases, dtype: float64
13547 13554    1993.0
Name: new_cases, dtype: float64
13548 13555    1989.0
Name: new_cases, dtype: float64
13549 13556    1993.0
Name: new_cases, dtype: float64
13550 13557    1998.0
Name: new_cases, dtype: float64
13551 13558    1899.0
Name: new_cases, dtype: float64
13552 13559    1867.0
Name: new_cases, dtype: float64
13553 13560    1983.0
Name: new_cases, dtype: float64
13554 13561    1991.0
Name: new_cases, dtype: float64

13555 13562    1983.0
Name: new_cases, dtype: float64
13556 13563    1995.0
Name: new_cases, dtype: float64
13557 13564    1998.0
Name: new_cases, dtype: float64
13558 13565    1979.0
Name: new_cases, dtype: float64
13559 13566    1943.0
Name: new_cases, dtype: float64
13560 13567    2038.0
Name: new_cases, dtype: float64
13561 13568    2060.0
Name: new_cases, dtype: float64
13562 13569    2052.0
Name: new_cases, dtype: float64
13563 13570    2073.0
Name: new_cases, dtype: float64
13564 13571    2068.0
Name: new_cases, dtype: float64
13565 13572    1981.0
Name: new_cases, dtype: float64
13566 13573    1956.0
Name: new_cases, dtype: float64
13567 13574    1913.0
Name: new_cases, dtype: float64
13568 13575    2076.0
Name: new_cases, dtype: float64
13569 13576    2097.0
Name: new_cases, dtype: float64
13570 13577    2082.0
Name: new_cases, dtype: float64
13571 13578    2079.0
Name: new_cases, dtype: float64
13572 13579    2044.0
Name: new_cases, dtype: float64
13573 13580    1997.0
Name: new_cases, dtype: float64
13574 13581    1995.0
Name: new_cases, dtype: float64
13575 13582    1998.0
Name: new_cases, dtype: float64
13576 13583    1979.0
Name: new_cases, dtype: float64
13577 13584    1988.0
Name: new_cases, dtype: float64
13578 13585    1992.0
Name: new_cases, dtype: float64
13579 13586    1985.0
Name: new_cases, dtype: float64
13580 13587    1890.0
Name: new_cases, dtype: float64
13581 13588    1979.0
Name: new_cases, dtype: float64
13582 13589    1996.0
Name: new_cases, dtype: float64
13583 13590    1998.0
Name: new_cases, dtype: float64
13584 13591    1991.0
Name: new_cases, dtype: float64
13585 13592    1993.0
Name: new_cases, dtype: float64
13586 13593    1912.0
Name: new_cases, dtype: float64
13587 13594    1887.0
Name: new_cases, dtype: float64
13588 13595    1905.0
Name: new_cases, dtype: float64
13589 13596    1989.0
Name: new_cases, dtype: float64
13590 13597    1981.0
Name: new_cases, dtype: float64
13591 13598    1939.0
Name: new_cases, dtype: float64
13592 13599    1964.0
Name: new_cases, dtype: float64
13593 13600    1886.0
Name: new_cases, dtype: float64
13594 13601    1793.0
Name: new_cases, dtype: float64
13595 13602    1754.0
Name: new_cases, dtype: float64
13596 13603    1862.0
Name: new_cases, dtype: float64
13597 13604    1844.0
Name: new_cases, dtype: float64
13598 13605    1812.0
Name: new_cases, dtype: float64
13599 13606    1859.0
Name: new_cases, dtype: float64
13600 13607    1804.0
Name: new_cases, dtype: float64
13601 13608    1713.0
Name: new_cases, dtype: float64
13602 13609    1453.0
Name: new_cases, dtype: float64
13603 13610    1697.0
Name: new_cases, dtype: float64
13604 13611    1674.0
Name: new_cases, dtype: float64
13605 13612    1729.0
Name: new_cases, dtype: float64
13606 13613    1696.0
Name: new_cases, dtype: float64
13607 13614    1671.0
Name: new_cases, dtype: float64
13608 13615    1484.0
Name: new_cases, dtype: float64
13609 13616    1395.0
Name: new_cases, dtype: float64
13610 13617    1792.0
Name: new_cases, dtype: float64
13611 13618    1818.0
Name: new_cases, dtype: float64
13612 13619    1876.0
Name: new_cases, dtype: float64
13613 13620    1852.0
Name: new_cases, dtype: float64
13614 13621    1757.0
Name: new_cases, dtype: float64
13615 13622    1312.0
Name: new_cases, dtype: float64
13616 13623    1012.0
Name: new_cases, dtype: float64
13617 13624    1756.0
Name: new_cases, dtype: float64
13618 13625    1738.0
Name: new_cases, dtype: float64
13619 13626    1801.0
Name: new_cases, dtype: float64
13620 13627    1837.0
Name: new_cases, dtype: float64
13621 13628    1454.0
Name: new_cases, dtype: float64
13622 13629    1011.0
Name: new_cases, dtype: float64
13623 13630    778.0
Name: new_cases, dtype: float64
13624 13631    1765.0
Name: new_cases, dtype: float64
13625 13632    1596.0
Name: new_cases, dtype: float64
13626 13633    1644.0
Name: new_cases, dtype: float64
13627 13634    1655.0
Name: new_cases, dtype: float64
13628 13635    1456.0
Name: new_cases, dtype: float64
13629 13636    834.0
Name: new_cases, dtype: float64
13630 13637    832.0
Name: new_cases, dtype: float64
13631 13638    1654.0
Name: new_cases, dtype: float64
13632 13639    1203.0
Name: new_cases, dtype: float64
13633 13640    1921.0
Name: new_cases, dtype: float64
13634 13641    1529.0
Name: new_cases, dtype: float64
13635 13642    983.0
Name: new_cases, dtype: float64
13636 13643    642.0
Name: new_cases, dtype: float64
13637 13644    501.0
Name: new_cases, dtype: float64
13638 13645    1493.0
Name: new_cases, dtype: float64
13639 13646    1380.0
Name: new_cases, dtype: float64
13640 13647    1510.0
Name: new_cases, dtype: float64
13641 13648    1311.0
Name: new_cases, dtype: float64
13642 13649    771.0
Name: new_cases, dtype: float64
13643 13650    507.0
Name: new_cases, dtype: float64
13644 13651    675.0
Name: new_cases, dtype: float64
13645 13652    1133.0
Name: new_cases, dtype: float64
13646 13653    1400.0
Name: new_cases, dtype: float64
13647 13654    1623.0
Name: new_cases, dtype: float64
13648 13655    1184.0
Name: new_cases, dtype: float64
13649 Series([], Name: new_cases, dtype: float64)
13650 Series([], Name: new_cases, dtype: float64)
13651 Series([], Name: new_cases, dtype: float64)
13652 Series([], Name: new_cases, dtype: float64)
13653 Series([], Name: new_cases, dtype: float64)
13654 Series([], Name: new_cases, dtype: float64)
13655 Series([], Name: new_cases, dtype: float64)
13656 13663    0.0
Name: new_cases, dtype: float64
13657 13664    0.0
Name: new_cases, dtype: float64
13658 13665    0.0
Name: new_cases, dtype: float64
13659 13666    0.0
Name: new_cases, dtype: float64
13660 13667    0.0
Name: new_cases, dtype: float64
13661 13668    0.0
Name: new_cases, dtype: float64
13662 13669    0.0
Name: new_cases, dtype: float64
13663 13670    0.0
Name: new_cases, dtype: float64
13664 13671    0.0
Name: new_cases, dtype: float64
13665 13672    0.0
Name: new_cases, dtype: float64
13666 13673    0.0
Name: new_cases, dtype: float64
13667 13674    0.0
Name: new_cases, dtype: float64
13668 13675    0.0
Name: new_cases, dtype: float64
13669 13676    0.0
Name: new_cases, dtype: float64
13670 13677    0.0
Name: new_cases, dtype: float64
13671 13678    0.0
Name: new_cases, dtype: float64
13672 13679    0.0
Name: new_cases, dtype: float64
13673 13680    0.0
Name: new_cases, dtype: float64
13674 13681    0.0
Name: new_cases, dtype: float64
13675 13682    1.0
Name: new_cases, dtype: float64
13676 13683    6.0
Name: new_cases, dtype: float64
13677 13684    5.0
Name: new_cases, dtype: float64
13678 13685    10.0
Name: new_cases, dtype: float64
13679 13686    27.0
Name: new_cases, dtype: float64
13680 13687    59.0
Name: new_cases, dtype: float64
13681 13688    60.0
Name: new_cases, dtype: float64
13682 13689    31.0
Name: new_cases, dtype: float64
13683 13690    39.0
Name: new_cases, dtype: float64
13684 13691    28.0
Name: new_cases, dtype: float64
13685 13692    47.0
Name: new_cases, dtype: float64
13686 13693    0.0
Name: new_cases, dtype: float64
13687 13694    245.0
Name: new_cases, dtype: float64
13688 13695    130.0
Name: new_cases, dtype: float64
13689 13696    197.0
Name: new_cases, dtype: float64
13690 13697    172.0
Name: new_cases, dtype: float64
13691 13698    185.0
Name: new_cases, dtype: float64
13692 13699    243.0
Name: new_cases, dtype: float64
13693 13700    309.0
Name: new_cases, dtype: float64
13694 13701    462.0
Name: new_cases, dtype: float64
13695 13702    558.0
Name: new_cases, dtype: float64
13696 13703    586.0
Name: new_cases, dtype: float64
13697 13704    342.0
Name: new_cases, dtype: float64
13698 13705    526.0
Name: new_cases, dtype: float64
13699 13706    668.0
Name: new_cases, dtype: float64
13700 13707    1298.0
Name: new_cases, dtype: float64
13701 13708    1049.0
Name: new_cases, dtype: float64
13702 13709    1850.0
Name: new_cases, dtype: float64
13703 13710    1702.0
Name: new_cases, dtype: float64
13704 13711    1063.0
Name: new_cases, dtype: float64
13705 13712    876.0
Name: new_cases, dtype: float64
13706 13713    1189.0
Name: new_cases, dtype: float64
13707 13714    1384.0
Name: new_cases, dtype: float64
13708 13715    1422.0
Name: new_cases, dtype: float64
13709 13716    1661.0
Name: new_cases, dtype: float64
13710 13717    1260.0
Name: new_cases, dtype: float64
13711 13718    1123.0
Name: new_cases, dtype: float64
13712 13719    1380.0
Name: new_cases, dtype: float64
13713 13720    1209.0
Name: new_cases, dtype: float64
13714 13721    1580.0
Name: new_cases, dtype: float64
13715 13722    1684.0
Name: new_cases, dtype: float64
13716 13723    1351.0
Name: new_cases, dtype: float64

13717 13724    1629.0
Name: new_cases, dtype: float64
13718 13725    942.0
Name: new_cases, dtype: float64
13719 13726    530.0
Name: new_cases, dtype: float64
13720 13727    2454.0
Name: new_cases, dtype: float64
13721 13728    1236.0
Name: new_cases, dtype: float64
13722 13729    1329.0
Name: new_cases, dtype: float64
13723 13730    1045.0
Name: new_cases, dtype: float64
13724 13731    1313.0
Name: new_cases, dtype: float64
13725 13732    1487.0
Name: new_cases, dtype: float64
13726 13733    973.0
Name: new_cases, dtype: float64
13727 13734    933.0
Name: new_cases, dtype: float64
13728 13735    908.0
Name: new_cases, dtype: float64
13729 13736    1496.0
Name: new_cases, dtype: float64
13730 13737    1032.0
Name: new_cases, dtype: float64
13731 13738    809.0
Name: new_cases, dtype: float64
13732 13739    553.0
Name: new_cases, dtype: float64
13733 13740    647.0
Name: new_cases, dtype: float64
13734 13741    525.0
Name: new_cases, dtype: float64
13735 13742    660.0
Name: new_cases, dtype: float64
13736 13743    513.0
Name: new_cases, dtype: float64
13737 13744    485.0
Name: new_cases, dtype: float64
13738 13745    389.0
Name: new_cases, dtype: float64
13739 13746    361.0
Name: new_cases, dtype: float64
13740 13747    242.0
Name: new_cases, dtype: float64
13741 13748    272.0
Name: new_cases, dtype: float64
13742 13749    639.0
Name: new_cases, dtype: float64
13743 13750    591.0
Name: new_cases, dtype: float64
13744 13751    585.0
Name: new_cases, dtype: float64
13745 13752    485.0
Name: new_cases, dtype: float64
13746 13753    368.0
Name: new_cases, dtype: float64
13747 13754    330.0
Name: new_cases, dtype: float64
13748 13755    202.0
Name: new_cases, dtype: float64
13749 13756    307.0
Name: new_cases, dtype: float64
13750 13757    356.0
Name: new_cases, dtype: float64
13751 13758    345.0
Name: new_cases, dtype: float64
13752 13759    291.0
Name: new_cases, dtype: float64
13753 13760    279.0
Name: new_cases, dtype: float64
13754 13761    232.0
Name: new_cases, dtype: float64
13755 13762    192.0
Name: new_cases, dtype: float64
13756 13763    252.0
Name: new_cases, dtype: float64
13757 13764    276.0
Name: new_cases, dtype: float64
13758 13765    299.0
Name: new_cases, dtype: float64
13759 13766    282.0
Name: new_cases, dtype: float64
13760 13767    250.0
Name: new_cases, dtype: float64
13761 13768    113.0
Name: new_cases, dtype: float64
13762 13769    137.0
Name: new_cases, dtype: float64
13763 13770    257.0
Name: new_cases, dtype: float64
13764 13771    212.0
Name: new_cases, dtype: float64
13765 13772    125.0
Name: new_cases, dtype: float64
13766 13773    195.0
Name: new_cases, dtype: float64
13767 13774    136.0
Name: new_cases, dtype: float64
13768 13775    98.0
Name: new_cases, dtype: float64
13769 13776    70.0
Name: new_cases, dtype: float64
13770 13777    82.0
Name: new_cases, dtype: float64
13771 13778    140.0
Name: new_cases, dtype: float64
13772 13779    165.0
Name: new_cases, dtype: float64
13773 13780    154.0
Name: new_cases, dtype: float64
13774 13781    122.0
Name: new_cases, dtype: float64
13775 13782    89.0
Name: new_cases, dtype: float64
13776 13783    132.0
Name: new_cases, dtype: float64
13777 13784    142.0
Name: new_cases, dtype: float64
13778 13785    108.0
Name: new_cases, dtype: float64
13779 13786    99.0
Name: new_cases, dtype: float64
13780 13787    111.0
Name: new_cases, dtype: float64
13781 13788    71.0
Name: new_cases, dtype: float64
13782 13789    55.0
Name: new_cases, dtype: float64
13783 13790    89.0
Name: new_cases, dtype: float64
13784 13791    104.0
Name: new_cases, dtype: float64
13785 13792    128.0
Name: new_cases, dtype: float64
13786 13793    74.0
Name: new_cases, dtype: float64
13787 13794    0.0
Name: new_cases, dtype: float64
13788 13795    0.0
Name: new_cases, dtype: float64
13789 13796    260.0
Name: new_cases, dtype: float64
13790 13797    88.0
Name: new_cases, dtype: float64
13791 13798    109.0
Name: new_cases, dtype: float64
13792 13799    99.0
Name: new_cases, dtype: float64
13793 13800    103.0
Name: new_cases, dtype: float64
13794 13801    86.0
Name: new_cases, dtype: float64
13795 13802    66.0
Name: new_cases, dtype: float64
13796 13803    66.0
Name: new_cases, dtype: float64
13797 13804    82.0
Name: new_cases, dtype: float64
13798 13805    89.0
Name: new_cases, dtype: float64
13799 13806    129.0
Name: new_cases, dtype: float64
13800 13807    111.0
Name: new_cases, dtype: float64
13801 13808    178.0
Name: new_cases, dtype: float64
13802 13809    42.0
Name: new_cases, dtype: float64
13803 13810    0.0
Name: new_cases, dtype: float64
13804 13811    65.0
Name: new_cases, dtype: float64
13805 13812    87.0
Name: new_cases, dtype: float64
13806 13813    147.0
Name: new_cases, dtype: float64
13807 13814    112.0
Name: new_cases, dtype: float64
13808 13815    238.0
Name: new_cases, dtype: float64
13809 13816    0.0
Name: new_cases, dtype: float64
13810 13817    74.0
Name: new_cases, dtype: float64
13811 13818    91.0
Name: new_cases, dtype: float64
13812 13819    366.0
Name: new_cases, dtype: float64
13813 13820    261.0
Name: new_cases, dtype: float64
13814 13821    207.0
Name: new_cases, dtype: float64
13815 13822    0.0
Name: new_cases, dtype: float64
13816 13823    388.0
Name: new_cases, dtype: float64
13817 13824    164.0
Name: new_cases, dtype: float64
13818 13825    369.0
Name: new_cases, dtype: float64
13819 13826    220.0
Name: new_cases, dtype: float64
13820 13827    352.0
Name: new_cases, dtype: float64
13821 13828    528.0
Name: new_cases, dtype: float64
13822 13829    299.0
Name: new_cases, dtype: float64
13823 13830    402.0
Name: new_cases, dtype: float64
13824 13831    234.0
Name: new_cases, dtype: float64
13825 13832    673.0
Name: new_cases, dtype: float64
13826 13833    671.0
Name: new_cases, dtype: float64
13827 13834    745.0
Name: new_cases, dtype: float64
13828 13835    651.0
Name: new_cases, dtype: float64
13829 13836    447.0
Name: new_cases, dtype: float64
13830 13837    465.0
Name: new_cases, dtype: float64
13831 13838    334.0
Name: new_cases, dtype: float64
13832 13839    510.0
Name: new_cases, dtype: float64
13833 13840    858.0
Name: new_cases, dtype: float64
13834 13841    768.0
Name: new_cases, dtype: float64
13835 13842    617.0
Name: new_cases, dtype: float64
13836 13843    751.0
Name: new_cases, dtype: float64
13837 13844    468.0
Name: new_cases, dtype: float64
13838 13845    388.0
Name: new_cases, dtype: float64
13839 13846    639.0
Name: new_cases, dtype: float64
13840 13847    544.0
Name: new_cases, dtype: float64
13841 13848    922.0
Name: new_cases, dtype: float64
13842 13849    756.0
Name: new_cases, dtype: float64
13843 13850    454.0
Name: new_cases, dtype: float64
13844 13851    211.0
Name: new_cases, dtype: float64
13845 13852    363.0
Name: new_cases, dtype: float64
13846 13853    582.0
Name: new_cases, dtype: float64
13847 13854    699.0
Name: new_cases, dtype: float64
13848 13855    716.0
Name: new_cases, dtype: float64
13849 13856    574.0
Name: new_cases, dtype: float64
13850 13857    468.0
Name: new_cases, dtype: float64
13851 13858    156.0
Name: new_cases, dtype: float64
13852 13859    355.0
Name: new_cases, dtype: float64
13853 13860    583.0
Name: new_cases, dtype: float64
13854 13861    470.0
Name: new_cases, dtype: float64
13855 13862    452.0
Name: new_cases, dtype: float64
13856 13863    647.0
Name: new_cases, dtype: float64
13857 13864    443.0
Name: new_cases, dtype: float64
13858 13865    194.0
Name: new_cases, dtype: float64
13859 13866    251.0
Name: new_cases, dtype: float64
13860 13867    424.0
Name: new_cases, dtype: float64
13861 13868    633.0
Name: new_cases, dtype: float64
13862 13869    630.0
Name: new_cases, dtype: float64
13863 13870    651.0
Name: new_cases, dtype: float64
13864 13871    542.0
Name: new_cases, dtype: float64
13865 13872    402.0
Name: new_cases, dtype: float64
13866 13873    372.0
Name: new_cases, dtype: float64
13867 13874    550.0
Name: new_cases, dtype: float64
13868 13875    877.0
Name: new_cases, dtype: float64
13869 13876    969.0
Name: new_cases, dtype: float64
13870 13877    941.0
Name: new_cases, dtype: float64
13871 13878    977.0
Name: new_cases, dtype: float64
13872 13879    851.0
Name: new_cases, dtype: float64
13873 13880    489.0
Name: new_cases, dtype: float64
13874 13881    1153.0
Name: new_cases, dtype: float64
13875 13882    2028.0
Name: new_cases, dtype: float64
13876 13883    1673.0
Name: new_cases, dtype: float64
13877 13884    1099.0
Name: new_cases, dtype: float64
13878 13885    1547.0
Name: new_cases, dtype: float64
13879 13886    1097.0
Name: new_cases, dtype: float64
13880 13887    1834.0
Name: new_cases, dtype: float64

13881 13888    1661.0
Name: new_cases, dtype: float64
13882 13889    1881.0
Name: new_cases, dtype: float64
13883 13890    2208.0
Name: new_cases, dtype: float64
13884 13891    1827.0
Name: new_cases, dtype: float64
13885 13892    1376.0
Name: new_cases, dtype: float64
13886 13893    1174.0
Name: new_cases, dtype: float64
13887 13894    1762.0
Name: new_cases, dtype: float64
13888 13895    1337.0
Name: new_cases, dtype: float64
13889 13896    2607.0
Name: new_cases, dtype: float64
13890 13897    3175.0
Name: new_cases, dtype: float64
13891 13898    3389.0
Name: new_cases, dtype: float64
13892 13899    2612.0
Name: new_cases, dtype: float64
13893 13900    1968.0
Name: new_cases, dtype: float64
13894 13901    2088.0
Name: new_cases, dtype: float64
13895 13902    3577.0
Name: new_cases, dtype: float64
13896 13903    5728.0
Name: new_cases, dtype: float64
13897 13904    5385.0
Name: new_cases, dtype: float64
13898 13905    7950.0
Name: new_cases, dtype: float64
13899 13906    5327.0
Name: new_cases, dtype: float64
13900 13907    3622.0
Name: new_cases, dtype: float64
13901 13908    7360.0
Name: new_cases, dtype: float64
13902 13909    8271.0
Name: new_cases, dtype: float64
13903 13910    10448.0
Name: new_cases, dtype: float64
13904 13911    10192.0
Name: new_cases, dtype: float64
13905 13912    10964.0
Name: new_cases, dtype: float64
13906 13913    9138.0
Name: new_cases, dtype: float64
13907 13914    8227.0
Name: new_cases, dtype: float64
13908 13915    9679.0
Name: new_cases, dtype: float64
13909 13916    13227.0
Name: new_cases, dtype: float64
13910 13917    16746.0
Name: new_cases, dtype: float64
13911 13918    17568.0
Name: new_cases, dtype: float64
13912 13919    17709.0
Name: new_cases, dtype: float64
13913 13920    15622.0
Name: new_cases, dtype: float64
13914 13921    12687.0
Name: new_cases, dtype: float64
13915 13922    13571.0
Name: new_cases, dtype: float64
13916 13923    21048.0
Name: new_cases, dtype: float64
13917 13924    23921.0
Name: new_cases, dtype: float64
13918 13925    20056.0
Name: new_cases, dtype: float64
13919 13926    16915.0
Name: new_cases, dtype: float64
13920 13927    11789.0
Name: new_cases, dtype: float64
13921 13928    6337.0
Name: new_cases, dtype: float64
13922 13929    5186.0
Name: new_cases, dtype: float64
13923 13930    15672.0
Name: new_cases, dtype: float64
13924 13931    11128.0
Name: new_cases, dtype: float64
13925 13932    8703.0
Name: new_cases, dtype: float64
13926 13933    6124.0
Name: new_cases, dtype: float64
13927 13934    6621.0
Name: new_cases, dtype: float64
13928 13935    2393.0
Name: new_cases, dtype: float64
13929 13936    4293.0
Name: new_cases, dtype: float64
13930 13937    7916.0
Name: new_cases, dtype: float64
13931 13938    5002.0
Name: new_cases, dtype: float64
13932 13939    4619.0
Name: new_cases, dtype: float64
13933 13940    6268.0
Name: new_cases, dtype: float64
13934 13941    4659.0
Name: new_cases, dtype: float64
13935 13942    1932.0
Name: new_cases, dtype: float64
13936 13943    2734.0
Name: new_cases, dtype: float64
13937 13944    5182.0
Name: new_cases, dtype: float64
13938 13945    4477.0
Name: new_cases, dtype: float64
13939 13946    3416.0
Name: new_cases, dtype: float64
13940 13947    3224.0
Name: new_cases, dtype: float64
13941 13948    1875.0
Name: new_cases, dtype: float64
13942 13949    1123.0
Name: new_cases, dtype: float64
13943 13950    1901.0
Name: new_cases, dtype: float64
13944 13951    3164.0
Name: new_cases, dtype: float64
13945 13952    2565.0
Name: new_cases, dtype: float64
13946 13953    3297.0
Name: new_cases, dtype: float64
13947 13954    3619.0
Name: new_cases, dtype: float64
13948 13955    2151.0
Name: new_cases, dtype: float64
13949 13956    746.0
Name: new_cases, dtype: float64
13950 13957    1867.0
Name: new_cases, dtype: float64
13951 13958    3040.0
Name: new_cases, dtype: float64
13952 13959    2605.0
Name: new_cases, dtype: float64
13953 13960    2582.0
Name: new_cases, dtype: float64
13954 13961    2503.0
Name: new_cases, dtype: float64
13955 13962    1814.0
Name: new_cases, dtype: float64
13956 13963    859.0
Name: new_cases, dtype: float64
13957 13964    1957.0
Name: new_cases, dtype: float64
13958 13965    3071.0
Name: new_cases, dtype: float64
13959 13966    2754.0
Name: new_cases, dtype: float64
13960 13967    0.0
Name: new_cases, dtype: float64
13961 13968    2762.0
Name: new_cases, dtype: float64
13962 13969    4978.0
Name: new_cases, dtype: float64
13963 13970    1074.0
Name: new_cases, dtype: float64
13964 13971    2211.0
Name: new_cases, dtype: float64
13965 13972    3636.0
Name: new_cases, dtype: float64
13966 13973    3146.0
Name: new_cases, dtype: float64
13967 13974    2835.0
Name: new_cases, dtype: float64
13968 13975    2721.0
Name: new_cases, dtype: float64
13969 13976    2170.0
Name: new_cases, dtype: float64
13970 13977    981.0
Name: new_cases, dtype: float64
13971 13978    2198.0
Name: new_cases, dtype: float64
13972 13979    3212.0
Name: new_cases, dtype: float64
13973 13980    2583.0
Name: new_cases, dtype: float64
13974 13981    2342.0
Name: new_cases, dtype: float64
13975 13982    784.0
Name: new_cases, dtype: float64
13976 13983    847.0
Name: new_cases, dtype: float64
13977 13984    857.0
Name: new_cases, dtype: float64
13978 13985    1677.0
Name: new_cases, dtype: float64
13979 13986    2831.0
Name: new_cases, dtype: float64
13980 13987    2254.0
Name: new_cases, dtype: float64
13981 13988    1793.0
Name: new_cases, dtype: float64
13982 13989    880.0
Name: new_cases, dtype: float64
13983 13990    842.0
Name: new_cases, dtype: float64
13984 13991    876.0
Name: new_cases, dtype: float64
13985 13992    1848.0
Name: new_cases, dtype: float64
13986 13993    2997.0
Name: new_cases, dtype: float64
13987 13994    2923.0
Name: new_cases, dtype: float64
13988 13995    2048.0
Name: new_cases, dtype: float64
13989 13996    1991.0
Name: new_cases, dtype: float64
13990 13997    1569.0
Name: new_cases, dtype: float64
13991 13998    960.0
Name: new_cases, dtype: float64
13992 13999    2099.0
Name: new_cases, dtype: float64
13993 14000    2927.0
Name: new_cases, dtype: float64
13994 14001    2637.0
Name: new_cases, dtype: float64
13995 14002    2203.0
Name: new_cases, dtype: float64
13996 14003    2120.0
Name: new_cases, dtype: float64
13997 14004    1630.0
Name: new_cases, dtype: float64
13998 14005    932.0
Name: new_cases, dtype: float64
13999 14006    1479.0
Name: new_cases, dtype: float64
14000 14007    3006.0
Name: new_cases, dtype: float64
14001 14008    2571.0
Name: new_cases, dtype: float64
14002 14009    2444.0
Name: new_cases, dtype: float64
14003 14010    2583.0
Name: new_cases, dtype: float64
14004 14011    1812.0
Name: new_cases, dtype: float64
14005 14012    1192.0
Name: new_cases, dtype: float64
14006 14013    1784.0
Name: new_cases, dtype: float64
14007 14014    3020.0
Name: new_cases, dtype: float64
14008 14015    2775.0
Name: new_cases, dtype: float64
14009 14016    2683.0
Name: new_cases, dtype: float64
14010 14017    2717.0
Name: new_cases, dtype: float64
14011 14018    2316.0
Name: new_cases, dtype: float64
14012 14019    1264.0
Name: new_cases, dtype: float64
14013 14020    1854.0
Name: new_cases, dtype: float64
14014 14021    3124.0
Name: new_cases, dtype: float64
14015 14022    2452.0
Name: new_cases, dtype: float64
14016 14023    2585.0
Name: new_cases, dtype: float64
14017 14024    2438.0
Name: new_cases, dtype: float64
14018 14025    1740.0
Name: new_cases, dtype: float64
14019 14026    873.0
Name: new_cases, dtype: float64
14020 14027    1851.0
Name: new_cases, dtype: float64
14021 14028    2617.0
Name: new_cases, dtype: float64
14022 14029    2149.0
Name: new_cases, dtype: float64
14023 14030    2120.0
Name: new_cases, dtype: float64
14024 14031    1895.0
Name: new_cases, dtype: float64
14025 14032    1516.0
Name: new_cases, dtype: float64
14026 14033    857.0
Name: new_cases, dtype: float64
14027 14034    1717.0
Name: new_cases, dtype: float64
14028 14035    2677.0
Name: new_cases, dtype: float64
14029 14036    2420.0
Name: new_cases, dtype: float64
14030 14037    3437.0
Name: new_cases, dtype: float64
14031 14038    2640.0
Name: new_cases, dtype: float64
14032 14039    2094.0
Name: new_cases, dtype: float64
14033 14040    1121.0
Name: new_cases, dtype: float64
14034 14041    2102.0
Name: new_cases, dtype: float64
14035 14042    3113.0
Name: new_cases, dtype: float64
14036 14043    3076.0
Name: new_cases, dtype: float64
14037 14044    2769.0
Name: new_cases, dtype: float64
14038 14045    2760.0
Name: new_cases, dtype: float64

14039 14046    2097.0
Name: new_cases, dtype: float64
14040 14047    783.0
Name: new_cases, dtype: float64
14041 14048    2050.0
Name: new_cases, dtype: float64
14042 14049    3264.0
Name: new_cases, dtype: float64
14043 14050    2643.0
Name: new_cases, dtype: float64
14044 14051    2759.0
Name: new_cases, dtype: float64
14045 14052    2799.0
Name: new_cases, dtype: float64
14046 14053    2082.0
Name: new_cases, dtype: float64
14047 14054    1117.0
Name: new_cases, dtype: float64
14048 14055    2163.0
Name: new_cases, dtype: float64
14049 14056    3434.0
Name: new_cases, dtype: float64
14050 14057    3503.0
Name: new_cases, dtype: float64
14051 14058    3615.0
Name: new_cases, dtype: float64
14052 14059    3598.0
Name: new_cases, dtype: float64
14053 14060    2962.0
Name: new_cases, dtype: float64
14054 14061    1578.0
Name: new_cases, dtype: float64
14055 14062    3165.0
Name: new_cases, dtype: float64
14056 14063    5116.0
Name: new_cases, dtype: float64
14057 14064    4659.0
Name: new_cases, dtype: float64
14058 14065    5140.0
Name: new_cases, dtype: float64
14059 14066    0.0
Name: new_cases, dtype: float64
14060 14067    9065.0
Name: new_cases, dtype: float64
14061 14068    2232.0
Name: new_cases, dtype: float64
14062 14069    3537.0
Name: new_cases, dtype: float64
14063 14070    6315.0
Name: new_cases, dtype: float64
14064 14071    5518.0
Name: new_cases, dtype: float64
14065 14072    6123.0
Name: new_cases, dtype: float64
14066 14073    5332.0
Name: new_cases, dtype: float64
14067 14074    4694.0
Name: new_cases, dtype: float64
14068 14075    2179.0
Name: new_cases, dtype: float64
14069 14076    3906.0
Name: new_cases, dtype: float64
14070 14077    5611.0
Name: new_cases, dtype: float64
14071 14078    5467.0
Name: new_cases, dtype: float64
14072 14079    4665.0
Name: new_cases, dtype: float64
14073 14080    4889.0
Name: new_cases, dtype: float64
14074 14081    3522.0
Name: new_cases, dtype: float64
14075 14082    1968.0
Name: new_cases, dtype: float64
14076 14083    1709.0
Name: new_cases, dtype: float64
14077 14084    3539.0
Name: new_cases, dtype: float64
14078 14085    4845.0
Name: new_cases, dtype: float64
14079 14086    4860.0
Name: new_cases, dtype: float64
14080 14087    4570.0
Name: new_cases, dtype: float64
14081 14088    2989.0
Name: new_cases, dtype: float64
14082 14089    1753.0
Name: new_cases, dtype: float64
14083 14090    3374.0
Name: new_cases, dtype: float64
14084 14091    4713.0
Name: new_cases, dtype: float64
14085 14092    3993.0
Name: new_cases, dtype: float64
14086 14093    3904.0
Name: new_cases, dtype: float64
14087 14094    3787.0
Name: new_cases, dtype: float64
14088 14095    2996.0
Name: new_cases, dtype: float64
14089 14096    1630.0
Name: new_cases, dtype: float64
14090 14097    3430.0
Name: new_cases, dtype: float64
14091 14098    5113.0
Name: new_cases, dtype: float64
14092 14099    4357.0
Name: new_cases, dtype: float64
14093 14100    3581.0
Name: new_cases, dtype: float64
14094 14101    3934.0
Name: new_cases, dtype: float64
14095 14102    2377.0
Name: new_cases, dtype: float64
14096 14103    1670.0
Name: new_cases, dtype: float64
14097 14104    2946.0
Name: new_cases, dtype: float64
14098 14105    3925.0
Name: new_cases, dtype: float64
14099 14106    3663.0
Name: new_cases, dtype: float64
14100 14107    3607.0
Name: new_cases, dtype: float64
14101 14108    3205.0
Name: new_cases, dtype: float64
14102 14109    2128.0
Name: new_cases, dtype: float64
14103 14110    1334.0
Name: new_cases, dtype: float64
14104 14111    2731.0
Name: new_cases, dtype: float64
14105 14112    4119.0
Name: new_cases, dtype: float64
14106 14113    3518.0
Name: new_cases, dtype: float64
14107 14114    3723.0
Name: new_cases, dtype: float64
14108 14115    3364.0
Name: new_cases, dtype: float64
14109 14116    2258.0
Name: new_cases, dtype: float64
14110 14117    1267.0
Name: new_cases, dtype: float64
14111 14118    2456.0
Name: new_cases, dtype: float64
14112 14119    3251.0
Name: new_cases, dtype: float64
14113 14120    2890.0
Name: new_cases, dtype: float64
14114 14121    1631.0
Name: new_cases, dtype: float64
14115 14122    1967.0
Name: new_cases, dtype: float64
14116 14123    1852.0
Name: new_cases, dtype: float64
14117 14124    972.0
Name: new_cases, dtype: float64
14118 14125    1819.0
Name: new_cases, dtype: float64
14119 14126    3800.0
Name: new_cases, dtype: float64
14120 14127    3192.0
Name: new_cases, dtype: float64
14121 14128    2906.0
Name: new_cases, dtype: float64
14122 14129    2516.0
Name: new_cases, dtype: float64
14123 14130    1753.0
Name: new_cases, dtype: float64
14124 14131    941.0
Name: new_cases, dtype: float64
14125 14132    855.0
Name: new_cases, dtype: float64
14126 14133    1975.0
Name: new_cases, dtype: float64
14127 14134    2891.0
Name: new_cases, dtype: float64
14128 14135    2360.0
Name: new_cases, dtype: float64
14129 14136    1860.0
Name: new_cases, dtype: float64
14130 14137    1437.0
Name: new_cases, dtype: float64
14131 14138    801.0
Name: new_cases, dtype: float64
14132 14139    1498.0
Name: new_cases, dtype: float64
14133 14140    1859.0
Name: new_cases, dtype: float64
14134 14141    1599.0
Name: new_cases, dtype: float64
14135 14142    1449.0
Name: new_cases, dtype: float64
14136 14143    1468.0
Name: new_cases, dtype: float64
14137 14144    928.0
Name: new_cases, dtype: float64
14138 14145    469.0
Name: new_cases, dtype: float64
14139 14146    904.0
Name: new_cases, dtype: float64
14140 14147    1183.0
Name: new_cases, dtype: float64
14141 14148    846.0
Name: new_cases, dtype: float64
14142 14149    784.0
Name: new_cases, dtype: float64
14143 14150    777.0
Name: new_cases, dtype: float64
14144 14151    573.0
Name: new_cases, dtype: float64
14145 14152    241.0
Name: new_cases, dtype: float64
14146 14153    508.0
Name: new_cases, dtype: float64
14147 14154    671.0
Name: new_cases, dtype: float64
14148 14155    493.0
Name: new_cases, dtype: float64
14149 14156    0.0
Name: new_cases, dtype: float64
14150 14157    833.0
Name: new_cases, dtype: float64
14151 14158    331.0
Name: new_cases, dtype: float64
14152 14159    225.0
Name: new_cases, dtype: float64
14153 14160    395.0
Name: new_cases, dtype: float64
14154 14161    1026.0
Name: new_cases, dtype: float64
14155 14162    847.0
Name: new_cases, dtype: float64
14156 14163    568.0
Name: new_cases, dtype: float64
14157 14164    0.0
Name: new_cases, dtype: float64
14158 14165    0.0
Name: new_cases, dtype: float64
14159 14166    1002.0
Name: new_cases, dtype: float64
14160 14167    1072.0
Name: new_cases, dtype: float64
14161 14168    581.0
Name: new_cases, dtype: float64
14162 14169    754.0
Name: new_cases, dtype: float64
14163 14170    623.0
Name: new_cases, dtype: float64
14164 14171    0.0
Name: new_cases, dtype: float64
14165 14172    0.0
Name: new_cases, dtype: float64
14166 14173    1855.0
Name: new_cases, dtype: float64
14167 14174    742.0
Name: new_cases, dtype: float64
14168 14175    1990.0
Name: new_cases, dtype: float64
14169 14176    1382.0
Name: new_cases, dtype: float64
14170 14177    1223.0
Name: new_cases, dtype: float64
14171 14178    0.0
Name: new_cases, dtype: float64
14172 14179    0.0
Name: new_cases, dtype: float64
14173 14180    3329.0
Name: new_cases, dtype: float64
14174 14181    1303.0
Name: new_cases, dtype: float64
14175 14182    2284.0
Name: new_cases, dtype: float64
14176 14183    1453.0
Name: new_cases, dtype: float64
14177 14184    1344.0
Name: new_cases, dtype: float64
14178 14185    0.0
Name: new_cases, dtype: float64
14179 14186    0.0
Name: new_cases, dtype: float64
14180 14187    3795.0
Name: new_cases, dtype: float64
14181 14188    1467.0
Name: new_cases, dtype: float64
14182 14189    0.0
Name: new_cases, dtype: float64
14183 14190    3486.0
Name: new_cases, dtype: float64
14184 14191    0.0
Name: new_cases, dtype: float64
14185 14192    1304.0
Name: new_cases, dtype: float64
14186 14193    0.0
Name: new_cases, dtype: float64
14187 14194    4232.0
Name: new_cases, dtype: float64
14188 14195    1333.0
Name: new_cases, dtype: float64
14189 14196    2059.0
Name: new_cases, dtype: float64
14190 14197    1862.0
Name: new_cases, dtype: float64
14191 14198    1764.0
Name: new_cases, dtype: float64
14192 14199    0.0
Name: new_cases, dtype: float64
14193 14200    0.0
Name: new_cases, dtype: float64
14194 14201    4303.0
Name: new_cases, dtype: float64
14195 14202    1740.0
Name: new_cases, dtype: float64
14196 14203    2176.0
Name: new_cases, dtype: float64
14197 14204    1973.0
Name: new_cases, dtype: float64
14198 14205    1819.0
Name: new_cases, dtype: float64
14199 14206    0.0
Name: new_cases, dtype: float64

14200 14207    0.0
Name: new_cases, dtype: float64
14201 14208    4653.0
Name: new_cases, dtype: float64
14202 14209    1748.0
Name: new_cases, dtype: float64
14203 14210    2609.0
Name: new_cases, dtype: float64
14204 14211    2119.0
Name: new_cases, dtype: float64
14205 14212    2014.0
Name: new_cases, dtype: float64
14206 14213    0.0
Name: new_cases, dtype: float64
14207 14214    0.0
Name: new_cases, dtype: float64
14208 14215    5010.0
Name: new_cases, dtype: float64
14209 14216    1741.0
Name: new_cases, dtype: float64
14210 14217    2746.0
Name: new_cases, dtype: float64
14211 14218    2192.0
Name: new_cases, dtype: float64
14212 14219    2168.0
Name: new_cases, dtype: float64
14213 14220    0.0
Name: new_cases, dtype: float64
14214 14221    0.0
Name: new_cases, dtype: float64
14215 14222    4876.0
Name: new_cases, dtype: float64
14216 14223    1611.0
Name: new_cases, dtype: float64
14217 14224    2895.0
Name: new_cases, dtype: float64
14218 14225    2467.0
Name: new_cases, dtype: float64
14219 14226    2334.0
Name: new_cases, dtype: float64
14220 14227    0.0
Name: new_cases, dtype: float64
14221 14228    0.0
Name: new_cases, dtype: float64
14222 14229    4901.0
Name: new_cases, dtype: float64
14223 14230    1854.0
Name: new_cases, dtype: float64
14224 14231    2842.0
Name: new_cases, dtype: float64
14225 14232    2204.0
Name: new_cases, dtype: float64
14226 14233    2298.0
Name: new_cases, dtype: float64
14227 14234    0.0
Name: new_cases, dtype: float64
14228 14235    0.0
Name: new_cases, dtype: float64
14229 14236    4648.0
Name: new_cases, dtype: float64
14230 14237    1847.0
Name: new_cases, dtype: float64
14231 14238    2553.0
Name: new_cases, dtype: float64
14232 14239    2270.0
Name: new_cases, dtype: float64
14233 14240    2190.0
Name: new_cases, dtype: float64
14234 14241    0.0
Name: new_cases, dtype: float64
14235 14242    0.0
Name: new_cases, dtype: float64
14236 14243    4865.0
Name: new_cases, dtype: float64
14237 14244    1725.0
Name: new_cases, dtype: float64
14238 14245    3008.0
Name: new_cases, dtype: float64
14239 14246    2359.0
Name: new_cases, dtype: float64
14240 14247    2341.0
Name: new_cases, dtype: float64
14241 14248    0.0
Name: new_cases, dtype: float64
14242 14249    0.0
Name: new_cases, dtype: float64
14243 14250    5071.0
Name: new_cases, dtype: float64
14244 14251    1797.0
Name: new_cases, dtype: float64
14245 14252    2554.0
Name: new_cases, dtype: float64
14246 14253    2287.0
Name: new_cases, dtype: float64
14247 14254    2200.0
Name: new_cases, dtype: float64
14248 14255    0.0
Name: new_cases, dtype: float64
14249 14256    0.0
Name: new_cases, dtype: float64
14250 14257    4635.0
Name: new_cases, dtype: float64
14251 14258    1874.0
Name: new_cases, dtype: float64
14252 14259    2589.0
Name: new_cases, dtype: float64
14253 14260    2133.0
Name: new_cases, dtype: float64
14254 14261    2243.0
Name: new_cases, dtype: float64
14255 14262    0.0
Name: new_cases, dtype: float64
14256 14263    0.0
Name: new_cases, dtype: float64
14257 14264    4660.0
Name: new_cases, dtype: float64
14258 14265    1730.0
Name: new_cases, dtype: float64
14259 14266    2604.0
Name: new_cases, dtype: float64
14260 14267    2497.0
Name: new_cases, dtype: float64
14261 14268    2414.0
Name: new_cases, dtype: float64
14262 14269    0.0
Name: new_cases, dtype: float64
14263 14270    0.0
Name: new_cases, dtype: float64
14264 14271    5460.0
Name: new_cases, dtype: float64
14265 14272    2440.0
Name: new_cases, dtype: float64
14266 14273    3667.0
Name: new_cases, dtype: float64
14267 14274    3552.0
Name: new_cases, dtype: float64
14268 14275    3648.0
Name: new_cases, dtype: float64
14269 14276    0.0
Name: new_cases, dtype: float64
14270 14277    0.0
Name: new_cases, dtype: float64
14271 14278    9164.0
Name: new_cases, dtype: float64
14272 14279    3854.0
Name: new_cases, dtype: float64
14273 14280    6552.0
Name: new_cases, dtype: float64
14274 14281    6239.0
Name: new_cases, dtype: float64
14275 14282    6682.0
Name: new_cases, dtype: float64
14276 14283    0.0
Name: new_cases, dtype: float64
14277 14284    0.0
Name: new_cases, dtype: float64
14278 14285    15842.0
Name: new_cases, dtype: float64
14279 14286    5745.0
Name: new_cases, dtype: float64
14280 14287    8771.0
Name: new_cases, dtype: float64
14281 14288    9195.0
Name: new_cases, dtype: float64
14282 14289    8737.0
Name: new_cases, dtype: float64
14283 14290    0.0
Name: new_cases, dtype: float64
14284 14291    0.0
Name: new_cases, dtype: float64
14285 14292    0.0
Name: new_cases, dtype: float64
14286 14293    0.0
Name: new_cases, dtype: float64
14287 14294    32708.0
Name: new_cases, dtype: float64
14288 14295    10190.0
Name: new_cases, dtype: float64
14289 14296    0.0
Name: new_cases, dtype: float64
14290 14297    10915.0
Name: new_cases, dtype: float64
14291 14298    0.0
Name: new_cases, dtype: float64
14292 14299    24367.0
Name: new_cases, dtype: float64
14293 14300    0.0
Name: new_cases, dtype: float64
14294 14301    24718.0
Name: new_cases, dtype: float64
14295 14302    0.0
Name: new_cases, dtype: float64
14296 14303    21164.0
Name: new_cases, dtype: float64
14297 14304    0.0
Name: new_cases, dtype: float64
14298 14305    0.0
Name: new_cases, dtype: float64
14299 14306    27762.0
Name: new_cases, dtype: float64
14300 14307    12388.0
Name: new_cases, dtype: float64
14301 14308    18437.0
Name: new_cases, dtype: float64
14302 14309    16699.0
Name: new_cases, dtype: float64
14303 14310    21502.0
Name: new_cases, dtype: float64
14304 14311    0.0
Name: new_cases, dtype: float64
14305 14312    0.0
Name: new_cases, dtype: float64
14306 14313    42060.0
Name: new_cases, dtype: float64
14307 14314    12115.0
Name: new_cases, dtype: float64
14308 14315    23350.0
Name: new_cases, dtype: float64
14309 14316    20836.0
Name: new_cases, dtype: float64
14310 14317    21772.0
Name: new_cases, dtype: float64
14311 14318    0.0
Name: new_cases, dtype: float64
14312 14319    0.0
Name: new_cases, dtype: float64
14313 14320    47836.0
Name: new_cases, dtype: float64
14314 14321    16566.0
Name: new_cases, dtype: float64
14315 14322    20409.0
Name: new_cases, dtype: float64
14316 14323    23113.0
Name: new_cases, dtype: float64
14317 14324    17910.0
Name: new_cases, dtype: float64
14318 14325    0.0
Name: new_cases, dtype: float64
14319 14326    0.0
Name: new_cases, dtype: float64
14320 14327    41439.0
Name: new_cases, dtype: float64
14321 14328    10878.0
Name: new_cases, dtype: float64
14322 14329    18714.0
Name: new_cases, dtype: float64
14323 14330    16029.0
Name: new_cases, dtype: float64
14324 14331    15245.0
Name: new_cases, dtype: float64
14325 14332    0.0
Name: new_cases, dtype: float64
14326 14333    0.0
Name: new_cases, dtype: float64
14327 14334    29421.0
Name: new_cases, dtype: float64
14328 14335    9076.0
Name: new_cases, dtype: float64
14329 14336    11851.0
Name: new_cases, dtype: float64
14330 14337    0.0
Name: new_cases, dtype: float64
14331 14338    10040.0
Name: new_cases, dtype: float64
14332 14339    9604.0
Name: new_cases, dtype: float64
14333 14340    0.0
Name: new_cases, dtype: float64
14334 14341    17390.0
Name: new_cases, dtype: float64
14335 14342    293.0
Name: new_cases, dtype: float64
14336 14343    5838.0
Name: new_cases, dtype: float64
14337 14344    7593.0
Name: new_cases, dtype: float64
14338 14345    7233.0
Name: new_cases, dtype: float64
14339 14346    0.0
Name: new_cases, dtype: float64
14340 14347    0.0
Name: new_cases, dtype: float64
14341 14348    14760.0
Name: new_cases, dtype: float64
14342 14349    9965.0
Name: new_cases, dtype: float64
14343 14350    12945.0
Name: new_cases, dtype: float64
14344 14351    13876.0
Name: new_cases, dtype: float64
14345 14352    15686.0
Name: new_cases, dtype: float64
14346 14353    0.0
Name: new_cases, dtype: float64
14347 14354    0.0
Name: new_cases, dtype: float64
14348 14355    27941.0
Name: new_cases, dtype: float64
14349 14356    18630.0
Name: new_cases, dtype: float64
14350 14357    27796.0
Name: new_cases, dtype: float64
14351 14358    27282.0
Name: new_cases, dtype: float64
14352 14359    24694.0
Name: new_cases, dtype: float64
14353 13678    0.0
Name: new_cases, dtype: float64
14354 13679    0.0
Name: new_cases, dtype: float64
14355 13680    0.0
Name: new_cases, dtype: float64
14356 13681    0.0
Name: new_cases, dtype: float64
14357 13682    1.0
Name: new_cases, dtype: float64
14358 13683    6.0
Name: new_cases, dtype: float64
14359 13684    5.0
Name: new_cases, dtype: float64
19658 19665    2.0
Name: new_cases, dtype: float64
19659 19666    0.0
Name: new_cases, dtype: float64
19660 19667    9.0
Name: new_cases, dtype: float64
19661 19668    0.0
Name: new_cases, dtype: float64
19662 19669    7.0
Name: new_cases, dtype: float64
19663 19670    5.0
Name: new_cases, dtype: float64
19664 19671    6.0
Name: new_cases, dtype: float64
19665 19672    7.0
Name: new_cases, dtype: float64
19666 19673    14.0
Name: new_cases, dtype: float64

19667 19674    99.0
Name: new_cases, dtype: float64
19668 19675    0.0
Name: new_cases, dtype: float64
19669 19676    11.0
Name: new_cases, dtype: float64
19670 19677    38.0
Name: new_cases, dtype: float64
19671 19678    121.0
Name: new_cases, dtype: float64
19672 19679    51.0
Name: new_cases, dtype: float64
19673 19680    249.0
Name: new_cases, dtype: float64
19674 19681    172.0
Name: new_cases, dtype: float64
19675 19682    228.0
Name: new_cases, dtype: float64
19676 19683    525.0
Name: new_cases, dtype: float64
19677 19684    378.0
Name: new_cases, dtype: float64
19678 19685    323.0
Name: new_cases, dtype: float64
19679 19686    307.0
Name: new_cases, dtype: float64
19680 19687    431.0
Name: new_cases, dtype: float64
19681 19688    432.0
Name: new_cases, dtype: float64
19682 19689    487.0
Name: new_cases, dtype: float64
19683 19690    352.0
Name: new_cases, dtype: float64
19684 19691    323.0
Name: new_cases, dtype: float64
19685 19692    1138.0
Name: new_cases, dtype: float64
19686 19693    1119.0
Name: new_cases, dtype: float64
19687 19694    1208.0
Name: new_cases, dtype: float64
19688 19695    1012.0
Name: new_cases, dtype: float64
19689 19696    1304.0
Name: new_cases, dtype: float64
19690 19697    770.0
Name: new_cases, dtype: float64
19691 19698    1031.0
Name: new_cases, dtype: float64
19692 19699    1873.0
Name: new_cases, dtype: float64
19693 19700    2136.0
Name: new_cases, dtype: float64
19694 19701    1922.0
Name: new_cases, dtype: float64
19695 19702    1546.0
Name: new_cases, dtype: float64
19696 19703    1089.0
Name: new_cases, dtype: float64
19697 19704    1465.0
Name: new_cases, dtype: float64
19698 19705    1238.0
Name: new_cases, dtype: float64
19699 19706    1832.0
Name: new_cases, dtype: float64
19700 19707    3058.0
Name: new_cases, dtype: float64
19701 19708    2105.0
Name: new_cases, dtype: float64
19702 19709    3257.0
Name: new_cases, dtype: float64
19703 19710    2976.0
Name: new_cases, dtype: float64
19704 19711    1996.0
Name: new_cases, dtype: float64
19705 19712    2089.0
Name: new_cases, dtype: float64
19706 19713    2336.0
Name: new_cases, dtype: float64
19707 19714    2678.0
Name: new_cases, dtype: float64
19708 19715    4279.0
Name: new_cases, dtype: float64
19709 19716    4007.0
Name: new_cases, dtype: float64
19710 19717    5281.0
Name: new_cases, dtype: float64
19711 19718    3776.0
Name: new_cases, dtype: float64
19712 19719    4346.0
Name: new_cases, dtype: float64
19713 19720    5789.0
Name: new_cases, dtype: float64
19714 19721    6450.0
Name: new_cases, dtype: float64
19715 19722    7502.0
Name: new_cases, dtype: float64
19716 19723    5015.0
Name: new_cases, dtype: float64
19717 19724    4898.0
Name: new_cases, dtype: float64
19718 19725    4726.0
Name: new_cases, dtype: float64
19719 19726    6794.0
Name: new_cases, dtype: float64
19720 19727    6835.0
Name: new_cases, dtype: float64
19721 19728    11156.0
Name: new_cases, dtype: float64
19722 19729    9162.0
Name: new_cases, dtype: float64
19723 19730    11121.0
Name: new_cases, dtype: float64
19724 19731    9167.0
Name: new_cases, dtype: float64
19725 19732    6638.0
Name: new_cases, dtype: float64
19726 19733    6895.0
Name: new_cases, dtype: float64
19727 19734    8620.0
Name: new_cases, dtype: float64
19728 19735    11923.0
Name: new_cases, dtype: float64
19729 19736    13028.0
Name: new_cases, dtype: float64
19730 19737    17126.0
Name: new_cases, dtype: float64
19731 19738    13220.0
Name: new_cases, dtype: float64
19732 19739    7569.0
Name: new_cases, dtype: float64
19733 19740    14288.0
Name: new_cases, dtype: float64
19734 19741    16517.0
Name: new_cases, dtype: float64
19735 19742    22739.0
Name: new_cases, dtype: float64
19736 19743    18137.0
Name: new_cases, dtype: float64
19737 19744    21807.0
Name: new_cases, dtype: float64
19738 19745    16997.0
Name: new_cases, dtype: float64
19739 19746    14468.0
Name: new_cases, dtype: float64
19740 19747    12807.0
Name: new_cases, dtype: float64
19741 19748    16327.0
Name: new_cases, dtype: float64
19742 19749    20199.0
Name: new_cases, dtype: float64
19743 19750    28337.0
Name: new_cases, dtype: float64
19744 19751    26890.0
Name: new_cases, dtype: float64
19745 19752    32321.0
Name: new_cases, dtype: float64
19746 19753    13223.0
Name: new_cases, dtype: float64
19747 19754    15149.0
Name: new_cases, dtype: float64
19748 19755    31677.0
Name: new_cases, dtype: float64
19749 19756    26085.0
Name: new_cases, dtype: float64
19750 19757    31954.0
Name: new_cases, dtype: float64
19751 19758    32101.0
Name: new_cases, dtype: float64
19752 19759    23790.0
Name: new_cases, dtype: float64
19753 19760    17988.0
Name: new_cases, dtype: float64
19754 19761    17338.0
Name: new_cases, dtype: float64
19755 19762    31698.0
Name: new_cases, dtype: float64
19756 19763    33790.0
Name: new_cases, dtype: float64
19757 19764    28692.0
Name: new_cases, dtype: float64
19758 19765    24282.0
Name: new_cases, dtype: float64
19759 19766    21230.0
Name: new_cases, dtype: float64
19760 19767    16794.0
Name: new_cases, dtype: float64
19761 19768    24617.0
Name: new_cases, dtype: float64
19762 19769    36983.0
Name: new_cases, dtype: float64
19763 19770    30925.0
Name: new_cases, dtype: float64
19764 19771    25520.0
Name: new_cases, dtype: float64
19765 19772    56059.0
Name: new_cases, dtype: float64
19766 19773    63523.0
Name: new_cases, dtype: float64
19767 19774   -19796.0
Name: new_cases, dtype: float64
19768 19775    28192.0
Name: new_cases, dtype: float64
19769 19776    39527.0
Name: new_cases, dtype: float64
19770 19777    41033.0
Name: new_cases, dtype: float64
19771 19778    41464.0
Name: new_cases, dtype: float64
19772 19779    44884.0
Name: new_cases, dtype: float64
19773 19780    36920.0
Name: new_cases, dtype: float64
19774 19781    32883.0
Name: new_cases, dtype: float64
19775 19782    21550.0
Name: new_cases, dtype: float64
19776 19783    39680.0
Name: new_cases, dtype: float64
19777 19784    46825.0
Name: new_cases, dtype: float64
19778 19785    44401.0
Name: new_cases, dtype: float64
19779 19786    43040.0
Name: new_cases, dtype: float64
19780 19787    33567.0
Name: new_cases, dtype: float64
19781 19788    25193.0
Name: new_cases, dtype: float64
19782 19789    24454.0
Name: new_cases, dtype: float64
19783 19790    46699.0
Name: new_cases, dtype: float64
19784 19791    45250.0
Name: new_cases, dtype: float64
19785 19792    42962.0
Name: new_cases, dtype: float64
19786 19793    44311.0
Name: new_cases, dtype: float64
19787 19794    34947.0
Name: new_cases, dtype: float64
19788 19795    23658.0
Name: new_cases, dtype: float64
19789 19796    22893.0
Name: new_cases, dtype: float64
19790 19797    42922.0
Name: new_cases, dtype: float64
19791 19798    40142.0
Name: new_cases, dtype: float64
19792 19799    43683.0
Name: new_cases, dtype: float64
19793 19800    34618.0
Name: new_cases, dtype: float64
19794 19801    25753.0
Name: new_cases, dtype: float64
19795 19802    23412.0
Name: new_cases, dtype: float64
19796 19803    22753.0
Name: new_cases, dtype: float64
19797 19804    46927.0
Name: new_cases, dtype: float64
19798 19805    66150.0
Name: new_cases, dtype: float64
19799 19806    57326.0
Name: new_cases, dtype: float64
19800 19807    56903.0
Name: new_cases, dtype: float64
19801 19808    47535.0
Name: new_cases, dtype: float64
19802 19809    22673.0
Name: new_cases, dtype: float64
19803 19810    28011.0
Name: new_cases, dtype: float64
19804 19811    54004.0
Name: new_cases, dtype: float64
19805 19812    55451.0
Name: new_cases, dtype: float64
19806 19813    58055.0
Name: new_cases, dtype: float64
19807 19814    53264.0
Name: new_cases, dtype: float64
19808 19815    41541.0
Name: new_cases, dtype: float64
19809 19816    24066.0
Name: new_cases, dtype: float64
19810 19817    20106.0
Name: new_cases, dtype: float64
19811 19818    56283.0
Name: new_cases, dtype: float64
19812 19819    56169.0
Name: new_cases, dtype: float64
19813 19820    53989.0
Name: new_cases, dtype: float64
19814 19821    49403.0
Name: new_cases, dtype: float64
19815 19822    46389.0
Name: new_cases, dtype: float64
19816 19823    22730.0
Name: new_cases, dtype: float64
19817 19824    26506.0
Name: new_cases, dtype: float64
19818 19825    50520.0
Name: new_cases, dtype: float64
19819 19826    54954.0
Name: new_cases, dtype: float64
19820 19827    60713.0
Name: new_cases, dtype: float64
19821 19828    49407.0
Name: new_cases, dtype: float64
19822 19829    36881.0
Name: new_cases, dtype: float64
19823 19830    23006.0
Name: new_cases, dtype: float64
19824 19831    24397.0
Name: new_cases, dtype: float64
19825 19832    49264.0
Name: new_cases, dtype: float64

19826 19833    48603.0
Name: new_cases, dtype: float64
19827 19834    42974.0
Name: new_cases, dtype: float64
19828 19835    32326.0
Name: new_cases, dtype: float64
19829 19836    45908.0
Name: new_cases, dtype: float64
19830 19837    21873.0
Name: new_cases, dtype: float64
19831 19838    23513.0
Name: new_cases, dtype: float64
19832 19839    46307.0
Name: new_cases, dtype: float64
19833 19840    48152.0
Name: new_cases, dtype: float64
19834 19841    42260.0
Name: new_cases, dtype: float64
19835 19842    44088.0
Name: new_cases, dtype: float64
19836 19843    37291.0
Name: new_cases, dtype: float64
19837 19844    14534.0
Name: new_cases, dtype: float64
19838 19845    50225.0
Name: new_cases, dtype: float64
19839 19846    44329.0
Name: new_cases, dtype: float64
19840 19847    46453.0
Name: new_cases, dtype: float64
19841 19848    46809.0
Name: new_cases, dtype: float64
19842 19849    39539.0
Name: new_cases, dtype: float64
19843 19850    33857.0
Name: new_cases, dtype: float64
19844 19851    14672.0
Name: new_cases, dtype: float64
19845 19852    9516.0
Name: new_cases, dtype: float64
19846 19853    18786.0
Name: new_cases, dtype: float64
19847 19854    37087.0
Name: new_cases, dtype: float64
19848 19855    40761.0
Name: new_cases, dtype: float64
19849 19856    41533.0
Name: new_cases, dtype: float64
19850 19857    30800.0
Name: new_cases, dtype: float64
19851 19858    14020.0
Name: new_cases, dtype: float64
19852 19859    20611.0
Name: new_cases, dtype: float64
19853 19860    34552.0
Name: new_cases, dtype: float64
19854 19861    37297.0
Name: new_cases, dtype: float64
19855 19862    36405.0
Name: new_cases, dtype: float64
19856 19863    39731.0
Name: new_cases, dtype: float64
19857 19864    29558.0
Name: new_cases, dtype: float64
19858 19865    15442.0
Name: new_cases, dtype: float64
19859 19866    17635.0
Name: new_cases, dtype: float64
19860 19867    34967.0
Name: new_cases, dtype: float64
19861 19868    32726.0
Name: new_cases, dtype: float64
19862 19869    32015.0
Name: new_cases, dtype: float64
19863 19870    32310.0
Name: new_cases, dtype: float64
19864 19871    24718.0
Name: new_cases, dtype: float64
19865 19872    13787.0
Name: new_cases, dtype: float64
19866 19873    16871.0
Name: new_cases, dtype: float64
19867 19874    32848.0
Name: new_cases, dtype: float64
19868 19875    32901.0
Name: new_cases, dtype: float64
19869 19876    35783.0
Name: new_cases, dtype: float64
19870 19877    32818.0
Name: new_cases, dtype: float64
19871 19878    23008.0
Name: new_cases, dtype: float64
19872 19879    8715.0
Name: new_cases, dtype: float64
19873 19880    26053.0
Name: new_cases, dtype: float64
19874 19881    31526.0
Name: new_cases, dtype: float64
19875 19882    30938.0
Name: new_cases, dtype: float64
19876 19883    26830.0
Name: new_cases, dtype: float64
19877 19884    27733.0
Name: new_cases, dtype: float64
19878 19885    23744.0
Name: new_cases, dtype: float64
19879 19886    12191.0
Name: new_cases, dtype: float64
19880 19887    8636.0
Name: new_cases, dtype: float64
19881 19888    13359.0
Name: new_cases, dtype: float64
19882 19889    27844.0
Name: new_cases, dtype: float64
19883 19890    30426.0
Name: new_cases, dtype: float64
19884 19891    28596.0
Name: new_cases, dtype: float64
19885 19892    20776.0
Name: new_cases, dtype: float64
19886 19893    12051.0
Name: new_cases, dtype: float64
19887 19894    16579.0
Name: new_cases, dtype: float64
19888 19895    23766.0
Name: new_cases, dtype: float64
19889 19896    25856.0
Name: new_cases, dtype: float64
19890 19897    24764.0
Name: new_cases, dtype: float64
19891 19898    30001.0
Name: new_cases, dtype: float64
19892 19899    24984.0
Name: new_cases, dtype: float64
19893 19900    12254.0
Name: new_cases, dtype: float64
19894 19901    18611.0
Name: new_cases, dtype: float64
19895 19902    29982.0
Name: new_cases, dtype: float64
19896 19903    28351.0
Name: new_cases, dtype: float64
19897 19904    26700.0
Name: new_cases, dtype: float64
19898 19905    24353.0
Name: new_cases, dtype: float64
19899 19906    13170.0
Name: new_cases, dtype: float64
19900 19907    10188.0
Name: new_cases, dtype: float64
19901 19908    8249.0
Name: new_cases, dtype: float64
19902 19909    14582.0
Name: new_cases, dtype: float64
19903 19910    23316.0
Name: new_cases, dtype: float64
19904 19911    23845.0
Name: new_cases, dtype: float64
19905 19912    20200.0
Name: new_cases, dtype: float64
19906 19913    17744.0
Name: new_cases, dtype: float64
19907 19914    10502.0
Name: new_cases, dtype: float64
19908 19915    13414.0
Name: new_cases, dtype: float64
19909 19916    46424.0
Name: new_cases, dtype: float64
19910 19917    26247.0
Name: new_cases, dtype: float64
19911 19918    33919.0
Name: new_cases, dtype: float64
19912 19919    38718.0
Name: new_cases, dtype: float64
19913 19920    26278.0
Name: new_cases, dtype: float64
19914 19921    13906.0
Name: new_cases, dtype: float64
19915 19922    15744.0
Name: new_cases, dtype: float64
19916 19923    35490.0
Name: new_cases, dtype: float64
19917 19924    34752.0
Name: new_cases, dtype: float64
19918 19925    35862.0
Name: new_cases, dtype: float64
19919 19926    38770.0
Name: new_cases, dtype: float64
19920 19927    30222.0
Name: new_cases, dtype: float64
19921 19928    17926.0
Name: new_cases, dtype: float64
19922 19929    18158.0
Name: new_cases, dtype: float64
19923 19930    34533.0
Name: new_cases, dtype: float64
19924 19931    44628.0
Name: new_cases, dtype: float64
19925 19932    40885.0
Name: new_cases, dtype: float64
19926 19933    33508.0
Name: new_cases, dtype: float64
19927 19934    51485.0
Name: new_cases, dtype: float64
19928 19935    21012.0
Name: new_cases, dtype: float64
19929 19936    23695.0
Name: new_cases, dtype: float64
19930 19937    51985.0
Name: new_cases, dtype: float64
19931 19938    48475.0
Name: new_cases, dtype: float64
19932 19939    50139.0
Name: new_cases, dtype: float64
19933 19940    47671.0
Name: new_cases, dtype: float64
19934 19941    40282.0
Name: new_cases, dtype: float64
19935 19942    26430.0
Name: new_cases, dtype: float64
19936 19943    27024.0
Name: new_cases, dtype: float64
19937 19944    47796.0
Name: new_cases, dtype: float64
19938 19945    54591.0
Name: new_cases, dtype: float64
19939 19946    53550.0
Name: new_cases, dtype: float64
19940 19947    52550.0
Name: new_cases, dtype: float64
19941 19948    42324.0
Name: new_cases, dtype: float64
19942 19949    22029.0
Name: new_cases, dtype: float64
19943 19950    27380.0
Name: new_cases, dtype: float64
19944 19951    48032.0
Name: new_cases, dtype: float64
19945 19952    66124.0
Name: new_cases, dtype: float64
19946 19953    68699.0
Name: new_cases, dtype: float64
19947 19954    52853.0
Name: new_cases, dtype: float64
19948 19955    48242.0
Name: new_cases, dtype: float64
19949 19956    24484.0
Name: new_cases, dtype: float64
19950 19957    27645.0
Name: new_cases, dtype: float64
19951 19958    56665.0
Name: new_cases, dtype: float64
19952 19959    45679.0
Name: new_cases, dtype: float64
19953 19960    58211.0
Name: new_cases, dtype: float64
19954 19961    21183.0
Name: new_cases, dtype: float64
19955 19962    17533.0
Name: new_cases, dtype: float64
19956 19963    17614.0
Name: new_cases, dtype: float64
19957 19964    27437.0
Name: new_cases, dtype: float64
19958 19965    56371.0
Name: new_cases, dtype: float64
19959 19966    55600.0
Name: new_cases, dtype: float64
19960 19967    54469.0
Name: new_cases, dtype: float64
19961 19968    22939.0
Name: new_cases, dtype: float64
19962 19969    15353.0
Name: new_cases, dtype: float64
19963 19970    17190.0
Name: new_cases, dtype: float64
19964 19971    25039.0
Name: new_cases, dtype: float64
19965 19972    58083.0
Name: new_cases, dtype: float64
19966 19973    62507.0
Name: new_cases, dtype: float64
19967 19974    87969.0
Name: new_cases, dtype: float64
19968 19975    59586.0
Name: new_cases, dtype: float64
19969 19976    51393.0
Name: new_cases, dtype: float64
19970 19977    29027.0
Name: new_cases, dtype: float64
19971 19978    30747.0
Name: new_cases, dtype: float64
19972 19979    64424.0
Name: new_cases, dtype: float64
19973 19980    59827.0
Name: new_cases, dtype: float64
19974 19981    68329.0
Name: new_cases, dtype: float64
19975 19982    69097.0
Name: new_cases, dtype: float64
19976 19983    58445.0
Name: new_cases, dtype: float64
19977 19984    31416.0
Name: new_cases, dtype: float64
19978 19985    28933.0
Name: new_cases, dtype: float64
19979 19986    62149.0
Name: new_cases, dtype: float64
19980 19987    64477.0
Name: new_cases, dtype: float64
19981 19988    58950.0
Name: new_cases, dtype: float64
19982 19989    56605.0
Name: new_cases, dtype: float64
19983 19990    58298.0
Name: new_cases, dtype: float64

19984 19991    28519.0
Name: new_cases, dtype: float64
19985 19992    30530.0
Name: new_cases, dtype: float64
19986 19993    61608.0
Name: new_cases, dtype: float64
19987 19994    64772.0
Name: new_cases, dtype: float64
19988 19995    60760.0
Name: new_cases, dtype: float64
19989 19996    59503.0
Name: new_cases, dtype: float64
19990 19997    53114.0
Name: new_cases, dtype: float64
19991 19998    27900.0
Name: new_cases, dtype: float64
19992 19999    28490.0
Name: new_cases, dtype: float64
19993 20000    56278.0
Name: new_cases, dtype: float64
19994 20001    54414.0
Name: new_cases, dtype: float64
19995 20002    57107.0
Name: new_cases, dtype: float64
19996 20003    51690.0
Name: new_cases, dtype: float64
19997 20004    46310.0
Name: new_cases, dtype: float64
19998 20005    26162.0
Name: new_cases, dtype: float64
19999 20006    28586.0
Name: new_cases, dtype: float64
20000 20007    51217.0
Name: new_cases, dtype: float64
20001 20008    61108.0
Name: new_cases, dtype: float64
20002 20009    53604.0
Name: new_cases, dtype: float64
20003 20010    48942.0
Name: new_cases, dtype: float64
20004 20011    44856.0
Name: new_cases, dtype: float64
20005 20012    30723.0
Name: new_cases, dtype: float64
20006 20013    25808.0
Name: new_cases, dtype: float64
20007 20014    65284.0
Name: new_cases, dtype: float64
20008 20015    47225.0
Name: new_cases, dtype: float64
20009 20016    53479.0
Name: new_cases, dtype: float64
20010 20017    52157.0
Name: new_cases, dtype: float64
20011 20018    52371.0
Name: new_cases, dtype: float64
20012 20019    29485.0
Name: new_cases, dtype: float64
20013 20020    31846.0
Name: new_cases, dtype: float64
20014 20021    63585.0
Name: new_cases, dtype: float64
20015 20022    65386.0
Name: new_cases, dtype: float64
20016 20023    68279.0
Name: new_cases, dtype: float64
20017 20024    63395.0
Name: new_cases, dtype: float64
20018 20025    58418.0
Name: new_cases, dtype: float64
20019 20026    33365.0
Name: new_cases, dtype: float64
20020 20027    40385.0
Name: new_cases, dtype: float64
20021 20028    59695.0
Name: new_cases, dtype: float64
20022 20029    72899.0
Name: new_cases, dtype: float64
20023 20030    76022.0
Name: new_cases, dtype: float64
20024 20031    72505.0
Name: new_cases, dtype: float64
20025 20032    66904.0
Name: new_cases, dtype: float64
20026 20033    81684.0
Name: new_cases, dtype: float64
20027 20034    36585.0
Name: new_cases, dtype: float64
20028 20035    71294.0
Name: new_cases, dtype: float64
20029 20036    81467.0
Name: new_cases, dtype: float64
20030 20037    77071.0
Name: new_cases, dtype: float64
20031 20038    82471.0
Name: new_cases, dtype: float64
20032 20039    70343.0
Name: new_cases, dtype: float64
20033 20040    43448.0
Name: new_cases, dtype: float64
20034 20041    44314.0
Name: new_cases, dtype: float64
20035 20042    85645.0
Name: new_cases, dtype: float64
20036 20043    88652.0
Name: new_cases, dtype: float64
20037 20044    87926.0
Name: new_cases, dtype: float64
20038 20045    88259.0
Name: new_cases, dtype: float64
20039 20046    73154.0
Name: new_cases, dtype: float64
20040 20047    47445.0
Name: new_cases, dtype: float64
20041 20048    55970.0
Name: new_cases, dtype: float64
20042 20049    85208.0
Name: new_cases, dtype: float64
20043 20050    90906.0
Name: new_cases, dtype: float64
20044 20051    98261.0
Name: new_cases, dtype: float64
20045 20052    80346.0
Name: new_cases, dtype: float64
20046 20053    81703.0
Name: new_cases, dtype: float64
20047 20054    46958.0
Name: new_cases, dtype: float64
20048 20055    42615.0
Name: new_cases, dtype: float64
20049 20056    86441.0
Name: new_cases, dtype: float64
20050 20057    88725.0
Name: new_cases, dtype: float64
20051 20058    87773.0
Name: new_cases, dtype: float64
20052 20059    69375.0
Name: new_cases, dtype: float64
20053 20060    39355.0
Name: new_cases, dtype: float64
20054 20061    32318.0
Name: new_cases, dtype: float64
20055 20062    42674.0
Name: new_cases, dtype: float64
20056 20063    85132.0
Name: new_cases, dtype: float64
20057 20064    88696.0
Name: new_cases, dtype: float64
20058 20065    88555.0
Name: new_cases, dtype: float64
20059 20066    88110.0
Name: new_cases, dtype: float64
20060 20067    66552.0
Name: new_cases, dtype: float64
20061 20068    39175.0
Name: new_cases, dtype: float64
20062 20069    39650.0
Name: new_cases, dtype: float64
20063 20070    82661.0
Name: new_cases, dtype: float64
20064 20071    74606.0
Name: new_cases, dtype: float64
20065 20072    71183.0
Name: new_cases, dtype: float64
20066 20073    84387.0
Name: new_cases, dtype: float64
20067 20074    68565.0
Name: new_cases, dtype: float64
20068 20075    38838.0
Name: new_cases, dtype: float64
20069 20076    36522.0
Name: new_cases, dtype: float64
20070 20077    72643.0
Name: new_cases, dtype: float64
20071 20078    73988.0
Name: new_cases, dtype: float64
20072 20079    48108.0
Name: new_cases, dtype: float64
20073 20080    69281.0
Name: new_cases, dtype: float64
20074 20081    63781.0
Name: new_cases, dtype: float64
20075 20082    33641.0
Name: new_cases, dtype: float64
20076 20083    32398.0
Name: new_cases, dtype: float64
20077 20084    75844.0
Name: new_cases, dtype: float64
20078 20085    77279.0
Name: new_cases, dtype: float64
20079 20086    68614.0
Name: new_cases, dtype: float64
20080 20087    72008.0
Name: new_cases, dtype: float64
20081 20088    58292.0
Name: new_cases, dtype: float64
20082 20089    29288.0
Name: new_cases, dtype: float64
20083 20090    38989.0
Name: new_cases, dtype: float64
20084 20091    69535.0
Name: new_cases, dtype: float64
20085 20092    76372.0
Name: new_cases, dtype: float64
20086 20093    72290.0
Name: new_cases, dtype: float64
20087 20094    76844.0
Name: new_cases, dtype: float64
20088 20095    61761.0
Name: new_cases, dtype: float64
20089 20096    32720.0
Name: new_cases, dtype: float64
20090 20097    36301.0
Name: new_cases, dtype: float64
20091 20098    70106.0
Name: new_cases, dtype: float64
20092 20099    76248.0
Name: new_cases, dtype: float64
20093 20100    80030.0
Name: new_cases, dtype: float64
20094 20101    77914.0
Name: new_cases, dtype: float64
20095 20102    67351.0
Name: new_cases, dtype: float64
20096 20103    37564.0
Name: new_cases, dtype: float64
20097 20104    35598.0
Name: new_cases, dtype: float64
20098 20105    74805.0
Name: new_cases, dtype: float64
20099 20106    80263.0
Name: new_cases, dtype: float64
20100 20107    83387.0
Name: new_cases, dtype: float64
20101 20108    76631.0
Name: new_cases, dtype: float64
20102 20109    67896.0
Name: new_cases, dtype: float64
20103 20110    38495.0
Name: new_cases, dtype: float64
20104 20111    37480.0
Name: new_cases, dtype: float64
20105 20112    74041.0
Name: new_cases, dtype: float64
20106 20113    80245.0
Name: new_cases, dtype: float64
20107 20114    64531.0
Name: new_cases, dtype: float64
20108 20115    53888.0
Name: new_cases, dtype: float64
20109 20116    75863.0
Name: new_cases, dtype: float64
20110 20117    41449.0
Name: new_cases, dtype: float64
20111 20118    36607.0
Name: new_cases, dtype: float64
20112 20119    78913.0
Name: new_cases, dtype: float64
20113 20120    96278.0
Name: new_cases, dtype: float64
20114 20121    76067.0
Name: new_cases, dtype: float64
20115 20122    43171.0
Name: new_cases, dtype: float64
20116 20123    61667.0
Name: new_cases, dtype: float64
20117 20124    40343.0
Name: new_cases, dtype: float64
20118 20125    39716.0
Name: new_cases, dtype: float64
20119 20126    55713.0
Name: new_cases, dtype: float64
20120 20127    84867.0
Name: new_cases, dtype: float64
20121 20128    91244.0
Name: new_cases, dtype: float64
20122 20129    86312.0
Name: new_cases, dtype: float64
20123 20130    73773.0
Name: new_cases, dtype: float64
20124 20131    36984.0
Name: new_cases, dtype: float64
20125 20132    42692.0
Name: new_cases, dtype: float64
20126 20133    87141.0
Name: new_cases, dtype: float64
20127 20134    86528.0
Name: new_cases, dtype: float64
20128 20135    76492.0
Name: new_cases, dtype: float64
20129 20136    95444.0
Name: new_cases, dtype: float64
20130 20137    77934.0
Name: new_cases, dtype: float64
20131 20138    44587.0
Name: new_cases, dtype: float64
20132 20139    45410.0
Name: new_cases, dtype: float64
20133 20140    124248.0
Name: new_cases, dtype: float64
20134 20141    77396.0
Name: new_cases, dtype: float64
20135 20142    76624.0
Name: new_cases, dtype: float64
20136 20143    75061.0
Name: new_cases, dtype: float64
20137 20144    60665.0
Name: new_cases, dtype: float64
20138 20145    31980.0
Name: new_cases, dtype: float64
20139 20146    32059.0
Name: new_cases, dtype: float64
20140 20147    65956.0
Name: new_cases, dtype: float64
20141 20148    47143.0
Name: new_cases, dtype: float64
20142 20149    61130.0
Name: new_cases, dtype: float64
20143 20150    63572.0
Name: new_cases, dtype: float64
20144 20151    53733.0
Name: new_cases, dtype: float64
20145 20152    25462.0
Name: new_cases, dtype: float64

20146 20153    27935.0
Name: new_cases, dtype: float64
20147 20154    61683.0
Name: new_cases, dtype: float64
20148 20155    54167.0
Name: new_cases, dtype: float64
20149 20156    54147.0
Name: new_cases, dtype: float64
20150 20157    58452.0
Name: new_cases, dtype: float64
20151 20158    44121.0
Name: new_cases, dtype: float64
20152 20159    19147.0
Name: new_cases, dtype: float64
20153 20160    19233.0
Name: new_cases, dtype: float64
20154 20161    48566.0
Name: new_cases, dtype: float64
20155 20162    56097.0
Name: new_cases, dtype: float64
20156 20163    54398.0
Name: new_cases, dtype: float64
20157 20164    42915.0
Name: new_cases, dtype: float64
20158 20165    49030.0
Name: new_cases, dtype: float64
20159 20166    16747.0
Name: new_cases, dtype: float64
20160 20167    16756.0
Name: new_cases, dtype: float64
20161 20168    31149.0
Name: new_cases, dtype: float64
20162 20169    55836.0
Name: new_cases, dtype: float64
20163 20170    48681.0
Name: new_cases, dtype: float64
20164 20171    107120.0
Name: new_cases, dtype: float64
20165 20172    34648.0
Name: new_cases, dtype: float64
20166 20173    18256.0
Name: new_cases, dtype: float64
20167 20174    21442.0
Name: new_cases, dtype: float64
20168 20175    43591.0
Name: new_cases, dtype: float64
20169 20176    47049.0
Name: new_cases, dtype: float64
20170 20177    41321.0
Name: new_cases, dtype: float64
20171 20178    40378.0
Name: new_cases, dtype: float64
20172 20179    35088.0
Name: new_cases, dtype: float64
20173 20180    20353.0
Name: new_cases, dtype: float64
20174 20181    18875.0
Name: new_cases, dtype: float64
20175 20182    32496.0
Name: new_cases, dtype: float64
20176 20183    40537.0
Name: new_cases, dtype: float64
20177 20184    39484.0
Name: new_cases, dtype: float64
20178 20185    42671.0
Name: new_cases, dtype: float64
20179 20186    39533.0
Name: new_cases, dtype: float64
20180 20187    13894.0
Name: new_cases, dtype: float64
20181 20188    15542.0
Name: new_cases, dtype: float64
20182 20189    35462.0
Name: new_cases, dtype: float64
20183 20190    35443.0
Name: new_cases, dtype: float64
20184 20191    35858.0
Name: new_cases, dtype: float64
20185 20192    32995.0
Name: new_cases, dtype: float64
20186 20193    29302.0
Name: new_cases, dtype: float64
20187 20194    13767.0
Name: new_cases, dtype: float64
20188 20195    18190.0
Name: new_cases, dtype: float64
20189 20196    39006.0
Name: new_cases, dtype: float64
20190 20197    40171.0
Name: new_cases, dtype: float64
20191 20198    36013.0
Name: new_cases, dtype: float64
20192 20199    34213.0
Name: new_cases, dtype: float64
20193 20200    25322.0
Name: new_cases, dtype: float64
20194 20201    13945.0
Name: new_cases, dtype: float64
20195 20202    15654.0
Name: new_cases, dtype: float64
20196 20203    31809.0
Name: new_cases, dtype: float64
20197 20204    29979.0
Name: new_cases, dtype: float64
20198 20205    30923.0
Name: new_cases, dtype: float64
20199 20206    27756.0
Name: new_cases, dtype: float64
20200 20207    22947.0
Name: new_cases, dtype: float64
20201 20208    11263.0
Name: new_cases, dtype: float64
20202 20209    12801.0
Name: new_cases, dtype: float64
20203 20210    26846.0
Name: new_cases, dtype: float64
20204 20211    25748.0
Name: new_cases, dtype: float64
20205 20212    27023.0
Name: new_cases, dtype: float64
20206 20213    23604.0
Name: new_cases, dtype: float64
20207 20214    20325.0
Name: new_cases, dtype: float64
20208 20215    12661.0
Name: new_cases, dtype: float64
20209 20216    10172.0
Name: new_cases, dtype: float64
20210 20217    13604.0
Name: new_cases, dtype: float64
20211 20218    14182.0
Name: new_cases, dtype: float64
20212 20219    32823.0
Name: new_cases, dtype: float64
20213 20220    16455.0
Name: new_cases, dtype: float64
20214 20221    13762.0
Name: new_cases, dtype: float64
20215 20222    7861.0
Name: new_cases, dtype: float64
20216 20223    8648.0
Name: new_cases, dtype: float64
20217 20224    13571.0
Name: new_cases, dtype: float64
20218 20225    13276.0
Name: new_cases, dtype: float64
20219 20226    35447.0
Name: new_cases, dtype: float64
20220 20227    35337.0
Name: new_cases, dtype: float64
20221 20229    9175.0
Name: new_cases, dtype: float64
20222 20230    9285.0
Name: new_cases, dtype: float64
20223 20231    15380.0
Name: new_cases, dtype: float64
20224 20232    32583.0
Name: new_cases, dtype: float64
20225 20233    24917.0
Name: new_cases, dtype: float64
20226 20234    18665.0
Name: new_cases, dtype: float64
20227 20235    13863.0
Name: new_cases, dtype: float64
20229 20236    8856.0
Name: new_cases, dtype: float64
20230 20237    9345.0
Name: new_cases, dtype: float64
20231 20238    16884.0
Name: new_cases, dtype: float64
20232 20239    16885.0
Name: new_cases, dtype: float64
20233 20240    21951.0
Name: new_cases, dtype: float64
20234 20241    18062.0
Name: new_cases, dtype: float64
20235 20242    12386.0
Name: new_cases, dtype: float64
20236 20243    9153.0
Name: new_cases, dtype: float64
20237 20244    11518.0
Name: new_cases, dtype: float64
20238 20245    22145.0
Name: new_cases, dtype: float64
20239 20246    18546.0
Name: new_cases, dtype: float64
20240 20247    14616.0
Name: new_cases, dtype: float64
20241 20248    18535.0
Name: new_cases, dtype: float64
20242 20249    14804.0
Name: new_cases, dtype: float64
20243 20250    8412.0
Name: new_cases, dtype: float64
20244 20251    6993.0
Name: new_cases, dtype: float64
20245 20252    7355.0
Name: new_cases, dtype: float64
20246 20253    8372.0
Name: new_cases, dtype: float64
20247 20254    15232.0
Name: new_cases, dtype: float64
20248 20255    14298.0
Name: new_cases, dtype: float64
20249 20256    9761.0
Name: new_cases, dtype: float64
20250 20257    6185.0
Name: new_cases, dtype: float64
20251 20258    9319.0
Name: new_cases, dtype: float64
20252 20259    13233.0
Name: new_cases, dtype: float64
20253 20260    15708.0
Name: new_cases, dtype: float64
20254 20261    16986.0
Name: new_cases, dtype: float64
20255 20262    13398.0
Name: new_cases, dtype: float64
20256 20263    11905.0
Name: new_cases, dtype: float64
20257 20264    4536.0
Name: new_cases, dtype: float64
20258 20265    7827.0
Name: new_cases, dtype: float64
20259 20266    13345.0
Name: new_cases, dtype: float64
20260 20267    17124.0
Name: new_cases, dtype: float64
20261 20268    13686.0
Name: new_cases, dtype: float64
20262 20269    12681.0
Name: new_cases, dtype: float64
20263 20270    10012.0
Name: new_cases, dtype: float64
20264 20271    6130.0
Name: new_cases, dtype: float64
20265 20272    4626.0
Name: new_cases, dtype: float64
20266 20273    5918.0
Name: new_cases, dtype: float64
20267 20274    16310.0
Name: new_cases, dtype: float64
20268 20275    13247.0
Name: new_cases, dtype: float64
20269 20276    12998.0
Name: new_cases, dtype: float64
20270 20277    11173.0
Name: new_cases, dtype: float64
20271 20278    5661.0
Name: new_cases, dtype: float64
20272 20279    6881.0
Name: new_cases, dtype: float64
20273 20280    11810.0
Name: new_cases, dtype: float64
20274 20281    14980.0
Name: new_cases, dtype: float64
20275 20282    15538.0
Name: new_cases, dtype: float64
20276 20283    14599.0
Name: new_cases, dtype: float64
20277 20284    9358.0
Name: new_cases, dtype: float64
20278 20285    4302.0
Name: new_cases, dtype: float64
20279 20286    2743.0
Name: new_cases, dtype: float64
20280 20287    6568.0
Name: new_cases, dtype: float64
20281 20288    13112.0
Name: new_cases, dtype: float64
20282 20289    11402.0
Name: new_cases, dtype: float64
20283 20290    12373.0
Name: new_cases, dtype: float64
20284 20291    8215.0
Name: new_cases, dtype: float64
20285 20292    5088.0
Name: new_cases, dtype: float64
20286 20293    4141.0
Name: new_cases, dtype: float64
20287 20294    12440.0
Name: new_cases, dtype: float64
20288 20295    12254.0
Name: new_cases, dtype: float64
20289 20296    12283.0
Name: new_cases, dtype: float64
20290 20297    10879.0
Name: new_cases, dtype: float64
20291 20298    8309.0
Name: new_cases, dtype: float64
20292 20299    3536.0
Name: new_cases, dtype: float64
20293 20300    4489.0
Name: new_cases, dtype: float64
20294 20301    10285.0
Name: new_cases, dtype: float64
20295 20302    12282.0
Name: new_cases, dtype: float64
20296 20303    11931.0
Name: new_cases, dtype: float64
20297 20304    10622.0
Name: new_cases, dtype: float64
20298 20305    7407.0
Name: new_cases, dtype: float64
20299 20306    4693.0
Name: new_cases, dtype: float64
20300 20307    6017.0
Name: new_cases, dtype: float64
20301 20308    10136.0
Name: new_cases, dtype: float64
20302 20309    10132.0
Name: new_cases, dtype: float64
20303 20310    8753.0
Name: new_cases, dtype: float64
20304 20311    7065.0
Name: new_cases, dtype: float64
20305 20312    2684.0
Name: new_cases, dtype: float64
20306 20313    1615.0
Name: new_cases, dtype: float64
20307 20314    2770.0
Name: new_cases, dtype: float64
20308 20315    4379.0
Name: new_cases, dtype: float64
20309 20316    5078.0
Name: new_cases, dtype: float64
20310 20317    3661.0
Name: new_cases, dtype: float64
20311 20318    4363.0
Name: new_cases, dtype: float64

20312 20319    2381.0
Name: new_cases, dtype: float64
20313 20320    1458.0
Name: new_cases, dtype: float64
20314 20321    2639.0
Name: new_cases, dtype: float64
20315 20322    3734.0
Name: new_cases, dtype: float64
20316 20323    3226.0
Name: new_cases, dtype: float64
20317 20324    3774.0
Name: new_cases, dtype: float64
20318 20325    3680.0
Name: new_cases, dtype: float64
20319 20326    3674.0
Name: new_cases, dtype: float64
20320 20327    4969.0
Name: new_cases, dtype: float64
20321 20328    6952.0
Name: new_cases, dtype: float64
20322 20329    9052.0
Name: new_cases, dtype: float64
20323 20330    9761.0
Name: new_cases, dtype: float64
20324 20331    12618.0
Name: new_cases, dtype: float64
20325 20332    10190.0
Name: new_cases, dtype: float64
20326 20333    3782.0
Name: new_cases, dtype: float64
20327 20334    1806.0
Name: new_cases, dtype: float64
20328 20335    11654.0
Name: new_cases, dtype: float64
20329 20336    19171.0
Name: new_cases, dtype: float64
20330 19669    7.0
Name: new_cases, dtype: float64
20331 19670    5.0
Name: new_cases, dtype: float64
20332 19671    6.0
Name: new_cases, dtype: float64
20333 19672    7.0
Name: new_cases, dtype: float64
20334 19673    14.0
Name: new_cases, dtype: float64
20335 19674    99.0
Name: new_cases, dtype: float64
20336 19675    0.0
Name: new_cases, dtype: float64
21664 21671    10.0
Name: new_cases, dtype: float64
21665 21672    1.0
Name: new_cases, dtype: float64
21666 21673    15.0
Name: new_cases, dtype: float64
21667 21674    25.0
Name: new_cases, dtype: float64
21668 21675    2.0
Name: new_cases, dtype: float64
21669 21676    33.0
Name: new_cases, dtype: float64
21670 21677    36.0
Name: new_cases, dtype: float64
21671 21678    24.0
Name: new_cases, dtype: float64
21672 21679    14.0
Name: new_cases, dtype: float64
21673 21680    17.0
Name: new_cases, dtype: float64
21674 21681    24.0
Name: new_cases, dtype: float64
21675 21682    22.0
Name: new_cases, dtype: float64
21676 21683    29.0
Name: new_cases, dtype: float64
21677 21684    38.0
Name: new_cases, dtype: float64
21678 21685    15.0
Name: new_cases, dtype: float64
21679 21686    13.0
Name: new_cases, dtype: float64
21680 21687    40.0
Name: new_cases, dtype: float64
21681 21688    23.0
Name: new_cases, dtype: float64
21682 21689    35.0
Name: new_cases, dtype: float64
21683 21690    28.0
Name: new_cases, dtype: float64
21684 21691    18.0
Name: new_cases, dtype: float64
21685 21692    28.0
Name: new_cases, dtype: float64
21686 21693    18.0
Name: new_cases, dtype: float64
21687 21694    28.0
Name: new_cases, dtype: float64
21688 21695    16.0
Name: new_cases, dtype: float64
21689 21696    25.0
Name: new_cases, dtype: float64
21690 21697    17.0
Name: new_cases, dtype: float64
21691 21698    26.0
Name: new_cases, dtype: float64
21692 21699    14.0
Name: new_cases, dtype: float64
21693 21700    10.0
Name: new_cases, dtype: float64
21694 21701    28.0
Name: new_cases, dtype: float64
21695 21702    34.0
Name: new_cases, dtype: float64
21696 21703    53.0
Name: new_cases, dtype: float64
21697 21704    46.0
Name: new_cases, dtype: float64
21698 21705    32.0
Name: new_cases, dtype: float64
21699 21706    16.0
Name: new_cases, dtype: float64
21700 21707    35.0
Name: new_cases, dtype: float64
21701 21708    46.0
Name: new_cases, dtype: float64
21702 21709    49.0
Name: new_cases, dtype: float64
21703 21710    73.0
Name: new_cases, dtype: float64
21704 21711    137.0
Name: new_cases, dtype: float64
21705 21712    13.0
Name: new_cases, dtype: float64
21706 21713    53.0
Name: new_cases, dtype: float64
21707 21714    63.0
Name: new_cases, dtype: float64
21708 21715    36.0
Name: new_cases, dtype: float64
21709 21716    48.0
Name: new_cases, dtype: float64
21710 21717    59.0
Name: new_cases, dtype: float64
21711 21718    49.0
Name: new_cases, dtype: float64
21712 21719    39.0
Name: new_cases, dtype: float64
21713 21720    24.0
Name: new_cases, dtype: float64
21714 21721    34.0
Name: new_cases, dtype: float64
21715 21722    52.0
Name: new_cases, dtype: float64
21716 21723    74.0
21724    74.0
Name: new_cases, dtype: float64
21717 21723    74.0
21724    74.0
Name: new_cases, dtype: float64
21718 21725    51.0
Name: new_cases, dtype: float64
21719 21726    43.0
Name: new_cases, dtype: float64
21720 21727    49.0
Name: new_cases, dtype: float64
21721 21728    44.0
Name: new_cases, dtype: float64
21722 21729    25.0
Name: new_cases, dtype: float64
21723 21730    33.0
Name: new_cases, dtype: float64
21724 21731    46.0
Name: new_cases, dtype: float64
21725 21732    31.0
Name: new_cases, dtype: float64
21726 21733    38.0
Name: new_cases, dtype: float64
21727 21734    37.0
Name: new_cases, dtype: float64
21728 21735    36.0
Name: new_cases, dtype: float64
21729 21736    24.0
Name: new_cases, dtype: float64
21730 21737    24.0
Name: new_cases, dtype: float64
21731 21738    33.0
Name: new_cases, dtype: float64
21732 21739    39.0
Name: new_cases, dtype: float64
21733 21740    41.0
Name: new_cases, dtype: float64
21734 21741    36.0
Name: new_cases, dtype: float64
21735 21742    19.0
Name: new_cases, dtype: float64
21736 21743    6.0
Name: new_cases, dtype: float64
21737 21744    10.0
Name: new_cases, dtype: float64
21738 21745    17.0
Name: new_cases, dtype: float64
21739 21746    17.0
Name: new_cases, dtype: float64
21740 21747    8.0
Name: new_cases, dtype: float64
21741 21748    14.0
Name: new_cases, dtype: float64
21742 21749    14.0
Name: new_cases, dtype: float64
21743 21750    6.0
Name: new_cases, dtype: float64
21744 21751    19.0
Name: new_cases, dtype: float64
21745 21752    22.0
Name: new_cases, dtype: float64
21746 21753    25.0
Name: new_cases, dtype: float64
21747 21754    42.0
Name: new_cases, dtype: float64
21748 21755    84.0
Name: new_cases, dtype: float64
21749 21756    16.0
Name: new_cases, dtype: float64
21750 21757    83.0
Name: new_cases, dtype: float64
21751 21758    79.0
Name: new_cases, dtype: float64
21752 21759    104.0
Name: new_cases, dtype: float64
21753 21760    93.0
Name: new_cases, dtype: float64
21754 21761    105.0
Name: new_cases, dtype: float64
21755 21762    75.0
Name: new_cases, dtype: float64
21756 21763    24.0
Name: new_cases, dtype: float64
21757 21764    51.0
Name: new_cases, dtype: float64
21758 21765    112.0
Name: new_cases, dtype: float64
21759 21766    89.0
Name: new_cases, dtype: float64
21760 21767    132.0
Name: new_cases, dtype: float64
21761 21768    81.0
Name: new_cases, dtype: float64
21762 21769    117.0
Name: new_cases, dtype: float64
21763 21770    33.0
Name: new_cases, dtype: float64
21764 21771    79.0
Name: new_cases, dtype: float64
21765 21772    130.0
Name: new_cases, dtype: float64
21766 21773    128.0
Name: new_cases, dtype: float64
21767 21774    166.0
Name: new_cases, dtype: float64
21768 21775    105.0
Name: new_cases, dtype: float64
21769 21776    112.0
Name: new_cases, dtype: float64
21770 21777    66.0
Name: new_cases, dtype: float64
21771 21778    140.0
Name: new_cases, dtype: float64
21772 21779    158.0
Name: new_cases, dtype: float64
21773 21780    165.0
Name: new_cases, dtype: float64
21774 21781    161.0
Name: new_cases, dtype: float64
21775 21782    182.0
Name: new_cases, dtype: float64
21776 21783    180.0
Name: new_cases, dtype: float64
21777 21784    63.0
Name: new_cases, dtype: float64
21778 21785    174.0
Name: new_cases, dtype: float64
21779 21786    188.0
Name: new_cases, dtype: float64
21780 21787    240.0
Name: new_cases, dtype: float64
21781 21788    330.0
Name: new_cases, dtype: float64
21782 21789    292.0
Name: new_cases, dtype: float64
21783 21790    211.0
Name: new_cases, dtype: float64
21784 21791    77.0
Name: new_cases, dtype: float64
21785 21792    159.0
Name: new_cases, dtype: float64
21786 21793    234.0
Name: new_cases, dtype: float64
21787 21794    232.0
Name: new_cases, dtype: float64
21788 21795    267.0
Name: new_cases, dtype: float64
21789 21796    298.0
Name: new_cases, dtype: float64
21790 21797    196.0
Name: new_cases, dtype: float64
21791 21798    95.0
Name: new_cases, dtype: float64
21792 21799    196.0
Name: new_cases, dtype: float64
21793 21800    325.0
Name: new_cases, dtype: float64
21794 21801    330.0
Name: new_cases, dtype: float64
21795 21802    269.0
Name: new_cases, dtype: float64
21796 21803    270.0
Name: new_cases, dtype: float64
21797 21804    189.0
Name: new_cases, dtype: float64
21798 21805    115.0
Name: new_cases, dtype: float64
21799 21806    194.0
Name: new_cases, dtype: float64
21800 21807    250.0
Name: new_cases, dtype: float64
21801 21808    284.0
Name: new_cases, dtype: float64
21802 21809    265.0
Name: new_cases, dtype: float64
21803 21810    270.0
Name: new_cases, dtype: float64
21804 21811    146.0
Name: new_cases, dtype: float64
21805 21812    119.0
Name: new_cases, dtype: float64
21806 21813    204.0
Name: new_cases, dtype: float64
21807 21814    255.0
Name: new_cases, dtype: float64

21808 21815    303.0
Name: new_cases, dtype: float64
21809 21816    297.0
Name: new_cases, dtype: float64
21810 21817    195.0
Name: new_cases, dtype: float64
21811 21818    134.0
Name: new_cases, dtype: float64
21812 21819    53.0
Name: new_cases, dtype: float64
21813 21820    116.0
Name: new_cases, dtype: float64
21814 21821    210.0
Name: new_cases, dtype: float64
21815 21822    171.0
Name: new_cases, dtype: float64
21816 21823    0.0
Name: new_cases, dtype: float64
21817 21824    350.0
Name: new_cases, dtype: float64
21818 21825    90.0
Name: new_cases, dtype: float64
21819 21826    32.0
Name: new_cases, dtype: float64
21820 21827    135.0
Name: new_cases, dtype: float64
21821 21828    169.0
Name: new_cases, dtype: float64
21822 21829    151.0
Name: new_cases, dtype: float64
21823 21830    142.0
Name: new_cases, dtype: float64
21824 21831    169.0
Name: new_cases, dtype: float64
21825 21832    0.0
Name: new_cases, dtype: float64
21826 21833    156.0
Name: new_cases, dtype: float64
21827 21834    99.0
Name: new_cases, dtype: float64
21828 21835    203.0
Name: new_cases, dtype: float64
21829 21836    162.0
Name: new_cases, dtype: float64
21830 21837    157.0
Name: new_cases, dtype: float64
21831 21838    157.0
Name: new_cases, dtype: float64
21832 21839    99.0
Name: new_cases, dtype: float64
21833 21840    26.0
Name: new_cases, dtype: float64
21834 21841    76.0
Name: new_cases, dtype: float64
21835 21842    188.0
Name: new_cases, dtype: float64
21836 21843    163.0
Name: new_cases, dtype: float64
21837 21844    158.0
Name: new_cases, dtype: float64
21838 21845    179.0
Name: new_cases, dtype: float64
21839 21846    96.0
Name: new_cases, dtype: float64
21840 21847    39.0
Name: new_cases, dtype: float64
21841 21848    57.0
Name: new_cases, dtype: float64
21842 21849    167.0
Name: new_cases, dtype: float64
21843 21850    122.0
Name: new_cases, dtype: float64
21844 21851    163.0
Name: new_cases, dtype: float64
21845 21852    201.0
Name: new_cases, dtype: float64
21846 21853    92.0
Name: new_cases, dtype: float64
21847 21854    27.0
Name: new_cases, dtype: float64
21848 21855    143.0
Name: new_cases, dtype: float64
21849 21856    155.0
Name: new_cases, dtype: float64
21850 21857    174.0
Name: new_cases, dtype: float64
21851 21858    154.0
Name: new_cases, dtype: float64
21852 21859    189.0
Name: new_cases, dtype: float64
21853 21860    86.0
Name: new_cases, dtype: float64
21854 21861    44.0
Name: new_cases, dtype: float64
21855 21862    151.0
Name: new_cases, dtype: float64
21856 21863    109.0
Name: new_cases, dtype: float64
21857 21864    160.0
Name: new_cases, dtype: float64
21858 21865    290.0
Name: new_cases, dtype: float64
21859 21866    255.0
Name: new_cases, dtype: float64
21860 21867    169.0
Name: new_cases, dtype: float64
21861 21868    58.0
Name: new_cases, dtype: float64
21862 21869    216.0
Name: new_cases, dtype: float64
21863 21870    276.0
Name: new_cases, dtype: float64
21864 21871    286.0
Name: new_cases, dtype: float64
21865 21872    0.0
Name: new_cases, dtype: float64
21866 21873    503.0
Name: new_cases, dtype: float64
21867 21874    182.0
Name: new_cases, dtype: float64
21868 21875    69.0
Name: new_cases, dtype: float64
21869 21876    283.0
Name: new_cases, dtype: float64
21870 21877    436.0
Name: new_cases, dtype: float64
21871 21878    437.0
Name: new_cases, dtype: float64
21872 21879    516.0
Name: new_cases, dtype: float64
21873 21880    612.0
Name: new_cases, dtype: float64
21874 21881    448.0
Name: new_cases, dtype: float64
21875 21882    83.0
Name: new_cases, dtype: float64
21876 21883    587.0
Name: new_cases, dtype: float64
21877 21884    785.0
Name: new_cases, dtype: float64
21878 21885    819.0
Name: new_cases, dtype: float64
21879 21886    914.0
Name: new_cases, dtype: float64
21880 21887    998.0
Name: new_cases, dtype: float64
21881 21888    603.0
Name: new_cases, dtype: float64
21882 21889    395.0
Name: new_cases, dtype: float64
21883 21890    1024.0
Name: new_cases, dtype: float64
21884 21891    1336.0
Name: new_cases, dtype: float64
21885 21892    1472.0
Name: new_cases, dtype: float64
21886 21893    1595.0
Name: new_cases, dtype: float64
21887 21894    1589.0
Name: new_cases, dtype: float64
21888 21895    1043.0
Name: new_cases, dtype: float64
21889 21896    327.0
Name: new_cases, dtype: float64
21890 21897    2243.0
Name: new_cases, dtype: float64
21891 21898    2569.0
Name: new_cases, dtype: float64
21892 21899    2760.0
Name: new_cases, dtype: float64
21893 21900    2689.0
Name: new_cases, dtype: float64
21894 21901    2891.0
Name: new_cases, dtype: float64
21895 21902    1803.0
Name: new_cases, dtype: float64
21896 21903    1225.0
Name: new_cases, dtype: float64
21897 21904    2427.0
Name: new_cases, dtype: float64
21898 21905    4041.0
Name: new_cases, dtype: float64
21899 21906    4054.0
Name: new_cases, dtype: float64
21900 21907    3754.0
Name: new_cases, dtype: float64
21901 21908    3839.0
Name: new_cases, dtype: float64
21902 21909    2301.0
Name: new_cases, dtype: float64
21903 21910    675.0
Name: new_cases, dtype: float64
21904 21911    3816.0
Name: new_cases, dtype: float64
21905 21912    4390.0
Name: new_cases, dtype: float64
21906 21913    3945.0
Name: new_cases, dtype: float64
21907 21914    3414.0
Name: new_cases, dtype: float64
21908 21915    4212.0
Name: new_cases, dtype: float64
21909 21916    2498.0
Name: new_cases, dtype: float64
21910 21917    816.0
Name: new_cases, dtype: float64
21911 21918    3519.0
Name: new_cases, dtype: float64
21912 21919    4828.0
Name: new_cases, dtype: float64
21913 21920    3938.0
Name: new_cases, dtype: float64
21914 21921    3899.0
Name: new_cases, dtype: float64
21915 21922    3983.0
Name: new_cases, dtype: float64
21916 21923    2279.0
Name: new_cases, dtype: float64
21917 21924    1123.0
Name: new_cases, dtype: float64
21918 21925    3146.0
Name: new_cases, dtype: float64
21919 21926    4382.0
Name: new_cases, dtype: float64
21920 21927    3712.0
Name: new_cases, dtype: float64
21921 21928    3568.0
Name: new_cases, dtype: float64
21922 21929    3327.0
Name: new_cases, dtype: float64
21923 21930    1792.0
Name: new_cases, dtype: float64
21924 21931    739.0
Name: new_cases, dtype: float64
21925 21932    2814.0
Name: new_cases, dtype: float64
21926 21933    3475.0
Name: new_cases, dtype: float64
21927 21934    3138.0
Name: new_cases, dtype: float64
21928 21935    3280.0
Name: new_cases, dtype: float64
21929 21936    3614.0
Name: new_cases, dtype: float64
21930 21937    2037.0
Name: new_cases, dtype: float64
21931 21938    577.0
Name: new_cases, dtype: float64
21932 21939    2764.0
Name: new_cases, dtype: float64
21933 21940    3980.0
Name: new_cases, dtype: float64
21934 21941    3328.0
Name: new_cases, dtype: float64
21935 21942    3075.0
Name: new_cases, dtype: float64
21936 21943    3097.0
Name: new_cases, dtype: float64
21937 21944    1287.0
Name: new_cases, dtype: float64
21938 21945    497.0
Name: new_cases, dtype: float64
21939 21946    2095.0
Name: new_cases, dtype: float64
21940 21947    2743.0
Name: new_cases, dtype: float64
21941 21948    1959.0
Name: new_cases, dtype: float64
21942 21949    2042.0
Name: new_cases, dtype: float64
21943 21950    1739.0
Name: new_cases, dtype: float64
21944 21951    1002.0
Name: new_cases, dtype: float64
21945 21952    166.0
Name: new_cases, dtype: float64
21946 21953    1277.0
Name: new_cases, dtype: float64
21947 21954    1799.0
Name: new_cases, dtype: float64
21948 21955    1615.0
Name: new_cases, dtype: float64
21949 21956    772.0
Name: new_cases, dtype: float64
21950 21957    257.0
Name: new_cases, dtype: float64
21951 21958    469.0
Name: new_cases, dtype: float64
21952 21959    332.0
Name: new_cases, dtype: float64
21953 21960    337.0
Name: new_cases, dtype: float64
21954 21961    1438.0
Name: new_cases, dtype: float64
21955 21962    1729.0
Name: new_cases, dtype: float64
21956 21963    1046.0
Name: new_cases, dtype: float64
21957 21964    274.0
Name: new_cases, dtype: float64
21958 21965    340.0
Name: new_cases, dtype: float64
21959 21966    171.0
Name: new_cases, dtype: float64
21960 21967    1029.0
Name: new_cases, dtype: float64
21961 21968    1310.0
Name: new_cases, dtype: float64
21962 21969    1002.0
Name: new_cases, dtype: float64
21963 21970    867.0
Name: new_cases, dtype: float64
21964 21971    753.0
Name: new_cases, dtype: float64
21965 21972    394.0
Name: new_cases, dtype: float64
21966 21973    105.0
Name: new_cases, dtype: float64
21967 21974    620.0
Name: new_cases, dtype: float64
21968 21975    750.0
Name: new_cases, dtype: float64
21969 21976    535.0
Name: new_cases, dtype: float64
21970 21977    535.0
Name: new_cases, dtype: float64
21971 21978    552.0
Name: new_cases, dtype: float64
21972 21979    233.0
Name: new_cases, dtype: float64
21973 21980    77.0
Name: new_cases, dtype: float64
21974 21981    570.0
Name: new_cases, dtype: float64
21975 21982    544.0
Name: new_cases, dtype: float64

21976 21983    482.0
Name: new_cases, dtype: float64
21977 21984    455.0
Name: new_cases, dtype: float64
21978 21985    566.0
Name: new_cases, dtype: float64
21979 21986    266.0
Name: new_cases, dtype: float64
21980 21987    121.0
Name: new_cases, dtype: float64
21981 21988    772.0
Name: new_cases, dtype: float64
21982 21989    827.0
Name: new_cases, dtype: float64
21983 21990    598.0
Name: new_cases, dtype: float64
21984 21991    560.0
Name: new_cases, dtype: float64
21985 21992    695.0
Name: new_cases, dtype: float64
21986 21993    349.0
Name: new_cases, dtype: float64
21987 21994    130.0
Name: new_cases, dtype: float64
21988 21995    832.0
Name: new_cases, dtype: float64
21989 21996    967.0
Name: new_cases, dtype: float64
21990 21997    719.0
Name: new_cases, dtype: float64
21991 21998    883.0
Name: new_cases, dtype: float64
21992 21999    910.0
Name: new_cases, dtype: float64
21993 22000    493.0
Name: new_cases, dtype: float64
21994 22001    182.0
Name: new_cases, dtype: float64
21995 22002    1115.0
Name: new_cases, dtype: float64
21996 22003    1212.0
Name: new_cases, dtype: float64
21997 22004    913.0
Name: new_cases, dtype: float64
21998 22005    1070.0
Name: new_cases, dtype: float64
21999 22006    966.0
Name: new_cases, dtype: float64
22000 22007    506.0
Name: new_cases, dtype: float64
22001 22008    163.0
Name: new_cases, dtype: float64
22002 22009    1068.0
Name: new_cases, dtype: float64
22003 22010    1349.0
Name: new_cases, dtype: float64
22004 22011    1246.0
Name: new_cases, dtype: float64
22005 22012    1086.0
Name: new_cases, dtype: float64
22006 22013    1463.0
Name: new_cases, dtype: float64
22007 22014    548.0
Name: new_cases, dtype: float64
22008 22015    227.0
Name: new_cases, dtype: float64
22009 22016    1925.0
Name: new_cases, dtype: float64
22010 22017    1800.0
Name: new_cases, dtype: float64
22011 22018    1733.0
Name: new_cases, dtype: float64
22012 22019    1822.0
Name: new_cases, dtype: float64
22013 22020    1681.0
Name: new_cases, dtype: float64
22014 22021    1079.0
Name: new_cases, dtype: float64
22015 22022    332.0
Name: new_cases, dtype: float64
22016 22023    2588.0
Name: new_cases, dtype: float64
22017 22024    2403.0
Name: new_cases, dtype: float64
22018 22025    1154.0
Name: new_cases, dtype: float64
22019 22026    2198.0
Name: new_cases, dtype: float64
22020 22027    3004.0
Name: new_cases, dtype: float64
22021 22028    1426.0
Name: new_cases, dtype: float64
22022 22029    497.0
Name: new_cases, dtype: float64
22023 22030    2995.0
Name: new_cases, dtype: float64
22024 22031    3502.0
Name: new_cases, dtype: float64
22025 22032    2774.0
Name: new_cases, dtype: float64
22026 22033    3121.0
Name: new_cases, dtype: float64
22027 22034    3159.0
Name: new_cases, dtype: float64
22028 22035    2019.0
Name: new_cases, dtype: float64
22029 22036    679.0
Name: new_cases, dtype: float64
22030 22037    4637.0
Name: new_cases, dtype: float64
22031 22038    4374.0
Name: new_cases, dtype: float64
22032 22039    4201.0
Name: new_cases, dtype: float64
22033 22040    4008.0
Name: new_cases, dtype: float64
22034 22041    4162.0
Name: new_cases, dtype: float64
22035 22042    2541.0
Name: new_cases, dtype: float64
22036 22043    943.0
Name: new_cases, dtype: float64
22037 22044    4467.0
Name: new_cases, dtype: float64
22038 22045    4851.0
Name: new_cases, dtype: float64
22039 22046    4375.0
Name: new_cases, dtype: float64
22040 22047    3988.0
Name: new_cases, dtype: float64
22041 22048    4129.0
Name: new_cases, dtype: float64
22042 22049    2537.0
Name: new_cases, dtype: float64
22043 22050    983.0
Name: new_cases, dtype: float64
22044 22051    4497.0
Name: new_cases, dtype: float64
22045 22052    5176.0
Name: new_cases, dtype: float64
22046 22053    4207.0
Name: new_cases, dtype: float64
22047 22054    3694.0
Name: new_cases, dtype: float64
22048 22055    4013.0
Name: new_cases, dtype: float64
22049 22056    1919.0
Name: new_cases, dtype: float64
22050 22057    740.0
Name: new_cases, dtype: float64
22051 22058    3860.0
Name: new_cases, dtype: float64
22052 22059    0.0
Name: new_cases, dtype: float64
22053 22060    7560.0
Name: new_cases, dtype: float64
22054 22061    2957.0
Name: new_cases, dtype: float64
22055 22062    2803.0
Name: new_cases, dtype: float64
22056 22063    1352.0
Name: new_cases, dtype: float64
22057 22064    462.0
Name: new_cases, dtype: float64
22058 22065    3122.0
Name: new_cases, dtype: float64
22059 22066    2944.0
Name: new_cases, dtype: float64
22060 22067    2517.0
Name: new_cases, dtype: float64
22061 22068    2185.0
Name: new_cases, dtype: float64
22062 22069    2126.0
Name: new_cases, dtype: float64
22063 22070    1076.0
Name: new_cases, dtype: float64
22064 22071    418.0
Name: new_cases, dtype: float64
22065 22072    2434.0
Name: new_cases, dtype: float64
22066 22073    2096.0
Name: new_cases, dtype: float64
22067 22074    2002.0
Name: new_cases, dtype: float64
22068 22075    0.0
Name: new_cases, dtype: float64
22069 22076    3389.0
Name: new_cases, dtype: float64
22070 22077    798.0
Name: new_cases, dtype: float64
22071 22078    400.0
Name: new_cases, dtype: float64
22072 22079    1759.0
Name: new_cases, dtype: float64
22073 22080    1850.0
Name: new_cases, dtype: float64
22074 22081    1382.0
Name: new_cases, dtype: float64
22075 22082    1237.0
Name: new_cases, dtype: float64
22076 22083    652.0
Name: new_cases, dtype: float64
22077 22084    466.0
Name: new_cases, dtype: float64
22078 22085    348.0
Name: new_cases, dtype: float64
22079 22086    631.0
Name: new_cases, dtype: float64
22080 22087    367.0
Name: new_cases, dtype: float64
22081 22088    1635.0
Name: new_cases, dtype: float64
22082 22089    545.0
Name: new_cases, dtype: float64
22083 22090    1123.0
Name: new_cases, dtype: float64
22084 22091    466.0
Name: new_cases, dtype: float64
22085 22092    241.0
Name: new_cases, dtype: float64
22086 22093    1078.0
Name: new_cases, dtype: float64
22087 22094    877.0
Name: new_cases, dtype: float64
22088 22095    657.0
Name: new_cases, dtype: float64
22089 22096    506.0
Name: new_cases, dtype: float64
22090 22097    518.0
Name: new_cases, dtype: float64
22091 22098    203.0
Name: new_cases, dtype: float64
22092 22099    151.0
Name: new_cases, dtype: float64
22093 22100    677.0
Name: new_cases, dtype: float64
22094 22101    457.0
Name: new_cases, dtype: float64
22095 22102    361.0
Name: new_cases, dtype: float64
22096 22103    368.0
Name: new_cases, dtype: float64
22097 22104    362.0
Name: new_cases, dtype: float64
22098 22105    148.0
Name: new_cases, dtype: float64
22099 22106    81.0
Name: new_cases, dtype: float64
22100 22107    81.0
Name: new_cases, dtype: float64
22101 22108    406.0
Name: new_cases, dtype: float64
22102 22109    393.0
Name: new_cases, dtype: float64
22103 22110    293.0
Name: new_cases, dtype: float64
22104 22111    287.0
Name: new_cases, dtype: float64
22105 22112    115.0
Name: new_cases, dtype: float64
22106 22113    53.0
Name: new_cases, dtype: float64
22107 22114    303.0
Name: new_cases, dtype: float64
22108 22115    236.0
Name: new_cases, dtype: float64
22109 22116    197.0
Name: new_cases, dtype: float64
22110 22117    170.0
Name: new_cases, dtype: float64
22111 22118    157.0
Name: new_cases, dtype: float64
22112 22119    89.0
Name: new_cases, dtype: float64
22113 22120    47.0
Name: new_cases, dtype: float64
22114 22121    208.0
Name: new_cases, dtype: float64
22115 22122    178.0
Name: new_cases, dtype: float64
22116 22123    131.0
Name: new_cases, dtype: float64
22117 22124    100.0
Name: new_cases, dtype: float64
22118 22125    123.0
Name: new_cases, dtype: float64
22119 22126    81.0
Name: new_cases, dtype: float64
22120 22127    42.0
Name: new_cases, dtype: float64
22121 22128    157.0
Name: new_cases, dtype: float64
22122 22129    161.0
Name: new_cases, dtype: float64
22123 22130    95.0
Name: new_cases, dtype: float64
22124 22131    110.0
Name: new_cases, dtype: float64
22125 22132    105.0
Name: new_cases, dtype: float64
22126 22133    41.0
Name: new_cases, dtype: float64
22127 22134    27.0
Name: new_cases, dtype: float64
22128 22135    120.0
Name: new_cases, dtype: float64
22129 22136    94.0
Name: new_cases, dtype: float64
22130 22137    93.0
Name: new_cases, dtype: float64
22131 22138    62.0
Name: new_cases, dtype: float64
22132 22139    86.0
Name: new_cases, dtype: float64
22133 22140    28.0
Name: new_cases, dtype: float64
22134 22141    16.0
Name: new_cases, dtype: float64
22135 22142    115.0
Name: new_cases, dtype: float64
22136 22143    105.0
Name: new_cases, dtype: float64
22137 22144    78.0
Name: new_cases, dtype: float64
22138 22145    73.0
Name: new_cases, dtype: float64
22139 22146    81.0
Name: new_cases, dtype: float64
22140 22147    51.0
Name: new_cases, dtype: float64
22141 22148    0.0
Name: new_cases, dtype: float64

22142 22149    117.0
Name: new_cases, dtype: float64
22143 22150    87.0
Name: new_cases, dtype: float64
22144 22151    60.0
Name: new_cases, dtype: float64
22145 22152    55.0
Name: new_cases, dtype: float64
22146 22153    61.0
Name: new_cases, dtype: float64
22147 22154    32.0
Name: new_cases, dtype: float64
22148 22155    16.0
Name: new_cases, dtype: float64
22149 22156    83.0
Name: new_cases, dtype: float64
22150 22157    74.0
Name: new_cases, dtype: float64
22151 22158    84.0
Name: new_cases, dtype: float64
22152 22159    94.0
Name: new_cases, dtype: float64
22153 22160    76.0
Name: new_cases, dtype: float64
22154 22161    57.0
Name: new_cases, dtype: float64
22155 22162    35.0
Name: new_cases, dtype: float64
22156 22163    113.0
Name: new_cases, dtype: float64
22157 22164    145.0
Name: new_cases, dtype: float64
22158 22165    96.0
Name: new_cases, dtype: float64
22159 22166    121.0
Name: new_cases, dtype: float64
22160 22167    135.0
Name: new_cases, dtype: float64
22161 22168    54.0
Name: new_cases, dtype: float64
22162 22169    57.0
Name: new_cases, dtype: float64
22163 22170    193.0
Name: new_cases, dtype: float64
22164 22171    200.0
Name: new_cases, dtype: float64
22165 22172    216.0
Name: new_cases, dtype: float64
22166 22173    231.0
Name: new_cases, dtype: float64
22167 22174    346.0
Name: new_cases, dtype: float64
22168 22175    182.0
Name: new_cases, dtype: float64
22169 22176    94.0
Name: new_cases, dtype: float64
22170 22177    393.0
Name: new_cases, dtype: float64
22171 22178    462.0
Name: new_cases, dtype: float64
22172 22179    429.0
Name: new_cases, dtype: float64
22173 22180    500.0
Name: new_cases, dtype: float64
22174 22181    549.0
Name: new_cases, dtype: float64
22175 22182    392.0
Name: new_cases, dtype: float64
22176 22183    176.0
Name: new_cases, dtype: float64
22177 22184    774.0
Name: new_cases, dtype: float64
22178 22185    805.0
Name: new_cases, dtype: float64
22179 22186    782.0
Name: new_cases, dtype: float64
22180 22187    882.0
Name: new_cases, dtype: float64
22181 22188    1047.0
Name: new_cases, dtype: float64
22182 22189    623.0
Name: new_cases, dtype: float64
22183 22190    272.0
Name: new_cases, dtype: float64
22184 22191    1301.0
Name: new_cases, dtype: float64
22185 22192    1405.0
Name: new_cases, dtype: float64
22186 22193    1387.0
Name: new_cases, dtype: float64
22187 22194    1371.0
Name: new_cases, dtype: float64
22188 22195    1368.0
Name: new_cases, dtype: float64
22189 22196    845.0
Name: new_cases, dtype: float64
22190 22197    384.0
Name: new_cases, dtype: float64
22191 22198    1891.0
Name: new_cases, dtype: float64
22192 22199    1911.0
Name: new_cases, dtype: float64
22193 22200    1601.0
Name: new_cases, dtype: float64
22194 22201    1733.0
Name: new_cases, dtype: float64
22195 22202    1713.0
Name: new_cases, dtype: float64
22196 22203    1004.0
Name: new_cases, dtype: float64
22197 22204    451.0
Name: new_cases, dtype: float64
22198 22205    2090.0
Name: new_cases, dtype: float64
22199 22206    2053.0
Name: new_cases, dtype: float64
22200 22207    1745.0
Name: new_cases, dtype: float64
22201 22208    1564.0
Name: new_cases, dtype: float64
22202 22209    1640.0
Name: new_cases, dtype: float64
22203 22210    854.0
Name: new_cases, dtype: float64
22204 22211    488.0
Name: new_cases, dtype: float64
22205 22212    677.0
Name: new_cases, dtype: float64
22206 22213    2005.0
Name: new_cases, dtype: float64
22207 22214    1956.0
Name: new_cases, dtype: float64
22208 22215    1629.0
Name: new_cases, dtype: float64
22209 22216    1626.0
Name: new_cases, dtype: float64
22210 22217    909.0
Name: new_cases, dtype: float64
22211 22218    437.0
Name: new_cases, dtype: float64
22212 22219    1998.0
Name: new_cases, dtype: float64
22213 22220    2029.0
Name: new_cases, dtype: float64
22214 22221    1862.0
Name: new_cases, dtype: float64
22215 22222    1724.0
Name: new_cases, dtype: float64
22216 22223    1892.0
Name: new_cases, dtype: float64
22217 22224    951.0
Name: new_cases, dtype: float64
22218 22225    458.0
Name: new_cases, dtype: float64
22219 22226    2360.0
Name: new_cases, dtype: float64
22220 22227    2192.0
Name: new_cases, dtype: float64
22221 22228    850.0
Name: new_cases, dtype: float64
22222 22229    1835.0
Name: new_cases, dtype: float64
22223 22230    1904.0
Name: new_cases, dtype: float64
22224 22231    1038.0
Name: new_cases, dtype: float64
22225 22232    496.0
Name: new_cases, dtype: float64
22226 22233    2536.0
Name: new_cases, dtype: float64
22227 22234    2573.0
Name: new_cases, dtype: float64
22228 22235    2142.0
Name: new_cases, dtype: float64
22229 22236    2050.0
Name: new_cases, dtype: float64
22230 22237    2091.0
Name: new_cases, dtype: float64
22231 22238    1228.0
Name: new_cases, dtype: float64
22232 22239    513.0
Name: new_cases, dtype: float64
22233 22240    2806.0
Name: new_cases, dtype: float64
22234 22241    2866.0
Name: new_cases, dtype: float64
22235 22242    2542.0
Name: new_cases, dtype: float64
22236 22243    2302.0
Name: new_cases, dtype: float64
22237 22244    2485.0
Name: new_cases, dtype: float64
22238 22245    1246.0
Name: new_cases, dtype: float64
22239 22246    621.0
Name: new_cases, dtype: float64
22240 22247    3471.0
Name: new_cases, dtype: float64
22241 22248    3469.0
Name: new_cases, dtype: float64
22242 22249    3327.0
Name: new_cases, dtype: float64
22243 22250    3183.0
Name: new_cases, dtype: float64
22244 22251    3440.0
Name: new_cases, dtype: float64
22245 22252    1867.0
Name: new_cases, dtype: float64
22246 22253    1000.0
Name: new_cases, dtype: float64
22247 22254    4979.0
Name: new_cases, dtype: float64
22248 22255    4957.0
Name: new_cases, dtype: float64
22249 22256    4522.0
Name: new_cases, dtype: float64
22250 22257    4816.0
Name: new_cases, dtype: float64
22251 22258    4826.0
Name: new_cases, dtype: float64
22252 22259    3354.0
Name: new_cases, dtype: float64
22253 22260    1370.0
Name: new_cases, dtype: float64
22254 22261    5863.0
Name: new_cases, dtype: float64
22255 22262    6816.0
Name: new_cases, dtype: float64
22256 22263    5643.0
Name: new_cases, dtype: float64
22257 22264    5178.0
Name: new_cases, dtype: float64
22258 22265    5256.0
Name: new_cases, dtype: float64
22259 22266    2836.0
Name: new_cases, dtype: float64
22260 22267    1457.0
Name: new_cases, dtype: float64
22261 22268    6007.0
Name: new_cases, dtype: float64
22262 22269    5863.0
Name: new_cases, dtype: float64
22263 22270    4922.0
Name: new_cases, dtype: float64
22264 22271    4662.0
Name: new_cases, dtype: float64
22265 22272    4734.0
Name: new_cases, dtype: float64
22266 22273    2826.0
Name: new_cases, dtype: float64
22267 22274    1256.0
Name: new_cases, dtype: float64
22268 22275    5286.0
Name: new_cases, dtype: float64
22269 22276    4955.0
Name: new_cases, dtype: float64
22270 22277    3853.0
Name: new_cases, dtype: float64
22271 22278    3207.0
Name: new_cases, dtype: float64
22272 22279    3146.0
Name: new_cases, dtype: float64
22273 22280    1610.0
Name: new_cases, dtype: float64
22274 22281    828.0
Name: new_cases, dtype: float64
22275 22282    3223.0
Name: new_cases, dtype: float64
22276 22283    3869.0
Name: new_cases, dtype: float64
22277 22284    2839.0
Name: new_cases, dtype: float64
22278 22285    2785.0
Name: new_cases, dtype: float64
22279 22286    2737.0
Name: new_cases, dtype: float64
22280 22287    1455.0
Name: new_cases, dtype: float64
22281 22288    733.0
Name: new_cases, dtype: float64
22282 22289    3462.0
Name: new_cases, dtype: float64
22283 22290    3233.0
Name: new_cases, dtype: float64
22284 22291    2569.0
Name: new_cases, dtype: float64
22285 22292    2370.0
Name: new_cases, dtype: float64
22286 22293    2488.0
Name: new_cases, dtype: float64
22287 22294    1218.0
Name: new_cases, dtype: float64
22288 22295    728.0
Name: new_cases, dtype: float64
22289 22296    3020.0
Name: new_cases, dtype: float64
22290 22297    2681.0
Name: new_cases, dtype: float64
22291 22298    2105.0
Name: new_cases, dtype: float64
22292 22299    2018.0
Name: new_cases, dtype: float64
22293 22300    2289.0
Name: new_cases, dtype: float64
22294 22301    985.0
Name: new_cases, dtype: float64
22295 22302    706.0
Name: new_cases, dtype: float64
22296 22303    2426.0
Name: new_cases, dtype: float64
22297 22304    2299.0
Name: new_cases, dtype: float64
22298 22305    1652.0
Name: new_cases, dtype: float64
22299 22306    1827.0
Name: new_cases, dtype: float64
22300 22307    1719.0
Name: new_cases, dtype: float64
22301 22308    1073.0
Name: new_cases, dtype: float64
22302 22309    532.0
Name: new_cases, dtype: float64
22303 22310    0.0
Name: new_cases, dtype: float64
22304 22311    3963.0
Name: new_cases, dtype: float64
22305 22312    1725.0
Name: new_cases, dtype: float64
22306 22313    1443.0
Name: new_cases, dtype: float64
22307 22314    1614.0
Name: new_cases, dtype: float64
22308 22315    904.0
Name: new_cases, dtype: float64
22309 22316    456.0
Name: new_cases, dtype: float64
22310 22317    2001.0
Name: new_cases, dtype: float64
22311 22318    1883.0
Name: new_cases, dtype: float64
22312 22319    1463.0
Name: new_cases, dtype: float64
22313 22320    1966.0
Name: new_cases, dtype: float64
22314 22321    1033.0
Name: new_cases, dtype: float64
22315 22322    743.0
Name: new_cases, dtype: float64

22316 22323    838.0
Name: new_cases, dtype: float64
22317 22324    1278.0
Name: new_cases, dtype: float64
22318 22325    1235.0
Name: new_cases, dtype: float64
22319 22326    3449.0
Name: new_cases, dtype: float64
22320 22327    3616.0
Name: new_cases, dtype: float64
22321 22328    2810.0
Name: new_cases, dtype: float64
22322 22329    1076.0
Name: new_cases, dtype: float64
22323 22330    1356.0
Name: new_cases, dtype: float64
22324 22331    1918.0
Name: new_cases, dtype: float64
22325 22332    6252.0
Name: new_cases, dtype: float64
22326 22333    6766.0
Name: new_cases, dtype: float64
22327 22334    5525.0
Name: new_cases, dtype: float64
22328 22335    5524.0
Name: new_cases, dtype: float64
22329 22336    3176.0
Name: new_cases, dtype: float64
22330 21687    40.0
Name: new_cases, dtype: float64
22331 21688    23.0
Name: new_cases, dtype: float64
22332 21689    35.0
Name: new_cases, dtype: float64
22333 21690    28.0
Name: new_cases, dtype: float64
22334 21691    18.0
Name: new_cases, dtype: float64
22335 21692    28.0
Name: new_cases, dtype: float64
22336 21693    18.0
Name: new_cases, dtype: float64
23007 23014    0.0
Name: new_cases, dtype: float64
23008 23015    0.0
Name: new_cases, dtype: float64
23009 23016    0.0
Name: new_cases, dtype: float64
23010 23017    0.0
Name: new_cases, dtype: float64
23011 23018    2.0
Name: new_cases, dtype: float64
23012 23019    0.0
Name: new_cases, dtype: float64
23013 23020    0.0
Name: new_cases, dtype: float64
23014 23021    0.0
Name: new_cases, dtype: float64
23015 23022    0.0
Name: new_cases, dtype: float64
23016 23023    0.0
Name: new_cases, dtype: float64
23017 23024    0.0
Name: new_cases, dtype: float64
23018 23025    0.0
Name: new_cases, dtype: float64
23019 23026    0.0
Name: new_cases, dtype: float64
23020 23027    0.0
Name: new_cases, dtype: float64
23021 23028    0.0
Name: new_cases, dtype: float64
23022 23029    6.0
Name: new_cases, dtype: float64
23023 23030    0.0
Name: new_cases, dtype: float64
23024 23031    0.0
Name: new_cases, dtype: float64
23025 23032    0.0
Name: new_cases, dtype: float64
23026 23033    0.0
Name: new_cases, dtype: float64
23027 23034    0.0
Name: new_cases, dtype: float64
23028 23035    0.0
Name: new_cases, dtype: float64
23029 23036    0.0
Name: new_cases, dtype: float64
23030 23037    0.0
Name: new_cases, dtype: float64
23031 23038    0.0
Name: new_cases, dtype: float64
23032 23039    4.0
Name: new_cases, dtype: float64
23033 23040    0.0
Name: new_cases, dtype: float64
23034 23041    0.0
Name: new_cases, dtype: float64
23035 23042    0.0
Name: new_cases, dtype: float64
23036 23043    0.0
Name: new_cases, dtype: float64
23037 23044    0.0
Name: new_cases, dtype: float64
23038 23045    0.0
Name: new_cases, dtype: float64
23039 23046    0.0
Name: new_cases, dtype: float64
23040 23047    0.0
Name: new_cases, dtype: float64
23041 23048    0.0
Name: new_cases, dtype: float64
23042 23049    0.0
Name: new_cases, dtype: float64
23043 23050    0.0
Name: new_cases, dtype: float64
23044 23051    0.0
Name: new_cases, dtype: float64
23045 23052    0.0
Name: new_cases, dtype: float64
23046 23053    0.0
Name: new_cases, dtype: float64
23047 23054    8.0
Name: new_cases, dtype: float64
23048 23055    19.0
Name: new_cases, dtype: float64
23049 23056    0.0
Name: new_cases, dtype: float64
23050 23057    0.0
Name: new_cases, dtype: float64
23051 23058    0.0
Name: new_cases, dtype: float64
23052 23059    0.0
Name: new_cases, dtype: float64
23053 23060    0.0
Name: new_cases, dtype: float64
23054 23061    0.0
Name: new_cases, dtype: float64
23055 23062    0.0
Name: new_cases, dtype: float64
23056 23063    0.0
Name: new_cases, dtype: float64
23057 23064    0.0
Name: new_cases, dtype: float64
23058 23065    0.0
Name: new_cases, dtype: float64
23059 23066    0.0
Name: new_cases, dtype: float64
23060 23067    21.0
Name: new_cases, dtype: float64
23061 23068    0.0
Name: new_cases, dtype: float64
23062 23069    0.0
Name: new_cases, dtype: float64
23063 23070    0.0
Name: new_cases, dtype: float64
23064 23071    0.0
Name: new_cases, dtype: float64
23065 23072    0.0
Name: new_cases, dtype: float64
23066 23073    0.0
Name: new_cases, dtype: float64
23067 23074    20.0
Name: new_cases, dtype: float64
23068 23075    0.0
Name: new_cases, dtype: float64
23069 23076    0.0
Name: new_cases, dtype: float64
23070 23077    0.0
Name: new_cases, dtype: float64
23071 23078    0.0
Name: new_cases, dtype: float64
23072 23079    2.0
Name: new_cases, dtype: float64
23073 23080    0.0
Name: new_cases, dtype: float64
23074 23081    0.0
Name: new_cases, dtype: float64
23075 23082    0.0
Name: new_cases, dtype: float64
23076 23083    0.0
Name: new_cases, dtype: float64
23077 23084    19.0
Name: new_cases, dtype: float64
23078 23085    0.0
Name: new_cases, dtype: float64
23079 23086    0.0
Name: new_cases, dtype: float64
23080 23087    0.0
Name: new_cases, dtype: float64
23081 23088    0.0
Name: new_cases, dtype: float64
23082 23089    40.0
Name: new_cases, dtype: float64
23083 23090    0.0
Name: new_cases, dtype: float64
23084 23091    0.0
Name: new_cases, dtype: float64
23085 23092    0.0
Name: new_cases, dtype: float64
23086 23093    0.0
Name: new_cases, dtype: float64
23087 23094    0.0
Name: new_cases, dtype: float64
23088 23095    26.0
Name: new_cases, dtype: float64
23089 23096    0.0
Name: new_cases, dtype: float64
23090 23097    0.0
Name: new_cases, dtype: float64
23091 23098    0.0
Name: new_cases, dtype: float64
23092 23099    0.0
Name: new_cases, dtype: float64
23093 23100    0.0
Name: new_cases, dtype: float64
23094 23101    21.0
Name: new_cases, dtype: float64
23095 23102    0.0
Name: new_cases, dtype: float64
23096 23103    0.0
Name: new_cases, dtype: float64
23097 23104    0.0
Name: new_cases, dtype: float64
23098 23105    0.0
Name: new_cases, dtype: float64
23099 23106    0.0
Name: new_cases, dtype: float64
23100 23107    0.0
Name: new_cases, dtype: float64
23101 23108    0.0
Name: new_cases, dtype: float64
23102 23109    0.0
Name: new_cases, dtype: float64
23103 23110    0.0
Name: new_cases, dtype: float64
23104 23111    78.0
Name: new_cases, dtype: float64
23105 23112    0.0
Name: new_cases, dtype: float64
23106 23113    0.0
Name: new_cases, dtype: float64
23107 23114    34.0
Name: new_cases, dtype: float64
23108 23115    7.0
Name: new_cases, dtype: float64
23109 23116    0.0
Name: new_cases, dtype: float64
23110 23117    0.0
Name: new_cases, dtype: float64
23111 23118    12.0
Name: new_cases, dtype: float64
23112 23119    6.0
Name: new_cases, dtype: float64
23113 23120    0.0
Name: new_cases, dtype: float64
23114 23121    17.0
Name: new_cases, dtype: float64
23115 23122    0.0
Name: new_cases, dtype: float64
23116 23123    16.0
Name: new_cases, dtype: float64
23117 23124    0.0
Name: new_cases, dtype: float64
23118 23125    17.0
Name: new_cases, dtype: float64
23119 23126    0.0
Name: new_cases, dtype: float64
23120 23127    9.0
Name: new_cases, dtype: float64
23121 23128    0.0
Name: new_cases, dtype: float64
23122 23129    0.0
Name: new_cases, dtype: float64
23123 23130    8.0
Name: new_cases, dtype: float64
23124 23131    0.0
Name: new_cases, dtype: float64
23125 23132    0.0
Name: new_cases, dtype: float64
23126 23133    0.0
Name: new_cases, dtype: float64
23127 23134    0.0
Name: new_cases, dtype: float64
23128 23135    5.0
Name: new_cases, dtype: float64
23129 23136    0.0
Name: new_cases, dtype: float64
23130 23137    5.0
Name: new_cases, dtype: float64
23131 23138    3.0
Name: new_cases, dtype: float64
23132 23139    0.0
Name: new_cases, dtype: float64
23133 23140    0.0
Name: new_cases, dtype: float64
23134 23141    1.0
Name: new_cases, dtype: float64
23135 23142    1.0
Name: new_cases, dtype: float64
23136 23143    2.0
Name: new_cases, dtype: float64
23137 23144    0.0
Name: new_cases, dtype: float64
23138 23145    1.0
Name: new_cases, dtype: float64
23139 23146    0.0
Name: new_cases, dtype: float64
23140 23147    3.0
Name: new_cases, dtype: float64
23141 23148    6.0
Name: new_cases, dtype: float64
23142 23149    0.0
Name: new_cases, dtype: float64
23143 23150    4.0
Name: new_cases, dtype: float64
23144 23151    3.0
Name: new_cases, dtype: float64
23145 23152    1.0
Name: new_cases, dtype: float64
23146 23153    0.0
Name: new_cases, dtype: float64
23147 23154    0.0
Name: new_cases, dtype: float64
23148 23155    0.0
Name: new_cases, dtype: float64
23149 23156    1.0
Name: new_cases, dtype: float64
23150 23157    2.0
Name: new_cases, dtype: float64
23151 23158    12.0
Name: new_cases, dtype: float64
23152 23159    0.0
Name: new_cases, dtype: float64
23153 23160    0.0
Name: new_cases, dtype: float64
23154 23161    0.0
Name: new_cases, dtype: float64
23155 23162    3.0
Name: new_cases, dtype: float64
23156 23163    0.0
Name: new_cases, dtype: float64
23157 23164    3.0
Name: new_cases, dtype: float64
23158 23165    9.0
Name: new_cases, dtype: float64
23159 23166    2.0
Name: new_cases, dtype: float64

23160 23167    4.0
Name: new_cases, dtype: float64
23161 23168    0.0
Name: new_cases, dtype: float64
23162 23169    0.0
Name: new_cases, dtype: float64
23163 23170    3.0
Name: new_cases, dtype: float64
23164 23171    0.0
Name: new_cases, dtype: float64
23165 23172    2.0
Name: new_cases, dtype: float64
23166 23173    1.0
Name: new_cases, dtype: float64
23167 23174    0.0
Name: new_cases, dtype: float64
23168 23175    0.0
Name: new_cases, dtype: float64
23169 23176    0.0
Name: new_cases, dtype: float64
23170 23177    1.0
Name: new_cases, dtype: float64
23171 23178    0.0
Name: new_cases, dtype: float64
23172 23179    0.0
Name: new_cases, dtype: float64
23173 23180    0.0
Name: new_cases, dtype: float64
23174 23181    1.0
Name: new_cases, dtype: float64
23175 23182    0.0
Name: new_cases, dtype: float64
23176 23183    2.0
Name: new_cases, dtype: float64
23177 23184    1.0
Name: new_cases, dtype: float64
23178 23185    6.0
Name: new_cases, dtype: float64
23179 23186    2.0
Name: new_cases, dtype: float64
23180 23187    0.0
Name: new_cases, dtype: float64
23181 23188    17.0
Name: new_cases, dtype: float64
23182 23189    4.0
Name: new_cases, dtype: float64
23183 23190    2.0
Name: new_cases, dtype: float64
23184 23191    2.0
Name: new_cases, dtype: float64
23185 23192    3.0
Name: new_cases, dtype: float64
23186 23193    0.0
Name: new_cases, dtype: float64
23187 23194    0.0
Name: new_cases, dtype: float64
23188 23195    1.0
Name: new_cases, dtype: float64
23189 23196    0.0
Name: new_cases, dtype: float64
23190 23197    1.0
Name: new_cases, dtype: float64
23191 23198    0.0
Name: new_cases, dtype: float64
23192 23199    0.0
Name: new_cases, dtype: float64
23193 23200    2.0
Name: new_cases, dtype: float64
23194 23201    7.0
Name: new_cases, dtype: float64
23195 23202    1.0
Name: new_cases, dtype: float64
23196 23203    4.0
Name: new_cases, dtype: float64
23197 23204    0.0
Name: new_cases, dtype: float64
23198 23205    0.0
Name: new_cases, dtype: float64
23199 23206    2.0
Name: new_cases, dtype: float64
23200 23207    5.0
Name: new_cases, dtype: float64
23201 23208    6.0
Name: new_cases, dtype: float64
23202 23209    7.0
Name: new_cases, dtype: float64
23203 23210    1.0
Name: new_cases, dtype: float64
23204 23211    0.0
Name: new_cases, dtype: float64
23205 23212    1.0
Name: new_cases, dtype: float64
23206 23213    2.0
Name: new_cases, dtype: float64
23207 23214    2.0
Name: new_cases, dtype: float64
23208 23215    2.0
Name: new_cases, dtype: float64
23209 23216    0.0
Name: new_cases, dtype: float64
23210 23217    1.0
Name: new_cases, dtype: float64
23211 23218    1.0
Name: new_cases, dtype: float64
23212 23219    1.0
Name: new_cases, dtype: float64
23213 23220    22.0
Name: new_cases, dtype: float64
23214 23221    3.0
Name: new_cases, dtype: float64
23215 23222    4.0
Name: new_cases, dtype: float64
23216 23223    0.0
Name: new_cases, dtype: float64
23217 23224    8.0
Name: new_cases, dtype: float64
23218 23225    9.0
Name: new_cases, dtype: float64
23219 23226    0.0
Name: new_cases, dtype: float64
23220 23227    0.0
Name: new_cases, dtype: float64
23221 23228    6.0
Name: new_cases, dtype: float64
23222 23229    0.0
Name: new_cases, dtype: float64
23223 23230    2.0
Name: new_cases, dtype: float64
23224 23231    1.0
Name: new_cases, dtype: float64
23225 23232    5.0
Name: new_cases, dtype: float64
23226 23233    3.0
Name: new_cases, dtype: float64
23227 23234    1.0
Name: new_cases, dtype: float64
23228 23235    3.0
Name: new_cases, dtype: float64
23229 23236    1.0
Name: new_cases, dtype: float64
23230 23237    2.0
Name: new_cases, dtype: float64
23231 23238    1.0
Name: new_cases, dtype: float64
23232 23239    10.0
Name: new_cases, dtype: float64
23233 23240    0.0
Name: new_cases, dtype: float64
23234 23241    8.0
Name: new_cases, dtype: float64
23235 23242    7.0
Name: new_cases, dtype: float64
23236 23243    6.0
Name: new_cases, dtype: float64
23237 23244    2.0
Name: new_cases, dtype: float64
23238 23245    9.0
Name: new_cases, dtype: float64
23239 23246    0.0
Name: new_cases, dtype: float64
23240 23247    4.0
Name: new_cases, dtype: float64
23241 23248    4.0
Name: new_cases, dtype: float64
23242 23249    0.0
Name: new_cases, dtype: float64
23243 23250    0.0
Name: new_cases, dtype: float64
23244 23251    7.0
Name: new_cases, dtype: float64
23245 23252    1.0
Name: new_cases, dtype: float64
23246 23253    0.0
Name: new_cases, dtype: float64
23247 23254    3.0
Name: new_cases, dtype: float64
23248 23255    0.0
Name: new_cases, dtype: float64
23249 23256    2.0
Name: new_cases, dtype: float64
23250 23257    0.0
Name: new_cases, dtype: float64
23251 23258    4.0
Name: new_cases, dtype: float64
23252 23259    18.0
Name: new_cases, dtype: float64
23253 23260    4.0
Name: new_cases, dtype: float64
23254 23261    0.0
Name: new_cases, dtype: float64
23255 23262    3.0
Name: new_cases, dtype: float64
23256 23263    5.0
Name: new_cases, dtype: float64
23257 23264    1.0
Name: new_cases, dtype: float64
23258 23265    0.0
Name: new_cases, dtype: float64
23259 23266    6.0
Name: new_cases, dtype: float64
23260 23267    6.0
Name: new_cases, dtype: float64
23261 23268    10.0
Name: new_cases, dtype: float64
23262 23269    0.0
Name: new_cases, dtype: float64
23263 23270    10.0
Name: new_cases, dtype: float64
23264 23271    0.0
Name: new_cases, dtype: float64
23265 23272    1.0
Name: new_cases, dtype: float64
23266 23273    0.0
Name: new_cases, dtype: float64
23267 23274    11.0
Name: new_cases, dtype: float64
23268 23275    0.0
Name: new_cases, dtype: float64
23269 23276    13.0
Name: new_cases, dtype: float64
23270 23277    0.0
Name: new_cases, dtype: float64
23271 23278    18.0
Name: new_cases, dtype: float64
23272 23279    0.0
Name: new_cases, dtype: float64
23273 23280    5.0
Name: new_cases, dtype: float64
23274 23281    0.0
Name: new_cases, dtype: float64
23275 23282    9.0
Name: new_cases, dtype: float64
23276 23283    4.0
Name: new_cases, dtype: float64
23277 23284    0.0
Name: new_cases, dtype: float64
23278 23285    11.0
Name: new_cases, dtype: float64
23279 23286    9.0
Name: new_cases, dtype: float64
23280 23287    0.0
Name: new_cases, dtype: float64
23281 23288    42.0
Name: new_cases, dtype: float64
23282 23289    1.0
Name: new_cases, dtype: float64
23283 23290    0.0
Name: new_cases, dtype: float64
23284 23291    0.0
Name: new_cases, dtype: float64
23285 23292    101.0
Name: new_cases, dtype: float64
23286 23293    33.0
Name: new_cases, dtype: float64
23287 23294    0.0
Name: new_cases, dtype: float64
23288 23295    43.0
Name: new_cases, dtype: float64
23289 23296    41.0
Name: new_cases, dtype: float64
23290 23297    47.0
Name: new_cases, dtype: float64
23291 23298    35.0
Name: new_cases, dtype: float64
23292 23299    51.0
Name: new_cases, dtype: float64
23293 23300    9.0
Name: new_cases, dtype: float64
23294 23301    8.0
Name: new_cases, dtype: float64
23295 23302    69.0
Name: new_cases, dtype: float64
23296 23303    36.0
Name: new_cases, dtype: float64
23297 23304    22.0
Name: new_cases, dtype: float64
23298 23305    58.0
Name: new_cases, dtype: float64
23299 23306    34.0
Name: new_cases, dtype: float64
23300 23307    7.0
Name: new_cases, dtype: float64
23301 23308    2.0
Name: new_cases, dtype: float64
23302 23309    61.0
Name: new_cases, dtype: float64
23303 23310    42.0
Name: new_cases, dtype: float64
23304 23311    20.0
Name: new_cases, dtype: float64
23305 23312    9.0
Name: new_cases, dtype: float64
23306 23313    19.0
Name: new_cases, dtype: float64
23307 23314    3.0
Name: new_cases, dtype: float64
23308 23315    6.0
Name: new_cases, dtype: float64
23309 23316    23.0
Name: new_cases, dtype: float64
23310 23317    22.0
Name: new_cases, dtype: float64
23311 23318    12.0
Name: new_cases, dtype: float64
23312 23319    19.0
Name: new_cases, dtype: float64
23313 23320    6.0
Name: new_cases, dtype: float64
23314 23321    5.0
Name: new_cases, dtype: float64
23315 23322    2.0
Name: new_cases, dtype: float64
23316 23323    21.0
Name: new_cases, dtype: float64
23317 23324    20.0
Name: new_cases, dtype: float64
23318 23325    26.0
Name: new_cases, dtype: float64
23319 23326    27.0
Name: new_cases, dtype: float64
23320 23327    0.0
Name: new_cases, dtype: float64
23321 23328    25.0
Name: new_cases, dtype: float64
23322 23329    6.0
Name: new_cases, dtype: float64
23323 23330    40.0
Name: new_cases, dtype: float64
23324 23331    33.0
Name: new_cases, dtype: float64
23325 23332    27.0
Name: new_cases, dtype: float64
23326 23333    28.0
Name: new_cases, dtype: float64
23327 23334    48.0
Name: new_cases, dtype: float64
23328 23335    3.0
Name: new_cases, dtype: float64
23329 23336    7.0
Name: new_cases, dtype: float64
23330 23337    28.0
Name: new_cases, dtype: float64
23331 23338    37.0
Name: new_cases, dtype: float64
23332 23339    37.0
Name: new_cases, dtype: float64
23333 23340    38.0
Name: new_cases, dtype: float64

23334 23341    28.0
Name: new_cases, dtype: float64
23335 23342    8.0
Name: new_cases, dtype: float64
23336 23343    7.0
Name: new_cases, dtype: float64
23337 23344    16.0
Name: new_cases, dtype: float64
23338 23345    28.0
Name: new_cases, dtype: float64
23339 23346    15.0
Name: new_cases, dtype: float64
23340 23347    16.0
Name: new_cases, dtype: float64
23341 23348    20.0
Name: new_cases, dtype: float64
23342 23349    15.0
Name: new_cases, dtype: float64
23343 23350    5.0
Name: new_cases, dtype: float64
23344 23351    30.0
Name: new_cases, dtype: float64
23345 23352    27.0
Name: new_cases, dtype: float64
23346 23353    24.0
Name: new_cases, dtype: float64
23347 23354    21.0
Name: new_cases, dtype: float64
23348 23355    20.0
Name: new_cases, dtype: float64
23349 23356    0.0
Name: new_cases, dtype: float64
23350 23357    0.0
Name: new_cases, dtype: float64
23351 23358    0.0
Name: new_cases, dtype: float64
23352 23359    81.0
Name: new_cases, dtype: float64
23353 23360    21.0
Name: new_cases, dtype: float64
23354 23361    0.0
Name: new_cases, dtype: float64
23355 23362    50.0
Name: new_cases, dtype: float64
23356 23363    5.0
Name: new_cases, dtype: float64
23357 23364    10.0
Name: new_cases, dtype: float64
23358 23365    29.0
Name: new_cases, dtype: float64
23359 23366    0.0
Name: new_cases, dtype: float64
23360 23367    0.0
Name: new_cases, dtype: float64
23361 23368    0.0
Name: new_cases, dtype: float64
23362 23369    100.0
Name: new_cases, dtype: float64
23363 23370    0.0
Name: new_cases, dtype: float64
23364 23371    0.0
Name: new_cases, dtype: float64
23365 23372    53.0
Name: new_cases, dtype: float64
23366 23373    32.0
Name: new_cases, dtype: float64
23367 23374    0.0
Name: new_cases, dtype: float64
23368 23375    69.0
Name: new_cases, dtype: float64
23369 23376    0.0
Name: new_cases, dtype: float64
23370 23377    53.0
Name: new_cases, dtype: float64
23371 23378    6.0
Name: new_cases, dtype: float64
23372 23379    47.0
Name: new_cases, dtype: float64
23373 23380    10.0
Name: new_cases, dtype: float64
23374 23381    51.0
Name: new_cases, dtype: float64
23375 23382    41.0
Name: new_cases, dtype: float64
23376 23383    35.0
Name: new_cases, dtype: float64
23377 23384    0.0
Name: new_cases, dtype: float64
23378 23385    108.0
Name: new_cases, dtype: float64
23379 23386    71.0
Name: new_cases, dtype: float64
23380 23387    91.0
Name: new_cases, dtype: float64
23381 23388    53.0
Name: new_cases, dtype: float64
23382 23389    0.0
Name: new_cases, dtype: float64
23383 23390    0.0
Name: new_cases, dtype: float64
23384 23391    0.0
Name: new_cases, dtype: float64
23385 23392    166.0
Name: new_cases, dtype: float64
23386 23393    63.0
Name: new_cases, dtype: float64
23387 23394    26.0
Name: new_cases, dtype: float64
23388 23395    27.0
Name: new_cases, dtype: float64
23389 23396    46.0
Name: new_cases, dtype: float64
23390 23397    48.0
Name: new_cases, dtype: float64
23391 23398    21.0
Name: new_cases, dtype: float64
23392 23399    10.0
Name: new_cases, dtype: float64
23393 23400    57.0
Name: new_cases, dtype: float64
23394 23401    44.0
Name: new_cases, dtype: float64
23395 23402    10.0
Name: new_cases, dtype: float64
23396 23403    23.0
Name: new_cases, dtype: float64
23397 23404    20.0
Name: new_cases, dtype: float64
23398 23405    8.0
Name: new_cases, dtype: float64
23399 23406    6.0
Name: new_cases, dtype: float64
23400 23407    17.0
Name: new_cases, dtype: float64
23401 23408    24.0
Name: new_cases, dtype: float64
23402 23409    39.0
Name: new_cases, dtype: float64
23403 23410    17.0
Name: new_cases, dtype: float64
23404 23411    28.0
Name: new_cases, dtype: float64
23405 23412    23.0
Name: new_cases, dtype: float64
23406 23413    8.0
Name: new_cases, dtype: float64
23407 23414    25.0
Name: new_cases, dtype: float64
23408 23415    28.0
Name: new_cases, dtype: float64
23409 23416    21.0
Name: new_cases, dtype: float64
23410 23417    8.0
Name: new_cases, dtype: float64
23411 23418    39.0
Name: new_cases, dtype: float64
23412 23419    18.0
Name: new_cases, dtype: float64
23413 23420    6.0
Name: new_cases, dtype: float64
23414 23421    29.0
Name: new_cases, dtype: float64
23415 23422    36.0
Name: new_cases, dtype: float64
23416 23423    33.0
Name: new_cases, dtype: float64
23417 23424    43.0
Name: new_cases, dtype: float64
23418 23425    0.0
Name: new_cases, dtype: float64
23419 23426    52.0
Name: new_cases, dtype: float64
23420 23427    22.0
Name: new_cases, dtype: float64
23421 23428    24.0
Name: new_cases, dtype: float64
23422 23429    58.0
Name: new_cases, dtype: float64
23423 23430    19.0
Name: new_cases, dtype: float64
23424 23431    46.0
Name: new_cases, dtype: float64
23425 23432    39.0
Name: new_cases, dtype: float64
23426 23433    36.0
Name: new_cases, dtype: float64
23427 23434    13.0
Name: new_cases, dtype: float64
23428 23435    25.0
Name: new_cases, dtype: float64
23429 23436    16.0
Name: new_cases, dtype: float64
23430 23437    17.0
Name: new_cases, dtype: float64
23431 23438    20.0
Name: new_cases, dtype: float64
23432 23439    24.0
Name: new_cases, dtype: float64
23433 23440    20.0
Name: new_cases, dtype: float64
23434 23441    0.0
Name: new_cases, dtype: float64
23435 23442    17.0
Name: new_cases, dtype: float64
23436 23443    18.0
Name: new_cases, dtype: float64
23437 23444    15.0
Name: new_cases, dtype: float64
23438 23445    20.0
Name: new_cases, dtype: float64
23439 23446    18.0
Name: new_cases, dtype: float64
23440 23447    13.0
Name: new_cases, dtype: float64
23441 23448    11.0
Name: new_cases, dtype: float64
23442 23449    45.0
Name: new_cases, dtype: float64
23443 23450    16.0
Name: new_cases, dtype: float64
23444 23451    23.0
Name: new_cases, dtype: float64
23445 23452    0.0
Name: new_cases, dtype: float64
23446 23453    0.0
Name: new_cases, dtype: float64
23447 23454    121.0
Name: new_cases, dtype: float64
23448 23455    31.0
Name: new_cases, dtype: float64
23449 23456    27.0
Name: new_cases, dtype: float64
23450 23457    34.0
Name: new_cases, dtype: float64
23451 23458    14.0
Name: new_cases, dtype: float64
23452 23459    0.0
Name: new_cases, dtype: float64
23453 23460    0.0
Name: new_cases, dtype: float64
23454 23461    75.0
Name: new_cases, dtype: float64
23455 23462    5.0
Name: new_cases, dtype: float64
23456 23463    24.0
Name: new_cases, dtype: float64
23457 23464    30.0
Name: new_cases, dtype: float64
23458 23465    12.0
Name: new_cases, dtype: float64
23459 23466    0.0
Name: new_cases, dtype: float64
23460 23467    0.0
Name: new_cases, dtype: float64
23461 23468    27.0
Name: new_cases, dtype: float64
23462 23469    14.0
Name: new_cases, dtype: float64
23463 23470    24.0
Name: new_cases, dtype: float64
23464 23471    26.0
Name: new_cases, dtype: float64
23465 23472    23.0
Name: new_cases, dtype: float64
23466 23473    0.0
Name: new_cases, dtype: float64
23467 23474    0.0
Name: new_cases, dtype: float64
23468 23475    78.0
Name: new_cases, dtype: float64
23469 23476    20.0
Name: new_cases, dtype: float64
23470 23477    17.0
Name: new_cases, dtype: float64
23471 23478    41.0
Name: new_cases, dtype: float64
23472 23479    38.0
Name: new_cases, dtype: float64
23473 23480    0.0
Name: new_cases, dtype: float64
23474 23481    0.0
Name: new_cases, dtype: float64
23475 23482    92.0
Name: new_cases, dtype: float64
23476 23483    48.0
Name: new_cases, dtype: float64
23477 23484    54.0
Name: new_cases, dtype: float64
23478 23485    22.0
Name: new_cases, dtype: float64
23479 23486    110.0
Name: new_cases, dtype: float64
23480 23487    0.0
Name: new_cases, dtype: float64
23481 23488    0.0
Name: new_cases, dtype: float64
23482 23489    445.0
Name: new_cases, dtype: float64
23483 23490    0.0
Name: new_cases, dtype: float64
23484 23491    142.0
Name: new_cases, dtype: float64
23485 23492    150.0
Name: new_cases, dtype: float64
23486 23493    215.0
Name: new_cases, dtype: float64
23487 23494    0.0
Name: new_cases, dtype: float64
23488 23495    0.0
Name: new_cases, dtype: float64
23489 23496    425.0
Name: new_cases, dtype: float64
23490 23497    13.0
Name: new_cases, dtype: float64
23491 23498    0.0
Name: new_cases, dtype: float64
23492 23499    196.0
Name: new_cases, dtype: float64
23493 23500    374.0
Name: new_cases, dtype: float64
23494 23501    0.0
Name: new_cases, dtype: float64
23495 23502    0.0
Name: new_cases, dtype: float64
23496 23503    712.0
Name: new_cases, dtype: float64
23497 23504    0.0
Name: new_cases, dtype: float64
23498 23505    375.0
Name: new_cases, dtype: float64
23499 23506    233.0
Name: new_cases, dtype: float64
23500 23507    212.0
Name: new_cases, dtype: float64
23501 23508    0.0
Name: new_cases, dtype: float64

23502 23509    0.0
Name: new_cases, dtype: float64
23503 23510    483.0
Name: new_cases, dtype: float64
23504 23511    95.0
Name: new_cases, dtype: float64
23505 23512    0.0
Name: new_cases, dtype: float64
23506 23513    0.0
Name: new_cases, dtype: float64
23507 23514    593.0
Name: new_cases, dtype: float64
23508 23515    0.0
Name: new_cases, dtype: float64
23509 23516    0.0
Name: new_cases, dtype: float64
23510 23517    0.0
Name: new_cases, dtype: float64
23511 23518    0.0
Name: new_cases, dtype: float64
23512 23519    590.0
Name: new_cases, dtype: float64
23513 23520    218.0
Name: new_cases, dtype: float64
23514 23521    219.0
Name: new_cases, dtype: float64
23515 23522    176.0
Name: new_cases, dtype: float64
23516 23523    0.0
Name: new_cases, dtype: float64
23517 23524    0.0
Name: new_cases, dtype: float64
23518 23525    0.0
Name: new_cases, dtype: float64
23519 23526    591.0
Name: new_cases, dtype: float64
23520 23527    0.0
Name: new_cases, dtype: float64
23521 23528    0.0
Name: new_cases, dtype: float64
23522 23529    0.0
Name: new_cases, dtype: float64
23523 23530    0.0
Name: new_cases, dtype: float64
23524 23531    0.0
Name: new_cases, dtype: float64
23525 23532    0.0
Name: new_cases, dtype: float64
23526 23533    0.0
Name: new_cases, dtype: float64
23527 23534    0.0
Name: new_cases, dtype: float64
23528 23535    1462.0
Name: new_cases, dtype: float64
23529 23536    0.0
Name: new_cases, dtype: float64
23530 23537    0.0
Name: new_cases, dtype: float64
23531 23538    142.0
Name: new_cases, dtype: float64
23532 23539    0.0
Name: new_cases, dtype: float64
23533 23540    0.0
Name: new_cases, dtype: float64
23534 23541    0.0
Name: new_cases, dtype: float64
23535 23542    0.0
Name: new_cases, dtype: float64
23536 23543    0.0
Name: new_cases, dtype: float64
23537 23544    0.0
Name: new_cases, dtype: float64
23538 23545    0.0
Name: new_cases, dtype: float64
23539 23546    0.0
Name: new_cases, dtype: float64
23540 23547    2167.0
Name: new_cases, dtype: float64
23541 23548    0.0
Name: new_cases, dtype: float64
23542 23549    0.0
Name: new_cases, dtype: float64
23543 23550    0.0
Name: new_cases, dtype: float64
23544 23551    0.0
Name: new_cases, dtype: float64
23545 23552    0.0
Name: new_cases, dtype: float64
23546 23553    1149.0
Name: new_cases, dtype: float64
23547 23554    0.0
Name: new_cases, dtype: float64
23548 23555    223.0
Name: new_cases, dtype: float64
23549 23556    251.0
Name: new_cases, dtype: float64
23550 23557    292.0
Name: new_cases, dtype: float64
23551 23558    0.0
Name: new_cases, dtype: float64
23552 23559    0.0
Name: new_cases, dtype: float64
23553 23560    329.0
Name: new_cases, dtype: float64
23554 23561    225.0
Name: new_cases, dtype: float64
23555 23562    147.0
Name: new_cases, dtype: float64
23556 23563    69.0
Name: new_cases, dtype: float64
23557 23564    0.0
Name: new_cases, dtype: float64
23558 23565    0.0
Name: new_cases, dtype: float64
23559 23566    216.0
Name: new_cases, dtype: float64
23560 23567    77.0
Name: new_cases, dtype: float64
23561 23568    107.0
Name: new_cases, dtype: float64
23562 23569    72.0
Name: new_cases, dtype: float64
23563 23570    42.0
Name: new_cases, dtype: float64
23564 23571    0.0
Name: new_cases, dtype: float64
23565 23572    0.0
Name: new_cases, dtype: float64
23566 23573    175.0
Name: new_cases, dtype: float64
23567 23574    15.0
Name: new_cases, dtype: float64
23568 23575    74.0
Name: new_cases, dtype: float64
23569 23576    48.0
Name: new_cases, dtype: float64
23570 23577    27.0
Name: new_cases, dtype: float64
23571 23578    0.0
Name: new_cases, dtype: float64
23572 23579    0.0
Name: new_cases, dtype: float64
23573 23580    51.0
Name: new_cases, dtype: float64
23574 23581    9.0
Name: new_cases, dtype: float64
23575 23582    34.0
Name: new_cases, dtype: float64
23576 23583    28.0
Name: new_cases, dtype: float64
23577 23584    23.0
Name: new_cases, dtype: float64
23578 23585    0.0
Name: new_cases, dtype: float64
23579 23586    0.0
Name: new_cases, dtype: float64
23580 23587    39.0
Name: new_cases, dtype: float64
23581 23588    9.0
Name: new_cases, dtype: float64
23582 23589    19.0
Name: new_cases, dtype: float64
23583 23590    0.0
Name: new_cases, dtype: float64
23584 23591    30.0
Name: new_cases, dtype: float64
23585 23592    0.0
Name: new_cases, dtype: float64
23586 23593    0.0
Name: new_cases, dtype: float64
23587 23594    26.0
Name: new_cases, dtype: float64
23588 23595    8.0
Name: new_cases, dtype: float64
23589 23596    30.0
Name: new_cases, dtype: float64
23590 23597    10.0
Name: new_cases, dtype: float64
23591 23598    11.0
Name: new_cases, dtype: float64
23592 23599    0.0
Name: new_cases, dtype: float64
23593 23600    0.0
Name: new_cases, dtype: float64
23594 23601    55.0
Name: new_cases, dtype: float64
23595 23602    6.0
Name: new_cases, dtype: float64
23596 23603    23.0
Name: new_cases, dtype: float64
23597 23604    16.0
Name: new_cases, dtype: float64
23598 23605    11.0
Name: new_cases, dtype: float64
23599 23606    0.0
Name: new_cases, dtype: float64
23600 23607    0.0
Name: new_cases, dtype: float64
23601 23608    17.0
Name: new_cases, dtype: float64
23602 23609    2.0
Name: new_cases, dtype: float64
23603 23610    0.0
Name: new_cases, dtype: float64
23604 23611    9.0
Name: new_cases, dtype: float64
23605 23612    26.0
Name: new_cases, dtype: float64
23606 23613    0.0
Name: new_cases, dtype: float64
23607 23614    0.0
Name: new_cases, dtype: float64
23608 23615    29.0
Name: new_cases, dtype: float64
23609 23616    0.0
Name: new_cases, dtype: float64
23610 23617    17.0
Name: new_cases, dtype: float64
23611 23618    7.0
Name: new_cases, dtype: float64
23612 23619    0.0
Name: new_cases, dtype: float64
23613 23620    0.0
Name: new_cases, dtype: float64
23614 23621    0.0
Name: new_cases, dtype: float64
23615 23622    34.0
Name: new_cases, dtype: float64
23616 23623    50.0
Name: new_cases, dtype: float64
23617 23624    0.0
Name: new_cases, dtype: float64
23618 23625    87.0
Name: new_cases, dtype: float64
23619 23626    56.0
Name: new_cases, dtype: float64
23620 23627    0.0
Name: new_cases, dtype: float64
23621 23628    0.0
Name: new_cases, dtype: float64
23622 23629    220.0
Name: new_cases, dtype: float64
23623 23630    0.0
Name: new_cases, dtype: float64
23624 23631    257.0
Name: new_cases, dtype: float64
23625 23632    279.0
Name: new_cases, dtype: float64
23626 23633    0.0
Name: new_cases, dtype: float64
23627 23634    0.0
Name: new_cases, dtype: float64
23628 23635    0.0
Name: new_cases, dtype: float64
23629 23636    1217.0
Name: new_cases, dtype: float64
23630 23637    370.0
Name: new_cases, dtype: float64
23631 23638    0.0
Name: new_cases, dtype: float64
23632 23639    648.0
Name: new_cases, dtype: float64
23633 23640    0.0
Name: new_cases, dtype: float64
23634 23641    0.0
Name: new_cases, dtype: float64
23635 23642    0.0
Name: new_cases, dtype: float64
23636 23643    2567.0
Name: new_cases, dtype: float64
23637 23644    775.0
Name: new_cases, dtype: float64
23638 23645    367.0
Name: new_cases, dtype: float64
23639 23646    0.0
Name: new_cases, dtype: float64
23640 23647    0.0
Name: new_cases, dtype: float64
23641 23648    0.0
Name: new_cases, dtype: float64
23642 23649    0.0
Name: new_cases, dtype: float64
23643 23650    0.0
Name: new_cases, dtype: float64
23644 23651    4710.0
Name: new_cases, dtype: float64
23645 23652    0.0
Name: new_cases, dtype: float64
23646 23653    1475.0
Name: new_cases, dtype: float64
23647 23654    1171.0
Name: new_cases, dtype: float64
23648 Series([], Name: new_cases, dtype: float64)
23649 Series([], Name: new_cases, dtype: float64)
23650 Series([], Name: new_cases, dtype: float64)
23651 Series([], Name: new_cases, dtype: float64)
23652 Series([], Name: new_cases, dtype: float64)
23653 Series([], Name: new_cases, dtype: float64)
23654 Series([], Name: new_cases, dtype: float64)
25043 25050    0.0
Name: new_cases, dtype: float64
25044 25051    0.0
Name: new_cases, dtype: float64
25045 25052    0.0
Name: new_cases, dtype: float64
25046 25053    1.0
Name: new_cases, dtype: float64
25047 25054    0.0
Name: new_cases, dtype: float64
25048 25055    2.0
Name: new_cases, dtype: float64
25049 25056    0.0
Name: new_cases, dtype: float64
25050 25057    0.0
Name: new_cases, dtype: float64
25051 25058    0.0
Name: new_cases, dtype: float64

25052 25059    0.0
Name: new_cases, dtype: float64
25053 25060    0.0
Name: new_cases, dtype: float64
25054 25061    0.0
Name: new_cases, dtype: float64
25055 25062    0.0
Name: new_cases, dtype: float64
25056 25063    0.0
Name: new_cases, dtype: float64
25057 25064    0.0
Name: new_cases, dtype: float64
25058 25065    1.0
Name: new_cases, dtype: float64
25059 25066    0.0
Name: new_cases, dtype: float64
25060 25067    0.0
Name: new_cases, dtype: float64
25061 25068    0.0
Name: new_cases, dtype: float64
25062 25069    1.0
Name: new_cases, dtype: float64
25063 25070    0.0
Name: new_cases, dtype: float64
25064 25071    0.0
Name: new_cases, dtype: float64
25065 25072    1.0
Name: new_cases, dtype: float64
25066 25073    2.0
Name: new_cases, dtype: float64
25067 25074    0.0
Name: new_cases, dtype: float64
25068 25075    2.0
Name: new_cases, dtype: float64
25069 25076    1.0
Name: new_cases, dtype: float64
25070 25077    6.0
Name: new_cases, dtype: float64
25071 25078    5.0
Name: new_cases, dtype: float64
25072 25079    6.0
Name: new_cases, dtype: float64
25073 25080    5.0
Name: new_cases, dtype: float64
25074 25081    5.0
Name: new_cases, dtype: float64
25075 25082    4.0
Name: new_cases, dtype: float64
25076 25083    14.0
Name: new_cases, dtype: float64
25077 25084    4.0
Name: new_cases, dtype: float64
25078 25085    10.0
Name: new_cases, dtype: float64
25079 25086    14.0
Name: new_cases, dtype: float64
25080 25087    4.0
Name: new_cases, dtype: float64
25081 25088    35.0
Name: new_cases, dtype: float64
25082 25089    14.0
Name: new_cases, dtype: float64
25083 25090    72.0
Name: new_cases, dtype: float64
25084 25091    23.0
Name: new_cases, dtype: float64
25085 25092    60.0
Name: new_cases, dtype: float64
25086 25093    154.0
Name: new_cases, dtype: float64
25087 25094    82.0
Name: new_cases, dtype: float64
25088 25095    200.0
Name: new_cases, dtype: float64
25089 25096    189.0
Name: new_cases, dtype: float64
25090 25097    254.0
Name: new_cases, dtype: float64
25091 25098    478.0
Name: new_cases, dtype: float64
25092 25099    392.0
Name: new_cases, dtype: float64
25093 25100    555.0
Name: new_cases, dtype: float64
25094 25101    585.0
Name: new_cases, dtype: float64
25095 25102    498.0
Name: new_cases, dtype: float64
25096 25103    867.0
Name: new_cases, dtype: float64
25097 25104    699.0
Name: new_cases, dtype: float64
25098 25105    836.0
Name: new_cases, dtype: float64
25099 25106    930.0
Name: new_cases, dtype: float64
25100 25107    1106.0
Name: new_cases, dtype: float64
25101 25108    1125.0
Name: new_cases, dtype: float64
25102 25109    1281.0
Name: new_cases, dtype: float64
25103 25110    1692.0
Name: new_cases, dtype: float64
25104 25111    1340.0
Name: new_cases, dtype: float64
25105 25112    1347.0
Name: new_cases, dtype: float64
25106 25113    1569.0
Name: new_cases, dtype: float64
25107 25114    1046.0
Name: new_cases, dtype: float64
25108 25115    1337.0
Name: new_cases, dtype: float64
25109 25116    1296.0
Name: new_cases, dtype: float64
25110 25117    1379.0
Name: new_cases, dtype: float64
25111 25118    1244.0
Name: new_cases, dtype: float64
25112 25119    1307.0
Name: new_cases, dtype: float64
25113 25120    1219.0
Name: new_cases, dtype: float64
25114 25121    1634.0
Name: new_cases, dtype: float64
25115 25122    1626.0
Name: new_cases, dtype: float64
25116 25123    1660.0
Name: new_cases, dtype: float64
25117 25124    2567.0
Name: new_cases, dtype: float64
25118 25125    2086.0
Name: new_cases, dtype: float64
25119 25126    1482.0
Name: new_cases, dtype: float64
25120 25127    1668.0
Name: new_cases, dtype: float64
25121 25128    1565.0
Name: new_cases, dtype: float64
25122 25129    1743.0
Name: new_cases, dtype: float64
25123 25130    2307.0
Name: new_cases, dtype: float64
25124 25131    1669.0
Name: new_cases, dtype: float64
25125 25132    1697.0
Name: new_cases, dtype: float64
25126 25133    1563.0
Name: new_cases, dtype: float64
25127 25134    1432.0
Name: new_cases, dtype: float64
25128 25135    1619.0
Name: new_cases, dtype: float64
25129 25136    1676.0
Name: new_cases, dtype: float64
25130 25137    1764.0
Name: new_cases, dtype: float64
25131 25138    1655.0
Name: new_cases, dtype: float64
25132 25139    1833.0
Name: new_cases, dtype: float64
25133 25140    1474.0
Name: new_cases, dtype: float64
25134 25141    1160.0
Name: new_cases, dtype: float64
25135 25142    1560.0
Name: new_cases, dtype: float64
25136 25143    1357.0
Name: new_cases, dtype: float64
25137 25144    1603.0
Name: new_cases, dtype: float64
25138 25145    1443.0
Name: new_cases, dtype: float64
25139 25146    1339.0
Name: new_cases, dtype: float64
25140 25147    1160.0
Name: new_cases, dtype: float64
25141 25148    1091.0
Name: new_cases, dtype: float64
25142 25149    1150.0
Name: new_cases, dtype: float64
25143 25150    1197.0
Name: new_cases, dtype: float64
25144 25151    1224.0
Name: new_cases, dtype: float64
25145 25152    1121.0
Name: new_cases, dtype: float64
25146 25153    1263.0
Name: new_cases, dtype: float64
25147 25154    1180.0
Name: new_cases, dtype: float64
25148 25155    1121.0
Name: new_cases, dtype: float64
25149 25156    1041.0
Name: new_cases, dtype: float64
25150 25157    1150.0
Name: new_cases, dtype: float64
25151 25158    1305.0
Name: new_cases, dtype: float64
25152 25159    1162.0
Name: new_cases, dtype: float64
25153 25160    1164.0
Name: new_cases, dtype: float64
25154 25161    1009.0
Name: new_cases, dtype: float64
25155 25162    926.0
Name: new_cases, dtype: float64
25156 25163    948.0
Name: new_cases, dtype: float64
25157 25164    805.0
Name: new_cases, dtype: float64
25158 25165    878.0
Name: new_cases, dtype: float64
25159 25166    839.0
Name: new_cases, dtype: float64
25160 25167    835.0
Name: new_cases, dtype: float64
25161 25168    751.0
Name: new_cases, dtype: float64
25162 25169    683.0
Name: new_cases, dtype: float64
25163 25170    842.0
Name: new_cases, dtype: float64
25164 25171    661.0
Name: new_cases, dtype: float64
25165 25172    667.0
Name: new_cases, dtype: float64
25166 25173    625.0
Name: new_cases, dtype: float64
25167 25174    666.0
Name: new_cases, dtype: float64
25168 25175    548.0
Name: new_cases, dtype: float64
25169 25176    667.0
Name: new_cases, dtype: float64
25170 25177    521.0
Name: new_cases, dtype: float64
25171 25178    489.0
Name: new_cases, dtype: float64
25172 25179    495.0
Name: new_cases, dtype: float64
25173 25180    449.0
Name: new_cases, dtype: float64
25174 25181    430.0
Name: new_cases, dtype: float64
25175 25182    411.0
Name: new_cases, dtype: float64
25176 25183    327.0
Name: new_cases, dtype: float64
25177 25184    369.0
Name: new_cases, dtype: float64
25178 25185    366.0
Name: new_cases, dtype: float64
25179 25186    408.0
Name: new_cases, dtype: float64
25180 25187    401.0
Name: new_cases, dtype: float64
25181 25188    403.0
Name: new_cases, dtype: float64
25182 25189    419.0
Name: new_cases, dtype: float64
25183 25190    305.0
Name: new_cases, dtype: float64
25184 25191    356.0
Name: new_cases, dtype: float64
25185 25192    394.0
Name: new_cases, dtype: float64
25186 25193    356.0
Name: new_cases, dtype: float64
25187 25194    324.0
Name: new_cases, dtype: float64
25188 25195    251.0
Name: new_cases, dtype: float64
25189 25196    337.0
Name: new_cases, dtype: float64
25190 25197    373.0
Name: new_cases, dtype: float64
25191 25198    384.0
Name: new_cases, dtype: float64
25192 25199    297.0
Name: new_cases, dtype: float64
25193 25200    197.0
Name: new_cases, dtype: float64
25194 25201    357.0
Name: new_cases, dtype: float64
25195 25202    320.0
Name: new_cases, dtype: float64
25196 25203    213.0
Name: new_cases, dtype: float64
25197 25204    187.0
Name: new_cases, dtype: float64
25198 25205    415.0
Name: new_cases, dtype: float64
25199 25206    255.0
Name: new_cases, dtype: float64
25200 25207    329.0
Name: new_cases, dtype: float64
25201 25208    315.0
Name: new_cases, dtype: float64
25202 25209    340.0
Name: new_cases, dtype: float64
25203 25210    176.0
Name: new_cases, dtype: float64
25204 25211    159.0
Name: new_cases, dtype: float64
25205 25212    673.0
Name: new_cases, dtype: float64
25206 25213    387.0
Name: new_cases, dtype: float64
25207 25214    361.0
Name: new_cases, dtype: float64
25208 25215    447.0
Name: new_cases, dtype: float64

25209 25216    470.0
Name: new_cases, dtype: float64
25210 25217    346.0
Name: new_cases, dtype: float64
25211 25218    255.0
Name: new_cases, dtype: float64
25212 25219    751.0
Name: new_cases, dtype: float64
25213 25220    505.0
Name: new_cases, dtype: float64
25214 25221    349.0
Name: new_cases, dtype: float64
25215 25222    658.0
Name: new_cases, dtype: float64
25216 25223    714.0
Name: new_cases, dtype: float64
25217 25224    346.0
Name: new_cases, dtype: float64
25218 25225    297.0
Name: new_cases, dtype: float64
25219 25226    626.0
Name: new_cases, dtype: float64
25220 25227    361.0
Name: new_cases, dtype: float64
25221 25228    487.0
Name: new_cases, dtype: float64
25222 25229    415.0
Name: new_cases, dtype: float64
25223 25230    557.0
Name: new_cases, dtype: float64
25224 25231    226.0
Name: new_cases, dtype: float64
25225 25232    196.0
Name: new_cases, dtype: float64
25226 25233    226.0
Name: new_cases, dtype: float64
25227 25234    713.0
Name: new_cases, dtype: float64
25228 25235    344.0
Name: new_cases, dtype: float64
25229 25236    313.0
Name: new_cases, dtype: float64
25230 25237    536.0
Name: new_cases, dtype: float64
25231 25238    233.0
Name: new_cases, dtype: float64
25232 25239    212.0
Name: new_cases, dtype: float64
25233 25240    630.0
Name: new_cases, dtype: float64
25234 25241    345.0
Name: new_cases, dtype: float64
25235 25242    309.0
Name: new_cases, dtype: float64
25236 25243    471.0
Name: new_cases, dtype: float64
25237 25244    413.0
Name: new_cases, dtype: float64
25238 25245    206.0
Name: new_cases, dtype: float64
25239 25246    156.0
Name: new_cases, dtype: float64
25240 25247    209.0
Name: new_cases, dtype: float64
25241 25248    901.0
Name: new_cases, dtype: float64
25242 25249    333.0
Name: new_cases, dtype: float64
25243 25250    236.0
Name: new_cases, dtype: float64
25244 25251    707.0
Name: new_cases, dtype: float64
25245 25252    209.0
Name: new_cases, dtype: float64
25246 25253    259.0
Name: new_cases, dtype: float64
25247 25254    753.0
Name: new_cases, dtype: float64
25248 25255    345.0
Name: new_cases, dtype: float64
25249 25256    461.0
Name: new_cases, dtype: float64
25250 25257    467.0
Name: new_cases, dtype: float64
25251 25258    547.0
Name: new_cases, dtype: float64
25252 25259    329.0
Name: new_cases, dtype: float64
25253 25260    247.0
Name: new_cases, dtype: float64
25254 25261    1020.0
Name: new_cases, dtype: float64
25255 25262    536.0
Name: new_cases, dtype: float64
25256 25263    571.0
Name: new_cases, dtype: float64
25257 25264    626.0
Name: new_cases, dtype: float64
25258 25265    615.0
Name: new_cases, dtype: float64
25259 25266    390.0
Name: new_cases, dtype: float64
25260 25267    368.0
Name: new_cases, dtype: float64
25261 25268    380.0
Name: new_cases, dtype: float64
25262 25269    1491.0
Name: new_cases, dtype: float64
25263 25270    450.0
Name: new_cases, dtype: float64
25264 25271    893.0
Name: new_cases, dtype: float64
25265 25272    807.0
Name: new_cases, dtype: float64
25266 25273    539.0
Name: new_cases, dtype: float64
25267 25274    513.0
Name: new_cases, dtype: float64
25268 25275    1459.0
Name: new_cases, dtype: float64
25269 25276    831.0
Name: new_cases, dtype: float64
25270 25277    952.0
Name: new_cases, dtype: float64
25271 25278    879.0
Name: new_cases, dtype: float64
25272 25279    1364.0
Name: new_cases, dtype: float64
25273 25280    624.0
Name: new_cases, dtype: float64
25274 25281    1184.0
Name: new_cases, dtype: float64
25275 25282    1725.0
Name: new_cases, dtype: float64
25276 25283    1305.0
Name: new_cases, dtype: float64
25277 25284    1301.0
Name: new_cases, dtype: float64
25278 25285    1292.0
Name: new_cases, dtype: float64
25279 25286    1736.0
Name: new_cases, dtype: float64
25280 25287    1268.0
Name: new_cases, dtype: float64
25281 25288    1612.0
Name: new_cases, dtype: float64
25282 25289    1950.0
Name: new_cases, dtype: float64
25283 25290    1931.0
Name: new_cases, dtype: float64
25284 25291    2295.0
Name: new_cases, dtype: float64
25285 25292    1847.0
Name: new_cases, dtype: float64
25286 25293    2241.0
Name: new_cases, dtype: float64
25287 25294    1354.0
Name: new_cases, dtype: float64
25288 25295    2111.0
Name: new_cases, dtype: float64
25289 25296    2537.0
Name: new_cases, dtype: float64
25290 25297    2009.0
Name: new_cases, dtype: float64
25291 25298    1700.0
Name: new_cases, dtype: float64
25292 25299    2369.0
Name: new_cases, dtype: float64
25293 25300    2933.0
Name: new_cases, dtype: float64
25294 25301    1955.0
Name: new_cases, dtype: float64
25295 25302    1774.0
Name: new_cases, dtype: float64
25296 25303    928.0
Name: new_cases, dtype: float64
25297 25304    4245.0
Name: new_cases, dtype: float64
25298 25305    2469.0
Name: new_cases, dtype: float64
25299 25306    2476.0
Name: new_cases, dtype: float64
25300 25307    2645.0
Name: new_cases, dtype: float64
25301 25308    1196.0
Name: new_cases, dtype: float64
25302 25309    2336.0
Name: new_cases, dtype: float64
25303 25310    3115.0
Name: new_cases, dtype: float64
25304 25311    2489.0
Name: new_cases, dtype: float64
25305 25312    2596.0
Name: new_cases, dtype: float64
25306 25313    2480.0
Name: new_cases, dtype: float64
25307 25314    3033.0
Name: new_cases, dtype: float64
25308 25315    1361.0
Name: new_cases, dtype: float64
25309 25316    2769.0
Name: new_cases, dtype: float64
25310 25317    4280.0
Name: new_cases, dtype: float64
25311 25318    2737.0
Name: new_cases, dtype: float64
25312 25319    2725.0
Name: new_cases, dtype: float64
25313 25320    3051.0
Name: new_cases, dtype: float64
25314 25321    3401.0
Name: new_cases, dtype: float64
25315 25322    2293.0
Name: new_cases, dtype: float64
25316 25323    2395.0
Name: new_cases, dtype: float64
25317 25324    3388.0
Name: new_cases, dtype: float64
25318 25325    4931.0
Name: new_cases, dtype: float64
25319 25326    2917.0
Name: new_cases, dtype: float64
25320 25327    2917.0
Name: new_cases, dtype: float64
25321 25328    5456.0
Name: new_cases, dtype: float64
25322 25329    4350.0
Name: new_cases, dtype: float64
25323 25330    3850.0
Name: new_cases, dtype: float64
25324 25331    4909.0
Name: new_cases, dtype: float64
25325 25332    4588.0
Name: new_cases, dtype: float64
25326 25333    3996.0
Name: new_cases, dtype: float64
25327 25334    5441.0
Name: new_cases, dtype: float64
25328 25335    4844.0
Name: new_cases, dtype: float64
25329 25336    4221.0
Name: new_cases, dtype: float64
25330 25337    4203.0
Name: new_cases, dtype: float64
25331 25338    5840.0
Name: new_cases, dtype: float64
25332 25339    4606.0
Name: new_cases, dtype: float64
25333 25340    4543.0
Name: new_cases, dtype: float64
25334 25341    4895.0
Name: new_cases, dtype: float64
25335 25342    4875.0
Name: new_cases, dtype: float64
25336 25343    4884.0
Name: new_cases, dtype: float64
25337 25344    4798.0
Name: new_cases, dtype: float64
25338 25345    6708.0
Name: new_cases, dtype: float64
25339 25346    5389.0
Name: new_cases, dtype: float64
25340 25347    5241.0
Name: new_cases, dtype: float64
25341 25348    5550.0
Name: new_cases, dtype: float64
25342 25349    5967.0
Name: new_cases, dtype: float64
25343 25350    5640.0
Name: new_cases, dtype: float64
25344 25351    5380.0
Name: new_cases, dtype: float64
25345 25352    7795.0
Name: new_cases, dtype: float64
25346 25353    5835.0
Name: new_cases, dtype: float64
25347 25354    6485.0
Name: new_cases, dtype: float64
25348 25355    6297.0
Name: new_cases, dtype: float64
25349 25356    6840.0
Name: new_cases, dtype: float64
25350 25357    5966.0
Name: new_cases, dtype: float64
25351 25358    6150.0
Name: new_cases, dtype: float64
25352 25359    7773.0
Name: new_cases, dtype: float64
25353 25360    6266.0
Name: new_cases, dtype: float64
25354 25361    6417.0
Name: new_cases, dtype: float64
25355 25362    6604.0
Name: new_cases, dtype: float64
25356 25363    6913.0
Name: new_cases, dtype: float64
25357 25364    6078.0
Name: new_cases, dtype: float64
25358 25365    5684.0
Name: new_cases, dtype: float64
25359 25366    8645.0
Name: new_cases, dtype: float64
25360 25367    6291.0
Name: new_cases, dtype: float64
25361 25368    6733.0
Name: new_cases, dtype: float64
25362 25369    7467.0
Name: new_cases, dtype: float64
25363 25370    7044.0
Name: new_cases, dtype: float64
25364 25371    6476.0
Name: new_cases, dtype: float64
25365 25372    5828.0
Name: new_cases, dtype: float64
25366 25373    7576.0
Name: new_cases, dtype: float64
25367 25374    6231.0
Name: new_cases, dtype: float64
25368 25375    6897.0
Name: new_cases, dtype: float64

25369 25376    6732.0
Name: new_cases, dtype: float64
25370 25377    4047.0
Name: new_cases, dtype: float64
25371 25378    5201.0
Name: new_cases, dtype: float64
25372 25379    5465.0
Name: new_cases, dtype: float64
25373 25380    6507.0
Name: new_cases, dtype: float64
25374 25381    8667.0
Name: new_cases, dtype: float64
25375 25382    8750.0
Name: new_cases, dtype: float64
25376 25383    6856.0
Name: new_cases, dtype: float64
25377 25384    3731.0
Name: new_cases, dtype: float64
25378 25385    6931.0
Name: new_cases, dtype: float64
25379 25386    10645.0
Name: new_cases, dtype: float64
25380 25387    10065.0
Name: new_cases, dtype: float64
25381 25388    7328.0
Name: new_cases, dtype: float64
25382 25389    8308.0
Name: new_cases, dtype: float64
25383 25390    8540.0
Name: new_cases, dtype: float64
25384 25391    9395.0
Name: new_cases, dtype: float64
25385 25392    7274.0
Name: new_cases, dtype: float64
25386 25393    6729.0
Name: new_cases, dtype: float64
25387 25394    8249.0
Name: new_cases, dtype: float64
25388 25395    6391.0
Name: new_cases, dtype: float64
25389 25396    7082.0
Name: new_cases, dtype: float64
25390 25397    7262.0
Name: new_cases, dtype: float64
25391 25398    6844.0
Name: new_cases, dtype: float64
25392 25399    6060.0
Name: new_cases, dtype: float64
25393 25400    6052.0
Name: new_cases, dtype: float64
25394 25401    6125.0
Name: new_cases, dtype: float64
25395 25402    5159.0
Name: new_cases, dtype: float64
25396 25403    5772.0
Name: new_cases, dtype: float64
25397 25404    6283.0
Name: new_cases, dtype: float64
25398 25405    5730.0
Name: new_cases, dtype: float64
25399 25406    4739.0
Name: new_cases, dtype: float64
25400 25407    4387.0
Name: new_cases, dtype: float64
25401 25408    5632.0
Name: new_cases, dtype: float64
25402 25409    4226.0
Name: new_cases, dtype: float64
25403 25410    4265.0
Name: new_cases, dtype: float64
25404 25411    4725.0
Name: new_cases, dtype: float64
25405 25412    4813.0
Name: new_cases, dtype: float64
25406 25413    3976.0
Name: new_cases, dtype: float64
25407 25414    3588.0
Name: new_cases, dtype: float64
25408 25415    4588.0
Name: new_cases, dtype: float64
25409 25416    3062.0
Name: new_cases, dtype: float64
25410 25417    3296.0
Name: new_cases, dtype: float64
25411 25418    3969.0
Name: new_cases, dtype: float64
25412 25419    4254.0
Name: new_cases, dtype: float64
25413 25420    3106.0
Name: new_cases, dtype: float64
25414 25421    2963.0
Name: new_cases, dtype: float64
25415 25422    3727.0
Name: new_cases, dtype: float64
25416 25423    2826.0
Name: new_cases, dtype: float64
25417 25424    3441.0
Name: new_cases, dtype: float64
25418 25425    3071.0
Name: new_cases, dtype: float64
25419 25426    2716.0
Name: new_cases, dtype: float64
25420 25427    3581.0
Name: new_cases, dtype: float64
25421 25428    2017.0
Name: new_cases, dtype: float64
25422 25429    1706.0
Name: new_cases, dtype: float64
25423 25430    4397.0
Name: new_cases, dtype: float64
25424 25431    2543.0
Name: new_cases, dtype: float64
25425 25432    3395.0
Name: new_cases, dtype: float64
25426 25433    3061.0
Name: new_cases, dtype: float64
25427 25434    2606.0
Name: new_cases, dtype: float64
25428 25435    2557.0
Name: new_cases, dtype: float64
25429 25436    3284.0
Name: new_cases, dtype: float64
25430 25437    3305.0
Name: new_cases, dtype: float64
25431 25438    2994.0
Name: new_cases, dtype: float64
25432 25439    3101.0
Name: new_cases, dtype: float64
25433 25440    3227.0
Name: new_cases, dtype: float64
25434 25441    2530.0
Name: new_cases, dtype: float64
25435 25442    2185.0
Name: new_cases, dtype: float64
25436 25443    3666.0
Name: new_cases, dtype: float64
25437 25444    2838.0
Name: new_cases, dtype: float64
25438 25445    2740.0
Name: new_cases, dtype: float64
25439 25446    3132.0
Name: new_cases, dtype: float64
25440 25447    2873.0
Name: new_cases, dtype: float64
25441 25448    2763.0
Name: new_cases, dtype: float64
25442 25449    2552.0
Name: new_cases, dtype: float64
25443 25450    4082.0
Name: new_cases, dtype: float64
25444 25451    3074.0
Name: new_cases, dtype: float64
25445 25452    2985.0
Name: new_cases, dtype: float64
25446 25453    3123.0
Name: new_cases, dtype: float64
25447 25454    3573.0
Name: new_cases, dtype: float64
25448 25455    2915.0
Name: new_cases, dtype: float64
25449 25456    2645.0
Name: new_cases, dtype: float64
25450 25457    3790.0
Name: new_cases, dtype: float64
25451 25458    3017.0
Name: new_cases, dtype: float64
25452 25459    3433.0
Name: new_cases, dtype: float64
25453 25460    3673.0
Name: new_cases, dtype: float64
25454 25461    4274.0
Name: new_cases, dtype: float64
25455 25462    3323.0
Name: new_cases, dtype: float64
25456 25463    3142.0
Name: new_cases, dtype: float64
25457 25464    4859.0
Name: new_cases, dtype: float64
25458 25465    3678.0
Name: new_cases, dtype: float64
25459 25466    4196.0
Name: new_cases, dtype: float64
25460 25467    5166.0
Name: new_cases, dtype: float64
25461 25468    5084.0
Name: new_cases, dtype: float64
25462 25469    4237.0
Name: new_cases, dtype: float64
25463 25470    4090.0
Name: new_cases, dtype: float64
25464 25471    6313.0
Name: new_cases, dtype: float64
25465 25472    3886.0
Name: new_cases, dtype: float64
25466 25473    9128.0
Name: new_cases, dtype: float64
25467 25474    5756.0
Name: new_cases, dtype: float64
25468 25475    3633.0
Name: new_cases, dtype: float64
25469 25476    7096.0
Name: new_cases, dtype: float64
25470 25477    3494.0
Name: new_cases, dtype: float64
25471 25478    8288.0
Name: new_cases, dtype: float64
25472 25479    10866.0
Name: new_cases, dtype: float64
25473 25480    7760.0
Name: new_cases, dtype: float64
25474 25481    8347.0
Name: new_cases, dtype: float64
25475 25482    9266.0
Name: new_cases, dtype: float64
25476 25483    7369.0
Name: new_cases, dtype: float64
25477 25484    7673.0
Name: new_cases, dtype: float64
25478 25485    10541.0
Name: new_cases, dtype: float64
25479 25486    7466.0
Name: new_cases, dtype: float64
25480 25487    8952.0
Name: new_cases, dtype: float64
25481 25488    9778.0
Name: new_cases, dtype: float64
25482 25489    9258.0
Name: new_cases, dtype: float64
25483 25490    7080.0
Name: new_cases, dtype: float64
25484 25491    7890.0
Name: new_cases, dtype: float64
25485 25492    10316.0
Name: new_cases, dtype: float64
25486 25493    7314.0
Name: new_cases, dtype: float64
25487 25494    8219.0
Name: new_cases, dtype: float64
25488 25495    8901.0
Name: new_cases, dtype: float64
25489 25496    8464.0
Name: new_cases, dtype: float64
25490 25497    7461.0
Name: new_cases, dtype: float64
25491 25498    6803.0
Name: new_cases, dtype: float64
25492 25499    8916.0
Name: new_cases, dtype: float64
25493 25500    7029.0
Name: new_cases, dtype: float64
25494 25501    8222.0
Name: new_cases, dtype: float64
25495 25502    9263.0
Name: new_cases, dtype: float64
25496 25503    8391.0
Name: new_cases, dtype: float64
25497 25504    6364.0
Name: new_cases, dtype: float64
25498 25505    5737.0
Name: new_cases, dtype: float64
25499 25506    10985.0
Name: new_cases, dtype: float64
25500 25507    6746.0
Name: new_cases, dtype: float64
25501 25508    7779.0
Name: new_cases, dtype: float64
25502 25509    8090.0
Name: new_cases, dtype: float64
25503 25510    7728.0
Name: new_cases, dtype: float64
25504 25511    5942.0
Name: new_cases, dtype: float64
25505 25512    5442.0
Name: new_cases, dtype: float64
25506 25513    8871.0
Name: new_cases, dtype: float64
25507 25514    5552.0
Name: new_cases, dtype: float64
25508 25515    6666.0
Name: new_cases, dtype: float64
25509 25516    5897.0
Name: new_cases, dtype: float64
25510 25517    6735.0
Name: new_cases, dtype: float64
25511 25518    4390.0
Name: new_cases, dtype: float64
25512 25519    4145.0
Name: new_cases, dtype: float64
25513 25520    6450.0
Name: new_cases, dtype: float64
25514 25521    3912.0
Name: new_cases, dtype: float64
25515 25522    5030.0
Name: new_cases, dtype: float64
25516 25523    4850.0
Name: new_cases, dtype: float64
25517 25524    4334.0
Name: new_cases, dtype: float64
25518 25525    3245.0
Name: new_cases, dtype: float64
25519 25526    2828.0
Name: new_cases, dtype: float64
25520 25527    1716.0
Name: new_cases, dtype: float64
25521 25528    3751.0
Name: new_cases, dtype: float64
25522 25529    2486.0
Name: new_cases, dtype: float64
25523 25530    4698.0
Name: new_cases, dtype: float64
25524 25531    3095.0
Name: new_cases, dtype: float64
25525 25532    2159.0
Name: new_cases, dtype: float64
25526 25533    1943.0
Name: new_cases, dtype: float64
25527 25534    2943.0
Name: new_cases, dtype: float64
25528 25535    1726.0
Name: new_cases, dtype: float64
25529 25536    2190.0
Name: new_cases, dtype: float64
25530 25537    2179.0
Name: new_cases, dtype: float64
25531 25538    1989.0
Name: new_cases, dtype: float64
25532 25539    1333.0
Name: new_cases, dtype: float64
25533 25540    1349.0
Name: new_cases, dtype: float64

25534 25541    1789.0
Name: new_cases, dtype: float64
25535 25542    1121.0
Name: new_cases, dtype: float64
25536 25543    1437.0
Name: new_cases, dtype: float64
25537 25544    1490.0
Name: new_cases, dtype: float64
25538 25545    1378.0
Name: new_cases, dtype: float64
25539 25546    1140.0
Name: new_cases, dtype: float64
25540 25547    974.0
Name: new_cases, dtype: float64
25541 25548    1319.0
Name: new_cases, dtype: float64
25542 25549    893.0
Name: new_cases, dtype: float64
25543 25550    1082.0
Name: new_cases, dtype: float64
25544 25551    1101.0
Name: new_cases, dtype: float64
25545 25552    968.0
Name: new_cases, dtype: float64
25546 25553    737.0
Name: new_cases, dtype: float64
25547 25554    580.0
Name: new_cases, dtype: float64
25548 25555    1036.0
Name: new_cases, dtype: float64
25549 25556    510.0
Name: new_cases, dtype: float64
25550 25557    718.0
Name: new_cases, dtype: float64
25551 25558    716.0
Name: new_cases, dtype: float64
25552 25559    622.0
Name: new_cases, dtype: float64
25553 25560    533.0
Name: new_cases, dtype: float64
25554 25561    398.0
Name: new_cases, dtype: float64
25555 25562    931.0
Name: new_cases, dtype: float64
25556 25563    565.0
Name: new_cases, dtype: float64
25557 25564    552.0
Name: new_cases, dtype: float64
25558 25565    151.0
Name: new_cases, dtype: float64
25559 25566    839.0
Name: new_cases, dtype: float64
25560 25567    342.0
Name: new_cases, dtype: float64
25561 25568    282.0
Name: new_cases, dtype: float64
25562 25569    810.0
Name: new_cases, dtype: float64
25563 25570    290.0
Name: new_cases, dtype: float64
25564 25571    551.0
Name: new_cases, dtype: float64
25565 25572    592.0
Name: new_cases, dtype: float64
25566 25573    555.0
Name: new_cases, dtype: float64
25567 25574    317.0
Name: new_cases, dtype: float64
25568 25575    262.0
Name: new_cases, dtype: float64
25569 25576    526.0
Name: new_cases, dtype: float64
25570 25577    342.0
Name: new_cases, dtype: float64
25571 25578    340.0
Name: new_cases, dtype: float64
25572 25579    378.0
Name: new_cases, dtype: float64
25573 25580    380.0
Name: new_cases, dtype: float64
25574 25581    310.0
Name: new_cases, dtype: float64
25575 25582    303.0
Name: new_cases, dtype: float64
25576 25583    638.0
Name: new_cases, dtype: float64
25577 25584    313.0
Name: new_cases, dtype: float64
25578 25585    517.0
Name: new_cases, dtype: float64
25579 25586    398.0
Name: new_cases, dtype: float64
25580 25587    594.0
Name: new_cases, dtype: float64
25581 25588    325.0
Name: new_cases, dtype: float64
25582 25589    267.0
Name: new_cases, dtype: float64
25583 25590    1074.0
Name: new_cases, dtype: float64
25584 25591    537.0
Name: new_cases, dtype: float64
25585 25592    796.0
Name: new_cases, dtype: float64
25586 25593    912.0
Name: new_cases, dtype: float64
25587 25594    910.0
Name: new_cases, dtype: float64
25588 25595    436.0
Name: new_cases, dtype: float64
25589 25596    360.0
Name: new_cases, dtype: float64
25590 25597    215.0
Name: new_cases, dtype: float64
25591 25598    2243.0
Name: new_cases, dtype: float64
25592 25599    980.0
Name: new_cases, dtype: float64
25593 25600    1523.0
Name: new_cases, dtype: float64
25594 25601    1552.0
Name: new_cases, dtype: float64
25595 25602    585.0
Name: new_cases, dtype: float64
25596 25603    582.0
Name: new_cases, dtype: float64
25597 25604    3209.0
Name: new_cases, dtype: float64
25598 25605    1334.0
Name: new_cases, dtype: float64
25599 25606    1960.0
Name: new_cases, dtype: float64
25600 25607    2141.0
Name: new_cases, dtype: float64
25601 25608    2316.0
Name: new_cases, dtype: float64
25602 25609    868.0
Name: new_cases, dtype: float64
25603 25610    744.0
Name: new_cases, dtype: float64
25604 25611    4547.0
Name: new_cases, dtype: float64
25605 25612    1862.0
Name: new_cases, dtype: float64
25606 25613    2356.0
Name: new_cases, dtype: float64
25607 25614    2969.0
Name: new_cases, dtype: float64
25608 25615    2998.0
Name: new_cases, dtype: float64
25609 25616    1053.0
Name: new_cases, dtype: float64
25610 25617    1156.0
Name: new_cases, dtype: float64
25611 25618    5445.0
Name: new_cases, dtype: float64
25612 25619    2205.0
Name: new_cases, dtype: float64
25613 25620    3537.0
Name: new_cases, dtype: float64
25614 25621    3420.0
Name: new_cases, dtype: float64
25615 25622    3780.0
Name: new_cases, dtype: float64
25616 25623    1462.0
Name: new_cases, dtype: float64
25617 25624    1424.0
Name: new_cases, dtype: float64
25618 25625    6874.0
Name: new_cases, dtype: float64
25619 25626    2935.0
Name: new_cases, dtype: float64
25620 25627    3954.0
Name: new_cases, dtype: float64
25621 25628    3996.0
Name: new_cases, dtype: float64
25622 25629    4206.0
Name: new_cases, dtype: float64
25623 25630    1651.0
Name: new_cases, dtype: float64
25624 25631    1744.0
Name: new_cases, dtype: float64
25625 25632    1050.0
Name: new_cases, dtype: float64
25626 25633    9896.0
Name: new_cases, dtype: float64
25627 25634    3705.0
Name: new_cases, dtype: float64
25628 25635    4261.0
Name: new_cases, dtype: float64
25629 25636    4599.0
Name: new_cases, dtype: float64
25630 25637    945.0
Name: new_cases, dtype: float64
25631 25638    2803.0
Name: new_cases, dtype: float64
25632 25639    9227.0
Name: new_cases, dtype: float64
25633 25640    4014.0
Name: new_cases, dtype: float64
25634 25641    4414.0
Name: new_cases, dtype: float64
25635 25642    4671.0
Name: new_cases, dtype: float64
25636 25643    5107.0
Name: new_cases, dtype: float64
25637 25644    1846.0
Name: new_cases, dtype: float64
25638 25645    1822.0
Name: new_cases, dtype: float64
25639 25646    8986.0
Name: new_cases, dtype: float64
25640 25647    3685.0
Name: new_cases, dtype: float64
25641 25648    4115.0
Name: new_cases, dtype: float64
25642 25649    4624.0
Name: new_cases, dtype: float64
25643 25650    4561.0
Name: new_cases, dtype: float64
25644 25651    1045.0
Name: new_cases, dtype: float64
25645 25652    1137.0
Name: new_cases, dtype: float64
25646 25653    11381.0
Name: new_cases, dtype: float64
25647 25654    3464.0
Name: new_cases, dtype: float64
25648 25655    4328.0
Name: new_cases, dtype: float64
25649 25656    3318.0
Name: new_cases, dtype: float64
25650 25657    5794.0
Name: new_cases, dtype: float64
25651 25658    1728.0
Name: new_cases, dtype: float64
25652 25659    1396.0
Name: new_cases, dtype: float64
25653 25660    8377.0
Name: new_cases, dtype: float64
25654 25661    2661.0
Name: new_cases, dtype: float64
25655 25662    3803.0
Name: new_cases, dtype: float64
25656 25663    4111.0
Name: new_cases, dtype: float64
25657 25664    4199.0
Name: new_cases, dtype: float64
25658 25665    1623.0
Name: new_cases, dtype: float64
25659 25666    1612.0
Name: new_cases, dtype: float64
25660 25667    1117.0
Name: new_cases, dtype: float64
25661 25668    7737.0
Name: new_cases, dtype: float64
25662 25669    2706.0
Name: new_cases, dtype: float64
25663 25670    3158.0
Name: new_cases, dtype: float64
25664 25671    3443.0
Name: new_cases, dtype: float64
25665 25672    1550.0
Name: new_cases, dtype: float64
25666 25673    1277.0
Name: new_cases, dtype: float64
25667 25674    5503.0
Name: new_cases, dtype: float64
25668 25675    2346.0
Name: new_cases, dtype: float64
25669 25676    2727.0
Name: new_cases, dtype: float64
25670 25677    2839.0
Name: new_cases, dtype: float64
25671 25678    2665.0
Name: new_cases, dtype: float64
25672 25679    1731.0
Name: new_cases, dtype: float64
25673 25680    1528.0
Name: new_cases, dtype: float64
25674 25681    3507.0
Name: new_cases, dtype: float64
25675 25682    1796.0
Name: new_cases, dtype: float64
25676 25683    2541.0
Name: new_cases, dtype: float64
25677 25684    2640.0
Name: new_cases, dtype: float64
25678 25685    2578.0
Name: new_cases, dtype: float64
25679 25686    1647.0
Name: new_cases, dtype: float64
25680 25687    1519.0
Name: new_cases, dtype: float64
25681 25688    3226.0
Name: new_cases, dtype: float64
25682 25689    1811.0
Name: new_cases, dtype: float64
25683 25690    2275.0
Name: new_cases, dtype: float64
25684 25691    2622.0
Name: new_cases, dtype: float64
25685 25692    2524.0
Name: new_cases, dtype: float64
25686 25693    1288.0
Name: new_cases, dtype: float64
25687 25694    1291.0
Name: new_cases, dtype: float64
25688 25695    4795.0
Name: new_cases, dtype: float64
25689 25696    2364.0
Name: new_cases, dtype: float64
25690 25697    2657.0
Name: new_cases, dtype: float64
25691 25698    1441.0
Name: new_cases, dtype: float64
25692 25699    3922.0
Name: new_cases, dtype: float64
25693 25700    1352.0
Name: new_cases, dtype: float64
25694 25701    1378.0
Name: new_cases, dtype: float64
25695 25702    4370.0
Name: new_cases, dtype: float64
25696 25703    1816.0
Name: new_cases, dtype: float64
25697 25704    2526.0
Name: new_cases, dtype: float64
25698 25705    2798.0
Name: new_cases, dtype: float64
25699 25706    2813.0
Name: new_cases, dtype: float64

25700 25707    1709.0
Name: new_cases, dtype: float64
25701 25708    1475.0
Name: new_cases, dtype: float64
25702 25709    4461.0
Name: new_cases, dtype: float64
25703 25710    2223.0
Name: new_cases, dtype: float64
25704 25711    2676.0
Name: new_cases, dtype: float64
25705 25712    4223.0
Name: new_cases, dtype: float64
25706 25713    3037.0
Name: new_cases, dtype: float64
25707 25714    1982.0
Name: new_cases, dtype: float64
25708 25715    1725.0
Name: new_cases, dtype: float64
25709 25716    4229.0
Name: new_cases, dtype: float64
25710 25717    2352.0
Name: new_cases, dtype: float64
25711 25718    3227.0
Name: new_cases, dtype: float64
25712 25719    3218.0
Name: new_cases, dtype: float64
25713 25720    3513.0
Name: new_cases, dtype: float64
25714 25721    2479.0
Name: new_cases, dtype: float64
25715 25722    2382.0
Name: new_cases, dtype: float64
25716 25723    5007.0
Name: new_cases, dtype: float64
25717 25724    3002.0
Name: new_cases, dtype: float64
25718 25725    3644.0
Name: new_cases, dtype: float64
25719 25726    4002.0
Name: new_cases, dtype: float64
25720 25727    3292.0
Name: new_cases, dtype: float64
25721 25728    5330.0
Name: new_cases, dtype: float64
25722 25729    2013.0
Name: new_cases, dtype: float64
25723 25730    8005.0
Name: new_cases, dtype: float64
25724 25731    4533.0
Name: new_cases, dtype: float64
25725 25732    6042.0
Name: new_cases, dtype: float64
25726 25733    7530.0
Name: new_cases, dtype: float64
25727 25734    9325.0
Name: new_cases, dtype: float64
25728 25735    6263.0
Name: new_cases, dtype: float64
25729 25736    7449.0
Name: new_cases, dtype: float64
25730 25737    17101.0
Name: new_cases, dtype: float64
25731 25738    12203.0
Name: new_cases, dtype: float64
25732 25739    15396.0
Name: new_cases, dtype: float64
25733 25740    22430.0
Name: new_cases, dtype: float64
25734 25741    24090.0
Name: new_cases, dtype: float64
25735 25742    9888.0
Name: new_cases, dtype: float64
25736 25743    8478.0
Name: new_cases, dtype: float64
25737 25744    19143.0
Name: new_cases, dtype: float64
25738 25745    17766.0
Name: new_cases, dtype: float64
25739 25746    80011.0
Name: new_cases, dtype: float64
25740 25747    35004.0
Name: new_cases, dtype: float64
25741 25748    47411.0
Name: new_cases, dtype: float64
25742 25749    18793.0
Name: new_cases, dtype: float64
25743 25750    19611.0
Name: new_cases, dtype: float64
25744 25751    32899.0
Name: new_cases, dtype: float64
25745 25752    84190.0
Name: new_cases, dtype: float64
25746 25753    38981.0
Name: new_cases, dtype: float64
25747 25754    41950.0
Name: new_cases, dtype: float64
25748 25755    44525.0
Name: new_cases, dtype: float64
25749 25756    26035.0
Name: new_cases, dtype: float64
25750 25071    0.0
Name: new_cases, dtype: float64
25751 25072    1.0
Name: new_cases, dtype: float64
25752 25073    2.0
Name: new_cases, dtype: float64
25753 25074    0.0
Name: new_cases, dtype: float64
25754 25075    2.0
Name: new_cases, dtype: float64
25755 25076    1.0
Name: new_cases, dtype: float64
25756 25077    6.0
Name: new_cases, dtype: float64
28410 28417    7.0
Name: new_cases, dtype: float64
28411 28418    0.0
Name: new_cases, dtype: float64
28412 28419    1.0
Name: new_cases, dtype: float64
28413 28420    0.0
Name: new_cases, dtype: float64
28414 28421    3.0
Name: new_cases, dtype: float64
28415 28422    0.0
Name: new_cases, dtype: float64
28416 28423    0.0
Name: new_cases, dtype: float64
28417 28424    7.0
Name: new_cases, dtype: float64
28418 28425    0.0
Name: new_cases, dtype: float64
28419 28426    5.0
Name: new_cases, dtype: float64
28420 28427    10.0
Name: new_cases, dtype: float64
28421 28428    0.0
Name: new_cases, dtype: float64
28422 28429    20.0
Name: new_cases, dtype: float64
28423 28430    33.0
Name: new_cases, dtype: float64
28424 28431    13.0
Name: new_cases, dtype: float64
28425 28432    81.0
Name: new_cases, dtype: float64
28426 28433    46.0
Name: new_cases, dtype: float64
28427 28434    37.0
Name: new_cases, dtype: float64
28428 28435    0.0
Name: new_cases, dtype: float64
28429 28436    196.0
Name: new_cases, dtype: float64
28430 28437    131.0
Name: new_cases, dtype: float64
28431 28438    95.0
Name: new_cases, dtype: float64
28432 28439    114.0
Name: new_cases, dtype: float64
28433 28440    176.0
Name: new_cases, dtype: float64
28434 28441    220.0
Name: new_cases, dtype: float64
28435 28442    164.0
Name: new_cases, dtype: float64
28436 28443    304.0
Name: new_cases, dtype: float64
28437 28444    350.0
Name: new_cases, dtype: float64
28438 28445    230.0
Name: new_cases, dtype: float64
28439 28446    310.0
Name: new_cases, dtype: float64
28440 28447    289.0
Name: new_cases, dtype: float64
28441 28448    293.0
Name: new_cases, dtype: float64
28442 28449    373.0
Name: new_cases, dtype: float64
28443 28450    333.0
Name: new_cases, dtype: float64
28444 28451    512.0
Name: new_cases, dtype: float64
28445 28452    310.0
Name: new_cases, dtype: float64
28446 28453    344.0
Name: new_cases, dtype: float64
28447 28454    301.0
Name: new_cases, dtype: float64
28448 28455    430.0
Name: new_cases, dtype: float64
28449 28456    426.0
Name: new_cases, dtype: float64
28450 28457    529.0
Name: new_cases, dtype: float64
28451 28458    671.0
Name: new_cases, dtype: float64
28452 28459    286.0
Name: new_cases, dtype: float64
28453 28460    312.0
Name: new_cases, dtype: float64
28454 28461    392.0
Name: new_cases, dtype: float64
28455 28462    356.0
Name: new_cases, dtype: float64
28456 28463    534.0
Name: new_cases, dtype: float64
28457 28464    445.0
Name: new_cases, dtype: float64
28458 28465    907.0
Name: new_cases, dtype: float64
28459 28466    358.0
Name: new_cases, dtype: float64
28460 28467    419.0
Name: new_cases, dtype: float64
28461 28468    325.0
Name: new_cases, dtype: float64
28462 28469    464.0
Name: new_cases, dtype: float64
28463 28470    516.0
Name: new_cases, dtype: float64
28464 28471    494.0
Name: new_cases, dtype: float64
28465 28472    1363.0
Name: new_cases, dtype: float64
28466 28473    473.0
Name: new_cases, dtype: float64
28467 28474    482.0
Name: new_cases, dtype: float64
28468 28475    552.0
Name: new_cases, dtype: float64
28469 28476    520.0
Name: new_cases, dtype: float64
28470 28477    1138.0
Name: new_cases, dtype: float64
28471 28478    985.0
Name: new_cases, dtype: float64
28472 28479    2526.0
Name: new_cases, dtype: float64
28473 28480    1228.0
Name: new_cases, dtype: float64
28474 28481    980.0
Name: new_cases, dtype: float64
28475 28482    1373.0
Name: new_cases, dtype: float64
28476 28483    1032.0
Name: new_cases, dtype: float64
28477 28484    1533.0
Name: new_cases, dtype: float64
28478 28485    1391.0
Name: new_cases, dtype: float64
28479 28486    3458.0
Name: new_cases, dtype: float64
28480 28487    1647.0
Name: new_cases, dtype: float64
28481 28488    1197.0
Name: new_cases, dtype: float64
28482 28489    1658.0
Name: new_cases, dtype: float64
28483 28490    2660.0
Name: new_cases, dtype: float64
28484 28491    2659.0
Name: new_cases, dtype: float64
28485 28492    2502.0
Name: new_cases, dtype: float64
28486 28493    5485.0
Name: new_cases, dtype: float64
28487 28494    2353.0
Name: new_cases, dtype: float64
28488 28495    2278.0
Name: new_cases, dtype: float64
28489 28496    3520.0
Name: new_cases, dtype: float64
28490 28497    4038.0
Name: new_cases, dtype: float64
28491 28498    3964.0
Name: new_cases, dtype: float64
28492 28499    4276.0
Name: new_cases, dtype: float64
28493 28500    9842.0
Name: new_cases, dtype: float64
28494 28501    3709.0
Name: new_cases, dtype: float64
28495 28502    4895.0
Name: new_cases, dtype: float64
28496 28503    3964.0
Name: new_cases, dtype: float64
28497 28504    4328.0
Name: new_cases, dtype: float64
28498 28505    4654.0
Name: new_cases, dtype: float64
28499 28506    3695.0
Name: new_cases, dtype: float64
28500 28507    13188.0
Name: new_cases, dtype: float64
28501 28508    4830.0
Name: new_cases, dtype: float64
28502 28509    5470.0
Name: new_cases, dtype: float64
28503 28510    3528.0
Name: new_cases, dtype: float64
28504 28511    4942.0
Name: new_cases, dtype: float64
28505 28512    4664.0
Name: new_cases, dtype: float64
28506 28513    4207.0
Name: new_cases, dtype: float64
28507 28514    13990.0
Name: new_cases, dtype: float64
28508 28515    6405.0
Name: new_cases, dtype: float64
28509 28516    4696.0
Name: new_cases, dtype: float64
28510 28517    3913.0
Name: new_cases, dtype: float64

28511 28518    5697.0
Name: new_cases, dtype: float64
28512 28519    5636.0
Name: new_cases, dtype: float64
28513 28520    6754.0
Name: new_cases, dtype: float64
28514 28521    8182.0
Name: new_cases, dtype: float64
28515 28522    6938.0
Name: new_cases, dtype: float64
28516 28523    5143.0
Name: new_cases, dtype: float64
28517 28524    5013.0
Name: new_cases, dtype: float64
28518 28525    1900.0
Name: new_cases, dtype: float64
28519 28526    4475.0
Name: new_cases, dtype: float64
28520 28527    6290.0
Name: new_cases, dtype: float64
28521 28528    5355.0
Name: new_cases, dtype: float64
28522 28529    5607.0
Name: new_cases, dtype: float64
28523 28530    4608.0
Name: new_cases, dtype: float64
28524 28531    3804.0
Name: new_cases, dtype: float64
28525 28532    3649.0
Name: new_cases, dtype: float64
28526 28533    4648.0
Name: new_cases, dtype: float64
28527 28534    4296.0
Name: new_cases, dtype: float64
28528 28535    4406.0
Name: new_cases, dtype: float64
28529 28536    4216.0
Name: new_cases, dtype: float64
28530 28537    4017.0
Name: new_cases, dtype: float64
28531 28538    3394.0
Name: new_cases, dtype: float64
28532 28539    2650.0
Name: new_cases, dtype: float64
28533 28540    2498.0
Name: new_cases, dtype: float64
28534 28541    3548.0
Name: new_cases, dtype: float64
28535 28542    3758.0
Name: new_cases, dtype: float64
28536 28543    3685.0
Name: new_cases, dtype: float64
28537 28544    3025.0
Name: new_cases, dtype: float64
28538 28545    2462.0
Name: new_cases, dtype: float64
28539 28546    2064.0
Name: new_cases, dtype: float64
28540 28547    3133.0
Name: new_cases, dtype: float64
28541 28548    3058.0
Name: new_cases, dtype: float64
28542 28549    2755.0
Name: new_cases, dtype: float64
28543 28550    3012.0
Name: new_cases, dtype: float64
28544 28551    2616.0
Name: new_cases, dtype: float64
28545 28552    1836.0
Name: new_cases, dtype: float64
28546 28553    1712.0
Name: new_cases, dtype: float64
28547 28554    2493.0
Name: new_cases, dtype: float64
28548 28555    2741.0
Name: new_cases, dtype: float64
28549 28556    2407.0
Name: new_cases, dtype: float64
28550 28557    2084.0
Name: new_cases, dtype: float64
28551 28558    2099.0
Name: new_cases, dtype: float64
28552 28559    1654.0
Name: new_cases, dtype: float64
28553 28560    1719.0
Name: new_cases, dtype: float64
28554 28561    2357.0
Name: new_cases, dtype: float64
28555 28562    2545.0
Name: new_cases, dtype: float64
28556 28563    2288.0
Name: new_cases, dtype: float64
28557 28564    2198.0
Name: new_cases, dtype: float64
28558 28565    2133.0
Name: new_cases, dtype: float64
28559 28566    1877.0
Name: new_cases, dtype: float64
28560 28567    1775.0
Name: new_cases, dtype: float64
28561 28568    1961.0
Name: new_cases, dtype: float64
28562 28569    2131.0
Name: new_cases, dtype: float64
28563 28570    1991.0
Name: new_cases, dtype: float64
28564 28571    2073.0
Name: new_cases, dtype: float64
28565 28572    1762.0
Name: new_cases, dtype: float64
28566 28573    1469.0
Name: new_cases, dtype: float64
28567 28574    1761.0
Name: new_cases, dtype: float64
28568 28575    1948.0
Name: new_cases, dtype: float64
28569 28576    2154.0
Name: new_cases, dtype: float64
28570 28577    2198.0
Name: new_cases, dtype: float64
28571 28578    2033.0
Name: new_cases, dtype: float64
28572 28579    1988.0
Name: new_cases, dtype: float64
28573 28580    1572.0
Name: new_cases, dtype: float64
28574 28581    1552.0
Name: new_cases, dtype: float64
28575 28582    1866.0
Name: new_cases, dtype: float64
28576 28583    2077.0
Name: new_cases, dtype: float64
28577 28584    1791.0
Name: new_cases, dtype: float64
28578 28585    2044.0
Name: new_cases, dtype: float64
28579 28586    1556.0
Name: new_cases, dtype: float64
28580 28587    1353.0
Name: new_cases, dtype: float64
28581 28588    1182.0
Name: new_cases, dtype: float64
28582 28589    1812.0
Name: new_cases, dtype: float64
28583 28590    1920.0
Name: new_cases, dtype: float64
28584 28591    1939.0
Name: new_cases, dtype: float64
28585 28592    1957.0
Name: new_cases, dtype: float64
28586 28593    1903.0
Name: new_cases, dtype: float64
28587 28594    1417.0
Name: new_cases, dtype: float64
28588 28595    1380.0
Name: new_cases, dtype: float64
28589 28596    1737.0
Name: new_cases, dtype: float64
28590 28597    1870.0
Name: new_cases, dtype: float64
28591 28598    2037.0
Name: new_cases, dtype: float64
28592 28599    1965.0
Name: new_cases, dtype: float64
28593 28600    1752.0
Name: new_cases, dtype: float64
28594 28601    1419.0
Name: new_cases, dtype: float64
28595 28602    1594.0
Name: new_cases, dtype: float64
28596 28603    1762.0
Name: new_cases, dtype: float64
28597 28604    1968.0
Name: new_cases, dtype: float64
28598 28605    1965.0
Name: new_cases, dtype: float64
28599 28606    2076.0
Name: new_cases, dtype: float64
28600 28607    1764.0
Name: new_cases, dtype: float64
28601 28608    1267.0
Name: new_cases, dtype: float64
28602 28609    1486.0
Name: new_cases, dtype: float64
28603 28610    1642.0
Name: new_cases, dtype: float64
28604 28611    1866.0
Name: new_cases, dtype: float64
28605 28612    2131.0
Name: new_cases, dtype: float64
28606 28613    2082.0
Name: new_cases, dtype: float64
28607 28614    1685.0
Name: new_cases, dtype: float64
28608 28615    1550.0
Name: new_cases, dtype: float64
28609 28616    1304.0
Name: new_cases, dtype: float64
28610 28617    1863.0
Name: new_cases, dtype: float64
28611 28618    1677.0
Name: new_cases, dtype: float64
28612 28619    1847.0
Name: new_cases, dtype: float64
28613 28620    1600.0
Name: new_cases, dtype: float64
28614 28621    1194.0
Name: new_cases, dtype: float64
28615 28622    1055.0
Name: new_cases, dtype: float64
28616 28623    1380.0
Name: new_cases, dtype: float64
28617 28624    1731.0
Name: new_cases, dtype: float64
28618 28625    2234.0
Name: new_cases, dtype: float64
28619 28626    2111.0
Name: new_cases, dtype: float64
28620 28627    1922.0
Name: new_cases, dtype: float64
28621 28628    1770.0
Name: new_cases, dtype: float64
28622 28629    1629.0
Name: new_cases, dtype: float64
28623 28630    1691.0
Name: new_cases, dtype: float64
28624 28631    1759.0
Name: new_cases, dtype: float64
28625 28632    1840.0
Name: new_cases, dtype: float64
28626 28633    1881.0
Name: new_cases, dtype: float64
28627 28634    1708.0
Name: new_cases, dtype: float64
28628 28635    1567.0
Name: new_cases, dtype: float64
28629 28636    1560.0
Name: new_cases, dtype: float64
28630 28637    1134.0
Name: new_cases, dtype: float64
28631 28638    1576.0
Name: new_cases, dtype: float64
28632 28639    1753.0
Name: new_cases, dtype: float64
28633 28640    1826.0
Name: new_cases, dtype: float64
28634 28641    1776.0
Name: new_cases, dtype: float64
28635 28642    1461.0
Name: new_cases, dtype: float64
28636 28643    1448.0
Name: new_cases, dtype: float64
28637 28644    1092.0
Name: new_cases, dtype: float64
28638 28645    1124.0
Name: new_cases, dtype: float64
28639 28646    1694.0
Name: new_cases, dtype: float64
28640 28647    1813.0
Name: new_cases, dtype: float64
28641 28648    1757.0
Name: new_cases, dtype: float64
28642 28649    1545.0
Name: new_cases, dtype: float64
28643 28650    1173.0
Name: new_cases, dtype: float64
28644 28651    1159.0
Name: new_cases, dtype: float64
28645 28652    1494.0
Name: new_cases, dtype: float64
28646 28653    1775.0
Name: new_cases, dtype: float64
28647 28654    1636.0
Name: new_cases, dtype: float64
28648 28655    1521.0
Name: new_cases, dtype: float64
28649 28656    1535.0
Name: new_cases, dtype: float64
28650 28657    927.0
Name: new_cases, dtype: float64
28651 28658    1005.0
Name: new_cases, dtype: float64
28652 28659    1520.0
Name: new_cases, dtype: float64
28653 28660    1521.0
Name: new_cases, dtype: float64
28654 28661    1685.0
Name: new_cases, dtype: float64
28655 28662    1608.0
Name: new_cases, dtype: float64
28656 28663    1276.0
Name: new_cases, dtype: float64
28657 28664    1062.0
Name: new_cases, dtype: float64
28658 28665    840.0
Name: new_cases, dtype: float64
28659 28666    1540.0
Name: new_cases, dtype: float64
28660 28667    1808.0
Name: new_cases, dtype: float64
28661 28668    1587.0
Name: new_cases, dtype: float64
28662 28669    1581.0
Name: new_cases, dtype: float64
28663 28670    1321.0
Name: new_cases, dtype: float64
28664 28671    1028.0
Name: new_cases, dtype: float64
28665 28672    897.0
Name: new_cases, dtype: float64
28666 28673    1634.0
Name: new_cases, dtype: float64
28667 28674    1592.0
Name: new_cases, dtype: float64
28668 28675    1646.0
Name: new_cases, dtype: float64
28669 28676    1597.0
Name: new_cases, dtype: float64

28670 28677    1331.0
Name: new_cases, dtype: float64
28671 28678    1006.0
Name: new_cases, dtype: float64
28672 28679    948.0
Name: new_cases, dtype: float64
28673 28680    1454.0
Name: new_cases, dtype: float64
28674 28681    1573.0
Name: new_cases, dtype: float64
28675 28682    1558.0
Name: new_cases, dtype: float64
28676 28683    1497.0
Name: new_cases, dtype: float64
28677 28684    1440.0
Name: new_cases, dtype: float64
28678 28685    1007.0
Name: new_cases, dtype: float64
28679 28686    1005.0
Name: new_cases, dtype: float64
28680 28687    1570.0
Name: new_cases, dtype: float64
28681 28688    1581.0
Name: new_cases, dtype: float64
28682 28689    1698.0
Name: new_cases, dtype: float64
28683 28690    1489.0
Name: new_cases, dtype: float64
28684 28691    1313.0
Name: new_cases, dtype: float64
28685 28692    1121.0
Name: new_cases, dtype: float64
28686 28693    1034.0
Name: new_cases, dtype: float64
28687 28694    1508.0
Name: new_cases, dtype: float64
28688 28695    1729.0
Name: new_cases, dtype: float64
28689 28696    1533.0
Name: new_cases, dtype: float64
28690 28697    1714.0
Name: new_cases, dtype: float64
28691 28698    1760.0
Name: new_cases, dtype: float64
28692 28699    1392.0
Name: new_cases, dtype: float64
28693 28700    1244.0
Name: new_cases, dtype: float64
28694 28701    1662.0
Name: new_cases, dtype: float64
28695 28702    1534.0
Name: new_cases, dtype: float64
28696 28703    1807.0
Name: new_cases, dtype: float64
28697 28704    2138.0
Name: new_cases, dtype: float64
28698 28705    1911.0
Name: new_cases, dtype: float64
28699 28706    1499.0
Name: new_cases, dtype: float64
28700 28707    1402.0
Name: new_cases, dtype: float64
28701 28708    2001.0
Name: new_cases, dtype: float64
28702 28709    2403.0
Name: new_cases, dtype: float64
28703 28710    2220.0
Name: new_cases, dtype: float64
28704 28711    2191.0
Name: new_cases, dtype: float64
28705 28712    2447.0
Name: new_cases, dtype: float64
28706 28713    1196.0
Name: new_cases, dtype: float64
28707 28714    1725.0
Name: new_cases, dtype: float64
28708 28715    3238.0
Name: new_cases, dtype: float64
28709 28716    1679.0
Name: new_cases, dtype: float64
28710 28717    2563.0
Name: new_cases, dtype: float64
28711 28718    1711.0
Name: new_cases, dtype: float64
28712 28719    1923.0
Name: new_cases, dtype: float64
28713 28720    1958.0
Name: new_cases, dtype: float64
28714 28721    2964.0
Name: new_cases, dtype: float64
28715 28722    2023.0
Name: new_cases, dtype: float64
28716 28723    3591.0
Name: new_cases, dtype: float64
28717 28724    3338.0
Name: new_cases, dtype: float64
28718 28725    2289.0
Name: new_cases, dtype: float64
28719 28726    2450.0
Name: new_cases, dtype: float64
28720 28727    2460.0
Name: new_cases, dtype: float64
28721 28728    2382.0
Name: new_cases, dtype: float64
28722 28729    3693.0
Name: new_cases, dtype: float64
28723 28730    4205.0
Name: new_cases, dtype: float64
28724 28731    4361.0
Name: new_cases, dtype: float64
28725 28732    4181.0
Name: new_cases, dtype: float64
28726 28733    3969.0
Name: new_cases, dtype: float64
28727 28734    3243.0
Name: new_cases, dtype: float64
28728 28735    3390.0
Name: new_cases, dtype: float64
28729 28736    4187.0
Name: new_cases, dtype: float64
28730 28737    4468.0
Name: new_cases, dtype: float64
28731 28738    4313.0
Name: new_cases, dtype: float64
28732 28739    4339.0
Name: new_cases, dtype: float64
28733 28740    3918.0
Name: new_cases, dtype: float64
28734 28741    3401.0
Name: new_cases, dtype: float64
28735 28742    3589.0
Name: new_cases, dtype: float64
28736 28743    4367.0
Name: new_cases, dtype: float64
28737 28744    4959.0
Name: new_cases, dtype: float64
28738 28745    4581.0
Name: new_cases, dtype: float64
28739 28746    4463.0
Name: new_cases, dtype: float64
28740 28747    4068.0
Name: new_cases, dtype: float64
28741 28748    3322.0
Name: new_cases, dtype: float64
28742 28749    3388.0
Name: new_cases, dtype: float64
28743 28750    4255.0
Name: new_cases, dtype: float64
28744 28751    4606.0
Name: new_cases, dtype: float64
28745 28752    4151.0
Name: new_cases, dtype: float64
28746 28753    4209.0
Name: new_cases, dtype: float64
28747 28754    3779.0
Name: new_cases, dtype: float64
28748 28755    3147.0
Name: new_cases, dtype: float64
28749 28756    2610.0
Name: new_cases, dtype: float64
28750 28757    3592.0
Name: new_cases, dtype: float64
28751 28758    3782.0
Name: new_cases, dtype: float64
28752 28759    4063.0
Name: new_cases, dtype: float64
28753 28760    3804.0
Name: new_cases, dtype: float64
28754 28761    3464.0
Name: new_cases, dtype: float64
28755 28762    2839.0
Name: new_cases, dtype: float64
28756 28763    2387.0
Name: new_cases, dtype: float64
28757 28764    3731.0
Name: new_cases, dtype: float64
28758 28765    4164.0
Name: new_cases, dtype: float64
28759 28766    3925.0
Name: new_cases, dtype: float64
28760 28767    3813.0
Name: new_cases, dtype: float64
28761 28768    3332.0
Name: new_cases, dtype: float64
28762 28769    2498.0
Name: new_cases, dtype: float64
28763 28770    2275.0
Name: new_cases, dtype: float64
28764 28771    3828.0
Name: new_cases, dtype: float64
28765 28772    3797.0
Name: new_cases, dtype: float64
28766 28773    3906.0
Name: new_cases, dtype: float64
28767 28774    3615.0
Name: new_cases, dtype: float64
28768 28775    3549.0
Name: new_cases, dtype: float64
28769 28776    2308.0
Name: new_cases, dtype: float64
28770 28777    2555.0
Name: new_cases, dtype: float64
28771 28778    4472.0
Name: new_cases, dtype: float64
28772 28779    4585.0
Name: new_cases, dtype: float64
28773 28780    4489.0
Name: new_cases, dtype: float64
28774 28781    3207.0
Name: new_cases, dtype: float64
28775 28782    5145.0
Name: new_cases, dtype: float64
28776 28783    2742.0
Name: new_cases, dtype: float64
28777 28784    3040.0
Name: new_cases, dtype: float64
28778 28785    4567.0
Name: new_cases, dtype: float64
28779 28786    5331.0
Name: new_cases, dtype: float64
28780 28787    5033.0
Name: new_cases, dtype: float64
28781 28788    5302.0
Name: new_cases, dtype: float64
28782 28789    4748.0
Name: new_cases, dtype: float64
28783 28790    3531.0
Name: new_cases, dtype: float64
28784 28791    3885.0
Name: new_cases, dtype: float64
28785 28792    5563.0
Name: new_cases, dtype: float64
28786 28793    5973.0
Name: new_cases, dtype: float64
28787 28794    5894.0
Name: new_cases, dtype: float64
28788 28795    5731.0
Name: new_cases, dtype: float64
28789 28796    5121.0
Name: new_cases, dtype: float64
28790 28797    4551.0
Name: new_cases, dtype: float64
28791 28798    3430.0
Name: new_cases, dtype: float64
28792 28799    7257.0
Name: new_cases, dtype: float64
28793 28800    6584.0
Name: new_cases, dtype: float64
28794 28801    7036.0
Name: new_cases, dtype: float64
28795 28802    6850.0
Name: new_cases, dtype: float64
28796 28803    6155.0
Name: new_cases, dtype: float64
28797 28804    4864.0
Name: new_cases, dtype: float64
28798 28805    4825.0
Name: new_cases, dtype: float64
28799 28806    7060.0
Name: new_cases, dtype: float64
28800 28807    7478.0
Name: new_cases, dtype: float64
28801 28808    7592.0
Name: new_cases, dtype: float64
28802 28809    7330.0
Name: new_cases, dtype: float64
28803 28810    7241.0
Name: new_cases, dtype: float64
28804 28811    5008.0
Name: new_cases, dtype: float64
28805 28812    6046.0
Name: new_cases, dtype: float64
28806 28813    7868.0
Name: new_cases, dtype: float64
28807 28814    8079.0
Name: new_cases, dtype: float64
28808 28815    7993.0
Name: new_cases, dtype: float64
28809 28816    7307.0
Name: new_cases, dtype: float64
28810 28817    5827.0
Name: new_cases, dtype: float64
28811 28818    5168.0
Name: new_cases, dtype: float64
28812 28819    5242.0
Name: new_cases, dtype: float64
28813 28820    8248.0
Name: new_cases, dtype: float64
28814 28821    9151.0
Name: new_cases, dtype: float64
28815 28822    8101.0
Name: new_cases, dtype: float64
28816 28823    7977.0
Name: new_cases, dtype: float64
28817 28824    6421.0
Name: new_cases, dtype: float64
28818 28825    5790.0
Name: new_cases, dtype: float64
28819 28826    5557.0
Name: new_cases, dtype: float64
28820 28827    7431.0
Name: new_cases, dtype: float64
28821 28828    7613.0
Name: new_cases, dtype: float64
28822 28829    8037.0
Name: new_cases, dtype: float64
28823 28830    7370.0
Name: new_cases, dtype: float64
28824 28831    6622.0
Name: new_cases, dtype: float64
28825 28832    4849.0
Name: new_cases, dtype: float64
28826 28833    5214.0
Name: new_cases, dtype: float64
28827 28834    6917.0
Name: new_cases, dtype: float64
28828 28835    7582.0
Name: new_cases, dtype: float64
28829 28836    6909.0
Name: new_cases, dtype: float64
28830 28837    6725.0
Name: new_cases, dtype: float64
28831 28838    6078.0
Name: new_cases, dtype: float64
28832 28839    4158.0
Name: new_cases, dtype: float64
28833 28840    4499.0
Name: new_cases, dtype: float64
28834 28841    6720.0
Name: new_cases, dtype: float64
28835 28842    7254.0
Name: new_cases, dtype: float64
28836 28843    5510.0
Name: new_cases, dtype: float64
28837 28844    7165.0
Name: new_cases, dtype: float64
28838 28845    4895.0
Name: new_cases, dtype: float64
28839 28846    3249.0
Name: new_cases, dtype: float64
28840 28847    3885.0
Name: new_cases, dtype: float64
28841 28848    6299.0
Name: new_cases, dtype: float64
28842 28849    6530.0
Name: new_cases, dtype: float64
28843 28850    6198.0
Name: new_cases, dtype: float64

28844 28851    5493.0
Name: new_cases, dtype: float64
28845 28852    5339.0
Name: new_cases, dtype: float64
28846 28853    3738.0
Name: new_cases, dtype: float64
28847 28854    3902.0
Name: new_cases, dtype: float64
28848 28855    6153.0
Name: new_cases, dtype: float64
28849 28856    6915.0
Name: new_cases, dtype: float64
28850 28857    6736.0
Name: new_cases, dtype: float64
28851 28858    6296.0
Name: new_cases, dtype: float64
28852 28859    5548.0
Name: new_cases, dtype: float64
28853 28860    3766.0
Name: new_cases, dtype: float64
28854 28861    4767.0
Name: new_cases, dtype: float64
28855 28862    7682.0
Name: new_cases, dtype: float64
28856 28863    7602.0
Name: new_cases, dtype: float64
28857 28864    7500.0
Name: new_cases, dtype: float64
28858 28865    6505.0
Name: new_cases, dtype: float64
28859 28866    5343.0
Name: new_cases, dtype: float64
28860 28867    4160.0
Name: new_cases, dtype: float64
28861 28868    5197.0
Name: new_cases, dtype: float64
28862 28869    8105.0
Name: new_cases, dtype: float64
28863 28870    8658.0
Name: new_cases, dtype: float64
28864 28871    8216.0
Name: new_cases, dtype: float64
28865 28872    7910.0
Name: new_cases, dtype: float64
28866 28873    6839.0
Name: new_cases, dtype: float64
28867 28874    5011.0
Name: new_cases, dtype: float64
28868 28875    5616.0
Name: new_cases, dtype: float64
28869 28876    8128.0
Name: new_cases, dtype: float64
28870 28877    8245.0
Name: new_cases, dtype: float64
28871 28878    8920.0
Name: new_cases, dtype: float64
28872 28879    7690.0
Name: new_cases, dtype: float64
28873 28880    6928.0
Name: new_cases, dtype: float64
28874 28881    5533.0
Name: new_cases, dtype: float64
28875 28882    5351.0
Name: new_cases, dtype: float64
28876 28883    7709.0
Name: new_cases, dtype: float64
28877 28884    7942.0
Name: new_cases, dtype: float64
28878 28885    7573.0
Name: new_cases, dtype: float64
28879 28886    7481.0
Name: new_cases, dtype: float64
28880 28887    6190.0
Name: new_cases, dtype: float64
28881 28888    4576.0
Name: new_cases, dtype: float64
28882 28889    4322.0
Name: new_cases, dtype: float64
28883 28890    6670.0
Name: new_cases, dtype: float64
28884 28891    6770.0
Name: new_cases, dtype: float64
28885 28892    6274.0
Name: new_cases, dtype: float64
28886 28893    5743.0
Name: new_cases, dtype: float64
28887 28894    5205.0
Name: new_cases, dtype: float64
28888 28895    3710.0
Name: new_cases, dtype: float64
28889 28896    2476.0
Name: new_cases, dtype: float64
28890 28897    3463.0
Name: new_cases, dtype: float64
28891 28898    5599.0
Name: new_cases, dtype: float64
28892 28899    5171.0
Name: new_cases, dtype: float64
28893 28900    4461.0
Name: new_cases, dtype: float64
28894 28901    4034.0
Name: new_cases, dtype: float64
28895 28902    2637.0
Name: new_cases, dtype: float64
28896 28903    2128.0
Name: new_cases, dtype: float64
28897 28904    2655.0
Name: new_cases, dtype: float64
28898 28905    4056.0
Name: new_cases, dtype: float64
28899 28906    3848.0
Name: new_cases, dtype: float64
28900 28907    3323.0
Name: new_cases, dtype: float64
28901 28908    2824.0
Name: new_cases, dtype: float64
28902 28909    1857.0
Name: new_cases, dtype: float64
28903 28910    1871.0
Name: new_cases, dtype: float64
28904 28911    3255.0
Name: new_cases, dtype: float64
28905 28912    2800.0
Name: new_cases, dtype: float64
28906 28913    2769.0
Name: new_cases, dtype: float64
28907 28914    2318.0
Name: new_cases, dtype: float64
28908 28915    2145.0
Name: new_cases, dtype: float64
28909 28916    1264.0
Name: new_cases, dtype: float64
28910 28917    1243.0
Name: new_cases, dtype: float64
28911 28918    2366.0
Name: new_cases, dtype: float64
28912 28919    2053.0
Name: new_cases, dtype: float64
28913 28920    1932.0
Name: new_cases, dtype: float64
28914 28921    1398.0
Name: new_cases, dtype: float64
28915 28922    1004.0
Name: new_cases, dtype: float64
28916 28923    975.0
Name: new_cases, dtype: float64
28917 28924    996.0
Name: new_cases, dtype: float64
28918 28925    1859.0
Name: new_cases, dtype: float64
28919 28926    1645.0
Name: new_cases, dtype: float64
28920 28927    1391.0
Name: new_cases, dtype: float64
28921 28928    1428.0
Name: new_cases, dtype: float64
28922 28929    1168.0
Name: new_cases, dtype: float64
28923 28930    745.0
Name: new_cases, dtype: float64
28924 28931    827.0
Name: new_cases, dtype: float64
28925 28932    1371.0
Name: new_cases, dtype: float64
28926 28933    1341.0
Name: new_cases, dtype: float64
28927 28934    1142.0
Name: new_cases, dtype: float64
28928 28935    1171.0
Name: new_cases, dtype: float64
28929 28936    910.0
Name: new_cases, dtype: float64
28930 28937    605.0
Name: new_cases, dtype: float64
28931 28938    726.0
Name: new_cases, dtype: float64
28932 28939    1206.0
Name: new_cases, dtype: float64
28933 28940    1182.0
Name: new_cases, dtype: float64
28934 28941    938.0
Name: new_cases, dtype: float64
28935 28942    854.0
Name: new_cases, dtype: float64
28936 28943    953.0
Name: new_cases, dtype: float64
28937 28944    507.0
Name: new_cases, dtype: float64
28938 28945    644.0
Name: new_cases, dtype: float64
28939 28946    1128.0
Name: new_cases, dtype: float64
28940 28947    833.0
Name: new_cases, dtype: float64
28941 28948    865.0
Name: new_cases, dtype: float64
28942 28949    899.0
Name: new_cases, dtype: float64
28943 28950    740.0
Name: new_cases, dtype: float64
28944 28951    398.0
Name: new_cases, dtype: float64
28945 28952    501.0
Name: new_cases, dtype: float64
28946 28953    858.0
Name: new_cases, dtype: float64
28947 28954    752.0
Name: new_cases, dtype: float64
28948 28955    712.0
Name: new_cases, dtype: float64
28949 28956    663.0
Name: new_cases, dtype: float64
28950 28957    578.0
Name: new_cases, dtype: float64
28951 28958    380.0
Name: new_cases, dtype: float64
28952 28959    399.0
Name: new_cases, dtype: float64
28953 28960    785.0
Name: new_cases, dtype: float64
28954 28961    669.0
Name: new_cases, dtype: float64
28955 28962    607.0
Name: new_cases, dtype: float64
28956 28963    595.0
Name: new_cases, dtype: float64
28957 28964    501.0
Name: new_cases, dtype: float64
28958 28965    345.0
Name: new_cases, dtype: float64
28959 28966    448.0
Name: new_cases, dtype: float64
28960 28967    575.0
Name: new_cases, dtype: float64
28961 28968    494.0
Name: new_cases, dtype: float64
28962 28969    474.0
Name: new_cases, dtype: float64
28963 28970    425.0
Name: new_cases, dtype: float64
28964 28971    435.0
Name: new_cases, dtype: float64
28965 28972    265.0
Name: new_cases, dtype: float64
28966 28973    355.0
Name: new_cases, dtype: float64
28967 28974    500.0
Name: new_cases, dtype: float64
28968 28975    510.0
Name: new_cases, dtype: float64
28969 28976    474.0
Name: new_cases, dtype: float64
28970 28977    441.0
Name: new_cases, dtype: float64
28971 28978    469.0
Name: new_cases, dtype: float64
28972 28979    292.0
Name: new_cases, dtype: float64
28973 28980    401.0
Name: new_cases, dtype: float64
28974 28981    587.0
Name: new_cases, dtype: float64
28975 28982    583.0
Name: new_cases, dtype: float64
28976 28983    591.0
Name: new_cases, dtype: float64
28977 28984    475.0
Name: new_cases, dtype: float64
28978 28985    277.0
Name: new_cases, dtype: float64
28979 28986    280.0
Name: new_cases, dtype: float64
28980 28987    524.0
Name: new_cases, dtype: float64
28981 28988    859.0
Name: new_cases, dtype: float64
28982 28989    829.0
Name: new_cases, dtype: float64
28983 28990    747.0
Name: new_cases, dtype: float64
28984 28991    765.0
Name: new_cases, dtype: float64
28985 28992    614.0
Name: new_cases, dtype: float64
28986 28993    431.0
Name: new_cases, dtype: float64
28987 28994    611.0
Name: new_cases, dtype: float64
28988 28995    858.0
Name: new_cases, dtype: float64
28989 28996    807.0
Name: new_cases, dtype: float64
28990 28997    813.0
Name: new_cases, dtype: float64
28991 28998    718.0
Name: new_cases, dtype: float64
28992 28999    654.0
Name: new_cases, dtype: float64
28993 29000    493.0
Name: new_cases, dtype: float64
28994 29001    695.0
Name: new_cases, dtype: float64
28995 29002    942.0
Name: new_cases, dtype: float64
28996 29003    986.0
Name: new_cases, dtype: float64
28997 29004    998.0
Name: new_cases, dtype: float64
28998 29005    1063.0
Name: new_cases, dtype: float64
28999 29006    950.0
Name: new_cases, dtype: float64
29000 29007    609.0
Name: new_cases, dtype: float64
29001 29008    733.0
Name: new_cases, dtype: float64
29002 29009    1191.0
Name: new_cases, dtype: float64
29003 29010    1631.0
Name: new_cases, dtype: float64
29004 29011    1689.0
Name: new_cases, dtype: float64
29005 29012    1514.0
Name: new_cases, dtype: float64
29006 29013    1315.0
Name: new_cases, dtype: float64
29007 29014    933.0
Name: new_cases, dtype: float64
29008 29015    1228.0
Name: new_cases, dtype: float64
29009 29016    1793.0
Name: new_cases, dtype: float64
29010 29017    2004.0
Name: new_cases, dtype: float64
29011 29018    1994.0
Name: new_cases, dtype: float64
29012 29019    1811.0
Name: new_cases, dtype: float64
29013 29020    1623.0
Name: new_cases, dtype: float64

29014 29021    1157.0
Name: new_cases, dtype: float64
29015 29022    1710.0
Name: new_cases, dtype: float64
29016 29023    2136.0
Name: new_cases, dtype: float64
29017 29024    2281.0
Name: new_cases, dtype: float64
29018 29025    2142.0
Name: new_cases, dtype: float64
29019 29026    2171.0
Name: new_cases, dtype: float64
29020 29027    1738.0
Name: new_cases, dtype: float64
29021 29028    1341.0
Name: new_cases, dtype: float64
29022 29029    1300.0
Name: new_cases, dtype: float64
29023 29030    1889.0
Name: new_cases, dtype: float64
29024 29031    2510.0
Name: new_cases, dtype: float64
29025 29032    2796.0
Name: new_cases, dtype: float64
29026 29033    2567.0
Name: new_cases, dtype: float64
29027 29034    2253.0
Name: new_cases, dtype: float64
29028 29035    1746.0
Name: new_cases, dtype: float64
29029 29036    2164.0
Name: new_cases, dtype: float64
29030 29037    2733.0
Name: new_cases, dtype: float64
29031 29038    2940.0
Name: new_cases, dtype: float64
29032 29039    2703.0
Name: new_cases, dtype: float64
29033 29040    2744.0
Name: new_cases, dtype: float64
29034 29041    2295.0
Name: new_cases, dtype: float64
29035 29042    1689.0
Name: new_cases, dtype: float64
29036 29043    2120.0
Name: new_cases, dtype: float64
29037 29044    2611.0
Name: new_cases, dtype: float64
29038 29045    2698.0
Name: new_cases, dtype: float64
29039 29046    2611.0
Name: new_cases, dtype: float64
29040 29047    2641.0
Name: new_cases, dtype: float64
29041 29048    2168.0
Name: new_cases, dtype: float64
29042 29049    1760.0
Name: new_cases, dtype: float64
29043 29050    2034.0
Name: new_cases, dtype: float64
29044 29051    2670.0
Name: new_cases, dtype: float64
29045 29052    2674.0
Name: new_cases, dtype: float64
29046 29053    2634.0
Name: new_cases, dtype: float64
29047 29054    2328.0
Name: new_cases, dtype: float64
29048 29055    1960.0
Name: new_cases, dtype: float64
29049 29056    1386.0
Name: new_cases, dtype: float64
29050 29057    1523.0
Name: new_cases, dtype: float64
29051 29058    2219.0
Name: new_cases, dtype: float64
29052 29059    2091.0
Name: new_cases, dtype: float64
29053 29060    2036.0
Name: new_cases, dtype: float64
29054 29061    1927.0
Name: new_cases, dtype: float64
29055 29062    1501.0
Name: new_cases, dtype: float64
29056 29063    1164.0
Name: new_cases, dtype: float64
29057 29064    1387.0
Name: new_cases, dtype: float64
29058 29065    1771.0
Name: new_cases, dtype: float64
29059 29066    0.0
Name: new_cases, dtype: float64
29060 29067    2857.0
Name: new_cases, dtype: float64
29061 29068    1577.0
Name: new_cases, dtype: float64
29062 29069    1361.0
Name: new_cases, dtype: float64
29063 29070    959.0
Name: new_cases, dtype: float64
29064 29071    1060.0
Name: new_cases, dtype: float64
29065 29072    1492.0
Name: new_cases, dtype: float64
29066 29073    1433.0
Name: new_cases, dtype: float64
29067 29074    1415.0
Name: new_cases, dtype: float64
29068 29075    1252.0
Name: new_cases, dtype: float64
29069 29076    1126.0
Name: new_cases, dtype: float64
29070 29077    884.0
Name: new_cases, dtype: float64
29071 29078    964.0
Name: new_cases, dtype: float64
29072 29079    1482.0
Name: new_cases, dtype: float64
29073 29080    1399.0
Name: new_cases, dtype: float64
29074 29081    1494.0
Name: new_cases, dtype: float64
29075 29082    1155.0
Name: new_cases, dtype: float64
29076 29083    753.0
Name: new_cases, dtype: float64
29077 29084    762.0
Name: new_cases, dtype: float64
29078 29085    1096.0
Name: new_cases, dtype: float64
29079 29086    1791.0
Name: new_cases, dtype: float64
29080 29087    1812.0
Name: new_cases, dtype: float64
29081 29088    1904.0
Name: new_cases, dtype: float64
29082 29089    1904.0
Name: new_cases, dtype: float64
29083 29090    995.0
Name: new_cases, dtype: float64
29084 29091    1051.0
Name: new_cases, dtype: float64
29085 29092    1840.0
Name: new_cases, dtype: float64
29086 29093    3112.0
Name: new_cases, dtype: float64
29087 29094    3771.0
Name: new_cases, dtype: float64
29088 29095    4346.0
Name: new_cases, dtype: float64
29089 Series([], Name: new_cases, dtype: float64)
29090 Series([], Name: new_cases, dtype: float64)
29091 Series([], Name: new_cases, dtype: float64)
29092 Series([], Name: new_cases, dtype: float64)
29093 Series([], Name: new_cases, dtype: float64)
29094 Series([], Name: new_cases, dtype: float64)
29095 Series([], Name: new_cases, dtype: float64)
29097 29104    2054.0
Name: new_cases, dtype: float64
29098 29105    1659.0
Name: new_cases, dtype: float64
29099 29106    2088.0
Name: new_cases, dtype: float64
29100 29107    4736.0
Name: new_cases, dtype: float64
29101 29108    3086.0
Name: new_cases, dtype: float64
29102 29109    3987.0
Name: new_cases, dtype: float64
29103 29110    3729.0
Name: new_cases, dtype: float64
29104 29111    3144.0
Name: new_cases, dtype: float64
29105 29112    3522.0
Name: new_cases, dtype: float64
29106 29113    2703.0
Name: new_cases, dtype: float64
29107 29114    3012.0
Name: new_cases, dtype: float64
29108 29115    2516.0
Name: new_cases, dtype: float64
29109 29116    2021.0
Name: new_cases, dtype: float64
29110 29117    372.0
Name: new_cases, dtype: float64
29111 29118    15133.0
Name: new_cases, dtype: float64
29112 29119    6460.0
Name: new_cases, dtype: float64
29113 29120    2055.0
Name: new_cases, dtype: float64
29114 29121    2099.0
Name: new_cases, dtype: float64
29115 29122    1918.0
Name: new_cases, dtype: float64
29116 29123    1775.0
Name: new_cases, dtype: float64
29117 29124    407.0
Name: new_cases, dtype: float64
29118 29125    453.0
Name: new_cases, dtype: float64
29119 29126    473.0
Name: new_cases, dtype: float64
29120 29127    1450.0
Name: new_cases, dtype: float64
29121 29128    16.0
Name: new_cases, dtype: float64
29122 29129    214.0
Name: new_cases, dtype: float64
29123 29130    508.0
Name: new_cases, dtype: float64
29124 29131    405.0
Name: new_cases, dtype: float64
29125 29132    433.0
Name: new_cases, dtype: float64
29126 29133    326.0
Name: new_cases, dtype: float64
29127 29134    427.0
Name: new_cases, dtype: float64
29128 29135    575.0
Name: new_cases, dtype: float64
29129 29136    200.0
Name: new_cases, dtype: float64
29130 29137    125.0
Name: new_cases, dtype: float64
29131 29138    120.0
Name: new_cases, dtype: float64
29132 29139    151.0
Name: new_cases, dtype: float64
29133 29140    151.0
Name: new_cases, dtype: float64
29134 29141    79.0
Name: new_cases, dtype: float64
29135 29142    47.0
Name: new_cases, dtype: float64
29136 29143    36.0
Name: new_cases, dtype: float64
29137 29144    22.0
Name: new_cases, dtype: float64
29138 29145    28.0
Name: new_cases, dtype: float64
29139 29146    8.0
Name: new_cases, dtype: float64
29140 29147    8.0
Name: new_cases, dtype: float64
29141 29148    26.0
Name: new_cases, dtype: float64
29142 29149    21.0
Name: new_cases, dtype: float64
29143 29150    19.0
Name: new_cases, dtype: float64
29144 29151    17.0
Name: new_cases, dtype: float64
29145 29152    22.0
Name: new_cases, dtype: float64
29146 29153    25.0
Name: new_cases, dtype: float64
29147 29154    46.0
Name: new_cases, dtype: float64
29148 29155    37.0
Name: new_cases, dtype: float64
29149 29156    80.0
Name: new_cases, dtype: float64
29150 29157    24.0
Name: new_cases, dtype: float64
29151 29158    62.0
Name: new_cases, dtype: float64
29152 29159    41.0
Name: new_cases, dtype: float64
29153 29160    77.0
Name: new_cases, dtype: float64
29154 29161    47.0
Name: new_cases, dtype: float64
29155 29162    56.0
Name: new_cases, dtype: float64
29156 29163    43.0
Name: new_cases, dtype: float64
29157 29164    34.0
Name: new_cases, dtype: float64
29158 29165    46.0
Name: new_cases, dtype: float64
29159 29166    31.0
Name: new_cases, dtype: float64
29160 29167    34.0
Name: new_cases, dtype: float64
29161 29168    34.0
Name: new_cases, dtype: float64
29162 29169    15.0
Name: new_cases, dtype: float64
29163 29170    30.0
Name: new_cases, dtype: float64
29164 29171    39.0
Name: new_cases, dtype: float64
29165 29172    32.0
Name: new_cases, dtype: float64
29166 29173    65.0
Name: new_cases, dtype: float64
29167 29174    61.0
Name: new_cases, dtype: float64
29168 29175    42.0
Name: new_cases, dtype: float64
29169 29176    62.0
Name: new_cases, dtype: float64
29170 29177    116.0
Name: new_cases, dtype: float64
29171 29178    74.0
Name: new_cases, dtype: float64
29172 29179    90.0
Name: new_cases, dtype: float64
29173 29180    45.0
Name: new_cases, dtype: float64

29174 29181    47.0
Name: new_cases, dtype: float64
29175 29182    353.0
Name: new_cases, dtype: float64
29176 29183    24.0
Name: new_cases, dtype: float64
29177 29184    17.0
Name: new_cases, dtype: float64
29178 29185    12.0
Name: new_cases, dtype: float64
29179 29186    32.0
Name: new_cases, dtype: float64
29180 29187    11.0
Name: new_cases, dtype: float64
29181 29188    14.0
Name: new_cases, dtype: float64
29182 29189    15.0
Name: new_cases, dtype: float64
29183 29190    8.0
Name: new_cases, dtype: float64
29184 29191    3.0
Name: new_cases, dtype: float64
29185 29192    6.0
Name: new_cases, dtype: float64
29186 29193    22.0
Name: new_cases, dtype: float64
29187 29194    4.0
Name: new_cases, dtype: float64
29188 29195    12.0
Name: new_cases, dtype: float64
29189 29196    1.0
Name: new_cases, dtype: float64
29190 29197    0.0
Name: new_cases, dtype: float64
29191 29198    5.0
Name: new_cases, dtype: float64
29192 29199    1.0
Name: new_cases, dtype: float64
29193 29200    2.0
Name: new_cases, dtype: float64
29194 29201    2.0
Name: new_cases, dtype: float64
29195 29202    1.0
Name: new_cases, dtype: float64
29196 29203    1.0
Name: new_cases, dtype: float64
29197 29204    14.0
Name: new_cases, dtype: float64
29198 29205    17.0
Name: new_cases, dtype: float64
29199 29206    1.0
Name: new_cases, dtype: float64
29200 29207    7.0
Name: new_cases, dtype: float64
29201 29208    3.0
Name: new_cases, dtype: float64
29202 29209    4.0
Name: new_cases, dtype: float64
29203 29210    8.0
Name: new_cases, dtype: float64
29204 29211    6.0
Name: new_cases, dtype: float64
29205 29212    7.0
Name: new_cases, dtype: float64
29206 29213    9.0
Name: new_cases, dtype: float64
29207 29214    0.0
Name: new_cases, dtype: float64
29208 29215    0.0
Name: new_cases, dtype: float64
29209 29216    0.0
Name: new_cases, dtype: float64
29210 29217    8.0
Name: new_cases, dtype: float64
29211 29218    3.0
Name: new_cases, dtype: float64
29212 29219    11.0
Name: new_cases, dtype: float64
29213 29220    7.0
Name: new_cases, dtype: float64
29214 29221    1.0
Name: new_cases, dtype: float64
29215 29222    2.0
Name: new_cases, dtype: float64
29216 29223    0.0
Name: new_cases, dtype: float64
29217 29224    4.0
Name: new_cases, dtype: float64
29218 29225    2.0
Name: new_cases, dtype: float64
29219 29226    16.0
Name: new_cases, dtype: float64
29220 29227    5.0
Name: new_cases, dtype: float64
29221 29228    1.0
Name: new_cases, dtype: float64
29222 29229   -1.0
Name: new_cases, dtype: float64
29223 29230    5.0
Name: new_cases, dtype: float64
29224 29231    3.0
Name: new_cases, dtype: float64
29225 29232    6.0
Name: new_cases, dtype: float64
29226 29233    4.0
Name: new_cases, dtype: float64
29227 29234    3.0
Name: new_cases, dtype: float64
29228 29235    3.0
Name: new_cases, dtype: float64
29229 29236    11.0
Name: new_cases, dtype: float64
29230 29237    7.0
Name: new_cases, dtype: float64
29231 29238    11.0
Name: new_cases, dtype: float64
29232 29239    57.0
Name: new_cases, dtype: float64
29233 29240    49.0
Name: new_cases, dtype: float64
29234 29241    40.0
Name: new_cases, dtype: float64
29235 29242    44.0
Name: new_cases, dtype: float64
29236 29243    28.0
Name: new_cases, dtype: float64
29237 29244    32.0
Name: new_cases, dtype: float64
29238 29245    0.0
Name: new_cases, dtype: float64
29239 29246    55.0
Name: new_cases, dtype: float64
29240 29247    16.0
Name: new_cases, dtype: float64
29241 29248    22.0
Name: new_cases, dtype: float64
29242 29249    13.0
Name: new_cases, dtype: float64
29243 29250    18.0
Name: new_cases, dtype: float64
29244 29251    13.0
Name: new_cases, dtype: float64
29245 29252    21.0
Name: new_cases, dtype: float64
29246 29253    17.0
Name: new_cases, dtype: float64
29247 29254    12.0
Name: new_cases, dtype: float64
29248 29255    19.0
Name: new_cases, dtype: float64
29249 29256    3.0
Name: new_cases, dtype: float64
29250 29257    3.0
Name: new_cases, dtype: float64
29251 29258    5.0
Name: new_cases, dtype: float64
29252 29259    3.0
Name: new_cases, dtype: float64
29253 29260    8.0
Name: new_cases, dtype: float64
29254 29261    4.0
Name: new_cases, dtype: float64
29255 29262    1.0
Name: new_cases, dtype: float64
29256 29263    14.0
Name: new_cases, dtype: float64
29257 29264    9.0
Name: new_cases, dtype: float64
29258 29265    0.0
Name: new_cases, dtype: float64
29259 29266    0.0
Name: new_cases, dtype: float64
29260 29267    13.0
Name: new_cases, dtype: float64
29261 29268    8.0
Name: new_cases, dtype: float64
29262 29269    0.0
Name: new_cases, dtype: float64
29263 29270    9.0
Name: new_cases, dtype: float64
29264 29271    1.0
Name: new_cases, dtype: float64
29265 29272    14.0
Name: new_cases, dtype: float64
29266 29273    17.0
Name: new_cases, dtype: float64
29267 29274    16.0
Name: new_cases, dtype: float64
29268 29275    21.0
Name: new_cases, dtype: float64
29269 29276    11.0
Name: new_cases, dtype: float64
29270 29277    13.0
Name: new_cases, dtype: float64
29271 29278    25.0
Name: new_cases, dtype: float64
29272 29279    21.0
Name: new_cases, dtype: float64
29273 29280    34.0
Name: new_cases, dtype: float64
29274 29281    46.0
Name: new_cases, dtype: float64
29275 29282    61.0
Name: new_cases, dtype: float64
29276 29283    68.0
Name: new_cases, dtype: float64
29277 29284    101.0
Name: new_cases, dtype: float64
29278 29285    105.0
Name: new_cases, dtype: float64
29279 29286    127.0
Name: new_cases, dtype: float64
29280 29287    45.0
Name: new_cases, dtype: float64
29281 29288    48.0
Name: new_cases, dtype: float64
29282 29289    43.0
Name: new_cases, dtype: float64
29283 29290    36.0
Name: new_cases, dtype: float64
29284 29291    27.0
Name: new_cases, dtype: float64
29285 29292    37.0
Name: new_cases, dtype: float64
29286 29293    37.0
Name: new_cases, dtype: float64
29287 29294    31.0
Name: new_cases, dtype: float64
29288 29295    23.0
Name: new_cases, dtype: float64
29289 29296    49.0
Name: new_cases, dtype: float64
29290 29297    44.0
Name: new_cases, dtype: float64
29291 29298    19.0
Name: new_cases, dtype: float64
29292 29299    25.0
Name: new_cases, dtype: float64
29293 29300    30.0
Name: new_cases, dtype: float64
29294 29301    22.0
Name: new_cases, dtype: float64
29295 29302    19.0
Name: new_cases, dtype: float64
29296 29303    22.0
Name: new_cases, dtype: float64
29297 29304    22.0
Name: new_cases, dtype: float64
29298 29305    17.0
Name: new_cases, dtype: float64
29299 29306    7.0
Name: new_cases, dtype: float64
29300 29307    22.0
Name: new_cases, dtype: float64
29301 29308    22.0
Name: new_cases, dtype: float64
29302 29309    12.0
Name: new_cases, dtype: float64
29303 29310    16.0
Name: new_cases, dtype: float64
29304 29311    14.0
Name: new_cases, dtype: float64
29305 29312    15.0
Name: new_cases, dtype: float64
29306 29313    8.0
Name: new_cases, dtype: float64
29307 29314    9.0
Name: new_cases, dtype: float64
29308 29315    9.0
Name: new_cases, dtype: float64
29309 29316    9.0
Name: new_cases, dtype: float64
29310 29317    17.0
Name: new_cases, dtype: float64
29311 29318    10.0
Name: new_cases, dtype: float64
29312 29319    7.0
Name: new_cases, dtype: float64
29313 29320    12.0
Name: new_cases, dtype: float64
29314 29321    25.0
Name: new_cases, dtype: float64
29315 29322    10.0
Name: new_cases, dtype: float64
29316 29323    10.0
Name: new_cases, dtype: float64
29317 29324    12.0
Name: new_cases, dtype: float64
29318 29325    9.0
Name: new_cases, dtype: float64
29319 29326    3.0
Name: new_cases, dtype: float64
29320 29327    7.0
Name: new_cases, dtype: float64
29321 29328    15.0
Name: new_cases, dtype: float64
29322 29329    6.0
Name: new_cases, dtype: float64
29323 29330    10.0
Name: new_cases, dtype: float64
29324 29331    10.0
Name: new_cases, dtype: float64
29325 29332    8.0
Name: new_cases, dtype: float64
29326 29333    12.0
Name: new_cases, dtype: float64
29327 29334    9.0
Name: new_cases, dtype: float64
29328 29335    32.0
Name: new_cases, dtype: float64
29329 29336    14.0
Name: new_cases, dtype: float64
29330 29337    10.0
Name: new_cases, dtype: float64
29331 29338    12.0
Name: new_cases, dtype: float64
29332 29339    6.0
Name: new_cases, dtype: float64
29333 29340    10.0
Name: new_cases, dtype: float64
29334 29341    7.0
Name: new_cases, dtype: float64

29335 29342    8.0
Name: new_cases, dtype: float64
29336 29343    15.0
Name: new_cases, dtype: float64
29337 29344    14.0
Name: new_cases, dtype: float64
29338 29345    21.0
Name: new_cases, dtype: float64
29339 29346    12.0
Name: new_cases, dtype: float64
29340 29347    19.0
Name: new_cases, dtype: float64
29341 29348    9.0
Name: new_cases, dtype: float64
29342 29349    12.0
29350    12.0
Name: new_cases, dtype: float64
29343 29349    12.0
29350    12.0
Name: new_cases, dtype: float64
29344 29351    10.0
Name: new_cases, dtype: float64
29345 29352    16.0
Name: new_cases, dtype: float64
29346 29353    20.0
Name: new_cases, dtype: float64
29347 29354    12.0
Name: new_cases, dtype: float64
29348 29355    7.0
Name: new_cases, dtype: float64
29349 29356    9.0
Name: new_cases, dtype: float64
29350 29357    23.0
Name: new_cases, dtype: float64
29351 29358    15.0
Name: new_cases, dtype: float64
29352 29359    21.0
Name: new_cases, dtype: float64
29353 29360    27.0
Name: new_cases, dtype: float64
29354 29361    7.0
Name: new_cases, dtype: float64
29355 29362    20.0
Name: new_cases, dtype: float64
29356 29363    11.0
Name: new_cases, dtype: float64
29357 29364    24.0
Name: new_cases, dtype: float64
29358 29365    13.0
Name: new_cases, dtype: float64
29359 29366    13.0
Name: new_cases, dtype: float64
29360 29367    13.0
Name: new_cases, dtype: float64
29361 29368    19.0
Name: new_cases, dtype: float64
29362 29369    11.0
Name: new_cases, dtype: float64
29363 29370    14.0
Name: new_cases, dtype: float64
29364 29371    18.0
Name: new_cases, dtype: float64
29365 29372    31.0
Name: new_cases, dtype: float64
29366 29373    15.0
Name: new_cases, dtype: float64
29367 29374    17.0
Name: new_cases, dtype: float64
29368 29375    16.0
Name: new_cases, dtype: float64
29369 29376    42.0
Name: new_cases, dtype: float64
29370 29377    47.0
Name: new_cases, dtype: float64
29371 29378    25.0
Name: new_cases, dtype: float64
29372 29379    33.0
Name: new_cases, dtype: float64
29373 29380    24.0
Name: new_cases, dtype: float64
29374 29381    24.0
Name: new_cases, dtype: float64
29375 29382    49.0
Name: new_cases, dtype: float64
29376 29383    17.0
Name: new_cases, dtype: float64
29377 29384    28.0
Name: new_cases, dtype: float64
29378 29385    36.0
Name: new_cases, dtype: float64
29379 29386    33.0
Name: new_cases, dtype: float64
29380 29387    28.0
Name: new_cases, dtype: float64
29381 29388    33.0
Name: new_cases, dtype: float64
29382 29389    22.0
Name: new_cases, dtype: float64
29383 29390    17.0
Name: new_cases, dtype: float64
29384 29391    15.0
Name: new_cases, dtype: float64
29385 29392    8.0
Name: new_cases, dtype: float64
29386 29393    18.0
Name: new_cases, dtype: float64
29387 29394    13.0
Name: new_cases, dtype: float64
29388 29395    8.0
Name: new_cases, dtype: float64
29389 29396    14.0
Name: new_cases, dtype: float64
29390 29397    9.0
Name: new_cases, dtype: float64
29391 29398    12.0
Name: new_cases, dtype: float64
29392 29399    17.0
Name: new_cases, dtype: float64
29393 29400    16.0
Name: new_cases, dtype: float64
29394 29401    17.0
Name: new_cases, dtype: float64
29395 29402    11.0
Name: new_cases, dtype: float64
29396 29403    22.0
Name: new_cases, dtype: float64
29397 29404    5.0
Name: new_cases, dtype: float64
29398 29405    21.0
Name: new_cases, dtype: float64
29399 29406    5.0
Name: new_cases, dtype: float64
29400 29407    6.0
Name: new_cases, dtype: float64
29401 29408    11.0
Name: new_cases, dtype: float64
29402 29409    18.0
Name: new_cases, dtype: float64
29403 29410    12.0
Name: new_cases, dtype: float64
29404 29411    9.0
Name: new_cases, dtype: float64
29405 29412    17.0
Name: new_cases, dtype: float64
29406 29413    18.0
Name: new_cases, dtype: float64
29407 29414    15.0
Name: new_cases, dtype: float64
29408 29415    18.0
Name: new_cases, dtype: float64
29409 29416    15.0
Name: new_cases, dtype: float64
29410 29417    15.0
Name: new_cases, dtype: float64
29411 29418    12.0
Name: new_cases, dtype: float64
29412 29419    12.0
Name: new_cases, dtype: float64
29413 29420    15.0
Name: new_cases, dtype: float64
29414 29421    13.0
Name: new_cases, dtype: float64
29415 29422    24.0
Name: new_cases, dtype: float64
29416 29423    16.0
Name: new_cases, dtype: float64
29417 29424    17.0
Name: new_cases, dtype: float64
29418 29425    12.0
Name: new_cases, dtype: float64
29419 29426    7.0
Name: new_cases, dtype: float64
29420 29427    12.0
Name: new_cases, dtype: float64
29421 29428    17.0
Name: new_cases, dtype: float64
29422 29429    23.0
Name: new_cases, dtype: float64
29423 29430    23.0
Name: new_cases, dtype: float64
29424 29431    15.0
Name: new_cases, dtype: float64
29425 29432    15.0
Name: new_cases, dtype: float64
29426 29433    17.0
Name: new_cases, dtype: float64
29427 29434    14.0
Name: new_cases, dtype: float64
29428 29435    20.0
Name: new_cases, dtype: float64
29429 29436    22.0
Name: new_cases, dtype: float64
29430 29437    21.0
Name: new_cases, dtype: float64
29431 29438    27.0
Name: new_cases, dtype: float64
29432 29439    24.0
Name: new_cases, dtype: float64
29433 29440    25.0
Name: new_cases, dtype: float64
29434 29441    19.0
Name: new_cases, dtype: float64
29435 29442    18.0
Name: new_cases, dtype: float64
29436 29443    28.0
Name: new_cases, dtype: float64
29437 29444    33.0
Name: new_cases, dtype: float64
29438 29445    33.0
Name: new_cases, dtype: float64
29439 29446    32.0
Name: new_cases, dtype: float64
29440 29447    63.0
Name: new_cases, dtype: float64
29441 29448    53.0
Name: new_cases, dtype: float64
29442 29449    33.0
Name: new_cases, dtype: float64
29443 29450    69.0
Name: new_cases, dtype: float64
29444 29451    103.0
Name: new_cases, dtype: float64
29445 29452    55.0
Name: new_cases, dtype: float64
29446 29453    115.0
Name: new_cases, dtype: float64
29447 29454    138.0
Name: new_cases, dtype: float64
29448 29455    144.0
Name: new_cases, dtype: float64
29449 29456    130.0
Name: new_cases, dtype: float64
29450 29457    109.0
Name: new_cases, dtype: float64
29451 29458    109.0
Name: new_cases, dtype: float64
29452 29459    118.0
Name: new_cases, dtype: float64
29453 29460    103.0
Name: new_cases, dtype: float64
29454 29461    144.0
Name: new_cases, dtype: float64
29455 29462    110.0
Name: new_cases, dtype: float64
29456 29463    100.0
Name: new_cases, dtype: float64
29457 29464    80.0
Name: new_cases, dtype: float64
29458 29465    124.0
Name: new_cases, dtype: float64
29459 29466    82.0
Name: new_cases, dtype: float64
29460 29467    75.0
Name: new_cases, dtype: float64
29461 29468    54.0
Name: new_cases, dtype: float64
29462 29469    52.0
Name: new_cases, dtype: float64
29463 29470    52.0
Name: new_cases, dtype: float64
29464 29471    92.0
Name: new_cases, dtype: float64
29465 29472    42.0
Name: new_cases, dtype: float64
29466 29473    30.0
Name: new_cases, dtype: float64
29467 29474    25.0
Name: new_cases, dtype: float64
29468 29475    30.0
Name: new_cases, dtype: float64
29469 29476    20.0
Name: new_cases, dtype: float64
29470 29477    12.0
Name: new_cases, dtype: float64
29471 29478    11.0
Name: new_cases, dtype: float64
29472 29479    14.0
Name: new_cases, dtype: float64
29473 29480    14.0
Name: new_cases, dtype: float64
29474 29481    14.0
Name: new_cases, dtype: float64
29475 29482    2.0
Name: new_cases, dtype: float64
29476 29483    12.0
Name: new_cases, dtype: float64
29477 29484    8.0
Name: new_cases, dtype: float64
29478 29485    7.0
Name: new_cases, dtype: float64
29479 29486    9.0
Name: new_cases, dtype: float64
29480 29487    16.0
Name: new_cases, dtype: float64
29481 29488    7.0
Name: new_cases, dtype: float64
29482 29489    11.0
Name: new_cases, dtype: float64
29483 29490    10.0
Name: new_cases, dtype: float64
29484 29491    8.0
Name: new_cases, dtype: float64
29485 29492    7.0
Name: new_cases, dtype: float64
29486 29493    11.0
Name: new_cases, dtype: float64
29487 29494    10.0
Name: new_cases, dtype: float64
29488 29495    12.0
Name: new_cases, dtype: float64
29489 29496    7.0
Name: new_cases, dtype: float64
29490 29497    6.0
Name: new_cases, dtype: float64
29491 29498    10.0
Name: new_cases, dtype: float64
29492 29499    6.0
Name: new_cases, dtype: float64
29493 29500    19.0
Name: new_cases, dtype: float64
29494 29501    11.0
Name: new_cases, dtype: float64
29495 29502    10.0

Name: new_cases, dtype: float64
29496 29503    10.0
Name: new_cases, dtype: float64
29497 29504    9.0
Name: new_cases, dtype: float64
29498 29505    10.0
Name: new_cases, dtype: float64
29499 29506    13.0
Name: new_cases, dtype: float64
29500 29507    19.0
Name: new_cases, dtype: float64
29501 29508    8.0
Name: new_cases, dtype: float64
29502 29509    5.0
Name: new_cases, dtype: float64
29503 29510    11.0
Name: new_cases, dtype: float64
29504 29511    9.0
Name: new_cases, dtype: float64
29505 29512    7.0
Name: new_cases, dtype: float64
29506 29513    10.0
Name: new_cases, dtype: float64
29507 29514    5.0
Name: new_cases, dtype: float64
29508 29515    13.0
Name: new_cases, dtype: float64
29509 29516    4.0
Name: new_cases, dtype: float64
29510 29517    6.0
Name: new_cases, dtype: float64
29511 29518    11.0
Name: new_cases, dtype: float64
29512 29519    4.0
Name: new_cases, dtype: float64
29513 29520    12.0
Name: new_cases, dtype: float64
29514 29521    7.0
Name: new_cases, dtype: float64
29515 29522    9.0
Name: new_cases, dtype: float64
29516 29523    10.0
Name: new_cases, dtype: float64
29517 29524    11.0
Name: new_cases, dtype: float64
29518 29525    11.0
Name: new_cases, dtype: float64
29519 29526    12.0
Name: new_cases, dtype: float64
29520 29527    11.0
Name: new_cases, dtype: float64
29521 29528    12.0
Name: new_cases, dtype: float64
29522 29529    8.0
Name: new_cases, dtype: float64
29523 29530    11.0
Name: new_cases, dtype: float64
29524 29531    16.0
Name: new_cases, dtype: float64
29525 29532    9.0
Name: new_cases, dtype: float64
29526 29533    26.0
Name: new_cases, dtype: float64
29527 29534    20.0
Name: new_cases, dtype: float64
29528 29535    33.0
Name: new_cases, dtype: float64
29529 29536    24.0
Name: new_cases, dtype: float64
29530 29537    12.0
Name: new_cases, dtype: float64
29531 29538    24.0
Name: new_cases, dtype: float64
29532 29539    21.0
Name: new_cases, dtype: float64
29533 29540    14.0
Name: new_cases, dtype: float64
29534 29541    10.0
Name: new_cases, dtype: float64
29535 29542    16.0
Name: new_cases, dtype: float64
29536 29543    9.0
Name: new_cases, dtype: float64
29537 29544    12.0
Name: new_cases, dtype: float64
29538 29545    10.0
Name: new_cases, dtype: float64
29539 29546    11.0
Name: new_cases, dtype: float64
29540 29547    15.0
Name: new_cases, dtype: float64
29541 29548    16.0
Name: new_cases, dtype: float64
29542 29549    11.0
Name: new_cases, dtype: float64
29543 29550    10.0
Name: new_cases, dtype: float64
29544 29551    21.0
Name: new_cases, dtype: float64
29545 29552    6.0
Name: new_cases, dtype: float64
29546 29553    19.0
Name: new_cases, dtype: float64
29547 29554    9.0
Name: new_cases, dtype: float64
29548 29555    13.0
Name: new_cases, dtype: float64
29549 29556    11.0
Name: new_cases, dtype: float64
29550 29557    11.0
Name: new_cases, dtype: float64
29551 29558    12.0
Name: new_cases, dtype: float64
29552 29559    20.0
Name: new_cases, dtype: float64
29553 29560    13.0
Name: new_cases, dtype: float64
29554 29561    16.0
Name: new_cases, dtype: float64
29555 29562    15.0
Name: new_cases, dtype: float64
29556 29563    11.0
Name: new_cases, dtype: float64
29557 29564    17.0
Name: new_cases, dtype: float64
29558 29565    7.0
Name: new_cases, dtype: float64
29559 29566    5.0
Name: new_cases, dtype: float64
29560 29567    13.0
Name: new_cases, dtype: float64
29561 29568    7.0
Name: new_cases, dtype: float64
29562 29569    12.0
Name: new_cases, dtype: float64
29563 29570    11.0
Name: new_cases, dtype: float64
29564 29571    14.0
Name: new_cases, dtype: float64
29565 29572    16.0
Name: new_cases, dtype: float64
29566 29573    9.0
Name: new_cases, dtype: float64
29567 29574    7.0
Name: new_cases, dtype: float64
29568 29575    14.0
Name: new_cases, dtype: float64
29569 29576    18.0
Name: new_cases, dtype: float64
29570 29577    25.0
Name: new_cases, dtype: float64
29571 29578    22.0
Name: new_cases, dtype: float64
29572 29579    14.0
Name: new_cases, dtype: float64
29573 29580    12.0
Name: new_cases, dtype: float64
29574 29581    24.0
Name: new_cases, dtype: float64
29575 29582    10.0
Name: new_cases, dtype: float64
29576 29583    19.0
Name: new_cases, dtype: float64
29577 29584    18.0
Name: new_cases, dtype: float64
29578 29585    15.0
Name: new_cases, dtype: float64
29579 29586    13.0
Name: new_cases, dtype: float64
29580 29587    19.0
Name: new_cases, dtype: float64
29581 29588    7.0
Name: new_cases, dtype: float64
29582 29589    16.0
Name: new_cases, dtype: float64
29583 29590    11.0
Name: new_cases, dtype: float64
29584 29591    27.0
Name: new_cases, dtype: float64
29585 29592    23.0
Name: new_cases, dtype: float64
29586 29593    24.0
Name: new_cases, dtype: float64
29587 29594    24.0
Name: new_cases, dtype: float64
29588 29595    24.0
Name: new_cases, dtype: float64
29589 29596    24.0
Name: new_cases, dtype: float64
29590 29597    30.0
Name: new_cases, dtype: float64
29591 29598    19.0
Name: new_cases, dtype: float64
29592 29599    33.0
Name: new_cases, dtype: float64
29593 29600    16.0
Name: new_cases, dtype: float64
29594 29601    21.0
Name: new_cases, dtype: float64
29595 29602    22.0
Name: new_cases, dtype: float64
29596 29603    35.0
Name: new_cases, dtype: float64
29597 29604    34.0
Name: new_cases, dtype: float64
29598 29605    23.0
Name: new_cases, dtype: float64
29599 29606    20.0
Name: new_cases, dtype: float64
29600 29607    21.0
Name: new_cases, dtype: float64
29601 29608    19.0
Name: new_cases, dtype: float64
29602 29609    23.0
Name: new_cases, dtype: float64
29603 29610    30.0
Name: new_cases, dtype: float64
29604 29611    23.0
Name: new_cases, dtype: float64
29605 29612    17.0
Name: new_cases, dtype: float64
29606 29613    25.0
Name: new_cases, dtype: float64
29607 29614    24.0
Name: new_cases, dtype: float64
29608 29615    16.0
Name: new_cases, dtype: float64
29609 29616    24.0
Name: new_cases, dtype: float64
29610 29617    25.0
Name: new_cases, dtype: float64
29611 29618    14.0
Name: new_cases, dtype: float64
29612 29619    22.0
Name: new_cases, dtype: float64
29613 29620    17.0
Name: new_cases, dtype: float64
29614 29621    9.0
Name: new_cases, dtype: float64
29615 29622    12.0
Name: new_cases, dtype: float64
29616 29623    18.0
Name: new_cases, dtype: float64
29617 29624    23.0
Name: new_cases, dtype: float64
29618 29625    14.0
Name: new_cases, dtype: float64
29619 29626    22.0
Name: new_cases, dtype: float64
29620 29627    23.0
Name: new_cases, dtype: float64
29621 29628    57.0
Name: new_cases, dtype: float64
29622 29629    17.0
Name: new_cases, dtype: float64
29623 29630    23.0
Name: new_cases, dtype: float64
29624 29631    26.0
Name: new_cases, dtype: float64
29625 29632    0.0
Name: new_cases, dtype: float64
29626 29633    51.0
Name: new_cases, dtype: float64
29627 29634    29.0
Name: new_cases, dtype: float64
29628 29635    24.0
Name: new_cases, dtype: float64
29629 29636    28.0
Name: new_cases, dtype: float64
29630 29637    36.0
Name: new_cases, dtype: float64
29631 29638    30.0
Name: new_cases, dtype: float64
29632 29639    33.0
Name: new_cases, dtype: float64
29633 29640    31.0
Name: new_cases, dtype: float64
29634 29641    65.0
Name: new_cases, dtype: float64
29635 29642    0.0
Name: new_cases, dtype: float64
29636 29643    72.0
Name: new_cases, dtype: float64
29637 29644    48.0
Name: new_cases, dtype: float64
29638 29645    72.0
Name: new_cases, dtype: float64
29639 29646   -5.0
Name: new_cases, dtype: float64
29640 29647    76.0
Name: new_cases, dtype: float64
29641 29648    71.0
Name: new_cases, dtype: float64
29642 29649    86.0
Name: new_cases, dtype: float64
29643 29650    49.0
Name: new_cases, dtype: float64
29644 29651    66.0
Name: new_cases, dtype: float64
29645 29652    53.0
Name: new_cases, dtype: float64
29646 29653    77.0
Name: new_cases, dtype: float64
29647 29654    96.0
Name: new_cases, dtype: float64
29648 29655    90.0
Name: new_cases, dtype: float64
29649 29656    96.0
Name: new_cases, dtype: float64
29650 29657    85.0
Name: new_cases, dtype: float64
29651 29658    124.0
Name: new_cases, dtype: float64
29652 29659    107.0
Name: new_cases, dtype: float64
29653 29660    96.0
Name: new_cases, dtype: float64
29654 29661    125.0
Name: new_cases, dtype: float64
29655 29662    143.0
Name: new_cases, dtype: float64
29656 29663    111.0
Name: new_cases, dtype: float64
29657 29664    81.0
Name: new_cases, dtype: float64
29658 29665    99.0
Name: new_cases, dtype: float64
29659 29666    66.0
Name: new_cases, dtype: float64
29660 29667    53.0
Name: new_cases, dtype: float64

29661 29668    51.0
Name: new_cases, dtype: float64
29662 29669    42.0
Name: new_cases, dtype: float64
29663 29670    28.0
Name: new_cases, dtype: float64
29664 29671    46.0
Name: new_cases, dtype: float64
29665 29672    33.0
Name: new_cases, dtype: float64
29666 29673    20.0
Name: new_cases, dtype: float64
29667 29674    32.0
Name: new_cases, dtype: float64
29668 29675    21.0
Name: new_cases, dtype: float64
29669 29676    35.0
Name: new_cases, dtype: float64
29670 29677    20.0
Name: new_cases, dtype: float64
29671 29678    26.0
Name: new_cases, dtype: float64
29672 29679    32.0
Name: new_cases, dtype: float64
29673 29680    21.0
Name: new_cases, dtype: float64
29674 29681    33.0
Name: new_cases, dtype: float64
29675 29682    23.0
Name: new_cases, dtype: float64
29676 29683    37.0
Name: new_cases, dtype: float64
29677 29684    19.0
Name: new_cases, dtype: float64
29678 29685    28.0
Name: new_cases, dtype: float64
29679 29686    28.0
Name: new_cases, dtype: float64
29680 29687    28.0
Name: new_cases, dtype: float64
29681 29688    28.0
Name: new_cases, dtype: float64
29682 29689    18.0
Name: new_cases, dtype: float64
29683 29690    36.0
Name: new_cases, dtype: float64
29684 29691    19.0
Name: new_cases, dtype: float64
29685 29692    28.0
Name: new_cases, dtype: float64
29686 29693    17.0
Name: new_cases, dtype: float64
29687 29694    25.0
Name: new_cases, dtype: float64
29688 29695    46.0
Name: new_cases, dtype: float64
29689 29696    49.0
Name: new_cases, dtype: float64
29690 29697    92.0
Name: new_cases, dtype: float64
29691 29698    73.0
Name: new_cases, dtype: float64
29692 29699    80.0
Name: new_cases, dtype: float64
29693 29700    84.0
Name: new_cases, dtype: float64
29694 29701    46.0
Name: new_cases, dtype: float64
29695 29702    66.0
Name: new_cases, dtype: float64
29696 29703    49.0
Name: new_cases, dtype: float64
29697 29704    72.0
Name: new_cases, dtype: float64
29698 29705    41.0
Name: new_cases, dtype: float64
29699 29706    43.0
Name: new_cases, dtype: float64
29700 29707    54.0
Name: new_cases, dtype: float64
29701 29708    38.0
Name: new_cases, dtype: float64
29702 29709    29.0
Name: new_cases, dtype: float64
29703 29710    35.0
Name: new_cases, dtype: float64
29704 29711    31.0
Name: new_cases, dtype: float64
29705 29712    25.0
Name: new_cases, dtype: float64
29706 29713    22.0
Name: new_cases, dtype: float64
29707 29714    34.0
Name: new_cases, dtype: float64
29708 29715    41.0
Name: new_cases, dtype: float64
29709 29716    28.0
Name: new_cases, dtype: float64
29710 29717    27.0
Name: new_cases, dtype: float64
29711 29718    26.0
Name: new_cases, dtype: float64
29712 29719    26.0
Name: new_cases, dtype: float64
29713 29720    25.0
Name: new_cases, dtype: float64
29714 29721    22.0
Name: new_cases, dtype: float64
29715 29722    17.0
Name: new_cases, dtype: float64
29716 29723    24.0
Name: new_cases, dtype: float64
29717 29724    25.0
Name: new_cases, dtype: float64
29718 29725    12.0
Name: new_cases, dtype: float64
29719 29726    22.0
Name: new_cases, dtype: float64
29720 29727    26.0
Name: new_cases, dtype: float64
29721 29728    5.0
Name: new_cases, dtype: float64
29722 29729    14.0
Name: new_cases, dtype: float64
29723 29730    21.0
Name: new_cases, dtype: float64
29724 29731    27.0
Name: new_cases, dtype: float64
29725 29732    21.0
Name: new_cases, dtype: float64
29726 29733    30.0
Name: new_cases, dtype: float64
29727 29734    21.0
Name: new_cases, dtype: float64
29728 29735    48.0
Name: new_cases, dtype: float64
29729 29736    45.0
Name: new_cases, dtype: float64
29730 29737    44.0
Name: new_cases, dtype: float64
29731 29738    38.0
Name: new_cases, dtype: float64
29732 29739    63.0
Name: new_cases, dtype: float64
29733 29740    39.0
Name: new_cases, dtype: float64
29734 29741    39.0
Name: new_cases, dtype: float64
29735 29742    64.0
Name: new_cases, dtype: float64
29736 29743    78.0
Name: new_cases, dtype: float64
29737 29744    72.0
Name: new_cases, dtype: float64
29738 29745    91.0
Name: new_cases, dtype: float64
29739 29746    71.0
Name: new_cases, dtype: float64
29740 29747    110.0
Name: new_cases, dtype: float64
29741 29748    103.0
Name: new_cases, dtype: float64
29742 29749    78.0
Name: new_cases, dtype: float64
29743 29750    60.0
Name: new_cases, dtype: float64
29744 29751    69.0
Name: new_cases, dtype: float64
29745 29752    89.0
Name: new_cases, dtype: float64
29746 29753    62.0
Name: new_cases, dtype: float64
29747 29754    54.0
Name: new_cases, dtype: float64
29748 29755    64.0
Name: new_cases, dtype: float64
29749 29756    96.0
Name: new_cases, dtype: float64
29750 29757    75.0
Name: new_cases, dtype: float64
29751 29758    89.0
Name: new_cases, dtype: float64
29752 29759    52.0
Name: new_cases, dtype: float64
29753 29760    22.0
Name: new_cases, dtype: float64
29754 29761    31.0
Name: new_cases, dtype: float64
29755 29762    35.0
Name: new_cases, dtype: float64
29756 29763    24.0
Name: new_cases, dtype: float64
29757 29764    23.0
Name: new_cases, dtype: float64
29758 29765    17.0
Name: new_cases, dtype: float64
29759 29766    38.0
Name: new_cases, dtype: float64
29760 29767    19.0
Name: new_cases, dtype: float64
29761 29768    22.0
Name: new_cases, dtype: float64
29762 29769    24.0
Name: new_cases, dtype: float64
29763 29770    13.0
Name: new_cases, dtype: float64
29764 29771    25.0
Name: new_cases, dtype: float64
29765 29772    23.0
Name: new_cases, dtype: float64
29766 29773    41.0
Name: new_cases, dtype: float64
29767 29774    39.0
Name: new_cases, dtype: float64
29768 29775    113.0
Name: new_cases, dtype: float64
29769 29776    73.0
Name: new_cases, dtype: float64
29770 29777    96.0
Name: new_cases, dtype: float64
29771 29778    90.0
Name: new_cases, dtype: float64
29772 29779    59.0
Name: new_cases, dtype: float64
29773 29780    61.0
Name: new_cases, dtype: float64
29774 29781    94.0
Name: new_cases, dtype: float64
29775 29782    74.0
Name: new_cases, dtype: float64
29776 29783    83.0
Name: new_cases, dtype: float64
29777 29784    63.0
Name: new_cases, dtype: float64
29778 29785    87.0
Name: new_cases, dtype: float64
29779 29786    75.0
Name: new_cases, dtype: float64
29780 29787    101.0
Name: new_cases, dtype: float64
29781 29788    76.0
Name: new_cases, dtype: float64
29782 29789    69.0
Name: new_cases, dtype: float64
29783 29790    75.0
Name: new_cases, dtype: float64
29784 29791    76.0
Name: new_cases, dtype: float64
29785 29792    125.0
Name: new_cases, dtype: float64
29786 29793    83.0
Name: new_cases, dtype: float64
29787 29794    102.0
Name: new_cases, dtype: float64
29788 29795    81.0
Name: new_cases, dtype: float64
29789 29796    78.0
Name: new_cases, dtype: float64
29790 29797    99.0
Name: new_cases, dtype: float64
29791 29798    87.0
Name: new_cases, dtype: float64
29792 29799    140.0
Name: new_cases, dtype: float64
29793 29800    46.0
Name: new_cases, dtype: float64
29794 29801    208.0
Name: new_cases, dtype: float64
29795 29802    361.0
Name: new_cases, dtype: float64
29796 29803    197.0
Name: new_cases, dtype: float64
29797 29804    207.0
Name: new_cases, dtype: float64
29798 29805    195.0
Name: new_cases, dtype: float64
29799 29806    229.0
Name: new_cases, dtype: float64
29800 29807    191.0
Name: new_cases, dtype: float64
29801 29808    161.0
Name: new_cases, dtype: float64
29802 29809    175.0
Name: new_cases, dtype: float64
29803 29810    91.0
Name: new_cases, dtype: float64
29804 29811    189.0
Name: new_cases, dtype: float64
29805 29812    174.0
Name: new_cases, dtype: float64
29806 29813    159.0
Name: new_cases, dtype: float64
29807 29814    165.0
Name: new_cases, dtype: float64
29808 29140    151.0
Name: new_cases, dtype: float64
29809 29141    79.0
Name: new_cases, dtype: float64
29810 29142    47.0
Name: new_cases, dtype: float64
29811 29143    36.0
Name: new_cases, dtype: float64
29812 29144    22.0
Name: new_cases, dtype: float64
29813 29145    28.0
Name: new_cases, dtype: float64
29814 29146    8.0
Name: new_cases, dtype: float64
29815 29822    4.0
Name: new_cases, dtype: float64
29816 29823    9.0
Name: new_cases, dtype: float64
29817 29824    12.0
Name: new_cases, dtype: float64
29818 29825    23.0
Name: new_cases, dtype: float64
29819 29826    18.0
Name: new_cases, dtype: float64

29820 29827    27.0
Name: new_cases, dtype: float64
29821 29828    6.0
Name: new_cases, dtype: float64
29822 29829    50.0
Name: new_cases, dtype: float64
29823 29830    38.0
Name: new_cases, dtype: float64
29824 29831    35.0
Name: new_cases, dtype: float64
29825 29832    46.0
Name: new_cases, dtype: float64
29826 29833    101.0
Name: new_cases, dtype: float64
29827 29834    92.0
Name: new_cases, dtype: float64
29828 29835    21.0
Name: new_cases, dtype: float64
29829 29836    48.0
Name: new_cases, dtype: float64
29830 29837    69.0
Name: new_cases, dtype: float64
29831 29838    94.0
Name: new_cases, dtype: float64
29832 29839    96.0
Name: new_cases, dtype: float64
29833 29840    108.0
Name: new_cases, dtype: float64
29834 29841    159.0
Name: new_cases, dtype: float64
29835 29842    96.0
Name: new_cases, dtype: float64
29836 29843    106.0
Name: new_cases, dtype: float64
29837 29844    139.0
Name: new_cases, dtype: float64
29838 29845    79.0
Name: new_cases, dtype: float64
29839 29846    94.0
Name: new_cases, dtype: float64
29840 29847    201.0
Name: new_cases, dtype: float64
29841 29848    274.0
Name: new_cases, dtype: float64
29842 29849    169.0
Name: new_cases, dtype: float64
29843 29850    250.0
Name: new_cases, dtype: float64
29844 29851    236.0
Name: new_cases, dtype: float64
29845 29852    67.0
Name: new_cases, dtype: float64
29846 29853    76.0
Name: new_cases, dtype: float64
29847 29854    127.0
Name: new_cases, dtype: float64
29848 29855    126.0
Name: new_cases, dtype: float64
29849 29856    128.0
Name: new_cases, dtype: float64
29850 29857    206.0
Name: new_cases, dtype: float64
29851 29858    182.0
Name: new_cases, dtype: float64
29852 29859    171.0
Name: new_cases, dtype: float64
29853 29860    185.0
Name: new_cases, dtype: float64
29854 29861    172.0
Name: new_cases, dtype: float64
29855 29862    207.0
Name: new_cases, dtype: float64
29856 29863    205.0
Name: new_cases, dtype: float64
29857 29864    320.0
Name: new_cases, dtype: float64
29858 29865    261.0
Name: new_cases, dtype: float64
29859 29866    237.0
Name: new_cases, dtype: float64
29860 29867    218.0
Name: new_cases, dtype: float64
29861 29868    352.0
Name: new_cases, dtype: float64
29862 29869    258.0
Name: new_cases, dtype: float64
29863 29870    300.0
Name: new_cases, dtype: float64
29864 29871    499.0
Name: new_cases, dtype: float64
29865 29872    279.0
Name: new_cases, dtype: float64
29866 29873    383.0
Name: new_cases, dtype: float64
29867 29874    305.0
Name: new_cases, dtype: float64
29868 29875    640.0
Name: new_cases, dtype: float64
29869 29876    346.0
Name: new_cases, dtype: float64
29870 29877    497.0
Name: new_cases, dtype: float64
29871 29878    595.0
Name: new_cases, dtype: float64
29872 29879    444.0
Name: new_cases, dtype: float64
29873 29880    568.0
Name: new_cases, dtype: float64
29874 29881    550.0
Name: new_cases, dtype: float64
29875 29882    659.0
Name: new_cases, dtype: float64
29876 29883    658.0
Name: new_cases, dtype: float64
29877 29884    680.0
Name: new_cases, dtype: float64
29878 29885    606.0
Name: new_cases, dtype: float64
29879 29886    723.0
Name: new_cases, dtype: float64
29880 29887    635.0
Name: new_cases, dtype: float64
29881 29888    721.0
Name: new_cases, dtype: float64
29882 29889    640.0
Name: new_cases, dtype: float64
29883 29890    752.0
Name: new_cases, dtype: float64
29884 29891    643.0
Name: new_cases, dtype: float64
29885 29892    801.0
Name: new_cases, dtype: float64
29886 29893    1046.0
Name: new_cases, dtype: float64
29887 29894    998.0
Name: new_cases, dtype: float64
29888 29895    806.0
Name: new_cases, dtype: float64
29889 29896    1022.0
Name: new_cases, dtype: float64
29890 29897    1101.0
Name: new_cases, dtype: float64
29891 29898    1262.0
Name: new_cases, dtype: float64
29892 29899    1322.0
Name: new_cases, dtype: float64
29893 29900    1548.0
Name: new_cases, dtype: float64
29894 29901    1147.0
Name: new_cases, dtype: float64
29895 29902    1110.0
Name: new_cases, dtype: float64
29896 29903    1340.0
Name: new_cases, dtype: float64
29897 29904    1521.0
Name: new_cases, dtype: float64
29898 29905    1766.0
Name: new_cases, dtype: float64
29899 29906    1515.0
Name: new_cases, dtype: float64
29900 29907    1392.0
Name: new_cases, dtype: float64
29901 29908    1209.0
Name: new_cases, dtype: float64
29902 29909    1483.0
Name: new_cases, dtype: float64
29903 29910    1359.0
Name: new_cases, dtype: float64
29904 29911    1604.0
Name: new_cases, dtype: float64
29905 29912    1530.0
Name: new_cases, dtype: float64
29906 29913    1646.0
Name: new_cases, dtype: float64
29907 29914    1888.0
Name: new_cases, dtype: float64
29908 29915    2193.0
Name: new_cases, dtype: float64
29909 29916    2124.0
Name: new_cases, dtype: float64
29910 29917    1868.0
Name: new_cases, dtype: float64
29911 29918    2115.0
Name: new_cases, dtype: float64
29912 29919    3171.0
Name: new_cases, dtype: float64
29913 29920    3059.0
Name: new_cases, dtype: float64
29914 29921    2357.0
Name: new_cases, dtype: float64
29915 29922    3019.0
Name: new_cases, dtype: float64
29916 29923    2531.0
Name: new_cases, dtype: float64
29917 29924    2389.0
Name: new_cases, dtype: float64
29918 29925    3541.0
Name: new_cases, dtype: float64
29919 29926    3486.0
Name: new_cases, dtype: float64
29920 29927    3843.0
Name: new_cases, dtype: float64
29921 29928    4149.0
Name: new_cases, dtype: float64
29922 29929    3178.0
Name: new_cases, dtype: float64
29923 29930    3274.0
Name: new_cases, dtype: float64
29924 29931    2803.0
Name: new_cases, dtype: float64
29925 29932    4163.0
Name: new_cases, dtype: float64
29926 29933    4101.0
Name: new_cases, dtype: float64
29927 29934    3395.0
Name: new_cases, dtype: float64
29928 29935    3884.0
Name: new_cases, dtype: float64
29929 29936    3721.0
Name: new_cases, dtype: float64
29930 29937    3171.0
Name: new_cases, dtype: float64
29931 29938    4213.0
Name: new_cases, dtype: float64
29932 29939    4144.0
Name: new_cases, dtype: float64
29933 29940    5335.0
Name: new_cases, dtype: float64
29934 29941    6803.0
Name: new_cases, dtype: float64
29935 29942    4856.0
Name: new_cases, dtype: float64
29936 29943    4813.0
Name: new_cases, dtype: float64
29937 29944    3832.0
Name: new_cases, dtype: float64
29938 29945    5621.0
Name: new_cases, dtype: float64
29939 29946    5271.0
Name: new_cases, dtype: float64
29940 29947    8037.0
Name: new_cases, dtype: float64
29941 29948    8934.0
Name: new_cases, dtype: float64
29942 29949    8560.0
Name: new_cases, dtype: float64
29943 29950    6578.0
Name: new_cases, dtype: float64
29944 29951    6727.0
Name: new_cases, dtype: float64
29945 29952    7033.0
Name: new_cases, dtype: float64
29946 29953    7390.0
Name: new_cases, dtype: float64
29947 29954    7945.0
Name: new_cases, dtype: float64
29948 29955    7168.0
Name: new_cases, dtype: float64
29949 29956    7254.0
Name: new_cases, dtype: float64
29950 29957    8181.0
Name: new_cases, dtype: float64
29951 29958    8125.0
Name: new_cases, dtype: float64
29952 29959    10284.0
Name: new_cases, dtype: float64
29953 29960    8670.0
Name: new_cases, dtype: float64
29954 29961    9965.0
Name: new_cases, dtype: float64
29955 29962    9488.0
Name: new_cases, dtype: float64
29956 29963    10673.0
Name: new_cases, dtype: float64
29957 29964    11470.0
Name: new_cases, dtype: float64
29958 29965    10199.0
Name: new_cases, dtype: float64
29959 29966    7129.0
Name: new_cases, dtype: float64
29960 29967    10735.0
Name: new_cases, dtype: float64
29961 29968    11996.0
Name: new_cases, dtype: float64
29962 29969    9494.0
Name: new_cases, dtype: float64
29963 29970    9666.0
Name: new_cases, dtype: float64
29964 29971    10611.0
Name: new_cases, dtype: float64
29965 29972    10142.0
Name: new_cases, dtype: float64
29966 29973    12830.0
Name: new_cases, dtype: float64
29967 29974    12066.0
Name: new_cases, dtype: float64
29968 29975    11286.0
Name: new_cases, dtype: float64
29969 29976    11306.0
Name: new_cases, dtype: float64
29970 29977    11578.0
Name: new_cases, dtype: float64
29971 29978    11643.0
Name: new_cases, dtype: float64
29972 29979    8328.0
Name: new_cases, dtype: float64
29973 29980    12462.0
Name: new_cases, dtype: float64
29974 29981    13056.0
Name: new_cases, dtype: float64
29975 29982    11541.0
Name: new_cases, dtype: float64
29976 29983    8419.0
Name: new_cases, dtype: float64
29977 29984    10965.0
Name: new_cases, dtype: float64
29978 29985    8036.0
Name: new_cases, dtype: float64
29979 29986    10549.0
Name: new_cases, dtype: float64
29980 29987    10425.0
Name: new_cases, dtype: float64
29981 29988    10130.0
Name: new_cases, dtype: float64
29982 29989    9752.0
Name: new_cases, dtype: float64
29983 29990    8497.0
Name: new_cases, dtype: float64
29984 29991    9392.0
Name: new_cases, dtype: float64
29985 29992    8020.0
Name: new_cases, dtype: float64

29986 29993    7190.0
Name: new_cases, dtype: float64
29987 29994    8932.0
Name: new_cases, dtype: float64
29988 29995    9295.0
Name: new_cases, dtype: float64
29989 29996    8253.0
Name: new_cases, dtype: float64
29990 29997    8489.0
Name: new_cases, dtype: float64
29991 29998    8393.0
Name: new_cases, dtype: float64
29992 29999    8065.0
Name: new_cases, dtype: float64
29993 30000    5327.0
Name: new_cases, dtype: float64
29994 30001    7665.0
Name: new_cases, dtype: float64
29995 30002    7338.0
Name: new_cases, dtype: float64
29996 30003    7813.0
Name: new_cases, dtype: float64
29997 30004    7424.0
Name: new_cases, dtype: float64
29998 30005    6876.0
Name: new_cases, dtype: float64
29999 30006    7355.0
Name: new_cases, dtype: float64
30000 30007    5573.0
Name: new_cases, dtype: float64
30001 30008    6698.0
Name: new_cases, dtype: float64
30002 30009    7787.0
Name: new_cases, dtype: float64
30003 30010    7568.0
Name: new_cases, dtype: float64
30004 30011    6526.0
Name: new_cases, dtype: float64
30005 30012    7927.0
Name: new_cases, dtype: float64
30006 30013    6678.0
Name: new_cases, dtype: float64
30007 30014    5359.0
Name: new_cases, dtype: float64
30008 30015    7102.0
Name: new_cases, dtype: float64
30009 30016    6731.0
Name: new_cases, dtype: float64
30010 30017    6555.0
Name: new_cases, dtype: float64
30011 30018    7494.0
Name: new_cases, dtype: float64
30012 30019    7721.0
Name: new_cases, dtype: float64
30013 30020    7018.0
Name: new_cases, dtype: float64
30014 30021    5147.0
Name: new_cases, dtype: float64
30015 30022    5839.0
Name: new_cases, dtype: float64
30016 30023    5637.0
Name: new_cases, dtype: float64
30017 30024    5660.0
Name: new_cases, dtype: float64
30018 30025    6193.0
Name: new_cases, dtype: float64
30019 30026    6615.0
Name: new_cases, dtype: float64
30020 30027    6905.0
Name: new_cases, dtype: float64
30021 30028    7106.0
Name: new_cases, dtype: float64
30022 30029    7650.0
Name: new_cases, dtype: float64
30023 30030    7876.0
Name: new_cases, dtype: float64
30024 30031    8495.0
Name: new_cases, dtype: float64
30025 30032    8121.0
Name: new_cases, dtype: float64
30026 30033    8447.0
Name: new_cases, dtype: float64
30027 30034    8569.0
Name: new_cases, dtype: float64
30028 30035    7768.0
Name: new_cases, dtype: float64
30029 30036    5014.0
Name: new_cases, dtype: float64
30030 30037    6061.0
Name: new_cases, dtype: float64
30031 30038    6823.0
Name: new_cases, dtype: float64
30032 30039    8372.0
Name: new_cases, dtype: float64
30033 30040    7017.0
Name: new_cases, dtype: float64
30034 30041    7201.0
Name: new_cases, dtype: float64
30035 30042    6311.0
Name: new_cases, dtype: float64
30036 30043    8256.0
Name: new_cases, dtype: float64
30037 30044    7561.0
Name: new_cases, dtype: float64
30038 30045    8673.0
Name: new_cases, dtype: float64
30039 30046    8569.0
Name: new_cases, dtype: float64
30040 30047    8769.0
Name: new_cases, dtype: float64
30041 30048    8174.0
Name: new_cases, dtype: float64
30042 30049    9167.0
Name: new_cases, dtype: float64
30043 30050    8166.0
Name: new_cases, dtype: float64
30044 30051    8717.0
Name: new_cases, dtype: float64
30045 30052    11187.0
Name: new_cases, dtype: float64
30046 30053    10029.0
Name: new_cases, dtype: float64
30047 30054    11033.0
Name: new_cases, dtype: float64
30048 30055    9137.0
Name: new_cases, dtype: float64
30049 30056    9935.0
Name: new_cases, dtype: float64
30050 30057    6136.0
Name: new_cases, dtype: float64
30051 30058    8694.0
Name: new_cases, dtype: float64
30052 30059    9891.0
Name: new_cases, dtype: float64
30053 30060    9756.0
Name: new_cases, dtype: float64
30054 30061    8714.0
Name: new_cases, dtype: float64
30055 30062    7440.0
Name: new_cases, dtype: float64
30056 30063    5177.0
Name: new_cases, dtype: float64
30057 30064    6292.0
Name: new_cases, dtype: float64
30058 30065    9970.0
Name: new_cases, dtype: float64
30059 30066    8686.0
Name: new_cases, dtype: float64
30060 30067    8685.0
Name: new_cases, dtype: float64
30061 30068    8937.0
Name: new_cases, dtype: float64
30062 30069    7112.0
Name: new_cases, dtype: float64
30063 30070    6471.0
Name: new_cases, dtype: float64
30064 30071    5911.0
Name: new_cases, dtype: float64
30065 30072    6875.0
Name: new_cases, dtype: float64
30066 30073    7487.0
Name: new_cases, dtype: float64
30067 30074    7954.0
Name: new_cases, dtype: float64
30068 30075    7049.0
Name: new_cases, dtype: float64
30069 30076    7924.0
Name: new_cases, dtype: float64
30070 30077    6562.0
Name: new_cases, dtype: float64
30071 30078    7515.0
Name: new_cases, dtype: float64
30072 30079    8497.0
Name: new_cases, dtype: float64
30073 30080    9496.0
Name: new_cases, dtype: float64
30074 30081    10023.0
Name: new_cases, dtype: float64
30075 30082    9103.0
Name: new_cases, dtype: float64
30076 30083    8763.0
Name: new_cases, dtype: float64
30077 30084    8430.0
Name: new_cases, dtype: float64
30078 30085    7986.0
Name: new_cases, dtype: float64
30079 30086    9297.0
Name: new_cases, dtype: float64
30080 30087    9233.0
Name: new_cases, dtype: float64
30081 30088    9285.0
Name: new_cases, dtype: float64
30082 30089    9642.0
Name: new_cases, dtype: float64
30083 30090    8854.0
Name: new_cases, dtype: float64
30084 30091    5997.0
Name: new_cases, dtype: float64
30085 30092    7510.0
Name: new_cases, dtype: float64
30086 30093    7523.0
Name: new_cases, dtype: float64
30087 30094    7778.0
Name: new_cases, dtype: float64
30088 30095    8998.0
Name: new_cases, dtype: float64
30089 30096    8163.0
Name: new_cases, dtype: float64
30090 30097    8702.0
Name: new_cases, dtype: float64
30091 30098    8742.0
Name: new_cases, dtype: float64
30092 30099    10130.0
Name: new_cases, dtype: float64
30093 30100    11953.0
Name: new_cases, dtype: float64
30094 30101    12196.0
Name: new_cases, dtype: float64
30095 30102    13277.0
Name: new_cases, dtype: float64
30096 30103    13990.0
Name: new_cases, dtype: float64
30097 30104    11160.0
Name: new_cases, dtype: float64
30098 30105    10845.0
Name: new_cases, dtype: float64
30099 30106    12526.0
Name: new_cases, dtype: float64
30100 30107    14233.0
Name: new_cases, dtype: float64
30101 30108    14940.0
Name: new_cases, dtype: float64
30102 30109    14941.0
Name: new_cases, dtype: float64
30103 30110    10196.0
Name: new_cases, dtype: float64
30104 30111    9594.0
Name: new_cases, dtype: float64
30105 30112    9310.0
Name: new_cases, dtype: float64
30106 30113    11015.0
Name: new_cases, dtype: float64
30107 30114    11639.0
Name: new_cases, dtype: float64
30108 30115    16314.0
Name: new_cases, dtype: float64
30109 30116    12105.0
Name: new_cases, dtype: float64
30110 30117    11528.0
Name: new_cases, dtype: float64
30111 30118    9412.0
Name: new_cases, dtype: float64
30112 30119    10311.0
Name: new_cases, dtype: float64
30113 30120    16835.0
Name: new_cases, dtype: float64
30114 30121    16805.0
Name: new_cases, dtype: float64
30115 30122    17576.0
Name: new_cases, dtype: float64
30116 30123    18221.0
Name: new_cases, dtype: float64
30117 30124    15795.0
Name: new_cases, dtype: float64
30118 30125    15537.0
Name: new_cases, dtype: float64
30119 30126    15003.0
Name: new_cases, dtype: float64
30120 30127    14179.0
Name: new_cases, dtype: float64
30121 30128    15898.0
Name: new_cases, dtype: float64
30122 30129    17121.0
Name: new_cases, dtype: float64
30123 30130    21078.0
Name: new_cases, dtype: float64
30124 30131    20855.0
Name: new_cases, dtype: float64
30125 30132    17379.0
Name: new_cases, dtype: float64
30126 30133    14719.0
Name: new_cases, dtype: float64
30127 30134    15939.0
Name: new_cases, dtype: float64
30128 30135    17908.0
Name: new_cases, dtype: float64
30129 30136    15366.0
Name: new_cases, dtype: float64
30130 30137    15073.0
Name: new_cases, dtype: float64
30131 30138    15551.0
Name: new_cases, dtype: float64
30132 30139    12516.0
Name: new_cases, dtype: float64
30133 30140    12261.0
Name: new_cases, dtype: float64
30134 30141    13606.0
Name: new_cases, dtype: float64
30135 30142    13953.0
Name: new_cases, dtype: float64
30136 30143    12270.0
Name: new_cases, dtype: float64
30137 30144    10058.0
Name: new_cases, dtype: float64
30138 30145    9173.0
Name: new_cases, dtype: float64
30139 30146    8078.0
Name: new_cases, dtype: float64
30140 30147    9622.0
Name: new_cases, dtype: float64
30141 30148    10091.0
Name: new_cases, dtype: float64
30142 30149    11025.0
Name: new_cases, dtype: float64
30143 30150    9790.0
Name: new_cases, dtype: float64
30144 30151    7248.0
Name: new_cases, dtype: float64

30145 30152    8547.0
Name: new_cases, dtype: float64
30146 30153    6009.0
Name: new_cases, dtype: float64
30147 30154    4246.0
Name: new_cases, dtype: float64
30148 30155    5442.0
Name: new_cases, dtype: float64
30149 30156    6443.0
Name: new_cases, dtype: float64
30150 30157    6294.0
Name: new_cases, dtype: float64
30151 30158    5528.0
Name: new_cases, dtype: float64
30152 30159    4947.0
Name: new_cases, dtype: float64
30153 30160    4923.0
Name: new_cases, dtype: float64
30154 30161    3510.0
Name: new_cases, dtype: float64
30155 30162    4049.0
Name: new_cases, dtype: float64
30156 30163    5103.0
Name: new_cases, dtype: float64
30157 30164    4824.0
Name: new_cases, dtype: float64
30158 30165    4476.0
Name: new_cases, dtype: float64
30159 30166    5017.0
Name: new_cases, dtype: float64
30160 30167    4244.0
Name: new_cases, dtype: float64
30161 30168    3401.0
Name: new_cases, dtype: float64
30162 30169    3926.0
Name: new_cases, dtype: float64
30163 30170    3953.0
Name: new_cases, dtype: float64
30164 30171    3683.0
Name: new_cases, dtype: float64
30165 30172    3567.0
Name: new_cases, dtype: float64
30166 30173    3343.0
Name: new_cases, dtype: float64
30167 30174    3555.0
Name: new_cases, dtype: float64
30168 30175    3570.0
Name: new_cases, dtype: float64
30169 30176    4339.0
Name: new_cases, dtype: float64
30170 30177    3047.0
Name: new_cases, dtype: float64
30171 30178    3565.0
Name: new_cases, dtype: float64
30172 30179    3371.0
Name: new_cases, dtype: float64
30173 30180    3663.0
Name: new_cases, dtype: float64
30174 30181    3411.0
Name: new_cases, dtype: float64
30175 30182    2205.0
Name: new_cases, dtype: float64
30176 30183    3511.0
Name: new_cases, dtype: float64
30177 30184    3588.0
Name: new_cases, dtype: float64
30178 30185    4579.0
Name: new_cases, dtype: float64
30179 30186    4078.0
Name: new_cases, dtype: float64
30180 30187    4465.0
Name: new_cases, dtype: float64
30181 30188    4062.0
Name: new_cases, dtype: float64
30182 30189    2740.0
Name: new_cases, dtype: float64
30183 30190    3716.0
Name: new_cases, dtype: float64
30184 30191    4554.0
Name: new_cases, dtype: float64
30185 30192    5139.0
Name: new_cases, dtype: float64
30186 30193    5133.0
Name: new_cases, dtype: float64
30187 30194    6761.0
Name: new_cases, dtype: float64
30188 30195    6043.0
Name: new_cases, dtype: float64
30189 30196    5048.0
Name: new_cases, dtype: float64
30190 30197    4946.0
Name: new_cases, dtype: float64
30191 30198    5986.0
Name: new_cases, dtype: float64
30192 30199    6732.0
Name: new_cases, dtype: float64
30193 30200    7395.0
Name: new_cases, dtype: float64
30194 30201    8254.0
Name: new_cases, dtype: float64
30195 30202    7139.0
Name: new_cases, dtype: float64
30196 30203    7049.0
Name: new_cases, dtype: float64
30197 30204    7952.0
Name: new_cases, dtype: float64
30198 30205    8646.0
Name: new_cases, dtype: float64
30199 30206    11449.0
Name: new_cases, dtype: float64
30200 30207    10222.0
Name: new_cases, dtype: float64
30201 30208    9149.0
Name: new_cases, dtype: float64
30202 30209    9022.0
Name: new_cases, dtype: float64
30203 30210    10190.0
Name: new_cases, dtype: float64
30204 30211    11827.0
Name: new_cases, dtype: float64
30205 30212    11381.0
Name: new_cases, dtype: float64
30206 30213    12464.0
Name: new_cases, dtype: float64
30207 30214    12125.0
Name: new_cases, dtype: float64
30208 30215    14509.0
Name: new_cases, dtype: float64
30209 30216    17483.0
Name: new_cases, dtype: float64
30210 30217    16739.0
Name: new_cases, dtype: float64
30211 30218    16377.0
Name: new_cases, dtype: float64
30212 30219    16487.0
Name: new_cases, dtype: float64
30213 30220    16918.0
Name: new_cases, dtype: float64
30214 30221    16703.0
Name: new_cases, dtype: float64
30215 30222    16654.0
Name: new_cases, dtype: float64
30216 30223    16871.0
Name: new_cases, dtype: float64
30217 30224    14189.0
Name: new_cases, dtype: float64
30218 30225    16965.0
Name: new_cases, dtype: float64
30219 30226    17212.0
Name: new_cases, dtype: float64
30220 30227    19306.0
Name: new_cases, dtype: float64
30221 30228    19925.0
Name: new_cases, dtype: float64
30222 30229    16730.0
Name: new_cases, dtype: float64
30223 30230    17190.0
Name: new_cases, dtype: float64
30224 30231    12839.0
Name: new_cases, dtype: float64
30225 30232    17578.0
Name: new_cases, dtype: float64
30226 30233    19745.0
Name: new_cases, dtype: float64
30227 30234    17308.0
Name: new_cases, dtype: float64
30228 30235    17790.0
Name: new_cases, dtype: float64
30229 30236    18022.0
Name: new_cases, dtype: float64
30230 30237    15909.0
Name: new_cases, dtype: float64
30231 30238    11599.0
Name: new_cases, dtype: float64
30232 30239    14551.0
Name: new_cases, dtype: float64
30233 30240    14806.0
Name: new_cases, dtype: float64
30234 30241    16490.0
Name: new_cases, dtype: float64
30235 30242    17525.0
Name: new_cases, dtype: float64
30236 30243    16910.0
Name: new_cases, dtype: float64
30237 30244    17222.0
Name: new_cases, dtype: float64
30238 30245    12543.0
Name: new_cases, dtype: float64
30239 30246    16425.0
Name: new_cases, dtype: float64
30240 30247    16993.0
Name: new_cases, dtype: float64
30241 30248    19160.0
Name: new_cases, dtype: float64
30242 30249    16581.0
Name: new_cases, dtype: float64
30243 30250    18873.0
Name: new_cases, dtype: float64
30244 30251    15093.0
Name: new_cases, dtype: float64
30245 30252    12984.0
Name: new_cases, dtype: float64
30246 30253    13137.0
Name: new_cases, dtype: float64
30247 30254    16579.0
Name: new_cases, dtype: float64
30248 30255    16086.0
Name: new_cases, dtype: float64
30249 30256    14838.0
Name: new_cases, dtype: float64
30250 30257    18737.0
Name: new_cases, dtype: float64
30251 30258    21669.0
Name: new_cases, dtype: float64
30252 30259    16977.0
Name: new_cases, dtype: float64
30253 30260    21181.0
Name: new_cases, dtype: float64
30254 30261    23487.0
Name: new_cases, dtype: float64
30255 30262    25092.0
Name: new_cases, dtype: float64
30256 30263    23374.0
Name: new_cases, dtype: float64
30257 30264    20494.0
Name: new_cases, dtype: float64
30258 30265    20218.0
Name: new_cases, dtype: float64
30259 30266    23177.0
Name: new_cases, dtype: float64
30260 30267    25966.0
Name: new_cases, dtype: float64
30261 30268    27000.0
Name: new_cases, dtype: float64
30262 30269    28624.0
Name: new_cases, dtype: float64
30263 30270    30000.0
Name: new_cases, dtype: float64
30264 30271    28971.0
Name: new_cases, dtype: float64
30265 30272    24050.0
Name: new_cases, dtype: float64
30266 30273    21949.0
Name: new_cases, dtype: float64
30267 30274    18586.0
Name: new_cases, dtype: float64
30268 30275    21879.0
Name: new_cases, dtype: float64
30269 30276    31656.0
Name: new_cases, dtype: float64
30270 30277    29570.0
Name: new_cases, dtype: float64
30271 30278    29998.0
Name: new_cases, dtype: float64
30272 30279    28519.0
Name: new_cases, dtype: float64
30273 30280    24376.0
Name: new_cases, dtype: float64
30274 30281    24452.0
Name: new_cases, dtype: float64
30275 30282    27827.0
Name: new_cases, dtype: float64
30276 30283    29945.0
Name: new_cases, dtype: float64
30277 30284    28790.0
Name: new_cases, dtype: float64
30278 30285    28734.0
Name: new_cases, dtype: float64
30279 30286    27818.0
Name: new_cases, dtype: float64
30280 30287    23239.0
Name: new_cases, dtype: float64
30281 30288    28616.0
Name: new_cases, dtype: float64
30282 30289    29995.0
Name: new_cases, dtype: float64
30283 30290    32997.0
Name: new_cases, dtype: float64
30284 30291    32733.0
Name: new_cases, dtype: float64
30285 30292    33594.0
Name: new_cases, dtype: float64
30286 30293    32376.0
Name: new_cases, dtype: float64
30287 30294    28478.0
Name: new_cases, dtype: float64
30288 30295    25880.0
Name: new_cases, dtype: float64
30289 30296    27908.0
Name: new_cases, dtype: float64
30290 30297    28315.0
Name: new_cases, dtype: float64
30291 30298    28005.0
Name: new_cases, dtype: float64
30292 30299    26928.0
Name: new_cases, dtype: float64
30293 30300    26265.0
Name: new_cases, dtype: float64
30294 30301    25366.0
Name: new_cases, dtype: float64

30295 30302    26721.0
Name: new_cases, dtype: float64
30296 30303    24229.0
Name: new_cases, dtype: float64
30297 30304    23275.0
Name: new_cases, dtype: float64
30298 30305    21536.0
Name: new_cases, dtype: float64
30299 30306    20915.0
Name: new_cases, dtype: float64
30300 30307    19423.0
Name: new_cases, dtype: float64
30301 30308    18650.0
Name: new_cases, dtype: float64
30302 30309    17532.0
Name: new_cases, dtype: float64
30303 30310    17230.0
Name: new_cases, dtype: float64
30304 30311    18070.0
Name: new_cases, dtype: float64
30305 30312    17893.0
Name: new_cases, dtype: float64
30306 30313    19925.0
Name: new_cases, dtype: float64
30307 30314    18206.0
Name: new_cases, dtype: float64
30308 30315    16455.0
Name: new_cases, dtype: float64
30309 30316    12829.0
Name: new_cases, dtype: float64
30310 30317    11244.0
Name: new_cases, dtype: float64
30311 30318    12576.0
Name: new_cases, dtype: float64
30312 30319    13164.0
Name: new_cases, dtype: float64
30313 30320    11064.0
Name: new_cases, dtype: float64
30314 30321    11048.0
Name: new_cases, dtype: float64
30315 30322    8503.0
Name: new_cases, dtype: float64
30316 30323    11426.0
Name: new_cases, dtype: float64
30317 30324    9364.0
Name: new_cases, dtype: float64
30318 30325    9690.0
Name: new_cases, dtype: float64
30319 30326    9462.0
Name: new_cases, dtype: float64
30320 30327    9029.0
Name: new_cases, dtype: float64
30321 30328    9094.0
Name: new_cases, dtype: float64
30322 30329    6636.0
Name: new_cases, dtype: float64
30323 30330    6929.0
Name: new_cases, dtype: float64
30324 30331    7084.0
Name: new_cases, dtype: float64
30325 30332    6540.0
Name: new_cases, dtype: float64
30326 30333    6980.0
Name: new_cases, dtype: float64
30327 30334    6051.0
Name: new_cases, dtype: float64
30328 30335    4350.0
Name: new_cases, dtype: float64
30329 30336    4023.0
Name: new_cases, dtype: float64
30330 30337    3948.0
Name: new_cases, dtype: float64
30331 30338    5368.0
Name: new_cases, dtype: float64
30332 30339    4272.0
Name: new_cases, dtype: float64
30333 30340    4027.0
Name: new_cases, dtype: float64
30334 30341    4007.0
Name: new_cases, dtype: float64
30335 30342    3132.0
Name: new_cases, dtype: float64
30336 30343    3161.0
Name: new_cases, dtype: float64
30337 30344    3247.0
Name: new_cases, dtype: float64
30338 30345    3154.0
Name: new_cases, dtype: float64
30339 30346    3193.0
Name: new_cases, dtype: float64
30340 30347    3416.0
Name: new_cases, dtype: float64
30341 30348    2965.0
Name: new_cases, dtype: float64
30342 30349    2640.0
Name: new_cases, dtype: float64
30343 30350    2698.0
Name: new_cases, dtype: float64
30344 30351    2467.0
Name: new_cases, dtype: float64
30345 30352    2448.0
Name: new_cases, dtype: float64
30346 30353    1935.0
Name: new_cases, dtype: float64
30347 30354    2078.0
Name: new_cases, dtype: float64
30348 30355    2141.0
Name: new_cases, dtype: float64
30349 30356    1954.0
Name: new_cases, dtype: float64
30350 30357    2006.0
Name: new_cases, dtype: float64
30351 30358    1822.0
Name: new_cases, dtype: float64
30352 30359    1996.0
Name: new_cases, dtype: float64
30353 30360    1949.0
Name: new_cases, dtype: float64
30354 30361    1850.0
Name: new_cases, dtype: float64
30355 30362    2099.0
Name: new_cases, dtype: float64
30356 30363    1669.0
Name: new_cases, dtype: float64
30357 30364    1124.0
Name: new_cases, dtype: float64
30358 30365    1637.0
Name: new_cases, dtype: float64
30359 30366    1787.0
Name: new_cases, dtype: float64
30360 30367    1803.0
Name: new_cases, dtype: float64
30361 30368    1772.0
Name: new_cases, dtype: float64
30362 30369    1806.0
Name: new_cases, dtype: float64
30363 30370    1671.0
Name: new_cases, dtype: float64
30364 30371    1314.0
Name: new_cases, dtype: float64
30365 30372    1435.0
Name: new_cases, dtype: float64
30366 30373    1570.0
Name: new_cases, dtype: float64
30367 30374    1484.0
Name: new_cases, dtype: float64
30368 30375    1544.0
Name: new_cases, dtype: float64
30369 30376    1655.0
Name: new_cases, dtype: float64
30370 30377    1813.0
Name: new_cases, dtype: float64
30371 30378    1185.0
Name: new_cases, dtype: float64
30372 30379    1373.0
Name: new_cases, dtype: float64
30373 30380    1581.0
Name: new_cases, dtype: float64
30374 30381    1608.0
Name: new_cases, dtype: float64
30375 30382    1702.0
Name: new_cases, dtype: float64
30376 30383    1740.0
Name: new_cases, dtype: float64
30377 30384    1422.0
Name: new_cases, dtype: float64
30378 30385    1015.0
Name: new_cases, dtype: float64
30379 30386    1686.0
Name: new_cases, dtype: float64
30380 30387    1472.0
Name: new_cases, dtype: float64
30381 30388    1429.0
Name: new_cases, dtype: float64
30382 30389    1867.0
Name: new_cases, dtype: float64
30383 30390    1497.0
Name: new_cases, dtype: float64
30384 30391    1413.0
Name: new_cases, dtype: float64
30385 30392    1189.0
Name: new_cases, dtype: float64
30386 30393    1211.0
Name: new_cases, dtype: float64
30387 30394    1393.0
Name: new_cases, dtype: float64
30388 30395    1677.0
Name: new_cases, dtype: float64
30389 30396    1607.0
Name: new_cases, dtype: float64
30390 30397    1587.0
Name: new_cases, dtype: float64
30391 30398    1518.0
Name: new_cases, dtype: float64
30392 30399    1089.0
Name: new_cases, dtype: float64
30393 30400    1075.0
Name: new_cases, dtype: float64
30394 30401    1256.0
Name: new_cases, dtype: float64
30395 30402    1387.0
Name: new_cases, dtype: float64
30396 30403    1646.0
Name: new_cases, dtype: float64
30397 30404    1544.0
Name: new_cases, dtype: float64
30398 30405    1299.0
Name: new_cases, dtype: float64
30399 30406    1043.0
Name: new_cases, dtype: float64
30400 30407    952.0
Name: new_cases, dtype: float64
30401 30408    1224.0
Name: new_cases, dtype: float64
30402 30409    1498.0
Name: new_cases, dtype: float64
30403 30410    1772.0
Name: new_cases, dtype: float64
30404 30411    1660.0
Name: new_cases, dtype: float64
30405 30412    1369.0
Name: new_cases, dtype: float64
30406 30413    1536.0
Name: new_cases, dtype: float64
30407 30414    1428.0
Name: new_cases, dtype: float64
30408 30415    1680.0
Name: new_cases, dtype: float64
30409 30416    1750.0
Name: new_cases, dtype: float64
30410 30417    1604.0
Name: new_cases, dtype: float64
30411 30418    1629.0
Name: new_cases, dtype: float64
30412 30419    1710.0
Name: new_cases, dtype: float64
30413 30420    1590.0
Name: new_cases, dtype: float64
30414 30421    1425.0
Name: new_cases, dtype: float64
30415 30422    1697.0
Name: new_cases, dtype: float64
30416 30423    1908.0
Name: new_cases, dtype: float64
30417 30424    1975.0
Name: new_cases, dtype: float64
30418 30425    1999.0
Name: new_cases, dtype: float64
30419 30426    2061.0
Name: new_cases, dtype: float64
30420 30427    1917.0
Name: new_cases, dtype: float64
30421 30428    2199.0
Name: new_cases, dtype: float64
30422 30429    2461.0
Name: new_cases, dtype: float64
30423 30430    2644.0
Name: new_cases, dtype: float64
30424 30431    2559.0
Name: new_cases, dtype: float64
30425 30432    2513.0
Name: new_cases, dtype: float64
30426 30433    2610.0
Name: new_cases, dtype: float64
30427 30434    2321.0
Name: new_cases, dtype: float64
30428 30435    2021.0
Name: new_cases, dtype: float64
30429 30436    2257.0
Name: new_cases, dtype: float64
30430 30437    2121.0
Name: new_cases, dtype: float64
30431 30438    2157.0
Name: new_cases, dtype: float64
30432 30439    2590.0
Name: new_cases, dtype: float64
30433 30440    2649.0
Name: new_cases, dtype: float64
30434 30441    2194.0
Name: new_cases, dtype: float64
30435 30442    2478.0
Name: new_cases, dtype: float64
30436 30443    2520.0
Name: new_cases, dtype: float64
30437 30444    2644.0
Name: new_cases, dtype: float64
30438 30445    2660.0
Name: new_cases, dtype: float64
30439 30446    2620.0
Name: new_cases, dtype: float64
30440 30447    2196.0
Name: new_cases, dtype: float64
30441 30448    1975.0
Name: new_cases, dtype: float64
30442 30449    2296.0
Name: new_cases, dtype: float64
30443 30450    2173.0
Name: new_cases, dtype: float64
30444 30451    2262.0
Name: new_cases, dtype: float64
30445 30452    2299.0
Name: new_cases, dtype: float64
30446 30453    2609.0
Name: new_cases, dtype: float64
30447 30454    2077.0
Name: new_cases, dtype: float64
30448 30455    1698.0
Name: new_cases, dtype: float64
30449 30456    1704.0
Name: new_cases, dtype: float64

30450 30457    1915.0
Name: new_cases, dtype: float64
30451 30458    1627.0
Name: new_cases, dtype: float64
30452 30459    1687.0
Name: new_cases, dtype: float64
30453 30460    1813.0
Name: new_cases, dtype: float64
30454 30461    2026.0
Name: new_cases, dtype: float64
30455 30462    2287.0
Name: new_cases, dtype: float64
30456 30463    1859.0
Name: new_cases, dtype: float64
30457 30464    2066.0
Name: new_cases, dtype: float64
30458 30465    1720.0
Name: new_cases, dtype: float64
30459 30466    1803.0
Name: new_cases, dtype: float64
30460 30467    2016.0
Name: new_cases, dtype: float64
30461 30468    2038.0
Name: new_cases, dtype: float64
30462 30469    1699.0
Name: new_cases, dtype: float64
30463 30470    1766.0
Name: new_cases, dtype: float64
30464 30471    1931.0
Name: new_cases, dtype: float64
30465 30472    2475.0
Name: new_cases, dtype: float64
30466 30473    3060.0
Name: new_cases, dtype: float64
30467 30474    3414.0
Name: new_cases, dtype: float64
30468 30475    3022.0
Name: new_cases, dtype: float64
30469 30476    3281.0
Name: new_cases, dtype: float64
30470 30477    4306.0
Name: new_cases, dtype: float64
30471 30478    6326.0
Name: new_cases, dtype: float64
30472 30479    8436.0
Name: new_cases, dtype: float64
30473 30480    10401.0
Name: new_cases, dtype: float64
30474 30481    12415.0
Name: new_cases, dtype: float64
30475 30482    11318.0
Name: new_cases, dtype: float64
30476 30483    9848.0
Name: new_cases, dtype: float64
30477 30484    12353.0
Name: new_cases, dtype: float64
30478 30485    16259.0
Name: new_cases, dtype: float64
30479 30486    23039.0
Name: new_cases, dtype: float64
30480 30487    26190.0
Name: new_cases, dtype: float64
30481 30488    31170.0
Name: new_cases, dtype: float64
30482 Series([], Name: new_cases, dtype: float64)
30483 Series([], Name: new_cases, dtype: float64)
30484 Series([], Name: new_cases, dtype: float64)
30485 Series([], Name: new_cases, dtype: float64)
30486 Series([], Name: new_cases, dtype: float64)
30487 Series([], Name: new_cases, dtype: float64)
30488 Series([], Name: new_cases, dtype: float64)
33349 33356    2.0
Name: new_cases, dtype: float64
33350 33357    1.0
Name: new_cases, dtype: float64
33351 33358    0.0
Name: new_cases, dtype: float64
33352 33359    1.0
Name: new_cases, dtype: float64
33353 33360    1.0
Name: new_cases, dtype: float64
33354 33361    0.0
Name: new_cases, dtype: float64
33355 33362    0.0
Name: new_cases, dtype: float64
33356 33363    2.0
Name: new_cases, dtype: float64
33357 33364    5.0
Name: new_cases, dtype: float64
33358 33365    0.0
Name: new_cases, dtype: float64
33359 33366    13.0
Name: new_cases, dtype: float64
33360 33367    6.0
Name: new_cases, dtype: float64
33361 33368    11.0
Name: new_cases, dtype: float64
33362 33369    8.0
Name: new_cases, dtype: float64
33363 33370    8.0
Name: new_cases, dtype: float64
33364 33371    16.0
Name: new_cases, dtype: float64
33365 33372    24.0
Name: new_cases, dtype: float64
33366 33373    23.0
Name: new_cases, dtype: float64
33367 33374    78.0
Name: new_cases, dtype: float64
33368 33375    48.0
Name: new_cases, dtype: float64
33369 33376    61.0
Name: new_cases, dtype: float64
33370 33377    67.0
Name: new_cases, dtype: float64
33371 33378    60.0
Name: new_cases, dtype: float64
33372 33379    53.0
Name: new_cases, dtype: float64
33373 33380    91.0
Name: new_cases, dtype: float64
33374 33381    71.0
Name: new_cases, dtype: float64
33375 33382    56.0
Name: new_cases, dtype: float64
33376 33383    77.0
Name: new_cases, dtype: float64
33377 33384    77.0
Name: new_cases, dtype: float64
33378 33385    96.0
Name: new_cases, dtype: float64
33379 33386    48.0
Name: new_cases, dtype: float64
33380 33387    68.0
Name: new_cases, dtype: float64
33381 33388    47.0
Name: new_cases, dtype: float64
33382 33389    56.0
Name: new_cases, dtype: float64
33383 33390    40.0
Name: new_cases, dtype: float64
33384 33391    60.0
Name: new_cases, dtype: float64
33385 33392    61.0
Name: new_cases, dtype: float64
33386 33393    64.0
Name: new_cases, dtype: float64
33387 33394    88.0
Name: new_cases, dtype: float64
33388 33395    39.0
Name: new_cases, dtype: float64
33389 33396    66.0
Name: new_cases, dtype: float64
33390 33397    50.0
Name: new_cases, dtype: float64
33391 33398    54.0
Name: new_cases, dtype: float64
33392 33399    37.0
Name: new_cases, dtype: float64
33393 33400    50.0
Name: new_cases, dtype: float64
33394 33401    23.0
Name: new_cases, dtype: float64
33395 33402    18.0
Name: new_cases, dtype: float64
33396 33403    39.0
Name: new_cases, dtype: float64
33397 33404    10.0
Name: new_cases, dtype: float64
33398 33405    27.0
Name: new_cases, dtype: float64
33399 33406    42.0
Name: new_cases, dtype: float64
33400 33407    31.0
Name: new_cases, dtype: float64
33401 33408    28.0
Name: new_cases, dtype: float64
33402 33409    7.0
Name: new_cases, dtype: float64
33403 33410    14.0
Name: new_cases, dtype: float64
33404 33411    9.0
Name: new_cases, dtype: float64
33405 33412    8.0
Name: new_cases, dtype: float64
33406 33413    15.0
Name: new_cases, dtype: float64
33407 33414    14.0
Name: new_cases, dtype: float64
33408 33415    9.0
Name: new_cases, dtype: float64
33409 33416    3.0
Name: new_cases, dtype: float64
33410 33417    8.0
Name: new_cases, dtype: float64
33411 33418    5.0
Name: new_cases, dtype: float64
33412 33419    11.0
Name: new_cases, dtype: float64
33413 33420    7.0
Name: new_cases, dtype: float64
33414 33421    6.0
Name: new_cases, dtype: float64
33415 33422    36.0
Name: new_cases, dtype: float64
33416 33423    15.0
Name: new_cases, dtype: float64
33417 33424    11.0
Name: new_cases, dtype: float64
33418 33425    9.0
Name: new_cases, dtype: float64
33419 33426    11.0
Name: new_cases, dtype: float64
33420 33427    6.0
Name: new_cases, dtype: float64
33421 33428    8.0
Name: new_cases, dtype: float64
33422 33429    1.0
Name: new_cases, dtype: float64
33423 33430    2.0
Name: new_cases, dtype: float64
33424 33431    2.0
Name: new_cases, dtype: float64
33425 33432    2.0
Name: new_cases, dtype: float64
33426 33433    4.0
Name: new_cases, dtype: float64
33427 33434    2.0
Name: new_cases, dtype: float64
33428 33435    3.0
Name: new_cases, dtype: float64
33429 33436    6.0
Name: new_cases, dtype: float64
33430 33437    0.0
Name: new_cases, dtype: float64
33431 33438    1.0
Name: new_cases, dtype: float64
33432 33439    0.0
Name: new_cases, dtype: float64
33433 33440    0.0
Name: new_cases, dtype: float64
33434 33441    0.0
Name: new_cases, dtype: float64
33435 33442    1.0
Name: new_cases, dtype: float64
33436 33443    0.0
Name: new_cases, dtype: float64
33437 33444    1.0
Name: new_cases, dtype: float64
33438 33445    0.0
Name: new_cases, dtype: float64
33439 33446    0.0
Name: new_cases, dtype: float64
33440 33447    0.0
Name: new_cases, dtype: float64
33441 33448    0.0
Name: new_cases, dtype: float64
33442 33449    1.0
Name: new_cases, dtype: float64
33443 33450    0.0
Name: new_cases, dtype: float64
33444 33451    0.0
Name: new_cases, dtype: float64
33445 33452    0.0
Name: new_cases, dtype: float64
33446 33453    0.0
Name: new_cases, dtype: float64
33447 33454    0.0
Name: new_cases, dtype: float64
33448 33455    2.0
Name: new_cases, dtype: float64
33449 33456    0.0
Name: new_cases, dtype: float64
33450 33457    0.0
Name: new_cases, dtype: float64
33451 33458    2.0
Name: new_cases, dtype: float64
33452 33459    1.0
Name: new_cases, dtype: float64
33453 33460    2.0
Name: new_cases, dtype: float64
33454 33461    1.0
Name: new_cases, dtype: float64
33455 33462    3.0
Name: new_cases, dtype: float64
33456 33463    11.0
Name: new_cases, dtype: float64
33457 33464    11.0
Name: new_cases, dtype: float64
33458 33465    19.0
Name: new_cases, dtype: float64
33459 33466    18.0
Name: new_cases, dtype: float64
33460 33467    19.0
Name: new_cases, dtype: float64
33461 33468    30.0
Name: new_cases, dtype: float64
33462 33469    22.0
Name: new_cases, dtype: float64
33463 33470    95.0
Name: new_cases, dtype: float64
33464 33471    56.0
Name: new_cases, dtype: float64
33465 33472    85.0
Name: new_cases, dtype: float64
33466 33473    67.0
Name: new_cases, dtype: float64
33467 33474    34.0
Name: new_cases, dtype: float64
33468 33475    52.0
Name: new_cases, dtype: float64
33469 33476    54.0
Name: new_cases, dtype: float64
33470 33477    81.0
Name: new_cases, dtype: float64
33471 33478    96.0
Name: new_cases, dtype: float64
33472 33479    86.0
Name: new_cases, dtype: float64
33473 33480    57.0
Name: new_cases, dtype: float64
33474 33481    69.0
Name: new_cases, dtype: float64
33475 33482    52.0
Name: new_cases, dtype: float64
33476 33483    53.0
Name: new_cases, dtype: float64
33477 33484    91.0
Name: new_cases, dtype: float64
33478 33485    116.0
Name: new_cases, dtype: float64

33479 33486    140.0
Name: new_cases, dtype: float64
33480 33487    50.0
Name: new_cases, dtype: float64
33481 33488    53.0
Name: new_cases, dtype: float64
33482 33489    52.0
Name: new_cases, dtype: float64
33483 33490    126.0
Name: new_cases, dtype: float64
33484 33491    86.0
Name: new_cases, dtype: float64
33485 33492    98.0
Name: new_cases, dtype: float64
33486 33493    116.0
Name: new_cases, dtype: float64
33487 33494    92.0
Name: new_cases, dtype: float64
33488 33495    25.0
Name: new_cases, dtype: float64
33489 33496    52.0
Name: new_cases, dtype: float64
33490 33497    108.0
Name: new_cases, dtype: float64
33491 33498    104.0
Name: new_cases, dtype: float64
33492 33499    81.0
Name: new_cases, dtype: float64
33493 33500    77.0
Name: new_cases, dtype: float64
33494 33501    65.0
Name: new_cases, dtype: float64
33495 33502    24.0
Name: new_cases, dtype: float64
33496 33503    42.0
Name: new_cases, dtype: float64
33497 33504    70.0
Name: new_cases, dtype: float64
33498 33505    78.0
Name: new_cases, dtype: float64
33499 33506    68.0
Name: new_cases, dtype: float64
33500 33507    85.0
Name: new_cases, dtype: float64
33501 33508    36.0
Name: new_cases, dtype: float64
33502 33509    34.0
Name: new_cases, dtype: float64
33503 33510    24.0
Name: new_cases, dtype: float64
33504 33511    58.0
Name: new_cases, dtype: float64
33505 33512    28.0
Name: new_cases, dtype: float64
33506 33513    62.0
Name: new_cases, dtype: float64
33507 33514    77.0
Name: new_cases, dtype: float64
33508 33515    61.0
Name: new_cases, dtype: float64
33509 33516    45.0
Name: new_cases, dtype: float64
33510 33517    91.0
Name: new_cases, dtype: float64
33511 33518    130.0
Name: new_cases, dtype: float64
33512 33519    180.0
Name: new_cases, dtype: float64
33513 33520    208.0
Name: new_cases, dtype: float64
33514 33521    162.0
Name: new_cases, dtype: float64
33515 33522    151.0
Name: new_cases, dtype: float64
33516 33523    85.0
Name: new_cases, dtype: float64
33517 33524    199.0
Name: new_cases, dtype: float64
33518 33525    219.0
Name: new_cases, dtype: float64
33519 33526    255.0
Name: new_cases, dtype: float64
33520 33527    265.0
Name: new_cases, dtype: float64
33521 33528    306.0
Name: new_cases, dtype: float64
33522 33529    275.0
Name: new_cases, dtype: float64
33523 33530    136.0
Name: new_cases, dtype: float64
33524 33531    219.0
Name: new_cases, dtype: float64
33525 33532    358.0
Name: new_cases, dtype: float64
33526 33533    304.0
Name: new_cases, dtype: float64
33527 33534    357.0
Name: new_cases, dtype: float64
33528 33535    312.0
Name: new_cases, dtype: float64
33529 33536    262.0
Name: new_cases, dtype: float64
33530 33537    146.0
Name: new_cases, dtype: float64
33531 33538    145.0
Name: new_cases, dtype: float64
33532 33539    311.0
Name: new_cases, dtype: float64
33533 33540    369.0
Name: new_cases, dtype: float64
33534 33541    334.0
Name: new_cases, dtype: float64
33535 33542    311.0
Name: new_cases, dtype: float64
33536 33543    225.0
Name: new_cases, dtype: float64
33537 33544    117.0
Name: new_cases, dtype: float64
33538 33545    204.0
Name: new_cases, dtype: float64
33539 33546    341.0
Name: new_cases, dtype: float64
33540 33547    291.0
Name: new_cases, dtype: float64
33541 33548    190.0
Name: new_cases, dtype: float64
33542 33549    261.0
Name: new_cases, dtype: float64
33543 33550    165.0
Name: new_cases, dtype: float64
33544 33551    65.0
Name: new_cases, dtype: float64
33545 33552    151.0
Name: new_cases, dtype: float64
33546 33553    280.0
Name: new_cases, dtype: float64
33547 33554    250.0
Name: new_cases, dtype: float64
33548 33555    234.0
Name: new_cases, dtype: float64
33549 33556    212.0
Name: new_cases, dtype: float64
33550 33557    197.0
Name: new_cases, dtype: float64
33551 33558    70.0
Name: new_cases, dtype: float64
33552 33559    144.0
Name: new_cases, dtype: float64
33553 33560    204.0
Name: new_cases, dtype: float64
33554 33561    232.0
Name: new_cases, dtype: float64
33555 33562    223.0
Name: new_cases, dtype: float64
33556 33563    212.0
Name: new_cases, dtype: float64
33557 33564    190.0
Name: new_cases, dtype: float64
33558 33565    48.0
Name: new_cases, dtype: float64
33559 33566    135.0
Name: new_cases, dtype: float64
33560 33567    213.0
Name: new_cases, dtype: float64
33561 33568    234.0
Name: new_cases, dtype: float64
33562 33569    333.0
Name: new_cases, dtype: float64
33563 33570    241.0
Name: new_cases, dtype: float64
33564 33571    258.0
Name: new_cases, dtype: float64
33565 33572    138.0
Name: new_cases, dtype: float64
33566 33573    287.0
Name: new_cases, dtype: float64
33567 33574    363.0
Name: new_cases, dtype: float64
33568 33575    542.0
Name: new_cases, dtype: float64
33569 33576    457.0
Name: new_cases, dtype: float64
33570 33577    486.0
Name: new_cases, dtype: float64
33571 33578    508.0
Name: new_cases, dtype: float64
33572 33579    181.0
Name: new_cases, dtype: float64
33573 33580    372.0
Name: new_cases, dtype: float64
33574 33581    748.0
Name: new_cases, dtype: float64
33575 33582    793.0
Name: new_cases, dtype: float64
33576 33583    1131.0
Name: new_cases, dtype: float64
33577 33584    1096.0
Name: new_cases, dtype: float64
33578 33585    819.0
Name: new_cases, dtype: float64
33579 33586    393.0
Name: new_cases, dtype: float64
33580 33587    890.0
Name: new_cases, dtype: float64
33581 33588    1424.0
Name: new_cases, dtype: float64
33582 33589    1563.0
Name: new_cases, dtype: float64
33583 33590    1867.0
Name: new_cases, dtype: float64
33584 33591    2242.0
Name: new_cases, dtype: float64
33585 33592    2421.0
Name: new_cases, dtype: float64
33586 33593    828.0
Name: new_cases, dtype: float64
33587 33594    1413.0
Name: new_cases, dtype: float64
33588 33595    2378.0
Name: new_cases, dtype: float64
33589 33596    2776.0
Name: new_cases, dtype: float64
33590 33597    2772.0
Name: new_cases, dtype: float64
33591 33598    2769.0
Name: new_cases, dtype: float64
33592 33599    2179.0
Name: new_cases, dtype: float64
33593 33600    1165.0
Name: new_cases, dtype: float64
33594 33601    1427.0
Name: new_cases, dtype: float64
33595 33602    2480.0
Name: new_cases, dtype: float64
33596 33603    2848.0
Name: new_cases, dtype: float64
33597 33604    2890.0
Name: new_cases, dtype: float64
33598 33605    2399.0
Name: new_cases, dtype: float64
33599 33606    2543.0
Name: new_cases, dtype: float64
33600 33607    1529.0
Name: new_cases, dtype: float64
33601 33608    1467.0
Name: new_cases, dtype: float64
33602 33609    2597.0
Name: new_cases, dtype: float64
33603 33610    3082.0
Name: new_cases, dtype: float64
33604 33611    3056.0
Name: new_cases, dtype: float64
33605 33612    2866.0
Name: new_cases, dtype: float64
33606 33613    2362.0
Name: new_cases, dtype: float64
33607 33614    1313.0
Name: new_cases, dtype: float64
33608 33615    1945.0
Name: new_cases, dtype: float64
33609 33616    3251.0
Name: new_cases, dtype: float64
33610 33617    3164.0
Name: new_cases, dtype: float64
33611 33618    2958.0
Name: new_cases, dtype: float64
33612 33619    3573.0
Name: new_cases, dtype: float64
33613 33620    3308.0
Name: new_cases, dtype: float64
33614 33621    1973.0
Name: new_cases, dtype: float64
33615 33622    2323.0
Name: new_cases, dtype: float64
33616 33623    3603.0
Name: new_cases, dtype: float64
33617 33624    4009.0
Name: new_cases, dtype: float64
33618 33625    4080.0
Name: new_cases, dtype: float64
33619 33626    3987.0
Name: new_cases, dtype: float64
33620 33627    2919.0
Name: new_cases, dtype: float64
33621 33628    1830.0
Name: new_cases, dtype: float64
33622 33629    2900.0
Name: new_cases, dtype: float64
33623 33630    3539.0
Name: new_cases, dtype: float64
33624 33631    4534.0
Name: new_cases, dtype: float64
33625 33632    3955.0
Name: new_cases, dtype: float64
33626 33633    4084.0
Name: new_cases, dtype: float64
33627 33634    2899.0
Name: new_cases, dtype: float64
33628 33635    1886.0
Name: new_cases, dtype: float64
33629 33636    2613.0
Name: new_cases, dtype: float64
33630 33637    4520.0
Name: new_cases, dtype: float64
33631 33638    4620.0
Name: new_cases, dtype: float64
33632 33639    4396.0
Name: new_cases, dtype: float64
33633 33640    4135.0
Name: new_cases, dtype: float64
33634 33641    3363.0
Name: new_cases, dtype: float64
33635 33642    1472.0
Name: new_cases, dtype: float64
33636 33643    2360.0
Name: new_cases, dtype: float64
33637 33644    3327.0
Name: new_cases, dtype: float64
33638 33645    3918.0
Name: new_cases, dtype: float64
33639 33646    3272.0
Name: new_cases, dtype: float64
33640 33647    2752.0
Name: new_cases, dtype: float64

33641 33648    1975.0
Name: new_cases, dtype: float64
33642 33649    766.0
Name: new_cases, dtype: float64
33643 33650    1595.0
Name: new_cases, dtype: float64
33644 33651    2763.0
Name: new_cases, dtype: float64
33645 33652    2233.0
Name: new_cases, dtype: float64
33646 33653    1643.0
Name: new_cases, dtype: float64
33647 33654    350.0
Name: new_cases, dtype: float64
33648 33655    618.0
Name: new_cases, dtype: float64
33649 33656    316.0
Name: new_cases, dtype: float64
33650 33657    1350.0
Name: new_cases, dtype: float64
33651 33658    1850.0
Name: new_cases, dtype: float64
33652 33659    2391.0
Name: new_cases, dtype: float64
33653 33660    1170.0
Name: new_cases, dtype: float64
33654 33661    255.0
Name: new_cases, dtype: float64
33655 33662    696.0
Name: new_cases, dtype: float64
33656 33663    361.0
Name: new_cases, dtype: float64
33657 33664    1071.0
Name: new_cases, dtype: float64
33658 33665    1896.0
Name: new_cases, dtype: float64
33659 33666    562.0
Name: new_cases, dtype: float64
33660 33667    1098.0
Name: new_cases, dtype: float64
33661 33668    1401.0
Name: new_cases, dtype: float64
33662 33669    646.0
Name: new_cases, dtype: float64
33663 33670    230.0
Name: new_cases, dtype: float64
33664 33671    759.0
Name: new_cases, dtype: float64
33665 33672    1135.0
Name: new_cases, dtype: float64
33666 33673    980.0
Name: new_cases, dtype: float64
33667 33674    715.0
Name: new_cases, dtype: float64
33668 33675    763.0
Name: new_cases, dtype: float64
33669 33676    379.0
Name: new_cases, dtype: float64
33670 33677    174.0
Name: new_cases, dtype: float64
33671 33678    520.0
Name: new_cases, dtype: float64
33672 33679    902.0
Name: new_cases, dtype: float64
33673 33680    776.0
Name: new_cases, dtype: float64
33674 33681    643.0
Name: new_cases, dtype: float64
33675 33682    599.0
Name: new_cases, dtype: float64
33676 33683    352.0
Name: new_cases, dtype: float64
33677 33684    134.0
Name: new_cases, dtype: float64
33678 33685    448.0
Name: new_cases, dtype: float64
33679 33686    857.0
Name: new_cases, dtype: float64
33680 33687    619.0
Name: new_cases, dtype: float64
33681 33688    561.0
Name: new_cases, dtype: float64
33682 33689    551.0
Name: new_cases, dtype: float64
33683 33690    336.0
Name: new_cases, dtype: float64
33684 33691    94.0
Name: new_cases, dtype: float64
33685 33692    387.0
Name: new_cases, dtype: float64
33686 33693    730.0
Name: new_cases, dtype: float64
33687 33694    516.0
Name: new_cases, dtype: float64
33688 33695    549.0
Name: new_cases, dtype: float64
33689 33696    424.0
Name: new_cases, dtype: float64
33690 33697    276.0
Name: new_cases, dtype: float64
33691 33698    71.0
Name: new_cases, dtype: float64
33692 33699    283.0
Name: new_cases, dtype: float64
33693 33700    577.0
Name: new_cases, dtype: float64
33694 33701    376.0
Name: new_cases, dtype: float64
33695 33702    371.0
Name: new_cases, dtype: float64
33696 33703    379.0
Name: new_cases, dtype: float64
33697 33704    198.0
Name: new_cases, dtype: float64
33698 33705    68.0
Name: new_cases, dtype: float64
33699 33706    274.0
Name: new_cases, dtype: float64
33700 33707    502.0
Name: new_cases, dtype: float64
33701 33708    365.0
Name: new_cases, dtype: float64
33702 33709    388.0
Name: new_cases, dtype: float64
33703 33710    431.0
Name: new_cases, dtype: float64
33704 33711    260.0
Name: new_cases, dtype: float64
33705 33712    72.0
Name: new_cases, dtype: float64
33706 33713    343.0
Name: new_cases, dtype: float64
33707 33714    688.0
Name: new_cases, dtype: float64
33708 33715    544.0
Name: new_cases, dtype: float64
33709 33716    505.0
Name: new_cases, dtype: float64
33710 33717    520.0
Name: new_cases, dtype: float64
33711 33718    356.0
Name: new_cases, dtype: float64
33712 33719    91.0
Name: new_cases, dtype: float64
33713 33720    394.0
Name: new_cases, dtype: float64
33714 33721    747.0
Name: new_cases, dtype: float64
33715 33722    667.0
Name: new_cases, dtype: float64
33716 33723    590.0
Name: new_cases, dtype: float64
33717 33724    658.0
Name: new_cases, dtype: float64
33718 33725    394.0
Name: new_cases, dtype: float64
33719 33726    94.0
Name: new_cases, dtype: float64
33720 33727    491.0
Name: new_cases, dtype: float64
33721 33728    962.0
Name: new_cases, dtype: float64
33722 33729    777.0
Name: new_cases, dtype: float64
33723 33730    823.0
Name: new_cases, dtype: float64
33724 33731    823.0
Name: new_cases, dtype: float64
33725 33732    561.0
Name: new_cases, dtype: float64
33726 33733    129.0
Name: new_cases, dtype: float64
33727 33734    691.0
Name: new_cases, dtype: float64
33728 33735    1445.0
Name: new_cases, dtype: float64
33729 33736    1197.0
Name: new_cases, dtype: float64
33730 33737    1112.0
Name: new_cases, dtype: float64
33731 33738    1186.0
Name: new_cases, dtype: float64
33732 33739    834.0
Name: new_cases, dtype: float64
33733 33740    150.0
Name: new_cases, dtype: float64
33734 33741    956.0
Name: new_cases, dtype: float64
33735 33742    1891.0
Name: new_cases, dtype: float64
33736 33743    1673.0
Name: new_cases, dtype: float64
33737 33744    1802.0
Name: new_cases, dtype: float64
33738 33745    1790.0
Name: new_cases, dtype: float64
33739 33746    1321.0
Name: new_cases, dtype: float64
33740 33747    300.0
Name: new_cases, dtype: float64
33741 33748    1487.0
Name: new_cases, dtype: float64
33742 33749    2623.0
Name: new_cases, dtype: float64
33743 33750    2422.0
Name: new_cases, dtype: float64
33744 33751    2362.0
Name: new_cases, dtype: float64
33745 33752    2234.0
Name: new_cases, dtype: float64
33746 33753    1376.0
Name: new_cases, dtype: float64
33747 33754    138.0
Name: new_cases, dtype: float64
33748 33755    735.0
Name: new_cases, dtype: float64
33749 33756    1649.0
Name: new_cases, dtype: float64
33750 33757    3217.0
Name: new_cases, dtype: float64
33751 33758    2599.0
Name: new_cases, dtype: float64
33752 33759    2535.0
Name: new_cases, dtype: float64
33753 33760    1617.0
Name: new_cases, dtype: float64
33754 33761    422.0
Name: new_cases, dtype: float64
33755 33762    1936.0
Name: new_cases, dtype: float64
33756 33763    3099.0
Name: new_cases, dtype: float64
33757 33764    2927.0
Name: new_cases, dtype: float64
33758 33765    2698.0
Name: new_cases, dtype: float64
33759 33766    2627.0
Name: new_cases, dtype: float64
33760 33767    1565.0
Name: new_cases, dtype: float64
33761 33768    410.0
Name: new_cases, dtype: float64
33762 33769    2106.0
Name: new_cases, dtype: float64
33763 33770    3117.0
Name: new_cases, dtype: float64
33764 33771    2885.0
Name: new_cases, dtype: float64
33765 33772    2529.0
Name: new_cases, dtype: float64
33766 33773    2535.0
Name: new_cases, dtype: float64
33767 33774    1254.0
Name: new_cases, dtype: float64
33768 33775    410.0
Name: new_cases, dtype: float64
33769 33776    1797.0
Name: new_cases, dtype: float64
33770 33777    2904.0
Name: new_cases, dtype: float64
33771 33778    2439.0
Name: new_cases, dtype: float64
33772 33779    2007.0
Name: new_cases, dtype: float64
33773 33780    2046.0
Name: new_cases, dtype: float64
33774 33781    944.0
Name: new_cases, dtype: float64
33775 33782    349.0
Name: new_cases, dtype: float64
33776 33783    1396.0
Name: new_cases, dtype: float64
33777 33784    2494.0
Name: new_cases, dtype: float64
33778 33785    1640.0
Name: new_cases, dtype: float64
33779 33786    1435.0
Name: new_cases, dtype: float64
33780 33787    1342.0
Name: new_cases, dtype: float64
33781 33788    665.0
Name: new_cases, dtype: float64
33782 33789    253.0
Name: new_cases, dtype: float64
33783 33790    876.0
Name: new_cases, dtype: float64
33784 33791    1471.0
Name: new_cases, dtype: float64
33785 33792    1064.0
Name: new_cases, dtype: float64
33786 33793    926.0
Name: new_cases, dtype: float64
33787 33794    826.0
Name: new_cases, dtype: float64
33788 33795    480.0
Name: new_cases, dtype: float64
33789 33796    116.0
Name: new_cases, dtype: float64
33790 33797    491.0
Name: new_cases, dtype: float64
33791 33798    1000.0
Name: new_cases, dtype: float64
33792 33799    695.0
Name: new_cases, dtype: float64
33793 33800    525.0
Name: new_cases, dtype: float64
33794 33801    518.0
Name: new_cases, dtype: float64
33795 33802    251.0
Name: new_cases, dtype: float64
33796 33803    74.0
Name: new_cases, dtype: float64
33797 33804    323.0
Name: new_cases, dtype: float64
33798 33805    538.0
Name: new_cases, dtype: float64
33799 33806    375.0
Name: new_cases, dtype: float64
33800 33807    321.0
Name: new_cases, dtype: float64
33801 33808    338.0
Name: new_cases, dtype: float64
33802 33809    186.0
Name: new_cases, dtype: float64
33803 33810    40.0
Name: new_cases, dtype: float64
33804 33811    216.0
Name: new_cases, dtype: float64
33805 33812    432.0
Name: new_cases, dtype: float64
33806 33813    280.0
Name: new_cases, dtype: float64
33807 33814    88.0
Name: new_cases, dtype: float64
33808 33815    211.0
Name: new_cases, dtype: float64
33809 33816    157.0
Name: new_cases, dtype: float64
33810 33817    43.0
Name: new_cases, dtype: float64
33811 33818    178.0
Name: new_cases, dtype: float64
33812 33819    275.0
Name: new_cases, dtype: float64
33813 33820    184.0
Name: new_cases, dtype: float64
33814 33821    134.0
Name: new_cases, dtype: float64
33815 33822    125.0
Name: new_cases, dtype: float64
33816 33823    59.0
Name: new_cases, dtype: float64

33817 33824    18.0
Name: new_cases, dtype: float64
33818 33825    96.0
Name: new_cases, dtype: float64
33819 33826    146.0
Name: new_cases, dtype: float64
33820 33827    95.0
Name: new_cases, dtype: float64
33821 33828    113.0
Name: new_cases, dtype: float64
33822 33829    84.0
Name: new_cases, dtype: float64
33823 33830    58.0
Name: new_cases, dtype: float64
33824 33831    11.0
Name: new_cases, dtype: float64
33825 33832    75.0
Name: new_cases, dtype: float64
33826 33833    43.0
Name: new_cases, dtype: float64
33827 33834    101.0
Name: new_cases, dtype: float64
33828 33835    118.0
Name: new_cases, dtype: float64
33829 33836    86.0
Name: new_cases, dtype: float64
33830 33837    45.0
Name: new_cases, dtype: float64
33831 33838    14.0
Name: new_cases, dtype: float64
33832 33839    70.0
Name: new_cases, dtype: float64
33833 33840    136.0
Name: new_cases, dtype: float64
33834 33841    103.0
Name: new_cases, dtype: float64
33835 33842    92.0
Name: new_cases, dtype: float64
33836 33843    114.0
Name: new_cases, dtype: float64
33837 33844    56.0
Name: new_cases, dtype: float64
33838 33845    9.0
Name: new_cases, dtype: float64
33839 33846    96.0
Name: new_cases, dtype: float64
33840 33847    141.0
Name: new_cases, dtype: float64
33841 33848    110.0
Name: new_cases, dtype: float64
33842 33849    87.0
Name: new_cases, dtype: float64
33843 33850    88.0
Name: new_cases, dtype: float64
33844 33851    58.0
Name: new_cases, dtype: float64
33845 33852    15.0
Name: new_cases, dtype: float64
33846 33853    83.0
Name: new_cases, dtype: float64
33847 33854    155.0
Name: new_cases, dtype: float64
33848 33855    139.0
Name: new_cases, dtype: float64
33849 33856    131.0
Name: new_cases, dtype: float64
33850 33857    139.0
Name: new_cases, dtype: float64
33851 33858    107.0
Name: new_cases, dtype: float64
33852 33859    18.0
Name: new_cases, dtype: float64
33853 33860    146.0
Name: new_cases, dtype: float64
33854 33861    191.0
Name: new_cases, dtype: float64
33855 33862    179.0
Name: new_cases, dtype: float64
33856 33863    176.0
Name: new_cases, dtype: float64
33857 33864    191.0
Name: new_cases, dtype: float64
33858 33865    125.0
Name: new_cases, dtype: float64
33859 33866    27.0
Name: new_cases, dtype: float64
33860 33867    193.0
Name: new_cases, dtype: float64
33861 33868    198.0
Name: new_cases, dtype: float64
33862 33869    188.0
Name: new_cases, dtype: float64
33863 33870    170.0
Name: new_cases, dtype: float64
33864 33871    218.0
Name: new_cases, dtype: float64
33865 33872    143.0
Name: new_cases, dtype: float64
33866 33873    29.0
Name: new_cases, dtype: float64
33867 33874    186.0
Name: new_cases, dtype: float64
33868 33875    271.0
Name: new_cases, dtype: float64
33869 33876    247.0
Name: new_cases, dtype: float64
33870 33877    108.0
Name: new_cases, dtype: float64
33871 33878    233.0
Name: new_cases, dtype: float64
33872 33879    213.0
Name: new_cases, dtype: float64
33873 33880    44.0
Name: new_cases, dtype: float64
33874 33881    246.0
Name: new_cases, dtype: float64
33875 33882    381.0
Name: new_cases, dtype: float64
33876 33883    333.0
Name: new_cases, dtype: float64
33877 33884    308.0
Name: new_cases, dtype: float64
33878 33885    367.0
Name: new_cases, dtype: float64
33879 33886    298.0
Name: new_cases, dtype: float64
33880 33887    46.0
Name: new_cases, dtype: float64
33881 33888    341.0
Name: new_cases, dtype: float64
33882 33889    524.0
Name: new_cases, dtype: float64
33883 33890    486.0
Name: new_cases, dtype: float64
33884 33891    468.0
Name: new_cases, dtype: float64
33885 33892    505.0
Name: new_cases, dtype: float64
33886 33893    373.0
Name: new_cases, dtype: float64
33887 33894    73.0
Name: new_cases, dtype: float64
33888 33895    470.0
Name: new_cases, dtype: float64
33889 33896    677.0
Name: new_cases, dtype: float64
33890 33897    638.0
Name: new_cases, dtype: float64
33891 33898    596.0
Name: new_cases, dtype: float64
33892 33899    595.0
Name: new_cases, dtype: float64
33893 33900    377.0
Name: new_cases, dtype: float64
33894 33901    139.0
Name: new_cases, dtype: float64
33895 33902    668.0
Name: new_cases, dtype: float64
33896 33903    805.0
Name: new_cases, dtype: float64
33897 33904    798.0
Name: new_cases, dtype: float64
33898 33905    816.0
Name: new_cases, dtype: float64
33899 33906    882.0
Name: new_cases, dtype: float64
33900 33907    539.0
Name: new_cases, dtype: float64
33901 33908    184.0
Name: new_cases, dtype: float64
33902 33909    704.0
Name: new_cases, dtype: float64
33903 33910    1237.0
Name: new_cases, dtype: float64
33904 33911    941.0
Name: new_cases, dtype: float64
33905 33912    1042.0
Name: new_cases, dtype: float64
33906 33913    1162.0
Name: new_cases, dtype: float64
33907 33914    807.0
Name: new_cases, dtype: float64
33908 33915    167.0
Name: new_cases, dtype: float64
33909 33916    974.0
Name: new_cases, dtype: float64
33910 33917    1835.0
Name: new_cases, dtype: float64
33911 33918    1369.0
Name: new_cases, dtype: float64
33912 33919    1394.0
Name: new_cases, dtype: float64
33913 33920    1455.0
Name: new_cases, dtype: float64
33914 33921    875.0
Name: new_cases, dtype: float64
33915 33922    264.0
Name: new_cases, dtype: float64
33916 33923    1037.0
Name: new_cases, dtype: float64
33917 33924    1812.0
Name: new_cases, dtype: float64
33918 33925    1373.0
Name: new_cases, dtype: float64
33919 33926    1291.0
Name: new_cases, dtype: float64
33920 33927    1293.0
Name: new_cases, dtype: float64
33921 33928    837.0
Name: new_cases, dtype: float64
33922 33929    217.0
Name: new_cases, dtype: float64
33923 33930    1061.0
Name: new_cases, dtype: float64
33924 33931    1911.0
Name: new_cases, dtype: float64
33925 33932    1710.0
Name: new_cases, dtype: float64
33926 33933    1517.0
Name: new_cases, dtype: float64
33927 33934    1448.0
Name: new_cases, dtype: float64
33928 33935    944.0
Name: new_cases, dtype: float64
33929 33936    219.0
Name: new_cases, dtype: float64
33930 33937    1074.0
Name: new_cases, dtype: float64
33931 33938    1925.0
Name: new_cases, dtype: float64
33932 33939    1748.0
Name: new_cases, dtype: float64
33933 33940    1691.0
Name: new_cases, dtype: float64
33934 33941    1594.0
Name: new_cases, dtype: float64
33935 33942    908.0
Name: new_cases, dtype: float64
33936 33943    170.0
Name: new_cases, dtype: float64
33937 33944    1007.0
Name: new_cases, dtype: float64
33938 33945    2022.0
Name: new_cases, dtype: float64
33939 33946    1851.0
Name: new_cases, dtype: float64
33940 33947    1758.0
Name: new_cases, dtype: float64
33941 33948    1947.0
Name: new_cases, dtype: float64
33942 33949    1301.0
Name: new_cases, dtype: float64
33943 33950    319.0
Name: new_cases, dtype: float64
33944 33951    1741.0
Name: new_cases, dtype: float64
33945 33952    3162.0
Name: new_cases, dtype: float64
33946 33953    3053.0
Name: new_cases, dtype: float64
33947 33954    3258.0
Name: new_cases, dtype: float64
33948 33955    3585.0
Name: new_cases, dtype: float64
33949 33956    2293.0
Name: new_cases, dtype: float64
33950 33957    680.0
Name: new_cases, dtype: float64
33951 33958    3360.0
Name: new_cases, dtype: float64
33952 33959    4571.0
Name: new_cases, dtype: float64
33953 33960    4154.0
Name: new_cases, dtype: float64
33954 33961    4392.0
Name: new_cases, dtype: float64
33955 33962    4547.0
Name: new_cases, dtype: float64
33956 33963    3319.0
Name: new_cases, dtype: float64
33957 33964    1126.0
Name: new_cases, dtype: float64
33958 33965    785.0
Name: new_cases, dtype: float64
33959 33966    4573.0
Name: new_cases, dtype: float64
33960 33967    6310.0
Name: new_cases, dtype: float64
33961 33968    6932.0
Name: new_cases, dtype: float64
33962 33969    7094.0
Name: new_cases, dtype: float64
33963 33970    4159.0
Name: new_cases, dtype: float64
33964 33971    1242.0
Name: new_cases, dtype: float64
33965 33972    4966.0
Name: new_cases, dtype: float64
33966 33973    7315.0
Name: new_cases, dtype: float64
33967 33974    6987.0
Name: new_cases, dtype: float64
33968 33975    6449.0
Name: new_cases, dtype: float64
33969 33976    6315.0
Name: new_cases, dtype: float64
33970 33977    4151.0
Name: new_cases, dtype: float64
33971 33978    1135.0
Name: new_cases, dtype: float64
33972 33979    4443.0
Name: new_cases, dtype: float64
33973 33980    6670.0
Name: new_cases, dtype: float64
33974 33981    7270.0
Name: new_cases, dtype: float64
33975 33982    2234.0
Name: new_cases, dtype: float64

33976 33983    5614.0
Name: new_cases, dtype: float64
33977 33984    4262.0
Name: new_cases, dtype: float64
33978 33985    1327.0
Name: new_cases, dtype: float64
33979 33986    4926.0
Name: new_cases, dtype: float64
33980 33987    6136.0
Name: new_cases, dtype: float64
33981 33988    6246.0
Name: new_cases, dtype: float64
33982 33989    5460.0
Name: new_cases, dtype: float64
33983 33990    5502.0
Name: new_cases, dtype: float64
33984 33991    3339.0
Name: new_cases, dtype: float64
33985 33992    1031.0
Name: new_cases, dtype: float64
33986 33993    3858.0
Name: new_cases, dtype: float64
33987 33994    5709.0
Name: new_cases, dtype: float64
33988 33995    5341.0
Name: new_cases, dtype: float64
33989 33996    4521.0
Name: new_cases, dtype: float64
33990 33997    4465.0
Name: new_cases, dtype: float64
33991 33998    2796.0
Name: new_cases, dtype: float64
33992 33999    728.0
Name: new_cases, dtype: float64
33993 34000    3262.0
Name: new_cases, dtype: float64
33994 34001    4751.0
Name: new_cases, dtype: float64
33995 34002    4428.0
Name: new_cases, dtype: float64
33996 34003    3797.0
Name: new_cases, dtype: float64
33997 34004    3860.0
Name: new_cases, dtype: float64
33998 34005    2339.0
Name: new_cases, dtype: float64
33999 34006    453.0
Name: new_cases, dtype: float64
34000 34007    3071.0
Name: new_cases, dtype: float64
34001 34008    4671.0
Name: new_cases, dtype: float64
34002 34009    3765.0
Name: new_cases, dtype: float64
34003 34010    3778.0
Name: new_cases, dtype: float64
34004 34011    3487.0
Name: new_cases, dtype: float64
34005 34012    1936.0
Name: new_cases, dtype: float64
34006 34013    367.0
Name: new_cases, dtype: float64
34007 34014    2803.0
Name: new_cases, dtype: float64
34008 34015    4226.0
Name: new_cases, dtype: float64
34009 34016    3831.0
Name: new_cases, dtype: float64
34010 34017    3241.0
Name: new_cases, dtype: float64
34011 34018    3271.0
Name: new_cases, dtype: float64
34012 34019    151.0
Name: new_cases, dtype: float64
34013 34020    560.0
Name: new_cases, dtype: float64
34014 34021    4139.0
Name: new_cases, dtype: float64
34015 34022    5768.0
Name: new_cases, dtype: float64
34016 34023    5958.0
Name: new_cases, dtype: float64
34017 34024    5567.0
Name: new_cases, dtype: float64
34018 34025    5293.0
Name: new_cases, dtype: float64
34019 34026    413.0
Name: new_cases, dtype: float64
34020 34027    1103.0
Name: new_cases, dtype: float64
34021 34028    5845.0
Name: new_cases, dtype: float64
34022 34029    8587.0
Name: new_cases, dtype: float64
34023 34030    9058.0
Name: new_cases, dtype: float64
34024 34031    3911.0
Name: new_cases, dtype: float64
34025 34032    8817.0
Name: new_cases, dtype: float64
34026 33354    1.0
Name: new_cases, dtype: float64
34027 33355    0.0
Name: new_cases, dtype: float64
34028 33356    2.0
Name: new_cases, dtype: float64
34029 33357    1.0
Name: new_cases, dtype: float64
34030 33358    0.0
Name: new_cases, dtype: float64
34031 33359    1.0
Name: new_cases, dtype: float64
34032 33360    1.0
Name: new_cases, dtype: float64
36039 36046    12.0
Name: new_cases, dtype: float64
36040 36047    0.0
Name: new_cases, dtype: float64
36041 36048    10.0
Name: new_cases, dtype: float64
36042 36049    50.0
Name: new_cases, dtype: float64
36043 36050    3.0
Name: new_cases, dtype: float64
36044 36051    47.0
Name: new_cases, dtype: float64
36045 36052    48.0
Name: new_cases, dtype: float64
36046 36053    64.0
Name: new_cases, dtype: float64
36047 36054    45.0
Name: new_cases, dtype: float64
36048 36055    98.0
Name: new_cases, dtype: float64
36049 36056    68.0
Name: new_cases, dtype: float64
36050 36057    230.0
Name: new_cases, dtype: float64
36051 36058    139.0
Name: new_cases, dtype: float64
36052 36059    162.0
Name: new_cases, dtype: float64
36053 36060    125.0
Name: new_cases, dtype: float64
36054 36061    116.0
Name: new_cases, dtype: float64
36055 36062    158.0
Name: new_cases, dtype: float64
36056 36063    260.0
Name: new_cases, dtype: float64
36057 36064    271.0
Name: new_cases, dtype: float64
36058 36065    354.0
Name: new_cases, dtype: float64
36059 36066    352.0
Name: new_cases, dtype: float64
36060 36067    186.0
Name: new_cases, dtype: float64
36061 36068    184.0
Name: new_cases, dtype: float64
36062 36069    307.0
Name: new_cases, dtype: float64
36063 36070    200.0
Name: new_cases, dtype: float64
36064 36071    350.0
Name: new_cases, dtype: float64
36065 36072    233.0
Name: new_cases, dtype: float64
36066 36073    381.0
Name: new_cases, dtype: float64
36067 36074    115.0
Name: new_cases, dtype: float64
36068 36075    235.0
Name: new_cases, dtype: float64
36069 36076    195.0
Name: new_cases, dtype: float64
36070 36077    295.0
Name: new_cases, dtype: float64
36071 36078    257.0
Name: new_cases, dtype: float64
36072 36079    163.0
Name: new_cases, dtype: float64
36073 36080    99.0
Name: new_cases, dtype: float64
36074 36081    160.0
Name: new_cases, dtype: float64
36075 36082    68.0
Name: new_cases, dtype: float64
36076 36083    52.0
Name: new_cases, dtype: float64
36077 36084    105.0
Name: new_cases, dtype: float64
36078 36085    217.0
Name: new_cases, dtype: float64
36079 36086    116.0
Name: new_cases, dtype: float64
36080 36087    57.0
Name: new_cases, dtype: float64
36081 36088    140.0
Name: new_cases, dtype: float64
36082 36089    154.0
Name: new_cases, dtype: float64
36083 36090    133.0
Name: new_cases, dtype: float64
36084 36091    99.0
Name: new_cases, dtype: float64
36085 36092    55.0
Name: new_cases, dtype: float64
36086 36093    86.0
Name: new_cases, dtype: float64
36087 36094    79.0
Name: new_cases, dtype: float64
36088 36095    52.0
Name: new_cases, dtype: float64
36089 36096    41.0
Name: new_cases, dtype: float64
36090 36097    59.0
Name: new_cases, dtype: float64
36091 36098    75.0
Name: new_cases, dtype: float64
36092 36099    103.0
Name: new_cases, dtype: float64
36093 36100    55.0
Name: new_cases, dtype: float64
36094 36101    18.0
Name: new_cases, dtype: float64
36095 36102    26.0
Name: new_cases, dtype: float64
36096 36103    38.0
Name: new_cases, dtype: float64
36097 36104    77.0
Name: new_cases, dtype: float64
36098 36105    78.0
Name: new_cases, dtype: float64
36099 36106    57.0
Name: new_cases, dtype: float64
36100 36107    46.0
Name: new_cases, dtype: float64
36101 36108    18.0
Name: new_cases, dtype: float64
36102 36109    28.0
Name: new_cases, dtype: float64
36103 36110    53.0
Name: new_cases, dtype: float64
36104 36111    45.0
Name: new_cases, dtype: float64
36105 36112    48.0
Name: new_cases, dtype: float64
36106 36113    82.0
Name: new_cases, dtype: float64
36107 36114    55.0
Name: new_cases, dtype: float64
36108 36115    49.0
Name: new_cases, dtype: float64
36109 36116    20.0
Name: new_cases, dtype: float64
36110 36117    111.0
Name: new_cases, dtype: float64
36111 36118    61.0
Name: new_cases, dtype: float64
36112 36119    74.0
Name: new_cases, dtype: float64
36113 36120    33.0
Name: new_cases, dtype: float64
36114 36121    59.0
Name: new_cases, dtype: float64
36115 36122    77.0
Name: new_cases, dtype: float64
36116 36123    65.0
Name: new_cases, dtype: float64
36117 36124    47.0
Name: new_cases, dtype: float64
36118 36125    48.0
Name: new_cases, dtype: float64
36119 36126    36.0
Name: new_cases, dtype: float64
36120 36127    54.0
Name: new_cases, dtype: float64
36121 36128    56.0
Name: new_cases, dtype: float64
36122 36129    34.0
Name: new_cases, dtype: float64
36123 36130    38.0
Name: new_cases, dtype: float64
36124 36131    34.0
Name: new_cases, dtype: float64
36125 36132    62.0
Name: new_cases, dtype: float64
36126 36133    74.0
Name: new_cases, dtype: float64
36127 36134    56.0
Name: new_cases, dtype: float64
36128 36135    35.0
Name: new_cases, dtype: float64
36129 36136    38.0
Name: new_cases, dtype: float64
36130 36137    61.0
Name: new_cases, dtype: float64
36131 36138    69.0
Name: new_cases, dtype: float64
36132 36139    54.0
Name: new_cases, dtype: float64
36133 36140    73.0
Name: new_cases, dtype: float64
36134 36141    31.0
Name: new_cases, dtype: float64
36135 36142    83.0
Name: new_cases, dtype: float64
36136 36143    53.0
Name: new_cases, dtype: float64
36137 36144    33.0
Name: new_cases, dtype: float64
36138 36145    40.0
Name: new_cases, dtype: float64
36139 36146    47.0
Name: new_cases, dtype: float64
36140 36147    51.0
Name: new_cases, dtype: float64
36141 36148    118.0
Name: new_cases, dtype: float64
36142 36149    126.0
Name: new_cases, dtype: float64
36143 36150    42.0
Name: new_cases, dtype: float64
36144 36151    50.0
Name: new_cases, dtype: float64
36145 36152    25.0
Name: new_cases, dtype: float64
36146 36153    127.0
Name: new_cases, dtype: float64
36147 36154    127.0
Name: new_cases, dtype: float64
36148 36155    93.0
Name: new_cases, dtype: float64

36149 36156    168.0
Name: new_cases, dtype: float64
36150 36157    260.0
Name: new_cases, dtype: float64
36151 36158    305.0
Name: new_cases, dtype: float64
36152 36159    202.0
Name: new_cases, dtype: float64
36153 36160    149.0
Name: new_cases, dtype: float64
36154 36161    92.0
Name: new_cases, dtype: float64
36155 36162    132.0
Name: new_cases, dtype: float64
36156 36163    141.0
Name: new_cases, dtype: float64
36157 36164    121.0
Name: new_cases, dtype: float64
36158 36165    75.0
Name: new_cases, dtype: float64
36159 36166    51.0
Name: new_cases, dtype: float64
36160 36167    119.0
Name: new_cases, dtype: float64
36161 36168    129.0
Name: new_cases, dtype: float64
36162 36169    105.0
Name: new_cases, dtype: float64
36163 36170    82.0
Name: new_cases, dtype: float64
36164 36171    114.0
Name: new_cases, dtype: float64
36165 36172    59.0
Name: new_cases, dtype: float64
36166 36173    64.0
Name: new_cases, dtype: float64
36167 36174    103.0
Name: new_cases, dtype: float64
36168 36175    134.0
Name: new_cases, dtype: float64
36169 36176    137.0
Name: new_cases, dtype: float64
36170 36177    130.0
Name: new_cases, dtype: float64
36171 36178    113.0
Name: new_cases, dtype: float64
36172 36179    90.0
Name: new_cases, dtype: float64
36173 36180    153.0
Name: new_cases, dtype: float64
36174 36181    226.0
Name: new_cases, dtype: float64
36175 36182    246.0
Name: new_cases, dtype: float64
36176 36183    230.0
Name: new_cases, dtype: float64
36177 36184    281.0
Name: new_cases, dtype: float64
36178 36185    131.0
Name: new_cases, dtype: float64
36179 36186    112.0
Name: new_cases, dtype: float64
36180 36187    192.0
Name: new_cases, dtype: float64
36181 36188    283.0
Name: new_cases, dtype: float64
36182 36189    294.0
Name: new_cases, dtype: float64
36183 36190    278.0
Name: new_cases, dtype: float64
36184 36191    203.0
Name: new_cases, dtype: float64
36185 36192    125.0
Name: new_cases, dtype: float64
36186 36193    101.0
Name: new_cases, dtype: float64
36187 36194    208.0
Name: new_cases, dtype: float64
36188 36195    278.0
Name: new_cases, dtype: float64
36189 36196    243.0
Name: new_cases, dtype: float64
36190 36197    202.0
Name: new_cases, dtype: float64
36191 36198    329.0
Name: new_cases, dtype: float64
36192 36199    175.0
Name: new_cases, dtype: float64
36193 36200    118.0
Name: new_cases, dtype: float64
36194 36201    141.0
Name: new_cases, dtype: float64
36195 36202    289.0
Name: new_cases, dtype: float64
36196 36203    292.0
Name: new_cases, dtype: float64
36197 36204    326.0
Name: new_cases, dtype: float64
36198 36205    292.0
Name: new_cases, dtype: float64
36199 36206    198.0
Name: new_cases, dtype: float64
36200 36207    121.0
Name: new_cases, dtype: float64
36201 36208    190.0
Name: new_cases, dtype: float64
36202 36209    281.0
Name: new_cases, dtype: float64
36203 36210    315.0
Name: new_cases, dtype: float64
36204 36211    247.0
Name: new_cases, dtype: float64
36205 36212    506.0
Name: new_cases, dtype: float64
36206 36213    239.0
Name: new_cases, dtype: float64
36207 36214    133.0
Name: new_cases, dtype: float64
36208 36215    258.0
Name: new_cases, dtype: float64
36209 36216    367.0
Name: new_cases, dtype: float64
36210 36217    403.0
Name: new_cases, dtype: float64
36211 36218    218.0
Name: new_cases, dtype: float64
36212 36219    608.0
Name: new_cases, dtype: float64
36213 36220    317.0
Name: new_cases, dtype: float64
36214 36221    273.0
Name: new_cases, dtype: float64
36215 36222    251.0
Name: new_cases, dtype: float64
36216 36223    499.0
Name: new_cases, dtype: float64
36217 36224    656.0
Name: new_cases, dtype: float64
36218 36225    679.0
Name: new_cases, dtype: float64
36219 36226    797.0
Name: new_cases, dtype: float64
36220 36227    503.0
Name: new_cases, dtype: float64
36221 36228    404.0
Name: new_cases, dtype: float64
36222 36229    560.0
Name: new_cases, dtype: float64
36223 36230    1161.0
Name: new_cases, dtype: float64
36224 36231    1159.0
Name: new_cases, dtype: float64
36225 36232    1377.0
Name: new_cases, dtype: float64
36226 36233    1447.0
Name: new_cases, dtype: float64
36227 36234    1541.0
Name: new_cases, dtype: float64
36228 36235    787.0
Name: new_cases, dtype: float64
36229 36236    1034.0
Name: new_cases, dtype: float64
36230 36237    1674.0
Name: new_cases, dtype: float64
36231 36238    2136.0
Name: new_cases, dtype: float64
36232 36239    3123.0
Name: new_cases, dtype: float64
36233 36240    2107.0
Name: new_cases, dtype: float64
36234 36241    2044.0
Name: new_cases, dtype: float64
36235 36242    984.0
Name: new_cases, dtype: float64
36236 36243    1474.0
Name: new_cases, dtype: float64
36237 36244    2394.0
Name: new_cases, dtype: float64
36238 36245    2306.0
Name: new_cases, dtype: float64
36239 36246    2910.0
Name: new_cases, dtype: float64
36240 36247    2944.0
Name: new_cases, dtype: float64
36241 36248    1976.0
Name: new_cases, dtype: float64
36242 36249    1303.0
Name: new_cases, dtype: float64
36243 36250    1286.0
Name: new_cases, dtype: float64
36244 36251    1960.0
Name: new_cases, dtype: float64
36245 36252    2920.0
Name: new_cases, dtype: float64
36246 36253    3492.0
Name: new_cases, dtype: float64
36247 36254    3796.0
Name: new_cases, dtype: float64
36248 36255    2554.0
Name: new_cases, dtype: float64
36249 36256    1841.0
Name: new_cases, dtype: float64
36250 36257    3120.0
Name: new_cases, dtype: float64
36251 36258    4456.0
Name: new_cases, dtype: float64
36252 36259    5338.0
Name: new_cases, dtype: float64
36253 36260    5397.0
Name: new_cases, dtype: float64
36254 36261    8617.0
Name: new_cases, dtype: float64
36255 36262    4631.0
Name: new_cases, dtype: float64
36256 36263    3105.0
Name: new_cases, dtype: float64
36257 36264    4311.0
Name: new_cases, dtype: float64
36258 36265    8326.0
Name: new_cases, dtype: float64
36259 36266    9543.0
Name: new_cases, dtype: float64
36260 36267    9720.0
Name: new_cases, dtype: float64
36261 36268    11102.0
Name: new_cases, dtype: float64
36262 36269    8715.0
Name: new_cases, dtype: float64
36263 36270    5058.0
Name: new_cases, dtype: float64
36264 36271    8077.0
Name: new_cases, dtype: float64
36265 36272    11984.0
Name: new_cases, dtype: float64
36266 36273    14969.0
Name: new_cases, dtype: float64
36267 36274    14150.0
Name: new_cases, dtype: float64
36268 36275    15258.0
Name: new_cases, dtype: float64
36269 36276    12474.0
Name: new_cases, dtype: float64
36270 36277    7300.0
Name: new_cases, dtype: float64
36271 36278    10273.0
Name: new_cases, dtype: float64
36272 36279    15663.0
Name: new_cases, dtype: float64
36273 36280    12980.0
Name: new_cases, dtype: float64
36274 36281    13055.0
Name: new_cases, dtype: float64
36275 36282    13605.0
Name: new_cases, dtype: float64
36276 36283    11429.0
Name: new_cases, dtype: float64
36277 36284    6542.0
Name: new_cases, dtype: float64
36278 36285    9252.0
Name: new_cases, dtype: float64
36279 36286    12089.0
Name: new_cases, dtype: float64
36280 36287    15731.0
Name: new_cases, dtype: float64
36281 36288    13229.0
Name: new_cases, dtype: float64
36282 36289    11552.0
Name: new_cases, dtype: float64
36283 36290    7723.0
Name: new_cases, dtype: float64
36284 36291    3608.0
Name: new_cases, dtype: float64
36285 36292    2353.0
Name: new_cases, dtype: float64
36286 36293    12699.0
Name: new_cases, dtype: float64
36287 36294    8925.0
Name: new_cases, dtype: float64
36288 36295    7870.0
Name: new_cases, dtype: float64
36289 36296    7355.0
Name: new_cases, dtype: float64
36290 36297    4199.0
Name: new_cases, dtype: float64
36291 36298    1887.0
Name: new_cases, dtype: float64
36292 36299    5407.0
Name: new_cases, dtype: float64
36293 36300    4246.0
Name: new_cases, dtype: float64
36294 36301    5515.0
Name: new_cases, dtype: float64
36295 36302    6471.0
Name: new_cases, dtype: float64
36296 36303    5808.0
Name: new_cases, dtype: float64
36297 36304    3187.0
Name: new_cases, dtype: float64
36298 36305    1513.0
Name: new_cases, dtype: float64
36299 36306    4375.0
Name: new_cases, dtype: float64
36300 36307    5896.0
Name: new_cases, dtype: float64
36301 36308    2681.0
Name: new_cases, dtype: float64
36302 36309    6305.0
Name: new_cases, dtype: float64
36303 36310    4464.0
Name: new_cases, dtype: float64
36304 36311    2665.0
Name: new_cases, dtype: float64
36305 36312    1074.0
Name: new_cases, dtype: float64
36306 36313    3575.0
Name: new_cases, dtype: float64

36307 36314    5176.0
Name: new_cases, dtype: float64
36308 36315    4568.0
Name: new_cases, dtype: float64
36309 36316    4621.0
Name: new_cases, dtype: float64
36310 36317    4743.0
Name: new_cases, dtype: float64
36311 36318    1773.0
Name: new_cases, dtype: float64
36312 36319    2654.0
Name: new_cases, dtype: float64
36313 36320    0.0
Name: new_cases, dtype: float64
36314 36321    4237.0
Name: new_cases, dtype: float64
36315 36322    5857.0
Name: new_cases, dtype: float64
36316 36323    6406.0
Name: new_cases, dtype: float64
36317 36324    5872.0
Name: new_cases, dtype: float64
36318 36325    6217.0
Name: new_cases, dtype: float64
36319 36326    3657.0
Name: new_cases, dtype: float64
36320 36327    2000.0
Name: new_cases, dtype: float64
36321 36328    5172.0
Name: new_cases, dtype: float64
36322 36329    7897.0
Name: new_cases, dtype: float64
36323 36330    8256.0
Name: new_cases, dtype: float64
36324 36331    7602.0
Name: new_cases, dtype: float64
36325 36332    8830.0
Name: new_cases, dtype: float64
36326 36333    5304.0
Name: new_cases, dtype: float64
36327 36334    3383.0
Name: new_cases, dtype: float64
36328 36335    7891.0
Name: new_cases, dtype: float64
36329 36336    10898.0
Name: new_cases, dtype: float64
36330 36337    14149.0
Name: new_cases, dtype: float64
36331 36338    4402.0
Name: new_cases, dtype: float64
36332 36339    2706.0
Name: new_cases, dtype: float64
36333 36340    3030.0
Name: new_cases, dtype: float64
36334 36341    3741.0
Name: new_cases, dtype: float64
36335 36342    10862.0
Name: new_cases, dtype: float64
36336 36343    16420.0
Name: new_cases, dtype: float64
36337 36344    17039.0
Name: new_cases, dtype: float64
36338 36345    13361.0
Name: new_cases, dtype: float64
36339 36346    3447.0
Name: new_cases, dtype: float64
36340 36347    5012.0
Name: new_cases, dtype: float64
36341 36348    6233.0
Name: new_cases, dtype: float64
36342 36349    12921.0
Name: new_cases, dtype: float64
36343 36350    17332.0
Name: new_cases, dtype: float64
36344 36351    17773.0
Name: new_cases, dtype: float64
36345 36352    14861.0
Name: new_cases, dtype: float64
36346 36353    13115.0
Name: new_cases, dtype: float64
36347 36354    8449.0
Name: new_cases, dtype: float64
36348 36355    4289.0
Name: new_cases, dtype: float64
36349 36356    9345.0
Name: new_cases, dtype: float64
36350 36357    10801.0
Name: new_cases, dtype: float64
36351 36358    10922.0
Name: new_cases, dtype: float64
36352 36359    8083.0
Name: new_cases, dtype: float64
36353 36360    9301.0
Name: new_cases, dtype: float64
36354 36361    5253.0
Name: new_cases, dtype: float64
36355 36362    2693.0
Name: new_cases, dtype: float64
36356 36363    7651.0
Name: new_cases, dtype: float64
36357 36364    9628.0
Name: new_cases, dtype: float64
36358 36365    8228.0
Name: new_cases, dtype: float64
36359 36366    7488.0
Name: new_cases, dtype: float64
36360 36367    8514.0
Name: new_cases, dtype: float64
36361 36368    4256.0
Name: new_cases, dtype: float64
36362 36369    2387.0
Name: new_cases, dtype: float64
36363 36370    6942.0
Name: new_cases, dtype: float64
36364 36371    9209.0
Name: new_cases, dtype: float64
36365 36372    8505.0
Name: new_cases, dtype: float64
36366 36373    7982.0
Name: new_cases, dtype: float64
36367 36374    8072.0
Name: new_cases, dtype: float64
36368 36375    4060.0
Name: new_cases, dtype: float64
36369 36376    2555.0
Name: new_cases, dtype: float64
36370 36377    7185.0
Name: new_cases, dtype: float64
36371 36378    9143.0
Name: new_cases, dtype: float64
36372 36379    9695.0
Name: new_cases, dtype: float64
36373 36380    8125.0
Name: new_cases, dtype: float64
36374 36381    8635.0
Name: new_cases, dtype: float64
36375 36382    4863.0
Name: new_cases, dtype: float64
36376 36383    2430.0
Name: new_cases, dtype: float64
36377 36384    7727.0
Name: new_cases, dtype: float64
36378 36385    10283.0
Name: new_cases, dtype: float64
36379 36386    9537.0
Name: new_cases, dtype: float64
36380 36387    9014.0
Name: new_cases, dtype: float64
36381 36388    8883.0
Name: new_cases, dtype: float64
36382 36389    5160.0
Name: new_cases, dtype: float64
36383 36390    2851.0
Name: new_cases, dtype: float64
36384 36391    8794.0
Name: new_cases, dtype: float64
36385 36392    12668.0
Name: new_cases, dtype: float64
36386 36393    10930.0
Name: new_cases, dtype: float64
36387 36394    11705.0
Name: new_cases, dtype: float64
36388 36395    11364.0
Name: new_cases, dtype: float64
36389 36396    6838.0
Name: new_cases, dtype: float64
36390 36397    4021.0
Name: new_cases, dtype: float64
36391 36398    11311.0
Name: new_cases, dtype: float64
36392 36399    15861.0
Name: new_cases, dtype: float64
36393 36400    13816.0
Name: new_cases, dtype: float64
36394 36401    14612.0
Name: new_cases, dtype: float64
36395 36402    14815.0
Name: new_cases, dtype: float64
36396 36403    7885.0
Name: new_cases, dtype: float64
36397 36404    4571.0
Name: new_cases, dtype: float64
36398 36405    12191.0
Name: new_cases, dtype: float64
36399 36406    16816.0
Name: new_cases, dtype: float64
36400 36407    15230.0
Name: new_cases, dtype: float64
36401 36408    14714.0
Name: new_cases, dtype: float64
36402 36409    13162.0
Name: new_cases, dtype: float64
36403 36410    9167.0
Name: new_cases, dtype: float64
36404 36411    3960.0
Name: new_cases, dtype: float64
36405 36412    10524.0
Name: new_cases, dtype: float64
36406 36413    15380.0
Name: new_cases, dtype: float64
36407 36414    14529.0
Name: new_cases, dtype: float64
36408 36415    11274.0
Name: new_cases, dtype: float64
36409 36416    15110.0
Name: new_cases, dtype: float64
36410 36417    6970.0
Name: new_cases, dtype: float64
36411 36418    3342.0
Name: new_cases, dtype: float64
36412 36419    10542.0
Name: new_cases, dtype: float64
36413 36420    14029.0
Name: new_cases, dtype: float64
36414 36421    12028.0
Name: new_cases, dtype: float64
36415 36422    10677.0
Name: new_cases, dtype: float64
36416 36423    9710.0
Name: new_cases, dtype: float64
36417 36424    10141.0
Name: new_cases, dtype: float64
36418 36425   -2214.0
Name: new_cases, dtype: float64
36419 36426    8205.0
Name: new_cases, dtype: float64
36420 36427    10972.0
Name: new_cases, dtype: float64
36421 36428    8851.0
Name: new_cases, dtype: float64
36422 36429    7946.0
Name: new_cases, dtype: float64
36423 36430    7714.0
Name: new_cases, dtype: float64
36424 36431    4008.0
Name: new_cases, dtype: float64
36425 36432    1743.0
Name: new_cases, dtype: float64
36426 36433    6896.0
Name: new_cases, dtype: float64
36427 36434    8664.0
Name: new_cases, dtype: float64
36428 36435    7285.0
Name: new_cases, dtype: float64
36429 36436    6248.0
Name: new_cases, dtype: float64
36430 36437    3869.0
Name: new_cases, dtype: float64
36431 36438    2162.0
Name: new_cases, dtype: float64
36432 36439    1924.0
Name: new_cases, dtype: float64
36433 36440    1425.0
Name: new_cases, dtype: float64
36434 36441    5532.0
Name: new_cases, dtype: float64
36435 36442    7071.0
Name: new_cases, dtype: float64
36436 36443    5305.0
Name: new_cases, dtype: float64
36437 36444    4819.0
Name: new_cases, dtype: float64
36438 36445    2217.0
Name: new_cases, dtype: float64
36439 36446    995.0
Name: new_cases, dtype: float64
36440 36447    3853.0
Name: new_cases, dtype: float64
36441 36448    5087.0
Name: new_cases, dtype: float64
36442 36449    3723.0
Name: new_cases, dtype: float64
36443 36450    3256.0
Name: new_cases, dtype: float64
36444 36451    3238.0
Name: new_cases, dtype: float64
36445 36452    1540.0
Name: new_cases, dtype: float64
36446 36453    830.0
Name: new_cases, dtype: float64
36447 36454    3319.0
Name: new_cases, dtype: float64
36448 36455    3831.0
Name: new_cases, dtype: float64
36449 36456    2971.0
Name: new_cases, dtype: float64
36450 36457    2629.0
Name: new_cases, dtype: float64
36451 36458    2607.0
Name: new_cases, dtype: float64
36452 36459    1315.0
Name: new_cases, dtype: float64
36453 36460    823.0
Name: new_cases, dtype: float64
36454 36461    2571.0
Name: new_cases, dtype: float64
36455 36462    3256.0
Name: new_cases, dtype: float64
36456 36463    2503.0
Name: new_cases, dtype: float64
36457 36464    2222.0
Name: new_cases, dtype: float64
36458 36465    2174.0
Name: new_cases, dtype: float64
36459 36466    1182.0
Name: new_cases, dtype: float64

36460 36467    505.0
Name: new_cases, dtype: float64
36461 36468    2217.0
Name: new_cases, dtype: float64
36462 36469    2412.0
Name: new_cases, dtype: float64
36463 36470    1872.0
Name: new_cases, dtype: float64
36464 36471    1576.0
Name: new_cases, dtype: float64
36465 36472    1639.0
Name: new_cases, dtype: float64
36466 36473    726.0
Name: new_cases, dtype: float64
36467 36474    387.0
Name: new_cases, dtype: float64
36468 36475    1533.0
Name: new_cases, dtype: float64
36469 36476    1686.0
Name: new_cases, dtype: float64
36470 36477    1280.0
Name: new_cases, dtype: float64
36471 36478    1231.0
Name: new_cases, dtype: float64
36472 36479    1060.0
Name: new_cases, dtype: float64
36473 36480    602.0
Name: new_cases, dtype: float64
36474 36481    259.0
Name: new_cases, dtype: float64
36475 36482    1120.0
Name: new_cases, dtype: float64
36476 36483    1195.0
Name: new_cases, dtype: float64
36477 36484    788.0
Name: new_cases, dtype: float64
36478 36485    672.0
Name: new_cases, dtype: float64
36479 36486    684.0
Name: new_cases, dtype: float64
36480 36487    335.0
Name: new_cases, dtype: float64
36481 36488    199.0
Name: new_cases, dtype: float64
36482 36489    686.0
Name: new_cases, dtype: float64
36483 36490    655.0
Name: new_cases, dtype: float64
36484 36491    547.0
Name: new_cases, dtype: float64
36485 36492    501.0
Name: new_cases, dtype: float64
36486 36493    454.0
Name: new_cases, dtype: float64
36487 36494    224.0
Name: new_cases, dtype: float64
36488 36495    113.0
Name: new_cases, dtype: float64
36489 36496    508.0
Name: new_cases, dtype: float64
36490 36497    476.0
Name: new_cases, dtype: float64
36491 36498    352.0
Name: new_cases, dtype: float64
36492 36499    432.0
Name: new_cases, dtype: float64
36493 36500    323.0
Name: new_cases, dtype: float64
36494 36501    154.0
Name: new_cases, dtype: float64
36495 36502    90.0
Name: new_cases, dtype: float64
36496 36503    391.0
Name: new_cases, dtype: float64
36497 36504    384.0
Name: new_cases, dtype: float64
36498 36505    267.0
Name: new_cases, dtype: float64
36499 36506    190.0
Name: new_cases, dtype: float64
36500 36507    183.0
Name: new_cases, dtype: float64
36501 36508    75.0
Name: new_cases, dtype: float64
36502 36509    41.0
Name: new_cases, dtype: float64
36503 36510    189.0
Name: new_cases, dtype: float64
36504 36511    199.0
Name: new_cases, dtype: float64
36505 36512    134.0
Name: new_cases, dtype: float64
36506 36513    158.0
Name: new_cases, dtype: float64
36507 36514    143.0
Name: new_cases, dtype: float64
36508 36515    64.0
Name: new_cases, dtype: float64
36509 36516    57.0
Name: new_cases, dtype: float64
36510 36517    110.0
Name: new_cases, dtype: float64
36511 36518    133.0
Name: new_cases, dtype: float64
36512 36519    196.0
Name: new_cases, dtype: float64
36513 36520    165.0
Name: new_cases, dtype: float64
36514 36521    135.0
Name: new_cases, dtype: float64
36515 36522    69.0
Name: new_cases, dtype: float64
36516 36523    57.0
Name: new_cases, dtype: float64
36517 36524    168.0
Name: new_cases, dtype: float64
36518 36525    172.0
Name: new_cases, dtype: float64
36519 36526    148.0
Name: new_cases, dtype: float64
36520 36527    173.0
Name: new_cases, dtype: float64
36521 36528    188.0
Name: new_cases, dtype: float64
36522 36529    139.0
Name: new_cases, dtype: float64
36523 36530    105.0
Name: new_cases, dtype: float64
36524 36531    130.0
Name: new_cases, dtype: float64
36525 36532    107.0
Name: new_cases, dtype: float64
36526 36533    342.0
Name: new_cases, dtype: float64
36527 36534    272.0
Name: new_cases, dtype: float64
36528 36535    291.0
Name: new_cases, dtype: float64
36529 36536    169.0
Name: new_cases, dtype: float64
36530 36537    145.0
Name: new_cases, dtype: float64
36531 36538    249.0
Name: new_cases, dtype: float64
36532 36539    328.0
Name: new_cases, dtype: float64
36533 36540    275.0
Name: new_cases, dtype: float64
36534 36541    235.0
Name: new_cases, dtype: float64
36535 36542    240.0
Name: new_cases, dtype: float64
36536 36543    204.0
Name: new_cases, dtype: float64
36537 36544    118.0
Name: new_cases, dtype: float64
36538 36545    227.0
Name: new_cases, dtype: float64
36539 36546    313.0
Name: new_cases, dtype: float64
36540 36547    248.0
Name: new_cases, dtype: float64
36541 36548    207.0
Name: new_cases, dtype: float64
36542 36549    200.0
Name: new_cases, dtype: float64
36543 36550    69.0
Name: new_cases, dtype: float64
36544 36551    138.0
Name: new_cases, dtype: float64
36545 36552    217.0
Name: new_cases, dtype: float64
36546 36553    253.0
Name: new_cases, dtype: float64
36547 36554    202.0
Name: new_cases, dtype: float64
36548 36555    210.0
Name: new_cases, dtype: float64
36549 36556    147.0
Name: new_cases, dtype: float64
36550 36557    118.0
Name: new_cases, dtype: float64
36551 36558    75.0
Name: new_cases, dtype: float64
36552 36559    157.0
Name: new_cases, dtype: float64
36553 36560    257.0
Name: new_cases, dtype: float64
36554 36561    227.0
Name: new_cases, dtype: float64
36555 36562    167.0
Name: new_cases, dtype: float64
36556 36563    149.0
Name: new_cases, dtype: float64
36557 36564    180.0
Name: new_cases, dtype: float64
36558 36565    104.0
Name: new_cases, dtype: float64
36559 36566    169.0
Name: new_cases, dtype: float64
36560 36567    271.0
Name: new_cases, dtype: float64
36561 36568    225.0
Name: new_cases, dtype: float64
36562 36569    193.0
Name: new_cases, dtype: float64
36563 36570    212.0
Name: new_cases, dtype: float64
36564 36571    142.0
Name: new_cases, dtype: float64
36565 36572    75.0
Name: new_cases, dtype: float64
36566 36573    221.0
Name: new_cases, dtype: float64
36567 36574    299.0
Name: new_cases, dtype: float64
36568 36575    212.0
Name: new_cases, dtype: float64
36569 36576    175.0
Name: new_cases, dtype: float64
36570 36577    174.0
Name: new_cases, dtype: float64
36571 36578    134.0
Name: new_cases, dtype: float64
36572 36579    107.0
Name: new_cases, dtype: float64
36573 36580    210.0
Name: new_cases, dtype: float64
36574 36581    254.0
Name: new_cases, dtype: float64
36575 36582    248.0
Name: new_cases, dtype: float64
36576 36583    213.0
Name: new_cases, dtype: float64
36577 36584    187.0
Name: new_cases, dtype: float64
36578 36585    131.0
Name: new_cases, dtype: float64
36579 36586    82.0
Name: new_cases, dtype: float64
36580 36587    245.0
Name: new_cases, dtype: float64
36581 36588    287.0
Name: new_cases, dtype: float64
36582 36589    262.0
Name: new_cases, dtype: float64
36583 36590    308.0
Name: new_cases, dtype: float64
36584 36591    308.0
Name: new_cases, dtype: float64
36585 36592    205.0
Name: new_cases, dtype: float64
36586 36593    138.0
Name: new_cases, dtype: float64
36587 36594    394.0
Name: new_cases, dtype: float64
36588 36595    590.0
Name: new_cases, dtype: float64
36589 36596    373.0
Name: new_cases, dtype: float64
36590 36597    421.0
Name: new_cases, dtype: float64
36591 36598    451.0
Name: new_cases, dtype: float64
36592 36599    253.0
Name: new_cases, dtype: float64
36593 36600    136.0
Name: new_cases, dtype: float64
36594 36601    487.0
Name: new_cases, dtype: float64
36595 36602    555.0
Name: new_cases, dtype: float64
36596 36603    524.0
Name: new_cases, dtype: float64
36597 36604    554.0
Name: new_cases, dtype: float64
36598 36605    443.0
Name: new_cases, dtype: float64
36599 36606    304.0
Name: new_cases, dtype: float64
36600 36607    182.0
Name: new_cases, dtype: float64
36601 36608    487.0
Name: new_cases, dtype: float64
36602 36609    597.0
Name: new_cases, dtype: float64
36603 36610    525.0
Name: new_cases, dtype: float64
36604 36611    484.0
Name: new_cases, dtype: float64
36605 36612    496.0
Name: new_cases, dtype: float64
36606 36613    411.0
Name: new_cases, dtype: float64
36607 36614    256.0
Name: new_cases, dtype: float64
36608 36615    668.0
Name: new_cases, dtype: float64
36609 36616    470.0
Name: new_cases, dtype: float64
36610 36617    731.0
Name: new_cases, dtype: float64
36611 36618    923.0
Name: new_cases, dtype: float64
36612 36619    822.0
Name: new_cases, dtype: float64
36613 36620    556.0
Name: new_cases, dtype: float64
36614 36621    317.0
Name: new_cases, dtype: float64

36615 36622    803.0
Name: new_cases, dtype: float64
36616 36623    1106.0
Name: new_cases, dtype: float64
36617 36624    1048.0
Name: new_cases, dtype: float64
36618 36625    997.0
Name: new_cases, dtype: float64
36619 36626    1013.0
Name: new_cases, dtype: float64
36620 36627    669.0
Name: new_cases, dtype: float64
36621 36628    335.0
Name: new_cases, dtype: float64
36622 36629    3925.0
Name: new_cases, dtype: float64
36623 36630    1529.0
Name: new_cases, dtype: float64
36624 36631   -1096.0
Name: new_cases, dtype: float64
36625 36632    1535.0
Name: new_cases, dtype: float64
36626 36633    1785.0
Name: new_cases, dtype: float64
36627 36634    1169.0
Name: new_cases, dtype: float64
36628 36635    791.0
Name: new_cases, dtype: float64
36629 36636    2530.0
Name: new_cases, dtype: float64
36630 36637    3269.0
Name: new_cases, dtype: float64
36631 36638    3293.0
Name: new_cases, dtype: float64
36632 36639    3638.0
Name: new_cases, dtype: float64
36633 36640    4244.0
Name: new_cases, dtype: float64
36634 36641    2768.0
Name: new_cases, dtype: float64
36635 36642    1829.0
Name: new_cases, dtype: float64
36636 36643    4265.0
Name: new_cases, dtype: float64
36637 36644    6307.0
Name: new_cases, dtype: float64
36638 36645    5842.0
Name: new_cases, dtype: float64
36639 36646    4385.0
Name: new_cases, dtype: float64
36640 36647    5735.0
Name: new_cases, dtype: float64
36641 36648    5081.0
Name: new_cases, dtype: float64
36642 36649    2752.0
Name: new_cases, dtype: float64
36643 36650    7637.0
Name: new_cases, dtype: float64
36644 36651    9936.0
Name: new_cases, dtype: float64
36645 36652    9480.0
Name: new_cases, dtype: float64
36646 36653    8447.0
Name: new_cases, dtype: float64
36647 36654    9241.0
Name: new_cases, dtype: float64
36648 36655    5766.0
Name: new_cases, dtype: float64
36649 36656    2997.0
Name: new_cases, dtype: float64
36650 36657    9282.0
Name: new_cases, dtype: float64
36651 36658    14579.0
Name: new_cases, dtype: float64
36652 36659    13536.0
Name: new_cases, dtype: float64
36653 36660    10414.0
Name: new_cases, dtype: float64
36654 36661    14237.0
Name: new_cases, dtype: float64
36655 36662    9199.0
Name: new_cases, dtype: float64
36656 36663    5670.0
Name: new_cases, dtype: float64
36657 36664    11554.0
Name: new_cases, dtype: float64
36658 36665    22585.0
Name: new_cases, dtype: float64
36659 36666    14186.0
Name: new_cases, dtype: float64
36660 36667    13416.0
Name: new_cases, dtype: float64
36661 36668    23033.0
Name: new_cases, dtype: float64
36662 36669    14442.0
Name: new_cases, dtype: float64
36663 36670    22778.0
Name: new_cases, dtype: float64
36664 36671    961.0
Name: new_cases, dtype: float64
36665 36672    24988.0
Name: new_cases, dtype: float64
36666 36673    18046.0
Name: new_cases, dtype: float64
36667 36674    27793.0
Name: new_cases, dtype: float64
36668 36675    20417.0
Name: new_cases, dtype: float64
36669 36676    22106.0
Name: new_cases, dtype: float64
36670 36677    718.0
Name: new_cases, dtype: float64
36671 36678    16944.0
Name: new_cases, dtype: float64
36672 36679    22042.0
Name: new_cases, dtype: float64
36673 36680    21205.0
Name: new_cases, dtype: float64
36674 36681    18683.0
Name: new_cases, dtype: float64
36675 36682    17743.0
Name: new_cases, dtype: float64
36676 36683    11006.0
Name: new_cases, dtype: float64
36677 36684    6346.0
Name: new_cases, dtype: float64
36678 36685    15599.0
Name: new_cases, dtype: float64
36679 36686    19546.0
Name: new_cases, dtype: float64
36680 36687    16229.0
Name: new_cases, dtype: float64
36681 36688    14295.0
Name: new_cases, dtype: float64
36682 36689    12445.0
Name: new_cases, dtype: float64
36683 36690    9108.0
Name: new_cases, dtype: float64
36684 36691    4113.0
Name: new_cases, dtype: float64
36685 36692    11936.0
Name: new_cases, dtype: float64
36686 36693    16738.0
Name: new_cases, dtype: float64
36687 36694    11652.0
Name: new_cases, dtype: float64
36688 36695    9525.0
Name: new_cases, dtype: float64
36689 36696    8993.0
Name: new_cases, dtype: float64
36690 36697    6002.0
Name: new_cases, dtype: float64
36691 36698    3741.0
Name: new_cases, dtype: float64
36692 36699    0.0
Name: new_cases, dtype: float64
36693 36700    0.0
Name: new_cases, dtype: float64
36694 36701    0.0
Name: new_cases, dtype: float64
36695 36702    0.0
Name: new_cases, dtype: float64
36696 36703    37659.0
Name: new_cases, dtype: float64
36697 36704    1093.0
Name: new_cases, dtype: float64
36698 36705    2017.0
Name: new_cases, dtype: float64
36699 36706    6887.0
Name: new_cases, dtype: float64
36700 36707    9135.0
Name: new_cases, dtype: float64
36701 36708    6171.0
Name: new_cases, dtype: float64
36702 36709    5778.0
Name: new_cases, dtype: float64
36703 36710    5007.0
Name: new_cases, dtype: float64
36704 36711    1096.0
Name: new_cases, dtype: float64
36705 36712    1930.0
Name: new_cases, dtype: float64
36706 36713    9383.0
Name: new_cases, dtype: float64
36707 36714    10229.0
Name: new_cases, dtype: float64
36708 36715    7422.0
Name: new_cases, dtype: float64
36709 36716    6679.0
Name: new_cases, dtype: float64
36710 36717    6696.0
Name: new_cases, dtype: float64
36711 Series([], Name: new_cases, dtype: float64)
36712 Series([], Name: new_cases, dtype: float64)
36713 Series([], Name: new_cases, dtype: float64)
36714 36039    3.0
Name: new_cases, dtype: float64
36715 36040    0.0
Name: new_cases, dtype: float64
36716 36041    2.0
Name: new_cases, dtype: float64
36717 36042    3.0
Name: new_cases, dtype: float64
37412 37419    0.0
Name: new_cases, dtype: float64
37413 37420    13.0
Name: new_cases, dtype: float64
37414 37421    0.0
Name: new_cases, dtype: float64
37415 37422    12.0
Name: new_cases, dtype: float64
37416 37423    55.0
Name: new_cases, dtype: float64
37417 37424    172.0
Name: new_cases, dtype: float64
37418 37425    180.0
Name: new_cases, dtype: float64
37419 37426    173.0
Name: new_cases, dtype: float64
37420 37427    186.0
Name: new_cases, dtype: float64
37421 37428    26.0
Name: new_cases, dtype: float64
37422 37429    37.0
Name: new_cases, dtype: float64
37423 37430    50.0
Name: new_cases, dtype: float64
37424 37431    63.0
Name: new_cases, dtype: float64
37425 37432    80.0
Name: new_cases, dtype: float64
37426 37433    94.0
Name: new_cases, dtype: float64
37427 37434    104.0
Name: new_cases, dtype: float64
37428 37435    71.0
Name: new_cases, dtype: float64
37429 37436    69.0
Name: new_cases, dtype: float64
37430 37437    55.0
Name: new_cases, dtype: float64
37431 37438    141.0
Name: new_cases, dtype: float64
37432 37439    133.0
Name: new_cases, dtype: float64
37433 37440    153.0
Name: new_cases, dtype: float64
37434 37441    169.0
Name: new_cases, dtype: float64
37435 37442    155.0
Name: new_cases, dtype: float64
37436 37443    194.0
Name: new_cases, dtype: float64
37437 37444    182.0
Name: new_cases, dtype: float64
37438 37445    283.0
Name: new_cases, dtype: float64
37439 37446    247.0
Name: new_cases, dtype: float64
37440 37447    279.0
Name: new_cases, dtype: float64
37441 37448    371.0
Name: new_cases, dtype: float64
37442 37449    320.0
Name: new_cases, dtype: float64
37443 37450    292.0
Name: new_cases, dtype: float64
37444 37451    312.0
Name: new_cases, dtype: float64
37445 37452    390.0
Name: new_cases, dtype: float64
37446 37453    331.0
Name: new_cases, dtype: float64
37447 37454    233.0
Name: new_cases, dtype: float64
37448 37455    184.0
Name: new_cases, dtype: float64
37449 37456    177.0
Name: new_cases, dtype: float64
37450 37457    178.0
Name: new_cases, dtype: float64
37451 37458    144.0
Name: new_cases, dtype: float64
37452 37459    193.0
Name: new_cases, dtype: float64
37453 37460    170.0
Name: new_cases, dtype: float64
37454 37461    198.0
Name: new_cases, dtype: float64
37455 37462    194.0
Name: new_cases, dtype: float64
37456 37463    169.0
Name: new_cases, dtype: float64
37457 37464    142.0
Name: new_cases, dtype: float64
37458 37465    131.0
Name: new_cases, dtype: float64
37459 37466    180.0
Name: new_cases, dtype: float64
37460 37467    217.0
Name: new_cases, dtype: float64
37461 37468    161.0
Name: new_cases, dtype: float64
37462 37469    137.0
Name: new_cases, dtype: float64

37463 37470    235.0
Name: new_cases, dtype: float64
37464 37471    130.0
Name: new_cases, dtype: float64
37465 37472    123.0
Name: new_cases, dtype: float64
37466 37473    153.0
Name: new_cases, dtype: float64
37467 37474    157.0
Name: new_cases, dtype: float64
37468 37475    150.0
Name: new_cases, dtype: float64
37469 37476    153.0
Name: new_cases, dtype: float64
37470 37477    96.0
Name: new_cases, dtype: float64
37471 37478    116.0
Name: new_cases, dtype: float64
37472 37479    147.0
Name: new_cases, dtype: float64
37473 37480    151.0
Name: new_cases, dtype: float64
37474 37481    117.0
Name: new_cases, dtype: float64
37475 37482    145.0
Name: new_cases, dtype: float64
37476 37483    135.0
Name: new_cases, dtype: float64
37477 37484    101.0
Name: new_cases, dtype: float64
37478 37485    110.0
Name: new_cases, dtype: float64
37479 37486    84.0
Name: new_cases, dtype: float64
37480 37487    78.0
Name: new_cases, dtype: float64
37481 37488    76.0
Name: new_cases, dtype: float64
37482 37489    46.0
Name: new_cases, dtype: float64
37483 37490    78.0
Name: new_cases, dtype: float64
37484 37491    67.0
Name: new_cases, dtype: float64
37485 37492    69.0
Name: new_cases, dtype: float64
37486 37493    41.0
Name: new_cases, dtype: float64
37487 37494    76.0
Name: new_cases, dtype: float64
37488 37495    73.0
Name: new_cases, dtype: float64
37489 37496    65.0
Name: new_cases, dtype: float64
37490 37497    48.0
Name: new_cases, dtype: float64
37491 37498    59.0
Name: new_cases, dtype: float64
37492 37499    71.0
Name: new_cases, dtype: float64
37493 37500    27.0
Name: new_cases, dtype: float64
37494 37501    41.0
Name: new_cases, dtype: float64
37495 37502    52.0
Name: new_cases, dtype: float64
37496 37503    32.0
Name: new_cases, dtype: float64
37497 37504    81.0
Name: new_cases, dtype: float64
37498 37505    40.0
Name: new_cases, dtype: float64
37499 37506    36.0
Name: new_cases, dtype: float64
37500 37507    30.0
Name: new_cases, dtype: float64
37501 37508    35.0
Name: new_cases, dtype: float64
37502 37509    37.0
Name: new_cases, dtype: float64
37503 37510    40.0
Name: new_cases, dtype: float64
37504 37511    64.0
Name: new_cases, dtype: float64
37505 37512    49.0
Name: new_cases, dtype: float64
37506 37513    24.0
Name: new_cases, dtype: float64
37507 37514    14.0
Name: new_cases, dtype: float64
37508 37515    39.0
Name: new_cases, dtype: float64
37509 37516    15.0
Name: new_cases, dtype: float64
37510 37517    19.0
Name: new_cases, dtype: float64
37511 37518    64.0
Name: new_cases, dtype: float64
37512 37519    40.0
Name: new_cases, dtype: float64
37513 37520    54.0
Name: new_cases, dtype: float64
37514 37521    24.0
Name: new_cases, dtype: float64
37515 37522    33.0
Name: new_cases, dtype: float64
37516 37523    44.0
Name: new_cases, dtype: float64
37517 37524    50.0
Name: new_cases, dtype: float64
37518 37525    47.0
Name: new_cases, dtype: float64
37519 37526    0.0
Name: new_cases, dtype: float64
37520 37527    0.0
Name: new_cases, dtype: float64
37521 37528    136.0
Name: new_cases, dtype: float64
37522 37529    34.0
Name: new_cases, dtype: float64
37523 37530    54.0
Name: new_cases, dtype: float64
37524 37531    21.0
Name: new_cases, dtype: float64
37525 37532    39.0
Name: new_cases, dtype: float64
37526 37533    0.0
Name: new_cases, dtype: float64
37527 37534    0.0
Name: new_cases, dtype: float64
37528 37535    76.0
Name: new_cases, dtype: float64
37529 37536    17.0
Name: new_cases, dtype: float64
37530 37537    26.0
Name: new_cases, dtype: float64
37531 37538    21.0
Name: new_cases, dtype: float64
37532 37539    17.0
Name: new_cases, dtype: float64
37533 37540    0.0
Name: new_cases, dtype: float64
37534 37541    0.0
Name: new_cases, dtype: float64
37535 37542    46.0
Name: new_cases, dtype: float64
37536 37543    10.0
Name: new_cases, dtype: float64
37537 37544    12.0
Name: new_cases, dtype: float64
37538 37545    16.0
Name: new_cases, dtype: float64
37539 37546    30.0
Name: new_cases, dtype: float64
37540 37547    0.0
Name: new_cases, dtype: float64
37541 37548    0.0
Name: new_cases, dtype: float64
37542 37549    91.0
Name: new_cases, dtype: float64
37543 37550    24.0
Name: new_cases, dtype: float64
37544 37551    31.0
Name: new_cases, dtype: float64
37545 37552    32.0
Name: new_cases, dtype: float64
37546 37553    49.0
Name: new_cases, dtype: float64
37547 37554    0.0
Name: new_cases, dtype: float64
37548 37555    0.0
Name: new_cases, dtype: float64
37549 37556    89.0
Name: new_cases, dtype: float64
37550 37557    40.0
Name: new_cases, dtype: float64
37551 37558    48.0
Name: new_cases, dtype: float64
37552 37559    40.0
Name: new_cases, dtype: float64
37553 37560    48.0
Name: new_cases, dtype: float64
37554 37561    0.0
Name: new_cases, dtype: float64
37555 37562    0.0
Name: new_cases, dtype: float64
37556 37563    109.0
Name: new_cases, dtype: float64
37557 37564    30.0
Name: new_cases, dtype: float64
37558 37565    57.0
Name: new_cases, dtype: float64
37559 37566    91.0
Name: new_cases, dtype: float64
37560 37567    64.0
Name: new_cases, dtype: float64
37561 37568    0.0
Name: new_cases, dtype: float64
37562 37569    0.0
Name: new_cases, dtype: float64
37563 37570    207.0
Name: new_cases, dtype: float64
37564 37571    77.0
Name: new_cases, dtype: float64
37565 37572    112.0
Name: new_cases, dtype: float64
37566 37573    121.0
Name: new_cases, dtype: float64
37567 37574    136.0
Name: new_cases, dtype: float64
37568 37575    0.0
Name: new_cases, dtype: float64
37569 37576    0.0
Name: new_cases, dtype: float64
37570 37577    373.0
Name: new_cases, dtype: float64
37571 37578    144.0
Name: new_cases, dtype: float64
37572 37579    111.0
Name: new_cases, dtype: float64
37573 37580    144.0
Name: new_cases, dtype: float64
37574 37581    165.0
Name: new_cases, dtype: float64
37575 37582    104.0
Name: new_cases, dtype: float64
37576 37583    134.0
Name: new_cases, dtype: float64
37577 37584    123.0
Name: new_cases, dtype: float64
37578 37585    115.0
Name: new_cases, dtype: float64
37579 37586    85.0
Name: new_cases, dtype: float64
37580 37587    116.0
Name: new_cases, dtype: float64
37581 37588    71.0
Name: new_cases, dtype: float64
37582 37589    112.0
Name: new_cases, dtype: float64
37583 37590    78.0
Name: new_cases, dtype: float64
37584 37591    80.0
Name: new_cases, dtype: float64
37585 37592    83.0
Name: new_cases, dtype: float64
37586 37593    57.0
Name: new_cases, dtype: float64
37587 37594    90.0
Name: new_cases, dtype: float64
37588 37595    73.0
Name: new_cases, dtype: float64
37589 37596    79.0
Name: new_cases, dtype: float64
37590 37597    112.0
Name: new_cases, dtype: float64
37591 37598    94.0
Name: new_cases, dtype: float64
37592 37599    99.0
Name: new_cases, dtype: float64
37593 37600    111.0
Name: new_cases, dtype: float64
37594 37601    179.0
Name: new_cases, dtype: float64
37595 37602    173.0
Name: new_cases, dtype: float64
37596 37603    189.0
Name: new_cases, dtype: float64
37597 37604    147.0
Name: new_cases, dtype: float64
37598 37605    230.0
Name: new_cases, dtype: float64
37599 37606    243.0
Name: new_cases, dtype: float64
37600 37607    251.0
Name: new_cases, dtype: float64
37601 37608    317.0
Name: new_cases, dtype: float64
37602 37609    292.0
Name: new_cases, dtype: float64
37603 37610    341.0
Name: new_cases, dtype: float64
37604 37611    333.0
Name: new_cases, dtype: float64
37605 37612    347.0
Name: new_cases, dtype: float64
37606 37613    334.0
Name: new_cases, dtype: float64
37607 37614    0.0
Name: new_cases, dtype: float64
37608 37615    822.0
Name: new_cases, dtype: float64
37609 37616    454.0
Name: new_cases, dtype: float64
37610 37617    589.0
Name: new_cases, dtype: float64
37611 37618    469.0
Name: new_cases, dtype: float64
37612 37619    418.0
Name: new_cases, dtype: float64
37613 37620    476.0
Name: new_cases, dtype: float64
37614 37621    558.0
Name: new_cases, dtype: float64
37615 37622    559.0
Name: new_cases, dtype: float64
37616 37623    678.0
Name: new_cases, dtype: float64
37617 37624    619.0
Name: new_cases, dtype: float64
37618 37625    424.0
Name: new_cases, dtype: float64
37619 37626    435.0
Name: new_cases, dtype: float64
37620 37627    392.0
Name: new_cases, dtype: float64
37621 37628    534.0
Name: new_cases, dtype: float64
37622 37629    398.0
Name: new_cases, dtype: float64
37623 37630    536.0
Name: new_cases, dtype: float64
37624 37631    370.0
Name: new_cases, dtype: float64
37625 37632    378.0
Name: new_cases, dtype: float64
37626 37633    377.0
Name: new_cases, dtype: float64
37627 37634    322.0
Name: new_cases, dtype: float64
37628 37635    331.0
Name: new_cases, dtype: float64
37629 37636    446.0
Name: new_cases, dtype: float64
37630 37637    482.0
Name: new_cases, dtype: float64
37631 37638    444.0
Name: new_cases, dtype: float64
37632 37639    340.0
Name: new_cases, dtype: float64
37633 37640    389.0
Name: new_cases, dtype: float64
37634 37641    290.0
Name: new_cases, dtype: float64
37635 37642    492.0
Name: new_cases, dtype: float64
37636 37643    430.0
Name: new_cases, dtype: float64
37637 37644    418.0
Name: new_cases, dtype: float64
37638 37645    500.0
Name: new_cases, dtype: float64
37639 37646    451.0
Name: new_cases, dtype: float64
37640 37647    452.0
Name: new_cases, dtype: float64
37641 37648    529.0
Name: new_cases, dtype: float64

37642 37649    630.0
Name: new_cases, dtype: float64
37643 37650    760.0
Name: new_cases, dtype: float64
37644 37651    859.0
Name: new_cases, dtype: float64
37645 37652    789.0
Name: new_cases, dtype: float64
37646 37653    945.0
Name: new_cases, dtype: float64
37647 37654    1056.0
Name: new_cases, dtype: float64
37648 37655    745.0
Name: new_cases, dtype: float64
37649 37656    1017.0
Name: new_cases, dtype: float64
37650 37657    860.0
Name: new_cases, dtype: float64
37651 37658    1191.0
Name: new_cases, dtype: float64
37652 37659    1126.0
Name: new_cases, dtype: float64
37653 37660    948.0
Name: new_cases, dtype: float64
37654 37661    942.0
Name: new_cases, dtype: float64
37655 37662    1353.0
Name: new_cases, dtype: float64
37656 37663    936.0
Name: new_cases, dtype: float64
37657 37664    1223.0
Name: new_cases, dtype: float64
37658 37665    1427.0
Name: new_cases, dtype: float64
37659 37666    1050.0
Name: new_cases, dtype: float64
37660 37667    891.0
Name: new_cases, dtype: float64
37661 37668    771.0
Name: new_cases, dtype: float64
37662 37669    1066.0
Name: new_cases, dtype: float64
37663 37670    994.0
Name: new_cases, dtype: float64
37664 37671    1011.0
Name: new_cases, dtype: float64
37665 37672    1037.0
Name: new_cases, dtype: float64
37666 37673    1078.0
Name: new_cases, dtype: float64
37667 37674    1058.0
Name: new_cases, dtype: float64
37668 37675    1195.0
Name: new_cases, dtype: float64
37669 37676    1220.0
Name: new_cases, dtype: float64
37670 37677    1257.0
Name: new_cases, dtype: float64
37671 37678    1297.0
Name: new_cases, dtype: float64
37672 37679    1257.0
Name: new_cases, dtype: float64
37673 37680    1273.0
Name: new_cases, dtype: float64
37674 37681    850.0
Name: new_cases, dtype: float64
37675 37682    1169.0
Name: new_cases, dtype: float64
37676 37683    1367.0
Name: new_cases, dtype: float64
37677 37684    1183.0
Name: new_cases, dtype: float64
37678 37685    1191.0
Name: new_cases, dtype: float64
37679 37686    1323.0
Name: new_cases, dtype: float64
37680 37687    1636.0
Name: new_cases, dtype: float64
37681 37688    998.0
Name: new_cases, dtype: float64
37682 37689    1129.0
Name: new_cases, dtype: float64
37683 37690    1468.0
Name: new_cases, dtype: float64
37684 37691    1586.0
Name: new_cases, dtype: float64
37685 37692    1605.0
Name: new_cases, dtype: float64
37686 37693    1603.0
Name: new_cases, dtype: float64
37687 37694    2115.0
Name: new_cases, dtype: float64
37688 37695    1745.0
Name: new_cases, dtype: float64
37689 37696    2046.0
Name: new_cases, dtype: float64
37690 37697    2150.0
Name: new_cases, dtype: float64
37691 37698    2558.0
Name: new_cases, dtype: float64
37692 37699    3132.0
Name: new_cases, dtype: float64
37693 37700    3075.0
Name: new_cases, dtype: float64
37694 37701    3552.0
Name: new_cases, dtype: float64
37695 37702    2642.0
Name: new_cases, dtype: float64
37696 37703    3337.0
Name: new_cases, dtype: float64
37697 37704    2992.0
Name: new_cases, dtype: float64
37698 37705    3692.0
Name: new_cases, dtype: float64
37699 37706    4034.0
Name: new_cases, dtype: float64
37700 37707    4508.0
Name: new_cases, dtype: float64
37701 37708    3285.0
Name: new_cases, dtype: float64
37702 37709    2828.0
Name: new_cases, dtype: float64
37703 37710    3198.0
Name: new_cases, dtype: float64
37704 37711    2543.0
Name: new_cases, dtype: float64
37705 37712    3297.0
Name: new_cases, dtype: float64
37706 37713    2869.0
Name: new_cases, dtype: float64
37707 37714    2992.0
Name: new_cases, dtype: float64
37708 37715    1834.0
Name: new_cases, dtype: float64
37709 37716    2180.0
Name: new_cases, dtype: float64
37710 37717    2479.0
Name: new_cases, dtype: float64
37711 37718    2621.0
Name: new_cases, dtype: float64
37712 37719    2783.0
Name: new_cases, dtype: float64
37713 37720    2249.0
Name: new_cases, dtype: float64
37714 37721    2451.0
Name: new_cases, dtype: float64
37715 37722    1611.0
Name: new_cases, dtype: float64
37716 37723    1170.0
Name: new_cases, dtype: float64
37717 37724    2076.0
Name: new_cases, dtype: float64
37718 37725    1992.0
Name: new_cases, dtype: float64
37719 37726    2216.0
Name: new_cases, dtype: float64
37720 37727    1842.0
Name: new_cases, dtype: float64
37721 37728    1660.0
Name: new_cases, dtype: float64
37722 37729    1743.0
Name: new_cases, dtype: float64
37723 37730    1246.0
Name: new_cases, dtype: float64
37724 37731    1239.0
Name: new_cases, dtype: float64
37725 37732    1076.0
Name: new_cases, dtype: float64
37726 37733    1358.0
Name: new_cases, dtype: float64
37727 37734    0.0
Name: new_cases, dtype: float64
37728 37735    2161.0
Name: new_cases, dtype: float64
37729 37736    879.0
Name: new_cases, dtype: float64
37730 37737    889.0
Name: new_cases, dtype: float64
37731 37738    807.0
Name: new_cases, dtype: float64
37732 37739    724.0
Name: new_cases, dtype: float64
37733 37740    886.0
Name: new_cases, dtype: float64
37734 37741    760.0
Name: new_cases, dtype: float64
37735 37742    773.0
Name: new_cases, dtype: float64
37736 37743    879.0
Name: new_cases, dtype: float64
37737 37744    754.0
Name: new_cases, dtype: float64
37738 37745    625.0
Name: new_cases, dtype: float64
37739 37746    652.0
Name: new_cases, dtype: float64
37740 37747    592.0
Name: new_cases, dtype: float64
37741 37748    668.0
Name: new_cases, dtype: float64
37742 37749    456.0
Name: new_cases, dtype: float64
37743 37750    431.0
Name: new_cases, dtype: float64
37744 37751    377.0
Name: new_cases, dtype: float64
37745 37752    488.0
Name: new_cases, dtype: float64
37746 37753    397.0
Name: new_cases, dtype: float64
37747 37754    425.0
Name: new_cases, dtype: float64
37748 37755    553.0
Name: new_cases, dtype: float64
37749 37756    438.0
Name: new_cases, dtype: float64
37750 37757    413.0
Name: new_cases, dtype: float64
37751 37758    435.0
Name: new_cases, dtype: float64
37752 37759    430.0
Name: new_cases, dtype: float64
37753 37760    366.0
Name: new_cases, dtype: float64
37754 37761    470.0
Name: new_cases, dtype: float64
37755 37762    478.0
Name: new_cases, dtype: float64
37756 37763    428.0
Name: new_cases, dtype: float64
37757 37764    274.0
Name: new_cases, dtype: float64
37758 37765    295.0
Name: new_cases, dtype: float64
37759 37766    437.0
Name: new_cases, dtype: float64
37760 37767    384.0
Name: new_cases, dtype: float64
37761 37768    414.0
Name: new_cases, dtype: float64
37762 37769    468.0
Name: new_cases, dtype: float64
37763 37770    552.0
Name: new_cases, dtype: float64
37764 37771    464.0
Name: new_cases, dtype: float64
37765 37772    496.0
Name: new_cases, dtype: float64
37766 37773    450.0
Name: new_cases, dtype: float64
37767 37774    529.0
Name: new_cases, dtype: float64
37768 37775    523.0
Name: new_cases, dtype: float64
37769 37776    603.0
Name: new_cases, dtype: float64
37770 37777    530.0
Name: new_cases, dtype: float64
37771 37778    520.0
Name: new_cases, dtype: float64
37772 37779    463.0
Name: new_cases, dtype: float64
37773 37780    497.0
Name: new_cases, dtype: float64
37774 37781    532.0
Name: new_cases, dtype: float64
37775 37782    574.0
Name: new_cases, dtype: float64
37776 37783    520.0
Name: new_cases, dtype: float64
37777 37784    614.0
Name: new_cases, dtype: float64
37778 37785    394.0
Name: new_cases, dtype: float64
37779 37786    513.0
Name: new_cases, dtype: float64
37780 37787    425.0
Name: new_cases, dtype: float64
37781 37788    527.0
Name: new_cases, dtype: float64
37782 37789    2007.0
Name: new_cases, dtype: float64
37783 37790    862.0
Name: new_cases, dtype: float64
37784 37791    645.0
Name: new_cases, dtype: float64
37785 37792    613.0
Name: new_cases, dtype: float64
37786 37793    541.0
Name: new_cases, dtype: float64
37787 37794    612.0
Name: new_cases, dtype: float64
37788 37795    771.0
Name: new_cases, dtype: float64
37789 37796    787.0
Name: new_cases, dtype: float64
37790 37797    786.0
Name: new_cases, dtype: float64
37791 37798    843.0
Name: new_cases, dtype: float64
37792 37799    590.0
Name: new_cases, dtype: float64
37793 37800    657.0
Name: new_cases, dtype: float64
37794 37801    1272.0
Name: new_cases, dtype: float64
37795 37802    254.0
Name: new_cases, dtype: float64
37796 37803   -2001.0
Name: new_cases, dtype: float64
37797 37804    814.0
Name: new_cases, dtype: float64

37798 37805    789.0
Name: new_cases, dtype: float64
37799 37806    416.0
Name: new_cases, dtype: float64
37800 37807    964.0
Name: new_cases, dtype: float64
37801 37808    679.0
Name: new_cases, dtype: float64
37802 37809    1210.0
Name: new_cases, dtype: float64
37803 37810    701.0
Name: new_cases, dtype: float64
37804 37811    662.0
Name: new_cases, dtype: float64
37805 37812    708.0
Name: new_cases, dtype: float64
37806 37813    745.0
Name: new_cases, dtype: float64
37807 37814    600.0
Name: new_cases, dtype: float64
37808 37815    479.0
Name: new_cases, dtype: float64
37809 37816    520.0
Name: new_cases, dtype: float64
37810 37817    614.0
Name: new_cases, dtype: float64
37811 37818    717.0
Name: new_cases, dtype: float64
37812 37819    698.0
Name: new_cases, dtype: float64
37813 37820    755.0
Name: new_cases, dtype: float64
37814 37821    691.0
Name: new_cases, dtype: float64
37815 37822    514.0
Name: new_cases, dtype: float64
37816 37823    563.0
Name: new_cases, dtype: float64
37817 37824    663.0
Name: new_cases, dtype: float64
37818 37825    798.0
Name: new_cases, dtype: float64
37819 37826    677.0
Name: new_cases, dtype: float64
37820 37827    724.0
Name: new_cases, dtype: float64
37821 37828    902.0
Name: new_cases, dtype: float64
37822 37829    741.0
Name: new_cases, dtype: float64
37823 37830    691.0
Name: new_cases, dtype: float64
37824 37831    803.0
Name: new_cases, dtype: float64
37825 37832    893.0
Name: new_cases, dtype: float64
37826 37833    702.0
Name: new_cases, dtype: float64
37827 37834    547.0
Name: new_cases, dtype: float64
37828 37835    612.0
Name: new_cases, dtype: float64
37829 37836    704.0
Name: new_cases, dtype: float64
37830 37837    624.0
Name: new_cases, dtype: float64
37831 37838    835.0
Name: new_cases, dtype: float64
37832 37839    769.0
Name: new_cases, dtype: float64
37833 37840    0.0
Name: new_cases, dtype: float64
37834 37841    1491.0
Name: new_cases, dtype: float64
37835 37842    867.0
Name: new_cases, dtype: float64
37836 37843    761.0
Name: new_cases, dtype: float64
37837 37844    809.0
Name: new_cases, dtype: float64
37838 37845    0.0
Name: new_cases, dtype: float64
37839 37846    2000.0
Name: new_cases, dtype: float64
37840 37847    1023.0
Name: new_cases, dtype: float64
37841 37848    677.0
Name: new_cases, dtype: float64
37842 37849    874.0
Name: new_cases, dtype: float64
37843 37850    932.0
Name: new_cases, dtype: float64
37844 37851    925.0
Name: new_cases, dtype: float64
37845 37852    1246.0
Name: new_cases, dtype: float64
37846 37853    1355.0
Name: new_cases, dtype: float64
37847 37854    951.0
Name: new_cases, dtype: float64
37848 37855    1074.0
Name: new_cases, dtype: float64
37849 37856    964.0
Name: new_cases, dtype: float64
37850 37857    836.0
Name: new_cases, dtype: float64
37851 37858    916.0
Name: new_cases, dtype: float64
37852 37859    1088.0
Name: new_cases, dtype: float64
37853 37860    1214.0
Name: new_cases, dtype: float64
37854 37861    1351.0
Name: new_cases, dtype: float64
37855 37862    751.0
Name: new_cases, dtype: float64
37856 37863    835.0
Name: new_cases, dtype: float64
37857 37864    919.0
Name: new_cases, dtype: float64
37858 37865    794.0
Name: new_cases, dtype: float64
37859 37866    1073.0
Name: new_cases, dtype: float64
37860 37867    1119.0
Name: new_cases, dtype: float64
37861 37868    997.0
Name: new_cases, dtype: float64
37862 37869    1038.0
Name: new_cases, dtype: float64
37863 37870    949.0
Name: new_cases, dtype: float64
37864 37871    844.0
Name: new_cases, dtype: float64
37865 37872    908.0
Name: new_cases, dtype: float64
37866 37873    954.0
Name: new_cases, dtype: float64
37867 37874    1028.0
Name: new_cases, dtype: float64
37868 37875    927.0
Name: new_cases, dtype: float64
37869 37876    592.0
Name: new_cases, dtype: float64
37870 37877    853.0
Name: new_cases, dtype: float64
37871 37878    459.0
Name: new_cases, dtype: float64
37872 37879    377.0
Name: new_cases, dtype: float64
37873 37880    904.0
Name: new_cases, dtype: float64
37874 37881    475.0
Name: new_cases, dtype: float64
37875 37882    418.0
Name: new_cases, dtype: float64
37876 37883    437.0
Name: new_cases, dtype: float64
37877 37884    315.0
Name: new_cases, dtype: float64
37878 37885    237.0
Name: new_cases, dtype: float64
37879 37886    222.0
Name: new_cases, dtype: float64
37880 37887    353.0
Name: new_cases, dtype: float64
37881 37888    331.0
Name: new_cases, dtype: float64
37882 37889    203.0
Name: new_cases, dtype: float64
37883 37890    243.0
Name: new_cases, dtype: float64
37884 37891    189.0
Name: new_cases, dtype: float64
37885 37892    149.0
Name: new_cases, dtype: float64
37886 37893    155.0
Name: new_cases, dtype: float64
37887 37894    223.0
Name: new_cases, dtype: float64
37888 37895    173.0
Name: new_cases, dtype: float64
37889 37896    222.0
Name: new_cases, dtype: float64
37890 37897    195.0
Name: new_cases, dtype: float64
37891 37898    174.0
Name: new_cases, dtype: float64
37892 37899    151.0
Name: new_cases, dtype: float64
37893 37900    243.0
Name: new_cases, dtype: float64
37894 37901    340.0
Name: new_cases, dtype: float64
37895 37902    475.0
Name: new_cases, dtype: float64
37896 37903    326.0
Name: new_cases, dtype: float64
37897 37904    447.0
Name: new_cases, dtype: float64
37898 37905    392.0
Name: new_cases, dtype: float64
37899 37906    337.0
Name: new_cases, dtype: float64
37900 37907    542.0
Name: new_cases, dtype: float64
37901 37908    689.0
Name: new_cases, dtype: float64
37902 37909    658.0
Name: new_cases, dtype: float64
37903 37910    551.0
Name: new_cases, dtype: float64
37904 37911    520.0
Name: new_cases, dtype: float64
37905 37912    609.0
Name: new_cases, dtype: float64
37906 37913    848.0
Name: new_cases, dtype: float64
37907 37914    1055.0
Name: new_cases, dtype: float64
37908 37915    1202.0
Name: new_cases, dtype: float64
37909 37916    1141.0
Name: new_cases, dtype: float64
37910 37917    960.0
Name: new_cases, dtype: float64
37911 37918    1030.0
Name: new_cases, dtype: float64
37912 37919    641.0
Name: new_cases, dtype: float64
37913 37920    844.0
Name: new_cases, dtype: float64
37914 37921    820.0
Name: new_cases, dtype: float64
37915 37922    851.0
Name: new_cases, dtype: float64
37916 37923    805.0
Name: new_cases, dtype: float64
37917 37924    707.0
Name: new_cases, dtype: float64
37918 37925    749.0
Name: new_cases, dtype: float64
37919 37926    644.0
Name: new_cases, dtype: float64
37920 37927    772.0
Name: new_cases, dtype: float64
37921 37928    559.0
Name: new_cases, dtype: float64
37922 37929    1284.0
Name: new_cases, dtype: float64
37923 37930    848.0
Name: new_cases, dtype: float64
37924 37931    1085.0
Name: new_cases, dtype: float64
37925 37932    739.0
Name: new_cases, dtype: float64
37926 37933    893.0
Name: new_cases, dtype: float64
37927 37934    785.0
Name: new_cases, dtype: float64
37928 37935    810.0
Name: new_cases, dtype: float64
37929 37936    927.0
Name: new_cases, dtype: float64
37930 37937    932.0
Name: new_cases, dtype: float64
37931 37938    865.0
Name: new_cases, dtype: float64
37932 37939    946.0
Name: new_cases, dtype: float64
37933 37940    821.0
Name: new_cases, dtype: float64
37934 37941    935.0
Name: new_cases, dtype: float64
37935 37942    1004.0
Name: new_cases, dtype: float64
37936 37943    1162.0
Name: new_cases, dtype: float64
37937 37944    1085.0
Name: new_cases, dtype: float64
37938 37945    1038.0
Name: new_cases, dtype: float64
37939 37946    917.0
Name: new_cases, dtype: float64
37940 37947    850.0
Name: new_cases, dtype: float64
37941 37948    959.0
Name: new_cases, dtype: float64
37942 37949    886.0
Name: new_cases, dtype: float64
37943 37950    1193.0
Name: new_cases, dtype: float64
37944 37951    984.0
Name: new_cases, dtype: float64
37945 37952    923.0
Name: new_cases, dtype: float64
37946 37953    1024.0
Name: new_cases, dtype: float64
37947 37954    720.0
Name: new_cases, dtype: float64
37948 37955    774.0
Name: new_cases, dtype: float64
37949 37956    1340.0
Name: new_cases, dtype: float64
37950 37957    987.0
Name: new_cases, dtype: float64
37951 37958    982.0
Name: new_cases, dtype: float64
37952 37959    925.0
Name: new_cases, dtype: float64
37953 37960    877.0
Name: new_cases, dtype: float64

37954 37961    737.0
Name: new_cases, dtype: float64
37955 37962    762.0
Name: new_cases, dtype: float64
37956 37963    843.0
Name: new_cases, dtype: float64
37957 37964    825.0
Name: new_cases, dtype: float64
37958 37965    694.0
Name: new_cases, dtype: float64
37959 37966    697.0
Name: new_cases, dtype: float64
37960 37967    438.0
Name: new_cases, dtype: float64
37961 37968    632.0
Name: new_cases, dtype: float64
37962 37969    461.0
Name: new_cases, dtype: float64
37963 37970    451.0
Name: new_cases, dtype: float64
37964 37971    514.0
Name: new_cases, dtype: float64
37965 37972    591.0
Name: new_cases, dtype: float64
37966 37973    557.0
Name: new_cases, dtype: float64
37967 37974    386.0
Name: new_cases, dtype: float64
37968 37975    434.0
Name: new_cases, dtype: float64
37969 37976    263.0
Name: new_cases, dtype: float64
37970 37977    425.0
Name: new_cases, dtype: float64
37971 37978    370.0
Name: new_cases, dtype: float64
37972 37979    313.0
Name: new_cases, dtype: float64
37973 37980    324.0
Name: new_cases, dtype: float64
37974 37981    325.0
Name: new_cases, dtype: float64
37975 37982    252.0
Name: new_cases, dtype: float64
37976 37983    268.0
Name: new_cases, dtype: float64
37977 37984    344.0
Name: new_cases, dtype: float64
37978 37985    346.0
Name: new_cases, dtype: float64
37979 37986    341.0
Name: new_cases, dtype: float64
37980 37987    382.0
Name: new_cases, dtype: float64
37981 37988    358.0
Name: new_cases, dtype: float64
37982 37989    353.0
Name: new_cases, dtype: float64
37983 37990    333.0
Name: new_cases, dtype: float64
37984 37991    457.0
Name: new_cases, dtype: float64
37985 37992    542.0
Name: new_cases, dtype: float64
37986 37993    427.0
Name: new_cases, dtype: float64
37987 37994    441.0
Name: new_cases, dtype: float64
37988 37995    426.0
Name: new_cases, dtype: float64
37989 37996    368.0
Name: new_cases, dtype: float64
37990 37997    380.0
Name: new_cases, dtype: float64
37991 37998    477.0
Name: new_cases, dtype: float64
37992 37999    573.0
Name: new_cases, dtype: float64
37993 38000    607.0
Name: new_cases, dtype: float64
37994 38001    670.0
Name: new_cases, dtype: float64
37995 38002    618.0
Name: new_cases, dtype: float64
37996 38003    544.0
Name: new_cases, dtype: float64
37997 38004    564.0
Name: new_cases, dtype: float64
37998 38005    587.0
Name: new_cases, dtype: float64
37999 38006    789.0
Name: new_cases, dtype: float64
38000 38007    767.0
Name: new_cases, dtype: float64
38001 38008    700.0
Name: new_cases, dtype: float64
38002 38009    753.0
Name: new_cases, dtype: float64
38003 38010    591.0
Name: new_cases, dtype: float64
38004 38011    752.0
Name: new_cases, dtype: float64
38005 38012    756.0
Name: new_cases, dtype: float64
38006 38013    1127.0
Name: new_cases, dtype: float64
38007 38014    1247.0
Name: new_cases, dtype: float64
38008 38015    1270.0
Name: new_cases, dtype: float64
38009 38016    1262.0
Name: new_cases, dtype: float64
38010 38017    1349.0
Name: new_cases, dtype: float64
38011 38018    1411.0
Name: new_cases, dtype: float64
38012 38019    1253.0
Name: new_cases, dtype: float64
38013 38020    1871.0
Name: new_cases, dtype: float64
38014 38021    1847.0
Name: new_cases, dtype: float64
38015 38022    1784.0
Name: new_cases, dtype: float64
38016 38023    1671.0
Name: new_cases, dtype: float64
38017 38024    1532.0
Name: new_cases, dtype: float64
38018 38025    1457.0
Name: new_cases, dtype: float64
38019 38026    1981.0
Name: new_cases, dtype: float64
38020 38027    1978.0
Name: new_cases, dtype: float64
38021 38028    2598.0
Name: new_cases, dtype: float64
38022 38029    2251.0
Name: new_cases, dtype: float64
38023 38030    2097.0
Name: new_cases, dtype: float64
38024 38031    2416.0
Name: new_cases, dtype: float64
38025 38032    2294.0
Name: new_cases, dtype: float64
38026 38033    2562.0
Name: new_cases, dtype: float64
38027 38034    3017.0
Name: new_cases, dtype: float64
38028 38035    2132.0
Name: new_cases, dtype: float64
38029 38036    4585.0
Name: new_cases, dtype: float64
38030 38037    2948.0
Name: new_cases, dtype: float64
38031 38038    3223.0
Name: new_cases, dtype: float64
38032 38039    3670.0
Name: new_cases, dtype: float64
38033 38040    3899.0
Name: new_cases, dtype: float64
38034 38041    3907.0
Name: new_cases, dtype: float64
38035 38042    4013.0
Name: new_cases, dtype: float64
38036 38043    4070.0
Name: new_cases, dtype: float64
38037 38044    3795.0
Name: new_cases, dtype: float64
38038 38045    3415.0
Name: new_cases, dtype: float64
38039 38046    3711.0
Name: new_cases, dtype: float64
38040 38047    4199.0
Name: new_cases, dtype: float64
38041 38048    4426.0
Name: new_cases, dtype: float64
38042 38049    4390.0
Name: new_cases, dtype: float64
38043 38050    4076.0
Name: new_cases, dtype: float64
38044 38051    3744.0
Name: new_cases, dtype: float64
38045 38052    4290.0
Name: new_cases, dtype: float64
38046 38053    4326.0
Name: new_cases, dtype: float64
38047 38054    4148.0
Name: new_cases, dtype: float64
38048 38055    5120.0
Name: new_cases, dtype: float64
38049 38056    4680.0
Name: new_cases, dtype: float64
38050 38057    4559.0
Name: new_cases, dtype: float64
38051 38058    4325.0
Name: new_cases, dtype: float64
38052 38059    3026.0
Name: new_cases, dtype: float64
38053 38060    7146.0
Name: new_cases, dtype: float64
38054 38061    6324.0
Name: new_cases, dtype: float64
38055 38062    6629.0
Name: new_cases, dtype: float64
38056 38063    6985.0
Name: new_cases, dtype: float64
38057 38064    6599.0
Name: new_cases, dtype: float64
38058 38065    5606.0
Name: new_cases, dtype: float64
38059 38066    5989.0
Name: new_cases, dtype: float64
38060 38067    7799.0
Name: new_cases, dtype: float64
38061 38068    8314.0
Name: new_cases, dtype: float64
38062 38069    8773.0
Name: new_cases, dtype: float64
38063 38070    9999.0
Name: new_cases, dtype: float64
38064 38071    11194.0
Name: new_cases, dtype: float64
38065 38072    8594.0
Name: new_cases, dtype: float64
38066 38073    8212.0
Name: new_cases, dtype: float64
38067 38074    10082.0
Name: new_cases, dtype: float64
38068 38075    20578.0
Name: new_cases, dtype: float64
38069 38076    13386.0
Name: new_cases, dtype: float64
38070 38077    12487.0
Name: new_cases, dtype: float64
38071 38078    11229.0
Name: new_cases, dtype: float64
38072 38079    0.0
Name: new_cases, dtype: float64
38073 38080    0.0
Name: new_cases, dtype: float64
38074 38081    41035.0
Name: new_cases, dtype: float64
38075 38082    13000.0
Name: new_cases, dtype: float64
38076 38083    23228.0
Name: new_cases, dtype: float64
38077 38084    21403.0
Name: new_cases, dtype: float64
38078 38085    18695.0
Name: new_cases, dtype: float64
38079 38086    20885.0
Name: new_cases, dtype: float64
38080 38087    7954.0
Name: new_cases, dtype: float64
38081 38088    8801.0
Name: new_cases, dtype: float64
38082 38089    25073.0
Name: new_cases, dtype: float64
38083 38090    28283.0
Name: new_cases, dtype: float64
38084 38091    25995.0
Name: new_cases, dtype: float64
38085 38092    18261.0
Name: new_cases, dtype: float64
38086 38093    12588.0
Name: new_cases, dtype: float64
38087 37415    1.0
Name: new_cases, dtype: float64
38088 37416    0.0
Name: new_cases, dtype: float64
38089 37417    2.0
Name: new_cases, dtype: float64
38090 37418    4.0
Name: new_cases, dtype: float64
38091 37419    0.0
Name: new_cases, dtype: float64
38092 37420    13.0
Name: new_cases, dtype: float64
38093 37421    0.0
Name: new_cases, dtype: float64
39414 39421    3.0
Name: new_cases, dtype: float64
39415 39422    0.0
Name: new_cases, dtype: float64
39416 39423    0.0
Name: new_cases, dtype: float64
39417 39424    0.0
Name: new_cases, dtype: float64
39418 39425    0.0
Name: new_cases, dtype: float64
39419 39426    0.0
Name: new_cases, dtype: float64
39420 39427    6.0
Name: new_cases, dtype: float64
39421 39428    0.0
Name: new_cases, dtype: float64
39422 39429    0.0
Name: new_cases, dtype: float64
39423 39430    10.0
Name: new_cases, dtype: float64
39424 39431    0.0
Name: new_cases, dtype: float64
39425 39432    13.0
Name: new_cases, dtype: float64
39426 39433    38.0
Name: new_cases, dtype: float64
39427 39434    40.0
Name: new_cases, dtype: float64
39428 39435    90.0
Name: new_cases, dtype: float64
39429 39436    43.0
Name: new_cases, dtype: float64
39430 39437    67.0
Name: new_cases, dtype: float64
39431 39438    80.0
Name: new_cases, dtype: float64

39432 39439    96.0
Name: new_cases, dtype: float64
39433 39440    93.0
Name: new_cases, dtype: float64
39434 39441    138.0
Name: new_cases, dtype: float64
39435 39442    140.0
Name: new_cases, dtype: float64
39436 39443    42.0
Name: new_cases, dtype: float64
39437 39444    208.0
Name: new_cases, dtype: float64
39438 39445    175.0
Name: new_cases, dtype: float64
39439 39446    96.0
Name: new_cases, dtype: float64
39440 39447    108.0
Name: new_cases, dtype: float64
39441 39448    0.0
Name: new_cases, dtype: float64
39442 39449    257.0
Name: new_cases, dtype: float64
39443 39450    83.0
Name: new_cases, dtype: float64
39444 39451    128.0
Name: new_cases, dtype: float64
39445 39452    155.0
Name: new_cases, dtype: float64
39446 39453    238.0
Name: new_cases, dtype: float64
39447 39454    271.0
Name: new_cases, dtype: float64
39448 39455    139.0
Name: new_cases, dtype: float64
39449 39456    208.0
Name: new_cases, dtype: float64
39450 39457    200.0
Name: new_cases, dtype: float64
39451 39458    119.0
Name: new_cases, dtype: float64
39452 39459    328.0
Name: new_cases, dtype: float64
39453 39460    141.0
Name: new_cases, dtype: float64
39454 39461    371.0
Name: new_cases, dtype: float64
39455 39462    209.0
Name: new_cases, dtype: float64
39456 39463    345.0
Name: new_cases, dtype: float64
39457 39464    284.0
Name: new_cases, dtype: float64
39458 39465    80.0
Name: new_cases, dtype: float64
39459 39466    256.0
Name: new_cases, dtype: float64
39460 39467    243.0
Name: new_cases, dtype: float64
39461 39468    206.0
Name: new_cases, dtype: float64
39462 39469    177.0
Name: new_cases, dtype: float64
39463 39470    209.0
Name: new_cases, dtype: float64
39464 39471    158.0
Name: new_cases, dtype: float64
39465 39472    123.0
Name: new_cases, dtype: float64
39466 39473    236.0
Name: new_cases, dtype: float64
39467 39474    320.0
Name: new_cases, dtype: float64
39468 39475    316.0
Name: new_cases, dtype: float64
39469 39476    290.0
Name: new_cases, dtype: float64
39470 39477    376.0
Name: new_cases, dtype: float64
39471 39478    281.0
Name: new_cases, dtype: float64
39472 39479    245.0
Name: new_cases, dtype: float64
39473 39480    327.0
Name: new_cases, dtype: float64
39474 39481    288.0
Name: new_cases, dtype: float64
39475 39482    281.0
Name: new_cases, dtype: float64
39476 39483    506.0
Name: new_cases, dtype: float64
39477 39484    465.0
Name: new_cases, dtype: float64
39478 39485    287.0
Name: new_cases, dtype: float64
39479 39486    266.0
Name: new_cases, dtype: float64
39480 39487    296.0
Name: new_cases, dtype: float64
39481 39488    124.0
Name: new_cases, dtype: float64
39482 39489    419.0
Name: new_cases, dtype: float64
39483 39490    371.0
Name: new_cases, dtype: float64
39484 39491    204.0
Name: new_cases, dtype: float64
39485 39492    411.0
Name: new_cases, dtype: float64
39486 39493    498.0
Name: new_cases, dtype: float64
39487 39494    254.0
Name: new_cases, dtype: float64
39488 39495    180.0
Name: new_cases, dtype: float64
39489 39496    332.0
Name: new_cases, dtype: float64
39490 39497    433.0
Name: new_cases, dtype: float64
39491 39498    379.0
Name: new_cases, dtype: float64
39492 39499    272.0
Name: new_cases, dtype: float64
39493 39500    191.0
Name: new_cases, dtype: float64
39494 39501    459.0
Name: new_cases, dtype: float64
39495 39502    345.0
Name: new_cases, dtype: float64
39496 39503    463.0
Name: new_cases, dtype: float64
39497 39504    377.0
Name: new_cases, dtype: float64
39498 39505    377.0
Name: new_cases, dtype: float64
39499 39506    287.0
Name: new_cases, dtype: float64
39500 39507    180.0
Name: new_cases, dtype: float64
39501 39508    288.0
Name: new_cases, dtype: float64
39502 39509    279.0
Name: new_cases, dtype: float64
39503 39510    389.0
Name: new_cases, dtype: float64
39504 39511    487.0
Name: new_cases, dtype: float64
39505 39512    405.0
Name: new_cases, dtype: float64
39506 39513    526.0
Name: new_cases, dtype: float64
39507 39514    289.0
Name: new_cases, dtype: float64
39508 39515    393.0
Name: new_cases, dtype: float64
39509 39516    629.0
Name: new_cases, dtype: float64
39510 39517    571.0
Name: new_cases, dtype: float64
39511 39518    564.0
Name: new_cases, dtype: float64
39512 39519    390.0
Name: new_cases, dtype: float64
39513 39520    309.0
Name: new_cases, dtype: float64
39514 39521    415.0
Name: new_cases, dtype: float64
39515 39522    419.0
Name: new_cases, dtype: float64
39516 39523    540.0
Name: new_cases, dtype: float64
39517 39524    423.0
Name: new_cases, dtype: float64
39518 39525    710.0
Name: new_cases, dtype: float64
39519 39526    899.0
Name: new_cases, dtype: float64
39520 39527    693.0
Name: new_cases, dtype: float64
39521 39528    566.0
Name: new_cases, dtype: float64
39522 39529    695.0
Name: new_cases, dtype: float64
39523 39530    510.0
Name: new_cases, dtype: float64
39524 39531    623.0
Name: new_cases, dtype: float64
39525 39532    855.0
Name: new_cases, dtype: float64
39526 39533    754.0
Name: new_cases, dtype: float64
39527 39534    443.0
Name: new_cases, dtype: float64
39528 39535    752.0
Name: new_cases, dtype: float64
39529 39536    819.0
Name: new_cases, dtype: float64
39530 39537    810.0
Name: new_cases, dtype: float64
39531 39538    951.0
Name: new_cases, dtype: float64
39532 39539    1036.0
Name: new_cases, dtype: float64
39533 39540    1241.0
Name: new_cases, dtype: float64
39534 39541    703.0
Name: new_cases, dtype: float64
39535 39542    302.0
Name: new_cases, dtype: float64
39536 39543    1158.0
Name: new_cases, dtype: float64
39537 39544    1202.0
Name: new_cases, dtype: float64
39538 39545    1125.0
Name: new_cases, dtype: float64
39539 39546    1199.0
Name: new_cases, dtype: float64
39540 39547    1418.0
Name: new_cases, dtype: float64
39541 39548    974.0
Name: new_cases, dtype: float64
39542 39549    799.0
Name: new_cases, dtype: float64
39543 39550    1366.0
Name: new_cases, dtype: float64
39544 39551    1072.0
Name: new_cases, dtype: float64
39545 39552    1370.0
Name: new_cases, dtype: float64
39546 39553    1406.0
Name: new_cases, dtype: float64
39547 39554    1336.0
Name: new_cases, dtype: float64
39548 39555    1101.0
Name: new_cases, dtype: float64
39549 39556    841.0
Name: new_cases, dtype: float64
39550 39557    1246.0
Name: new_cases, dtype: float64
39551 39558    1572.0
Name: new_cases, dtype: float64
39552 39559    1462.0
Name: new_cases, dtype: float64
39553 39560    1819.0
Name: new_cases, dtype: float64
39554 39561    2012.0
Name: new_cases, dtype: float64
39555 39562    1248.0
Name: new_cases, dtype: float64
39556 39563    534.0
Name: new_cases, dtype: float64
39557 39564    1492.0
Name: new_cases, dtype: float64
39558 39565    1733.0
Name: new_cases, dtype: float64
39559 39566    1734.0
Name: new_cases, dtype: float64
39560 39567    1766.0
Name: new_cases, dtype: float64
39561 39568    828.0
Name: new_cases, dtype: float64
39562 39569    874.0
Name: new_cases, dtype: float64
39563 39570    1178.0
Name: new_cases, dtype: float64
39564 39571    1365.0
Name: new_cases, dtype: float64
39565 39572    876.0
Name: new_cases, dtype: float64
39566 39573    1173.0
Name: new_cases, dtype: float64
39567 39574    1069.0
Name: new_cases, dtype: float64
39568 39575    954.0
Name: new_cases, dtype: float64
39569 39576    767.0
Name: new_cases, dtype: float64
39570 39577    595.0
Name: new_cases, dtype: float64
39571 39578    1130.0
Name: new_cases, dtype: float64
39572 39579    910.0
Name: new_cases, dtype: float64
39573 39580    1354.0
Name: new_cases, dtype: float64
39574 39581    1057.0
Name: new_cases, dtype: float64
39575 39582    764.0
Name: new_cases, dtype: float64
39576 39583    428.0
Name: new_cases, dtype: float64
39577 39584    386.0
Name: new_cases, dtype: float64
39578 39585    1004.0
Name: new_cases, dtype: float64
39579 39586    883.0
Name: new_cases, dtype: float64
39580 39587    857.0
Name: new_cases, dtype: float64
39581 39588    694.0
Name: new_cases, dtype: float64
39582 39589    600.0
Name: new_cases, dtype: float64
39583 39590    447.0
Name: new_cases, dtype: float64
39584 39591    609.0
Name: new_cases, dtype: float64
39585 39592    340.0
Name: new_cases, dtype: float64
39586 39593    407.0
Name: new_cases, dtype: float64
39587 39594    426.0
Name: new_cases, dtype: float64
39588 39595    342.0
Name: new_cases, dtype: float64
39589 39596    509.0
Name: new_cases, dtype: float64

39590 39597    474.0
Name: new_cases, dtype: float64
39591 39598    264.0
Name: new_cases, dtype: float64
39592 39599    648.0
Name: new_cases, dtype: float64
39593 39600    1002.0
Name: new_cases, dtype: float64
39594 39601    0.0
Name: new_cases, dtype: float64
39595 39602    2147.0
Name: new_cases, dtype: float64
39596 39603    557.0
Name: new_cases, dtype: float64
39597 39604    565.0
Name: new_cases, dtype: float64
39598 39605    233.0
Name: new_cases, dtype: float64
39599 39606    806.0
Name: new_cases, dtype: float64
39600 39607    779.0
Name: new_cases, dtype: float64
39601 39608    516.0
Name: new_cases, dtype: float64
39602 39609    860.0
Name: new_cases, dtype: float64
39603 39610    568.0
Name: new_cases, dtype: float64
39604 39611    450.0
Name: new_cases, dtype: float64
39605 39612    693.0
Name: new_cases, dtype: float64
39606 39613    718.0
Name: new_cases, dtype: float64
39607 39614    615.0
Name: new_cases, dtype: float64
39608 39615    596.0
Name: new_cases, dtype: float64
39609 39616    968.0
Name: new_cases, dtype: float64
39610 39617    589.0
Name: new_cases, dtype: float64
39611 39618    494.0
Name: new_cases, dtype: float64
39612 39619    486.0
Name: new_cases, dtype: float64
39613 39620    468.0
Name: new_cases, dtype: float64
39614 39621    385.0
Name: new_cases, dtype: float64
39615 39622    475.0
Name: new_cases, dtype: float64
39616 39623    360.0
Name: new_cases, dtype: float64
39617 39624    429.0
Name: new_cases, dtype: float64
39618 39625    280.0
Name: new_cases, dtype: float64
39619 39626    234.0
Name: new_cases, dtype: float64
39620 39627    309.0
Name: new_cases, dtype: float64
39621 39628    519.0
Name: new_cases, dtype: float64
39622 39629    622.0
Name: new_cases, dtype: float64
39623 39630    576.0
Name: new_cases, dtype: float64
39624 39631    554.0
Name: new_cases, dtype: float64
39625 39632    574.0
Name: new_cases, dtype: float64
39626 39633    317.0
Name: new_cases, dtype: float64
39627 39634    777.0
Name: new_cases, dtype: float64
39628 39635    724.0
Name: new_cases, dtype: float64
39629 39636    585.0
Name: new_cases, dtype: float64
39630 39637    557.0
Name: new_cases, dtype: float64
39631 39638    463.0
Name: new_cases, dtype: float64
39632 39639    366.0
Name: new_cases, dtype: float64
39633 39640    165.0
Name: new_cases, dtype: float64
39634 39641    654.0
Name: new_cases, dtype: float64
39635 39642    404.0
Name: new_cases, dtype: float64
39636 39643    384.0
Name: new_cases, dtype: float64
39637 39644    475.0
Name: new_cases, dtype: float64
39638 39645    422.0
Name: new_cases, dtype: float64
39639 39646    320.0
Name: new_cases, dtype: float64
39640 39647    306.0
Name: new_cases, dtype: float64
39641 39648    425.0
Name: new_cases, dtype: float64
39642 39649    475.0
Name: new_cases, dtype: float64
39643 39650    0.0
Name: new_cases, dtype: float64
39644 39651    1145.0
Name: new_cases, dtype: float64
39645 39652    509.0
Name: new_cases, dtype: float64
39646 39653    316.0
Name: new_cases, dtype: float64
39647 39654    165.0
Name: new_cases, dtype: float64
39648 39655    562.0
Name: new_cases, dtype: float64
39649 39656    343.0
Name: new_cases, dtype: float64
39650 39657    419.0
Name: new_cases, dtype: float64
39651 39658    686.0
Name: new_cases, dtype: float64
39652 39659    314.0
Name: new_cases, dtype: float64
39653 39660    259.0
Name: new_cases, dtype: float64
39654 39661    257.0
Name: new_cases, dtype: float64
39655 39662    430.0
Name: new_cases, dtype: float64
39656 39663    546.0
Name: new_cases, dtype: float64
39657 39664    476.0
Name: new_cases, dtype: float64
39658 39665    345.0
Name: new_cases, dtype: float64
39659 39666    537.0
Name: new_cases, dtype: float64
39660 39667    421.0
Name: new_cases, dtype: float64
39661 39668    528.0
Name: new_cases, dtype: float64
39662 39669    134.0
Name: new_cases, dtype: float64
39663 39670    371.0
Name: new_cases, dtype: float64
39664 39671    918.0
Name: new_cases, dtype: float64
39665 39672    671.0
Name: new_cases, dtype: float64
39666 39673    499.0
Name: new_cases, dtype: float64
39667 39674    479.0
Name: new_cases, dtype: float64
39668 39675    494.0
Name: new_cases, dtype: float64
39669 39676    460.0
Name: new_cases, dtype: float64
39670 39677    1026.0
Name: new_cases, dtype: float64
39671 39678    601.0
Name: new_cases, dtype: float64
39672 39679    986.0
Name: new_cases, dtype: float64
39673 39680    640.0
Name: new_cases, dtype: float64
39674 39681    419.0
Name: new_cases, dtype: float64
39675 39682    282.0
Name: new_cases, dtype: float64
39676 39683    285.0
Name: new_cases, dtype: float64
39677 39684    1526.0
Name: new_cases, dtype: float64
39678 39685    855.0
Name: new_cases, dtype: float64
39679 39686    876.0
Name: new_cases, dtype: float64
39680 39687    820.0
Name: new_cases, dtype: float64
39681 39688    515.0
Name: new_cases, dtype: float64
39682 39689    314.0
Name: new_cases, dtype: float64
39683 39690    895.0
Name: new_cases, dtype: float64
39684 39691    812.0
Name: new_cases, dtype: float64
39685 39692    671.0
Name: new_cases, dtype: float64
39686 39693    975.0
Name: new_cases, dtype: float64
39687 39694    798.0
Name: new_cases, dtype: float64
39688 39695    685.0
Name: new_cases, dtype: float64
39689 39696    492.0
Name: new_cases, dtype: float64
39690 39697    531.0
Name: new_cases, dtype: float64
39691 39698    1560.0
Name: new_cases, dtype: float64
39692 39699    731.0
Name: new_cases, dtype: float64
39693 39700    1133.0
Name: new_cases, dtype: float64
39694 39701    1107.0
Name: new_cases, dtype: float64
39695 39702    492.0
Name: new_cases, dtype: float64
39696 39703    613.0
Name: new_cases, dtype: float64
39697 39704    788.0
Name: new_cases, dtype: float64
39698 39705    720.0
Name: new_cases, dtype: float64
39699 39706    624.0
Name: new_cases, dtype: float64
39700 39707    1135.0
Name: new_cases, dtype: float64
39701 39708    1322.0
Name: new_cases, dtype: float64
39702 39709    666.0
Name: new_cases, dtype: float64
39703 39710    878.0
Name: new_cases, dtype: float64
39704 39711    566.0
Name: new_cases, dtype: float64
39705 39712    1158.0
Name: new_cases, dtype: float64
39706 39713    1381.0
Name: new_cases, dtype: float64
39707 39714    905.0
Name: new_cases, dtype: float64
39708 39715    824.0
Name: new_cases, dtype: float64
39709 39716    641.0
Name: new_cases, dtype: float64
39710 39717    860.0
Name: new_cases, dtype: float64
39711 39718    1314.0
Name: new_cases, dtype: float64
39712 39719    1206.0
Name: new_cases, dtype: float64
39713 39720    1433.0
Name: new_cases, dtype: float64
39714 39721    747.0
Name: new_cases, dtype: float64
39715 39722    366.0
Name: new_cases, dtype: float64
39716 39723    2043.0
Name: new_cases, dtype: float64
39717 39724    475.0
Name: new_cases, dtype: float64
39718 39725    529.0
Name: new_cases, dtype: float64
39719 39726    1115.0
Name: new_cases, dtype: float64
39720 39727    1045.0
Name: new_cases, dtype: float64
39721 39728    2106.0
Name: new_cases, dtype: float64
39722 39729    1459.0
Name: new_cases, dtype: float64
39723 39730    1179.0
Name: new_cases, dtype: float64
39724 39731    1506.0
Name: new_cases, dtype: float64
39725 39732    1595.0
Name: new_cases, dtype: float64
39726 39733    1104.0
Name: new_cases, dtype: float64
39727 39734    1482.0
Name: new_cases, dtype: float64
39728 39735    2370.0
Name: new_cases, dtype: float64
39729 39736    1779.0
Name: new_cases, dtype: float64
39730 39737    1848.0
Name: new_cases, dtype: float64
39731 39738    1625.0
Name: new_cases, dtype: float64
39732 39739    1532.0
Name: new_cases, dtype: float64
39733 39740    1549.0
Name: new_cases, dtype: float64
39734 39741    1473.0
Name: new_cases, dtype: float64
39735 39742    1362.0
Name: new_cases, dtype: float64
39736 39743    1439.0
Name: new_cases, dtype: float64
39737 39744    1216.0
Name: new_cases, dtype: float64
39738 39745    1143.0
Name: new_cases, dtype: float64
39739 39746    1150.0
Name: new_cases, dtype: float64
39740 39747    1155.0
Name: new_cases, dtype: float64
39741 39748    1802.0
Name: new_cases, dtype: float64
39742 39749    2141.0
Name: new_cases, dtype: float64
39743 39750    1507.0
Name: new_cases, dtype: float64
39744 39751    1026.0
Name: new_cases, dtype: float64
39745 39752    834.0
Name: new_cases, dtype: float64
39746 39753    1357.0
Name: new_cases, dtype: float64
39747 39754    1671.0
Name: new_cases, dtype: float64
39748 39755    1478.0
Name: new_cases, dtype: float64
39749 39756    1722.0
Name: new_cases, dtype: float64

39750 39757    1250.0
Name: new_cases, dtype: float64
39751 39758    721.0
Name: new_cases, dtype: float64
39752 39759    419.0
Name: new_cases, dtype: float64
39753 39760    934.0
Name: new_cases, dtype: float64
39754 39761    1242.0
Name: new_cases, dtype: float64
39755 39762    1050.0
Name: new_cases, dtype: float64
39756 39763    1131.0
Name: new_cases, dtype: float64
39757 39764    873.0
Name: new_cases, dtype: float64
39758 39765    795.0
Name: new_cases, dtype: float64
39759 39766    532.0
Name: new_cases, dtype: float64
39760 39767    642.0
Name: new_cases, dtype: float64
39761 39768    1043.0
Name: new_cases, dtype: float64
39762 39769    818.0
Name: new_cases, dtype: float64
39763 39770    904.0
Name: new_cases, dtype: float64
39764 39771    960.0
Name: new_cases, dtype: float64
39765 39772    420.0
Name: new_cases, dtype: float64
39766 39773    328.0
Name: new_cases, dtype: float64
39767 39774    673.0
Name: new_cases, dtype: float64
39768 39775    746.0
Name: new_cases, dtype: float64
39769 39776    576.0
Name: new_cases, dtype: float64
39770 39777    804.0
Name: new_cases, dtype: float64
39771 39778    608.0
Name: new_cases, dtype: float64
39772 39779    381.0
Name: new_cases, dtype: float64
39773 39780    203.0
Name: new_cases, dtype: float64
39774 39781    572.0
Name: new_cases, dtype: float64
39775 39782    619.0
Name: new_cases, dtype: float64
39776 39783    695.0
Name: new_cases, dtype: float64
39777 39784    573.0
Name: new_cases, dtype: float64
39778 39785    587.0
Name: new_cases, dtype: float64
39779 39786    279.0
Name: new_cases, dtype: float64
39780 39787    252.0
Name: new_cases, dtype: float64
39781 39788    390.0
Name: new_cases, dtype: float64
39782 39789    755.0
Name: new_cases, dtype: float64
39783 39790    529.0
Name: new_cases, dtype: float64
39784 39791    164.0
Name: new_cases, dtype: float64
39785 39792    429.0
Name: new_cases, dtype: float64
39786 39793    254.0
Name: new_cases, dtype: float64
39787 39794    495.0
Name: new_cases, dtype: float64
39788 39795    570.0
Name: new_cases, dtype: float64
39789 39796    615.0
Name: new_cases, dtype: float64
39790 39797    523.0
Name: new_cases, dtype: float64
39791 39798    487.0
Name: new_cases, dtype: float64
39792 39799    474.0
Name: new_cases, dtype: float64
39793 39800    313.0
Name: new_cases, dtype: float64
39794 39801    401.0
Name: new_cases, dtype: float64
39795 39802    402.0
Name: new_cases, dtype: float64
39796 39803    389.0
Name: new_cases, dtype: float64
39797 39804    364.0
Name: new_cases, dtype: float64
39798 39805    250.0
Name: new_cases, dtype: float64
39799 39806    401.0
Name: new_cases, dtype: float64
39800 39807    199.0
Name: new_cases, dtype: float64
39801 39808    202.0
Name: new_cases, dtype: float64
39802 39809    343.0
Name: new_cases, dtype: float64
39803 39810    469.0
Name: new_cases, dtype: float64
39804 39811    585.0
Name: new_cases, dtype: float64
39805 39812    355.0
Name: new_cases, dtype: float64
39806 39813    159.0
Name: new_cases, dtype: float64
39807 39814    140.0
Name: new_cases, dtype: float64
39808 39815    168.0
Name: new_cases, dtype: float64
39809 39816    334.0
Name: new_cases, dtype: float64
39810 39817    1094.0
Name: new_cases, dtype: float64
39811 39818    532.0
Name: new_cases, dtype: float64
39812 39819    623.0
Name: new_cases, dtype: float64
39813 39820    512.0
Name: new_cases, dtype: float64
39814 39821    341.0
Name: new_cases, dtype: float64
39815 39822    598.0
Name: new_cases, dtype: float64
39816 39823    623.0
Name: new_cases, dtype: float64
39817 39824    379.0
Name: new_cases, dtype: float64
39818 39825    494.0
Name: new_cases, dtype: float64
39819 39826    494.0
Name: new_cases, dtype: float64
39820 39827    502.0
Name: new_cases, dtype: float64
39821 39828    402.0
Name: new_cases, dtype: float64
39822 39829    317.0
Name: new_cases, dtype: float64
39823 39830    556.0
Name: new_cases, dtype: float64
39824 39831    531.0
Name: new_cases, dtype: float64
39825 39832    535.0
Name: new_cases, dtype: float64
39826 39833    474.0
Name: new_cases, dtype: float64
39827 39834    919.0
Name: new_cases, dtype: float64
39828 39835    540.0
Name: new_cases, dtype: float64
39829 39836    78.0
Name: new_cases, dtype: float64
39830 39837    338.0
Name: new_cases, dtype: float64
39831 39838    395.0
Name: new_cases, dtype: float64
39832 39839    347.0
Name: new_cases, dtype: float64
39833 39840    300.0
Name: new_cases, dtype: float64
39834 39841    594.0
Name: new_cases, dtype: float64
39835 39842    226.0
Name: new_cases, dtype: float64
39836 39843    389.0
Name: new_cases, dtype: float64
39837 39844    491.0
Name: new_cases, dtype: float64
39838 39845    623.0
Name: new_cases, dtype: float64
39839 39846    774.0
Name: new_cases, dtype: float64
39840 39847    642.0
Name: new_cases, dtype: float64
39841 39848    948.0
Name: new_cases, dtype: float64
39842 39849    560.0
Name: new_cases, dtype: float64
39843 39850    701.0
Name: new_cases, dtype: float64
39844 39851    688.0
Name: new_cases, dtype: float64
39845 39852    822.0
Name: new_cases, dtype: float64
39846 39853    1059.0
Name: new_cases, dtype: float64
39847 39854    894.0
Name: new_cases, dtype: float64
39848 39855    916.0
Name: new_cases, dtype: float64
39849 39856    731.0
Name: new_cases, dtype: float64
39850 39857    630.0
Name: new_cases, dtype: float64
39851 39858    1016.0
Name: new_cases, dtype: float64
39852 39859    1429.0
Name: new_cases, dtype: float64
39853 39860    636.0
Name: new_cases, dtype: float64
39854 39861    1055.0
Name: new_cases, dtype: float64
39855 39862    1044.0
Name: new_cases, dtype: float64
39856 39863    838.0
Name: new_cases, dtype: float64
39857 39864    644.0
Name: new_cases, dtype: float64
39858 39865    1058.0
Name: new_cases, dtype: float64
39859 39866    1765.0
Name: new_cases, dtype: float64
39860 39867    1254.0
Name: new_cases, dtype: float64
39861 39868    1238.0
Name: new_cases, dtype: float64
39862 39869    1384.0
Name: new_cases, dtype: float64
39863 39870    876.0
Name: new_cases, dtype: float64
39864 39871    1235.0
Name: new_cases, dtype: float64
39865 39872    1659.0
Name: new_cases, dtype: float64
39866 39873    1439.0
Name: new_cases, dtype: float64
39867 39874    1295.0
Name: new_cases, dtype: float64
39868 39875    1267.0
Name: new_cases, dtype: float64
39869 39876    1397.0
Name: new_cases, dtype: float64
39870 39877    906.0
Name: new_cases, dtype: float64
39871 39878    1004.0
Name: new_cases, dtype: float64
39872 39879    1440.0
Name: new_cases, dtype: float64
39873 39880    1141.0
Name: new_cases, dtype: float64
39874 39881    1129.0
Name: new_cases, dtype: float64
39875 39882    1149.0
Name: new_cases, dtype: float64
39876 39883    803.0
Name: new_cases, dtype: float64
39877 39884    827.0
Name: new_cases, dtype: float64
39878 39885    914.0
Name: new_cases, dtype: float64
39879 39886    1442.0
Name: new_cases, dtype: float64
39880 39887    982.0
Name: new_cases, dtype: float64
39881 39888    1216.0
Name: new_cases, dtype: float64
39882 39889    1784.0
Name: new_cases, dtype: float64
39883 39890    972.0
Name: new_cases, dtype: float64
39884 39891    858.0
Name: new_cases, dtype: float64
39885 39892    723.0
Name: new_cases, dtype: float64
39886 39893    886.0
Name: new_cases, dtype: float64
39887 39894    882.0
Name: new_cases, dtype: float64
39888 39895    937.0
Name: new_cases, dtype: float64
39889 39896    998.0
Name: new_cases, dtype: float64
39890 39897    707.0
Name: new_cases, dtype: float64
39891 39898    872.0
Name: new_cases, dtype: float64
39892 39899    714.0
Name: new_cases, dtype: float64
39893 39900    857.0
Name: new_cases, dtype: float64
39894 39901    972.0
Name: new_cases, dtype: float64
39895 39902    1368.0
Name: new_cases, dtype: float64
39896 39903    815.0
Name: new_cases, dtype: float64
39897 39904    566.0
Name: new_cases, dtype: float64
39898 39905    589.0
Name: new_cases, dtype: float64
39899 39906    713.0
Name: new_cases, dtype: float64
39900 39907    697.0
Name: new_cases, dtype: float64
39901 39908    885.0
Name: new_cases, dtype: float64
39902 39909    558.0
Name: new_cases, dtype: float64
39903 39910    669.0
Name: new_cases, dtype: float64
39904 39911    628.0
Name: new_cases, dtype: float64
39905 39912    863.0
Name: new_cases, dtype: float64
39906 39913    535.0
Name: new_cases, dtype: float64
39907 39914    530.0
Name: new_cases, dtype: float64
39908 39915    535.0
Name: new_cases, dtype: float64
39909 39916    549.0
Name: new_cases, dtype: float64
39910 39917    454.0
Name: new_cases, dtype: float64
39911 39918    428.0
Name: new_cases, dtype: float64
39912 39919    163.0
Name: new_cases, dtype: float64
39913 39920    237.0
Name: new_cases, dtype: float64
39914 39921    316.0
Name: new_cases, dtype: float64
39915 39922    611.0
Name: new_cases, dtype: float64
39916 39923    400.0
Name: new_cases, dtype: float64
39917 39924    367.0
Name: new_cases, dtype: float64

39918 39925    384.0
Name: new_cases, dtype: float64
39919 39926    177.0
Name: new_cases, dtype: float64
39920 39927    268.0
Name: new_cases, dtype: float64
39921 39928    316.0
Name: new_cases, dtype: float64
39922 39929    365.0
Name: new_cases, dtype: float64
39923 39930    331.0
Name: new_cases, dtype: float64
39924 39931    395.0
Name: new_cases, dtype: float64
39925 39932    362.0
Name: new_cases, dtype: float64
39926 39933    393.0
Name: new_cases, dtype: float64
39927 39934    190.0
Name: new_cases, dtype: float64
39928 39935    336.0
Name: new_cases, dtype: float64
39929 39936    326.0
Name: new_cases, dtype: float64
39930 39937    317.0
Name: new_cases, dtype: float64
39931 39938    322.0
Name: new_cases, dtype: float64
39932 39939    344.0
Name: new_cases, dtype: float64
39933 39940    130.0
Name: new_cases, dtype: float64
39934 39941    211.0
Name: new_cases, dtype: float64
39935 39942    282.0
Name: new_cases, dtype: float64
39936 39943    207.0
Name: new_cases, dtype: float64
39937 39944    312.0
Name: new_cases, dtype: float64
39938 39945    323.0
Name: new_cases, dtype: float64
39939 39946    216.0
Name: new_cases, dtype: float64
39940 39947    283.0
Name: new_cases, dtype: float64
39941 39948    51.0
Name: new_cases, dtype: float64
39942 39949    183.0
Name: new_cases, dtype: float64
39943 39950    304.0
Name: new_cases, dtype: float64
39944 39951    373.0
Name: new_cases, dtype: float64
39945 39952    267.0
Name: new_cases, dtype: float64
39946 39953    198.0
Name: new_cases, dtype: float64
39947 39954    191.0
Name: new_cases, dtype: float64
39948 39955    223.0
Name: new_cases, dtype: float64
39949 39956    317.0
Name: new_cases, dtype: float64
39950 39957    349.0
Name: new_cases, dtype: float64
39951 39958    338.0
Name: new_cases, dtype: float64
39952 39959    367.0
Name: new_cases, dtype: float64
39953 39960    239.0
Name: new_cases, dtype: float64
39954 39961    158.0
Name: new_cases, dtype: float64
39955 39962    156.0
Name: new_cases, dtype: float64
39956 39963    295.0
Name: new_cases, dtype: float64
39957 39964    321.0
Name: new_cases, dtype: float64
39958 39965    411.0
Name: new_cases, dtype: float64
39959 39966    253.0
Name: new_cases, dtype: float64
39960 39967    285.0
Name: new_cases, dtype: float64
39961 39968    156.0
Name: new_cases, dtype: float64
39962 39969    115.0
Name: new_cases, dtype: float64
39963 39970    192.0
Name: new_cases, dtype: float64
39964 39971    240.0
Name: new_cases, dtype: float64
39965 39972    321.0
Name: new_cases, dtype: float64
39966 39973    309.0
Name: new_cases, dtype: float64
39967 39974    232.0
Name: new_cases, dtype: float64
39968 39975    239.0
Name: new_cases, dtype: float64
39969 39976    345.0
Name: new_cases, dtype: float64
39970 39977    282.0
Name: new_cases, dtype: float64
39971 39978    274.0
Name: new_cases, dtype: float64
39972 39979    273.0
Name: new_cases, dtype: float64
39973 39980    297.0
Name: new_cases, dtype: float64
39974 39981    137.0
Name: new_cases, dtype: float64
39975 39982    228.0
Name: new_cases, dtype: float64
39976 39983    343.0
Name: new_cases, dtype: float64
39977 39984    321.0
Name: new_cases, dtype: float64
39978 39985    279.0
Name: new_cases, dtype: float64
39979 39986    373.0
Name: new_cases, dtype: float64
39980 39987    240.0
Name: new_cases, dtype: float64
39981 39988    215.0
Name: new_cases, dtype: float64
39982 39989    368.0
Name: new_cases, dtype: float64
39983 39990    465.0
Name: new_cases, dtype: float64
39984 39991    473.0
Name: new_cases, dtype: float64
39985 39992    592.0
Name: new_cases, dtype: float64
39986 39993    550.0
Name: new_cases, dtype: float64
39987 39994    660.0
Name: new_cases, dtype: float64
39988 39995    573.0
Name: new_cases, dtype: float64
39989 39996    572.0
Name: new_cases, dtype: float64
39990 39997    701.0
Name: new_cases, dtype: float64
39991 39998    746.0
Name: new_cases, dtype: float64
39992 39999    886.0
Name: new_cases, dtype: float64
39993 40000    517.0
Name: new_cases, dtype: float64
39994 40001    811.0
Name: new_cases, dtype: float64
39995 40002    495.0
Name: new_cases, dtype: float64
39996 40003    633.0
Name: new_cases, dtype: float64
39997 40004    520.0
Name: new_cases, dtype: float64
39998 40005    668.0
Name: new_cases, dtype: float64
39999 40006    752.0
Name: new_cases, dtype: float64
40000 40007    699.0
Name: new_cases, dtype: float64
40001 40008    870.0
Name: new_cases, dtype: float64
40002 40009    751.0
Name: new_cases, dtype: float64
40003 40010    996.0
Name: new_cases, dtype: float64
40004 40011    630.0
Name: new_cases, dtype: float64
40005 40012    963.0
Name: new_cases, dtype: float64
40006 40013    889.0
Name: new_cases, dtype: float64
40007 40014    793.0
Name: new_cases, dtype: float64
40008 40015    823.0
Name: new_cases, dtype: float64
40009 40016    727.0
Name: new_cases, dtype: float64
40010 40017    464.0
Name: new_cases, dtype: float64
40011 40018    649.0
Name: new_cases, dtype: float64
40012 40019    849.0
Name: new_cases, dtype: float64
40013 40020    1102.0
Name: new_cases, dtype: float64
40014 40021    879.0
Name: new_cases, dtype: float64
40015 40022    759.0
Name: new_cases, dtype: float64
40016 40023    693.0
Name: new_cases, dtype: float64
40017 40024    809.0
Name: new_cases, dtype: float64
40018 40025    841.0
Name: new_cases, dtype: float64
40019 40026    891.0
Name: new_cases, dtype: float64
40020 40027    973.0
Name: new_cases, dtype: float64
40021 40028    1104.0
Name: new_cases, dtype: float64
40022 40029    984.0
Name: new_cases, dtype: float64
40023 40030    896.0
Name: new_cases, dtype: float64
40024 40031    925.0
Name: new_cases, dtype: float64
40025 40032    968.0
Name: new_cases, dtype: float64
40026 40033    1046.0
Name: new_cases, dtype: float64
40027 40034    1119.0
Name: new_cases, dtype: float64
40028 40035    1160.0
Name: new_cases, dtype: float64
40029 40036    1225.0
Name: new_cases, dtype: float64
40030 40037    1248.0
Name: new_cases, dtype: float64
40031 40038    1160.0
Name: new_cases, dtype: float64
40032 40039    1002.0
Name: new_cases, dtype: float64
40033 40040    862.0
Name: new_cases, dtype: float64
40034 40041    893.0
Name: new_cases, dtype: float64
40035 40042    1073.0
Name: new_cases, dtype: float64
40036 40043    1068.0
Name: new_cases, dtype: float64
40037 40044    817.0
Name: new_cases, dtype: float64
40038 40045    707.0
Name: new_cases, dtype: float64
40039 40046    846.0
Name: new_cases, dtype: float64
40040 40047    470.0
Name: new_cases, dtype: float64
40041 40048    759.0
Name: new_cases, dtype: float64
40042 40049    508.0
Name: new_cases, dtype: float64
40043 40050    490.0
Name: new_cases, dtype: float64
40044 40051    292.0
Name: new_cases, dtype: float64
40045 40052    310.0
Name: new_cases, dtype: float64
40046 40053    138.0
Name: new_cases, dtype: float64
40047 40054    223.0
Name: new_cases, dtype: float64
40048 40055    155.0
Name: new_cases, dtype: float64
40049 40056    289.0
Name: new_cases, dtype: float64
40050 40057    327.0
Name: new_cases, dtype: float64
40051 40058    271.0
Name: new_cases, dtype: float64
40052 40059    232.0
Name: new_cases, dtype: float64
40053 40060    254.0
Name: new_cases, dtype: float64
40054 40061    230.0
Name: new_cases, dtype: float64
40055 40062    258.0
Name: new_cases, dtype: float64
40056 40063    372.0
Name: new_cases, dtype: float64
40057 40064    225.0
Name: new_cases, dtype: float64
40058 40065    178.0
Name: new_cases, dtype: float64
40059 40066    147.0
Name: new_cases, dtype: float64
40060 40067    308.0
Name: new_cases, dtype: float64
40061 40068    206.0
Name: new_cases, dtype: float64
40062 40069    88.0
Name: new_cases, dtype: float64
40063 40070    252.0
Name: new_cases, dtype: float64
40064 40071    183.0
Name: new_cases, dtype: float64
40065 40072    272.0
Name: new_cases, dtype: float64
40066 40073    162.0
Name: new_cases, dtype: float64
40067 40074    139.0
Name: new_cases, dtype: float64
40068 40075    241.0
Name: new_cases, dtype: float64
40069 40076    422.0
Name: new_cases, dtype: float64
40070 40077    506.0
Name: new_cases, dtype: float64
40071 40078    696.0
Name: new_cases, dtype: float64
40072 40079    339.0
Name: new_cases, dtype: float64
40073 40080    478.0
Name: new_cases, dtype: float64
40074 40081    655.0
Name: new_cases, dtype: float64
40075 40082    911.0
Name: new_cases, dtype: float64
40076 40083    998.0
Name: new_cases, dtype: float64
40077 40084    1510.0
Name: new_cases, dtype: float64
40078 40085    1149.0
Name: new_cases, dtype: float64
40079 40086    2026.0
Name: new_cases, dtype: float64
40080 40087    2856.0
Name: new_cases, dtype: float64
40081 40088    3700.0
Name: new_cases, dtype: float64
40082 40089    5201.0
Name: new_cases, dtype: float64
40083 40090    5307.0
Name: new_cases, dtype: float64
40084 40091    5968.0
Name: new_cases, dtype: float64
40085 40092    6200.0
Name: new_cases, dtype: float64
40086 Series([], Name: new_cases, dtype: float64)
40087 Series([], Name: new_cases, dtype: float64)
40088 Series([], Name: new_cases, dtype: float64)
40089 Series([], Name: new_cases, dtype: float64)
40090 Series([], Name: new_cases, dtype: float64)
40091 Series([], Name: new_cases, dtype: float64)
40092 Series([], Name: new_cases, dtype: float64)
40772 40779    0.0
Name: new_cases, dtype: float64

40773 40780    0.0
Name: new_cases, dtype: float64
40774 40781    0.0
Name: new_cases, dtype: float64
40775 40782    0.0
Name: new_cases, dtype: float64
40776 40783    0.0
Name: new_cases, dtype: float64
40777 40784    0.0
Name: new_cases, dtype: float64
40778 40785    0.0
Name: new_cases, dtype: float64
40779 40786    0.0
Name: new_cases, dtype: float64
40780 40787    0.0
Name: new_cases, dtype: float64
40781 40788    1.0
Name: new_cases, dtype: float64
40782 40789    0.0
Name: new_cases, dtype: float64
40783 40790    0.0
Name: new_cases, dtype: float64
40784 40791    0.0
Name: new_cases, dtype: float64
40785 40792    1.0
Name: new_cases, dtype: float64
40786 40793    12.0
Name: new_cases, dtype: float64
40787 40794    0.0
Name: new_cases, dtype: float64
40788 40795    34.0
Name: new_cases, dtype: float64
40789 40796    6.0
Name: new_cases, dtype: float64
40790 40797    4.0
Name: new_cases, dtype: float64
40791 40798    1.0
Name: new_cases, dtype: float64
40792 40799    7.0
Name: new_cases, dtype: float64
40793 40800    13.0
Name: new_cases, dtype: float64
40794 40801    29.0
Name: new_cases, dtype: float64
40795 40802    1.0
Name: new_cases, dtype: float64
40796 40803    40.0
Name: new_cases, dtype: float64
40797 40804    46.0
Name: new_cases, dtype: float64
40798 40805    0.0
Name: new_cases, dtype: float64
40799 40806    60.0
Name: new_cases, dtype: float64
40800 40807    29.0
Name: new_cases, dtype: float64
40801 40808    9.0
Name: new_cases, dtype: float64
40802 40809    33.0
Name: new_cases, dtype: float64
40803 40810    39.0
Name: new_cases, dtype: float64
40804 40811    36.0
Name: new_cases, dtype: float64
40805 40812    54.0
Name: new_cases, dtype: float64
40806 40813    39.0
Name: new_cases, dtype: float64
40807 40814    41.0
Name: new_cases, dtype: float64
40808 40815    40.0
Name: new_cases, dtype: float64
40809 40816    33.0
Name: new_cases, dtype: float64
40810 40817    47.0
Name: new_cases, dtype: float64
40811 40818    54.0
Name: new_cases, dtype: float64
40812 40819    69.0
Name: new_cases, dtype: float64
40813 40820    86.0
Name: new_cases, dtype: float64
40814 40821    120.0
Name: new_cases, dtype: float64
40815 40822    85.0
Name: new_cases, dtype: float64
40816 40823    103.0
Name: new_cases, dtype: float64
40817 40824    149.0
Name: new_cases, dtype: float64
40818 40825    128.0
Name: new_cases, dtype: float64
40819 40826    110.0
Name: new_cases, dtype: float64
40820 40827    139.0
Name: new_cases, dtype: float64
40821 40828    95.0
Name: new_cases, dtype: float64
40822 40829    145.0
Name: new_cases, dtype: float64
40823 40830    126.0
Name: new_cases, dtype: float64
40824 40831    125.0
Name: new_cases, dtype: float64
40825 40832    160.0
Name: new_cases, dtype: float64
40826 40833    155.0
Name: new_cases, dtype: float64
40827 40834    168.0
Name: new_cases, dtype: float64
40828 40835    171.0
Name: new_cases, dtype: float64
40829 40836    188.0
Name: new_cases, dtype: float64
40830 40837    112.0
Name: new_cases, dtype: float64
40831 40838    189.0
Name: new_cases, dtype: float64
40832 40839    157.0
Name: new_cases, dtype: float64
40833 40840    169.0
Name: new_cases, dtype: float64
40834 40841    232.0
Name: new_cases, dtype: float64
40835 40842    201.0
Name: new_cases, dtype: float64
40836 40843    227.0
Name: new_cases, dtype: float64
40837 40844    215.0
Name: new_cases, dtype: float64
40838 40845    248.0
Name: new_cases, dtype: float64
40839 40846    260.0
Name: new_cases, dtype: float64
40840 40847    226.0
Name: new_cases, dtype: float64
40841 40848    269.0
Name: new_cases, dtype: float64
40842 40849    358.0
Name: new_cases, dtype: float64
40843 40850    298.0
Name: new_cases, dtype: float64
40844 40851    272.0
Name: new_cases, dtype: float64
40845 40852    348.0
Name: new_cases, dtype: float64
40846 40853    388.0
Name: new_cases, dtype: float64
40847 40854    387.0
Name: new_cases, dtype: float64
40848 40855    393.0
Name: new_cases, dtype: float64
40849 40856    495.0
Name: new_cases, dtype: float64
40850 40857    488.0
Name: new_cases, dtype: float64
40851 40858    436.0
Name: new_cases, dtype: float64
40852 40859    346.0
Name: new_cases, dtype: float64
40853 40860    347.0
Name: new_cases, dtype: float64
40854 40861    338.0
Name: new_cases, dtype: float64
40855 40862    398.0
Name: new_cases, dtype: float64
40856 40863    399.0
Name: new_cases, dtype: float64
40857 40864    491.0
Name: new_cases, dtype: float64
40858 40865    510.0
Name: new_cases, dtype: float64
40859 40866    535.0
Name: new_cases, dtype: float64
40860 40867    720.0
Name: new_cases, dtype: float64
40861 40868    745.0
Name: new_cases, dtype: float64
40862 40869    774.0
Name: new_cases, dtype: float64
40863 40870    783.0
Name: new_cases, dtype: float64
40864 40871    727.0
Name: new_cases, dtype: float64
40865 40872    752.0
Name: new_cases, dtype: float64
40866 40873    702.0
Name: new_cases, dtype: float64
40867 40874    789.0
Name: new_cases, dtype: float64
40868 40875    910.0
Name: new_cases, dtype: float64
40869 40876    1127.0
Name: new_cases, dtype: float64
40870 40877    1289.0
Name: new_cases, dtype: float64
40871 40878    1367.0
Name: new_cases, dtype: float64
40872 40879    1536.0
Name: new_cases, dtype: float64
40873 40880    1399.0
Name: new_cases, dtype: float64
40874 40881    1152.0
Name: new_cases, dtype: float64
40875 40882    1079.0
Name: new_cases, dtype: float64
40876 40883    1152.0
Name: new_cases, dtype: float64
40877 40884    1348.0
Name: new_cases, dtype: float64
40878 40885    1497.0
Name: new_cases, dtype: float64
40879 40886    1467.0
Name: new_cases, dtype: float64
40880 40887    1365.0
Name: new_cases, dtype: float64
40881 40888    1385.0
Name: new_cases, dtype: float64
40882 40889    1455.0
Name: new_cases, dtype: float64
40883 40890    1442.0
Name: new_cases, dtype: float64
40884 40891    1577.0
Name: new_cases, dtype: float64
40885 40892    1677.0
Name: new_cases, dtype: float64
40886 40893    1618.0
Name: new_cases, dtype: float64
40887 40894    1691.0
Name: new_cases, dtype: float64
40888 40895    1567.0
Name: new_cases, dtype: float64
40889 40896    1363.0
Name: new_cases, dtype: float64
40890 40897    1218.0
Name: new_cases, dtype: float64
40891 40898    1774.0
Name: new_cases, dtype: float64
40892 40899    1547.0
Name: new_cases, dtype: float64
40893 40900    1475.0
Name: new_cases, dtype: float64
40894 40901    1576.0
Name: new_cases, dtype: float64
40895 40902    1332.0
Name: new_cases, dtype: float64
40896 40903    1420.0
Name: new_cases, dtype: float64
40897 40904    1569.0
Name: new_cases, dtype: float64
40898 40905    1625.0
Name: new_cases, dtype: float64
40899 40906    1168.0
Name: new_cases, dtype: float64
40900 40907    1265.0
Name: new_cases, dtype: float64
40901 40908    1566.0
Name: new_cases, dtype: float64
40902 40909    1557.0
Name: new_cases, dtype: float64
40903 40910    1503.0
Name: new_cases, dtype: float64
40904 40911    1485.0
Name: new_cases, dtype: float64
40905 40912    1412.0
Name: new_cases, dtype: float64
40906 40913    1324.0
Name: new_cases, dtype: float64
40907 40914    1218.0
Name: new_cases, dtype: float64
40908 40915    969.0
Name: new_cases, dtype: float64
40909 40916    1057.0
Name: new_cases, dtype: float64
40910 40917    1025.0
Name: new_cases, dtype: float64
40911 40918    950.0
Name: new_cases, dtype: float64
40912 40919    981.0
Name: new_cases, dtype: float64
40913 40920    923.0
Name: new_cases, dtype: float64
40914 40921    912.0
Name: new_cases, dtype: float64
40915 40922    931.0
Name: new_cases, dtype: float64
40916 40923    929.0
Name: new_cases, dtype: float64
40917 40924    913.0
Name: new_cases, dtype: float64
40918 40925    928.0
Name: new_cases, dtype: float64
40919 40926    703.0
Name: new_cases, dtype: float64
40920 40927    698.0
Name: new_cases, dtype: float64
40921 40928    603.0
Name: new_cases, dtype: float64
40922 40929    627.0
Name: new_cases, dtype: float64
40923 40930    676.0
Name: new_cases, dtype: float64
40924 40931    667.0
Name: new_cases, dtype: float64
40925 40932    668.0
Name: new_cases, dtype: float64
40926 40933    659.0
Name: new_cases, dtype: float64
40927 40934    511.0
Name: new_cases, dtype: float64
40928 40935    479.0
Name: new_cases, dtype: float64
40929 40936    420.0
Name: new_cases, dtype: float64
40930 40937    465.0
Name: new_cases, dtype: float64
40931 40938    409.0
Name: new_cases, dtype: float64
40932 40939    401.0
Name: new_cases, dtype: float64
40933 40940    321.0
Name: new_cases, dtype: float64
40934 40941    238.0
Name: new_cases, dtype: float64
40935 40942    167.0
Name: new_cases, dtype: float64
40936 40943    157.0
Name: new_cases, dtype: float64
40937 40944    112.0
Name: new_cases, dtype: float64
40938 40945    123.0
Name: new_cases, dtype: float64
40939 40946    131.0
Name: new_cases, dtype: float64
40940 40947    141.0
Name: new_cases, dtype: float64
40941 40948    167.0
Name: new_cases, dtype: float64

40942 40949    178.0
Name: new_cases, dtype: float64
40943 40950    174.0
Name: new_cases, dtype: float64
40944 40951    168.0
Name: new_cases, dtype: float64
40945 40952    129.0
Name: new_cases, dtype: float64
40946 40953    145.0
Name: new_cases, dtype: float64
40947 40954    112.0
Name: new_cases, dtype: float64
40948 40955    116.0
Name: new_cases, dtype: float64
40949 40956    139.0
Name: new_cases, dtype: float64
40950 40957    115.0
Name: new_cases, dtype: float64
40951 40958    163.0
Name: new_cases, dtype: float64
40952 40959    161.0
Name: new_cases, dtype: float64
40953 40960    111.0
Name: new_cases, dtype: float64
40954 40961    123.0
Name: new_cases, dtype: float64
40955 40962    89.0
Name: new_cases, dtype: float64
40956 40963    103.0
Name: new_cases, dtype: float64
40957 40964    138.0
Name: new_cases, dtype: float64
40958 40965    141.0
Name: new_cases, dtype: float64
40959 40966    206.0
Name: new_cases, dtype: float64
40960 40967    237.0
Name: new_cases, dtype: float64
40961 40968    223.0
Name: new_cases, dtype: float64
40962 40969    212.0
Name: new_cases, dtype: float64
40963 40970    230.0
Name: new_cases, dtype: float64
40964 40971    212.0
Name: new_cases, dtype: float64
40965 40972    176.0
Name: new_cases, dtype: float64
40966 40973    165.0
Name: new_cases, dtype: float64
40967 40974    145.0
Name: new_cases, dtype: float64
40968 40975    157.0
Name: new_cases, dtype: float64
40969 40976    130.0
Name: new_cases, dtype: float64
40970 40977    151.0
Name: new_cases, dtype: float64
40971 40978    178.0
Name: new_cases, dtype: float64
40972 40979    187.0
Name: new_cases, dtype: float64
40973 40980    175.0
Name: new_cases, dtype: float64
40974 40981    154.0
Name: new_cases, dtype: float64
40975 40982    151.0
Name: new_cases, dtype: float64
40976 40983    148.0
Name: new_cases, dtype: float64
40977 40984    153.0
Name: new_cases, dtype: float64
40978 40985    168.0
Name: new_cases, dtype: float64
40979 40986    163.0
Name: new_cases, dtype: float64
40980 40987    160.0
Name: new_cases, dtype: float64
40981 40988    141.0
Name: new_cases, dtype: float64
40982 40989    131.0
Name: new_cases, dtype: float64
40983 40990    128.0
Name: new_cases, dtype: float64
40984 40991    115.0
Name: new_cases, dtype: float64
40985 40992    126.0
Name: new_cases, dtype: float64
40986 40993    113.0
Name: new_cases, dtype: float64
40987 40994    121.0
Name: new_cases, dtype: float64
40988 40995    138.0
Name: new_cases, dtype: float64
40989 40996    112.0
Name: new_cases, dtype: float64
40990 40997    111.0
Name: new_cases, dtype: float64
40991 40998    104.0
Name: new_cases, dtype: float64
40992 40999    115.0
Name: new_cases, dtype: float64
40993 41000    124.0
Name: new_cases, dtype: float64
40994 41001    119.0
Name: new_cases, dtype: float64
40995 41002    119.0
Name: new_cases, dtype: float64
40996 41003    149.0
Name: new_cases, dtype: float64
40997 41004    109.0
Name: new_cases, dtype: float64
40998 41005    108.0
Name: new_cases, dtype: float64
40999 41006    98.0
Name: new_cases, dtype: float64
41000 41007    121.0
Name: new_cases, dtype: float64
41001 41008    133.0
Name: new_cases, dtype: float64
41002 41009    121.0
Name: new_cases, dtype: float64
41003 41010    106.0
Name: new_cases, dtype: float64
41004 41011    125.0
Name: new_cases, dtype: float64
41005 41012    129.0
Name: new_cases, dtype: float64
41006 41013    132.0
Name: new_cases, dtype: float64
41007 41014    139.0
Name: new_cases, dtype: float64
41008 41015    128.0
Name: new_cases, dtype: float64
41009 41016    118.0
Name: new_cases, dtype: float64
41010 41017    126.0
Name: new_cases, dtype: float64
41011 41018    138.0
Name: new_cases, dtype: float64
41012 41019    127.0
Name: new_cases, dtype: float64
41013 41020    123.0
Name: new_cases, dtype: float64
41014 41021    158.0
Name: new_cases, dtype: float64
41015 41022    178.0
Name: new_cases, dtype: float64
41016 41023    177.0
Name: new_cases, dtype: float64
41017 41024    170.0
Name: new_cases, dtype: float64
41018 41025    167.0
Name: new_cases, dtype: float64
41019 41026    143.0
Name: new_cases, dtype: float64
41020 41027    167.0
Name: new_cases, dtype: float64
41021 41028    170.0
Name: new_cases, dtype: float64
41022 41029    153.0
Name: new_cases, dtype: float64
41023 41030    179.0
Name: new_cases, dtype: float64
41024 41031    167.0
Name: new_cases, dtype: float64
41025 41032    179.0
Name: new_cases, dtype: float64
41026 41033    181.0
Name: new_cases, dtype: float64
41027 41034    189.0
Name: new_cases, dtype: float64
41028 41035    197.0
Name: new_cases, dtype: float64
41029 41036    207.0
Name: new_cases, dtype: float64
41030 41037    201.0
Name: new_cases, dtype: float64
41031 41038    224.0
Name: new_cases, dtype: float64
41032 41039    208.0
Name: new_cases, dtype: float64
41033 41040    239.0
Name: new_cases, dtype: float64
41034 41041    221.0
Name: new_cases, dtype: float64
41035 41042    232.0
Name: new_cases, dtype: float64
41036 41043    227.0
Name: new_cases, dtype: float64
41037 41044    214.0
Name: new_cases, dtype: float64
41038 41045    224.0
Name: new_cases, dtype: float64
41039 41046    228.0
Name: new_cases, dtype: float64
41040 41047    220.0
Name: new_cases, dtype: float64
41041 41048    242.0
Name: new_cases, dtype: float64
41042 41049    275.0
Name: new_cases, dtype: float64
41043 41050    329.0
Name: new_cases, dtype: float64
41044 41051    342.0
Name: new_cases, dtype: float64
41045 41052    363.0
Name: new_cases, dtype: float64
41046 41053    358.0
Name: new_cases, dtype: float64
41047 41054    351.0
Name: new_cases, dtype: float64
41048 41055    354.0
Name: new_cases, dtype: float64
41049 41056    361.0
Name: new_cases, dtype: float64
41050 41057    365.0
Name: new_cases, dtype: float64
41051 41058    368.0
Name: new_cases, dtype: float64
41052 41059    357.0
Name: new_cases, dtype: float64
41053 41060    351.0
Name: new_cases, dtype: float64
41054 41061    358.0
Name: new_cases, dtype: float64
41055 41062    370.0
Name: new_cases, dtype: float64
41056 41063    392.0
Name: new_cases, dtype: float64
41057 41064    421.0
Name: new_cases, dtype: float64
41058 41065    432.0
Name: new_cases, dtype: float64
41059 41066    427.0
Name: new_cases, dtype: float64
41060 41067    431.0
Name: new_cases, dtype: float64
41061 41068    418.0
Name: new_cases, dtype: float64
41062 41069    415.0
Name: new_cases, dtype: float64
41063 41070    434.0
Name: new_cases, dtype: float64
41064 41071    421.0
Name: new_cases, dtype: float64
41065 41072    445.0
Name: new_cases, dtype: float64
41066 41073    464.0
Name: new_cases, dtype: float64
41067 41074    478.0
Name: new_cases, dtype: float64
41068 41075    486.0
Name: new_cases, dtype: float64
41069 41076    511.0
Name: new_cases, dtype: float64
41070 41077    523.0
Name: new_cases, dtype: float64
41071 41078    544.0
Name: new_cases, dtype: float64
41072 41079    548.0
Name: new_cases, dtype: float64
41073 41080    579.0
Name: new_cases, dtype: float64
41074 41081    611.0
Name: new_cases, dtype: float64
41075 41082    664.0
Name: new_cases, dtype: float64
41076 41083    718.0
Name: new_cases, dtype: float64
41077 41084    788.0
Name: new_cases, dtype: float64
41078 41085    911.0
Name: new_cases, dtype: float64
41079 41086    1021.0
Name: new_cases, dtype: float64
41080 41087    1133.0
Name: new_cases, dtype: float64
41081 41088    1189.0
Name: new_cases, dtype: float64
41082 41089    1226.0
Name: new_cases, dtype: float64
41083 41090    1359.0
Name: new_cases, dtype: float64
41084 41091    1333.0
Name: new_cases, dtype: float64
41085 41092    1411.0
Name: new_cases, dtype: float64
41086 41093    1418.0
Name: new_cases, dtype: float64
41087 41094    1409.0
Name: new_cases, dtype: float64
41088 41095    1407.0
Name: new_cases, dtype: float64
41089 41096    1309.0
Name: new_cases, dtype: float64
41090 41097    1277.0
Name: new_cases, dtype: float64
41091 41098    1119.0
Name: new_cases, dtype: float64
41092 41099    1007.0
Name: new_cases, dtype: float64
41093 41100    1219.0
Name: new_cases, dtype: float64
41094 41101    1001.0
Name: new_cases, dtype: float64
41095 41102    989.0
Name: new_cases, dtype: float64
41096 41103    993.0
Name: new_cases, dtype: float64
41097 41104    961.0
Name: new_cases, dtype: float64
41098 41105    970.0
Name: new_cases, dtype: float64
41099 41106    996.0
Name: new_cases, dtype: float64
41100 41107    1022.0
Name: new_cases, dtype: float64

41101 41108    879.0
Name: new_cases, dtype: float64
41102 41109    887.0
Name: new_cases, dtype: float64
41103 41110    890.0
Name: new_cases, dtype: float64
41104 41111    878.0
Name: new_cases, dtype: float64
41105 41112    899.0
Name: new_cases, dtype: float64
41106 41113    789.0
Name: new_cases, dtype: float64
41107 41114    752.0
Name: new_cases, dtype: float64
41108 41115    748.0
Name: new_cases, dtype: float64
41109 41116    680.0
Name: new_cases, dtype: float64
41110 41117    674.0
Name: new_cases, dtype: float64
41111 41118    669.0
Name: new_cases, dtype: float64
41112 41119    643.0
Name: new_cases, dtype: float64
41113 41120    632.0
Name: new_cases, dtype: float64
41114 41121    521.0
Name: new_cases, dtype: float64
41115 41122    589.0
Name: new_cases, dtype: float64
41116 41123    547.0
Name: new_cases, dtype: float64
41117 41124    533.0
Name: new_cases, dtype: float64
41118 41125    541.0
Name: new_cases, dtype: float64
41119 41126    521.0
Name: new_cases, dtype: float64
41120 41127    512.0
Name: new_cases, dtype: float64
41121 41128    532.0
Name: new_cases, dtype: float64
41122 41129    540.0
Name: new_cases, dtype: float64
41123 41130    509.0
Name: new_cases, dtype: float64
41124 41131    534.0
Name: new_cases, dtype: float64
41125 41132    567.0
Name: new_cases, dtype: float64
41126 41133    573.0
Name: new_cases, dtype: float64
41127 41134    610.0
Name: new_cases, dtype: float64
41128 41135    603.0
Name: new_cases, dtype: float64
41129 41136    609.0
Name: new_cases, dtype: float64
41130 41137    600.0
Name: new_cases, dtype: float64
41131 41138    611.0
Name: new_cases, dtype: float64
41132 41139    613.0
Name: new_cases, dtype: float64
41133 41140    633.0
Name: new_cases, dtype: float64
41134 41141    618.0
Name: new_cases, dtype: float64
41135 41142    656.0
Name: new_cases, dtype: float64
41136 41143    610.0
Name: new_cases, dtype: float64
41137 41144    600.0
Name: new_cases, dtype: float64
41138 41145    608.0
Name: new_cases, dtype: float64
41139 41146    623.0
Name: new_cases, dtype: float64
41140 41147    633.0
Name: new_cases, dtype: float64
41141 41148    644.0
Name: new_cases, dtype: float64
41142 41149    589.0
Name: new_cases, dtype: float64
41143 41150    601.0
Name: new_cases, dtype: float64
41144 41151    588.0
Name: new_cases, dtype: float64
41145 41152    595.0
Name: new_cases, dtype: float64
41146 41153    586.0
Name: new_cases, dtype: float64
41147 41154    581.0
Name: new_cases, dtype: float64
41148 41155    577.0
Name: new_cases, dtype: float64
41149 41156    587.0
Name: new_cases, dtype: float64
41150 41157    579.0
Name: new_cases, dtype: float64
41151 41158    588.0
Name: new_cases, dtype: float64
41152 41159    581.0
Name: new_cases, dtype: float64
41153 41160    591.0
Name: new_cases, dtype: float64
41154 41161    622.0
Name: new_cases, dtype: float64
41155 41162    645.0
Name: new_cases, dtype: float64
41156 41163    639.0
Name: new_cases, dtype: float64
41157 41164    639.0
Name: new_cases, dtype: float64
41158 41165    641.0
Name: new_cases, dtype: float64
41159 41166    644.0
Name: new_cases, dtype: float64
41160 41167    631.0
Name: new_cases, dtype: float64
41161 41168    640.0
Name: new_cases, dtype: float64
41162 41169    645.0
Name: new_cases, dtype: float64
41163 41170    642.0
Name: new_cases, dtype: float64
41164 41171    645.0
Name: new_cases, dtype: float64
41165 41172    644.0
Name: new_cases, dtype: float64
41166 41173    647.0
Name: new_cases, dtype: float64
41167 41174    643.0
Name: new_cases, dtype: float64
41168 41175    648.0
Name: new_cases, dtype: float64
41169 41176    641.0
Name: new_cases, dtype: float64
41170 41177    661.0
Name: new_cases, dtype: float64
41171 41178    670.0
Name: new_cases, dtype: float64
41172 41179    683.0
Name: new_cases, dtype: float64
41173 41180    686.0
Name: new_cases, dtype: float64
41174 41181    689.0
Name: new_cases, dtype: float64
41175 41182    693.0
Name: new_cases, dtype: float64
41176 41183    699.0
Name: new_cases, dtype: float64
41177 41184    712.0
Name: new_cases, dtype: float64
41178 41185    703.0
Name: new_cases, dtype: float64
41179 41186    710.0
Name: new_cases, dtype: float64
41180 41187    709.0
Name: new_cases, dtype: float64
41181 41188    767.0
Name: new_cases, dtype: float64
41182 41189    778.0
Name: new_cases, dtype: float64
41183 41190    783.0
Name: new_cases, dtype: float64
41184 41191    789.0
Name: new_cases, dtype: float64
41185 41192    794.0
Name: new_cases, dtype: float64
41186 41193    801.0
Name: new_cases, dtype: float64
41187 41194    812.0
Name: new_cases, dtype: float64
41188 41195    818.0
Name: new_cases, dtype: float64
41189 41196    823.0
Name: new_cases, dtype: float64
41190 41197    831.0
Name: new_cases, dtype: float64
41191 41198    837.0
Name: new_cases, dtype: float64
41192 41199    841.0
Name: new_cases, dtype: float64
41193 41200    845.0
Name: new_cases, dtype: float64
41194 41201    850.0
Name: new_cases, dtype: float64
41195 41202    852.0
Name: new_cases, dtype: float64
41196 41203    855.0
Name: new_cases, dtype: float64
41197 41204    861.0
Name: new_cases, dtype: float64
41198 41205    872.0
Name: new_cases, dtype: float64
41199 41206    884.0
Name: new_cases, dtype: float64
41200 41207    912.0
Name: new_cases, dtype: float64
41201 41208    953.0
Name: new_cases, dtype: float64
41202 41209    991.0
Name: new_cases, dtype: float64
41203 41210    1003.0
Name: new_cases, dtype: float64
41204 41211    1011.0
Name: new_cases, dtype: float64
41205 41212    1003.0
Name: new_cases, dtype: float64
41206 41213    1021.0
Name: new_cases, dtype: float64
41207 41214    1032.0
Name: new_cases, dtype: float64
41208 41215    1051.0
Name: new_cases, dtype: float64
41209 41216    1078.0
Name: new_cases, dtype: float64
41210 41217    1090.0
Name: new_cases, dtype: float64
41211 41218    1102.0
Name: new_cases, dtype: float64
41212 41219    1110.0
Name: new_cases, dtype: float64
41213 41220    1125.0
Name: new_cases, dtype: float64
41214 41221    1132.0
Name: new_cases, dtype: float64
41215 41222    1138.0
Name: new_cases, dtype: float64
41216 41223    1150.0
Name: new_cases, dtype: float64
41217 41224    1180.0
Name: new_cases, dtype: float64
41218 41225    1187.0
Name: new_cases, dtype: float64
41219 41226    1193.0
Name: new_cases, dtype: float64
41220 41227    1197.0
Name: new_cases, dtype: float64
41221 41228    1203.0
Name: new_cases, dtype: float64
41222 41229    1201.0
Name: new_cases, dtype: float64
41223 41230    1188.0
Name: new_cases, dtype: float64
41224 41231    1169.0
Name: new_cases, dtype: float64
41225 41232    1160.0
Name: new_cases, dtype: float64
41226 41233    1153.0
Name: new_cases, dtype: float64
41227 41234    1148.0
Name: new_cases, dtype: float64
41228 41235    1151.0
Name: new_cases, dtype: float64
41229 41236    1145.0
Name: new_cases, dtype: float64
41230 41237    1149.0
Name: new_cases, dtype: float64
41231 41238    1140.0
Name: new_cases, dtype: float64
41232 41239    1151.0
Name: new_cases, dtype: float64
41233 41240    1132.0
Name: new_cases, dtype: float64
41234 41241    1133.0
Name: new_cases, dtype: float64
41235 41242    1119.0
Name: new_cases, dtype: float64
41236 41243    1007.0
Name: new_cases, dtype: float64
41237 41244    984.0
Name: new_cases, dtype: float64
41238 41245    956.0
Name: new_cases, dtype: float64
41239 41246    951.0
Name: new_cases, dtype: float64
41240 41247    932.0
Name: new_cases, dtype: float64
41241 41248    861.0
Name: new_cases, dtype: float64
41242 41249    821.0
Name: new_cases, dtype: float64
41243 41250    801.0
Name: new_cases, dtype: float64
41244 41251    782.0
Name: new_cases, dtype: float64
41245 41252    773.0
Name: new_cases, dtype: float64
41246 41253    765.0
Name: new_cases, dtype: float64
41247 41254    755.0
Name: new_cases, dtype: float64
41248 41255    733.0
Name: new_cases, dtype: float64
41249 41256    711.0
Name: new_cases, dtype: float64
41250 41257    691.0
Name: new_cases, dtype: float64
41251 41258    613.0
Name: new_cases, dtype: float64
41252 41259    609.0
Name: new_cases, dtype: float64
41253 41260    606.0
Name: new_cases, dtype: float64
41254 41261    591.0
Name: new_cases, dtype: float64
41255 41262    589.0
Name: new_cases, dtype: float64
41256 41263    566.0
Name: new_cases, dtype: float64
41257 41264    532.0
Name: new_cases, dtype: float64
41258 41265    509.0
Name: new_cases, dtype: float64

41259 41266    498.0
Name: new_cases, dtype: float64
41260 41267    466.0
Name: new_cases, dtype: float64
41261 41268    423.0
Name: new_cases, dtype: float64
41262 41269    412.0
Name: new_cases, dtype: float64
41263 41270    409.0
Name: new_cases, dtype: float64
41264 41271    389.0
Name: new_cases, dtype: float64
41265 41272    376.0
Name: new_cases, dtype: float64
41266 41273    261.0
Name: new_cases, dtype: float64
41267 41274    251.0
Name: new_cases, dtype: float64
41268 41275    242.0
Name: new_cases, dtype: float64
41269 41276    198.0
Name: new_cases, dtype: float64
41270 41277    181.0
Name: new_cases, dtype: float64
41271 41278    179.0
Name: new_cases, dtype: float64
41272 41279    175.0
Name: new_cases, dtype: float64
41273 41280    164.0
Name: new_cases, dtype: float64
41274 41281    161.0
Name: new_cases, dtype: float64
41275 41282    155.0
Name: new_cases, dtype: float64
41276 41283    127.0
Name: new_cases, dtype: float64
41277 41284    121.0
Name: new_cases, dtype: float64
41278 41285    117.0
Name: new_cases, dtype: float64
41279 41286    110.0
Name: new_cases, dtype: float64
41280 41287    108.0
Name: new_cases, dtype: float64
41281 41288    89.0
Name: new_cases, dtype: float64
41282 41289    81.0
Name: new_cases, dtype: float64
41283 41290    77.0
Name: new_cases, dtype: float64
41284 41291    69.0
Name: new_cases, dtype: float64
41285 41292    0.0
Name: new_cases, dtype: float64
41286 41293    126.0
Name: new_cases, dtype: float64
41287 41294    51.0
Name: new_cases, dtype: float64
41288 41295    49.0
Name: new_cases, dtype: float64
41289 41296    44.0
Name: new_cases, dtype: float64
41290 41297    41.0
Name: new_cases, dtype: float64
41291 41298    38.0
Name: new_cases, dtype: float64
41292 41299    39.0
Name: new_cases, dtype: float64
41293 41300    35.0
Name: new_cases, dtype: float64
41294 41301    31.0
Name: new_cases, dtype: float64
41295 41302    38.0
Name: new_cases, dtype: float64
41296 41303    42.0
Name: new_cases, dtype: float64
41297 41304    45.0
Name: new_cases, dtype: float64
41298 41305    47.0
Name: new_cases, dtype: float64
41299 41306    49.0
Name: new_cases, dtype: float64
41300 41307    51.0
Name: new_cases, dtype: float64
41301 41308    53.0
Name: new_cases, dtype: float64
41302 41309    57.0
Name: new_cases, dtype: float64
41303 41310    51.0
Name: new_cases, dtype: float64
41304 41311    57.0
Name: new_cases, dtype: float64
41305 41312    61.0
Name: new_cases, dtype: float64
41306 41313    65.0
Name: new_cases, dtype: float64
41307 41314    83.0
Name: new_cases, dtype: float64
41308 41315    86.0
Name: new_cases, dtype: float64
41309 41316    91.0
Name: new_cases, dtype: float64
41310 41317    95.0
Name: new_cases, dtype: float64
41311 41318    97.0
Name: new_cases, dtype: float64
41312 41319    99.0
Name: new_cases, dtype: float64
41313 41320    101.0
Name: new_cases, dtype: float64
41314 41321    107.0
Name: new_cases, dtype: float64
41315 41322    112.0
Name: new_cases, dtype: float64
41316 41323    123.0
Name: new_cases, dtype: float64
41317 41324    131.0
Name: new_cases, dtype: float64
41318 41325    164.0
Name: new_cases, dtype: float64
41319 41326    173.0
Name: new_cases, dtype: float64
41320 41327    184.0
Name: new_cases, dtype: float64
41321 41328    189.0
Name: new_cases, dtype: float64
41322 41329    194.0
Name: new_cases, dtype: float64
41323 41330    203.0
Name: new_cases, dtype: float64
41324 41331    221.0
Name: new_cases, dtype: float64
41325 41332    234.0
Name: new_cases, dtype: float64
41326 41333    251.0
Name: new_cases, dtype: float64
41327 41334    255.0
Name: new_cases, dtype: float64
41328 41335    263.0
Name: new_cases, dtype: float64
41329 41336    279.0
Name: new_cases, dtype: float64
41330 41337    291.0
Name: new_cases, dtype: float64
41331 41338    303.0
Name: new_cases, dtype: float64
41332 41339    318.0
Name: new_cases, dtype: float64
41333 41340    331.0
Name: new_cases, dtype: float64
41334 41341    343.0
Name: new_cases, dtype: float64
41335 41342    368.0
Name: new_cases, dtype: float64
41336 41343    378.0
Name: new_cases, dtype: float64
41337 41344    399.0
Name: new_cases, dtype: float64
41338 41345    413.0
Name: new_cases, dtype: float64
41339 41346    433.0
Name: new_cases, dtype: float64
41340 41347    458.0
Name: new_cases, dtype: float64
41341 41348    481.0
Name: new_cases, dtype: float64
41342 41349    491.0
Name: new_cases, dtype: float64
41343 41350    503.0
Name: new_cases, dtype: float64
41344 41351    531.0
Name: new_cases, dtype: float64
41345 41352    569.0
Name: new_cases, dtype: float64
41346 41353    588.0
Name: new_cases, dtype: float64
41347 41354    637.0
Name: new_cases, dtype: float64
41348 41355    653.0
Name: new_cases, dtype: float64
41349 41356    679.0
Name: new_cases, dtype: float64
41350 41357    688.0
Name: new_cases, dtype: float64
41351 41358    692.0
Name: new_cases, dtype: float64
41352 41359    722.0
Name: new_cases, dtype: float64
41353 41360    568.0
Name: new_cases, dtype: float64
41354 41361    667.0
Name: new_cases, dtype: float64
41355 41362    680.0
Name: new_cases, dtype: float64
41356 41363    702.0
Name: new_cases, dtype: float64
41357 41364    718.0
Name: new_cases, dtype: float64
41358 41365    738.0
Name: new_cases, dtype: float64
41359 41366    741.0
Name: new_cases, dtype: float64
41360 41367    745.0
Name: new_cases, dtype: float64
41361 41368    761.0
Name: new_cases, dtype: float64
41362 41369    768.0
Name: new_cases, dtype: float64
41363 41370    771.0
Name: new_cases, dtype: float64
41364 41371    778.0
Name: new_cases, dtype: float64
41365 41372    788.0
Name: new_cases, dtype: float64
41366 41373    799.0
Name: new_cases, dtype: float64
41367 41374    811.0
Name: new_cases, dtype: float64
41368 41375    831.0
Name: new_cases, dtype: float64
41369 41376    837.0
Name: new_cases, dtype: float64
41370 41377    846.0
Name: new_cases, dtype: float64
41371 41378    857.0
Name: new_cases, dtype: float64
41372 41379    861.0
Name: new_cases, dtype: float64
41373 41380    865.0
Name: new_cases, dtype: float64
41374 41381    869.0
Name: new_cases, dtype: float64
41375 41382    874.0
Name: new_cases, dtype: float64
41376 41383    871.0
Name: new_cases, dtype: float64
41377 41384    883.0
Name: new_cases, dtype: float64
41378 41385    868.0
Name: new_cases, dtype: float64
41379 41386    877.0
Name: new_cases, dtype: float64
41380 41387    883.0
Name: new_cases, dtype: float64
41381 41388    885.0
Name: new_cases, dtype: float64
41382 41389    881.0
Name: new_cases, dtype: float64
41383 41390    886.0
Name: new_cases, dtype: float64
41384 41391    889.0
Name: new_cases, dtype: float64
41385 41392    871.0
Name: new_cases, dtype: float64
41386 41393    907.0
Name: new_cases, dtype: float64
41387 41394    923.0
Name: new_cases, dtype: float64
41388 41395    927.0
Name: new_cases, dtype: float64
41389 41396    948.0
Name: new_cases, dtype: float64
41390 41397    933.0
Name: new_cases, dtype: float64
41391 41398    951.0
Name: new_cases, dtype: float64
41392 41399    921.0
Name: new_cases, dtype: float64
41393 41400    951.0
Name: new_cases, dtype: float64
41394 41401    911.0
Name: new_cases, dtype: float64
41395 41402    922.0
Name: new_cases, dtype: float64
41396 41403    909.0
Name: new_cases, dtype: float64
41397 41404    903.0
Name: new_cases, dtype: float64
41398 41405    929.0
Name: new_cases, dtype: float64
41399 41406    921.0
Name: new_cases, dtype: float64
41400 41407    934.0
Name: new_cases, dtype: float64
41401 41408    919.0
Name: new_cases, dtype: float64
41402 41409    909.0
Name: new_cases, dtype: float64
41403 41410    929.0
Name: new_cases, dtype: float64
41404 41411    0.0
Name: new_cases, dtype: float64
41405 41412    1881.0
Name: new_cases, dtype: float64
41406 41413    941.0
Name: new_cases, dtype: float64
41407 41414    960.0
Name: new_cases, dtype: float64
41408 41415    911.0
Name: new_cases, dtype: float64
41409 41416    892.0
Name: new_cases, dtype: float64
41410 41417    902.0
Name: new_cases, dtype: float64
41411 41418    884.0
Name: new_cases, dtype: float64
41412 41419    870.0
Name: new_cases, dtype: float64
41413 41420    856.0
Name: new_cases, dtype: float64
41414 41421    901.0
Name: new_cases, dtype: float64
41415 41422    899.0
Name: new_cases, dtype: float64
41416 41423    913.0
Name: new_cases, dtype: float64
41417 41424    931.0
Name: new_cases, dtype: float64
41418 41425    951.0
Name: new_cases, dtype: float64
41419 41426    911.0
Name: new_cases, dtype: float64
41420 41427    949.0
Name: new_cases, dtype: float64
41421 41428    938.0
Name: new_cases, dtype: float64
41422 41429    919.0
Name: new_cases, dtype: float64
41423 41430    933.0
Name: new_cases, dtype: float64
41424 41431    892.0
Name: new_cases, dtype: float64
41425 41432    902.0
Name: new_cases, dtype: float64
41426 41433    871.0
Name: new_cases, dtype: float64
41427 41434    889.0
Name: new_cases, dtype: float64
41428 41435    909.0
Name: new_cases, dtype: float64
41429 41436    803.0
Name: new_cases, dtype: float64
41430 41437    822.0
Name: new_cases, dtype: float64
41431 41438    879.0
Name: new_cases, dtype: float64
41432 41439    863.0
Name: new_cases, dtype: float64
41433 41440    0.0
Name: new_cases, dtype: float64

41434 41441    1621.0
Name: new_cases, dtype: float64
41435 41442    879.0
Name: new_cases, dtype: float64
41436 41443    901.0
Name: new_cases, dtype: float64
41437 41444    910.0
Name: new_cases, dtype: float64
41438 41445    902.0
Name: new_cases, dtype: float64
41439 41446    919.0
Name: new_cases, dtype: float64
41440 41447    903.0
Name: new_cases, dtype: float64
41441 41448    848.0
Name: new_cases, dtype: float64
41442 41449    879.0
Name: new_cases, dtype: float64
41443 41450    883.0
Name: new_cases, dtype: float64
41444 41451    811.0
Name: new_cases, dtype: float64
41445 41452    866.0
Name: new_cases, dtype: float64
41446 41453    823.0
Name: new_cases, dtype: float64
41447 41454    851.0
Name: new_cases, dtype: float64
41448 41455    809.0
Name: new_cases, dtype: float64
41449 41456    854.0
Name: new_cases, dtype: float64
41450 41457    871.0
Name: new_cases, dtype: float64
41451 41458    847.0
Name: new_cases, dtype: float64
41452 41459    783.0
Name: new_cases, dtype: float64
41453 41460    801.0
Name: new_cases, dtype: float64
41454 41461    723.0
Name: new_cases, dtype: float64
41455 41462    769.0
Name: new_cases, dtype: float64
41456 41463    803.0
Name: new_cases, dtype: float64
41457 41464    840.0
Name: new_cases, dtype: float64
41458 41465    821.0
Name: new_cases, dtype: float64
41459 41466    830.0
Name: new_cases, dtype: float64
41460 40785    0.0
Name: new_cases, dtype: float64
41461 40786    0.0
Name: new_cases, dtype: float64
41462 40787    0.0
Name: new_cases, dtype: float64
41463 40788    1.0
Name: new_cases, dtype: float64
41464 40789    0.0
Name: new_cases, dtype: float64
41465 40790    0.0
Name: new_cases, dtype: float64
41466 40791    0.0
Name: new_cases, dtype: float64
43476 43483    1.0
Name: new_cases, dtype: float64
43477 43484    7.0
Name: new_cases, dtype: float64
43478 43485    0.0
Name: new_cases, dtype: float64
43479 43486    0.0
Name: new_cases, dtype: float64
43480 43487    0.0
Name: new_cases, dtype: float64
43481 43488    2.0
Name: new_cases, dtype: float64
43482 43489    4.0
Name: new_cases, dtype: float64
43483 43490    0.0
Name: new_cases, dtype: float64
43484 43491    63.0
Name: new_cases, dtype: float64
43485 43492    36.0
Name: new_cases, dtype: float64
43486 43493    56.0
Name: new_cases, dtype: float64
43487 43494    34.0
Name: new_cases, dtype: float64
43488 43495    20.0
Name: new_cases, dtype: float64
43489 43496    33.0
Name: new_cases, dtype: float64
43490 43497    9.0
Name: new_cases, dtype: float64
43491 43498    16.0
Name: new_cases, dtype: float64
43492 43499    23.0
Name: new_cases, dtype: float64
43493 43500    20.0
Name: new_cases, dtype: float64
43494 43501    26.0
Name: new_cases, dtype: float64
43495 43502    17.0
Name: new_cases, dtype: float64
43496 43503    35.0
Name: new_cases, dtype: float64
43497 43504    134.0
Name: new_cases, dtype: float64
43498 43505    37.0
Name: new_cases, dtype: float64
43499 43506    70.0
Name: new_cases, dtype: float64
43500 43507    34.0
Name: new_cases, dtype: float64
43501 43508    36.0
Name: new_cases, dtype: float64
43502 43509    30.0
Name: new_cases, dtype: float64
43503 43510    34.0
Name: new_cases, dtype: float64
43504 43511    79.0
Name: new_cases, dtype: float64
43505 43512    103.0
Name: new_cases, dtype: float64
43506 43513    78.0
Name: new_cases, dtype: float64
43507 43514    58.0
Name: new_cases, dtype: float64
43508 43515    11.0
Name: new_cases, dtype: float64
43509 43516    41.0
Name: new_cases, dtype: float64
43510 43517    36.0
Name: new_cases, dtype: float64
43511 43518    22.0
Name: new_cases, dtype: float64
43512 43519    51.0
Name: new_cases, dtype: float64
43513 43520    46.0
Name: new_cases, dtype: float64
43514 43521    5.0
Name: new_cases, dtype: float64
43515 43522    23.0
Name: new_cases, dtype: float64
43516 43523    41.0
Name: new_cases, dtype: float64
43517 43524    27.0
Name: new_cases, dtype: float64
43518 43525    34.0
Name: new_cases, dtype: float64
43519 43526    25.0
Name: new_cases, dtype: float64
43520 43527    53.0
Name: new_cases, dtype: float64
43521 43528    16.0
Name: new_cases, dtype: float64
43522 43529    7.0
Name: new_cases, dtype: float64
43523 43530    17.0
Name: new_cases, dtype: float64
43524 43531    7.0
Name: new_cases, dtype: float64
43525 43532    33.0
Name: new_cases, dtype: float64
43526 43533    13.0
Name: new_cases, dtype: float64
43527 43534    30.0
Name: new_cases, dtype: float64
43528 43535    8.0
Name: new_cases, dtype: float64
43529 43536    4.0
Name: new_cases, dtype: float64
43530 43537    13.0
Name: new_cases, dtype: float64
43531 43538    6.0
Name: new_cases, dtype: float64
43532 43539    23.0
Name: new_cases, dtype: float64
43533 43540    5.0
Name: new_cases, dtype: float64
43534 43541    5.0
Name: new_cases, dtype: float64
43535 43542    1.0
Name: new_cases, dtype: float64
43536 43543    3.0
Name: new_cases, dtype: float64
43537 43544    8.0
Name: new_cases, dtype: float64
43538 43545    2.0
Name: new_cases, dtype: float64
43539 43546    7.0
Name: new_cases, dtype: float64
43540 43547    5.0
Name: new_cases, dtype: float64
43541 43548    8.0
Name: new_cases, dtype: float64
43542 43549    6.0
Name: new_cases, dtype: float64
43543 43550    2.0
Name: new_cases, dtype: float64
43544 43551    5.0
Name: new_cases, dtype: float64
43545 43552    5.0
Name: new_cases, dtype: float64
43546 43553    7.0
Name: new_cases, dtype: float64
43547 43554    8.0
Name: new_cases, dtype: float64
43548 43555    4.0
Name: new_cases, dtype: float64
43549 43556    4.0
Name: new_cases, dtype: float64
43550 43557    10.0
Name: new_cases, dtype: float64
43551 43558    7.0
Name: new_cases, dtype: float64
43552 43559    3.0
Name: new_cases, dtype: float64
43553 43560    6.0
Name: new_cases, dtype: float64
43554 43561    7.0
Name: new_cases, dtype: float64
43555 43562    14.0
Name: new_cases, dtype: float64
43556 43563    2.0
Name: new_cases, dtype: float64
43557 43564    1.0
Name: new_cases, dtype: float64
43558 43565    10.0
Name: new_cases, dtype: float64
43559 43566    6.0
Name: new_cases, dtype: float64
43560 43567    11.0
Name: new_cases, dtype: float64
43561 43568    8.0
Name: new_cases, dtype: float64
43562 43569    6.0
Name: new_cases, dtype: float64
43563 43570    4.0
Name: new_cases, dtype: float64
43564 43571    1.0
Name: new_cases, dtype: float64
43565 43572    0.0
Name: new_cases, dtype: float64
43566 43573    10.0
Name: new_cases, dtype: float64
43567 43574    10.0
Name: new_cases, dtype: float64
43568 43575    20.0
Name: new_cases, dtype: float64
43569 43576    21.0
Name: new_cases, dtype: float64
43570 43577    8.0
Name: new_cases, dtype: float64
43571 43578    1.0
Name: new_cases, dtype: float64
43572 43579    7.0
Name: new_cases, dtype: float64
43573 43580    11.0
Name: new_cases, dtype: float64
43574 43581    7.0
Name: new_cases, dtype: float64
43575 43582    5.0
Name: new_cases, dtype: float64
43576 43583    3.0
Name: new_cases, dtype: float64
43577 43584    0.0
Name: new_cases, dtype: float64
43578 43585    1.0
Name: new_cases, dtype: float64
43579 43586    1.0
Name: new_cases, dtype: float64
43580 43587    2.0
Name: new_cases, dtype: float64
43581 43588    0.0
Name: new_cases, dtype: float64
43582 43589    2.0
Name: new_cases, dtype: float64
43583 43590    2.0
Name: new_cases, dtype: float64
43584 43591    0.0
Name: new_cases, dtype: float64
43585 43592    0.0
Name: new_cases, dtype: float64
43586 43593    1.0
Name: new_cases, dtype: float64
43587 43594    1.0
Name: new_cases, dtype: float64
43588 43595    1.0
Name: new_cases, dtype: float64
43589 43596    2.0
Name: new_cases, dtype: float64
43590 43597    0.0
Name: new_cases, dtype: float64
43591 43598    1.0
Name: new_cases, dtype: float64
43592 43599    0.0
Name: new_cases, dtype: float64
43593 43600    2.0
Name: new_cases, dtype: float64
43594 43601    0.0
Name: new_cases, dtype: float64
43595 43602    1.0
Name: new_cases, dtype: float64
43596 43603    1.0
Name: new_cases, dtype: float64
43597 43604    2.0
Name: new_cases, dtype: float64
43598 43605    0.0
Name: new_cases, dtype: float64
43599 43606    1.0
Name: new_cases, dtype: float64
43600 43607    1.0
Name: new_cases, dtype: float64
43601 43608    8.0
Name: new_cases, dtype: float64

43602 43609    8.0
Name: new_cases, dtype: float64
43603 43610    2.0
Name: new_cases, dtype: float64
43604 43611    1.0
Name: new_cases, dtype: float64
43605 43612    0.0
Name: new_cases, dtype: float64
43606 43613    0.0
Name: new_cases, dtype: float64
43607 43614    1.0
Name: new_cases, dtype: float64
43608 43615    1.0
Name: new_cases, dtype: float64
43609 43616    0.0
Name: new_cases, dtype: float64
43610 43617    4.0
Name: new_cases, dtype: float64
43611 43618    1.0
Name: new_cases, dtype: float64
43612 43619    0.0
Name: new_cases, dtype: float64
43613 43620    0.0
Name: new_cases, dtype: float64
43614 43621    1.0
Name: new_cases, dtype: float64
43615 43622    3.0
Name: new_cases, dtype: float64
43616 43623    2.0
Name: new_cases, dtype: float64
43617 43624    1.0
Name: new_cases, dtype: float64
43618 43625    5.0
Name: new_cases, dtype: float64
43619 43626    1.0
Name: new_cases, dtype: float64
43620 43627    0.0
Name: new_cases, dtype: float64
43621 43628    4.0
Name: new_cases, dtype: float64
43622 43629    4.0
Name: new_cases, dtype: float64
43623 43630    9.0
Name: new_cases, dtype: float64
43624 43631    13.0
Name: new_cases, dtype: float64
43625 43632    8.0
Name: new_cases, dtype: float64
43626 43633    7.0
Name: new_cases, dtype: float64
43627 43634    1.0
Name: new_cases, dtype: float64
43628 43635    11.0
Name: new_cases, dtype: float64
43629 43636    22.0
Name: new_cases, dtype: float64
43630 43637    11.0
Name: new_cases, dtype: float64
43631 43638    9.0
Name: new_cases, dtype: float64
43632 43639    14.0
Name: new_cases, dtype: float64
43633 43640    5.0
Name: new_cases, dtype: float64
43634 43641    6.0
Name: new_cases, dtype: float64
43635 43642    9.0
Name: new_cases, dtype: float64
43636 43643    7.0
Name: new_cases, dtype: float64
43637 43644    0.0
Name: new_cases, dtype: float64
43638 43645    3.0
Name: new_cases, dtype: float64
43639 43646    7.0
Name: new_cases, dtype: float64
43640 43647    6.0
Name: new_cases, dtype: float64
43641 43648    2.0
Name: new_cases, dtype: float64
43642 43649    8.0
Name: new_cases, dtype: float64
43643 43650    7.0
Name: new_cases, dtype: float64
43644 43651    20.0
Name: new_cases, dtype: float64
43645 43652    17.0
Name: new_cases, dtype: float64
43646 43653    21.0
Name: new_cases, dtype: float64
43647 43654    7.0
Name: new_cases, dtype: float64
43648 43655    3.0
Name: new_cases, dtype: float64
43649 43656    19.0
Name: new_cases, dtype: float64
43650 43657    17.0
Name: new_cases, dtype: float64
43651 43658    14.0
Name: new_cases, dtype: float64
43652 43659    18.0
Name: new_cases, dtype: float64
43653 43660    20.0
Name: new_cases, dtype: float64
43654 43661    10.0
Name: new_cases, dtype: float64
43655 43662    2.0
Name: new_cases, dtype: float64
43656 43663    20.0
Name: new_cases, dtype: float64
43657 43664    20.0
Name: new_cases, dtype: float64
43658 43665    26.0
Name: new_cases, dtype: float64
43659 43666    15.0
Name: new_cases, dtype: float64
43660 43667    35.0
Name: new_cases, dtype: float64
43661 43668    25.0
Name: new_cases, dtype: float64
43662 43669    16.0
Name: new_cases, dtype: float64
43663 43670    32.0
Name: new_cases, dtype: float64
43664 43671    21.0
Name: new_cases, dtype: float64
43665 43672    15.0
Name: new_cases, dtype: float64
43666 43673    32.0
Name: new_cases, dtype: float64
43667 43674    23.0
Name: new_cases, dtype: float64
43668 43675    21.0
Name: new_cases, dtype: float64
43669 43676    22.0
Name: new_cases, dtype: float64
43670 43677    24.0
Name: new_cases, dtype: float64
43671 43678    34.0
Name: new_cases, dtype: float64
43672 43679    22.0
Name: new_cases, dtype: float64
43673 43680    36.0
Name: new_cases, dtype: float64
43674 43681    61.0
Name: new_cases, dtype: float64
43675 43682    49.0
Name: new_cases, dtype: float64
43676 43683    17.0
Name: new_cases, dtype: float64
43677 43684    35.0
Name: new_cases, dtype: float64
43678 43685    57.0
Name: new_cases, dtype: float64
43679 43686    43.0
Name: new_cases, dtype: float64
43680 43687    42.0
Name: new_cases, dtype: float64
43681 43688    47.0
Name: new_cases, dtype: float64
43682 43689    35.0
Name: new_cases, dtype: float64
43683 43690    67.0
Name: new_cases, dtype: float64
43684 43691    48.0
Name: new_cases, dtype: float64
43685 43692    56.0
Name: new_cases, dtype: float64
43686 43693    79.0
Name: new_cases, dtype: float64
43687 43694    57.0
Name: new_cases, dtype: float64
43688 43695    70.0
Name: new_cases, dtype: float64
43689 43696    30.0
Name: new_cases, dtype: float64
43690 43697    10.0
Name: new_cases, dtype: float64
43691 43698    42.0
Name: new_cases, dtype: float64
43692 43699    56.0
Name: new_cases, dtype: float64
43693 43700    45.0
Name: new_cases, dtype: float64
43694 43701    49.0
Name: new_cases, dtype: float64
43695 43702    37.0
Name: new_cases, dtype: float64
43696 43703    19.0
Name: new_cases, dtype: float64
43697 43704    18.0
Name: new_cases, dtype: float64
43698 43705    25.0
Name: new_cases, dtype: float64
43699 43706    39.0
Name: new_cases, dtype: float64
43700 43707    33.0
Name: new_cases, dtype: float64
43701 43708    37.0
Name: new_cases, dtype: float64
43702 43709    35.0
Name: new_cases, dtype: float64
43703 43710    26.0
Name: new_cases, dtype: float64
43704 43711    7.0
Name: new_cases, dtype: float64
43705 43712    42.0
Name: new_cases, dtype: float64
43706 43713    44.0
Name: new_cases, dtype: float64
43707 43714    76.0
Name: new_cases, dtype: float64
43708 43715    53.0
Name: new_cases, dtype: float64
43709 43716    51.0
Name: new_cases, dtype: float64
43710 43717    60.0
Name: new_cases, dtype: float64
43711 43718    17.0
Name: new_cases, dtype: float64
43712 43719    37.0
Name: new_cases, dtype: float64
43713 43720    125.0
Name: new_cases, dtype: float64
43714 43721    81.0
Name: new_cases, dtype: float64
43715 43722    100.0
Name: new_cases, dtype: float64
43716 43723    134.0
Name: new_cases, dtype: float64
43717 43724    80.0
Name: new_cases, dtype: float64
43718 43725    61.0
Name: new_cases, dtype: float64
43719 43726    79.0
Name: new_cases, dtype: float64
43720 43727    208.0
Name: new_cases, dtype: float64
43721 43728    131.0
Name: new_cases, dtype: float64
43722 43729    241.0
Name: new_cases, dtype: float64
43723 43730    228.0
Name: new_cases, dtype: float64
43724 43731    192.0
Name: new_cases, dtype: float64
43725 43732    125.0
Name: new_cases, dtype: float64
43726 43733    126.0
Name: new_cases, dtype: float64
43727 43734    132.0
Name: new_cases, dtype: float64
43728 43735    373.0
Name: new_cases, dtype: float64
43729 43736    267.0
Name: new_cases, dtype: float64
43730 43737    264.0
Name: new_cases, dtype: float64
43731 43738    225.0
Name: new_cases, dtype: float64
43732 43739    211.0
Name: new_cases, dtype: float64
43733 43740    185.0
Name: new_cases, dtype: float64
43734 43741    271.0
Name: new_cases, dtype: float64
43735 43742    411.0
Name: new_cases, dtype: float64
43736 43743    361.0
Name: new_cases, dtype: float64
43737 43744    299.0
Name: new_cases, dtype: float64
43738 43745    349.0
Name: new_cases, dtype: float64
43739 43746    232.0
Name: new_cases, dtype: float64
43740 43747    203.0
Name: new_cases, dtype: float64
43741 43748    382.0
Name: new_cases, dtype: float64
43742 43749    414.0
Name: new_cases, dtype: float64
43743 43750    368.0
Name: new_cases, dtype: float64
43744 43751    375.0
Name: new_cases, dtype: float64
43745 43752    354.0
Name: new_cases, dtype: float64
43746 43753    256.0
Name: new_cases, dtype: float64
43747 43754    189.0
Name: new_cases, dtype: float64
43748 43755    522.0
Name: new_cases, dtype: float64
43749 43756    450.0
Name: new_cases, dtype: float64
43750 43757    470.0
Name: new_cases, dtype: float64
43751 43758    561.0
Name: new_cases, dtype: float64
43752 43759    478.0
Name: new_cases, dtype: float64
43753 43760    248.0
Name: new_cases, dtype: float64
43754 43761    284.0
Name: new_cases, dtype: float64
43755 43762    544.0
Name: new_cases, dtype: float64
43756 43763    544.0
Name: new_cases, dtype: float64
43757 43764    358.0
Name: new_cases, dtype: float64
43758 43765    757.0
Name: new_cases, dtype: float64
43759 43766    342.0
Name: new_cases, dtype: float64
43760 43767    330.0
Name: new_cases, dtype: float64
43761 43768    297.0
Name: new_cases, dtype: float64
43762 43769    589.0
Name: new_cases, dtype: float64
43763 43770    733.0
Name: new_cases, dtype: float64
43764 43771    654.0
Name: new_cases, dtype: float64
43765 43772    561.0
Name: new_cases, dtype: float64
43766 43773    575.0
Name: new_cases, dtype: float64
43767 43774    289.0
Name: new_cases, dtype: float64
43768 43775    564.0
Name: new_cases, dtype: float64
43769 43776    662.0
Name: new_cases, dtype: float64
43770 43777    700.0
Name: new_cases, dtype: float64
43771 43778    573.0
Name: new_cases, dtype: float64
43772 43779    445.0
Name: new_cases, dtype: float64
43773 43780    365.0
Name: new_cases, dtype: float64
43774 43781    416.0
Name: new_cases, dtype: float64
43775 43782    475.0
Name: new_cases, dtype: float64
43776 43783    973.0
Name: new_cases, dtype: float64
43777 43784    734.0
Name: new_cases, dtype: float64
43778 43785    416.0
Name: new_cases, dtype: float64
43779 43786    383.0
Name: new_cases, dtype: float64

43780 43787    342.0
Name: new_cases, dtype: float64
43781 43788    390.0
Name: new_cases, dtype: float64
43782 43789    429.0
Name: new_cases, dtype: float64
43783 43790    717.0
Name: new_cases, dtype: float64
43784 43791    1084.0
Name: new_cases, dtype: float64
43785 43792    786.0
Name: new_cases, dtype: float64
43786 43793    552.0
Name: new_cases, dtype: float64
43787 43794    427.0
Name: new_cases, dtype: float64
43788 43795    289.0
Name: new_cases, dtype: float64
43789 43796    333.0
Name: new_cases, dtype: float64
43790 43797    853.0
Name: new_cases, dtype: float64
43791 43798    630.0
Name: new_cases, dtype: float64
43792 43799    475.0
Name: new_cases, dtype: float64
43793 43800    595.0
Name: new_cases, dtype: float64
43794 43801    388.0
Name: new_cases, dtype: float64
43795 43802    265.0
Name: new_cases, dtype: float64
43796 43803    597.0
Name: new_cases, dtype: float64
43797 43804    603.0
Name: new_cases, dtype: float64
43798 43805    668.0
Name: new_cases, dtype: float64
43799 43806    489.0
Name: new_cases, dtype: float64
43800 43807    483.0
Name: new_cases, dtype: float64
43801 43808    532.0
Name: new_cases, dtype: float64
43802 43809    259.0
Name: new_cases, dtype: float64
43803 43810    355.0
Name: new_cases, dtype: float64
43804 43811    636.0
Name: new_cases, dtype: float64
43805 43812    690.0
Name: new_cases, dtype: float64
43806 43813    687.0
Name: new_cases, dtype: float64
43807 43814    404.0
Name: new_cases, dtype: float64
43808 43815    461.0
Name: new_cases, dtype: float64
43809 43816    367.0
Name: new_cases, dtype: float64
43810 43817    403.0
Name: new_cases, dtype: float64
43811 43818    685.0
Name: new_cases, dtype: float64
43812 43819    671.0
Name: new_cases, dtype: float64
43813 43820    591.0
Name: new_cases, dtype: float64
43814 43821    587.0
Name: new_cases, dtype: float64
43815 43822    416.0
Name: new_cases, dtype: float64
43816 43823    339.0
Name: new_cases, dtype: float64
43817 43824    542.0
Name: new_cases, dtype: float64
43818 43825    796.0
Name: new_cases, dtype: float64
43819 43826    675.0
Name: new_cases, dtype: float64
43820 43827    713.0
Name: new_cases, dtype: float64
43821 43828    756.0
Name: new_cases, dtype: float64
43822 43829    667.0
Name: new_cases, dtype: float64
43823 43830    411.0
Name: new_cases, dtype: float64
43824 43831    617.0
Name: new_cases, dtype: float64
43825 43832    856.0
Name: new_cases, dtype: float64
43826 43833    995.0
Name: new_cases, dtype: float64
43827 43834    951.0
Name: new_cases, dtype: float64
43828 43835    787.0
Name: new_cases, dtype: float64
43829 43836    583.0
Name: new_cases, dtype: float64
43830 43837    829.0
Name: new_cases, dtype: float64
43831 43838    962.0
Name: new_cases, dtype: float64
43832 43839    1068.0
Name: new_cases, dtype: float64
43833 43840    1152.0
Name: new_cases, dtype: float64
43834 43841    1203.0
Name: new_cases, dtype: float64
43835 43842    1569.0
Name: new_cases, dtype: float64
43836 43843    1201.0
Name: new_cases, dtype: float64
43837 43844    1028.0
Name: new_cases, dtype: float64
43838 43845    1111.0
Name: new_cases, dtype: float64
43839 43846    1454.0
Name: new_cases, dtype: float64
43840 43847    1417.0
Name: new_cases, dtype: float64
43841 43848    1534.0
Name: new_cases, dtype: float64
43842 43849    1540.0
Name: new_cases, dtype: float64
43843 43850    1319.0
Name: new_cases, dtype: float64
43844 43851    1180.0
Name: new_cases, dtype: float64
43845 43852    1308.0
Name: new_cases, dtype: float64
43846 43853    1482.0
Name: new_cases, dtype: float64
43847 43854    1956.0
Name: new_cases, dtype: float64
43848 43855    1357.0
Name: new_cases, dtype: float64
43849 43856    1586.0
Name: new_cases, dtype: float64
43850 43857    935.0
Name: new_cases, dtype: float64
43851 43858    1279.0
Name: new_cases, dtype: float64
43852 43859    1462.0
Name: new_cases, dtype: float64
43853 43860    1783.0
Name: new_cases, dtype: float64
43854 43861    1700.0
Name: new_cases, dtype: float64
43855 43862    1749.0
Name: new_cases, dtype: float64
43856 43863    1248.0
Name: new_cases, dtype: float64
43857 43864    1373.0
Name: new_cases, dtype: float64
43858 43865    993.0
Name: new_cases, dtype: float64
43859 43866    1062.0
Name: new_cases, dtype: float64
43860 43867    1552.0
Name: new_cases, dtype: float64
43861 43868    1429.0
Name: new_cases, dtype: float64
43862 43869    1150.0
Name: new_cases, dtype: float64
43863 43870    1151.0
Name: new_cases, dtype: float64
43864 43871    892.0
Name: new_cases, dtype: float64
43865 43872    584.0
Name: new_cases, dtype: float64
43866 43873    1202.0
Name: new_cases, dtype: float64
43867 43874    1008.0
Name: new_cases, dtype: float64
43868 43875    829.0
Name: new_cases, dtype: float64
43869 43876    1165.0
Name: new_cases, dtype: float64
43870 43877    519.0
Name: new_cases, dtype: float64
43871 43878    462.0
Name: new_cases, dtype: float64
43872 43879    382.0
Name: new_cases, dtype: float64
43873 43880    899.0
Name: new_cases, dtype: float64
43874 43881    984.0
Name: new_cases, dtype: float64
43875 43882    757.0
Name: new_cases, dtype: float64
43876 43883    677.0
Name: new_cases, dtype: float64
43877 43884    638.0
Name: new_cases, dtype: float64
43878 43885    438.0
Name: new_cases, dtype: float64
43879 43886    269.0
Name: new_cases, dtype: float64
43880 43887    637.0
Name: new_cases, dtype: float64
43881 43888    549.0
Name: new_cases, dtype: float64
43882 43889    571.0
Name: new_cases, dtype: float64
43883 43890    478.0
Name: new_cases, dtype: float64
43884 43891    333.0
Name: new_cases, dtype: float64
43885 43892    543.0
Name: new_cases, dtype: float64
43886 43893    228.0
Name: new_cases, dtype: float64
43887 43894    535.0
Name: new_cases, dtype: float64
43888 43895    472.0
Name: new_cases, dtype: float64
43889 43896    429.0
Name: new_cases, dtype: float64
43890 43897    392.0
Name: new_cases, dtype: float64
43891 43898    390.0
Name: new_cases, dtype: float64
43892 43899    215.0
Name: new_cases, dtype: float64
43893 43900    163.0
Name: new_cases, dtype: float64
43894 43901    458.0
Name: new_cases, dtype: float64
43895 43902    396.0
Name: new_cases, dtype: float64
43896 43903    425.0
Name: new_cases, dtype: float64
43897 43904    362.0
Name: new_cases, dtype: float64
43898 43905    431.0
Name: new_cases, dtype: float64
43899 43906    235.0
Name: new_cases, dtype: float64
43900 43907    258.0
Name: new_cases, dtype: float64
43901 43908    401.0
Name: new_cases, dtype: float64
43902 43909    437.0
Name: new_cases, dtype: float64
43903 43910    366.0
Name: new_cases, dtype: float64
43904 43911    382.0
Name: new_cases, dtype: float64
43905 43912    372.0
Name: new_cases, dtype: float64
43906 43913    225.0
Name: new_cases, dtype: float64
43907 43914    211.0
Name: new_cases, dtype: float64
43908 43915    359.0
Name: new_cases, dtype: float64
43909 43916    368.0
Name: new_cases, dtype: float64
43910 43917    300.0
Name: new_cases, dtype: float64
43911 43918    278.0
Name: new_cases, dtype: float64
43912 43919    280.0
Name: new_cases, dtype: float64
43913 43920    131.0
Name: new_cases, dtype: float64
43914 43921    153.0
Name: new_cases, dtype: float64
43915 43922    294.0
Name: new_cases, dtype: float64
43916 43923    257.0
Name: new_cases, dtype: float64
43917 43924    327.0
Name: new_cases, dtype: float64
43918 43925    225.0
Name: new_cases, dtype: float64
43919 43926    180.0
Name: new_cases, dtype: float64
43920 43927    103.0
Name: new_cases, dtype: float64
43921 43928    77.0
Name: new_cases, dtype: float64
43922 43929    160.0
Name: new_cases, dtype: float64
43923 43930    185.0
Name: new_cases, dtype: float64
43924 43931    144.0
Name: new_cases, dtype: float64
43925 43932    139.0
Name: new_cases, dtype: float64
43926 43933    127.0
Name: new_cases, dtype: float64
43927 43934    62.0
Name: new_cases, dtype: float64
43928 43935    58.0
Name: new_cases, dtype: float64
43929 43936    130.0
Name: new_cases, dtype: float64
43930 43937    130.0
Name: new_cases, dtype: float64
43931 43938    105.0
Name: new_cases, dtype: float64
43932 43939    96.0
Name: new_cases, dtype: float64
43933 43940    63.0
Name: new_cases, dtype: float64
43934 43941    51.0
Name: new_cases, dtype: float64

43935 43942    37.0
Name: new_cases, dtype: float64
43936 43943    86.0
Name: new_cases, dtype: float64
43937 43944    68.0
Name: new_cases, dtype: float64
43938 43945    54.0
Name: new_cases, dtype: float64
43939 43946    54.0
Name: new_cases, dtype: float64
43940 43947    55.0
Name: new_cases, dtype: float64
43941 43948    37.0
Name: new_cases, dtype: float64
43942 43949    28.0
Name: new_cases, dtype: float64
43943 43950    61.0
Name: new_cases, dtype: float64
43944 43951    59.0
Name: new_cases, dtype: float64
43945 43952    37.0
Name: new_cases, dtype: float64
43946 43953    56.0
Name: new_cases, dtype: float64
43947 43954    30.0
Name: new_cases, dtype: float64
43948 43955    25.0
Name: new_cases, dtype: float64
43949 43956    12.0
Name: new_cases, dtype: float64
43950 43957    37.0
Name: new_cases, dtype: float64
43951 43958    25.0
Name: new_cases, dtype: float64
43952 43959    18.0
Name: new_cases, dtype: float64
43953 43960    10.0
Name: new_cases, dtype: float64
43954 43961    33.0
Name: new_cases, dtype: float64
43955 43962    27.0
Name: new_cases, dtype: float64
43956 43963    15.0
Name: new_cases, dtype: float64
43957 43964    45.0
Name: new_cases, dtype: float64
43958 43965    36.0
Name: new_cases, dtype: float64
43959 43966    21.0
Name: new_cases, dtype: float64
43960 43967    38.0
Name: new_cases, dtype: float64
43961 43968    38.0
Name: new_cases, dtype: float64
43962 43969    27.0
Name: new_cases, dtype: float64
43963 43970    19.0
Name: new_cases, dtype: float64
43964 43971    50.0
Name: new_cases, dtype: float64
43965 43972    42.0
Name: new_cases, dtype: float64
43966 43973    58.0
Name: new_cases, dtype: float64
43967 43974    39.0
Name: new_cases, dtype: float64
43968 43975    64.0
Name: new_cases, dtype: float64
43969 43976    27.0
Name: new_cases, dtype: float64
43970 43977    21.0
Name: new_cases, dtype: float64
43971 43978    54.0
Name: new_cases, dtype: float64
43972 43979    56.0
Name: new_cases, dtype: float64
43973 43980    63.0
Name: new_cases, dtype: float64
43974 43981    62.0
Name: new_cases, dtype: float64
43975 43982    64.0
Name: new_cases, dtype: float64
43976 43983    41.0
Name: new_cases, dtype: float64
43977 43984    34.0
Name: new_cases, dtype: float64
43978 43985    81.0
Name: new_cases, dtype: float64
43979 43986    96.0
Name: new_cases, dtype: float64
43980 43987    120.0
Name: new_cases, dtype: float64
43981 43988    83.0
Name: new_cases, dtype: float64
43982 43989    106.0
Name: new_cases, dtype: float64
43983 43990    90.0
Name: new_cases, dtype: float64
43984 43991    66.0
Name: new_cases, dtype: float64
43985 43992    193.0
Name: new_cases, dtype: float64
43986 43993    174.0
Name: new_cases, dtype: float64
43987 43994    220.0
Name: new_cases, dtype: float64
43988 43995    197.0
Name: new_cases, dtype: float64
43989 43996    249.0
Name: new_cases, dtype: float64
43990 43997    128.0
Name: new_cases, dtype: float64
43991 43998    86.0
Name: new_cases, dtype: float64
43992 43999    207.0
Name: new_cases, dtype: float64
43993 44000    243.0
Name: new_cases, dtype: float64
43994 44001    258.0
Name: new_cases, dtype: float64
43995 44002    241.0
Name: new_cases, dtype: float64
43996 44003    230.0
Name: new_cases, dtype: float64
43997 44004    126.0
Name: new_cases, dtype: float64
43998 44005    147.0
Name: new_cases, dtype: float64
43999 44006    289.0
Name: new_cases, dtype: float64
44000 44007    344.0
Name: new_cases, dtype: float64
44001 44008    372.0
Name: new_cases, dtype: float64
44002 44009    272.0
Name: new_cases, dtype: float64
44003 44010    290.0
Name: new_cases, dtype: float64
44004 44011    202.0
Name: new_cases, dtype: float64
44005 44012    163.0
Name: new_cases, dtype: float64
44006 44013    359.0
Name: new_cases, dtype: float64
44007 44014    286.0
Name: new_cases, dtype: float64
44008 44015    357.0
Name: new_cases, dtype: float64
44009 44016    331.0
Name: new_cases, dtype: float64
44010 44017    218.0
Name: new_cases, dtype: float64
44011 44018    101.0
Name: new_cases, dtype: float64
44012 44019    319.0
Name: new_cases, dtype: float64
44013 44020    374.0
Name: new_cases, dtype: float64
44014 44021    437.0
Name: new_cases, dtype: float64
44015 44022    404.0
Name: new_cases, dtype: float64
44016 44023    351.0
Name: new_cases, dtype: float64
44017 44024    322.0
Name: new_cases, dtype: float64
44018 44025    330.0
Name: new_cases, dtype: float64
44019 44026    255.0
Name: new_cases, dtype: float64
44020 44027    357.0
Name: new_cases, dtype: float64
44021 44028    407.0
Name: new_cases, dtype: float64
44022 44029    474.0
Name: new_cases, dtype: float64
44023 44030    344.0
Name: new_cases, dtype: float64
44024 44031    352.0
Name: new_cases, dtype: float64
44025 44032    255.0
Name: new_cases, dtype: float64
44026 44033    213.0
Name: new_cases, dtype: float64
44027 44034    389.0
Name: new_cases, dtype: float64
44028 44035    488.0
Name: new_cases, dtype: float64
44029 44036    467.0
Name: new_cases, dtype: float64
44030 44037    540.0
Name: new_cases, dtype: float64
44031 44038    493.0
Name: new_cases, dtype: float64
44032 44039    329.0
Name: new_cases, dtype: float64
44033 44040    177.0
Name: new_cases, dtype: float64
44034 44041    473.0
Name: new_cases, dtype: float64
44035 44042    524.0
Name: new_cases, dtype: float64
44036 44043    510.0
Name: new_cases, dtype: float64
44037 44044    532.0
Name: new_cases, dtype: float64
44038 44045    391.0
Name: new_cases, dtype: float64
44039 44046    462.0
Name: new_cases, dtype: float64
44040 44047    366.0
Name: new_cases, dtype: float64
44041 44048    463.0
Name: new_cases, dtype: float64
44042 44049    687.0
Name: new_cases, dtype: float64
44043 44050    589.0
Name: new_cases, dtype: float64
44044 44051    548.0
Name: new_cases, dtype: float64
44045 44052    642.0
Name: new_cases, dtype: float64
44046 44053    465.0
Name: new_cases, dtype: float64
44047 44054    390.0
Name: new_cases, dtype: float64
44048 44055    796.0
Name: new_cases, dtype: float64
44049 44056    747.0
Name: new_cases, dtype: float64
44050 44057    788.0
Name: new_cases, dtype: float64
44051 44058    729.0
Name: new_cases, dtype: float64
44052 44059    742.0
Name: new_cases, dtype: float64
44053 44060    629.0
Name: new_cases, dtype: float64
44054 44061    538.0
Name: new_cases, dtype: float64
44055 44062    892.0
Name: new_cases, dtype: float64
44056 44063    1045.0
Name: new_cases, dtype: float64
44057 44064    949.0
Name: new_cases, dtype: float64
44058 44065    954.0
Name: new_cases, dtype: float64
44059 44066    1068.0
Name: new_cases, dtype: float64
44060 44067    815.0
Name: new_cases, dtype: float64
44061 44068    727.0
Name: new_cases, dtype: float64
44062 44069    1256.0
Name: new_cases, dtype: float64
44063 44070    1227.0
Name: new_cases, dtype: float64
44064 44071    1056.0
Name: new_cases, dtype: float64
44065 44072    1275.0
Name: new_cases, dtype: float64
44066 44073    1236.0
Name: new_cases, dtype: float64
44067 44074    1119.0
Name: new_cases, dtype: float64
44068 44075    821.0
Name: new_cases, dtype: float64
44069 44076    1101.0
Name: new_cases, dtype: float64
44070 44077    1346.0
Name: new_cases, dtype: float64
44071 44078    1505.0
Name: new_cases, dtype: float64
44072 44079    1323.0
Name: new_cases, dtype: float64
44073 44080    1642.0
Name: new_cases, dtype: float64
44074 44081    1787.0
Name: new_cases, dtype: float64
44075 44082    1281.0
Name: new_cases, dtype: float64
44076 44083    1189.0
Name: new_cases, dtype: float64
44077 44084    2021.0
Name: new_cases, dtype: float64
44078 44085    1992.0
Name: new_cases, dtype: float64
44079 44086    1679.0
Name: new_cases, dtype: float64
44080 44087    1891.0
Name: new_cases, dtype: float64
44081 44088    1877.0
Name: new_cases, dtype: float64
44082 44089    1413.0
Name: new_cases, dtype: float64
44083 44090    1569.0
Name: new_cases, dtype: float64
44084 44091    2300.0
Name: new_cases, dtype: float64
44085 44092    1943.0
Name: new_cases, dtype: float64
44086 44093    1435.0
Name: new_cases, dtype: float64
44087 44094    1519.0
Name: new_cases, dtype: float64
44088 44095    948.0
Name: new_cases, dtype: float64
44089 44096    787.0
Name: new_cases, dtype: float64
44090 44097    1089.0
Name: new_cases, dtype: float64
44091 44098    1354.0
Name: new_cases, dtype: float64
44092 44099    1271.0
Name: new_cases, dtype: float64
44093 44100    945.0
Name: new_cases, dtype: float64
44094 44101    993.0
Name: new_cases, dtype: float64

44095 44102    561.0
Name: new_cases, dtype: float64
44096 44103    511.0
Name: new_cases, dtype: float64
44097 44104    867.0
Name: new_cases, dtype: float64
44098 44105    1022.0
Name: new_cases, dtype: float64
44099 44106    871.0
Name: new_cases, dtype: float64
44100 44107    714.0
Name: new_cases, dtype: float64
44101 44108    463.0
Name: new_cases, dtype: float64
44102 44109    837.0
Name: new_cases, dtype: float64
44103 44110    403.0
Name: new_cases, dtype: float64
44104 44111    820.0
Name: new_cases, dtype: float64
44105 44112    655.0
Name: new_cases, dtype: float64
44106 44113    619.0
Name: new_cases, dtype: float64
44107 44114    636.0
Name: new_cases, dtype: float64
44108 44115    646.0
Name: new_cases, dtype: float64
44109 44116    389.0
Name: new_cases, dtype: float64
44110 44117    311.0
Name: new_cases, dtype: float64
44111 44118    724.0
Name: new_cases, dtype: float64
44112 44119    587.0
Name: new_cases, dtype: float64
44113 44120    518.0
Name: new_cases, dtype: float64
44114 44121    506.0
Name: new_cases, dtype: float64
44115 44122    459.0
Name: new_cases, dtype: float64
44116 44123    339.0
Name: new_cases, dtype: float64
44117 44124    301.0
Name: new_cases, dtype: float64
44118 44125    543.0
Name: new_cases, dtype: float64
44119 44126    467.0
Name: new_cases, dtype: float64
44120 44127    554.0
Name: new_cases, dtype: float64
44121 44128    588.0
Name: new_cases, dtype: float64
44122 44129    456.0
Name: new_cases, dtype: float64
44123 44130    377.0
Name: new_cases, dtype: float64
44124 44131    317.0
Name: new_cases, dtype: float64
44125 44132    618.0
Name: new_cases, dtype: float64
44126 44133    655.0
Name: new_cases, dtype: float64
44127 44134    645.0
Name: new_cases, dtype: float64
44128 44135    603.0
Name: new_cases, dtype: float64
44129 44136    577.0
Name: new_cases, dtype: float64
44130 44137    426.0
Name: new_cases, dtype: float64
44131 44138    386.0
Name: new_cases, dtype: float64
44132 44139    861.0
Name: new_cases, dtype: float64
44133 44140    725.0
Name: new_cases, dtype: float64
44134 44141    866.0
Name: new_cases, dtype: float64
44135 44142    710.0
Name: new_cases, dtype: float64
44136 44143    465.0
Name: new_cases, dtype: float64
44137 44144    432.0
Name: new_cases, dtype: float64
44138 44145    534.0
Name: new_cases, dtype: float64
44139 44146    980.0
Name: new_cases, dtype: float64
44140 44147    878.0
Name: new_cases, dtype: float64
44141 44148    1377.0
Name: new_cases, dtype: float64
44142 44149    1074.0
Name: new_cases, dtype: float64
44143 44150    715.0
Name: new_cases, dtype: float64
44144 44151    429.0
Name: new_cases, dtype: float64
44145 44152    684.0
Name: new_cases, dtype: float64
44146 44153    1497.0
Name: new_cases, dtype: float64
44147 44154    1488.0
Name: new_cases, dtype: float64
44148 44155    1642.0
Name: new_cases, dtype: float64
44149 44156    1729.0
Name: new_cases, dtype: float64
44150 44157    1647.0
Name: new_cases, dtype: float64
44151 Series([], Name: new_cases, dtype: float64)
44152 Series([], Name: new_cases, dtype: float64)
44153 Series([], Name: new_cases, dtype: float64)
44154 Series([], Name: new_cases, dtype: float64)
44155 Series([], Name: new_cases, dtype: float64)
44156 Series([], Name: new_cases, dtype: float64)
44157 Series([], Name: new_cases, dtype: float64)
48956 48963    0.0
Name: new_cases, dtype: float64
48957 48964    0.0
Name: new_cases, dtype: float64
48958 48965    0.0
Name: new_cases, dtype: float64
48959 48966    0.0
Name: new_cases, dtype: float64
48960 48967    0.0
Name: new_cases, dtype: float64
48961 48968    0.0
Name: new_cases, dtype: float64
48962 48969    0.0
Name: new_cases, dtype: float64
48963 48970    0.0
Name: new_cases, dtype: float64
48964 48971    0.0
Name: new_cases, dtype: float64
48965 48972    0.0
Name: new_cases, dtype: float64
48966 48973    0.0
Name: new_cases, dtype: float64
48967 48974    0.0
Name: new_cases, dtype: float64
48968 48975    0.0
Name: new_cases, dtype: float64
48969 48976    0.0
Name: new_cases, dtype: float64
48970 48977    0.0
Name: new_cases, dtype: float64
48971 48978    0.0
Name: new_cases, dtype: float64
48972 48979    0.0
Name: new_cases, dtype: float64
48973 48980    0.0
Name: new_cases, dtype: float64
48974 48981    0.0
Name: new_cases, dtype: float64
48975 48982    0.0
Name: new_cases, dtype: float64
48976 48983    0.0
Name: new_cases, dtype: float64
48977 48984    1.0
Name: new_cases, dtype: float64
48978 48985    0.0
Name: new_cases, dtype: float64
48979 48986    0.0
Name: new_cases, dtype: float64
48980 48987    1.0
Name: new_cases, dtype: float64
48981 48988    3.0
Name: new_cases, dtype: float64
48982 48989    0.0
Name: new_cases, dtype: float64
48983 48990    0.0
Name: new_cases, dtype: float64
48984 48991    0.0
Name: new_cases, dtype: float64
48985 48992    6.0
Name: new_cases, dtype: float64
48986 48993    3.0
Name: new_cases, dtype: float64
48987 48994    0.0
Name: new_cases, dtype: float64
48988 48995    8.0
Name: new_cases, dtype: float64
48989 48996    7.0
Name: new_cases, dtype: float64
48990 48997    10.0
Name: new_cases, dtype: float64
48991 48998    19.0
Name: new_cases, dtype: float64
48992 48999    0.0
Name: new_cases, dtype: float64
48993 49000    96.0
Name: new_cases, dtype: float64
48994 49001    70.0
Name: new_cases, dtype: float64
48995 49002    19.0
Name: new_cases, dtype: float64
48996 49003    33.0
Name: new_cases, dtype: float64
48997 49004    44.0
Name: new_cases, dtype: float64
48998 49005    15.0
Name: new_cases, dtype: float64
48999 49006    64.0
Name: new_cases, dtype: float64
49000 49007    50.0
Name: new_cases, dtype: float64
49001 49008    73.0
Name: new_cases, dtype: float64
49002 49009    103.0
Name: new_cases, dtype: float64
49003 49010    74.0
Name: new_cases, dtype: float64
49004 49011    92.0
Name: new_cases, dtype: float64
49005 49012    88.0
Name: new_cases, dtype: float64
49006 49013    78.0
Name: new_cases, dtype: float64
49007 49014    83.0
Name: new_cases, dtype: float64
49008 49015    126.0
Name: new_cases, dtype: float64
49009 49016    73.0
Name: new_cases, dtype: float64
49010 49017    112.0
Name: new_cases, dtype: float64
49011 49018    66.0
Name: new_cases, dtype: float64
49012 49019    28.0
Name: new_cases, dtype: float64
49013 49020    72.0
Name: new_cases, dtype: float64
49014 49021    97.0
Name: new_cases, dtype: float64
49015 49022    267.0
Name: new_cases, dtype: float64
49016 49023    45.0
Name: new_cases, dtype: float64
49017 49024    249.0
Name: new_cases, dtype: float64
49018 49025    132.0
Name: new_cases, dtype: float64
49019 49026    179.0
Name: new_cases, dtype: float64
49020 49027    118.0
Name: new_cases, dtype: float64
49021 49028    164.0
Name: new_cases, dtype: float64
49022 49029    136.0
Name: new_cases, dtype: float64
49023 49030    69.0
Name: new_cases, dtype: float64
49024 49031    90.0
Name: new_cases, dtype: float64
49025 49032    97.0
Name: new_cases, dtype: float64
49026 49033    76.0
Name: new_cases, dtype: float64
49027 49034    132.0
Name: new_cases, dtype: float64
49028 49035    120.0
Name: new_cases, dtype: float64
49029 49036    192.0
Name: new_cases, dtype: float64
49030 49037    102.0
Name: new_cases, dtype: float64
49031 49038    85.0
Name: new_cases, dtype: float64
49032 49039    146.0
Name: new_cases, dtype: float64
49033 49040    115.0
Name: new_cases, dtype: float64
49034 49041    155.0
Name: new_cases, dtype: float64
49035 49042    111.0
Name: new_cases, dtype: float64
49036 49043    80.0
Name: new_cases, dtype: float64
49037 49044    101.0
Name: new_cases, dtype: float64
49038 49045    119.0
Name: new_cases, dtype: float64
49039 49046    45.0
Name: new_cases, dtype: float64
49040 49047    166.0
Name: new_cases, dtype: float64
49041 49048    89.0
Name: new_cases, dtype: float64
49042 49049    56.0
Name: new_cases, dtype: float64
49043 49050    125.0
Name: new_cases, dtype: float64
49044 49051    78.0
Name: new_cases, dtype: float64
49045 49052    73.0
Name: new_cases, dtype: float64
49046 49053    85.0
Name: new_cases, dtype: float64
49047 49054    161.0
Name: new_cases, dtype: float64
49048 49055    100.0
Name: new_cases, dtype: float64
49049 49056    65.0
Name: new_cases, dtype: float64
49050 49057    142.0
Name: new_cases, dtype: float64
49051 49058    82.0
Name: new_cases, dtype: float64

49052 49059    22.0
Name: new_cases, dtype: float64
49053 49060    19.0
Name: new_cases, dtype: float64
49054 49061    51.0
Name: new_cases, dtype: float64
49055 49062    91.0
Name: new_cases, dtype: float64
49056 49063    83.0
Name: new_cases, dtype: float64
49057 49064    58.0
Name: new_cases, dtype: float64
49058 49065    61.0
Name: new_cases, dtype: float64
49059 49066    33.0
Name: new_cases, dtype: float64
49060 49067    19.0
Name: new_cases, dtype: float64
49061 49068    44.0
Name: new_cases, dtype: float64
49062 49069    50.0
Name: new_cases, dtype: float64
49063 49070    44.0
Name: new_cases, dtype: float64
49064 49071    31.0
Name: new_cases, dtype: float64
49065 49072    11.0
Name: new_cases, dtype: float64
49066 49073    20.0
Name: new_cases, dtype: float64
49067 49074    29.0
Name: new_cases, dtype: float64
49068 49075    64.0
Name: new_cases, dtype: float64
49069 49076    51.0
Name: new_cases, dtype: float64
49070 49077    33.0
Name: new_cases, dtype: float64
49071 49078    50.0
Name: new_cases, dtype: float64
49072 49079    33.0
Name: new_cases, dtype: float64
49073 49080    26.0
Name: new_cases, dtype: float64
49074 49081    2.0
Name: new_cases, dtype: float64
49075 49082    24.0
Name: new_cases, dtype: float64
49076 49083    0.0
Name: new_cases, dtype: float64
49077 49084    30.0
Name: new_cases, dtype: float64
49078 49085    23.0
Name: new_cases, dtype: float64
49079 49086    17.0
Name: new_cases, dtype: float64
49080 49087    20.0
Name: new_cases, dtype: float64
49081 49088    24.0
Name: new_cases, dtype: float64
49082 49089    15.0
Name: new_cases, dtype: float64
49083 49090    24.0
Name: new_cases, dtype: float64
49084 49091    9.0
Name: new_cases, dtype: float64
49085 49092    14.0
Name: new_cases, dtype: float64
49086 49093    17.0
Name: new_cases, dtype: float64
49087 49094    4.0
Name: new_cases, dtype: float64
49088 49095    4.0
Name: new_cases, dtype: float64
49089 49096    5.0
Name: new_cases, dtype: float64
49090 49097    2.0
Name: new_cases, dtype: float64
49091 49098    14.0
Name: new_cases, dtype: float64
49092 49099    9.0
Name: new_cases, dtype: float64
49093 49100    1.0
Name: new_cases, dtype: float64
49094 49101    1.0
Name: new_cases, dtype: float64
49095 49102    11.0
Name: new_cases, dtype: float64
49096 49103    12.0
Name: new_cases, dtype: float64
49097 49104    5.0
Name: new_cases, dtype: float64
49098 49105    19.0
Name: new_cases, dtype: float64
49099 49106    7.0
Name: new_cases, dtype: float64
49100 49107    0.0
Name: new_cases, dtype: float64
49101 49108    11.0
Name: new_cases, dtype: float64
49102 49109    5.0
Name: new_cases, dtype: float64
49103 49110    22.0
Name: new_cases, dtype: float64
49104 49111    5.0
Name: new_cases, dtype: float64
49105 49112    1.0
Name: new_cases, dtype: float64
49106 49113    6.0
Name: new_cases, dtype: float64
49107 49114    5.0
Name: new_cases, dtype: float64
49108 49115    4.0
Name: new_cases, dtype: float64
49109 49116    5.0
Name: new_cases, dtype: float64
49110 49117    3.0
Name: new_cases, dtype: float64
49111 49118    8.0
Name: new_cases, dtype: float64
49112 49119    6.0
Name: new_cases, dtype: float64
49113 49120    12.0
Name: new_cases, dtype: float64
49114 49121    3.0
Name: new_cases, dtype: float64
49115 49122    1.0
Name: new_cases, dtype: float64
49116 49123    6.0
Name: new_cases, dtype: float64
49117 49124   -5.0
Name: new_cases, dtype: float64
49118 49125   -3.0
Name: new_cases, dtype: float64
49119 49126    8.0
Name: new_cases, dtype: float64
49120 49127    17.0
Name: new_cases, dtype: float64
49121 49128    17.0
Name: new_cases, dtype: float64
49122 49129    5.0
Name: new_cases, dtype: float64
49123 49130    11.0
Name: new_cases, dtype: float64
49124 49131    11.0
Name: new_cases, dtype: float64
49125 49132    10.0
Name: new_cases, dtype: float64
49126 49133    8.0
Name: new_cases, dtype: float64
49127 49134    8.0
Name: new_cases, dtype: float64
49128 49135    5.0
Name: new_cases, dtype: float64
49129 49136    5.0
Name: new_cases, dtype: float64
49130 49137    6.0
Name: new_cases, dtype: float64
49131 49138    10.0
Name: new_cases, dtype: float64
49132 49139    9.0
Name: new_cases, dtype: float64
49133 49140    9.0
Name: new_cases, dtype: float64
49134 49141    11.0
Name: new_cases, dtype: float64
49135 49142    10.0
Name: new_cases, dtype: float64
49136 49143    13.0
Name: new_cases, dtype: float64
49137 49144    17.0
Name: new_cases, dtype: float64
49138 49145    29.0
Name: new_cases, dtype: float64
49139 49146    20.0
Name: new_cases, dtype: float64
49140 49147    22.0
Name: new_cases, dtype: float64
49141 49148    14.0
Name: new_cases, dtype: float64
49142 49149    16.0
Name: new_cases, dtype: float64
49143 49150    17.0
Name: new_cases, dtype: float64
49144 49151    22.0
Name: new_cases, dtype: float64
49145 49152    19.0
Name: new_cases, dtype: float64
49146 49153    41.0
Name: new_cases, dtype: float64
49147 49154    17.0
Name: new_cases, dtype: float64
49148 49155    20.0
Name: new_cases, dtype: float64
49149 49156    11.0
Name: new_cases, dtype: float64
49150 49157    21.0
Name: new_cases, dtype: float64
49151 49158    24.0
Name: new_cases, dtype: float64
49152 49159    29.0
Name: new_cases, dtype: float64
49153 49160    37.0
Name: new_cases, dtype: float64
49154 49161    29.0
Name: new_cases, dtype: float64
49155 49162    35.0
Name: new_cases, dtype: float64
49156 49163    14.0
Name: new_cases, dtype: float64
49157 49164    18.0
Name: new_cases, dtype: float64
49158 49165    43.0
Name: new_cases, dtype: float64
49159 49166    21.0
Name: new_cases, dtype: float64
49160 49167    17.0
Name: new_cases, dtype: float64
49161 49168    23.0
Name: new_cases, dtype: float64
49162 49169    7.0
Name: new_cases, dtype: float64
49163 49170    28.0
Name: new_cases, dtype: float64
49164 49171    9.0
Name: new_cases, dtype: float64
49165 49172    56.0
Name: new_cases, dtype: float64
49166 49173    19.0
Name: new_cases, dtype: float64
49167 49174    39.0
Name: new_cases, dtype: float64
49168 49175    25.0
Name: new_cases, dtype: float64
49169 49176    36.0
Name: new_cases, dtype: float64
49170 49177    30.0
Name: new_cases, dtype: float64
49171 49178    36.0
Name: new_cases, dtype: float64
49172 49179    10.0
Name: new_cases, dtype: float64
49173 49180    93.0
Name: new_cases, dtype: float64
49174 49181    39.0
Name: new_cases, dtype: float64
49175 49182    43.0
Name: new_cases, dtype: float64
49176 49183    45.0
Name: new_cases, dtype: float64
49177 49184    23.0
Name: new_cases, dtype: float64
49178 49185    47.0
Name: new_cases, dtype: float64
49179 49186    98.0
Name: new_cases, dtype: float64
49180 49187    25.0
Name: new_cases, dtype: float64
49181 49188    49.0
Name: new_cases, dtype: float64
49182 49189    59.0
Name: new_cases, dtype: float64
49183 49190    64.0
Name: new_cases, dtype: float64
49184 49191    58.0
Name: new_cases, dtype: float64
49185 49192    66.0
Name: new_cases, dtype: float64
49186 49193    149.0
Name: new_cases, dtype: float64
49187 49194    93.0
Name: new_cases, dtype: float64
49188 49195    91.0
Name: new_cases, dtype: float64
49189 49196    105.0
Name: new_cases, dtype: float64
49190 49197    93.0
Name: new_cases, dtype: float64
49191 49198    105.0
Name: new_cases, dtype: float64
49192 49199    61.0
Name: new_cases, dtype: float64
49193 49200    149.0
Name: new_cases, dtype: float64
49194 49201    100.0
Name: new_cases, dtype: float64
49195 49202    111.0
Name: new_cases, dtype: float64
49196 49203    141.0
Name: new_cases, dtype: float64
49197 49204    147.0
Name: new_cases, dtype: float64
49198 49205    147.0
Name: new_cases, dtype: float64
49199 49206    164.0
Name: new_cases, dtype: float64
49200 49207    227.0
Name: new_cases, dtype: float64
49201 49208    120.0
Name: new_cases, dtype: float64
49202 49209    296.0
Name: new_cases, dtype: float64
49203 49210    235.0
Name: new_cases, dtype: float64
49204 49211    269.0
Name: new_cases, dtype: float64
49205 49212    149.0
Name: new_cases, dtype: float64
49206 49213    214.0
Name: new_cases, dtype: float64
49207 49214    287.0
Name: new_cases, dtype: float64
49208 49215    204.0
Name: new_cases, dtype: float64
49209 49216    241.0
Name: new_cases, dtype: float64
49210 49217    189.0
Name: new_cases, dtype: float64
49211 49218    160.0
Name: new_cases, dtype: float64
49212 49219    131.0
Name: new_cases, dtype: float64
49213 49220    131.0
Name: new_cases, dtype: float64
49214 49221    294.0
Name: new_cases, dtype: float64
49215 49222    222.0
Name: new_cases, dtype: float64
49216 49223    184.0
Name: new_cases, dtype: float64
49217 49224    219.0
Name: new_cases, dtype: float64
49218 49225    178.0
Name: new_cases, dtype: float64
49219 49226    196.0
Name: new_cases, dtype: float64
49220 49227    122.0
Name: new_cases, dtype: float64
49221 49228    193.0
Name: new_cases, dtype: float64
49222 49229    215.0
Name: new_cases, dtype: float64
49223 49230    188.0
Name: new_cases, dtype: float64

49224 49231    344.0
Name: new_cases, dtype: float64
49225 49232    203.0
Name: new_cases, dtype: float64
49226 49233    178.0
Name: new_cases, dtype: float64
49227 49234    109.0
Name: new_cases, dtype: float64
49228 49235    237.0
Name: new_cases, dtype: float64
49229 49236    293.0
Name: new_cases, dtype: float64
49230 49237    189.0
Name: new_cases, dtype: float64
49231 49238    266.0
Name: new_cases, dtype: float64
49232 49239    0.0
Name: new_cases, dtype: float64
49233 49240    412.0
Name: new_cases, dtype: float64
49234 49241    90.0
Name: new_cases, dtype: float64
49235 49242    220.0
Name: new_cases, dtype: float64
49236 49243    238.0
Name: new_cases, dtype: float64
49237 49244    197.0
Name: new_cases, dtype: float64
49238 49245    316.0
Name: new_cases, dtype: float64
49239 49246    244.0
Name: new_cases, dtype: float64
49240 49247    213.0
Name: new_cases, dtype: float64
49241 49248    104.0
Name: new_cases, dtype: float64
49242 49249    228.0
Name: new_cases, dtype: float64
49243 49250    288.0
Name: new_cases, dtype: float64
49244 49251    351.0
Name: new_cases, dtype: float64
49245 49252    461.0
Name: new_cases, dtype: float64
49246 49253    469.0
Name: new_cases, dtype: float64
49247 49254    423.0
Name: new_cases, dtype: float64
49248 49255    297.0
Name: new_cases, dtype: float64
49249 49256    353.0
Name: new_cases, dtype: float64
49250 49257    363.0
Name: new_cases, dtype: float64
49251 49258    496.0
Name: new_cases, dtype: float64
49252 49259    618.0
Name: new_cases, dtype: float64
49253 49260    541.0
Name: new_cases, dtype: float64
49254 49261    322.0
Name: new_cases, dtype: float64
49255 49262    283.0
Name: new_cases, dtype: float64
49256 49263    550.0
Name: new_cases, dtype: float64
49257 49264    420.0
Name: new_cases, dtype: float64
49258 49265    540.0
Name: new_cases, dtype: float64
49259 49266    336.0
Name: new_cases, dtype: float64
49260 49267    460.0
Name: new_cases, dtype: float64
49261 49268    413.0
Name: new_cases, dtype: float64
49262 49269    250.0
Name: new_cases, dtype: float64
49263 49270    361.0
Name: new_cases, dtype: float64
49264 49271    490.0
Name: new_cases, dtype: float64
49265 49272    840.0
Name: new_cases, dtype: float64
49266 49273    501.0
Name: new_cases, dtype: float64
49267 49274    377.0
Name: new_cases, dtype: float64
49268 49275    360.0
Name: new_cases, dtype: float64
49269 49276    300.0
Name: new_cases, dtype: float64
49270 49277    349.0
Name: new_cases, dtype: float64
49271 49278    411.0
Name: new_cases, dtype: float64
49272 49279    358.0
Name: new_cases, dtype: float64
49273 49280    354.0
Name: new_cases, dtype: float64
49274 49281    271.0
Name: new_cases, dtype: float64
49275 49282    309.0
Name: new_cases, dtype: float64
49276 49283    252.0
Name: new_cases, dtype: float64
49277 49284    303.0
Name: new_cases, dtype: float64
49278 49285    367.0
Name: new_cases, dtype: float64
49279 49286    363.0
Name: new_cases, dtype: float64
49280 49287    201.0
Name: new_cases, dtype: float64
49281 49288    173.0
Name: new_cases, dtype: float64
49282 49289    156.0
Name: new_cases, dtype: float64
49283 49290    160.0
Name: new_cases, dtype: float64
49284 49291    283.0
Name: new_cases, dtype: float64
49285 49292    438.0
Name: new_cases, dtype: float64
49286 49293    249.0
Name: new_cases, dtype: float64
49287 49294    296.0
Name: new_cases, dtype: float64
49288 49295    201.0
Name: new_cases, dtype: float64
49289 49296    168.0
Name: new_cases, dtype: float64
49290 49297    147.0
Name: new_cases, dtype: float64
49291 49298    299.0
Name: new_cases, dtype: float64
49292 49299    331.0
Name: new_cases, dtype: float64
49293 49300    223.0
Name: new_cases, dtype: float64
49294 49301    296.0
Name: new_cases, dtype: float64
49295 49302    324.0
Name: new_cases, dtype: float64
49296 49303    198.0
Name: new_cases, dtype: float64
49297 49304    200.0
Name: new_cases, dtype: float64
49298 49305    221.0
Name: new_cases, dtype: float64
49299 49306    324.0
Name: new_cases, dtype: float64
49300 49307    258.0
Name: new_cases, dtype: float64
49301 49308    318.0
Name: new_cases, dtype: float64
49302 49309    190.0
Name: new_cases, dtype: float64
49303 49310    236.0
Name: new_cases, dtype: float64
49304 49311    168.0
Name: new_cases, dtype: float64
49305 49312    217.0
Name: new_cases, dtype: float64
49306 49313    444.0
Name: new_cases, dtype: float64
49307 49314    399.0
Name: new_cases, dtype: float64
49308 49315    350.0
Name: new_cases, dtype: float64
49309 49316    419.0
Name: new_cases, dtype: float64
49310 49317    246.0
Name: new_cases, dtype: float64
49311 49318    192.0
Name: new_cases, dtype: float64
49312 49319    348.0
Name: new_cases, dtype: float64
49313 49320    496.0
Name: new_cases, dtype: float64
49314 49321    423.0
Name: new_cases, dtype: float64
49315 49322    363.0
Name: new_cases, dtype: float64
49316 49323    469.0
Name: new_cases, dtype: float64
49317 49324    367.0
Name: new_cases, dtype: float64
49318 49325    244.0
Name: new_cases, dtype: float64
49319 49326    302.0
Name: new_cases, dtype: float64
49320 49327    265.0
Name: new_cases, dtype: float64
49321 49328    444.0
Name: new_cases, dtype: float64
49322 49329    401.0
Name: new_cases, dtype: float64
49323 49330    368.0
Name: new_cases, dtype: float64
49324 49331    354.0
Name: new_cases, dtype: float64
49325 49332    353.0
Name: new_cases, dtype: float64
49326 49333    438.0
Name: new_cases, dtype: float64
49327 49334    400.0
Name: new_cases, dtype: float64
49328 49335    358.0
Name: new_cases, dtype: float64
49329 49336    407.0
Name: new_cases, dtype: float64
49330 49337    435.0
Name: new_cases, dtype: float64
49331 49338    312.0
Name: new_cases, dtype: float64
49332 49339    343.0
Name: new_cases, dtype: float64
49333 49340    385.0
Name: new_cases, dtype: float64
49334 49341    548.0
Name: new_cases, dtype: float64
49335 49342    614.0
Name: new_cases, dtype: float64
49336 49343    444.0
Name: new_cases, dtype: float64
49337 49344    632.0
Name: new_cases, dtype: float64
49338 49345    457.0
Name: new_cases, dtype: float64
49339 49346    390.0
Name: new_cases, dtype: float64
49340 49347    400.0
Name: new_cases, dtype: float64
49341 49348    590.0
Name: new_cases, dtype: float64
49342 49349    565.0
Name: new_cases, dtype: float64
49343 49350    720.0
Name: new_cases, dtype: float64
49344 49351    645.0
Name: new_cases, dtype: float64
49345 49352    620.0
Name: new_cases, dtype: float64
49346 49353    392.0
Name: new_cases, dtype: float64
49347 49354    581.0
Name: new_cases, dtype: float64
49348 49355    797.0
Name: new_cases, dtype: float64
49349 49356    758.0
Name: new_cases, dtype: float64
49350 49357    704.0
Name: new_cases, dtype: float64
49351 49358    648.0
Name: new_cases, dtype: float64
49352 49359    511.0
Name: new_cases, dtype: float64
49353 49360    459.0
Name: new_cases, dtype: float64
49354 49361    588.0
Name: new_cases, dtype: float64
49355 49362    779.0
Name: new_cases, dtype: float64
49356 49363    720.0
Name: new_cases, dtype: float64
49357 49364    706.0
Name: new_cases, dtype: float64
49358 49365    691.0
Name: new_cases, dtype: float64
49359 49366    863.0
Name: new_cases, dtype: float64
49360 49367    465.0
Name: new_cases, dtype: float64
49361 49368    517.0
Name: new_cases, dtype: float64
49362 49369    842.0
Name: new_cases, dtype: float64
49363 49370    804.0
Name: new_cases, dtype: float64
49364 49371    770.0
Name: new_cases, dtype: float64
49365 49372    856.0
Name: new_cases, dtype: float64
49366 49373    520.0
Name: new_cases, dtype: float64
49367 49374    430.0
Name: new_cases, dtype: float64
49368 49375    640.0
Name: new_cases, dtype: float64
49369 49376    803.0
Name: new_cases, dtype: float64
49370 49377    726.0
Name: new_cases, dtype: float64
49371 49378    512.0
Name: new_cases, dtype: float64
49372 49379    791.0
Name: new_cases, dtype: float64
49373 49380    458.0
Name: new_cases, dtype: float64
49374 49381    422.0
Name: new_cases, dtype: float64
49375 49382    420.0
Name: new_cases, dtype: float64
49376 49383    607.0
Name: new_cases, dtype: float64
49377 49384    654.0
Name: new_cases, dtype: float64
49378 49385    566.0
Name: new_cases, dtype: float64
49379 49386    422.0
Name: new_cases, dtype: float64
49380 49387    302.0
Name: new_cases, dtype: float64
49381 49388    341.0
Name: new_cases, dtype: float64
49382 49389    331.0
Name: new_cases, dtype: float64
49383 49390    348.0
Name: new_cases, dtype: float64
49384 49391    426.0
Name: new_cases, dtype: float64
49385 49392    419.0
Name: new_cases, dtype: float64
49386 49393    446.0
Name: new_cases, dtype: float64
49387 49394    346.0
Name: new_cases, dtype: float64
49388 49395    225.0
Name: new_cases, dtype: float64
49389 49396    286.0
Name: new_cases, dtype: float64
49390 49397    400.0
Name: new_cases, dtype: float64
49391 49398    289.0
Name: new_cases, dtype: float64
49392 49399    380.0
Name: new_cases, dtype: float64
49393 49400    0.0
Name: new_cases, dtype: float64
49394 49401    498.0
Name: new_cases, dtype: float64
49395 49402    156.0
Name: new_cases, dtype: float64
49396 49403    214.0
Name: new_cases, dtype: float64
49397 49404    296.0
Name: new_cases, dtype: float64
49398 49405    280.0
Name: new_cases, dtype: float64

49399 49406    267.0
Name: new_cases, dtype: float64
49400 49407    263.0
Name: new_cases, dtype: float64
49401 49408    197.0
Name: new_cases, dtype: float64
49402 49409    133.0
Name: new_cases, dtype: float64
49403 49410    224.0
Name: new_cases, dtype: float64
49404 49411    244.0
Name: new_cases, dtype: float64
49405 49412    208.0
Name: new_cases, dtype: float64
49406 49413    195.0
Name: new_cases, dtype: float64
49407 49414    288.0
Name: new_cases, dtype: float64
49408 49415    132.0
Name: new_cases, dtype: float64
49409 49416    117.0
Name: new_cases, dtype: float64
49410 49417    184.0
Name: new_cases, dtype: float64
49411 49418    269.0
Name: new_cases, dtype: float64
49412 49419    280.0
Name: new_cases, dtype: float64
49413 49420    254.0
Name: new_cases, dtype: float64
49414 49421    229.0
Name: new_cases, dtype: float64
49415 49422    162.0
Name: new_cases, dtype: float64
49416 49423    143.0
Name: new_cases, dtype: float64
49417 49424    124.0
Name: new_cases, dtype: float64
49418 49425    280.0
Name: new_cases, dtype: float64
49419 49426    262.0
Name: new_cases, dtype: float64
49420 49427    154.0
Name: new_cases, dtype: float64
49421 49428    192.0
Name: new_cases, dtype: float64
49422 49429    227.0
Name: new_cases, dtype: float64
49423 49430    144.0
Name: new_cases, dtype: float64
49424 49431    149.0
Name: new_cases, dtype: float64
49425 49432    289.0
Name: new_cases, dtype: float64
49426 49433    259.0
Name: new_cases, dtype: float64
49427 49434    211.0
Name: new_cases, dtype: float64
49428 49435    248.0
Name: new_cases, dtype: float64
49429 49436    121.0
Name: new_cases, dtype: float64
49430 49437    93.0
Name: new_cases, dtype: float64
49431 49438    125.0
Name: new_cases, dtype: float64
49432 49439    220.0
Name: new_cases, dtype: float64
49433 49440    98.0
Name: new_cases, dtype: float64
49434 49441    182.0
Name: new_cases, dtype: float64
49435 49442    0.0
Name: new_cases, dtype: float64
49436 49443    188.0
Name: new_cases, dtype: float64
49437 49444    56.0
Name: new_cases, dtype: float64
49438 49445    154.0
Name: new_cases, dtype: float64
49439 49446    128.0
Name: new_cases, dtype: float64
49440 49447    143.0
Name: new_cases, dtype: float64
49441 49448    125.0
Name: new_cases, dtype: float64
49442 49449    120.0
Name: new_cases, dtype: float64
49443 49450    68.0
Name: new_cases, dtype: float64
49444 49451    55.0
Name: new_cases, dtype: float64
49445 49452    113.0
Name: new_cases, dtype: float64
49446 49453    126.0
Name: new_cases, dtype: float64
49447 49454    93.0
Name: new_cases, dtype: float64
49448 49455    47.0
Name: new_cases, dtype: float64
49449 49456    114.0
Name: new_cases, dtype: float64
49450 49457    47.0
Name: new_cases, dtype: float64
49451 49458    29.0
Name: new_cases, dtype: float64
49452 49459    73.0
Name: new_cases, dtype: float64
49453 49460    103.0
Name: new_cases, dtype: float64
49454 49461    55.0
Name: new_cases, dtype: float64
49455 49462    73.0
Name: new_cases, dtype: float64
49456 49463    115.0
Name: new_cases, dtype: float64
49457 49464    65.0
Name: new_cases, dtype: float64
49458 49465    45.0
Name: new_cases, dtype: float64
49459 49466    110.0
Name: new_cases, dtype: float64
49460 49467    107.0
Name: new_cases, dtype: float64
49461 49468    123.0
Name: new_cases, dtype: float64
49462 49469    0.0
Name: new_cases, dtype: float64
49463 49470    270.0
Name: new_cases, dtype: float64
49464 49471    95.0
Name: new_cases, dtype: float64
49465 49472    84.0
Name: new_cases, dtype: float64
49466 49473    219.0
Name: new_cases, dtype: float64
49467 49474    355.0
Name: new_cases, dtype: float64
49468 49475    222.0
Name: new_cases, dtype: float64
49469 49476    216.0
Name: new_cases, dtype: float64
49470 49477    192.0
Name: new_cases, dtype: float64
49471 49478    91.0
Name: new_cases, dtype: float64
49472 49479    106.0
Name: new_cases, dtype: float64
49473 49480    222.0
Name: new_cases, dtype: float64
49474 49481    258.0
Name: new_cases, dtype: float64
49475 49482    300.0
Name: new_cases, dtype: float64
49476 49483    302.0
Name: new_cases, dtype: float64
49477 49484    293.0
Name: new_cases, dtype: float64
49478 49485    138.0
Name: new_cases, dtype: float64
49479 49486    133.0
Name: new_cases, dtype: float64
49480 49487    290.0
Name: new_cases, dtype: float64
49481 49488    383.0
Name: new_cases, dtype: float64
49482 49489    324.0
Name: new_cases, dtype: float64
49483 49490    380.0
Name: new_cases, dtype: float64
49484 49491    384.0
Name: new_cases, dtype: float64
49485 49492    180.0
Name: new_cases, dtype: float64
49486 49493    156.0
Name: new_cases, dtype: float64
49487 49494    461.0
Name: new_cases, dtype: float64
49488 49495    453.0
Name: new_cases, dtype: float64
49489 49496    404.0
Name: new_cases, dtype: float64
49490 49497    412.0
Name: new_cases, dtype: float64
49491 49498    570.0
Name: new_cases, dtype: float64
49492 49499    360.0
Name: new_cases, dtype: float64
49493 49500    267.0
Name: new_cases, dtype: float64
49494 49501    612.0
Name: new_cases, dtype: float64
49495 49502    644.0
Name: new_cases, dtype: float64
49496 49503    765.0
Name: new_cases, dtype: float64
49497 49504    748.0
Name: new_cases, dtype: float64
49498 49505    794.0
Name: new_cases, dtype: float64
49499 49506    519.0
Name: new_cases, dtype: float64
49500 49507    345.0
Name: new_cases, dtype: float64
49501 49508    692.0
Name: new_cases, dtype: float64
49502 49509    872.0
Name: new_cases, dtype: float64
49503 49510    752.0
Name: new_cases, dtype: float64
49504 49511    738.0
Name: new_cases, dtype: float64
49505 49512    165.0
Name: new_cases, dtype: float64
49506 49513    1322.0
Name: new_cases, dtype: float64
49507 49514    449.0
Name: new_cases, dtype: float64
49508 49515    781.0
Name: new_cases, dtype: float64
49509 49516    844.0
Name: new_cases, dtype: float64
49510 49517    1024.0
Name: new_cases, dtype: float64
49511 49518    926.0
Name: new_cases, dtype: float64
49512 49519    765.0
Name: new_cases, dtype: float64
49513 49520    535.0
Name: new_cases, dtype: float64
49514 49521    451.0
Name: new_cases, dtype: float64
49515 49522    665.0
Name: new_cases, dtype: float64
49516 49523    673.0
Name: new_cases, dtype: float64
49517 49524    866.0
Name: new_cases, dtype: float64
49518 49525    684.0
Name: new_cases, dtype: float64
49519 49526    673.0
Name: new_cases, dtype: float64
49520 49527    503.0
Name: new_cases, dtype: float64
49521 49528    371.0
Name: new_cases, dtype: float64
49522 49529    644.0
Name: new_cases, dtype: float64
49523 49530    574.0
Name: new_cases, dtype: float64
49524 49531    650.0
Name: new_cases, dtype: float64
49525 49532    570.0
Name: new_cases, dtype: float64
49526 49533    619.0
Name: new_cases, dtype: float64
49527 49534    619.0
Name: new_cases, dtype: float64
49528 49535    472.0
Name: new_cases, dtype: float64
49529 49536    617.0
Name: new_cases, dtype: float64
49530 49537    679.0
Name: new_cases, dtype: float64
49531 49538    683.0
Name: new_cases, dtype: float64
49532 49539    561.0
Name: new_cases, dtype: float64
49533 49540    87.0
Name: new_cases, dtype: float64
49534 49541    910.0
Name: new_cases, dtype: float64
49535 49542    408.0
Name: new_cases, dtype: float64
49536 49543    544.0
Name: new_cases, dtype: float64
49537 49544    632.0
Name: new_cases, dtype: float64
49538 49545    486.0
Name: new_cases, dtype: float64
49539 49546    490.0
Name: new_cases, dtype: float64
49540 49547    0.0
Name: new_cases, dtype: float64
49541 49548    976.0
Name: new_cases, dtype: float64
49542 49549    213.0
Name: new_cases, dtype: float64
49543 49550    454.0
Name: new_cases, dtype: float64
49544 49551    522.0
Name: new_cases, dtype: float64
49545 49552    487.0
Name: new_cases, dtype: float64
49546 49553    501.0
Name: new_cases, dtype: float64
49547 49554    391.0
Name: new_cases, dtype: float64
49548 49555    51.0
Name: new_cases, dtype: float64
49549 49556    0.0
Name: new_cases, dtype: float64
49550 49557    860.0
Name: new_cases, dtype: float64
49551 49558    477.0
Name: new_cases, dtype: float64
49552 49559    474.0
Name: new_cases, dtype: float64
49553 49560    510.0
Name: new_cases, dtype: float64
49554 49561    0.0
Name: new_cases, dtype: float64
49555 49562    827.0
Name: new_cases, dtype: float64
49556 49563    273.0
Name: new_cases, dtype: float64
49557 49564    409.0
Name: new_cases, dtype: float64
49558 49565    802.0
Name: new_cases, dtype: float64

49559 49566    663.0
Name: new_cases, dtype: float64
49560 49567    562.0
Name: new_cases, dtype: float64
49561 49568    0.0
Name: new_cases, dtype: float64
49562 49569    0.0
Name: new_cases, dtype: float64
49563 49570    1302.0
Name: new_cases, dtype: float64
49564 49571    583.0
Name: new_cases, dtype: float64
49565 49572    666.0
Name: new_cases, dtype: float64
49566 49573    689.0
Name: new_cases, dtype: float64
49567 49574    325.0
Name: new_cases, dtype: float64
49568 49575    0.0
Name: new_cases, dtype: float64
49569 49576    0.0
Name: new_cases, dtype: float64
49570 49577    1618.0
Name: new_cases, dtype: float64
49571 49578    622.0
Name: new_cases, dtype: float64
49572 49579    753.0
Name: new_cases, dtype: float64
49573 49580    502.0
Name: new_cases, dtype: float64
49574 49581    723.0
Name: new_cases, dtype: float64
49575 49582    0.0
Name: new_cases, dtype: float64
49576 49583    0.0
Name: new_cases, dtype: float64
49577 49584    1310.0
Name: new_cases, dtype: float64
49578 49585    580.0
Name: new_cases, dtype: float64
49579 49586    312.0
Name: new_cases, dtype: float64
49580 49587    608.0
Name: new_cases, dtype: float64
49581 49588    449.0
Name: new_cases, dtype: float64
49582 49589    0.0
Name: new_cases, dtype: float64
49583 49590    0.0
Name: new_cases, dtype: float64
49584 49591    1732.0
Name: new_cases, dtype: float64
49585 49592    659.0
Name: new_cases, dtype: float64
49586 49593    739.0
Name: new_cases, dtype: float64
49587 49594    673.0
Name: new_cases, dtype: float64
49588 49595    572.0
Name: new_cases, dtype: float64
49589 49596    0.0
Name: new_cases, dtype: float64
49590 49597    0.0
Name: new_cases, dtype: float64
49591 49598    1460.0
Name: new_cases, dtype: float64
49592 49599    807.0
Name: new_cases, dtype: float64
49593 49600    1150.0
Name: new_cases, dtype: float64
49594 49601    740.0
Name: new_cases, dtype: float64
49595 49602    788.0
Name: new_cases, dtype: float64
49596 49603    0.0
Name: new_cases, dtype: float64
49597 49604    0.0
Name: new_cases, dtype: float64
49598 49605    2016.0
Name: new_cases, dtype: float64
49599 49606    810.0
Name: new_cases, dtype: float64
49600 49607    954.0
Name: new_cases, dtype: float64
49601 49608    863.0
Name: new_cases, dtype: float64
49602 49609    0.0
Name: new_cases, dtype: float64
49603 49610    0.0
Name: new_cases, dtype: float64
49604 49611    0.0
Name: new_cases, dtype: float64
49605 49612    3166.0
Name: new_cases, dtype: float64
49606 49613    937.0
Name: new_cases, dtype: float64
49607 49614    1151.0
Name: new_cases, dtype: float64
49608 49615    1259.0
Name: new_cases, dtype: float64
49609 49616    1191.0
Name: new_cases, dtype: float64
49610 49617    0.0
Name: new_cases, dtype: float64
49611 49618    0.0
Name: new_cases, dtype: float64
49612 49619    2616.0
Name: new_cases, dtype: float64
49613 49620    1088.0
Name: new_cases, dtype: float64
49614 49621    1007.0
Name: new_cases, dtype: float64
49615 49622    1344.0
Name: new_cases, dtype: float64
49616 49623    1406.0
Name: new_cases, dtype: float64
49617 49624    0.0
Name: new_cases, dtype: float64
49618 49625    0.0
Name: new_cases, dtype: float64
49619 49626    3338.0
Name: new_cases, dtype: float64
49620 49627    916.0
Name: new_cases, dtype: float64
49621 49628    1570.0
Name: new_cases, dtype: float64
49622 49629    1622.0
Name: new_cases, dtype: float64
49623 49630    1496.0
Name: new_cases, dtype: float64
49624 49631    0.0
Name: new_cases, dtype: float64
49625 49632    0.0
Name: new_cases, dtype: float64
49626 49633    3412.0
Name: new_cases, dtype: float64
49627 49634    1542.0
Name: new_cases, dtype: float64
49628 49635    1296.0
Name: new_cases, dtype: float64
49629 49636    1781.0
Name: new_cases, dtype: float64
49630 49637    1794.0
Name: new_cases, dtype: float64
49631 49638    0.0
Name: new_cases, dtype: float64
49632 49639    0.0
Name: new_cases, dtype: float64
49633 49640    4306.0
Name: new_cases, dtype: float64
49634 49641    1676.0
Name: new_cases, dtype: float64
49635 49642    2225.0
Name: new_cases, dtype: float64
49636 49643    1981.0
Name: new_cases, dtype: float64
49637 49644    2079.0
Name: new_cases, dtype: float64
49638 49645    0.0
Name: new_cases, dtype: float64
49639 49646    0.0
Name: new_cases, dtype: float64
49640 49647    5932.0
Name: new_cases, dtype: float64
49641 49648    2042.0
Name: new_cases, dtype: float64
49642 49649    2877.0
Name: new_cases, dtype: float64
49643 49650    3000.0
Name: new_cases, dtype: float64
49644 49651    3223.0
Name: new_cases, dtype: float64
49645 49652    0.0
Name: new_cases, dtype: float64
49646 49653    0.0
Name: new_cases, dtype: float64
49647 49654    3649.0
Name: new_cases, dtype: float64
49648 49655    2714.0
Name: new_cases, dtype: float64
49649 49656    2584.0
Name: new_cases, dtype: float64
49650 49657    9619.0
Name: new_cases, dtype: float64
49651 49658    11334.0
Name: new_cases, dtype: float64
49652 49659    0.0
Name: new_cases, dtype: float64
49653 49660    0.0
Name: new_cases, dtype: float64
49654 49661    17047.0
Name: new_cases, dtype: float64
49655 49662    5492.0
Name: new_cases, dtype: float64
49656 49663    6791.0
Name: new_cases, dtype: float64
49657 49664    5979.0
Name: new_cases, dtype: float64
49658 49665    9921.0
Name: new_cases, dtype: float64
49659 Series([], Name: new_cases, dtype: float64)
49660 Series([], Name: new_cases, dtype: float64)
49661 Series([], Name: new_cases, dtype: float64)
49662 Series([], Name: new_cases, dtype: float64)
49663 Series([], Name: new_cases, dtype: float64)
49664 48956    1.0
Name: new_cases, dtype: float64
49665 48957    0.0
Name: new_cases, dtype: float64
49667 49674    0.0
Name: new_cases, dtype: float64
49668 49675    1.0
Name: new_cases, dtype: float64
49669 49676    0.0
Name: new_cases, dtype: float64
49670 49677    0.0
Name: new_cases, dtype: float64
49671 49678    0.0
Name: new_cases, dtype: float64
49672 49679    0.0
Name: new_cases, dtype: float64
49673 49680    0.0
Name: new_cases, dtype: float64
49674 49681    0.0
Name: new_cases, dtype: float64
49675 49682    5.0
Name: new_cases, dtype: float64
49676 49683    0.0
Name: new_cases, dtype: float64
49677 49684    0.0
Name: new_cases, dtype: float64
49678 49685    0.0
Name: new_cases, dtype: float64
49679 49686    0.0
Name: new_cases, dtype: float64
49680 49687    0.0
Name: new_cases, dtype: float64
49681 49688    0.0
Name: new_cases, dtype: float64
49682 49689    1.0
Name: new_cases, dtype: float64
49683 49690    0.0
Name: new_cases, dtype: float64
49684 49691    0.0
Name: new_cases, dtype: float64
49685 49692    0.0
Name: new_cases, dtype: float64
49686 49693    0.0
Name: new_cases, dtype: float64
49687 49694    0.0
Name: new_cases, dtype: float64
49688 49695    0.0
Name: new_cases, dtype: float64
49689 49696    0.0
Name: new_cases, dtype: float64
49690 49697    0.0
Name: new_cases, dtype: float64
49691 49698    0.0
Name: new_cases, dtype: float64
49692 49699    2.0
Name: new_cases, dtype: float64
49693 49700    4.0
Name: new_cases, dtype: float64
49694 49701    20.0
Name: new_cases, dtype: float64
49695 49702    19.0
Name: new_cases, dtype: float64
49696 49703    43.0
Name: new_cases, dtype: float64
49697 49704    30.0
Name: new_cases, dtype: float64
49698 49705    61.0
Name: new_cases, dtype: float64
49699 49706    21.0
Name: new_cases, dtype: float64
49700 49707    76.0
Name: new_cases, dtype: float64
49701 49708    138.0
Name: new_cases, dtype: float64
49702 49709    190.0
Name: new_cases, dtype: float64
49703 49710    332.0
Name: new_cases, dtype: float64
49704 49711    177.0
Name: new_cases, dtype: float64
49705 49712    286.0
Name: new_cases, dtype: float64
49706 49713    372.0
Name: new_cases, dtype: float64
49707 49714    510.0
Name: new_cases, dtype: float64
49708 49715    0.0
Name: new_cases, dtype: float64
49709 49716    1385.0
Name: new_cases, dtype: float64
49710 49717    815.0
Name: new_cases, dtype: float64
49711 49718    36.0
Name: new_cases, dtype: float64
49712 49719    2151.0
Name: new_cases, dtype: float64
49713 49720    1032.0
Name: new_cases, dtype: float64
49714 49721    1409.0
Name: new_cases, dtype: float64
49715 49722    1841.0
Name: new_cases, dtype: float64
49716 49723    1783.0
Name: new_cases, dtype: float64
49717 49724    1699.0
Name: new_cases, dtype: float64
49718 49725    2295.0
Name: new_cases, dtype: float64
49719 49726    3355.0
Name: new_cases, dtype: float64
49720 49727    2243.0
Name: new_cases, dtype: float64
49721 49728    2955.0
Name: new_cases, dtype: float64
49722 49729    3916.0
Name: new_cases, dtype: float64
49723 49730    3792.0
Name: new_cases, dtype: float64
49724 49731    4648.0
Name: new_cases, dtype: float64
49725 49732    2603.0
Name: new_cases, dtype: float64
49726 49733    4343.0
Name: new_cases, dtype: float64
49727 49734    7635.0
Name: new_cases, dtype: float64
49728 49735    4843.0
Name: new_cases, dtype: float64
49729 49736    2100.0
Name: new_cases, dtype: float64
49730 49737    5223.0
Name: new_cases, dtype: float64
49731 49738   -17076.0
Name: new_cases, dtype: float64
49732 49740    2658.0
Name: new_cases, dtype: float64
49733 49741   -3494.0
Name: new_cases, dtype: float64
49734 49742    3851.0
Name: new_cases, dtype: float64
49735 49743    3784.0
Name: new_cases, dtype: float64
49736 49744    1566.0
Name: new_cases, dtype: float64
49737 49745    1445.0
Name: new_cases, dtype: float64
49738 49746    50745.0
Name: new_cases, dtype: float64
49740 49747    3139.0
Name: new_cases, dtype: float64

49741 49748    17448.0
Name: new_cases, dtype: float64
49742 49749    3207.0
Name: new_cases, dtype: float64
49743 49750    12578.0
Name: new_cases, dtype: float64
49744 49751    1891.0
Name: new_cases, dtype: float64
49745 49752    3804.0
Name: new_cases, dtype: float64
49746 49753    1094.0
Name: new_cases, dtype: float64
49747 49754    2446.0
Name: new_cases, dtype: float64
49748 49755    2666.0
Name: new_cases, dtype: float64
49749 49756    1798.0
Name: new_cases, dtype: float64
49750 49757   -1709.0
Name: new_cases, dtype: float64
49751 49758    2811.0
Name: new_cases, dtype: float64
49752 49759    1678.0
Name: new_cases, dtype: float64
49753 49760    633.0
Name: new_cases, dtype: float64
49754 49761    3686.0
Name: new_cases, dtype: float64
49755 49762    3131.0
Name: new_cases, dtype: float64
49756 49763   -1455.0
Name: new_cases, dtype: float64
49757 49764    1218.0
Name: new_cases, dtype: float64
49758 49765    526.0
Name: new_cases, dtype: float64
49759 49766    792.0
Name: new_cases, dtype: float64
49760 49767    361.0
Name: new_cases, dtype: float64
49761 49768    562.0
Name: new_cases, dtype: float64
49762 49769    1115.0
Name: new_cases, dtype: float64
49763 49770    4136.0
Name: new_cases, dtype: float64
49764 49771    741.0
Name: new_cases, dtype: float64
49765 49772    531.0
Name: new_cases, dtype: float64
49766 49773    528.0
Name: new_cases, dtype: float64
49767 49774    249.0
Name: new_cases, dtype: float64
49768 49775    315.0
Name: new_cases, dtype: float64
49769 49776    753.0
Name: new_cases, dtype: float64
49770 49777    521.0
Name: new_cases, dtype: float64
49771 49778    642.0
Name: new_cases, dtype: float64
49772 49779    513.0
Name: new_cases, dtype: float64
49773 49780    415.0
Name: new_cases, dtype: float64
49774 49781    140.0
Name: new_cases, dtype: float64
49775 49782    444.0
Name: new_cases, dtype: float64
49776 49783    501.0
Name: new_cases, dtype: float64
49777 49784    481.0
Name: new_cases, dtype: float64
49778 49785    267.0
Name: new_cases, dtype: float64
49779 49786    756.0
Name: new_cases, dtype: float64
49780 49787    546.0
Name: new_cases, dtype: float64
49781 49788   -439.0
Name: new_cases, dtype: float64
49782 49789    325.0
Name: new_cases, dtype: float64
49783 49790    255.0
Name: new_cases, dtype: float64
49784 49791    173.0
Name: new_cases, dtype: float64
49785 49792    3342.0
Name: new_cases, dtype: float64
49786 49793    594.0
Name: new_cases, dtype: float64
49787 49794    1794.0
Name: new_cases, dtype: float64
49788 49795    232.0
Name: new_cases, dtype: float64
49789 49796    406.0
Name: new_cases, dtype: float64
49790 49797   -647.0
Name: new_cases, dtype: float64
49791 49798   -3226.0
Name: new_cases, dtype: float64
49792 49799    4360.0
Name: new_cases, dtype: float64
49793 49800    581.0
Name: new_cases, dtype: float64
49794 49801    572.0
Name: new_cases, dtype: float64
49795 49802    341.0
Name: new_cases, dtype: float64
49796 49803    274.0
Name: new_cases, dtype: float64
49797 49804    552.0
Name: new_cases, dtype: float64
49798 49805    625.0
Name: new_cases, dtype: float64
49799 49806    364.0
Name: new_cases, dtype: float64
49800 49807    801.0
Name: new_cases, dtype: float64
49801 49808    497.0
Name: new_cases, dtype: float64
49802 49809    390.0
Name: new_cases, dtype: float64
49803 49810    136.0
Name: new_cases, dtype: float64
49804 49811    663.0
Name: new_cases, dtype: float64
49805 49812    489.0
Name: new_cases, dtype: float64
49806 49813    586.0
Name: new_cases, dtype: float64
49807 49814    787.0
Name: new_cases, dtype: float64
49808 49815    619.0
Name: new_cases, dtype: float64
49809 49816    343.0
Name: new_cases, dtype: float64
49810 49817    142.0
Name: new_cases, dtype: float64
49811 49818    698.0
Name: new_cases, dtype: float64
49812 49819    268.0
Name: new_cases, dtype: float64
49813 49820    255.0
Name: new_cases, dtype: float64
49814 49821    1263.0
Name: new_cases, dtype: float64
49815 49822    448.0
Name: new_cases, dtype: float64
49816 49823   -409.0
Name: new_cases, dtype: float64
49817 49824    645.0
Name: new_cases, dtype: float64
49818 49825    442.0
Name: new_cases, dtype: float64
49819 49826    990.0
Name: new_cases, dtype: float64
49820 49827    539.0
Name: new_cases, dtype: float64
49821 49828    539.0
Name: new_cases, dtype: float64
49822 49829    358.0
Name: new_cases, dtype: float64
49823 49830    12.0
Name: new_cases, dtype: float64
49824 49831    1018.0
Name: new_cases, dtype: float64
49825 49832    454.0
Name: new_cases, dtype: float64
49826 49833    822.0
Name: new_cases, dtype: float64
49827 49834    444.0
Name: new_cases, dtype: float64
49828 49835    714.0
Name: new_cases, dtype: float64
49829 49836    251.0
Name: new_cases, dtype: float64
49830 49837    16.0
Name: new_cases, dtype: float64
49831 49838    1423.0
Name: new_cases, dtype: float64
49832 49839    62.0
Name: new_cases, dtype: float64
49833 49840    726.0
Name: new_cases, dtype: float64
49834 49841    569.0
Name: new_cases, dtype: float64
49835 49842    824.0
Name: new_cases, dtype: float64
49836 49843    165.0
Name: new_cases, dtype: float64
49837 49844    4.0
Name: new_cases, dtype: float64
49838 49845    1911.0
Name: new_cases, dtype: float64
49839 49846    595.0
Name: new_cases, dtype: float64
49840 49847    921.0
Name: new_cases, dtype: float64
49841 49848    1236.0
Name: new_cases, dtype: float64
49842 49849    1091.0
Name: new_cases, dtype: float64
49843 49850    84.0
Name: new_cases, dtype: float64
49844 49851    4.0
Name: new_cases, dtype: float64
49845 49852    2488.0
Name: new_cases, dtype: float64
49846 49853    564.0
Name: new_cases, dtype: float64
49847 49854    1470.0
Name: new_cases, dtype: float64
49848 49855    1394.0
Name: new_cases, dtype: float64
49849 49856    1303.0
Name: new_cases, dtype: float64
49850 49857    62.0
Name: new_cases, dtype: float64
49851 49858    3.0
Name: new_cases, dtype: float64
49852 49859    3361.0
Name: new_cases, dtype: float64
49853 49860    969.0
Name: new_cases, dtype: float64
49854 49861    1708.0
Name: new_cases, dtype: float64
49855 49862    1601.0
Name: new_cases, dtype: float64
49856 49863    2382.0
Name: new_cases, dtype: float64
49857 49864    69.0
Name: new_cases, dtype: float64
49858 49865    6.0
Name: new_cases, dtype: float64
49859 49866    4717.0
Name: new_cases, dtype: float64
49860 49867    1408.0
Name: new_cases, dtype: float64
49861 49868    2577.0
Name: new_cases, dtype: float64
49862 49869    2670.0
Name: new_cases, dtype: float64
49863 49870    2887.0
Name: new_cases, dtype: float64
49864 49871    3210.0
Name: new_cases, dtype: float64
49865 49872    3020.0
Name: new_cases, dtype: float64
49866 49873    590.0
Name: new_cases, dtype: float64
49867 49874    2118.0
Name: new_cases, dtype: float64
49868 49875    3787.0
Name: new_cases, dtype: float64
49869 49876    4800.0
Name: new_cases, dtype: float64
49870 49877    4954.0
Name: new_cases, dtype: float64
49871 49878    3474.0
Name: new_cases, dtype: float64
49872 49879    4735.0
Name: new_cases, dtype: float64
49873 49880    1976.0
Name: new_cases, dtype: float64
49874 49881    3432.0
Name: new_cases, dtype: float64
49875 49882    244.0
Name: new_cases, dtype: float64
49876 49883    11226.0
Name: new_cases, dtype: float64
49877 49884    7558.0
Name: new_cases, dtype: float64
49878 49885    5460.0
Name: new_cases, dtype: float64
49879 49886    5382.0
Name: new_cases, dtype: float64
49880 49887    3022.0
Name: new_cases, dtype: float64
49881 49888    5104.0
Name: new_cases, dtype: float64
49882 49889    7038.0
Name: new_cases, dtype: float64
49883 49890    7119.0
Name: new_cases, dtype: float64
49884 49891    8788.0
Name: new_cases, dtype: float64
49885 49892    8594.0
Name: new_cases, dtype: float64
49886 49893    7015.0
Name: new_cases, dtype: float64
49887 49894    4184.0
Name: new_cases, dtype: float64
49888 49895    6738.0
Name: new_cases, dtype: float64
49889 49896    8577.0
Name: new_cases, dtype: float64
49890 49897    9699.0
Name: new_cases, dtype: float64
49891 49898    9433.0
Name: new_cases, dtype: float64
49892 49899    11336.0
Name: new_cases, dtype: float64
49893 49900    6345.0
Name: new_cases, dtype: float64
49894 49901    6174.0
Name: new_cases, dtype: float64
49895 49902    7826.0
Name: new_cases, dtype: float64
49896 49903    10267.0
Name: new_cases, dtype: float64
49897 49904    10239.0
Name: new_cases, dtype: float64
49898 49905    13221.0
Name: new_cases, dtype: float64
49899 49906    13400.0
Name: new_cases, dtype: float64
49900 49907    10536.0
Name: new_cases, dtype: float64
49901 49908    5539.0
Name: new_cases, dtype: float64
49902 49909    9961.0
Name: new_cases, dtype: float64

49903 49910    13156.0
Name: new_cases, dtype: float64
49904 49911    15905.0
Name: new_cases, dtype: float64
49905 49912    15994.0
Name: new_cases, dtype: float64
49906 49913    14219.0
Name: new_cases, dtype: float64
49907 49914    10635.0
Name: new_cases, dtype: float64
49908 49915    4299.0
Name: new_cases, dtype: float64
49909 49916    7856.0
Name: new_cases, dtype: float64
49910 49917    14242.0
Name: new_cases, dtype: float64
49911 49918    13025.0
Name: new_cases, dtype: float64
49912 49919    12324.0
Name: new_cases, dtype: float64
49913 49920    16514.0
Name: new_cases, dtype: float64
49914 49921    12504.0
Name: new_cases, dtype: float64
49915 49922    5375.0
Name: new_cases, dtype: float64
49916 49923    11310.0
Name: new_cases, dtype: float64
49917 49924    18823.0
Name: new_cases, dtype: float64
49918 49925    17340.0
Name: new_cases, dtype: float64
49919 49926    20697.0
Name: new_cases, dtype: float64
49920 49927    26677.0
Name: new_cases, dtype: float64
49921 49928    15994.0
Name: new_cases, dtype: float64
49922 49929    8715.0
Name: new_cases, dtype: float64
49923 49930    13626.0
Name: new_cases, dtype: float64
49924 49931    22643.0
Name: new_cases, dtype: float64
49925 49932    29757.0
Name: new_cases, dtype: float64
49926 49933    25410.0
Name: new_cases, dtype: float64
49927 49934    32139.0
Name: new_cases, dtype: float64
49928 49935    29837.0
Name: new_cases, dtype: float64
49929 49936    13538.0
Name: new_cases, dtype: float64
49930 49937    20376.0
Name: new_cases, dtype: float64
49931 49938    26797.0
Name: new_cases, dtype: float64
49932 49939    40813.0
Name: new_cases, dtype: float64
49933 49940    42213.0
Name: new_cases, dtype: float64
49934 49941    45265.0
Name: new_cases, dtype: float64
49935 49942    6554.0
Name: new_cases, dtype: float64
49936 49943    72438.0
Name: new_cases, dtype: float64
49937 49944    34458.0
Name: new_cases, dtype: float64
49938 49945    36719.0
Name: new_cases, dtype: float64
49939 49946    46636.0
Name: new_cases, dtype: float64
49940 49947    49473.0
Name: new_cases, dtype: float64
49941 49948    35101.0
Name: new_cases, dtype: float64
49942 49949    46179.0
Name: new_cases, dtype: float64
49943 49950    104707.0
Name: new_cases, dtype: float64
49944 49951    72298.0
Name: new_cases, dtype: float64
49945 49953    57352.0
Name: new_cases, dtype: float64
49946 49954    60711.0
Name: new_cases, dtype: float64
49947 49955    86655.0
Name: new_cases, dtype: float64
49948 49956    38562.0
Name: new_cases, dtype: float64
49949 49957    20739.0
Name: new_cases, dtype: float64
49950 49958    22322.0
Name: new_cases, dtype: float64
49951 49959    36061.0
Name: new_cases, dtype: float64
49953 49960    32388.0
Name: new_cases, dtype: float64
49954 49961    23914.0
Name: new_cases, dtype: float64
49955 49962    31957.0
Name: new_cases, dtype: float64
49956 49963    27192.0
Name: new_cases, dtype: float64
49957 49964    9635.0
Name: new_cases, dtype: float64
49958 49965    45361.0
Name: new_cases, dtype: float64
49959 49966    28619.0
Name: new_cases, dtype: float64
49960 49967    20560.0
Name: new_cases, dtype: float64
49961 49968    23102.0
Name: new_cases, dtype: float64
49962 49969    17668.0
Name: new_cases, dtype: float64
49963 49970    13130.0
Name: new_cases, dtype: float64
49964 49971    4754.0
Name: new_cases, dtype: float64
49965 49972    9690.0
Name: new_cases, dtype: float64
49966 49973    16488.0
Name: new_cases, dtype: float64
49967 49974    12901.0
Name: new_cases, dtype: float64
49968 49975    12561.0
Name: new_cases, dtype: float64
49969 49976    12477.0
Name: new_cases, dtype: float64
49970 49977    9763.0
Name: new_cases, dtype: float64
49971 49978    4030.0
Name: new_cases, dtype: float64
49972 49979    8256.0
Name: new_cases, dtype: float64
49973 49980    14071.0
Name: new_cases, dtype: float64
49974 49981    12605.0
Name: new_cases, dtype: float64
49975 49982    11300.0
Name: new_cases, dtype: float64
49976 49983    12882.0
Name: new_cases, dtype: float64
49977 49984    10949.0
Name: new_cases, dtype: float64
49978 49985    3411.0
Name: new_cases, dtype: float64
49979 49986    13819.0
Name: new_cases, dtype: float64
49980 49987    14595.0
Name: new_cases, dtype: float64
49981 49988    13750.0
Name: new_cases, dtype: float64
49982 49989    13406.0
Name: new_cases, dtype: float64
49983 49990    13947.0
Name: new_cases, dtype: float64
49984 49991    11533.0
Name: new_cases, dtype: float64
49985 49992    3063.0
Name: new_cases, dtype: float64
49986 49993    11601.0
Name: new_cases, dtype: float64
49987 49994    17615.0
Name: new_cases, dtype: float64
49988 49995    18254.0
Name: new_cases, dtype: float64
49989 49996    15811.0
Name: new_cases, dtype: float64
49990 49997    17428.0
Name: new_cases, dtype: float64
49991 49998    12858.0
Name: new_cases, dtype: float64
49992 49999    5797.0
Name: new_cases, dtype: float64
49993 50000    11795.0
Name: new_cases, dtype: float64
49994 50001    14929.0
Name: new_cases, dtype: float64
49995 50002    21634.0
Name: new_cases, dtype: float64
49996 50003    20262.0
Name: new_cases, dtype: float64
49997 50004    3093.0
Name: new_cases, dtype: float64
49998 50005    8867.0
Name: new_cases, dtype: float64
49999 50006    2960.0
Name: new_cases, dtype: float64
50000 50007    11395.0
Name: new_cases, dtype: float64
50001 50008    26457.0
Name: new_cases, dtype: float64
50002 50009    19927.0
Name: new_cases, dtype: float64
50003 50010    19358.0
Name: new_cases, dtype: float64
50004 50011    3466.0
Name: new_cases, dtype: float64
50005 50012    12489.0
Name: new_cases, dtype: float64
50006 50013    4022.0
Name: new_cases, dtype: float64
50007 50014    20733.0
Name: new_cases, dtype: float64
50008 50015    25143.0
Name: new_cases, dtype: float64
50009 50016    21703.0
Name: new_cases, dtype: float64
50010 50017    19814.0
Name: new_cases, dtype: float64
50011 50018    20177.0
Name: new_cases, dtype: float64
50012 50019    15944.0
Name: new_cases, dtype: float64
50013 50020    3717.0
Name: new_cases, dtype: float64
50014 50021    19694.0
Name: new_cases, dtype: float64
50015 50022    23852.0
Name: new_cases, dtype: float64
50016 50023    21228.0
Name: new_cases, dtype: float64
50017 50024    21271.0
Name: new_cases, dtype: float64
50018 50025    21406.0
Name: new_cases, dtype: float64
50019 50026    16642.0
Name: new_cases, dtype: float64
50020 50027    3736.0
Name: new_cases, dtype: float64
50021 50028    24023.0
Name: new_cases, dtype: float64
50022 50029    26758.0
Name: new_cases, dtype: float64
50023 50030    22587.0
Name: new_cases, dtype: float64
50024 50031    23292.0
Name: new_cases, dtype: float64
50025 50032    24093.0
Name: new_cases, dtype: float64
50026 50033    18436.0
Name: new_cases, dtype: float64
50027 50034    4240.0
Name: new_cases, dtype: float64
50028 50035    22086.0
Name: new_cases, dtype: float64
50029 50036    26916.0
Name: new_cases, dtype: float64
50030 50037    23770.0
Name: new_cases, dtype: float64
50031 50038    23205.0
Name: new_cases, dtype: float64
50032 50039    24045.0
Name: new_cases, dtype: float64
50033 50040    19336.0
Name: new_cases, dtype: float64
50034 50041    4347.0
Name: new_cases, dtype: float64
50035 50042    23337.0
Name: new_cases, dtype: float64
50036 50043    26362.0
Name: new_cases, dtype: float64
50037 50044    0.0
Name: new_cases, dtype: float64
50038 50045    45587.0
Name: new_cases, dtype: float64
50039 50046    20586.0
Name: new_cases, dtype: float64
50040 50047    19715.0
Name: new_cases, dtype: float64
50041 50048    4317.0
Name: new_cases, dtype: float64
50042 50049    19004.0
Name: new_cases, dtype: float64
50043 50050    25387.0
Name: new_cases, dtype: float64
50044 50051    21063.0
Name: new_cases, dtype: float64
50045 50052    20701.0
Name: new_cases, dtype: float64
50046 50053    21231.0
Name: new_cases, dtype: float64
50047 50054    16675.0
Name: new_cases, dtype: float64
50048 50055    4376.0
Name: new_cases, dtype: float64
50049 50056    19590.0
Name: new_cases, dtype: float64
50050 50057    25018.0
Name: new_cases, dtype: float64
50051 50058    22501.0
Name: new_cases, dtype: float64
50052 50059    24116.0
Name: new_cases, dtype: float64
50053 50060    22371.0
Name: new_cases, dtype: float64
50054 50061    22046.0
Name: new_cases, dtype: float64

50055 50062    4646.0
Name: new_cases, dtype: float64
50056 50063    20185.0
Name: new_cases, dtype: float64
50057 50064    31519.0
Name: new_cases, dtype: float64
50058 50065    25403.0
Name: new_cases, dtype: float64
50059 50066    25207.0
Name: new_cases, dtype: float64
50060 50067    24110.0
Name: new_cases, dtype: float64
50061 50068    19952.0
Name: new_cases, dtype: float64
50062 50069    4703.0
Name: new_cases, dtype: float64
50063 50070    22857.0
Name: new_cases, dtype: float64
50064 50071    26788.0
Name: new_cases, dtype: float64
50065 50072    25279.0
Name: new_cases, dtype: float64
50066 50073    23507.0
Name: new_cases, dtype: float64
50067 50074    23392.0
Name: new_cases, dtype: float64
50068 50075    21825.0
Name: new_cases, dtype: float64
50069 50076    5502.0
Name: new_cases, dtype: float64
50070 50077    23127.0
Name: new_cases, dtype: float64
50071 50078    29627.0
Name: new_cases, dtype: float64
50072 50079    28033.0
Name: new_cases, dtype: float64
50073 50080    25038.0
Name: new_cases, dtype: float64
50074 50081    29759.0
Name: new_cases, dtype: float64
50075 50082    26428.0
Name: new_cases, dtype: float64
50076 50083    6444.0
Name: new_cases, dtype: float64
50077 50084    30002.0
Name: new_cases, dtype: float64
50078 50085    38468.0
Name: new_cases, dtype: float64
50079 50086    35031.0
Name: new_cases, dtype: float64
50080 50087    35088.0
Name: new_cases, dtype: float64
50081 50088    35327.0
Name: new_cases, dtype: float64
50082 50089    30653.0
Name: new_cases, dtype: float64
50083 50090    15792.0
Name: new_cases, dtype: float64
50084 50091    14678.0
Name: new_cases, dtype: float64
50085 50092    65373.0
Name: new_cases, dtype: float64
50086 50093    45641.0
Name: new_cases, dtype: float64
50087 50094    41869.0
Name: new_cases, dtype: float64
50088 50095    42619.0
Name: new_cases, dtype: float64
50089 50096    37119.0
Name: new_cases, dtype: float64
50090 50097    9094.0
Name: new_cases, dtype: float64
50091 50098    30702.0
Name: new_cases, dtype: float64
50092 50099    59038.0
Name: new_cases, dtype: float64
50093 50100    50659.0
Name: new_cases, dtype: float64
50094 50101    46677.0
Name: new_cases, dtype: float64
50095 50102    165.0
Name: new_cases, dtype: float64
50096 50103    80629.0
Name: new_cases, dtype: float64
50097 50104    10793.0
Name: new_cases, dtype: float64
50098 50105    8045.0
Name: new_cases, dtype: float64
50099 50106    922.0
Name: new_cases, dtype: float64
50100 50107    97028.0
Name: new_cases, dtype: float64
50101 50108    153.0
Name: new_cases, dtype: float64
50102 50109    1403.0
Name: new_cases, dtype: float64
50103 50110    117900.0
Name: new_cases, dtype: float64
50104 50111    8536.0
Name: new_cases, dtype: float64
50105 50112    39113.0
Name: new_cases, dtype: float64
50106 50113    43505.0
Name: new_cases, dtype: float64
50107 50114    38045.0
Name: new_cases, dtype: float64
50108 50115    36442.0
Name: new_cases, dtype: float64
50109 50116    35861.0
Name: new_cases, dtype: float64
50110 50117    29377.0
Name: new_cases, dtype: float64
50111 50118    6696.0
Name: new_cases, dtype: float64
50112 50119    44063.0
Name: new_cases, dtype: float64
50113 50120    34921.0
Name: new_cases, dtype: float64
50114 50121    33400.0
Name: new_cases, dtype: float64
50115 50122    32340.0
Name: new_cases, dtype: float64
50116 50123    32633.0
Name: new_cases, dtype: float64
50117 50124    24505.0
Name: new_cases, dtype: float64
50118 50125    5952.0
Name: new_cases, dtype: float64
50119 50126    30317.0
Name: new_cases, dtype: float64
50120 50127    31539.0
Name: new_cases, dtype: float64
50121 50128    26538.0
Name: new_cases, dtype: float64
50122 50129    24299.0
Name: new_cases, dtype: float64
50123 50130    25670.0
Name: new_cases, dtype: float64
50124 50131    9921.0
Name: new_cases, dtype: float64
50125 50132    3760.0
Name: new_cases, dtype: float64
50126 50133    24371.0
Name: new_cases, dtype: float64
50127 50134    26000.0
Name: new_cases, dtype: float64
50128 50135    21712.0
Name: new_cases, dtype: float64
50129 50136    19124.0
Name: new_cases, dtype: float64
50130 50137    20779.0
Name: new_cases, dtype: float64
50131 50138    9128.0
Name: new_cases, dtype: float64
50132 50139    3292.0
Name: new_cases, dtype: float64
50133 50140    19791.0
Name: new_cases, dtype: float64
50134 50141    21498.0
Name: new_cases, dtype: float64
50135 50142    19461.0
Name: new_cases, dtype: float64
50136 50143    7025.0
Name: new_cases, dtype: float64
50137 50144    15685.0
Name: new_cases, dtype: float64
50138 50145    14026.0
Name: new_cases, dtype: float64
50139 50146    3350.0
Name: new_cases, dtype: float64
50140 50147    17210.0
Name: new_cases, dtype: float64
50141 50148    19050.0
Name: new_cases, dtype: float64
50142 50150    12800.0
Name: new_cases, dtype: float64
50143 50151    12611.0
Name: new_cases, dtype: float64
50144 50152    9766.0
Name: new_cases, dtype: float64
50145 50153    2229.0
Name: new_cases, dtype: float64
50146 50154    3155.0
Name: new_cases, dtype: float64
50147 50155    12646.0
Name: new_cases, dtype: float64
50148 50156    13933.0
Name: new_cases, dtype: float64
50150 50157    11268.0
Name: new_cases, dtype: float64
50151 50158    11526.0
Name: new_cases, dtype: float64
50152 50159    8662.0
Name: new_cases, dtype: float64
50153 50160    360.0
Name: new_cases, dtype: float64
50154 50161    9848.0
Name: new_cases, dtype: float64
50155 50162    1350.0
Name: new_cases, dtype: float64
50156 50163    15554.0
Name: new_cases, dtype: float64
50157 50164    6953.0
Name: new_cases, dtype: float64
50158 50165    6654.0
Name: new_cases, dtype: float64
50159 50166    5180.0
Name: new_cases, dtype: float64
50160 50167    1164.0
Name: new_cases, dtype: float64
50161 50168    6018.0
Name: new_cases, dtype: float64
50162 50169    5557.0
Name: new_cases, dtype: float64
50163 50170    4475.0
Name: new_cases, dtype: float64
50164 50171    3871.0
Name: new_cases, dtype: float64
50165 50172    3972.0
Name: new_cases, dtype: float64
50166 50173    2973.0
Name: new_cases, dtype: float64
50167 50174    689.0
Name: new_cases, dtype: float64
50168 50175    3235.0
Name: new_cases, dtype: float64
50169 50176    3058.0
Name: new_cases, dtype: float64
50170 50177    2044.0
Name: new_cases, dtype: float64
50171 50178    3181.0
Name: new_cases, dtype: float64
50172 50179    2624.0
Name: new_cases, dtype: float64
50173 50180    1909.0
Name: new_cases, dtype: float64
50174 50181    487.0
Name: new_cases, dtype: float64
50175 50182    2204.0
Name: new_cases, dtype: float64
50176 50183    2320.0
Name: new_cases, dtype: float64
50177 50184    2007.0
Name: new_cases, dtype: float64
50178 50185    1986.0
Name: new_cases, dtype: float64
50179 50186    2128.0
Name: new_cases, dtype: float64
50180 50187    1634.0
Name: new_cases, dtype: float64
50181 50188    509.0
Name: new_cases, dtype: float64
50182 50189    3395.0
Name: new_cases, dtype: float64
50183 50190    1376.0
Name: new_cases, dtype: float64
50184 50191    2664.0
Name: new_cases, dtype: float64
50185 50192    2683.0
Name: new_cases, dtype: float64
50186 50193    3006.0
Name: new_cases, dtype: float64
50187 50194    2605.0
Name: new_cases, dtype: float64
50188 50195    796.0
Name: new_cases, dtype: float64
50189 50196    3585.0
Name: new_cases, dtype: float64
50190 50197    4081.0
Name: new_cases, dtype: float64
50191 50198    4442.0
Name: new_cases, dtype: float64
50192 50199    4580.0
Name: new_cases, dtype: float64
50193 50200    4696.0
Name: new_cases, dtype: float64
50194 50201    4314.0
Name: new_cases, dtype: float64
50195 50202    1260.0
Name: new_cases, dtype: float64
50196 50203    6950.0
Name: new_cases, dtype: float64
50197 50204    1450.0
Name: new_cases, dtype: float64
50198 50205    11042.0
Name: new_cases, dtype: float64
50199 50206    10908.0
Name: new_cases, dtype: float64
50200 50207    11005.0
Name: new_cases, dtype: float64
50201 50208    12532.0
Name: new_cases, dtype: float64
50202 50209    4151.0
Name: new_cases, dtype: float64
50203 50210    18181.0
Name: new_cases, dtype: float64
50204 50211    21539.0
Name: new_cases, dtype: float64
50205 50212    22061.0
Name: new_cases, dtype: float64
50206 50213    19409.0
Name: new_cases, dtype: float64
50207 50214    25688.0
Name: new_cases, dtype: float64
50208 50215    15242.0
Name: new_cases, dtype: float64
50209 50216    5307.0
Name: new_cases, dtype: float64
50210 50217    27024.0
Name: new_cases, dtype: float64
50211 50218    27781.0
Name: new_cases, dtype: float64
50212 50219    25190.0
Name: new_cases, dtype: float64
50213 50220    24309.0
Name: new_cases, dtype: float64
50214 50221    23689.0
Name: new_cases, dtype: float64
50215 50222    19714.0
Name: new_cases, dtype: float64
50216 50223    8160.0
Name: new_cases, dtype: float64

50217 50224    23919.0
Name: new_cases, dtype: float64
50218 50225    28784.0
Name: new_cases, dtype: float64
50219 50226    26460.0
Name: new_cases, dtype: float64
50220 50227    25077.0
Name: new_cases, dtype: float64
50221 50228    25857.0
Name: new_cases, dtype: float64
50222 50229    20460.0
Name: new_cases, dtype: float64
50223 50230    5775.0
Name: new_cases, dtype: float64
50224 50231    27815.0
Name: new_cases, dtype: float64
50225 50232    31852.0
Name: new_cases, dtype: float64
50226 50233    28554.0
Name: new_cases, dtype: float64
50227 50234    26453.0
Name: new_cases, dtype: float64
50228 50235    24427.0
Name: new_cases, dtype: float64
50229 50236    21269.0
Name: new_cases, dtype: float64
50230 50237    11186.0
Name: new_cases, dtype: float64
50231 50238    22959.0
Name: new_cases, dtype: float64
50232 50239    28405.0
Name: new_cases, dtype: float64
50233 50240    23973.0
Name: new_cases, dtype: float64
50234 50241    22319.0
Name: new_cases, dtype: float64
50235 50242    22712.0
Name: new_cases, dtype: float64
50236 50243    17300.0
Name: new_cases, dtype: float64
50237 50244    5166.0
Name: new_cases, dtype: float64
50238 50245    24853.0
Name: new_cases, dtype: float64
50239 50246    23706.0
Name: new_cases, dtype: float64
50240 50247    19683.0
Name: new_cases, dtype: float64
50241 50248    457.0
Name: new_cases, dtype: float64
50242 50249    35630.0
Name: new_cases, dtype: float64
50243 50250    13630.0
Name: new_cases, dtype: float64
50244 50251    7688.0
Name: new_cases, dtype: float64
50245 50252    24.0
Name: new_cases, dtype: float64
50246 50253    33129.0
Name: new_cases, dtype: float64
50247 50254    14153.0
Name: new_cases, dtype: float64
50248 50255    15224.0
Name: new_cases, dtype: float64
50249 50256    13336.0
Name: new_cases, dtype: float64
50250 50257    10410.0
Name: new_cases, dtype: float64
50251 50258    3050.0
Name: new_cases, dtype: float64
50252 50259    14534.0
Name: new_cases, dtype: float64
50253 50260    5922.0
Name: new_cases, dtype: float64
50254 50261    18070.0
Name: new_cases, dtype: float64
50255 50262    9966.0
Name: new_cases, dtype: float64
50256 50263    9601.0
Name: new_cases, dtype: float64
50257 50264    7679.0
Name: new_cases, dtype: float64
50258 50265    2062.0
Name: new_cases, dtype: float64
50259 50266    14065.0
Name: new_cases, dtype: float64
50260 50267    383.0
Name: new_cases, dtype: float64
50261 50268    13272.0
Name: new_cases, dtype: float64
50262 50269    7373.0
Name: new_cases, dtype: float64
50263 50270    7414.0
Name: new_cases, dtype: float64
50264 50271    5814.0
Name: new_cases, dtype: float64
50265 50272    1475.0
Name: new_cases, dtype: float64
50266 50273    7983.0
Name: new_cases, dtype: float64
50267 50274    6794.0
Name: new_cases, dtype: float64
50268 50275    6229.0
Name: new_cases, dtype: float64
50269 50276    6675.0
Name: new_cases, dtype: float64
50270 50277    5216.0
Name: new_cases, dtype: float64
50271 50278    4706.0
Name: new_cases, dtype: float64
50272 50279    1309.0
Name: new_cases, dtype: float64
50273 50280    6765.0
Name: new_cases, dtype: float64
50274 50281    5900.0
Name: new_cases, dtype: float64
50275 50282    5204.0
Name: new_cases, dtype: float64
50276 50283    4935.0
Name: new_cases, dtype: float64
50277 50284    4948.0
Name: new_cases, dtype: float64
50278 50285    3744.0
Name: new_cases, dtype: float64
50279 50286    1138.0
Name: new_cases, dtype: float64
50280 50287    5582.0
Name: new_cases, dtype: float64
50281 50288    4570.0
Name: new_cases, dtype: float64
50282 50289    5006.0
Name: new_cases, dtype: float64
50283 50290    4470.0
Name: new_cases, dtype: float64
50284 50291    4734.0
Name: new_cases, dtype: float64
50285 50292    3991.0
Name: new_cases, dtype: float64
50286 50293    1120.0
Name: new_cases, dtype: float64
50287 50294    5880.0
Name: new_cases, dtype: float64
50288 50295    1359.0
Name: new_cases, dtype: float64
50289 50296    9474.0
Name: new_cases, dtype: float64
50290 50297    6099.0
Name: new_cases, dtype: float64
50291 50298    4899.0
Name: new_cases, dtype: float64
50292 50299    3778.0
Name: new_cases, dtype: float64
50293 50300    1057.0
Name: new_cases, dtype: float64
50294 50301    5945.0
Name: new_cases, dtype: float64
50295 50302    6036.0
Name: new_cases, dtype: float64
50296 50303    6127.0
Name: new_cases, dtype: float64
50297 50304    6366.0
Name: new_cases, dtype: float64
50298 50305    6291.0
Name: new_cases, dtype: float64
50299 50306    5005.0
Name: new_cases, dtype: float64
50300 50307    1295.0
Name: new_cases, dtype: float64
50301 50308    6635.0
Name: new_cases, dtype: float64
50302 50309    6999.0
Name: new_cases, dtype: float64
50303 50310    5990.0
Name: new_cases, dtype: float64
50304 50311    6433.0
Name: new_cases, dtype: float64
50305 50312    7360.0
Name: new_cases, dtype: float64
50306 50313    6329.0
Name: new_cases, dtype: float64
50307 50314    1866.0
Name: new_cases, dtype: float64
50308 50315    2039.0
Name: new_cases, dtype: float64
50309 50316    10230.0
Name: new_cases, dtype: float64
50310 50317    9344.0
Name: new_cases, dtype: float64
50311 50318    8998.0
Name: new_cases, dtype: float64
50312 50319    9605.0
Name: new_cases, dtype: float64
50313 50320    8547.0
Name: new_cases, dtype: float64
50314 50321    2197.0
Name: new_cases, dtype: float64
50315 50322    12511.0
Name: new_cases, dtype: float64
50316 50323    11883.0
Name: new_cases, dtype: float64
50317 50324    12603.0
Name: new_cases, dtype: float64
50318 50325    3860.0
Name: new_cases, dtype: float64
50319 50326    14646.0
Name: new_cases, dtype: float64
50320 50327    12496.0
Name: new_cases, dtype: float64
50321 50328    3259.0
Name: new_cases, dtype: float64
50322 50329    19778.0
Name: new_cases, dtype: float64
50323 50330    20294.0
Name: new_cases, dtype: float64
50324 50331    20366.0
Name: new_cases, dtype: float64
50325 50332    21220.0
Name: new_cases, dtype: float64
50326 50333    22678.0
Name: new_cases, dtype: float64
50327 50334    19749.0
Name: new_cases, dtype: float64
50328 50335    5291.0
Name: new_cases, dtype: float64
50329 50336    30454.0
Name: new_cases, dtype: float64
50330 50337    32591.0
Name: new_cases, dtype: float64
50331 50338    33464.0
Name: new_cases, dtype: float64
50332 50339    34436.0
Name: new_cases, dtype: float64
50333 50340    37057.0
Name: new_cases, dtype: float64
50334 50341    31581.0
Name: new_cases, dtype: float64
50335 50342    8507.0
Name: new_cases, dtype: float64
50336 50343    47201.0
Name: new_cases, dtype: float64
50337 50344    49610.0
Name: new_cases, dtype: float64
50338 50345    48416.0
Name: new_cases, dtype: float64
50339 50346    49858.0
Name: new_cases, dtype: float64
50340 50347    51464.0
Name: new_cases, dtype: float64
50341 50348    42153.0
Name: new_cases, dtype: float64
50342 50349    11578.0
Name: new_cases, dtype: float64
50343 50350    59019.0
Name: new_cases, dtype: float64
50344 50351    61340.0
Name: new_cases, dtype: float64
50345 50352    56854.0
Name: new_cases, dtype: float64
50346 50353    55140.0
Name: new_cases, dtype: float64
50347 50354    53919.0
Name: new_cases, dtype: float64
50348 50355    43848.0
Name: new_cases, dtype: float64
50349 50356    12064.0
Name: new_cases, dtype: float64
50350 50357    63405.0
Name: new_cases, dtype: float64
50351 50358    65713.0
Name: new_cases, dtype: float64
50352 50359    60866.0
Name: new_cases, dtype: float64
50353 50360    58128.0
Name: new_cases, dtype: float64
50354 50361    58536.0
Name: new_cases, dtype: float64
50355 50362    48473.0
Name: new_cases, dtype: float64
50356 50363    15075.0
Name: new_cases, dtype: float64
50357 50364    72857.0
Name: new_cases, dtype: float64
50358 50365    84272.0
Name: new_cases, dtype: float64
50359 50366    91608.0
Name: new_cases, dtype: float64
50360 50367    94124.0
Name: new_cases, dtype: float64
50361 50368    104611.0
Name: new_cases, dtype: float64
50362 50369    27697.0
Name: new_cases, dtype: float64
50363 50370    30459.0
Name: new_cases, dtype: float64
50364 50371    179808.0
Name: new_cases, dtype: float64
50365 50372    208099.0
Name: new_cases, dtype: float64
50366 50373    206544.0
Name: new_cases, dtype: float64
50367 50374    232200.0
Name: new_cases, dtype: float64
50368 50375    219126.0
Name: new_cases, dtype: float64
50369 50376    58432.0
Name: new_cases, dtype: float64

50370 50377    67461.0
Name: new_cases, dtype: float64
50371 50378    271746.0
Name: new_cases, dtype: float64
50372 50379    332252.0
Name: new_cases, dtype: float64
50373 50380    262787.0
Name: new_cases, dtype: float64
50374 50381    333285.0
Name: new_cases, dtype: float64
50375 50382    298598.0
Name: new_cases, dtype: float64
50376 49700    4.0
Name: new_cases, dtype: float64
50377 49701    20.0
Name: new_cases, dtype: float64
50378 49702    19.0
Name: new_cases, dtype: float64
50379 49703    43.0
Name: new_cases, dtype: float64
50380 49704    30.0
Name: new_cases, dtype: float64
50381 49705    61.0
Name: new_cases, dtype: float64
50382 49706    21.0
Name: new_cases, dtype: float64
52379 52386    0.0
Name: new_cases, dtype: float64
52380 52387    1.0
Name: new_cases, dtype: float64
52381 52388    0.0
Name: new_cases, dtype: float64
52382 52389    0.0
Name: new_cases, dtype: float64
52383 52390    9.0
Name: new_cases, dtype: float64
52384 52391    2.0
Name: new_cases, dtype: float64
52385 52392    0.0
Name: new_cases, dtype: float64
52386 52393    9.0
Name: new_cases, dtype: float64
52387 52394    0.0
Name: new_cases, dtype: float64
52388 52395    1.0
Name: new_cases, dtype: float64
52389 52396    5.0
Name: new_cases, dtype: float64
52390 52397    3.0
Name: new_cases, dtype: float64
52391 52398    0.0
Name: new_cases, dtype: float64
52392 52399    1.0
Name: new_cases, dtype: float64
52393 52400    4.0
Name: new_cases, dtype: float64
52394 52401    2.0
Name: new_cases, dtype: float64
52395 52402    3.0
Name: new_cases, dtype: float64
52396 52403    6.0
Name: new_cases, dtype: float64
52397 52404    5.0
Name: new_cases, dtype: float64
52398 52405    7.0
Name: new_cases, dtype: float64
52399 52406    9.0
Name: new_cases, dtype: float64
52400 52407    5.0
Name: new_cases, dtype: float64
52401 52408    4.0
Name: new_cases, dtype: float64
52402 52409    4.0
Name: new_cases, dtype: float64
52403 52410    7.0
Name: new_cases, dtype: float64
52404 52411    1.0
Name: new_cases, dtype: float64
52405 52412    12.0
Name: new_cases, dtype: float64
52406 52413    7.0
Name: new_cases, dtype: float64
52407 52414    7.0
Name: new_cases, dtype: float64
52408 52415    17.0
Name: new_cases, dtype: float64
52409 52416    21.0
Name: new_cases, dtype: float64
52410 52417    7.0
Name: new_cases, dtype: float64
52411 52418    12.0
Name: new_cases, dtype: float64
52412 52419    14.0
Name: new_cases, dtype: float64
52413 52420    8.0
Name: new_cases, dtype: float64
52414 52421    15.0
Name: new_cases, dtype: float64
52415 52422    7.0
Name: new_cases, dtype: float64
52416 52423    16.0
Name: new_cases, dtype: float64
52417 52424    8.0
Name: new_cases, dtype: float64
52418 52425    15.0
Name: new_cases, dtype: float64
52419 52426    15.0
Name: new_cases, dtype: float64
52420 52427    28.0
Name: new_cases, dtype: float64
52421 52428    6.0
Name: new_cases, dtype: float64
52422 52429    42.0
Name: new_cases, dtype: float64
52423 52430    22.0
Name: new_cases, dtype: float64
52424 52431    18.0
Name: new_cases, dtype: float64
52425 52432    6.0
Name: new_cases, dtype: float64
52426 52433    8.0
Name: new_cases, dtype: float64
52427 52434    6.0
Name: new_cases, dtype: float64
52428 52435    8.0
Name: new_cases, dtype: float64
52429 52436    9.0
Name: new_cases, dtype: float64
52430 52437    19.0
Name: new_cases, dtype: float64
52431 52438    12.0
Name: new_cases, dtype: float64
52432 52439    30.0
Name: new_cases, dtype: float64
52433 52440    11.0
Name: new_cases, dtype: float64
52434 52441    14.0
Name: new_cases, dtype: float64
52435 52442    6.0
Name: new_cases, dtype: float64
52436 52443    22.0
Name: new_cases, dtype: float64
52437 52444    27.0
Name: new_cases, dtype: float64
52438 52445    16.0
Name: new_cases, dtype: float64
52439 52446    7.0
Name: new_cases, dtype: float64
52440 52447    4.0
Name: new_cases, dtype: float64
52441 52448    11.0
Name: new_cases, dtype: float64
52442 52449    6.0
Name: new_cases, dtype: float64
52443 52450    5.0
Name: new_cases, dtype: float64
52444 52451    8.0
Name: new_cases, dtype: float64
52445 52452    3.0
Name: new_cases, dtype: float64
52446 52453    9.0
Name: new_cases, dtype: float64
52447 52454    3.0
Name: new_cases, dtype: float64
52448 52455    4.0
Name: new_cases, dtype: float64
52449 52456    5.0
Name: new_cases, dtype: float64
52450 52457    20.0
Name: new_cases, dtype: float64
52451 52458    4.0
Name: new_cases, dtype: float64
52452 52459    12.0
Name: new_cases, dtype: float64
52453 52460    12.0
Name: new_cases, dtype: float64
52454 52461    6.0
Name: new_cases, dtype: float64
52455 52462    6.0
Name: new_cases, dtype: float64
52456 52463    6.0
Name: new_cases, dtype: float64
52457 52464    8.0
Name: new_cases, dtype: float64
52458 52465    2.0
Name: new_cases, dtype: float64
52459 52466    5.0
Name: new_cases, dtype: float64
52460 52467    2.0
Name: new_cases, dtype: float64
52461 52468    1.0
Name: new_cases, dtype: float64
52462 52469    1.0
Name: new_cases, dtype: float64
52463 52470    3.0
Name: new_cases, dtype: float64
52464 52471    3.0
Name: new_cases, dtype: float64
52465 52472    8.0
Name: new_cases, dtype: float64
52466 52473    11.0
Name: new_cases, dtype: float64
52467 52474    26.0
Name: new_cases, dtype: float64
52468 52475    11.0
Name: new_cases, dtype: float64
52469 52476    2.0
Name: new_cases, dtype: float64
52470 52477    4.0
Name: new_cases, dtype: float64
52471 52478    1.0
Name: new_cases, dtype: float64
52472 52479    4.0
Name: new_cases, dtype: float64
52473 52480    3.0
Name: new_cases, dtype: float64
52474 52481    1.0
Name: new_cases, dtype: float64
52475 52482    3.0
Name: new_cases, dtype: float64
52476 52483    6.0
Name: new_cases, dtype: float64
52477 52484    9.0
Name: new_cases, dtype: float64
52478 52485    4.0
Name: new_cases, dtype: float64
52479 52486    12.0
Name: new_cases, dtype: float64
52480 52487    8.0
Name: new_cases, dtype: float64
52481 52488    13.0
Name: new_cases, dtype: float64
52482 52489    15.0
Name: new_cases, dtype: float64
52483 52490    0.0
Name: new_cases, dtype: float64
52484 52491    9.0
Name: new_cases, dtype: float64
52485 52492    5.0
Name: new_cases, dtype: float64
52486 52493    3.0
Name: new_cases, dtype: float64
52487 52494    2.0
Name: new_cases, dtype: float64
52488 52495    8.0
Name: new_cases, dtype: float64
52489 52496    2.0
Name: new_cases, dtype: float64
52490 52497    3.0
Name: new_cases, dtype: float64
52491 52498    3.0
Name: new_cases, dtype: float64
52492 52499    3.0
Name: new_cases, dtype: float64
52493 52500    2.0
Name: new_cases, dtype: float64
52494 52501    2.0
Name: new_cases, dtype: float64
52495 52502    3.0
Name: new_cases, dtype: float64
52496 52503    2.0
Name: new_cases, dtype: float64
52497 52504    2.0
Name: new_cases, dtype: float64
52498 52505    3.0
Name: new_cases, dtype: float64
52499 52506    8.0
Name: new_cases, dtype: float64
52500 52507    4.0
Name: new_cases, dtype: float64
52501 52508    5.0
Name: new_cases, dtype: float64
52502 52509    3.0
Name: new_cases, dtype: float64
52503 52510    2.0
Name: new_cases, dtype: float64
52504 52511    5.0
Name: new_cases, dtype: float64
52505 52512    5.0
Name: new_cases, dtype: float64
52506 52513    5.0
Name: new_cases, dtype: float64
52507 52514    5.0
Name: new_cases, dtype: float64
52508 52515    8.0
Name: new_cases, dtype: float64
52509 52516    5.0
Name: new_cases, dtype: float64
52510 52517    9.0
Name: new_cases, dtype: float64
52511 52518    4.0
Name: new_cases, dtype: float64
52512 52519    5.0
Name: new_cases, dtype: float64
52513 52520    2.0
Name: new_cases, dtype: float64
52514 52521    4.0
Name: new_cases, dtype: float64
52515 52522    8.0
Name: new_cases, dtype: float64
52516 52523    10.0
Name: new_cases, dtype: float64
52517 52524    11.0
Name: new_cases, dtype: float64
52518 52525    10.0
Name: new_cases, dtype: float64
52519 52526    24.0
Name: new_cases, dtype: float64
52520 52527    12.0
Name: new_cases, dtype: float64
52521 52528    19.0
Name: new_cases, dtype: float64
52522 52529    13.0
Name: new_cases, dtype: float64
52523 52530    14.0
Name: new_cases, dtype: float64
52524 52531    6.0
Name: new_cases, dtype: float64
52525 52532    8.0
Name: new_cases, dtype: float64

52526 52533    10.0
Name: new_cases, dtype: float64
52527 52534    5.0
Name: new_cases, dtype: float64
52528 52535    8.0
Name: new_cases, dtype: float64
52529 52536    3.0
Name: new_cases, dtype: float64
52530 52537    6.0
Name: new_cases, dtype: float64
52531 52538    2.0
Name: new_cases, dtype: float64
52532 52539    3.0
Name: new_cases, dtype: float64
52533 52540    15.0
Name: new_cases, dtype: float64
52534 52541    9.0
Name: new_cases, dtype: float64
52535 52542    7.0
Name: new_cases, dtype: float64
52536 52543    3.0
Name: new_cases, dtype: float64
52537 52544    9.0
Name: new_cases, dtype: float64
52538 52545    25.0
Name: new_cases, dtype: float64
52539 52546    14.0
Name: new_cases, dtype: float64
52540 52547    14.0
Name: new_cases, dtype: float64
52541 52548    5.0
Name: new_cases, dtype: float64
52542 52549    23.0
Name: new_cases, dtype: float64
52543 52550    15.0
Name: new_cases, dtype: float64
52544 52551    15.0
Name: new_cases, dtype: float64
52545 52552    5.0
Name: new_cases, dtype: float64
52546 52553    10.0
Name: new_cases, dtype: float64
52547 52554    10.0
Name: new_cases, dtype: float64
52548 52555    9.0
Name: new_cases, dtype: float64
52549 52556    15.0
Name: new_cases, dtype: float64
52550 52557    9.0
Name: new_cases, dtype: float64
52551 52558    17.0
Name: new_cases, dtype: float64
52552 52559    10.0
Name: new_cases, dtype: float64
52553 52560    8.0
Name: new_cases, dtype: float64
52554 52561    7.0
Name: new_cases, dtype: float64
52555 52562    11.0
Name: new_cases, dtype: float64
52556 52563    8.0
Name: new_cases, dtype: float64
52557 52564    7.0
Name: new_cases, dtype: float64
52558 52565    7.0
Name: new_cases, dtype: float64
52559 52566    18.0
Name: new_cases, dtype: float64
52560 52567    23.0
Name: new_cases, dtype: float64
52561 52568    38.0
Name: new_cases, dtype: float64
52562 52569    20.0
Name: new_cases, dtype: float64
52563 52570    28.0
Name: new_cases, dtype: float64
52564 52571    25.0
Name: new_cases, dtype: float64
52565 52572    29.0
Name: new_cases, dtype: float64
52566 52573    34.0
Name: new_cases, dtype: float64
52567 52574    45.0
Name: new_cases, dtype: float64
52568 52575    44.0
Name: new_cases, dtype: float64
52569 52576    57.0
Name: new_cases, dtype: float64
52570 52577    87.0
Name: new_cases, dtype: float64
52571 52578    158.0
Name: new_cases, dtype: float64
52572 52579    152.0
Name: new_cases, dtype: float64
52573 52580    165.0
Name: new_cases, dtype: float64
52574 52581    170.0
Name: new_cases, dtype: float64
52575 52582    196.0
Name: new_cases, dtype: float64
52576 52583    179.0
Name: new_cases, dtype: float64
52577 52584    182.0
Name: new_cases, dtype: float64
52578 52585    187.0
Name: new_cases, dtype: float64
52579 52586    196.0
Name: new_cases, dtype: float64
52580 52587    193.0
Name: new_cases, dtype: float64
52581 52588    218.0
Name: new_cases, dtype: float64
52582 52589    227.0
Name: new_cases, dtype: float64
52583 52590    259.0
Name: new_cases, dtype: float64
52584 52591    265.0
Name: new_cases, dtype: float64
52585 52592    296.0
Name: new_cases, dtype: float64
52586 52593    294.0
Name: new_cases, dtype: float64
52587 52594    298.0
Name: new_cases, dtype: float64
52588 52595    314.0
Name: new_cases, dtype: float64
52589 52596    326.0
Name: new_cases, dtype: float64
52590 52597    448.0
Name: new_cases, dtype: float64
52591 52598    453.0
Name: new_cases, dtype: float64
52592 52599    471.0
Name: new_cases, dtype: float64
52593 52600    554.0
Name: new_cases, dtype: float64
52594 52601    578.0
Name: new_cases, dtype: float64
52595 52602    549.0
Name: new_cases, dtype: float64
52596 52603    508.0
Name: new_cases, dtype: float64
52597 52604    472.0
Name: new_cases, dtype: float64
52598 52605    527.0
Name: new_cases, dtype: float64
52599 52606    519.0
Name: new_cases, dtype: float64
52600 52607    523.0
Name: new_cases, dtype: float64
52601 52608    478.0
Name: new_cases, dtype: float64
52602 52609    569.0
Name: new_cases, dtype: float64
52603 52610    680.0
Name: new_cases, dtype: float64
52604 52611    919.0
Name: new_cases, dtype: float64
52605 52612    887.0
Name: new_cases, dtype: float64
52606 52613    958.0
Name: new_cases, dtype: float64
52607 52614    1192.0
Name: new_cases, dtype: float64
52608 52615    1186.0
Name: new_cases, dtype: float64
52609 52616    1194.0
Name: new_cases, dtype: float64
52610 52617    1351.0
Name: new_cases, dtype: float64
52611 52618    1595.0
Name: new_cases, dtype: float64
52612 52619    1759.0
Name: new_cases, dtype: float64
52613 52620    1941.0
Name: new_cases, dtype: float64
52614 52621    1928.0
Name: new_cases, dtype: float64
52615 52622    1872.0
Name: new_cases, dtype: float64
52616 52623    1824.0
Name: new_cases, dtype: float64
52617 52624    1731.0
Name: new_cases, dtype: float64
52618 52625    1709.0
Name: new_cases, dtype: float64
52619 52626    1696.0
Name: new_cases, dtype: float64
52620 52627    1673.0
Name: new_cases, dtype: float64
52621 52628    1791.0
Name: new_cases, dtype: float64
52622 52629    1852.0
Name: new_cases, dtype: float64
52623 52630    1943.0
Name: new_cases, dtype: float64
52624 52631    2295.0
Name: new_cases, dtype: float64
52625 52632    2401.0
Name: new_cases, dtype: float64
52626 52633    2775.0
Name: new_cases, dtype: float64
52627 52634    2859.0
Name: new_cases, dtype: float64
52628 52635    2901.0
Name: new_cases, dtype: float64
52629 52636    2927.0
Name: new_cases, dtype: float64
52630 52637    2970.0
Name: new_cases, dtype: float64
52631 52638    2911.0
Name: new_cases, dtype: float64
52632 52639    3120.0
Name: new_cases, dtype: float64
52633 52640    3473.0
Name: new_cases, dtype: float64
52634 52641    3504.0
Name: new_cases, dtype: float64
52635 52642    3020.0
Name: new_cases, dtype: float64
52636 52643    3157.0
Name: new_cases, dtype: float64
52637 52644    3117.0
Name: new_cases, dtype: float64
52638 52645    3443.0
Name: new_cases, dtype: float64
52639 52646    3697.0
Name: new_cases, dtype: float64
52640 52647    3768.0
Name: new_cases, dtype: float64
52641 52648    3824.0
Name: new_cases, dtype: float64
52642 52649    4048.0
Name: new_cases, dtype: float64
52643 52650    3958.0
Name: new_cases, dtype: float64
52644 52651    3128.0
Name: new_cases, dtype: float64
52645 52652    3071.0
Name: new_cases, dtype: float64
52646 52653    3801.0
Name: new_cases, dtype: float64
52647 52654    4780.0
Name: new_cases, dtype: float64
52648 52655    4472.0
Name: new_cases, dtype: float64
52649 52656    4426.0
Name: new_cases, dtype: float64
52650 52657    3216.0
Name: new_cases, dtype: float64
52651 52658    3759.0
Name: new_cases, dtype: float64
52652 52659    4033.0
Name: new_cases, dtype: float64
52653 52660    4260.0
Name: new_cases, dtype: float64
52654 52661    5068.0
Name: new_cases, dtype: float64
52655 52662    5450.0
Name: new_cases, dtype: float64
52656 52663    4321.0
Name: new_cases, dtype: float64
52657 52664    2501.0
Name: new_cases, dtype: float64
52658 52665    4673.0
Name: new_cases, dtype: float64
52659 52666    4734.0
Name: new_cases, dtype: float64
52660 52667    4570.0
Name: new_cases, dtype: float64
52661 52668    4146.0
Name: new_cases, dtype: float64
52662 52669    3907.0
Name: new_cases, dtype: float64
52663 52670    2720.0
Name: new_cases, dtype: float64
52664 52671    1337.0
Name: new_cases, dtype: float64
52665 52672    3837.0
Name: new_cases, dtype: float64
52666 52673    3487.0
Name: new_cases, dtype: float64
52667 52674    2981.0
Name: new_cases, dtype: float64
52668 52675    2635.0
Name: new_cases, dtype: float64
52669 52676    2904.0
Name: new_cases, dtype: float64
52670 52677    1731.0
Name: new_cases, dtype: float64
52671 52678    824.0
Name: new_cases, dtype: float64
52672 52679    3064.0
Name: new_cases, dtype: float64
52673 52680    2345.0
Name: new_cases, dtype: float64
52674 52681    1972.0
Name: new_cases, dtype: float64
52675 52682    1881.0
Name: new_cases, dtype: float64
52676 52683    1784.0
Name: new_cases, dtype: float64
52677 52684    1097.0
Name: new_cases, dtype: float64
52678 52685    538.0
Name: new_cases, dtype: float64
52679 52686    2012.0
Name: new_cases, dtype: float64
52680 52687    1738.0
Name: new_cases, dtype: float64

52681 52688    1527.0
Name: new_cases, dtype: float64
52682 52689    990.0
Name: new_cases, dtype: float64
52683 52690    342.0
Name: new_cases, dtype: float64
52684 52691    417.0
Name: new_cases, dtype: float64
52685 52692    594.0
Name: new_cases, dtype: float64
52686 52693    2316.0
Name: new_cases, dtype: float64
52687 52694    1800.0
Name: new_cases, dtype: float64
52688 52695    1612.0
Name: new_cases, dtype: float64
52689 52696    537.0
Name: new_cases, dtype: float64
52690 52697    2058.0
Name: new_cases, dtype: float64
52691 52698    1143.0
Name: new_cases, dtype: float64
52692 52699    551.0
Name: new_cases, dtype: float64
52693 52700    1857.0
Name: new_cases, dtype: float64
52694 52701    1618.0
Name: new_cases, dtype: float64
52695 52702    1357.0
Name: new_cases, dtype: float64
52696 52703    1177.0
Name: new_cases, dtype: float64
52697 52704    1236.0
Name: new_cases, dtype: float64
52698 52705    780.0
Name: new_cases, dtype: float64
52699 52706    110.0
Name: new_cases, dtype: float64
52700 52707    1550.0
Name: new_cases, dtype: float64
52701 52708    469.0
Name: new_cases, dtype: float64
52702 52709    1137.0
Name: new_cases, dtype: float64
52703 52710    903.0
Name: new_cases, dtype: float64
52704 52711    998.0
Name: new_cases, dtype: float64
52705 52712    546.0
Name: new_cases, dtype: float64
52706 52713    298.0
Name: new_cases, dtype: float64
52707 52714    1006.0
Name: new_cases, dtype: float64
52708 52715    742.0
Name: new_cases, dtype: float64
52709 52716    723.0
Name: new_cases, dtype: float64
52710 52717    669.0
Name: new_cases, dtype: float64
52711 52718    676.0
Name: new_cases, dtype: float64
52712 52719    479.0
Name: new_cases, dtype: float64
52713 52720    240.0
Name: new_cases, dtype: float64
52714 52721    858.0
Name: new_cases, dtype: float64
52715 52722    688.0
Name: new_cases, dtype: float64
52716 52723    583.0
Name: new_cases, dtype: float64
52717 52724    538.0
Name: new_cases, dtype: float64
52718 52725    602.0
Name: new_cases, dtype: float64
52719 52726    404.0
Name: new_cases, dtype: float64
52720 52727    204.0
Name: new_cases, dtype: float64
52721 52728    829.0
Name: new_cases, dtype: float64
52722 52729    544.0
Name: new_cases, dtype: float64
52723 52730    557.0
Name: new_cases, dtype: float64
52724 52731    507.0
Name: new_cases, dtype: float64
52725 52732    535.0
Name: new_cases, dtype: float64
52726 52733    357.0
Name: new_cases, dtype: float64
52727 52734    165.0
Name: new_cases, dtype: float64
52728 52735    740.0
Name: new_cases, dtype: float64
52729 52736    486.0
Name: new_cases, dtype: float64
52730 52737    365.0
Name: new_cases, dtype: float64
52731 52738    388.0
Name: new_cases, dtype: float64
52732 52739    396.0
Name: new_cases, dtype: float64
52733 52740    258.0
Name: new_cases, dtype: float64
52734 52741    147.0
Name: new_cases, dtype: float64
52735 52742    493.0
Name: new_cases, dtype: float64
52736 52743    443.0
Name: new_cases, dtype: float64
52737 52744    362.0
Name: new_cases, dtype: float64
52738 52745    337.0
Name: new_cases, dtype: float64
52739 52746    373.0
Name: new_cases, dtype: float64
52740 52747    248.0
Name: new_cases, dtype: float64
52741 52748    160.0
Name: new_cases, dtype: float64
52742 52749    461.0
Name: new_cases, dtype: float64
52743 52750    360.0
Name: new_cases, dtype: float64
52744 52751    133.0
Name: new_cases, dtype: float64
52745 52752    390.0
Name: new_cases, dtype: float64
52746 52753    355.0
Name: new_cases, dtype: float64
52747 52754    234.0
Name: new_cases, dtype: float64
52748 52755    147.0
Name: new_cases, dtype: float64
52749 52756    139.0
Name: new_cases, dtype: float64
52750 52757    513.0
Name: new_cases, dtype: float64
52751 52758    395.0
Name: new_cases, dtype: float64
52752 52759    332.0
Name: new_cases, dtype: float64
52753 52760    344.0
Name: new_cases, dtype: float64
52754 52761    268.0
Name: new_cases, dtype: float64
52755 52762    159.0
Name: new_cases, dtype: float64
52756 52763    537.0
Name: new_cases, dtype: float64
52757 52764    382.0
Name: new_cases, dtype: float64
52758 52765    369.0
Name: new_cases, dtype: float64
52759 52766    360.0
Name: new_cases, dtype: float64
52760 52767    422.0
Name: new_cases, dtype: float64
52761 52768    262.0
Name: new_cases, dtype: float64
52762 52769    170.0
Name: new_cases, dtype: float64
52763 52770    528.0
Name: new_cases, dtype: float64
52764 52771    450.0
Name: new_cases, dtype: float64
52765 52772    399.0
Name: new_cases, dtype: float64
52766 52773    419.0
Name: new_cases, dtype: float64
52767 52774    490.0
Name: new_cases, dtype: float64
52768 52775    365.0
Name: new_cases, dtype: float64
52769 52776    171.0
Name: new_cases, dtype: float64
52770 52777    673.0
Name: new_cases, dtype: float64
52771 52778    616.0
Name: new_cases, dtype: float64
52772 52779    499.0
Name: new_cases, dtype: float64
52773 52780    529.0
Name: new_cases, dtype: float64
52774 52781    580.0
Name: new_cases, dtype: float64
52775 52782    464.0
Name: new_cases, dtype: float64
52776 52783    228.0
Name: new_cases, dtype: float64
52777 52784    897.0
Name: new_cases, dtype: float64
52778 52785    687.0
Name: new_cases, dtype: float64
52779 52786    761.0
Name: new_cases, dtype: float64
52780 52787    777.0
Name: new_cases, dtype: float64
52781 52788    506.0
Name: new_cases, dtype: float64
52782 52789    707.0
Name: new_cases, dtype: float64
52783 52790    359.0
Name: new_cases, dtype: float64
52784 52791    1374.0
Name: new_cases, dtype: float64
52785 52792    1085.0
Name: new_cases, dtype: float64
52786 52793    1030.0
Name: new_cases, dtype: float64
52787 52794    1077.0
Name: new_cases, dtype: float64
52788 52795    1219.0
Name: new_cases, dtype: float64
52789 52796    818.0
Name: new_cases, dtype: float64
52790 52797    578.0
Name: new_cases, dtype: float64
52791 52798    1792.0
Name: new_cases, dtype: float64
52792 52799    1310.0
Name: new_cases, dtype: float64
52793 52800    1226.0
Name: new_cases, dtype: float64
52794 52801    1271.0
Name: new_cases, dtype: float64
52795 52802    1250.0
Name: new_cases, dtype: float64
52796 52803    966.0
Name: new_cases, dtype: float64
52797 52804    521.0
Name: new_cases, dtype: float64
52798 52805    1578.0
Name: new_cases, dtype: float64
52799 52806    1551.0
Name: new_cases, dtype: float64
52800 52807    1433.0
Name: new_cases, dtype: float64
52801 52808    1476.0
Name: new_cases, dtype: float64
52802 52809    1147.0
Name: new_cases, dtype: float64
52803 52810    988.0
Name: new_cases, dtype: float64
52804 52811    509.0
Name: new_cases, dtype: float64
52805 52812    788.0
Name: new_cases, dtype: float64
52806 52813    2171.0
Name: new_cases, dtype: float64
52807 52814    1806.0
Name: new_cases, dtype: float64
52808 52815    1547.0
Name: new_cases, dtype: float64
52809 52816    1564.0
Name: new_cases, dtype: float64
52810 52817    1089.0
Name: new_cases, dtype: float64
52811 52818    549.0
Name: new_cases, dtype: float64
52812 52819    1788.0
Name: new_cases, dtype: float64
52813 52820    1409.0
Name: new_cases, dtype: float64
52814 52821    776.0
Name: new_cases, dtype: float64
52815 52822    1390.0
Name: new_cases, dtype: float64
52816 52823    1576.0
Name: new_cases, dtype: float64
52817 52824    968.0
Name: new_cases, dtype: float64
52818 52825    504.0
Name: new_cases, dtype: float64
52819 52826    1562.0
Name: new_cases, dtype: float64
52820 52827    1160.0
Name: new_cases, dtype: float64
52821 52828    1104.0
Name: new_cases, dtype: float64
52822 52829    1064.0
Name: new_cases, dtype: float64
52823 52830    1071.0
Name: new_cases, dtype: float64
52824 52831    733.0
Name: new_cases, dtype: float64
52825 52832    388.0
Name: new_cases, dtype: float64
52826 52833    1354.0
Name: new_cases, dtype: float64
52827 52834    1015.0
Name: new_cases, dtype: float64
52828 52835    508.0
Name: new_cases, dtype: float64
52829 52836    1056.0
Name: new_cases, dtype: float64
52830 52837    986.0
Name: new_cases, dtype: float64
52831 52838    723.0
Name: new_cases, dtype: float64
52832 52839    360.0
Name: new_cases, dtype: float64
52833 52840    1233.0
Name: new_cases, dtype: float64
52834 52841    954.0
Name: new_cases, dtype: float64
52835 52842    833.0
Name: new_cases, dtype: float64
52836 52843    779.0
Name: new_cases, dtype: float64
52837 52844    832.0
Name: new_cases, dtype: float64
52838 52845    504.0
Name: new_cases, dtype: float64
52839 52846    307.0
Name: new_cases, dtype: float64
52840 52847    1023.0
Name: new_cases, dtype: float64
52841 52848    821.0
Name: new_cases, dtype: float64
52842 52849    705.0
Name: new_cases, dtype: float64
52843 52850    695.0
Name: new_cases, dtype: float64
52844 52851    794.0
Name: new_cases, dtype: float64
52845 52852    522.0
Name: new_cases, dtype: float64
52846 52853    311.0
Name: new_cases, dtype: float64
52847 52854    1092.0
Name: new_cases, dtype: float64
52848 52855    811.0
Name: new_cases, dtype: float64
52849 52856    741.0
Name: new_cases, dtype: float64

52850 52857    671.0
Name: new_cases, dtype: float64
52851 52858    769.0
Name: new_cases, dtype: float64
52852 52859    521.0
Name: new_cases, dtype: float64
52853 52860    260.0
Name: new_cases, dtype: float64
52854 52861    914.0
Name: new_cases, dtype: float64
52855 52862    773.0
Name: new_cases, dtype: float64
52856 52863    656.0
Name: new_cases, dtype: float64
52857 52864    699.0
Name: new_cases, dtype: float64
52858 52865    754.0
Name: new_cases, dtype: float64
52859 52866    585.0
Name: new_cases, dtype: float64
52860 52867    352.0
Name: new_cases, dtype: float64
52861 52868    1194.0
Name: new_cases, dtype: float64
52862 52869    1010.0
Name: new_cases, dtype: float64
52863 52870    980.0
Name: new_cases, dtype: float64
52864 52871    964.0
Name: new_cases, dtype: float64
52865 52872    1026.0
Name: new_cases, dtype: float64
52866 52873    0.0
Name: new_cases, dtype: float64
52867 52874    838.0
Name: new_cases, dtype: float64
52868 52875    1407.0
Name: new_cases, dtype: float64
52869 52876    1392.0
Name: new_cases, dtype: float64
52870 52877    1043.0
Name: new_cases, dtype: float64
52871 52878    1108.0
Name: new_cases, dtype: float64
52872 52879    1364.0
Name: new_cases, dtype: float64
52873 52880    952.0
Name: new_cases, dtype: float64
52874 52881    659.0
Name: new_cases, dtype: float64
52875 52882    1862.0
Name: new_cases, dtype: float64
52876 52883    1663.0
Name: new_cases, dtype: float64
52877 52884    1398.0
Name: new_cases, dtype: float64
52878 52885    1653.0
Name: new_cases, dtype: float64
52879 52886    1808.0
Name: new_cases, dtype: float64
52880 52887    1286.0
Name: new_cases, dtype: float64
52881 52888    848.0
Name: new_cases, dtype: float64
52882 52889    2616.0
Name: new_cases, dtype: float64
52883 52890    2415.0
Name: new_cases, dtype: float64
52884 52891    2261.0
Name: new_cases, dtype: float64
52885 52892    2460.0
Name: new_cases, dtype: float64
52886 52893    2617.0
Name: new_cases, dtype: float64
52887 52894    2061.0
Name: new_cases, dtype: float64
52888 52895    1264.0
Name: new_cases, dtype: float64
52889 52896    3666.0
Name: new_cases, dtype: float64
52890 52897    3141.0
Name: new_cases, dtype: float64
52891 52898    2796.0
Name: new_cases, dtype: float64
52892 52899    2712.0
Name: new_cases, dtype: float64
52893 52900    3196.0
Name: new_cases, dtype: float64
52894 52901    2654.0
Name: new_cases, dtype: float64
52895 52902    1655.0
Name: new_cases, dtype: float64
52896 52903    4827.0
Name: new_cases, dtype: float64
52897 52904    4233.0
Name: new_cases, dtype: float64
52898 52905    3670.0
Name: new_cases, dtype: float64
52899 52906    3780.0
Name: new_cases, dtype: float64
52900 52907    4216.0
Name: new_cases, dtype: float64
52901 52908    3344.0
Name: new_cases, dtype: float64
52902 52909    2236.0
Name: new_cases, dtype: float64
52903 52910    5697.0
Name: new_cases, dtype: float64
52904 52911    5352.0
Name: new_cases, dtype: float64
52905 52912    5128.0
Name: new_cases, dtype: float64
52906 52913    5359.0
Name: new_cases, dtype: float64
52907 52914    5579.0
Name: new_cases, dtype: float64
52908 52915    4314.0
Name: new_cases, dtype: float64
52909 52916    2676.0
Name: new_cases, dtype: float64
52910 52917    6208.0
Name: new_cases, dtype: float64
52911 52918    5914.0
Name: new_cases, dtype: float64
52912 52919    4921.0
Name: new_cases, dtype: float64
52913 52920    4743.0
Name: new_cases, dtype: float64
52914 52921    4901.0
Name: new_cases, dtype: float64
52915 52922    3803.0
Name: new_cases, dtype: float64
52916 52923    2354.0
Name: new_cases, dtype: float64
52917 52924    5924.0
Name: new_cases, dtype: float64
52918 52925    5021.0
Name: new_cases, dtype: float64
52919 52926    4128.0
Name: new_cases, dtype: float64
52920 52927    4031.0
Name: new_cases, dtype: float64
52921 52928    4247.0
Name: new_cases, dtype: float64
52922 52929    2669.0
Name: new_cases, dtype: float64
52923 52930    1915.0
Name: new_cases, dtype: float64
52924 52931    4778.0
Name: new_cases, dtype: float64
52925 52932    3886.0
Name: new_cases, dtype: float64
52926 52933    3212.0
Name: new_cases, dtype: float64
52927 52934    3034.0
Name: new_cases, dtype: float64
52928 52935    2684.0
Name: new_cases, dtype: float64
52929 52936    2210.0
Name: new_cases, dtype: float64
52930 52937    1120.0
Name: new_cases, dtype: float64
52931 52938    1965.0
Name: new_cases, dtype: float64
52932 52939    2571.0
Name: new_cases, dtype: float64
52933 52940    2455.0
Name: new_cases, dtype: float64
52934 52941    2262.0
Name: new_cases, dtype: float64
52935 52942    3821.0
Name: new_cases, dtype: float64
52936 52943    1838.0
Name: new_cases, dtype: float64
52937 52944    946.0
Name: new_cases, dtype: float64
52938 52945    3221.0
Name: new_cases, dtype: float64
52939 52946    2515.0
Name: new_cases, dtype: float64
52940 52947    2176.0
Name: new_cases, dtype: float64
52941 52948    2039.0
Name: new_cases, dtype: float64
52942 52949    1997.0
Name: new_cases, dtype: float64
52943 52950    1501.0
Name: new_cases, dtype: float64
52944 52951    662.0
Name: new_cases, dtype: float64
52945 52952    2470.0
Name: new_cases, dtype: float64
52946 52953    2016.0
Name: new_cases, dtype: float64
52947 52954    1653.0
Name: new_cases, dtype: float64
52948 52955    1698.0
Name: new_cases, dtype: float64
52949 52956    1597.0
Name: new_cases, dtype: float64
52950 52957    1132.0
Name: new_cases, dtype: float64
52951 52958    663.0
Name: new_cases, dtype: float64
52952 52959    2185.0
Name: new_cases, dtype: float64
52953 52960    1929.0
Name: new_cases, dtype: float64
52954 52961    1743.0
Name: new_cases, dtype: float64
52955 52962    1751.0
Name: new_cases, dtype: float64
52956 52963    1826.0
Name: new_cases, dtype: float64
52957 52964    1164.0
Name: new_cases, dtype: float64
52958 52965    867.0
Name: new_cases, dtype: float64
52959 52966    2800.0
Name: new_cases, dtype: float64
52960 52967    2410.0
Name: new_cases, dtype: float64
52961 52968    2228.0
Name: new_cases, dtype: float64
52962 52969    2661.0
Name: new_cases, dtype: float64
52963 52970    2844.0
Name: new_cases, dtype: float64
52964 52971    2490.0
Name: new_cases, dtype: float64
52965 52972    1530.0
Name: new_cases, dtype: float64
52966 52973    4775.0
Name: new_cases, dtype: float64
52967 52974    4837.0
Name: new_cases, dtype: float64
52968 52975    4212.0
Name: new_cases, dtype: float64
52969 52976    3270.0
Name: new_cases, dtype: float64
52970 52977    5076.0
Name: new_cases, dtype: float64
52971 52978    4581.0
Name: new_cases, dtype: float64
52972 52979    2479.0
Name: new_cases, dtype: float64
52973 52980    5739.0
Name: new_cases, dtype: float64
52974 52981    5219.0
Name: new_cases, dtype: float64
52975 52982    4411.0
Name: new_cases, dtype: float64
52976 52983    4155.0
Name: new_cases, dtype: float64
52977 52984    4467.0
Name: new_cases, dtype: float64
52978 52985    3436.0
Name: new_cases, dtype: float64
52979 52986    1942.0
Name: new_cases, dtype: float64
52980 52987    4762.0
Name: new_cases, dtype: float64
52981 52988    4337.0
Name: new_cases, dtype: float64
52982 52989    4009.0
Name: new_cases, dtype: float64
52983 52990    3965.0
Name: new_cases, dtype: float64
52984 52991    4610.0
Name: new_cases, dtype: float64
52985 52992    3382.0
Name: new_cases, dtype: float64
52986 52993    2141.0
Name: new_cases, dtype: float64
52987 52994    5553.0
Name: new_cases, dtype: float64
52988 52995    6024.0
Name: new_cases, dtype: float64
52989 52996    5206.0
Name: new_cases, dtype: float64
52990 52997    5340.0
Name: new_cases, dtype: float64
52991 52998    5240.0
Name: new_cases, dtype: float64
52992 52999    4104.0
Name: new_cases, dtype: float64
52993 53000    2191.0
Name: new_cases, dtype: float64
52994 53001    6021.0
Name: new_cases, dtype: float64
52995 53002    5751.0
Name: new_cases, dtype: float64
52996 53003    4563.0
Name: new_cases, dtype: float64
52997 53004    4445.0
Name: new_cases, dtype: float64
52998 53005    4565.0
Name: new_cases, dtype: float64
52999 53006    3700.0
Name: new_cases, dtype: float64
53000 53007    1820.0
Name: new_cases, dtype: float64
53001 53008    5204.0
Name: new_cases, dtype: float64
53002 53009    4732.0
Name: new_cases, dtype: float64
53003 53010    4446.0
Name: new_cases, dtype: float64
53004 53011    4278.0
Name: new_cases, dtype: float64
53005 53012    4318.0
Name: new_cases, dtype: float64
53006 53013    3357.0
Name: new_cases, dtype: float64
53007 53014    1851.0
Name: new_cases, dtype: float64
53008 53015    5085.0
Name: new_cases, dtype: float64
53009 53016    3201.0
Name: new_cases, dtype: float64
53010 53017    4331.0
Name: new_cases, dtype: float64
53011 53018    4534.0
Name: new_cases, dtype: float64
53012 53019    4058.0
Name: new_cases, dtype: float64
53013 53020    3333.0
Name: new_cases, dtype: float64
53014 53021    1954.0
Name: new_cases, dtype: float64
53015 53022    5050.0
Name: new_cases, dtype: float64
53016 53023    4459.0
Name: new_cases, dtype: float64
53017 53024    3731.0
Name: new_cases, dtype: float64

53018 53025    4100.0
Name: new_cases, dtype: float64
53019 53026    3950.0
Name: new_cases, dtype: float64
53020 53027    3410.0
Name: new_cases, dtype: float64
53021 53028    1778.0
Name: new_cases, dtype: float64
53022 53029    4509.0
Name: new_cases, dtype: float64
53023 53030    4226.0
Name: new_cases, dtype: float64
53024 53031    3562.0
Name: new_cases, dtype: float64
53025 53032    3454.0
Name: new_cases, dtype: float64
53026 53033    3542.0
Name: new_cases, dtype: float64
53027 53034    2922.0
Name: new_cases, dtype: float64
53028 53035    1527.0
Name: new_cases, dtype: float64
53029 53036    3988.0
Name: new_cases, dtype: float64
53030 53037    3278.0
Name: new_cases, dtype: float64
53031 53038    3123.0
Name: new_cases, dtype: float64
53032 53039    2979.0
Name: new_cases, dtype: float64
53033 53040    2784.0
Name: new_cases, dtype: float64
53034 53041    2195.0
Name: new_cases, dtype: float64
53035 53042    1296.0
Name: new_cases, dtype: float64
53036 53043    3282.0
Name: new_cases, dtype: float64
53037 53044    2739.0
Name: new_cases, dtype: float64
53038 53045    2164.0
Name: new_cases, dtype: float64
53039 53046    1976.0
Name: new_cases, dtype: float64
53040 53047    2090.0
Name: new_cases, dtype: float64
53041 53048    1661.0
Name: new_cases, dtype: float64
53042 53049    986.0
Name: new_cases, dtype: float64
53043 53050    2676.0
Name: new_cases, dtype: float64
53044 53051    2514.0
Name: new_cases, dtype: float64
53045 53052    2097.0
Name: new_cases, dtype: float64
53046 53053    2100.0
Name: new_cases, dtype: float64
53047 53054    2103.0
Name: new_cases, dtype: float64
53048 53055    796.0
Name: new_cases, dtype: float64
53049 53056    943.0
Name: new_cases, dtype: float64
53050 53057    3590.0
Name: new_cases, dtype: float64
53051 53058    3436.0
Name: new_cases, dtype: float64
53052 53059    3567.0
Name: new_cases, dtype: float64
53053 53060    4234.0
Name: new_cases, dtype: float64
53054 53061    2622.0
Name: new_cases, dtype: float64
53055 Series([], Name: new_cases, dtype: float64)
53056 Series([], Name: new_cases, dtype: float64)
53057 Series([], Name: new_cases, dtype: float64)
53058 Series([], Name: new_cases, dtype: float64)
53059 Series([], Name: new_cases, dtype: float64)
53060 Series([], Name: new_cases, dtype: float64)
53061 Series([], Name: new_cases, dtype: float64)
53062 53069    2.0
Name: new_cases, dtype: float64
53063 53070    0.0
Name: new_cases, dtype: float64
53064 53071    0.0
Name: new_cases, dtype: float64
53065 53072    0.0
Name: new_cases, dtype: float64
53066 53073    1.0
Name: new_cases, dtype: float64
53067 53074    0.0
Name: new_cases, dtype: float64
53068 53075    1.0
Name: new_cases, dtype: float64
53069 53076    0.0
Name: new_cases, dtype: float64
53070 53077    2.0
Name: new_cases, dtype: float64
53071 53078    0.0
Name: new_cases, dtype: float64
53072 53079    0.0
Name: new_cases, dtype: float64
53073 53080    0.0
Name: new_cases, dtype: float64
53074 53081    0.0
Name: new_cases, dtype: float64
53075 53082    0.0
Name: new_cases, dtype: float64
53076 53083    0.0
Name: new_cases, dtype: float64
53077 53084    0.0
Name: new_cases, dtype: float64
53078 53085    0.0
Name: new_cases, dtype: float64
53079 53086    0.0
Name: new_cases, dtype: float64
53080 53087    0.0
Name: new_cases, dtype: float64
53081 53088    0.0
Name: new_cases, dtype: float64
53082 53089    0.0
Name: new_cases, dtype: float64
53083 53090    0.0
Name: new_cases, dtype: float64
53084 53091    1.0
Name: new_cases, dtype: float64
53085 53092    10.0
Name: new_cases, dtype: float64
53086 53093    19.0
Name: new_cases, dtype: float64
53087 53094    2.0
Name: new_cases, dtype: float64
53088 53095    31.0
Name: new_cases, dtype: float64
53089 53096    51.0
Name: new_cases, dtype: float64
53090 53097    29.0
Name: new_cases, dtype: float64
53091 53098    37.0
Name: new_cases, dtype: float64
53092 53099    66.0
Name: new_cases, dtype: float64
53093 53100    220.0
Name: new_cases, dtype: float64
53094 53101    188.0
Name: new_cases, dtype: float64
53095 53102    129.0
Name: new_cases, dtype: float64
53096 53103    241.0
Name: new_cases, dtype: float64
53097 53104    136.0
Name: new_cases, dtype: float64
53098 53105    281.0
Name: new_cases, dtype: float64
53099 53106    451.0
Name: new_cases, dtype: float64
53100 53107    170.0
Name: new_cases, dtype: float64
53101 53108    1597.0
Name: new_cases, dtype: float64
53102 53109    910.0
Name: new_cases, dtype: float64
53103 53110    1210.0
Name: new_cases, dtype: float64
53104 53111    1477.0
Name: new_cases, dtype: float64
53105 53112    1985.0
Name: new_cases, dtype: float64
53106 53113    3070.0
Name: new_cases, dtype: float64
53107 53114    2993.0
Name: new_cases, dtype: float64
53108 53115    4528.0
Name: new_cases, dtype: float64
53109 53116    2365.0
Name: new_cases, dtype: float64
53110 53117    2660.0
Name: new_cases, dtype: float64
53111 53118    4183.0
Name: new_cases, dtype: float64
53112 53119    3930.0
Name: new_cases, dtype: float64
53113 53120    4337.0
Name: new_cases, dtype: float64
53114 53121    6615.0
Name: new_cases, dtype: float64
53115 53122    6933.0
Name: new_cases, dtype: float64
53116 53123    6824.0
Name: new_cases, dtype: float64
53117 53124    4400.0
Name: new_cases, dtype: float64
53118 53125    4790.0
Name: new_cases, dtype: float64
53119 53126    4923.0
Name: new_cases, dtype: float64
53120 53127    6064.0
Name: new_cases, dtype: float64
53121 53128    6922.0
Name: new_cases, dtype: float64
53122 53129    6365.0
Name: new_cases, dtype: float64
53123 53130    4933.0
Name: new_cases, dtype: float64
53124 53131    4031.0
Name: new_cases, dtype: float64
53125 53132    3251.0
Name: new_cases, dtype: float64
53126 53133    4289.0
Name: new_cases, dtype: float64
53127 53134    5633.0
Name: new_cases, dtype: float64
53128 53135    4885.0
Name: new_cases, dtype: float64
53129 53136    3990.0
Name: new_cases, dtype: float64
53130 53137    2737.0
Name: new_cases, dtype: float64
53131 53138    2946.0
Name: new_cases, dtype: float64
53132 53139    2218.0
Name: new_cases, dtype: float64
53133 53140    1287.0
Name: new_cases, dtype: float64
53134 53141    3394.0
Name: new_cases, dtype: float64
53135 53142    2945.0
Name: new_cases, dtype: float64
53136 53143    3699.0
Name: new_cases, dtype: float64
53137 53144    1945.0
Name: new_cases, dtype: float64
53138 53145    1842.0
Name: new_cases, dtype: float64
53139 53146    1881.0
Name: new_cases, dtype: float64
53140 53147    1226.0
Name: new_cases, dtype: float64
53141 53148    2357.0
Name: new_cases, dtype: float64
53142 53149    2481.0
Name: new_cases, dtype: float64
53143 53150    1870.0
Name: new_cases, dtype: float64
53144 53151    1514.0
Name: new_cases, dtype: float64
53145 53152    1257.0
Name: new_cases, dtype: float64
53146 53153    988.0
Name: new_cases, dtype: float64
53147 53154    1154.0
Name: new_cases, dtype: float64
53148 53155    1627.0
Name: new_cases, dtype: float64
53149 53156    1470.0
Name: new_cases, dtype: float64
53150 53157    1068.0
Name: new_cases, dtype: float64
53151 53158    890.0
Name: new_cases, dtype: float64
53152 53159    697.0
Name: new_cases, dtype: float64
53153 53160    488.0
Name: new_cases, dtype: float64
53154 53161    855.0
Name: new_cases, dtype: float64
53155 53162    1155.0
Name: new_cases, dtype: float64
53156 53163    1268.0
Name: new_cases, dtype: float64
53157 53164    1158.0
Name: new_cases, dtype: float64
53158 53165    736.0
Name: new_cases, dtype: float64
53159 53166    555.0
Name: new_cases, dtype: float64
53160 53167    697.0
Name: new_cases, dtype: float64
53161 53168    595.0
Name: new_cases, dtype: float64
53162 53169    927.0
Name: new_cases, dtype: float64
53163 53170    380.0
Name: new_cases, dtype: float64
53164 53171    755.0
Name: new_cases, dtype: float64
53165 53172    519.0
Name: new_cases, dtype: float64
53166 53173    617.0
Name: new_cases, dtype: float64
53167 53174    182.0
Name: new_cases, dtype: float64
53168 53175    1227.0
Name: new_cases, dtype: float64
53169 53176    695.0
Name: new_cases, dtype: float64
53170 53177    548.0
Name: new_cases, dtype: float64
53171 53178    689.0
Name: new_cases, dtype: float64
53172 53179    276.0
Name: new_cases, dtype: float64
53173 53180    342.0
Name: new_cases, dtype: float64
53174 53181    272.0
Name: new_cases, dtype: float64
53175 53182    600.0
Name: new_cases, dtype: float64
53176 53183    324.0
Name: new_cases, dtype: float64
53177 53184    672.0
Name: new_cases, dtype: float64
53178 53185    726.0
Name: new_cases, dtype: float64
53179 53186    267.0
Name: new_cases, dtype: float64
53180 53187    221.0
Name: new_cases, dtype: float64
53181 53188    184.0
Name: new_cases, dtype: float64
53182 53189    285.0
Name: new_cases, dtype: float64
53183 53190    242.0
Name: new_cases, dtype: float64
53184 53191    351.0
Name: new_cases, dtype: float64
53185 53192    452.0
Name: new_cases, dtype: float64
53186 53193    526.0
Name: new_cases, dtype: float64
53187 53194    300.0
Name: new_cases, dtype: float64
53188 53195    359.0
Name: new_cases, dtype: float64

53189 53196    397.0
Name: new_cases, dtype: float64
53190 53197    16.0
Name: new_cases, dtype: float64
53191 53198    169.0
Name: new_cases, dtype: float64
53192 53199    535.0
Name: new_cases, dtype: float64
53193 53200    41.0
Name: new_cases, dtype: float64
53194 53201    251.0
Name: new_cases, dtype: float64
53195 53202    164.0
Name: new_cases, dtype: float64
53196 53203    570.0
Name: new_cases, dtype: float64
53197 53204    352.0
Name: new_cases, dtype: float64
53198 53205    1213.0
Name: new_cases, dtype: float64
53199 53206    482.0
Name: new_cases, dtype: float64
53200 53207    371.0
Name: new_cases, dtype: float64
53201 53208    602.0
Name: new_cases, dtype: float64
53202 53209    496.0
Name: new_cases, dtype: float64
53203 53210    712.0
Name: new_cases, dtype: float64
53204 53211    391.0
Name: new_cases, dtype: float64
53205 53212    500.0
Name: new_cases, dtype: float64
53206 53213    665.0
Name: new_cases, dtype: float64
53207 53214    422.0
Name: new_cases, dtype: float64
53208 53215    235.0
Name: new_cases, dtype: float64
53209 53216    349.0
Name: new_cases, dtype: float64
53210 53217    376.0
Name: new_cases, dtype: float64
53211 53218    475.0
Name: new_cases, dtype: float64
53212 53219    477.0
Name: new_cases, dtype: float64
53213 53220    410.0
Name: new_cases, dtype: float64
53214 53221    418.0
Name: new_cases, dtype: float64
53215 53222    325.0
Name: new_cases, dtype: float64
53216 53223    541.0
Name: new_cases, dtype: float64
53217 53224    279.0
Name: new_cases, dtype: float64
53218 53225    356.0
Name: new_cases, dtype: float64
53219 53226    302.0
Name: new_cases, dtype: float64
53220 53227    331.0
Name: new_cases, dtype: float64
53221 53228    377.0
Name: new_cases, dtype: float64
53222 53229    210.0
Name: new_cases, dtype: float64
53223 53230    261.0
Name: new_cases, dtype: float64
53224 53231    276.0
Name: new_cases, dtype: float64
53225 53232    434.0
Name: new_cases, dtype: float64
53226 53233    560.0
Name: new_cases, dtype: float64
53227 53234    595.0
Name: new_cases, dtype: float64
53228 53235    381.0
Name: new_cases, dtype: float64
53229 53236    309.0
Name: new_cases, dtype: float64
53230 53237    590.0
Name: new_cases, dtype: float64
53231 53238    392.0
Name: new_cases, dtype: float64
53232 53239    559.0
Name: new_cases, dtype: float64
53233 53240    605.0
Name: new_cases, dtype: float64
53234 53241    742.0
Name: new_cases, dtype: float64
53235 53242    655.0
Name: new_cases, dtype: float64
53236 53243    389.0
Name: new_cases, dtype: float64
53237 53244    445.0
Name: new_cases, dtype: float64
53238 53245    595.0
Name: new_cases, dtype: float64
53239 53246    839.0
Name: new_cases, dtype: float64
53240 53247    989.0
Name: new_cases, dtype: float64
53241 53248    864.0
Name: new_cases, dtype: float64
53242 53249    606.0
Name: new_cases, dtype: float64
53243 53250    215.0
Name: new_cases, dtype: float64
53244 53251    891.0
Name: new_cases, dtype: float64
53245 53252    717.0
Name: new_cases, dtype: float64
53246 53253    1285.0
Name: new_cases, dtype: float64
53247 53254    926.0
Name: new_cases, dtype: float64
53248 53255    1157.0
Name: new_cases, dtype: float64
53249 53256    707.0
Name: new_cases, dtype: float64
53250 53257    385.0
Name: new_cases, dtype: float64
53251 53258    1220.0
Name: new_cases, dtype: float64
53252 53259    1032.0
Name: new_cases, dtype: float64
53253 53260    1319.0
Name: new_cases, dtype: float64
53254 53261    1422.0
Name: new_cases, dtype: float64
53255 53262    1510.0
Name: new_cases, dtype: float64
53256 53263    697.0
Name: new_cases, dtype: float64
53257 53264    519.0
Name: new_cases, dtype: float64
53258 53265    1693.0
Name: new_cases, dtype: float64
53259 53266    1420.0
Name: new_cases, dtype: float64
53260 53267    1586.0
Name: new_cases, dtype: float64
53261 53268    1586.0
Name: new_cases, dtype: float64
53262 53269    1737.0
Name: new_cases, dtype: float64
53263 53270    832.0
Name: new_cases, dtype: float64
53264 53271    633.0
Name: new_cases, dtype: float64
53265 53272    1628.0
Name: new_cases, dtype: float64
53266 53273    1461.0
Name: new_cases, dtype: float64
53267 53274    1427.0
Name: new_cases, dtype: float64
53268 53275    1561.0
Name: new_cases, dtype: float64
53269 53276    1555.0
Name: new_cases, dtype: float64
53270 53277    709.0
Name: new_cases, dtype: float64
53271 53278    470.0
Name: new_cases, dtype: float64
53272 53279    1497.0
Name: new_cases, dtype: float64
53273 53280    1213.0
Name: new_cases, dtype: float64
53274 53281    1396.0
Name: new_cases, dtype: float64
53275 53282    1429.0
Name: new_cases, dtype: float64
53276 53283    1443.0
Name: new_cases, dtype: float64
53277 53284    775.0
Name: new_cases, dtype: float64
53278 53285    670.0
Name: new_cases, dtype: float64
53279 53286    1898.0
Name: new_cases, dtype: float64
53280 53287    1331.0
Name: new_cases, dtype: float64
53281 53288    1476.0
Name: new_cases, dtype: float64
53282 53289    1716.0
Name: new_cases, dtype: float64
53283 53290    1586.0
Name: new_cases, dtype: float64
53284 53291    1082.0
Name: new_cases, dtype: float64
53285 53292    920.0
Name: new_cases, dtype: float64
53286 53293    1485.0
Name: new_cases, dtype: float64
53287 53294    1792.0
Name: new_cases, dtype: float64
53288 53295    1855.0
Name: new_cases, dtype: float64
53289 53296    2179.0
Name: new_cases, dtype: float64
53290 53297    2199.0
Name: new_cases, dtype: float64
53291 53298    1685.0
Name: new_cases, dtype: float64
53292 53299    1033.0
Name: new_cases, dtype: float64
53293 53300    1595.0
Name: new_cases, dtype: float64
53294 53301    1852.0
Name: new_cases, dtype: float64
53295 53302    1613.0
Name: new_cases, dtype: float64
53296 53303    2321.0
Name: new_cases, dtype: float64
53297 53304    2366.0
Name: new_cases, dtype: float64
53298 53305    1314.0
Name: new_cases, dtype: float64
53299 53306    1313.0
Name: new_cases, dtype: float64
53300 53307    2292.0
Name: new_cases, dtype: float64
53301 53308    1840.0
Name: new_cases, dtype: float64
53302 53309    2442.0
Name: new_cases, dtype: float64
53303 53310    2626.0
Name: new_cases, dtype: float64
53304 53311    2835.0
Name: new_cases, dtype: float64
53305 53312    1653.0
Name: new_cases, dtype: float64
53306 53313    1546.0
Name: new_cases, dtype: float64
53307 53314    3100.0
Name: new_cases, dtype: float64
53308 53315    2454.0
Name: new_cases, dtype: float64
53309 53316    4010.0
Name: new_cases, dtype: float64
53310 53317    4804.0
Name: new_cases, dtype: float64
53311 53318    4554.0
Name: new_cases, dtype: float64
53312 53319    2968.0
Name: new_cases, dtype: float64
53313 53320    2846.0
Name: new_cases, dtype: float64
53314 53321    6541.0
Name: new_cases, dtype: float64
53315 53322    4464.0
Name: new_cases, dtype: float64
53316 53323    7173.0
Name: new_cases, dtype: float64
53317 53324    7620.0
Name: new_cases, dtype: float64
53318 53325    7695.0
Name: new_cases, dtype: float64
53319 53326    4862.0
Name: new_cases, dtype: float64
53320 53327    4007.0
Name: new_cases, dtype: float64
53321 53328    8397.0
Name: new_cases, dtype: float64
53322 53329    8523.0
Name: new_cases, dtype: float64
53323 53330    12331.0
Name: new_cases, dtype: float64
53324 53331    5952.0
Name: new_cases, dtype: float64
53325 53332    13476.0
Name: new_cases, dtype: float64
53326 53333    10458.0
Name: new_cases, dtype: float64
53327 53334    9890.0
Name: new_cases, dtype: float64
53328 53335    12560.0
Name: new_cases, dtype: float64
53329 53336    13161.0
Name: new_cases, dtype: float64
53330 53337    16202.0
Name: new_cases, dtype: float64
53331 53338    18733.0
Name: new_cases, dtype: float64
53332 53339    19382.0
Name: new_cases, dtype: float64
53333 53340    14054.0
Name: new_cases, dtype: float64
53334 53341    12556.0
Name: new_cases, dtype: float64
53335 53342    25252.0
Name: new_cases, dtype: float64
53336 53343    7533.0
Name: new_cases, dtype: float64
53337 53344    31480.0
Name: new_cases, dtype: float64
53338 53345    22561.0
Name: new_cases, dtype: float64
53339 53346    22820.0
Name: new_cases, dtype: float64
53340 53347    14122.0
Name: new_cases, dtype: float64
53341 53348    14510.0
Name: new_cases, dtype: float64
53342 53349    6522.0
Name: new_cases, dtype: float64
53343 53350    26547.0
Name: new_cases, dtype: float64
53344 53351    22401.0
Name: new_cases, dtype: float64
53345 53352    24738.0
Name: new_cases, dtype: float64
53346 53353    22261.0
Name: new_cases, dtype: float64
53347 53354    14640.0
Name: new_cases, dtype: float64
53348 53355    3213.0
Name: new_cases, dtype: float64
53349 53356    14580.0
Name: new_cases, dtype: float64
53350 53357    26231.0
Name: new_cases, dtype: float64
53351 53358    23727.0
Name: new_cases, dtype: float64
53352 53359    24041.0
Name: new_cases, dtype: float64
53353 53360    22593.0
Name: new_cases, dtype: float64
53354 53361    13872.0
Name: new_cases, dtype: float64
53355 53362    4377.0
Name: new_cases, dtype: float64
53356 53363    14455.0
Name: new_cases, dtype: float64
53357 53364    16370.0
Name: new_cases, dtype: float64
53358 53365    32687.0
Name: new_cases, dtype: float64

53359 53366    21951.0
Name: new_cases, dtype: float64
53360 53367    20819.0
Name: new_cases, dtype: float64
53361 53368    13845.0
Name: new_cases, dtype: float64
53362 53369    3197.0
Name: new_cases, dtype: float64
53363 53370    14221.0
Name: new_cases, dtype: float64
53364 53371    24766.0
Name: new_cases, dtype: float64
53365 53372    23275.0
Name: new_cases, dtype: float64
53366 53373    23591.0
Name: new_cases, dtype: float64
53367 53374    15970.0
Name: new_cases, dtype: float64
53368 53375    26126.0
Name: new_cases, dtype: float64
53369 53376    10910.0
Name: new_cases, dtype: float64
53370 53377    5456.0
Name: new_cases, dtype: float64
53371 53378    29263.0
Name: new_cases, dtype: float64
53372 53379    25089.0
Name: new_cases, dtype: float64
53373 53380    32734.0
Name: new_cases, dtype: float64
53374 53381    27217.0
Name: new_cases, dtype: float64
53375 53382    21792.0
Name: new_cases, dtype: float64
53376 53383    14709.0
Name: new_cases, dtype: float64
53377 53384    6451.0
Name: new_cases, dtype: float64
53378 53385    33825.0
Name: new_cases, dtype: float64
53379 53386    32744.0
Name: new_cases, dtype: float64
53380 53387    30179.0
Name: new_cases, dtype: float64
53381 53388    32830.0
Name: new_cases, dtype: float64
53382 53389    21679.0
Name: new_cases, dtype: float64
53383 53390    6444.0
Name: new_cases, dtype: float64
53384 53391    19256.0
Name: new_cases, dtype: float64
53385 53392    36153.0
Name: new_cases, dtype: float64
53386 53393    33758.0
Name: new_cases, dtype: float64
53387 53394    26467.0
Name: new_cases, dtype: float64
53388 53395    2140.0
Name: new_cases, dtype: float64
53389 53396    13504.0
Name: new_cases, dtype: float64
53390 53397    12399.0
Name: new_cases, dtype: float64
53391 53398    14004.0
Name: new_cases, dtype: float64
53392 53399    19112.0
Name: new_cases, dtype: float64
53393 53400    31941.0
Name: new_cases, dtype: float64
53394 53401    23233.0
Name: new_cases, dtype: float64
53395 53402    15575.0
Name: new_cases, dtype: float64
53396 53403    11036.0
Name: new_cases, dtype: float64
53397 53404    10356.0
Name: new_cases, dtype: float64
53398 53405    12320.0
Name: new_cases, dtype: float64
53399 53406    18349.0
Name: new_cases, dtype: float64
53400 53407    26663.0
Name: new_cases, dtype: float64
53401 53408    45333.0
Name: new_cases, dtype: float64
53402 53409    19077.0
Name: new_cases, dtype: float64
53403 53410    22824.0
Name: new_cases, dtype: float64
53404 53411    948.0
Name: new_cases, dtype: float64
53405 53412    11706.0
Name: new_cases, dtype: float64
53406 53413    27210.0
Name: new_cases, dtype: float64
53407 53414    25566.0
Name: new_cases, dtype: float64
53408 53415    21343.0
Name: new_cases, dtype: float64
53409 53416    8593.0
Name: new_cases, dtype: float64
53410 53417    14817.0
Name: new_cases, dtype: float64
53411 53418    11484.0
Name: new_cases, dtype: float64
53412 53419    9253.0
Name: new_cases, dtype: float64
53413 53420    12233.0
Name: new_cases, dtype: float64
53414 53421    29003.0
Name: new_cases, dtype: float64
53415 53422    8277.0
Name: new_cases, dtype: float64
53416 53423    16366.0
Name: new_cases, dtype: float64
53417 53424    12430.0
Name: new_cases, dtype: float64
53418 53425    10078.0
Name: new_cases, dtype: float64
53419 53426    6887.0
Name: new_cases, dtype: float64
53420 53427    9387.0
Name: new_cases, dtype: float64
53421 53428    15636.0
Name: new_cases, dtype: float64
53422 53429    14883.0
Name: new_cases, dtype: float64
53423 53430    12831.0
Name: new_cases, dtype: float64
53424 53431    17518.0
Name: new_cases, dtype: float64
53425 53432    748.0
Name: new_cases, dtype: float64
53426 53433    6668.0
Name: new_cases, dtype: float64
53427 53434    7690.0
Name: new_cases, dtype: float64
53428 53435    12487.0
Name: new_cases, dtype: float64
53429 53436    13032.0
Name: new_cases, dtype: float64
53430 53437    10835.0
Name: new_cases, dtype: float64
53431 53438    8632.0
Name: new_cases, dtype: float64
53432 53439    6670.0
Name: new_cases, dtype: float64
53433 53440    4650.0
Name: new_cases, dtype: float64
53434 53441    5728.0
Name: new_cases, dtype: float64
53435 53442    9246.0
Name: new_cases, dtype: float64
53436 53443    9928.0
Name: new_cases, dtype: float64
53437 53444    9197.0
Name: new_cases, dtype: float64
53438 53445    6484.0
Name: new_cases, dtype: float64
53439 53446    4838.0
Name: new_cases, dtype: float64
53440 53447    5132.0
Name: new_cases, dtype: float64
53441 53448    5890.0
Name: new_cases, dtype: float64
53442 53449    9598.0
Name: new_cases, dtype: float64
53443 53450    9845.0
Name: new_cases, dtype: float64
53444 53451    9050.0
Name: new_cases, dtype: float64
53445 53452    7162.0
Name: new_cases, dtype: float64
53446 53453    6094.0
Name: new_cases, dtype: float64
53447 53454    4984.0
Name: new_cases, dtype: float64
53448 53455    5764.0
Name: new_cases, dtype: float64
53449 53456    10774.0
Name: new_cases, dtype: float64
53450 53457    11032.0
Name: new_cases, dtype: float64
53451 53458    9437.0
Name: new_cases, dtype: float64
53452 53459    7671.0
Name: new_cases, dtype: float64
53453 53460    6118.0
Name: new_cases, dtype: float64
53454 53461    5274.0
Name: new_cases, dtype: float64
53455 53462    6492.0
Name: new_cases, dtype: float64
53456 53463    10852.0
Name: new_cases, dtype: float64
53457 53464    11393.0
Name: new_cases, dtype: float64
53458 53465    9581.0
Name: new_cases, dtype: float64
53459 53466    8264.0
Name: new_cases, dtype: float64
53460 53467    6504.0
Name: new_cases, dtype: float64
53461 53468    5129.0
Name: new_cases, dtype: float64
53462 53469    6834.0
Name: new_cases, dtype: float64
53463 53470    21163.0
Name: new_cases, dtype: float64
53464 53471    4745.0
Name: new_cases, dtype: float64
53465 53472    12770.0
Name: new_cases, dtype: float64
53466 53473    10568.0
Name: new_cases, dtype: float64
53467 53474    8978.0
Name: new_cases, dtype: float64
53468 53475    6543.0
Name: new_cases, dtype: float64
53469 53476    9673.0
Name: new_cases, dtype: float64
53470 53477    17850.0
Name: new_cases, dtype: float64
53471 53478    17052.0
Name: new_cases, dtype: float64
53472 53479    16147.0
Name: new_cases, dtype: float64
53473 53480    13685.0
Name: new_cases, dtype: float64
53474 53481    10209.0
Name: new_cases, dtype: float64
53475 53482    8261.0
Name: new_cases, dtype: float64
53476 53483    20969.0
Name: new_cases, dtype: float64
53477 53484    23757.0
Name: new_cases, dtype: float64
53478 53485    21620.0
Name: new_cases, dtype: float64
53479 53486    20689.0
Name: new_cases, dtype: float64
53480 53487    17628.0
Name: new_cases, dtype: float64
53481 53488    1727.0
Name: new_cases, dtype: float64
53482 53489    10297.0
Name: new_cases, dtype: float64
53483 53490    23681.0
Name: new_cases, dtype: float64
53484 53491    25014.0
Name: new_cases, dtype: float64
53485 53492    22679.0
Name: new_cases, dtype: float64
53486 53493    16033.0
Name: new_cases, dtype: float64
53487 53494    3673.0
Name: new_cases, dtype: float64
53488 53495    10300.0
Name: new_cases, dtype: float64
53489 53496    5980.0
Name: new_cases, dtype: float64
53490 53497    7593.0
Name: new_cases, dtype: float64
53491 53498    30377.0
Name: new_cases, dtype: float64
53492 53499    26510.0
Name: new_cases, dtype: float64
53493 53500    23935.0
Name: new_cases, dtype: float64
53494 53501    18728.0
Name: new_cases, dtype: float64
53495 53502    2706.0
Name: new_cases, dtype: float64
53496 53503    12446.0
Name: new_cases, dtype: float64
53497 53504    29421.0
Name: new_cases, dtype: float64
53498 53505    31117.0
Name: new_cases, dtype: float64
53499 53506    25110.0
Name: new_cases, dtype: float64
53500 53507    23856.0
Name: new_cases, dtype: float64
53501 53508    20197.0
Name: new_cases, dtype: float64
53502 53509    1217.0
Name: new_cases, dtype: float64
53503 53510    11615.0
Name: new_cases, dtype: float64
53504 53511    31397.0
Name: new_cases, dtype: float64
53505 53512    24354.0
Name: new_cases, dtype: float64
53506 53513    31721.0
Name: new_cases, dtype: float64
53507 53514    22262.0
Name: new_cases, dtype: float64
53508 53515    14422.0
Name: new_cases, dtype: float64
53509 53516    15399.0
Name: new_cases, dtype: float64
53510 53517    5961.0
Name: new_cases, dtype: float64
53511 53518    25911.0
Name: new_cases, dtype: float64
53512 53519    28263.0
Name: new_cases, dtype: float64

53513 53520    24212.0
Name: new_cases, dtype: float64
53514 53521    14326.0
Name: new_cases, dtype: float64
53515 53522    18535.0
Name: new_cases, dtype: float64
53516 53523    8776.0
Name: new_cases, dtype: float64
53517 53524    5510.0
Name: new_cases, dtype: float64
53518 53525    24111.0
Name: new_cases, dtype: float64
53519 53526    22458.0
Name: new_cases, dtype: float64
53520 53527    17917.0
Name: new_cases, dtype: float64
53521 53528    15090.0
Name: new_cases, dtype: float64
53522 53529    13125.0
Name: new_cases, dtype: float64
53523 53530    0.0
Name: new_cases, dtype: float64
53524 53531    7321.0
Name: new_cases, dtype: float64
53525 53532    19696.0
Name: new_cases, dtype: float64
53526 53533    6590.0
Name: new_cases, dtype: float64
53527 53534    13631.0
Name: new_cases, dtype: float64
53528 53535    10377.0
Name: new_cases, dtype: float64
53529 53536    7370.0
Name: new_cases, dtype: float64
53530 53537    7067.0
Name: new_cases, dtype: float64
53531 53538    5381.0
Name: new_cases, dtype: float64
53532 53539    7576.0
Name: new_cases, dtype: float64
53533 53540    11881.0
Name: new_cases, dtype: float64
53534 53541    10727.0
Name: new_cases, dtype: float64
53535 53542    8096.0
Name: new_cases, dtype: float64
53536 53543    6419.0
Name: new_cases, dtype: float64
53537 53544    4643.0
Name: new_cases, dtype: float64
53538 53545    2328.0
Name: new_cases, dtype: float64
53539 53546    2578.0
Name: new_cases, dtype: float64
53540 53547    4473.0
Name: new_cases, dtype: float64
53541 53548    6949.0
Name: new_cases, dtype: float64
53542 53549    6169.0
Name: new_cases, dtype: float64
53543 53550    4513.0
Name: new_cases, dtype: float64
53544 53551    3043.0
Name: new_cases, dtype: float64
53545 53552    2206.0
Name: new_cases, dtype: float64
53546 53553    2987.0
Name: new_cases, dtype: float64
53547 53554    5096.0
Name: new_cases, dtype: float64
53548 53555    3688.0
Name: new_cases, dtype: float64
53549 53556    2993.0
Name: new_cases, dtype: float64
53550 53557    2249.0
Name: new_cases, dtype: float64
53551 53558    1964.0
Name: new_cases, dtype: float64
53552 53559    1444.0
Name: new_cases, dtype: float64
53553 53560    2253.0
Name: new_cases, dtype: float64
53554 53561    3275.0
Name: new_cases, dtype: float64
53555 53562    2747.0
Name: new_cases, dtype: float64
53556 53563    2194.0
Name: new_cases, dtype: float64
53557 53564    1484.0
Name: new_cases, dtype: float64
53558 53565    1000.0
Name: new_cases, dtype: float64
53559 53566    873.0
Name: new_cases, dtype: float64
53560 53567    1160.0
Name: new_cases, dtype: float64
53561 53568    1439.0
Name: new_cases, dtype: float64
53562 53569    901.0
Name: new_cases, dtype: float64
53563 53570    933.0
Name: new_cases, dtype: float64
53564 53571    996.0
Name: new_cases, dtype: float64
53565 53572    529.0
Name: new_cases, dtype: float64
53566 53573    493.0
Name: new_cases, dtype: float64
53567 53574    685.0
Name: new_cases, dtype: float64
53568 53575    1135.0
Name: new_cases, dtype: float64
53569 53576    475.0
Name: new_cases, dtype: float64
53570 53577    751.0
Name: new_cases, dtype: float64
53571 53578    488.0
Name: new_cases, dtype: float64
53572 53579    336.0
Name: new_cases, dtype: float64
53573 53580    341.0
Name: new_cases, dtype: float64
53574 53581    569.0
Name: new_cases, dtype: float64
53575 53582    806.0
Name: new_cases, dtype: float64
53576 53583    754.0
Name: new_cases, dtype: float64
53577 53584    671.0
Name: new_cases, dtype: float64
53578 53585    429.0
Name: new_cases, dtype: float64
53579 53586    411.0
Name: new_cases, dtype: float64
53580 53587    392.0
Name: new_cases, dtype: float64
53581 53588    713.0
Name: new_cases, dtype: float64
53582 53589    992.0
Name: new_cases, dtype: float64
53583 53590    903.0
Name: new_cases, dtype: float64
53584 53591    885.0
Name: new_cases, dtype: float64
53585 53592    809.0
Name: new_cases, dtype: float64
53586 53593    568.0
Name: new_cases, dtype: float64
53587 53594    553.0
Name: new_cases, dtype: float64
53588 53595    1027.0
Name: new_cases, dtype: float64
53589 53596    1623.0
Name: new_cases, dtype: float64
53590 53597    1444.0
Name: new_cases, dtype: float64
53591 53598    1565.0
Name: new_cases, dtype: float64
53592 53599    1309.0
Name: new_cases, dtype: float64
53593 53600    983.0
Name: new_cases, dtype: float64
53594 53601    984.0
Name: new_cases, dtype: float64
53595 53602    1626.0
Name: new_cases, dtype: float64
53596 53603    1651.0
Name: new_cases, dtype: float64
53597 53604    1928.0
Name: new_cases, dtype: float64
53598 53605    1866.0
Name: new_cases, dtype: float64
53599 53606    1578.0
Name: new_cases, dtype: float64
53600 53607    1149.0
Name: new_cases, dtype: float64
53601 53608    1423.0
Name: new_cases, dtype: float64
53602 53609    2060.0
Name: new_cases, dtype: float64
53603 53610    3051.0
Name: new_cases, dtype: float64
53604 53611    2774.0
Name: new_cases, dtype: float64
53605 53612    2592.0
Name: new_cases, dtype: float64
53606 53613    1806.0
Name: new_cases, dtype: float64
53607 53614    1553.0
Name: new_cases, dtype: float64
53608 53615    1520.0
Name: new_cases, dtype: float64
53609 53616    2547.0
Name: new_cases, dtype: float64
53610 53617    3659.0
Name: new_cases, dtype: float64
53611 53618    3457.0
Name: new_cases, dtype: float64
53612 53619    3388.0
Name: new_cases, dtype: float64
53613 53620    2761.0
Name: new_cases, dtype: float64
53614 53621    2240.0
Name: new_cases, dtype: float64
53615 53622    2220.0
Name: new_cases, dtype: float64
53616 53623    3282.0
Name: new_cases, dtype: float64
53617 53624    5487.0
Name: new_cases, dtype: float64
53618 53625    5497.0
Name: new_cases, dtype: float64
53619 53626    5536.0
Name: new_cases, dtype: float64
53620 53627    4675.0
Name: new_cases, dtype: float64
53621 53628    3732.0
Name: new_cases, dtype: float64
53622 53629    3549.0
Name: new_cases, dtype: float64
53623 53630    5391.0
Name: new_cases, dtype: float64
53624 53631    9008.0
Name: new_cases, dtype: float64
53625 53632    8303.0
Name: new_cases, dtype: float64
53626 53633    8966.0
Name: new_cases, dtype: float64
53627 53634    6600.0
Name: new_cases, dtype: float64
53628 53635    5946.0
Name: new_cases, dtype: float64
53629 53636    5592.0
Name: new_cases, dtype: float64
53630 53637    16654.0
Name: new_cases, dtype: float64
53631 53638    13275.0
Name: new_cases, dtype: float64
53632 53639    11688.0
Name: new_cases, dtype: float64
53633 53640    1940.0
Name: new_cases, dtype: float64
53634 53641    8395.0
Name: new_cases, dtype: float64
53635 53642    6627.0
Name: new_cases, dtype: float64
53636 53643    6823.0
Name: new_cases, dtype: float64
53637 53644    18646.0
Name: new_cases, dtype: float64
53638 53645    14158.0
Name: new_cases, dtype: float64
53639 53646    13950.0
Name: new_cases, dtype: float64
53640 53647    2899.0
Name: new_cases, dtype: float64
53641 53648    8944.0
Name: new_cases, dtype: float64
53642 53649    8176.0
Name: new_cases, dtype: float64
53643 53650    6779.0
Name: new_cases, dtype: float64
53644 53651    19080.0
Name: new_cases, dtype: float64
53645 53652    5110.0
Name: new_cases, dtype: float64
53646 53653    23718.0
Name: new_cases, dtype: float64
53647 53654    3148.0
Name: new_cases, dtype: float64
53648 53655    8537.0
Name: new_cases, dtype: float64
53649 53656    6945.0
Name: new_cases, dtype: float64
53650 53657    6287.0
Name: new_cases, dtype: float64
53651 53658    8840.0
Name: new_cases, dtype: float64
53652 53659    13090.0
Name: new_cases, dtype: float64
53653 53660    11816.0
Name: new_cases, dtype: float64
53654 53661    9904.0
Name: new_cases, dtype: float64
53655 53662    7103.0
Name: new_cases, dtype: float64
53656 53663    5667.0
Name: new_cases, dtype: float64
53657 53664    5328.0
Name: new_cases, dtype: float64
53658 53665    7277.0
Name: new_cases, dtype: float64
53659 53666    10920.0
Name: new_cases, dtype: float64
53660 53667    10315.0
Name: new_cases, dtype: float64
53661 53668    8934.0
Name: new_cases, dtype: float64
53662 53669    6423.0
Name: new_cases, dtype: float64
53663 53670    5271.0
Name: new_cases, dtype: float64
53664 53671    4798.0
Name: new_cases, dtype: float64
53665 53672    7409.0
Name: new_cases, dtype: float64
53666 53673    12267.0
Name: new_cases, dtype: float64
53667 53674    10999.0
Name: new_cases, dtype: float64
53668 53675    9288.0
Name: new_cases, dtype: float64
53669 53676    6482.0
Name: new_cases, dtype: float64
53670 53677    4951.0
Name: new_cases, dtype: float64
53671 53678    4507.0
Name: new_cases, dtype: float64
53672 53679    7763.0
Name: new_cases, dtype: float64
53673 53680    11636.0
Name: new_cases, dtype: float64

53674 53681    11476.0
Name: new_cases, dtype: float64
53675 53682    9758.0
Name: new_cases, dtype: float64
53676 53683    6894.0
Name: new_cases, dtype: float64
53677 53684    5909.0
Name: new_cases, dtype: float64
53678 53685    4909.0
Name: new_cases, dtype: float64
53679 53686    7928.0
Name: new_cases, dtype: float64
53680 53687    12317.0
Name: new_cases, dtype: float64
53681 53688    11578.0
Name: new_cases, dtype: float64
53682 53689    11664.0
Name: new_cases, dtype: float64
53683 53690    8420.0
Name: new_cases, dtype: float64
53684 53691    6766.0
Name: new_cases, dtype: float64
53685 53692    6562.0
Name: new_cases, dtype: float64
53686 53693    22340.0
Name: new_cases, dtype: float64
53687 53694    18802.0
Name: new_cases, dtype: float64
53688 53695    17508.0
Name: new_cases, dtype: float64
53689 53696    15093.0
Name: new_cases, dtype: float64
53690 53697    3849.0
Name: new_cases, dtype: float64
53691 53698    9905.0
Name: new_cases, dtype: float64
53692 53699    9359.0
Name: new_cases, dtype: float64
53693 53700    31402.0
Name: new_cases, dtype: float64
53694 53701    28826.0
Name: new_cases, dtype: float64
53695 53702    8079.0
Name: new_cases, dtype: float64
53696 53703    37520.0
Name: new_cases, dtype: float64
53697 53704    17248.0
Name: new_cases, dtype: float64
53698 53705   -554.0
Name: new_cases, dtype: float64
53699 53706    11315.0
Name: new_cases, dtype: float64
53700 53707    30691.0
Name: new_cases, dtype: float64
53701 53708    34498.0
Name: new_cases, dtype: float64
53702 53709    37640.0
Name: new_cases, dtype: float64
53703 53710    33785.0
Name: new_cases, dtype: float64
53704 53711    23788.0
Name: new_cases, dtype: float64
53705 53712    12788.0
Name: new_cases, dtype: float64
53706 53713    23714.0
Name: new_cases, dtype: float64
53707 53714    41286.0
Name: new_cases, dtype: float64
53708 53715    51077.0
Name: new_cases, dtype: float64
53709 53716    48834.0
Name: new_cases, dtype: float64
53710 53717    45356.0
Name: new_cases, dtype: float64
53711 53718    34309.0
Name: new_cases, dtype: float64
53712 53719    19203.0
Name: new_cases, dtype: float64
53713 53720    34958.0
Name: new_cases, dtype: float64
53714 53721    53627.0
Name: new_cases, dtype: float64
53715 53722    68366.0
Name: new_cases, dtype: float64
53716 53723    58768.0
Name: new_cases, dtype: float64
53717 53724    57302.0
Name: new_cases, dtype: float64
53718 53725    45183.0
Name: new_cases, dtype: float64
53719 53726    26241.0
Name: new_cases, dtype: float64
53720 53727    47887.0
Name: new_cases, dtype: float64
53721 53728    68049.0
Name: new_cases, dtype: float64
53722 53729    79051.0
Name: new_cases, dtype: float64
53723 53730    74579.0
Name: new_cases, dtype: float64
53724 53731    65584.0
Name: new_cases, dtype: float64
53725 53732    44977.0
Name: new_cases, dtype: float64
53726 53733    23325.0
Name: new_cases, dtype: float64
53727 53734    50745.0
Name: new_cases, dtype: float64
53728 53735    68680.0
Name: new_cases, dtype: float64
53729 53736    75456.0
Name: new_cases, dtype: float64
53730 53737    73279.0
Name: new_cases, dtype: float64
53731 53738    62193.0
Name: new_cases, dtype: float64
53732 53739    43500.0
Name: new_cases, dtype: float64
53733 53740    22945.0
Name: new_cases, dtype: float64
53734 53741    18322.0
Name: new_cases, dtype: float64
53735 53742    93087.0
Name: new_cases, dtype: float64
53736 53743    27482.0
Name: new_cases, dtype: float64
53737 53744    103018.0
Name: new_cases, dtype: float64
53738 53745    53296.0
Name: new_cases, dtype: float64
53739 53746    32752.0
Name: new_cases, dtype: float64
53740 53747    17116.0
Name: new_cases, dtype: float64
53741 53748    35423.0
Name: new_cases, dtype: float64
53742 53749    52233.0
Name: new_cases, dtype: float64
53743 53750    56902.0
Name: new_cases, dtype: float64
53744 53751    51400.0
Name: new_cases, dtype: float64
53745 53752    15716.0
Name: new_cases, dtype: float64
53746 53753    55603.0
Name: new_cases, dtype: float64
53747 53754   -541.0
Name: new_cases, dtype: float64
53748 53755    21742.0
Name: new_cases, dtype: float64
53749 53756    64949.0
Name: new_cases, dtype: float64
53750 53757    44313.0
Name: new_cases, dtype: float64
53751 53758    34420.0
Name: new_cases, dtype: float64
53752 53759    4068.0
Name: new_cases, dtype: float64
53753 53760    17238.0
Name: new_cases, dtype: float64
53754 53761    10172.0
Name: new_cases, dtype: float64
53755 53762    18750.0
Name: new_cases, dtype: float64
53756 53763    30998.0
Name: new_cases, dtype: float64
53757 53764    69956.0
Name: new_cases, dtype: float64
53758 53765    42070.0
Name: new_cases, dtype: float64
53759 53766    21764.0
Name: new_cases, dtype: float64
53760 53767    2968.0
Name: new_cases, dtype: float64
53761 53768    12636.0
Name: new_cases, dtype: float64
53762 53769    50013.0
Name: new_cases, dtype: float64
53763 53770    61905.0
Name: new_cases, dtype: float64
53764 53771    67337.0
Name: new_cases, dtype: float64
53765 53772    59110.0
Name: new_cases, dtype: float64
53766 53773    52621.0
Name: new_cases, dtype: float64
53767 53774    32128.0
Name: new_cases, dtype: float64
53768 53092    10.0
Name: new_cases, dtype: float64
53769 53093    19.0
Name: new_cases, dtype: float64
53770 53094    2.0
Name: new_cases, dtype: float64
53771 53095    31.0
Name: new_cases, dtype: float64
53772 53096    51.0
Name: new_cases, dtype: float64
53773 53097    29.0
Name: new_cases, dtype: float64
53774 53098    37.0
Name: new_cases, dtype: float64
55120 55127    2.0
Name: new_cases, dtype: float64
55121 55128    22.0
Name: new_cases, dtype: float64
55122 55129    14.0
Name: new_cases, dtype: float64
55123 55130    1.0
Name: new_cases, dtype: float64
55124 55131    27.0
Name: new_cases, dtype: float64
55125 55132    0.0
Name: new_cases, dtype: float64
55126 55133    16.0
Name: new_cases, dtype: float64
55127 55134    10.0
Name: new_cases, dtype: float64
55128 55135    0.0
Name: new_cases, dtype: float64
55129 55136    91.0
Name: new_cases, dtype: float64
55130 55137    38.0
Name: new_cases, dtype: float64
55131 55138    103.0
Name: new_cases, dtype: float64
55132 55139    0.0
Name: new_cases, dtype: float64
55133 55140    56.0
Name: new_cases, dtype: float64
55134 55141    31.0
Name: new_cases, dtype: float64
55135 55142    0.0
Name: new_cases, dtype: float64
55136 55143    77.0
Name: new_cases, dtype: float64
55137 55144    35.0
Name: new_cases, dtype: float64
55138 55145    94.0
Name: new_cases, dtype: float64
55139 55146    71.0
Name: new_cases, dtype: float64
55140 55147    48.0
Name: new_cases, dtype: float64
55141 55148    92.0
Name: new_cases, dtype: float64
55142 55149    0.0
Name: new_cases, dtype: float64
55143 55150    0.0
Name: new_cases, dtype: float64
55144 55151    0.0
Name: new_cases, dtype: float64
55145 55152    321.0
Name: new_cases, dtype: float64
55146 55153    0.0
Name: new_cases, dtype: float64
55147 55154    0.0
Name: new_cases, dtype: float64
55148 55155    0.0
Name: new_cases, dtype: float64
55149 55156    0.0
Name: new_cases, dtype: float64
55150 55157    457.0
Name: new_cases, dtype: float64
55151 55158    60.0
Name: new_cases, dtype: float64
55152 55159    62.0
Name: new_cases, dtype: float64
55153 55160    20.0
Name: new_cases, dtype: float64
55154 55161    77.0
Name: new_cases, dtype: float64
55155 55162    52.0
Name: new_cases, dtype: float64
55156 55163    71.0
Name: new_cases, dtype: float64
55157 55164    54.0
Name: new_cases, dtype: float64
55158 55165    72.0
Name: new_cases, dtype: float64
55159 55166    0.0
Name: new_cases, dtype: float64
55160 55167    64.0
Name: new_cases, dtype: float64
55161 55168    25.0
Name: new_cases, dtype: float64
55162 55169    22.0
Name: new_cases, dtype: float64
55163 55170    15.0
Name: new_cases, dtype: float64
55164 55171    17.0
Name: new_cases, dtype: float64
55165 55172    11.0
Name: new_cases, dtype: float64
55166 55173    10.0
Name: new_cases, dtype: float64
55167 55174    0.0
Name: new_cases, dtype: float64
55168 55175    156.0
Name: new_cases, dtype: float64
55169 55176    7.0
Name: new_cases, dtype: float64
55170 55177    55.0
Name: new_cases, dtype: float64
55171 55178    27.0
Name: new_cases, dtype: float64
55172 55179    16.0
Name: new_cases, dtype: float64

55173 55180    11.0
Name: new_cases, dtype: float64
55174 55181    17.0
Name: new_cases, dtype: float64
55175 55182    32.0
Name: new_cases, dtype: float64
55176 55183    10.0
Name: new_cases, dtype: float64
55177 55184    15.0
Name: new_cases, dtype: float64
55178 55185    21.0
Name: new_cases, dtype: float64
55179 55186    8.0
Name: new_cases, dtype: float64
55180 55187    6.0
Name: new_cases, dtype: float64
55181 55188    6.0
Name: new_cases, dtype: float64
55182 55189    10.0
Name: new_cases, dtype: float64
55183 55190    21.0
Name: new_cases, dtype: float64
55184 55191    15.0
Name: new_cases, dtype: float64
55185 55192    13.0
Name: new_cases, dtype: float64
55186 55193    19.0
Name: new_cases, dtype: float64
55187 55194    6.0
Name: new_cases, dtype: float64
55188 55195    10.0
Name: new_cases, dtype: float64
55189 55196    18.0
Name: new_cases, dtype: float64
55190 55197    16.0
Name: new_cases, dtype: float64
55191 55198    10.0
Name: new_cases, dtype: float64
55192 55199    40.0
Name: new_cases, dtype: float64
55193 55200    9.0
Name: new_cases, dtype: float64
55194 55201    15.0
Name: new_cases, dtype: float64
55195 55202    2.0
Name: new_cases, dtype: float64
55196 55203    4.0
Name: new_cases, dtype: float64
55197 55204    10.0
Name: new_cases, dtype: float64
55198 55205    3.0
Name: new_cases, dtype: float64
55199 55206    20.0
Name: new_cases, dtype: float64
55200 55207    3.0
Name: new_cases, dtype: float64
55201 55208    2.0
Name: new_cases, dtype: float64
55202 55209    4.0
Name: new_cases, dtype: float64
55203 55210    7.0
Name: new_cases, dtype: float64
55204 55211    14.0
Name: new_cases, dtype: float64
55205 55212    3.0
Name: new_cases, dtype: float64
55206 55213    3.0
Name: new_cases, dtype: float64
55207 55214    6.0
Name: new_cases, dtype: float64
55208 55215    2.0
Name: new_cases, dtype: float64
55209 55216    1.0
Name: new_cases, dtype: float64
55210 55217    19.0
Name: new_cases, dtype: float64
55211 55218    15.0
Name: new_cases, dtype: float64
55212 55219    0.0
Name: new_cases, dtype: float64
55213 55220    97.0
Name: new_cases, dtype: float64
55214 55221    0.0
Name: new_cases, dtype: float64
55215 55222    0.0
Name: new_cases, dtype: float64
55216 55223    0.0
Name: new_cases, dtype: float64
55217 55224    9.0
Name: new_cases, dtype: float64
55218 55225    10.0
Name: new_cases, dtype: float64
55219 55226    20.0
Name: new_cases, dtype: float64
55220 55227    20.0
Name: new_cases, dtype: float64
55221 55228    4.0
Name: new_cases, dtype: float64
55222 55229    9.0
Name: new_cases, dtype: float64
55223 55230    13.0
Name: new_cases, dtype: float64
55224 55231    14.0
Name: new_cases, dtype: float64
55225 55232    55.0
Name: new_cases, dtype: float64
55226 55233    24.0
Name: new_cases, dtype: float64
55227 55234    10.0
Name: new_cases, dtype: float64
55228 55235    19.0
Name: new_cases, dtype: float64
55229 55236    10.0
Name: new_cases, dtype: float64
55230 55237    21.0
Name: new_cases, dtype: float64
55231 55238    15.0
Name: new_cases, dtype: float64
55232 55239    8.0
Name: new_cases, dtype: float64
55233 55240    11.0
Name: new_cases, dtype: float64
55234 55241    22.0
Name: new_cases, dtype: float64
55235 55242    23.0
Name: new_cases, dtype: float64
55236 55243    10.0
Name: new_cases, dtype: float64
55237 55244    14.0
Name: new_cases, dtype: float64
55238 55245    19.0
Name: new_cases, dtype: float64
55239 55246    23.0
Name: new_cases, dtype: float64
55240 55247    26.0
Name: new_cases, dtype: float64
55241 55248    28.0
Name: new_cases, dtype: float64
55242 55249    25.0
Name: new_cases, dtype: float64
55243 55250    8.0
Name: new_cases, dtype: float64
55244 55251    43.0
Name: new_cases, dtype: float64
55245 55252    27.0
Name: new_cases, dtype: float64
55246 55253    33.0
Name: new_cases, dtype: float64
55247 55254    50.0
Name: new_cases, dtype: float64
55248 55255    60.0
Name: new_cases, dtype: float64
55249 55256    40.0
Name: new_cases, dtype: float64
55250 55257    31.0
Name: new_cases, dtype: float64
55251 55258    23.0
Name: new_cases, dtype: float64
55252 55259    57.0
Name: new_cases, dtype: float64
55253 55260    27.0
Name: new_cases, dtype: float64
55254 55261    29.0
Name: new_cases, dtype: float64
55255 55262    25.0
Name: new_cases, dtype: float64
55256 55263    19.0
Name: new_cases, dtype: float64
55257 55264    24.0
Name: new_cases, dtype: float64
55258 55265    5.0
Name: new_cases, dtype: float64
55259 55266    36.0
Name: new_cases, dtype: float64
55260 55267    29.0
Name: new_cases, dtype: float64
55261 55268    33.0
Name: new_cases, dtype: float64
55262 55269    25.0
Name: new_cases, dtype: float64
55263 55270    31.0
Name: new_cases, dtype: float64
55264 55271    27.0
Name: new_cases, dtype: float64
55265 55272    34.0
Name: new_cases, dtype: float64
55266 55273    52.0
Name: new_cases, dtype: float64
55267 55274    57.0
Name: new_cases, dtype: float64
55268 55275    65.0
Name: new_cases, dtype: float64
55269 55276    76.0
Name: new_cases, dtype: float64
55270 55277    110.0
Name: new_cases, dtype: float64
55271 55278    75.0
Name: new_cases, dtype: float64
55272 55279    75.0
Name: new_cases, dtype: float64
55273 55280    118.0
Name: new_cases, dtype: float64
55274 55281    118.0
Name: new_cases, dtype: float64
55275 55282    150.0
Name: new_cases, dtype: float64
55276 55283    147.0
Name: new_cases, dtype: float64
55277 55284    151.0
Name: new_cases, dtype: float64
55278 55285    202.0
Name: new_cases, dtype: float64
55279 55286    126.0
Name: new_cases, dtype: float64
55280 55287    193.0
Name: new_cases, dtype: float64
55281 55288    235.0
Name: new_cases, dtype: float64
55282 55289    204.0
Name: new_cases, dtype: float64
55283 55290    251.0
Name: new_cases, dtype: float64
55284 55291    226.0
Name: new_cases, dtype: float64
55285 55292    217.0
Name: new_cases, dtype: float64
55286 55293    147.0
Name: new_cases, dtype: float64
55287 55294    250.0
Name: new_cases, dtype: float64
55288 55295    212.0
Name: new_cases, dtype: float64
55289 55296    250.0
Name: new_cases, dtype: float64
55290 55297    204.0
Name: new_cases, dtype: float64
55291 55298    243.0
Name: new_cases, dtype: float64
55292 55299    283.0
Name: new_cases, dtype: float64
55293 55300    155.0
Name: new_cases, dtype: float64
55294 55301    168.0
Name: new_cases, dtype: float64
55295 55302    0.0
Name: new_cases, dtype: float64
55296 55303    544.0
Name: new_cases, dtype: float64
55297 55304    269.0
Name: new_cases, dtype: float64
55298 55305    177.0
Name: new_cases, dtype: float64
55299 55306    157.0
Name: new_cases, dtype: float64
55300 55307    183.0
Name: new_cases, dtype: float64
55301 55308    207.0
Name: new_cases, dtype: float64
55302 55309    233.0
Name: new_cases, dtype: float64
55303 55310    241.0
Name: new_cases, dtype: float64
55304 55311    202.0
Name: new_cases, dtype: float64
55305 55312    186.0
Name: new_cases, dtype: float64
55306 55313    138.0
Name: new_cases, dtype: float64
55307 55314    139.0
Name: new_cases, dtype: float64
55308 55315    169.0
Name: new_cases, dtype: float64
55309 55316    248.0
Name: new_cases, dtype: float64
55310 55317    372.0
Name: new_cases, dtype: float64
55311 55318    282.0
Name: new_cases, dtype: float64
55312 55319    302.0
Name: new_cases, dtype: float64
55313 55320    204.0
Name: new_cases, dtype: float64
55314 55321    180.0
Name: new_cases, dtype: float64
55315 55322    310.0
Name: new_cases, dtype: float64
55316 55323    311.0
Name: new_cases, dtype: float64
55317 55324    359.0
Name: new_cases, dtype: float64
55318 55325    338.0
Name: new_cases, dtype: float64
55319 55326    240.0
Name: new_cases, dtype: float64
55320 55327    164.0
Name: new_cases, dtype: float64
55321 55328    453.0
Name: new_cases, dtype: float64
55322 55329    333.0
Name: new_cases, dtype: float64
55323 55330    358.0
Name: new_cases, dtype: float64
55324 55331    341.0
Name: new_cases, dtype: float64
55325 55332    286.0
Name: new_cases, dtype: float64
55326 55333    315.0
Name: new_cases, dtype: float64
55327 55334    216.0
Name: new_cases, dtype: float64
55328 55335    263.0
Name: new_cases, dtype: float64
55329 55336    416.0
Name: new_cases, dtype: float64
55330 55337    352.0
Name: new_cases, dtype: float64
55331 55338    411.0
Name: new_cases, dtype: float64
55332 55339    460.0
Name: new_cases, dtype: float64
55333 55340    267.0
Name: new_cases, dtype: float64

55334 55341    229.0
Name: new_cases, dtype: float64
55335 55342    300.0
Name: new_cases, dtype: float64
55336 55343    399.0
Name: new_cases, dtype: float64
55337 55344    406.0
Name: new_cases, dtype: float64
55338 55345    434.0
Name: new_cases, dtype: float64
55339 55346    391.0
Name: new_cases, dtype: float64
55340 55347    306.0
Name: new_cases, dtype: float64
55341 55348    280.0
Name: new_cases, dtype: float64
55342 55349    294.0
Name: new_cases, dtype: float64
55343 55350    408.0
Name: new_cases, dtype: float64
55344 55351    435.0
Name: new_cases, dtype: float64
55345 55352    452.0
Name: new_cases, dtype: float64
55346 55353    503.0
Name: new_cases, dtype: float64
55347 55354    482.0
Name: new_cases, dtype: float64
55348 55355    438.0
Name: new_cases, dtype: float64
55349 55356    432.0
Name: new_cases, dtype: float64
55350 55357    667.0
Name: new_cases, dtype: float64
55351 55358    865.0
Name: new_cases, dtype: float64
55352 55359    882.0
Name: new_cases, dtype: float64
55353 55360    841.0
Name: new_cases, dtype: float64
55354 55361    935.0
Name: new_cases, dtype: float64
55355 55362    790.0
Name: new_cases, dtype: float64
55356 55363    714.0
Name: new_cases, dtype: float64
55357 55364    1256.0
Name: new_cases, dtype: float64
55358 55365    1547.0
Name: new_cases, dtype: float64
55359 55366    1211.0
Name: new_cases, dtype: float64
55360 55367    1686.0
Name: new_cases, dtype: float64
55361 55368    2055.0
Name: new_cases, dtype: float64
55362 55369    1678.0
Name: new_cases, dtype: float64
55363 55370    1151.0
Name: new_cases, dtype: float64
55364 55371    2166.0
Name: new_cases, dtype: float64
55365 55372    2646.0
Name: new_cases, dtype: float64
55366 55373    2915.0
Name: new_cases, dtype: float64
55367 55374    2447.0
Name: new_cases, dtype: float64
55368 55375    2555.0
Name: new_cases, dtype: float64
55369 55376    1889.0
Name: new_cases, dtype: float64
55370 55377    1489.0
Name: new_cases, dtype: float64
55371 55378    2383.0
Name: new_cases, dtype: float64
55372 55379    2751.0
Name: new_cases, dtype: float64
55373 55380    3316.0
Name: new_cases, dtype: float64
55374 55381    3038.0
Name: new_cases, dtype: float64
55375 55382    2835.0
Name: new_cases, dtype: float64
55376 55383    1695.0
Name: new_cases, dtype: float64
55377 55384    2198.0
Name: new_cases, dtype: float64
55378 55385    2422.0
Name: new_cases, dtype: float64
55379 55386    3209.0
Name: new_cases, dtype: float64
55380 55387    3227.0
Name: new_cases, dtype: float64
55381 55388    2551.0
Name: new_cases, dtype: float64
55382 55389    2309.0
Name: new_cases, dtype: float64
55383 55390    1498.0
Name: new_cases, dtype: float64
55384 55391    1387.0
Name: new_cases, dtype: float64
55385 55392    2131.0
Name: new_cases, dtype: float64
55386 55393    2151.0
Name: new_cases, dtype: float64
55387 55394    2018.0
Name: new_cases, dtype: float64
55388 55395    1981.0
Name: new_cases, dtype: float64
55389 55396    1747.0
Name: new_cases, dtype: float64
55390 55397    1193.0
Name: new_cases, dtype: float64
55391 55398    1044.0
Name: new_cases, dtype: float64
55392 55399    2199.0
Name: new_cases, dtype: float64
55393 55400    2185.0
Name: new_cases, dtype: float64
55394 55401    1882.0
Name: new_cases, dtype: float64
55395 55402    1648.0
Name: new_cases, dtype: float64
55396 55403    1383.0
Name: new_cases, dtype: float64
55397 55404    903.0
Name: new_cases, dtype: float64
55398 55405    1250.0
Name: new_cases, dtype: float64
55399 55406    1324.0
Name: new_cases, dtype: float64
55400 55407    1675.0
Name: new_cases, dtype: float64
55401 55408    1533.0
Name: new_cases, dtype: float64
55402 55409    1395.0
Name: new_cases, dtype: float64
55403 55410    1194.0
Name: new_cases, dtype: float64
55404 55411    692.0
Name: new_cases, dtype: float64
55405 55412    639.0
Name: new_cases, dtype: float64
55406 55413    1199.0
Name: new_cases, dtype: float64
55407 55414    1185.0
Name: new_cases, dtype: float64
55408 55415    1153.0
Name: new_cases, dtype: float64
55409 55416    874.0
Name: new_cases, dtype: float64
55410 55417    901.0
Name: new_cases, dtype: float64
55411 55418    587.0
Name: new_cases, dtype: float64
55412 55419    525.0
Name: new_cases, dtype: float64
55413 55420    833.0
Name: new_cases, dtype: float64
55414 55421    935.0
Name: new_cases, dtype: float64
55415 55422    870.0
Name: new_cases, dtype: float64
55416 55423    617.0
Name: new_cases, dtype: float64
55417 55424    262.0
Name: new_cases, dtype: float64
55418 55425    342.0
Name: new_cases, dtype: float64
55419 55426    475.0
Name: new_cases, dtype: float64
55420 55427    1045.0
Name: new_cases, dtype: float64
55421 55428    942.0
Name: new_cases, dtype: float64
55422 55429    932.0
Name: new_cases, dtype: float64
55423 55430    597.0
Name: new_cases, dtype: float64
55424 55431    262.0
Name: new_cases, dtype: float64
55425 55432    390.0
Name: new_cases, dtype: float64
55426 55433    427.0
Name: new_cases, dtype: float64
55427 55434    927.0
Name: new_cases, dtype: float64
55428 55435    814.0
Name: new_cases, dtype: float64
55429 55436    510.0
Name: new_cases, dtype: float64
55430 55437    717.0
Name: new_cases, dtype: float64
55431 55438    799.0
Name: new_cases, dtype: float64
55432 55439    445.0
Name: new_cases, dtype: float64
55433 55440    441.0
Name: new_cases, dtype: float64
55434 55441    841.0
Name: new_cases, dtype: float64
55435 55442    668.0
Name: new_cases, dtype: float64
55436 55443    595.0
Name: new_cases, dtype: float64
55437 55444    577.0
Name: new_cases, dtype: float64
55438 55445    510.0
Name: new_cases, dtype: float64
55439 55446    237.0
Name: new_cases, dtype: float64
55440 55447    318.0
Name: new_cases, dtype: float64
55441 55448    537.0
Name: new_cases, dtype: float64
55442 55449    511.0
Name: new_cases, dtype: float64
55443 55450    506.0
Name: new_cases, dtype: float64
55444 55451    562.0
Name: new_cases, dtype: float64
55445 55452    605.0
Name: new_cases, dtype: float64
55446 55453    334.0
Name: new_cases, dtype: float64
55447 55454    432.0
Name: new_cases, dtype: float64
55448 55455    814.0
Name: new_cases, dtype: float64
55449 55456    857.0
Name: new_cases, dtype: float64
55450 55457    713.0
Name: new_cases, dtype: float64
55451 55458    882.0
Name: new_cases, dtype: float64
55452 55459    795.0
Name: new_cases, dtype: float64
55453 55460    484.0
Name: new_cases, dtype: float64
55454 55461    538.0
Name: new_cases, dtype: float64
55455 55462    1221.0
Name: new_cases, dtype: float64
55456 55463    1150.0
Name: new_cases, dtype: float64
55457 55464    1069.0
Name: new_cases, dtype: float64
55458 55465    1172.0
Name: new_cases, dtype: float64
55459 55466    1106.0
Name: new_cases, dtype: float64
55460 55467    733.0
Name: new_cases, dtype: float64
55461 55468    629.0
Name: new_cases, dtype: float64
55462 55469    1492.0
Name: new_cases, dtype: float64
55463 55470    1482.0
Name: new_cases, dtype: float64
55464 55471    1323.0
Name: new_cases, dtype: float64
55465 55472    1372.0
Name: new_cases, dtype: float64
55466 55473    1222.0
Name: new_cases, dtype: float64
55467 55474    662.0
Name: new_cases, dtype: float64
55468 55475    696.0
Name: new_cases, dtype: float64
55469 55476    1081.0
Name: new_cases, dtype: float64
55470 55477    754.0
Name: new_cases, dtype: float64
55471 55478    1400.0
Name: new_cases, dtype: float64
55472 55479    1435.0
Name: new_cases, dtype: float64
55473 55480    1424.0
Name: new_cases, dtype: float64
55474 55481    884.0
Name: new_cases, dtype: float64
55475 55482    870.0
Name: new_cases, dtype: float64
55476 55483    2111.0
Name: new_cases, dtype: float64
55477 55484    1903.0
Name: new_cases, dtype: float64
55478 55485    1783.0
Name: new_cases, dtype: float64
55479 55486    1732.0
Name: new_cases, dtype: float64
55480 55487    1630.0
Name: new_cases, dtype: float64
55481 55488    1269.0
Name: new_cases, dtype: float64
55482 55489    1170.0
Name: new_cases, dtype: float64
55483 55490    2312.0
Name: new_cases, dtype: float64
55484 55491    2697.0
Name: new_cases, dtype: float64
55485 55492    2217.0
Name: new_cases, dtype: float64
55486 55493    2181.0
Name: new_cases, dtype: float64
55487 55494    2301.0
Name: new_cases, dtype: float64
55488 55495    1142.0
Name: new_cases, dtype: float64
55489 55496    1161.0
Name: new_cases, dtype: float64
55490 55497    3181.0
Name: new_cases, dtype: float64
55491 55498    2629.0
Name: new_cases, dtype: float64
55492 55499    2570.0
Name: new_cases, dtype: float64
55493 55500    2357.0
Name: new_cases, dtype: float64
55494 55501    2503.0
Name: new_cases, dtype: float64
55495 55502    1626.0
Name: new_cases, dtype: float64
55496 55503    1134.0
Name: new_cases, dtype: float64

55497 55504    1508.0
Name: new_cases, dtype: float64
55498 55505    3458.0
Name: new_cases, dtype: float64
55499 55506    3070.0
Name: new_cases, dtype: float64
55500 55507    2762.0
Name: new_cases, dtype: float64
55501 55508    2532.0
Name: new_cases, dtype: float64
55502 55509    1514.0
Name: new_cases, dtype: float64
55503 55510    1705.0
Name: new_cases, dtype: float64
55504 55511    3517.0
Name: new_cases, dtype: float64
55505 55512    3058.0
Name: new_cases, dtype: float64
55506 55513    2587.0
Name: new_cases, dtype: float64
55507 55514    1466.0
Name: new_cases, dtype: float64
55508 55515    3132.0
Name: new_cases, dtype: float64
55509 55516    1441.0
Name: new_cases, dtype: float64
55510 55517    1724.0
Name: new_cases, dtype: float64
55511 55518    4322.0
Name: new_cases, dtype: float64
55512 55519    3612.0
Name: new_cases, dtype: float64
55513 55520    3483.0
Name: new_cases, dtype: float64
55514 55521    3058.0
Name: new_cases, dtype: float64
55515 55522    3229.0
Name: new_cases, dtype: float64
55516 55523    1955.0
Name: new_cases, dtype: float64
55517 55524    1863.0
Name: new_cases, dtype: float64
55518 55525    4293.0
Name: new_cases, dtype: float64
55519 55526    3445.0
Name: new_cases, dtype: float64
55520 55527    3215.0
Name: new_cases, dtype: float64
55521 55528    2734.0
Name: new_cases, dtype: float64
55522 55529    2799.0
Name: new_cases, dtype: float64
55523 55530    1717.0
Name: new_cases, dtype: float64
55524 55531    1606.0
Name: new_cases, dtype: float64
55525 55532    4017.0
Name: new_cases, dtype: float64
55526 55533    3081.0
Name: new_cases, dtype: float64
55527 55534    3822.0
Name: new_cases, dtype: float64
55528 55535    3027.0
Name: new_cases, dtype: float64
55529 55536    2411.0
Name: new_cases, dtype: float64
55530 55537    1829.0
Name: new_cases, dtype: float64
55531 55538    1606.0
Name: new_cases, dtype: float64
55532 55539    3750.0
Name: new_cases, dtype: float64
55533 55540    3010.0
Name: new_cases, dtype: float64
55534 55541    2756.0
Name: new_cases, dtype: float64
55535 55542    2739.0
Name: new_cases, dtype: float64
55536 55543    2596.0
Name: new_cases, dtype: float64
55537 55544    1399.0
Name: new_cases, dtype: float64
55538 55545    1307.0
Name: new_cases, dtype: float64
55539 55546    3287.0
Name: new_cases, dtype: float64
55540 55547    2770.0
Name: new_cases, dtype: float64
55541 55548    2415.0
Name: new_cases, dtype: float64
55542 55549    2125.0
Name: new_cases, dtype: float64
55543 55550    1389.0
Name: new_cases, dtype: float64
55544 55551    0.0
Name: new_cases, dtype: float64
55545 55552    2146.0
Name: new_cases, dtype: float64
55546 55553    1368.0
Name: new_cases, dtype: float64
55547 55554    2091.0
Name: new_cases, dtype: float64
55548 55555    3418.0
Name: new_cases, dtype: float64
55549 55556    2671.0
Name: new_cases, dtype: float64
55550 55557    2461.0
Name: new_cases, dtype: float64
55551 55558    1427.0
Name: new_cases, dtype: float64
55552 55559    1900.0
Name: new_cases, dtype: float64
55553 55560    3172.0
Name: new_cases, dtype: float64
55554 55561    2478.0
Name: new_cases, dtype: float64
55555 55562    2139.0
Name: new_cases, dtype: float64
55556 55563    2188.0
Name: new_cases, dtype: float64
55557 55564    1950.0
Name: new_cases, dtype: float64
55558 55565    1259.0
Name: new_cases, dtype: float64
55559 55566    1395.0
Name: new_cases, dtype: float64
55560 55567    2781.0
Name: new_cases, dtype: float64
55561 55568    2292.0
Name: new_cases, dtype: float64
55562 55569    1886.0
Name: new_cases, dtype: float64
55563 55570    1982.0
Name: new_cases, dtype: float64
55564 55571    1503.0
Name: new_cases, dtype: float64
55565 55572    875.0
Name: new_cases, dtype: float64
55566 55573    1377.0
Name: new_cases, dtype: float64
55567 55574    2402.0
Name: new_cases, dtype: float64
55568 55575    1511.0
Name: new_cases, dtype: float64
55569 55576    1876.0
Name: new_cases, dtype: float64
55570 55577    1928.0
Name: new_cases, dtype: float64
55571 55578    1497.0
Name: new_cases, dtype: float64
55572 55579    906.0
Name: new_cases, dtype: float64
55573 55580    1005.0
Name: new_cases, dtype: float64
55574 55581    1857.0
Name: new_cases, dtype: float64
55575 55582    1379.0
Name: new_cases, dtype: float64
55576 55583    1209.0
Name: new_cases, dtype: float64
55577 55584    1106.0
Name: new_cases, dtype: float64
55578 55585    932.0
Name: new_cases, dtype: float64
55579 55586    579.0
Name: new_cases, dtype: float64
55580 55587    798.0
Name: new_cases, dtype: float64
55581 55588    1368.0
Name: new_cases, dtype: float64
55582 55589    886.0
Name: new_cases, dtype: float64
55583 55590    750.0
Name: new_cases, dtype: float64
55584 55591    784.0
Name: new_cases, dtype: float64
55585 55592    682.0
Name: new_cases, dtype: float64
55586 55593    297.0
Name: new_cases, dtype: float64
55587 55594    468.0
Name: new_cases, dtype: float64
55588 55595    794.0
Name: new_cases, dtype: float64
55589 55596    546.0
Name: new_cases, dtype: float64
55590 55597    512.0
Name: new_cases, dtype: float64
55591 55598    453.0
Name: new_cases, dtype: float64
55592 55599    389.0
Name: new_cases, dtype: float64
55593 55600    247.0
Name: new_cases, dtype: float64
55594 55601    206.0
Name: new_cases, dtype: float64
55595 55602    395.0
Name: new_cases, dtype: float64
55596 55603    512.0
Name: new_cases, dtype: float64
55597 55604    454.0
Name: new_cases, dtype: float64
55598 55605    386.0
Name: new_cases, dtype: float64
55599 55606    375.0
Name: new_cases, dtype: float64
55600 55607    235.0
Name: new_cases, dtype: float64
55601 55608    361.0
Name: new_cases, dtype: float64
55602 55609    563.0
Name: new_cases, dtype: float64
55603 55610    627.0
Name: new_cases, dtype: float64
55604 55611    729.0
Name: new_cases, dtype: float64
55605 55612    980.0
Name: new_cases, dtype: float64
55606 55613    1182.0
Name: new_cases, dtype: float64
55607 55614    617.0
Name: new_cases, dtype: float64
55608 55615    999.0
Name: new_cases, dtype: float64
55609 55616    2181.0
Name: new_cases, dtype: float64
55610 55617    1816.0
Name: new_cases, dtype: float64
55611 55618    2061.0
Name: new_cases, dtype: float64
55612 55619    1997.0
Name: new_cases, dtype: float64
55613 55620    2327.0
Name: new_cases, dtype: float64
55614 55621    1464.0
Name: new_cases, dtype: float64
55615 55622    2063.0
Name: new_cases, dtype: float64
55616 55623    3911.0
Name: new_cases, dtype: float64
55617 55624    2935.0
Name: new_cases, dtype: float64
55618 55625    2794.0
Name: new_cases, dtype: float64
55619 55626    2688.0
Name: new_cases, dtype: float64
55620 55627    2554.0
Name: new_cases, dtype: float64
55621 55628    1558.0
Name: new_cases, dtype: float64
55622 55629    1834.0
Name: new_cases, dtype: float64
55623 55630    4327.0
Name: new_cases, dtype: float64
55624 55631    2968.0
Name: new_cases, dtype: float64
55625 55632    2601.0
Name: new_cases, dtype: float64
55626 55633    2852.0
Name: new_cases, dtype: float64
55627 55634    2472.0
Name: new_cases, dtype: float64
55628 55635    1553.0
Name: new_cases, dtype: float64
55629 55636    2056.0
Name: new_cases, dtype: float64
55630 55637    4170.0
Name: new_cases, dtype: float64
55631 55638    2870.0
Name: new_cases, dtype: float64
55632 55639    2694.0
Name: new_cases, dtype: float64
55633 55640    2843.0
Name: new_cases, dtype: float64
55634 55641    2752.0
Name: new_cases, dtype: float64
55635 55642    1603.0
Name: new_cases, dtype: float64
55636 55643    2154.0
Name: new_cases, dtype: float64
55637 55644    3969.0
Name: new_cases, dtype: float64
55638 55645    2855.0
Name: new_cases, dtype: float64
55639 55646    2787.0
Name: new_cases, dtype: float64
55640 55647    2924.0
Name: new_cases, dtype: float64
55641 55648    2746.0
Name: new_cases, dtype: float64
55642 55649    1850.0
Name: new_cases, dtype: float64
55643 55650    2593.0
Name: new_cases, dtype: float64
55644 55651    4614.0
Name: new_cases, dtype: float64
55645 55652    3472.0
Name: new_cases, dtype: float64
55646 55653    3603.0
Name: new_cases, dtype: float64
55647 55654    3493.0
Name: new_cases, dtype: float64
55648 55655    3270.0
Name: new_cases, dtype: float64
55649 55656    1888.0
Name: new_cases, dtype: float64
55650 55657    2212.0
Name: new_cases, dtype: float64
55651 55658    4412.0
Name: new_cases, dtype: float64
55652 55659    3437.0
Name: new_cases, dtype: float64
55653 55660    3273.0
Name: new_cases, dtype: float64
55654 55661    3596.0
Name: new_cases, dtype: float64

55655 55662    3184.0
Name: new_cases, dtype: float64
55656 55663    1947.0
Name: new_cases, dtype: float64
55657 55664    2626.0
Name: new_cases, dtype: float64
55658 55665    5000.0
Name: new_cases, dtype: float64
55659 55666    3265.0
Name: new_cases, dtype: float64
55660 55667    3528.0
Name: new_cases, dtype: float64
55661 55668    3067.0
Name: new_cases, dtype: float64
55662 55669    3062.0
Name: new_cases, dtype: float64
55663 55670    1581.0
Name: new_cases, dtype: float64
55664 55671    2343.0
Name: new_cases, dtype: float64
55665 55672    4306.0
Name: new_cases, dtype: float64
55666 55673    2868.0
Name: new_cases, dtype: float64
55667 55674    2836.0
Name: new_cases, dtype: float64
55668 55675    2715.0
Name: new_cases, dtype: float64
55669 55676    2284.0
Name: new_cases, dtype: float64
55670 55677    1284.0
Name: new_cases, dtype: float64
55671 55678    1765.0
Name: new_cases, dtype: float64
55672 55679    3442.0
Name: new_cases, dtype: float64
55673 55680    2198.0
Name: new_cases, dtype: float64
55674 55681    2163.0
Name: new_cases, dtype: float64
55675 55682    2129.0
Name: new_cases, dtype: float64
55676 55683    2190.0
Name: new_cases, dtype: float64
55677 55684    1319.0
Name: new_cases, dtype: float64
55678 55685    1608.0
Name: new_cases, dtype: float64
55679 55686    3590.0
Name: new_cases, dtype: float64
55680 55687    2406.0
Name: new_cases, dtype: float64
55681 55688    2322.0
Name: new_cases, dtype: float64
55682 55689    2231.0
Name: new_cases, dtype: float64
55683 55690    2184.0
Name: new_cases, dtype: float64
55684 55691    1286.0
Name: new_cases, dtype: float64
55685 55692    2124.0
Name: new_cases, dtype: float64
55686 55693    3688.0
Name: new_cases, dtype: float64
55687 55694    2325.0
Name: new_cases, dtype: float64
55688 55695    2101.0
Name: new_cases, dtype: float64
55689 55696    2033.0
Name: new_cases, dtype: float64
55690 55697    1814.0
Name: new_cases, dtype: float64
55691 55698    1100.0
Name: new_cases, dtype: float64
55692 55699    2122.0
Name: new_cases, dtype: float64
55693 55700    3287.0
Name: new_cases, dtype: float64
55694 55701    2157.0
Name: new_cases, dtype: float64
55695 55702    2232.0
Name: new_cases, dtype: float64
55696 55703    2601.0
Name: new_cases, dtype: float64
55697 55704    1798.0
Name: new_cases, dtype: float64
55698 55705    1142.0
Name: new_cases, dtype: float64
55699 55706    2125.0
Name: new_cases, dtype: float64
55700 55707    3084.0
Name: new_cases, dtype: float64
55701 55708    2294.0
Name: new_cases, dtype: float64
55702 55709    2229.0
Name: new_cases, dtype: float64
55703 55710    2277.0
Name: new_cases, dtype: float64
55704 55711    2162.0
Name: new_cases, dtype: float64
55705 55712    1320.0
Name: new_cases, dtype: float64
55706 55713    2358.0
Name: new_cases, dtype: float64
55707 55714    3237.0
Name: new_cases, dtype: float64
55708 55715    2312.0
Name: new_cases, dtype: float64
55709 55716    2572.0
Name: new_cases, dtype: float64
55710 55717    2618.0
Name: new_cases, dtype: float64
55711 55718    2301.0
Name: new_cases, dtype: float64
55712 55719    1689.0
Name: new_cases, dtype: float64
55713 55720    3147.0
Name: new_cases, dtype: float64
55714 55721    3926.0
Name: new_cases, dtype: float64
55715 55722    3252.0
Name: new_cases, dtype: float64
55716 55723    3376.0
Name: new_cases, dtype: float64
55717 55724    3541.0
Name: new_cases, dtype: float64
55718 55725    3155.0
Name: new_cases, dtype: float64
55719 55726    2075.0
Name: new_cases, dtype: float64
55720 55727    3937.0
Name: new_cases, dtype: float64
55721 55728    4276.0
Name: new_cases, dtype: float64
55722 55729    3639.0
Name: new_cases, dtype: float64
55723 55730    2957.0
Name: new_cases, dtype: float64
55724 55731    3611.0
Name: new_cases, dtype: float64
55725 55732    4670.0
Name: new_cases, dtype: float64
55726 55733    2722.0
Name: new_cases, dtype: float64
55727 55734    5425.0
Name: new_cases, dtype: float64
55728 55735    6856.0
Name: new_cases, dtype: float64
55729 55736    6141.0
Name: new_cases, dtype: float64
55730 55737    6784.0
Name: new_cases, dtype: float64
55731 55738    6889.0
Name: new_cases, dtype: float64
55732 55739    6356.0
Name: new_cases, dtype: float64
55733 55740    4283.0
Name: new_cases, dtype: float64
55734 55741    7335.0
Name: new_cases, dtype: float64
55735 55742    8969.0
Name: new_cases, dtype: float64
55736 55743    7089.0
Name: new_cases, dtype: float64
55737 55744    6771.0
Name: new_cases, dtype: float64
55738 55745    6832.0
Name: new_cases, dtype: float64
55739 55746    6132.0
Name: new_cases, dtype: float64
55740 55747    3842.0
Name: new_cases, dtype: float64
55741 55748    6950.0
Name: new_cases, dtype: float64
55742 55749    8364.0
Name: new_cases, dtype: float64
55743 55750    6653.0
Name: new_cases, dtype: float64
55744 55751    7276.0
Name: new_cases, dtype: float64
55745 55752    7751.0
Name: new_cases, dtype: float64
55746 55753    5944.0
Name: new_cases, dtype: float64
55747 55754    4108.0
Name: new_cases, dtype: float64
55748 55755    7287.0
Name: new_cases, dtype: float64
55749 55756    8348.0
Name: new_cases, dtype: float64
55750 55757    7106.0
Name: new_cases, dtype: float64
55751 55758    6561.0
Name: new_cases, dtype: float64
55752 55759    6602.0
Name: new_cases, dtype: float64
55753 55760    5859.0
Name: new_cases, dtype: float64
55754 55761    3823.0
Name: new_cases, dtype: float64
55755 55762    6677.0
Name: new_cases, dtype: float64
55756 55763    7720.0
Name: new_cases, dtype: float64
55757 55764    6192.0
Name: new_cases, dtype: float64
55758 55765    6256.0
Name: new_cases, dtype: float64
55759 55766    6201.0
Name: new_cases, dtype: float64
55760 55767    5143.0
Name: new_cases, dtype: float64
55761 55768    3526.0
Name: new_cases, dtype: float64
55762 55769    4927.0
Name: new_cases, dtype: float64
55763 55770    7254.0
Name: new_cases, dtype: float64
55764 55771    5899.0
Name: new_cases, dtype: float64
55765 55772    5513.0
Name: new_cases, dtype: float64
55766 55773    5087.0
Name: new_cases, dtype: float64
55767 55774    4751.0
Name: new_cases, dtype: float64
55768 55775    3225.0
Name: new_cases, dtype: float64
55769 55776    3829.0
Name: new_cases, dtype: float64
55770 55777    5953.0
Name: new_cases, dtype: float64
55771 55778    4786.0
Name: new_cases, dtype: float64
55772 55779    4696.0
Name: new_cases, dtype: float64
55773 55780    4761.0
Name: new_cases, dtype: float64
55774 55781    4337.0
Name: new_cases, dtype: float64
55775 55782    2831.0
Name: new_cases, dtype: float64
55776 55783    3689.0
Name: new_cases, dtype: float64
55777 55784    6542.0
Name: new_cases, dtype: float64
55778 55785    5635.0
Name: new_cases, dtype: float64
55779 55786    6647.0
Name: new_cases, dtype: float64
55780 55787    7660.0
Name: new_cases, dtype: float64
55781 55788    6590.0
Name: new_cases, dtype: float64
55782 55789    4036.0
Name: new_cases, dtype: float64
55783 55790    9284.0
Name: new_cases, dtype: float64
55784 55791    21732.0
Name: new_cases, dtype: float64
55785 55792    28828.0
Name: new_cases, dtype: float64
55786 55793    35580.0
Name: new_cases, dtype: float64
55787 55794    40560.0
Name: new_cases, dtype: float64
55788 55795    30009.0
Name: new_cases, dtype: float64
55789 55796    17633.0
Name: new_cases, dtype: float64
55790 55797    36246.0
Name: new_cases, dtype: float64
55791 55798    50182.0
Name: new_cases, dtype: float64
55792 55799    43386.0
Name: new_cases, dtype: float64
55793 55800    33711.0
Name: new_cases, dtype: float64
55794 55801    29334.0
Name: new_cases, dtype: float64
55795 55802    37670.0
Name: new_cases, dtype: float64
55796 55134    10.0
Name: new_cases, dtype: float64
55797 55135    0.0
Name: new_cases, dtype: float64
55798 55136    91.0
Name: new_cases, dtype: float64
55799 55137    38.0
Name: new_cases, dtype: float64
55800 55138    103.0
Name: new_cases, dtype: float64
55801 55139    0.0
Name: new_cases, dtype: float64
55802 55140    56.0
Name: new_cases, dtype: float64
61531 61538    1.0
Name: new_cases, dtype: float64
61532 61539    3.0
Name: new_cases, dtype: float64
61533 61540    12.0
Name: new_cases, dtype: float64
61534 61541    0.0
Name: new_cases, dtype: float64
61535 61542    2.0
Name: new_cases, dtype: float64
61536 61543    4.0
Name: new_cases, dtype: float64
61537 61544    0.0
Name: new_cases, dtype: float64
61538 61545    6.0
Name: new_cases, dtype: float64
61539 61546    16.0
Name: new_cases, dtype: float64
61540 61547    16.0
Name: new_cases, dtype: float64
61541 61548    27.0
Name: new_cases, dtype: float64
61542 61549    15.0
Name: new_cases, dtype: float64
61543 61550    29.0
Name: new_cases, dtype: float64
61544 61551    2.0
Name: new_cases, dtype: float64
61545 61552    31.0
Name: new_cases, dtype: float64

61546 61553    47.0
Name: new_cases, dtype: float64
61547 61554    3.0
Name: new_cases, dtype: float64
61548 61555    42.0
Name: new_cases, dtype: float64
61549 61556    4.0
Name: new_cases, dtype: float64
61550 61557    30.0
Name: new_cases, dtype: float64
61551 61558    7.0
Name: new_cases, dtype: float64
61552 61559    7.0
Name: new_cases, dtype: float64
61553 61560    31.0
Name: new_cases, dtype: float64
61554 61561    39.0
Name: new_cases, dtype: float64
61555 61562    10.0
Name: new_cases, dtype: float64
61556 61563    1.0
Name: new_cases, dtype: float64
61557 61564    4.0
Name: new_cases, dtype: float64
61558 61565    10.0
Name: new_cases, dtype: float64
61559 61566    12.0
Name: new_cases, dtype: float64
61560 61567    7.0
Name: new_cases, dtype: float64
61561 61568    16.0
Name: new_cases, dtype: float64
61562 61569    15.0
Name: new_cases, dtype: float64
61563 61570    15.0
Name: new_cases, dtype: float64
61564 61571    5.0
Name: new_cases, dtype: float64
61565 61572    17.0
Name: new_cases, dtype: float64
61566 61573    16.0
Name: new_cases, dtype: float64
61567 61574    9.0
Name: new_cases, dtype: float64
61568 61575    72.0
Name: new_cases, dtype: float64
61569 61576    36.0
Name: new_cases, dtype: float64
61570 61577    0.0
Name: new_cases, dtype: float64
61571 61578    34.0
Name: new_cases, dtype: float64
61572 61579    41.0
Name: new_cases, dtype: float64
61573 61580    36.0
Name: new_cases, dtype: float64
61574 61581    33.0
Name: new_cases, dtype: float64
61575 61582    33.0
Name: new_cases, dtype: float64
61576 61583    206.0
Name: new_cases, dtype: float64
61577 61584    45.0
Name: new_cases, dtype: float64
61578 61585    123.0
Name: new_cases, dtype: float64
61579 61586    92.0
Name: new_cases, dtype: float64
61580 61587    191.0
Name: new_cases, dtype: float64
61581 61588    224.0
Name: new_cases, dtype: float64
61582 61589    86.0
Name: new_cases, dtype: float64
61583 61590    59.0
Name: new_cases, dtype: float64
61584 61591    142.0
Name: new_cases, dtype: float64
61585 61592    128.0
Name: new_cases, dtype: float64
61586 61593   -20.0
Name: new_cases, dtype: float64
61587 61594    175.0
Name: new_cases, dtype: float64
61588 61595    63.0
Name: new_cases, dtype: float64
61589 61596    142.0
Name: new_cases, dtype: float64
61590 61597    105.0
Name: new_cases, dtype: float64
61591 61598    81.0
Name: new_cases, dtype: float64
61592 61599    152.0
Name: new_cases, dtype: float64
61593 61600    157.0
Name: new_cases, dtype: float64
61594 61601    0.0
Name: new_cases, dtype: float64
61595 61602    249.0
Name: new_cases, dtype: float64
61596 61603    273.0
Name: new_cases, dtype: float64
61597 61604    0.0
Name: new_cases, dtype: float64
61598 61605    473.0
Name: new_cases, dtype: float64
61599 61606    239.0
Name: new_cases, dtype: float64
61600 61607    212.0
Name: new_cases, dtype: float64
61601 61608    239.0
Name: new_cases, dtype: float64
61602 61609    112.0
Name: new_cases, dtype: float64
61603 61610    0.0
Name: new_cases, dtype: float64
61604 61611    342.0
Name: new_cases, dtype: float64
61605 61612    108.0
Name: new_cases, dtype: float64
61606 61613    160.0
Name: new_cases, dtype: float64
61607 61614    165.0
Name: new_cases, dtype: float64
61608 61615    163.0
Name: new_cases, dtype: float64
61609 61616    190.0
Name: new_cases, dtype: float64
61610 61617    91.0
Name: new_cases, dtype: float64
61611 61618    184.0
Name: new_cases, dtype: float64
61612 61619    172.0
Name: new_cases, dtype: float64
61613 61620    123.0
Name: new_cases, dtype: float64
61614 61621    485.0
Name: new_cases, dtype: float64
61615 61622    425.0
Name: new_cases, dtype: float64
61616 61623    309.0
Name: new_cases, dtype: float64
61617 61624    463.0
Name: new_cases, dtype: float64
61618 61625    323.0
Name: new_cases, dtype: float64
61619 61626    403.0
Name: new_cases, dtype: float64
61620 61627    320.0
Name: new_cases, dtype: float64
61621 61628    478.0
Name: new_cases, dtype: float64
61622 61629    643.0
Name: new_cases, dtype: float64
61623 61630    440.0
Name: new_cases, dtype: float64
61624 61631    519.0
Name: new_cases, dtype: float64
61625 61632    1048.0
Name: new_cases, dtype: float64
61626 61633    463.0
Name: new_cases, dtype: float64
61627 61634    587.0
Name: new_cases, dtype: float64
61628 61635    587.0
Name: new_cases, dtype: float64
61629 61636    628.0
Name: new_cases, dtype: float64
61630 61637    795.0
Name: new_cases, dtype: float64
61631 61638    628.0
Name: new_cases, dtype: float64
61632 61639    1013.0
Name: new_cases, dtype: float64
61633 61640    1075.0
Name: new_cases, dtype: float64
61634 61641    736.0
Name: new_cases, dtype: float64
61635 61642    740.0
Name: new_cases, dtype: float64
61636 61643    704.0
Name: new_cases, dtype: float64
61637 61644    858.0
Name: new_cases, dtype: float64
61638 61645    996.0
Name: new_cases, dtype: float64
61639 61646    805.0
Name: new_cases, dtype: float64
61640 61647    1022.0
Name: new_cases, dtype: float64
61641 61648    722.0
Name: new_cases, dtype: float64
61642 61649    763.0
Name: new_cases, dtype: float64
61643 61650    550.0
Name: new_cases, dtype: float64
61644 61651    406.0
Name: new_cases, dtype: float64
61645 61652    669.0
Name: new_cases, dtype: float64
61646 61653    530.0
Name: new_cases, dtype: float64
61647 61654    507.0
Name: new_cases, dtype: float64
61648 61655    489.0
Name: new_cases, dtype: float64
61649 61656    527.0
Name: new_cases, dtype: float64
61650 61657    930.0
Name: new_cases, dtype: float64
61651 61658    831.0
Name: new_cases, dtype: float64
61652 61659    878.0
Name: new_cases, dtype: float64
61653 61660    1048.0
Name: new_cases, dtype: float64
61654 61661    1042.0
Name: new_cases, dtype: float64
61655 61662    776.0
Name: new_cases, dtype: float64
61656 61663    734.0
Name: new_cases, dtype: float64
61657 61664    757.0
Name: new_cases, dtype: float64
61658 61665    800.0
Name: new_cases, dtype: float64
61659 61666    657.0
Name: new_cases, dtype: float64
61660 61667    879.0
Name: new_cases, dtype: float64
61661 61668    838.0
Name: new_cases, dtype: float64
61662 61669    465.0
Name: new_cases, dtype: float64
61663 61670    719.0
Name: new_cases, dtype: float64
61664 61671    484.0
Name: new_cases, dtype: float64
61665 61672    482.0
Name: new_cases, dtype: float64
61666 61673    588.0
Name: new_cases, dtype: float64
61667 61674    671.0
Name: new_cases, dtype: float64
61668 61675    512.0
Name: new_cases, dtype: float64
61669 61676    597.0
Name: new_cases, dtype: float64
61670 61677    505.0
Name: new_cases, dtype: float64
61671 61678    799.0
Name: new_cases, dtype: float64
61672 61679    657.0
Name: new_cases, dtype: float64
61673 61680    610.0
Name: new_cases, dtype: float64
61674 61681    608.0
Name: new_cases, dtype: float64
61675 61682    481.0
Name: new_cases, dtype: float64
61676 61683    418.0
Name: new_cases, dtype: float64
61677 61684    531.0
Name: new_cases, dtype: float64
61678 61685    254.0
Name: new_cases, dtype: float64
61679 61686    385.0
Name: new_cases, dtype: float64
61680 61687    425.0
Name: new_cases, dtype: float64
61681 61688    512.0
Name: new_cases, dtype: float64
61682 61689    523.0
Name: new_cases, dtype: float64
61683 61690    493.0
Name: new_cases, dtype: float64
61684 61691    675.0
Name: new_cases, dtype: float64
61685 61692    628.0
Name: new_cases, dtype: float64
61686 61693    521.0
Name: new_cases, dtype: float64
61687 61694    562.0
Name: new_cases, dtype: float64
61688 61695    602.0
Name: new_cases, dtype: float64
61689 61696    528.0
Name: new_cases, dtype: float64
61690 61697    968.0
Name: new_cases, dtype: float64
61691 61698    398.0
Name: new_cases, dtype: float64
61692 61699    772.0
Name: new_cases, dtype: float64
61693 61700    1020.0
Name: new_cases, dtype: float64
61694 61701    1141.0
Name: new_cases, dtype: float64
61695 61702    835.0
Name: new_cases, dtype: float64
61696 61703    529.0
Name: new_cases, dtype: float64
61697 61704    840.0
Name: new_cases, dtype: float64
61698 61705    755.0
Name: new_cases, dtype: float64
61699 61706    757.0
Name: new_cases, dtype: float64
61700 61707    632.0
Name: new_cases, dtype: float64
61701 61708    640.0
Name: new_cases, dtype: float64
61702 61709    554.0
Name: new_cases, dtype: float64

61703 61710    412.0
Name: new_cases, dtype: float64
61704 61711    50.0
Name: new_cases, dtype: float64
61705 61712    404.0
Name: new_cases, dtype: float64
61706 61713    379.0
Name: new_cases, dtype: float64
61707 61714    205.0
Name: new_cases, dtype: float64
61708 61715    247.0
Name: new_cases, dtype: float64
61709 61716    1087.0
Name: new_cases, dtype: float64
61710 61717    653.0
Name: new_cases, dtype: float64
61711 61718    831.0
Name: new_cases, dtype: float64
61712 61719    0.0
Name: new_cases, dtype: float64
61713 61720    1040.0
Name: new_cases, dtype: float64
61714 61721    460.0
Name: new_cases, dtype: float64
61715 61722    491.0
Name: new_cases, dtype: float64
61716 61723    532.0
Name: new_cases, dtype: float64
61717 61724    473.0
Name: new_cases, dtype: float64
61718 61725    459.0
Name: new_cases, dtype: float64
61719 61726    231.0
Name: new_cases, dtype: float64
61720 61727    369.0
Name: new_cases, dtype: float64
61721 61728    518.0
Name: new_cases, dtype: float64
61722 61729    647.0
Name: new_cases, dtype: float64
61723 61730    708.0
Name: new_cases, dtype: float64
61724 61731    0.0
Name: new_cases, dtype: float64
61725 61732    989.0
Name: new_cases, dtype: float64
61726 61733    561.0
Name: new_cases, dtype: float64
61727 61734    802.0
Name: new_cases, dtype: float64
61728 61735    698.0
Name: new_cases, dtype: float64
61729 61736    671.0
Name: new_cases, dtype: float64
61730 61737    519.0
Name: new_cases, dtype: float64
61731 61738    841.0
Name: new_cases, dtype: float64
61732 61739    391.0
Name: new_cases, dtype: float64
61733 61740    642.0
Name: new_cases, dtype: float64
61734 61741    354.0
Name: new_cases, dtype: float64
61735 61742    656.0
Name: new_cases, dtype: float64
61736 61743    880.0
Name: new_cases, dtype: float64
61737 61744    594.0
Name: new_cases, dtype: float64
61738 61745    935.0
Name: new_cases, dtype: float64
61739 61746    332.0
Name: new_cases, dtype: float64
61740 61747    439.0
Name: new_cases, dtype: float64
61741 61748    606.0
Name: new_cases, dtype: float64
61742 61749    631.0
Name: new_cases, dtype: float64
61743 61750    602.0
Name: new_cases, dtype: float64
61744 61751    903.0
Name: new_cases, dtype: float64
61745 61752    831.0
Name: new_cases, dtype: float64
61746 61753    956.0
Name: new_cases, dtype: float64
61747 61754    851.0
Name: new_cases, dtype: float64
61748 61755    846.0
Name: new_cases, dtype: float64
61749 61756    431.0
Name: new_cases, dtype: float64
61750 61757    0.0
Name: new_cases, dtype: float64
61751 61758    1215.0
Name: new_cases, dtype: float64
61752 61759    490.0
Name: new_cases, dtype: float64
61753 61760    752.0
Name: new_cases, dtype: float64
61754 61761    657.0
Name: new_cases, dtype: float64
61755 61762    576.0
Name: new_cases, dtype: float64
61756 61763    951.0
Name: new_cases, dtype: float64
61757 61764    738.0
Name: new_cases, dtype: float64
61758 61765    0.0
Name: new_cases, dtype: float64
61759 61766    1324.0
Name: new_cases, dtype: float64
61760 61767    193.0
Name: new_cases, dtype: float64
61761 61768    283.0
Name: new_cases, dtype: float64
61762 61769    436.0
Name: new_cases, dtype: float64
61763 61770    223.0
Name: new_cases, dtype: float64
61764 61771    229.0
Name: new_cases, dtype: float64
61765 61772    465.0
Name: new_cases, dtype: float64
61766 61773    0.0
Name: new_cases, dtype: float64
61767 61774    532.0
Name: new_cases, dtype: float64
61768 61775    231.0
Name: new_cases, dtype: float64
61769 61776    365.0
Name: new_cases, dtype: float64
61770 61777    299.0
Name: new_cases, dtype: float64
61771 61778    611.0
Name: new_cases, dtype: float64
61772 61779    476.0
Name: new_cases, dtype: float64
61773 61780    547.0
Name: new_cases, dtype: float64
61774 61781    137.0
Name: new_cases, dtype: float64
61775 61782    249.0
Name: new_cases, dtype: float64
61776 61783    0.0
Name: new_cases, dtype: float64
61777 61784    0.0
Name: new_cases, dtype: float64
61778 61785    63.0
Name: new_cases, dtype: float64
61779 61786    884.0
Name: new_cases, dtype: float64
61780 61787    0.0
Name: new_cases, dtype: float64
61781 61788    776.0
Name: new_cases, dtype: float64
61782 61789    0.0
Name: new_cases, dtype: float64
61783 61790    905.0
Name: new_cases, dtype: float64
61784 61791    565.0
Name: new_cases, dtype: float64
61785 61792    453.0
Name: new_cases, dtype: float64
61786 61793    379.0
Name: new_cases, dtype: float64
61787 61794    375.0
Name: new_cases, dtype: float64
61788 61795    365.0
Name: new_cases, dtype: float64
61789 61796    0.0
Name: new_cases, dtype: float64
61790 61797    891.0
Name: new_cases, dtype: float64
61791 61798    616.0
Name: new_cases, dtype: float64
61792 61799    0.0
Name: new_cases, dtype: float64
61793 61800    200.0
Name: new_cases, dtype: float64
61794 61801    1063.0
Name: new_cases, dtype: float64
61795 61802    0.0
Name: new_cases, dtype: float64
61796 61803    684.0
Name: new_cases, dtype: float64
61797 61804    1085.0
Name: new_cases, dtype: float64
61798 61805    415.0
Name: new_cases, dtype: float64
61799 61806    501.0
Name: new_cases, dtype: float64
61800 61807    335.0
Name: new_cases, dtype: float64
61801 61808    316.0
Name: new_cases, dtype: float64
61802 61809    283.0
Name: new_cases, dtype: float64
61803 61810    301.0
Name: new_cases, dtype: float64
61804 61811    374.0
Name: new_cases, dtype: float64
61805 61812    157.0
Name: new_cases, dtype: float64
61806 61813    738.0
Name: new_cases, dtype: float64
61807 61814    0.0
Name: new_cases, dtype: float64
61808 61815    810.0
Name: new_cases, dtype: float64
61809 61816    168.0
Name: new_cases, dtype: float64
61810 61817    398.0
Name: new_cases, dtype: float64
61811 61818    448.0
Name: new_cases, dtype: float64
61812 61819    0.0
Name: new_cases, dtype: float64
61813 61820    623.0
Name: new_cases, dtype: float64
61814 61821    438.0
Name: new_cases, dtype: float64
61815 61822    0.0
Name: new_cases, dtype: float64
61816 61823    616.0
Name: new_cases, dtype: float64
61817 61824    1199.0
Name: new_cases, dtype: float64
61818 61825    0.0
Name: new_cases, dtype: float64
61819 61826    915.0
Name: new_cases, dtype: float64
61820 61827    1147.0
Name: new_cases, dtype: float64
61821 61828    170.0
Name: new_cases, dtype: float64
61822 61829    225.0
Name: new_cases, dtype: float64
61823 61830    29.0
Name: new_cases, dtype: float64
61824 61831    424.0
Name: new_cases, dtype: float64
61825 61832    1077.0
Name: new_cases, dtype: float64
61826 61833    219.0
Name: new_cases, dtype: float64
61827 61834    439.0
Name: new_cases, dtype: float64
61828 61835    1386.0
Name: new_cases, dtype: float64
61829 61836    1002.0
Name: new_cases, dtype: float64
61830 61837    756.0
Name: new_cases, dtype: float64
61831 61838    1104.0
Name: new_cases, dtype: float64
61832 61839    1204.0
Name: new_cases, dtype: float64
61833 61840    954.0
Name: new_cases, dtype: float64
61834 61841    449.0
Name: new_cases, dtype: float64
61835 61842    1095.0
Name: new_cases, dtype: float64
61836 61843    604.0
Name: new_cases, dtype: float64
61837 61844    827.0
Name: new_cases, dtype: float64
61838 61845    1130.0
Name: new_cases, dtype: float64
61839 61846    830.0
Name: new_cases, dtype: float64
61840 61847    1146.0
Name: new_cases, dtype: float64
61841 61848    1138.0
Name: new_cases, dtype: float64
61842 61849    1056.0
Name: new_cases, dtype: float64
61843 61850    691.0
Name: new_cases, dtype: float64
61844 61851    1055.0
Name: new_cases, dtype: float64
61845 61852    896.0
Name: new_cases, dtype: float64
61846 61853    1127.0
Name: new_cases, dtype: float64
61847 61854    985.0
Name: new_cases, dtype: float64
61848 61855    1118.0
Name: new_cases, dtype: float64
61849 61856    990.0
Name: new_cases, dtype: float64
61850 61857    743.0
Name: new_cases, dtype: float64
61851 61858    0.0
Name: new_cases, dtype: float64
61852 61859    1108.0
Name: new_cases, dtype: float64
61853 61860    2152.0
Name: new_cases, dtype: float64
61854 61861    1122.0
Name: new_cases, dtype: float64
61855 61862    1028.0
Name: new_cases, dtype: float64
61856 61863    652.0
Name: new_cases, dtype: float64
61857 61864    663.0
Name: new_cases, dtype: float64
61858 61865    1167.0
Name: new_cases, dtype: float64
61859 61866    871.0
Name: new_cases, dtype: float64
61860 61867    862.0
Name: new_cases, dtype: float64
61861 61868    887.0
Name: new_cases, dtype: float64
61862 61869    669.0
Name: new_cases, dtype: float64
61863 61870    764.0
Name: new_cases, dtype: float64
61864 61871    383.0
Name: new_cases, dtype: float64

61865 61872    812.0
Name: new_cases, dtype: float64
61866 61873    744.0
Name: new_cases, dtype: float64
61867 61874    857.0
Name: new_cases, dtype: float64
61868 61875    721.0
Name: new_cases, dtype: float64
61869 61876    772.0
Name: new_cases, dtype: float64
61870 61877    418.0
Name: new_cases, dtype: float64
61871 61878    600.0
Name: new_cases, dtype: float64
61872 61879    642.0
Name: new_cases, dtype: float64
61873 61880    810.0
Name: new_cases, dtype: float64
61874 61881    947.0
Name: new_cases, dtype: float64
61875 61882    749.0
Name: new_cases, dtype: float64
61876 61883    668.0
Name: new_cases, dtype: float64
61877 61884    843.0
Name: new_cases, dtype: float64
61878 61885    550.0
Name: new_cases, dtype: float64
61879 61886    681.0
Name: new_cases, dtype: float64
61880 61887    773.0
Name: new_cases, dtype: float64
61881 61888    342.0
Name: new_cases, dtype: float64
61882 61889    477.0
Name: new_cases, dtype: float64
61883 61890    0.0
Name: new_cases, dtype: float64
61884 61891    443.0
Name: new_cases, dtype: float64
61885 61892    709.0
Name: new_cases, dtype: float64
61886 61893    514.0
Name: new_cases, dtype: float64
61887 61894    265.0
Name: new_cases, dtype: float64
61888 61895    934.0
Name: new_cases, dtype: float64
61889 61896    985.0
Name: new_cases, dtype: float64
61890 61897    741.0
Name: new_cases, dtype: float64
61891 61898    664.0
Name: new_cases, dtype: float64
61892 61899    445.0
Name: new_cases, dtype: float64
61893 61900    648.0
Name: new_cases, dtype: float64
61894 61901    590.0
Name: new_cases, dtype: float64
61895 61902    756.0
Name: new_cases, dtype: float64
61896 61903    525.0
Name: new_cases, dtype: float64
61897 61904    561.0
Name: new_cases, dtype: float64
61898 61905    574.0
Name: new_cases, dtype: float64
61899 61906    478.0
Name: new_cases, dtype: float64
61900 61907    871.0
Name: new_cases, dtype: float64
61901 61908    751.0
Name: new_cases, dtype: float64
61902 61909    790.0
Name: new_cases, dtype: float64
61903 61910    663.0
Name: new_cases, dtype: float64
61904 61911    853.0
Name: new_cases, dtype: float64
61905 61912    678.0
Name: new_cases, dtype: float64
61906 61913    445.0
Name: new_cases, dtype: float64
61907 61914    515.0
Name: new_cases, dtype: float64
61908 61915    539.0
Name: new_cases, dtype: float64
61909 61916    529.0
Name: new_cases, dtype: float64
61910 61917    683.0
Name: new_cases, dtype: float64
61911 61918    0.0
Name: new_cases, dtype: float64
61912 61919    416.0
Name: new_cases, dtype: float64
61913 61920    489.0
Name: new_cases, dtype: float64
61914 61921    505.0
Name: new_cases, dtype: float64
61915 61922    1277.0
Name: new_cases, dtype: float64
61916 61923    616.0
Name: new_cases, dtype: float64
61917 61924    754.0
Name: new_cases, dtype: float64
61918 61925    765.0
Name: new_cases, dtype: float64
61919 61926    977.0
Name: new_cases, dtype: float64
61920 61927    255.0
Name: new_cases, dtype: float64
61921 61928    306.0
Name: new_cases, dtype: float64
61922 61929    618.0
Name: new_cases, dtype: float64
61923 61930    1510.0
Name: new_cases, dtype: float64
61924 61931    761.0
Name: new_cases, dtype: float64
61925 61932    707.0
Name: new_cases, dtype: float64
61926 61933    577.0
Name: new_cases, dtype: float64
61927 61934    676.0
Name: new_cases, dtype: float64
61928 61935    742.0
Name: new_cases, dtype: float64
61929 61936    736.0
Name: new_cases, dtype: float64
61930 61937    0.0
Name: new_cases, dtype: float64
61931 61938    2415.0
Name: new_cases, dtype: float64
61932 61939    868.0
Name: new_cases, dtype: float64
61933 61940    0.0
Name: new_cases, dtype: float64
61934 61941    1211.0
Name: new_cases, dtype: float64
61935 61942    0.0
Name: new_cases, dtype: float64
61936 61943    413.0
Name: new_cases, dtype: float64
61937 61944    1036.0
Name: new_cases, dtype: float64
61938 61945    2720.0
Name: new_cases, dtype: float64
61939 61946    1257.0
Name: new_cases, dtype: float64
61940 61947    834.0
Name: new_cases, dtype: float64
61941 61948    0.0
Name: new_cases, dtype: float64
61942 61949    1308.0
Name: new_cases, dtype: float64
61943 61950    1358.0
Name: new_cases, dtype: float64
61944 61951    1131.0
Name: new_cases, dtype: float64
61945 61952    631.0
Name: new_cases, dtype: float64
61946 61953    735.0
Name: new_cases, dtype: float64
61947 61954    958.0
Name: new_cases, dtype: float64
61948 61955    0.0
Name: new_cases, dtype: float64
61949 61956    897.0
Name: new_cases, dtype: float64
61950 61957    1933.0
Name: new_cases, dtype: float64
61951 61958    874.0
Name: new_cases, dtype: float64
61952 61959    0.0
Name: new_cases, dtype: float64
61953 61960    930.0
Name: new_cases, dtype: float64
61954 61961    2042.0
Name: new_cases, dtype: float64
61955 61962    755.0
Name: new_cases, dtype: float64
61956 61963    797.0
Name: new_cases, dtype: float64
61957 61964    771.0
Name: new_cases, dtype: float64
61958 61965    924.0
Name: new_cases, dtype: float64
61959 61966    1100.0
Name: new_cases, dtype: float64
61960 61967    1249.0
Name: new_cases, dtype: float64
61961 61968    581.0
Name: new_cases, dtype: float64
61962 61969    531.0
Name: new_cases, dtype: float64
61963 61970    444.0
Name: new_cases, dtype: float64
61964 61971    800.0
Name: new_cases, dtype: float64
61965 61972    1007.0
Name: new_cases, dtype: float64
61966 61973    676.0
Name: new_cases, dtype: float64
61967 61974    852.0
Name: new_cases, dtype: float64
61968 61975    501.0
Name: new_cases, dtype: float64
61969 61976    0.0
Name: new_cases, dtype: float64
61970 61977    1275.0
Name: new_cases, dtype: float64
61971 61978    593.0
Name: new_cases, dtype: float64
61972 61979    608.0
Name: new_cases, dtype: float64
61973 61980    954.0
Name: new_cases, dtype: float64
61974 61981    657.0
Name: new_cases, dtype: float64
61975 61982    535.0
Name: new_cases, dtype: float64
61976 61983    252.0
Name: new_cases, dtype: float64
61977 61984    551.0
Name: new_cases, dtype: float64
61978 61985    419.0
Name: new_cases, dtype: float64
61979 61986    671.0
Name: new_cases, dtype: float64
61980 61987    828.0
Name: new_cases, dtype: float64
61981 61988    1400.0
Name: new_cases, dtype: float64
61982 61989    1379.0
Name: new_cases, dtype: float64
61983 61990    654.0
Name: new_cases, dtype: float64
61984 61991    387.0
Name: new_cases, dtype: float64
61985 61992    1003.0
Name: new_cases, dtype: float64
61986 61993    813.0
Name: new_cases, dtype: float64
61987 61994    0.0
Name: new_cases, dtype: float64
61988 61995    1218.0
Name: new_cases, dtype: float64
61989 61996    1979.0
Name: new_cases, dtype: float64
61990 61997    747.0
Name: new_cases, dtype: float64
61991 61998    319.0
Name: new_cases, dtype: float64
61992 61999    923.0
Name: new_cases, dtype: float64
61993 62000    546.0
Name: new_cases, dtype: float64
61994 62001    1155.0
Name: new_cases, dtype: float64
61995 62002    1531.0
Name: new_cases, dtype: float64
61996 62003    1279.0
Name: new_cases, dtype: float64
61997 62004    0.0
Name: new_cases, dtype: float64
61998 62005    703.0
Name: new_cases, dtype: float64
61999 62006    1738.0
Name: new_cases, dtype: float64
62000 62007    691.0
Name: new_cases, dtype: float64
62001 62008    616.0
Name: new_cases, dtype: float64
62002 62009    1798.0
Name: new_cases, dtype: float64
62003 62010    1744.0
Name: new_cases, dtype: float64
62004 62011    940.0
Name: new_cases, dtype: float64
62005 62012    1142.0
Name: new_cases, dtype: float64
62006 62013    1020.0
Name: new_cases, dtype: float64
62007 62014    669.0
Name: new_cases, dtype: float64
62008 62015    930.0
Name: new_cases, dtype: float64
62009 62016    1111.0
Name: new_cases, dtype: float64
62010 62017    972.0
Name: new_cases, dtype: float64
62011 62018    776.0
Name: new_cases, dtype: float64
62012 62019    499.0
Name: new_cases, dtype: float64
62013 62020    698.0
Name: new_cases, dtype: float64
62014 62021    1314.0
Name: new_cases, dtype: float64
62015 62022    985.0
Name: new_cases, dtype: float64
62016 62023    1283.0
Name: new_cases, dtype: float64
62017 62024    0.0
Name: new_cases, dtype: float64
62018 62025    0.0
Name: new_cases, dtype: float64
62019 62026    2347.0
Name: new_cases, dtype: float64
62020 62027    1082.0
Name: new_cases, dtype: float64
62021 62028    1501.0
Name: new_cases, dtype: float64
62022 62029    1188.0
Name: new_cases, dtype: float64
62023 62030    1260.0
Name: new_cases, dtype: float64

62024 62031    0.0
Name: new_cases, dtype: float64
62025 62032    0.0
Name: new_cases, dtype: float64
62026 62033    3812.0
Name: new_cases, dtype: float64
62027 62034    1240.0
Name: new_cases, dtype: float64
62028 62035    1282.0
Name: new_cases, dtype: float64
62029 62036    1592.0
Name: new_cases, dtype: float64
62030 62037    2550.0
Name: new_cases, dtype: float64
62031 62038    0.0
Name: new_cases, dtype: float64
62032 62039    0.0
Name: new_cases, dtype: float64
62033 62040    3461.0
Name: new_cases, dtype: float64
62034 62041    0.0
Name: new_cases, dtype: float64
62035 62042    2815.0
Name: new_cases, dtype: float64
62036 62043    794.0
Name: new_cases, dtype: float64
62037 62044    1755.0
Name: new_cases, dtype: float64
62038 62045    0.0
Name: new_cases, dtype: float64
62039 62046    0.0
Name: new_cases, dtype: float64
62040 62047    0.0
Name: new_cases, dtype: float64
62041 62048    3093.0
Name: new_cases, dtype: float64
62042 62049    3163.0
Name: new_cases, dtype: float64
62043 62050    0.0
Name: new_cases, dtype: float64
62044 62051    4043.0
Name: new_cases, dtype: float64
62045 62052    0.0
Name: new_cases, dtype: float64
62046 62053    0.0
Name: new_cases, dtype: float64
62047 62054    3596.0
Name: new_cases, dtype: float64
62048 62055    1844.0
Name: new_cases, dtype: float64
62049 62056    1950.0
Name: new_cases, dtype: float64
62050 62057    0.0
Name: new_cases, dtype: float64
62051 62058    3205.0
Name: new_cases, dtype: float64
62052 62059    0.0
Name: new_cases, dtype: float64
62053 62060    0.0
Name: new_cases, dtype: float64
62054 62061    2861.0
Name: new_cases, dtype: float64
62055 62062    1681.0
Name: new_cases, dtype: float64
62056 62063    0.0
Name: new_cases, dtype: float64
62057 62064    2518.0
Name: new_cases, dtype: float64
62058 62065    0.0
Name: new_cases, dtype: float64
62059 62066    1508.0
Name: new_cases, dtype: float64
62060 62067    0.0
Name: new_cases, dtype: float64
62061 62068    3359.0
Name: new_cases, dtype: float64
62062 62069    0.0
Name: new_cases, dtype: float64
62063 62070    1802.0
Name: new_cases, dtype: float64
62064 62071    1949.0
Name: new_cases, dtype: float64
62065 62072    0.0
Name: new_cases, dtype: float64
62066 62073    1299.0
Name: new_cases, dtype: float64
62067 62074    0.0
Name: new_cases, dtype: float64
62068 62075    2327.0
Name: new_cases, dtype: float64
62069 62076    1377.0
Name: new_cases, dtype: float64
62070 62077    1383.0
Name: new_cases, dtype: float64
62071 62078    0.0
Name: new_cases, dtype: float64
62072 62079    1985.0
Name: new_cases, dtype: float64
62073 62080    0.0
Name: new_cases, dtype: float64
62074 62081    0.0
Name: new_cases, dtype: float64
62075 62082    2762.0
Name: new_cases, dtype: float64
62076 62083    0.0
Name: new_cases, dtype: float64
62077 62084    1329.0
Name: new_cases, dtype: float64
62078 62085    0.0
Name: new_cases, dtype: float64
62079 62086    1737.0
Name: new_cases, dtype: float64
62080 62087    947.0
Name: new_cases, dtype: float64
62081 62088    0.0
Name: new_cases, dtype: float64
62082 62089    2114.0
Name: new_cases, dtype: float64
62083 62090    830.0
Name: new_cases, dtype: float64
62084 62091    929.0
Name: new_cases, dtype: float64
62085 62092    0.0
Name: new_cases, dtype: float64
62086 62093    1490.0
Name: new_cases, dtype: float64
62087 62094    0.0
Name: new_cases, dtype: float64
62088 62095    0.0
Name: new_cases, dtype: float64
62089 62096    89.0
Name: new_cases, dtype: float64
62090 62097    2153.0
Name: new_cases, dtype: float64
62091 62098    735.0
Name: new_cases, dtype: float64
62092 62099    0.0
Name: new_cases, dtype: float64
62093 62100    1281.0
Name: new_cases, dtype: float64
62094 62101    0.0
Name: new_cases, dtype: float64
62095 62102    0.0
Name: new_cases, dtype: float64
62096 62103    1049.0
Name: new_cases, dtype: float64
62097 62104    330.0
Name: new_cases, dtype: float64
62098 62105    376.0
Name: new_cases, dtype: float64
62099 62106    0.0
Name: new_cases, dtype: float64
62100 62107    0.0
Name: new_cases, dtype: float64
62101 62108    0.0
Name: new_cases, dtype: float64
62102 62109    0.0
Name: new_cases, dtype: float64
62103 62110    1232.0
Name: new_cases, dtype: float64
62104 62111    706.0
Name: new_cases, dtype: float64
62105 62112    463.0
Name: new_cases, dtype: float64
62106 62113    430.0
Name: new_cases, dtype: float64
62107 62114    0.0
Name: new_cases, dtype: float64
62108 62115    318.0
Name: new_cases, dtype: float64
62109 62116    0.0
Name: new_cases, dtype: float64
62110 62117    0.0
Name: new_cases, dtype: float64
62111 62118    1027.0
Name: new_cases, dtype: float64
62112 62119    0.0
Name: new_cases, dtype: float64
62113 62120    383.0
Name: new_cases, dtype: float64
62114 62121    249.0
Name: new_cases, dtype: float64
62115 62122    310.0
Name: new_cases, dtype: float64
62116 62123    0.0
Name: new_cases, dtype: float64
62117 62124    0.0
Name: new_cases, dtype: float64
62118 62125    635.0
Name: new_cases, dtype: float64
62119 62126    0.0
Name: new_cases, dtype: float64
62120 62127    430.0
Name: new_cases, dtype: float64
62121 62128    0.0
Name: new_cases, dtype: float64
62122 62129    168.0
Name: new_cases, dtype: float64
62123 62130    0.0
Name: new_cases, dtype: float64
62124 62131    0.0
Name: new_cases, dtype: float64
62125 62132    496.0
Name: new_cases, dtype: float64
62126 62133    106.0
Name: new_cases, dtype: float64
62127 62134    0.0
Name: new_cases, dtype: float64
62128 62135    298.0
Name: new_cases, dtype: float64
62129 62136    0.0
Name: new_cases, dtype: float64
62130 62137    0.0
Name: new_cases, dtype: float64
62131 62138    314.0
Name: new_cases, dtype: float64
62132 62139    81.0
Name: new_cases, dtype: float64
62133 62140    0.0
Name: new_cases, dtype: float64
62134 62141    165.0
Name: new_cases, dtype: float64
62135 62142    0.0
Name: new_cases, dtype: float64
62136 62143    32.0
Name: new_cases, dtype: float64
62137 62144    94.0
Name: new_cases, dtype: float64
62138 62145    135.0
Name: new_cases, dtype: float64
62139 62146    0.0
Name: new_cases, dtype: float64
62140 62147    191.0
Name: new_cases, dtype: float64
62141 62148    0.0
Name: new_cases, dtype: float64
62142 62149    127.0
Name: new_cases, dtype: float64
62143 62150    0.0
Name: new_cases, dtype: float64
62144 62151    0.0
Name: new_cases, dtype: float64
62145 62152    107.0
Name: new_cases, dtype: float64
62146 62153    0.0
Name: new_cases, dtype: float64
62147 62154    185.0
Name: new_cases, dtype: float64
62148 62155    0.0
Name: new_cases, dtype: float64
62149 62156    147.0
Name: new_cases, dtype: float64
62150 62157    0.0
Name: new_cases, dtype: float64
62151 62158    0.0
Name: new_cases, dtype: float64
62152 62159    0.0
Name: new_cases, dtype: float64
62153 62160    0.0
Name: new_cases, dtype: float64
62154 62161    0.0
Name: new_cases, dtype: float64
62155 62162    0.0
Name: new_cases, dtype: float64
62156 62163    392.0
Name: new_cases, dtype: float64
62157 62164    0.0
Name: new_cases, dtype: float64
62158 62165    0.0
Name: new_cases, dtype: float64
62159 62166    0.0
Name: new_cases, dtype: float64
62160 62167    0.0
Name: new_cases, dtype: float64
62161 62168    0.0
Name: new_cases, dtype: float64
62162 62169    172.0
Name: new_cases, dtype: float64
62163 62170    0.0
Name: new_cases, dtype: float64
62164 62171    0.0
Name: new_cases, dtype: float64
62165 62172    0.0
Name: new_cases, dtype: float64
62166 62173    192.0
Name: new_cases, dtype: float64
62167 62174    0.0
Name: new_cases, dtype: float64
62168 62175    70.0
Name: new_cases, dtype: float64
62169 62176    0.0
Name: new_cases, dtype: float64
62170 62177    0.0
Name: new_cases, dtype: float64
62171 62178    0.0
Name: new_cases, dtype: float64
62172 62179    0.0
Name: new_cases, dtype: float64
62173 62180    0.0
Name: new_cases, dtype: float64
62174 62181    0.0
Name: new_cases, dtype: float64
62175 62182    0.0
Name: new_cases, dtype: float64
62176 62183    0.0
Name: new_cases, dtype: float64
62177 62184    0.0
Name: new_cases, dtype: float64
62178 62185    388.0
Name: new_cases, dtype: float64
62179 62186    0.0
Name: new_cases, dtype: float64
62180 62187    203.0
Name: new_cases, dtype: float64
62181 62188    126.0
Name: new_cases, dtype: float64
62182 62189    0.0
Name: new_cases, dtype: float64
62183 62190    0.0
Name: new_cases, dtype: float64
62184 62191    0.0
Name: new_cases, dtype: float64
62185 62192    0.0
Name: new_cases, dtype: float64
62186 62193    0.0
Name: new_cases, dtype: float64
62187 62194    0.0
Name: new_cases, dtype: float64
62188 62195    0.0
Name: new_cases, dtype: float64
62189 62196    0.0
Name: new_cases, dtype: float64
62190 62197    0.0
Name: new_cases, dtype: float64
62191 62198    0.0
Name: new_cases, dtype: float64
62192 62199    1852.0
Name: new_cases, dtype: float64
62193 Series([], Name: new_cases, dtype: float64)
62194 Series([], Name: new_cases, dtype: float64)

62195 Series([], Name: new_cases, dtype: float64)
62196 Series([], Name: new_cases, dtype: float64)
62197 Series([], Name: new_cases, dtype: float64)
62198 Series([], Name: new_cases, dtype: float64)
62199 Series([], Name: new_cases, dtype: float64)
62918 62925    4.0
Name: new_cases, dtype: float64
62919 62926    0.0
Name: new_cases, dtype: float64
62920 62927    6.0
Name: new_cases, dtype: float64
62921 62928    11.0
Name: new_cases, dtype: float64
62922 62929    2.0
Name: new_cases, dtype: float64
62923 62930    7.0
Name: new_cases, dtype: float64
62924 62931    11.0
Name: new_cases, dtype: float64
62925 62932    8.0
Name: new_cases, dtype: float64
62926 62933    15.0
Name: new_cases, dtype: float64
62927 62934    12.0
Name: new_cases, dtype: float64
62928 62935    18.0
Name: new_cases, dtype: float64
62929 62936    28.0
Name: new_cases, dtype: float64
62930 62937    36.0
Name: new_cases, dtype: float64
62931 62938    20.0
Name: new_cases, dtype: float64
62932 62939    39.0
Name: new_cases, dtype: float64
62933 62940    35.0
Name: new_cases, dtype: float64
62934 62941    39.0
Name: new_cases, dtype: float64
62935 62942    43.0
Name: new_cases, dtype: float64
62936 62943    65.0
Name: new_cases, dtype: float64
62937 62944    39.0
Name: new_cases, dtype: float64
62938 62945    45.0
Name: new_cases, dtype: float64
62939 62946    33.0
Name: new_cases, dtype: float64
62940 62947    60.0
Name: new_cases, dtype: float64
62941 62948    38.0
Name: new_cases, dtype: float64
62942 62949    55.0
Name: new_cases, dtype: float64
62943 62950    55.0
Name: new_cases, dtype: float64
62944 62951    11.0
Name: new_cases, dtype: float64
62945 62952    73.0
Name: new_cases, dtype: float64
62946 62953    78.0
Name: new_cases, dtype: float64
62947 62954    85.0
Name: new_cases, dtype: float64
62948 62955    210.0
Name: new_cases, dtype: float64
62949 62956    120.0
Name: new_cases, dtype: float64
62950 62957    100.0
Name: new_cases, dtype: float64
62951 62958    48.0
Name: new_cases, dtype: float64
62952 62959    54.0
Name: new_cases, dtype: float64
62953 62960    67.0
Name: new_cases, dtype: float64
62954 62961    73.0
Name: new_cases, dtype: float64
62955 62962    111.0
Name: new_cases, dtype: float64
62956 62963    71.0
Name: new_cases, dtype: float64
62957 62964    82.0
Name: new_cases, dtype: float64
62958 62965    68.0
Name: new_cases, dtype: float64
62959 62966    114.0
Name: new_cases, dtype: float64
62960 62967    70.0
Name: new_cases, dtype: float64
62961 62968    116.0
Name: new_cases, dtype: float64
62962 62969    159.0
Name: new_cases, dtype: float64
62963 62970    0.0
Name: new_cases, dtype: float64
62964 62971    57.0
Name: new_cases, dtype: float64
62965 62972    83.0
Name: new_cases, dtype: float64
62966 62973    66.0
Name: new_cases, dtype: float64
62967 62974    78.0
Name: new_cases, dtype: float64
62968 62975    48.0
Name: new_cases, dtype: float64
62969 62976    88.0
Name: new_cases, dtype: float64
62970 62977    79.0
Name: new_cases, dtype: float64
62971 62978    56.0
Name: new_cases, dtype: float64
62972 62979    37.0
Name: new_cases, dtype: float64
62973 62980    30.0
Name: new_cases, dtype: float64
62974 62981    46.0
Name: new_cases, dtype: float64
62975 62982    39.0
Name: new_cases, dtype: float64
62976 62983    28.0
Name: new_cases, dtype: float64
62977 62984    35.0
Name: new_cases, dtype: float64
62978 62985    50.0
Name: new_cases, dtype: float64
62979 62986    21.0
Name: new_cases, dtype: float64
62980 62987    29.0
Name: new_cases, dtype: float64
62981 62988    28.0
Name: new_cases, dtype: float64
62982 62989    39.0
Name: new_cases, dtype: float64
62983 62990    37.0
Name: new_cases, dtype: float64
62984 62991    56.0
Name: new_cases, dtype: float64
62985 62992    36.0
Name: new_cases, dtype: float64
62986 62993    26.0
Name: new_cases, dtype: float64
62987 62994    21.0
Name: new_cases, dtype: float64
62988 62995    42.0
Name: new_cases, dtype: float64
62989 62996    43.0
Name: new_cases, dtype: float64
62990 62997    37.0
Name: new_cases, dtype: float64
62991 62998    35.0
Name: new_cases, dtype: float64
62992 62999    28.0
Name: new_cases, dtype: float64
62993 63000    15.0
Name: new_cases, dtype: float64
62994 63001    15.0
Name: new_cases, dtype: float64
62995 63002    22.0
Name: new_cases, dtype: float64
62996 63003    23.0
Name: new_cases, dtype: float64
62997 63004    25.0
Name: new_cases, dtype: float64
62998 63005    26.0
Name: new_cases, dtype: float64
62999 63006    9.0
Name: new_cases, dtype: float64
63000 63007    16.0
Name: new_cases, dtype: float64
63001 63008    29.0
Name: new_cases, dtype: float64
63002 63009    10.0
Name: new_cases, dtype: float64
63003 63010    23.0
Name: new_cases, dtype: float64
63004 63011    16.0
Name: new_cases, dtype: float64
63005 63012    20.0
Name: new_cases, dtype: float64
63006 63013    18.0
Name: new_cases, dtype: float64
63007 63014    6.0
Name: new_cases, dtype: float64
63008 63015    3.0
Name: new_cases, dtype: float64
63009 63016    10.0
Name: new_cases, dtype: float64
63010 63017    12.0
Name: new_cases, dtype: float64
63011 63018    14.0
Name: new_cases, dtype: float64
63012 63019    11.0
Name: new_cases, dtype: float64
63013 63020    5.0
Name: new_cases, dtype: float64
63014 63021    7.0
Name: new_cases, dtype: float64
63015 63022    1.0
Name: new_cases, dtype: float64
63016 63023    1.0
Name: new_cases, dtype: float64
63017 63024    1.0
Name: new_cases, dtype: float64
63018 63025    2.0
Name: new_cases, dtype: float64
63019 63026    5.0
Name: new_cases, dtype: float64
63020 63027    8.0
Name: new_cases, dtype: float64
63021 63028    8.0
Name: new_cases, dtype: float64
63022 63029    5.0
Name: new_cases, dtype: float64
63023 63030    7.0
Name: new_cases, dtype: float64
63024 63031    9.0
Name: new_cases, dtype: float64
63025 63032    4.0
Name: new_cases, dtype: float64
63026 63033    11.0
Name: new_cases, dtype: float64
63027 63034    4.0
Name: new_cases, dtype: float64
63028 63035    3.0
Name: new_cases, dtype: float64
63029 63036    10.0
Name: new_cases, dtype: float64
63030 63037    2.0
Name: new_cases, dtype: float64
63031 63038    9.0
Name: new_cases, dtype: float64
63032 63039    6.0
Name: new_cases, dtype: float64
63033 63040    2.0
Name: new_cases, dtype: float64
63034 63041    9.0
Name: new_cases, dtype: float64
63035 63042    6.0
Name: new_cases, dtype: float64
63036 63043    16.0
Name: new_cases, dtype: float64
63037 63044    5.0
Name: new_cases, dtype: float64
63038 63045    10.0
Name: new_cases, dtype: float64
63039 63046    3.0
Name: new_cases, dtype: float64
63040 63047    6.0
Name: new_cases, dtype: float64
63041 63048    5.0
Name: new_cases, dtype: float64
63042 63049    13.0
Name: new_cases, dtype: float64
63043 63050    11.0
Name: new_cases, dtype: float64
63044 63051    5.0
Name: new_cases, dtype: float64
63045 63052    16.0
Name: new_cases, dtype: float64
63046 63053    14.0
Name: new_cases, dtype: float64
63047 63054    22.0
Name: new_cases, dtype: float64
63048 63055    18.0
Name: new_cases, dtype: float64
63049 63056    6.0
Name: new_cases, dtype: float64
63050 63057    8.0
Name: new_cases, dtype: float64
63051 63058    19.0
Name: new_cases, dtype: float64
63052 63059    14.0
Name: new_cases, dtype: float64
63053 63060    18.0
Name: new_cases, dtype: float64
63054 63061    26.0
Name: new_cases, dtype: float64
63055 63062    11.0
Name: new_cases, dtype: float64
63056 63063    13.0
Name: new_cases, dtype: float64
63057 63064    8.0
Name: new_cases, dtype: float64
63058 63065    9.0
Name: new_cases, dtype: float64
63059 63066    19.0
Name: new_cases, dtype: float64
63060 63067    21.0
Name: new_cases, dtype: float64
63061 63068    21.0
Name: new_cases, dtype: float64
63062 63069    9.0
Name: new_cases, dtype: float64
63063 63070    9.0
Name: new_cases, dtype: float64
63064 63071    9.0
Name: new_cases, dtype: float64
63065 63072    11.0
Name: new_cases, dtype: float64
63066 63073    33.0
Name: new_cases, dtype: float64
63067 63074    24.0
Name: new_cases, dtype: float64
63068 63075    32.0
Name: new_cases, dtype: float64
63069 63076    43.0
Name: new_cases, dtype: float64
63070 63077    35.0
Name: new_cases, dtype: float64
63071 63078    15.0
Name: new_cases, dtype: float64
63072 63079    22.0
Name: new_cases, dtype: float64
63073 63080    45.0
Name: new_cases, dtype: float64
63074 63081    40.0
Name: new_cases, dtype: float64
63075 63082    24.0
Name: new_cases, dtype: float64
63076 63083    39.0
Name: new_cases, dtype: float64
63077 63084    30.0
Name: new_cases, dtype: float64
63078 63085    24.0
Name: new_cases, dtype: float64
63079 63086    32.0
Name: new_cases, dtype: float64
63080 63087    44.0
Name: new_cases, dtype: float64
63081 63088    52.0
Name: new_cases, dtype: float64
63082 63089    35.0
Name: new_cases, dtype: float64
63083 63090    22.0
Name: new_cases, dtype: float64
63084 63091    36.0
Name: new_cases, dtype: float64
63085 63092    24.0
Name: new_cases, dtype: float64
63086 63093    73.0
Name: new_cases, dtype: float64
63087 63094    91.0
Name: new_cases, dtype: float64
63088 63095    132.0
Name: new_cases, dtype: float64
63089 63096    158.0
Name: new_cases, dtype: float64

63090 63097    292.0
Name: new_cases, dtype: float64
63091 63098    178.0
Name: new_cases, dtype: float64
63092 63099    118.0
Name: new_cases, dtype: float64
63093 63100    365.0
Name: new_cases, dtype: float64
63094 63101    301.0
Name: new_cases, dtype: float64
63095 63102    459.0
Name: new_cases, dtype: float64
63096 63103    510.0
Name: new_cases, dtype: float64
63097 63104    495.0
Name: new_cases, dtype: float64
63098 63105    576.0
Name: new_cases, dtype: float64
63099 63106    341.0
Name: new_cases, dtype: float64
63100 63107    411.0
Name: new_cases, dtype: float64
63101 63108    476.0
Name: new_cases, dtype: float64
63102 63109    718.0
Name: new_cases, dtype: float64
63103 63110    916.0
Name: new_cases, dtype: float64
63104 63111    484.0
Name: new_cases, dtype: float64
63105 63112    844.0
Name: new_cases, dtype: float64
63106 63113    726.0
Name: new_cases, dtype: float64
63107 63114    581.0
Name: new_cases, dtype: float64
63108 63115    710.0
Name: new_cases, dtype: float64
63109 63116    941.0
Name: new_cases, dtype: float64
63110 63117    809.0
Name: new_cases, dtype: float64
63111 63118    1070.0
Name: new_cases, dtype: float64
63112 63119    876.0
Name: new_cases, dtype: float64
63113 63120    633.0
Name: new_cases, dtype: float64
63114 63121    951.0
Name: new_cases, dtype: float64
63115 63122    750.0
Name: new_cases, dtype: float64
63116 63123    927.0
Name: new_cases, dtype: float64
63117 63124    950.0
Name: new_cases, dtype: float64
63118 63125    937.0
Name: new_cases, dtype: float64
63119 63126    702.0
Name: new_cases, dtype: float64
63120 63127    851.0
Name: new_cases, dtype: float64
63121 63128    894.0
Name: new_cases, dtype: float64
63122 63129    848.0
Name: new_cases, dtype: float64
63123 63130    1322.0
Name: new_cases, dtype: float64
63124 63131    1086.0
Name: new_cases, dtype: float64
63125 63132    858.0
Name: new_cases, dtype: float64
63126 63133    905.0
Name: new_cases, dtype: float64
63127 63134    818.0
Name: new_cases, dtype: float64
63128 63135    816.0
Name: new_cases, dtype: float64
63129 63136    932.0
Name: new_cases, dtype: float64
63130 63137    1176.0
Name: new_cases, dtype: float64
63131 63138    1374.0
Name: new_cases, dtype: float64
63132 63139    1068.0
Name: new_cases, dtype: float64
63133 63140    1173.0
Name: new_cases, dtype: float64
63134 63141    1025.0
Name: new_cases, dtype: float64
63135 63142    920.0
Name: new_cases, dtype: float64
63136 63143    950.0
Name: new_cases, dtype: float64
63137 63144    1293.0
Name: new_cases, dtype: float64
63138 63145    1791.0
Name: new_cases, dtype: float64
63139 63146    1474.0
Name: new_cases, dtype: float64
63140 63147    1478.0
Name: new_cases, dtype: float64
63141 63148    989.0
Name: new_cases, dtype: float64
63142 63149    1423.0
Name: new_cases, dtype: float64
63143 63150    2032.0
Name: new_cases, dtype: float64
63144 63151    2066.0
Name: new_cases, dtype: float64
63145 63152    1820.0
Name: new_cases, dtype: float64
63146 63153    3149.0
Name: new_cases, dtype: float64
63147 63154    2316.0
Name: new_cases, dtype: float64
63148 63155    2079.0
Name: new_cases, dtype: float64
63149 63156    2291.0
Name: new_cases, dtype: float64
63150 63157    2194.0
Name: new_cases, dtype: float64
63151 63158    3286.0
Name: new_cases, dtype: float64
63152 63159    3908.0
Name: new_cases, dtype: float64
63153 63160    3878.0
Name: new_cases, dtype: float64
63154 63161    3581.0
Name: new_cases, dtype: float64
63155 63162    3989.0
Name: new_cases, dtype: float64
63156 63163    4219.0
Name: new_cases, dtype: float64
63157 63164    3928.0
Name: new_cases, dtype: float64
63158 63165    4709.0
Name: new_cases, dtype: float64
63159 63166    5318.0
Name: new_cases, dtype: float64
63160 63167    4673.0
Name: new_cases, dtype: float64
63161 63168    5162.0
Name: new_cases, dtype: float64
63162 63169    4140.0
Name: new_cases, dtype: float64
63163 63170    3945.0
Name: new_cases, dtype: float64
63164 63171    3927.0
Name: new_cases, dtype: float64
63165 63172    5097.0
Name: new_cases, dtype: float64
63166 63173    4836.0
Name: new_cases, dtype: float64
63167 63174    4238.0
Name: new_cases, dtype: float64
63168 63175    6495.0
Name: new_cases, dtype: float64
63169 63176    5203.0
Name: new_cases, dtype: float64
63170 63177    4290.0
Name: new_cases, dtype: float64
63171 63178    4512.0
Name: new_cases, dtype: float64
63172 63179    4440.0
Name: new_cases, dtype: float64
63173 63180    4397.0
Name: new_cases, dtype: float64
63174 63181    4320.0
Name: new_cases, dtype: float64
63175 63182    3334.0
Name: new_cases, dtype: float64
63176 63183    3929.0
Name: new_cases, dtype: float64
63177 63184    3806.0
Name: new_cases, dtype: float64
63178 63185    6360.0
Name: new_cases, dtype: float64
63179 63186    6393.0
Name: new_cases, dtype: float64
63180 63187    6268.0
Name: new_cases, dtype: float64
63181 63188    6819.0
Name: new_cases, dtype: float64
63182 63189    5595.0
Name: new_cases, dtype: float64
63183 63190    3951.0
Name: new_cases, dtype: float64
63184 63191    4136.0
Name: new_cases, dtype: float64
63185 63192    6635.0
Name: new_cases, dtype: float64
63186 63193    6212.0
Name: new_cases, dtype: float64
63187 63194    5525.0
Name: new_cases, dtype: float64
63188 63195    6697.0
Name: new_cases, dtype: float64
63189 63196    3870.0
Name: new_cases, dtype: float64
63190 63197    2219.0
Name: new_cases, dtype: float64
63191 63198    3221.0
Name: new_cases, dtype: float64
63192 63199    5415.0
Name: new_cases, dtype: float64
63193 63200    6197.0
Name: new_cases, dtype: float64
63194 63201    5047.0
Name: new_cases, dtype: float64
63195 63202    4153.0
Name: new_cases, dtype: float64
63196 63203    3470.0
Name: new_cases, dtype: float64
63197 63204    1893.0
Name: new_cases, dtype: float64
63198 63205    2804.0
Name: new_cases, dtype: float64
63199 63206    2982.0
Name: new_cases, dtype: float64
63200 63207    4428.0
Name: new_cases, dtype: float64
63201 63208    4045.0
Name: new_cases, dtype: float64
63202 63209    2967.0
Name: new_cases, dtype: float64
63203 63210    2141.0
Name: new_cases, dtype: float64
63204 63211    1238.0
Name: new_cases, dtype: float64
63205 63212    1894.0
Name: new_cases, dtype: float64
63206 63213    3292.0
Name: new_cases, dtype: float64
63207 63214    2610.0
Name: new_cases, dtype: float64
63208 63215    1198.0
Name: new_cases, dtype: float64
63209 63216    698.0
Name: new_cases, dtype: float64
63210 63217    609.0
Name: new_cases, dtype: float64
63211 63218    902.0
Name: new_cases, dtype: float64
63212 63219    1972.0
Name: new_cases, dtype: float64
63213 63220    2971.0
Name: new_cases, dtype: float64
63214 63221    2764.0
Name: new_cases, dtype: float64
63215 63222    1410.0
Name: new_cases, dtype: float64
63216 63223    1307.0
Name: new_cases, dtype: float64
63217 63224    856.0
Name: new_cases, dtype: float64
63218 63225    870.0
Name: new_cases, dtype: float64
63219 63226    2047.0
Name: new_cases, dtype: float64
63220 63227    3068.0
Name: new_cases, dtype: float64
63221 63228    2907.0
Name: new_cases, dtype: float64
63222 63229    2716.0
Name: new_cases, dtype: float64
63223 63230    1778.0
Name: new_cases, dtype: float64
63224 63231    1419.0
Name: new_cases, dtype: float64
63225 63232    696.0
Name: new_cases, dtype: float64
63226 63233    1358.0
Name: new_cases, dtype: float64
63227 63234    1926.0
Name: new_cases, dtype: float64
63228 63235    1513.0
Name: new_cases, dtype: float64
63229 63236    1438.0
Name: new_cases, dtype: float64
63230 63237    1241.0
Name: new_cases, dtype: float64
63231 63238    875.0
Name: new_cases, dtype: float64
63232 63239    573.0
Name: new_cases, dtype: float64
63233 63240    976.0
Name: new_cases, dtype: float64
63234 63241    1410.0
Name: new_cases, dtype: float64
63235 63242    1311.0
Name: new_cases, dtype: float64
63236 63243    1344.0
Name: new_cases, dtype: float64
63237 63244    1257.0
Name: new_cases, dtype: float64
63238 63245    844.0
Name: new_cases, dtype: float64
63239 63246    459.0
Name: new_cases, dtype: float64
63240 63247    1004.0
Name: new_cases, dtype: float64
63241 63248    1569.0
Name: new_cases, dtype: float64
63242 63249    1459.0
Name: new_cases, dtype: float64
63243 63250    1370.0
Name: new_cases, dtype: float64
63244 63251    1307.0
Name: new_cases, dtype: float64
63245 63252    1124.0
Name: new_cases, dtype: float64

63246 63253    578.0
Name: new_cases, dtype: float64
63247 63254    1048.0
Name: new_cases, dtype: float64
63248 63255    1652.0
Name: new_cases, dtype: float64
63249 63256    1576.0
Name: new_cases, dtype: float64
63250 63257    1561.0
Name: new_cases, dtype: float64
63251 63258    1370.0
Name: new_cases, dtype: float64
63252 63259    1160.0
Name: new_cases, dtype: float64
63253 63260    1079.0
Name: new_cases, dtype: float64
63254 63261    1279.0
Name: new_cases, dtype: float64
63255 63262    1862.0
Name: new_cases, dtype: float64
63256 63263    1860.0
Name: new_cases, dtype: float64
63257 63264    2020.0
Name: new_cases, dtype: float64
63258 63265    1707.0
Name: new_cases, dtype: float64
63259 63266    1337.0
Name: new_cases, dtype: float64
63260 63267    823.0
Name: new_cases, dtype: float64
63261 63268    1548.0
Name: new_cases, dtype: float64
63262 63269    2853.0
Name: new_cases, dtype: float64
63263 63270    3093.0
Name: new_cases, dtype: float64
63264 63271    2995.0
Name: new_cases, dtype: float64
63265 63272    2912.0
Name: new_cases, dtype: float64
63266 63273    2623.0
Name: new_cases, dtype: float64
63267 63274    1628.0
Name: new_cases, dtype: float64
63268 63275    2855.0
Name: new_cases, dtype: float64
63269 63276    4385.0
Name: new_cases, dtype: float64
63270 63277    4668.0
Name: new_cases, dtype: float64
63271 63278    4948.0
Name: new_cases, dtype: float64
63272 63279    4469.0
Name: new_cases, dtype: float64
63273 63280    4326.0
Name: new_cases, dtype: float64
63274 63281    2764.0
Name: new_cases, dtype: float64
63275 63282    4211.0
Name: new_cases, dtype: float64
63276 63283    6278.0
Name: new_cases, dtype: float64
63277 63284    6369.0
Name: new_cases, dtype: float64
63278 63285    7269.0
Name: new_cases, dtype: float64
63279 63286    6201.0
Name: new_cases, dtype: float64
63280 63287    2696.0
Name: new_cases, dtype: float64
63281 63288    6494.0
Name: new_cases, dtype: float64
63282 63289    5653.0
Name: new_cases, dtype: float64
63283 63290    8312.0
Name: new_cases, dtype: float64
63284 63291    9011.0
Name: new_cases, dtype: float64
63285 63292    9444.0
Name: new_cases, dtype: float64
63286 63293    8863.0
Name: new_cases, dtype: float64
63287 63294    7706.0
Name: new_cases, dtype: float64
63288 63295    4926.0
Name: new_cases, dtype: float64
63289 63296    3456.0
Name: new_cases, dtype: float64
63290 63297    6502.0
Name: new_cases, dtype: float64
63291 63298    10759.0
Name: new_cases, dtype: float64
63292 63299    11132.0
Name: new_cases, dtype: float64
63293 63300    10625.0
Name: new_cases, dtype: float64
63294 63301    9046.0
Name: new_cases, dtype: float64
63295 63302    5481.0
Name: new_cases, dtype: float64
63296 63303    7587.0
Name: new_cases, dtype: float64
63297 63304    9637.0
Name: new_cases, dtype: float64
63298 63305    11265.0
Name: new_cases, dtype: float64
63299 63306    10167.0
Name: new_cases, dtype: float64
63300 63307    9082.0
Name: new_cases, dtype: float64
63301 63308    7263.0
Name: new_cases, dtype: float64
63302 63309    4609.0
Name: new_cases, dtype: float64
63303 63310    6700.0
Name: new_cases, dtype: float64
63304 63311    9288.0
Name: new_cases, dtype: float64
63305 63312    9055.0
Name: new_cases, dtype: float64
63306 63313    8637.0
Name: new_cases, dtype: float64
63307 63314    6566.0
Name: new_cases, dtype: float64
63308 63315    3874.0
Name: new_cases, dtype: float64
63309 63316    1890.0
Name: new_cases, dtype: float64
63310 63317    1933.0
Name: new_cases, dtype: float64
63311 63318    4814.0
Name: new_cases, dtype: float64
63312 63319    7325.0
Name: new_cases, dtype: float64
63313 63320    8053.0
Name: new_cases, dtype: float64
63314 63321    6296.0
Name: new_cases, dtype: float64
63315 63322    5077.0
Name: new_cases, dtype: float64
63316 63323    2837.0
Name: new_cases, dtype: float64
63317 63324    3597.0
Name: new_cases, dtype: float64
63318 63325    5307.0
Name: new_cases, dtype: float64
63319 63326    5216.0
Name: new_cases, dtype: float64
63320 63327    4604.0
Name: new_cases, dtype: float64
63321 63328    3706.0
Name: new_cases, dtype: float64
63322 63329    2680.0
Name: new_cases, dtype: float64
63323 63330    1645.0
Name: new_cases, dtype: float64
63324 63331    2527.0
Name: new_cases, dtype: float64
63325 63332    3607.0
Name: new_cases, dtype: float64
63326 63333    3427.0
Name: new_cases, dtype: float64
63327 63334    2796.0
Name: new_cases, dtype: float64
63328 63335    2328.0
Name: new_cases, dtype: float64
63329 63336    1936.0
Name: new_cases, dtype: float64
63330 63337    1253.0
Name: new_cases, dtype: float64
63331 63338    1692.0
Name: new_cases, dtype: float64
63332 63339    2584.0
Name: new_cases, dtype: float64
63333 63340    2365.0
Name: new_cases, dtype: float64
63334 63341    1951.0
Name: new_cases, dtype: float64
63335 63342    1593.0
Name: new_cases, dtype: float64
63336 63343    1219.0
Name: new_cases, dtype: float64
63337 63344    726.0
Name: new_cases, dtype: float64
63338 63345    1130.0
Name: new_cases, dtype: float64
63339 63346    1680.0
Name: new_cases, dtype: float64
63340 63347    1541.0
Name: new_cases, dtype: float64
63341 63348    1376.0
Name: new_cases, dtype: float64
63342 63349    1145.0
Name: new_cases, dtype: float64
63343 63350    677.0
Name: new_cases, dtype: float64
63344 63351    493.0
Name: new_cases, dtype: float64
63345 63352    905.0
Name: new_cases, dtype: float64
63346 63353    1416.0
Name: new_cases, dtype: float64
63347 63354    1190.0
Name: new_cases, dtype: float64
63348 63355    1039.0
Name: new_cases, dtype: float64
63349 63356    718.0
Name: new_cases, dtype: float64
63350 63357    426.0
Name: new_cases, dtype: float64
63351 63358    382.0
Name: new_cases, dtype: float64
63352 63359    633.0
Name: new_cases, dtype: float64
63353 63360    780.0
Name: new_cases, dtype: float64
63354 63361    657.0
Name: new_cases, dtype: float64
63355 63362    647.0
Name: new_cases, dtype: float64
63356 63363    416.0
Name: new_cases, dtype: float64
63357 63364    258.0
Name: new_cases, dtype: float64
63358 63365    164.0
Name: new_cases, dtype: float64
63359 63366    213.0
Name: new_cases, dtype: float64
63360 63367    396.0
Name: new_cases, dtype: float64
63361 63368    448.0
Name: new_cases, dtype: float64
63362 63369    465.0
Name: new_cases, dtype: float64
63363 63370    350.0
Name: new_cases, dtype: float64
63364 63371    156.0
Name: new_cases, dtype: float64
63365 63372    174.0
Name: new_cases, dtype: float64
63366 63373    275.0
Name: new_cases, dtype: float64
63367 63374    315.0
Name: new_cases, dtype: float64
63368 63375    269.0
Name: new_cases, dtype: float64
63369 63376    300.0
Name: new_cases, dtype: float64
63370 63377    137.0
Name: new_cases, dtype: float64
63371 63378    81.0
Name: new_cases, dtype: float64
63372 63379    117.0
Name: new_cases, dtype: float64
63373 63380    179.0
Name: new_cases, dtype: float64
63374 63381    206.0
Name: new_cases, dtype: float64
63375 63382    199.0
Name: new_cases, dtype: float64
63376 63383    0.0
Name: new_cases, dtype: float64
63377 63384    0.0
Name: new_cases, dtype: float64
63378 63385    255.0
Name: new_cases, dtype: float64
63379 63386    57.0
Name: new_cases, dtype: float64
63380 63387    107.0
Name: new_cases, dtype: float64
63381 63388    113.0
Name: new_cases, dtype: float64
63382 63389    106.0
Name: new_cases, dtype: float64
63383 63390    0.0
Name: new_cases, dtype: float64
63384 63391    0.0
Name: new_cases, dtype: float64
63385 63392    202.0
Name: new_cases, dtype: float64
63386 63393    54.0
Name: new_cases, dtype: float64
63387 63394    91.0
Name: new_cases, dtype: float64
63388 63395    69.0
Name: new_cases, dtype: float64
63389 63396    66.0
Name: new_cases, dtype: float64
63390 63397    0.0
Name: new_cases, dtype: float64
63391 63398    0.0
Name: new_cases, dtype: float64
63392 63399    132.0
Name: new_cases, dtype: float64
63393 63400    34.0
Name: new_cases, dtype: float64
63394 63401    52.0
Name: new_cases, dtype: float64
63395 63402    32.0
Name: new_cases, dtype: float64
63396 63403    37.0
Name: new_cases, dtype: float64
63397 63404    0.0
Name: new_cases, dtype: float64
63398 63405    0.0
Name: new_cases, dtype: float64
63399 63406    65.0
Name: new_cases, dtype: float64
63400 63407    32.0
Name: new_cases, dtype: float64
63401 63408    44.0
Name: new_cases, dtype: float64
63402 63409    55.0
Name: new_cases, dtype: float64
63403 63410    44.0
Name: new_cases, dtype: float64
63404 63411    0.0
Name: new_cases, dtype: float64
63405 63412    0.0
Name: new_cases, dtype: float64
63406 63413    102.0
Name: new_cases, dtype: float64
63407 63414    17.0
Name: new_cases, dtype: float64
63408 63415    56.0
Name: new_cases, dtype: float64
63409 63416    49.0
Name: new_cases, dtype: float64
63410 63417    64.0
Name: new_cases, dtype: float64
63411 63418    0.0
Name: new_cases, dtype: float64
63412 63419    0.0
Name: new_cases, dtype: float64
63413 63420    139.0
Name: new_cases, dtype: float64
63414 63421    25.0
Name: new_cases, dtype: float64
63415 63422    56.0
Name: new_cases, dtype: float64
63416 63423    71.0
Name: new_cases, dtype: float64
63417 63424    85.0
Name: new_cases, dtype: float64
63418 63425    0.0
Name: new_cases, dtype: float64
63419 63426    0.0
Name: new_cases, dtype: float64

63420 63427    161.0
Name: new_cases, dtype: float64
63421 63428    26.0
Name: new_cases, dtype: float64
63422 63429    74.0
Name: new_cases, dtype: float64
63423 63430    65.0
Name: new_cases, dtype: float64
63424 63431    64.0
Name: new_cases, dtype: float64
63425 63432    0.0
Name: new_cases, dtype: float64
63426 63433    0.0
Name: new_cases, dtype: float64
63427 63434    155.0
Name: new_cases, dtype: float64
63428 63435    26.0
Name: new_cases, dtype: float64
63429 63436    59.0
Name: new_cases, dtype: float64
63430 63437    72.0
Name: new_cases, dtype: float64
63431 63438    52.0
Name: new_cases, dtype: float64
63432 63439    0.0
Name: new_cases, dtype: float64
63433 63440    0.0
Name: new_cases, dtype: float64
63434 63441    156.0
Name: new_cases, dtype: float64
63435 63442    35.0
Name: new_cases, dtype: float64
63436 63443    80.0
Name: new_cases, dtype: float64
63437 63444    86.0
Name: new_cases, dtype: float64
63438 63445    104.0
Name: new_cases, dtype: float64
63439 63446    0.0
Name: new_cases, dtype: float64
63440 63447    0.0
Name: new_cases, dtype: float64
63441 63448    188.0
Name: new_cases, dtype: float64
63442 63449    45.0
Name: new_cases, dtype: float64
63443 63450    109.0
Name: new_cases, dtype: float64
63444 63451    123.0
Name: new_cases, dtype: float64
63445 63452    0.0
Name: new_cases, dtype: float64
63446 63453    0.0
Name: new_cases, dtype: float64
63447 63454    0.0
Name: new_cases, dtype: float64
63448 63455    340.0
Name: new_cases, dtype: float64
63449 63456    82.0
Name: new_cases, dtype: float64
63450 63457    134.0
Name: new_cases, dtype: float64
63451 63458    180.0
Name: new_cases, dtype: float64
63452 63459    189.0
Name: new_cases, dtype: float64
63453 63460    0.0
Name: new_cases, dtype: float64
63454 63461    0.0
Name: new_cases, dtype: float64
63455 63462    521.0
Name: new_cases, dtype: float64
63456 63463    110.0
Name: new_cases, dtype: float64
63457 63464    194.0
Name: new_cases, dtype: float64
63458 63465    262.0
Name: new_cases, dtype: float64
63459 63466    247.0
Name: new_cases, dtype: float64
63460 63467    0.0
Name: new_cases, dtype: float64
63461 63468    0.0
Name: new_cases, dtype: float64
63462 63469    648.0
Name: new_cases, dtype: float64
63463 63470    130.0
Name: new_cases, dtype: float64
63464 63471    246.0
Name: new_cases, dtype: float64
63465 63472    345.0
Name: new_cases, dtype: float64
63466 63473    323.0
Name: new_cases, dtype: float64
63467 63474    0.0
Name: new_cases, dtype: float64
63468 63475    0.0
Name: new_cases, dtype: float64
63469 63476    873.0
Name: new_cases, dtype: float64
63470 63477    246.0
Name: new_cases, dtype: float64
63471 63478    371.0
Name: new_cases, dtype: float64
63472 63479    458.0
Name: new_cases, dtype: float64
63473 63480    479.0
Name: new_cases, dtype: float64
63474 63481    0.0
Name: new_cases, dtype: float64
63475 63482    0.0
Name: new_cases, dtype: float64
63476 63483    1072.0
Name: new_cases, dtype: float64
63477 63484    289.0
Name: new_cases, dtype: float64
63478 63485    501.0
Name: new_cases, dtype: float64
63479 63486    526.0
Name: new_cases, dtype: float64
63480 63487    531.0
Name: new_cases, dtype: float64
63481 63488    0.0
Name: new_cases, dtype: float64
63482 63489    0.0
Name: new_cases, dtype: float64
63483 63490    1183.0
Name: new_cases, dtype: float64
63484 63491    265.0
Name: new_cases, dtype: float64
63485 63492    546.0
Name: new_cases, dtype: float64
63486 63493    633.0
Name: new_cases, dtype: float64
63487 63494    679.0
Name: new_cases, dtype: float64
63488 63495    0.0
Name: new_cases, dtype: float64
63489 63496    0.0
Name: new_cases, dtype: float64
63490 63497    1492.0
Name: new_cases, dtype: float64
63491 63498    294.0
Name: new_cases, dtype: float64
63492 63499    629.0
Name: new_cases, dtype: float64
63493 63500    837.0
Name: new_cases, dtype: float64
63494 63501    774.0
Name: new_cases, dtype: float64
63495 63502    0.0
Name: new_cases, dtype: float64
63496 63503    0.0
Name: new_cases, dtype: float64
63497 63504    2046.0
Name: new_cases, dtype: float64
63498 63505    455.0
Name: new_cases, dtype: float64
63499 63506    814.0
Name: new_cases, dtype: float64
63500 63507    1141.0
Name: new_cases, dtype: float64
63501 63508    1249.0
Name: new_cases, dtype: float64
63502 63509    0.0
Name: new_cases, dtype: float64
63503 63510    0.0
Name: new_cases, dtype: float64
63504 63511    3274.0
Name: new_cases, dtype: float64
63505 63512    859.0
Name: new_cases, dtype: float64
63506 63513    1668.0
Name: new_cases, dtype: float64
63507 63514    2361.0
Name: new_cases, dtype: float64
63508 63515    2548.0
Name: new_cases, dtype: float64
63509 63516    0.0
Name: new_cases, dtype: float64
63510 63517    0.0
Name: new_cases, dtype: float64
63511 63518    6688.0
Name: new_cases, dtype: float64
63512 63519    1701.0
Name: new_cases, dtype: float64
63513 63520    3125.0
Name: new_cases, dtype: float64
63514 63521    4039.0
Name: new_cases, dtype: float64
63515 63522    4041.0
Name: new_cases, dtype: float64
63516 63523    0.0
Name: new_cases, dtype: float64
63517 63524    0.0
Name: new_cases, dtype: float64
63518 63525    11211.0
Name: new_cases, dtype: float64
63519 63526    1867.0
Name: new_cases, dtype: float64
63520 63527    2595.0
Name: new_cases, dtype: float64
63521 63528    6268.0
Name: new_cases, dtype: float64
63522 63529    6804.0
Name: new_cases, dtype: float64
63523 63530    0.0
Name: new_cases, dtype: float64
63524 63531    0.0
Name: new_cases, dtype: float64
63525 63532    17834.0
Name: new_cases, dtype: float64
63526 63533    4588.0
Name: new_cases, dtype: float64
63527 63534    8434.0
Name: new_cases, dtype: float64
63528 63535    8394.0
Name: new_cases, dtype: float64
63529 63536    8370.0
Name: new_cases, dtype: float64
63530 63537    0.0
Name: new_cases, dtype: float64
63531 63538    0.0
Name: new_cases, dtype: float64
63532 63539    21060.0
Name: new_cases, dtype: float64
63533 63540    5323.0
Name: new_cases, dtype: float64
63534 63541    10265.0
Name: new_cases, dtype: float64
63535 63542    10767.0
Name: new_cases, dtype: float64
63536 63543    11289.0
Name: new_cases, dtype: float64
63537 63544    0.0
Name: new_cases, dtype: float64
63538 63545    0.0
Name: new_cases, dtype: float64
63539 63546    27209.0
Name: new_cases, dtype: float64
63540 63547    6518.0
Name: new_cases, dtype: float64
63541 63548    12637.0
Name: new_cases, dtype: float64
63542 63549    12165.0
Name: new_cases, dtype: float64
63543 63550    11871.0
Name: new_cases, dtype: float64
63544 63551    0.0
Name: new_cases, dtype: float64
63545 63552    0.0
Name: new_cases, dtype: float64
63546 63553    27830.0
Name: new_cases, dtype: float64
63547 63554    6390.0
Name: new_cases, dtype: float64
63548 63555    11152.0
Name: new_cases, dtype: float64
63549 63556    10466.0
Name: new_cases, dtype: float64
63550 63557    10143.0
Name: new_cases, dtype: float64
63551 63558    0.0
Name: new_cases, dtype: float64
63552 63559    0.0
Name: new_cases, dtype: float64
63553 63560    22699.0
Name: new_cases, dtype: float64
63554 63561    4311.0
Name: new_cases, dtype: float64
63555 63562    6849.0
Name: new_cases, dtype: float64
63556 63563    7310.0
Name: new_cases, dtype: float64
63557 63564    6884.0
Name: new_cases, dtype: float64
63558 63565    0.0
Name: new_cases, dtype: float64
63559 63566    0.0
Name: new_cases, dtype: float64
63560 63567    16017.0
Name: new_cases, dtype: float64
63561 63568    3575.0
Name: new_cases, dtype: float64
63562 63569    5506.0
Name: new_cases, dtype: float64
63563 63570    5298.0
Name: new_cases, dtype: float64
63564 63571    4977.0
Name: new_cases, dtype: float64
63565 63572    0.0
Name: new_cases, dtype: float64
63566 63573    0.0
Name: new_cases, dtype: float64
63567 63574    10105.0
Name: new_cases, dtype: float64
63568 63575    1985.0
Name: new_cases, dtype: float64
63569 63576    3359.0
Name: new_cases, dtype: float64
63570 63577    3586.0
Name: new_cases, dtype: float64
63571 63578    0.0
Name: new_cases, dtype: float64
63572 63579    0.0
Name: new_cases, dtype: float64
63573 63580    0.0
Name: new_cases, dtype: float64
63574 63581    7989.0
Name: new_cases, dtype: float64
63575 63582    1370.0
Name: new_cases, dtype: float64
63576 63583    3005.0
Name: new_cases, dtype: float64
63577 63584    3361.0
Name: new_cases, dtype: float64
63578 63585    3360.0
Name: new_cases, dtype: float64
63579 63586    0.0
Name: new_cases, dtype: float64
63580 63587    0.0
Name: new_cases, dtype: float64
63581 63588    5865.0
Name: new_cases, dtype: float64
63582 63589    2429.0
Name: new_cases, dtype: float64
63583 63590    5270.0
Name: new_cases, dtype: float64
63584 63591    6454.0
Name: new_cases, dtype: float64
63585 63592    6524.0
Name: new_cases, dtype: float64
63586 Series([], Name: new_cases, dtype: float64)
63587 Series([], Name: new_cases, dtype: float64)

63588 Series([], Name: new_cases, dtype: float64)
63589 Series([], Name: new_cases, dtype: float64)
63590 Series([], Name: new_cases, dtype: float64)
63591 62918    2.0
Name: new_cases, dtype: float64
63592 62919    0.0
Name: new_cases, dtype: float64
63595 63602    9.0
Name: new_cases, dtype: float64
63596 63603    7.0
Name: new_cases, dtype: float64
63597 63604    0.0
Name: new_cases, dtype: float64
63598 63605    8.0
Name: new_cases, dtype: float64
63599 63606    11.0
Name: new_cases, dtype: float64
63600 63607    16.0
Name: new_cases, dtype: float64
63601 63608    18.0
Name: new_cases, dtype: float64
63602 63609    31.0
Name: new_cases, dtype: float64
63603 63610    22.0
Name: new_cases, dtype: float64
63604 63611    15.0
Name: new_cases, dtype: float64
63605 63612    9.0
Name: new_cases, dtype: float64
63606 63613    40.0
Name: new_cases, dtype: float64
63607 63614    30.0
Name: new_cases, dtype: float64
63608 63615    80.0
Name: new_cases, dtype: float64
63609 63616    79.0
Name: new_cases, dtype: float64
63610 63617    64.0
Name: new_cases, dtype: float64
63611 63618    95.0
Name: new_cases, dtype: float64
63612 63619    20.0
Name: new_cases, dtype: float64
63613 63620    60.0
Name: new_cases, dtype: float64
63614 63621    89.0
Name: new_cases, dtype: float64
63615 63622    65.0
Name: new_cases, dtype: float64
63616 63623    88.0
Name: new_cases, dtype: float64
63617 63624    73.0
Name: new_cases, dtype: float64
63618 63625    57.0
Name: new_cases, dtype: float64
63619 63626    66.0
Name: new_cases, dtype: float64
63620 63627    49.0
Name: new_cases, dtype: float64
63621 63628    85.0
Name: new_cases, dtype: float64
63622 63629    99.0
Name: new_cases, dtype: float64
63623 63630    45.0
Name: new_cases, dtype: float64
63624 63631    53.0
Name: new_cases, dtype: float64
63625 63632    69.0
Name: new_cases, dtype: float64
63626 63633    76.0
Name: new_cases, dtype: float64
63627 63634    24.0
Name: new_cases, dtype: float64
63628 63635    30.0
Name: new_cases, dtype: float64
63629 63636    32.0
Name: new_cases, dtype: float64
63630 63637    27.0
Name: new_cases, dtype: float64
63631 63638    14.0
Name: new_cases, dtype: float64
63632 63639    12.0
Name: new_cases, dtype: float64
63633 63640    10.0
Name: new_cases, dtype: float64
63634 63641    9.0
Name: new_cases, dtype: float64
63635 63642    7.0
Name: new_cases, dtype: float64
63636 63643    12.0
Name: new_cases, dtype: float64
63637 63644    15.0
Name: new_cases, dtype: float64
63638 63645    6.0
Name: new_cases, dtype: float64
63639 63646    11.0
Name: new_cases, dtype: float64
63640 63647    2.0
Name: new_cases, dtype: float64
63641 63648    5.0
Name: new_cases, dtype: float64
63642 63649    7.0
Name: new_cases, dtype: float64
63643 63650    4.0
Name: new_cases, dtype: float64
63644 63651    0.0
Name: new_cases, dtype: float64
63645 63652    1.0
Name: new_cases, dtype: float64
63646 63653    2.0
Name: new_cases, dtype: float64
63647 63654    0.0
Name: new_cases, dtype: float64
63648 63655    3.0
Name: new_cases, dtype: float64
63649 63656    2.0
Name: new_cases, dtype: float64
63650 63657    0.0
Name: new_cases, dtype: float64
63651 63658    1.0
Name: new_cases, dtype: float64
63652 63659    0.0
Name: new_cases, dtype: float64
63653 63660    1.0
Name: new_cases, dtype: float64
63654 63661    0.0
Name: new_cases, dtype: float64
63655 63662    0.0
Name: new_cases, dtype: float64
63656 63663    0.0
Name: new_cases, dtype: float64
63657 63664    2.0
Name: new_cases, dtype: float64
63658 63665    0.0
Name: new_cases, dtype: float64
63659 63666    0.0
Name: new_cases, dtype: float64
63660 63667    0.0
Name: new_cases, dtype: float64
63661 63668    0.0
Name: new_cases, dtype: float64
63662 63669    0.0
Name: new_cases, dtype: float64
63663 63670    1.0
Name: new_cases, dtype: float64
63664 63671    0.0
Name: new_cases, dtype: float64
63665 63672    0.0
Name: new_cases, dtype: float64
63666 63673    0.0
Name: new_cases, dtype: float64
63667 63674    0.0
Name: new_cases, dtype: float64
63668 63675    0.0
Name: new_cases, dtype: float64
63669 63676    0.0
Name: new_cases, dtype: float64
63670 63677    1.0
Name: new_cases, dtype: float64
63671 63678    0.0
Name: new_cases, dtype: float64
63672 63679    0.0
Name: new_cases, dtype: float64
63673 63680    1.0
Name: new_cases, dtype: float64
63674 63681    0.0
Name: new_cases, dtype: float64
63675 63682    0.0
Name: new_cases, dtype: float64
63676 63683    0.0
Name: new_cases, dtype: float64
63677 63684    1.0
Name: new_cases, dtype: float64
63678 63685    0.0
Name: new_cases, dtype: float64
63679 63686    0.0
Name: new_cases, dtype: float64
63680 63687    1.0
Name: new_cases, dtype: float64
63681 63688    0.0
Name: new_cases, dtype: float64
63682 63689    0.0
Name: new_cases, dtype: float64
63683 63690    0.0
Name: new_cases, dtype: float64
63684 63691    0.0
Name: new_cases, dtype: float64
63685 63692    0.0
Name: new_cases, dtype: float64
63686 63693    0.0
Name: new_cases, dtype: float64
63687 63694    0.0
Name: new_cases, dtype: float64
63688 63695    1.0
Name: new_cases, dtype: float64
63689 63696    0.0
Name: new_cases, dtype: float64
63690 63697    0.0
Name: new_cases, dtype: float64
63691 63698    0.0
Name: new_cases, dtype: float64
63692 63699    0.0
Name: new_cases, dtype: float64
63693 63700    0.0
Name: new_cases, dtype: float64
63694 63701    1.0
Name: new_cases, dtype: float64
63695 63702    2.0
Name: new_cases, dtype: float64
63696 63703    1.0
Name: new_cases, dtype: float64
63697 63704    1.0
Name: new_cases, dtype: float64
63698 63705    0.0
Name: new_cases, dtype: float64
63699 63706    2.0
Name: new_cases, dtype: float64
63700 63707    1.0
Name: new_cases, dtype: float64
63701 63708    0.0
Name: new_cases, dtype: float64
63702 63709    0.0
Name: new_cases, dtype: float64
63703 63710    0.0
Name: new_cases, dtype: float64
63704 63711    0.0
Name: new_cases, dtype: float64
63705 63712    2.0
Name: new_cases, dtype: float64
63706 63713    1.0
Name: new_cases, dtype: float64
63707 63714    2.0
Name: new_cases, dtype: float64
63708 63715    0.0
Name: new_cases, dtype: float64
63709 63716    1.0
Name: new_cases, dtype: float64
63710 63717    1.0
Name: new_cases, dtype: float64
63711 63718    2.0
Name: new_cases, dtype: float64
63712 63719    1.0
Name: new_cases, dtype: float64
63713 63720    5.0
Name: new_cases, dtype: float64
63714 63721    0.0
Name: new_cases, dtype: float64
63715 63722    0.0
Name: new_cases, dtype: float64
63716 63723    0.0
Name: new_cases, dtype: float64
63717 63724    2.0
Name: new_cases, dtype: float64
63718 63725    1.0
Name: new_cases, dtype: float64
63719 63726    0.0
Name: new_cases, dtype: float64
63720 63727    0.0
Name: new_cases, dtype: float64
63721 63728    0.0
Name: new_cases, dtype: float64
63722 63729    0.0
Name: new_cases, dtype: float64
63723 63730    0.0
Name: new_cases, dtype: float64
63724 63731    0.0
Name: new_cases, dtype: float64
63725 63732    2.0
Name: new_cases, dtype: float64
63726 63733    0.0
Name: new_cases, dtype: float64
63727 63734    1.0
Name: new_cases, dtype: float64
63728 63735    0.0
Name: new_cases, dtype: float64
63729 63736    2.0
Name: new_cases, dtype: float64
63730 63737    1.0
Name: new_cases, dtype: float64
63731 63738    0.0
Name: new_cases, dtype: float64
63732 63739    0.0
Name: new_cases, dtype: float64
63733 63740    1.0
Name: new_cases, dtype: float64
63734 63741    1.0
Name: new_cases, dtype: float64
63735 63742    2.0
Name: new_cases, dtype: float64
63736 63743    0.0
Name: new_cases, dtype: float64
63737 63744    4.0
Name: new_cases, dtype: float64
63738 63745    7.0
Name: new_cases, dtype: float64
63739 63746    3.0
Name: new_cases, dtype: float64
63740 63747    4.0
Name: new_cases, dtype: float64
63741 63748    11.0
Name: new_cases, dtype: float64
63742 63749    13.0
Name: new_cases, dtype: float64
63743 63750    8.0
Name: new_cases, dtype: float64
63744 63751    14.0
Name: new_cases, dtype: float64
63745 63752    8.0
Name: new_cases, dtype: float64
63746 63753    3.0
Name: new_cases, dtype: float64
63747 63754    8.0
Name: new_cases, dtype: float64
63748 63755    6.0
Name: new_cases, dtype: float64
63749 63756    20.0
Name: new_cases, dtype: float64
63750 63757    3.0
Name: new_cases, dtype: float64
63751 63758    3.0
Name: new_cases, dtype: float64
63752 63759    4.0
Name: new_cases, dtype: float64
63753 63760    6.0
Name: new_cases, dtype: float64
63754 63761    4.0
Name: new_cases, dtype: float64
63755 63762    4.0
Name: new_cases, dtype: float64
63756 63763    7.0
Name: new_cases, dtype: float64
63757 63764    16.0
Name: new_cases, dtype: float64
63758 63765    12.0
Name: new_cases, dtype: float64
63759 63766    3.0
Name: new_cases, dtype: float64
63760 63767    13.0
Name: new_cases, dtype: float64
63761 63768    8.0
Name: new_cases, dtype: float64
63762 63769    5.0
Name: new_cases, dtype: float64
63763 63770    10.0
Name: new_cases, dtype: float64

63764 63771    8.0
Name: new_cases, dtype: float64
63765 63772    6.0
Name: new_cases, dtype: float64
63766 63773    9.0
Name: new_cases, dtype: float64
63767 63774    4.0
Name: new_cases, dtype: float64
63768 63775    5.0
Name: new_cases, dtype: float64
63769 63776    5.0
Name: new_cases, dtype: float64
63770 63777    5.0
Name: new_cases, dtype: float64
63771 63778    8.0
Name: new_cases, dtype: float64
63772 63779    5.0
Name: new_cases, dtype: float64
63773 63780    2.0
Name: new_cases, dtype: float64
63774 63781    9.0
Name: new_cases, dtype: float64
63775 63782    5.0
Name: new_cases, dtype: float64
63776 63783    7.0
Name: new_cases, dtype: float64
63777 63784    7.0
Name: new_cases, dtype: float64
63778 63785    1.0
Name: new_cases, dtype: float64
63779 63786    5.0
Name: new_cases, dtype: float64
63780 63787    2.0
Name: new_cases, dtype: float64
63781 63788    7.0
Name: new_cases, dtype: float64
63782 63789    3.0
Name: new_cases, dtype: float64
63783 63790    4.0
Name: new_cases, dtype: float64
63784 63791    4.0
Name: new_cases, dtype: float64
63785 63792    1.0
Name: new_cases, dtype: float64
63786 63793    3.0
Name: new_cases, dtype: float64
63787 63794    3.0
Name: new_cases, dtype: float64
63788 63795    6.0
Name: new_cases, dtype: float64
63789 63796    15.0
Name: new_cases, dtype: float64
63790 63797    17.0
Name: new_cases, dtype: float64
63791 63798    24.0
Name: new_cases, dtype: float64
63792 63799    77.0
Name: new_cases, dtype: float64
63793 63800    0.0
Name: new_cases, dtype: float64
63794 63801    70.0
Name: new_cases, dtype: float64
63795 63802    42.0
Name: new_cases, dtype: float64
63796 63803    57.0
Name: new_cases, dtype: float64
63797 63804    36.0
Name: new_cases, dtype: float64
63798 63805    49.0
Name: new_cases, dtype: float64
63799 63806    40.0
Name: new_cases, dtype: float64
63800 63807    22.0
Name: new_cases, dtype: float64
63801 63808    40.0
Name: new_cases, dtype: float64
63802 63809    32.0
Name: new_cases, dtype: float64
63803 63810    33.0
Name: new_cases, dtype: float64
63804 63811    41.0
Name: new_cases, dtype: float64
63805 63812    40.0
Name: new_cases, dtype: float64
63806 63813    63.0
Name: new_cases, dtype: float64
63807 63814    49.0
Name: new_cases, dtype: float64
63808 63815    59.0
Name: new_cases, dtype: float64
63809 63816    101.0
Name: new_cases, dtype: float64
63810 63817    91.0
Name: new_cases, dtype: float64
63811 63818    95.0
Name: new_cases, dtype: float64
63812 63819    106.0
Name: new_cases, dtype: float64
63813 63820    87.0
Name: new_cases, dtype: float64
63814 63821    66.0
Name: new_cases, dtype: float64
63815 63822    56.0
Name: new_cases, dtype: float64
63816 63823    86.0
Name: new_cases, dtype: float64
63817 63824    89.0
Name: new_cases, dtype: float64
63818 63825    80.0
Name: new_cases, dtype: float64
63819 63826    92.0
Name: new_cases, dtype: float64
63820 63827    69.0
Name: new_cases, dtype: float64
63821 63828    57.0
Name: new_cases, dtype: float64
63822 63829    46.0
Name: new_cases, dtype: float64
63823 63830    92.0
Name: new_cases, dtype: float64
63824 63831    37.0
Name: new_cases, dtype: float64
63825 63832    38.0
Name: new_cases, dtype: float64
63826 63833    40.0
Name: new_cases, dtype: float64
63827 63834    86.0
Name: new_cases, dtype: float64
63828 63835    54.0
Name: new_cases, dtype: float64
63829 63836    56.0
Name: new_cases, dtype: float64
63830 63837    70.0
Name: new_cases, dtype: float64
63831 63838    97.0
Name: new_cases, dtype: float64
63832 63839    48.0
Name: new_cases, dtype: float64
63833 63840    78.0
Name: new_cases, dtype: float64
63834 63841    68.0
Name: new_cases, dtype: float64
63835 63842    25.0
Name: new_cases, dtype: float64
63836 63843    41.0
Name: new_cases, dtype: float64
63837 63844    26.0
Name: new_cases, dtype: float64
63838 63845    32.0
Name: new_cases, dtype: float64
63839 63846    28.0
Name: new_cases, dtype: float64
63840 63847    22.0
Name: new_cases, dtype: float64
63841 63848    24.0
Name: new_cases, dtype: float64
63842 63849    15.0
Name: new_cases, dtype: float64
63843 63850    23.0
Name: new_cases, dtype: float64
63844 63851    13.0
Name: new_cases, dtype: float64
63845 63852    28.0
Name: new_cases, dtype: float64
63846 63853    18.0
Name: new_cases, dtype: float64
63847 63854    10.0
Name: new_cases, dtype: float64
63848 63855    16.0
Name: new_cases, dtype: float64
63849 63856    3.0
Name: new_cases, dtype: float64
63850 63857    16.0
Name: new_cases, dtype: float64
63851 63858    10.0
Name: new_cases, dtype: float64
63852 63859    11.0
Name: new_cases, dtype: float64
63853 63860    5.0
Name: new_cases, dtype: float64
63854 63861    20.0
Name: new_cases, dtype: float64
63855 63862    18.0
Name: new_cases, dtype: float64
63856 63863    8.0
Name: new_cases, dtype: float64
63857 63864    12.0
Name: new_cases, dtype: float64
63858 63865    9.0
Name: new_cases, dtype: float64
63859 63866    14.0
Name: new_cases, dtype: float64
63860 63867    11.0
Name: new_cases, dtype: float64
63861 63868    23.0
Name: new_cases, dtype: float64
63862 63869    25.0
Name: new_cases, dtype: float64
63863 63870    10.0
Name: new_cases, dtype: float64
63864 63871    11.0
Name: new_cases, dtype: float64
63865 63872    21.0
Name: new_cases, dtype: float64
63866 63873    0.0
Name: new_cases, dtype: float64
63867 63874    35.0
Name: new_cases, dtype: float64
63868 63875    14.0
Name: new_cases, dtype: float64
63869 63876    14.0
Name: new_cases, dtype: float64
63870 63877    6.0
Name: new_cases, dtype: float64
63871 63878    14.0
Name: new_cases, dtype: float64
63872 63879    10.0
Name: new_cases, dtype: float64
63873 63880    10.0
Name: new_cases, dtype: float64
63874 63881    8.0
Name: new_cases, dtype: float64
63875 63882    15.0
Name: new_cases, dtype: float64
63876 63883    13.0
Name: new_cases, dtype: float64
63877 63884    5.0
Name: new_cases, dtype: float64
63878 63885    7.0
Name: new_cases, dtype: float64
63879 63886    7.0
Name: new_cases, dtype: float64
63880 63887    7.0
Name: new_cases, dtype: float64
63881 63888    10.0
Name: new_cases, dtype: float64
63882 63889    16.0
Name: new_cases, dtype: float64
63883 63890    17.0
Name: new_cases, dtype: float64
63884 63891    21.0
Name: new_cases, dtype: float64
63885 63892    14.0
Name: new_cases, dtype: float64
63886 63893    11.0
Name: new_cases, dtype: float64
63887 63894    16.0
Name: new_cases, dtype: float64
63888 63895    0.0
Name: new_cases, dtype: float64
63889 63896    0.0
Name: new_cases, dtype: float64
63890 63897    0.0
Name: new_cases, dtype: float64
63891 63898    0.0
Name: new_cases, dtype: float64
63892 63899    43.0
Name: new_cases, dtype: float64
63893 63900    10.0
Name: new_cases, dtype: float64
63894 63901    18.0
Name: new_cases, dtype: float64
63895 63902    0.0
Name: new_cases, dtype: float64
63896 63903    0.0
Name: new_cases, dtype: float64
63897 63904    0.0
Name: new_cases, dtype: float64
63898 63905    0.0
Name: new_cases, dtype: float64
63899 63906    41.0
Name: new_cases, dtype: float64
63900 63907    16.0
Name: new_cases, dtype: float64
63901 63908    21.0
Name: new_cases, dtype: float64
63902 63909    13.0
Name: new_cases, dtype: float64
63903 63910    22.0
Name: new_cases, dtype: float64
63904 63911    13.0
Name: new_cases, dtype: float64
63905 63912    10.0
Name: new_cases, dtype: float64
63906 63913    8.0
Name: new_cases, dtype: float64
63907 63914    14.0
Name: new_cases, dtype: float64
63908 63915    23.0
Name: new_cases, dtype: float64
63909 63916    13.0
Name: new_cases, dtype: float64
63910 63917    8.0
Name: new_cases, dtype: float64
63911 63918    0.0
Name: new_cases, dtype: float64
63912 63919    0.0
Name: new_cases, dtype: float64
63913 63920    14.0
Name: new_cases, dtype: float64
63914 63921    0.0
Name: new_cases, dtype: float64
63915 63922    5.0
Name: new_cases, dtype: float64
63916 63923    6.0
Name: new_cases, dtype: float64
63917 63924    0.0
Name: new_cases, dtype: float64
63918 63925    0.0
Name: new_cases, dtype: float64
63919 63926    0.0
Name: new_cases, dtype: float64
63920 63927    9.0
Name: new_cases, dtype: float64
63921 63928    2.0
Name: new_cases, dtype: float64
63922 63929    8.0
Name: new_cases, dtype: float64
63923 63930    1.0
Name: new_cases, dtype: float64
63924 63931    1.0
Name: new_cases, dtype: float64
63925 63932    0.0
Name: new_cases, dtype: float64
63926 63933    0.0
Name: new_cases, dtype: float64
63927 63934    7.0
Name: new_cases, dtype: float64
63928 63935    2.0
Name: new_cases, dtype: float64
63929 63936    2.0
Name: new_cases, dtype: float64
63930 63937    3.0
Name: new_cases, dtype: float64
63931 63938    5.0
Name: new_cases, dtype: float64
63932 63939    0.0
Name: new_cases, dtype: float64
63933 63940    0.0
Name: new_cases, dtype: float64
63934 63941   -1.0
Name: new_cases, dtype: float64
63935 63942    5.0
Name: new_cases, dtype: float64

63936 63943    1.0
Name: new_cases, dtype: float64
63937 63944    0.0
Name: new_cases, dtype: float64
63938 63945    7.0
Name: new_cases, dtype: float64
63939 63946    0.0
Name: new_cases, dtype: float64
63940 63947    0.0
Name: new_cases, dtype: float64
63941 63948    6.0
Name: new_cases, dtype: float64
63942 63949    0.0
Name: new_cases, dtype: float64
63943 63950    5.0
Name: new_cases, dtype: float64
63944 63951    0.0
Name: new_cases, dtype: float64
63945 63952    1.0
Name: new_cases, dtype: float64
63946 63953    0.0
Name: new_cases, dtype: float64
63947 63954    0.0
Name: new_cases, dtype: float64
63948 63955    4.0
Name: new_cases, dtype: float64
63949 63956    0.0
Name: new_cases, dtype: float64
63950 63957    0.0
Name: new_cases, dtype: float64
63951 63958    0.0
Name: new_cases, dtype: float64
63952 63959    0.0
Name: new_cases, dtype: float64
63953 63960    0.0
Name: new_cases, dtype: float64
63954 63961    0.0
Name: new_cases, dtype: float64
63955 63962    5.0
Name: new_cases, dtype: float64
63956 63963    1.0
Name: new_cases, dtype: float64
63957 63964    3.0
Name: new_cases, dtype: float64
63958 63965    0.0
Name: new_cases, dtype: float64
63959 63966    1.0
Name: new_cases, dtype: float64
63960 63967    0.0
Name: new_cases, dtype: float64
63961 63968    0.0
Name: new_cases, dtype: float64
63962 63969    5.0
Name: new_cases, dtype: float64
63963 63970    3.0
Name: new_cases, dtype: float64
63964 63971    2.0
Name: new_cases, dtype: float64
63965 63972    1.0
Name: new_cases, dtype: float64
63966 63973    2.0
Name: new_cases, dtype: float64
63967 63974    0.0
Name: new_cases, dtype: float64
63968 63975    0.0
Name: new_cases, dtype: float64
63969 63976    11.0
Name: new_cases, dtype: float64
63970 63977    4.0
Name: new_cases, dtype: float64
63971 63978    2.0
Name: new_cases, dtype: float64
63972 63979    2.0
Name: new_cases, dtype: float64
63973 63980    6.0
Name: new_cases, dtype: float64
63974 63981    0.0
Name: new_cases, dtype: float64
63975 63982    0.0
Name: new_cases, dtype: float64
63976 63983    22.0
Name: new_cases, dtype: float64
63977 63984    3.0
Name: new_cases, dtype: float64
63978 63985    22.0
Name: new_cases, dtype: float64
63979 63986    14.0
Name: new_cases, dtype: float64
63980 63987    5.0
Name: new_cases, dtype: float64
63981 63988    0.0
Name: new_cases, dtype: float64
63982 63989    0.0
Name: new_cases, dtype: float64
63983 63990    20.0
Name: new_cases, dtype: float64
63984 63991    11.0
Name: new_cases, dtype: float64
63985 63992    11.0
Name: new_cases, dtype: float64
63986 63993    0.0
Name: new_cases, dtype: float64
63987 63994    0.0
Name: new_cases, dtype: float64
63988 63995    20.0
Name: new_cases, dtype: float64
63989 63996    0.0
Name: new_cases, dtype: float64
63990 63997    0.0
Name: new_cases, dtype: float64
63991 63998    16.0
Name: new_cases, dtype: float64
63992 63999    10.0
Name: new_cases, dtype: float64
63993 64000    5.0
Name: new_cases, dtype: float64
63994 64001    2.0
Name: new_cases, dtype: float64
63995 64002    0.0
Name: new_cases, dtype: float64
63996 64003    0.0
Name: new_cases, dtype: float64
63997 64004    9.0
Name: new_cases, dtype: float64
63998 64005    7.0
Name: new_cases, dtype: float64
63999 64006    1.0
Name: new_cases, dtype: float64
64000 64007    4.0
Name: new_cases, dtype: float64
64001 64008    7.0
Name: new_cases, dtype: float64
64002 64009    0.0
Name: new_cases, dtype: float64
64003 64010    0.0
Name: new_cases, dtype: float64
64004 64011    43.0
Name: new_cases, dtype: float64
64005 64012    21.0
Name: new_cases, dtype: float64
64006 64013    12.0
Name: new_cases, dtype: float64
64007 64014    17.0
Name: new_cases, dtype: float64
64008 64015    11.0
Name: new_cases, dtype: float64
64009 64016    0.0
Name: new_cases, dtype: float64
64010 64017    0.0
Name: new_cases, dtype: float64
64011 64018    39.0
Name: new_cases, dtype: float64
64012 64019    18.0
Name: new_cases, dtype: float64
64013 64020    9.0
Name: new_cases, dtype: float64
64014 64021    10.0
Name: new_cases, dtype: float64
64015 64022    6.0
Name: new_cases, dtype: float64
64016 64023    0.0
Name: new_cases, dtype: float64
64017 64024    0.0
Name: new_cases, dtype: float64
64018 64025    11.0
Name: new_cases, dtype: float64
64019 64026    8.0
Name: new_cases, dtype: float64
64020 64027    6.0
Name: new_cases, dtype: float64
64021 64028    3.0
Name: new_cases, dtype: float64
64022 64029    6.0
Name: new_cases, dtype: float64
64023 64030    0.0
Name: new_cases, dtype: float64
64024 64031    0.0
Name: new_cases, dtype: float64
64025 64032    13.0
Name: new_cases, dtype: float64
64026 64033    3.0
Name: new_cases, dtype: float64
64027 64034    4.0
Name: new_cases, dtype: float64
64028 64035    0.0
Name: new_cases, dtype: float64
64029 64036    11.0
Name: new_cases, dtype: float64
64030 64037    0.0
Name: new_cases, dtype: float64
64031 64038    0.0
Name: new_cases, dtype: float64
64032 64039    11.0
Name: new_cases, dtype: float64
64033 64040    1.0
Name: new_cases, dtype: float64
64034 64041    2.0
Name: new_cases, dtype: float64
64035 64042    4.0
Name: new_cases, dtype: float64
64036 64043    0.0
Name: new_cases, dtype: float64
64037 64044    0.0
Name: new_cases, dtype: float64
64038 64045    1.0
Name: new_cases, dtype: float64
64039 64046    0.0
Name: new_cases, dtype: float64
64040 64047    0.0
Name: new_cases, dtype: float64
64041 64048    4.0
Name: new_cases, dtype: float64
64042 64049    4.0
Name: new_cases, dtype: float64
64043 64050    0.0
Name: new_cases, dtype: float64
64044 64051    12.0
Name: new_cases, dtype: float64
64045 64052    0.0
Name: new_cases, dtype: float64
64046 64053    0.0
Name: new_cases, dtype: float64
64047 64054    0.0
Name: new_cases, dtype: float64
64048 64055    10.0
Name: new_cases, dtype: float64
64049 64056    4.0
Name: new_cases, dtype: float64
64050 64057    5.0
Name: new_cases, dtype: float64
64051 64058    2.0
Name: new_cases, dtype: float64
64052 64059    7.0
Name: new_cases, dtype: float64
64053 64060    0.0
Name: new_cases, dtype: float64
64054 64061    0.0
Name: new_cases, dtype: float64
64055 64062    8.0
Name: new_cases, dtype: float64
64056 64063    0.0
Name: new_cases, dtype: float64
64057 64064    4.0
Name: new_cases, dtype: float64
64058 64065    0.0
Name: new_cases, dtype: float64
64059 64066    0.0
Name: new_cases, dtype: float64
64060 64067    0.0
Name: new_cases, dtype: float64
64061 64068    5.0
Name: new_cases, dtype: float64
64062 64069    0.0
Name: new_cases, dtype: float64
64063 64070    1.0
Name: new_cases, dtype: float64
64064 64071    0.0
Name: new_cases, dtype: float64
64065 64072    5.0
Name: new_cases, dtype: float64
64066 64073    0.0
Name: new_cases, dtype: float64
64067 64074    0.0
Name: new_cases, dtype: float64
64068 64075    3.0
Name: new_cases, dtype: float64
64069 64076    0.0
Name: new_cases, dtype: float64
64070 64077    0.0
Name: new_cases, dtype: float64
64071 64078    0.0
Name: new_cases, dtype: float64
64072 64079    7.0
Name: new_cases, dtype: float64
64073 64080    0.0
Name: new_cases, dtype: float64
64074 64081    0.0
Name: new_cases, dtype: float64
64075 64082    12.0
Name: new_cases, dtype: float64
64076 64083    0.0
Name: new_cases, dtype: float64
64077 64084    0.0
Name: new_cases, dtype: float64
64078 64085    0.0
Name: new_cases, dtype: float64
64079 64086    5.0
Name: new_cases, dtype: float64
64080 64087    0.0
Name: new_cases, dtype: float64
64081 64088    0.0
Name: new_cases, dtype: float64
64082 64089    0.0
Name: new_cases, dtype: float64
64083 64090    10.0
Name: new_cases, dtype: float64
64084 64091    0.0
Name: new_cases, dtype: float64
64085 64092    0.0
Name: new_cases, dtype: float64
64086 64093    11.0
Name: new_cases, dtype: float64
64087 64094    0.0
Name: new_cases, dtype: float64
64088 64095    0.0
Name: new_cases, dtype: float64
64089 64096    0.0
Name: new_cases, dtype: float64
64090 64097    0.0
Name: new_cases, dtype: float64
64091 64098    0.0
Name: new_cases, dtype: float64
64092 64099    0.0
Name: new_cases, dtype: float64
64093 64100    43.0
Name: new_cases, dtype: float64
64094 64101    0.0
Name: new_cases, dtype: float64
64095 64102    0.0
Name: new_cases, dtype: float64
64096 64103    114.0
Name: new_cases, dtype: float64
64097 64104    65.0
Name: new_cases, dtype: float64
64098 64105    70.0
Name: new_cases, dtype: float64
64099 64106    87.0
Name: new_cases, dtype: float64
64100 64107    94.0
Name: new_cases, dtype: float64
64101 64108    85.0
Name: new_cases, dtype: float64
64102 64109    71.0
Name: new_cases, dtype: float64
64103 64110    124.0
Name: new_cases, dtype: float64
64104 64111    117.0
Name: new_cases, dtype: float64
64105 64112    131.0
Name: new_cases, dtype: float64
64106 64113    125.0
Name: new_cases, dtype: float64
64107 64114    158.0
Name: new_cases, dtype: float64
64108 64115    92.0
Name: new_cases, dtype: float64
64109 64116    71.0
Name: new_cases, dtype: float64
64110 64117    111.0
Name: new_cases, dtype: float64

64111 64118    120.0
Name: new_cases, dtype: float64
64112 64119    155.0
Name: new_cases, dtype: float64
64113 64120    105.0
Name: new_cases, dtype: float64
64114 64121    125.0
Name: new_cases, dtype: float64
64115 64122    55.0
Name: new_cases, dtype: float64
64116 64123    107.0
Name: new_cases, dtype: float64
64117 64124    56.0
Name: new_cases, dtype: float64
64118 64125    170.0
Name: new_cases, dtype: float64
64119 64126    120.0
Name: new_cases, dtype: float64
64120 64127    130.0
Name: new_cases, dtype: float64
64121 64128    82.0
Name: new_cases, dtype: float64
64122 64129    64.0
Name: new_cases, dtype: float64
64123 64130    56.0
Name: new_cases, dtype: float64
64124 64131    104.0
Name: new_cases, dtype: float64
64125 64132    130.0
Name: new_cases, dtype: float64
64126 64133    104.0
Name: new_cases, dtype: float64
64127 64134    64.0
Name: new_cases, dtype: float64
64128 64135    73.0
Name: new_cases, dtype: float64
64129 64136    62.0
Name: new_cases, dtype: float64
64130 64137    62.0
Name: new_cases, dtype: float64
64131 64138    77.0
Name: new_cases, dtype: float64
64132 64139    87.0
Name: new_cases, dtype: float64
64133 64140    102.0
Name: new_cases, dtype: float64
64134 64141    71.0
Name: new_cases, dtype: float64
64135 64142    91.0
Name: new_cases, dtype: float64
64136 64143    53.0
Name: new_cases, dtype: float64
64137 64144    47.0
Name: new_cases, dtype: float64
64138 64145    84.0
Name: new_cases, dtype: float64
64139 64146    67.0
Name: new_cases, dtype: float64
64140 64147    56.0
Name: new_cases, dtype: float64
64141 64148    44.0
Name: new_cases, dtype: float64
64142 64149    54.0
Name: new_cases, dtype: float64
64143 64150    22.0
Name: new_cases, dtype: float64
64144 64151    31.0
Name: new_cases, dtype: float64
64145 64152    27.0
Name: new_cases, dtype: float64
64146 64153    40.0
Name: new_cases, dtype: float64
64147 64154    43.0
Name: new_cases, dtype: float64
64148 64155    26.0
Name: new_cases, dtype: float64
64149 64156    35.0
Name: new_cases, dtype: float64
64150 64157    13.0
Name: new_cases, dtype: float64
64151 64158    32.0
Name: new_cases, dtype: float64
64152 64159    28.0
Name: new_cases, dtype: float64
64153 64160    31.0
Name: new_cases, dtype: float64
64154 64161    39.0
Name: new_cases, dtype: float64
64155 64162    27.0
Name: new_cases, dtype: float64
64156 64163    0.0
Name: new_cases, dtype: float64
64157 64164    0.0
Name: new_cases, dtype: float64
64158 64165    67.0
Name: new_cases, dtype: float64
64159 64166    47.0
Name: new_cases, dtype: float64
64160 64167    40.0
Name: new_cases, dtype: float64
64161 64168    36.0
Name: new_cases, dtype: float64
64162 64169    38.0
Name: new_cases, dtype: float64
64163 64170    0.0
Name: new_cases, dtype: float64
64164 64171    0.0
Name: new_cases, dtype: float64
64165 64172    90.0
Name: new_cases, dtype: float64
64166 64173    38.0
Name: new_cases, dtype: float64
64167 64174    21.0
Name: new_cases, dtype: float64
64168 64175    20.0
Name: new_cases, dtype: float64
64169 64176    38.0
Name: new_cases, dtype: float64
64170 64177    0.0
Name: new_cases, dtype: float64
64171 64178    0.0
Name: new_cases, dtype: float64
64172 64179    119.0
Name: new_cases, dtype: float64
64173 64180    32.0
Name: new_cases, dtype: float64
64174 64181    45.0
Name: new_cases, dtype: float64
64175 64182    57.0
Name: new_cases, dtype: float64
64176 64183    55.0
Name: new_cases, dtype: float64
64177 64184    0.0
Name: new_cases, dtype: float64
64178 64185    0.0
Name: new_cases, dtype: float64
64179 64186    96.0
Name: new_cases, dtype: float64
64180 64187    44.0
Name: new_cases, dtype: float64
64181 64188    55.0
Name: new_cases, dtype: float64
64182 64189    48.0
Name: new_cases, dtype: float64
64183 64190    65.0
Name: new_cases, dtype: float64
64184 64191    0.0
Name: new_cases, dtype: float64
64185 64192    0.0
Name: new_cases, dtype: float64
64186 64193    159.0
Name: new_cases, dtype: float64
64187 64194    89.0
Name: new_cases, dtype: float64
64188 64195    72.0
Name: new_cases, dtype: float64
64189 64196    52.0
Name: new_cases, dtype: float64
64190 64197    72.0
Name: new_cases, dtype: float64
64191 64198    0.0
Name: new_cases, dtype: float64
64192 64199    0.0
Name: new_cases, dtype: float64
64193 64200    243.0
Name: new_cases, dtype: float64
64194 64201    94.0
Name: new_cases, dtype: float64
64195 64202    77.0
Name: new_cases, dtype: float64
64196 64203    100.0
Name: new_cases, dtype: float64
64197 64204    79.0
Name: new_cases, dtype: float64
64198 64205    0.0
Name: new_cases, dtype: float64
64199 64206    0.0
Name: new_cases, dtype: float64
64200 64207    247.0
Name: new_cases, dtype: float64
64201 64208    90.0
Name: new_cases, dtype: float64
64202 64209    94.0
Name: new_cases, dtype: float64
64203 64210    164.0
Name: new_cases, dtype: float64
64204 64211    168.0
Name: new_cases, dtype: float64
64205 64212    0.0
Name: new_cases, dtype: float64
64206 64213    0.0
Name: new_cases, dtype: float64
64207 64214    316.0
Name: new_cases, dtype: float64
64208 64215    186.0
Name: new_cases, dtype: float64
64209 64216    178.0
Name: new_cases, dtype: float64
64210 64217    205.0
Name: new_cases, dtype: float64
64211 64218    181.0
Name: new_cases, dtype: float64
64212 64219    0.0
Name: new_cases, dtype: float64
64213 64220    0.0
Name: new_cases, dtype: float64
64214 64221    420.0
Name: new_cases, dtype: float64
64215 64222    227.0
Name: new_cases, dtype: float64
64216 64223    145.0
Name: new_cases, dtype: float64
64217 64224    130.0
Name: new_cases, dtype: float64
64218 64225    192.0
Name: new_cases, dtype: float64
64219 64226    0.0
Name: new_cases, dtype: float64
64220 64227    0.0
Name: new_cases, dtype: float64
64221 64228    365.0
Name: new_cases, dtype: float64
64222 64229    202.0
Name: new_cases, dtype: float64
64223 64230    150.0
Name: new_cases, dtype: float64
64224 64231    142.0
Name: new_cases, dtype: float64
64225 64232    152.0
Name: new_cases, dtype: float64
64226 64233    0.0
Name: new_cases, dtype: float64
64227 64234    0.0
Name: new_cases, dtype: float64
64228 64235    324.0
Name: new_cases, dtype: float64
64229 64236    124.0
Name: new_cases, dtype: float64
64230 64237    161.0
Name: new_cases, dtype: float64
64231 64238    143.0
Name: new_cases, dtype: float64
64232 64239    135.0
Name: new_cases, dtype: float64
64233 64240    0.0
Name: new_cases, dtype: float64
64234 64241    0.0
Name: new_cases, dtype: float64
64235 64242    309.0
Name: new_cases, dtype: float64
64236 64243    123.0
Name: new_cases, dtype: float64
64237 64244    131.0
Name: new_cases, dtype: float64
64238 64245    156.0
Name: new_cases, dtype: float64
64239 64246    107.0
Name: new_cases, dtype: float64
64240 64247    0.0
Name: new_cases, dtype: float64
64241 64248    0.0
Name: new_cases, dtype: float64
64242 64249    388.0
Name: new_cases, dtype: float64
64243 64250    161.0
Name: new_cases, dtype: float64
64244 64251    153.0
Name: new_cases, dtype: float64
64245 64252    183.0
Name: new_cases, dtype: float64
64246 64253    188.0
Name: new_cases, dtype: float64
64247 64254    0.0
Name: new_cases, dtype: float64
64248 64255    0.0
Name: new_cases, dtype: float64
64249 64256    658.0
Name: new_cases, dtype: float64
64250 64257    325.0
Name: new_cases, dtype: float64
64251 64258    372.0
Name: new_cases, dtype: float64
64252 64259    500.0
Name: new_cases, dtype: float64
64253 64260    0.0
Name: new_cases, dtype: float64
64254 64261    0.0
Name: new_cases, dtype: float64
64255 64262    0.0
Name: new_cases, dtype: float64
64256 64263    2253.0
Name: new_cases, dtype: float64
64257 64264    974.0
Name: new_cases, dtype: float64
64258 64265    0.0
Name: new_cases, dtype: float64
64259 64266    1745.0
Name: new_cases, dtype: float64
64260 64267    0.0
Name: new_cases, dtype: float64
64261 64268    0.0
Name: new_cases, dtype: float64
64262 64269    0.0
Name: new_cases, dtype: float64
64263 64270    4011.0
Name: new_cases, dtype: float64
64264 64271    1470.0
Name: new_cases, dtype: float64
64265 64272    1361.0
Name: new_cases, dtype: float64
64266 64273    1338.0
Name: new_cases, dtype: float64
64267 64274    1208.0
Name: new_cases, dtype: float64
64268 Series([], Name: new_cases, dtype: float64)
64269 Series([], Name: new_cases, dtype: float64)
64270 Series([], Name: new_cases, dtype: float64)
64271 Series([], Name: new_cases, dtype: float64)
64272 Series([], Name: new_cases, dtype: float64)
64273 Series([], Name: new_cases, dtype: float64)
64274 Series([], Name: new_cases, dtype: float64)
64276 64283    0.0
Name: new_cases, dtype: float64
64277 64284    0.0
Name: new_cases, dtype: float64
64278 64285    0.0
Name: new_cases, dtype: float64
64279 64286    0.0
Name: new_cases, dtype: float64
64280 64287    0.0
Name: new_cases, dtype: float64
64281 64288    0.0
Name: new_cases, dtype: float64
64282 64289    0.0
Name: new_cases, dtype: float64
64283 64290    0.0
Name: new_cases, dtype: float64
64284 64291    0.0
Name: new_cases, dtype: float64
64285 64292    0.0
Name: new_cases, dtype: float64
64286 64293    0.0
Name: new_cases, dtype: float64
64287 64294    0.0
Name: new_cases, dtype: float64
64288 64295    0.0
Name: new_cases, dtype: float64
64289 64296    0.0
Name: new_cases, dtype: float64

64290 64297    0.0
Name: new_cases, dtype: float64
64291 64298    0.0
Name: new_cases, dtype: float64
64292 64299    0.0
Name: new_cases, dtype: float64
64293 64300    0.0
Name: new_cases, dtype: float64
64294 64301    0.0
Name: new_cases, dtype: float64
64295 64302    0.0
Name: new_cases, dtype: float64
64296 64303    0.0
Name: new_cases, dtype: float64
64297 64304    0.0
Name: new_cases, dtype: float64
64298 64305    0.0
Name: new_cases, dtype: float64
64299 64306    0.0
Name: new_cases, dtype: float64
64300 64307    0.0
Name: new_cases, dtype: float64
64301 64308    2.0
Name: new_cases, dtype: float64
64302 64309    0.0
Name: new_cases, dtype: float64
64303 64310    23.0
Name: new_cases, dtype: float64
64304 64311    2.0
Name: new_cases, dtype: float64
64305 64312    1.0
Name: new_cases, dtype: float64
64306 64313    3.0
Name: new_cases, dtype: float64
64307 64314    5.0
Name: new_cases, dtype: float64
64308 64315    4.0
Name: new_cases, dtype: float64
64309 64316    13.0
Name: new_cases, dtype: float64
64310 64317    6.0
Name: new_cases, dtype: float64
64311 64318    11.0
Name: new_cases, dtype: float64
64312 64319    9.0
Name: new_cases, dtype: float64
64313 64320    20.0
Name: new_cases, dtype: float64
64314 64321    11.0
Name: new_cases, dtype: float64
64315 64322    6.0
Name: new_cases, dtype: float64
64316 64323    23.0
Name: new_cases, dtype: float64
64317 64324    14.0
Name: new_cases, dtype: float64
64318 64325    38.0
Name: new_cases, dtype: float64
64319 64326    50.0
Name: new_cases, dtype: float64
64320 64327    86.0
Name: new_cases, dtype: float64
64321 64328    66.0
Name: new_cases, dtype: float64
64322 64329    103.0
Name: new_cases, dtype: float64
64323 64330    37.0
Name: new_cases, dtype: float64
64324 64331    121.0
Name: new_cases, dtype: float64
64325 64332    70.0
Name: new_cases, dtype: float64
64326 64333    160.0
Name: new_cases, dtype: float64
64327 64334    100.0
Name: new_cases, dtype: float64
64328 64335    37.0
Name: new_cases, dtype: float64
64329 64336    227.0
Name: new_cases, dtype: float64
64330 64337    146.0
Name: new_cases, dtype: float64
64331 64338    601.0
Name: new_cases, dtype: float64
64332 64339    545.0
Name: new_cases, dtype: float64
64333 64340    24.0
Name: new_cases, dtype: float64
64334 64341    515.0
Name: new_cases, dtype: float64
64335 64342    506.0
Name: new_cases, dtype: float64
64336 64343    1190.0
Name: new_cases, dtype: float64
64337 64344    533.0
Name: new_cases, dtype: float64
64338 64345    605.0
Name: new_cases, dtype: float64
64339 64346    809.0
Name: new_cases, dtype: float64
64340 64347    873.0
Name: new_cases, dtype: float64
64341 64348    848.0
Name: new_cases, dtype: float64
64342 64349    759.0
Name: new_cases, dtype: float64
64343 64350    1248.0
Name: new_cases, dtype: float64
64344 64351    1034.0
Name: new_cases, dtype: float64
64345 64352    835.0
Name: new_cases, dtype: float64
64346 64353    1108.0
Name: new_cases, dtype: float64
64347 64354    922.0
Name: new_cases, dtype: float64
64348 64355    1370.0
Name: new_cases, dtype: float64
64349 64356    1893.0
Name: new_cases, dtype: float64
64350 64357    924.0
Name: new_cases, dtype: float64
64351 64358    1541.0
Name: new_cases, dtype: float64
64352 64359    1290.0
Name: new_cases, dtype: float64
64353 64360    1707.0
Name: new_cases, dtype: float64
64354 64361    1453.0
Name: new_cases, dtype: float64
64355 64362    1753.0
Name: new_cases, dtype: float64
64356 64363    1607.0
Name: new_cases, dtype: float64
64357 64364    1561.0
Name: new_cases, dtype: float64
64358 64365    1873.0
Name: new_cases, dtype: float64
64359 64366    1738.0
Name: new_cases, dtype: float64
64360 64367    1801.0
Name: new_cases, dtype: float64
64361 64368    2394.0
Name: new_cases, dtype: float64
64362 64369    2442.0
Name: new_cases, dtype: float64
64363 64370    2806.0
Name: new_cases, dtype: float64
64364 64371    3932.0
Name: new_cases, dtype: float64
64365 64372    2963.0
Name: new_cases, dtype: float64
64366 64373    3587.0
Name: new_cases, dtype: float64
64367 64374    3364.0
Name: new_cases, dtype: float64
64368 64375    3344.0
Name: new_cases, dtype: float64
64369 64376    3113.0
Name: new_cases, dtype: float64
64370 64377    4353.0
Name: new_cases, dtype: float64
64371 64378    3607.0
Name: new_cases, dtype: float64
64372 64379    3524.0
Name: new_cases, dtype: float64
64373 64380    3763.0
Name: new_cases, dtype: float64
64374 64381    3942.0
Name: new_cases, dtype: float64
64375 64382    3787.0
Name: new_cases, dtype: float64
64376 64383    4864.0
Name: new_cases, dtype: float64
64377 64384    5050.0
Name: new_cases, dtype: float64
64378 64385    4630.0
Name: new_cases, dtype: float64
64379 64386    6147.0
Name: new_cases, dtype: float64
64380 64387    5553.0
Name: new_cases, dtype: float64
64381 64388    6198.0
Name: new_cases, dtype: float64
64382 64389    6568.0
Name: new_cases, dtype: float64
64383 64390    6629.0
Name: new_cases, dtype: float64
64384 64391    7113.0
Name: new_cases, dtype: float64
64385 64392    6414.0
Name: new_cases, dtype: float64
64386 64393    5843.0
Name: new_cases, dtype: float64
64387 64394    7293.0
Name: new_cases, dtype: float64
64388 64395    7300.0
Name: new_cases, dtype: float64
64389 64396    8105.0
Name: new_cases, dtype: float64
64390 64397    8336.0
Name: new_cases, dtype: float64
64391 64398    8782.0
Name: new_cases, dtype: float64
64392 64399    7761.0
Name: new_cases, dtype: float64
64393 64400    8821.0
Name: new_cases, dtype: float64
64394 64401    9633.0
Name: new_cases, dtype: float64
64395 64402    9889.0
Name: new_cases, dtype: float64
64396 64403    9471.0
Name: new_cases, dtype: float64
64397 64404    10438.0
Name: new_cases, dtype: float64
64398 64405    10864.0
Name: new_cases, dtype: float64
64399 64406    8442.0
Name: new_cases, dtype: float64
64400 64407    10218.0
Name: new_cases, dtype: float64
64401 64408    10459.0
Name: new_cases, dtype: float64
64402 64409    10930.0
Name: new_cases, dtype: float64
64403 64410    11458.0
Name: new_cases, dtype: float64
64404 64411    11929.0
Name: new_cases, dtype: float64
64405 64412    11502.0
Name: new_cases, dtype: float64
64406 64413    10667.0
Name: new_cases, dtype: float64
64407 64414    10974.0
Name: new_cases, dtype: float64
64408 64415    12881.0
Name: new_cases, dtype: float64
64409 64416    13586.0
Name: new_cases, dtype: float64
64410 64417    14516.0
Name: new_cases, dtype: float64
64411 64418    15403.0
Name: new_cases, dtype: float64
64412 64419    14831.0
Name: new_cases, dtype: float64
64413 64420    14933.0
Name: new_cases, dtype: float64
64414 64421    15968.0
Name: new_cases, dtype: float64
64415 64422    16922.0
Name: new_cases, dtype: float64
64416 64423    17296.0
Name: new_cases, dtype: float64
64417 64424    18552.0
Name: new_cases, dtype: float64
64418 64425    19906.0
Name: new_cases, dtype: float64
64419 64426    19459.0
Name: new_cases, dtype: float64
64420 64427    18522.0
Name: new_cases, dtype: float64
64421 64428    18641.0
Name: new_cases, dtype: float64
64422 64429    19160.0
Name: new_cases, dtype: float64
64423 64430    20903.0
Name: new_cases, dtype: float64
64424 64431    22771.0
Name: new_cases, dtype: float64
64425 64432    24850.0
Name: new_cases, dtype: float64
64426 64433    24248.0
Name: new_cases, dtype: float64
64427 64434    22251.0
Name: new_cases, dtype: float64
64428 64435    22753.0
Name: new_cases, dtype: float64
64429 64436    24879.0
Name: new_cases, dtype: float64
64430 64437    26506.0
Name: new_cases, dtype: float64
64431 64438    27114.0
Name: new_cases, dtype: float64
64432 64439    28606.0
Name: new_cases, dtype: float64
64433 64440    28732.0
Name: new_cases, dtype: float64
64434 64441    28498.0
Name: new_cases, dtype: float64
64435 64442    29429.0
Name: new_cases, dtype: float64
64436 64443    32676.0
Name: new_cases, dtype: float64
64437 64444    34975.0
Name: new_cases, dtype: float64
64438 64445    35252.0
Name: new_cases, dtype: float64
64439 64446    38697.0
Name: new_cases, dtype: float64
64440 64447    40425.0
Name: new_cases, dtype: float64
64441 64448    37132.0
Name: new_cases, dtype: float64
64442 64449    37740.0
Name: new_cases, dtype: float64
64443 64450    45720.0
Name: new_cases, dtype: float64
64444 64451    49310.0
Name: new_cases, dtype: float64

64445 64452    48916.0
Name: new_cases, dtype: float64
64446 64453    48611.0
Name: new_cases, dtype: float64
64447 64454    49981.0
Name: new_cases, dtype: float64
64448 64455    44457.0
Name: new_cases, dtype: float64
64449 64456    51596.0
Name: new_cases, dtype: float64
64450 64457    50294.0
Name: new_cases, dtype: float64
64451 64458    52783.0
Name: new_cases, dtype: float64
64452 64459    61242.0
Name: new_cases, dtype: float64
64453 64460    54735.0
Name: new_cases, dtype: float64
64454 64461    52972.0
Name: new_cases, dtype: float64
64455 64462    52050.0
Name: new_cases, dtype: float64
64456 64463    52509.0
Name: new_cases, dtype: float64
64457 64464    56282.0
Name: new_cases, dtype: float64
64458 64465    62538.0
Name: new_cases, dtype: float64
64459 64466    61537.0
Name: new_cases, dtype: float64
64460 64467    64399.0
Name: new_cases, dtype: float64
64461 64468    62064.0
Name: new_cases, dtype: float64
64462 64469    53601.0
Name: new_cases, dtype: float64
64463 64470    60963.0
Name: new_cases, dtype: float64
64464 64471    66999.0
Name: new_cases, dtype: float64
64465 64472    64553.0
Name: new_cases, dtype: float64
64466 64473    64732.0
Name: new_cases, dtype: float64
64467 64474    64030.0
Name: new_cases, dtype: float64
64468 64475    57711.0
Name: new_cases, dtype: float64
64469 64476    55018.0
Name: new_cases, dtype: float64
64470 64477    64572.0
Name: new_cases, dtype: float64
64471 64478    69672.0
Name: new_cases, dtype: float64
64472 64479    68900.0
Name: new_cases, dtype: float64
64473 64480    69876.0
Name: new_cases, dtype: float64
64474 64481    69239.0
Name: new_cases, dtype: float64
64475 64482    61408.0
Name: new_cases, dtype: float64
64476 64483    60975.0
Name: new_cases, dtype: float64
64477 64484    57224.0
Name: new_cases, dtype: float64
64478 64485    85687.0
Name: new_cases, dtype: float64
64479 64486    77266.0
Name: new_cases, dtype: float64
64480 64487    76472.0
Name: new_cases, dtype: float64
64481 64488    78761.0
Name: new_cases, dtype: float64
64482 64489    78512.0
Name: new_cases, dtype: float64
64483 64490    69921.0
Name: new_cases, dtype: float64
64484 64491    78357.0
Name: new_cases, dtype: float64
64485 64492    83883.0
Name: new_cases, dtype: float64
64486 64493    83341.0
Name: new_cases, dtype: float64
64487 64494    86432.0
Name: new_cases, dtype: float64
64488 64495    90632.0
Name: new_cases, dtype: float64
64489 64496    90802.0
Name: new_cases, dtype: float64
64490 64497    75809.0
Name: new_cases, dtype: float64
64491 64498    89706.0
Name: new_cases, dtype: float64
64492 64499    95735.0
Name: new_cases, dtype: float64
64493 64500    96551.0
Name: new_cases, dtype: float64
64494 64501    97570.0
Name: new_cases, dtype: float64
64495 64502    94372.0
Name: new_cases, dtype: float64
64496 64503    92071.0
Name: new_cases, dtype: float64
64497 64504    83809.0
Name: new_cases, dtype: float64
64498 64505    90123.0
Name: new_cases, dtype: float64
64499 64506    97894.0
Name: new_cases, dtype: float64
64500 64507    96424.0
Name: new_cases, dtype: float64
64501 64508    93337.0
Name: new_cases, dtype: float64
64502 64509    92605.0
Name: new_cases, dtype: float64
64503 64510    86961.0
Name: new_cases, dtype: float64
64504 64511    75083.0
Name: new_cases, dtype: float64
64505 64512    83347.0
Name: new_cases, dtype: float64
64506 64513    86508.0
Name: new_cases, dtype: float64
64507 64514    86052.0
Name: new_cases, dtype: float64
64508 64515    85362.0
Name: new_cases, dtype: float64
64509 64516    88600.0
Name: new_cases, dtype: float64
64510 64517    82170.0
Name: new_cases, dtype: float64
64511 64518    70589.0
Name: new_cases, dtype: float64
64512 64519    80472.0
Name: new_cases, dtype: float64
64513 64520    86821.0
Name: new_cases, dtype: float64
64514 64521    81484.0
Name: new_cases, dtype: float64
64515 64522    79476.0
Name: new_cases, dtype: float64
64516 64523    75829.0
Name: new_cases, dtype: float64
64517 64524    74442.0
Name: new_cases, dtype: float64
64518 64525    61267.0
Name: new_cases, dtype: float64
64519 64526    72049.0
Name: new_cases, dtype: float64
64520 64527    78524.0
Name: new_cases, dtype: float64
64521 64528    70496.0
Name: new_cases, dtype: float64
64522 64529    73272.0
Name: new_cases, dtype: float64
64523 64530    74383.0
Name: new_cases, dtype: float64
64524 64531    66732.0
Name: new_cases, dtype: float64
64525 64532    55342.0
Name: new_cases, dtype: float64
64526 64533    63509.0
Name: new_cases, dtype: float64
64527 64534    67708.0
Name: new_cases, dtype: float64
64528 64535    63371.0
Name: new_cases, dtype: float64
64529 64536    62212.0
Name: new_cases, dtype: float64
64530 64537    61871.0
Name: new_cases, dtype: float64
64531 64538    55722.0
Name: new_cases, dtype: float64
64532 64539    46790.0
Name: new_cases, dtype: float64
64533 64540    54044.0
Name: new_cases, dtype: float64
64534 64541    55839.0
Name: new_cases, dtype: float64
64535 64542    54366.0
Name: new_cases, dtype: float64
64536 64543    53370.0
Name: new_cases, dtype: float64
64537 64544    50129.0
Name: new_cases, dtype: float64
64538 64545    45148.0
Name: new_cases, dtype: float64
64539 64546    36470.0
Name: new_cases, dtype: float64
64540 64547    43893.0
Name: new_cases, dtype: float64
64541 64548    49881.0
Name: new_cases, dtype: float64
64542 64549    48648.0
Name: new_cases, dtype: float64
64543 64550    48268.0
Name: new_cases, dtype: float64
64544 64551    46963.0
Name: new_cases, dtype: float64
64545 64552    45231.0
Name: new_cases, dtype: float64
64546 64553    38310.0
Name: new_cases, dtype: float64
64547 64554    46253.0
Name: new_cases, dtype: float64
64548 64555    50210.0
Name: new_cases, dtype: float64
64549 64556    47638.0
Name: new_cases, dtype: float64
64550 64557    50356.0
Name: new_cases, dtype: float64
64551 64558    45674.0
Name: new_cases, dtype: float64
64552 64559    45903.0
Name: new_cases, dtype: float64
64553 64560    38073.0
Name: new_cases, dtype: float64
64554 64561    44281.0
Name: new_cases, dtype: float64
64555 64562    47905.0
Name: new_cases, dtype: float64
64556 64563    44879.0
Name: new_cases, dtype: float64
64557 64564    44684.0
Name: new_cases, dtype: float64
64558 64565    41100.0
Name: new_cases, dtype: float64
64559 64566    30548.0
Name: new_cases, dtype: float64
64560 64567    29163.0
Name: new_cases, dtype: float64
64561 64568    38617.0
Name: new_cases, dtype: float64
64562 64569    45576.0
Name: new_cases, dtype: float64
64563 64570    45882.0
Name: new_cases, dtype: float64
64564 64571    46232.0
Name: new_cases, dtype: float64
64565 64572    45209.0
Name: new_cases, dtype: float64
64566 64573    44059.0
Name: new_cases, dtype: float64
64567 64574    37975.0
Name: new_cases, dtype: float64
64568 64575    44376.0
Name: new_cases, dtype: float64
64569 64576    44489.0
Name: new_cases, dtype: float64
64570 64577    43082.0
Name: new_cases, dtype: float64
64571 64578    41322.0
Name: new_cases, dtype: float64
64572 64579    41810.0
Name: new_cases, dtype: float64
64573 64580    38772.0
Name: new_cases, dtype: float64
64574 64581    31118.0
Name: new_cases, dtype: float64
64575 64582    36604.0
Name: new_cases, dtype: float64
64576 64583    35551.0
Name: new_cases, dtype: float64
64577 64584    36595.0
Name: new_cases, dtype: float64
64578 64585    36652.0
Name: new_cases, dtype: float64
64579 64586    36011.0
Name: new_cases, dtype: float64
64580 64587    32981.0
Name: new_cases, dtype: float64
64581 64588    26567.0
Name: new_cases, dtype: float64
64582 64589    32080.0
Name: new_cases, dtype: float64
64583 64590    31521.0
Name: new_cases, dtype: float64
64584 64591    29373.0
Name: new_cases, dtype: float64
64585 64592    30031.0
Name: new_cases, dtype: float64
64586 64593    30254.0
Name: new_cases, dtype: float64
64587 64594    27071.0
Name: new_cases, dtype: float64
64588 64595    22065.0
Name: new_cases, dtype: float64
64589 64596    26382.0
Name: new_cases, dtype: float64
64590 64597    24010.0
Name: new_cases, dtype: float64
64591 64598    22890.0
Name: new_cases, dtype: float64
64592 64599    25152.0
Name: new_cases, dtype: float64
64593 64600    26624.0
Name: new_cases, dtype: float64
64594 64601    24337.0
Name: new_cases, dtype: float64
64595 64602    19556.0
Name: new_cases, dtype: float64
64596 64603    23950.0
Name: new_cases, dtype: float64
64597 64604    24712.0
Name: new_cases, dtype: float64
64598 64605    23067.0
Name: new_cases, dtype: float64
64599 64606    22273.0
Name: new_cases, dtype: float64
64600 64607    18732.0
Name: new_cases, dtype: float64
64601 64608    20021.0
Name: new_cases, dtype: float64

64602 64609    16432.0
Name: new_cases, dtype: float64
64603 64610    20549.0
Name: new_cases, dtype: float64
64604 64611    21822.0
Name: new_cases, dtype: float64
64605 64612    20035.0
Name: new_cases, dtype: float64
64606 64613    19079.0
Name: new_cases, dtype: float64
64607 64614    18177.0
Name: new_cases, dtype: float64
64608 64615    16504.0
Name: new_cases, dtype: float64
64609 64616    16375.0
Name: new_cases, dtype: float64
64610 64617    18088.0
Name: new_cases, dtype: float64
64611 64618    20346.0
Name: new_cases, dtype: float64
64612 64619    18139.0
Name: new_cases, dtype: float64
64613 64620    0.0
Name: new_cases, dtype: float64
64614 64621    36867.0
Name: new_cases, dtype: float64
64615 64622    16311.0
Name: new_cases, dtype: float64
64616 64623    12584.0
Name: new_cases, dtype: float64
64617 64624    15968.0
Name: new_cases, dtype: float64
64618 64625    16946.0
Name: new_cases, dtype: float64
64619 64626    15590.0
Name: new_cases, dtype: float64
64620 64627    15158.0
Name: new_cases, dtype: float64
64621 64628    15144.0
Name: new_cases, dtype: float64
64622 64629    13788.0
Name: new_cases, dtype: float64
64623 64630    10050.0
Name: new_cases, dtype: float64
64624 64631    13816.0
Name: new_cases, dtype: float64
64625 64632    15244.0
Name: new_cases, dtype: float64
64626 64633    14545.0
Name: new_cases, dtype: float64
64627 64634    14256.0
Name: new_cases, dtype: float64
64628 64635    14849.0
Name: new_cases, dtype: float64
64629 64636    13203.0
Name: new_cases, dtype: float64
64630 64637    9102.0
Name: new_cases, dtype: float64
64631 64638    12689.0
Name: new_cases, dtype: float64
64632 64639    11666.0
Name: new_cases, dtype: float64
64633 64640    18855.0
Name: new_cases, dtype: float64
64634 64641    13082.0
Name: new_cases, dtype: float64
64635 64642    13044.0
Name: new_cases, dtype: float64
64636 64643    11436.0
Name: new_cases, dtype: float64
64637 64644    8635.0
Name: new_cases, dtype: float64
64638 64645    11039.0
Name: new_cases, dtype: float64
64639 64646    12899.0
Name: new_cases, dtype: float64
64640 64647    12408.0
Name: new_cases, dtype: float64
64641 64648    11713.0
Name: new_cases, dtype: float64
64642 64649    12059.0
Name: new_cases, dtype: float64
64643 64650    11831.0
Name: new_cases, dtype: float64
64644 64651    9110.0
Name: new_cases, dtype: float64
64645 64652    11067.0
Name: new_cases, dtype: float64
64646 64653    12923.0
Name: new_cases, dtype: float64
64647 64654    9309.0
Name: new_cases, dtype: float64
64648 64655    12143.0
Name: new_cases, dtype: float64
64649 64656    12194.0
Name: new_cases, dtype: float64
64650 64657    11649.0
Name: new_cases, dtype: float64
64651 64658    9121.0
Name: new_cases, dtype: float64
64652 64659    11610.0
Name: new_cases, dtype: float64
64653 64660    12881.0
Name: new_cases, dtype: float64
64654 64661    13193.0
Name: new_cases, dtype: float64
64655 64662    13993.0
Name: new_cases, dtype: float64
64656 64663    14264.0
Name: new_cases, dtype: float64
64657 64664    14199.0
Name: new_cases, dtype: float64
64658 64665    10584.0
Name: new_cases, dtype: float64
64659 64666    13742.0
Name: new_cases, dtype: float64
64660 64667    16738.0
Name: new_cases, dtype: float64
64661 64668    16577.0
Name: new_cases, dtype: float64
64662 64669    16488.0
Name: new_cases, dtype: float64
64663 64670    16752.0
Name: new_cases, dtype: float64
64664 64671    15510.0
Name: new_cases, dtype: float64
64665 64672    12286.0
Name: new_cases, dtype: float64
64666 64673    14989.0
Name: new_cases, dtype: float64
64667 64674    17407.0
Name: new_cases, dtype: float64
64668 64675    16838.0
Name: new_cases, dtype: float64
64669 64676    18284.0
Name: new_cases, dtype: float64
64670 64677    18754.0
Name: new_cases, dtype: float64
64671 64678    18599.0
Name: new_cases, dtype: float64
64672 64679    15388.0
Name: new_cases, dtype: float64
64673 64680    17921.0
Name: new_cases, dtype: float64
64674 64681    22854.0
Name: new_cases, dtype: float64
64675 64682    23285.0
Name: new_cases, dtype: float64
64676 64683    24882.0
Name: new_cases, dtype: float64
64677 64684    25320.0
Name: new_cases, dtype: float64
64678 64685    26291.0
Name: new_cases, dtype: float64
64679 64686    24492.0
Name: new_cases, dtype: float64
64680 64687    28903.0
Name: new_cases, dtype: float64
64681 64688    35871.0
Name: new_cases, dtype: float64
64682 64689    39726.0
Name: new_cases, dtype: float64
64683 64690    40953.0
Name: new_cases, dtype: float64
64684 64691    43846.0
Name: new_cases, dtype: float64
64685 64692    46951.0
Name: new_cases, dtype: float64
64686 64693    40715.0
Name: new_cases, dtype: float64
64687 64694    47262.0
Name: new_cases, dtype: float64
64688 64695    53476.0
Name: new_cases, dtype: float64
64689 64696    59118.0
Name: new_cases, dtype: float64
64690 64697    62258.0
Name: new_cases, dtype: float64
64691 64698    62714.0
Name: new_cases, dtype: float64
64692 64699    68020.0
Name: new_cases, dtype: float64
64693 64700    56211.0
Name: new_cases, dtype: float64
64694 64701    53480.0
Name: new_cases, dtype: float64
64695 64702    72330.0
Name: new_cases, dtype: float64
64696 64703    81466.0
Name: new_cases, dtype: float64
64697 64704    89129.0
Name: new_cases, dtype: float64
64698 64705    93249.0
Name: new_cases, dtype: float64
64699 64706    103558.0
Name: new_cases, dtype: float64
64700 64707    96982.0
Name: new_cases, dtype: float64
64701 64708    115736.0
Name: new_cases, dtype: float64
64702 64709    126789.0
Name: new_cases, dtype: float64
64703 64710    131968.0
Name: new_cases, dtype: float64
64704 64711    145384.0
Name: new_cases, dtype: float64
64705 64712    152879.0
Name: new_cases, dtype: float64
64706 64713    168912.0
Name: new_cases, dtype: float64
64707 64714    161736.0
Name: new_cases, dtype: float64
64708 64715    184372.0
Name: new_cases, dtype: float64
64709 64716    200739.0
Name: new_cases, dtype: float64
64710 64717    217353.0
Name: new_cases, dtype: float64
64711 64718    234692.0
Name: new_cases, dtype: float64
64712 64719    261394.0
Name: new_cases, dtype: float64
64713 64720    273802.0
Name: new_cases, dtype: float64
64714 64721    259167.0
Name: new_cases, dtype: float64
64715 64722    295158.0
Name: new_cases, dtype: float64
64716 64723    314644.0
Name: new_cases, dtype: float64
64717 64724    332921.0
Name: new_cases, dtype: float64
64718 64725    346786.0
Name: new_cases, dtype: float64
64719 64726    349691.0
Name: new_cases, dtype: float64
64720 64727    352991.0
Name: new_cases, dtype: float64
64721 64728    323023.0
Name: new_cases, dtype: float64
64722 64729    360927.0
Name: new_cases, dtype: float64
64723 64730    379308.0
Name: new_cases, dtype: float64
64724 64731    386555.0
Name: new_cases, dtype: float64
64725 64732    401993.0
Name: new_cases, dtype: float64
64726 64733    392488.0
Name: new_cases, dtype: float64
64727 64734    368060.0
Name: new_cases, dtype: float64
64728 64735    357316.0
Name: new_cases, dtype: float64
64729 64736    382146.0
Name: new_cases, dtype: float64
64730 64737    412431.0
Name: new_cases, dtype: float64
64731 64738    414188.0
Name: new_cases, dtype: float64
64732 64739    401078.0
Name: new_cases, dtype: float64
64733 64740    403405.0
Name: new_cases, dtype: float64
64734 64741    366494.0
Name: new_cases, dtype: float64
64735 64742    329942.0
Name: new_cases, dtype: float64
64736 64743    348421.0
Name: new_cases, dtype: float64
64737 64744    362727.0
Name: new_cases, dtype: float64
64738 64745    343144.0
Name: new_cases, dtype: float64
64739 64746    326098.0
Name: new_cases, dtype: float64
64740 64747    311170.0
Name: new_cases, dtype: float64
64741 64748    281386.0
Name: new_cases, dtype: float64
64742 64749    263533.0
Name: new_cases, dtype: float64
64743 64750    267334.0
Name: new_cases, dtype: float64
64744 64751    276110.0
Name: new_cases, dtype: float64
64745 64752    259551.0
Name: new_cases, dtype: float64
64746 64753    257299.0
Name: new_cases, dtype: float64
64747 64754    240842.0
Name: new_cases, dtype: float64
64748 64755    222315.0
Name: new_cases, dtype: float64
64749 64756    196427.0
Name: new_cases, dtype: float64
64750 64757    208921.0
Name: new_cases, dtype: float64
64751 64758    211298.0
Name: new_cases, dtype: float64
64752 64759    186364.0
Name: new_cases, dtype: float64
64753 64760    173790.0
Name: new_cases, dtype: float64
64754 64761    165553.0
Name: new_cases, dtype: float64
64755 64762    152734.0
Name: new_cases, dtype: float64
64756 64763    127510.0
Name: new_cases, dtype: float64
64757 64764    132788.0
Name: new_cases, dtype: float64
64758 64765    134154.0
Name: new_cases, dtype: float64
64759 64766    132364.0
Name: new_cases, dtype: float64
64760 64767    120529.0
Name: new_cases, dtype: float64
64761 64768    114460.0
Name: new_cases, dtype: float64

64762 64769    100636.0
Name: new_cases, dtype: float64
64763 64770    86498.0
Name: new_cases, dtype: float64
64764 64771    92596.0
Name: new_cases, dtype: float64
64765 64772    93463.0
Name: new_cases, dtype: float64
64766 64773    92291.0
Name: new_cases, dtype: float64
64767 64774    84332.0
Name: new_cases, dtype: float64
64768 64775    80834.0
Name: new_cases, dtype: float64
64769 64776    70421.0
Name: new_cases, dtype: float64
64770 64777    60471.0
Name: new_cases, dtype: float64
64771 64778    62224.0
Name: new_cases, dtype: float64
64772 64779    67208.0
Name: new_cases, dtype: float64
64773 64780    62480.0
Name: new_cases, dtype: float64
64774 64781    60753.0
Name: new_cases, dtype: float64
64775 64782    58226.0
Name: new_cases, dtype: float64
64776 64783    53449.0
Name: new_cases, dtype: float64
64777 64784    42640.0
Name: new_cases, dtype: float64
64778 64785    50848.0
Name: new_cases, dtype: float64
64779 64786    54069.0
Name: new_cases, dtype: float64
64780 64787    51667.0
Name: new_cases, dtype: float64
64781 64788    48698.0
Name: new_cases, dtype: float64
64782 64789    50040.0
Name: new_cases, dtype: float64
64783 64790    46148.0
Name: new_cases, dtype: float64
64784 64791    37566.0
Name: new_cases, dtype: float64
64785 64792    45951.0
Name: new_cases, dtype: float64
64786 64793    48786.0
Name: new_cases, dtype: float64
64787 64794    46617.0
Name: new_cases, dtype: float64
64788 64795    44111.0
Name: new_cases, dtype: float64
64789 64796    43071.0
Name: new_cases, dtype: float64
64790 64797    39796.0
Name: new_cases, dtype: float64
64791 64798    34703.0
Name: new_cases, dtype: float64
64792 64799    43733.0
Name: new_cases, dtype: float64
64793 64800    45892.0
Name: new_cases, dtype: float64
64794 64801    43393.0
Name: new_cases, dtype: float64
64795 64802    42766.0
Name: new_cases, dtype: float64
64796 64803    41506.0
Name: new_cases, dtype: float64
64797 64804    37154.0
Name: new_cases, dtype: float64
64798 64805    32906.0
Name: new_cases, dtype: float64
64799 64806    38865.0
Name: new_cases, dtype: float64
64800 64807    41733.0
Name: new_cases, dtype: float64
64801 64808    38949.0
Name: new_cases, dtype: float64
64802 64809    38079.0
Name: new_cases, dtype: float64
64803 64810    41157.0
Name: new_cases, dtype: float64
64804 64811    38164.0
Name: new_cases, dtype: float64
64805 64812    30093.0
Name: new_cases, dtype: float64
64806 64813    42015.0
Name: new_cases, dtype: float64
64807 64814    41383.0
Name: new_cases, dtype: float64
64808 64815    35342.0
Name: new_cases, dtype: float64
64809 64816    39097.0
Name: new_cases, dtype: float64
64810 64817    39742.0
Name: new_cases, dtype: float64
64811 64818    39361.0
Name: new_cases, dtype: float64
64812 64819    29689.0
Name: new_cases, dtype: float64
64813 64820    43654.0
Name: new_cases, dtype: float64
64814 64821    43509.0
Name: new_cases, dtype: float64
64815 64822    44230.0
Name: new_cases, dtype: float64
64816 64823    41649.0
Name: new_cases, dtype: float64
64817 64824    41831.0
Name: new_cases, dtype: float64
64818 64825    40134.0
Name: new_cases, dtype: float64
64819 64826    30549.0
Name: new_cases, dtype: float64
64820 64827    42625.0
Name: new_cases, dtype: float64
64821 64828    42982.0
Name: new_cases, dtype: float64
64822 64829    44643.0
Name: new_cases, dtype: float64
64823 64830    38628.0
Name: new_cases, dtype: float64
64824 64831    39070.0
Name: new_cases, dtype: float64
64825 64832    35499.0
Name: new_cases, dtype: float64
64826 64833    28204.0
Name: new_cases, dtype: float64
64827 64834    38353.0
Name: new_cases, dtype: float64
64828 64835    41195.0
Name: new_cases, dtype: float64
64829 64836    40120.0
Name: new_cases, dtype: float64
64830 64837    38667.0
Name: new_cases, dtype: float64
64831 64838    36083.0
Name: new_cases, dtype: float64
64832 64839    32937.0
Name: new_cases, dtype: float64
64833 64840    25166.0
Name: new_cases, dtype: float64
64834 64841    35178.0
Name: new_cases, dtype: float64
64835 64842    36401.0
Name: new_cases, dtype: float64
64836 64843    36571.0
Name: new_cases, dtype: float64
64837 64844    34457.0
Name: new_cases, dtype: float64
64838 64845    30948.0
Name: new_cases, dtype: float64
64839 64846    25072.0
Name: new_cases, dtype: float64
64840 64847    25467.0
Name: new_cases, dtype: float64
64841 64848    37593.0
Name: new_cases, dtype: float64
64842 64849    46164.0
Name: new_cases, dtype: float64
64843 64850    44658.0
Name: new_cases, dtype: float64
64844 64851    46759.0
Name: new_cases, dtype: float64
64845 64852    45083.0
Name: new_cases, dtype: float64
64846 64853    42909.0
Name: new_cases, dtype: float64
64847 64854    30941.0
Name: new_cases, dtype: float64
64848 64855    41965.0
Name: new_cases, dtype: float64
64849 64856    47092.0
Name: new_cases, dtype: float64
64850 64857    45352.0
Name: new_cases, dtype: float64
64851 64858    42618.0
Name: new_cases, dtype: float64
64852 64859    42766.0
Name: new_cases, dtype: float64
64853 64860    38948.0
Name: new_cases, dtype: float64
64854 64861    31222.0
Name: new_cases, dtype: float64
64855 64862    37875.0
Name: new_cases, dtype: float64
64856 64863    43263.0
Name: new_cases, dtype: float64
64857 64864    34973.0
Name: new_cases, dtype: float64
64858 64865    33376.0
Name: new_cases, dtype: float64
64859 64866    28591.0
Name: new_cases, dtype: float64
64860 64867    27254.0
Name: new_cases, dtype: float64
64861 64868    25404.0
Name: new_cases, dtype: float64
64862 64869    27176.0
Name: new_cases, dtype: float64
64863 64870    30570.0
Name: new_cases, dtype: float64
64864 64871    34403.0
Name: new_cases, dtype: float64
64865 64872    35662.0
Name: new_cases, dtype: float64
64866 64873    30773.0
Name: new_cases, dtype: float64
64867 64874    30256.0
Name: new_cases, dtype: float64
64868 64875    26115.0
Name: new_cases, dtype: float64
64869 64876    26964.0
Name: new_cases, dtype: float64
64870 64877    31923.0
Name: new_cases, dtype: float64
64871 64878    31382.0
Name: new_cases, dtype: float64
64872 64879    29616.0
Name: new_cases, dtype: float64
64873 64880    28326.0
Name: new_cases, dtype: float64
64874 64881    26041.0
Name: new_cases, dtype: float64
64875 64882    18795.0
Name: new_cases, dtype: float64
64876 64883    18870.0
Name: new_cases, dtype: float64
64877 64884    23529.0
Name: new_cases, dtype: float64
64878 64885    26727.0
Name: new_cases, dtype: float64
64879 64886    24354.0
Name: new_cases, dtype: float64
64880 64887    22842.0
Name: new_cases, dtype: float64
64881 64888    20799.0
Name: new_cases, dtype: float64
64882 64889    18346.0
Name: new_cases, dtype: float64
64883 64890    18833.0
Name: new_cases, dtype: float64
64884 64891    22431.0
Name: new_cases, dtype: float64
64885 64892    21257.0
Name: new_cases, dtype: float64
64886 64893    19740.0
Name: new_cases, dtype: float64
64887 64894    18166.0
Name: new_cases, dtype: float64
64888 64895    18132.0
Name: new_cases, dtype: float64
64889 64896    14313.0
Name: new_cases, dtype: float64
64890 64897    15823.0
Name: new_cases, dtype: float64
64891 64898    18987.0
Name: new_cases, dtype: float64
64892 64899    16862.0
Name: new_cases, dtype: float64
64893 64900    15981.0
Name: new_cases, dtype: float64
64894 64901    14146.0
Name: new_cases, dtype: float64
64895 64902    13596.0
Name: new_cases, dtype: float64
64896 64903    13058.0
Name: new_cases, dtype: float64
64897 64904    14623.0
Name: new_cases, dtype: float64
64898 64905    18454.0
Name: new_cases, dtype: float64
64899 64906    15786.0
Name: new_cases, dtype: float64
64900 64907    16326.0
Name: new_cases, dtype: float64
64901 64908    15906.0
Name: new_cases, dtype: float64
64902 64909    14306.0
Name: new_cases, dtype: float64
64903 64910    12428.0
Name: new_cases, dtype: float64
64904 64911    13451.0
Name: new_cases, dtype: float64
64905 64912    16156.0
Name: new_cases, dtype: float64
64906 64913    14348.0
Name: new_cases, dtype: float64
64907 64914    14313.0
Name: new_cases, dtype: float64
64908 64915    12830.0
Name: new_cases, dtype: float64
64909 64916    12514.0
Name: new_cases, dtype: float64
64910 64917    10423.0
Name: new_cases, dtype: float64
64911 64918    11903.0
Name: new_cases, dtype: float64
64912 64919    12885.0
Name: new_cases, dtype: float64
64913 64920    12729.0
Name: new_cases, dtype: float64
64914 64921    10929.0
Name: new_cases, dtype: float64
64915 64922    10826.0
Name: new_cases, dtype: float64
64916 64923    11478.0
Name: new_cases, dtype: float64
64917 64924    10126.0
Name: new_cases, dtype: float64

64918 64925    11466.0
Name: new_cases, dtype: float64
64919 64926    13091.0
Name: new_cases, dtype: float64
64920 64927    12516.0
Name: new_cases, dtype: float64
64921 64928    11850.0
Name: new_cases, dtype: float64
64922 64929    11271.0
Name: new_cases, dtype: float64
64923 64930    10229.0
Name: new_cases, dtype: float64
64924 64931    8865.0
Name: new_cases, dtype: float64
64925 64932    10197.0
Name: new_cases, dtype: float64
64926 64933    11919.0
Name: new_cases, dtype: float64
64927 64934    11106.0
Name: new_cases, dtype: float64
64928 64935    10302.0
Name: new_cases, dtype: float64
64929 64936    10488.0
Name: new_cases, dtype: float64
64930 64937    8488.0
Name: new_cases, dtype: float64
64931 64938    7579.0
Name: new_cases, dtype: float64
64932 64939    9283.0
Name: new_cases, dtype: float64
64933 64940    9119.0
Name: new_cases, dtype: float64
64934 64941    10549.0
Name: new_cases, dtype: float64
64935 64942    8318.0
Name: new_cases, dtype: float64
64936 64943    8774.0
Name: new_cases, dtype: float64
64937 64944    8309.0
Name: new_cases, dtype: float64
64938 64945    6990.0
Name: new_cases, dtype: float64
64939 64946    8954.0
Name: new_cases, dtype: float64
64940 64947    9765.0
Name: new_cases, dtype: float64
64941 64948    9216.0
Name: new_cases, dtype: float64
64942 64949    8603.0
Name: new_cases, dtype: float64
64943 64950    0.0
Name: new_cases, dtype: float64
64944 64951    17201.0
Name: new_cases, dtype: float64
64945 64952    6822.0
Name: new_cases, dtype: float64
64946 64953    8439.0
Name: new_cases, dtype: float64
64947 64954    9419.0
Name: new_cases, dtype: float64
64948 64955    8402.0
Name: new_cases, dtype: float64
64949 64956    7990.0
Name: new_cases, dtype: float64
64950 64957    7877.0
Name: new_cases, dtype: float64
64951 64958    7350.0
Name: new_cases, dtype: float64
64952 64959    5784.0
Name: new_cases, dtype: float64
64953 64960    6984.0
Name: new_cases, dtype: float64
64954 64961    7974.0
Name: new_cases, dtype: float64
64955 64962    7447.0
Name: new_cases, dtype: float64
64956 64963    0.0
Name: new_cases, dtype: float64
64957 64964    7145.0
Name: new_cases, dtype: float64
64958 64965    13644.0
Name: new_cases, dtype: float64
64959 64966    5326.0
Name: new_cases, dtype: float64
64960 64967    6317.0
Name: new_cases, dtype: float64
64961 64968    7495.0
Name: new_cases, dtype: float64
64962 64969    6650.0
Name: new_cases, dtype: float64
64963 64970    7189.0
Name: new_cases, dtype: float64
64964 64971    6987.0
Name: new_cases, dtype: float64
64965 64972    6531.0
Name: new_cases, dtype: float64
64966 64973    6358.0
Name: new_cases, dtype: float64
64967 64974    9195.0
Name: new_cases, dtype: float64
64968 64975    13154.0
Name: new_cases, dtype: float64
64969 64976    16764.0
Name: new_cases, dtype: float64
64970 64977    22775.0
Name: new_cases, dtype: float64
64971 64978    27553.0
Name: new_cases, dtype: float64
64972 64979    33750.0
Name: new_cases, dtype: float64
64973 64980    37379.0
Name: new_cases, dtype: float64
64974 64981    58097.0
Name: new_cases, dtype: float64
64975 64982    90928.0
Name: new_cases, dtype: float64
64976 64983    117100.0
Name: new_cases, dtype: float64
64977 64984    141986.0
Name: new_cases, dtype: float64
64978 64985    159632.0
Name: new_cases, dtype: float64
64979 64308    2.0
Name: new_cases, dtype: float64
64980 64309    0.0
Name: new_cases, dtype: float64
64981 64310    23.0
Name: new_cases, dtype: float64
64982 64311    2.0
Name: new_cases, dtype: float64
64983 64312    1.0
Name: new_cases, dtype: float64
64984 64313    3.0
Name: new_cases, dtype: float64
64985 64314    5.0
Name: new_cases, dtype: float64
64986 64993    13.0
Name: new_cases, dtype: float64
64987 64994    8.0
Name: new_cases, dtype: float64
64988 64995    7.0
Name: new_cases, dtype: float64
64989 64996    0.0
Name: new_cases, dtype: float64
64990 64997    35.0
Name: new_cases, dtype: float64
64991 64998    27.0
Name: new_cases, dtype: float64
64992 64999    21.0
Name: new_cases, dtype: float64
64993 65000    17.0
Name: new_cases, dtype: float64
64994 65001    38.0
Name: new_cases, dtype: float64
64995 65002    55.0
Name: new_cases, dtype: float64
64996 65003    84.0
Name: new_cases, dtype: float64
64997 65004    58.0
Name: new_cases, dtype: float64
64998 65005    81.0
Name: new_cases, dtype: float64
64999 65006    64.0
Name: new_cases, dtype: float64
65000 65007    65.0
Name: new_cases, dtype: float64
65001 65008    107.0
Name: new_cases, dtype: float64
65002 65009    104.0
Name: new_cases, dtype: float64
65003 65010    103.0
Name: new_cases, dtype: float64
65004 65011    153.0
Name: new_cases, dtype: float64
65005 65012    109.0
Name: new_cases, dtype: float64
65006 65013    130.0
Name: new_cases, dtype: float64
65007 65014    129.0
Name: new_cases, dtype: float64
65008 65015    114.0
Name: new_cases, dtype: float64
65009 65016    149.0
Name: new_cases, dtype: float64
65010 65017    113.0
Name: new_cases, dtype: float64
65011 65018    196.0
Name: new_cases, dtype: float64
65012 65019    106.0
Name: new_cases, dtype: float64
65013 65020    181.0
Name: new_cases, dtype: float64
65014 65021    218.0
Name: new_cases, dtype: float64
65015 65022    247.0
Name: new_cases, dtype: float64
65016 65023    218.0
Name: new_cases, dtype: float64
65017 65024    337.0
Name: new_cases, dtype: float64
65018 65025    219.0
Name: new_cases, dtype: float64
65019 65026    330.0
Name: new_cases, dtype: float64
65020 65027    399.0
Name: new_cases, dtype: float64
65021 65028    316.0
Name: new_cases, dtype: float64
65022 65029    282.0
Name: new_cases, dtype: float64
65023 65030    297.0
Name: new_cases, dtype: float64
65024 65031    380.0
Name: new_cases, dtype: float64
65025 65032    407.0
Name: new_cases, dtype: float64
65026 65033    325.0
Name: new_cases, dtype: float64
65027 65034    327.0
Name: new_cases, dtype: float64
65028 65035    185.0
Name: new_cases, dtype: float64
65029 65036    375.0
Name: new_cases, dtype: float64
65030 65037    283.0
Name: new_cases, dtype: float64
65031 65038    357.0
Name: new_cases, dtype: float64
65032 65039    436.0
Name: new_cases, dtype: float64
65033 65040    396.0
Name: new_cases, dtype: float64
65034 65041    275.0
Name: new_cases, dtype: float64
65035 65042    214.0
Name: new_cases, dtype: float64
65036 65043    415.0
Name: new_cases, dtype: float64
65037 65044    260.0
Name: new_cases, dtype: float64
65038 65045    347.0
Name: new_cases, dtype: float64
65039 65046    433.0
Name: new_cases, dtype: float64
65040 65047    292.0
Name: new_cases, dtype: float64
65041 65048    349.0
Name: new_cases, dtype: float64
65042 65049    395.0
Name: new_cases, dtype: float64
65043 65050    484.0
Name: new_cases, dtype: float64
65044 65051    367.0
Name: new_cases, dtype: float64
65045 65052    338.0
Name: new_cases, dtype: float64
65046 65053    336.0
Name: new_cases, dtype: float64
65047 65054    533.0
Name: new_cases, dtype: float64
65048 65055    387.0
Name: new_cases, dtype: float64
65049 65056    233.0
Name: new_cases, dtype: float64
65050 65057    484.0
Name: new_cases, dtype: float64
65051 65058    689.0
Name: new_cases, dtype: float64
65052 65059    568.0
Name: new_cases, dtype: float64
65053 65060    490.0
Name: new_cases, dtype: float64
65054 65061    529.0
Name: new_cases, dtype: float64
65055 65062    489.0
Name: new_cases, dtype: float64
65056 65063    496.0
Name: new_cases, dtype: float64
65057 65064    486.0
Name: new_cases, dtype: float64
65058 65065    693.0
Name: new_cases, dtype: float64
65059 65066    973.0
Name: new_cases, dtype: float64
65060 65067    634.0
Name: new_cases, dtype: float64
65061 65068    949.0
Name: new_cases, dtype: float64
65062 65069    526.0
Name: new_cases, dtype: float64
65063 65070    479.0
Name: new_cases, dtype: float64
65064 65071    415.0
Name: new_cases, dtype: float64
65065 65072    686.0
Name: new_cases, dtype: float64
65066 65073    687.0
Name: new_cases, dtype: float64
65067 65074    678.0
Name: new_cases, dtype: float64
65068 65075    557.0
Name: new_cases, dtype: float64
65069 65076    700.0
Name: new_cases, dtype: float64
65070 65077    467.0
Name: new_cases, dtype: float64
65071 65078    609.0
Name: new_cases, dtype: float64
65072 65079    684.0
Name: new_cases, dtype: float64
65073 65080    585.0
Name: new_cases, dtype: float64
65074 65081    703.0
Name: new_cases, dtype: float64
65075 65082    993.0
Name: new_cases, dtype: float64
65076 65083    672.0
Name: new_cases, dtype: float64

65077 65084    847.0
Name: new_cases, dtype: float64
65078 65085    1043.0
Name: new_cases, dtype: float64
65079 65086    1240.0
Name: new_cases, dtype: float64
65080 65087    979.0
Name: new_cases, dtype: float64
65081 65088    1111.0
Name: new_cases, dtype: float64
65082 65089    1014.0
Name: new_cases, dtype: float64
65083 65090    857.0
Name: new_cases, dtype: float64
65084 65091    1017.0
Name: new_cases, dtype: float64
65085 65092    1106.0
Name: new_cases, dtype: float64
65086 65093    1031.0
Name: new_cases, dtype: float64
65087 65094    1331.0
Name: new_cases, dtype: float64
65088 65095    1041.0
Name: new_cases, dtype: float64
65089 65096    1226.0
Name: new_cases, dtype: float64
65090 65097    862.0
Name: new_cases, dtype: float64
65091 65098    954.0
Name: new_cases, dtype: float64
65092 65099    1051.0
Name: new_cases, dtype: float64
65093 65100    1113.0
Name: new_cases, dtype: float64
65094 65101    1178.0
Name: new_cases, dtype: float64
65095 65102    1240.0
Name: new_cases, dtype: float64
65096 65103    1385.0
Name: new_cases, dtype: float64
65097 65104    1198.0
Name: new_cases, dtype: float64
65098 65105    1082.0
Name: new_cases, dtype: float64
65099 65106    1293.0
Name: new_cases, dtype: float64
65100 65107    1385.0
Name: new_cases, dtype: float64
65101 65108    1624.0
Name: new_cases, dtype: float64
65102 65109    1301.0
Name: new_cases, dtype: float64
65103 65110    1447.0
Name: new_cases, dtype: float64
65104 65111    1607.0
Name: new_cases, dtype: float64
65105 65112    1209.0
Name: new_cases, dtype: float64
65106 65113    1268.0
Name: new_cases, dtype: float64
65107 65114    1853.0
Name: new_cases, dtype: float64
65108 65115    2657.0
Name: new_cases, dtype: float64
65109 65116    1611.0
Name: new_cases, dtype: float64
65110 65117    1671.0
Name: new_cases, dtype: float64
65111 65118    1681.0
Name: new_cases, dtype: float64
65112 65119    1282.0
Name: new_cases, dtype: float64
65113 65120    1591.0
Name: new_cases, dtype: float64
65114 65121    1522.0
Name: new_cases, dtype: float64
65115 65122    1574.0
Name: new_cases, dtype: float64
65116 65123    1462.0
Name: new_cases, dtype: float64
65117 65124    1752.0
Name: new_cases, dtype: float64
65118 65125    1639.0
Name: new_cases, dtype: float64
65119 65126    1693.0
Name: new_cases, dtype: float64
65120 65127    1655.0
Name: new_cases, dtype: float64
65121 65128    1882.0
Name: new_cases, dtype: float64
65122 65129    1906.0
Name: new_cases, dtype: float64
65123 65130    1761.0
Name: new_cases, dtype: float64
65124 65131    1868.0
Name: new_cases, dtype: float64
65125 65132    1492.0
Name: new_cases, dtype: float64
65126 65133    1525.0
Name: new_cases, dtype: float64
65127 65134    1748.0
Name: new_cases, dtype: float64
65128 65135    2381.0
Name: new_cases, dtype: float64
65129 65136    1904.0
Name: new_cases, dtype: float64
65130 65137    2040.0
Name: new_cases, dtype: float64
65131 65138    1560.0
Name: new_cases, dtype: float64
65132 65139    1519.0
Name: new_cases, dtype: float64
65133 65140    1679.0
Name: new_cases, dtype: float64
65134 65141    1922.0
Name: new_cases, dtype: float64
65135 65142    1815.0
Name: new_cases, dtype: float64
65136 65143    1882.0
Name: new_cases, dtype: float64
65137 65144    2473.0
Name: new_cases, dtype: float64
65138 65145    2277.0
Name: new_cases, dtype: float64
65139 65146    1893.0
Name: new_cases, dtype: float64
65140 65147    1687.0
Name: new_cases, dtype: float64
65141 65148    1693.0
Name: new_cases, dtype: float64
65142 65149    1942.0
Name: new_cases, dtype: float64
65143 65150    2098.0
Name: new_cases, dtype: float64
65144 65151    2307.0
Name: new_cases, dtype: float64
65145 65152    2345.0
Name: new_cases, dtype: float64
65146 65153    2081.0
Name: new_cases, dtype: float64
65147 65154    1821.0
Name: new_cases, dtype: float64
65148 65155    1673.0
Name: new_cases, dtype: float64
65149 65156    1902.0
Name: new_cases, dtype: float64
65150 65157    2266.0
Name: new_cases, dtype: float64
65151 65158    2197.0
Name: new_cases, dtype: float64
65152 65159    2090.0
Name: new_cases, dtype: float64
65153 65160    2037.0
Name: new_cases, dtype: float64
65154 65161    1877.0
Name: new_cases, dtype: float64
65155 65162    2447.0
Name: new_cases, dtype: float64
65156 65163    2306.0
Name: new_cases, dtype: float64
65157 65164    2719.0
Name: new_cases, dtype: float64
65158 65165    3003.0
Name: new_cases, dtype: float64
65159 65166    3308.0
Name: new_cases, dtype: float64
65160 65167    2858.0
Name: new_cases, dtype: float64
65161 65168    2743.0
Name: new_cases, dtype: float64
65162 65169    2775.0
Name: new_cases, dtype: float64
65163 65170    3075.0
Name: new_cases, dtype: float64
65164 65171    3622.0
Name: new_cases, dtype: float64
65165 65172    3269.0
Name: new_cases, dtype: float64
65166 65173    3128.0
Name: new_cases, dtype: float64
65167 65174    3444.0
Name: new_cases, dtype: float64
65168 65175    2880.0
Name: new_cases, dtype: float64
65169 65176    3046.0
Name: new_cases, dtype: float64
65170 65177    3307.0
Name: new_cases, dtype: float64
65171 65178    3861.0
Name: new_cases, dtype: float64
65172 65179    3737.0
Name: new_cases, dtype: float64
65173 65180    3806.0
Name: new_cases, dtype: float64
65174 65181    3636.0
Name: new_cases, dtype: float64
65175 65182    3141.0
Name: new_cases, dtype: float64
65176 65183    3507.0
Name: new_cases, dtype: float64
65177 65184    3963.0
Name: new_cases, dtype: float64
65178 65185    3635.0
Name: new_cases, dtype: float64
65179 65186    3891.0
Name: new_cases, dtype: float64
65180 65187    4168.0
Name: new_cases, dtype: float64
65181 65188    3989.0
Name: new_cases, dtype: float64
65182 65189    4176.0
Name: new_cases, dtype: float64
65183 65190    4071.0
Name: new_cases, dtype: float64
65184 65191    4465.0
Name: new_cases, dtype: float64
65185 65192    4634.0
Name: new_cases, dtype: float64
65186 65193    4823.0
Name: new_cases, dtype: float64
65187 65194    4494.0
Name: new_cases, dtype: float64
65188 65195    3874.0
Name: new_cases, dtype: float64
65189 65196    3509.0
Name: new_cases, dtype: float64
65190 65197    4002.0
Name: new_cases, dtype: float64
65191 65198    4284.0
Name: new_cases, dtype: float64
65192 65199    4174.0
Name: new_cases, dtype: float64
65193 65200    4317.0
Name: new_cases, dtype: float64
65194 65201    4007.0
Name: new_cases, dtype: float64
65195 65202    3992.0
Name: new_cases, dtype: float64
65196 65203    3622.0
Name: new_cases, dtype: float64
65197 65204    4056.0
Name: new_cases, dtype: float64
65198 65205    4538.0
Name: new_cases, dtype: float64
65199 65206    4850.0
Name: new_cases, dtype: float64
65200 65207    4094.0
Name: new_cases, dtype: float64
65201 65208    4294.0
Name: new_cases, dtype: float64
65202 65209    4497.0
Name: new_cases, dtype: float64
65203 65210    3267.0
Name: new_cases, dtype: float64
65204 65211    3906.0
Name: new_cases, dtype: float64
65205 65212    4127.0
Name: new_cases, dtype: float64
65206 65213    4411.0
Name: new_cases, dtype: float64
65207 65214    4301.0
Name: new_cases, dtype: float64
65208 65215    4301.0
Name: new_cases, dtype: float64
65209 65216    4105.0
Name: new_cases, dtype: float64
65210 65217    3373.0
Name: new_cases, dtype: float64
65211 65218    3602.0
Name: new_cases, dtype: float64
65212 65219    4267.0
Name: new_cases, dtype: float64
65213 65220    4432.0
Name: new_cases, dtype: float64
65214 65221    4369.0
Name: new_cases, dtype: float64
65215 65222    4070.0
Name: new_cases, dtype: float64
65216 65223    3732.0
Name: new_cases, dtype: float64
65217 65224    3222.0
Name: new_cases, dtype: float64
65218 65225    3520.0
Name: new_cases, dtype: float64
65219 65226    4029.0
Name: new_cases, dtype: float64
65220 65227    3565.0
Name: new_cases, dtype: float64
65221 65228    2897.0
Name: new_cases, dtype: float64
65222 65229    3143.0
Name: new_cases, dtype: float64
65223 65230    2696.0
Name: new_cases, dtype: float64
65224 65231    2618.0
Name: new_cases, dtype: float64
65225 65232    2973.0
Name: new_cases, dtype: float64
65226 65233    3356.0
Name: new_cases, dtype: float64
65227 65234    4065.0
Name: new_cases, dtype: float64
65228 65235    3778.0
Name: new_cases, dtype: float64
65229 65236    4262.0
Name: new_cases, dtype: float64
65230 65237    3880.0
Name: new_cases, dtype: float64
65231 65238    2853.0
Name: new_cases, dtype: float64
65232 65239    3779.0
Name: new_cases, dtype: float64
65233 65240    3770.0
Name: new_cases, dtype: float64
65234 65241    4173.0
Name: new_cases, dtype: float64
65235 65242    5444.0
Name: new_cases, dtype: float64
65236 65243    5272.0
Name: new_cases, dtype: float64
65237 65244    4106.0
Name: new_cases, dtype: float64
65238 65245    3535.0
Name: new_cases, dtype: float64
65239 65246    3807.0
Name: new_cases, dtype: float64
65240 65247    4265.0
Name: new_cases, dtype: float64
65241 65248    4798.0
Name: new_cases, dtype: float64
65242 65249    4792.0
Name: new_cases, dtype: float64
65243 65250    4998.0
Name: new_cases, dtype: float64
65244 65251    4360.0
Name: new_cases, dtype: float64
65245 65252    4442.0
Name: new_cases, dtype: float64
65246 65253    4192.0
Name: new_cases, dtype: float64
65247 65254    5534.0
Name: new_cases, dtype: float64
65248 65255    4917.0
Name: new_cases, dtype: float64
65249 65256    5828.0
Name: new_cases, dtype: float64
65250 65257    5418.0
Name: new_cases, dtype: float64

65251 65258    6267.0
Name: new_cases, dtype: float64
65252 65259    4617.0
Name: new_cases, dtype: float64
65253 65260    5092.0
Name: new_cases, dtype: float64
65254 65261    5533.0
Name: new_cases, dtype: float64
65255 65262    8369.0
Name: new_cases, dtype: float64
65256 65263    5803.0
Name: new_cases, dtype: float64
65257 65264    6027.0
Name: new_cases, dtype: float64
65258 65265    6089.0
Name: new_cases, dtype: float64
65259 65266    5754.0
Name: new_cases, dtype: float64
65260 65267    5292.0
Name: new_cases, dtype: float64
65261 65268    6058.0
Name: new_cases, dtype: float64
65262 65269    6033.0
Name: new_cases, dtype: float64
65263 65270    6310.0
Name: new_cases, dtype: float64
65264 65271    6388.0
Name: new_cases, dtype: float64
65265 65272    6189.0
Name: new_cases, dtype: float64
65266 65273    5489.0
Name: new_cases, dtype: float64
65267 65274    6120.0
Name: new_cases, dtype: float64
65268 65275    6725.0
Name: new_cases, dtype: float64
65269 65276    7354.0
Name: new_cases, dtype: float64
65270 65277    6689.0
Name: new_cases, dtype: float64
65271 65278    7751.0
Name: new_cases, dtype: float64
65272 65279    6982.0
Name: new_cases, dtype: float64
65273 65280    6848.0
Name: new_cases, dtype: float64
65274 65281    6347.0
Name: new_cases, dtype: float64
65275 65282    7514.0
Name: new_cases, dtype: float64
65276 65283    7199.0
Name: new_cases, dtype: float64
65277 65284    7259.0
Name: new_cases, dtype: float64
65278 65285    6740.0
Name: new_cases, dtype: float64
65279 65286    6528.0
Name: new_cases, dtype: float64
65280 65287    5854.0
Name: new_cases, dtype: float64
65281 65288    7903.0
Name: new_cases, dtype: float64
65282 65289    8002.0
Name: new_cases, dtype: float64
65283 65290    8074.0
Name: new_cases, dtype: float64
65284 65291    8072.0
Name: new_cases, dtype: float64
65285 65292    7203.0
Name: new_cases, dtype: float64
65286 65293    6877.0
Name: new_cases, dtype: float64
65287 65294    6753.0
Name: new_cases, dtype: float64
65288 65295    7445.0
Name: new_cases, dtype: float64
65289 65296    8854.0
Name: new_cases, dtype: float64
65290 65297    9321.0
Name: new_cases, dtype: float64
65291 65298    10617.0
Name: new_cases, dtype: float64
65292 65299    10046.0
Name: new_cases, dtype: float64
65293 65300    9640.0
Name: new_cases, dtype: float64
65294 65301    8692.0
Name: new_cases, dtype: float64
65295 65302    10047.0
Name: new_cases, dtype: float64
65296 65303    11278.0
Name: new_cases, dtype: float64
65297 65304    11557.0
Name: new_cases, dtype: float64
65298 65305    12818.0
Name: new_cases, dtype: float64
65299 65306    14224.0
Name: new_cases, dtype: float64
65300 65307    11287.0
Name: new_cases, dtype: float64
65301 65308    9086.0
Name: new_cases, dtype: float64
65302 65309    10365.0
Name: new_cases, dtype: float64
65303 65310    12568.0
Name: new_cases, dtype: float64
65304 65311    11703.0
Name: new_cases, dtype: float64
65305 65312    13632.0
Name: new_cases, dtype: float64
65306 65313    12191.0
Name: new_cases, dtype: float64
65307 65314    11788.0
Name: new_cases, dtype: float64
65308 65315    9994.0
Name: new_cases, dtype: float64
65309 65316    13094.0
Name: new_cases, dtype: float64
65310 65317    11948.0
Name: new_cases, dtype: float64
65311 65318    13695.0
Name: new_cases, dtype: float64
65312 65319    13802.0
Name: new_cases, dtype: float64
65313 65320    14518.0
Name: new_cases, dtype: float64
65314 65321    12001.0
Name: new_cases, dtype: float64
65315 65322    10994.0
Name: new_cases, dtype: float64
65316 65323    10379.0
Name: new_cases, dtype: float64
65317 65324    11984.0
Name: new_cases, dtype: float64
65318 65325    11434.0
Name: new_cases, dtype: float64
65319 65326    11749.0
Name: new_cases, dtype: float64
65320 65327    12156.0
Name: new_cases, dtype: float64
65321 65328    10827.0
Name: new_cases, dtype: float64
65322 65329    8242.0
Name: new_cases, dtype: float64
65323 65330    8700.0
Name: new_cases, dtype: float64
65324 65331    8776.0
Name: new_cases, dtype: float64
65325 65332    8435.0
Name: new_cases, dtype: float64
65326 65333    9869.0
Name: new_cases, dtype: float64
65327 65334    8844.0
Name: new_cases, dtype: float64
65328 65335    6765.0
Name: new_cases, dtype: float64
65329 65336    6462.0
Name: new_cases, dtype: float64
65330 65337    10029.0
Name: new_cases, dtype: float64
65331 65338    9687.0
Name: new_cases, dtype: float64
65332 65339    9039.0
Name: new_cases, dtype: float64
65333 65340    10614.0
Name: new_cases, dtype: float64
65334 65341    8054.0
Name: new_cases, dtype: float64
65335 65342    7300.0
Name: new_cases, dtype: float64
65336 65343    10180.0
Name: new_cases, dtype: float64
65337 65344    9775.0
Name: new_cases, dtype: float64
65338 65345    7533.0
Name: new_cases, dtype: float64
65339 65346    8493.0
Name: new_cases, dtype: float64
65340 65347    8232.0
Name: new_cases, dtype: float64
65341 65348    6208.0
Name: new_cases, dtype: float64
65342 65349    5560.0
Name: new_cases, dtype: float64
65343 65350    6680.0
Name: new_cases, dtype: float64
65344 65351    5712.0
Name: new_cases, dtype: float64
65345 65352    6808.0
Name: new_cases, dtype: float64
65346 65353    7264.0
Name: new_cases, dtype: float64
65347 65354    6971.0
Name: new_cases, dtype: float64
65348 65355    5767.0
Name: new_cases, dtype: float64
65349 65356    5826.0
Name: new_cases, dtype: float64
65350 65357    6894.0
Name: new_cases, dtype: float64
65351 65358    6389.0
Name: new_cases, dtype: float64
65352 65359    5633.0
Name: new_cases, dtype: float64
65353 65360    5144.0
Name: new_cases, dtype: float64
65354 65361    6412.0
Name: new_cases, dtype: float64
65355 65362    4607.0
Name: new_cases, dtype: float64
65356 65363    4714.0
Name: new_cases, dtype: float64
65357 65364    5589.0
Name: new_cases, dtype: float64
65358 65365    5414.0
Name: new_cases, dtype: float64
65359 65366    6825.0
Name: new_cases, dtype: float64
65360 65367    6570.0
Name: new_cases, dtype: float64
65361 65368    6279.0
Name: new_cases, dtype: float64
65362 65369    5656.0
Name: new_cases, dtype: float64
65363 65370    4396.0
Name: new_cases, dtype: float64
65364 65371    5744.0
Name: new_cases, dtype: float64
65365 65372    5297.0
Name: new_cases, dtype: float64
65366 65373    5227.0
Name: new_cases, dtype: float64
65367 65374    6107.0
Name: new_cases, dtype: float64
65368 65375    4982.0
Name: new_cases, dtype: float64
65369 65376    4461.0
Name: new_cases, dtype: float64
65370 65377    4083.0
Name: new_cases, dtype: float64
65371 65378    5008.0
Name: new_cases, dtype: float64
65372 65379    4682.0
Name: new_cases, dtype: float64
65373 65380    5937.0
Name: new_cases, dtype: float64
65374 65381    6142.0
Name: new_cases, dtype: float64
65375 65382    5325.0
Name: new_cases, dtype: float64
65376 65383    4345.0
Name: new_cases, dtype: float64
65377 65384    6731.0
Name: new_cases, dtype: float64
65378 65385    3712.0
Name: new_cases, dtype: float64
65379 65386    4549.0
Name: new_cases, dtype: float64
65380 65387    4860.0
Name: new_cases, dtype: float64
65381 65388    5504.0
Name: new_cases, dtype: float64
65382 65389    5265.0
Name: new_cases, dtype: float64
65383 65390    4723.0
Name: new_cases, dtype: float64
65384 65391    4127.0
Name: new_cases, dtype: float64
65385 65392    4829.0
Name: new_cases, dtype: float64
65386 65393    5702.0
Name: new_cases, dtype: float64
65387 65394    5656.0
Name: new_cases, dtype: float64
65388 65395    6177.0
Name: new_cases, dtype: float64
65389 65396    5363.0
Name: new_cases, dtype: float64
65390 65397    5041.0
Name: new_cases, dtype: float64
65391 65398    4585.0
Name: new_cases, dtype: float64
65392 65399    4952.0
Name: new_cases, dtype: float64
65393 65400    5549.0
Name: new_cases, dtype: float64
65394 65401    5720.0
Name: new_cases, dtype: float64
65395 65402    6243.0
Name: new_cases, dtype: float64
65396 65403    5436.0
Name: new_cases, dtype: float64
65397 65404    4544.0
Name: new_cases, dtype: float64
65398 65405    4402.0
Name: new_cases, dtype: float64
65399 65406    5944.0
Name: new_cases, dtype: float64
65400 65407    4656.0
Name: new_cases, dtype: float64
65401 65408    5241.0
Name: new_cases, dtype: float64
65402 65409    5833.0
Name: new_cases, dtype: float64
65403 65410    5500.0
Name: new_cases, dtype: float64
65404 65411    4512.0
Name: new_cases, dtype: float64
65405 65412    4394.0
Name: new_cases, dtype: float64
65406 65413    4730.0
Name: new_cases, dtype: float64
65407 65414    4369.0
Name: new_cases, dtype: float64
65408 65415    5285.0
Name: new_cases, dtype: float64
65409 65416    5647.0
Name: new_cases, dtype: float64
65410 65417    6327.0
Name: new_cases, dtype: float64
65411 65418    6130.0
Name: new_cases, dtype: float64
65412 65419    3922.0
Name: new_cases, dtype: float64
65413 65420    4891.0
Name: new_cases, dtype: float64

65414 65421    5021.0
Name: new_cases, dtype: float64
65415 65422    4608.0
Name: new_cases, dtype: float64
65416 65423    3448.0
Name: new_cases, dtype: float64
65417 65424    2633.0
Name: new_cases, dtype: float64
65418 65425    2385.0
Name: new_cases, dtype: float64
65419 65426    3080.0
Name: new_cases, dtype: float64
65420 65427    4295.0
Name: new_cases, dtype: float64
65421 65428    4185.0
Name: new_cases, dtype: float64
65422 65429    4871.0
Name: new_cases, dtype: float64
65423 65430    5797.0
Name: new_cases, dtype: float64
65424 65431    5746.0
Name: new_cases, dtype: float64
65425 65432    5296.0
Name: new_cases, dtype: float64
65426 65433    5280.0
Name: new_cases, dtype: float64
65427 65434    5907.0
Name: new_cases, dtype: float64
65428 65435    5060.0
Name: new_cases, dtype: float64
65429 65436    5034.0
Name: new_cases, dtype: float64
65430 65437    6278.0
Name: new_cases, dtype: float64
65431 65438    5862.0
Name: new_cases, dtype: float64
65432 65439    6565.0
Name: new_cases, dtype: float64
65433 65440    6115.0
Name: new_cases, dtype: float64
65434 65441    5662.0
Name: new_cases, dtype: float64
65435 65442    4824.0
Name: new_cases, dtype: float64
65436 65443    5246.0
Name: new_cases, dtype: float64
65437 65444    5353.0
Name: new_cases, dtype: float64
65438 65445    6486.0
Name: new_cases, dtype: float64
65439 65446    6594.0
Name: new_cases, dtype: float64
65440 65447    5832.0
Name: new_cases, dtype: float64
65441 65448    6993.0
Name: new_cases, dtype: float64
65442 65449    6294.0
Name: new_cases, dtype: float64
65443 65450    7725.0
Name: new_cases, dtype: float64
65444 65451    8892.0
Name: new_cases, dtype: float64
65445 65452    8083.0
Name: new_cases, dtype: float64
65446 65453    7465.0
Name: new_cases, dtype: float64
65447 65454    9868.0
Name: new_cases, dtype: float64
65448 65455    8189.0
Name: new_cases, dtype: float64
65449 65456    8161.0
Name: new_cases, dtype: float64
65450 65457    9944.0
Name: new_cases, dtype: float64
65451 65458    12624.0
Name: new_cases, dtype: float64
65452 65459    12990.0
Name: new_cases, dtype: float64
65453 65460    12906.0
Name: new_cases, dtype: float64
65454 65461    13737.0
Name: new_cases, dtype: float64
65455 65462    14536.0
Name: new_cases, dtype: float64
65456 65463    13668.0
Name: new_cases, dtype: float64
65457 65464    15308.0
Name: new_cases, dtype: float64
65458 65465    20574.0
Name: new_cases, dtype: float64
65459 65466    18872.0
Name: new_cases, dtype: float64
65460 65467    21095.0
Name: new_cases, dtype: float64
65461 65468    21342.0
Name: new_cases, dtype: float64
65462 65469    20694.0
Name: new_cases, dtype: float64
65463 65470    20467.0
Name: new_cases, dtype: float64
65464 65471    21807.0
Name: new_cases, dtype: float64
65465 65472    24836.0
Name: new_cases, dtype: float64
65466 65473    25830.0
Name: new_cases, dtype: float64
65467 65474    27913.0
Name: new_cases, dtype: float64
65468 65475    27233.0
Name: new_cases, dtype: float64
65469 65476    29745.0
Name: new_cases, dtype: float64
65470 65477    31189.0
Name: new_cases, dtype: float64
65471 65478    34379.0
Name: new_cases, dtype: float64
65472 65479    38391.0
Name: new_cases, dtype: float64
65473 65480    38124.0
Name: new_cases, dtype: float64
65474 65481    35094.0
Name: new_cases, dtype: float64
65475 65482    36197.0
Name: new_cases, dtype: float64
65476 65483    40427.0
Name: new_cases, dtype: float64
65477 65484    47899.0
Name: new_cases, dtype: float64
65478 65485    54517.0
Name: new_cases, dtype: float64
65479 65486    56757.0
Name: new_cases, dtype: float64
65480 65487    54000.0
Name: new_cases, dtype: float64
65481 65488    51952.0
Name: new_cases, dtype: float64
65482 65489    44721.0
Name: new_cases, dtype: float64
65483 65490    34257.0
Name: new_cases, dtype: float64
65484 65491    38325.0
Name: new_cases, dtype: float64
65485 65492    33772.0
Name: new_cases, dtype: float64
65486 65493    49509.0
Name: new_cases, dtype: float64
65487 65494    49071.0
Name: new_cases, dtype: float64
65488 65495    45416.0
Name: new_cases, dtype: float64
65489 65496    38679.0
Name: new_cases, dtype: float64
65490 65497    28228.0
Name: new_cases, dtype: float64
65491 65498    45203.0
Name: new_cases, dtype: float64
65492 65499    47791.0
Name: new_cases, dtype: float64
65493 65500    43479.0
Name: new_cases, dtype: float64
65494 65501    41168.0
Name: new_cases, dtype: float64
65495 65502    37284.0
Name: new_cases, dtype: float64
65496 65503    30738.0
Name: new_cases, dtype: float64
65497 65504    22404.0
Name: new_cases, dtype: float64
65498 65505    33900.0
Name: new_cases, dtype: float64
65499 65506    35867.0
Name: new_cases, dtype: float64
65500 65507    35764.0
Name: new_cases, dtype: float64
65501 65508    39532.0
Name: new_cases, dtype: float64
65502 65509    31753.0
Name: new_cases, dtype: float64
65503 65510    26415.0
Name: new_cases, dtype: float64
65504 65511    20709.0
Name: new_cases, dtype: float64
65505 65512    32081.0
Name: new_cases, dtype: float64
65506 65513    30625.0
Name: new_cases, dtype: float64
65507 65514    24709.0
Name: new_cases, dtype: float64
65508 65515    30788.0
Name: new_cases, dtype: float64
65509 65516    28598.0
Name: new_cases, dtype: float64
65510 65517    20813.0
Name: new_cases, dtype: float64
65511 65518    17384.0
Name: new_cases, dtype: float64
65512 65519    20741.0
Name: new_cases, dtype: float64
65513 65520    15768.0
Name: new_cases, dtype: float64
65514 65521    22053.0
Name: new_cases, dtype: float64
65515 65522    20004.0
Name: new_cases, dtype: float64
65516 65523    16744.0
Name: new_cases, dtype: float64
65517 65524    12408.0
Name: new_cases, dtype: float64
65518 65525    9604.0
Name: new_cases, dtype: float64
65519 65526    19106.0
Name: new_cases, dtype: float64
65520 65527    18671.0
Name: new_cases, dtype: float64
65521 65528    16899.0
Name: new_cases, dtype: float64
65522 65529    12618.0
Name: new_cases, dtype: float64
65523 65530    10050.0
Name: new_cases, dtype: float64
65524 65531    7427.0
Name: new_cases, dtype: float64
65525 65532    5436.0
Name: new_cases, dtype: float64
65526 65533    10534.0
Name: new_cases, dtype: float64
65527 65534    10337.0
Name: new_cases, dtype: float64
65528 65535    0.0
Name: new_cases, dtype: float64
65529 65536    16752.0
Name: new_cases, dtype: float64
65530 65537    6727.0
Name: new_cases, dtype: float64
65531 65538    5403.0
Name: new_cases, dtype: float64
65532 65539    4413.0
Name: new_cases, dtype: float64
65533 65540    7201.0
Name: new_cases, dtype: float64
65534 65541    6731.0
Name: new_cases, dtype: float64
65535 65542    5990.0
Name: new_cases, dtype: float64
65536 65543    5376.0
Name: new_cases, dtype: float64
65537 65544    5001.0
Name: new_cases, dtype: float64
65538 65545    3779.0
Name: new_cases, dtype: float64
65539 65546    2577.0
Name: new_cases, dtype: float64
65540 65547    4128.0
Name: new_cases, dtype: float64
65541 65548    3948.0
Name: new_cases, dtype: float64
65542 65549    3145.0
Name: new_cases, dtype: float64
65543 65550    3835.0
Name: new_cases, dtype: float64
65544 65551    3385.0
Name: new_cases, dtype: float64
65545 65552    2234.0
Name: new_cases, dtype: float64
65546 65553    1932.0
Name: new_cases, dtype: float64
65547 65554    3263.0
Name: new_cases, dtype: float64
65548 65555    2720.0
Name: new_cases, dtype: float64
65549 65556    2881.0
Name: new_cases, dtype: float64
65550 65557    2557.0
Name: new_cases, dtype: float64
65551 65558    2137.0
Name: new_cases, dtype: float64
65552 65559    1760.0
Name: new_cases, dtype: float64
65553 65560    1390.0
Name: new_cases, dtype: float64
65554 65561    2057.0
Name: new_cases, dtype: float64
65555 65562    1954.0
Name: new_cases, dtype: float64
65556 65563    1690.0
Name: new_cases, dtype: float64
65557 65564    1624.0
Name: new_cases, dtype: float64
65558 65565    1414.0
Name: new_cases, dtype: float64
65559 65566    1142.0
Name: new_cases, dtype: float64
65560 65567    922.0
Name: new_cases, dtype: float64
65561 65568    1404.0
Name: new_cases, dtype: float64
65562 65569    1484.0
Name: new_cases, dtype: float64
65563 65570    1393.0
Name: new_cases, dtype: float64
65564 65571    1384.0
Name: new_cases, dtype: float64
65565 65572    1167.0
Name: new_cases, dtype: float64
65566 65573    894.0
Name: new_cases, dtype: float64
65567 65574    620.0
Name: new_cases, dtype: float64
65568 65575    1261.0
Name: new_cases, dtype: float64
65569 65576    1233.0
Name: new_cases, dtype: float64
65570 65577    1053.0
Name: new_cases, dtype: float64
65571 65578    915.0
Name: new_cases, dtype: float64
65572 65579    997.0
Name: new_cases, dtype: float64
65573 65580    747.0
Name: new_cases, dtype: float64

65574 65581    626.0
Name: new_cases, dtype: float64
65575 65582    903.0
Name: new_cases, dtype: float64
65576 65583    914.0
Name: new_cases, dtype: float64
65577 65584    633.0
Name: new_cases, dtype: float64
65578 65585    760.0
Name: new_cases, dtype: float64
65579 65586    802.0
Name: new_cases, dtype: float64
65580 65587    623.0
Name: new_cases, dtype: float64
65581 65588    460.0
Name: new_cases, dtype: float64
65582 65589    611.0
Name: new_cases, dtype: float64
65583 65590    719.0
Name: new_cases, dtype: float64
65584 65591    723.0
Name: new_cases, dtype: float64
65585 65592    683.0
Name: new_cases, dtype: float64
65586 65593    620.0
Name: new_cases, dtype: float64
65587 65594    523.0
Name: new_cases, dtype: float64
65588 65595    403.0
Name: new_cases, dtype: float64
65589 65596    612.0
Name: new_cases, dtype: float64
65590 65597    801.0
Name: new_cases, dtype: float64
65591 65598    628.0
Name: new_cases, dtype: float64
65592 65599    518.0
Name: new_cases, dtype: float64
65593 65600    401.0
Name: new_cases, dtype: float64
65594 65601    444.0
Name: new_cases, dtype: float64
65595 65602    244.0
Name: new_cases, dtype: float64
65596 65603    434.0
Name: new_cases, dtype: float64
65597 65604    480.0
Name: new_cases, dtype: float64
65598 65605    435.0
Name: new_cases, dtype: float64
65599 65606    399.0
Name: new_cases, dtype: float64
65600 65607    359.0
Name: new_cases, dtype: float64
65601 65608    339.0
Name: new_cases, dtype: float64
65602 65609    221.0
Name: new_cases, dtype: float64
65603 65610    347.0
Name: new_cases, dtype: float64
65604 65611    522.0
Name: new_cases, dtype: float64
65605 65612    400.0
Name: new_cases, dtype: float64
65606 65613    360.0
Name: new_cases, dtype: float64
65607 65614    393.0
Name: new_cases, dtype: float64
65608 65615    314.0
Name: new_cases, dtype: float64
65609 65616    186.0
Name: new_cases, dtype: float64
65610 65617    394.0
Name: new_cases, dtype: float64
65611 65618    451.0
Name: new_cases, dtype: float64
65612 65619    372.0
Name: new_cases, dtype: float64
65613 65620    453.0
Name: new_cases, dtype: float64
65614 65621    404.0
Name: new_cases, dtype: float64
65615 65622    264.0
Name: new_cases, dtype: float64
65616 65623    176.0
Name: new_cases, dtype: float64
65617 65624    297.0
Name: new_cases, dtype: float64
65618 65625    278.0
Name: new_cases, dtype: float64
65619 65626    311.0
Name: new_cases, dtype: float64
65620 65627    245.0
Name: new_cases, dtype: float64
65621 65628    246.0
Name: new_cases, dtype: float64
65622 65629    196.0
Name: new_cases, dtype: float64
65623 65630    130.0
Name: new_cases, dtype: float64
65624 65631    261.0
Name: new_cases, dtype: float64
65625 65632    264.0
Name: new_cases, dtype: float64
65626 65633    220.0
Name: new_cases, dtype: float64
65627 65634    192.0
Name: new_cases, dtype: float64
65628 65635    228.0
Name: new_cases, dtype: float64
65629 65636    163.0
Name: new_cases, dtype: float64
65630 65637    106.0
Name: new_cases, dtype: float64
65631 65638    190.0
Name: new_cases, dtype: float64
65632 65639    205.0
Name: new_cases, dtype: float64
65633 65640    213.0
Name: new_cases, dtype: float64
65634 65641    291.0
Name: new_cases, dtype: float64
65635 65642    232.0
Name: new_cases, dtype: float64
65636 65643    164.0
Name: new_cases, dtype: float64
65637 65644    133.0
Name: new_cases, dtype: float64
65638 65645    216.0
Name: new_cases, dtype: float64
65639 65646    179.0
Name: new_cases, dtype: float64
65640 65647    136.0
Name: new_cases, dtype: float64
65641 65648    204.0
Name: new_cases, dtype: float64
65642 65649    255.0
Name: new_cases, dtype: float64
65643 65650    0.0
Name: new_cases, dtype: float64
65644 65651    212.0
Name: new_cases, dtype: float64
65645 65652    278.0
Name: new_cases, dtype: float64
65646 65653    194.0
Name: new_cases, dtype: float64
65647 65654    189.0
Name: new_cases, dtype: float64
65648 65655    180.0
Name: new_cases, dtype: float64
65649 65656    274.0
Name: new_cases, dtype: float64
65650 65657    174.0
Name: new_cases, dtype: float64
65651 65658    265.0
Name: new_cases, dtype: float64
65652 65659    299.0
Name: new_cases, dtype: float64
65653 65660    404.0
Name: new_cases, dtype: float64
65654 65661    533.0
Name: new_cases, dtype: float64
65655 65662    518.0
Name: new_cases, dtype: float64
65656 65663    479.0
Name: new_cases, dtype: float64
65657 Series([], Name: new_cases, dtype: float64)
65658 Series([], Name: new_cases, dtype: float64)
65659 64986    2.0
Name: new_cases, dtype: float64
65660 64987    0.0
Name: new_cases, dtype: float64
65661 64988    0.0
Name: new_cases, dtype: float64
65662 64989    0.0
Name: new_cases, dtype: float64
65663 64990    2.0
Name: new_cases, dtype: float64
67741 67748    0.0
Name: new_cases, dtype: float64
67742 67749    1.0
Name: new_cases, dtype: float64
67743 67750    2.0
Name: new_cases, dtype: float64
67744 67751    13.0
Name: new_cases, dtype: float64
67745 67752    9.0
Name: new_cases, dtype: float64
67746 67753    0.0
Name: new_cases, dtype: float64
67747 67754    47.0
Name: new_cases, dtype: float64
67748 67755    39.0
Name: new_cases, dtype: float64
67749 67756    0.0
Name: new_cases, dtype: float64
67750 67757    40.0
Name: new_cases, dtype: float64
67751 67758    54.0
Name: new_cases, dtype: float64
67752 67759    69.0
Name: new_cases, dtype: float64
67753 67760    265.0
Name: new_cases, dtype: float64
67754 67761    126.0
Name: new_cases, dtype: float64
67755 67762    102.0
Name: new_cases, dtype: float64
67756 67763    121.0
Name: new_cases, dtype: float64
67757 67764    219.0
Name: new_cases, dtype: float64
67758 67765    204.0
Name: new_cases, dtype: float64
67759 67766    235.0
Name: new_cases, dtype: float64
67760 67767    255.0
Name: new_cases, dtype: float64
67761 67768    302.0
Name: new_cases, dtype: float64
67762 67769    294.0
Name: new_cases, dtype: float64
67763 67770    200.0
Name: new_cases, dtype: float64
67764 67771    295.0
Name: new_cases, dtype: float64
67765 67772    325.0
Name: new_cases, dtype: float64
67766 67773    212.0
Name: new_cases, dtype: float64
67767 67774    402.0
Name: new_cases, dtype: float64
67768 67775    424.0
Name: new_cases, dtype: float64
67769 67776    331.0
Name: new_cases, dtype: float64
67770 67777    390.0
Name: new_cases, dtype: float64
67771 67778    370.0
Name: new_cases, dtype: float64
67772 67779    345.0
Name: new_cases, dtype: float64
67773 67780    365.0
Name: new_cases, dtype: float64
67774 67781    500.0
Name: new_cases, dtype: float64
67775 67782    1515.0
Name: new_cases, dtype: float64
67776 67783    839.0
Name: new_cases, dtype: float64
67777 67784    727.0
Name: new_cases, dtype: float64
67778 67785    992.0
Name: new_cases, dtype: float64
67779 67786    832.0
Name: new_cases, dtype: float64
67780 67787    1068.0
Name: new_cases, dtype: float64
67781 67788    724.0
Name: new_cases, dtype: float64
67782 67789    709.0
Name: new_cases, dtype: float64
67783 67790    778.0
Name: new_cases, dtype: float64
67784 67791    493.0
Name: new_cases, dtype: float64
67785 67792    401.0
Name: new_cases, dtype: float64
67786 67793    388.0
Name: new_cases, dtype: float64
67787 67794    631.0
Name: new_cases, dtype: float64
67788 67795    936.0
Name: new_cases, dtype: float64
67789 67796    577.0
Name: new_cases, dtype: float64
67790 67797    377.0
Name: new_cases, dtype: float64
67791 67798    701.0
Name: new_cases, dtype: float64
67792 67799    386.0
Name: new_cases, dtype: float64
67793 67800    229.0
Name: new_cases, dtype: float64
67794 67801    376.0
Name: new_cases, dtype: float64
67795 67802    359.0
Name: new_cases, dtype: float64
67796 67803    221.0
Name: new_cases, dtype: float64
67797 67804    343.0
Name: new_cases, dtype: float64
67798 67805    330.0
Name: new_cases, dtype: float64
67799 67806    266.0
Name: new_cases, dtype: float64
67800 67807    211.0
Name: new_cases, dtype: float64
67801 67808    265.0
Name: new_cases, dtype: float64
67802 67809    137.0
Name: new_cases, dtype: float64
67803 67810    156.0
Name: new_cases, dtype: float64
67804 67811    219.0
Name: new_cases, dtype: float64
67805 67812    236.0
Name: new_cases, dtype: float64
67806 67813    139.0
Name: new_cases, dtype: float64
67807 67814    107.0
Name: new_cases, dtype: float64

67808 67815    159.0
Name: new_cases, dtype: float64
67809 67816    426.0
Name: new_cases, dtype: float64
67810 67817    129.0
Name: new_cases, dtype: float64
67811 67818    92.0
Name: new_cases, dtype: float64
67812 67819    64.0
Name: new_cases, dtype: float64
67813 67820    88.0
Name: new_cases, dtype: float64
67814 67821    51.0
Name: new_cases, dtype: float64
67815 67822    64.0
Name: new_cases, dtype: float64
67816 67823    76.0
Name: new_cases, dtype: float64
67817 67824    115.0
Name: new_cases, dtype: float64
67818 67825    76.0
Name: new_cases, dtype: float64
67819 67826    57.0
Name: new_cases, dtype: float64
67820 67827    59.0
Name: new_cases, dtype: float64
67821 67828    37.0
Name: new_cases, dtype: float64
67822 67829    68.0
Name: new_cases, dtype: float64
67823 67830    38.0
Name: new_cases, dtype: float64
67824 67831    35.0
Name: new_cases, dtype: float64
67825 67832    53.0
Name: new_cases, dtype: float64
67826 67833    61.0
Name: new_cases, dtype: float64
67827 67834    72.0
Name: new_cases, dtype: float64
67828 67835    4.0
Name: new_cases, dtype: float64
67829 67836    45.0
Name: new_cases, dtype: float64
67830 67837    31.0
Name: new_cases, dtype: float64
67831 67838    21.0
Name: new_cases, dtype: float64
67832 67839    20.0
Name: new_cases, dtype: float64
67833 67840    18.0
Name: new_cases, dtype: float64
67834 67841    6.0
Name: new_cases, dtype: float64
67835 67842    8.0
Name: new_cases, dtype: float64
67836 67843    16.0
Name: new_cases, dtype: float64
67837 67844    7.0
Name: new_cases, dtype: float64
67838 67845    12.0
Name: new_cases, dtype: float64
67839 67846    45.0
Name: new_cases, dtype: float64
67840 67847    8.0
Name: new_cases, dtype: float64
67841 67848    18.0
Name: new_cases, dtype: float64
67842 67849    13.0
Name: new_cases, dtype: float64
67843 67850    7.0
Name: new_cases, dtype: float64
67844 67851    14.0
Name: new_cases, dtype: float64
67845 67852    13.0
Name: new_cases, dtype: float64
67846 67853    6.0
Name: new_cases, dtype: float64
67847 67854    5.0
Name: new_cases, dtype: float64
67848 67855    4.0
Name: new_cases, dtype: float64
67849 67856    8.0
Name: new_cases, dtype: float64
67850 67857    5.0
Name: new_cases, dtype: float64
67851 67858    9.0
Name: new_cases, dtype: float64
67852 67859    9.0
Name: new_cases, dtype: float64
67853 67860    23.0
Name: new_cases, dtype: float64
67854 67861    2.0
Name: new_cases, dtype: float64
67855 67862    23.0
Name: new_cases, dtype: float64
67856 67863    11.0
Name: new_cases, dtype: float64
67857 67864    4.0
Name: new_cases, dtype: float64
67858 67865    12.0
Name: new_cases, dtype: float64
67859 67866    9.0
Name: new_cases, dtype: float64
67860 67867    11.0
Name: new_cases, dtype: float64
67861 67868    18.0
Name: new_cases, dtype: float64
67862 67869    4.0
Name: new_cases, dtype: float64
67863 67870    7.0
Name: new_cases, dtype: float64
67864 67871    4.0
Name: new_cases, dtype: float64
67865 67872    23.0
Name: new_cases, dtype: float64
67866 67873    24.0
Name: new_cases, dtype: float64
67867 67874    22.0
Name: new_cases, dtype: float64
67868 67875    17.0
Name: new_cases, dtype: float64
67869 67876    10.0
Name: new_cases, dtype: float64
67870 67877    32.0
Name: new_cases, dtype: float64
67871 67878    13.0
Name: new_cases, dtype: float64
67872 67879    15.0
Name: new_cases, dtype: float64
67873 67880    32.0
Name: new_cases, dtype: float64
67874 67881    20.0
Name: new_cases, dtype: float64
67875 67882    10.0
Name: new_cases, dtype: float64
67876 67883    6.0
Name: new_cases, dtype: float64
67877 67884    36.0
Name: new_cases, dtype: float64
67878 67885    17.0
Name: new_cases, dtype: float64
67879 67886    7.0
Name: new_cases, dtype: float64
67880 67887    19.0
Name: new_cases, dtype: float64
67881 67888    24.0
Name: new_cases, dtype: float64
67882 67889    12.0
Name: new_cases, dtype: float64
67883 67890    11.0
Name: new_cases, dtype: float64
67884 67891    37.0
Name: new_cases, dtype: float64
67885 67892    13.0
Name: new_cases, dtype: float64
67886 67893    85.0
Name: new_cases, dtype: float64
67887 67894    38.0
Name: new_cases, dtype: float64
67888 67895    44.0
Name: new_cases, dtype: float64
67889 67896    53.0
Name: new_cases, dtype: float64
67890 67897    46.0
Name: new_cases, dtype: float64
67891 67898    45.0
Name: new_cases, dtype: float64
67892 67899    50.0
Name: new_cases, dtype: float64
67893 67900    69.0
Name: new_cases, dtype: float64
67894 67901    98.0
Name: new_cases, dtype: float64
67895 67902    174.0
Name: new_cases, dtype: float64
67896 67903    68.0
Name: new_cases, dtype: float64
67897 67904    56.0
Name: new_cases, dtype: float64
67898 67905    33.0
Name: new_cases, dtype: float64
67899 67906    37.0
Name: new_cases, dtype: float64
67900 67907    91.0
Name: new_cases, dtype: float64
67901 67908    66.0
Name: new_cases, dtype: float64
67902 67909    196.0
Name: new_cases, dtype: float64
67903 67910    66.0
Name: new_cases, dtype: float64
67904 67911    56.0
Name: new_cases, dtype: float64
67905 67912    186.0
Name: new_cases, dtype: float64
67906 67913    48.0
Name: new_cases, dtype: float64
67907 67914    129.0
Name: new_cases, dtype: float64
67908 67915    79.0
Name: new_cases, dtype: float64
67909 67916    153.0
Name: new_cases, dtype: float64
67910 67917    61.0
Name: new_cases, dtype: float64
67911 67918    147.0
Name: new_cases, dtype: float64
67912 67919    85.0
Name: new_cases, dtype: float64
67913 67920    162.0
Name: new_cases, dtype: float64
67914 67921    90.0
Name: new_cases, dtype: float64
67915 67922    125.0
Name: new_cases, dtype: float64
67916 67923    142.0
Name: new_cases, dtype: float64
67917 67924    40.0
Name: new_cases, dtype: float64
67918 67925    51.0
Name: new_cases, dtype: float64
67919 67926    214.0
Name: new_cases, dtype: float64
67920 67927    89.0
Name: new_cases, dtype: float64
67921 67928    92.0
Name: new_cases, dtype: float64
67922 67929    97.0
Name: new_cases, dtype: float64
67923 67930    231.0
Name: new_cases, dtype: float64
67924 67931    138.0
Name: new_cases, dtype: float64
67925 67932    102.0
Name: new_cases, dtype: float64
67926 67933    306.0
Name: new_cases, dtype: float64
67927 67934    84.0
Name: new_cases, dtype: float64
67928 67935    196.0
Name: new_cases, dtype: float64
67929 67936    211.0
Name: new_cases, dtype: float64
67930 67937    159.0
Name: new_cases, dtype: float64
67931 67938    255.0
Name: new_cases, dtype: float64
67932 67939    207.0
Name: new_cases, dtype: float64
67933 67940    357.0
Name: new_cases, dtype: float64
67934 67941    250.0
Name: new_cases, dtype: float64
67935 67942    224.0
Name: new_cases, dtype: float64
67936 67943    248.0
Name: new_cases, dtype: float64
67937 67944    267.0
Name: new_cases, dtype: float64
67938 67945    395.0
Name: new_cases, dtype: float64
67939 67946    188.0
Name: new_cases, dtype: float64
67940 67947    323.0
Name: new_cases, dtype: float64
67941 67948    231.0
Name: new_cases, dtype: float64
67942 67949    319.0
Name: new_cases, dtype: float64
67943 67950    321.0
Name: new_cases, dtype: float64
67944 67951    245.0
Name: new_cases, dtype: float64
67945 67952    430.0
Name: new_cases, dtype: float64
67946 67953    387.0
Name: new_cases, dtype: float64
67947 67954    363.0
Name: new_cases, dtype: float64
67948 67955    415.0
Name: new_cases, dtype: float64
67949 67956    442.0
Name: new_cases, dtype: float64
67950 67957    466.0
Name: new_cases, dtype: float64
67951 67958    605.0
Name: new_cases, dtype: float64
67952 67959    364.0
Name: new_cases, dtype: float64
67953 67960    517.0
Name: new_cases, dtype: float64
67954 67961    424.0
Name: new_cases, dtype: float64
67955 67962    611.0
Name: new_cases, dtype: float64
67956 67963    502.0
Name: new_cases, dtype: float64
67957 67964    617.0
Name: new_cases, dtype: float64
67958 67965    1011.0
Name: new_cases, dtype: float64
67959 67966    814.0
Name: new_cases, dtype: float64
67960 67967    823.0
Name: new_cases, dtype: float64
67961 67968    808.0
Name: new_cases, dtype: float64
67962 67969    1084.0
Name: new_cases, dtype: float64
67963 67970    1186.0
Name: new_cases, dtype: float64
67964 67971    998.0
Name: new_cases, dtype: float64
67965 67972    1251.0
Name: new_cases, dtype: float64
67966 67973    1284.0
Name: new_cases, dtype: float64
67967 67974    1031.0
Name: new_cases, dtype: float64
67968 67975    1263.0
Name: new_cases, dtype: float64
67969 67976    1166.0
Name: new_cases, dtype: float64
67970 67977    1054.0
Name: new_cases, dtype: float64

67971 67978    785.0
Name: new_cases, dtype: float64
67972 67979    847.0
Name: new_cases, dtype: float64
67973 67980    1020.0
Name: new_cases, dtype: float64
67974 67981    939.0
Name: new_cases, dtype: float64
67975 67982    700.0
Name: new_cases, dtype: float64
67976 67983    667.0
Name: new_cases, dtype: float64
67977 67984    863.0
Name: new_cases, dtype: float64
67978 67985    762.0
Name: new_cases, dtype: float64
67979 67986    397.0
Name: new_cases, dtype: float64
67980 67987    546.0
Name: new_cases, dtype: float64
67981 67988    748.0
Name: new_cases, dtype: float64
67982 67989    298.0
Name: new_cases, dtype: float64
67983 67990    435.0
Name: new_cases, dtype: float64
67984 67991    563.0
Name: new_cases, dtype: float64
67985 67992    492.0
Name: new_cases, dtype: float64
67986 67993    317.0
Name: new_cases, dtype: float64
67987 67994    539.0
Name: new_cases, dtype: float64
67988 67995    265.0
Name: new_cases, dtype: float64
67989 67996    230.0
Name: new_cases, dtype: float64
67990 67997    358.0
Name: new_cases, dtype: float64
67991 67998    385.0
Name: new_cases, dtype: float64
67992 67999    467.0
Name: new_cases, dtype: float64
67993 68000    427.0
Name: new_cases, dtype: float64
67994 68001    377.0
Name: new_cases, dtype: float64
67995 68002    453.0
Name: new_cases, dtype: float64
67996 68003    330.0
Name: new_cases, dtype: float64
67997 68004    372.0
Name: new_cases, dtype: float64
67998 68005    415.0
Name: new_cases, dtype: float64
67999 68006    329.0
Name: new_cases, dtype: float64
68000 68007    341.0
Name: new_cases, dtype: float64
68001 68008    318.0
Name: new_cases, dtype: float64
68002 68009    250.0
Name: new_cases, dtype: float64
68003 68010    219.0
Name: new_cases, dtype: float64
68004 68011    257.0
Name: new_cases, dtype: float64
68005 68012    307.0
Name: new_cases, dtype: float64
68006 68013    205.0
Name: new_cases, dtype: float64
68007 68014    243.0
Name: new_cases, dtype: float64
68008 68015    299.0
Name: new_cases, dtype: float64
68009 68016    303.0
Name: new_cases, dtype: float64
68010 68017    254.0
Name: new_cases, dtype: float64
68011 68018    268.0
Name: new_cases, dtype: float64
68012 68019    162.0
Name: new_cases, dtype: float64
68013 68020    263.0
Name: new_cases, dtype: float64
68014 68021    457.0
Name: new_cases, dtype: float64
68015 68022    298.0
Name: new_cases, dtype: float64
68016 68023    222.0
Name: new_cases, dtype: float64
68017 68024    214.0
Name: new_cases, dtype: float64
68018 68025    218.0
Name: new_cases, dtype: float64
68019 68026    303.0
Name: new_cases, dtype: float64
68020 68027    304.0
Name: new_cases, dtype: float64
68021 68028    249.0
Name: new_cases, dtype: float64
68022 68029    429.0
Name: new_cases, dtype: float64
68023 68030    264.0
Name: new_cases, dtype: float64
68024 68031    327.0
Name: new_cases, dtype: float64
68025 68032    421.0
Name: new_cases, dtype: float64
68026 68033    481.0
Name: new_cases, dtype: float64
68027 68034    576.0
Name: new_cases, dtype: float64
68028 68035    522.0
Name: new_cases, dtype: float64
68029 68036    766.0
Name: new_cases, dtype: float64
68030 68037    725.0
Name: new_cases, dtype: float64
68031 68038    961.0
Name: new_cases, dtype: float64
68032 68039    927.0
Name: new_cases, dtype: float64
68033 68040    918.0
Name: new_cases, dtype: float64
68034 68041    1025.0
Name: new_cases, dtype: float64
68035 68042    1296.0
Name: new_cases, dtype: float64
68036 68043    735.0
Name: new_cases, dtype: float64
68037 68044    765.0
Name: new_cases, dtype: float64
68038 68045    1545.0
Name: new_cases, dtype: float64
68039 68046    1718.0
Name: new_cases, dtype: float64
68040 68047    1622.0
Name: new_cases, dtype: float64
68041 68048    1753.0
Name: new_cases, dtype: float64
68042 68049    3394.0
Name: new_cases, dtype: float64
68043 68050    4961.0
Name: new_cases, dtype: float64
68044 68051    6110.0
Name: new_cases, dtype: float64
68045 68052    5325.0
Name: new_cases, dtype: float64
68046 68053    7832.0
Name: new_cases, dtype: float64
68047 68054    6503.0
Name: new_cases, dtype: float64
68048 68055    8227.0
Name: new_cases, dtype: float64
68049 68056    4843.0
Name: new_cases, dtype: float64
68050 68057    6886.0
Name: new_cases, dtype: float64
68051 68058    4926.0
Name: new_cases, dtype: float64
68052 68059    3052.0
Name: new_cases, dtype: float64
68053 68060    3553.0
Name: new_cases, dtype: float64
68054 68061    3913.0
Name: new_cases, dtype: float64
68055 68062    3491.0
Name: new_cases, dtype: float64
68056 68063    3232.0
Name: new_cases, dtype: float64
68057 68064    2946.0
Name: new_cases, dtype: float64
68058 68065    2117.0
Name: new_cases, dtype: float64
68059 68066    1996.0
Name: new_cases, dtype: float64
68060 68067    2485.0
Name: new_cases, dtype: float64
68061 68068    2598.0
Name: new_cases, dtype: float64
68062 68069    2357.0
Name: new_cases, dtype: float64
68063 68070    1905.0
Name: new_cases, dtype: float64
68064 68071    1370.0
Name: new_cases, dtype: float64
68065 68072    1369.0
Name: new_cases, dtype: float64
68066 68073    928.0
Name: new_cases, dtype: float64
68067 68074    1331.0
Name: new_cases, dtype: float64
68068 68075    1463.0
Name: new_cases, dtype: float64
68069 68076    1247.0
Name: new_cases, dtype: float64
68070 68077    1411.0
Name: new_cases, dtype: float64
68071 68078    1244.0
Name: new_cases, dtype: float64
68072 68079    1006.0
Name: new_cases, dtype: float64
68073 68080    871.0
Name: new_cases, dtype: float64
68074 68081    1006.0
Name: new_cases, dtype: float64
68075 68082    1314.0
Name: new_cases, dtype: float64
68076 68083    1019.0
Name: new_cases, dtype: float64
68077 68084    785.0
Name: new_cases, dtype: float64
68078 68085    1020.0
Name: new_cases, dtype: float64
68079 68086    829.0
Name: new_cases, dtype: float64
68080 68087    543.0
Name: new_cases, dtype: float64
68081 68088    999.0
Name: new_cases, dtype: float64
68082 68089    862.0
Name: new_cases, dtype: float64
68083 68090    919.0
Name: new_cases, dtype: float64
68084 68091    1076.0
Name: new_cases, dtype: float64
68085 68092    786.0
Name: new_cases, dtype: float64
68086 68093    820.0
Name: new_cases, dtype: float64
68087 68094    711.0
Name: new_cases, dtype: float64
68088 68095    638.0
Name: new_cases, dtype: float64
68089 68096    896.0
Name: new_cases, dtype: float64
68090 68097    753.0
Name: new_cases, dtype: float64
68091 68098    978.0
Name: new_cases, dtype: float64
68092 68099    679.0
Name: new_cases, dtype: float64
68093 68100    686.0
Name: new_cases, dtype: float64
68094 68101    557.0
Name: new_cases, dtype: float64
68095 68102    540.0
Name: new_cases, dtype: float64
68096 68103    638.0
Name: new_cases, dtype: float64
68097 68104    773.0
Name: new_cases, dtype: float64
68098 68105    729.0
Name: new_cases, dtype: float64
68099 68106    612.0
Name: new_cases, dtype: float64
68100 68107    681.0
Name: new_cases, dtype: float64
68101 68108    357.0
Name: new_cases, dtype: float64
68102 68109    559.0
Name: new_cases, dtype: float64
68103 68110    460.0
Name: new_cases, dtype: float64
68104 68111    520.0
Name: new_cases, dtype: float64
68105 68112    530.0
Name: new_cases, dtype: float64
68106 68113    520.0
Name: new_cases, dtype: float64
68107 68114    432.0
Name: new_cases, dtype: float64
68108 68115    306.0
Name: new_cases, dtype: float64
68109 68116    631.0
Name: new_cases, dtype: float64
68110 68117    591.0
Name: new_cases, dtype: float64
68111 68118    641.0
Name: new_cases, dtype: float64
68112 68119    538.0
Name: new_cases, dtype: float64
68113 68120    383.0
Name: new_cases, dtype: float64
68114 68121    575.0
Name: new_cases, dtype: float64
68115 68122    347.0
Name: new_cases, dtype: float64
68116 68123    552.0
Name: new_cases, dtype: float64
68117 68124    581.0
Name: new_cases, dtype: float64
68118 68125    510.0
Name: new_cases, dtype: float64
68119 68126    525.0
Name: new_cases, dtype: float64
68120 68127    768.0
Name: new_cases, dtype: float64
68121 68128    520.0
Name: new_cases, dtype: float64
68122 68129    365.0
Name: new_cases, dtype: float64
68123 68130    680.0
Name: new_cases, dtype: float64
68124 68131    594.0
Name: new_cases, dtype: float64
68125 68132    569.0
Name: new_cases, dtype: float64
68126 68133    610.0
Name: new_cases, dtype: float64
68127 68134    604.0
Name: new_cases, dtype: float64
68128 68135    537.0
Name: new_cases, dtype: float64
68129 68136    366.0
Name: new_cases, dtype: float64

68130 68137    410.0
Name: new_cases, dtype: float64
68131 68138    746.0
Name: new_cases, dtype: float64
68132 68139    587.0
Name: new_cases, dtype: float64
68133 68140    508.0
Name: new_cases, dtype: float64
68134 68141    453.0
Name: new_cases, dtype: float64
68135 68142    318.0
Name: new_cases, dtype: float64
68136 68143    441.0
Name: new_cases, dtype: float64
68137 68144    418.0
Name: new_cases, dtype: float64
68138 68145    398.0
Name: new_cases, dtype: float64
68139 68146    469.0
Name: new_cases, dtype: float64
68140 68147    451.0
Name: new_cases, dtype: float64
68141 68148    302.0
Name: new_cases, dtype: float64
68142 68149    385.0
Name: new_cases, dtype: float64
68143 68150    354.0
Name: new_cases, dtype: float64
68144 68151    421.0
Name: new_cases, dtype: float64
68145 68152    297.0
Name: new_cases, dtype: float64
68146 68153    417.0
Name: new_cases, dtype: float64
68147 68154    419.0
Name: new_cases, dtype: float64
68148 68155    270.0
Name: new_cases, dtype: float64
68149 68156    403.0
Name: new_cases, dtype: float64
68150 68157    386.0
Name: new_cases, dtype: float64
68151 68158    398.0
Name: new_cases, dtype: float64
68152 68159    615.0
Name: new_cases, dtype: float64
68153 68160    433.0
Name: new_cases, dtype: float64
68154 68161    461.0
Name: new_cases, dtype: float64
68155 68162    429.0
Name: new_cases, dtype: float64
68156 68163    436.0
Name: new_cases, dtype: float64
68157 68164    420.0
Name: new_cases, dtype: float64
68158 68165    368.0
Name: new_cases, dtype: float64
68159 68166    469.0
Name: new_cases, dtype: float64
68160 68167    544.0
Name: new_cases, dtype: float64
68161 68168    567.0
Name: new_cases, dtype: float64
68162 68169    401.0
Name: new_cases, dtype: float64
68163 68170    452.0
Name: new_cases, dtype: float64
68164 68171    382.0
Name: new_cases, dtype: float64
68165 68172    415.0
Name: new_cases, dtype: float64
68166 68173    387.0
Name: new_cases, dtype: float64
68167 68174    430.0
Name: new_cases, dtype: float64
68168 68175    399.0
Name: new_cases, dtype: float64
68169 68176    506.0
Name: new_cases, dtype: float64
68170 68177    380.0
Name: new_cases, dtype: float64
68171 68178    378.0
Name: new_cases, dtype: float64
68172 68179    446.0
Name: new_cases, dtype: float64
68173 68180    437.0
Name: new_cases, dtype: float64
68174 68181    420.0
Name: new_cases, dtype: float64
68175 68182    461.0
Name: new_cases, dtype: float64
68176 68183    375.0
Name: new_cases, dtype: float64
68177 68184    379.0
Name: new_cases, dtype: float64
68178 68185    365.0
Name: new_cases, dtype: float64
68179 68186    526.0
Name: new_cases, dtype: float64
68180 68187    470.0
Name: new_cases, dtype: float64
68181 68188    533.0
Name: new_cases, dtype: float64
68182 68189    384.0
Name: new_cases, dtype: float64
68183 68190    447.0
Name: new_cases, dtype: float64
68184 68191    349.0
Name: new_cases, dtype: float64
68185 68192    353.0
Name: new_cases, dtype: float64
68186 68193    445.0
Name: new_cases, dtype: float64
68187 68194    432.0
Name: new_cases, dtype: float64
68188 68195    461.0
Name: new_cases, dtype: float64
68189 68196    456.0
Name: new_cases, dtype: float64
68190 68197    367.0
Name: new_cases, dtype: float64
68191 68198    370.0
Name: new_cases, dtype: float64
68192 68199    337.0
Name: new_cases, dtype: float64
68193 68200    407.0
Name: new_cases, dtype: float64
68194 68201    465.0
Name: new_cases, dtype: float64
68195 68202    517.0
Name: new_cases, dtype: float64
68196 68203    416.0
Name: new_cases, dtype: float64
68197 68204    313.0
Name: new_cases, dtype: float64
68198 68205    377.0
Name: new_cases, dtype: float64
68199 68206    239.0
Name: new_cases, dtype: float64
68200 68207    227.0
Name: new_cases, dtype: float64
68201 68208    398.0
Name: new_cases, dtype: float64
68202 68209    319.0
Name: new_cases, dtype: float64
68203 68210    431.0
Name: new_cases, dtype: float64
68204 68211    315.0
Name: new_cases, dtype: float64
68205 68212    202.0
Name: new_cases, dtype: float64
68206 68213    283.0
Name: new_cases, dtype: float64
68207 68214    287.0
Name: new_cases, dtype: float64
68208 68215    373.0
Name: new_cases, dtype: float64
68209 68216    302.0
Name: new_cases, dtype: float64
68210 68217    393.0
Name: new_cases, dtype: float64
68211 68218    393.0
Name: new_cases, dtype: float64
68212 68219    284.0
Name: new_cases, dtype: float64
68213 68220    174.0
Name: new_cases, dtype: float64
68214 68221    298.0
Name: new_cases, dtype: float64
68215 68222    304.0
Name: new_cases, dtype: float64
68216 68223    380.0
Name: new_cases, dtype: float64
68217 68224    443.0
Name: new_cases, dtype: float64
68218 68225    340.0
Name: new_cases, dtype: float64
68219 68226    329.0
Name: new_cases, dtype: float64
68220 68227    342.0
Name: new_cases, dtype: float64
68221 68228   -23.0
Name: new_cases, dtype: float64
68222 68229    876.0
Name: new_cases, dtype: float64
68223 68230    512.0
Name: new_cases, dtype: float64
68224 68231    448.0
Name: new_cases, dtype: float64
68225 68232    562.0
Name: new_cases, dtype: float64
68226 68233    335.0
Name: new_cases, dtype: float64
68227 68234    397.0
Name: new_cases, dtype: float64
68228 68235    533.0
Name: new_cases, dtype: float64
68229 68236    533.0
Name: new_cases, dtype: float64
68230 68237    631.0
Name: new_cases, dtype: float64
68231 68238    581.0
Name: new_cases, dtype: float64
68232 68239    576.0
Name: new_cases, dtype: float64
68233 68240    572.0
Name: new_cases, dtype: float64
68234 68241    589.0
Name: new_cases, dtype: float64
68235 68242    737.0
Name: new_cases, dtype: float64
68236 68243    994.0
Name: new_cases, dtype: float64
68237 68244    1170.0
Name: new_cases, dtype: float64
68238 68245    1377.0
Name: new_cases, dtype: float64
68239 68246    1179.0
Name: new_cases, dtype: float64
68240 68247    1071.0
Name: new_cases, dtype: float64
68241 68248    1110.0
Name: new_cases, dtype: float64
68242 68249    1260.0
Name: new_cases, dtype: float64
68243 68250    1188.0
Name: new_cases, dtype: float64
68244 68251    1386.0
Name: new_cases, dtype: float64
68245 68252    1345.0
Name: new_cases, dtype: float64
68246 68253    1126.0
Name: new_cases, dtype: float64
68247 68254    1276.0
Name: new_cases, dtype: float64
68248 68255    1114.0
Name: new_cases, dtype: float64
68249 68256    1301.0
Name: new_cases, dtype: float64
68250 68257    1361.0
Name: new_cases, dtype: float64
68251 68258    1501.0
Name: new_cases, dtype: float64
68252 68259    1427.0
Name: new_cases, dtype: float64
68253 68260    1098.0
Name: new_cases, dtype: float64
68254 68261    1352.0
Name: new_cases, dtype: float64
68255 68262    884.0
Name: new_cases, dtype: float64
68256 68263    1217.0
Name: new_cases, dtype: float64
68257 68264    1492.0
Name: new_cases, dtype: float64
68258 68265    1781.0
Name: new_cases, dtype: float64
68259 68266    1828.0
Name: new_cases, dtype: float64
68260 68267    1837.0
Name: new_cases, dtype: float64
68261 68268    1411.0
Name: new_cases, dtype: float64
68262 68269    1509.0
Name: new_cases, dtype: float64
68263 68270    1819.0
Name: new_cases, dtype: float64
68264 68271    1733.0
Name: new_cases, dtype: float64
68265 68272    1978.0
Name: new_cases, dtype: float64
68266 68273    2074.0
Name: new_cases, dtype: float64
68267 68274    1758.0
Name: new_cases, dtype: float64
68268 68275    1441.0
Name: new_cases, dtype: float64
68269 68276    1496.0
Name: new_cases, dtype: float64
68270 68277    1704.0
Name: new_cases, dtype: float64
68271 68278    1818.0
Name: new_cases, dtype: float64
68272 68279    2098.0
Name: new_cases, dtype: float64
68273 68280    2125.0
Name: new_cases, dtype: float64
68274 68281    1688.0
Name: new_cases, dtype: float64
68275 68282    1590.0
Name: new_cases, dtype: float64
68276 68283    1571.0
Name: new_cases, dtype: float64
68277 68284    2051.0
Name: new_cases, dtype: float64
68278 68285    1866.0
Name: new_cases, dtype: float64
68279 68286    1875.0
Name: new_cases, dtype: float64
68280 68287    1997.0
Name: new_cases, dtype: float64
68281 68288    1706.0
Name: new_cases, dtype: float64
68282 68289    1292.0
Name: new_cases, dtype: float64
68283 68290    1382.0
Name: new_cases, dtype: float64
68284 68291    1789.0
Name: new_cases, dtype: float64
68285 68292   -1707.0
Name: new_cases, dtype: float64
68286 68293    1407.0
Name: new_cases, dtype: float64
68287 68294    1703.0
Name: new_cases, dtype: float64
68288 68295    1180.0
Name: new_cases, dtype: float64
68289 68296    1136.0
Name: new_cases, dtype: float64
68290 68297    1465.0
Name: new_cases, dtype: float64
68291 68298    1537.0
Name: new_cases, dtype: float64
68292 68299    1271.0
Name: new_cases, dtype: float64
68293 68300    1619.0
Name: new_cases, dtype: float64
68294 68301    1466.0
Name: new_cases, dtype: float64
68295 68302    1346.0
Name: new_cases, dtype: float64
68296 68303    877.0
Name: new_cases, dtype: float64
68297 68304    1176.0
Name: new_cases, dtype: float64
68298 68305   -1176.0
Name: new_cases, dtype: float64
68299 68306    3765.0
Name: new_cases, dtype: float64
68300 68307    1386.0
Name: new_cases, dtype: float64
68301 68308    1456.0
Name: new_cases, dtype: float64
68302 68309    1224.0
Name: new_cases, dtype: float64

68303 68310    1150.0
Name: new_cases, dtype: float64
68304 68311    1420.0
Name: new_cases, dtype: float64
68305 68312    1429.0
Name: new_cases, dtype: float64
68306 68313    1354.0
Name: new_cases, dtype: float64
68307 68314    1163.0
Name: new_cases, dtype: float64
68308 68315    1335.0
Name: new_cases, dtype: float64
68309 68316    1459.0
Name: new_cases, dtype: float64
68310 68317    1044.0
Name: new_cases, dtype: float64
68311 68318    1497.0
Name: new_cases, dtype: float64
68312 68319    1447.0
Name: new_cases, dtype: float64
68313 68320    1267.0
Name: new_cases, dtype: float64
68314 68321    1057.0
Name: new_cases, dtype: float64
68315 68322    1586.0
Name: new_cases, dtype: float64
68316 68323    1051.0
Name: new_cases, dtype: float64
68317 68324    893.0
Name: new_cases, dtype: float64
68318 68325    1124.0
Name: new_cases, dtype: float64
68319 68326    982.0
Name: new_cases, dtype: float64
68320 68327    1206.0
Name: new_cases, dtype: float64
68321 68328    2002.0
Name: new_cases, dtype: float64
68322 68329    1940.0
Name: new_cases, dtype: float64
68323 68330    1384.0
Name: new_cases, dtype: float64
68324 68331    1357.0
Name: new_cases, dtype: float64
68325 68332    1456.0
Name: new_cases, dtype: float64
68326 68333    2051.0
Name: new_cases, dtype: float64
68327 68334    1626.0
Name: new_cases, dtype: float64
68328 68335    1907.0
Name: new_cases, dtype: float64
68329 68336    2180.0
Name: new_cases, dtype: float64
68330 68337    1380.0
Name: new_cases, dtype: float64
68331 68338    1576.0
Name: new_cases, dtype: float64
68332 68339    2397.0
Name: new_cases, dtype: float64
68333 68340    2147.0
Name: new_cases, dtype: float64
68334 68341    2026.0
Name: new_cases, dtype: float64
68335 68342    2465.0
Name: new_cases, dtype: float64
68336 68343    2427.0
Name: new_cases, dtype: float64
68337 68344    1725.0
Name: new_cases, dtype: float64
68338 68345    1845.0
Name: new_cases, dtype: float64
68339 68346    2180.0
Name: new_cases, dtype: float64
68340 68347    1624.0
Name: new_cases, dtype: float64
68341 68348    2598.0
Name: new_cases, dtype: float64
68342 68349    2541.0
Name: new_cases, dtype: float64
68343 68350    2966.0
Name: new_cases, dtype: float64
68344 68351    1963.0
Name: new_cases, dtype: float64
68345 68352    2855.0
Name: new_cases, dtype: float64
68346 68353    3723.0
Name: new_cases, dtype: float64
68347 68354    3174.0
Name: new_cases, dtype: float64
68348 68355    3024.0
Name: new_cases, dtype: float64
68349 68356    3903.0
Name: new_cases, dtype: float64
68350 68357    3685.0
Name: new_cases, dtype: float64
68351 68358    3428.0
Name: new_cases, dtype: float64
68352 68359    3161.0
Name: new_cases, dtype: float64
68353 68360    5331.0
Name: new_cases, dtype: float64
68354 68361    2968.0
Name: new_cases, dtype: float64
68355 68362    3677.0
Name: new_cases, dtype: float64
68356 68363    5478.0
Name: new_cases, dtype: float64
68357 68364    4642.0
Name: new_cases, dtype: float64
68358 68365    3805.0
Name: new_cases, dtype: float64
68359 68366    4558.0
Name: new_cases, dtype: float64
68360 68367    4407.0
Name: new_cases, dtype: float64
68361 68368    3632.0
Name: new_cases, dtype: float64
68362 68369    4646.0
Name: new_cases, dtype: float64
68363 68370    3133.0
Name: new_cases, dtype: float64
68364 68371    5959.0
Name: new_cases, dtype: float64
68365 68372    4181.0
Name: new_cases, dtype: float64
68366 68373    5630.0
Name: new_cases, dtype: float64
68367 68374    3661.0
Name: new_cases, dtype: float64
68368 68375    3891.0
Name: new_cases, dtype: float64
68369 68376    4763.0
Name: new_cases, dtype: float64
68370 68377    4619.0
Name: new_cases, dtype: float64
68371 68378    4791.0
Name: new_cases, dtype: float64
68372 68379    3735.0
Name: new_cases, dtype: float64
68373 68380    4603.0
Name: new_cases, dtype: float64
68374 68381    5458.0
Name: new_cases, dtype: float64
68375 68382    3790.0
Name: new_cases, dtype: float64
68376 68383    4159.0
Name: new_cases, dtype: float64
68377 68384    5408.0
Name: new_cases, dtype: float64
68378 68385    5622.0
Name: new_cases, dtype: float64
68379 68386    5156.0
Name: new_cases, dtype: float64
68380 68387    2911.0
Name: new_cases, dtype: float64
68381 68388    5565.0
Name: new_cases, dtype: float64
68382 68389    4126.0
Name: new_cases, dtype: float64
68383 68390    4003.0
Name: new_cases, dtype: float64
68384 68391    4097.0
Name: new_cases, dtype: float64
68385 68392    4004.0
Name: new_cases, dtype: float64
68386 68393    4667.0
Name: new_cases, dtype: float64
68387 68394    4683.0
Name: new_cases, dtype: float64
68388 68395    3871.0
Name: new_cases, dtype: float64
68389 68396    4230.0
Name: new_cases, dtype: float64
68390 68397    4141.0
Name: new_cases, dtype: float64
68391 68398    3595.0
Name: new_cases, dtype: float64
68392 68399    7333.0
Name: new_cases, dtype: float64
68393 68400    5124.0
Name: new_cases, dtype: float64
68394 68401    4788.0
Name: new_cases, dtype: float64
68395 68402    5269.0
Name: new_cases, dtype: float64
68396 68403    6307.0
Name: new_cases, dtype: float64
68397 68404    7411.0
Name: new_cases, dtype: float64
68398 68405    11182.0
Name: new_cases, dtype: float64
68399 68406    13765.0
Name: new_cases, dtype: float64
68400 68407    10404.0
Name: new_cases, dtype: float64
68401 68408    6735.0
Name: new_cases, dtype: float64
68402 68409    9006.0
Name: new_cases, dtype: float64
68403 68410    16428.0
Name: new_cases, dtype: float64
68404 68411    20554.0
Name: new_cases, dtype: float64
68405 68412    20110.0
Name: new_cases, dtype: float64
68406 68413    23281.0
Name: new_cases, dtype: float64
68407 68414    0.0
Name: new_cases, dtype: float64
68408 68415    34057.0
Name: new_cases, dtype: float64
68409 68416    21302.0
Name: new_cases, dtype: float64
68410 68417    17656.0
Name: new_cases, dtype: float64
68411 68418    23817.0
Name: new_cases, dtype: float64
68412 68419    21926.0
Name: new_cases, dtype: float64
68413 68420    26122.0
Name: new_cases, dtype: float64
68414 Series([], Name: new_cases, dtype: float64)
68415 Series([], Name: new_cases, dtype: float64)
68416 Series([], Name: new_cases, dtype: float64)
68417 Series([], Name: new_cases, dtype: float64)
68418 Series([], Name: new_cases, dtype: float64)
68419 Series([], Name: new_cases, dtype: float64)
68420 Series([], Name: new_cases, dtype: float64)
69082 69089    3.0
Name: new_cases, dtype: float64
69083 69090    0.0
Name: new_cases, dtype: float64
69084 69091    1.0
Name: new_cases, dtype: float64
69085 69092    5.0
Name: new_cases, dtype: float64
69086 69093    3.0
Name: new_cases, dtype: float64
69087 69094    0.0
Name: new_cases, dtype: float64
69088 69095    6.0
Name: new_cases, dtype: float64
69089 69096    16.0
Name: new_cases, dtype: float64
69090 69097    10.0
Name: new_cases, dtype: float64
69091 69098    9.0
Name: new_cases, dtype: float64
69092 69099    4.0
Name: new_cases, dtype: float64
69093 69100    28.0
Name: new_cases, dtype: float64
69094 69101   -28.0
Name: new_cases, dtype: float64
69095 69102    21.0
Name: new_cases, dtype: float64
69096 69103    31.0
Name: new_cases, dtype: float64
69097 69104    26.0
Name: new_cases, dtype: float64
69098 69105    39.0
Name: new_cases, dtype: float64
69099 69106    74.0
Name: new_cases, dtype: float64
69100 69107    44.0
Name: new_cases, dtype: float64
69101 69108    76.0
Name: new_cases, dtype: float64
69102 69109    15.0
Name: new_cases, dtype: float64
69103 69110    242.0
Name: new_cases, dtype: float64
69104 69111    215.0
Name: new_cases, dtype: float64
69105 69112    237.0
Name: new_cases, dtype: float64
69106 69113    169.0
Name: new_cases, dtype: float64
69107 69114    102.0
Name: new_cases, dtype: float64
69108 69115    1117.0
Name: new_cases, dtype: float64
69109 69116    520.0
Name: new_cases, dtype: float64
69110 69117    433.0
Name: new_cases, dtype: float64
69111 69118    480.0
Name: new_cases, dtype: float64
69112 69119    532.0
Name: new_cases, dtype: float64
69113 69120    546.0
Name: new_cases, dtype: float64
69114 69121    738.0
Name: new_cases, dtype: float64
69115 69122    696.0
Name: new_cases, dtype: float64
69116 69123    719.0
Name: new_cases, dtype: float64
69117 69124    597.0
Name: new_cases, dtype: float64
69118 69125    428.0
Name: new_cases, dtype: float64
69119 69126    583.0
Name: new_cases, dtype: float64
69120 69127    451.0
Name: new_cases, dtype: float64
69121 69128    377.0
Name: new_cases, dtype: float64
69122 69129    338.0
Name: new_cases, dtype: float64
69123 69130    343.0
Name: new_cases, dtype: float64
69124 69131    358.0
Name: new_cases, dtype: float64

69125 69132    345.0
Name: new_cases, dtype: float64
69126 69133    552.0
Name: new_cases, dtype: float64
69127 69134    438.0
Name: new_cases, dtype: float64
69128 69135    399.0
Name: new_cases, dtype: float64
69129 69136    311.0
Name: new_cases, dtype: float64
69130 69137    296.0
Name: new_cases, dtype: float64
69131 69138    298.0
Name: new_cases, dtype: float64
69132 69139    291.0
Name: new_cases, dtype: float64
69133 69140    276.0
Name: new_cases, dtype: float64
69134 69141    299.0
Name: new_cases, dtype: float64
69135 69142    282.0
Name: new_cases, dtype: float64
69136 69143    225.0
Name: new_cases, dtype: float64
69137 69144    276.0
Name: new_cases, dtype: float64
69138 69145    248.0
Name: new_cases, dtype: float64
69139 69146    159.0
Name: new_cases, dtype: float64
69140 69147    83.0
Name: new_cases, dtype: float64
69141 69148    128.0
Name: new_cases, dtype: float64
69142 69149    159.0
Name: new_cases, dtype: float64
69143 69150    82.0
Name: new_cases, dtype: float64
69144 69151    142.0
Name: new_cases, dtype: float64
69145 69152    116.0
Name: new_cases, dtype: float64
69146 69153    57.0
Name: new_cases, dtype: float64
69147 69154    27.0
Name: new_cases, dtype: float64
69148 69155    53.0
Name: new_cases, dtype: float64
69149 69156    32.0
Name: new_cases, dtype: float64
69150 69157    65.0
Name: new_cases, dtype: float64
69151 69158    61.0
Name: new_cases, dtype: float64
69152 69159    33.0
Name: new_cases, dtype: float64
69153 69160    19.0
Name: new_cases, dtype: float64
69154 69161    29.0
Name: new_cases, dtype: float64
69155 69162    39.0
Name: new_cases, dtype: float64
69156 69163    23.0
Name: new_cases, dtype: float64
69157 69164    39.0
Name: new_cases, dtype: float64
69158 69165    22.0
Name: new_cases, dtype: float64
69159 69166    12.0
Name: new_cases, dtype: float64
69160 69167    5.0
Name: new_cases, dtype: float64
69161 69168    15.0
Name: new_cases, dtype: float64
69162 69169    27.0
Name: new_cases, dtype: float64
69163 69170    22.0
Name: new_cases, dtype: float64
69164 69171    15.0
Name: new_cases, dtype: float64
69165 69172    17.0
Name: new_cases, dtype: float64
69166 69173    19.0
Name: new_cases, dtype: float64
69167 69174    5.0
Name: new_cases, dtype: float64
69168 69175    13.0
Name: new_cases, dtype: float64
69169 69176    22.0
Name: new_cases, dtype: float64
69170 69177    50.0
Name: new_cases, dtype: float64
69171 69178    40.0
Name: new_cases, dtype: float64
69172 69179    77.0
Name: new_cases, dtype: float64
69173 69180    113.0
Name: new_cases, dtype: float64
69174 69181    29.0
Name: new_cases, dtype: float64
69175 69182    87.0
Name: new_cases, dtype: float64
69176 69183    100.0
Name: new_cases, dtype: float64
69177 69184    121.0
Name: new_cases, dtype: float64
69178 69185    97.0
Name: new_cases, dtype: float64
69179 69186    142.0
Name: new_cases, dtype: float64
69180 69187    127.0
Name: new_cases, dtype: float64
69181 69188    78.0
Name: new_cases, dtype: float64
69182 69189    140.0
Name: new_cases, dtype: float64
69183 69190    179.0
Name: new_cases, dtype: float64
69184 69191    173.0
Name: new_cases, dtype: float64
69185 69192    240.0
Name: new_cases, dtype: float64
69186 69193    191.0
Name: new_cases, dtype: float64
69187 69194    184.0
Name: new_cases, dtype: float64
69188 69195    149.0
Name: new_cases, dtype: float64
69189 69196    136.0
Name: new_cases, dtype: float64
69190 69197    198.0
Name: new_cases, dtype: float64
69191 69198    300.0
Name: new_cases, dtype: float64
69192 69199    271.0
Name: new_cases, dtype: float64
69193 69200    302.0
Name: new_cases, dtype: float64
69194 69201    310.0
Name: new_cases, dtype: float64
69195 69202    159.0
Name: new_cases, dtype: float64
69196 69203    173.0
Name: new_cases, dtype: float64
69197 69204    345.0
Name: new_cases, dtype: float64
69198 69205    451.0
Name: new_cases, dtype: float64
69199 69206    487.0
Name: new_cases, dtype: float64
69200 69207    516.0
Name: new_cases, dtype: float64
69201 69208    464.0
Name: new_cases, dtype: float64
69202 69209    398.0
Name: new_cases, dtype: float64
69203 69210    385.0
Name: new_cases, dtype: float64
69204 69211    757.0
Name: new_cases, dtype: float64
69205 69212    786.0
Name: new_cases, dtype: float64
69206 69213    972.0
Name: new_cases, dtype: float64
69207 69214    1146.0
Name: new_cases, dtype: float64
69208 69215    939.0
Name: new_cases, dtype: float64
69209 69216    821.0
Name: new_cases, dtype: float64
69210 69217    831.0
Name: new_cases, dtype: float64
69211 69218    1134.0
Name: new_cases, dtype: float64
69212 69219    1390.0
Name: new_cases, dtype: float64
69213 69220    1327.0
Name: new_cases, dtype: float64
69214 69221    1525.0
Name: new_cases, dtype: float64
69215 69222    1409.0
Name: new_cases, dtype: float64
69216 69223    1168.0
Name: new_cases, dtype: float64
69217 69224    1238.0
Name: new_cases, dtype: float64
69218 69225    1720.0
Name: new_cases, dtype: float64
69219 69226    1604.0
Name: new_cases, dtype: float64
69220 69227    1877.0
Name: new_cases, dtype: float64
69221 69228    1939.0
Name: new_cases, dtype: float64
69222 69229    1605.0
Name: new_cases, dtype: float64
69223 69230    1448.0
Name: new_cases, dtype: float64
69224 69231    1016.0
Name: new_cases, dtype: float64
69225 69232    1887.0
Name: new_cases, dtype: float64
69226 69233    2006.0
Name: new_cases, dtype: float64
69227 69234    2044.0
Name: new_cases, dtype: float64
69228 69235    1990.0
Name: new_cases, dtype: float64
69229 69236    1830.0
Name: new_cases, dtype: float64
69230 69237    1112.0
Name: new_cases, dtype: float64
69231 69238    1042.0
Name: new_cases, dtype: float64
69232 69239    2048.0
Name: new_cases, dtype: float64
69233 69240    2125.0
Name: new_cases, dtype: float64
69234 69241    1954.0
Name: new_cases, dtype: float64
69235 69242    1787.0
Name: new_cases, dtype: float64
69236 69243    1362.0
Name: new_cases, dtype: float64
69237 69244    625.0
Name: new_cases, dtype: float64
69238 69245    708.0
Name: new_cases, dtype: float64
69239 69246    1800.0
Name: new_cases, dtype: float64
69240 69247    1729.0
Name: new_cases, dtype: float64
69241 69248    1690.0
Name: new_cases, dtype: float64
69242 69249    1677.0
Name: new_cases, dtype: float64
69243 69250    1764.0
Name: new_cases, dtype: float64
69244 69251    754.0
Name: new_cases, dtype: float64
69245 69252    924.0
Name: new_cases, dtype: float64
69246 69253    1704.0
Name: new_cases, dtype: float64
69247 69254    1823.0
Name: new_cases, dtype: float64
69248 69255    1622.0
Name: new_cases, dtype: float64
69249 69256    1643.0
Name: new_cases, dtype: float64
69250 69257    1388.0
Name: new_cases, dtype: float64
69251 69258    757.0
Name: new_cases, dtype: float64
69252 69259    1068.0
Name: new_cases, dtype: float64
69253 69260    1650.0
Name: new_cases, dtype: float64
69254 69261    1649.0
Name: new_cases, dtype: float64
69255 69262    1640.0
Name: new_cases, dtype: float64
69256 69263    1487.0
Name: new_cases, dtype: float64
69257 69264    1493.0
Name: new_cases, dtype: float64
69258 69265    711.0
Name: new_cases, dtype: float64
69259 69266    965.0
Name: new_cases, dtype: float64
69260 69267    1900.0
Name: new_cases, dtype: float64
69261 69268    1956.0
Name: new_cases, dtype: float64
69262 69269    1953.0
Name: new_cases, dtype: float64
69263 69270    2071.0
Name: new_cases, dtype: float64
69264 69271    1832.0
Name: new_cases, dtype: float64
69265 69272    910.0
Name: new_cases, dtype: float64
69266 69273    1101.0
Name: new_cases, dtype: float64
69267 69274    2178.0
Name: new_cases, dtype: float64
69268 69275    2252.0
Name: new_cases, dtype: float64
69269 69276    3193.0
Name: new_cases, dtype: float64
69270 69277    2661.0
Name: new_cases, dtype: float64
69271 69278    2623.0
Name: new_cases, dtype: float64
69272 69279    1505.0
Name: new_cases, dtype: float64
69273 69280    2177.0
Name: new_cases, dtype: float64
69274 69281    3388.0
Name: new_cases, dtype: float64
69275 69282    3489.0
Name: new_cases, dtype: float64
69276 69283    3996.0
Name: new_cases, dtype: float64
69277 69284    4161.0
Name: new_cases, dtype: float64
69278 69285    3975.0
Name: new_cases, dtype: float64
69279 69286    2719.0
Name: new_cases, dtype: float64
69280 69287    3175.0
Name: new_cases, dtype: float64
69281 69288    4805.0
Name: new_cases, dtype: float64
69282 69289    5539.0
Name: new_cases, dtype: float64
69283 69290    4574.0
Name: new_cases, dtype: float64
69284 69291    5385.0
Name: new_cases, dtype: float64
69285 69292    5340.0
Name: new_cases, dtype: float64
69286 69293    3809.0
Name: new_cases, dtype: float64
69287 69294    2579.0
Name: new_cases, dtype: float64
69288 69295    3866.0
Name: new_cases, dtype: float64
69289 69296    7021.0
Name: new_cases, dtype: float64
69290 69297    7125.0
Name: new_cases, dtype: float64

69291 69298    8234.0
Name: new_cases, dtype: float64
69292 69299    8390.0
Name: new_cases, dtype: float64
69293 69300    5882.0
Name: new_cases, dtype: float64
69294 69301    3414.0
Name: new_cases, dtype: float64
69295 69302    1159.0
Name: new_cases, dtype: float64
69296 69303    4991.0
Name: new_cases, dtype: float64
69297 69304    9078.0
Name: new_cases, dtype: float64
69298 69305    7731.0
Name: new_cases, dtype: float64
69299 69306    7058.0
Name: new_cases, dtype: float64
69300 69307    2593.0
Name: new_cases, dtype: float64
69301 69308    2937.0
Name: new_cases, dtype: float64
69302 69309    5721.0
Name: new_cases, dtype: float64
69303 69310    4724.0
Name: new_cases, dtype: float64
69304 69311    4165.0
Name: new_cases, dtype: float64
69305 69312    3755.0
Name: new_cases, dtype: float64
69306 69313    2963.0
Name: new_cases, dtype: float64
69307 69314    916.0
Name: new_cases, dtype: float64
69308 69315    1646.0
Name: new_cases, dtype: float64
69309 69316    3169.0
Name: new_cases, dtype: float64
69310 69317    2336.0
Name: new_cases, dtype: float64
69311 69318    2117.0
Name: new_cases, dtype: float64
69312 69319    1612.0
Name: new_cases, dtype: float64
69313 69320    1500.0
Name: new_cases, dtype: float64
69314 69321    411.0
Name: new_cases, dtype: float64
69315 69322    922.0
Name: new_cases, dtype: float64
69316 69323    1517.0
Name: new_cases, dtype: float64
69317 69324    1193.0
Name: new_cases, dtype: float64
69318 69325    1172.0
Name: new_cases, dtype: float64
69319 69326    1032.0
Name: new_cases, dtype: float64
69320 69327    849.0
Name: new_cases, dtype: float64
69321 69328    246.0
Name: new_cases, dtype: float64
69322 69329    607.0
Name: new_cases, dtype: float64
69323 69330    884.0
Name: new_cases, dtype: float64
69324 69331    887.0
Name: new_cases, dtype: float64
69325 69332    723.0
Name: new_cases, dtype: float64
69326 69333    644.0
Name: new_cases, dtype: float64
69327 69334    680.0
Name: new_cases, dtype: float64
69328 69335    228.0
Name: new_cases, dtype: float64
69329 69336    658.0
Name: new_cases, dtype: float64
69330 69337    788.0
Name: new_cases, dtype: float64
69331 69338    846.0
Name: new_cases, dtype: float64
69332 69339    769.0
Name: new_cases, dtype: float64
69333 69340    570.0
Name: new_cases, dtype: float64
69334 69341    691.0
Name: new_cases, dtype: float64
69335 69342    212.0
Name: new_cases, dtype: float64
69336 69343    534.0
Name: new_cases, dtype: float64
69337 69344    719.0
Name: new_cases, dtype: float64
69338 69345    675.0
Name: new_cases, dtype: float64
69339 69346    763.0
Name: new_cases, dtype: float64
69340 69347    836.0
Name: new_cases, dtype: float64
69341 69348    761.0
Name: new_cases, dtype: float64
69342 69349    292.0
Name: new_cases, dtype: float64
69343 69350    625.0
Name: new_cases, dtype: float64
69344 69351    873.0
Name: new_cases, dtype: float64
69345 69352    829.0
Name: new_cases, dtype: float64
69346 69353    795.0
Name: new_cases, dtype: float64
69347 69354    770.0
Name: new_cases, dtype: float64
69348 69355    774.0
Name: new_cases, dtype: float64
69349 69356    422.0
Name: new_cases, dtype: float64
69350 69357    765.0
Name: new_cases, dtype: float64
69351 69358    959.0
Name: new_cases, dtype: float64
69352 69359    857.0
Name: new_cases, dtype: float64
69353 69360    1079.0
Name: new_cases, dtype: float64
69354 69361    1085.0
Name: new_cases, dtype: float64
69355 69362    1032.0
Name: new_cases, dtype: float64
69356 69363    580.0
Name: new_cases, dtype: float64
69357 69364    1025.0
Name: new_cases, dtype: float64
69358 69365    1258.0
Name: new_cases, dtype: float64
69359 69366    1198.0
Name: new_cases, dtype: float64
69360 69367    1579.0
Name: new_cases, dtype: float64
69361 69368    1438.0
Name: new_cases, dtype: float64
69362 69369    695.0
Name: new_cases, dtype: float64
69363 69370    1725.0
Name: new_cases, dtype: float64
69364 69371    1080.0
Name: new_cases, dtype: float64
69365 69372    1891.0
Name: new_cases, dtype: float64
69366 69373    1488.0
Name: new_cases, dtype: float64
69367 69374    1986.0
Name: new_cases, dtype: float64
69368 69375    2126.0
Name: new_cases, dtype: float64
69369 69376    872.0
Name: new_cases, dtype: float64
69370 69377    2517.0
Name: new_cases, dtype: float64
69371 69378    1390.0
Name: new_cases, dtype: float64
69372 69379    2330.0
Name: new_cases, dtype: float64
69373 69380    1124.0
Name: new_cases, dtype: float64
69374 69381    4412.0
Name: new_cases, dtype: float64
69375 69382    2933.0
Name: new_cases, dtype: float64
69376 69383    2177.0
Name: new_cases, dtype: float64
69377 69384    2734.0
Name: new_cases, dtype: float64
69378 69385    1874.0
Name: new_cases, dtype: float64
69379 69386    3499.0
Name: new_cases, dtype: float64
69380 69387    4228.0
Name: new_cases, dtype: float64
69381 69388    2535.0
Name: new_cases, dtype: float64
69382 69389    4656.0
Name: new_cases, dtype: float64
69383 69390    4713.0
Name: new_cases, dtype: float64
69384 69391    4273.0
Name: new_cases, dtype: float64
69385 69392    2806.0
Name: new_cases, dtype: float64
69386 69393    5815.0
Name: new_cases, dtype: float64
69387 69394    5113.0
Name: new_cases, dtype: float64
69388 69395    4186.0
Name: new_cases, dtype: float64
69389 69396    6678.0
Name: new_cases, dtype: float64
69390 69397    5248.0
Name: new_cases, dtype: float64
69391 69398    6289.0
Name: new_cases, dtype: float64
69392 69399    6743.0
Name: new_cases, dtype: float64
69393 69400    6631.0
Name: new_cases, dtype: float64
69394 69401    7966.0
Name: new_cases, dtype: float64
69395 69402    7309.0
Name: new_cases, dtype: float64
69396 69403    7600.0
Name: new_cases, dtype: float64
69397 69404    6309.0
Name: new_cases, dtype: float64
69398 69405    8077.0
Name: new_cases, dtype: float64
69399 69406    5885.0
Name: new_cases, dtype: float64
69400 69407    9754.0
Name: new_cases, dtype: float64
69401 69408    8990.0
Name: new_cases, dtype: float64
69402 69409    9997.0
Name: new_cases, dtype: float64
69403 69410    9754.0
Name: new_cases, dtype: float64
69404 69411    5235.0
Name: new_cases, dtype: float64
69405 69412    8450.0
Name: new_cases, dtype: float64
69406 69413    8190.0
Name: new_cases, dtype: float64
69407 69414    6560.0
Name: new_cases, dtype: float64
69408 69415    7380.0
Name: new_cases, dtype: float64
69409 69416    10213.0
Name: new_cases, dtype: float64
69410 69417    7027.0
Name: new_cases, dtype: float64
69411 69418    6159.0
Name: new_cases, dtype: float64
69412 69419    4933.0
Name: new_cases, dtype: float64
69413 69420    3442.0
Name: new_cases, dtype: float64
69414 69421    3666.0
Name: new_cases, dtype: float64
69415 69422    8587.0
Name: new_cases, dtype: float64
69416 69423    11934.0
Name: new_cases, dtype: float64
69417 69424    7305.0
Name: new_cases, dtype: float64
69418 69425    5096.0
Name: new_cases, dtype: float64
69419 69426    4798.0
Name: new_cases, dtype: float64
69420 69427    4646.0
Name: new_cases, dtype: float64
69421 69428    8811.0
Name: new_cases, dtype: float64
69422 69429    7732.0
Name: new_cases, dtype: float64
69423 69430    8896.0
Name: new_cases, dtype: float64
69424 69431    6744.0
Name: new_cases, dtype: float64
69425 69432    5238.0
Name: new_cases, dtype: float64
69426 69433    4727.0
Name: new_cases, dtype: float64
69427 69434    6518.0
Name: new_cases, dtype: float64
69428 69435    4427.0
Name: new_cases, dtype: float64
69429 69436    7191.0
Name: new_cases, dtype: float64
69430 69437    6010.0
Name: new_cases, dtype: float64
69431 69438    5083.0
Name: new_cases, dtype: float64
69432 69439    3934.0
Name: new_cases, dtype: float64
69433 69440    3100.0
Name: new_cases, dtype: float64
69434 69441    2534.0
Name: new_cases, dtype: float64
69435 69442    5913.0
Name: new_cases, dtype: float64
69436 69443    4282.0
Name: new_cases, dtype: float64
69437 69444    4054.0
Name: new_cases, dtype: float64
69438 69445    3305.0
Name: new_cases, dtype: float64
69439 69446    2579.0
Name: new_cases, dtype: float64
69440 69447    0.0
Name: new_cases, dtype: float64
69441 69448    5530.0
Name: new_cases, dtype: float64
69442 69449    4955.0
Name: new_cases, dtype: float64
69443 69450    4574.0
Name: new_cases, dtype: float64
69444 69451    4184.0
Name: new_cases, dtype: float64
69445 69452    3970.0
Name: new_cases, dtype: float64
69446 69453    3054.0
Name: new_cases, dtype: float64
69447 69454    2555.0
Name: new_cases, dtype: float64
69448 69455    2472.0
Name: new_cases, dtype: float64
69449 69456    4151.0
Name: new_cases, dtype: float64
69450 69457    5260.0
Name: new_cases, dtype: float64
69451 69458    4267.0
Name: new_cases, dtype: float64
69452 69459    3922.0
Name: new_cases, dtype: float64
69453 69460    3058.0
Name: new_cases, dtype: float64
69454 69461    3262.0
Name: new_cases, dtype: float64
69455 69462    1848.0
Name: new_cases, dtype: float64
69456 69463    3541.0
Name: new_cases, dtype: float64

69457 69464    3146.0
Name: new_cases, dtype: float64
69458 69465    3230.0
Name: new_cases, dtype: float64
69459 69466    2758.0
Name: new_cases, dtype: float64
69460 69467    1948.0
Name: new_cases, dtype: float64
69461 69468    1601.0
Name: new_cases, dtype: float64
69462 69469    1178.0
Name: new_cases, dtype: float64
69463 69470    1936.0
Name: new_cases, dtype: float64
69464 69471    1790.0
Name: new_cases, dtype: float64
69465 69472    1475.0
Name: new_cases, dtype: float64
69466 69473    1384.0
Name: new_cases, dtype: float64
69467 69474    1047.0
Name: new_cases, dtype: float64
69468 69475    611.0
Name: new_cases, dtype: float64
69469 69476    552.0
Name: new_cases, dtype: float64
69470 69477    992.0
Name: new_cases, dtype: float64
69471 69478    925.0
Name: new_cases, dtype: float64
69472 69479    339.0
Name: new_cases, dtype: float64
69473 69480    817.0
Name: new_cases, dtype: float64
69474 69481    538.0
Name: new_cases, dtype: float64
69475 69482    0.0
Name: new_cases, dtype: float64
69476 69483    541.0
Name: new_cases, dtype: float64
69477 69484    201.0
Name: new_cases, dtype: float64
69478 69485    514.0
Name: new_cases, dtype: float64
69479 69486    466.0
Name: new_cases, dtype: float64
69480 69487    351.0
Name: new_cases, dtype: float64
69481 69488    251.0
Name: new_cases, dtype: float64
69482 69489    363.0
Name: new_cases, dtype: float64
69483 69490    177.0
Name: new_cases, dtype: float64
69484 69491    356.0
Name: new_cases, dtype: float64
69485 69492    317.0
Name: new_cases, dtype: float64
69486 69493    296.0
Name: new_cases, dtype: float64
69487 69494    270.0
Name: new_cases, dtype: float64
69488 69495    188.0
Name: new_cases, dtype: float64
69489 69496    139.0
Name: new_cases, dtype: float64
69490 69497    120.0
Name: new_cases, dtype: float64
69491 69498    225.0
Name: new_cases, dtype: float64
69492 69499    176.0
Name: new_cases, dtype: float64
69493 69500    256.0
Name: new_cases, dtype: float64
69494 69501    312.0
Name: new_cases, dtype: float64
69495 69502    34.0
Name: new_cases, dtype: float64
69496 69503   -53.0
Name: new_cases, dtype: float64
69497 69504    164.0
Name: new_cases, dtype: float64
69498 69505    171.0
Name: new_cases, dtype: float64
69499 69506    139.0
Name: new_cases, dtype: float64
69500 69507    135.0
Name: new_cases, dtype: float64
69501 69508    315.0
Name: new_cases, dtype: float64
69502 69509    85.0
Name: new_cases, dtype: float64
69503 69510    82.0
Name: new_cases, dtype: float64
69504 69511    50.0
Name: new_cases, dtype: float64
69505 69512    83.0
Name: new_cases, dtype: float64
69506 69513    110.0
Name: new_cases, dtype: float64
69507 69514    106.0
Name: new_cases, dtype: float64
69508 69515    84.0
Name: new_cases, dtype: float64
69509 69516    74.0
Name: new_cases, dtype: float64
69510 69517    0.0
Name: new_cases, dtype: float64
69511 69518    73.0
Name: new_cases, dtype: float64
69512 69519    67.0
Name: new_cases, dtype: float64
69513 69520    76.0
Name: new_cases, dtype: float64
69514 69521    70.0
Name: new_cases, dtype: float64
69515 69522    61.0
Name: new_cases, dtype: float64
69516 69523    30.0
Name: new_cases, dtype: float64
69517 69524    28.0
Name: new_cases, dtype: float64
69518 69525    8.0
Name: new_cases, dtype: float64
69519 69526    63.0
Name: new_cases, dtype: float64
69520 69527    43.0
Name: new_cases, dtype: float64
69521 69528    30.0
Name: new_cases, dtype: float64
69522 69529    29.0
Name: new_cases, dtype: float64
69523 69530    20.0
Name: new_cases, dtype: float64
69524 69531    39.0
Name: new_cases, dtype: float64
69525 69532    1.0
Name: new_cases, dtype: float64
69526 69533    40.0
Name: new_cases, dtype: float64
69527 69534    8.0
Name: new_cases, dtype: float64
69528 69535    54.0
Name: new_cases, dtype: float64
69529 69536    42.0
Name: new_cases, dtype: float64
69530 69537    27.0
Name: new_cases, dtype: float64
69531 69538    18.0
Name: new_cases, dtype: float64
69532 69539    11.0
Name: new_cases, dtype: float64
69533 69540    48.0
Name: new_cases, dtype: float64
69534 69541    22.0
Name: new_cases, dtype: float64
69535 69542    19.0
Name: new_cases, dtype: float64
69536 69543    12.0
Name: new_cases, dtype: float64
69537 69544    13.0
Name: new_cases, dtype: float64
69538 69545    20.0
Name: new_cases, dtype: float64
69539 69546    5.0
Name: new_cases, dtype: float64
69540 69547    17.0
Name: new_cases, dtype: float64
69541 69548    36.0
Name: new_cases, dtype: float64
69542 69549    6.0
Name: new_cases, dtype: float64
69543 69550    15.0
Name: new_cases, dtype: float64
69544 69551    7.0
Name: new_cases, dtype: float64
69545 69552    27.0
Name: new_cases, dtype: float64
69546 69553    5.0
Name: new_cases, dtype: float64
69547 69554    14.0
Name: new_cases, dtype: float64
69548 69555    0.0
Name: new_cases, dtype: float64
69549 69556    0.0
Name: new_cases, dtype: float64
69550 69557    45.0
Name: new_cases, dtype: float64
69551 69558    23.0
Name: new_cases, dtype: float64
69552 69559    8.0
Name: new_cases, dtype: float64
69553 69560    5.0
Name: new_cases, dtype: float64
69554 69561    24.0
Name: new_cases, dtype: float64
69555 69562    11.0
Name: new_cases, dtype: float64
69556 69563    19.0
Name: new_cases, dtype: float64
69557 69564    27.0
Name: new_cases, dtype: float64
69558 69565    22.0
Name: new_cases, dtype: float64
69559 69566    61.0
Name: new_cases, dtype: float64
69560 69567    37.0
Name: new_cases, dtype: float64
69561 69568    123.0
Name: new_cases, dtype: float64
69562 69569    89.0
Name: new_cases, dtype: float64
69563 69570    146.0
Name: new_cases, dtype: float64
69564 69571    219.0
Name: new_cases, dtype: float64
69565 69572    194.0
Name: new_cases, dtype: float64
69566 69573    185.0
Name: new_cases, dtype: float64
69567 69574    65.0
Name: new_cases, dtype: float64
69568 69575    308.0
Name: new_cases, dtype: float64
69569 69576    290.0
Name: new_cases, dtype: float64
69570 69577    291.0
Name: new_cases, dtype: float64
69571 69578    290.0
Name: new_cases, dtype: float64
69572 69579    304.0
Name: new_cases, dtype: float64
69573 69580    277.0
Name: new_cases, dtype: float64
69574 69581    321.0
Name: new_cases, dtype: float64
69575 69582    496.0
Name: new_cases, dtype: float64
69576 69583    427.0
Name: new_cases, dtype: float64
69577 69584    486.0
Name: new_cases, dtype: float64
69578 69585    611.0
Name: new_cases, dtype: float64
69579 69586    390.0
Name: new_cases, dtype: float64
69580 69587    432.0
Name: new_cases, dtype: float64
69581 69588    323.0
Name: new_cases, dtype: float64
69582 69589    193.0
Name: new_cases, dtype: float64
69583 69590    1275.0
Name: new_cases, dtype: float64
69584 69591    720.0
Name: new_cases, dtype: float64
69585 69592    952.0
Name: new_cases, dtype: float64
69586 69593    830.0
Name: new_cases, dtype: float64
69587 69594    864.0
Name: new_cases, dtype: float64
69588 69595    755.0
Name: new_cases, dtype: float64
69589 69596    1220.0
Name: new_cases, dtype: float64
69590 69597    1491.0
Name: new_cases, dtype: float64
69591 69598    1118.0
Name: new_cases, dtype: float64
69592 69599    1434.0
Name: new_cases, dtype: float64
69593 69600    991.0
Name: new_cases, dtype: float64
69594 69601    1421.0
Name: new_cases, dtype: float64
69595 69602    1254.0
Name: new_cases, dtype: float64
69596 69603    2065.0
Name: new_cases, dtype: float64
69597 69604    2195.0
Name: new_cases, dtype: float64
69598 69605    2328.0
Name: new_cases, dtype: float64
69599 69606    1823.0
Name: new_cases, dtype: float64
69600 69607    2280.0
Name: new_cases, dtype: float64
69601 69608    2675.0
Name: new_cases, dtype: float64
69602 69609    1783.0
Name: new_cases, dtype: float64
69603 69610    3849.0
Name: new_cases, dtype: float64
69604 69611    3148.0
Name: new_cases, dtype: float64
69605 69612    2968.0
Name: new_cases, dtype: float64
69606 69613    4435.0
Name: new_cases, dtype: float64
69607 69614    2904.0
Name: new_cases, dtype: float64
69608 69615    4221.0
Name: new_cases, dtype: float64
69609 69616    3156.0
Name: new_cases, dtype: float64
69610 69617    5923.0
Name: new_cases, dtype: float64
69611 69618    4164.0
Name: new_cases, dtype: float64
69612 69619    7668.0
Name: new_cases, dtype: float64
69613 69620    6525.0
Name: new_cases, dtype: float64
69614 69621    4512.0
Name: new_cases, dtype: float64
69615 69622    5622.0
Name: new_cases, dtype: float64

69616 69623    4464.0
Name: new_cases, dtype: float64
69617 69624    8698.0
Name: new_cases, dtype: float64
69618 69625    8252.0
Name: new_cases, dtype: float64
69619 69626    5883.0
Name: new_cases, dtype: float64
69620 69627    8413.0
Name: new_cases, dtype: float64
69621 69628    7606.0
Name: new_cases, dtype: float64
69622 69629    7277.0
Name: new_cases, dtype: float64
69623 69630    5035.0
Name: new_cases, dtype: float64
69624 69631    8586.0
Name: new_cases, dtype: float64
69625 69632    12113.0
Name: new_cases, dtype: float64
69626 69633    6602.0
Name: new_cases, dtype: float64
69627 69634    10446.0
Name: new_cases, dtype: float64
69628 69635    6352.0
Name: new_cases, dtype: float64
69629 69636    11177.0
Name: new_cases, dtype: float64
69630 69637    5809.0
Name: new_cases, dtype: float64
69631 69638    9879.0
Name: new_cases, dtype: float64
69632 69639    4864.0
Name: new_cases, dtype: float64
69633 69640    16629.0
Name: new_cases, dtype: float64
69634 69641    13900.0
Name: new_cases, dtype: float64
69635 69642    8090.0
Name: new_cases, dtype: float64
69636 69643    7993.0
Name: new_cases, dtype: float64
69637 69644    4632.0
Name: new_cases, dtype: float64
69638 69645    0.0
Name: new_cases, dtype: float64
69639 69646    0.0
Name: new_cases, dtype: float64
69640 69647    22291.0
Name: new_cases, dtype: float64
69641 69648    6045.0
Name: new_cases, dtype: float64
69642 69649    8354.0
Name: new_cases, dtype: float64
69643 69650    11396.0
Name: new_cases, dtype: float64
69644 69651    6571.0
Name: new_cases, dtype: float64
69645 69652    11800.0
Name: new_cases, dtype: float64
69646 69653    10730.0
Name: new_cases, dtype: float64
69647 69654    7429.0
Name: new_cases, dtype: float64
69648 69655    6191.0
Name: new_cases, dtype: float64
69649 69656    3040.0
Name: new_cases, dtype: float64
69650 69657    8954.0
Name: new_cases, dtype: float64
69651 69658    7732.0
Name: new_cases, dtype: float64
69652 69659    6935.0
Name: new_cases, dtype: float64
69653 69660    7198.0
Name: new_cases, dtype: float64
69654 69661    5371.0
Name: new_cases, dtype: float64
69655 69662    6718.0
Name: new_cases, dtype: float64
69656 69663    2249.0
Name: new_cases, dtype: float64
69657 69664    6345.0
Name: new_cases, dtype: float64
69658 69665    3261.0
Name: new_cases, dtype: float64
69659 69666    4024.0
Name: new_cases, dtype: float64
69660 69667    4165.0
Name: new_cases, dtype: float64
69661 69668    2875.0
Name: new_cases, dtype: float64
69662 69669    4948.0
Name: new_cases, dtype: float64
69663 69670    3352.0
Name: new_cases, dtype: float64
69664 69671    2407.0
Name: new_cases, dtype: float64
69665 69672    2152.0
Name: new_cases, dtype: float64
69666 69673    3369.0
Name: new_cases, dtype: float64
69667 69674    2845.0
Name: new_cases, dtype: float64
69668 69675    2246.0
Name: new_cases, dtype: float64
69669 69676    2379.0
Name: new_cases, dtype: float64
69670 69677    1809.0
Name: new_cases, dtype: float64
69671 69678    1579.0
Name: new_cases, dtype: float64
69672 69679    1355.0
Name: new_cases, dtype: float64
69673 69680    2159.0
Name: new_cases, dtype: float64
69674 69681    1868.0
Name: new_cases, dtype: float64
69675 69682    1557.0
Name: new_cases, dtype: float64
69676 69683    1613.0
Name: new_cases, dtype: float64
69677 69684    1305.0
Name: new_cases, dtype: float64
69678 69685    1104.0
Name: new_cases, dtype: float64
69679 69686    1000.0
Name: new_cases, dtype: float64
69680 69687    1441.0
Name: new_cases, dtype: float64
69681 69688    1243.0
Name: new_cases, dtype: float64
69682 69689    901.0
Name: new_cases, dtype: float64
69683 69690    1060.0
Name: new_cases, dtype: float64
69684 69691    932.0
Name: new_cases, dtype: float64
69685 69692    501.0
Name: new_cases, dtype: float64
69686 69693    684.0
Name: new_cases, dtype: float64
69687 69694    961.0
Name: new_cases, dtype: float64
69688 69695    857.0
Name: new_cases, dtype: float64
69689 69696    599.0
Name: new_cases, dtype: float64
69690 69697    675.0
Name: new_cases, dtype: float64
69691 69698    571.0
Name: new_cases, dtype: float64
69692 69699    384.0
Name: new_cases, dtype: float64
69693 69700    332.0
Name: new_cases, dtype: float64
69694 69701    760.0
Name: new_cases, dtype: float64
69695 69702    3379.0
Name: new_cases, dtype: float64
69696 69703    650.0
Name: new_cases, dtype: float64
69697 69704    554.0
Name: new_cases, dtype: float64
69698 69705    462.0
Name: new_cases, dtype: float64
69699 69706    342.0
Name: new_cases, dtype: float64
69700 69707    384.0
Name: new_cases, dtype: float64
69701 69708    777.0
Name: new_cases, dtype: float64
69702 69709    418.0
Name: new_cases, dtype: float64
69703 69710    470.0
Name: new_cases, dtype: float64
69704 69711    520.0
Name: new_cases, dtype: float64
69705 69712    413.0
Name: new_cases, dtype: float64
69706 69713    295.0
Name: new_cases, dtype: float64
69707 69714    308.0
Name: new_cases, dtype: float64
69708 69715    591.0
Name: new_cases, dtype: float64
69709 69716    452.0
Name: new_cases, dtype: float64
69710 69717    580.0
Name: new_cases, dtype: float64
69711 69718    445.0
Name: new_cases, dtype: float64
69712 69719    465.0
Name: new_cases, dtype: float64
69713 69720    361.0
Name: new_cases, dtype: float64
69714 69721    351.0
Name: new_cases, dtype: float64
69715 69722    701.0
Name: new_cases, dtype: float64
69716 69723   -1149.0
Name: new_cases, dtype: float64
69717 69724    494.0
Name: new_cases, dtype: float64
69718 69725    607.0
Name: new_cases, dtype: float64
69719 69726    453.0
Name: new_cases, dtype: float64
69720 69727    340.0
Name: new_cases, dtype: float64
69721 69728    329.0
Name: new_cases, dtype: float64
69722 69729    766.0
Name: new_cases, dtype: float64
69723 69730    684.0
Name: new_cases, dtype: float64
69724 69731    443.0
Name: new_cases, dtype: float64
69725 69732    565.0
Name: new_cases, dtype: float64
69726 69733    415.0
Name: new_cases, dtype: float64
69727 69734    359.0
Name: new_cases, dtype: float64
69728 69735    473.0
Name: new_cases, dtype: float64
69729 69736    755.0
Name: new_cases, dtype: float64
69730 69737    804.0
Name: new_cases, dtype: float64
69731 69738    755.0
Name: new_cases, dtype: float64
69732 69739    571.0
Name: new_cases, dtype: float64
69733 69740    585.0
Name: new_cases, dtype: float64
69734 69741    356.0
Name: new_cases, dtype: float64
69735 69742    474.0
Name: new_cases, dtype: float64
69736 69743    800.0
Name: new_cases, dtype: float64
69737 69744    761.0
Name: new_cases, dtype: float64
69738 69745    627.0
Name: new_cases, dtype: float64
69739 69746    878.0
Name: new_cases, dtype: float64
69740 69747    720.0
Name: new_cases, dtype: float64
69741 69748    696.0
Name: new_cases, dtype: float64
69742 69749    794.0
Name: new_cases, dtype: float64
69743 69750    1356.0
Name: new_cases, dtype: float64
69744 69751    1120.0
Name: new_cases, dtype: float64
69745 69752    1200.0
Name: new_cases, dtype: float64
69746 69753    1745.0
Name: new_cases, dtype: float64
69747 69754    1351.0
Name: new_cases, dtype: float64
69748 69755    1455.0
Name: new_cases, dtype: float64
69749 69756    1241.0
Name: new_cases, dtype: float64
69750 69757    3046.0
Name: new_cases, dtype: float64
69751 69758    2995.0
Name: new_cases, dtype: float64
69752 69759    3446.0
Name: new_cases, dtype: float64
69753 69760    5600.0
Name: new_cases, dtype: float64
69754 69761    3886.0
Name: new_cases, dtype: float64
69755 69762    6121.0
Name: new_cases, dtype: float64
69756 69763    5060.0
Name: new_cases, dtype: float64
69757 69764    9803.0
Name: new_cases, dtype: float64
69758 69765    6882.0
Name: new_cases, dtype: float64
69759 69766    17232.0
Name: new_cases, dtype: float64
69760 69767    19418.0
Name: new_cases, dtype: float64
69761 69768    14745.0
Name: new_cases, dtype: float64
69762 69769    22398.0
Name: new_cases, dtype: float64
69763 Series([], Name: new_cases, dtype: float64)
69764 Series([], Name: new_cases, dtype: float64)
69765 Series([], Name: new_cases, dtype: float64)
69766 Series([], Name: new_cases, dtype: float64)
69767 Series([], Name: new_cases, dtype: float64)
69768 Series([], Name: new_cases, dtype: float64)
69769 Series([], Name: new_cases, dtype: float64)
69770 69777    1.0
Name: new_cases, dtype: float64
69771 69778    0.0
Name: new_cases, dtype: float64
69772 69779    0.0
Name: new_cases, dtype: float64
69773 69780    0.0
Name: new_cases, dtype: float64
69774 69781    0.0
Name: new_cases, dtype: float64
69775 69782    0.0
Name: new_cases, dtype: float64
69776 69783    0.0
Name: new_cases, dtype: float64
69777 69784    0.0
Name: new_cases, dtype: float64
69778 69785    0.0
Name: new_cases, dtype: float64
69779 69786    0.0
Name: new_cases, dtype: float64
69780 69787    0.0
Name: new_cases, dtype: float64
69781 69788    0.0
Name: new_cases, dtype: float64
69782 69789    0.0
Name: new_cases, dtype: float64
69783 69790    0.0
Name: new_cases, dtype: float64
69784 69791    17.0
Name: new_cases, dtype: float64
69785 69792    42.0
Name: new_cases, dtype: float64

69786 69793    93.0
Name: new_cases, dtype: float64
69787 69794    74.0
Name: new_cases, dtype: float64
69788 69795    93.0
Name: new_cases, dtype: float64
69789 69796    131.0
Name: new_cases, dtype: float64
69790 69797    202.0
Name: new_cases, dtype: float64
69791 69798    233.0
Name: new_cases, dtype: float64
69792 69799    240.0
Name: new_cases, dtype: float64
69793 69800    566.0
Name: new_cases, dtype: float64
69794 69801    342.0
Name: new_cases, dtype: float64
69795 69802    466.0
Name: new_cases, dtype: float64
69796 69803    587.0
Name: new_cases, dtype: float64
69797 69804    769.0
Name: new_cases, dtype: float64
69798 69805    778.0
Name: new_cases, dtype: float64
69799 69806    1247.0
Name: new_cases, dtype: float64
69800 69807    1492.0
Name: new_cases, dtype: float64
69801 69808    1797.0
Name: new_cases, dtype: float64
69802 69809    977.0
Name: new_cases, dtype: float64
69803 69810    2313.0
Name: new_cases, dtype: float64
69804 69811    2651.0
Name: new_cases, dtype: float64
69805 69812    2547.0
Name: new_cases, dtype: float64
69806 69813    3497.0
Name: new_cases, dtype: float64
69807 69814    3590.0
Name: new_cases, dtype: float64
69808 69815    3233.0
Name: new_cases, dtype: float64
69809 69816    3526.0
Name: new_cases, dtype: float64
69810 69817    4207.0
Name: new_cases, dtype: float64
69811 69818    5322.0
Name: new_cases, dtype: float64
69812 69819    5986.0
Name: new_cases, dtype: float64
69813 69820    6557.0
Name: new_cases, dtype: float64
69814 69821    5560.0
Name: new_cases, dtype: float64
69815 69822    4789.0
Name: new_cases, dtype: float64
69816 69823    5249.0
Name: new_cases, dtype: float64
69817 69824    5210.0
Name: new_cases, dtype: float64
69818 69825    6203.0
Name: new_cases, dtype: float64
69819 69826    5909.0
Name: new_cases, dtype: float64
69820 69827    5974.0
Name: new_cases, dtype: float64
69821 69828    5217.0
Name: new_cases, dtype: float64
69822 69829    4050.0
Name: new_cases, dtype: float64
69823 69830    4053.0
Name: new_cases, dtype: float64
69824 69831    4782.0
Name: new_cases, dtype: float64
69825 69832    4668.0
Name: new_cases, dtype: float64
69826 69833    4585.0
Name: new_cases, dtype: float64
69827 69834    4805.0
Name: new_cases, dtype: float64
69828 69835    4316.0
Name: new_cases, dtype: float64
69829 69836    3599.0
Name: new_cases, dtype: float64
69830 69837    3039.0
Name: new_cases, dtype: float64
69831 69838    3836.0
Name: new_cases, dtype: float64
69832 69839    4204.0
Name: new_cases, dtype: float64
69833 69840    3951.0
Name: new_cases, dtype: float64
69834 69841    4694.0
Name: new_cases, dtype: float64
69835 69842    4092.0
Name: new_cases, dtype: float64
69836 69843    3153.0
Name: new_cases, dtype: float64
69837 69844    2972.0
Name: new_cases, dtype: float64
69838 69845    2667.0
Name: new_cases, dtype: float64
69839 69846    3786.0
Name: new_cases, dtype: float64
69840 69847    3493.0
Name: new_cases, dtype: float64
69841 69848    3491.0
Name: new_cases, dtype: float64
69842 69849    3047.0
Name: new_cases, dtype: float64
69843 69850    2256.0
Name: new_cases, dtype: float64
69844 69851    2729.0
Name: new_cases, dtype: float64
69845 69852    3370.0
Name: new_cases, dtype: float64
69846 69853    2646.0
Name: new_cases, dtype: float64
69847 69854    3021.0
Name: new_cases, dtype: float64
69848 69855    2357.0
Name: new_cases, dtype: float64
69849 69856    2324.0
Name: new_cases, dtype: float64
69850 69857    1739.0
Name: new_cases, dtype: float64
69851 69858    2091.0
Name: new_cases, dtype: float64
69852 69859    2086.0
Name: new_cases, dtype: float64
69853 69860    1872.0
Name: new_cases, dtype: float64
69854 69861    1965.0
Name: new_cases, dtype: float64
69855 69862    1900.0
Name: new_cases, dtype: float64
69856 69863    1389.0
Name: new_cases, dtype: float64
69857 69864    1221.0
Name: new_cases, dtype: float64
69858 69865    1075.0
Name: new_cases, dtype: float64
69859 69866    1444.0
Name: new_cases, dtype: float64
69860 69867    1401.0
Name: new_cases, dtype: float64
69861 69868    1327.0
Name: new_cases, dtype: float64
69862 69869    1083.0
Name: new_cases, dtype: float64
69863 69870    802.0
Name: new_cases, dtype: float64
69864 69871    744.0
Name: new_cases, dtype: float64
69865 69872    1402.0
Name: new_cases, dtype: float64
69866 69873    888.0
Name: new_cases, dtype: float64
69867 69874    992.0
Name: new_cases, dtype: float64
69868 69875    789.0
Name: new_cases, dtype: float64
69869 69876    875.0
Name: new_cases, dtype: float64
69870 69877    675.0
Name: new_cases, dtype: float64
69871 69878    451.0
Name: new_cases, dtype: float64
69872 69879    813.0
Name: new_cases, dtype: float64
69873 69880    665.0
Name: new_cases, dtype: float64
69874 69881    642.0
Name: new_cases, dtype: float64
69875 69882    652.0
Name: new_cases, dtype: float64
69876 69883    669.0
Name: new_cases, dtype: float64
69877 69884    531.0
Name: new_cases, dtype: float64
69878 69885    300.0
Name: new_cases, dtype: float64
69879 69886    397.0
Name: new_cases, dtype: float64
69880 69887    584.0
Name: new_cases, dtype: float64
69881 69888    593.0
Name: new_cases, dtype: float64
69882 69889    516.0
Name: new_cases, dtype: float64
69883 69890    416.0
Name: new_cases, dtype: float64
69884 69891    333.0
Name: new_cases, dtype: float64
69885 69892    200.0
Name: new_cases, dtype: float64
69886 69893    318.0
Name: new_cases, dtype: float64
69887 69894    321.0
Name: new_cases, dtype: float64
69888 69895    177.0
Name: new_cases, dtype: float64
69889 69896    518.0
Name: new_cases, dtype: float64
69890 69897    270.0
Name: new_cases, dtype: float64
69891 69898    197.0
Name: new_cases, dtype: float64
69892 69899    280.0
Name: new_cases, dtype: float64
69893 69900    283.0
Name: new_cases, dtype: float64
69894 69901    202.0
Name: new_cases, dtype: float64
69895 69902    379.0
Name: new_cases, dtype: float64
69896 69903    163.0
Name: new_cases, dtype: float64
69897 69904    346.0
Name: new_cases, dtype: float64
69898 69905    338.0
Name: new_cases, dtype: float64
69899 69906    301.0
Name: new_cases, dtype: float64
69900 69907    210.0
Name: new_cases, dtype: float64
69901 69908    328.0
Name: new_cases, dtype: float64
69902 69909    331.0
Name: new_cases, dtype: float64
69903 69910   -148.0
Name: new_cases, dtype: float64
69904 69911    264.0
Name: new_cases, dtype: float64
69905 69912    224.0
Name: new_cases, dtype: float64
69906 69913    221.0
Name: new_cases, dtype: float64
69907 69914    113.0
Name: new_cases, dtype: float64
69908 69915    577.0
Name: new_cases, dtype: float64
69909 69916    296.0
Name: new_cases, dtype: float64
69910 69917    255.0
Name: new_cases, dtype: float64
69911 69918    175.0
Name: new_cases, dtype: float64
69912 69919    174.0
Name: new_cases, dtype: float64
69913 69920    126.0
Name: new_cases, dtype: float64
69914 69921    142.0
Name: new_cases, dtype: float64
69915 69922    182.0
Name: new_cases, dtype: float64
69916 69923    201.0
Name: new_cases, dtype: float64
69917 69924    223.0
Name: new_cases, dtype: float64
69918 69925    235.0
Name: new_cases, dtype: float64
69919 69926    192.0
Name: new_cases, dtype: float64
69920 69927    208.0
Name: new_cases, dtype: float64
69921 69928    137.0
Name: new_cases, dtype: float64
69922 69929    193.0
Name: new_cases, dtype: float64
69923 69930    214.0
Name: new_cases, dtype: float64
69924 69931    276.0
Name: new_cases, dtype: float64
69925 69932    188.0
Name: new_cases, dtype: float64
69926 69933    234.0
Name: new_cases, dtype: float64
69927 69934    169.0
Name: new_cases, dtype: float64
69928 69935    114.0
Name: new_cases, dtype: float64
69929 69936    162.0
Name: new_cases, dtype: float64
69930 69937    230.0
Name: new_cases, dtype: float64
69931 69938    231.0
Name: new_cases, dtype: float64
69932 69939    249.0
Name: new_cases, dtype: float64
69933 69940    218.0
Name: new_cases, dtype: float64
69934 69941    190.0
Name: new_cases, dtype: float64
69935 69942    128.0
Name: new_cases, dtype: float64
69936 69943    280.0
Name: new_cases, dtype: float64
69937 69944    306.0
Name: new_cases, dtype: float64
69938 69945    252.0
Name: new_cases, dtype: float64
69939 69946    274.0
Name: new_cases, dtype: float64
69940 69947    254.0
Name: new_cases, dtype: float64

69941 69948    168.0
Name: new_cases, dtype: float64
69942 69949    202.0
Name: new_cases, dtype: float64
69943 69950    288.0
Name: new_cases, dtype: float64
69944 69951    382.0
Name: new_cases, dtype: float64
69945 69952    379.0
Name: new_cases, dtype: float64
69946 69953    295.0
Name: new_cases, dtype: float64
69947 69954    238.0
Name: new_cases, dtype: float64
69948 69955    159.0
Name: new_cases, dtype: float64
69949 69956    190.0
Name: new_cases, dtype: float64
69950 69957    384.0
Name: new_cases, dtype: float64
69951 69958    401.0
Name: new_cases, dtype: float64
69952 69959    552.0
Name: new_cases, dtype: float64
69953 69960    347.0
Name: new_cases, dtype: float64
69954 69961    463.0
Name: new_cases, dtype: float64
69955 69962    259.0
Name: new_cases, dtype: float64
69956 69963    412.0
Name: new_cases, dtype: float64
69957 69964    476.0
Name: new_cases, dtype: float64
69958 69965    522.0
Name: new_cases, dtype: float64
69959 69966    574.0
Name: new_cases, dtype: float64
69960 69967    629.0
Name: new_cases, dtype: float64
69961 69968    477.0
Name: new_cases, dtype: float64
69962 69969    320.0
Name: new_cases, dtype: float64
69963 69970    401.0
Name: new_cases, dtype: float64
69964 69971    642.0
Name: new_cases, dtype: float64
69965 69972    840.0
Name: new_cases, dtype: float64
69966 69973    947.0
Name: new_cases, dtype: float64
69967 69974    1071.0
Name: new_cases, dtype: float64
69968 69975    1209.0
Name: new_cases, dtype: float64
69969 69976    953.0
Name: new_cases, dtype: float64
69970 69977    876.0
Name: new_cases, dtype: float64
69971 69978    1366.0
Name: new_cases, dtype: float64
69972 69979    1409.0
Name: new_cases, dtype: float64
69973 69980    1460.0
Name: new_cases, dtype: float64
69974 69981    1444.0
Name: new_cases, dtype: float64
69975 69982    1365.0
Name: new_cases, dtype: float64
69976 69983    996.0
Name: new_cases, dtype: float64
69977 69984    975.0
Name: new_cases, dtype: float64
69978 69985    1326.0
Name: new_cases, dtype: float64
69979 69986    1397.0
Name: new_cases, dtype: float64
69980 69987    1732.0
Name: new_cases, dtype: float64
69981 69988    1694.0
Name: new_cases, dtype: float64
69982 69989    1296.0
Name: new_cases, dtype: float64
69983 69990    1150.0
Name: new_cases, dtype: float64
69984 69991    1369.0
Name: new_cases, dtype: float64
69985 69992    1430.0
Name: new_cases, dtype: float64
69986 69993    1597.0
Name: new_cases, dtype: float64
69987 69994    1616.0
Name: new_cases, dtype: float64
69988 69995    1501.0
Name: new_cases, dtype: float64
69989 69996    1456.0
Name: new_cases, dtype: float64
69990 69997    1008.0
Name: new_cases, dtype: float64
69991 69998    1229.0
Name: new_cases, dtype: float64
69992 69999    1452.0
Name: new_cases, dtype: float64
69993 70000    1583.0
Name: new_cases, dtype: float64
69994 70001    1907.0
Name: new_cases, dtype: float64
69995 70002    1637.0
Name: new_cases, dtype: float64
69996 70003    1587.0
Name: new_cases, dtype: float64
69997 70004    1350.0
Name: new_cases, dtype: float64
69998 70005    1391.0
Name: new_cases, dtype: float64
69999 70006    1640.0
Name: new_cases, dtype: float64
70000 70007    1786.0
Name: new_cases, dtype: float64
70001 70008    1912.0
Name: new_cases, dtype: float64
70002 70009    1869.0
Name: new_cases, dtype: float64
70003 70010    1766.0
Name: new_cases, dtype: float64
70004 70011    1494.0
Name: new_cases, dtype: float64
70005 70012    1647.0
Name: new_cases, dtype: float64
70006 70013    1850.0
Name: new_cases, dtype: float64
70007 70014    2548.0
Name: new_cases, dtype: float64
70008 70015    2499.0
Name: new_cases, dtype: float64
70009 70016    2843.0
Name: new_cases, dtype: float64
70010 70017    2578.0
Name: new_cases, dtype: float64
70011 70018    2257.0
Name: new_cases, dtype: float64
70012 70019    2677.0
Name: new_cases, dtype: float64
70013 70020    3677.0
Name: new_cases, dtype: float64
70014 70021    4458.0
Name: new_cases, dtype: float64
70015 70022    5372.0
Name: new_cases, dtype: float64
70016 70023    5724.0
Name: new_cases, dtype: float64
70017 70024    5456.0
Name: new_cases, dtype: float64
70018 70025    4619.0
Name: new_cases, dtype: float64
70019 70026    5898.0
Name: new_cases, dtype: float64
70020 70027    7332.0
Name: new_cases, dtype: float64
70021 70028    8803.0
Name: new_cases, dtype: float64
70022 70029    10009.0
Name: new_cases, dtype: float64
70023 70030    10925.0
Name: new_cases, dtype: float64
70024 70031    11705.0
Name: new_cases, dtype: float64
70025 70032    9337.0
Name: new_cases, dtype: float64
70026 70033    10871.0
Name: new_cases, dtype: float64
70027 70034    15199.0
Name: new_cases, dtype: float64
70028 70035    16078.0
Name: new_cases, dtype: float64
70029 70036    19143.0
Name: new_cases, dtype: float64
70030 70037    19640.0
Name: new_cases, dtype: float64
70031 70038    21273.0
Name: new_cases, dtype: float64
70032 70039    17007.0
Name: new_cases, dtype: float64
70033 70040    21989.0
Name: new_cases, dtype: float64
70034 70041    24988.0
Name: new_cases, dtype: float64
70035 70042    26829.0
Name: new_cases, dtype: float64
70036 70043    31079.0
Name: new_cases, dtype: float64
70037 70044    31756.0
Name: new_cases, dtype: float64
70038 70045    29905.0
Name: new_cases, dtype: float64
70039 70046    22253.0
Name: new_cases, dtype: float64
70040 70047    28241.0
Name: new_cases, dtype: float64
70041 70048    30548.0
Name: new_cases, dtype: float64
70042 70049    34502.0
Name: new_cases, dtype: float64
70043 70050    37802.0
Name: new_cases, dtype: float64
70044 70051    39809.0
Name: new_cases, dtype: float64
70045 70052    32614.0
Name: new_cases, dtype: float64
70046 70053    25269.0
Name: new_cases, dtype: float64
70047 70054    35090.0
Name: new_cases, dtype: float64
70048 70055    32961.0
Name: new_cases, dtype: float64
70049 70056    37977.0
Name: new_cases, dtype: float64
70050 70057    40902.0
Name: new_cases, dtype: float64
70051 70058    37249.0
Name: new_cases, dtype: float64
70052 70059    33977.0
Name: new_cases, dtype: float64
70053 70060    27352.0
Name: new_cases, dtype: float64
70054 70061    32191.0
Name: new_cases, dtype: float64
70055 70062    34280.0
Name: new_cases, dtype: float64
70056 70063    36176.0
Name: new_cases, dtype: float64
70057 70064    37239.0
Name: new_cases, dtype: float64
70058 70065    34764.0
Name: new_cases, dtype: float64
70059 70066    28337.0
Name: new_cases, dtype: float64
70060 70067    22927.0
Name: new_cases, dtype: float64
70061 70068    23227.0
Name: new_cases, dtype: float64
70062 70069    25852.0
Name: new_cases, dtype: float64
70063 70070    29001.0
Name: new_cases, dtype: float64
70064 70071    28342.0
Name: new_cases, dtype: float64
70065 70072    26315.0
Name: new_cases, dtype: float64
70066 70073    20646.0
Name: new_cases, dtype: float64
70067 70074    16376.0
Name: new_cases, dtype: float64
70068 70075    19347.0
Name: new_cases, dtype: float64
70069 70076    20709.0
Name: new_cases, dtype: float64
70070 70077    23219.0
Name: new_cases, dtype: float64
70071 70078    24110.0
Name: new_cases, dtype: float64
70072 70079    21052.0
Name: new_cases, dtype: float64
70073 70080    18887.0
Name: new_cases, dtype: float64
70074 70081    13679.0
Name: new_cases, dtype: float64
70075 70082    14837.0
Name: new_cases, dtype: float64
70076 70083    12755.0
Name: new_cases, dtype: float64
70077 70084    16998.0
Name: new_cases, dtype: float64
70078 70085    18726.0
Name: new_cases, dtype: float64
70079 70086    19902.0
Name: new_cases, dtype: float64
70080 70087    17937.0
Name: new_cases, dtype: float64
70081 70088    12025.0
Name: new_cases, dtype: float64
70082 70089    14839.0
Name: new_cases, dtype: float64
70083 70090    17568.0
Name: new_cases, dtype: float64
70084 70091    18233.0
Name: new_cases, dtype: float64
70085 70092    15401.0
Name: new_cases, dtype: float64
70086 70093    16305.0
Name: new_cases, dtype: float64
70087 70094    15102.0
Name: new_cases, dtype: float64
70088 70095    10869.0
Name: new_cases, dtype: float64
70089 70096    13316.0
Name: new_cases, dtype: float64
70090 70097    13908.0
Name: new_cases, dtype: float64
70091 70098    18039.0
Name: new_cases, dtype: float64
70092 70099    19037.0
Name: new_cases, dtype: float64

70093 70100    10405.0
Name: new_cases, dtype: float64
70094 70101    8937.0
Name: new_cases, dtype: float64
70095 70102    8581.0
Name: new_cases, dtype: float64
70096 70103    11210.0
Name: new_cases, dtype: float64
70097 70104    16202.0
Name: new_cases, dtype: float64
70098 70105    23477.0
Name: new_cases, dtype: float64
70099 70106    22210.0
Name: new_cases, dtype: float64
70100 70107    11825.0
Name: new_cases, dtype: float64
70101 70108    14245.0
Name: new_cases, dtype: float64
70102 70109    10798.0
Name: new_cases, dtype: float64
70103 70110    15375.0
Name: new_cases, dtype: float64
70104 70111    20326.0
Name: new_cases, dtype: float64
70105 70112    18416.0
Name: new_cases, dtype: float64
70106 70113    17529.0
Name: new_cases, dtype: float64
70107 70114    19976.0
Name: new_cases, dtype: float64
70108 70115    18625.0
Name: new_cases, dtype: float64
70109 70116    12530.0
Name: new_cases, dtype: float64
70110 70117    14242.0
Name: new_cases, dtype: float64
70111 70118    15773.0
Name: new_cases, dtype: float64
70112 70119    17243.0
Name: new_cases, dtype: float64
70113 70120    16144.0
Name: new_cases, dtype: float64
70114 70121    16310.0
Name: new_cases, dtype: float64
70115 70122    12544.0
Name: new_cases, dtype: float64
70116 70123    8825.0
Name: new_cases, dtype: float64
70117 70124    10496.0
Name: new_cases, dtype: float64
70118 70125    13568.0
Name: new_cases, dtype: float64
70119 70126    14055.0
Name: new_cases, dtype: float64
70120 70127    13633.0
Name: new_cases, dtype: float64
70121 70128    13331.0
Name: new_cases, dtype: float64
70122 70129    11628.0
Name: new_cases, dtype: float64
70123 70130    8559.0
Name: new_cases, dtype: float64
70124 70131    10584.0
Name: new_cases, dtype: float64
70125 70132    15191.0
Name: new_cases, dtype: float64
70126 70133    14360.0
Name: new_cases, dtype: float64
70127 70134    13563.0
Name: new_cases, dtype: float64
70128 70135    12713.0
Name: new_cases, dtype: float64
70129 70136    11249.0
Name: new_cases, dtype: float64
70130 70137    7925.0
Name: new_cases, dtype: float64
70131 70138    9651.0
Name: new_cases, dtype: float64
70132 70139    13182.0
Name: new_cases, dtype: float64
70133 70140    13656.0
Name: new_cases, dtype: float64
70134 70141    14213.0
Name: new_cases, dtype: float64
70135 70142    13439.0
Name: new_cases, dtype: float64
70136 70143    11640.0
Name: new_cases, dtype: float64
70137 70144    7969.0
Name: new_cases, dtype: float64
70138 70145    10612.0
Name: new_cases, dtype: float64
70139 70146    12947.0
Name: new_cases, dtype: float64
70140 70147    15137.0
Name: new_cases, dtype: float64
70141 70148    13893.0
Name: new_cases, dtype: float64
70142 70149    13523.0
Name: new_cases, dtype: float64
70143 70150    11060.0
Name: new_cases, dtype: float64
70144 70151    7344.0
Name: new_cases, dtype: float64
70145 70152    10368.0
Name: new_cases, dtype: float64
70146 70153    12066.0
Name: new_cases, dtype: float64
70147 70154    13755.0
Name: new_cases, dtype: float64
70148 70155    15470.0
Name: new_cases, dtype: float64
70149 70156    14914.0
Name: new_cases, dtype: float64
70150 70157    13450.0
Name: new_cases, dtype: float64
70151 70158    9617.0
Name: new_cases, dtype: float64
70152 70159    13299.0
Name: new_cases, dtype: float64
70153 70160    16402.0
Name: new_cases, dtype: float64
70154 70161    19871.0
Name: new_cases, dtype: float64
70155 70162    20488.0
Name: new_cases, dtype: float64
70156 70163    18902.0
Name: new_cases, dtype: float64
70157 70164    17440.0
Name: new_cases, dtype: float64
70158 70165    13106.0
Name: new_cases, dtype: float64
70159 70166    17063.0
Name: new_cases, dtype: float64
70160 70167    20840.0
Name: new_cases, dtype: float64
70161 70168    22845.0
Name: new_cases, dtype: float64
70162 70169    24010.0
Name: new_cases, dtype: float64
70163 70170    23633.0
Name: new_cases, dtype: float64
70164 70171    20724.0
Name: new_cases, dtype: float64
70165 70172    13882.0
Name: new_cases, dtype: float64
70166 70173    19725.0
Name: new_cases, dtype: float64
70167 70174    22275.0
Name: new_cases, dtype: float64
70168 70175    25649.0
Name: new_cases, dtype: float64
70169 70176    26790.0
Name: new_cases, dtype: float64
70170 70177    26031.0
Name: new_cases, dtype: float64
70171 70178    21304.0
Name: new_cases, dtype: float64
70172 70179    15252.0
Name: new_cases, dtype: float64
70173 70180    20376.0
Name: new_cases, dtype: float64
70174 70181    23040.0
Name: new_cases, dtype: float64
70175 70182    24901.0
Name: new_cases, dtype: float64
70176 70183    25707.0
Name: new_cases, dtype: float64
70177 70184    23913.0
Name: new_cases, dtype: float64
70178 70185    20045.0
Name: new_cases, dtype: float64
70179 70186    24501.0
Name: new_cases, dtype: float64
70180 70187    18739.0
Name: new_cases, dtype: float64
70181 70188    21246.0
Name: new_cases, dtype: float64
70182 70189    23681.0
Name: new_cases, dtype: float64
70183 70190    24076.0
Name: new_cases, dtype: float64
70184 70191    23834.0
Name: new_cases, dtype: float64
70185 70192    19604.0
Name: new_cases, dtype: float64
70186 70193    12900.0
Name: new_cases, dtype: float64
70187 70194    16055.0
Name: new_cases, dtype: float64
70188 70195    23887.0
Name: new_cases, dtype: float64
70189 70196    22184.0
Name: new_cases, dtype: float64
70190 70197    21917.0
Name: new_cases, dtype: float64
70191 70198    21247.0
Name: new_cases, dtype: float64
70192 70199    18017.0
Name: new_cases, dtype: float64
70193 70200    10680.0
Name: new_cases, dtype: float64
70194 70201    7763.0
Name: new_cases, dtype: float64
70195 70202    13686.0
Name: new_cases, dtype: float64
70196 70203    17209.0
Name: new_cases, dtype: float64
70197 70204    18924.0
Name: new_cases, dtype: float64
70198 70205    17551.0
Name: new_cases, dtype: float64
70199 70206    15737.0
Name: new_cases, dtype: float64
70200 70207    9780.0
Name: new_cases, dtype: float64
70201 70208    13439.0
Name: new_cases, dtype: float64
70202 70209    16160.0
Name: new_cases, dtype: float64
70203 70210    16963.0
Name: new_cases, dtype: float64
70204 70211    15923.0
Name: new_cases, dtype: float64
70205 70212    15364.0
Name: new_cases, dtype: float64
70206 70213    12688.0
Name: new_cases, dtype: float64
70207 70214    8863.0
Name: new_cases, dtype: float64
70208 70215    12069.0
Name: new_cases, dtype: float64
70209 70216    13836.0
Name: new_cases, dtype: float64
70210 70217    16046.0
Name: new_cases, dtype: float64
70211 70218    14758.0
Name: new_cases, dtype: float64
70212 70219    13814.0
Name: new_cases, dtype: float64
70213 70220    13157.0
Name: new_cases, dtype: float64
70214 70221    8440.0
Name: new_cases, dtype: float64
70215 70222    10398.0
Name: new_cases, dtype: float64
70216 70223    13382.0
Name: new_cases, dtype: float64
70217 70224    14314.0
Name: new_cases, dtype: float64
70218 70225    13445.0
Name: new_cases, dtype: float64
70219 70226    12964.0
Name: new_cases, dtype: float64
70220 70227    9145.0
Name: new_cases, dtype: float64
70221 70228    5946.0
Name: new_cases, dtype: float64
70222 70229    9113.0
Name: new_cases, dtype: float64
70223 70230    10579.0
Name: new_cases, dtype: float64
70224 70231    11798.0
Name: new_cases, dtype: float64
70225 70232    10549.0
Name: new_cases, dtype: float64
70226 70233    10174.0
Name: new_cases, dtype: float64
70227 70234    8289.0
Name: new_cases, dtype: float64
70228 70235    5077.0
Name: new_cases, dtype: float64
70229 70236    6943.0
Name: new_cases, dtype: float64
70230 70237    7848.0
Name: new_cases, dtype: float64
70231 70238    8082.0
Name: new_cases, dtype: float64
70232 70239    7562.0
Name: new_cases, dtype: float64
70233 70240    6652.0
Name: new_cases, dtype: float64
70234 70241    5748.0
Name: new_cases, dtype: float64
70235 70242    3454.0
Name: new_cases, dtype: float64
70236 70243    4449.0
Name: new_cases, dtype: float64
70237 70244    5500.0
Name: new_cases, dtype: float64
70238 70245    5736.0
Name: new_cases, dtype: float64
70239 70246    5215.0
Name: new_cases, dtype: float64
70240 70247    4714.0
Name: new_cases, dtype: float64
70241 70248    3993.0
Name: new_cases, dtype: float64
70242 70249    2489.0
Name: new_cases, dtype: float64
70243 70250    3220.0
Name: new_cases, dtype: float64
70244 70251    3935.0
Name: new_cases, dtype: float64
70245 70252    4143.0
Name: new_cases, dtype: float64
70246 70253    3737.0
Name: new_cases, dtype: float64
70247 70254    3348.0
Name: new_cases, dtype: float64
70248 70255    2948.0
Name: new_cases, dtype: float64
70249 70256    1818.0
Name: new_cases, dtype: float64
70250 70257    2483.0
Name: new_cases, dtype: float64
70251 70258    2896.0
Name: new_cases, dtype: float64
70252 70259    1963.0
Name: new_cases, dtype: float64
70253 70260    2556.0
Name: new_cases, dtype: float64

70254 70261    2434.0
Name: new_cases, dtype: float64
70255 70262    2275.0
Name: new_cases, dtype: float64
70256 70263    1270.0
Name: new_cases, dtype: float64
70257 70264    1894.0
Name: new_cases, dtype: float64
70258 70265    2198.0
Name: new_cases, dtype: float64
70259 70266    2078.0
Name: new_cases, dtype: float64
70260 70267    1892.0
Name: new_cases, dtype: float64
70261 70268    1722.0
Name: new_cases, dtype: float64
70262 70269    1390.0
Name: new_cases, dtype: float64
70263 70270    907.0
Name: new_cases, dtype: float64
70264 70271    1253.0
Name: new_cases, dtype: float64
70265 70272    1400.0
Name: new_cases, dtype: float64
70266 70273    1323.0
Name: new_cases, dtype: float64
70267 70274    1147.0
Name: new_cases, dtype: float64
70268 70275    1193.0
Name: new_cases, dtype: float64
70269 70276    881.0
Name: new_cases, dtype: float64
70270 70277    484.0
Name: new_cases, dtype: float64
70271 70278    834.0
Name: new_cases, dtype: float64
70272 70279    1140.0
Name: new_cases, dtype: float64
70273 70280    266.0
Name: new_cases, dtype: float64
70274 70281    751.0
Name: new_cases, dtype: float64
70275 70282    838.0
Name: new_cases, dtype: float64
70276 70283    780.0
Name: new_cases, dtype: float64
70277 70284    387.0
Name: new_cases, dtype: float64
70278 70285    677.0
Name: new_cases, dtype: float64
70279 70286    776.0
Name: new_cases, dtype: float64
70280 70287    879.0
Name: new_cases, dtype: float64
70281 70288    794.0
Name: new_cases, dtype: float64
70282 70289    929.0
Name: new_cases, dtype: float64
70283 70290    806.0
Name: new_cases, dtype: float64
70284 70291    480.0
Name: new_cases, dtype: float64
70285 70292    907.0
Name: new_cases, dtype: float64
70286 70293    1010.0
Name: new_cases, dtype: float64
70287 70294    1391.0
Name: new_cases, dtype: float64
70288 70295    1386.0
Name: new_cases, dtype: float64
70289 70296    1394.0
Name: new_cases, dtype: float64
70290 70297    1391.0
Name: new_cases, dtype: float64
70291 70298    887.0
Name: new_cases, dtype: float64
70292 70299    1530.0
Name: new_cases, dtype: float64
70293 70300    2153.0
Name: new_cases, dtype: float64
70294 70301    2473.0
Name: new_cases, dtype: float64
70295 70302    2895.0
Name: new_cases, dtype: float64
70296 70303    3118.0
Name: new_cases, dtype: float64
70297 70304    3126.0
Name: new_cases, dtype: float64
70298 70305    2070.0
Name: new_cases, dtype: float64
70299 70306    3555.0
Name: new_cases, dtype: float64
70300 70307    4254.0
Name: new_cases, dtype: float64
70301 70308    5056.0
Name: new_cases, dtype: float64
70302 70309    5142.0
Name: new_cases, dtype: float64
70303 70310    5138.0
Name: new_cases, dtype: float64
70304 70311    4742.0
Name: new_cases, dtype: float64
70305 70312    3115.0
Name: new_cases, dtype: float64
70306 70313    4516.0
Name: new_cases, dtype: float64
70307 70314    5693.0
Name: new_cases, dtype: float64
70308 70315    6167.0
Name: new_cases, dtype: float64
70309 70316    6613.0
Name: new_cases, dtype: float64
70310 70317    6509.0
Name: new_cases, dtype: float64
70311 70318    5320.0
Name: new_cases, dtype: float64
70312 70319    3185.0
Name: new_cases, dtype: float64
70313 70320    4841.0
Name: new_cases, dtype: float64
70314 70321    6590.0
Name: new_cases, dtype: float64
70315 70322    7224.0
Name: new_cases, dtype: float64
70316 70323    6599.0
Name: new_cases, dtype: float64
70317 70324    6897.0
Name: new_cases, dtype: float64
70318 70325    5733.0
Name: new_cases, dtype: float64
70319 70326    4200.0
Name: new_cases, dtype: float64
70320 70327    5624.0
Name: new_cases, dtype: float64
70321 70328    6921.0
Name: new_cases, dtype: float64
70322 70329    7267.0
Name: new_cases, dtype: float64
70323 70330    7398.0
Name: new_cases, dtype: float64
70324 70331    7181.0
Name: new_cases, dtype: float64
70325 70332    5661.0
Name: new_cases, dtype: float64
70326 70333    3669.0
Name: new_cases, dtype: float64
70327 70334    5268.0
Name: new_cases, dtype: float64
70328 70335    7159.0
Name: new_cases, dtype: float64
70329 70336    7240.0
Name: new_cases, dtype: float64
70330 70337    7220.0
Name: new_cases, dtype: float64
70331 70338    7466.0
Name: new_cases, dtype: float64
70332 70339    5922.0
Name: new_cases, dtype: float64
70333 70340    4166.0
Name: new_cases, dtype: float64
70334 70341    6078.0
Name: new_cases, dtype: float64
70335 70342    7539.0
Name: new_cases, dtype: float64
70336 70343    7215.0
Name: new_cases, dtype: float64
70337 70344    7823.0
Name: new_cases, dtype: float64
70338 70345    6858.0
Name: new_cases, dtype: float64
70339 70346    5954.0
Name: new_cases, dtype: float64
70340 70347    4253.0
Name: new_cases, dtype: float64
70341 70348    5492.0
Name: new_cases, dtype: float64
70342 70349    6496.0
Name: new_cases, dtype: float64
70343 70350    6754.0
Name: new_cases, dtype: float64
70344 70351    6729.0
Name: new_cases, dtype: float64
70345 70352    6156.0
Name: new_cases, dtype: float64
70346 70353    5314.0
Name: new_cases, dtype: float64
70347 70354    3347.0
Name: new_cases, dtype: float64
70348 70355    4715.0
Name: new_cases, dtype: float64
70349 70356    5921.0
Name: new_cases, dtype: float64
70350 70357    5518.0
Name: new_cases, dtype: float64
70351 70358    5617.0
Name: new_cases, dtype: float64
70352 70359    5191.0
Name: new_cases, dtype: float64
70353 70360    4664.0
Name: new_cases, dtype: float64
70354 70361    2792.0
Name: new_cases, dtype: float64
70355 70362    4009.0
Name: new_cases, dtype: float64
70356 70363    4826.0
Name: new_cases, dtype: float64
70357 70364    5115.0
Name: new_cases, dtype: float64
70358 70365    4544.0
Name: new_cases, dtype: float64
70359 70366    4576.0
Name: new_cases, dtype: float64
70360 70367    3836.0
Name: new_cases, dtype: float64
70361 70368    2405.0
Name: new_cases, dtype: float64
70362 70369    3374.0
Name: new_cases, dtype: float64
70363 70370    3963.0
Name: new_cases, dtype: float64
70364 70371    4053.0
Name: new_cases, dtype: float64
70365 70372    3790.0
Name: new_cases, dtype: float64
70366 70373    3519.0
Name: new_cases, dtype: float64
70367 70374    3099.0
Name: new_cases, dtype: float64
70368 70375    1773.0
Name: new_cases, dtype: float64
70369 70376    2962.0
Name: new_cases, dtype: float64
70370 70377    3212.0
Name: new_cases, dtype: float64
70371 70378    4094.0
Name: new_cases, dtype: float64
70372 70379    3403.0
Name: new_cases, dtype: float64
70373 70380    3309.0
Name: new_cases, dtype: float64
70374 70381    2967.0
Name: new_cases, dtype: float64
70375 70382    1612.0
Name: new_cases, dtype: float64
70376 70383    2463.0
Name: new_cases, dtype: float64
70377 70384    3232.0
Name: new_cases, dtype: float64
70378 70385    2933.0
Name: new_cases, dtype: float64
70379 70386    3017.0
Name: new_cases, dtype: float64
70380 70387    2747.0
Name: new_cases, dtype: float64
70381 70388    2278.0
Name: new_cases, dtype: float64
70382 70389    1516.0
Name: new_cases, dtype: float64
70383 70390    2486.0
Name: new_cases, dtype: float64
70384 70391    2769.0
Name: new_cases, dtype: float64
70385 70392    2666.0
Name: new_cases, dtype: float64
70386 70393    2729.0
Name: new_cases, dtype: float64
70387 70394    2982.0
Name: new_cases, dtype: float64
70388 70395    2435.0
Name: new_cases, dtype: float64
70389 70396    1594.0
Name: new_cases, dtype: float64
70390 70397    2695.0
Name: new_cases, dtype: float64
70391 70398    3699.0
Name: new_cases, dtype: float64
70392 70399    3791.0
Name: new_cases, dtype: float64
70393 70400    3879.0
Name: new_cases, dtype: float64
70394 70401    3905.0
Name: new_cases, dtype: float64
70395 70402    3723.0
Name: new_cases, dtype: float64
70396 70403    2535.0
Name: new_cases, dtype: float64
70397 70404    4053.0
Name: new_cases, dtype: float64
70398 70405    4595.0
Name: new_cases, dtype: float64
70399 70406    4863.0
Name: new_cases, dtype: float64
70400 70407    5332.0
Name: new_cases, dtype: float64
70401 70408    4877.0
Name: new_cases, dtype: float64
70402 70409    4525.0
Name: new_cases, dtype: float64
70403 70410    2818.0
Name: new_cases, dtype: float64
70404 70411    2831.0
Name: new_cases, dtype: float64
70405 70412    5188.0
Name: new_cases, dtype: float64
70406 70413    5902.0
Name: new_cases, dtype: float64
70407 70414    6761.0
Name: new_cases, dtype: float64
70408 70415    6760.0
Name: new_cases, dtype: float64
70409 70416    5822.0
Name: new_cases, dtype: float64
70410 70417    4547.0
Name: new_cases, dtype: float64
70411 70418    6111.0
Name: new_cases, dtype: float64
70412 70419    8033.0
Name: new_cases, dtype: float64
70413 70420    8697.0
Name: new_cases, dtype: float64
70414 70421    8522.0
Name: new_cases, dtype: float64
70415 70422    8539.0
Name: new_cases, dtype: float64
70416 70423    7565.0
Name: new_cases, dtype: float64
70417 70424    5199.0
Name: new_cases, dtype: float64
70418 70425    7815.0
Name: new_cases, dtype: float64
70419 70426    10167.0
Name: new_cases, dtype: float64
70420 70427    10645.0
Name: new_cases, dtype: float64

70421 70428    10554.0
Name: new_cases, dtype: float64
70422 70429    11540.0
Name: new_cases, dtype: float64
70423 70430    9707.0
Name: new_cases, dtype: float64
70424 70431    6403.0
Name: new_cases, dtype: float64
70425 70432    10044.0
Name: new_cases, dtype: float64
70426 70433    12450.0
Name: new_cases, dtype: float64
70427 70434    13756.0
Name: new_cases, dtype: float64
70428 70435    13681.0
Name: new_cases, dtype: float64
70429 70436    12869.0
Name: new_cases, dtype: float64
70430 70437    12927.0
Name: new_cases, dtype: float64
70431 70438    7972.0
Name: new_cases, dtype: float64
70432 70439    12757.0
Name: new_cases, dtype: float64
70433 70440    15073.0
Name: new_cases, dtype: float64
70434 70441    16810.0
Name: new_cases, dtype: float64
70435 70442    17015.0
Name: new_cases, dtype: float64
70436 70443    16627.0
Name: new_cases, dtype: float64
70437 70444    15010.0
Name: new_cases, dtype: float64
70438 70445    9494.0
Name: new_cases, dtype: float64
70439 70446    15742.0
Name: new_cases, dtype: float64
70440 70447    17946.0
Name: new_cases, dtype: float64
70441 70448    12516.0
Name: new_cases, dtype: float64
70442 70449    20490.0
Name: new_cases, dtype: float64
70443 70450    21035.0
Name: new_cases, dtype: float64
70444 70451    19212.0
Name: new_cases, dtype: float64
70445 70452    12704.0
Name: new_cases, dtype: float64
70446 70453    20665.0
Name: new_cases, dtype: float64
70447 70454    23190.0
Name: new_cases, dtype: float64
70448 70455    26104.0
Name: new_cases, dtype: float64
70449 70456    28615.0
Name: new_cases, dtype: float64
70450 70457    28057.0
Name: new_cases, dtype: float64
70451 70458    24303.0
Name: new_cases, dtype: float64
70452 70459    16205.0
Name: new_cases, dtype: float64
70453 70460    30783.0
Name: new_cases, dtype: float64
70454 70461    36326.0
Name: new_cases, dtype: float64
70455 70462    44585.0
Name: new_cases, dtype: float64
70456 70463    50590.0
Name: new_cases, dtype: float64
70457 70464    54787.0
Name: new_cases, dtype: float64
70458 70465    24882.0
Name: new_cases, dtype: float64
70459 70466    30799.0
Name: new_cases, dtype: float64
70460 70467    78300.0
Name: new_cases, dtype: float64
70461 70468    98016.0
Name: new_cases, dtype: float64
70462 70469    127000.0
Name: new_cases, dtype: float64
70463 70470    144255.0
Name: new_cases, dtype: float64
70464 70471    141256.0
Name: new_cases, dtype: float64
70465 70472    61137.0
Name: new_cases, dtype: float64
70466 70473    68034.0
Name: new_cases, dtype: float64
70467 70474    170837.0
Name: new_cases, dtype: float64
70468 70475    189088.0
Name: new_cases, dtype: float64
70469 70476    219430.0
Name: new_cases, dtype: float64
70470 70477    108297.0
Name: new_cases, dtype: float64
70471 70478    197535.0
Name: new_cases, dtype: float64
70472 Series([], Name: new_cases, dtype: float64)
70473 Series([], Name: new_cases, dtype: float64)
70474 Series([], Name: new_cases, dtype: float64)
70475 Series([], Name: new_cases, dtype: float64)
70476 Series([], Name: new_cases, dtype: float64)
70477 Series([], Name: new_cases, dtype: float64)
70478 Series([], Name: new_cases, dtype: float64)
71149 71156    4.0
Name: new_cases, dtype: float64
71150 71157    4.0
Name: new_cases, dtype: float64
71151 71158    5.0
Name: new_cases, dtype: float64
71152 71159    0.0
Name: new_cases, dtype: float64
71153 71160    0.0
Name: new_cases, dtype: float64
71154 71161    2.0
Name: new_cases, dtype: float64
71155 71162    1.0
Name: new_cases, dtype: float64
71156 71163    0.0
Name: new_cases, dtype: float64
71157 71164    0.0
Name: new_cases, dtype: float64
71158 71165    1.0
Name: new_cases, dtype: float64
71159 71166    0.0
Name: new_cases, dtype: float64
71160 71167    2.0
Name: new_cases, dtype: float64
71161 71168    1.0
Name: new_cases, dtype: float64
71162 71169    1.0
Name: new_cases, dtype: float64
71163 71170    5.0
Name: new_cases, dtype: float64
71164 71171    10.0
Name: new_cases, dtype: float64
71165 71172    11.0
Name: new_cases, dtype: float64
71166 71173    6.0
Name: new_cases, dtype: float64
71167 71174    7.0
Name: new_cases, dtype: float64
71168 71175    12.0
Name: new_cases, dtype: float64
71169 71176    6.0
Name: new_cases, dtype: float64
71170 71177    10.0
Name: new_cases, dtype: float64
71171 71178    17.0
Name: new_cases, dtype: float64
71172 71179    25.0
Name: new_cases, dtype: float64
71173 71180    12.0
Name: new_cases, dtype: float64
71174 71181    11.0
Name: new_cases, dtype: float64
71175 71182    13.0
Name: new_cases, dtype: float64
71176 71183    19.0
Name: new_cases, dtype: float64
71177 71184    26.0
Name: new_cases, dtype: float64
71178 71185    18.0
Name: new_cases, dtype: float64
71179 71186    9.0
Name: new_cases, dtype: float64
71180 71187    14.0
Name: new_cases, dtype: float64
71181 71188    19.0
Name: new_cases, dtype: float64
71182 71189    20.0
Name: new_cases, dtype: float64
71183 71190    35.0
Name: new_cases, dtype: float64
71184 71191    32.0
Name: new_cases, dtype: float64
71185 71192    55.0
Name: new_cases, dtype: float64
71186 71193    46.0
Name: new_cases, dtype: float64
71187 71194    33.0
Name: new_cases, dtype: float64
71188 71195    28.0
Name: new_cases, dtype: float64
71189 71196    58.0
Name: new_cases, dtype: float64
71190 71197    55.0
Name: new_cases, dtype: float64
71191 71198    56.0
Name: new_cases, dtype: float64
71192 71199    37.0
Name: new_cases, dtype: float64
71193 71200    62.0
Name: new_cases, dtype: float64
71194 71201    31.0
Name: new_cases, dtype: float64
71195 71202    17.0
Name: new_cases, dtype: float64
71196 71203    50.0
Name: new_cases, dtype: float64
71197 71204    35.0
Name: new_cases, dtype: float64
71198 71205    40.0
Name: new_cases, dtype: float64
71199 71206    54.0
Name: new_cases, dtype: float64
71200 71207    37.0
Name: new_cases, dtype: float64
71201 71208    45.0
Name: new_cases, dtype: float64
71202 71209    40.0
Name: new_cases, dtype: float64
71203 71210    73.0
Name: new_cases, dtype: float64
71204 71211    97.0
Name: new_cases, dtype: float64
71205 71212    102.0
Name: new_cases, dtype: float64
71206 71213    114.0
Name: new_cases, dtype: float64
71207 71214    198.0
Name: new_cases, dtype: float64
71208 71215    179.0
Name: new_cases, dtype: float64
71209 71216    94.0
Name: new_cases, dtype: float64
71210 71217    254.0
Name: new_cases, dtype: float64
71211 71218    280.0
Name: new_cases, dtype: float64
71212 71219    283.0
Name: new_cases, dtype: float64
71213 71220    336.0
Name: new_cases, dtype: float64
71214 71221    371.0
Name: new_cases, dtype: float64
71215 71222    351.0
Name: new_cases, dtype: float64
71216 71223    234.0
Name: new_cases, dtype: float64
71217 71224    375.0
Name: new_cases, dtype: float64
71218 71225    535.0
Name: new_cases, dtype: float64
71219 71226    594.0
Name: new_cases, dtype: float64
71220 71227    636.0
Name: new_cases, dtype: float64
71221 71228    701.0
Name: new_cases, dtype: float64
71222 71229    522.0
Name: new_cases, dtype: float64
71223 71230    300.0
Name: new_cases, dtype: float64
71224 71231    504.0
Name: new_cases, dtype: float64
71225 71232    558.0
Name: new_cases, dtype: float64
71226 71233    563.0
Name: new_cases, dtype: float64
71227 71234    560.0
Name: new_cases, dtype: float64
71228 71235    590.0
Name: new_cases, dtype: float64
71229 71236    366.0
Name: new_cases, dtype: float64
71230 71237    344.0
Name: new_cases, dtype: float64
71231 71238    383.0
Name: new_cases, dtype: float64
71232 71239    396.0
Name: new_cases, dtype: float64
71233 71240    432.0
Name: new_cases, dtype: float64
71234 71241    385.0
Name: new_cases, dtype: float64
71235 71242    332.0
Name: new_cases, dtype: float64
71236 71243    219.0
Name: new_cases, dtype: float64
71237 71244    171.0
Name: new_cases, dtype: float64
71238 71245    284.0
Name: new_cases, dtype: float64
71239 71246    216.0
Name: new_cases, dtype: float64
71240 71247    208.0
Name: new_cases, dtype: float64
71241 71248    274.0
Name: new_cases, dtype: float64
71242 71249    303.0
Name: new_cases, dtype: float64
71243 71250    200.0
Name: new_cases, dtype: float64
71244 71251    168.0
Name: new_cases, dtype: float64
71245 71252    125.0
Name: new_cases, dtype: float64
71246 71253    101.0
Name: new_cases, dtype: float64
71247 71254    98.0
Name: new_cases, dtype: float64
71248 71255    87.0
Name: new_cases, dtype: float64
71249 71256    115.0
Name: new_cases, dtype: float64
71250 71257    69.0
Name: new_cases, dtype: float64
71251 71258    37.0
Name: new_cases, dtype: float64
71252 71259    87.0
Name: new_cases, dtype: float64
71253 71260    50.0
Name: new_cases, dtype: float64
71254 71261    98.0
Name: new_cases, dtype: float64
71255 71262    52.0
Name: new_cases, dtype: float64
71256 71263    54.0
Name: new_cases, dtype: float64
71257 71264    24.0
Name: new_cases, dtype: float64
71258 71265    33.0
Name: new_cases, dtype: float64
71259 71266    28.0
Name: new_cases, dtype: float64
71260 71267    34.0
Name: new_cases, dtype: float64
71261 71268    41.0
Name: new_cases, dtype: float64
71262 71269    23.0
Name: new_cases, dtype: float64
71263 71270    25.0
Name: new_cases, dtype: float64
71264 71271    41.0
Name: new_cases, dtype: float64
71265 71272    21.0
Name: new_cases, dtype: float64
71266 71273    30.0
Name: new_cases, dtype: float64

71267 71274    26.0
Name: new_cases, dtype: float64
71268 71275    60.0
Name: new_cases, dtype: float64
71269 71276    73.0
Name: new_cases, dtype: float64
71270 71277    45.0
Name: new_cases, dtype: float64
71271 71278    35.0
Name: new_cases, dtype: float64
71272 71279    37.0
Name: new_cases, dtype: float64
71273 71280    51.0
Name: new_cases, dtype: float64
71274 71281    29.0
Name: new_cases, dtype: float64
71275 71282    44.0
Name: new_cases, dtype: float64
71276 71283    47.0
Name: new_cases, dtype: float64
71277 71284    46.0
Name: new_cases, dtype: float64
71278 71285    38.0
Name: new_cases, dtype: float64
71279 71286    21.0
Name: new_cases, dtype: float64
71280 71287    45.0
Name: new_cases, dtype: float64
71281 71288    36.0
Name: new_cases, dtype: float64
71282 71289    44.0
Name: new_cases, dtype: float64
71283 71290    61.0
Name: new_cases, dtype: float64
71284 71291    45.0
Name: new_cases, dtype: float64
71285 71292    75.0
Name: new_cases, dtype: float64
71286 71293    72.0
Name: new_cases, dtype: float64
71287 71294    42.0
Name: new_cases, dtype: float64
71288 71295    46.0
Name: new_cases, dtype: float64
71289 71296    69.0
Name: new_cases, dtype: float64
71290 71297    61.0
Name: new_cases, dtype: float64
71291 71298    64.0
Name: new_cases, dtype: float64
71292 71299    55.0
Name: new_cases, dtype: float64
71293 71300    43.0
Name: new_cases, dtype: float64
71294 71301    57.0
Name: new_cases, dtype: float64
71295 71302    96.0
Name: new_cases, dtype: float64
71296 71303    82.0
Name: new_cases, dtype: float64
71297 71304    105.0
Name: new_cases, dtype: float64
71298 71305    92.0
Name: new_cases, dtype: float64
71299 71306    113.0
Name: new_cases, dtype: float64
71300 71307    110.0
Name: new_cases, dtype: float64
71301 71308    138.0
Name: new_cases, dtype: float64
71302 71309    127.0
Name: new_cases, dtype: float64
71303 71310    194.0
Name: new_cases, dtype: float64
71304 71311    250.0
Name: new_cases, dtype: float64
71305 71312    274.0
Name: new_cases, dtype: float64
71306 71313    208.0
Name: new_cases, dtype: float64
71307 71314    176.0
Name: new_cases, dtype: float64
71308 71315    208.0
Name: new_cases, dtype: float64
71309 71316    207.0
Name: new_cases, dtype: float64
71310 71317    355.0
Name: new_cases, dtype: float64
71311 71318    430.0
Name: new_cases, dtype: float64
71312 71319    386.0
Name: new_cases, dtype: float64
71313 71320    407.0
Name: new_cases, dtype: float64
71314 71321    259.0
Name: new_cases, dtype: float64
71315 71322    333.0
Name: new_cases, dtype: float64
71316 71323    450.0
Name: new_cases, dtype: float64
71317 71324    624.0
Name: new_cases, dtype: float64
71318 71325    597.0
Name: new_cases, dtype: float64
71319 71326    661.0
Name: new_cases, dtype: float64
71320 71327    511.0
Name: new_cases, dtype: float64
71321 71328    418.0
Name: new_cases, dtype: float64
71322 71329    632.0
Name: new_cases, dtype: float64
71323 71330    795.0
Name: new_cases, dtype: float64
71324 71331    981.0
Name: new_cases, dtype: float64
71325 71332    779.0
Name: new_cases, dtype: float64
71326 71333    801.0
Name: new_cases, dtype: float64
71327 71334    839.0
Name: new_cases, dtype: float64
71328 71335    600.0
Name: new_cases, dtype: float64
71329 71336    985.0
Name: new_cases, dtype: float64
71330 71337    1270.0
Name: new_cases, dtype: float64
71331 71338    1308.0
Name: new_cases, dtype: float64
71332 71339    1586.0
Name: new_cases, dtype: float64
71333 71340    1534.0
Name: new_cases, dtype: float64
71334 71341    1331.0
Name: new_cases, dtype: float64
71335 71342    965.0
Name: new_cases, dtype: float64
71336 71343    1246.0
Name: new_cases, dtype: float64
71337 71344    1355.0
Name: new_cases, dtype: float64
71338 71345    1485.0
Name: new_cases, dtype: float64
71339 71346    1605.0
Name: new_cases, dtype: float64
71340 71347    1571.0
Name: new_cases, dtype: float64
71341 71348    1441.0
Name: new_cases, dtype: float64
71342 71349    838.0
Name: new_cases, dtype: float64
71343 71350    697.0
Name: new_cases, dtype: float64
71344 71351    979.0
Name: new_cases, dtype: float64
71345 71352    1172.0
Name: new_cases, dtype: float64
71346 71353    1356.0
Name: new_cases, dtype: float64
71347 71354    1231.0
Name: new_cases, dtype: float64
71348 71355    1017.0
Name: new_cases, dtype: float64
71349 71356    647.0
Name: new_cases, dtype: float64
71350 71357    916.0
Name: new_cases, dtype: float64
71351 71358    1070.0
Name: new_cases, dtype: float64
71352 71359    1178.0
Name: new_cases, dtype: float64
71353 71360    1037.0
Name: new_cases, dtype: float64
71354 71361    984.0
Name: new_cases, dtype: float64
71355 71362    744.0
Name: new_cases, dtype: float64
71356 71363    493.0
Name: new_cases, dtype: float64
71357 71364    715.0
Name: new_cases, dtype: float64
71358 71365    903.0
Name: new_cases, dtype: float64
71359 71366    863.0
Name: new_cases, dtype: float64
71360 71367    876.0
Name: new_cases, dtype: float64
71361 71368    844.0
Name: new_cases, dtype: float64
71362 71369    600.0
Name: new_cases, dtype: float64
71363 71370    436.0
Name: new_cases, dtype: float64
71364 71371    633.0
Name: new_cases, dtype: float64
71365 71372    592.0
Name: new_cases, dtype: float64
71366 71373    657.0
Name: new_cases, dtype: float64
71367 71374    587.0
Name: new_cases, dtype: float64
71368 71375    598.0
Name: new_cases, dtype: float64
71369 71376    451.0
Name: new_cases, dtype: float64
71370 71377    291.0
Name: new_cases, dtype: float64
71371 71378    509.0
Name: new_cases, dtype: float64
71372 71379    508.0
Name: new_cases, dtype: float64
71373 71380    712.0
Name: new_cases, dtype: float64
71374 71381    642.0
Name: new_cases, dtype: float64
71375 71382    646.0
Name: new_cases, dtype: float64
71376 71383    439.0
Name: new_cases, dtype: float64
71377 71384    266.0
Name: new_cases, dtype: float64
71378 71385    531.0
Name: new_cases, dtype: float64
71379 71386    551.0
Name: new_cases, dtype: float64
71380 71387    489.0
Name: new_cases, dtype: float64
71381 71388    572.0
Name: new_cases, dtype: float64
71382 71389    596.0
Name: new_cases, dtype: float64
71383 71390    480.0
Name: new_cases, dtype: float64
71384 71391    310.0
Name: new_cases, dtype: float64
71385 71392    331.0
Name: new_cases, dtype: float64
71386 71393    219.0
Name: new_cases, dtype: float64
71387 71394    482.0
Name: new_cases, dtype: float64
71388 71395    573.0
Name: new_cases, dtype: float64
71389 71396    639.0
Name: new_cases, dtype: float64
71390 71397    485.0
Name: new_cases, dtype: float64
71391 71398    302.0
Name: new_cases, dtype: float64
71392 71399    527.0
Name: new_cases, dtype: float64
71393 71400    576.0
Name: new_cases, dtype: float64
71394 71401    633.0
Name: new_cases, dtype: float64
71395 71402    542.0
Name: new_cases, dtype: float64
71396 71403    574.0
Name: new_cases, dtype: float64
71397 71404    400.0
Name: new_cases, dtype: float64
71398 71405    279.0
Name: new_cases, dtype: float64
71399 71406    500.0
Name: new_cases, dtype: float64
71400 71407    506.0
Name: new_cases, dtype: float64
71401 71408    627.0
Name: new_cases, dtype: float64
71402 71409    603.0
Name: new_cases, dtype: float64
71403 71410    678.0
Name: new_cases, dtype: float64
71404 71411    436.0
Name: new_cases, dtype: float64
71405 71412    278.0
Name: new_cases, dtype: float64
71406 71413    498.0
Name: new_cases, dtype: float64
71407 71414    552.0
Name: new_cases, dtype: float64
71408 71415    708.0
Name: new_cases, dtype: float64
71409 71416    639.0
Name: new_cases, dtype: float64
71410 71417    623.0
Name: new_cases, dtype: float64
71411 71418    430.0
Name: new_cases, dtype: float64
71412 71419    316.0
Name: new_cases, dtype: float64
71413 71420    481.0
Name: new_cases, dtype: float64
71414 71421    615.0
Name: new_cases, dtype: float64
71415 71422    616.0
Name: new_cases, dtype: float64
71416 71423    745.0
Name: new_cases, dtype: float64
71417 71424    726.0
Name: new_cases, dtype: float64
71418 71425    493.0
Name: new_cases, dtype: float64
71419 71426    410.0
Name: new_cases, dtype: float64
71420 71427    646.0
Name: new_cases, dtype: float64
71421 71428    731.0
Name: new_cases, dtype: float64
71422 71429    808.0
Name: new_cases, dtype: float64
71423 71430    774.0
Name: new_cases, dtype: float64
71424 71431    877.0
Name: new_cases, dtype: float64
71425 71432    613.0
Name: new_cases, dtype: float64

71426 71433    487.0
Name: new_cases, dtype: float64
71427 71434    865.0
Name: new_cases, dtype: float64
71428 71435    624.0
Name: new_cases, dtype: float64
71429 71436    1048.0
Name: new_cases, dtype: float64
71430 71437    1143.0
Name: new_cases, dtype: float64
71431 71438    1333.0
Name: new_cases, dtype: float64
71432 71439    950.0
Name: new_cases, dtype: float64
71433 71440    780.0
Name: new_cases, dtype: float64
71434 71441    1283.0
Name: new_cases, dtype: float64
71435 71442    1544.0
Name: new_cases, dtype: float64
71436 71443    1659.0
Name: new_cases, dtype: float64
71437 71444    1704.0
Name: new_cases, dtype: float64
71438 71445    1735.0
Name: new_cases, dtype: float64
71439 71446    1439.0
Name: new_cases, dtype: float64
71440 71447    950.0
Name: new_cases, dtype: float64
71441 71448    1700.0
Name: new_cases, dtype: float64
71442 71449    2194.0
Name: new_cases, dtype: float64
71443 71450    2385.0
Name: new_cases, dtype: float64
71444 71451    2421.0
Name: new_cases, dtype: float64
71445 71452    2592.0
Name: new_cases, dtype: float64
71446 71453    2159.0
Name: new_cases, dtype: float64
71447 71454    1518.0
Name: new_cases, dtype: float64
71448 71455    1229.0
Name: new_cases, dtype: float64
71449 71456    1942.0
Name: new_cases, dtype: float64
71450 71457    2500.0
Name: new_cases, dtype: float64
71451 71458    2531.0
Name: new_cases, dtype: float64
71452 71459    2675.0
Name: new_cases, dtype: float64
71453 71460    2062.0
Name: new_cases, dtype: float64
71454 71461    1436.0
Name: new_cases, dtype: float64
71455 71462    2033.0
Name: new_cases, dtype: float64
71456 71463    2432.0
Name: new_cases, dtype: float64
71457 71464    2517.0
Name: new_cases, dtype: float64
71458 71465    2452.0
Name: new_cases, dtype: float64
71459 71466    2508.0
Name: new_cases, dtype: float64
71460 71467    2038.0
Name: new_cases, dtype: float64
71461 71468    1531.0
Name: new_cases, dtype: float64
71462 71469    2176.0
Name: new_cases, dtype: float64
71463 71470    2810.0
Name: new_cases, dtype: float64
71464 71471    2969.0
Name: new_cases, dtype: float64
71465 71472    2795.0
Name: new_cases, dtype: float64
71466 71473    3037.0
Name: new_cases, dtype: float64
71467 71474    2383.0
Name: new_cases, dtype: float64
71468 71475    1681.0
Name: new_cases, dtype: float64
71469 71476    2426.0
Name: new_cases, dtype: float64
71470 71477    2996.0
Name: new_cases, dtype: float64
71471 71478    3209.0
Name: new_cases, dtype: float64
71472 71479    2837.0
Name: new_cases, dtype: float64
71473 71480    2989.0
Name: new_cases, dtype: float64
71474 71481    2491.0
Name: new_cases, dtype: float64
71475 71482    1811.0
Name: new_cases, dtype: float64
71476 71483    2694.0
Name: new_cases, dtype: float64
71477 71484    3276.0
Name: new_cases, dtype: float64
71478 71485    3746.0
Name: new_cases, dtype: float64
71479 71486    3832.0
Name: new_cases, dtype: float64
71480 71487    3885.0
Name: new_cases, dtype: float64
71481 71488    2944.0
Name: new_cases, dtype: float64
71482 71489    2397.0
Name: new_cases, dtype: float64
71483 71490    3627.0
Name: new_cases, dtype: float64
71484 71491    3871.0
Name: new_cases, dtype: float64
71485 71492    4532.0
Name: new_cases, dtype: float64
71486 71493    3256.0
Name: new_cases, dtype: float64
71487 71494    3071.0
Name: new_cases, dtype: float64
71488 71495    3166.0
Name: new_cases, dtype: float64
71489 71496    3343.0
Name: new_cases, dtype: float64
71490 71497    4949.0
Name: new_cases, dtype: float64
71491 71498    6049.0
Name: new_cases, dtype: float64
71492 71499    7642.0
Name: new_cases, dtype: float64
71493 71500    7957.0
Name: new_cases, dtype: float64
71494 71501    7854.0
Name: new_cases, dtype: float64
71495 71502    6108.0
Name: new_cases, dtype: float64
71496 71503    4906.0
Name: new_cases, dtype: float64
71497 71504    4597.0
Name: new_cases, dtype: float64
71498 71505    5917.0
Name: new_cases, dtype: float64
71499 71506    6656.0
Name: new_cases, dtype: float64
71500 71507    7173.0
Name: new_cases, dtype: float64
71501 71508    7042.0
Name: new_cases, dtype: float64
71502 71509    5760.0
Name: new_cases, dtype: float64
71503 71510    4937.0
Name: new_cases, dtype: float64
71504 71511    5335.0
Name: new_cases, dtype: float64
71505 71512    5562.0
Name: new_cases, dtype: float64
71506 71513    5664.0
Name: new_cases, dtype: float64
71507 71514    5057.0
Name: new_cases, dtype: float64
71508 71515    4726.0
Name: new_cases, dtype: float64
71509 71516    3990.0
Name: new_cases, dtype: float64
71510 71517    2763.0
Name: new_cases, dtype: float64
71511 71518    3853.0
Name: new_cases, dtype: float64
71512 71519    3974.0
Name: new_cases, dtype: float64
71513 71520    4131.0
Name: new_cases, dtype: float64
71514 71521    3538.0
Name: new_cases, dtype: float64
71515 71522    3342.0
Name: new_cases, dtype: float64
71516 71523    2673.0
Name: new_cases, dtype: float64
71517 71524    1793.0
Name: new_cases, dtype: float64
71518 71525    2324.0
Name: new_cases, dtype: float64
71519 71526    2634.0
Name: new_cases, dtype: float64
71520 71527    2578.0
Name: new_cases, dtype: float64
71521 71528    2370.0
Name: new_cases, dtype: float64
71522 71529    2277.0
Name: new_cases, dtype: float64
71523 71530    1630.0
Name: new_cases, dtype: float64
71524 71531    1217.0
Name: new_cases, dtype: float64
71525 71532    1568.0
Name: new_cases, dtype: float64
71526 71533    1886.0
Name: new_cases, dtype: float64
71527 71534    1690.0
Name: new_cases, dtype: float64
71528 71535    1300.0
Name: new_cases, dtype: float64
71529 71536    1360.0
Name: new_cases, dtype: float64
71530 71537    1362.0
Name: new_cases, dtype: float64
71531 71538    965.0
Name: new_cases, dtype: float64
71532 71539    1308.0
Name: new_cases, dtype: float64
71533 71540    1448.0
Name: new_cases, dtype: float64
71534 71541    1536.0
Name: new_cases, dtype: float64
71535 71542    1301.0
Name: new_cases, dtype: float64
71536 71543    1233.0
Name: new_cases, dtype: float64
71537 71544    1032.0
Name: new_cases, dtype: float64
71538 71545    740.0
Name: new_cases, dtype: float64
71539 71546    1081.0
Name: new_cases, dtype: float64
71540 71547    921.0
Name: new_cases, dtype: float64
71541 71548    1076.0
Name: new_cases, dtype: float64
71542 71549    1054.0
Name: new_cases, dtype: float64
71543 71550    1213.0
Name: new_cases, dtype: float64
71544 71551    999.0
Name: new_cases, dtype: float64
71545 71552    698.0
Name: new_cases, dtype: float64
71546 71553    888.0
Name: new_cases, dtype: float64
71547 71554    1243.0
Name: new_cases, dtype: float64
71548 71555    1169.0
Name: new_cases, dtype: float64
71549 71556    1148.0
Name: new_cases, dtype: float64
71550 71557    1043.0
Name: new_cases, dtype: float64
71551 71558    1071.0
Name: new_cases, dtype: float64
71552 71559    600.0
Name: new_cases, dtype: float64
71553 71560    1127.0
Name: new_cases, dtype: float64
71554 71561    1313.0
Name: new_cases, dtype: float64
71555 71562    1317.0
Name: new_cases, dtype: float64
71556 71563    1271.0
Name: new_cases, dtype: float64
71557 71564    1319.0
Name: new_cases, dtype: float64
71558 71565    987.0
Name: new_cases, dtype: float64
71559 71566    695.0
Name: new_cases, dtype: float64
71560 71567    1133.0
Name: new_cases, dtype: float64
71561 71568    1533.0
Name: new_cases, dtype: float64
71562 71569    1497.0
Name: new_cases, dtype: float64
71563 71570    1463.0
Name: new_cases, dtype: float64
71564 71571    1516.0
Name: new_cases, dtype: float64
71565 71572    1118.0
Name: new_cases, dtype: float64
71566 71573    816.0
Name: new_cases, dtype: float64
71567 71574    1500.0
Name: new_cases, dtype: float64
71568 71575    1917.0
Name: new_cases, dtype: float64
71569 71576    1915.0
Name: new_cases, dtype: float64
71570 71577    2025.0
Name: new_cases, dtype: float64
71571 71578    2071.0
Name: new_cases, dtype: float64
71572 71579    1782.0
Name: new_cases, dtype: float64
71573 71580    1345.0
Name: new_cases, dtype: float64
71574 71581    2087.0
Name: new_cases, dtype: float64
71575 71582    2843.0
Name: new_cases, dtype: float64
71576 71583    2605.0
Name: new_cases, dtype: float64
71577 71584    2754.0
Name: new_cases, dtype: float64
71578 71585    2772.0
Name: new_cases, dtype: float64
71579 71586    2467.0
Name: new_cases, dtype: float64
71580 71587    1571.0
Name: new_cases, dtype: float64
71581 71588    2666.0
Name: new_cases, dtype: float64
71582 71589    3448.0
Name: new_cases, dtype: float64
71583 71590    3496.0
Name: new_cases, dtype: float64
71584 71591    3488.0
Name: new_cases, dtype: float64
71585 71592    3765.0
Name: new_cases, dtype: float64

71586 71593    2836.0
Name: new_cases, dtype: float64
71587 71594    2104.0
Name: new_cases, dtype: float64
71588 71595    3452.0
Name: new_cases, dtype: float64
71589 71596    4307.0
Name: new_cases, dtype: float64
71590 71597    4569.0
Name: new_cases, dtype: float64
71591 71598    4524.0
Name: new_cases, dtype: float64
71592 71599    4793.0
Name: new_cases, dtype: float64
71593 71600    4084.0
Name: new_cases, dtype: float64
71594 71601    2903.0
Name: new_cases, dtype: float64
71595 71602    4350.0
Name: new_cases, dtype: float64
71596 71603    5286.0
Name: new_cases, dtype: float64
71597 71604    5492.0
Name: new_cases, dtype: float64
71598 71605    5104.0
Name: new_cases, dtype: float64
71599 71606    5595.0
Name: new_cases, dtype: float64
71600 71607    4599.0
Name: new_cases, dtype: float64
71601 71608    3314.0
Name: new_cases, dtype: float64
71602 71609    4961.0
Name: new_cases, dtype: float64
71603 71610    5783.0
Name: new_cases, dtype: float64
71604 71611    5913.0
Name: new_cases, dtype: float64
71605 71612    4684.0
Name: new_cases, dtype: float64
71606 71613    5983.0
Name: new_cases, dtype: float64
71607 71614    5890.0
Name: new_cases, dtype: float64
71608 71615    4464.0
Name: new_cases, dtype: float64
71609 71616    4190.0
Name: new_cases, dtype: float64
71610 71617    4060.0
Name: new_cases, dtype: float64
71611 71618    4370.0
Name: new_cases, dtype: float64
71612 71619    6050.0
Name: new_cases, dtype: float64
71613 71620    7238.0
Name: new_cases, dtype: float64
71614 71621    6484.0
Name: new_cases, dtype: float64
71615 71622    4940.0
Name: new_cases, dtype: float64
71616 71623    6235.0
Name: new_cases, dtype: float64
71617 71624    7051.0
Name: new_cases, dtype: float64
71618 71625    6874.0
Name: new_cases, dtype: float64
71619 71626    6262.0
Name: new_cases, dtype: float64
71620 71627    6417.0
Name: new_cases, dtype: float64
71621 71628    5256.0
Name: new_cases, dtype: float64
71622 71629    3677.0
Name: new_cases, dtype: float64
71623 71630    5224.0
Name: new_cases, dtype: float64
71624 71631    5791.0
Name: new_cases, dtype: float64
71625 71632    5712.0
Name: new_cases, dtype: float64
71626 71633    5245.0
Name: new_cases, dtype: float64
71627 71634    5035.0
Name: new_cases, dtype: float64
71628 71635    4039.0
Name: new_cases, dtype: float64
71629 71636    2711.0
Name: new_cases, dtype: float64
71630 71637    3892.0
Name: new_cases, dtype: float64
71631 71638    4533.0
Name: new_cases, dtype: float64
71632 71639    4132.0
Name: new_cases, dtype: float64
71633 71640    3703.0
Name: new_cases, dtype: float64
71634 71641    3593.0
Name: new_cases, dtype: float64
71635 71642    2874.0
Name: new_cases, dtype: float64
71636 71643    1791.0
Name: new_cases, dtype: float64
71637 71644    2639.0
Name: new_cases, dtype: float64
71638 71645    3034.0
Name: new_cases, dtype: float64
71639 71646    2831.0
Name: new_cases, dtype: float64
71640 71647    2592.0
Name: new_cases, dtype: float64
71641 71648    2650.0
Name: new_cases, dtype: float64
71642 71649    2020.0
Name: new_cases, dtype: float64
71643 71650    1280.0
Name: new_cases, dtype: float64
71644 71651    1881.0
Name: new_cases, dtype: float64
71645 71652    2238.0
Name: new_cases, dtype: float64
71646 71653    2042.0
Name: new_cases, dtype: float64
71647 71654    1934.0
Name: new_cases, dtype: float64
71648 71655    1941.0
Name: new_cases, dtype: float64
71649 71656    1382.0
Name: new_cases, dtype: float64
71650 71657    933.0
Name: new_cases, dtype: float64
71651 71658    1417.0
Name: new_cases, dtype: float64
71652 71659    1707.0
Name: new_cases, dtype: float64
71653 71660    1550.0
Name: new_cases, dtype: float64
71654 71661    1620.0
Name: new_cases, dtype: float64
71655 71662    1518.0
Name: new_cases, dtype: float64
71656 71663    1306.0
Name: new_cases, dtype: float64
71657 71664    868.0
Name: new_cases, dtype: float64
71658 71665    1435.0
Name: new_cases, dtype: float64
71659 71666    1780.0
Name: new_cases, dtype: float64
71660 71667    1674.0
Name: new_cases, dtype: float64
71661 71668    1710.0
Name: new_cases, dtype: float64
71662 71669    1631.0
Name: new_cases, dtype: float64
71663 71670    1282.0
Name: new_cases, dtype: float64
71664 71671    1001.0
Name: new_cases, dtype: float64
71665 71672    1380.0
Name: new_cases, dtype: float64
71666 71673    1820.0
Name: new_cases, dtype: float64
71667 71674    1754.0
Name: new_cases, dtype: float64
71668 71675    1775.0
Name: new_cases, dtype: float64
71669 71676    1878.0
Name: new_cases, dtype: float64
71670 71677    1485.0
Name: new_cases, dtype: float64
71671 71678    1029.0
Name: new_cases, dtype: float64
71672 71679    1668.0
Name: new_cases, dtype: float64
71673 71680    2189.0
Name: new_cases, dtype: float64
71674 71681    2246.0
Name: new_cases, dtype: float64
71675 71682    2276.0
Name: new_cases, dtype: float64
71676 71683    2458.0
Name: new_cases, dtype: float64
71677 71684    2030.0
Name: new_cases, dtype: float64
71678 71685    1505.0
Name: new_cases, dtype: float64
71679 71686    2384.0
Name: new_cases, dtype: float64
71680 71687    3192.0
Name: new_cases, dtype: float64
71681 71688    3418.0
Name: new_cases, dtype: float64
71682 71689    3433.0
Name: new_cases, dtype: float64
71683 71690    3886.0
Name: new_cases, dtype: float64
71684 71691    3101.0
Name: new_cases, dtype: float64
71685 71692    2328.0
Name: new_cases, dtype: float64
71686 71693    3759.0
Name: new_cases, dtype: float64
71687 71694    4949.0
Name: new_cases, dtype: float64
71688 71695    5399.0
Name: new_cases, dtype: float64
71689 71696    4234.0
Name: new_cases, dtype: float64
71690 71697    3594.0
Name: new_cases, dtype: float64
71691 71698    5039.0
Name: new_cases, dtype: float64
71692 71699    4709.0
Name: new_cases, dtype: float64
71693 71700    7670.0
Name: new_cases, dtype: float64
71694 71701    9628.0
Name: new_cases, dtype: float64
71695 71702    10752.0
Name: new_cases, dtype: float64
71696 71703    10831.0
Name: new_cases, dtype: float64
71697 71704    12422.0
Name: new_cases, dtype: float64
71698 71705    10248.0
Name: new_cases, dtype: float64
71699 71706    8478.0
Name: new_cases, dtype: float64
71700 71707    12101.0
Name: new_cases, dtype: float64
71701 71708    14312.0
Name: new_cases, dtype: float64
71702 71709    15317.0
Name: new_cases, dtype: float64
71703 71710    15807.0
Name: new_cases, dtype: float64
71704 71711    15821.0
Name: new_cases, dtype: float64
71705 71712    14526.0
Name: new_cases, dtype: float64
71706 71713    12178.0
Name: new_cases, dtype: float64
71707 71714    10733.0
Name: new_cases, dtype: float64
71708 71715    16028.0
Name: new_cases, dtype: float64
71709 71716    19034.0
Name: new_cases, dtype: float64
71710 71717    20496.0
Name: new_cases, dtype: float64
71711 71718    20303.0
Name: new_cases, dtype: float64
71712 71719    17888.0
Name: new_cases, dtype: float64
71713 71720    15007.0
Name: new_cases, dtype: float64
71714 71721    20105.0
Name: new_cases, dtype: float64
71715 71722    24096.0
Name: new_cases, dtype: float64
71716 71723    25341.0
Name: new_cases, dtype: float64
71717 71724    25992.0
Name: new_cases, dtype: float64
71718 71725    25662.0
Name: new_cases, dtype: float64
71719 71726    22345.0
Name: new_cases, dtype: float64
71720 71727    16924.0
Name: new_cases, dtype: float64
71721 71728    21669.0
Name: new_cases, dtype: float64
71722 71729    24411.0
Name: new_cases, dtype: float64
71723 71730    25038.0
Name: new_cases, dtype: float64
71724 71731    24319.0
Name: new_cases, dtype: float64
71725 71732    22859.0
Name: new_cases, dtype: float64
71726 71733    19337.0
Name: new_cases, dtype: float64
71727 71734    13674.0
Name: new_cases, dtype: float64
71728 71735    17719.0
Name: new_cases, dtype: float64
71729 71736    20028.0
Name: new_cases, dtype: float64
71730 71737    18216.0
Name: new_cases, dtype: float64
71731 71738    16721.0
Name: new_cases, dtype: float64
71732 71739    16014.0
Name: new_cases, dtype: float64
71733 71740    12907.0
Name: new_cases, dtype: float64
71734 71741    8224.0
Name: new_cases, dtype: float64
71735 71742    10607.0
Name: new_cases, dtype: float64
71736 71743    12388.0
Name: new_cases, dtype: float64
71737 71744    10396.0
Name: new_cases, dtype: float64
71738 71745    8859.0
Name: new_cases, dtype: float64
71739 71746    8802.0
Name: new_cases, dtype: float64
71740 71747    7213.0
Name: new_cases, dtype: float64
71741 71748    4173.0
Name: new_cases, dtype: float64
71742 71749    6279.0
Name: new_cases, dtype: float64
71743 71750    6809.0
Name: new_cases, dtype: float64
71744 71751    5691.0
Name: new_cases, dtype: float64
71745 71752    5113.0
Name: new_cases, dtype: float64
71746 71753    4700.0
Name: new_cases, dtype: float64
71747 71754    3396.0
Name: new_cases, dtype: float64
71748 71755    2221.0
Name: new_cases, dtype: float64
71749 71756    1770.0
Name: new_cases, dtype: float64
71750 71757    3243.0
Name: new_cases, dtype: float64
71751 71758    3601.0
Name: new_cases, dtype: float64
71752 71759    2095.0
Name: new_cases, dtype: float64
71753 71760    2670.0
Name: new_cases, dtype: float64
71754 71761    2136.0
Name: new_cases, dtype: float64
71755 71762    1148.0
Name: new_cases, dtype: float64
71756 71763    1722.0
Name: new_cases, dtype: float64
71757 71764    1983.0
Name: new_cases, dtype: float64
71758 71765    1575.0
Name: new_cases, dtype: float64
71759 71766    1444.0
Name: new_cases, dtype: float64
71760 71767    1243.0
Name: new_cases, dtype: float64

71761 71768    967.0
Name: new_cases, dtype: float64
71762 71769    599.0
Name: new_cases, dtype: float64
71763 71770    979.0
Name: new_cases, dtype: float64
71764 71771    1125.0
Name: new_cases, dtype: float64
71765 71772    972.0
Name: new_cases, dtype: float64
71766 71773    827.0
Name: new_cases, dtype: float64
71767 71774    774.0
Name: new_cases, dtype: float64
71768 71775    553.0
Name: new_cases, dtype: float64
71769 71776    369.0
Name: new_cases, dtype: float64
71770 71777    607.0
Name: new_cases, dtype: float64
71771 71778    731.0
Name: new_cases, dtype: float64
71772 71779    617.0
Name: new_cases, dtype: float64
71773 71780    517.0
Name: new_cases, dtype: float64
71774 71781    500.0
Name: new_cases, dtype: float64
71775 71782    428.0
Name: new_cases, dtype: float64
71776 71783    230.0
Name: new_cases, dtype: float64
71777 71784    371.0
Name: new_cases, dtype: float64
71778 71785    388.0
Name: new_cases, dtype: float64
71779 71786    343.0
Name: new_cases, dtype: float64
71780 71787    324.0
Name: new_cases, dtype: float64
71781 71788    283.0
Name: new_cases, dtype: float64
71782 71789    232.0
Name: new_cases, dtype: float64
71783 71790    151.0
Name: new_cases, dtype: float64
71784 71791    310.0
Name: new_cases, dtype: float64
71785 71792    310.0
Name: new_cases, dtype: float64
71786 71793    273.0
Name: new_cases, dtype: float64
71787 71794    292.0
Name: new_cases, dtype: float64
71788 71795    284.0
Name: new_cases, dtype: float64
71789 71796    228.0
Name: new_cases, dtype: float64
71790 71797    84.0
Name: new_cases, dtype: float64
71791 71798    221.0
Name: new_cases, dtype: float64
71792 71799    264.0
Name: new_cases, dtype: float64
71793 71800    158.0
Name: new_cases, dtype: float64
71794 71801    225.0
Name: new_cases, dtype: float64
71795 71802    230.0
Name: new_cases, dtype: float64
71796 71803    157.0
Name: new_cases, dtype: float64
71797 71804    100.0
Name: new_cases, dtype: float64
71798 71805    194.0
Name: new_cases, dtype: float64
71799 71806    196.0
Name: new_cases, dtype: float64
71800 71807    207.0
Name: new_cases, dtype: float64
71801 71808    194.0
Name: new_cases, dtype: float64
71802 71809    194.0
Name: new_cases, dtype: float64
71803 71810    126.0
Name: new_cases, dtype: float64
71804 71811    74.0
Name: new_cases, dtype: float64
71805 71812    144.0
Name: new_cases, dtype: float64
71806 71813    199.0
Name: new_cases, dtype: float64
71807 71814    148.0
Name: new_cases, dtype: float64
71808 71815    153.0
Name: new_cases, dtype: float64
71809 71816    104.0
Name: new_cases, dtype: float64
71810 71817    135.0
Name: new_cases, dtype: float64
71811 71818    44.0
Name: new_cases, dtype: float64
71812 71819    107.0
Name: new_cases, dtype: float64
71813 71820    73.0
Name: new_cases, dtype: float64
71814 71821    112.0
Name: new_cases, dtype: float64
71815 71822    113.0
Name: new_cases, dtype: float64
71816 71823    120.0
Name: new_cases, dtype: float64
71817 71824    60.0
Name: new_cases, dtype: float64
71818 71825    76.0
Name: new_cases, dtype: float64
71819 71826    81.0
Name: new_cases, dtype: float64
71820 71827    115.0
Name: new_cases, dtype: float64
71821 71828    113.0
Name: new_cases, dtype: float64
71822 71829    141.0
Name: new_cases, dtype: float64
71823 71830    120.0
Name: new_cases, dtype: float64
71824 71831    104.0
Name: new_cases, dtype: float64
71825 71832    54.0
Name: new_cases, dtype: float64
71826 71833    99.0
Name: new_cases, dtype: float64
71827 71834    122.0
Name: new_cases, dtype: float64
71828 71835    154.0
Name: new_cases, dtype: float64
71829 71836    136.0
Name: new_cases, dtype: float64
71830 71837    131.0
Name: new_cases, dtype: float64
71831 71838    98.0
Name: new_cases, dtype: float64
71832 71839    67.0
Name: new_cases, dtype: float64
71833 71840    128.0
Name: new_cases, dtype: float64
71834 71841    159.0
Name: new_cases, dtype: float64
71835 71842    163.0
Name: new_cases, dtype: float64
71836 71843    161.0
Name: new_cases, dtype: float64
71837 71844    179.0
Name: new_cases, dtype: float64
71838 71845    150.0
Name: new_cases, dtype: float64
71839 71846    109.0
Name: new_cases, dtype: float64
71840 71847    218.0
Name: new_cases, dtype: float64
71841 71848    220.0
Name: new_cases, dtype: float64
71842 71849    247.0
Name: new_cases, dtype: float64
71843 71850    260.0
Name: new_cases, dtype: float64
71844 71851    263.0
Name: new_cases, dtype: float64
71845 71852    225.0
Name: new_cases, dtype: float64
71846 71853    163.0
Name: new_cases, dtype: float64
71847 71854    313.0
Name: new_cases, dtype: float64
71848 71855    398.0
Name: new_cases, dtype: float64
71849 71856    432.0
Name: new_cases, dtype: float64
71850 71857    418.0
Name: new_cases, dtype: float64
71851 71858    456.0
Name: new_cases, dtype: float64
71852 71859    477.0
Name: new_cases, dtype: float64
71853 71860    672.0
Name: new_cases, dtype: float64
71854 71861    1149.0
Name: new_cases, dtype: float64
71855 71862    2490.0
Name: new_cases, dtype: float64
71856 71863    4297.0
Name: new_cases, dtype: float64
71857 71864    6070.0
Name: new_cases, dtype: float64
71858 71865    8302.0
Name: new_cases, dtype: float64
71859 71199    37.0
Name: new_cases, dtype: float64
71860 71200    62.0
Name: new_cases, dtype: float64
71861 71201    31.0
Name: new_cases, dtype: float64
71862 71202    17.0
Name: new_cases, dtype: float64
71863 71203    50.0
Name: new_cases, dtype: float64
71864 71204    35.0
Name: new_cases, dtype: float64
71865 71205    40.0
Name: new_cases, dtype: float64
73512 73519    0.0
Name: new_cases, dtype: float64
73513 73520    0.0
Name: new_cases, dtype: float64
73514 73521    8.0
Name: new_cases, dtype: float64
73515 73522    1.0
Name: new_cases, dtype: float64
73516 73523    9.0
Name: new_cases, dtype: float64
73517 73524    3.0
Name: new_cases, dtype: float64
73518 73525    3.0
Name: new_cases, dtype: float64
73519 73526    0.0
Name: new_cases, dtype: float64
73520 73527    7.0
Name: new_cases, dtype: float64
73521 73528    4.0
Name: new_cases, dtype: float64
73522 73529    8.0
Name: new_cases, dtype: float64
73523 73530    9.0
Name: new_cases, dtype: float64
73524 73531    22.0
Name: new_cases, dtype: float64
73525 73532    29.0
Name: new_cases, dtype: float64
73526 73533    12.0
Name: new_cases, dtype: float64
73527 73534    4.0
Name: new_cases, dtype: float64
73528 73535    16.0
Name: new_cases, dtype: float64
73529 73536    16.0
Name: new_cases, dtype: float64
73530 73537    14.0
Name: new_cases, dtype: float64
73531 73538    7.0
Name: new_cases, dtype: float64
73532 73539    5.0
Name: new_cases, dtype: float64
73533 73540    5.0
Name: new_cases, dtype: float64
73534 73541    2.0
Name: new_cases, dtype: float64
73535 73542    6.0
Name: new_cases, dtype: float64
73536 73543    11.0
Name: new_cases, dtype: float64
73537 73544    8.0
Name: new_cases, dtype: float64
73538 73545    9.0
Name: new_cases, dtype: float64
73539 73546    9.0
Name: new_cases, dtype: float64
73540 73547    12.0
Name: new_cases, dtype: float64
73541 73548    16.0
Name: new_cases, dtype: float64
73542 73549    8.0
Name: new_cases, dtype: float64
73543 73550    11.0
Name: new_cases, dtype: float64
73544 73551    15.0
Name: new_cases, dtype: float64
73545 73552    7.0
Name: new_cases, dtype: float64
73546 73553    17.0
Name: new_cases, dtype: float64
73547 73554    16.0
Name: new_cases, dtype: float64
73548 73555    7.0
Name: new_cases, dtype: float64
73549 73556    12.0
Name: new_cases, dtype: float64
73550 73557    8.0
Name: new_cases, dtype: float64
73551 73558    11.0
Name: new_cases, dtype: float64
73552 73559    10.0
Name: new_cases, dtype: float64
73553 73560    12.0
Name: new_cases, dtype: float64
73554 73561    15.0
Name: new_cases, dtype: float64
73555 73562    24.0
Name: new_cases, dtype: float64
73556 73563    30.0
Name: new_cases, dtype: float64
73557 73564    25.0
Name: new_cases, dtype: float64
73558 73565    45.0
Name: new_cases, dtype: float64
73559 73566    47.0
Name: new_cases, dtype: float64
73560 73567    25.0
Name: new_cases, dtype: float64
73561 73568    14.0
Name: new_cases, dtype: float64
73562 73569    28.0
Name: new_cases, dtype: float64
73563 73570    23.0
Name: new_cases, dtype: float64
73564 73571    28.0
Name: new_cases, dtype: float64
73565 73572    15.0
Name: new_cases, dtype: float64
73566 73573    22.0
Name: new_cases, dtype: float64
73567 73574    21.0
Name: new_cases, dtype: float64
73568 73575    23.0
Name: new_cases, dtype: float64

73569 73576    49.0
Name: new_cases, dtype: float64
73570 73577    57.0
Name: new_cases, dtype: float64
73571 73578    25.0
Name: new_cases, dtype: float64
73572 73579    51.0
Name: new_cases, dtype: float64
73573 73580    66.0
Name: new_cases, dtype: float64
73574 73581    80.0
Name: new_cases, dtype: float64
73575 73582    52.0
Name: new_cases, dtype: float64
73576 73583    31.0
Name: new_cases, dtype: float64
73577 73584    22.0
Name: new_cases, dtype: float64
73578 73585    72.0
Name: new_cases, dtype: float64
73579 73586    62.0
Name: new_cases, dtype: float64
73580 73587    123.0
Name: new_cases, dtype: float64
73581 73588    147.0
Name: new_cases, dtype: float64
73582 73589    127.0
Name: new_cases, dtype: float64
73583 73590    143.0
Name: new_cases, dtype: float64
73584 73591    74.0
Name: new_cases, dtype: float64
73585 73592    59.0
Name: new_cases, dtype: float64
73586 73593    72.0
Name: new_cases, dtype: float64
73587 73594    123.0
Name: new_cases, dtype: float64
73588 73595    124.0
Name: new_cases, dtype: float64
73589 73596    134.0
Name: new_cases, dtype: float64
73590 73597    126.0
Name: new_cases, dtype: float64
73591 73598    167.0
Name: new_cases, dtype: float64
73592 73599    105.0
Name: new_cases, dtype: float64
73593 73600    117.0
Name: new_cases, dtype: float64
73594 73601    105.0
Name: new_cases, dtype: float64
73595 73602    121.0
Name: new_cases, dtype: float64
73596 73603    90.0
Name: new_cases, dtype: float64
73597 73604    152.0
Name: new_cases, dtype: float64
73598 73605    137.0
Name: new_cases, dtype: float64
73599 73606    133.0
Name: new_cases, dtype: float64
73600 73607    133.0
Name: new_cases, dtype: float64
73601 73608    184.0
Name: new_cases, dtype: float64
73602 73609    213.0
Name: new_cases, dtype: float64
73603 73610    117.0
Name: new_cases, dtype: float64
73604 73611    104.0
Name: new_cases, dtype: float64
73605 73612    260.0
Name: new_cases, dtype: float64
73606 73613    59.0
Name: new_cases, dtype: float64
73607 73614    155.0
Name: new_cases, dtype: float64
73608 73615    254.0
Name: new_cases, dtype: float64
73609 73616    178.0
Name: new_cases, dtype: float64
73610 73617    149.0
Name: new_cases, dtype: float64
73611 73618    278.0
Name: new_cases, dtype: float64
73612 73619    259.0
Name: new_cases, dtype: float64
73613 73620    120.0
Name: new_cases, dtype: float64
73614 73621    176.0
Name: new_cases, dtype: float64
73615 73622    307.0
Name: new_cases, dtype: float64
73616 73623    268.0
Name: new_cases, dtype: float64
73617 73624    247.0
Name: new_cases, dtype: float64
73618 73625    389.0
Name: new_cases, dtype: float64
73619 73626    309.0
Name: new_cases, dtype: float64
73620 73627    181.0
Name: new_cases, dtype: float64
73621 73628    183.0
Name: new_cases, dtype: float64
73622 73629    278.0
Name: new_cases, dtype: float64
73623 73630    447.0
Name: new_cases, dtype: float64
73624 73631    473.0
Name: new_cases, dtype: float64
73625 73632    278.0
Name: new_cases, dtype: float64
73626 73633    379.0
Name: new_cases, dtype: float64
73627 73634    189.0
Name: new_cases, dtype: float64
73628 73635    497.0
Name: new_cases, dtype: float64
73629 73636    461.0
Name: new_cases, dtype: float64
73630 73637    421.0
Name: new_cases, dtype: float64
73631 73638    389.0
Name: new_cases, dtype: float64
73632 73639    688.0
Name: new_cases, dtype: float64
73633 73640    603.0
Name: new_cases, dtype: float64
73634 73641    418.0
Name: new_cases, dtype: float64
73635 73642    397.0
Name: new_cases, dtype: float64
73636 73643    637.0
Name: new_cases, dtype: float64
73637 73644    796.0
Name: new_cases, dtype: float64
73638 73645    667.0
Name: new_cases, dtype: float64
73639 73646    375.0
Name: new_cases, dtype: float64
73640 73647    960.0
Name: new_cases, dtype: float64
73641 73648    372.0
Name: new_cases, dtype: float64
73642 73649    606.0
Name: new_cases, dtype: float64
73643 73650    544.0
Name: new_cases, dtype: float64
73644 73651    788.0
Name: new_cases, dtype: float64
73645 73652    723.0
Name: new_cases, dtype: float64
73646 73653    727.0
Name: new_cases, dtype: float64
73647 73654    690.0
Name: new_cases, dtype: float64
73648 73655    544.0
Name: new_cases, dtype: float64
73649 73656    605.0
Name: new_cases, dtype: float64
73650 73657    671.0
Name: new_cases, dtype: float64
73651 73658    538.0
Name: new_cases, dtype: float64
73652 73659    727.0
Name: new_cases, dtype: float64
73653 73660    699.0
Name: new_cases, dtype: float64
73654 73661    599.0
Name: new_cases, dtype: float64
73655 73662    492.0
Name: new_cases, dtype: float64
73656 73663    497.0
Name: new_cases, dtype: float64
73657 73664    679.0
Name: new_cases, dtype: float64
73658 73665    650.0
Name: new_cases, dtype: float64
73659 73666    580.0
Name: new_cases, dtype: float64
73660 73667    515.0
Name: new_cases, dtype: float64
73661 73668    271.0
Name: new_cases, dtype: float64
73662 73669    245.0
Name: new_cases, dtype: float64
73663 73670    271.0
Name: new_cases, dtype: float64
73664 73671    379.0
Name: new_cases, dtype: float64
73665 73672    426.0
Name: new_cases, dtype: float64
73666 73673    322.0
Name: new_cases, dtype: float64
73667 73674    355.0
Name: new_cases, dtype: float64
73668 73675    246.0
Name: new_cases, dtype: float64
73669 73676    193.0
Name: new_cases, dtype: float64
73670 73677    246.0
Name: new_cases, dtype: float64
73671 73678    213.0
Name: new_cases, dtype: float64
73672 73679    373.0
Name: new_cases, dtype: float64
73673 73680    241.0
Name: new_cases, dtype: float64
73674 73681    164.0
Name: new_cases, dtype: float64
73675 73682    263.0
Name: new_cases, dtype: float64
73676 73683    144.0
Name: new_cases, dtype: float64
73677 73684    114.0
Name: new_cases, dtype: float64
73678 73685    178.0
Name: new_cases, dtype: float64
73679 73686    212.0
Name: new_cases, dtype: float64
73680 73687    179.0
Name: new_cases, dtype: float64
73681 73688    136.0
Name: new_cases, dtype: float64
73682 73689    83.0
Name: new_cases, dtype: float64
73683 73690    102.0
Name: new_cases, dtype: float64
73684 73691    151.0
Name: new_cases, dtype: float64
73685 73692    104.0
Name: new_cases, dtype: float64
73686 73693    143.0
Name: new_cases, dtype: float64
73687 73694    190.0
Name: new_cases, dtype: float64
73688 73695    176.0
Name: new_cases, dtype: float64
73689 73696    188.0
Name: new_cases, dtype: float64
73690 73697    48.0
Name: new_cases, dtype: float64
73691 73698    96.0
Name: new_cases, dtype: float64
73692 73699    0.0
Name: new_cases, dtype: float64
73693 73700    275.0
Name: new_cases, dtype: float64
73694 73701    148.0
Name: new_cases, dtype: float64
73695 73702    105.0
Name: new_cases, dtype: float64
73696 73703    152.0
Name: new_cases, dtype: float64
73697 73704    98.0
Name: new_cases, dtype: float64
73698 73705    139.0
Name: new_cases, dtype: float64
73699 73706    130.0
Name: new_cases, dtype: float64
73700 73707    141.0
Name: new_cases, dtype: float64
73701 73708    218.0
Name: new_cases, dtype: float64
73702 73709    164.0
Name: new_cases, dtype: float64
73703 73710    244.0
Name: new_cases, dtype: float64
73704 73711    53.0
Name: new_cases, dtype: float64
73705 73712    210.0
Name: new_cases, dtype: float64
73706 73713    151.0
Name: new_cases, dtype: float64
73707 73714    184.0
Name: new_cases, dtype: float64
73708 73715    210.0
Name: new_cases, dtype: float64
73709 73716    261.0
Name: new_cases, dtype: float64
73710 73717    243.0
Name: new_cases, dtype: float64
73711 73718    22.0
Name: new_cases, dtype: float64
73712 73719    137.0
Name: new_cases, dtype: float64
73713 73720    321.0
Name: new_cases, dtype: float64
73714 73721    271.0
Name: new_cases, dtype: float64
73715 73722    442.0
Name: new_cases, dtype: float64
73716 73723    538.0
Name: new_cases, dtype: float64
73717 73724    388.0
Name: new_cases, dtype: float64
73718 73725    73.0
Name: new_cases, dtype: float64
73719 73726    318.0
Name: new_cases, dtype: float64
73720 73727    604.0
Name: new_cases, dtype: float64
73721 73728    602.0
Name: new_cases, dtype: float64
73722 73729    437.0
Name: new_cases, dtype: float64
73723 73730    616.0
Name: new_cases, dtype: float64
73724 73731    685.0
Name: new_cases, dtype: float64
73725 73732    195.0
Name: new_cases, dtype: float64
73726 73733    571.0
Name: new_cases, dtype: float64
73727 73734    497.0
Name: new_cases, dtype: float64
73728 73735    1068.0
Name: new_cases, dtype: float64
73729 73736    631.0
Name: new_cases, dtype: float64
73730 73737    947.0
Name: new_cases, dtype: float64
73731 73738    931.0
Name: new_cases, dtype: float64
73732 73739    276.0
Name: new_cases, dtype: float64
73733 73740    836.0
Name: new_cases, dtype: float64
73734 73741    1018.0
Name: new_cases, dtype: float64
73735 73742    761.0
Name: new_cases, dtype: float64
73736 73743    1185.0
Name: new_cases, dtype: float64
73737 73744    1395.0
Name: new_cases, dtype: float64
73738 73745    685.0
Name: new_cases, dtype: float64
73739 73746    724.0
Name: new_cases, dtype: float64
73740 73747    492.0
Name: new_cases, dtype: float64

73741 73748    1494.0
Name: new_cases, dtype: float64
73742 73749    1008.0
Name: new_cases, dtype: float64
73743 73750    1109.0
Name: new_cases, dtype: float64
73744 73751    1065.0
Name: new_cases, dtype: float64
73745 73752    719.0
Name: new_cases, dtype: float64
73746 73753    756.0
Name: new_cases, dtype: float64
73747 73754    1344.0
Name: new_cases, dtype: float64
73748 73755    1216.0
Name: new_cases, dtype: float64
73749 73756    919.0
Name: new_cases, dtype: float64
73750 73757    1470.0
Name: new_cases, dtype: float64
73751 73758    1080.0
Name: new_cases, dtype: float64
73752 73759    972.0
Name: new_cases, dtype: float64
73753 73760    559.0
Name: new_cases, dtype: float64
73754 73761    925.0
Name: new_cases, dtype: float64
73755 73762    957.0
Name: new_cases, dtype: float64
73756 73763    1459.0
Name: new_cases, dtype: float64
73757 73764    1048.0
Name: new_cases, dtype: float64
73758 73765    1211.0
Name: new_cases, dtype: float64
73759 73766    968.0
Name: new_cases, dtype: float64
73760 73767    413.0
Name: new_cases, dtype: float64
73761 73768    727.0
Name: new_cases, dtype: float64
73762 73769    810.0
Name: new_cases, dtype: float64
73763 73770    780.0
Name: new_cases, dtype: float64
73764 73771    1554.0
Name: new_cases, dtype: float64
73765 73772    949.0
Name: new_cases, dtype: float64
73766 73773    711.0
Name: new_cases, dtype: float64
73767 73774    302.0
Name: new_cases, dtype: float64
73768 73775    551.0
Name: new_cases, dtype: float64
73769 73776    961.0
Name: new_cases, dtype: float64
73770 73777    1253.0
Name: new_cases, dtype: float64
73771 73778    866.0
Name: new_cases, dtype: float64
73772 73779    735.0
Name: new_cases, dtype: float64
73773 73780    396.0
Name: new_cases, dtype: float64
73774 73781    199.0
Name: new_cases, dtype: float64
73775 73782    521.0
Name: new_cases, dtype: float64
73776 73783    561.0
Name: new_cases, dtype: float64
73777 73784    644.0
Name: new_cases, dtype: float64
73778 73785    673.0
Name: new_cases, dtype: float64
73779 73786    548.0
Name: new_cases, dtype: float64
73780 73787    366.0
Name: new_cases, dtype: float64
73781 73788    163.0
Name: new_cases, dtype: float64
73782 73789    404.0
Name: new_cases, dtype: float64
73783 73790    394.0
Name: new_cases, dtype: float64
73784 73791    552.0
Name: new_cases, dtype: float64
73785 73792    356.0
Name: new_cases, dtype: float64
73786 73793    390.0
Name: new_cases, dtype: float64
73787 73794    349.0
Name: new_cases, dtype: float64
73788 73795    114.0
Name: new_cases, dtype: float64
73789 73796    154.0
Name: new_cases, dtype: float64
73790 73797    427.0
Name: new_cases, dtype: float64
73791 73798    236.0
Name: new_cases, dtype: float64
73792 73799    282.0
Name: new_cases, dtype: float64
73793 73800    130.0
Name: new_cases, dtype: float64
73794 73801    80.0
Name: new_cases, dtype: float64
73795 73802    69.0
Name: new_cases, dtype: float64
73796 73803    147.0
Name: new_cases, dtype: float64
73797 73804    112.0
Name: new_cases, dtype: float64
73798 73805    207.0
Name: new_cases, dtype: float64
73799 73806    156.0
Name: new_cases, dtype: float64
73800 73807    64.0
Name: new_cases, dtype: float64
73801 73808    124.0
Name: new_cases, dtype: float64
73802 73809    106.0
Name: new_cases, dtype: float64
73803 73810    219.0
Name: new_cases, dtype: float64
73804 73811    271.0
Name: new_cases, dtype: float64
73805 73812    335.0
Name: new_cases, dtype: float64
73806 73813    221.0
Name: new_cases, dtype: float64
73807 73814    230.0
Name: new_cases, dtype: float64
73808 73815    87.0
Name: new_cases, dtype: float64
73809 73816    63.0
Name: new_cases, dtype: float64
73810 73817    98.0
Name: new_cases, dtype: float64
73811 73818    123.0
Name: new_cases, dtype: float64
73812 73819    138.0
Name: new_cases, dtype: float64
73813 73820    166.0
Name: new_cases, dtype: float64
73814 73821    223.0
Name: new_cases, dtype: float64
73815 73822    80.0
Name: new_cases, dtype: float64
73816 73823    65.0
Name: new_cases, dtype: float64
73817 73824    81.0
Name: new_cases, dtype: float64
73818 73825    136.0
Name: new_cases, dtype: float64
73819 73826    186.0
Name: new_cases, dtype: float64
73820 73827    139.0
Name: new_cases, dtype: float64
73821 73828    129.0
Name: new_cases, dtype: float64
73822 73829    85.0
Name: new_cases, dtype: float64
73823 73830    69.0
Name: new_cases, dtype: float64
73824 73831    141.0
Name: new_cases, dtype: float64
73825 73832    130.0
Name: new_cases, dtype: float64
73826 73833    99.0
Name: new_cases, dtype: float64
73827 73834    141.0
Name: new_cases, dtype: float64
73828 73835    112.0
Name: new_cases, dtype: float64
73829 73836    98.0
Name: new_cases, dtype: float64
73830 73837    83.0
Name: new_cases, dtype: float64
73831 73838    153.0
Name: new_cases, dtype: float64
73832 73839    150.0
Name: new_cases, dtype: float64
73833 73840    180.0
Name: new_cases, dtype: float64
73834 73841    195.0
Name: new_cases, dtype: float64
73835 73842    156.0
Name: new_cases, dtype: float64
73836 73843    129.0
Name: new_cases, dtype: float64
73837 73844    125.0
Name: new_cases, dtype: float64
73838 73845    104.0
Name: new_cases, dtype: float64
73839 73846    173.0
Name: new_cases, dtype: float64
73840 73847    132.0
Name: new_cases, dtype: float64
73841 73848    260.0
Name: new_cases, dtype: float64
73842 73849    179.0
Name: new_cases, dtype: float64
73843 73850    75.0
Name: new_cases, dtype: float64
73844 73851    147.0
Name: new_cases, dtype: float64
73845 73852    174.0
Name: new_cases, dtype: float64
73846 73853    144.0
Name: new_cases, dtype: float64
73847 73854    283.0
Name: new_cases, dtype: float64
73848 73855    226.0
Name: new_cases, dtype: float64
73849 73856    152.0
Name: new_cases, dtype: float64
73850 73857    208.0
Name: new_cases, dtype: float64
73851 73858    105.0
Name: new_cases, dtype: float64
73852 73859    194.0
Name: new_cases, dtype: float64
73853 73860    280.0
Name: new_cases, dtype: float64
73854 73861    277.0
Name: new_cases, dtype: float64
73855 73862    410.0
Name: new_cases, dtype: float64
73856 73863    181.0
Name: new_cases, dtype: float64
73857 73864    325.0
Name: new_cases, dtype: float64
73858 73865    152.0
Name: new_cases, dtype: float64
73859 73866    345.0
Name: new_cases, dtype: float64
73860 73867    331.0
Name: new_cases, dtype: float64
73861 73868    528.0
Name: new_cases, dtype: float64
73862 73869    400.0
Name: new_cases, dtype: float64
73863 73870    633.0
Name: new_cases, dtype: float64
73864 73871    465.0
Name: new_cases, dtype: float64
73865 73872    337.0
Name: new_cases, dtype: float64
73866 73873    479.0
Name: new_cases, dtype: float64
73867 73874    713.0
Name: new_cases, dtype: float64
73868 73875    829.0
Name: new_cases, dtype: float64
73869 73876    750.0
Name: new_cases, dtype: float64
73870 73877    870.0
Name: new_cases, dtype: float64
73871 73878    431.0
Name: new_cases, dtype: float64
73872 73879    731.0
Name: new_cases, dtype: float64
73873 73880    1064.0
Name: new_cases, dtype: float64
73874 73881    1279.0
Name: new_cases, dtype: float64
73875 73882    1225.0
Name: new_cases, dtype: float64
73876 73883    1354.0
Name: new_cases, dtype: float64
73877 73884    1274.0
Name: new_cases, dtype: float64
73878 73885    747.0
Name: new_cases, dtype: float64
73879 73886    1130.0
Name: new_cases, dtype: float64
73880 73887    1127.0
Name: new_cases, dtype: float64
73881 73888    1540.0
Name: new_cases, dtype: float64
73882 73889    1463.0
Name: new_cases, dtype: float64
73883 73890    2008.0
Name: new_cases, dtype: float64
73884 73891    1152.0
Name: new_cases, dtype: float64
73885 73892    884.0
Name: new_cases, dtype: float64
73886 73893    902.0
Name: new_cases, dtype: float64
73887 73894    1530.0
Name: new_cases, dtype: float64
73888 73895    1412.0
Name: new_cases, dtype: float64
73889 73896    984.0
Name: new_cases, dtype: float64
73890 73897    1851.0
Name: new_cases, dtype: float64
73891 73898    1184.0
Name: new_cases, dtype: float64
73892 73899    911.0
Name: new_cases, dtype: float64
73893 73900    460.0
Name: new_cases, dtype: float64
73894 73901    394.0
Name: new_cases, dtype: float64
73895 73902    1523.0
Name: new_cases, dtype: float64
73896 73903    1698.0
Name: new_cases, dtype: float64
73897 73904    1091.0
Name: new_cases, dtype: float64
73898 73905    1030.0
Name: new_cases, dtype: float64
73899 73906    486.0
Name: new_cases, dtype: float64
73900 73907    486.0
Name: new_cases, dtype: float64

73901 73908    991.0
Name: new_cases, dtype: float64
73902 73909    981.0
Name: new_cases, dtype: float64
73903 73910    1091.0
Name: new_cases, dtype: float64
73904 73911    1041.0
Name: new_cases, dtype: float64
73905 73912    1027.0
Name: new_cases, dtype: float64
73906 73913    366.0
Name: new_cases, dtype: float64
73907 73914    241.0
Name: new_cases, dtype: float64
73908 73915    629.0
Name: new_cases, dtype: float64
73909 73916    965.0
Name: new_cases, dtype: float64
73910 73917    904.0
Name: new_cases, dtype: float64
73911 73918    773.0
Name: new_cases, dtype: float64
73912 73919    1153.0
Name: new_cases, dtype: float64
73913 73920    469.0
Name: new_cases, dtype: float64
73914 73921    194.0
Name: new_cases, dtype: float64
73915 73922    511.0
Name: new_cases, dtype: float64
73916 73923    834.0
Name: new_cases, dtype: float64
73917 73924    495.0
Name: new_cases, dtype: float64
73918 73925    497.0
Name: new_cases, dtype: float64
73919 73926    735.0
Name: new_cases, dtype: float64
73920 73927    369.0
Name: new_cases, dtype: float64
73921 73928    137.0
Name: new_cases, dtype: float64
73922 73929    345.0
Name: new_cases, dtype: float64
73923 73930    489.0
Name: new_cases, dtype: float64
73924 73931    705.0
Name: new_cases, dtype: float64
73925 73932    568.0
Name: new_cases, dtype: float64
73926 73933    572.0
Name: new_cases, dtype: float64
73927 73934    316.0
Name: new_cases, dtype: float64
73928 73935    66.0
Name: new_cases, dtype: float64
73929 73936    356.0
Name: new_cases, dtype: float64
73930 73937    410.0
Name: new_cases, dtype: float64
73931 73938    334.0
Name: new_cases, dtype: float64
73932 73939    392.0
Name: new_cases, dtype: float64
73933 73940    267.0
Name: new_cases, dtype: float64
73934 73941    86.0
Name: new_cases, dtype: float64
73935 73942    72.0
Name: new_cases, dtype: float64
73936 73943    469.0
Name: new_cases, dtype: float64
73937 73944    376.0
Name: new_cases, dtype: float64
73938 73945    494.0
Name: new_cases, dtype: float64
73939 73946    659.0
Name: new_cases, dtype: float64
73940 73947    573.0
Name: new_cases, dtype: float64
73941 73948    324.0
Name: new_cases, dtype: float64
73942 73949    111.0
Name: new_cases, dtype: float64
73943 73950    382.0
Name: new_cases, dtype: float64
73944 73951    431.0
Name: new_cases, dtype: float64
73945 73952    341.0
Name: new_cases, dtype: float64
73946 73953    344.0
Name: new_cases, dtype: float64
73947 73954    444.0
Name: new_cases, dtype: float64
73948 73955    162.0
Name: new_cases, dtype: float64
73949 73956    88.0
Name: new_cases, dtype: float64
73950 73957    349.0
Name: new_cases, dtype: float64
73951 73958    142.0
Name: new_cases, dtype: float64
73952 73959    432.0
Name: new_cases, dtype: float64
73953 73960    284.0
Name: new_cases, dtype: float64
73954 73961    383.0
Name: new_cases, dtype: float64
73955 73962    166.0
Name: new_cases, dtype: float64
73956 73963    148.0
Name: new_cases, dtype: float64
73957 73964    433.0
Name: new_cases, dtype: float64
73958 73965    589.0
Name: new_cases, dtype: float64
73959 73966    624.0
Name: new_cases, dtype: float64
73960 73967    488.0
Name: new_cases, dtype: float64
73961 73968    403.0
Name: new_cases, dtype: float64
73962 73969    161.0
Name: new_cases, dtype: float64
73963 73970    344.0
Name: new_cases, dtype: float64
73964 73971    456.0
Name: new_cases, dtype: float64
73965 73972    485.0
Name: new_cases, dtype: float64
73966 73973    660.0
Name: new_cases, dtype: float64
73967 73974    796.0
Name: new_cases, dtype: float64
73968 73975    714.0
Name: new_cases, dtype: float64
73969 73976    283.0
Name: new_cases, dtype: float64
73970 73977    218.0
Name: new_cases, dtype: float64
73971 73978    583.0
Name: new_cases, dtype: float64
73972 73979    622.0
Name: new_cases, dtype: float64
73973 73980    741.0
Name: new_cases, dtype: float64
73974 73981    646.0
Name: new_cases, dtype: float64
73975 73982    508.0
Name: new_cases, dtype: float64
73976 73983    204.0
Name: new_cases, dtype: float64
73977 73984    287.0
Name: new_cases, dtype: float64
73978 73985    719.0
Name: new_cases, dtype: float64
73979 73986    558.0
Name: new_cases, dtype: float64
73980 73987    376.0
Name: new_cases, dtype: float64
73981 73988    523.0
Name: new_cases, dtype: float64
73982 73989    531.0
Name: new_cases, dtype: float64
73983 73990    277.0
Name: new_cases, dtype: float64
73984 73991    185.0
Name: new_cases, dtype: float64
73985 73992    400.0
Name: new_cases, dtype: float64
73986 73993    506.0
Name: new_cases, dtype: float64
73987 73994    566.0
Name: new_cases, dtype: float64
73988 73995    452.0
Name: new_cases, dtype: float64
73989 73996    536.0
Name: new_cases, dtype: float64
73990 73997    241.0
Name: new_cases, dtype: float64
73991 73998    188.0
Name: new_cases, dtype: float64
73992 73999    761.0
Name: new_cases, dtype: float64
73993 74000    480.0
Name: new_cases, dtype: float64
73994 74001    837.0
Name: new_cases, dtype: float64
73995 74002    692.0
Name: new_cases, dtype: float64
73996 74003    723.0
Name: new_cases, dtype: float64
73997 74004    323.0
Name: new_cases, dtype: float64
73998 74005    431.0
Name: new_cases, dtype: float64
73999 74006    618.0
Name: new_cases, dtype: float64
74000 74007    503.0
Name: new_cases, dtype: float64
74001 74008    801.0
Name: new_cases, dtype: float64
74002 74009    787.0
Name: new_cases, dtype: float64
74003 74010    847.0
Name: new_cases, dtype: float64
74004 74011    664.0
Name: new_cases, dtype: float64
74005 74012    550.0
Name: new_cases, dtype: float64
74006 74013    976.0
Name: new_cases, dtype: float64
74007 74014    1006.0
Name: new_cases, dtype: float64
74008 74015    1068.0
Name: new_cases, dtype: float64
74009 74016    945.0
Name: new_cases, dtype: float64
74010 74017    1259.0
Name: new_cases, dtype: float64
74011 74018    467.0
Name: new_cases, dtype: float64
74012 74019    591.0
Name: new_cases, dtype: float64
74013 74020    1085.0
Name: new_cases, dtype: float64
74014 74021    1335.0
Name: new_cases, dtype: float64
74015 74022    1571.0
Name: new_cases, dtype: float64
74016 74023    1561.0
Name: new_cases, dtype: float64
74017 74024    1205.0
Name: new_cases, dtype: float64
74018 74025    800.0
Name: new_cases, dtype: float64
74019 74026    745.0
Name: new_cases, dtype: float64
74020 74027    1183.0
Name: new_cases, dtype: float64
74021 74028    1974.0
Name: new_cases, dtype: float64
74022 74029    1546.0
Name: new_cases, dtype: float64
74023 74030    1437.0
Name: new_cases, dtype: float64
74024 74031    1225.0
Name: new_cases, dtype: float64
74025 74032    789.0
Name: new_cases, dtype: float64
74026 74033    679.0
Name: new_cases, dtype: float64
74027 74034    1488.0
Name: new_cases, dtype: float64
74028 74035    1506.0
Name: new_cases, dtype: float64
74029 74036    1263.0
Name: new_cases, dtype: float64
74030 74037    1414.0
Name: new_cases, dtype: float64
74031 74038    1286.0
Name: new_cases, dtype: float64
74032 74039    646.0
Name: new_cases, dtype: float64
74033 74040    619.0
Name: new_cases, dtype: float64
74034 74041    1166.0
Name: new_cases, dtype: float64
74035 74042    1258.0
Name: new_cases, dtype: float64
74036 74043    817.0
Name: new_cases, dtype: float64
74037 74044    932.0
Name: new_cases, dtype: float64
74038 74045    788.0
Name: new_cases, dtype: float64
74039 74046    363.0
Name: new_cases, dtype: float64
74040 74047    346.0
Name: new_cases, dtype: float64
74041 74048    565.0
Name: new_cases, dtype: float64
74042 74049    1018.0
Name: new_cases, dtype: float64
74043 74050    970.0
Name: new_cases, dtype: float64
74044 74051    1001.0
Name: new_cases, dtype: float64
74045 74052    840.0
Name: new_cases, dtype: float64
74046 74053    480.0
Name: new_cases, dtype: float64
74047 74054    258.0
Name: new_cases, dtype: float64
74048 74055    704.0
Name: new_cases, dtype: float64
74049 74056    649.0
Name: new_cases, dtype: float64
74050 74057    501.0
Name: new_cases, dtype: float64
74051 74058    661.0
Name: new_cases, dtype: float64
74052 74059    511.0
Name: new_cases, dtype: float64
74053 74060    269.0
Name: new_cases, dtype: float64
74054 74061    204.0
Name: new_cases, dtype: float64
74055 74062    451.0
Name: new_cases, dtype: float64
74056 74063    446.0
Name: new_cases, dtype: float64

74057 74064    511.0
Name: new_cases, dtype: float64
74058 74065    444.0
Name: new_cases, dtype: float64
74059 74066    515.0
Name: new_cases, dtype: float64
74060 74067    234.0
Name: new_cases, dtype: float64
74061 74068    113.0
Name: new_cases, dtype: float64
74062 74069    313.0
Name: new_cases, dtype: float64
74063 74070    402.0
Name: new_cases, dtype: float64
74064 74071    317.0
Name: new_cases, dtype: float64
74065 74072    394.0
Name: new_cases, dtype: float64
74066 74073    323.0
Name: new_cases, dtype: float64
74067 74074    69.0
Name: new_cases, dtype: float64
74068 74075    54.0
Name: new_cases, dtype: float64
74069 74076    255.0
Name: new_cases, dtype: float64
74070 74077    404.0
Name: new_cases, dtype: float64
74071 74078    260.0
Name: new_cases, dtype: float64
74072 74079    291.0
Name: new_cases, dtype: float64
74073 74080    298.0
Name: new_cases, dtype: float64
74074 74081    91.0
Name: new_cases, dtype: float64
74075 74082    77.0
Name: new_cases, dtype: float64
74076 74083    189.0
Name: new_cases, dtype: float64
74077 74084    130.0
Name: new_cases, dtype: float64
74078 74085    218.0
Name: new_cases, dtype: float64
74079 74086    170.0
Name: new_cases, dtype: float64
74080 74087    159.0
Name: new_cases, dtype: float64
74081 74088    95.0
Name: new_cases, dtype: float64
74082 74089    96.0
Name: new_cases, dtype: float64
74083 74090    65.0
Name: new_cases, dtype: float64
74084 74091    170.0
Name: new_cases, dtype: float64
74085 74092    186.0
Name: new_cases, dtype: float64
74086 74093    134.0
Name: new_cases, dtype: float64
74087 74094    156.0
Name: new_cases, dtype: float64
74088 74095    74.0
Name: new_cases, dtype: float64
74089 74096    33.0
Name: new_cases, dtype: float64
74090 74097    133.0
Name: new_cases, dtype: float64
74091 74098    109.0
Name: new_cases, dtype: float64
74092 74099    67.0
Name: new_cases, dtype: float64
74093 74100    124.0
Name: new_cases, dtype: float64
74094 74101    129.0
Name: new_cases, dtype: float64
74095 74102    44.0
Name: new_cases, dtype: float64
74096 74103    16.0
Name: new_cases, dtype: float64
74097 74104    151.0
Name: new_cases, dtype: float64
74098 74105    99.0
Name: new_cases, dtype: float64
74099 74106    80.0
Name: new_cases, dtype: float64
74100 74107    133.0
Name: new_cases, dtype: float64
74101 74108    142.0
Name: new_cases, dtype: float64
74102 74109    17.0
Name: new_cases, dtype: float64
74103 74110    29.0
Name: new_cases, dtype: float64
74104 74111    70.0
Name: new_cases, dtype: float64
74105 74112    103.0
Name: new_cases, dtype: float64
74106 74113    149.0
Name: new_cases, dtype: float64
74107 74114    76.0
Name: new_cases, dtype: float64
74108 74115    76.0
Name: new_cases, dtype: float64
74109 74116    20.0
Name: new_cases, dtype: float64
74110 74117    20.0
Name: new_cases, dtype: float64
74111 74118    26.0
Name: new_cases, dtype: float64
74112 74119    178.0
Name: new_cases, dtype: float64
74113 74120    94.0
Name: new_cases, dtype: float64
74114 74121    64.0
Name: new_cases, dtype: float64
74115 74122    61.0
Name: new_cases, dtype: float64
74116 74123    21.0
Name: new_cases, dtype: float64
74117 74124    12.0
Name: new_cases, dtype: float64
74118 74125    75.0
Name: new_cases, dtype: float64
74119 74126    69.0
Name: new_cases, dtype: float64
74120 74127    88.0
Name: new_cases, dtype: float64
74121 74128    88.0
Name: new_cases, dtype: float64
74122 74129    59.0
Name: new_cases, dtype: float64
74123 74130    22.0
Name: new_cases, dtype: float64
74124 74131    18.0
Name: new_cases, dtype: float64
74125 74132    53.0
Name: new_cases, dtype: float64
74126 74133    35.0
Name: new_cases, dtype: float64
74127 74134    46.0
Name: new_cases, dtype: float64
74128 74135    42.0
Name: new_cases, dtype: float64
74129 74136    36.0
Name: new_cases, dtype: float64
74130 74137    11.0
Name: new_cases, dtype: float64
74131 74138    28.0
Name: new_cases, dtype: float64
74132 74139    109.0
Name: new_cases, dtype: float64
74133 74140    76.0
Name: new_cases, dtype: float64
74134 74141    96.0
Name: new_cases, dtype: float64
74135 74142    95.0
Name: new_cases, dtype: float64
74136 74143    53.0
Name: new_cases, dtype: float64
74137 74144    29.0
Name: new_cases, dtype: float64
74138 74145    32.0
Name: new_cases, dtype: float64
74139 74146    75.0
Name: new_cases, dtype: float64
74140 74147    108.0
Name: new_cases, dtype: float64
74141 74148    144.0
Name: new_cases, dtype: float64
74142 74149    136.0
Name: new_cases, dtype: float64
74143 74150    202.0
Name: new_cases, dtype: float64
74144 74151    201.0
Name: new_cases, dtype: float64
74145 74152    149.0
Name: new_cases, dtype: float64
74146 74153    331.0
Name: new_cases, dtype: float64
74147 74154    799.0
Name: new_cases, dtype: float64
74148 74155    943.0
Name: new_cases, dtype: float64
74149 74156    1609.0
Name: new_cases, dtype: float64
74150 74157    2169.0
Name: new_cases, dtype: float64
74151 74158    1372.0
Name: new_cases, dtype: float64
74152 74159    1020.0
Name: new_cases, dtype: float64
74153 74160    2844.0
Name: new_cases, dtype: float64
74154 74161    3328.0
Name: new_cases, dtype: float64
74155 74162    3746.0
Name: new_cases, dtype: float64
74156 74163    2964.0
Name: new_cases, dtype: float64
74157 74164    3749.0
Name: new_cases, dtype: float64
74158 74165    1196.0
Name: new_cases, dtype: float64
74159 74166    1596.0
Name: new_cases, dtype: float64
74160 74167    1504.0
Name: new_cases, dtype: float64
74161 74168    3297.0
Name: new_cases, dtype: float64
74162 74169    3286.0
Name: new_cases, dtype: float64
74163 74170    2791.0
Name: new_cases, dtype: float64
74164 74171    2127.0
Name: new_cases, dtype: float64
74165 74172    1354.0
Name: new_cases, dtype: float64
74166 74173    1223.0
Name: new_cases, dtype: float64
74167 74174    2402.0
Name: new_cases, dtype: float64
74168 74175    2216.0
Name: new_cases, dtype: float64
74169 74176    2336.0
Name: new_cases, dtype: float64
74170 74177    2444.0
Name: new_cases, dtype: float64
74171 74178    1667.0
Name: new_cases, dtype: float64
74172 Series([], Name: new_cases, dtype: float64)
74173 Series([], Name: new_cases, dtype: float64)
74174 Series([], Name: new_cases, dtype: float64)
74175 Series([], Name: new_cases, dtype: float64)
74176 Series([], Name: new_cases, dtype: float64)
74177 Series([], Name: new_cases, dtype: float64)
74178 Series([], Name: new_cases, dtype: float64)
77089 77096    4.0
Name: new_cases, dtype: float64
77090 77097    2.0
Name: new_cases, dtype: float64
77091 77098    2.0
Name: new_cases, dtype: float64
77092 77099    0.0
Name: new_cases, dtype: float64
77093 77100    7.0
Name: new_cases, dtype: float64
77094 77101    9.0
Name: new_cases, dtype: float64
77095 77102    4.0
Name: new_cases, dtype: float64
77096 77103    4.0
Name: new_cases, dtype: float64
77097 77104    15.0
Name: new_cases, dtype: float64
77098 77105    22.0
Name: new_cases, dtype: float64
77099 77106    15.0
Name: new_cases, dtype: float64
77100 77107    25.0
Name: new_cases, dtype: float64
77101 77108    13.0
Name: new_cases, dtype: float64
77102 77109    15.0
Name: new_cases, dtype: float64
77103 77110    41.0
Name: new_cases, dtype: float64
77104 77111    17.0
Name: new_cases, dtype: float64
77105 77112    24.0
Name: new_cases, dtype: float64
77106 77113    23.0
Name: new_cases, dtype: float64
77107 77114    36.0
Name: new_cases, dtype: float64
77108 77115    25.0
Name: new_cases, dtype: float64
77109 77116    42.0
Name: new_cases, dtype: float64
77110 77117    29.0
Name: new_cases, dtype: float64
77111 77118    22.0
Name: new_cases, dtype: float64
77112 77119    48.0
Name: new_cases, dtype: float64
77113 77120    12.0
Name: new_cases, dtype: float64
77114 77121    35.0
Name: new_cases, dtype: float64
77115 77122    16.0
Name: new_cases, dtype: float64
77116 77123    24.0
Name: new_cases, dtype: float64
77117 77124    9.0
Name: new_cases, dtype: float64
77118 77125    6.0
Name: new_cases, dtype: float64
77119 77126    29.0
Name: new_cases, dtype: float64
77120 77127    12.0
Name: new_cases, dtype: float64
77121 77128    23.0
Name: new_cases, dtype: float64
77122 77129    18.0
Name: new_cases, dtype: float64
77123 77130    21.0
Name: new_cases, dtype: float64
77124 77131    4.0
Name: new_cases, dtype: float64
77125 77132    2.0
Name: new_cases, dtype: float64

77126 77133    9.0
Name: new_cases, dtype: float64
77127 77134    9.0
Name: new_cases, dtype: float64
77128 77135    7.0
Name: new_cases, dtype: float64
77129 77136    30.0
Name: new_cases, dtype: float64
77130 77137    15.0
Name: new_cases, dtype: float64
77131 77138    12.0
Name: new_cases, dtype: float64
77132 77139    9.0
Name: new_cases, dtype: float64
77133 77140    13.0
Name: new_cases, dtype: float64
77134 77141    17.0
Name: new_cases, dtype: float64
77135 77142    6.0
Name: new_cases, dtype: float64
77136 77143    20.0
Name: new_cases, dtype: float64
77137 77144    8.0
Name: new_cases, dtype: float64
77138 77145    6.0
Name: new_cases, dtype: float64
77139 77146    18.0
Name: new_cases, dtype: float64
77140 77147    13.0
Name: new_cases, dtype: float64
77141 77148    9.0
Name: new_cases, dtype: float64
77142 77149    12.0
Name: new_cases, dtype: float64
77143 77150    1.0
Name: new_cases, dtype: float64
77144 77151    8.0
Name: new_cases, dtype: float64
77145 77152    17.0
Name: new_cases, dtype: float64
77146 77153    0.0
Name: new_cases, dtype: float64
77147 77154    4.0
Name: new_cases, dtype: float64
77148 77155    9.0
Name: new_cases, dtype: float64
77149 77156    19.0
Name: new_cases, dtype: float64
77150 77157    2.0
Name: new_cases, dtype: float64
77151 77158    9.0
Name: new_cases, dtype: float64
77152 77159    7.0
Name: new_cases, dtype: float64
77153 77160    4.0
Name: new_cases, dtype: float64
77154 77161    1.0
Name: new_cases, dtype: float64
77155 77162    11.0
Name: new_cases, dtype: float64
77156 77163    8.0
Name: new_cases, dtype: float64
77157 77164    27.0
Name: new_cases, dtype: float64
77158 77165    11.0
Name: new_cases, dtype: float64
77159 77166    1.0
Name: new_cases, dtype: float64
77160 77167    3.0
Name: new_cases, dtype: float64
77161 77168    4.0
Name: new_cases, dtype: float64
77162 77169    9.0
Name: new_cases, dtype: float64
77163 77170    5.0
Name: new_cases, dtype: float64
77164 77171    16.0
Name: new_cases, dtype: float64
77165 77172    1.0
Name: new_cases, dtype: float64
77166 77173    2.0
Name: new_cases, dtype: float64
77167 77174    4.0
Name: new_cases, dtype: float64
77168 77175    4.0
Name: new_cases, dtype: float64
77169 77176    4.0
Name: new_cases, dtype: float64
77170 77177    3.0
Name: new_cases, dtype: float64
77171 77178    1.0
Name: new_cases, dtype: float64
77172 77179    1.0
Name: new_cases, dtype: float64
77173 77180    0.0
Name: new_cases, dtype: float64
77174 77181    5.0
Name: new_cases, dtype: float64
77175 77182    8.0
Name: new_cases, dtype: float64
77176 77183    3.0
Name: new_cases, dtype: float64
77177 77184    3.0
Name: new_cases, dtype: float64
77178 77185    1.0
Name: new_cases, dtype: float64
77179 77186    2.0
Name: new_cases, dtype: float64
77180 77187    0.0
Name: new_cases, dtype: float64
77181 77188    1.0
Name: new_cases, dtype: float64
77182 77189    3.0
Name: new_cases, dtype: float64
77183 77190    2.0
Name: new_cases, dtype: float64
77184 77191    2.0
Name: new_cases, dtype: float64
77185 77192    1.0
Name: new_cases, dtype: float64
77186 77193    0.0
Name: new_cases, dtype: float64
77187 77194    0.0
Name: new_cases, dtype: float64
77188 77195    1.0
Name: new_cases, dtype: float64
77189 77196    6.0
Name: new_cases, dtype: float64
77190 77197    4.0
Name: new_cases, dtype: float64
77191 77198    2.0
Name: new_cases, dtype: float64
77192 77199    1.0
Name: new_cases, dtype: float64
77193 77200    0.0
Name: new_cases, dtype: float64
77194 77201    0.0
Name: new_cases, dtype: float64
77195 77202    0.0
Name: new_cases, dtype: float64
77196 77203    0.0
Name: new_cases, dtype: float64
77197 77204    0.0
Name: new_cases, dtype: float64
77198 77205    1.0
Name: new_cases, dtype: float64
77199 77206    3.0
Name: new_cases, dtype: float64
77200 77207    1.0
Name: new_cases, dtype: float64
77201 77208    1.0
Name: new_cases, dtype: float64
77202 77209    1.0
Name: new_cases, dtype: float64
77203 77210    3.0
Name: new_cases, dtype: float64
77204 77211    1.0
Name: new_cases, dtype: float64
77205 77212    0.0
Name: new_cases, dtype: float64
77206 77213    1.0
Name: new_cases, dtype: float64
77207 77214    1.0
Name: new_cases, dtype: float64
77208 77215    3.0
Name: new_cases, dtype: float64
77209 77216    7.0
Name: new_cases, dtype: float64
77210 77217    7.0
Name: new_cases, dtype: float64
77211 77218    13.0
Name: new_cases, dtype: float64
77212 77219    11.0
Name: new_cases, dtype: float64
77213 77220    8.0
Name: new_cases, dtype: float64
77214 77221    0.0
Name: new_cases, dtype: float64
77215 77222    1.0
Name: new_cases, dtype: float64
77216 77223    0.0
Name: new_cases, dtype: float64
77217 77224    4.0
Name: new_cases, dtype: float64
77218 77225    1.0
Name: new_cases, dtype: float64
77219 77226    6.0
Name: new_cases, dtype: float64
77220 77227    4.0
Name: new_cases, dtype: float64
77221 77228    3.0
Name: new_cases, dtype: float64
77222 77229    0.0
Name: new_cases, dtype: float64
77223 77230    1.0
Name: new_cases, dtype: float64
77224 77231    4.0
Name: new_cases, dtype: float64
77225 77232    6.0
Name: new_cases, dtype: float64
77226 77233    2.0
Name: new_cases, dtype: float64
77227 77234    1.0
Name: new_cases, dtype: float64
77228 77235    13.0
Name: new_cases, dtype: float64
77229 77236    0.0
Name: new_cases, dtype: float64
77230 77237    1.0
Name: new_cases, dtype: float64
77231 77238    4.0
Name: new_cases, dtype: float64
77232 77239    4.0
Name: new_cases, dtype: float64
77233 77240    3.0
Name: new_cases, dtype: float64
77234 77241    7.0
Name: new_cases, dtype: float64
77235 77242    5.0
Name: new_cases, dtype: float64
77236 77243    3.0
Name: new_cases, dtype: float64
77237 77244    3.0
Name: new_cases, dtype: float64
77238 77245    8.0
Name: new_cases, dtype: float64
77239 77246    18.0
Name: new_cases, dtype: float64
77240 77247    6.0
Name: new_cases, dtype: float64
77241 77248    7.0
Name: new_cases, dtype: float64
77242 77249    2.0
Name: new_cases, dtype: float64
77243 77250    0.0
Name: new_cases, dtype: float64
77244 77251    3.0
Name: new_cases, dtype: float64
77245 77252    10.0
Name: new_cases, dtype: float64
77246 77253    4.0
Name: new_cases, dtype: float64
77247 77254    1.0
Name: new_cases, dtype: float64
77248 77255    7.0
Name: new_cases, dtype: float64
77249 77256    7.0
Name: new_cases, dtype: float64
77250 77257    1.0
Name: new_cases, dtype: float64
77251 77258    0.0
Name: new_cases, dtype: float64
77252 77259    3.0
Name: new_cases, dtype: float64
77253 77260    1.0
Name: new_cases, dtype: float64
77254 77261    3.0
Name: new_cases, dtype: float64
77255 77262    3.0
Name: new_cases, dtype: float64
77256 77263    4.0
Name: new_cases, dtype: float64
77257 77264    0.0
Name: new_cases, dtype: float64
77258 77265    5.0
Name: new_cases, dtype: float64
77259 77266    18.0
Name: new_cases, dtype: float64
77260 77267    6.0
Name: new_cases, dtype: float64
77261 77268    9.0
Name: new_cases, dtype: float64
77262 77269    6.0
Name: new_cases, dtype: float64
77263 77270    12.0
Name: new_cases, dtype: float64
77264 77271    3.0
Name: new_cases, dtype: float64
77265 77272    8.0
Name: new_cases, dtype: float64
77266 77273    2.0
Name: new_cases, dtype: float64
77267 77274    4.0
Name: new_cases, dtype: float64
77268 77275    6.0
Name: new_cases, dtype: float64
77269 77276    9.0
Name: new_cases, dtype: float64
77270 77277    3.0
Name: new_cases, dtype: float64
77271 77278    1.0
Name: new_cases, dtype: float64
77272 77279    3.0
Name: new_cases, dtype: float64
77273 77280    11.0
Name: new_cases, dtype: float64
77274 77281    5.0
Name: new_cases, dtype: float64
77275 77282    11.0
Name: new_cases, dtype: float64
77276 77283    5.0
Name: new_cases, dtype: float64
77277 77284    10.0
Name: new_cases, dtype: float64
77278 77285    3.0
Name: new_cases, dtype: float64
77279 77286    5.0
Name: new_cases, dtype: float64
77280 77287    4.0
Name: new_cases, dtype: float64
77281 77288    8.0
Name: new_cases, dtype: float64
77282 77289    4.0
Name: new_cases, dtype: float64
77283 77290    17.0
Name: new_cases, dtype: float64
77284 77291    10.0
Name: new_cases, dtype: float64
77285 77292    1.0
Name: new_cases, dtype: float64
77286 77293    34.0
Name: new_cases, dtype: float64
77287 77294    12.0
Name: new_cases, dtype: float64

77288 77295    22.0
Name: new_cases, dtype: float64
77289 77296    31.0
Name: new_cases, dtype: float64
77290 77297    29.0
Name: new_cases, dtype: float64
77291 77298    22.0
Name: new_cases, dtype: float64
77292 77299    21.0
Name: new_cases, dtype: float64
77293 77300    32.0
Name: new_cases, dtype: float64
77294 77301    95.0
Name: new_cases, dtype: float64
77295 77302    44.0
Name: new_cases, dtype: float64
77296 77303    77.0
Name: new_cases, dtype: float64
77297 77304    74.0
Name: new_cases, dtype: float64
77298 77305    67.0
Name: new_cases, dtype: float64
77299 77306    40.0
Name: new_cases, dtype: float64
77300 77307    68.0
Name: new_cases, dtype: float64
77301 77308    67.0
Name: new_cases, dtype: float64
77302 77309    109.0
Name: new_cases, dtype: float64
77303 77310    137.0
Name: new_cases, dtype: float64
77304 77311    89.0
Name: new_cases, dtype: float64
77305 77312    74.0
Name: new_cases, dtype: float64
77306 77313    95.0
Name: new_cases, dtype: float64
77307 77314    75.0
Name: new_cases, dtype: float64
77308 77315    102.0
Name: new_cases, dtype: float64
77309 77316    114.0
Name: new_cases, dtype: float64
77310 77317    148.0
Name: new_cases, dtype: float64
77311 77318    188.0
Name: new_cases, dtype: float64
77312 77319    58.0
Name: new_cases, dtype: float64
77313 77320    44.0
Name: new_cases, dtype: float64
77314 77321    115.0
Name: new_cases, dtype: float64
77315 77322    188.0
Name: new_cases, dtype: float64
77316 77323    161.0
Name: new_cases, dtype: float64
77317 77324    250.0
Name: new_cases, dtype: float64
77318 77325    259.0
Name: new_cases, dtype: float64
77319 77326    211.0
Name: new_cases, dtype: float64
77320 77327    79.0
Name: new_cases, dtype: float64
77321 77328    136.0
Name: new_cases, dtype: float64
77322 77329    251.0
Name: new_cases, dtype: float64
77323 77330    251.0
Name: new_cases, dtype: float64
77324 77331    284.0
Name: new_cases, dtype: float64
77325 77332    215.0
Name: new_cases, dtype: float64
77326 77333    242.0
Name: new_cases, dtype: float64
77327 77334    132.0
Name: new_cases, dtype: float64
77328 77335    171.0
Name: new_cases, dtype: float64
77329 77336    313.0
Name: new_cases, dtype: float64
77330 77337    367.0
Name: new_cases, dtype: float64
77331 77338    357.0
Name: new_cases, dtype: float64
77332 77339    404.0
Name: new_cases, dtype: float64
77333 77340    215.0
Name: new_cases, dtype: float64
77334 77341    92.0
Name: new_cases, dtype: float64
77335 77342    208.0
Name: new_cases, dtype: float64
77336 77343    453.0
Name: new_cases, dtype: float64
77337 77344    533.0
Name: new_cases, dtype: float64
77338 77345    455.0
Name: new_cases, dtype: float64
77339 77346    395.0
Name: new_cases, dtype: float64
77340 77347    316.0
Name: new_cases, dtype: float64
77341 77348    89.0
Name: new_cases, dtype: float64
77342 77349    278.0
Name: new_cases, dtype: float64
77343 77350    442.0
Name: new_cases, dtype: float64
77344 77351    366.0
Name: new_cases, dtype: float64
77345 77352    380.0
Name: new_cases, dtype: float64
77346 77353    642.0
Name: new_cases, dtype: float64
77347 77354    376.0
Name: new_cases, dtype: float64
77348 77355    116.0
Name: new_cases, dtype: float64
77349 77356    457.0
Name: new_cases, dtype: float64
77350 77357    580.0
Name: new_cases, dtype: float64
77351 77358    898.0
Name: new_cases, dtype: float64
77352 77359    637.0
Name: new_cases, dtype: float64
77353 77360    753.0
Name: new_cases, dtype: float64
77354 77361    414.0
Name: new_cases, dtype: float64
77355 77362    100.0
Name: new_cases, dtype: float64
77356 77363    612.0
Name: new_cases, dtype: float64
77357 77364    690.0
Name: new_cases, dtype: float64
77358 77365    930.0
Name: new_cases, dtype: float64
77359 77366    686.0
Name: new_cases, dtype: float64
77360 77367    794.0
Name: new_cases, dtype: float64
77361 77368    526.0
Name: new_cases, dtype: float64
77362 77369    207.0
Name: new_cases, dtype: float64
77363 77370    584.0
Name: new_cases, dtype: float64
77364 77371    712.0
Name: new_cases, dtype: float64
77365 77372    890.0
Name: new_cases, dtype: float64
77366 77373    680.0
Name: new_cases, dtype: float64
77367 77374    660.0
Name: new_cases, dtype: float64
77368 77375    629.0
Name: new_cases, dtype: float64
77369 77376    210.0
Name: new_cases, dtype: float64
77370 77377    587.0
Name: new_cases, dtype: float64
77371 77378    1023.0
Name: new_cases, dtype: float64
77372 77379    1040.0
Name: new_cases, dtype: float64
77373 77380    892.0
Name: new_cases, dtype: float64
77374 77381    870.0
Name: new_cases, dtype: float64
77375 77382    643.0
Name: new_cases, dtype: float64
77376 77383    395.0
Name: new_cases, dtype: float64
77377 77384    1004.0
Name: new_cases, dtype: float64
77378 77385    1145.0
Name: new_cases, dtype: float64
77379 77386    1270.0
Name: new_cases, dtype: float64
77380 77387    666.0
Name: new_cases, dtype: float64
77381 77388    399.0
Name: new_cases, dtype: float64
77382 77389    511.0
Name: new_cases, dtype: float64
77383 77390    508.0
Name: new_cases, dtype: float64
77384 77391    838.0
Name: new_cases, dtype: float64
77385 77392    1367.0
Name: new_cases, dtype: float64
77386 77393    1861.0
Name: new_cases, dtype: float64
77387 77394    711.0
Name: new_cases, dtype: float64
77388 77395    314.0
Name: new_cases, dtype: float64
77389 77396    568.0
Name: new_cases, dtype: float64
77390 77397    621.0
Name: new_cases, dtype: float64
77391 77398    824.0
Name: new_cases, dtype: float64
77392 77399    1229.0
Name: new_cases, dtype: float64
77393 77400    1374.0
Name: new_cases, dtype: float64
77394 77401    1237.0
Name: new_cases, dtype: float64
77395 77402    1170.0
Name: new_cases, dtype: float64
77396 77403    616.0
Name: new_cases, dtype: float64
77397 77404    331.0
Name: new_cases, dtype: float64
77398 77405    878.0
Name: new_cases, dtype: float64
77399 77406    1255.0
Name: new_cases, dtype: float64
77400 77407    950.0
Name: new_cases, dtype: float64
77401 77408    1084.0
Name: new_cases, dtype: float64
77402 77409    1031.0
Name: new_cases, dtype: float64
77403 77410    567.0
Name: new_cases, dtype: float64
77404 77411    244.0
Name: new_cases, dtype: float64
77405 77412    812.0
Name: new_cases, dtype: float64
77406 77413    1088.0
Name: new_cases, dtype: float64
77407 77414    902.0
Name: new_cases, dtype: float64
77408 77415    876.0
Name: new_cases, dtype: float64
77409 77416    910.0
Name: new_cases, dtype: float64
77410 77417    512.0
Name: new_cases, dtype: float64
77411 77418    223.0
Name: new_cases, dtype: float64
77412 77419    693.0
Name: new_cases, dtype: float64
77413 77420    1103.0
Name: new_cases, dtype: float64
77414 77421    965.0
Name: new_cases, dtype: float64
77415 77422    931.0
Name: new_cases, dtype: float64
77416 77423    785.0
Name: new_cases, dtype: float64
77417 77424    533.0
Name: new_cases, dtype: float64
77418 77425    411.0
Name: new_cases, dtype: float64
77419 77426    775.0
Name: new_cases, dtype: float64
77420 77427    1231.0
Name: new_cases, dtype: float64
77421 77428    742.0
Name: new_cases, dtype: float64
77422 77429    876.0
Name: new_cases, dtype: float64
77423 77430    1044.0
Name: new_cases, dtype: float64
77424 77431    480.0
Name: new_cases, dtype: float64
77425 77432    288.0
Name: new_cases, dtype: float64
77426 77433    781.0
Name: new_cases, dtype: float64
77427 77434    990.0
Name: new_cases, dtype: float64
77428 77435    842.0
Name: new_cases, dtype: float64
77429 77436    808.0
Name: new_cases, dtype: float64
77430 77437    773.0
Name: new_cases, dtype: float64
77431 77438    424.0
Name: new_cases, dtype: float64
77432 77439    278.0
Name: new_cases, dtype: float64
77433 77440    713.0
Name: new_cases, dtype: float64
77434 77441    946.0
Name: new_cases, dtype: float64
77435 77442    708.0
Name: new_cases, dtype: float64
77436 77443    689.0
Name: new_cases, dtype: float64
77437 77444    1069.0
Name: new_cases, dtype: float64
77438 77445    410.0
Name: new_cases, dtype: float64
77439 77446    274.0
Name: new_cases, dtype: float64
77440 77447    669.0
Name: new_cases, dtype: float64
77441 77448    983.0
Name: new_cases, dtype: float64
77442 77449    813.0
Name: new_cases, dtype: float64
77443 77450    725.0
Name: new_cases, dtype: float64

77444 77451    827.0
Name: new_cases, dtype: float64
77445 77452    376.0
Name: new_cases, dtype: float64
77446 77453    272.0
Name: new_cases, dtype: float64
77447 77454    645.0
Name: new_cases, dtype: float64
77448 77455    919.0
Name: new_cases, dtype: float64
77449 77456    646.0
Name: new_cases, dtype: float64
77450 77457    746.0
Name: new_cases, dtype: float64
77451 77458    595.0
Name: new_cases, dtype: float64
77452 77459    322.0
Name: new_cases, dtype: float64
77453 77460    194.0
Name: new_cases, dtype: float64
77454 77461    472.0
Name: new_cases, dtype: float64
77455 77462    639.0
Name: new_cases, dtype: float64
77456 77463    638.0
Name: new_cases, dtype: float64
77457 77464    632.0
Name: new_cases, dtype: float64
77458 77465    578.0
Name: new_cases, dtype: float64
77459 77466    297.0
Name: new_cases, dtype: float64
77460 77467    178.0
Name: new_cases, dtype: float64
77461 77468    643.0
Name: new_cases, dtype: float64
77462 77469    818.0
Name: new_cases, dtype: float64
77463 77470    482.0
Name: new_cases, dtype: float64
77464 77471    622.0
Name: new_cases, dtype: float64
77465 77472    625.0
Name: new_cases, dtype: float64
77466 77473    260.0
Name: new_cases, dtype: float64
77467 77474    177.0
Name: new_cases, dtype: float64
77468 77475    508.0
Name: new_cases, dtype: float64
77469 77476    776.0
Name: new_cases, dtype: float64
77470 77477    606.0
Name: new_cases, dtype: float64
77471 77478    638.0
Name: new_cases, dtype: float64
77472 77479    602.0
Name: new_cases, dtype: float64
77473 77480    324.0
Name: new_cases, dtype: float64
77474 77481    167.0
Name: new_cases, dtype: float64
77475 77482    526.0
Name: new_cases, dtype: float64
77476 77483    630.0
Name: new_cases, dtype: float64
77477 77484    638.0
Name: new_cases, dtype: float64
77478 77485    587.0
Name: new_cases, dtype: float64
77479 77486    279.0
Name: new_cases, dtype: float64
77480 77487    238.0
Name: new_cases, dtype: float64
77481 77488    119.0
Name: new_cases, dtype: float64
77482 77489    309.0
Name: new_cases, dtype: float64
77483 77490    643.0
Name: new_cases, dtype: float64
77484 77491    740.0
Name: new_cases, dtype: float64
77485 77492    658.0
Name: new_cases, dtype: float64
77486 77493    666.0
Name: new_cases, dtype: float64
77487 77494    368.0
Name: new_cases, dtype: float64
77488 77495    210.0
Name: new_cases, dtype: float64
77489 77496    537.0
Name: new_cases, dtype: float64
77490 77497    733.0
Name: new_cases, dtype: float64
77491 77498    643.0
Name: new_cases, dtype: float64
77492 77499    612.0
Name: new_cases, dtype: float64
77493 77500    654.0
Name: new_cases, dtype: float64
77494 77501    337.0
Name: new_cases, dtype: float64
77495 77502    202.0
Name: new_cases, dtype: float64
77496 77503    688.0
Name: new_cases, dtype: float64
77497 77504    759.0
Name: new_cases, dtype: float64
77498 77505    578.0
Name: new_cases, dtype: float64
77499 77506    683.0
Name: new_cases, dtype: float64
77500 77507    711.0
Name: new_cases, dtype: float64
77501 77508    361.0
Name: new_cases, dtype: float64
77502 77509    220.0
Name: new_cases, dtype: float64
77503 77510    596.0
Name: new_cases, dtype: float64
77504 77511    967.0
Name: new_cases, dtype: float64
77505 77512    696.0
Name: new_cases, dtype: float64
77506 77513    763.0
Name: new_cases, dtype: float64
77507 77514    812.0
Name: new_cases, dtype: float64
77508 77515    380.0
Name: new_cases, dtype: float64
77509 77516    203.0
Name: new_cases, dtype: float64
77510 77517    425.0
Name: new_cases, dtype: float64
77511 77518    358.0
Name: new_cases, dtype: float64
77512 77519    773.0
Name: new_cases, dtype: float64
77513 77520    1036.0
Name: new_cases, dtype: float64
77514 77521    786.0
Name: new_cases, dtype: float64
77515 77522    632.0
Name: new_cases, dtype: float64
77516 77523    338.0
Name: new_cases, dtype: float64
77517 77524    659.0
Name: new_cases, dtype: float64
77518 77525    729.0
Name: new_cases, dtype: float64
77519 77526    689.0
Name: new_cases, dtype: float64
77520 77527    675.0
Name: new_cases, dtype: float64
77521 77528    544.0
Name: new_cases, dtype: float64
77522 77529    381.0
Name: new_cases, dtype: float64
77523 77530    147.0
Name: new_cases, dtype: float64
77524 77531    563.0
Name: new_cases, dtype: float64
77525 77532    609.0
Name: new_cases, dtype: float64
77526 77533    497.0
Name: new_cases, dtype: float64
77527 77534    477.0
Name: new_cases, dtype: float64
77528 77535    441.0
Name: new_cases, dtype: float64
77529 77536    233.0
Name: new_cases, dtype: float64
77530 77537    134.0
Name: new_cases, dtype: float64
77531 77538    435.0
Name: new_cases, dtype: float64
77532 77539    396.0
Name: new_cases, dtype: float64
77533 77540    348.0
Name: new_cases, dtype: float64
77534 77541    354.0
Name: new_cases, dtype: float64
77535 77542    306.0
Name: new_cases, dtype: float64
77536 77543    180.0
Name: new_cases, dtype: float64
77537 77544    101.0
Name: new_cases, dtype: float64
77538 77545    319.0
Name: new_cases, dtype: float64
77539 77546    348.0
Name: new_cases, dtype: float64
77540 77547    296.0
Name: new_cases, dtype: float64
77541 77548    259.0
Name: new_cases, dtype: float64
77542 77549    256.0
Name: new_cases, dtype: float64
77543 77550    135.0
Name: new_cases, dtype: float64
77544 77551    76.0
Name: new_cases, dtype: float64
77545 77552    256.0
Name: new_cases, dtype: float64
77546 77553    244.0
Name: new_cases, dtype: float64
77547 77554    196.0
Name: new_cases, dtype: float64
77548 77555    178.0
Name: new_cases, dtype: float64
77549 77556    178.0
Name: new_cases, dtype: float64
77550 77557    90.0
Name: new_cases, dtype: float64
77551 77558    74.0
Name: new_cases, dtype: float64
77552 77559    143.0
Name: new_cases, dtype: float64
77553 77560    156.0
Name: new_cases, dtype: float64
77554 77561    141.0
Name: new_cases, dtype: float64
77555 77562    108.0
Name: new_cases, dtype: float64
77556 77563    84.0
Name: new_cases, dtype: float64
77557 77564    74.0
Name: new_cases, dtype: float64
77558 77565    40.0
Name: new_cases, dtype: float64
77559 77566    125.0
Name: new_cases, dtype: float64
77560 77567    102.0
Name: new_cases, dtype: float64
77561 77568    33.0
Name: new_cases, dtype: float64
77562 77569    20.0
Name: new_cases, dtype: float64
77563 77570    39.0
Name: new_cases, dtype: float64
77564 77571    41.0
Name: new_cases, dtype: float64
77565 77572    30.0
Name: new_cases, dtype: float64
77566 77573    89.0
Name: new_cases, dtype: float64
77567 77574    100.0
Name: new_cases, dtype: float64
77568 77575    71.0
Name: new_cases, dtype: float64
77569 77576    40.0
Name: new_cases, dtype: float64
77570 77577    60.0
Name: new_cases, dtype: float64
77571 77578    31.0
Name: new_cases, dtype: float64
77572 77579    22.0
Name: new_cases, dtype: float64
77573 77580    46.0
Name: new_cases, dtype: float64
77574 77581    48.0
Name: new_cases, dtype: float64
77575 77582    50.0
Name: new_cases, dtype: float64
77576 77583    34.0
Name: new_cases, dtype: float64
77577 77584    32.0
Name: new_cases, dtype: float64
77578 77585    36.0
Name: new_cases, dtype: float64
77579 77586    18.0
Name: new_cases, dtype: float64
77580 77587    53.0
Name: new_cases, dtype: float64
77581 77588    34.0
Name: new_cases, dtype: float64
77582 77589    37.0
Name: new_cases, dtype: float64
77583 77590    46.0
Name: new_cases, dtype: float64
77584 77591    39.0
Name: new_cases, dtype: float64
77585 77592    33.0
Name: new_cases, dtype: float64
77586 77593    25.0
Name: new_cases, dtype: float64
77587 77594    54.0
Name: new_cases, dtype: float64
77588 77595    62.0
Name: new_cases, dtype: float64
77589 77596    44.0
Name: new_cases, dtype: float64
77590 77597    38.0
Name: new_cases, dtype: float64
77591 77598    43.0
Name: new_cases, dtype: float64
77592 77599    56.0
Name: new_cases, dtype: float64
77593 77600    23.0
Name: new_cases, dtype: float64
77594 77601    68.0
Name: new_cases, dtype: float64
77595 77602    78.0
Name: new_cases, dtype: float64
77596 77603    67.0
Name: new_cases, dtype: float64
77597 77604    82.0
Name: new_cases, dtype: float64
77598 77605    64.0
Name: new_cases, dtype: float64
77599 77606    36.0
Name: new_cases, dtype: float64
77600 77607    26.0
Name: new_cases, dtype: float64
77601 77608    112.0
Name: new_cases, dtype: float64
77602 77609    97.0
Name: new_cases, dtype: float64
77603 77610    70.0
Name: new_cases, dtype: float64

77604 77611    80.0
Name: new_cases, dtype: float64
77605 77612    63.0
Name: new_cases, dtype: float64
77606 77613    74.0
Name: new_cases, dtype: float64
77607 77614    41.0
Name: new_cases, dtype: float64
77608 77615    125.0
Name: new_cases, dtype: float64
77609 77616    120.0
Name: new_cases, dtype: float64
77610 77617    107.0
Name: new_cases, dtype: float64
77611 77618    127.0
Name: new_cases, dtype: float64
77612 77619    108.0
Name: new_cases, dtype: float64
77613 77620    73.0
Name: new_cases, dtype: float64
77614 77621    49.0
Name: new_cases, dtype: float64
77615 77622    154.0
Name: new_cases, dtype: float64
77616 77623    180.0
Name: new_cases, dtype: float64
77617 77624    146.0
Name: new_cases, dtype: float64
77618 77625    133.0
Name: new_cases, dtype: float64
77619 77626    160.0
Name: new_cases, dtype: float64
77620 77627    101.0
Name: new_cases, dtype: float64
77621 77628    73.0
Name: new_cases, dtype: float64
77622 77629    169.0
Name: new_cases, dtype: float64
77623 77630    249.0
Name: new_cases, dtype: float64
77624 77631    150.0
Name: new_cases, dtype: float64
77625 77632    181.0
Name: new_cases, dtype: float64
77626 77633    256.0
Name: new_cases, dtype: float64
77627 77634    196.0
Name: new_cases, dtype: float64
77628 77635    81.0
Name: new_cases, dtype: float64
77629 77636    237.0
Name: new_cases, dtype: float64
77630 77637    469.0
Name: new_cases, dtype: float64
77631 77638    340.0
Name: new_cases, dtype: float64
77632 77639    354.0
Name: new_cases, dtype: float64
77633 77640    360.0
Name: new_cases, dtype: float64
77634 77641    358.0
Name: new_cases, dtype: float64
77635 77642    114.0
Name: new_cases, dtype: float64
77636 77643    311.0
Name: new_cases, dtype: float64
77637 77644    459.0
Name: new_cases, dtype: float64
77638 77645    491.0
Name: new_cases, dtype: float64
77639 77646    488.0
Name: new_cases, dtype: float64
77640 77647    419.0
Name: new_cases, dtype: float64
77641 77648    393.0
Name: new_cases, dtype: float64
77642 77649    135.0
Name: new_cases, dtype: float64
77643 77650    460.0
Name: new_cases, dtype: float64
77644 77651    697.0
Name: new_cases, dtype: float64
77645 77652    596.0
Name: new_cases, dtype: float64
77646 77653    533.0
Name: new_cases, dtype: float64
77647 77654    542.0
Name: new_cases, dtype: float64
77648 77655    404.0
Name: new_cases, dtype: float64
77649 77656    189.0
Name: new_cases, dtype: float64
77650 77657    494.0
Name: new_cases, dtype: float64
77651 77658    674.0
Name: new_cases, dtype: float64
77652 77659    776.0
Name: new_cases, dtype: float64
77653 77660    710.0
Name: new_cases, dtype: float64
77654 77661    816.0
Name: new_cases, dtype: float64
77655 77662    567.0
Name: new_cases, dtype: float64
77656 77663    290.0
Name: new_cases, dtype: float64
77657 77664    804.0
Name: new_cases, dtype: float64
77658 77665    1203.0
Name: new_cases, dtype: float64
77659 77666    1208.0
Name: new_cases, dtype: float64
77660 77667    1127.0
Name: new_cases, dtype: float64
77661 77668    1190.0
Name: new_cases, dtype: float64
77662 77669    1033.0
Name: new_cases, dtype: float64
77663 77670    479.0
Name: new_cases, dtype: float64
77664 77671    1010.0
Name: new_cases, dtype: float64
77665 77672    1671.0
Name: new_cases, dtype: float64
77666 77673    1752.0
Name: new_cases, dtype: float64
77667 77674    1695.0
Name: new_cases, dtype: float64
77668 77675    1669.0
Name: new_cases, dtype: float64
77669 77676    1359.0
Name: new_cases, dtype: float64
77670 77677    1002.0
Name: new_cases, dtype: float64
77671 77678    1376.0
Name: new_cases, dtype: float64
77672 77679    2236.0
Name: new_cases, dtype: float64
77673 77680    2408.0
Name: new_cases, dtype: float64
77674 77681    2142.0
Name: new_cases, dtype: float64
77675 77682    2799.0
Name: new_cases, dtype: float64
77676 77683    2375.0
Name: new_cases, dtype: float64
77677 77684    1255.0
Name: new_cases, dtype: float64
77678 77685    1853.0
Name: new_cases, dtype: float64
77679 77686    2599.0
Name: new_cases, dtype: float64
77680 77687    2935.0
Name: new_cases, dtype: float64
77681 77688    3133.0
Name: new_cases, dtype: float64
77682 77689    2932.0
Name: new_cases, dtype: float64
77683 77690    2252.0
Name: new_cases, dtype: float64
77684 77691    887.0
Name: new_cases, dtype: float64
77685 77692    2117.0
Name: new_cases, dtype: float64
77686 77693    3206.0
Name: new_cases, dtype: float64
77687 77694    2919.0
Name: new_cases, dtype: float64
77688 77695    2758.0
Name: new_cases, dtype: float64
77689 77696    2879.0
Name: new_cases, dtype: float64
77690 77697    1800.0
Name: new_cases, dtype: float64
77691 77698    772.0
Name: new_cases, dtype: float64
77692 77699    1884.0
Name: new_cases, dtype: float64
77693 77700    2718.0
Name: new_cases, dtype: float64
77694 77701    2347.0
Name: new_cases, dtype: float64
77695 77702    1821.0
Name: new_cases, dtype: float64
77696 77703    1888.0
Name: new_cases, dtype: float64
77697 77704    1255.0
Name: new_cases, dtype: float64
77698 77705    423.0
Name: new_cases, dtype: float64
77699 77706    1451.0
Name: new_cases, dtype: float64
77700 77707    1689.0
Name: new_cases, dtype: float64
77701 77708    1378.0
Name: new_cases, dtype: float64
77702 77709    1388.0
Name: new_cases, dtype: float64
77703 77710    1422.0
Name: new_cases, dtype: float64
77704 77711    765.0
Name: new_cases, dtype: float64
77705 77712    422.0
Name: new_cases, dtype: float64
77706 77713    1077.0
Name: new_cases, dtype: float64
77707 77714    1501.0
Name: new_cases, dtype: float64
77708 77715    1221.0
Name: new_cases, dtype: float64
77709 77716    445.0
Name: new_cases, dtype: float64
77710 77717    617.0
Name: new_cases, dtype: float64
77711 77718    493.0
Name: new_cases, dtype: float64
77712 77719    349.0
Name: new_cases, dtype: float64
77713 77720    1293.0
Name: new_cases, dtype: float64
77714 77721    1279.0
Name: new_cases, dtype: float64
77715 77722    1095.0
Name: new_cases, dtype: float64
77716 77723    874.0
Name: new_cases, dtype: float64
77717 77724    919.0
Name: new_cases, dtype: float64
77718 77725    488.0
Name: new_cases, dtype: float64
77719 77726    315.0
Name: new_cases, dtype: float64
77720 77727    931.0
Name: new_cases, dtype: float64
77721 77728    1031.0
Name: new_cases, dtype: float64
77722 77729    712.0
Name: new_cases, dtype: float64
77723 77730    723.0
Name: new_cases, dtype: float64
77724 77731    727.0
Name: new_cases, dtype: float64
77725 77732    477.0
Name: new_cases, dtype: float64
77726 77733    230.0
Name: new_cases, dtype: float64
77727 77734    860.0
Name: new_cases, dtype: float64
77728 77735    796.0
Name: new_cases, dtype: float64
77729 77736    793.0
Name: new_cases, dtype: float64
77730 77737    650.0
Name: new_cases, dtype: float64
77731 77738    805.0
Name: new_cases, dtype: float64
77732 77739    481.0
Name: new_cases, dtype: float64
77733 77740    271.0
Name: new_cases, dtype: float64
77734 77741    930.0
Name: new_cases, dtype: float64
77735 77742    886.0
Name: new_cases, dtype: float64
77736 77743    934.0
Name: new_cases, dtype: float64
77737 77744    841.0
Name: new_cases, dtype: float64
77738 77745    910.0
Name: new_cases, dtype: float64
77739 77746    423.0
Name: new_cases, dtype: float64
77740 77747    326.0
Name: new_cases, dtype: float64
77741 77748    991.0
Name: new_cases, dtype: float64
77742 77749    748.0
Name: new_cases, dtype: float64
77743 77750    954.0
Name: new_cases, dtype: float64
77744 77751    948.0
Name: new_cases, dtype: float64
77745 77752    122.0
Name: new_cases, dtype: float64
77746 77753    203.0
Name: new_cases, dtype: float64
77747 77754    335.0
Name: new_cases, dtype: float64
77748 77755    1186.0
Name: new_cases, dtype: float64
77749 77756    1319.0
Name: new_cases, dtype: float64
77750 77757    1246.0
Name: new_cases, dtype: float64
77751 77758    1157.0
Name: new_cases, dtype: float64
77752 77759    167.0
Name: new_cases, dtype: float64
77753 77760    180.0
Name: new_cases, dtype: float64
77754 77761    671.0
Name: new_cases, dtype: float64
77755 77762    1628.0
Name: new_cases, dtype: float64
77756 77763    1835.0
Name: new_cases, dtype: float64
77757 77764    1994.0
Name: new_cases, dtype: float64
77758 77765    1877.0
Name: new_cases, dtype: float64
77759 77766    1815.0
Name: new_cases, dtype: float64
77760 Series([], Name: new_cases, dtype: float64)
77761 Series([], Name: new_cases, dtype: float64)
77762 77089    1.0
Name: new_cases, dtype: float64
77763 77090    0.0
Name: new_cases, dtype: float64
77764 77091    0.0
Name: new_cases, dtype: float64
77765 77092    0.0
Name: new_cases, dtype: float64
77766 77093    0.0
Name: new_cases, dtype: float64
81076 81083    0.0
Name: new_cases, dtype: float64
81077 81084    0.0
Name: new_cases, dtype: float64
81078 81085    0.0
Name: new_cases, dtype: float64
81079 81086    0.0
Name: new_cases, dtype: float64
81080 81087    2.0
Name: new_cases, dtype: float64
81081 81088    0.0
Name: new_cases, dtype: float64

81082 81089    1.0
Name: new_cases, dtype: float64
81083 81090    2.0
Name: new_cases, dtype: float64
81084 81091    3.0
Name: new_cases, dtype: float64
81085 81092    3.0
Name: new_cases, dtype: float64
81086 81093    7.0
Name: new_cases, dtype: float64
81087 81094    8.0
Name: new_cases, dtype: float64
81088 81095    9.0
Name: new_cases, dtype: float64
81089 81096    11.0
Name: new_cases, dtype: float64
81090 81097    22.0
Name: new_cases, dtype: float64
81091 81098    42.0
Name: new_cases, dtype: float64
81092 81099    17.0
Name: new_cases, dtype: float64
81093 81100    38.0
Name: new_cases, dtype: float64
81094 81101    42.0
Name: new_cases, dtype: float64
81095 81102    55.0
Name: new_cases, dtype: float64
81096 81103    29.0
Name: new_cases, dtype: float64
81097 81104    47.0
Name: new_cases, dtype: float64
81098 81105    39.0
Name: new_cases, dtype: float64
81099 81106    46.0
Name: new_cases, dtype: float64
81100 81107    44.0
Name: new_cases, dtype: float64
81101 81108    44.0
Name: new_cases, dtype: float64
81102 81109    67.0
Name: new_cases, dtype: float64
81103 81110    52.0
Name: new_cases, dtype: float64
81104 81111    52.0
Name: new_cases, dtype: float64
81105 81112    33.0
Name: new_cases, dtype: float64
81106 81113    34.0
Name: new_cases, dtype: float64
81107 81114    33.0
Name: new_cases, dtype: float64
81108 81115    38.0
Name: new_cases, dtype: float64
81109 81116    37.0
Name: new_cases, dtype: float64
81110 81117    38.0
Name: new_cases, dtype: float64
81111 81118    30.0
Name: new_cases, dtype: float64
81112 81119    26.0
Name: new_cases, dtype: float64
81113 81120    18.0
Name: new_cases, dtype: float64
81114 81121    7.0
Name: new_cases, dtype: float64
81115 81122    18.0
Name: new_cases, dtype: float64
81116 81123    27.0
Name: new_cases, dtype: float64
81117 81124    28.0
Name: new_cases, dtype: float64
81118 81125    41.0
Name: new_cases, dtype: float64
81119 81126    62.0
Name: new_cases, dtype: float64
81120 81127    20.0
Name: new_cases, dtype: float64
81121 81128    53.0
Name: new_cases, dtype: float64
81122 81129    24.0
Name: new_cases, dtype: float64
81123 81130    22.0
Name: new_cases, dtype: float64
81124 81131    19.0
Name: new_cases, dtype: float64
81125 81132    10.0
Name: new_cases, dtype: float64
81126 81133    15.0
Name: new_cases, dtype: float64
81127 81134    12.0
Name: new_cases, dtype: float64
81128 81135    9.0
Name: new_cases, dtype: float64
81129 81136    27.0
Name: new_cases, dtype: float64
81130 81137    11.0
Name: new_cases, dtype: float64
81131 81138    14.0
Name: new_cases, dtype: float64
81132 81139    5.0
Name: new_cases, dtype: float64
81133 81140    5.0
Name: new_cases, dtype: float64
81134 81141    8.0
Name: new_cases, dtype: float64
81135 81142    3.0
Name: new_cases, dtype: float64
81136 81143    6.0
Name: new_cases, dtype: float64
81137 81144    5.0
Name: new_cases, dtype: float64
81138 81145    9.0
Name: new_cases, dtype: float64
81139 81146    29.0
Name: new_cases, dtype: float64
81140 81147    12.0
Name: new_cases, dtype: float64
81141 81148    8.0
Name: new_cases, dtype: float64
81142 81149    9.0
Name: new_cases, dtype: float64
81143 81150    14.0
Name: new_cases, dtype: float64
81144 81151    9.0
Name: new_cases, dtype: float64
81145 81152    10.0
Name: new_cases, dtype: float64
81146 81153    15.0
Name: new_cases, dtype: float64
81147 81154    9.0
Name: new_cases, dtype: float64
81148 81155    6.0
Name: new_cases, dtype: float64
81149 81156    8.0
Name: new_cases, dtype: float64
81150 81157    21.0
Name: new_cases, dtype: float64
81151 81158    12.0
Name: new_cases, dtype: float64
81152 81159    6.0
Name: new_cases, dtype: float64
81153 81160    14.0
Name: new_cases, dtype: float64
81154 81161    6.0
Name: new_cases, dtype: float64
81155 81162    10.0
Name: new_cases, dtype: float64
81156 81163    4.0
Name: new_cases, dtype: float64
81157 81164    8.0
Name: new_cases, dtype: float64
81158 81165    9.0
Name: new_cases, dtype: float64
81159 81166    5.0
Name: new_cases, dtype: float64
81160 81167    8.0
Name: new_cases, dtype: float64
81161 81168    5.0
Name: new_cases, dtype: float64
81162 81169    4.0
Name: new_cases, dtype: float64
81163 81170    5.0
Name: new_cases, dtype: float64
81164 81171    3.0
Name: new_cases, dtype: float64
81165 81172    5.0
Name: new_cases, dtype: float64
81166 81173    5.0
Name: new_cases, dtype: float64
81167 81174    11.0
Name: new_cases, dtype: float64
81168 81175    9.0
Name: new_cases, dtype: float64
81169 81176    7.0
Name: new_cases, dtype: float64
81170 81177    6.0
Name: new_cases, dtype: float64
81171 81178    6.0
Name: new_cases, dtype: float64
81172 81179    19.0
Name: new_cases, dtype: float64
81173 81180    4.0
Name: new_cases, dtype: float64
81174 81181    7.0
Name: new_cases, dtype: float64
81175 81182    5.0
Name: new_cases, dtype: float64
81176 81183    5.0
Name: new_cases, dtype: float64
81177 81184    3.0
Name: new_cases, dtype: float64
81178 81185    2.0
Name: new_cases, dtype: float64
81179 81186    6.0
Name: new_cases, dtype: float64
81180 81187    8.0
Name: new_cases, dtype: float64
81181 81188    3.0
Name: new_cases, dtype: float64
81182 81189    3.0
Name: new_cases, dtype: float64
81183 81190    3.0
Name: new_cases, dtype: float64
81184 81191    2.0
Name: new_cases, dtype: float64
81185 81192    1.0
81193    1.0
Name: new_cases, dtype: float64
81186 81192    1.0
81193    1.0
Name: new_cases, dtype: float64
81187 81194    2.0
Name: new_cases, dtype: float64
81188 81195    2.0
Name: new_cases, dtype: float64
81189 81196    5.0
Name: new_cases, dtype: float64
81190 81197    2.0
Name: new_cases, dtype: float64
81191 81198    1.0
Name: new_cases, dtype: float64
81192 81199    1.0
Name: new_cases, dtype: float64
81193 81200    1.0
Name: new_cases, dtype: float64
81194 81201    7.0
Name: new_cases, dtype: float64
81195 81202    3.0
Name: new_cases, dtype: float64
81196 81203    3.0
Name: new_cases, dtype: float64
81197 81204    5.0
Name: new_cases, dtype: float64
81198 81205    5.0
Name: new_cases, dtype: float64
81199 81206    3.0
Name: new_cases, dtype: float64
81200 81207    10.0
Name: new_cases, dtype: float64
81201 81208    3.0
Name: new_cases, dtype: float64
81202 81209    4.0
Name: new_cases, dtype: float64
81203 81210    4.0
Name: new_cases, dtype: float64
81204 81211    4.0
Name: new_cases, dtype: float64
81205 81212    5.0
Name: new_cases, dtype: float64
81206 81213    1.0
Name: new_cases, dtype: float64
81207 81214    21.0
Name: new_cases, dtype: float64
81208 81215    6.0
Name: new_cases, dtype: float64
81209 81216    6.0
Name: new_cases, dtype: float64
81210 81217    7.0
Name: new_cases, dtype: float64
81211 81218    18.0
Name: new_cases, dtype: float64
81212 81219    14.0
Name: new_cases, dtype: float64
81213 81220    2.0
Name: new_cases, dtype: float64
81214 81221    2.0
Name: new_cases, dtype: float64
81215 81222    10.0
Name: new_cases, dtype: float64
81216 81223    26.0
Name: new_cases, dtype: float64
81217 81224    14.0
Name: new_cases, dtype: float64
81218 81225    7.0
Name: new_cases, dtype: float64
81219 81226    11.0
Name: new_cases, dtype: float64
81220 81227    8.0
Name: new_cases, dtype: float64
81221 81228    15.0
Name: new_cases, dtype: float64
81222 81229    19.0
Name: new_cases, dtype: float64
81223 81230    13.0
Name: new_cases, dtype: float64
81224 81231    18.0
Name: new_cases, dtype: float64
81225 81232    17.0
Name: new_cases, dtype: float64
81226 81233    10.0
Name: new_cases, dtype: float64
81227 81234    17.0
Name: new_cases, dtype: float64
81228 81235    10.0
Name: new_cases, dtype: float64
81229 81236    24.0
Name: new_cases, dtype: float64
81230 81237    24.0
Name: new_cases, dtype: float64
81231 81238    36.0
Name: new_cases, dtype: float64
81232 81239    22.0
Name: new_cases, dtype: float64
81233 81240    12.0
Name: new_cases, dtype: float64
81234 81241    18.0
Name: new_cases, dtype: float64
81235 81242    26.0
Name: new_cases, dtype: float64
81236 81243    21.0
Name: new_cases, dtype: float64
81237 81244    22.0
Name: new_cases, dtype: float64
81238 81245    33.0
Name: new_cases, dtype: float64
81239 81246    30.0
Name: new_cases, dtype: float64
81240 81247    21.0
Name: new_cases, dtype: float64
81241 81248    37.0
Name: new_cases, dtype: float64
81242 81249    22.0
Name: new_cases, dtype: float64
81243 81250    32.0
Name: new_cases, dtype: float64
81244 81251    37.0
Name: new_cases, dtype: float64
81245 81252    30.0
Name: new_cases, dtype: float64
81246 81253    41.0
Name: new_cases, dtype: float64
81247 81254    38.0
Name: new_cases, dtype: float64
81248 81255    21.0
Name: new_cases, dtype: float64
81249 81256    32.0
Name: new_cases, dtype: float64
81250 81257    36.0
Name: new_cases, dtype: float64
81251 81258    48.0
Name: new_cases, dtype: float64
81252 81259    29.0
Name: new_cases, dtype: float64
81253 81260    35.0
Name: new_cases, dtype: float64
81254 81261    32.0
Name: new_cases, dtype: float64
81255 81262    23.0
Name: new_cases, dtype: float64
81256 81263    29.0
Name: new_cases, dtype: float64

81257 81264    20.0
Name: new_cases, dtype: float64
81258 81265    26.0
Name: new_cases, dtype: float64
81259 81266    36.0
Name: new_cases, dtype: float64
81260 81267    43.0
Name: new_cases, dtype: float64
81261 81268    17.0
Name: new_cases, dtype: float64
81262 81269    32.0
Name: new_cases, dtype: float64
81263 81270    32.0
Name: new_cases, dtype: float64
81264 81271    36.0
Name: new_cases, dtype: float64
81265 81272    44.0
Name: new_cases, dtype: float64
81266 81273    53.0
Name: new_cases, dtype: float64
81267 81274    39.0
Name: new_cases, dtype: float64
81268 81275    51.0
Name: new_cases, dtype: float64
81269 81276    11.0
Name: new_cases, dtype: float64
81270 81277    45.0
Name: new_cases, dtype: float64
81271 81278    62.0
Name: new_cases, dtype: float64
81272 81279    61.0
Name: new_cases, dtype: float64
81273 81280    99.0
Name: new_cases, dtype: float64
81274 81281    80.0
Name: new_cases, dtype: float64
81275 81282    70.0
Name: new_cases, dtype: float64
81276 81283    45.0
Name: new_cases, dtype: float64
81277 81284    73.0
Name: new_cases, dtype: float64
81278 81285    138.0
Name: new_cases, dtype: float64
81279 81286    114.0
Name: new_cases, dtype: float64
81280 81287    111.0
Name: new_cases, dtype: float64
81281 81288    91.0
Name: new_cases, dtype: float64
81282 81289    104.0
Name: new_cases, dtype: float64
81283 81290    88.0
Name: new_cases, dtype: float64
81284 81291    115.0
Name: new_cases, dtype: float64
81285 81292    91.0
Name: new_cases, dtype: float64
81286 81293    171.0
Name: new_cases, dtype: float64
81287 81294    125.0
Name: new_cases, dtype: float64
81288 81295    105.0
Name: new_cases, dtype: float64
81289 81296    99.0
Name: new_cases, dtype: float64
81290 81297    80.0
Name: new_cases, dtype: float64
81291 81298    115.0
Name: new_cases, dtype: float64
81292 81299    142.0
Name: new_cases, dtype: float64
81293 81300    133.0
Name: new_cases, dtype: float64
81294 81301    204.0
Name: new_cases, dtype: float64
81295 81302    160.0
Name: new_cases, dtype: float64
81296 81303    126.0
Name: new_cases, dtype: float64
81297 81304    118.0
Name: new_cases, dtype: float64
81298 81305    137.0
Name: new_cases, dtype: float64
81299 81306    255.0
Name: new_cases, dtype: float64
81300 81307    281.0
Name: new_cases, dtype: float64
81301 81308    228.0
Name: new_cases, dtype: float64
81302 81309    253.0
Name: new_cases, dtype: float64
81303 81310    207.0
Name: new_cases, dtype: float64
81304 81311    203.0
Name: new_cases, dtype: float64
81305 81312    313.0
Name: new_cases, dtype: float64
81306 81313    427.0
Name: new_cases, dtype: float64
81307 81314    445.0
Name: new_cases, dtype: float64
81308 81315    480.0
Name: new_cases, dtype: float64
81309 81316    597.0
Name: new_cases, dtype: float64
81310 81317    765.0
Name: new_cases, dtype: float64
81311 81318    423.0
Name: new_cases, dtype: float64
81312 81319    771.0
Name: new_cases, dtype: float64
81313 81320    948.0
Name: new_cases, dtype: float64
81314 81321    725.0
Name: new_cases, dtype: float64
81315 81322    1000.0
Name: new_cases, dtype: float64
81316 81323    883.0
Name: new_cases, dtype: float64
81317 81324    834.0
Name: new_cases, dtype: float64
81318 81325    893.0
Name: new_cases, dtype: float64
81319 81326    653.0
Name: new_cases, dtype: float64
81320 81327    992.0
Name: new_cases, dtype: float64
81321 81328    1650.0
Name: new_cases, dtype: float64
81322 81329    1940.0
Name: new_cases, dtype: float64
81323 81330    1976.0
Name: new_cases, dtype: float64
81324 81331    1038.0
Name: new_cases, dtype: float64
81325 81332    1108.0
Name: new_cases, dtype: float64
81326 81333    1433.0
Name: new_cases, dtype: float64
81327 81334    1554.0
Name: new_cases, dtype: float64
81328 81335    2057.0
Name: new_cases, dtype: float64
81329 81336    1525.0
Name: new_cases, dtype: float64
81330 81337    1377.0
Name: new_cases, dtype: float64
81331 81338    1148.0
Name: new_cases, dtype: float64
81332 81339    966.0
Name: new_cases, dtype: float64
81333 81340    1941.0
Name: new_cases, dtype: float64
81334 81341    1669.0
Name: new_cases, dtype: float64
81335 81342    2269.0
Name: new_cases, dtype: float64
81336 81343    1978.0
Name: new_cases, dtype: float64
81337 81344    2309.0
Name: new_cases, dtype: float64
81338 81345    1189.0
Name: new_cases, dtype: float64
81339 81346    1171.0
Name: new_cases, dtype: float64
81340 81347    2288.0
Name: new_cases, dtype: float64
81341 81348    2099.0
Name: new_cases, dtype: float64
81342 81349    2330.0
Name: new_cases, dtype: float64
81343 81350    2126.0
Name: new_cases, dtype: float64
81344 81351    1965.0
Name: new_cases, dtype: float64
81345 81352    1135.0
Name: new_cases, dtype: float64
81346 81353    1200.0
Name: new_cases, dtype: float64
81347 81354    2110.0
Name: new_cases, dtype: float64
81348 81355    2460.0
Name: new_cases, dtype: float64
81349 81356    2519.0
Name: new_cases, dtype: float64
81350 81357    2863.0
Name: new_cases, dtype: float64
81351 81358    2217.0
Name: new_cases, dtype: float64
81352 81359    1391.0
Name: new_cases, dtype: float64
81353 81360    1405.0
Name: new_cases, dtype: float64
81354 81361    3139.0
Name: new_cases, dtype: float64
81355 81362    3344.0
Name: new_cases, dtype: float64
81356 81363    3107.0
Name: new_cases, dtype: float64
81357 81364    3346.0
Name: new_cases, dtype: float64
81358 81365    2843.0
Name: new_cases, dtype: float64
81359 81366    1923.0
Name: new_cases, dtype: float64
81360 81367    1516.0
Name: new_cases, dtype: float64
81361 81368    3479.0
Name: new_cases, dtype: float64
81362 81369    3225.0
Name: new_cases, dtype: float64
81363 81370    3247.0
Name: new_cases, dtype: float64
81364 81371    3344.0
Name: new_cases, dtype: float64
81365 81372    2923.0
Name: new_cases, dtype: float64
81366 81373    2135.0
Name: new_cases, dtype: float64
81367 81374    2039.0
Name: new_cases, dtype: float64
81368 81375    3804.0
Name: new_cases, dtype: float64
81369 81376    3966.0
Name: new_cases, dtype: float64
81370 81377    2691.0
Name: new_cases, dtype: float64
81371 81378    2367.0
Name: new_cases, dtype: float64
81372 81379    1687.0
Name: new_cases, dtype: float64
81373 81380    1794.0
Name: new_cases, dtype: float64
81374 81381    2108.0
Name: new_cases, dtype: float64
81375 81382    3984.0
Name: new_cases, dtype: float64
81376 81383    2468.0
Name: new_cases, dtype: float64
81377 81384    3475.0
Name: new_cases, dtype: float64
81378 81385    1507.0
Name: new_cases, dtype: float64
81379 81386    1265.0
Name: new_cases, dtype: float64
81380 81387    1377.0
Name: new_cases, dtype: float64
81381 81388    1641.0
Name: new_cases, dtype: float64
81382 81389    2787.0
Name: new_cases, dtype: float64
81383 81390    2409.0
Name: new_cases, dtype: float64
81384 81391    2058.0
Name: new_cases, dtype: float64
81385 81392    1764.0
Name: new_cases, dtype: float64
81386 81393    1503.0
Name: new_cases, dtype: float64
81387 81394    774.0
Name: new_cases, dtype: float64
81388 81395    1012.0
Name: new_cases, dtype: float64
81389 81396    1764.0
Name: new_cases, dtype: float64
81390 81397    1445.0
Name: new_cases, dtype: float64
81391 81398    1224.0
Name: new_cases, dtype: float64
81392 81399    1234.0
Name: new_cases, dtype: float64
81393 81400    842.0
Name: new_cases, dtype: float64
81394 81401    477.0
Name: new_cases, dtype: float64
81395 81402    867.0
Name: new_cases, dtype: float64
81396 81403    1232.0
Name: new_cases, dtype: float64
81397 81404    1277.0
Name: new_cases, dtype: float64
81398 81405    1033.0
Name: new_cases, dtype: float64
81399 81406    1007.0
Name: new_cases, dtype: float64
81400 81407    773.0
Name: new_cases, dtype: float64
81401 81408    541.0
Name: new_cases, dtype: float64
81402 81409    691.0
Name: new_cases, dtype: float64
81403 81410    1283.0
Name: new_cases, dtype: float64
81404 81411    943.0
Name: new_cases, dtype: float64
81405 81412    859.0
Name: new_cases, dtype: float64
81406 81413    721.0
Name: new_cases, dtype: float64
81407 81414    803.0
Name: new_cases, dtype: float64
81408 81415    355.0
Name: new_cases, dtype: float64
81409 81416    546.0
Name: new_cases, dtype: float64
81410 81417    764.0
Name: new_cases, dtype: float64
81411 81418    740.0
Name: new_cases, dtype: float64
81412 81419    653.0
Name: new_cases, dtype: float64
81413 81420    677.0
Name: new_cases, dtype: float64
81414 81421    492.0
Name: new_cases, dtype: float64

81415 81422    269.0
Name: new_cases, dtype: float64
81416 81423    382.0
Name: new_cases, dtype: float64
81417 81424    570.0
Name: new_cases, dtype: float64
81418 81425    1067.0
Name: new_cases, dtype: float64
81419 81426    607.0
Name: new_cases, dtype: float64
81420 81427    576.0
Name: new_cases, dtype: float64
81421 81428    483.0
Name: new_cases, dtype: float64
81422 81429    213.0
Name: new_cases, dtype: float64
81423 81430    327.0
Name: new_cases, dtype: float64
81424 81431    557.0
Name: new_cases, dtype: float64
81425 81432    372.0
Name: new_cases, dtype: float64
81426 81433    793.0
Name: new_cases, dtype: float64
81427 81434    576.0
Name: new_cases, dtype: float64
81428 81435    489.0
Name: new_cases, dtype: float64
81429 81436    282.0
Name: new_cases, dtype: float64
81430 81437    500.0
Name: new_cases, dtype: float64
81431 81438    648.0
Name: new_cases, dtype: float64
81432 81439    568.0
Name: new_cases, dtype: float64
81433 81440    641.0
Name: new_cases, dtype: float64
81434 81441    653.0
Name: new_cases, dtype: float64
81435 81442    1802.0
Name: new_cases, dtype: float64
81436 81443    253.0
Name: new_cases, dtype: float64
81437 81444    427.0
Name: new_cases, dtype: float64
81438 81445    526.0
Name: new_cases, dtype: float64
81439 81446    547.0
Name: new_cases, dtype: float64
81440 81447    437.0
Name: new_cases, dtype: float64
81441 81448    464.0
Name: new_cases, dtype: float64
81442 81449    415.0
Name: new_cases, dtype: float64
81443 81450    216.0
Name: new_cases, dtype: float64
81444 81451    470.0
Name: new_cases, dtype: float64
81445 81452    486.0
Name: new_cases, dtype: float64
81446 81453    606.0
Name: new_cases, dtype: float64
81447 81454    364.0
Name: new_cases, dtype: float64
81448 81455    598.0
Name: new_cases, dtype: float64
81449 81456    431.0
Name: new_cases, dtype: float64
81450 81457    259.0
Name: new_cases, dtype: float64
81451 81458    646.0
Name: new_cases, dtype: float64
81452 81459    599.0
Name: new_cases, dtype: float64
81453 81460    580.0
Name: new_cases, dtype: float64
81454 81461    579.0
Name: new_cases, dtype: float64
81455 81462    602.0
Name: new_cases, dtype: float64
81456 81463    361.0
Name: new_cases, dtype: float64
81457 81464    329.0
Name: new_cases, dtype: float64
81458 81465    862.0
Name: new_cases, dtype: float64
81459 81466    809.0
Name: new_cases, dtype: float64
81460 81467    793.0
Name: new_cases, dtype: float64
81461 81468    872.0
Name: new_cases, dtype: float64
81462 81469    771.0
Name: new_cases, dtype: float64
81463 81470    494.0
Name: new_cases, dtype: float64
81464 81471    424.0
Name: new_cases, dtype: float64
81465 81472    851.0
Name: new_cases, dtype: float64
81466 81473    903.0
Name: new_cases, dtype: float64
81467 81474    886.0
Name: new_cases, dtype: float64
81468 81475    860.0
Name: new_cases, dtype: float64
81469 81476    1013.0
Name: new_cases, dtype: float64
81470 81477    729.0
Name: new_cases, dtype: float64
81471 81478    605.0
Name: new_cases, dtype: float64
81472 81479    688.0
Name: new_cases, dtype: float64
81473 81480    1120.0
Name: new_cases, dtype: float64
81474 81481    1107.0
Name: new_cases, dtype: float64
81475 81482    1182.0
Name: new_cases, dtype: float64
81476 81483    999.0
Name: new_cases, dtype: float64
81477 81484    865.0
Name: new_cases, dtype: float64
81478 81485    610.0
Name: new_cases, dtype: float64
81479 81486    1106.0
Name: new_cases, dtype: float64
81480 81487    1371.0
Name: new_cases, dtype: float64
81481 81488    1202.0
Name: new_cases, dtype: float64
81482 81489    1139.0
Name: new_cases, dtype: float64
81483 81490    1228.0
Name: new_cases, dtype: float64
81484 81491    802.0
Name: new_cases, dtype: float64
81485 81492    601.0
Name: new_cases, dtype: float64
81486 81493    1151.0
Name: new_cases, dtype: float64
81487 81494    1150.0
Name: new_cases, dtype: float64
81488 81495    1417.0
Name: new_cases, dtype: float64
81489 81496    1313.0
Name: new_cases, dtype: float64
81490 81497    1259.0
Name: new_cases, dtype: float64
81491 81498    775.0
Name: new_cases, dtype: float64
81492 81499    575.0
Name: new_cases, dtype: float64
81493 81500    1054.0
Name: new_cases, dtype: float64
81494 81501    1629.0
Name: new_cases, dtype: float64
81495 81502    1341.0
Name: new_cases, dtype: float64
81496 81503    1373.0
Name: new_cases, dtype: float64
81497 81504    1386.0
Name: new_cases, dtype: float64
81498 81505    1025.0
Name: new_cases, dtype: float64
81499 81506    657.0
Name: new_cases, dtype: float64
81500 81507    1113.0
Name: new_cases, dtype: float64
81501 81508    1249.0
Name: new_cases, dtype: float64
81502 81509    1392.0
Name: new_cases, dtype: float64
81503 81510    1293.0
Name: new_cases, dtype: float64
81504 81511    1522.0
Name: new_cases, dtype: float64
81505 81512    921.0
Name: new_cases, dtype: float64
81506 81513    796.0
Name: new_cases, dtype: float64
81507 81514    1239.0
Name: new_cases, dtype: float64
81508 81515    1266.0
Name: new_cases, dtype: float64
81509 81516    1207.0
Name: new_cases, dtype: float64
81510 81517    1140.0
Name: new_cases, dtype: float64
81511 81518    1249.0
Name: new_cases, dtype: float64
81512 81519    812.0
Name: new_cases, dtype: float64
81513 81520    527.0
Name: new_cases, dtype: float64
81514 81521    732.0
Name: new_cases, dtype: float64
81515 81522    974.0
Name: new_cases, dtype: float64
81516 81523    915.0
Name: new_cases, dtype: float64
81517 81524    679.0
Name: new_cases, dtype: float64
81518 81525    1013.0
Name: new_cases, dtype: float64
81519 81526    473.0
Name: new_cases, dtype: float64
81520 81527    281.0
Name: new_cases, dtype: float64
81521 81528    552.0
Name: new_cases, dtype: float64
81522 81529    549.0
Name: new_cases, dtype: float64
81523 81530    595.0
Name: new_cases, dtype: float64
81524 81531    520.0
Name: new_cases, dtype: float64
81525 81532    520.0
Name: new_cases, dtype: float64
81526 81533    333.0
Name: new_cases, dtype: float64
81527 81534    184.0
Name: new_cases, dtype: float64
81528 81535    393.0
Name: new_cases, dtype: float64
81529 81536    422.0
Name: new_cases, dtype: float64
81530 81537    347.0
Name: new_cases, dtype: float64
81531 81538    370.0
Name: new_cases, dtype: float64
81532 81539    341.0
Name: new_cases, dtype: float64
81533 81540    197.0
Name: new_cases, dtype: float64
81534 81541    90.0
Name: new_cases, dtype: float64
81535 81542    216.0
Name: new_cases, dtype: float64
81536 81543    243.0
Name: new_cases, dtype: float64
81537 81544    220.0
Name: new_cases, dtype: float64
81538 81545    157.0
Name: new_cases, dtype: float64
81539 81546    244.0
Name: new_cases, dtype: float64
81540 81547    123.0
Name: new_cases, dtype: float64
81541 81548    66.0
Name: new_cases, dtype: float64
81542 81549    130.0
Name: new_cases, dtype: float64
81543 81550    130.0
Name: new_cases, dtype: float64
81544 81551    105.0
Name: new_cases, dtype: float64
81545 81552    77.0
Name: new_cases, dtype: float64
81546 81553    74.0
Name: new_cases, dtype: float64
81547 81554    51.0
Name: new_cases, dtype: float64
81548 81555    28.0
Name: new_cases, dtype: float64
81549 81556    59.0
Name: new_cases, dtype: float64
81550 81557    60.0
Name: new_cases, dtype: float64
81551 81558    64.0
Name: new_cases, dtype: float64
81552 81559    18.0
Name: new_cases, dtype: float64
81553 81560    47.0
Name: new_cases, dtype: float64
81554 81561    19.0
Name: new_cases, dtype: float64
81555 81562    15.0
Name: new_cases, dtype: float64
81556 81563    37.0
Name: new_cases, dtype: float64
81557 81564    43.0
Name: new_cases, dtype: float64
81558 81565    40.0
Name: new_cases, dtype: float64
81559 81566    17.0
Name: new_cases, dtype: float64
81560 81567    37.0
Name: new_cases, dtype: float64
81561 81568    25.0
Name: new_cases, dtype: float64
81562 81569    18.0
Name: new_cases, dtype: float64
81563 81570    44.0
Name: new_cases, dtype: float64
81564 81571    34.0
Name: new_cases, dtype: float64
81565 81572    40.0
Name: new_cases, dtype: float64
81566 81573    70.0
Name: new_cases, dtype: float64
81567 81574    73.0
Name: new_cases, dtype: float64
81568 81575    25.0
Name: new_cases, dtype: float64
81569 81576    25.0
Name: new_cases, dtype: float64
81570 81577    85.0
Name: new_cases, dtype: float64
81571 81578    79.0
Name: new_cases, dtype: float64
81572 81579    107.0
Name: new_cases, dtype: float64
81573 81580    84.0
Name: new_cases, dtype: float64
81574 81581    90.0
Name: new_cases, dtype: float64
81575 81582    83.0
Name: new_cases, dtype: float64
81576 81583    68.0
Name: new_cases, dtype: float64
81577 81584    101.0
Name: new_cases, dtype: float64
81578 81585    179.0
Name: new_cases, dtype: float64
81579 81586    203.0
Name: new_cases, dtype: float64
81580 81587    245.0
Name: new_cases, dtype: float64
81581 81588    233.0
Name: new_cases, dtype: float64
81582 81589    192.0
Name: new_cases, dtype: float64
81583 81590    97.0
Name: new_cases, dtype: float64
81584 81591    221.0
Name: new_cases, dtype: float64

81585 81592    345.0
Name: new_cases, dtype: float64
81586 81593    410.0
Name: new_cases, dtype: float64
81587 81594    377.0
Name: new_cases, dtype: float64
81588 81595    402.0
Name: new_cases, dtype: float64
81589 81596    198.0
Name: new_cases, dtype: float64
81590 81597    230.0
Name: new_cases, dtype: float64
81591 81598    410.0
Name: new_cases, dtype: float64
81592 81599    535.0
Name: new_cases, dtype: float64
81593 81600    241.0
Name: new_cases, dtype: float64
81594 81601    777.0
Name: new_cases, dtype: float64
81595 81602    517.0
Name: new_cases, dtype: float64
81596 81603    377.0
Name: new_cases, dtype: float64
81597 81604    305.0
Name: new_cases, dtype: float64
81598 81605    535.0
Name: new_cases, dtype: float64
81599 81606    626.0
Name: new_cases, dtype: float64
81600 81607    604.0
Name: new_cases, dtype: float64
81601 81608    574.0
Name: new_cases, dtype: float64
81602 81609    599.0
Name: new_cases, dtype: float64
81603 81610    464.0
Name: new_cases, dtype: float64
81604 81611    360.0
Name: new_cases, dtype: float64
81605 81612    596.0
Name: new_cases, dtype: float64
81606 81613    646.0
Name: new_cases, dtype: float64
81607 81614    557.0
Name: new_cases, dtype: float64
81608 81615    583.0
Name: new_cases, dtype: float64
81609 81616    790.0
Name: new_cases, dtype: float64
81610 81617    425.0
Name: new_cases, dtype: float64
81611 81618    319.0
Name: new_cases, dtype: float64
81612 81619    622.0
Name: new_cases, dtype: float64
81613 81620    665.0
Name: new_cases, dtype: float64
81614 81621    723.0
Name: new_cases, dtype: float64
81615 81622    642.0
Name: new_cases, dtype: float64
81616 81623    596.0
Name: new_cases, dtype: float64
81617 81624    443.0
Name: new_cases, dtype: float64
81618 81625    388.0
Name: new_cases, dtype: float64
81619 81626    660.0
Name: new_cases, dtype: float64
81620 81627    707.0
Name: new_cases, dtype: float64
81621 81628    807.0
Name: new_cases, dtype: float64
81622 81629    828.0
Name: new_cases, dtype: float64
81623 81630    847.0
Name: new_cases, dtype: float64
81624 81631    610.0
Name: new_cases, dtype: float64
81625 81632    355.0
Name: new_cases, dtype: float64
81626 81633    713.0
Name: new_cases, dtype: float64
81627 81634    908.0
Name: new_cases, dtype: float64
81628 81635    1005.0
Name: new_cases, dtype: float64
81629 81636    953.0
Name: new_cases, dtype: float64
81630 81637    1064.0
Name: new_cases, dtype: float64
81631 81638    842.0
Name: new_cases, dtype: float64
81632 81639    492.0
Name: new_cases, dtype: float64
81633 81640    899.0
Name: new_cases, dtype: float64
81634 81641    1296.0
Name: new_cases, dtype: float64
81635 81642    1330.0
Name: new_cases, dtype: float64
81636 81643    1211.0
Name: new_cases, dtype: float64
81637 81644    1374.0
Name: new_cases, dtype: float64
81638 81645    883.0
Name: new_cases, dtype: float64
81639 81646    746.0
Name: new_cases, dtype: float64
81640 81647    1157.0
Name: new_cases, dtype: float64
81641 81648    1429.0
Name: new_cases, dtype: float64
81642 81649    1962.0
Name: new_cases, dtype: float64
81643 81650    1477.0
Name: new_cases, dtype: float64
81644 81651    1609.0
Name: new_cases, dtype: float64
81645 81652    1277.0
Name: new_cases, dtype: float64
81646 81653    1048.0
Name: new_cases, dtype: float64
81647 81654    1242.0
Name: new_cases, dtype: float64
81648 81655    1973.0
Name: new_cases, dtype: float64
81649 81656    1814.0
Name: new_cases, dtype: float64
81650 81657    2007.0
Name: new_cases, dtype: float64
81651 81658    2111.0
Name: new_cases, dtype: float64
81652 81659    1615.0
Name: new_cases, dtype: float64
81653 81660    1116.0
Name: new_cases, dtype: float64
81654 81661    1548.0
Name: new_cases, dtype: float64
81655 81662    2747.0
Name: new_cases, dtype: float64
81656 81663    2268.0
Name: new_cases, dtype: float64
81657 81664    2453.0
Name: new_cases, dtype: float64
81658 81665    2481.0
Name: new_cases, dtype: float64
81659 81666    1910.0
Name: new_cases, dtype: float64
81660 81667    1350.0
Name: new_cases, dtype: float64
81661 81668    1772.0
Name: new_cases, dtype: float64
81662 81669    2740.0
Name: new_cases, dtype: float64
81663 81670    2962.0
Name: new_cases, dtype: float64
81664 81671    2867.0
Name: new_cases, dtype: float64
81665 81672    2851.0
Name: new_cases, dtype: float64
81666 81673    2160.0
Name: new_cases, dtype: float64
81667 81674    1478.0
Name: new_cases, dtype: float64
81668 81675    2466.0
Name: new_cases, dtype: float64
81669 81676    3504.0
Name: new_cases, dtype: float64
81670 81677    3349.0
Name: new_cases, dtype: float64
81671 81678    3016.0
Name: new_cases, dtype: float64
81672 81679    3186.0
Name: new_cases, dtype: float64
81673 81680    2545.0
Name: new_cases, dtype: float64
81674 81681    1846.0
Name: new_cases, dtype: float64
81675 81682    2394.0
Name: new_cases, dtype: float64
81676 81683    3622.0
Name: new_cases, dtype: float64
81677 81684    3485.0
Name: new_cases, dtype: float64
81678 81685    3519.0
Name: new_cases, dtype: float64
81679 81686    3044.0
Name: new_cases, dtype: float64
81680 81687    2620.0
Name: new_cases, dtype: float64
81681 81688    1865.0
Name: new_cases, dtype: float64
81682 81689    2189.0
Name: new_cases, dtype: float64
81683 81690    2048.0
Name: new_cases, dtype: float64
81684 81691    3261.0
Name: new_cases, dtype: float64
81685 81692    3282.0
Name: new_cases, dtype: float64
81686 81693    3524.0
Name: new_cases, dtype: float64
81687 81694    2234.0
Name: new_cases, dtype: float64
81688 81695    1423.0
Name: new_cases, dtype: float64
81689 81696    2314.0
Name: new_cases, dtype: float64
81690 81697    3178.0
Name: new_cases, dtype: float64
81691 81698    2657.0
Name: new_cases, dtype: float64
81692 81699    2683.0
Name: new_cases, dtype: float64
81693 81700    2411.0
Name: new_cases, dtype: float64
81694 81701    1442.0
Name: new_cases, dtype: float64
81695 81702    955.0
Name: new_cases, dtype: float64
81696 81703    1939.0
Name: new_cases, dtype: float64
81697 81704    2184.0
Name: new_cases, dtype: float64
81698 81705    2117.0
Name: new_cases, dtype: float64
81699 81706    1847.0
Name: new_cases, dtype: float64
81700 81707    1931.0
Name: new_cases, dtype: float64
81701 81708    1359.0
Name: new_cases, dtype: float64
81702 81709    867.0
Name: new_cases, dtype: float64
81703 81710    1873.0
Name: new_cases, dtype: float64
81704 81711    2169.0
Name: new_cases, dtype: float64
81705 81712    1964.0
Name: new_cases, dtype: float64
81706 81713    2131.0
Name: new_cases, dtype: float64
81707 81714    2046.0
Name: new_cases, dtype: float64
81708 81715    1292.0
Name: new_cases, dtype: float64
81709 81716    594.0
Name: new_cases, dtype: float64
81710 81717    1804.0
Name: new_cases, dtype: float64
81711 81718    1941.0
Name: new_cases, dtype: float64
81712 81719    1945.0
Name: new_cases, dtype: float64
81713 81720    2170.0
Name: new_cases, dtype: float64
81714 81721    1960.0
Name: new_cases, dtype: float64
81715 81722    1525.0
Name: new_cases, dtype: float64
81716 81723    471.0
Name: new_cases, dtype: float64
81717 81724    2148.0
Name: new_cases, dtype: float64
81718 81725    2079.0
Name: new_cases, dtype: float64
81719 81726    1687.0
Name: new_cases, dtype: float64
81720 81727    1729.0
Name: new_cases, dtype: float64
81721 81728    1720.0
Name: new_cases, dtype: float64
81722 81729    1449.0
Name: new_cases, dtype: float64
81723 81730    831.0
Name: new_cases, dtype: float64
81724 81731    1518.0
Name: new_cases, dtype: float64
81725 81732    2215.0
Name: new_cases, dtype: float64
81726 81733    1957.0
Name: new_cases, dtype: float64
81727 81734    1619.0
Name: new_cases, dtype: float64
81728 81735    1724.0
Name: new_cases, dtype: float64
81729 81736    1359.0
Name: new_cases, dtype: float64
81730 81737    624.0
Name: new_cases, dtype: float64
81731 81738    1453.0
Name: new_cases, dtype: float64
81732 81739    1722.0
Name: new_cases, dtype: float64
81733 81740    1772.0
Name: new_cases, dtype: float64
81734 81741    1581.0
Name: new_cases, dtype: float64
81735 81742    1255.0
Name: new_cases, dtype: float64
81736 81743    828.0
Name: new_cases, dtype: float64
81737 81744    651.0
Name: new_cases, dtype: float64
81738 81745    1599.0
Name: new_cases, dtype: float64
81739 81746    2062.0
Name: new_cases, dtype: float64
81740 81747    1763.0
Name: new_cases, dtype: float64

81741 81748    1942.0
Name: new_cases, dtype: float64
81742 81749    2095.0
Name: new_cases, dtype: float64
81743 81750    1192.0
Name: new_cases, dtype: float64
81744 81751    1244.0
Name: new_cases, dtype: float64
81745 81752    2315.0
Name: new_cases, dtype: float64
81746 81753    3097.0
Name: new_cases, dtype: float64
81747 81754    3267.0
Name: new_cases, dtype: float64
81748 81755    3598.0
Name: new_cases, dtype: float64
81749 81756    3366.0
Name: new_cases, dtype: float64
81750 81076    1.0
Name: new_cases, dtype: float64
81751 81077    0.0
Name: new_cases, dtype: float64
81752 81078    0.0
Name: new_cases, dtype: float64
81753 81079    0.0
Name: new_cases, dtype: float64
81754 81080    0.0
Name: new_cases, dtype: float64
81755 81081    0.0
Name: new_cases, dtype: float64
81756 81082    0.0
Name: new_cases, dtype: float64
83166 83173    0.0
Name: new_cases, dtype: float64
83167 83174    1.0
Name: new_cases, dtype: float64
83168 83175    0.0
Name: new_cases, dtype: float64
83169 83176    2.0
Name: new_cases, dtype: float64
83170 83177    2.0
Name: new_cases, dtype: float64
83171 83178    12.0
Name: new_cases, dtype: float64
83172 83179    15.0
Name: new_cases, dtype: float64
83173 83180    17.0
Name: new_cases, dtype: float64
83174 83181    8.0
Name: new_cases, dtype: float64
83175 83182    18.0
Name: new_cases, dtype: float64
83176 83183    63.0
Name: new_cases, dtype: float64
83177 83184    63.0
Name: new_cases, dtype: float64
83178 83185    132.0
Name: new_cases, dtype: float64
83179 83186    149.0
Name: new_cases, dtype: float64
83180 83187    186.0
Name: new_cases, dtype: float64
83181 83188    128.0
Name: new_cases, dtype: float64
83182 83189    77.0
Name: new_cases, dtype: float64
83183 83190    224.0
Name: new_cases, dtype: float64
83184 83191    234.0
Name: new_cases, dtype: float64
83185 83192    120.0
Name: new_cases, dtype: float64
83186 83193    152.0
Name: new_cases, dtype: float64
83187 83194    226.0
Name: new_cases, dtype: float64
83188 83195    119.0
Name: new_cases, dtype: float64
83189 83196    38.0
Name: new_cases, dtype: float64
83190 83197    190.0
Name: new_cases, dtype: float64
83191 83198    141.0
Name: new_cases, dtype: float64
83192 83199    168.0
Name: new_cases, dtype: float64
83193 83200    125.0
Name: new_cases, dtype: float64
83194 83201    117.0
Name: new_cases, dtype: float64
83195 83202    75.0
Name: new_cases, dtype: float64
83196 83203    39.0
Name: new_cases, dtype: float64
83197 83204    127.0
Name: new_cases, dtype: float64
83198 83205    64.0
Name: new_cases, dtype: float64
83199 83206    81.0
Name: new_cases, dtype: float64
83200 83207    108.0
Name: new_cases, dtype: float64
83201 83208    47.0
Name: new_cases, dtype: float64
83202 83209    11.0
Name: new_cases, dtype: float64
83203 83210    11.0
Name: new_cases, dtype: float64
83204 83211    15.0
Name: new_cases, dtype: float64
83205 83212    66.0
Name: new_cases, dtype: float64
83206 83213    71.0
Name: new_cases, dtype: float64
83207 83214    36.0
Name: new_cases, dtype: float64
83208 83215    57.0
Name: new_cases, dtype: float64
83209 83216    13.0
Name: new_cases, dtype: float64
83210 83217    8.0
Name: new_cases, dtype: float64
83211 83218    60.0
Name: new_cases, dtype: float64
83212 83219    36.0
Name: new_cases, dtype: float64
83213 83220    11.0
Name: new_cases, dtype: float64
83214 83221    30.0
Name: new_cases, dtype: float64
83215 83222    16.0
Name: new_cases, dtype: float64
83216 83223    12.0
Name: new_cases, dtype: float64
83217 83224    6.0
Name: new_cases, dtype: float64
83218 83225    12.0
Name: new_cases, dtype: float64
83219 83226    28.0
Name: new_cases, dtype: float64
83220 83227    15.0
Name: new_cases, dtype: float64
83221 83228    18.0
Name: new_cases, dtype: float64
83222 83229    10.0
Name: new_cases, dtype: float64
83223 83230    12.0
Name: new_cases, dtype: float64
83224 83231    4.0
Name: new_cases, dtype: float64
83225 83232    12.0
Name: new_cases, dtype: float64
83226 83233    11.0
Name: new_cases, dtype: float64
83227 83234    8.0
Name: new_cases, dtype: float64
83228 83235    12.0
Name: new_cases, dtype: float64
83229 83236    6.0
Name: new_cases, dtype: float64
83230 83237    9.0
Name: new_cases, dtype: float64
83231 83238    2.0
Name: new_cases, dtype: float64
83232 83239    6.0
Name: new_cases, dtype: float64
83233 83240    10.0
Name: new_cases, dtype: float64
83234 83241    11.0
Name: new_cases, dtype: float64
83235 83242    8.0
Name: new_cases, dtype: float64
83236 83243    7.0
Name: new_cases, dtype: float64
83237 83244    15.0
Name: new_cases, dtype: float64
83238 83245    2.0
Name: new_cases, dtype: float64
83239 83246    11.0
Name: new_cases, dtype: float64
83240 83247    13.0
Name: new_cases, dtype: float64
83241 83248    9.0
Name: new_cases, dtype: float64
83242 83249    1.0
Name: new_cases, dtype: float64
83243 83250    9.0
Name: new_cases, dtype: float64
83244 83251    2.0
Name: new_cases, dtype: float64
83245 83252    1.0
Name: new_cases, dtype: float64
83246 83253    2.0
Name: new_cases, dtype: float64
83247 83254    6.0
Name: new_cases, dtype: float64
83248 83255    7.0
Name: new_cases, dtype: float64
83249 83256    4.0
Name: new_cases, dtype: float64
83250 83257    4.0
Name: new_cases, dtype: float64
83251 83258    2.0
Name: new_cases, dtype: float64
83252 83259    1.0
Name: new_cases, dtype: float64
83253 83260    1.0
Name: new_cases, dtype: float64
83254 83261    4.0
Name: new_cases, dtype: float64
83255 83262    3.0
Name: new_cases, dtype: float64
83256 83263    5.0
Name: new_cases, dtype: float64
83257 83264    3.0
Name: new_cases, dtype: float64
83258 83265    4.0
Name: new_cases, dtype: float64
83259 83266    1.0
Name: new_cases, dtype: float64
83260 83267    6.0
Name: new_cases, dtype: float64
83261 83268    3.0
Name: new_cases, dtype: float64
83262 83269    3.0
Name: new_cases, dtype: float64
83263 83270    3.0
Name: new_cases, dtype: float64
83264 83271    8.0
Name: new_cases, dtype: float64
83265 83272    7.0
Name: new_cases, dtype: float64
83266 83273    2.0
Name: new_cases, dtype: float64
83267 83274    3.0
Name: new_cases, dtype: float64
83268 83275    10.0
Name: new_cases, dtype: float64
83269 83276    6.0
Name: new_cases, dtype: float64
83270 83277    8.0
Name: new_cases, dtype: float64
83271 83278    6.0
Name: new_cases, dtype: float64
83272 83279    15.0
Name: new_cases, dtype: float64
83273 83280    1.0
Name: new_cases, dtype: float64
83274 83281    12.0
Name: new_cases, dtype: float64
83275 83282    7.0
Name: new_cases, dtype: float64
83276 83283    11.0
Name: new_cases, dtype: float64
83277 83284    22.0
Name: new_cases, dtype: float64
83278 83285    44.0
Name: new_cases, dtype: float64
83279 83286    25.0
Name: new_cases, dtype: float64
83280 83287    14.0
Name: new_cases, dtype: float64
83281 83288    43.0
Name: new_cases, dtype: float64
83282 83289    46.0
Name: new_cases, dtype: float64
83283 83290    50.0
Name: new_cases, dtype: float64
83284 83291    52.0
Name: new_cases, dtype: float64
83285 83292    29.0
Name: new_cases, dtype: float64
83286 83293    46.0
Name: new_cases, dtype: float64
83287 83294    20.0
Name: new_cases, dtype: float64
83288 83295    61.0
Name: new_cases, dtype: float64
83289 83296    47.0
Name: new_cases, dtype: float64
83290 83297    69.0
Name: new_cases, dtype: float64
83291 83298    58.0
Name: new_cases, dtype: float64
83292 83299    65.0
Name: new_cases, dtype: float64
83293 83300    83.0
Name: new_cases, dtype: float64
83294 83301    31.0
Name: new_cases, dtype: float64
83295 83302    100.0
Name: new_cases, dtype: float64
83296 83303    66.0
Name: new_cases, dtype: float64
83297 83304    163.0
Name: new_cases, dtype: float64
83298 83305    124.0
Name: new_cases, dtype: float64
83299 83306    74.0
Name: new_cases, dtype: float64
83300 83307    122.0
Name: new_cases, dtype: float64
83301 83308    34.0
Name: new_cases, dtype: float64
83302 83309    86.0
Name: new_cases, dtype: float64
83303 83310    129.0
Name: new_cases, dtype: float64
83304 83311    98.0
Name: new_cases, dtype: float64
83305 83312    104.0
Name: new_cases, dtype: float64
83306 83313    133.0
Name: new_cases, dtype: float64
83307 83314    83.0
Name: new_cases, dtype: float64
83308 83315    49.0
Name: new_cases, dtype: float64
83309 83316    54.0
Name: new_cases, dtype: float64
83310 83317    158.0
Name: new_cases, dtype: float64
83311 83318    83.0
Name: new_cases, dtype: float64
83312 83319    79.0
Name: new_cases, dtype: float64
83313 83320    98.0
Name: new_cases, dtype: float64
83314 83321    62.0
Name: new_cases, dtype: float64
83315 83322    9.0
Name: new_cases, dtype: float64
83316 83323    53.0
Name: new_cases, dtype: float64
83317 83324    90.0
Name: new_cases, dtype: float64
83318 83325    66.0
Name: new_cases, dtype: float64
83319 83326    40.0
Name: new_cases, dtype: float64
83320 83327    56.0
Name: new_cases, dtype: float64
83321 83328    36.0
Name: new_cases, dtype: float64

83322 83329    11.0
Name: new_cases, dtype: float64
83323 83330    26.0
Name: new_cases, dtype: float64
83324 83331    58.0
Name: new_cases, dtype: float64
83325 83332    68.0
Name: new_cases, dtype: float64
83326 83333    37.0
Name: new_cases, dtype: float64
83327 83334    34.0
Name: new_cases, dtype: float64
83328 83335    19.0
Name: new_cases, dtype: float64
83329 83336    11.0
Name: new_cases, dtype: float64
83330 83337    30.0
Name: new_cases, dtype: float64
83331 83338    67.0
Name: new_cases, dtype: float64
83332 83339    71.0
Name: new_cases, dtype: float64
83333 83340    67.0
Name: new_cases, dtype: float64
83334 83341    58.0
Name: new_cases, dtype: float64
83335 83342    13.0
Name: new_cases, dtype: float64
83336 83343    19.0
Name: new_cases, dtype: float64
83337 83344    44.0
Name: new_cases, dtype: float64
83338 83345    90.0
Name: new_cases, dtype: float64
83339 83346    0.0
Name: new_cases, dtype: float64
83340 83347   -1348.0
Name: new_cases, dtype: float64
83341 83348    45.0
Name: new_cases, dtype: float64
83342 83349    0.0
Name: new_cases, dtype: float64
83343 83350    0.0
Name: new_cases, dtype: float64
83344 83351    0.0
Name: new_cases, dtype: float64
83345 83352    120.0
Name: new_cases, dtype: float64
83346 83353    66.0
Name: new_cases, dtype: float64
83347 83354    43.0
Name: new_cases, dtype: float64
83348 83355    42.0
Name: new_cases, dtype: float64
83349 83356    54.0
Name: new_cases, dtype: float64
83350 83357    10.0
Name: new_cases, dtype: float64
83351 83358    14.0
Name: new_cases, dtype: float64
83352 83359    49.0
Name: new_cases, dtype: float64
83353 83360    65.0
Name: new_cases, dtype: float64
83354 83361    0.0
Name: new_cases, dtype: float64
83355 83362    71.0
Name: new_cases, dtype: float64
83356 83363    0.0
Name: new_cases, dtype: float64
83357 83364    85.0
Name: new_cases, dtype: float64
83358 83365    40.0
Name: new_cases, dtype: float64
83359 83366    110.0
Name: new_cases, dtype: float64
83360 83367    147.0
Name: new_cases, dtype: float64
83361 83368    177.0
Name: new_cases, dtype: float64
83362 83369    0.0
Name: new_cases, dtype: float64
83363 83370    0.0
Name: new_cases, dtype: float64
83364 83371    198.0
Name: new_cases, dtype: float64
83365 83372    100.0
Name: new_cases, dtype: float64
83366 83373    74.0
Name: new_cases, dtype: float64
83367 83374    68.0
Name: new_cases, dtype: float64
83368 83375    75.0
Name: new_cases, dtype: float64
83369 83376    0.0
Name: new_cases, dtype: float64
83370 83377    0.0
Name: new_cases, dtype: float64
83371 83378    143.0
Name: new_cases, dtype: float64
83372 83379    55.0
Name: new_cases, dtype: float64
83373 83380    78.0
Name: new_cases, dtype: float64
83374 83381    86.0
Name: new_cases, dtype: float64
83375 83382    114.0
Name: new_cases, dtype: float64
83376 83383    0.0
Name: new_cases, dtype: float64
83377 83384    0.0
Name: new_cases, dtype: float64
83378 83385    216.0
Name: new_cases, dtype: float64
83379 83386    54.0
Name: new_cases, dtype: float64
83380 83387    140.0
Name: new_cases, dtype: float64
83381 83388    100.0
Name: new_cases, dtype: float64
83382 83389    141.0
Name: new_cases, dtype: float64
83383 83390    154.0
Name: new_cases, dtype: float64
83384 83391    208.0
Name: new_cases, dtype: float64
83385 83392    9.0
Name: new_cases, dtype: float64
83386 83393    109.0
Name: new_cases, dtype: float64
83387 83394    190.0
Name: new_cases, dtype: float64
83388 83395    214.0
Name: new_cases, dtype: float64
83389 83396    227.0
Name: new_cases, dtype: float64
83390 83397    0.0
Name: new_cases, dtype: float64
83391 83398    417.0
Name: new_cases, dtype: float64
83392 83399    122.0
Name: new_cases, dtype: float64
83393 83400    231.0
Name: new_cases, dtype: float64
83394 83401    430.0
Name: new_cases, dtype: float64
83395 83402    662.0
Name: new_cases, dtype: float64
83396 83403    518.0
Name: new_cases, dtype: float64
83397 83404    0.0
Name: new_cases, dtype: float64
83398 83405    0.0
Name: new_cases, dtype: float64
83399 83406    1548.0
Name: new_cases, dtype: float64
83400 83407    485.0
Name: new_cases, dtype: float64
83401 83408    775.0
Name: new_cases, dtype: float64
83402 83409    697.0
Name: new_cases, dtype: float64
83403 83410    778.0
Name: new_cases, dtype: float64
83404 83411    0.0
Name: new_cases, dtype: float64
83405 83412    0.0
Name: new_cases, dtype: float64
83406 83413    1967.0
Name: new_cases, dtype: float64
83407 83414    533.0
Name: new_cases, dtype: float64
83408 83415    710.0
Name: new_cases, dtype: float64
83409 83416    803.0
Name: new_cases, dtype: float64
83410 83417    659.0
Name: new_cases, dtype: float64
83411 83418    0.0
Name: new_cases, dtype: float64
83412 83419    0.0
Name: new_cases, dtype: float64
83413 83420    1421.0
Name: new_cases, dtype: float64
83414 83421    483.0
Name: new_cases, dtype: float64
83415 83422    0.0
Name: new_cases, dtype: float64
83416 83423    1508.0
Name: new_cases, dtype: float64
83417 83424    713.0
Name: new_cases, dtype: float64
83418 83425    0.0
Name: new_cases, dtype: float64
83419 83426    0.0
Name: new_cases, dtype: float64
83420 83427    1325.0
Name: new_cases, dtype: float64
83421 83428    425.0
Name: new_cases, dtype: float64
83422 83429    892.0
Name: new_cases, dtype: float64
83423 83430    670.0
Name: new_cases, dtype: float64
83424 83431    519.0
Name: new_cases, dtype: float64
83425 83432    0.0
Name: new_cases, dtype: float64
83426 83433    0.0
Name: new_cases, dtype: float64
83427 83434    1349.0
Name: new_cases, dtype: float64
83428 83435    373.0
Name: new_cases, dtype: float64
83429 83436    616.0
Name: new_cases, dtype: float64
83430 83437    773.0
Name: new_cases, dtype: float64
83431 83438    536.0
Name: new_cases, dtype: float64
83432 83439    0.0
Name: new_cases, dtype: float64
83433 83440    0.0
Name: new_cases, dtype: float64
83434 83441    1269.0
Name: new_cases, dtype: float64
83435 83442    451.0
Name: new_cases, dtype: float64
83436 83443    673.0
Name: new_cases, dtype: float64
83437 83444    627.0
Name: new_cases, dtype: float64
83438 83445    588.0
Name: new_cases, dtype: float64
83439 83446    0.0
Name: new_cases, dtype: float64
83440 83447    0.0
Name: new_cases, dtype: float64
83441 83448    1459.0
Name: new_cases, dtype: float64
83442 83449    0.0
Name: new_cases, dtype: float64
83443 83450    0.0
Name: new_cases, dtype: float64
83444 83451    1561.0
Name: new_cases, dtype: float64
83445 83452    718.0
Name: new_cases, dtype: float64
83446 83453    0.0
Name: new_cases, dtype: float64
83447 83454    0.0
Name: new_cases, dtype: float64
83448 83455    1145.0
Name: new_cases, dtype: float64
83449 83456    350.0
Name: new_cases, dtype: float64
83450 83457    595.0
Name: new_cases, dtype: float64
83451 83458    434.0
Name: new_cases, dtype: float64
83452 83459    449.0
Name: new_cases, dtype: float64
83453 83460    0.0
Name: new_cases, dtype: float64
83454 83461    0.0
Name: new_cases, dtype: float64
83455 83462    854.0
Name: new_cases, dtype: float64
83456 83463    227.0
Name: new_cases, dtype: float64
83457 83464    400.0
Name: new_cases, dtype: float64
83458 83465    0.0
Name: new_cases, dtype: float64
83459 83466    0.0
Name: new_cases, dtype: float64
83460 83467    0.0
Name: new_cases, dtype: float64
83461 83468    0.0
Name: new_cases, dtype: float64
83462 83469    640.0
Name: new_cases, dtype: float64
83463 83470    239.0
Name: new_cases, dtype: float64
83464 83471    327.0
Name: new_cases, dtype: float64
83465 83472    0.0
Name: new_cases, dtype: float64
83466 83473    0.0
Name: new_cases, dtype: float64
83467 83474    0.0
Name: new_cases, dtype: float64
83468 83475    0.0
Name: new_cases, dtype: float64
83469 83476    571.0
Name: new_cases, dtype: float64
83470 83477    163.0
Name: new_cases, dtype: float64
83471 83478    281.0
Name: new_cases, dtype: float64
83472 83479    162.0
Name: new_cases, dtype: float64
83473 83480    152.0
Name: new_cases, dtype: float64
83474 83481    0.0
Name: new_cases, dtype: float64
83475 83482    0.0
Name: new_cases, dtype: float64
83476 83483    283.0
Name: new_cases, dtype: float64
83477 83484    154.0
Name: new_cases, dtype: float64
83478 83485    191.0
Name: new_cases, dtype: float64
83479 83486    114.0
Name: new_cases, dtype: float64
83480 83487    144.0
Name: new_cases, dtype: float64
83481 83488    0.0
Name: new_cases, dtype: float64
83482 83489    0.0
Name: new_cases, dtype: float64
83483 83490    260.0
Name: new_cases, dtype: float64
83484 83491    85.0
Name: new_cases, dtype: float64
83485 83492    229.0
Name: new_cases, dtype: float64
83486 83493    115.0
Name: new_cases, dtype: float64
83487 83494    119.0
Name: new_cases, dtype: float64
83488 83495    0.0
Name: new_cases, dtype: float64
83489 83496    0.0
Name: new_cases, dtype: float64
83490 83497    295.0
Name: new_cases, dtype: float64
83491 83498    119.0
Name: new_cases, dtype: float64
83492 83499    237.0
Name: new_cases, dtype: float64
83493 83500    139.0
Name: new_cases, dtype: float64
83494 83501    160.0
Name: new_cases, dtype: float64
83495 83502    0.0
Name: new_cases, dtype: float64
83496 83503    0.0
Name: new_cases, dtype: float64

83497 83504    345.0
Name: new_cases, dtype: float64
83498 83505    190.0
Name: new_cases, dtype: float64
83499 83506    205.0
Name: new_cases, dtype: float64
83500 83507    202.0
Name: new_cases, dtype: float64
83501 83508    182.0
Name: new_cases, dtype: float64
83502 83509    0.0
Name: new_cases, dtype: float64
83503 83510    0.0
Name: new_cases, dtype: float64
83504 83511    367.0
Name: new_cases, dtype: float64
83505 83512    143.0
Name: new_cases, dtype: float64
83506 83513    225.0
Name: new_cases, dtype: float64
83507 83514    145.0
Name: new_cases, dtype: float64
83508 83515    147.0
Name: new_cases, dtype: float64
83509 83516    0.0
Name: new_cases, dtype: float64
83510 83517    0.0
Name: new_cases, dtype: float64
83511 83518    384.0
Name: new_cases, dtype: float64
83512 83519    139.0
Name: new_cases, dtype: float64
83513 83520    267.0
Name: new_cases, dtype: float64
83514 83521    233.0
Name: new_cases, dtype: float64
83515 83522    220.0
Name: new_cases, dtype: float64
83516 83523    0.0
Name: new_cases, dtype: float64
83517 83524    0.0
Name: new_cases, dtype: float64
83518 83525    390.0
Name: new_cases, dtype: float64
83519 83526    182.0
Name: new_cases, dtype: float64
83520 83527    324.0
Name: new_cases, dtype: float64
83521 83528    193.0
Name: new_cases, dtype: float64
83522 83529    239.0
Name: new_cases, dtype: float64
83523 83530    0.0
Name: new_cases, dtype: float64
83524 83531    0.0
Name: new_cases, dtype: float64
83525 83532    370.0
Name: new_cases, dtype: float64
83526 83533    152.0
Name: new_cases, dtype: float64
83527 83534    270.0
Name: new_cases, dtype: float64
83528 83535    208.0
Name: new_cases, dtype: float64
83529 83536    186.0
Name: new_cases, dtype: float64
83530 83537    0.0
Name: new_cases, dtype: float64
83531 83538    0.0
Name: new_cases, dtype: float64
83532 83539    381.0
Name: new_cases, dtype: float64
83533 83540    145.0
Name: new_cases, dtype: float64
83534 83541    234.0
Name: new_cases, dtype: float64
83535 83542    265.0
Name: new_cases, dtype: float64
83536 83543    182.0
Name: new_cases, dtype: float64
83537 83544    0.0
Name: new_cases, dtype: float64
83538 83545    0.0
Name: new_cases, dtype: float64
83539 83546    423.0
Name: new_cases, dtype: float64
83540 83547    185.0
Name: new_cases, dtype: float64
83541 83548    297.0
Name: new_cases, dtype: float64
83542 83549    266.0
Name: new_cases, dtype: float64
83543 83550    281.0
Name: new_cases, dtype: float64
83544 83551    0.0
Name: new_cases, dtype: float64
83545 83552    0.0
Name: new_cases, dtype: float64
83546 83553    542.0
Name: new_cases, dtype: float64
83547 83554    165.0
Name: new_cases, dtype: float64
83548 83555    245.0
Name: new_cases, dtype: float64
83549 83556    298.0
Name: new_cases, dtype: float64
83550 83557    260.0
Name: new_cases, dtype: float64
83551 83558    0.0
Name: new_cases, dtype: float64
83552 83559    0.0
Name: new_cases, dtype: float64
83553 83560    608.0
Name: new_cases, dtype: float64
83554 83561    182.0
Name: new_cases, dtype: float64
83555 83562    387.0
Name: new_cases, dtype: float64
83556 83563    239.0
Name: new_cases, dtype: float64
83557 83564    224.0
Name: new_cases, dtype: float64
83558 83565    0.0
Name: new_cases, dtype: float64
83559 83566    0.0
Name: new_cases, dtype: float64
83560 83567    0.0
Name: new_cases, dtype: float64
83561 83568    520.0
Name: new_cases, dtype: float64
83562 83569    168.0
Name: new_cases, dtype: float64
83563 83570    387.0
Name: new_cases, dtype: float64
83564 83571    287.0
Name: new_cases, dtype: float64
83565 83572    0.0
Name: new_cases, dtype: float64
83566 83573    0.0
Name: new_cases, dtype: float64
83567 83574    413.0
Name: new_cases, dtype: float64
83568 83575    182.0
Name: new_cases, dtype: float64
83569 83576    272.0
Name: new_cases, dtype: float64
83570 83577    215.0
Name: new_cases, dtype: float64
83571 83578    197.0
Name: new_cases, dtype: float64
83572 83579    0.0
Name: new_cases, dtype: float64
83573 83580    0.0
Name: new_cases, dtype: float64
83574 83581    398.0
Name: new_cases, dtype: float64
83575 83582    175.0
Name: new_cases, dtype: float64
83576 83583    285.0
Name: new_cases, dtype: float64
83577 83584    209.0
Name: new_cases, dtype: float64
83578 83585    194.0
Name: new_cases, dtype: float64
83579 83586    0.0
Name: new_cases, dtype: float64
83580 83587    0.0
Name: new_cases, dtype: float64
83581 83588    367.0
Name: new_cases, dtype: float64
83582 83589    220.0
Name: new_cases, dtype: float64
83583 83590    232.0
Name: new_cases, dtype: float64
83584 83591    219.0
Name: new_cases, dtype: float64
83585 83592    160.0
Name: new_cases, dtype: float64
83586 83593    0.0
Name: new_cases, dtype: float64
83587 83594    0.0
Name: new_cases, dtype: float64
83588 83595    290.0
Name: new_cases, dtype: float64
83589 83596    147.0
Name: new_cases, dtype: float64
83590 83597    208.0
Name: new_cases, dtype: float64
83591 83598    170.0
Name: new_cases, dtype: float64
83592 83599    133.0
Name: new_cases, dtype: float64
83593 83600    0.0
Name: new_cases, dtype: float64
83594 83601    0.0
Name: new_cases, dtype: float64
83595 83602    278.0
Name: new_cases, dtype: float64
83596 83603    121.0
Name: new_cases, dtype: float64
83597 83604    196.0
Name: new_cases, dtype: float64
83598 83605    0.0
Name: new_cases, dtype: float64
83599 83606    174.0
Name: new_cases, dtype: float64
83600 83607    0.0
Name: new_cases, dtype: float64
83601 83608    0.0
Name: new_cases, dtype: float64
83602 83609    268.0
Name: new_cases, dtype: float64
83603 83610    49.0
Name: new_cases, dtype: float64
83604 83611    159.0
Name: new_cases, dtype: float64
83605 83612    67.0
Name: new_cases, dtype: float64
83606 83613    80.0
Name: new_cases, dtype: float64
83607 83614    0.0
Name: new_cases, dtype: float64
83608 83615    0.0
Name: new_cases, dtype: float64
83609 83616    0.0
Name: new_cases, dtype: float64
83610 83617    34.0
Name: new_cases, dtype: float64
83611 83618    90.0
Name: new_cases, dtype: float64
83612 83619    80.0
Name: new_cases, dtype: float64
83613 83620    81.0
Name: new_cases, dtype: float64
83614 83621    0.0
Name: new_cases, dtype: float64
83615 83622    0.0
Name: new_cases, dtype: float64
83616 83623    102.0
Name: new_cases, dtype: float64
83617 83624    51.0
Name: new_cases, dtype: float64
83618 83625    44.0
Name: new_cases, dtype: float64
83619 83626    61.0
Name: new_cases, dtype: float64
83620 83627    94.0
Name: new_cases, dtype: float64
83621 83628    0.0
Name: new_cases, dtype: float64
83622 83629    0.0
Name: new_cases, dtype: float64
83623 83630    74.0
Name: new_cases, dtype: float64
83624 83631    35.0
Name: new_cases, dtype: float64
83625 83632    52.0
Name: new_cases, dtype: float64
83626 83633    40.0
Name: new_cases, dtype: float64
83627 83634    23.0
Name: new_cases, dtype: float64
83628 83635    0.0
Name: new_cases, dtype: float64
83629 83636    0.0
Name: new_cases, dtype: float64
83630 83637    39.0
Name: new_cases, dtype: float64
83631 83638    21.0
Name: new_cases, dtype: float64
83632 83639    19.0
Name: new_cases, dtype: float64
83633 83640    18.0
Name: new_cases, dtype: float64
83634 83641    13.0
Name: new_cases, dtype: float64
83635 83642    0.0
Name: new_cases, dtype: float64
83636 83643    0.0
Name: new_cases, dtype: float64
83637 83644    19.0
Name: new_cases, dtype: float64
83638 83645    12.0
Name: new_cases, dtype: float64
83639 83646    0.0
Name: new_cases, dtype: float64
83640 83647    39.0
Name: new_cases, dtype: float64
83641 83648    14.0
Name: new_cases, dtype: float64
83642 83649    0.0
Name: new_cases, dtype: float64
83643 83650    0.0
Name: new_cases, dtype: float64
83644 83651    42.0
Name: new_cases, dtype: float64
83645 83652    53.0
Name: new_cases, dtype: float64
83646 83653    92.0
Name: new_cases, dtype: float64
83647 83654    108.0
Name: new_cases, dtype: float64
83648 83655    136.0
Name: new_cases, dtype: float64
83649 83656    0.0
Name: new_cases, dtype: float64
83650 83657    0.0
Name: new_cases, dtype: float64
83651 83658    398.0
Name: new_cases, dtype: float64
83652 83659    118.0
Name: new_cases, dtype: float64
83653 83660    201.0
Name: new_cases, dtype: float64
83654 83661    131.0
Name: new_cases, dtype: float64
83655 83662    131.0
Name: new_cases, dtype: float64
83656 83663    0.0
Name: new_cases, dtype: float64
83657 83664    0.0
Name: new_cases, dtype: float64
83658 83665    247.0
Name: new_cases, dtype: float64
83659 83666    134.0
Name: new_cases, dtype: float64
83660 83667    118.0
Name: new_cases, dtype: float64
83661 83668    123.0
Name: new_cases, dtype: float64
83662 83669    127.0
Name: new_cases, dtype: float64
83663 83670    0.0
Name: new_cases, dtype: float64
83664 83671    0.0
Name: new_cases, dtype: float64
83665 83672    226.0
Name: new_cases, dtype: float64

83666 83673    89.0
Name: new_cases, dtype: float64
83667 83674    141.0
Name: new_cases, dtype: float64
83668 83675    94.0
Name: new_cases, dtype: float64
83669 83676    103.0
Name: new_cases, dtype: float64
83670 83677    0.0
Name: new_cases, dtype: float64
83671 83678    0.0
Name: new_cases, dtype: float64
83672 83679    139.0
Name: new_cases, dtype: float64
83673 83680    86.0
Name: new_cases, dtype: float64
83674 83681    107.0
Name: new_cases, dtype: float64
83675 83682    72.0
Name: new_cases, dtype: float64
83676 83683    54.0
Name: new_cases, dtype: float64
83677 83684    0.0
Name: new_cases, dtype: float64
83678 83685    0.0
Name: new_cases, dtype: float64
83679 83686    120.0
Name: new_cases, dtype: float64
83680 83687    52.0
Name: new_cases, dtype: float64
83681 83688    102.0
Name: new_cases, dtype: float64
83682 83689    68.0
Name: new_cases, dtype: float64
83683 83690    50.0
Name: new_cases, dtype: float64
83684 83691    0.0
Name: new_cases, dtype: float64
83685 83692    0.0
Name: new_cases, dtype: float64
83686 83693    133.0
Name: new_cases, dtype: float64
83687 83694    42.0
Name: new_cases, dtype: float64
83688 83695    61.0
Name: new_cases, dtype: float64
83689 83696    47.0
Name: new_cases, dtype: float64
83690 83697    50.0
Name: new_cases, dtype: float64
83691 83698    0.0
Name: new_cases, dtype: float64
83692 83699    0.0
Name: new_cases, dtype: float64
83693 83700    95.0
Name: new_cases, dtype: float64
83694 83701    89.0
Name: new_cases, dtype: float64
83695 83702    76.0
Name: new_cases, dtype: float64
83696 83703    63.0
Name: new_cases, dtype: float64
83697 83704    67.0
Name: new_cases, dtype: float64
83698 83705    0.0
Name: new_cases, dtype: float64
83699 83706    0.0
Name: new_cases, dtype: float64
83700 83707    145.0
Name: new_cases, dtype: float64
83701 83708    86.0
Name: new_cases, dtype: float64
83702 83709    96.0
Name: new_cases, dtype: float64
83703 83710    130.0
Name: new_cases, dtype: float64
83704 83711    75.0
Name: new_cases, dtype: float64
83705 83712    0.0
Name: new_cases, dtype: float64
83706 83713    0.0
Name: new_cases, dtype: float64
83707 83714    155.0
Name: new_cases, dtype: float64
83708 83715    88.0
Name: new_cases, dtype: float64
83709 83716    144.0
Name: new_cases, dtype: float64
83710 83717    77.0
Name: new_cases, dtype: float64
83711 83718    121.0
Name: new_cases, dtype: float64
83712 83719    0.0
Name: new_cases, dtype: float64
83713 83720    0.0
Name: new_cases, dtype: float64
83714 83721    143.0
Name: new_cases, dtype: float64
83715 83722    113.0
Name: new_cases, dtype: float64
83716 83723    97.0
Name: new_cases, dtype: float64
83717 83724    85.0
Name: new_cases, dtype: float64
83718 83725    92.0
Name: new_cases, dtype: float64
83719 83726    0.0
Name: new_cases, dtype: float64
83720 83727    0.0
Name: new_cases, dtype: float64
83721 83728    166.0
Name: new_cases, dtype: float64
83722 83729    96.0
Name: new_cases, dtype: float64
83723 83730    102.0
Name: new_cases, dtype: float64
83724 83731    102.0
Name: new_cases, dtype: float64
83725 83732    91.0
Name: new_cases, dtype: float64
83726 83733    0.0
Name: new_cases, dtype: float64
83727 83734    0.0
Name: new_cases, dtype: float64
83728 83735    151.0
Name: new_cases, dtype: float64
83729 83736    101.0
Name: new_cases, dtype: float64
83730 83737    111.0
Name: new_cases, dtype: float64
83731 83738    136.0
Name: new_cases, dtype: float64
83732 83739    74.0
Name: new_cases, dtype: float64
83733 83740    0.0
Name: new_cases, dtype: float64
83734 83741    0.0
Name: new_cases, dtype: float64
83735 83742    168.0
Name: new_cases, dtype: float64
83736 83743    68.0
Name: new_cases, dtype: float64
83737 83744    132.0
Name: new_cases, dtype: float64
83738 83745    89.0
Name: new_cases, dtype: float64
83739 83746    107.0
Name: new_cases, dtype: float64
83740 83747    0.0
Name: new_cases, dtype: float64
83741 83748    0.0
Name: new_cases, dtype: float64
83742 83749    195.0
Name: new_cases, dtype: float64
83743 83750    99.0
Name: new_cases, dtype: float64
83744 83751    161.0
Name: new_cases, dtype: float64
83745 83752    160.0
Name: new_cases, dtype: float64
83746 83753    77.0
Name: new_cases, dtype: float64
83747 83754    0.0
Name: new_cases, dtype: float64
83748 83755    0.0
Name: new_cases, dtype: float64
83749 83756    178.0
Name: new_cases, dtype: float64
83750 83757    104.0
Name: new_cases, dtype: float64
83751 83758    163.0
Name: new_cases, dtype: float64
83752 83759    165.0
Name: new_cases, dtype: float64
83753 83760    92.0
Name: new_cases, dtype: float64
83754 83761    0.0
Name: new_cases, dtype: float64
83755 83762    0.0
Name: new_cases, dtype: float64
83756 83763    262.0
Name: new_cases, dtype: float64
83757 83764    103.0
Name: new_cases, dtype: float64
83758 83765    246.0
Name: new_cases, dtype: float64
83759 83766    131.0
Name: new_cases, dtype: float64
83760 83767    141.0
Name: new_cases, dtype: float64
83761 83768    0.0
Name: new_cases, dtype: float64
83762 83769    0.0
Name: new_cases, dtype: float64
83763 83770    0.0
Name: new_cases, dtype: float64
83764 83771    521.0
Name: new_cases, dtype: float64
83765 83772    239.0
Name: new_cases, dtype: float64
83766 83773    138.0
Name: new_cases, dtype: float64
83767 83774    182.0
Name: new_cases, dtype: float64
83768 83775    0.0
Name: new_cases, dtype: float64
83769 83776    0.0
Name: new_cases, dtype: float64
83770 83777    0.0
Name: new_cases, dtype: float64
83771 83778    409.0
Name: new_cases, dtype: float64
83772 83779    98.0
Name: new_cases, dtype: float64
83773 83780    433.0
Name: new_cases, dtype: float64
83774 83781    219.0
Name: new_cases, dtype: float64
83775 83782    0.0
Name: new_cases, dtype: float64
83776 83783    0.0
Name: new_cases, dtype: float64
83777 83784    452.0
Name: new_cases, dtype: float64
83778 83785    185.0
Name: new_cases, dtype: float64
83779 83786    347.0
Name: new_cases, dtype: float64
83780 83787    243.0
Name: new_cases, dtype: float64
83781 83788    179.0
Name: new_cases, dtype: float64
83782 83789    0.0
Name: new_cases, dtype: float64
83783 83790    0.0
Name: new_cases, dtype: float64
83784 83791    490.0
Name: new_cases, dtype: float64
83785 83792    128.0
Name: new_cases, dtype: float64
83786 83793    495.0
Name: new_cases, dtype: float64
83787 83794    299.0
Name: new_cases, dtype: float64
83788 83795    300.0
Name: new_cases, dtype: float64
83789 83796    0.0
Name: new_cases, dtype: float64
83790 83797    0.0
Name: new_cases, dtype: float64
83791 83798    677.0
Name: new_cases, dtype: float64
83792 83799    159.0
Name: new_cases, dtype: float64
83793 83800    556.0
Name: new_cases, dtype: float64
83794 83801    421.0
Name: new_cases, dtype: float64
83795 83802    335.0
Name: new_cases, dtype: float64
83796 83803    0.0
Name: new_cases, dtype: float64
83797 83804    0.0
Name: new_cases, dtype: float64
83798 83805    902.0
Name: new_cases, dtype: float64
83799 83806    171.0
Name: new_cases, dtype: float64
83800 83807    585.0
Name: new_cases, dtype: float64
83801 83808    570.0
Name: new_cases, dtype: float64
83802 83809    438.0
Name: new_cases, dtype: float64
83803 83810    0.0
Name: new_cases, dtype: float64
83804 83811    0.0
Name: new_cases, dtype: float64
83805 83812    935.0
Name: new_cases, dtype: float64
83806 83813    199.0
Name: new_cases, dtype: float64
83807 83814    666.0
Name: new_cases, dtype: float64
83808 83815    486.0
Name: new_cases, dtype: float64
83809 83816    369.0
Name: new_cases, dtype: float64
83810 83817    0.0
Name: new_cases, dtype: float64
83811 83818    0.0
Name: new_cases, dtype: float64
83812 83819    871.0
Name: new_cases, dtype: float64
83813 83820    211.0
Name: new_cases, dtype: float64
83814 83821    711.0
Name: new_cases, dtype: float64
83815 83822    537.0
Name: new_cases, dtype: float64
83816 83823    349.0
Name: new_cases, dtype: float64
83817 83824    0.0
Name: new_cases, dtype: float64
83818 83825    0.0
Name: new_cases, dtype: float64
83819 83826    921.0
Name: new_cases, dtype: float64
83820 83827    229.0
Name: new_cases, dtype: float64
83821 83828    600.0
Name: new_cases, dtype: float64
83822 83829    582.0
Name: new_cases, dtype: float64
83823 83830    543.0
Name: new_cases, dtype: float64
83824 83831    0.0
Name: new_cases, dtype: float64
83825 83832    0.0
Name: new_cases, dtype: float64
83826 83833    734.0
Name: new_cases, dtype: float64
83827 83834    486.0
Name: new_cases, dtype: float64
83828 83835    1053.0
Name: new_cases, dtype: float64
83829 83836    1230.0
Name: new_cases, dtype: float64
83830 83837    1280.0
Name: new_cases, dtype: float64
83831 83838    0.0
Name: new_cases, dtype: float64
83832 83839    0.0
Name: new_cases, dtype: float64
83833 83840    1592.0
Name: new_cases, dtype: float64
83834 83841    877.0
Name: new_cases, dtype: float64

83835 83842    2131.0
Name: new_cases, dtype: float64
83836 83843    1932.0
Name: new_cases, dtype: float64
83837 83844    1905.0
Name: new_cases, dtype: float64
83838 Series([], Name: new_cases, dtype: float64)
83839 Series([], Name: new_cases, dtype: float64)
83840 Series([], Name: new_cases, dtype: float64)
83841 Series([], Name: new_cases, dtype: float64)
83842 Series([], Name: new_cases, dtype: float64)
83843 Series([], Name: new_cases, dtype: float64)
83844 Series([], Name: new_cases, dtype: float64)
85876 85883    0.0
Name: new_cases, dtype: float64
85877 85884    0.0
Name: new_cases, dtype: float64
85878 85885    0.0
Name: new_cases, dtype: float64
85879 85886    2.0
Name: new_cases, dtype: float64
85880 85887    2.0
Name: new_cases, dtype: float64
85881 85888    2.0
Name: new_cases, dtype: float64
85882 85889    1.0
Name: new_cases, dtype: float64
85883 85890    1.0
Name: new_cases, dtype: float64
85884 85891    1.0
Name: new_cases, dtype: float64
85885 85892    1.0
Name: new_cases, dtype: float64
85886 85893    0.0
Name: new_cases, dtype: float64
85887 85894    0.0
Name: new_cases, dtype: float64
85888 85895    0.0
Name: new_cases, dtype: float64
85889 85896    1.0
Name: new_cases, dtype: float64
85890 85897    3.0
Name: new_cases, dtype: float64
85891 85898    0.0
Name: new_cases, dtype: float64
85892 85899    0.0
Name: new_cases, dtype: float64
85893 85900    0.0
Name: new_cases, dtype: float64
85894 85901    0.0
Name: new_cases, dtype: float64
85895 85902    0.0
Name: new_cases, dtype: float64
85896 85903    0.0
Name: new_cases, dtype: float64
85897 85904    0.0
Name: new_cases, dtype: float64
85898 85905    0.0
Name: new_cases, dtype: float64
85899 85906    0.0
Name: new_cases, dtype: float64
85900 85907    0.0
Name: new_cases, dtype: float64
85901 85908    0.0
Name: new_cases, dtype: float64
85902 85909    1.0
Name: new_cases, dtype: float64
85903 85910    2.0
Name: new_cases, dtype: float64
85904 85911    4.0
Name: new_cases, dtype: float64
85905 85912    0.0
Name: new_cases, dtype: float64
85906 85913    0.0
Name: new_cases, dtype: float64
85907 85914    7.0
Name: new_cases, dtype: float64
85908 85915    14.0
Name: new_cases, dtype: float64
85909 85916    5.0
Name: new_cases, dtype: float64
85910 85917    28.0
Name: new_cases, dtype: float64
85911 85918    10.0
Name: new_cases, dtype: float64
85912 85919    6.0
Name: new_cases, dtype: float64
85913 85920    18.0
Name: new_cases, dtype: float64
85914 85921    12.0
Name: new_cases, dtype: float64
85915 85922    20.0
Name: new_cases, dtype: float64
85916 85923    9.0
Name: new_cases, dtype: float64
85917 85924    39.0
Name: new_cases, dtype: float64
85918 85925    41.0
Name: new_cases, dtype: float64
85919 85926    190.0
Name: new_cases, dtype: float64
85920 85927    125.0
Name: new_cases, dtype: float64
85921 85928    120.0
Name: new_cases, dtype: float64
85922 85929    117.0
Name: new_cases, dtype: float64
85923 85930    110.0
Name: new_cases, dtype: float64
85924 85931    130.0
Name: new_cases, dtype: float64
85925 85932    153.0
Name: new_cases, dtype: float64
85926 85933    123.0
Name: new_cases, dtype: float64
85927 85934    212.0
Name: new_cases, dtype: float64
85928 85935    106.0
Name: new_cases, dtype: float64
85929 85936    172.0
Name: new_cases, dtype: float64
85930 85937    235.0
Name: new_cases, dtype: float64
85931 85938    130.0
Name: new_cases, dtype: float64
85932 85939    159.0
Name: new_cases, dtype: float64
85933 85940    150.0
Name: new_cases, dtype: float64
85934 85941    156.0
Name: new_cases, dtype: float64
85935 85942    140.0
Name: new_cases, dtype: float64
85936 85943    142.0
Name: new_cases, dtype: float64
85937 85944    208.0
Name: new_cases, dtype: float64
85938 85945    217.0
Name: new_cases, dtype: float64
85939 85946    150.0
Name: new_cases, dtype: float64
85940 85947    179.0
Name: new_cases, dtype: float64
85941 85948    131.0
Name: new_cases, dtype: float64
85942 85949    170.0
Name: new_cases, dtype: float64
85943 85950    156.0
Name: new_cases, dtype: float64
85944 85951    109.0
Name: new_cases, dtype: float64
85945 85952    118.0
Name: new_cases, dtype: float64
85946 85953    184.0
Name: new_cases, dtype: float64
85947 85954    153.0
Name: new_cases, dtype: float64
85948 85955    134.0
Name: new_cases, dtype: float64
85949 85956    170.0
Name: new_cases, dtype: float64
85950 85957    85.0
Name: new_cases, dtype: float64
85951 85958    110.0
Name: new_cases, dtype: float64
85952 85959    69.0
Name: new_cases, dtype: float64
85953 85960    54.0
Name: new_cases, dtype: float64
85954 85961    84.0
Name: new_cases, dtype: float64
85955 85962    36.0
Name: new_cases, dtype: float64
85956 85963    57.0
Name: new_cases, dtype: float64
85957 85964    50.0
Name: new_cases, dtype: float64
85958 85965    71.0
Name: new_cases, dtype: float64
85959 85966    88.0
Name: new_cases, dtype: float64
85960 85967    51.0
Name: new_cases, dtype: float64
85961 85968    38.0
Name: new_cases, dtype: float64
85962 85969    40.0
Name: new_cases, dtype: float64
85963 85970    31.0
Name: new_cases, dtype: float64
85964 85971    94.0
Name: new_cases, dtype: float64
85965 85972    57.0
Name: new_cases, dtype: float64
85966 85973    69.0
Name: new_cases, dtype: float64
85967 85974    105.0
Name: new_cases, dtype: float64
85968 85975    122.0
Name: new_cases, dtype: float64
85969 85976    55.0
Name: new_cases, dtype: float64
85970 85977    30.0
Name: new_cases, dtype: float64
85971 85978    45.0
Name: new_cases, dtype: float64
85972 85979    39.0
Name: new_cases, dtype: float64
85973 85980    68.0
Name: new_cases, dtype: float64
85974 85981    54.0
Name: new_cases, dtype: float64
85975 85982    67.0
Name: new_cases, dtype: float64
85976 85983    70.0
Name: new_cases, dtype: float64
85977 85984    16.0
Name: new_cases, dtype: float64
85978 85985    37.0
Name: new_cases, dtype: float64
85979 85986    40.0
Name: new_cases, dtype: float64
85980 85987    36.0
Name: new_cases, dtype: float64
85981 85988    17.0
Name: new_cases, dtype: float64
85982 85989    22.0
Name: new_cases, dtype: float64
85983 85990    47.0
Name: new_cases, dtype: float64
85984 85991    37.0
Name: new_cases, dtype: float64
85985 85992    31.0
Name: new_cases, dtype: float64
85986 85993    50.0
Name: new_cases, dtype: float64
85987 85994    78.0
Name: new_cases, dtype: float64
85988 85995    48.0
Name: new_cases, dtype: float64
85989 85996    60.0
Name: new_cases, dtype: float64
85990 85997    172.0
Name: new_cases, dtype: float64
85991 85998    187.0
Name: new_cases, dtype: float64
85992 85999    15.0
Name: new_cases, dtype: float64
85993 86000    10.0
Name: new_cases, dtype: float64
85994 86001    103.0
Name: new_cases, dtype: float64
85995 86002    30.0
Name: new_cases, dtype: float64
85996 86003    57.0
Name: new_cases, dtype: float64
85997 86004    38.0
Name: new_cases, dtype: float64
85998 86005    20.0
Name: new_cases, dtype: float64
85999 86006    93.0
Name: new_cases, dtype: float64
86000 86007    277.0
Name: new_cases, dtype: float64
86001 86008    19.0
Name: new_cases, dtype: float64
86002 86009    37.0
Name: new_cases, dtype: float64
86003 86010    19.0
Name: new_cases, dtype: float64
86004 86011    7.0
Name: new_cases, dtype: float64
86005 86012    7.0
Name: new_cases, dtype: float64
86006 86013    2.0
Name: new_cases, dtype: float64
86007 86014    31.0
Name: new_cases, dtype: float64
86008 86015    33.0
Name: new_cases, dtype: float64
86009 86016    43.0
Name: new_cases, dtype: float64
86010 86017    8.0
Name: new_cases, dtype: float64
86011 86018    41.0
Name: new_cases, dtype: float64
86012 86019    11.0
Name: new_cases, dtype: float64
86013 86020    10.0
Name: new_cases, dtype: float64
86014 86021    14.0
Name: new_cases, dtype: float64
86015 86022    6.0
Name: new_cases, dtype: float64
86016 86023    21.0
Name: new_cases, dtype: float64
86017 86024    16.0
Name: new_cases, dtype: float64
86018 86025    15.0
Name: new_cases, dtype: float64
86019 86026    3.0
Name: new_cases, dtype: float64
86020 86027    6.0
Name: new_cases, dtype: float64
86021 86028    4.0
Name: new_cases, dtype: float64
86022 86029    6.0
Name: new_cases, dtype: float64
86023 86030    10.0
Name: new_cases, dtype: float64

86024 86031    18.0
Name: new_cases, dtype: float64
86025 86032    3.0
Name: new_cases, dtype: float64
86026 86033    2.0
Name: new_cases, dtype: float64
86027 86034    1.0
Name: new_cases, dtype: float64
86028 86035    3.0
Name: new_cases, dtype: float64
86029 86036    5.0
Name: new_cases, dtype: float64
86030 86037    10.0
Name: new_cases, dtype: float64
86031 86038    5.0
Name: new_cases, dtype: float64
86032 86039    5.0
Name: new_cases, dtype: float64
86033 86040    6.0
Name: new_cases, dtype: float64
86034 86041    3.0
Name: new_cases, dtype: float64
86035 86042    6.0
Name: new_cases, dtype: float64
86036 86043    13.0
Name: new_cases, dtype: float64
86037 86044    8.0
Name: new_cases, dtype: float64
86038 86045    14.0
Name: new_cases, dtype: float64
86039 86046    7.0
Name: new_cases, dtype: float64
86040 86047    4.0
Name: new_cases, dtype: float64
86041 86048    5.0
Name: new_cases, dtype: float64
86042 86049    3.0
Name: new_cases, dtype: float64
86043 86050    18.0
Name: new_cases, dtype: float64
86044 86051    9.0
Name: new_cases, dtype: float64
86045 86052    15.0
Name: new_cases, dtype: float64
86046 86053    21.0
Name: new_cases, dtype: float64
86047 86054    15.0
Name: new_cases, dtype: float64
86048 86055    16.0
Name: new_cases, dtype: float64
86049 86056    9.0
Name: new_cases, dtype: float64
86050 86057    21.0
Name: new_cases, dtype: float64
86051 86058    23.0
Name: new_cases, dtype: float64
86052 86059    13.0
Name: new_cases, dtype: float64
86053 86060    7.0
Name: new_cases, dtype: float64
86054 86061    39.0
Name: new_cases, dtype: float64
86055 86062    13.0
Name: new_cases, dtype: float64
86056 86063    8.0
Name: new_cases, dtype: float64
86057 86064    12.0
Name: new_cases, dtype: float64
86058 86065    9.0
Name: new_cases, dtype: float64
86059 86066    14.0
Name: new_cases, dtype: float64
86060 86067    2.0
Name: new_cases, dtype: float64
86061 86068    1.0
Name: new_cases, dtype: float64
86062 86069    21.0
Name: new_cases, dtype: float64
86063 86070    15.0
Name: new_cases, dtype: float64
86064 86071    25.0
Name: new_cases, dtype: float64
86065 86072    7.0
Name: new_cases, dtype: float64
86066 86073    13.0
Name: new_cases, dtype: float64
86067 86074    11.0
Name: new_cases, dtype: float64
86068 86075    9.0
Name: new_cases, dtype: float64
86069 86076    11.0
Name: new_cases, dtype: float64
86070 86077    15.0
Name: new_cases, dtype: float64
86071 86078    20.0
Name: new_cases, dtype: float64
86072 86079    26.0
Name: new_cases, dtype: float64
86073 86080    25.0
Name: new_cases, dtype: float64
86074 86081    12.0
Name: new_cases, dtype: float64
86075 86082    7.0
Name: new_cases, dtype: float64
86076 86083    16.0
Name: new_cases, dtype: float64
86077 86084    5.0
Name: new_cases, dtype: float64
86078 86085    9.0
Name: new_cases, dtype: float64
86079 86086    8.0
Name: new_cases, dtype: float64
86080 86087    10.0
Name: new_cases, dtype: float64
86081 86088    7.0
Name: new_cases, dtype: float64
86082 86089    11.0
Name: new_cases, dtype: float64
86083 86090    6.0
Name: new_cases, dtype: float64
86084 86091    5.0
Name: new_cases, dtype: float64
86085 86092    10.0
Name: new_cases, dtype: float64
86086 86093    11.0
Name: new_cases, dtype: float64
86087 86094    17.0
Name: new_cases, dtype: float64
86088 86095    6.0
Name: new_cases, dtype: float64
86089 86096    14.0
Name: new_cases, dtype: float64
86090 86097    6.0
Name: new_cases, dtype: float64
86091 86098    14.0
Name: new_cases, dtype: float64
86092 86099    11.0
Name: new_cases, dtype: float64
86093 86100    6.0
Name: new_cases, dtype: float64
86094 86101    6.0
Name: new_cases, dtype: float64
86095 86102    62.0
Name: new_cases, dtype: float64
86096 86103    100.0
Name: new_cases, dtype: float64
86097 86104    24.0
Name: new_cases, dtype: float64
86098 86105    45.0
Name: new_cases, dtype: float64
86099 86106    182.0
Name: new_cases, dtype: float64
86100 86107    58.0
Name: new_cases, dtype: float64
86101 86108    47.0
Name: new_cases, dtype: float64
86102 86109    31.0
Name: new_cases, dtype: float64
86103 86110    23.0
Name: new_cases, dtype: float64
86104 86111    62.0
Name: new_cases, dtype: float64
86105 86112    21.0
Name: new_cases, dtype: float64
86106 86113    95.0
Name: new_cases, dtype: float64
86107 86114    20.0
Name: new_cases, dtype: float64
86108 86115    52.0
Name: new_cases, dtype: float64
86109 86116    57.0
Name: new_cases, dtype: float64
86110 86117    82.0
Name: new_cases, dtype: float64
86111 86118    147.0
Name: new_cases, dtype: float64
86112 86119    71.0
Name: new_cases, dtype: float64
86113 86120    111.0
Name: new_cases, dtype: float64
86114 86121    82.0
Name: new_cases, dtype: float64
86115 86122    150.0
Name: new_cases, dtype: float64
86116 86123    115.0
Name: new_cases, dtype: float64
86117 86124    101.0
Name: new_cases, dtype: float64
86118 86125    89.0
Name: new_cases, dtype: float64
86119 86126    260.0
Name: new_cases, dtype: float64
86120 86127    287.0
Name: new_cases, dtype: float64
86121 86128    317.0
Name: new_cases, dtype: float64
86122 86129    293.0
Name: new_cases, dtype: float64
86123 86130    432.0
Name: new_cases, dtype: float64
86124 86131    691.0
Name: new_cases, dtype: float64
86125 86132    489.0
Name: new_cases, dtype: float64
86126 86133    375.0
Name: new_cases, dtype: float64
86127 86134    354.0
Name: new_cases, dtype: float64
86128 86135    374.0
Name: new_cases, dtype: float64
86129 86136    561.0
Name: new_cases, dtype: float64
86130 86137    563.0
Name: new_cases, dtype: float64
86131 86138    660.0
Name: new_cases, dtype: float64
86132 86139    660.0
Name: new_cases, dtype: float64
86133 86140    589.0
Name: new_cases, dtype: float64
86134 86141    629.0
Name: new_cases, dtype: float64
86135 86142    869.0
Name: new_cases, dtype: float64
86136 86143    871.0
Name: new_cases, dtype: float64
86137 86144    865.0
Name: new_cases, dtype: float64
86138 86145    862.0
Name: new_cases, dtype: float64
86139 86146    732.0
Name: new_cases, dtype: float64
86140 86147    847.0
Name: new_cases, dtype: float64
86141 86148    710.0
Name: new_cases, dtype: float64
86142 86149    1228.0
Name: new_cases, dtype: float64
86143 86150    823.0
Name: new_cases, dtype: float64
86144 86151    1240.0
Name: new_cases, dtype: float64
86145 86152    835.0
Name: new_cases, dtype: float64
86146 86153    801.0
Name: new_cases, dtype: float64
86147 86154    649.0
Name: new_cases, dtype: float64
86148 86155    799.0
Name: new_cases, dtype: float64
86149 86156    659.0
Name: new_cases, dtype: float64
86150 86157    957.0
Name: new_cases, dtype: float64
86151 86158    834.0
Name: new_cases, dtype: float64
86152 86159    1054.0
Name: new_cases, dtype: float64
86153 86160    1032.0
Name: new_cases, dtype: float64
86154 86161    1009.0
Name: new_cases, dtype: float64
86155 86162    1755.0
Name: new_cases, dtype: float64
86156 86163    1168.0
Name: new_cases, dtype: float64
86157 86164    852.0
Name: new_cases, dtype: float64
86158 86165    972.0
Name: new_cases, dtype: float64
86159 86166    869.0
Name: new_cases, dtype: float64
86160 86167    822.0
Name: new_cases, dtype: float64
86161 86168    919.0
Name: new_cases, dtype: float64
86162 86169    1304.0
Name: new_cases, dtype: float64
86163 86170    1114.0
Name: new_cases, dtype: float64
86164 86171    1208.0
Name: new_cases, dtype: float64
86165 86172    1103.0
Name: new_cases, dtype: float64
86166 86173    1210.0
Name: new_cases, dtype: float64
86167 86174    660.0
Name: new_cases, dtype: float64
86168 86175    1290.0
Name: new_cases, dtype: float64
86169 86176    958.0
Name: new_cases, dtype: float64
86170 86177    1041.0
Name: new_cases, dtype: float64
86171 86178    1096.0
Name: new_cases, dtype: float64
86172 86179    1884.0
Name: new_cases, dtype: float64
86173 86180    2188.0
Name: new_cases, dtype: float64
86174 86181    970.0
Name: new_cases, dtype: float64
86175 86182    935.0
Name: new_cases, dtype: float64
86176 86183    1109.0
Name: new_cases, dtype: float64
86177 86184    1315.0
Name: new_cases, dtype: float64
86178 86185    1309.0
Name: new_cases, dtype: float64
86179 86186    1212.0
Name: new_cases, dtype: float64
86180 86187    1472.0
Name: new_cases, dtype: float64
86181 86188    851.0
Name: new_cases, dtype: float64
86182 86189    1075.0
Name: new_cases, dtype: float64
86183 86190    1141.0
Name: new_cases, dtype: float64
86184 86191    1123.0
Name: new_cases, dtype: float64
86185 86192    1335.0
Name: new_cases, dtype: float64
86186 86193    1600.0
Name: new_cases, dtype: float64
86187 86194    1012.0
Name: new_cases, dtype: float64
86188 86195    959.0
Name: new_cases, dtype: float64
86189 86196    2234.0
Name: new_cases, dtype: float64

86190 86197    1810.0
Name: new_cases, dtype: float64
86191 86198    1937.0
Name: new_cases, dtype: float64
86192 86199    1229.0
Name: new_cases, dtype: float64
86193 86200    1371.0
Name: new_cases, dtype: float64
86194 86201    1772.0
Name: new_cases, dtype: float64
86195 86202    1295.0
Name: new_cases, dtype: float64
86196 86203    1220.0
Name: new_cases, dtype: float64
86197 86204    1683.0
Name: new_cases, dtype: float64
86198 86205    1153.0
Name: new_cases, dtype: float64
86199 86206    1340.0
Name: new_cases, dtype: float64
86200 86207    2018.0
Name: new_cases, dtype: float64
86201 86208    2062.0
Name: new_cases, dtype: float64
86202 86209    1348.0
Name: new_cases, dtype: float64
86203 86210    1581.0
Name: new_cases, dtype: float64
86204 86211    1247.0
Name: new_cases, dtype: float64
86205 86212    2335.0
Name: new_cases, dtype: float64
86206 86213    1196.0
Name: new_cases, dtype: float64
86207 86214    1594.0
Name: new_cases, dtype: float64
86208 86215    1925.0
Name: new_cases, dtype: float64
86209 86216    1870.0
Name: new_cases, dtype: float64
86210 86217    2525.0
Name: new_cases, dtype: float64
86211 86218    2068.0
Name: new_cases, dtype: float64
86212 86219    2295.0
Name: new_cases, dtype: float64
86213 86220    1704.0
Name: new_cases, dtype: float64
86214 86221    1741.0
Name: new_cases, dtype: float64
86215 86222    2027.0
Name: new_cases, dtype: float64
86216 86223    2593.0
Name: new_cases, dtype: float64
86217 86224    3027.0
Name: new_cases, dtype: float64
86218 86225    2643.0
Name: new_cases, dtype: float64
86219 86226    2451.0
Name: new_cases, dtype: float64
86220 86227    2433.0
Name: new_cases, dtype: float64
86221 86228    2232.0
Name: new_cases, dtype: float64
86222 86229    3309.0
Name: new_cases, dtype: float64
86223 86230    2985.0
Name: new_cases, dtype: float64
86224 86231    3337.0
Name: new_cases, dtype: float64
86225 86232    3211.0
Name: new_cases, dtype: float64
86226 86233    4029.0
Name: new_cases, dtype: float64
86227 86234    3339.0
Name: new_cases, dtype: float64
86228 86235    3306.0
Name: new_cases, dtype: float64
86229 86236    3631.0
Name: new_cases, dtype: float64
86230 86237    4008.0
Name: new_cases, dtype: float64
86231 86238    3170.0
Name: new_cases, dtype: float64
86232 86239    3631.0
Name: new_cases, dtype: float64
86233 86240    4275.0
Name: new_cases, dtype: float64
86234 86241    3346.0
Name: new_cases, dtype: float64
86235 86242    3048.0
Name: new_cases, dtype: float64
86236 86243    3585.0
Name: new_cases, dtype: float64
86237 86244    3680.0
Name: new_cases, dtype: float64
86238 86245    4094.0
Name: new_cases, dtype: float64
86239 86246    5725.0
Name: new_cases, dtype: float64
86240 86247    5728.0
Name: new_cases, dtype: float64
86241 86248    5298.0
Name: new_cases, dtype: float64
86242 86249    4214.0
Name: new_cases, dtype: float64
86243 86250    3455.0
Name: new_cases, dtype: float64
86244 86251    4284.0
Name: new_cases, dtype: float64
86245 86252    4571.0
Name: new_cases, dtype: float64
86246 86253    3391.0
Name: new_cases, dtype: float64
86247 86254    3847.0
Name: new_cases, dtype: float64
86248 86255    3731.0
Name: new_cases, dtype: float64
86249 86256    3100.0
Name: new_cases, dtype: float64
86250 86257    2764.0
Name: new_cases, dtype: float64
86251 86258    3288.0
Name: new_cases, dtype: float64
86252 86259    3384.0
Name: new_cases, dtype: float64
86253 86260    3318.0
Name: new_cases, dtype: float64
86254 86261    3499.0
Name: new_cases, dtype: float64
86255 86262    2464.0
Name: new_cases, dtype: float64
86256 86263    2176.0
Name: new_cases, dtype: float64
86257 86264    2720.0
Name: new_cases, dtype: float64
86258 86265    2998.0
Name: new_cases, dtype: float64
86259 86266    2712.0
Name: new_cases, dtype: float64
86260 86267    2936.0
Name: new_cases, dtype: float64
86261 86268    2461.0
Name: new_cases, dtype: float64
86262 86269    3297.0
Name: new_cases, dtype: float64
86263 86270    2192.0
Name: new_cases, dtype: float64
86264 86271    2468.0
Name: new_cases, dtype: float64
86265 86272    3545.0
Name: new_cases, dtype: float64
86266 86273    1924.0
Name: new_cases, dtype: float64
86267 86274    2253.0
Name: new_cases, dtype: float64
86268 86275    2364.0
Name: new_cases, dtype: float64
86269 86276    2437.0
Name: new_cases, dtype: float64
86270 86277    1828.0
Name: new_cases, dtype: float64
86271 86278    1555.0
Name: new_cases, dtype: float64
86272 86279    1745.0
Name: new_cases, dtype: float64
86273 86280    2063.0
Name: new_cases, dtype: float64
86274 86281    2154.0
Name: new_cases, dtype: float64
86275 86282    1680.0
Name: new_cases, dtype: float64
86276 86283    1683.0
Name: new_cases, dtype: float64
86277 86284    1529.0
Name: new_cases, dtype: float64
86278 86285    1280.0
Name: new_cases, dtype: float64
86279 86286    1448.0
Name: new_cases, dtype: float64
86280 86287    1647.0
Name: new_cases, dtype: float64
86281 86288    1575.0
Name: new_cases, dtype: float64
86282 86289    1470.0
Name: new_cases, dtype: float64
86283 86290    1354.0
Name: new_cases, dtype: float64
86284 86291    1208.0
Name: new_cases, dtype: float64
86285 86292    1063.0
Name: new_cases, dtype: float64
86286 86293    1219.0
Name: new_cases, dtype: float64
86287 86294    1213.0
Name: new_cases, dtype: float64
86288 86295    1576.0
Name: new_cases, dtype: float64
86289 86296    1671.0
Name: new_cases, dtype: float64
86290 86297    1327.0
Name: new_cases, dtype: float64
86291 86298    1116.0
Name: new_cases, dtype: float64
86292 86299    1384.0
Name: new_cases, dtype: float64
86293 86300    1268.0
Name: new_cases, dtype: float64
86294 86301    1360.0
Name: new_cases, dtype: float64
86295 86302    1275.0
Name: new_cases, dtype: float64
86296 86303    1199.0
Name: new_cases, dtype: float64
86297 86304    1302.0
Name: new_cases, dtype: float64
86298 86305    941.0
Name: new_cases, dtype: float64
86299 86306    1133.0
Name: new_cases, dtype: float64
86300 86307    1482.0
Name: new_cases, dtype: float64
86301 86308    1178.0
Name: new_cases, dtype: float64
86302 86309    1294.0
Name: new_cases, dtype: float64
86303 86310    1638.0
Name: new_cases, dtype: float64
86304 86311    1349.0
Name: new_cases, dtype: float64
86305 86312    1070.0
Name: new_cases, dtype: float64
86306 86313    1300.0
Name: new_cases, dtype: float64
86307 86314    1139.0
Name: new_cases, dtype: float64
86308 86315    1285.0
Name: new_cases, dtype: float64
86309 86316    1854.0
Name: new_cases, dtype: float64
86310 86317    1510.0
Name: new_cases, dtype: float64
86311 86318    1739.0
Name: new_cases, dtype: float64
86312 86319    1317.0
Name: new_cases, dtype: float64
86313 86320    1767.0
Name: new_cases, dtype: float64
86314 86321    1889.0
Name: new_cases, dtype: float64
86315 86322    2148.0
Name: new_cases, dtype: float64
86316 86323    2551.0
Name: new_cases, dtype: float64
86317 86324    2331.0
Name: new_cases, dtype: float64
86318 86325    2195.0
Name: new_cases, dtype: float64
86319 86326    2078.0
Name: new_cases, dtype: float64
86320 86327    2341.0
Name: new_cases, dtype: float64
86321 86328    2340.0
Name: new_cases, dtype: float64
86322 86329    2875.0
Name: new_cases, dtype: float64
86323 86330    2847.0
Name: new_cases, dtype: float64
86324 86331    2717.0
Name: new_cases, dtype: float64
86325 86332    2690.0
Name: new_cases, dtype: float64
86326 86333    2776.0
Name: new_cases, dtype: float64
86327 86334    2733.0
Name: new_cases, dtype: float64
86328 86335    3142.0
Name: new_cases, dtype: float64
86329 86336    3332.0
Name: new_cases, dtype: float64
86330 86337    3788.0
Name: new_cases, dtype: float64
86331 86338    2881.0
Name: new_cases, dtype: float64
86332 86339    3418.0
Name: new_cases, dtype: float64
86333 86340    2500.0
Name: new_cases, dtype: float64
86334 86341    3120.0
Name: new_cases, dtype: float64
86335 86342    3744.0
Name: new_cases, dtype: float64
86336 86343    3551.0
Name: new_cases, dtype: float64
86337 86344    4498.0
Name: new_cases, dtype: float64
86338 86345    4519.0
Name: new_cases, dtype: float64
86339 86346    3733.0
Name: new_cases, dtype: float64
86340 86347    3807.0
Name: new_cases, dtype: float64
86341 86348    3973.0
Name: new_cases, dtype: float64
86342 86349    4765.0
Name: new_cases, dtype: float64
86343 86350    4855.0
Name: new_cases, dtype: float64
86344 86351    4113.0
Name: new_cases, dtype: float64
86345 86352    4140.0
Name: new_cases, dtype: float64

86346 86353    3780.0
Name: new_cases, dtype: float64
86347 86354    4446.0
Name: new_cases, dtype: float64
86348 86355    4865.0
Name: new_cases, dtype: float64
86349 86356    6075.0
Name: new_cases, dtype: float64
86350 86357    6806.0
Name: new_cases, dtype: float64
86351 86358    6493.0
Name: new_cases, dtype: float64
86352 86359    6320.0
Name: new_cases, dtype: float64
86353 86360    6976.0
Name: new_cases, dtype: float64
86354 86361    6509.0
Name: new_cases, dtype: float64
86355 86362    7289.0
Name: new_cases, dtype: float64
86356 86363    7478.0
Name: new_cases, dtype: float64
86357 86364    7857.0
Name: new_cases, dtype: float64
86358 86365    8290.0
Name: new_cases, dtype: float64
86359 86366    9020.0
Name: new_cases, dtype: float64
86360 86367    6999.0
Name: new_cases, dtype: float64
86361 86368    6824.0
Name: new_cases, dtype: float64
86362 86369    7105.0
Name: new_cases, dtype: float64
86363 86370    7703.0
Name: new_cases, dtype: float64
86364 86371    8209.0
Name: new_cases, dtype: float64
86365 86372    7748.0
Name: new_cases, dtype: float64
86366 86373    7452.0
Name: new_cases, dtype: float64
86367 86374    6241.0
Name: new_cases, dtype: float64
86368 86375    5271.0
Name: new_cases, dtype: float64
86369 86376    5566.0
Name: new_cases, dtype: float64
86370 86377    6239.0
Name: new_cases, dtype: float64
86371 86378    5671.0
Name: new_cases, dtype: float64
86372 86379    6849.0
Name: new_cases, dtype: float64
86373 86380    5793.0
Name: new_cases, dtype: float64
86374 86381    5304.0
Name: new_cases, dtype: float64
86375 86382    4949.0
Name: new_cases, dtype: float64
86376 86383    5419.0
Name: new_cases, dtype: float64
86377 86384    5150.0
Name: new_cases, dtype: float64
86378 86385    5738.0
Name: new_cases, dtype: float64
86379 86386    6440.0
Name: new_cases, dtype: float64
86380 86387    5911.0
Name: new_cases, dtype: float64
86381 86388    5293.0
Name: new_cases, dtype: float64
86382 86389    4611.0
Name: new_cases, dtype: float64
86383 86390    4743.0
Name: new_cases, dtype: float64
86384 86391    5244.0
Name: new_cases, dtype: float64
86385 86392    5841.0
Name: new_cases, dtype: float64
86386 86393    5812.0
Name: new_cases, dtype: float64
86387 86394    5803.0
Name: new_cases, dtype: float64
86388 86395    5586.0
Name: new_cases, dtype: float64
86389 86396    5218.0
Name: new_cases, dtype: float64
86390 86397    6437.0
Name: new_cases, dtype: float64
86391 86398    6276.0
Name: new_cases, dtype: float64
86392 86399    6988.0
Name: new_cases, dtype: float64
86393 86400    6982.0
Name: new_cases, dtype: float64
86394 86401    6658.0
Name: new_cases, dtype: float64
86395 86402    6045.0
Name: new_cases, dtype: float64
86396 86403    6387.0
Name: new_cases, dtype: float64
86397 86404    7654.0
Name: new_cases, dtype: float64
86398 86405    7097.0
Name: new_cases, dtype: float64
86399 86406    8868.0
Name: new_cases, dtype: float64
86400 86407    9180.0
Name: new_cases, dtype: float64
86401 86408    9353.0
Name: new_cases, dtype: float64
86402 86409    9105.0
Name: new_cases, dtype: float64
86403 86410    8574.0
Name: new_cases, dtype: float64
86404 86411    11079.0
Name: new_cases, dtype: float64
86405 86412    11618.0
Name: new_cases, dtype: float64
86406 86413    13215.0
Name: new_cases, dtype: float64
86407 86414    12541.0
Name: new_cases, dtype: float64
86408 86415    12528.0
Name: new_cases, dtype: float64
86409 86416    10710.0
Name: new_cases, dtype: float64
86410 86417    10972.0
Name: new_cases, dtype: float64
86411 86418    12366.0
Name: new_cases, dtype: float64
86412 86419    11985.0
Name: new_cases, dtype: float64
86413 86420    13034.0
Name: new_cases, dtype: float64
86414 86421    15573.0
Name: new_cases, dtype: float64
86415 86422    15902.0
Name: new_cases, dtype: float64
86416 86423    17045.0
Name: new_cases, dtype: float64
86417 86424    14516.0
Name: new_cases, dtype: float64
86418 86425    16117.0
Name: new_cases, dtype: float64
86419 86426    17405.0
Name: new_cases, dtype: float64
86420 86427    17170.0
Name: new_cases, dtype: float64
86421 86428    16840.0
Name: new_cases, dtype: float64
86422 86429    17786.0
Name: new_cases, dtype: float64
86423 86430    17150.0
Name: new_cases, dtype: float64
86424 86431    15764.0
Name: new_cases, dtype: float64
86425 86432    17105.0
Name: new_cases, dtype: float64
86426 86433    19819.0
Name: new_cases, dtype: float64
86427 86434    20596.0
Name: new_cases, dtype: float64
86428 86435    20889.0
Name: new_cases, dtype: float64
86429 86436    19257.0
Name: new_cases, dtype: float64
86430 86437    18688.0
Name: new_cases, dtype: float64
86431 86438    17236.0
Name: new_cases, dtype: float64
86432 86439    19991.0
Name: new_cases, dtype: float64
86433 86440    20780.0
Name: new_cases, dtype: float64
86434 86441    21668.0
Name: new_cases, dtype: float64
86435 86442    21468.0
Name: new_cases, dtype: float64
86436 86443    20670.0
Name: new_cases, dtype: float64
86437 86444    20546.0
Name: new_cases, dtype: float64
86438 86445    19740.0
Name: new_cases, dtype: float64
86439 86446    19631.0
Name: new_cases, dtype: float64
86440 86447    22242.0
Name: new_cases, dtype: float64
86441 86448    22948.0
Name: new_cases, dtype: float64
86442 86449    23564.0
Name: new_cases, dtype: float64
86443 86450    22262.0
Name: new_cases, dtype: float64
86444 86451    19807.0
Name: new_cases, dtype: float64
86445 86452    17672.0
Name: new_cases, dtype: float64
86446 86453    20837.0
Name: new_cases, dtype: float64
86447 86454    22642.0
Name: new_cases, dtype: float64
86448 86455    24599.0
Name: new_cases, dtype: float64
86449 86456    22070.0
Name: new_cases, dtype: float64
86450 86457    22597.0
Name: new_cases, dtype: float64
86451 86458    20579.0
Name: new_cases, dtype: float64
86452 86459    19268.0
Name: new_cases, dtype: float64
86453 86460    20897.0
Name: new_cases, dtype: float64
86454 86461    18762.0
Name: new_cases, dtype: float64
86455 86462    20988.0
Name: new_cases, dtype: float64
86456 86463    19378.0
Name: new_cases, dtype: float64
86457 86464    19057.0
Name: new_cases, dtype: float64
86458 86465    20396.0
Name: new_cases, dtype: float64
86459 86466    17352.0
Name: new_cases, dtype: float64
86460 86467    18547.0
Name: new_cases, dtype: float64
86461 86468    19733.0
Name: new_cases, dtype: float64
86462 86469    19307.0
Name: new_cases, dtype: float64
86463 86470    21176.0
Name: new_cases, dtype: float64
86464 86471    19550.0
Name: new_cases, dtype: float64
86465 86472    19198.0
Name: new_cases, dtype: float64
86466 86473    16073.0
Name: new_cases, dtype: float64
86467 86474    15669.0
Name: new_cases, dtype: float64
86468 86475    19495.0
Name: new_cases, dtype: float64
86469 86476    18815.0
Name: new_cases, dtype: float64
86470 86477    17577.0
Name: new_cases, dtype: float64
86471 86478    15549.0
Name: new_cases, dtype: float64
86472 86479    14954.0
Name: new_cases, dtype: float64
86473 86480    14345.0
Name: new_cases, dtype: float64
86474 86481    15759.0
Name: new_cases, dtype: float64
86475 86482    14990.0
Name: new_cases, dtype: float64
86476 86483    13754.0
Name: new_cases, dtype: float64
86477 86484    14554.0
Name: new_cases, dtype: float64
86478 86485    13899.0
Name: new_cases, dtype: float64
86479 86486    13104.0
Name: new_cases, dtype: float64
86480 86487    10959.0
Name: new_cases, dtype: float64
86481 86488    11332.0
Name: new_cases, dtype: float64
86482 86489    12434.0
Name: new_cases, dtype: float64
86483 86490    12735.0
Name: new_cases, dtype: float64
86484 86491    11889.0
Name: new_cases, dtype: float64
86485 86492    10915.0
Name: new_cases, dtype: float64
86486 86493    9066.0
Name: new_cases, dtype: float64
86487 86494    8075.0
Name: new_cases, dtype: float64
86488 86495    8817.0
Name: new_cases, dtype: float64
86489 86496    9380.0
Name: new_cases, dtype: float64
86490 86497    9890.0
Name: new_cases, dtype: float64
86491 86498    9751.0
Name: new_cases, dtype: float64
86492 86499    8743.0
Name: new_cases, dtype: float64
86493 86500    7373.0
Name: new_cases, dtype: float64
86494 86501    6709.0
Name: new_cases, dtype: float64
86495 86502    7276.0
Name: new_cases, dtype: float64
86496 86503    7950.0
Name: new_cases, dtype: float64
86497 86504    8084.0
Name: new_cases, dtype: float64
86498 86505    7420.0
Name: new_cases, dtype: float64
86499 86506    7509.0
Name: new_cases, dtype: float64
86500 86507    6145.0
Name: new_cases, dtype: float64
86501 86508    5434.0
Name: new_cases, dtype: float64
86502 86509    5745.0
Name: new_cases, dtype: float64
86503 86510    5516.0
Name: new_cases, dtype: float64
86504 86511    6210.0
Name: new_cases, dtype: float64
86505 86512    6630.0
Name: new_cases, dtype: float64
86506 86513    5828.0
Name: new_cases, dtype: float64
86507 86514    5666.0
Name: new_cases, dtype: float64
86508 86515    4782.0
Name: new_cases, dtype: float64
86509 86516    5726.0
Name: new_cases, dtype: float64
86510 86517    6148.0
Name: new_cases, dtype: float64
86511 86518    6377.0
Name: new_cases, dtype: float64
86512 86519    6060.0
Name: new_cases, dtype: float64

86513 86520    5854.0
Name: new_cases, dtype: float64
86514 86521    4979.0
Name: new_cases, dtype: float64
86515 86522    4626.0
Name: new_cases, dtype: float64
86516 86523    5071.0
Name: new_cases, dtype: float64
86517 86524    5291.0
Name: new_cases, dtype: float64
86518 86525    5713.0
Name: new_cases, dtype: float64
86519 86526    4922.0
Name: new_cases, dtype: float64
86520 86527    4701.0
Name: new_cases, dtype: float64
86521 86528    4343.0
Name: new_cases, dtype: float64
86522 86529    4543.0
Name: new_cases, dtype: float64
86523 86530    6321.0
Name: new_cases, dtype: float64
86524 86531    5325.0
Name: new_cases, dtype: float64
86525 86532    6323.0
Name: new_cases, dtype: float64
86526 86533    6517.0
Name: new_cases, dtype: float64
86527 86534    5809.0
Name: new_cases, dtype: float64
86528 86535    5162.0
Name: new_cases, dtype: float64
86529 86536    5143.0
Name: new_cases, dtype: float64
86530 86537    5413.0
Name: new_cases, dtype: float64
86531 86538    6288.0
Name: new_cases, dtype: float64
86532 86539    6380.0
Name: new_cases, dtype: float64
86533 86540    6355.0
Name: new_cases, dtype: float64
86534 86541    5859.0
Name: new_cases, dtype: float64
86535 86542    4854.0
Name: new_cases, dtype: float64
86536 86543    4885.0
Name: new_cases, dtype: float64
86537 86544    5594.0
Name: new_cases, dtype: float64
86538 86545    5755.0
Name: new_cases, dtype: float64
86539 86546    6144.0
Name: new_cases, dtype: float64
86540 86547    5501.0
Name: new_cases, dtype: float64
86541 86548    5097.0
Name: new_cases, dtype: float64
86542 86549    4239.0
Name: new_cases, dtype: float64
86543 86550    4087.0
Name: new_cases, dtype: float64
86544 86551    4879.0
Name: new_cases, dtype: float64
86545 86552    5439.0
Name: new_cases, dtype: float64
86546 86553    5806.0
Name: new_cases, dtype: float64
86547 86554    5551.0
Name: new_cases, dtype: float64
86548 86555    4896.0
Name: new_cases, dtype: float64
86549 86556    4298.0
Name: new_cases, dtype: float64
86550 86557    4262.0
Name: new_cases, dtype: float64
86551 86558    4965.0
Name: new_cases, dtype: float64
86552 86559    5020.0
Name: new_cases, dtype: float64
86553 86560    5446.0
Name: new_cases, dtype: float64
86554 86561    5058.0
Name: new_cases, dtype: float64
86555 86562    4626.0
Name: new_cases, dtype: float64
86556 86563    3490.0
Name: new_cases, dtype: float64
86557 86564    3504.0
Name: new_cases, dtype: float64
86558 86565    4097.0
Name: new_cases, dtype: float64
86559 86566    3900.0
Name: new_cases, dtype: float64
86560 86567    4262.0
Name: new_cases, dtype: float64
86561 86568    4362.0
Name: new_cases, dtype: float64
86562 86569    4083.0
Name: new_cases, dtype: float64
86563 86570    3108.0
Name: new_cases, dtype: float64
86564 86571    2589.0
Name: new_cases, dtype: float64
86565 86572    3140.0
Name: new_cases, dtype: float64
86566 86573    3519.0
Name: new_cases, dtype: float64
86567 86574    3510.0
Name: new_cases, dtype: float64
86568 86575    3528.0
Name: new_cases, dtype: float64
86569 86576    3160.0
Name: new_cases, dtype: float64
86570 86577    2778.0
Name: new_cases, dtype: float64
86571 86578    2757.0
Name: new_cases, dtype: float64
86572 86579    2897.0
Name: new_cases, dtype: float64
86573 86580    3683.0
Name: new_cases, dtype: float64
86574 86581    3997.0
Name: new_cases, dtype: float64
86575 86582    3573.0
Name: new_cases, dtype: float64
86576 86583    3386.0
Name: new_cases, dtype: float64
86577 86584    2882.0
Name: new_cases, dtype: float64
86578 86585    2690.0
Name: new_cases, dtype: float64
86579 86586    2842.0
Name: new_cases, dtype: float64
86580 86587    3270.0
Name: new_cases, dtype: float64
86581 86588    3543.0
Name: new_cases, dtype: float64
86582 86589    3381.0
Name: new_cases, dtype: float64
86583 86590    3251.0
Name: new_cases, dtype: float64
86584 85910    2.0
Name: new_cases, dtype: float64
86585 85911    4.0
Name: new_cases, dtype: float64
86586 85912    0.0
Name: new_cases, dtype: float64
86587 85913    0.0
Name: new_cases, dtype: float64
86588 85914    7.0
Name: new_cases, dtype: float64
86589 85915    14.0
Name: new_cases, dtype: float64
86590 85916    5.0
Name: new_cases, dtype: float64
90417 90424    1.0
Name: new_cases, dtype: float64
90418 90425    0.0
Name: new_cases, dtype: float64
90419 90426    1.0
Name: new_cases, dtype: float64
90420 90427    0.0
Name: new_cases, dtype: float64
90421 90428    0.0
Name: new_cases, dtype: float64
90422 90429    1.0
Name: new_cases, dtype: float64
90423 90430    4.0
Name: new_cases, dtype: float64
90424 90431    14.0
Name: new_cases, dtype: float64
90425 90432    15.0
Name: new_cases, dtype: float64
90426 90433    12.0
Name: new_cases, dtype: float64
90427 90434    29.0
Name: new_cases, dtype: float64
90428 90435    11.0
Name: new_cases, dtype: float64
90429 90436    25.0
Name: new_cases, dtype: float64
90430 90437    46.0
Name: new_cases, dtype: float64
90431 90438    39.0
Name: new_cases, dtype: float64
90432 90439    48.0
Name: new_cases, dtype: float64
90433 90440    65.0
Name: new_cases, dtype: float64
90434 90441    51.0
Name: new_cases, dtype: float64
90435 90442    38.0
Name: new_cases, dtype: float64
90436 90443    70.0
Name: new_cases, dtype: float64
90437 90444    110.0
Name: new_cases, dtype: float64
90438 90445    132.0
Name: new_cases, dtype: float64
90439 90446    131.0
Name: new_cases, dtype: float64
90440 90447    145.0
Name: new_cases, dtype: float64
90441 90448    101.0
Name: new_cases, dtype: float64
90442 90449    121.0
Name: new_cases, dtype: float64
90443 90450    163.0
Name: new_cases, dtype: float64
90444 90451    132.0
Name: new_cases, dtype: float64
90445 90452    178.0
Name: new_cases, dtype: float64
90446 90453    202.0
Name: new_cases, dtype: float64
90447 90454    253.0
Name: new_cases, dtype: float64
90448 90455    296.0
Name: new_cases, dtype: float64
90449 90456    346.0
Name: new_cases, dtype: float64
90450 90457    396.0
Name: new_cases, dtype: float64
90451 90458    260.0
Name: new_cases, dtype: float64
90452 90459    403.0
Name: new_cases, dtype: float64
90453 90460    375.0
Name: new_cases, dtype: float64
90454 90461    442.0
Name: new_cases, dtype: float64
90455 90462    353.0
Name: new_cases, dtype: float64
90456 90463    385.0
Name: new_cases, dtype: float64
90457 90464    448.0
Name: new_cases, dtype: float64
90458 90465    450.0
Name: new_cases, dtype: float64
90459 90466    578.0
Name: new_cases, dtype: float64
90460 90467    622.0
Name: new_cases, dtype: float64
90461 90468    764.0
Name: new_cases, dtype: float64
90462 90469    511.0
Name: new_cases, dtype: float64
90463 90470    729.0
Name: new_cases, dtype: float64
90464 90471    1043.0
Name: new_cases, dtype: float64
90465 90472    1089.0
Name: new_cases, dtype: float64
90466 90473    1239.0
Name: new_cases, dtype: float64
90467 90474    970.0
Name: new_cases, dtype: float64
90468 90475    835.0
Name: new_cases, dtype: float64
90469 90476    852.0
Name: new_cases, dtype: float64
90470 90477    1223.0
Name: new_cases, dtype: float64
90471 90478    1047.0
Name: new_cases, dtype: float64
90472 90479    1425.0
Name: new_cases, dtype: float64
90473 90480    1515.0
Name: new_cases, dtype: float64
90474 90481    1349.0
Name: new_cases, dtype: float64
90475 90482    1383.0
Name: new_cases, dtype: float64
90476 90483    1434.0
Name: new_cases, dtype: float64
90477 90484    1120.0
Name: new_cases, dtype: float64
90478 90485    1609.0
Name: new_cases, dtype: float64
90479 90486    1982.0
Name: new_cases, dtype: float64
90480 90487    1906.0
Name: new_cases, dtype: float64
90481 90488    1938.0
Name: new_cases, dtype: float64
90482 90489    1562.0
Name: new_cases, dtype: float64
90483 90490    1305.0
Name: new_cases, dtype: float64
90484 90491    1997.0
Name: new_cases, dtype: float64
90485 90492    1862.0
Name: new_cases, dtype: float64
90486 90493    2409.0
Name: new_cases, dtype: float64
90487 90494    2437.0
Name: new_cases, dtype: float64
90488 90495    2112.0
Name: new_cases, dtype: float64
90489 90496    2075.0
Name: new_cases, dtype: float64
90490 90497    2414.0
Name: new_cases, dtype: float64
90491 90498    2713.0
Name: new_cases, dtype: float64
90492 90499    2248.0
Name: new_cases, dtype: float64

90493 90500    2973.0
Name: new_cases, dtype: float64
90494 90501    2960.0
Name: new_cases, dtype: float64
90495 90502    3329.0
Name: new_cases, dtype: float64
90496 90503    2764.0
Name: new_cases, dtype: float64
90497 90504    2485.0
Name: new_cases, dtype: float64
90498 90505    3455.0
Name: new_cases, dtype: float64
90499 90506    3463.0
Name: new_cases, dtype: float64
90500 90507    3377.0
Name: new_cases, dtype: float64
90501 90508    3227.0
Name: new_cases, dtype: float64
90502 90509    2885.0
Name: new_cases, dtype: float64
90503 90510    3152.0
Name: new_cases, dtype: float64
90504 90511    2771.0
Name: new_cases, dtype: float64
90505 90512    3891.0
Name: new_cases, dtype: float64
90506 90513    3912.0
Name: new_cases, dtype: float64
90507 90514    4442.0
Name: new_cases, dtype: float64
90508 90515    4346.0
Name: new_cases, dtype: float64
90509 90516    3593.0
Name: new_cases, dtype: float64
90510 90517    3484.0
Name: new_cases, dtype: float64
90511 90518    2999.0
Name: new_cases, dtype: float64
90512 90519    4199.0
Name: new_cases, dtype: float64
90513 90520    4883.0
Name: new_cases, dtype: float64
90514 90521    4790.0
Name: new_cases, dtype: float64
90515 90522    5222.0
Name: new_cases, dtype: float64
90516 90523    3494.0
Name: new_cases, dtype: float64
90517 90524    4147.0
Name: new_cases, dtype: float64
90518 90525    3427.0
Name: new_cases, dtype: float64
90519 90526    4599.0
Name: new_cases, dtype: float64
90520 90527    4930.0
Name: new_cases, dtype: float64
90521 90528    5662.0
Name: new_cases, dtype: float64
90522 90529    5030.0
Name: new_cases, dtype: float64
90523 90530    4717.0
Name: new_cases, dtype: float64
90524 90531    5343.0
Name: new_cases, dtype: float64
90525 90532    4577.0
Name: new_cases, dtype: float64
90526 90533    6288.0
Name: new_cases, dtype: float64
90527 90534    5437.0
Name: new_cases, dtype: float64
90528 90535    6104.0
Name: new_cases, dtype: float64
90529 90536    5441.0
Name: new_cases, dtype: float64
90530 90537    4410.0
Name: new_cases, dtype: float64
90531 90538    4050.0
Name: new_cases, dtype: float64
90532 90539    3805.0
Name: new_cases, dtype: float64
90533 90540    5432.0
Name: new_cases, dtype: float64
90534 90541    5681.0
Name: new_cases, dtype: float64
90535 90542    6741.0
Name: new_cases, dtype: float64
90536 90543    6740.0
Name: new_cases, dtype: float64
90537 90544    6914.0
Name: new_cases, dtype: float64
90538 90545    4683.0
Name: new_cases, dtype: float64
90539 90546    4902.0
Name: new_cases, dtype: float64
90540 90547    6258.0
Name: new_cases, dtype: float64
90541 90548    6995.0
Name: new_cases, dtype: float64
90542 90549    7280.0
Name: new_cases, dtype: float64
90543 90550    6891.0
Name: new_cases, dtype: float64
90544 90551    6094.0
Name: new_cases, dtype: float64
90545 90552    4482.0
Name: new_cases, dtype: float64
90546 90553    4685.0
Name: new_cases, dtype: float64
90547 90554    7051.0
Name: new_cases, dtype: float64
90548 90555    6149.0
Name: new_cases, dtype: float64
90549 90556    6406.0
Name: new_cases, dtype: float64
90550 90557    7257.0
Name: new_cases, dtype: float64
90551 90558    7615.0
Name: new_cases, dtype: float64
90552 90559    5311.0
Name: new_cases, dtype: float64
90553 90560    5172.0
Name: new_cases, dtype: float64
90554 90561    6859.0
Name: new_cases, dtype: float64
90555 90562    6019.0
Name: new_cases, dtype: float64
90556 90563    8438.0
Name: new_cases, dtype: float64
90557 90564    7573.0
Name: new_cases, dtype: float64
90558 90565    6751.0
Name: new_cases, dtype: float64
90559 90566    5480.0
Name: new_cases, dtype: float64
90560 90567    4973.0
Name: new_cases, dtype: float64
90561 90568    7208.0
Name: new_cases, dtype: float64
90562 90569    5752.0
Name: new_cases, dtype: float64
90563 90570    7730.0
Name: new_cases, dtype: float64
90564 90571    8458.0
Name: new_cases, dtype: float64
90565 90572    9556.0
Name: new_cases, dtype: float64
90566 90573    4853.0
Name: new_cases, dtype: float64
90567 90574    4767.0
Name: new_cases, dtype: float64
90568 90575    6148.0
Name: new_cases, dtype: float64
90569 90576    6139.0
Name: new_cases, dtype: float64
90570 90577    6590.0
Name: new_cases, dtype: float64
90571 90578    6717.0
Name: new_cases, dtype: float64
90572 90579    6495.0
Name: new_cases, dtype: float64
90573 90580    4376.0
Name: new_cases, dtype: float64
90574 90581    5558.0
Name: new_cases, dtype: float64
90575 90582    6686.0
Name: new_cases, dtype: float64
90576 90583    5858.0
Name: new_cases, dtype: float64
90577 90584    7371.0
Name: new_cases, dtype: float64
90578 90585    5618.0
Name: new_cases, dtype: float64
90579 90586    6345.0
Name: new_cases, dtype: float64
90580 90587    4448.0
Name: new_cases, dtype: float64
90581 90588    3571.0
Name: new_cases, dtype: float64
90582 90589    5506.0
Name: new_cases, dtype: float64
90583 90590    5792.0
Name: new_cases, dtype: float64
90584 90591    6775.0
Name: new_cases, dtype: float64
90585 90592    5928.0
Name: new_cases, dtype: float64
90586 90593    6482.0
Name: new_cases, dtype: float64
90587 90594    3948.0
Name: new_cases, dtype: float64
90588 90595    3541.0
Name: new_cases, dtype: float64
90589 90596    4916.0
Name: new_cases, dtype: float64
90590 90597    5267.0
Name: new_cases, dtype: float64
90591 90598    6026.0
Name: new_cases, dtype: float64
90592 90599    5824.0
Name: new_cases, dtype: float64
90593 90600    5974.0
Name: new_cases, dtype: float64
90594 90601    4129.0
Name: new_cases, dtype: float64
90595 90602    3719.0
Name: new_cases, dtype: float64
90596 90603    6476.0
Name: new_cases, dtype: float64
90597 90604    4921.0
Name: new_cases, dtype: float64
90598 90605    5937.0
Name: new_cases, dtype: float64
90599 90606    6196.0
Name: new_cases, dtype: float64
90600 90607    6319.0
Name: new_cases, dtype: float64
90601 90608    4614.0
Name: new_cases, dtype: float64
90602 90609    3486.0
Name: new_cases, dtype: float64
90603 90610    5351.0
Name: new_cases, dtype: float64
90604 90611    4461.0
Name: new_cases, dtype: float64
90605 90612    5043.0
Name: new_cases, dtype: float64
90606 90613    5935.0
Name: new_cases, dtype: float64
90607 90614    5674.0
Name: new_cases, dtype: float64
90608 90615    4408.0
Name: new_cases, dtype: float64
90609 90616    3335.0
Name: new_cases, dtype: float64
90610 90617    4771.0
Name: new_cases, dtype: float64
90611 90618    4444.0
Name: new_cases, dtype: float64
90612 90619    3182.0
Name: new_cases, dtype: float64
90613 90620    4841.0
Name: new_cases, dtype: float64
90614 90621    5167.0
Name: new_cases, dtype: float64
90615 90622    3542.0
Name: new_cases, dtype: float64
90616 90623    2917.0
Name: new_cases, dtype: float64
90617 90624    4683.0
Name: new_cases, dtype: float64
90618 90625    4786.0
Name: new_cases, dtype: float64
90619 90626    5408.0
Name: new_cases, dtype: float64
90620 90627    5401.0
Name: new_cases, dtype: float64
90621 90628    5573.0
Name: new_cases, dtype: float64
90622 90629    3886.0
Name: new_cases, dtype: float64
90623 90630    3400.0
Name: new_cases, dtype: float64
90624 90631    4446.0
Name: new_cases, dtype: float64
90625 90632    5053.0
Name: new_cases, dtype: float64
90626 90633    5099.0
Name: new_cases, dtype: float64
90627 90634    4775.0
Name: new_cases, dtype: float64
90628 90635    4863.0
Name: new_cases, dtype: float64
90629 90636    3712.0
Name: new_cases, dtype: float64
90630 90637    28115.0
Name: new_cases, dtype: float64
90631 90638    4828.0
Name: new_cases, dtype: float64
90632 90639    4580.0
Name: new_cases, dtype: float64
90633 90640    5300.0
Name: new_cases, dtype: float64
90634 90641    5532.0
Name: new_cases, dtype: float64
90635 90642    4308.0
Name: new_cases, dtype: float64
90636 90643    3175.0
Name: new_cases, dtype: float64
90637 90644    3542.0
Name: new_cases, dtype: float64
90638 90645    4295.0
Name: new_cases, dtype: float64
90639 90646    4056.0
Name: new_cases, dtype: float64
90640 90647    5514.0
Name: new_cases, dtype: float64
90641 90648    6751.0
Name: new_cases, dtype: float64
90642 90649    5447.0
Name: new_cases, dtype: float64
90643 90650    4119.0
Name: new_cases, dtype: float64
90644 90651    3699.0
Name: new_cases, dtype: float64
90645 90652    5788.0
Name: new_cases, dtype: float64
90646 90653    6845.0
Name: new_cases, dtype: float64

90647 90654    6612.0
Name: new_cases, dtype: float64
90648 90655    6604.0
Name: new_cases, dtype: float64
90649 90656    6025.0
Name: new_cases, dtype: float64
90650 90657    4360.0
Name: new_cases, dtype: float64
90651 90658    4166.0
Name: new_cases, dtype: float64
90652 90659    5942.0
Name: new_cases, dtype: float64
90653 90660    5595.0
Name: new_cases, dtype: float64
90654 90661    5948.0
Name: new_cases, dtype: float64
90655 90662    6000.0
Name: new_cases, dtype: float64
90656 90663    6151.0
Name: new_cases, dtype: float64
90657 90664    4430.0
Name: new_cases, dtype: float64
90658 90665    3763.0
Name: new_cases, dtype: float64
90659 90666    5250.0
Name: new_cases, dtype: float64
90660 90667    5225.0
Name: new_cases, dtype: float64
90661 90668    5567.0
Name: new_cases, dtype: float64
90662 90669    5931.0
Name: new_cases, dtype: float64
90663 90670    6810.0
Name: new_cases, dtype: float64
90664 90671    5887.0
Name: new_cases, dtype: float64
90665 90672    4960.0
Name: new_cases, dtype: float64
90666 90673    5746.0
Name: new_cases, dtype: float64
90667 90674    7646.0
Name: new_cases, dtype: float64
90668 90675    5658.0
Name: new_cases, dtype: float64
90669 90676    5558.0
Name: new_cases, dtype: float64
90670 90677    5860.0
Name: new_cases, dtype: float64
90671 90678    3269.0
Name: new_cases, dtype: float64
90672 90679    2874.0
Name: new_cases, dtype: float64
90673 90680    1757.0
Name: new_cases, dtype: float64
90674 90681    3918.0
Name: new_cases, dtype: float64
90675 90682    4472.0
Name: new_cases, dtype: float64
90676 90683    6426.0
Name: new_cases, dtype: float64
90677 90684    6719.0
Name: new_cases, dtype: float64
90678 90685    9187.0
Name: new_cases, dtype: float64
90679 90686    7483.0
Name: new_cases, dtype: float64
90680 90687    10794.0
Name: new_cases, dtype: float64
90681 90688    10335.0
Name: new_cases, dtype: float64
90682 90689    8107.0
Name: new_cases, dtype: float64
90683 90690    12081.0
Name: new_cases, dtype: float64
90684 90691    10728.0
Name: new_cases, dtype: float64
90685 90692    5668.0
Name: new_cases, dtype: float64
90686 90693    6472.0
Name: new_cases, dtype: float64
90687 90694    8819.0
Name: new_cases, dtype: float64
90688 90695    11251.0
Name: new_cases, dtype: float64
90689 90696    11030.0
Name: new_cases, dtype: float64
90690 90697    12127.0
Name: new_cases, dtype: float64
90691 90698    11625.0
Name: new_cases, dtype: float64
90692 90699    7455.0
Name: new_cases, dtype: float64
90693 90700    6399.0
Name: new_cases, dtype: float64
90694 90701    11006.0
Name: new_cases, dtype: float64
90695 90702    11974.0
Name: new_cases, dtype: float64
90696 90703    11897.0
Name: new_cases, dtype: float64
90697 90704    12253.0
Name: new_cases, dtype: float64
90698 90705    12057.0
Name: new_cases, dtype: float64
90699 90706    8608.0
Name: new_cases, dtype: float64
90700 90707    5930.0
Name: new_cases, dtype: float64
90701 90708    11228.0
Name: new_cases, dtype: float64
90702 90709    10297.0
Name: new_cases, dtype: float64
90703 90710    11799.0
Name: new_cases, dtype: float64
90704 90711    12248.0
Name: new_cases, dtype: float64
90705 90712    12129.0
Name: new_cases, dtype: float64
90706 90713    6870.0
Name: new_cases, dtype: float64
90707 90714    5370.0
Name: new_cases, dtype: float64
90708 90715    12511.0
Name: new_cases, dtype: float64
90709 90716    11653.0
Name: new_cases, dtype: float64
90710 90717    12485.0
Name: new_cases, dtype: float64
90711 90718    9679.0
Name: new_cases, dtype: float64
90712 90719    4974.0
Name: new_cases, dtype: float64
90713 90720    6217.0
Name: new_cases, dtype: float64
90714 90721    5996.0
Name: new_cases, dtype: float64
90715 90722    12099.0
Name: new_cases, dtype: float64
90716 90723    12406.0
Name: new_cases, dtype: float64
90717 90724    12159.0
Name: new_cases, dtype: float64
90718 90725    11091.0
Name: new_cases, dtype: float64
90719 90726    6359.0
Name: new_cases, dtype: float64
90720 90727    5211.0
Name: new_cases, dtype: float64
90721 90728    6464.0
Name: new_cases, dtype: float64
90722 90729    11271.0
Name: new_cases, dtype: float64
90723 90730    13345.0
Name: new_cases, dtype: float64
90724 90731    13734.0
Name: new_cases, dtype: float64
90725 90732    14362.0
Name: new_cases, dtype: float64
90726 90733    16105.0
Name: new_cases, dtype: float64
90727 90734    10003.0
Name: new_cases, dtype: float64
90728 90735    7594.0
Name: new_cases, dtype: float64
90729 90736    14395.0
Name: new_cases, dtype: float64
90730 90737    15873.0
Name: new_cases, dtype: float64
90731 90738    16468.0
Name: new_cases, dtype: float64
90732 90739    21366.0
Name: new_cases, dtype: float64
90733 90740    20523.0
Name: new_cases, dtype: float64
90734 90741    11170.0
Name: new_cases, dtype: float64
90735 90742    8074.0
Name: new_cases, dtype: float64
90736 90743    18894.0
Name: new_cases, dtype: float64
90737 90744    20548.0
Name: new_cases, dtype: float64
90738 90745    22339.0
Name: new_cases, dtype: float64
90739 90746    21007.0
Name: new_cases, dtype: float64
90740 90747    20057.0
Name: new_cases, dtype: float64
90741 90748    10872.0
Name: new_cases, dtype: float64
90742 90749    8521.0
Name: new_cases, dtype: float64
90743 90750    17165.0
Name: new_cases, dtype: float64
90744 90751    17944.0
Name: new_cases, dtype: float64
90745 90752    18670.0
Name: new_cases, dtype: float64
90746 90753    16374.0
Name: new_cases, dtype: float64
90747 90754    15337.0
Name: new_cases, dtype: float64
90748 90755    7030.0
Name: new_cases, dtype: float64
90749 90756    5448.0
Name: new_cases, dtype: float64
90750 90757    4384.0
Name: new_cases, dtype: float64
90751 90758    12153.0
Name: new_cases, dtype: float64
90752 90759    0.0
Name: new_cases, dtype: float64
90753 90760    26626.0
Name: new_cases, dtype: float64
90754 90761    13209.0
Name: new_cases, dtype: float64
90755 90762    6065.0
Name: new_cases, dtype: float64
90756 90763    3868.0
Name: new_cases, dtype: float64
90757 90764    10738.0
Name: new_cases, dtype: float64
90758 90765    11138.0
Name: new_cases, dtype: float64
90759 90766    10677.0
Name: new_cases, dtype: float64
90760 90767    10388.0
Name: new_cases, dtype: float64
90761 90768    9741.0
Name: new_cases, dtype: float64
90762 90769    4099.0
Name: new_cases, dtype: float64
90763 90770    3098.0
Name: new_cases, dtype: float64
90764 90771    8683.0
Name: new_cases, dtype: float64
90765 90772    8988.0
Name: new_cases, dtype: float64
90766 90773    9099.0
Name: new_cases, dtype: float64
90767 90774    7829.0
Name: new_cases, dtype: float64
90768 90775    7785.0
Name: new_cases, dtype: float64
90769 90776    3104.0
Name: new_cases, dtype: float64
90770 90777    2252.0
Name: new_cases, dtype: float64
90771 90778    8634.0
Name: new_cases, dtype: float64
90772 90779    8642.0
Name: new_cases, dtype: float64
90773 90780    8462.0
Name: new_cases, dtype: float64
90774 90781    7512.0
Name: new_cases, dtype: float64
90775 90782    7246.0
Name: new_cases, dtype: float64
90776 90783    2810.0
Name: new_cases, dtype: float64
90777 90784    2343.0
Name: new_cases, dtype: float64
90778 90785    7913.0
Name: new_cases, dtype: float64
90779 90786    7793.0
Name: new_cases, dtype: float64
90780 90787    7521.0
Name: new_cases, dtype: float64
90781 90788    6797.0
Name: new_cases, dtype: float64
90782 90789    6561.0
Name: new_cases, dtype: float64
90783 90790    2734.0
Name: new_cases, dtype: float64
90784 90791    1877.0
Name: new_cases, dtype: float64
90785 90792    7407.0
Name: new_cases, dtype: float64
90786 90793    6602.0
Name: new_cases, dtype: float64
90787 90794    6469.0
Name: new_cases, dtype: float64
90788 90795    6816.0
Name: new_cases, dtype: float64
90789 90796    6104.0
Name: new_cases, dtype: float64
90790 90797    2415.0
Name: new_cases, dtype: float64
90791 90798    1439.0
Name: new_cases, dtype: float64
90792 90799    1278.0
Name: new_cases, dtype: float64
90793 90800    6455.0
Name: new_cases, dtype: float64
90794 90801    6726.0
Name: new_cases, dtype: float64
90795 90802    5722.0
Name: new_cases, dtype: float64
90796 90803    5729.0
Name: new_cases, dtype: float64
90797 90804    2133.0
Name: new_cases, dtype: float64
90798 90805    1388.0
Name: new_cases, dtype: float64
90799 90806    5881.0
Name: new_cases, dtype: float64
90800 90807    5714.0
Name: new_cases, dtype: float64
90801 90808    5787.0
Name: new_cases, dtype: float64
90802 90809    5303.0
Name: new_cases, dtype: float64
90803 90810    5059.0
Name: new_cases, dtype: float64
90804 90811    1646.0
Name: new_cases, dtype: float64
90805 90812    1293.0
Name: new_cases, dtype: float64
90806 90813    5067.0
Name: new_cases, dtype: float64
90807 90814    5977.0
Name: new_cases, dtype: float64
90808 90815    5381.0
Name: new_cases, dtype: float64
90809 90816    3089.0
Name: new_cases, dtype: float64
90810 90817    1838.0
Name: new_cases, dtype: float64
90811 90818    1263.0
Name: new_cases, dtype: float64
90812 90819    1247.0
Name: new_cases, dtype: float64

90813 90820    4804.0
Name: new_cases, dtype: float64
90814 90821    5370.0
Name: new_cases, dtype: float64
90815 90822    5140.0
Name: new_cases, dtype: float64
90816 90823    5045.0
Name: new_cases, dtype: float64
90817 90824    6356.0
Name: new_cases, dtype: float64
90818 90825    1793.0
Name: new_cases, dtype: float64
90819 90826    1627.0
Name: new_cases, dtype: float64
90820 90827    4512.0
Name: new_cases, dtype: float64
90821 90828    4894.0
Name: new_cases, dtype: float64
90822 90829    4189.0
Name: new_cases, dtype: float64
90823 90830    4504.0
Name: new_cases, dtype: float64
90824 90831    4157.0
Name: new_cases, dtype: float64
90825 90832    1506.0
Name: new_cases, dtype: float64
90826 90833    1308.0
Name: new_cases, dtype: float64
90827 90834    4262.0
Name: new_cases, dtype: float64
90828 90835    4639.0
Name: new_cases, dtype: float64
90829 90836    3708.0
Name: new_cases, dtype: float64
90830 90837    3911.0
Name: new_cases, dtype: float64
90831 90838    3308.0
Name: new_cases, dtype: float64
90832 90839    1653.0
Name: new_cases, dtype: float64
90833 90840    1143.0
Name: new_cases, dtype: float64
90834 90841    3592.0
Name: new_cases, dtype: float64
90835 90842    3818.0
Name: new_cases, dtype: float64
90836 90843    3990.0
Name: new_cases, dtype: float64
90837 90844    3821.0
Name: new_cases, dtype: float64
90838 90845    3025.0
Name: new_cases, dtype: float64
90839 90846    1093.0
Name: new_cases, dtype: float64
90840 90847    1027.0
Name: new_cases, dtype: float64
90841 90848    3064.0
Name: new_cases, dtype: float64
90842 90849    3021.0
Name: new_cases, dtype: float64
90843 90850    2846.0
Name: new_cases, dtype: float64
90844 90851    3043.0
Name: new_cases, dtype: float64
90845 90852    2743.0
Name: new_cases, dtype: float64
90846 90853    1175.0
Name: new_cases, dtype: float64
90847 90854    704.0
Name: new_cases, dtype: float64
90848 90855    1897.0
Name: new_cases, dtype: float64
90849 90856    3090.0
Name: new_cases, dtype: float64
90850 90857    3632.0
Name: new_cases, dtype: float64
90851 90858    2880.0
Name: new_cases, dtype: float64
90852 90859    2695.0
Name: new_cases, dtype: float64
90853 90860    1233.0
Name: new_cases, dtype: float64
90854 90861    822.0
Name: new_cases, dtype: float64
90855 90862    2767.0
Name: new_cases, dtype: float64
90856 90863    2000.0
Name: new_cases, dtype: float64
90857 90864    2628.0
Name: new_cases, dtype: float64
90858 90865    2604.0
Name: new_cases, dtype: float64
90859 90866    2586.0
Name: new_cases, dtype: float64
90860 90867    1274.0
Name: new_cases, dtype: float64
90861 90868    703.0
Name: new_cases, dtype: float64
90862 90869    2483.0
Name: new_cases, dtype: float64
90863 90870    2932.0
Name: new_cases, dtype: float64
90864 90871    3050.0
Name: new_cases, dtype: float64
90865 90872    3006.0
Name: new_cases, dtype: float64
90866 90873    2725.0
Name: new_cases, dtype: float64
90867 90874    1307.0
Name: new_cases, dtype: float64
90868 90875    932.0
Name: new_cases, dtype: float64
90869 90876    6917.0
Name: new_cases, dtype: float64
90870 90877    3269.0
Name: new_cases, dtype: float64
90871 90878    2894.0
Name: new_cases, dtype: float64
90872 90879    2809.0
Name: new_cases, dtype: float64
90873 90880    2071.0
Name: new_cases, dtype: float64
90874 90881    1979.0
Name: new_cases, dtype: float64
90875 90882    881.0
Name: new_cases, dtype: float64
90876 90883    3449.0
Name: new_cases, dtype: float64
90877 90884    3855.0
Name: new_cases, dtype: float64
90878 90885    3672.0
Name: new_cases, dtype: float64
90879 90886    3282.0
Name: new_cases, dtype: float64
90880 90887    3649.0
Name: new_cases, dtype: float64
90881 90888    1707.0
Name: new_cases, dtype: float64
90882 90889    1175.0
Name: new_cases, dtype: float64
90883 90890    4250.0
Name: new_cases, dtype: float64
90884 90891    3789.0
Name: new_cases, dtype: float64
90885 90892    4253.0
Name: new_cases, dtype: float64
90886 90893    4098.0
Name: new_cases, dtype: float64
90887 90894    0.0
Name: new_cases, dtype: float64
90888 90895    5542.0
Name: new_cases, dtype: float64
90889 90896    1268.0
Name: new_cases, dtype: float64
90890 90897    4233.0
Name: new_cases, dtype: float64
90891 90898    4963.0
Name: new_cases, dtype: float64
90892 90899    5340.0
Name: new_cases, dtype: float64
90893 90900    5270.0
Name: new_cases, dtype: float64
90894 90901    5051.0
Name: new_cases, dtype: float64
90895 90902    2384.0
Name: new_cases, dtype: float64
90896 90903    1661.0
Name: new_cases, dtype: float64
90897 90904    5711.0
Name: new_cases, dtype: float64
90898 90905    6105.0
Name: new_cases, dtype: float64
90899 90906    6081.0
Name: new_cases, dtype: float64
90900 90907    5842.0
Name: new_cases, dtype: float64
90901 90908    6265.0
Name: new_cases, dtype: float64
90902 90909    2611.0
Name: new_cases, dtype: float64
90903 90910    1805.0
Name: new_cases, dtype: float64
90904 90911    7989.0
Name: new_cases, dtype: float64
90905 90912    8507.0
Name: new_cases, dtype: float64
90906 90913    9452.0
Name: new_cases, dtype: float64
90907 90914    9319.0
Name: new_cases, dtype: float64
90908 90915    9581.0
Name: new_cases, dtype: float64
90909 90916    3779.0
Name: new_cases, dtype: float64
90910 90917    3074.0
Name: new_cases, dtype: float64
90911 90918    11137.0
Name: new_cases, dtype: float64
90912 90919    12116.0
Name: new_cases, dtype: float64
90913 90920    12821.0
Name: new_cases, dtype: float64
90914 90921    12420.0
Name: new_cases, dtype: float64
90915 90922    12631.0
Name: new_cases, dtype: float64
90916 90923    4438.0
Name: new_cases, dtype: float64
90917 90924    5307.0
Name: new_cases, dtype: float64
90918 90925    13853.0
Name: new_cases, dtype: float64
90919 90926    15198.0
Name: new_cases, dtype: float64
90920 90927    16244.0
Name: new_cases, dtype: float64
90921 90928    0.0
Name: new_cases, dtype: float64
90922 90929    32244.0
Name: new_cases, dtype: float64
90923 90930    6535.0
Name: new_cases, dtype: float64
90924 90931    5920.0
Name: new_cases, dtype: float64
90925 90932    17408.0
Name: new_cases, dtype: float64
90926 90933    19028.0
Name: new_cases, dtype: float64
90927 90934    19223.0
Name: new_cases, dtype: float64
90928 90935    19346.0
Name: new_cases, dtype: float64
90929 90936    18809.0
Name: new_cases, dtype: float64
90930 90937    6740.0
Name: new_cases, dtype: float64
90931 90938    6506.0
Name: new_cases, dtype: float64
90932 90939    18911.0
Name: new_cases, dtype: float64
90933 90940    20685.0
Name: new_cases, dtype: float64
90934 90941    21569.0
Name: new_cases, dtype: float64
90935 90942    21563.0
Name: new_cases, dtype: float64
90936 90943    20018.0
Name: new_cases, dtype: float64
90937 90944    7573.0
Name: new_cases, dtype: float64
90938 90945    6513.0
Name: new_cases, dtype: float64
90939 90946    19555.0
Name: new_cases, dtype: float64
90940 90947    22711.0
Name: new_cases, dtype: float64
90941 90948    24975.0
Name: new_cases, dtype: float64
90942 90949    22758.0
Name: new_cases, dtype: float64
90943 90950    23642.0
Name: new_cases, dtype: float64
90944 90951    0.0
Name: new_cases, dtype: float64
90945 90952    16467.0
Name: new_cases, dtype: float64
90946 90953    14814.0
Name: new_cases, dtype: float64
90947 90954    28953.0
Name: new_cases, dtype: float64
90948 90955    23169.0
Name: new_cases, dtype: float64
90949 90956    21734.0
Name: new_cases, dtype: float64
90950 90957    20307.0
Name: new_cases, dtype: float64
90951 90958    7658.0
Name: new_cases, dtype: float64
90952 90959    6543.0
Name: new_cases, dtype: float64
90953 90960    18262.0
Name: new_cases, dtype: float64
90954 90961    21250.0
Name: new_cases, dtype: float64
90955 90962    20633.0
Name: new_cases, dtype: float64
90956 90963    19556.0
Name: new_cases, dtype: float64
90957 90964    17546.0
Name: new_cases, dtype: float64
90958 90965    6837.0
Name: new_cases, dtype: float64
90959 90966    5564.0
Name: new_cases, dtype: float64
90960 90967    11146.0
Name: new_cases, dtype: float64
90961 90968    17337.0
Name: new_cases, dtype: float64
90962 90969    18138.0
Name: new_cases, dtype: float64
90963 90970    17409.0
Name: new_cases, dtype: float64
90964 90971    15586.0
Name: new_cases, dtype: float64
90965 90972    7504.0
Name: new_cases, dtype: float64
90966 90973    5127.0
Name: new_cases, dtype: float64
90967 90974    15784.0
Name: new_cases, dtype: float64
90968 90975    15876.0
Name: new_cases, dtype: float64
90969 90976    14828.0
Name: new_cases, dtype: float64
90970 90977    0.0
Name: new_cases, dtype: float64
90971 90978    26744.0
Name: new_cases, dtype: float64
90972 90979    5139.0
Name: new_cases, dtype: float64
90973 90980    4161.0
Name: new_cases, dtype: float64
90974 90981    12929.0
Name: new_cases, dtype: float64
90975 90982    13217.0
Name: new_cases, dtype: float64
90976 90983    7040.0
Name: new_cases, dtype: float64
90977 90984    3754.0
Name: new_cases, dtype: float64
90978 90985    0.0
Name: new_cases, dtype: float64
90979 90986    16694.0
Name: new_cases, dtype: float64
90980 90987    3367.0
Name: new_cases, dtype: float64
90981 90988    12521.0
Name: new_cases, dtype: float64
90982 90989    11603.0
Name: new_cases, dtype: float64

90983 90990    11808.0
Name: new_cases, dtype: float64
90984 90991    10139.0
Name: new_cases, dtype: float64
90985 90992    0.0
Name: new_cases, dtype: float64
90986 90993    13685.0
Name: new_cases, dtype: float64
90987 90994    3007.0
Name: new_cases, dtype: float64
90988 90995    9792.0
Name: new_cases, dtype: float64
90989 90996    9796.0
Name: new_cases, dtype: float64
90990 90997    8828.0
Name: new_cases, dtype: float64
90991 90998    7388.0
Name: new_cases, dtype: float64
90992 90999    7369.0
Name: new_cases, dtype: float64
90993 91000    0.0
Name: new_cases, dtype: float64
90994 91001    5262.0
Name: new_cases, dtype: float64
90995 91002    0.0
Name: new_cases, dtype: float64
90996 91003    7682.0
Name: new_cases, dtype: float64
90997 91004    15310.0
Name: new_cases, dtype: float64
90998 91005    7158.0
Name: new_cases, dtype: float64
90999 91006    0.0
Name: new_cases, dtype: float64
91000 91007    8843.0
Name: new_cases, dtype: float64
91001 91008    2007.0
Name: new_cases, dtype: float64
91002 91009    7187.0
Name: new_cases, dtype: float64
91003 91010    6320.0
Name: new_cases, dtype: float64
91004 91011    5825.0
Name: new_cases, dtype: float64
91005 91012    5286.0
Name: new_cases, dtype: float64
91006 91013    5203.0
Name: new_cases, dtype: float64
91007 91014    1993.0
Name: new_cases, dtype: float64
91008 91015    1413.0
Name: new_cases, dtype: float64
91009 91016    4220.0
Name: new_cases, dtype: float64
91010 91017    5069.0
Name: new_cases, dtype: float64
91011 91018    4798.0
Name: new_cases, dtype: float64
91012 91019    4653.0
Name: new_cases, dtype: float64
91013 91020    4452.0
Name: new_cases, dtype: float64
91014 91021    0.0
Name: new_cases, dtype: float64
91015 91022    2787.0
Name: new_cases, dtype: float64
91016 91023    0.0
Name: new_cases, dtype: float64
91017 91024    4538.0
Name: new_cases, dtype: float64
91018 91025    9300.0
Name: new_cases, dtype: float64
91019 91026    4001.0
Name: new_cases, dtype: float64
91020 91027    3478.0
Name: new_cases, dtype: float64
91021 91028    1446.0
Name: new_cases, dtype: float64
91022 91029    0.0
Name: new_cases, dtype: float64
91023 91030    994.0
Name: new_cases, dtype: float64
91024 91031    3588.0
Name: new_cases, dtype: float64
91025 91032    2660.0
Name: new_cases, dtype: float64
91026 91033    3763.0
Name: new_cases, dtype: float64
91027 91034    7188.0
Name: new_cases, dtype: float64
91028 91035    1382.0
Name: new_cases, dtype: float64
91029 91036    0.0
Name: new_cases, dtype: float64
91030 91037    4473.0
Name: new_cases, dtype: float64
91031 91038    0.0
Name: new_cases, dtype: float64
91032 91039    7049.0
Name: new_cases, dtype: float64
91033 91040    0.0
Name: new_cases, dtype: float64
91034 91041    3353.0
Name: new_cases, dtype: float64
91035 91042    3130.0
Name: new_cases, dtype: float64
91036 91043    942.0
Name: new_cases, dtype: float64
91037 91044    775.0
Name: new_cases, dtype: float64
91038 91045    4571.0
Name: new_cases, dtype: float64
91039 91046    3915.0
Name: new_cases, dtype: float64
91040 91047    0.0
Name: new_cases, dtype: float64
91041 91048    3837.0
Name: new_cases, dtype: float64
91042 91049    3306.0
Name: new_cases, dtype: float64
91043 91050    2141.0
Name: new_cases, dtype: float64
91044 91051    0.0
Name: new_cases, dtype: float64
91045 91052    3698.0
Name: new_cases, dtype: float64
91046 91053    8415.0
Name: new_cases, dtype: float64
91047 91054    3445.0
Name: new_cases, dtype: float64
91048 91055    0.0
Name: new_cases, dtype: float64
91049 91056    2956.0
Name: new_cases, dtype: float64
91050 91057    1774.0
Name: new_cases, dtype: float64
91051 91058    0.0
Name: new_cases, dtype: float64
91052 91059    6652.0
Name: new_cases, dtype: float64
91053 91060    0.0
Name: new_cases, dtype: float64
91054 91061    6234.0
Name: new_cases, dtype: float64
91055 91062    0.0
Name: new_cases, dtype: float64
91056 91063    3811.0
Name: new_cases, dtype: float64
91057 91064    752.0
Name: new_cases, dtype: float64
91058 91065    0.0
Name: new_cases, dtype: float64
91059 91066    3304.0
Name: new_cases, dtype: float64
91060 91067    6395.0
Name: new_cases, dtype: float64
91061 91068    0.0
Name: new_cases, dtype: float64
91062 91069    2992.0
Name: new_cases, dtype: float64
91063 91070    2655.0
Name: new_cases, dtype: float64
91064 91071    855.0
Name: new_cases, dtype: float64
91065 91072    771.0
Name: new_cases, dtype: float64
91066 91073    5651.0
Name: new_cases, dtype: float64
91067 91074    2627.0
Name: new_cases, dtype: float64
91068 91075    0.0
Name: new_cases, dtype: float64
91069 91076    2750.0
Name: new_cases, dtype: float64
91070 91077    2530.0
Name: new_cases, dtype: float64
91071 91078    1557.0
Name: new_cases, dtype: float64
91072 91079    0.0
Name: new_cases, dtype: float64
91073 91080    2980.0
Name: new_cases, dtype: float64
91074 91081    3319.0
Name: new_cases, dtype: float64
91075 91082    6883.0
Name: new_cases, dtype: float64
91076 91083    2916.0
Name: new_cases, dtype: float64
91077 91084    0.0
Name: new_cases, dtype: float64
91078 91085    803.0
Name: new_cases, dtype: float64
91079 91086    943.0
Name: new_cases, dtype: float64
91080 91087    4426.0
Name: new_cases, dtype: float64
91081 91088    5290.0
Name: new_cases, dtype: float64
91082 91089    18061.0
Name: new_cases, dtype: float64
91083 91090    9193.0
Name: new_cases, dtype: float64
91084 91091    1671.0
Name: new_cases, dtype: float64
91085 91092    2877.0
Name: new_cases, dtype: float64
91086 91093    15184.0
Name: new_cases, dtype: float64
91087 91094    20626.0
Name: new_cases, dtype: float64
91088 91095    25821.0
Name: new_cases, dtype: float64
91089 91096    28023.0
Name: new_cases, dtype: float64
91090 91097    30671.0
Name: new_cases, dtype: float64
91091 90426    1.0
Name: new_cases, dtype: float64
91092 90427    0.0
Name: new_cases, dtype: float64
91093 90428    0.0
Name: new_cases, dtype: float64
91094 90429    1.0
Name: new_cases, dtype: float64
91095 90430    4.0
Name: new_cases, dtype: float64
91096 90431    14.0
Name: new_cases, dtype: float64
91097 90432    15.0
Name: new_cases, dtype: float64
91451 91458    11.0
Name: new_cases, dtype: float64
91452 91459    0.0
Name: new_cases, dtype: float64
91453 91460    7.0
Name: new_cases, dtype: float64
91454 91461    0.0
Name: new_cases, dtype: float64
91455 91462    19.0
Name: new_cases, dtype: float64
91456 91463    17.0
Name: new_cases, dtype: float64
91457 91464    14.0
Name: new_cases, dtype: float64
91458 91465    14.0
Name: new_cases, dtype: float64
91459 91466    15.0
Name: new_cases, dtype: float64
91460 91467    16.0
Name: new_cases, dtype: float64
91461 91468    24.0
Name: new_cases, dtype: float64
91462 91469    28.0
Name: new_cases, dtype: float64
91463 91470    22.0
Name: new_cases, dtype: float64
91464 91471    32.0
Name: new_cases, dtype: float64
91465 91472    32.0
Name: new_cases, dtype: float64
91466 91473    35.0
Name: new_cases, dtype: float64
91467 91474    55.0
Name: new_cases, dtype: float64
91468 91475    70.0
Name: new_cases, dtype: float64
91469 91476    82.0
Name: new_cases, dtype: float64
91470 91477    86.0
Name: new_cases, dtype: float64
91471 91478    161.0
Name: new_cases, dtype: float64
91472 91479    112.0
Name: new_cases, dtype: float64
91473 91480    101.0
Name: new_cases, dtype: float64
91474 91481    91.0
Name: new_cases, dtype: float64
91475 91482    118.0
Name: new_cases, dtype: float64
91476 91483    115.0
Name: new_cases, dtype: float64
91477 91484    149.0
Name: new_cases, dtype: float64
91478 91485    122.0
Name: new_cases, dtype: float64
91479 91486    102.0
Name: new_cases, dtype: float64
91480 91487    50.0
Name: new_cases, dtype: float64
91481 91488    222.0
Name: new_cases, dtype: float64
91482 91489    115.0
Name: new_cases, dtype: float64
91483 91490    105.0
Name: new_cases, dtype: float64
91484 91491    110.0
Name: new_cases, dtype: float64
91485 91492    114.0
Name: new_cases, dtype: float64
91486 91493    94.0
Name: new_cases, dtype: float64
91487 91494    76.0
Name: new_cases, dtype: float64
91488 91495    66.0
Name: new_cases, dtype: float64
91489 91496    164.0
Name: new_cases, dtype: float64
91490 91497    148.0
Name: new_cases, dtype: float64
91491 91498    184.0
Name: new_cases, dtype: float64
91492 91499    194.0
Name: new_cases, dtype: float64
91493 91500    104.0
Name: new_cases, dtype: float64
91494 91501    73.0
Name: new_cases, dtype: float64
91495 91502    157.0
Name: new_cases, dtype: float64
91496 91503    133.0
Name: new_cases, dtype: float64
91497 91504    126.0
Name: new_cases, dtype: float64
91498 91505    83.0
Name: new_cases, dtype: float64
91499 91506    72.0
Name: new_cases, dtype: float64
91500 91507    69.0
Name: new_cases, dtype: float64
91501 91508    127.0
Name: new_cases, dtype: float64
91502 91509    115.0
Name: new_cases, dtype: float64
91503 91510    113.0
Name: new_cases, dtype: float64
91504 91511    129.0
Name: new_cases, dtype: float64
91505 91512    123.0
Name: new_cases, dtype: float64
91506 91513    139.0
Name: new_cases, dtype: float64
91507 91514    60.0
Name: new_cases, dtype: float64
91508 91515    68.0
Name: new_cases, dtype: float64
91509 91516    159.0
Name: new_cases, dtype: float64
91510 91517    252.0
Name: new_cases, dtype: float64
91511 91518    147.0
Name: new_cases, dtype: float64
91512 91519    192.0
Name: new_cases, dtype: float64

91513 91520    189.0
Name: new_cases, dtype: float64
91514 91521    126.0
Name: new_cases, dtype: float64
91515 91522    78.0
Name: new_cases, dtype: float64
91516 91523    202.0
Name: new_cases, dtype: float64
91517 91524    213.0
Name: new_cases, dtype: float64
91518 91525    151.0
Name: new_cases, dtype: float64
91519 91526    143.0
Name: new_cases, dtype: float64
91520 91527    147.0
Name: new_cases, dtype: float64
91521 91528    99.0
Name: new_cases, dtype: float64
91522 91529    54.0
Name: new_cases, dtype: float64
91523 91530    158.0
Name: new_cases, dtype: float64
91524 91531    232.0
Name: new_cases, dtype: float64
91525 91532    188.0
Name: new_cases, dtype: float64
91526 91533    171.0
Name: new_cases, dtype: float64
91527 91534    202.0
Name: new_cases, dtype: float64
91528 91535    153.0
Name: new_cases, dtype: float64
91529 91536    109.0
Name: new_cases, dtype: float64
91530 91537    188.0
Name: new_cases, dtype: float64
91531 91538    247.0
Name: new_cases, dtype: float64
91532 91539    223.0
Name: new_cases, dtype: float64
91533 91540    229.0
Name: new_cases, dtype: float64
91534 91541    264.0
Name: new_cases, dtype: float64
91535 91542    189.0
Name: new_cases, dtype: float64
91536 91543    107.0
Name: new_cases, dtype: float64
91537 91544    218.0
Name: new_cases, dtype: float64
91538 91545    296.0
Name: new_cases, dtype: float64
91539 91546    406.0
Name: new_cases, dtype: float64
91540 91547    366.0
Name: new_cases, dtype: float64
91541 91548    366.0
Name: new_cases, dtype: float64
91542 91549    281.0
Name: new_cases, dtype: float64
91543 91550    139.0
Name: new_cases, dtype: float64
91544 91551    375.0
Name: new_cases, dtype: float64
91545 91552    478.0
Name: new_cases, dtype: float64
91546 91553    374.0
Name: new_cases, dtype: float64
91547 91554    450.0
Name: new_cases, dtype: float64
91548 91555    397.0
Name: new_cases, dtype: float64
91549 91556    247.0
Name: new_cases, dtype: float64
91550 91557    163.0
Name: new_cases, dtype: float64
91551 91558    351.0
Name: new_cases, dtype: float64
91552 91559    364.0
Name: new_cases, dtype: float64
91553 91560    375.0
Name: new_cases, dtype: float64
91554 91561    323.0
Name: new_cases, dtype: float64
91555 91562    304.0
Name: new_cases, dtype: float64
91556 91563    170.0
Name: new_cases, dtype: float64
91557 91564    107.0
Name: new_cases, dtype: float64
91558 91565    256.0
Name: new_cases, dtype: float64
91559 91566    285.0
Name: new_cases, dtype: float64
91560 91567    252.0
Name: new_cases, dtype: float64
91561 91568    295.0
Name: new_cases, dtype: float64
91562 91569    227.0
Name: new_cases, dtype: float64
91563 91570    142.0
Name: new_cases, dtype: float64
91564 91571    92.0
Name: new_cases, dtype: float64
91565 91572    235.0
Name: new_cases, dtype: float64
91566 91573    330.0
Name: new_cases, dtype: float64
91567 91574    195.0
Name: new_cases, dtype: float64
91568 91575    258.0
Name: new_cases, dtype: float64
91569 91576    284.0
Name: new_cases, dtype: float64
91570 91577    174.0
Name: new_cases, dtype: float64
91571 91578    57.0
Name: new_cases, dtype: float64
91572 91579    269.0
Name: new_cases, dtype: float64
91573 91580    332.0
Name: new_cases, dtype: float64
91574 91581    224.0
Name: new_cases, dtype: float64
91575 91582    230.0
Name: new_cases, dtype: float64
91576 91583    300.0
Name: new_cases, dtype: float64
91577 91584    186.0
Name: new_cases, dtype: float64
91578 91585    135.0
Name: new_cases, dtype: float64
91579 91586    327.0
Name: new_cases, dtype: float64
91580 91587    356.0
Name: new_cases, dtype: float64
91581 91588    307.0
Name: new_cases, dtype: float64
91582 91589    378.0
Name: new_cases, dtype: float64
91583 91590    345.0
Name: new_cases, dtype: float64
91584 91591    206.0
Name: new_cases, dtype: float64
91585 91592    120.0
Name: new_cases, dtype: float64
91586 91593    367.0
Name: new_cases, dtype: float64
91587 91594    426.0
Name: new_cases, dtype: float64
91588 91595    396.0
Name: new_cases, dtype: float64
91589 91596    390.0
Name: new_cases, dtype: float64
91590 91597    380.0
Name: new_cases, dtype: float64
91591 91598    249.0
Name: new_cases, dtype: float64
91592 91599    120.0
Name: new_cases, dtype: float64
91593 91600    332.0
Name: new_cases, dtype: float64
91594 91601    408.0
Name: new_cases, dtype: float64
91595 91602    406.0
Name: new_cases, dtype: float64
91596 91603    362.0
Name: new_cases, dtype: float64
91597 91604    453.0
Name: new_cases, dtype: float64
91598 91605    217.0
Name: new_cases, dtype: float64
91599 91606    181.0
Name: new_cases, dtype: float64
91600 91607    382.0
Name: new_cases, dtype: float64
91601 91608    474.0
Name: new_cases, dtype: float64
91602 91609    390.0
Name: new_cases, dtype: float64
91603 91610    396.0
Name: new_cases, dtype: float64
91604 91611    422.0
Name: new_cases, dtype: float64
91605 91612    278.0
Name: new_cases, dtype: float64
91606 91613    194.0
Name: new_cases, dtype: float64
91607 91614    412.0
Name: new_cases, dtype: float64
91608 91615    626.0
Name: new_cases, dtype: float64
91609 91616    522.0
Name: new_cases, dtype: float64
91610 91617    547.0
Name: new_cases, dtype: float64
91611 91618    588.0
Name: new_cases, dtype: float64
91612 91619    406.0
Name: new_cases, dtype: float64
91613 91620    350.0
Name: new_cases, dtype: float64
91614 91621    530.0
Name: new_cases, dtype: float64
91615 91622    624.0
Name: new_cases, dtype: float64
91616 91623    564.0
Name: new_cases, dtype: float64
91617 91624    358.0
Name: new_cases, dtype: float64
91618 91625    500.0
Name: new_cases, dtype: float64
91619 91626    296.0
Name: new_cases, dtype: float64
91620 91627    220.0
Name: new_cases, dtype: float64
91621 91628    288.0
Name: new_cases, dtype: float64
91622 91629    532.0
Name: new_cases, dtype: float64
91623 91630    632.0
Name: new_cases, dtype: float64
91624 91631    534.0
Name: new_cases, dtype: float64
91625 91632    567.0
Name: new_cases, dtype: float64
91626 91633    324.0
Name: new_cases, dtype: float64
91627 91634    258.0
Name: new_cases, dtype: float64
91628 91635    501.0
Name: new_cases, dtype: float64
91629 91636    588.0
Name: new_cases, dtype: float64
91630 91637    560.0
Name: new_cases, dtype: float64
91631 91638    479.0
Name: new_cases, dtype: float64
91632 91639    531.0
Name: new_cases, dtype: float64
91633 91640    264.0
Name: new_cases, dtype: float64
91634 91641    229.0
Name: new_cases, dtype: float64
91635 91642    527.0
Name: new_cases, dtype: float64
91636 91643    627.0
Name: new_cases, dtype: float64
91637 91644    622.0
Name: new_cases, dtype: float64
91638 91645    665.0
Name: new_cases, dtype: float64
91639 91646    688.0
Name: new_cases, dtype: float64
91640 91647    260.0
Name: new_cases, dtype: float64
91641 91648    200.0
Name: new_cases, dtype: float64
91642 91649    650.0
Name: new_cases, dtype: float64
91643 91650    786.0
Name: new_cases, dtype: float64
91644 91651    721.0
Name: new_cases, dtype: float64
91645 91652    713.0
Name: new_cases, dtype: float64
91646 91653    868.0
Name: new_cases, dtype: float64
91647 91654    341.0
Name: new_cases, dtype: float64
91648 91655    319.0
Name: new_cases, dtype: float64
91649 91656    835.0
Name: new_cases, dtype: float64
91650 91657    1013.0
Name: new_cases, dtype: float64
91651 91658    1022.0
Name: new_cases, dtype: float64
91652 91659    952.0
Name: new_cases, dtype: float64
91653 91660    872.0
Name: new_cases, dtype: float64
91654 91661    691.0
Name: new_cases, dtype: float64
91655 91662    322.0
Name: new_cases, dtype: float64
91656 91663    831.0
Name: new_cases, dtype: float64
91657 91664    1062.0
Name: new_cases, dtype: float64
91658 91665    1121.0
Name: new_cases, dtype: float64
91659 91666    918.0
Name: new_cases, dtype: float64
91660 91667    929.0
Name: new_cases, dtype: float64
91661 91668    389.0
Name: new_cases, dtype: float64
91662 91669    467.0
Name: new_cases, dtype: float64
91663 91670    657.0
Name: new_cases, dtype: float64
91664 91671    1149.0
Name: new_cases, dtype: float64
91665 91672    652.0
Name: new_cases, dtype: float64
91666 91673    784.0
Name: new_cases, dtype: float64
91667 91674    792.0
Name: new_cases, dtype: float64
91668 91675    398.0
Name: new_cases, dtype: float64
91669 91676    252.0
Name: new_cases, dtype: float64
91670 91677    656.0
Name: new_cases, dtype: float64
91671 91678    833.0
Name: new_cases, dtype: float64
91672 91679    777.0
Name: new_cases, dtype: float64
91673 91680    688.0
Name: new_cases, dtype: float64
91674 91681    833.0
Name: new_cases, dtype: float64
91675 91682    414.0
Name: new_cases, dtype: float64
91676 91683    308.0
Name: new_cases, dtype: float64
91677 91684    649.0
Name: new_cases, dtype: float64
91678 91685    861.0
Name: new_cases, dtype: float64
91679 91686    912.0
Name: new_cases, dtype: float64
91680 91687    968.0
Name: new_cases, dtype: float64
91681 91688    839.0
Name: new_cases, dtype: float64
91682 91689    542.0
Name: new_cases, dtype: float64
91683 91690    195.0
Name: new_cases, dtype: float64
91684 91691    710.0
Name: new_cases, dtype: float64

91685 91692    1020.0
Name: new_cases, dtype: float64
91686 91693    1059.0
Name: new_cases, dtype: float64
91687 91694    935.0
Name: new_cases, dtype: float64
91688 91695    1174.0
Name: new_cases, dtype: float64
91689 91696    671.0
Name: new_cases, dtype: float64
91690 91697    331.0
Name: new_cases, dtype: float64
91691 91698    915.0
Name: new_cases, dtype: float64
91692 91699    1115.0
Name: new_cases, dtype: float64
91693 91700    1331.0
Name: new_cases, dtype: float64
91694 91701    1323.0
Name: new_cases, dtype: float64
91695 91702    1411.0
Name: new_cases, dtype: float64
91696 91703    507.0
Name: new_cases, dtype: float64
91697 91704    564.0
Name: new_cases, dtype: float64
91698 91705    1069.0
Name: new_cases, dtype: float64
91699 91706    1607.0
Name: new_cases, dtype: float64
91700 91707    1442.0
Name: new_cases, dtype: float64
91701 91708    1422.0
Name: new_cases, dtype: float64
91702 91709    1306.0
Name: new_cases, dtype: float64
91703 91710    1252.0
Name: new_cases, dtype: float64
91704 91711    477.0
Name: new_cases, dtype: float64
91705 91712    1215.0
Name: new_cases, dtype: float64
91706 91713    1570.0
Name: new_cases, dtype: float64
91707 91714    1691.0
Name: new_cases, dtype: float64
91708 91715    1246.0
Name: new_cases, dtype: float64
91709 91716    1712.0
Name: new_cases, dtype: float64
91710 91717    1165.0
Name: new_cases, dtype: float64
91711 91718    347.0
Name: new_cases, dtype: float64
91712 91719    1499.0
Name: new_cases, dtype: float64
91713 91720    1717.0
Name: new_cases, dtype: float64
91714 91721    1727.0
Name: new_cases, dtype: float64
91715 91722    1522.0
Name: new_cases, dtype: float64
91716 91723    1728.0
Name: new_cases, dtype: float64
91717 91724    808.0
Name: new_cases, dtype: float64
91718 91725    1130.0
Name: new_cases, dtype: float64
91719 91726    1709.0
Name: new_cases, dtype: float64
91720 91727    1766.0
Name: new_cases, dtype: float64
91721 91728    1715.0
Name: new_cases, dtype: float64
91722 91729    1579.0
Name: new_cases, dtype: float64
91723 91730    1459.0
Name: new_cases, dtype: float64
91724 91731    795.0
Name: new_cases, dtype: float64
91725 91732    735.0
Name: new_cases, dtype: float64
91726 91733    1403.0
Name: new_cases, dtype: float64
91727 91734    1673.0
Name: new_cases, dtype: float64
91728 91735    1590.0
Name: new_cases, dtype: float64
91729 91736    1441.0
Name: new_cases, dtype: float64
91730 91737    1218.0
Name: new_cases, dtype: float64
91731 91738    629.0
Name: new_cases, dtype: float64
91732 91739    703.0
Name: new_cases, dtype: float64
91733 91740    1021.0
Name: new_cases, dtype: float64
91734 91741    1282.0
Name: new_cases, dtype: float64
91735 91742    1222.0
Name: new_cases, dtype: float64
91736 91743    815.0
Name: new_cases, dtype: float64
91737 91744    746.0
Name: new_cases, dtype: float64
91738 91745    359.0
Name: new_cases, dtype: float64
91739 91746    569.0
Name: new_cases, dtype: float64
91740 91747    927.0
Name: new_cases, dtype: float64
91741 91748    990.0
Name: new_cases, dtype: float64
91742 91749    977.0
Name: new_cases, dtype: float64
91743 91750    440.0
Name: new_cases, dtype: float64
91744 91751    436.0
Name: new_cases, dtype: float64
91745 91752    179.0
Name: new_cases, dtype: float64
91746 91753    436.0
Name: new_cases, dtype: float64
91747 91754    612.0
Name: new_cases, dtype: float64
91748 91755    950.0
Name: new_cases, dtype: float64
91749 91756    423.0
Name: new_cases, dtype: float64
91750 91757    375.0
Name: new_cases, dtype: float64
91751 91758    424.0
Name: new_cases, dtype: float64
91752 91759    298.0
Name: new_cases, dtype: float64
91753 91760    271.0
Name: new_cases, dtype: float64
91754 91761    476.0
Name: new_cases, dtype: float64
91755 91762    808.0
Name: new_cases, dtype: float64
91756 91763    741.0
Name: new_cases, dtype: float64
91757 91764    576.0
Name: new_cases, dtype: float64
91758 91765    377.0
Name: new_cases, dtype: float64
91759 91766    214.0
Name: new_cases, dtype: float64
91760 91767    258.0
Name: new_cases, dtype: float64
91761 91768    394.0
Name: new_cases, dtype: float64
91762 91769    612.0
Name: new_cases, dtype: float64
91763 91770    670.0
Name: new_cases, dtype: float64
91764 91771    514.0
Name: new_cases, dtype: float64
91765 91772    635.0
Name: new_cases, dtype: float64
91766 91773    265.0
Name: new_cases, dtype: float64
91767 91774    224.0
Name: new_cases, dtype: float64
91768 91775    546.0
Name: new_cases, dtype: float64
91769 91776    654.0
Name: new_cases, dtype: float64
91770 91777    683.0
Name: new_cases, dtype: float64
91771 91778    551.0
Name: new_cases, dtype: float64
91772 91779    653.0
Name: new_cases, dtype: float64
91773 91780    291.0
Name: new_cases, dtype: float64
91774 91781    282.0
Name: new_cases, dtype: float64
91775 91782    639.0
Name: new_cases, dtype: float64
91776 91783    917.0
Name: new_cases, dtype: float64
91777 91784    982.0
Name: new_cases, dtype: float64
91778 91785    776.0
Name: new_cases, dtype: float64
91779 91786    843.0
Name: new_cases, dtype: float64
91780 91787    326.0
Name: new_cases, dtype: float64
91781 91788    289.0
Name: new_cases, dtype: float64
91782 91789    805.0
Name: new_cases, dtype: float64
91783 91790    890.0
Name: new_cases, dtype: float64
91784 91791    993.0
Name: new_cases, dtype: float64
91785 91792    1280.0
Name: new_cases, dtype: float64
91786 91793    979.0
Name: new_cases, dtype: float64
91787 91794    381.0
Name: new_cases, dtype: float64
91788 91795    363.0
Name: new_cases, dtype: float64
91789 91796    965.0
Name: new_cases, dtype: float64
91790 91797    1301.0
Name: new_cases, dtype: float64
91791 91798    1340.0
Name: new_cases, dtype: float64
91792 91799    1028.0
Name: new_cases, dtype: float64
91793 91800    1062.0
Name: new_cases, dtype: float64
91794 91801    507.0
Name: new_cases, dtype: float64
91795 91802    655.0
Name: new_cases, dtype: float64
91796 91803    1133.0
Name: new_cases, dtype: float64
91797 91804    1610.0
Name: new_cases, dtype: float64
91798 91805    1736.0
Name: new_cases, dtype: float64
91799 91806    1452.0
Name: new_cases, dtype: float64
91800 91807    1518.0
Name: new_cases, dtype: float64
91801 91808    597.0
Name: new_cases, dtype: float64
91802 91809    994.0
Name: new_cases, dtype: float64
91803 91810    1400.0
Name: new_cases, dtype: float64
91804 91811    1550.0
Name: new_cases, dtype: float64
91805 91812    1800.0
Name: new_cases, dtype: float64
91806 91813    1788.0
Name: new_cases, dtype: float64
91807 91814    1620.0
Name: new_cases, dtype: float64
91808 91815    647.0
Name: new_cases, dtype: float64
91809 91816    350.0
Name: new_cases, dtype: float64
91810 91817    873.0
Name: new_cases, dtype: float64
91811 91818    1753.0
Name: new_cases, dtype: float64
91812 91819    1896.0
Name: new_cases, dtype: float64
91813 91820    1785.0
Name: new_cases, dtype: float64
91814 91821    1801.0
Name: new_cases, dtype: float64
91815 91822    753.0
Name: new_cases, dtype: float64
91816 91823    861.0
Name: new_cases, dtype: float64
91817 91824    1688.0
Name: new_cases, dtype: float64
91818 91825    1916.0
Name: new_cases, dtype: float64
91819 91826    1797.0
Name: new_cases, dtype: float64
91820 91827    1843.0
Name: new_cases, dtype: float64
91821 91828    1635.0
Name: new_cases, dtype: float64
91822 91829    831.0
Name: new_cases, dtype: float64
91823 91830    1060.0
Name: new_cases, dtype: float64
91824 91831    1621.0
Name: new_cases, dtype: float64
91825 91832    2273.0
Name: new_cases, dtype: float64
91826 91833    2132.0
Name: new_cases, dtype: float64
91827 91834    1866.0
Name: new_cases, dtype: float64
91828 91835    1674.0
Name: new_cases, dtype: float64
91829 91836    861.0
Name: new_cases, dtype: float64
91830 91837    932.0
Name: new_cases, dtype: float64
91831 91838    917.0
Name: new_cases, dtype: float64
91832 91839    1871.0
Name: new_cases, dtype: float64
91833 91840    1515.0
Name: new_cases, dtype: float64
91834 91841    1380.0
Name: new_cases, dtype: float64
91835 91842    1258.0
Name: new_cases, dtype: float64
91836 91843    693.0
Name: new_cases, dtype: float64
91837 91844    703.0
Name: new_cases, dtype: float64
91838 91845    773.0
Name: new_cases, dtype: float64
91839 91846    1155.0
Name: new_cases, dtype: float64

91840 91847    1428.0
Name: new_cases, dtype: float64
91841 91848    910.0
Name: new_cases, dtype: float64
91842 91849    830.0
Name: new_cases, dtype: float64
91843 91850    331.0
Name: new_cases, dtype: float64
91844 91851    603.0
Name: new_cases, dtype: float64
91845 91852    544.0
Name: new_cases, dtype: float64
91846 91853    1001.0
Name: new_cases, dtype: float64
91847 91854    812.0
Name: new_cases, dtype: float64
91848 91855    689.0
Name: new_cases, dtype: float64
91849 91856    628.0
Name: new_cases, dtype: float64
91850 91857    403.0
Name: new_cases, dtype: float64
91851 91858    341.0
Name: new_cases, dtype: float64
91852 91859    453.0
Name: new_cases, dtype: float64
91853 91860    700.0
Name: new_cases, dtype: float64
91854 91861    618.0
Name: new_cases, dtype: float64
91855 91862    509.0
Name: new_cases, dtype: float64
91856 91863    380.0
Name: new_cases, dtype: float64
91857 91864    241.0
Name: new_cases, dtype: float64
91858 91865    246.0
Name: new_cases, dtype: float64
91859 91866    329.0
Name: new_cases, dtype: float64
91860 91867    424.0
Name: new_cases, dtype: float64
91861 91868    370.0
Name: new_cases, dtype: float64
91862 91869    329.0
Name: new_cases, dtype: float64
91863 91870    323.0
Name: new_cases, dtype: float64
91864 91871    175.0
Name: new_cases, dtype: float64
91865 91872    43.0
Name: new_cases, dtype: float64
91866 91873    126.0
Name: new_cases, dtype: float64
91867 91874    316.0
Name: new_cases, dtype: float64
91868 91875    333.0
Name: new_cases, dtype: float64
91869 91876    260.0
Name: new_cases, dtype: float64
91870 91877    191.0
Name: new_cases, dtype: float64
91871 91878    145.0
Name: new_cases, dtype: float64
91872 91879    49.0
Name: new_cases, dtype: float64
91873 91880    151.0
Name: new_cases, dtype: float64
91874 91881    224.0
Name: new_cases, dtype: float64
91875 91882    213.0
Name: new_cases, dtype: float64
91876 91883    181.0
Name: new_cases, dtype: float64
91877 91884    169.0
Name: new_cases, dtype: float64
91878 91885    109.0
Name: new_cases, dtype: float64
91879 91886    109.0
Name: new_cases, dtype: float64
91880 91887    121.0
Name: new_cases, dtype: float64
91881 91888    138.0
Name: new_cases, dtype: float64
91882 91889    166.0
Name: new_cases, dtype: float64
91883 91890    120.0
Name: new_cases, dtype: float64
91884 91891    102.0
Name: new_cases, dtype: float64
91885 91892    75.0
Name: new_cases, dtype: float64
91886 91893    65.0
Name: new_cases, dtype: float64
91887 91894    73.0
Name: new_cases, dtype: float64
91888 91895    94.0
Name: new_cases, dtype: float64
91889 91896    77.0
Name: new_cases, dtype: float64
91890 91897    75.0
Name: new_cases, dtype: float64
91891 91898    45.0
Name: new_cases, dtype: float64
91892 91899    40.0
Name: new_cases, dtype: float64
91893 91900    41.0
Name: new_cases, dtype: float64
91894 91901    55.0
Name: new_cases, dtype: float64
91895 91902    44.0
Name: new_cases, dtype: float64
91896 91903    69.0
Name: new_cases, dtype: float64
91897 91904    48.0
Name: new_cases, dtype: float64
91898 91905    30.0
Name: new_cases, dtype: float64
91899 91906    21.0
Name: new_cases, dtype: float64
91900 91907    48.0
Name: new_cases, dtype: float64
91901 91908    40.0
Name: new_cases, dtype: float64
91902 91909    60.0
Name: new_cases, dtype: float64
91903 91910    60.0
Name: new_cases, dtype: float64
91904 91911    54.0
Name: new_cases, dtype: float64
91905 91912    43.0
Name: new_cases, dtype: float64
91906 91913    39.0
Name: new_cases, dtype: float64
91907 91914    33.0
Name: new_cases, dtype: float64
91908 91915    48.0
Name: new_cases, dtype: float64
91909 91916    59.0
Name: new_cases, dtype: float64
91910 91917    57.0
Name: new_cases, dtype: float64
91911 91918    60.0
Name: new_cases, dtype: float64
91912 91919    49.0
Name: new_cases, dtype: float64
91913 91920    37.0
Name: new_cases, dtype: float64
91914 91921    47.0
Name: new_cases, dtype: float64
91915 91922    45.0
Name: new_cases, dtype: float64
91916 91923    92.0
Name: new_cases, dtype: float64
91917 91924    63.0
Name: new_cases, dtype: float64
91918 91925    88.0
Name: new_cases, dtype: float64
91919 91926    52.0
Name: new_cases, dtype: float64
91920 91927    32.0
Name: new_cases, dtype: float64
91921 91928    55.0
Name: new_cases, dtype: float64
91922 91929    55.0
Name: new_cases, dtype: float64
91923 91930    65.0
Name: new_cases, dtype: float64
91924 91931    82.0
Name: new_cases, dtype: float64
91925 91932    54.0
Name: new_cases, dtype: float64
91926 91933    61.0
Name: new_cases, dtype: float64
91927 91934    39.0
Name: new_cases, dtype: float64
91928 91935    65.0
Name: new_cases, dtype: float64
91929 91936    70.0
Name: new_cases, dtype: float64
91930 91937    82.0
Name: new_cases, dtype: float64
91931 91938    85.0
Name: new_cases, dtype: float64
91932 91939    71.0
Name: new_cases, dtype: float64
91933 91940    76.0
Name: new_cases, dtype: float64
91934 91941    48.0
Name: new_cases, dtype: float64
91935 91942    62.0
Name: new_cases, dtype: float64
91936 91943    59.0
Name: new_cases, dtype: float64
91937 91944    90.0
Name: new_cases, dtype: float64
91938 91945    88.0
Name: new_cases, dtype: float64
91939 91946    76.0
Name: new_cases, dtype: float64
91940 91947    61.0
Name: new_cases, dtype: float64
91941 91948    43.0
Name: new_cases, dtype: float64
91942 91949    61.0
Name: new_cases, dtype: float64
91943 91950    89.0
Name: new_cases, dtype: float64
91944 91951    141.0
Name: new_cases, dtype: float64
91945 91952    128.0
Name: new_cases, dtype: float64
91946 91953    119.0
Name: new_cases, dtype: float64
91947 91954    97.0
Name: new_cases, dtype: float64
91948 91955    43.0
Name: new_cases, dtype: float64
91949 91956    89.0
Name: new_cases, dtype: float64
91950 91957    139.0
Name: new_cases, dtype: float64
91951 91958    166.0
Name: new_cases, dtype: float64
91952 91959    184.0
Name: new_cases, dtype: float64
91953 91960    154.0
Name: new_cases, dtype: float64
91954 91961    122.0
Name: new_cases, dtype: float64
91955 91962    71.0
Name: new_cases, dtype: float64
91956 91963    118.0
Name: new_cases, dtype: float64
91957 91964    161.0
Name: new_cases, dtype: float64
91958 91965    196.0
Name: new_cases, dtype: float64
91959 91966    159.0
Name: new_cases, dtype: float64
91960 91967    241.0
Name: new_cases, dtype: float64
91961 91968    131.0
Name: new_cases, dtype: float64
91962 91969    75.0
Name: new_cases, dtype: float64
91963 91970    177.0
Name: new_cases, dtype: float64
91964 91971    193.0
Name: new_cases, dtype: float64
91965 91972    256.0
Name: new_cases, dtype: float64
91966 91973    268.0
Name: new_cases, dtype: float64
91967 91974    283.0
Name: new_cases, dtype: float64
91968 91975    140.0
Name: new_cases, dtype: float64
91969 91976    97.0
Name: new_cases, dtype: float64
91970 91977    200.0
Name: new_cases, dtype: float64
91971 91978    345.0
Name: new_cases, dtype: float64
91972 91979    485.0
Name: new_cases, dtype: float64
91973 91980    426.0
Name: new_cases, dtype: float64
91974 91981    407.0
Name: new_cases, dtype: float64
91975 91982    376.0
Name: new_cases, dtype: float64
91976 91983    149.0
Name: new_cases, dtype: float64
91977 91984    314.0
Name: new_cases, dtype: float64
91978 91985    512.0
Name: new_cases, dtype: float64
91979 91986    559.0
Name: new_cases, dtype: float64
91980 91987    497.0
Name: new_cases, dtype: float64
91981 91988    277.0
Name: new_cases, dtype: float64
91982 91989    193.0
Name: new_cases, dtype: float64
91983 91990    204.0
Name: new_cases, dtype: float64
91984 91991    216.0
Name: new_cases, dtype: float64
91985 91992    322.0
Name: new_cases, dtype: float64
91986 91993    579.0
Name: new_cases, dtype: float64
91987 91994    787.0
Name: new_cases, dtype: float64
91988 91995    710.0
Name: new_cases, dtype: float64
91989 91996    384.0
Name: new_cases, dtype: float64
91990 91997    233.0
Name: new_cases, dtype: float64
91991 91998    466.0
Name: new_cases, dtype: float64
91992 91999    850.0
Name: new_cases, dtype: float64
91993 92000    790.0
Name: new_cases, dtype: float64
91994 92001    731.0
Name: new_cases, dtype: float64
91995 92002    862.0
Name: new_cases, dtype: float64
91996 92003    681.0
Name: new_cases, dtype: float64
91997 92004    213.0
Name: new_cases, dtype: float64
91998 92005    746.0
Name: new_cases, dtype: float64
91999 92006    1143.0
Name: new_cases, dtype: float64
92000 92007    1153.0
Name: new_cases, dtype: float64
92001 92008    1289.0
Name: new_cases, dtype: float64
92002 92009    1032.0
Name: new_cases, dtype: float64
92003 92010    1041.0
Name: new_cases, dtype: float64
92004 92011    484.0
Name: new_cases, dtype: float64
92005 92012    950.0
Name: new_cases, dtype: float64
92006 92013    1300.0
Name: new_cases, dtype: float64
92007 92014    1371.0
Name: new_cases, dtype: float64
92008 92015    1215.0
Name: new_cases, dtype: float64

92009 92016    1194.0
Name: new_cases, dtype: float64
92010 92017    647.0
Name: new_cases, dtype: float64
92011 92018    648.0
Name: new_cases, dtype: float64
92012 92019    1018.0
Name: new_cases, dtype: float64
92013 92020    1209.0
Name: new_cases, dtype: float64
92014 92021    1587.0
Name: new_cases, dtype: float64
92015 92022    1553.0
Name: new_cases, dtype: float64
92016 92023    1289.0
Name: new_cases, dtype: float64
92017 92024    991.0
Name: new_cases, dtype: float64
92018 92025    560.0
Name: new_cases, dtype: float64
92019 92026    1078.0
Name: new_cases, dtype: float64
92020 92027    1533.0
Name: new_cases, dtype: float64
92021 92028    1588.0
Name: new_cases, dtype: float64
92022 92029    1777.0
Name: new_cases, dtype: float64
92023 92030    1470.0
Name: new_cases, dtype: float64
92024 92031    1299.0
Name: new_cases, dtype: float64
92025 92032    670.0
Name: new_cases, dtype: float64
92026 92033    535.0
Name: new_cases, dtype: float64
92027 92034    1542.0
Name: new_cases, dtype: float64
92028 92035    2052.0
Name: new_cases, dtype: float64
92029 92036    1666.0
Name: new_cases, dtype: float64
92030 92037    1407.0
Name: new_cases, dtype: float64
92031 92038    1565.0
Name: new_cases, dtype: float64
92032 92039    1115.0
Name: new_cases, dtype: float64
92033 92040    1370.0
Name: new_cases, dtype: float64
92034 92041    1715.0
Name: new_cases, dtype: float64
92035 92042    2068.0
Name: new_cases, dtype: float64
92036 92043    1787.0
Name: new_cases, dtype: float64
92037 92044    2057.0
Name: new_cases, dtype: float64
92038 92045    1568.0
Name: new_cases, dtype: float64
92039 92046    906.0
Name: new_cases, dtype: float64
92040 92047    1294.0
Name: new_cases, dtype: float64
92041 92048    1505.0
Name: new_cases, dtype: float64
92042 92049    1826.0
Name: new_cases, dtype: float64
92043 92050    1662.0
Name: new_cases, dtype: float64
92044 92051    1573.0
Name: new_cases, dtype: float64
92045 92052    1255.0
Name: new_cases, dtype: float64
92046 92053    653.0
Name: new_cases, dtype: float64
92047 92054    1346.0
Name: new_cases, dtype: float64
92048 92055    1074.0
Name: new_cases, dtype: float64
92049 92056    1487.0
Name: new_cases, dtype: float64
92050 92057    1586.0
Name: new_cases, dtype: float64
92051 92058    1302.0
Name: new_cases, dtype: float64
92052 92059    954.0
Name: new_cases, dtype: float64
92053 92060    447.0
Name: new_cases, dtype: float64
92054 92061    1141.0
Name: new_cases, dtype: float64
92055 92062    1483.0
Name: new_cases, dtype: float64
92056 92063    980.0
Name: new_cases, dtype: float64
92057 92064    1129.0
Name: new_cases, dtype: float64
92058 92065    1243.0
Name: new_cases, dtype: float64
92059 92066    730.0
Name: new_cases, dtype: float64
92060 92067    152.0
Name: new_cases, dtype: float64
92061 92068    956.0
Name: new_cases, dtype: float64
92062 92069    977.0
Name: new_cases, dtype: float64
92063 92070    891.0
Name: new_cases, dtype: float64
92064 92071    802.0
Name: new_cases, dtype: float64
92065 92072    763.0
Name: new_cases, dtype: float64
92066 92073    620.0
Name: new_cases, dtype: float64
92067 92074    371.0
Name: new_cases, dtype: float64
92068 92075    655.0
Name: new_cases, dtype: float64
92069 92076    544.0
Name: new_cases, dtype: float64
92070 92077    860.0
Name: new_cases, dtype: float64
92071 92078    855.0
Name: new_cases, dtype: float64
92072 92079    712.0
Name: new_cases, dtype: float64
92073 92080    498.0
Name: new_cases, dtype: float64
92074 92081    107.0
Name: new_cases, dtype: float64
92075 92082    677.0
Name: new_cases, dtype: float64
92076 92083    664.0
Name: new_cases, dtype: float64
92077 92084    659.0
Name: new_cases, dtype: float64
92078 92085    732.0
Name: new_cases, dtype: float64
92079 92086    548.0
Name: new_cases, dtype: float64
92080 92087    449.0
Name: new_cases, dtype: float64
92081 92088    94.0
Name: new_cases, dtype: float64
92082 92089    495.0
Name: new_cases, dtype: float64
92083 92090    588.0
Name: new_cases, dtype: float64
92084 92091    609.0
Name: new_cases, dtype: float64
92085 92092    549.0
Name: new_cases, dtype: float64
92086 92093    516.0
Name: new_cases, dtype: float64
92087 92094    389.0
Name: new_cases, dtype: float64
92088 92095    257.0
Name: new_cases, dtype: float64
92089 92096    344.0
Name: new_cases, dtype: float64
92090 92097    456.0
Name: new_cases, dtype: float64
92091 92098    492.0
Name: new_cases, dtype: float64
92092 92099    459.0
Name: new_cases, dtype: float64
92093 92100    440.0
Name: new_cases, dtype: float64
92094 92101    304.0
Name: new_cases, dtype: float64
92095 92102    46.0
Name: new_cases, dtype: float64
92096 92103    229.0
Name: new_cases, dtype: float64
92097 92104    554.0
Name: new_cases, dtype: float64
92098 92105    390.0
Name: new_cases, dtype: float64
92099 92106    379.0
Name: new_cases, dtype: float64
92100 92107    368.0
Name: new_cases, dtype: float64
92101 92108    229.0
Name: new_cases, dtype: float64
92102 92109    177.0
Name: new_cases, dtype: float64
92103 92110    237.0
Name: new_cases, dtype: float64
92104 92111    302.0
Name: new_cases, dtype: float64
92105 92112    293.0
Name: new_cases, dtype: float64
92106 92113    422.0
Name: new_cases, dtype: float64
92107 92114    375.0
Name: new_cases, dtype: float64
92108 92115    279.0
Name: new_cases, dtype: float64
92109 92116    168.0
Name: new_cases, dtype: float64
92110 92117    242.0
Name: new_cases, dtype: float64
92111 92118    652.0
Name: new_cases, dtype: float64
92112 92119    706.0
Name: new_cases, dtype: float64
92113 92120    702.0
Name: new_cases, dtype: float64
92114 92121    668.0
Name: new_cases, dtype: float64
92115 92122    329.0
Name: new_cases, dtype: float64
92116 Series([], Name: new_cases, dtype: float64)
92117 Series([], Name: new_cases, dtype: float64)
92118 Series([], Name: new_cases, dtype: float64)
92119 Series([], Name: new_cases, dtype: float64)
92120 Series([], Name: new_cases, dtype: float64)
92121 Series([], Name: new_cases, dtype: float64)
92122 91451    1.0
Name: new_cases, dtype: float64
94822 94829    0.0
Name: new_cases, dtype: float64
94823 94830    1.0
Name: new_cases, dtype: float64
94824 94831    2.0
Name: new_cases, dtype: float64
94825 94832    1.0
Name: new_cases, dtype: float64
94826 94833    1.0
Name: new_cases, dtype: float64
94827 94834    10.0
Name: new_cases, dtype: float64
94828 94835    11.0
Name: new_cases, dtype: float64
94829 94836    1.0
Name: new_cases, dtype: float64
94830 94837    9.0
Name: new_cases, dtype: float64
94831 94838    11.0
Name: new_cases, dtype: float64
94832 94839    14.0
Name: new_cases, dtype: float64
94833 94840    14.0
Name: new_cases, dtype: float64
94834 94841    19.0
Name: new_cases, dtype: float64
94835 94842    19.0
Name: new_cases, dtype: float64
94836 94843    28.0
Name: new_cases, dtype: float64
94837 94844    27.0
Name: new_cases, dtype: float64
94838 94845    55.0
Name: new_cases, dtype: float64
94839 94846    50.0
Name: new_cases, dtype: float64
94840 94847    70.0
Name: new_cases, dtype: float64
94841 94848    57.0
Name: new_cases, dtype: float64
94842 94849    77.0
Name: new_cases, dtype: float64
94843 94850    77.0
Name: new_cases, dtype: float64
94844 94851    61.0
Name: new_cases, dtype: float64
94845 94852    37.0
Name: new_cases, dtype: float64
94846 94853    54.0
Name: new_cases, dtype: float64
94847 94854    83.0
Name: new_cases, dtype: float64
94848 94855    128.0
Name: new_cases, dtype: float64
94849 94856    102.0
Name: new_cases, dtype: float64
94850 94857    99.0
Name: new_cases, dtype: float64
94851 94858    64.0
Name: new_cases, dtype: float64
94852 94859    91.0
Name: new_cases, dtype: float64
94853 94860    99.0
Name: new_cases, dtype: float64
94854 94861    74.0
Name: new_cases, dtype: float64
94855 94862    97.0
Name: new_cases, dtype: float64
94856 94863    116.0
Name: new_cases, dtype: float64
94857 94864    102.0
Name: new_cases, dtype: float64
94858 94865    125.0
Name: new_cases, dtype: float64
94859 94866    136.0
Name: new_cases, dtype: float64
94860 94867    259.0
Name: new_cases, dtype: float64
94861 94868    281.0
Name: new_cases, dtype: float64
94862 94869    121.0
Name: new_cases, dtype: float64
94863 94870    170.0
Name: new_cases, dtype: float64
94864 94871    191.0
Name: new_cases, dtype: float64
94865 94872    163.0
Name: new_cases, dtype: float64
94866 94873    237.0
Name: new_cases, dtype: float64
94867 94874    122.0
Name: new_cases, dtype: float64
94868 94875    190.0
Name: new_cases, dtype: float64
94869 94876    139.0
Name: new_cases, dtype: float64
94870 94877    168.0
Name: new_cases, dtype: float64
94871 94878    55.0
Name: new_cases, dtype: float64
94872 94879    132.0
Name: new_cases, dtype: float64
94873 94880    69.0
Name: new_cases, dtype: float64
94874 94881    102.0
Name: new_cases, dtype: float64
94875 94882    146.0
Name: new_cases, dtype: float64
94876 94883    160.0
Name: new_cases, dtype: float64
94877 94884    174.0
Name: new_cases, dtype: float64
94878 94885    150.0
Name: new_cases, dtype: float64
94879 94886    166.0
Name: new_cases, dtype: float64
94880 94887    189.0
Name: new_cases, dtype: float64
94881 94888    140.0
Name: new_cases, dtype: float64
94882 94889    163.0
Name: new_cases, dtype: float64
94883 94890    199.0
Name: new_cases, dtype: float64

94884 94891    153.0
Name: new_cases, dtype: float64
94885 94892    218.0
Name: new_cases, dtype: float64
94886 94893    137.0
Name: new_cases, dtype: float64
94887 94894    94.0
Name: new_cases, dtype: float64
94888 94895    95.0
Name: new_cases, dtype: float64
94889 94896    45.0
Name: new_cases, dtype: float64
94890 94897    89.0
Name: new_cases, dtype: float64
94891 94898    129.0
Name: new_cases, dtype: float64
94892 94899    82.0
Name: new_cases, dtype: float64
94893 94900    71.0
Name: new_cases, dtype: float64
94894 94901    110.0
Name: new_cases, dtype: float64
94895 94902    78.0
Name: new_cases, dtype: float64
94896 94903    121.0
Name: new_cases, dtype: float64
94897 94904    74.0
Name: new_cases, dtype: float64
94898 94905    27.0
Name: new_cases, dtype: float64
94899 94906    99.0
Name: new_cases, dtype: float64
94900 94907    45.0
Name: new_cases, dtype: float64
94901 94908    24.0
Name: new_cases, dtype: float64
94902 94909    42.0
Name: new_cases, dtype: float64
94903 94910    71.0
Name: new_cases, dtype: float64
94904 94911    66.0
Name: new_cases, dtype: float64
94905 94912    27.0
Name: new_cases, dtype: float64
94906 94913    26.0
Name: new_cases, dtype: float64
94907 94914    33.0
Name: new_cases, dtype: float64
94908 94915    56.0
Name: new_cases, dtype: float64
94909 94916    81.0
Name: new_cases, dtype: float64
94910 94917    68.0
Name: new_cases, dtype: float64
94911 94918    80.0
Name: new_cases, dtype: float64
94912 94919    73.0
Name: new_cases, dtype: float64
94913 94920    78.0
Name: new_cases, dtype: float64
94914 94921    135.0
Name: new_cases, dtype: float64
94915 94922    71.0
Name: new_cases, dtype: float64
94916 94923    29.0
Name: new_cases, dtype: float64
94917 94924    73.0
Name: new_cases, dtype: float64
94918 94925    82.0
Name: new_cases, dtype: float64
94919 94926    101.0
Name: new_cases, dtype: float64
94920 94927    92.0
Name: new_cases, dtype: float64
94921 94928    46.0
Name: new_cases, dtype: float64
94922 94929    66.0
Name: new_cases, dtype: float64
94923 94930    77.0
Name: new_cases, dtype: float64
94924 94931    539.0
Name: new_cases, dtype: float64
94925 94932    226.0
Name: new_cases, dtype: float64
94926 94933    138.0
Name: new_cases, dtype: float64
94927 94934    195.0
Name: new_cases, dtype: float64
94928 94935    172.0
Name: new_cases, dtype: float64
94929 94936    563.0
Name: new_cases, dtype: float64
94930 94937    431.0
Name: new_cases, dtype: float64
94931 94938    295.0
Name: new_cases, dtype: float64
94932 94939    244.0
Name: new_cases, dtype: float64
94933 94940    175.0
Name: new_cases, dtype: float64
94934 94941    238.0
Name: new_cases, dtype: float64
94935 94942    243.0
Name: new_cases, dtype: float64
94936 94943    103.0
Name: new_cases, dtype: float64
94937 94944    333.0
Name: new_cases, dtype: float64
94938 94945    319.0
Name: new_cases, dtype: float64
94939 94946    534.0
Name: new_cases, dtype: float64
94940 94947    393.0
Name: new_cases, dtype: float64
94941 94948    164.0
Name: new_cases, dtype: float64
94942 94949    228.0
Name: new_cases, dtype: float64
94943 94950    164.0
Name: new_cases, dtype: float64
94944 94951    308.0
Name: new_cases, dtype: float64
94945 94952    249.0
Name: new_cases, dtype: float64
94946 94953    214.0
Name: new_cases, dtype: float64
94947 94954    203.0
Name: new_cases, dtype: float64
94948 94955    191.0
Name: new_cases, dtype: float64
94949 94956    161.0
Name: new_cases, dtype: float64
94950 94957    165.0
Name: new_cases, dtype: float64
94951 94958    283.0
Name: new_cases, dtype: float64
94952 94959    181.0
Name: new_cases, dtype: float64
94953 94960    289.0
Name: new_cases, dtype: float64
94954 94961    221.0
Name: new_cases, dtype: float64
94955 94962    326.0
Name: new_cases, dtype: float64
94956 94963    180.0
Name: new_cases, dtype: float64
94957 94964    220.0
Name: new_cases, dtype: float64
94958 94965    302.0
Name: new_cases, dtype: float64
94959 94966    570.0
Name: new_cases, dtype: float64
94960 94967    811.0
Name: new_cases, dtype: float64
94961 94968    633.0
Name: new_cases, dtype: float64
94962 94969    609.0
Name: new_cases, dtype: float64
94963 94970    500.0
Name: new_cases, dtype: float64
94964 94971    826.0
Name: new_cases, dtype: float64
94965 94972    1046.0
Name: new_cases, dtype: float64
94966 94973    1063.0
Name: new_cases, dtype: float64
94967 94974    693.0
Name: new_cases, dtype: float64
94968 94975    522.0
Name: new_cases, dtype: float64
94969 94976    659.0
Name: new_cases, dtype: float64
94970 94977    1021.0
Name: new_cases, dtype: float64
94971 94978    1283.0
Name: new_cases, dtype: float64
94972 94979    1144.0
Name: new_cases, dtype: float64
94973 94980    1018.0
Name: new_cases, dtype: float64
94974 94981    1345.0
Name: new_cases, dtype: float64
94975 94982    1230.0
Name: new_cases, dtype: float64
94976 94983    826.0
Name: new_cases, dtype: float64
94977 94984    1132.0
Name: new_cases, dtype: float64
94978 94985    1499.0
Name: new_cases, dtype: float64
94979 94986    1241.0
Name: new_cases, dtype: float64
94980 94987    1306.0
Name: new_cases, dtype: float64
94981 94988    1776.0
Name: new_cases, dtype: float64
94982 94989    1472.0
Name: new_cases, dtype: float64
94983 94990    1069.0
Name: new_cases, dtype: float64
94984 94991    1245.0
Name: new_cases, dtype: float64
94985 94992    1510.0
Name: new_cases, dtype: float64
94986 94993    1325.0
Name: new_cases, dtype: float64
94987 94994    1609.0
Name: new_cases, dtype: float64
94988 94995    1565.0
Name: new_cases, dtype: float64
94989 94996    1537.0
Name: new_cases, dtype: float64
94990 94997    903.0
Name: new_cases, dtype: float64
94991 94998    1276.0
Name: new_cases, dtype: float64
94992 94999    1336.0
Name: new_cases, dtype: float64
94993 95000    1221.0
Name: new_cases, dtype: float64
94994 95001    1404.0
Name: new_cases, dtype: float64
94995 95002    1567.0
Name: new_cases, dtype: float64
94996 95003    1343.0
Name: new_cases, dtype: float64
94997 95004    1191.0
Name: new_cases, dtype: float64
94998 95005    1191.0
Name: new_cases, dtype: float64
94999 95006    1672.0
Name: new_cases, dtype: float64
95000 95007    1402.0
Name: new_cases, dtype: float64
95001 95008    1750.0
Name: new_cases, dtype: float64
95002 95009    1555.0
Name: new_cases, dtype: float64
95003 95010    2234.0
Name: new_cases, dtype: float64
95004 95011    1386.0
Name: new_cases, dtype: float64
95005 95012    1941.0
Name: new_cases, dtype: float64
95006 95013    2157.0
Name: new_cases, dtype: float64
95007 95014    1889.0
Name: new_cases, dtype: float64
95008 95015    2430.0
Name: new_cases, dtype: float64
95009 95016    2238.0
Name: new_cases, dtype: float64
95010 95017    2251.0
Name: new_cases, dtype: float64
95011 95018    1517.0
Name: new_cases, dtype: float64
95012 95019    2121.0
Name: new_cases, dtype: float64
95013 95020    1692.0
Name: new_cases, dtype: float64
95014 95021    2488.0
Name: new_cases, dtype: float64
95015 95022    2760.0
Name: new_cases, dtype: float64
95016 95023    2552.0
Name: new_cases, dtype: float64
95017 95024    1927.0
Name: new_cases, dtype: float64
95018 95025    1376.0
Name: new_cases, dtype: float64
95019 95026    2227.0
Name: new_cases, dtype: float64
95020 95027    2397.0
Name: new_cases, dtype: float64
95021 95028    2356.0
Name: new_cases, dtype: float64
95022 95029    2423.0
Name: new_cases, dtype: float64
95023 95030    2719.0
Name: new_cases, dtype: float64
95024 95031    2444.0
Name: new_cases, dtype: float64
95025 95032    1422.0
Name: new_cases, dtype: float64
95026 95033    2076.0
Name: new_cases, dtype: float64
95027 95034    2470.0
Name: new_cases, dtype: float64
95028 95035    2391.0
Name: new_cases, dtype: float64
95029 95036    2521.0
Name: new_cases, dtype: float64
95030 95037    2663.0
Name: new_cases, dtype: float64
95031 95038    2044.0
Name: new_cases, dtype: float64
95032 95039    1423.0
Name: new_cases, dtype: float64
95033 95040    2553.0
Name: new_cases, dtype: float64
95034 95041    2776.0
Name: new_cases, dtype: float64
95035 95042    2929.0
Name: new_cases, dtype: float64
95036 95043    3445.0
Name: new_cases, dtype: float64
95037 95044    3443.0
Name: new_cases, dtype: float64
95038 95045    2563.0
Name: new_cases, dtype: float64
95039 95046    1357.0
Name: new_cases, dtype: float64
95040 95047    3185.0
Name: new_cases, dtype: float64
95041 95048    3387.0
Name: new_cases, dtype: float64
95042 95049    3317.0
Name: new_cases, dtype: float64
95043 95050    3498.0
Name: new_cases, dtype: float64
95044 95051    3763.0
Name: new_cases, dtype: float64
95045 95052    2721.0
Name: new_cases, dtype: float64
95046 95053    2117.0
Name: new_cases, dtype: float64
95047 95054    3254.0
Name: new_cases, dtype: float64
95048 95055    3577.0
Name: new_cases, dtype: float64
95049 95056    4151.0
Name: new_cases, dtype: float64
95050 95057    3685.0
Name: new_cases, dtype: float64
95051 95058    4045.0
Name: new_cases, dtype: float64
95052 95059    3020.0
Name: new_cases, dtype: float64
95053 95060    2264.0
Name: new_cases, dtype: float64
95054 95061    3988.0
Name: new_cases, dtype: float64
95055 95062    3985.0
Name: new_cases, dtype: float64
95056 95063    4320.0
Name: new_cases, dtype: float64
95057 95064    3256.0
Name: new_cases, dtype: float64
95058 95065    3790.0
Name: new_cases, dtype: float64

95059 95066    3460.0
Name: new_cases, dtype: float64
95060 95067    2526.0
Name: new_cases, dtype: float64
95061 95068    4495.0
Name: new_cases, dtype: float64
95062 95069    5745.0
Name: new_cases, dtype: float64
95063 95070    5641.0
Name: new_cases, dtype: float64
95064 95071    5398.0
Name: new_cases, dtype: float64
95065 95072    5836.0
Name: new_cases, dtype: float64
95066 95073    4596.0
Name: new_cases, dtype: float64
95067 95074    3170.0
Name: new_cases, dtype: float64
95068 95075    5214.0
Name: new_cases, dtype: float64
95069 95076    5461.0
Name: new_cases, dtype: float64
95070 95077    6195.0
Name: new_cases, dtype: float64
95071 95078    5515.0
Name: new_cases, dtype: float64
95072 95079    5875.0
Name: new_cases, dtype: float64
95073 95080    4966.0
Name: new_cases, dtype: float64
95074 95081    3012.0
Name: new_cases, dtype: float64
95075 95082    5415.0
Name: new_cases, dtype: float64
95076 95083    5391.0
Name: new_cases, dtype: float64
95077 95084    4559.0
Name: new_cases, dtype: float64
95078 95085    4706.0
Name: new_cases, dtype: float64
95079 95086    4702.0
Name: new_cases, dtype: float64
95080 95087    3979.0
Name: new_cases, dtype: float64
95081 95088    2587.0
Name: new_cases, dtype: float64
95082 95089    3999.0
Name: new_cases, dtype: float64
95083 95090    4979.0
Name: new_cases, dtype: float64
95084 95091    4178.0
Name: new_cases, dtype: float64
95085 95092    4592.0
Name: new_cases, dtype: float64
95086 95093    4412.0
Name: new_cases, dtype: float64
95087 95094    4115.0
Name: new_cases, dtype: float64
95088 95095    2533.0
Name: new_cases, dtype: float64
95089 95096    3508.0
Name: new_cases, dtype: float64
95090 95097    4346.0
Name: new_cases, dtype: float64
95091 95098    4434.0
Name: new_cases, dtype: float64
95092 95099    3996.0
Name: new_cases, dtype: float64
95093 95100    4118.0
Name: new_cases, dtype: float64
95094 95101    2919.0
Name: new_cases, dtype: float64
95095 95102    1531.0
Name: new_cases, dtype: float64
95096 95103    2900.0
Name: new_cases, dtype: float64
95097 95104    4096.0
Name: new_cases, dtype: float64
95098 95105    3345.0
Name: new_cases, dtype: float64
95099 95106    3035.0
Name: new_cases, dtype: float64
95100 95107    3033.0
Name: new_cases, dtype: float64
95101 95108    2012.0
Name: new_cases, dtype: float64
95102 95109    1217.0
Name: new_cases, dtype: float64
95103 95110    2793.0
Name: new_cases, dtype: float64
95104 95111    3351.0
Name: new_cases, dtype: float64
95105 95112    2776.0
Name: new_cases, dtype: float64
95106 95113    2647.0
Name: new_cases, dtype: float64
95107 95114    2833.0
Name: new_cases, dtype: float64
95108 95115    1899.0
Name: new_cases, dtype: float64
95109 95116    877.0
Name: new_cases, dtype: float64
95110 95117    2646.0
Name: new_cases, dtype: float64
95111 95118    2566.0
Name: new_cases, dtype: float64
95112 95119    2650.0
Name: new_cases, dtype: float64
95113 95120    2329.0
Name: new_cases, dtype: float64
95114 95121    2369.0
Name: new_cases, dtype: float64
95115 95122    1517.0
Name: new_cases, dtype: float64
95116 95123    950.0
Name: new_cases, dtype: float64
95117 95124    2160.0
Name: new_cases, dtype: float64
95118 95125    2143.0
Name: new_cases, dtype: float64
95119 95126    1861.0
Name: new_cases, dtype: float64
95120 95127    1777.0
Name: new_cases, dtype: float64
95121 95128    1171.0
Name: new_cases, dtype: float64
95122 95129    1005.0
Name: new_cases, dtype: float64
95123 95130    656.0
Name: new_cases, dtype: float64
95124 95131    1637.0
Name: new_cases, dtype: float64
95125 95132    1642.0
Name: new_cases, dtype: float64
95126 95133    1597.0
Name: new_cases, dtype: float64
95127 95134    1543.0
Name: new_cases, dtype: float64
95128 95135    1416.0
Name: new_cases, dtype: float64
95129 95136    895.0
Name: new_cases, dtype: float64
95130 95137    456.0
Name: new_cases, dtype: float64
95131 95138    801.0
Name: new_cases, dtype: float64
95132 95139    1266.0
Name: new_cases, dtype: float64
95133 95140    1279.0
Name: new_cases, dtype: float64
95134 95141    1291.0
Name: new_cases, dtype: float64
95135 95142    1240.0
Name: new_cases, dtype: float64
95136 95143    806.0
Name: new_cases, dtype: float64
95137 95144    473.0
Name: new_cases, dtype: float64
95138 95145    1246.0
Name: new_cases, dtype: float64
95139 95146    1152.0
Name: new_cases, dtype: float64
95140 95147    1164.0
Name: new_cases, dtype: float64
95141 95148    1138.0
Name: new_cases, dtype: float64
95142 95149    925.0
Name: new_cases, dtype: float64
95143 95150    520.0
Name: new_cases, dtype: float64
95144 95151    337.0
Name: new_cases, dtype: float64
95145 95152    867.0
Name: new_cases, dtype: float64
95146 95153    890.0
Name: new_cases, dtype: float64
95147 95154    756.0
Name: new_cases, dtype: float64
95148 95155    851.0
Name: new_cases, dtype: float64
95149 95156    701.0
Name: new_cases, dtype: float64
95150 95157    466.0
Name: new_cases, dtype: float64
95151 95158    281.0
Name: new_cases, dtype: float64
95152 95159    835.0
Name: new_cases, dtype: float64
95153 95160    774.0
Name: new_cases, dtype: float64
95154 95161    620.0
Name: new_cases, dtype: float64
95155 95162    712.0
Name: new_cases, dtype: float64
95156 95163    587.0
Name: new_cases, dtype: float64
95157 95164    389.0
Name: new_cases, dtype: float64
95158 95165    234.0
Name: new_cases, dtype: float64
95159 95166    536.0
Name: new_cases, dtype: float64
95160 95167    564.0
Name: new_cases, dtype: float64
95161 95168    471.0
Name: new_cases, dtype: float64
95162 95169    496.0
Name: new_cases, dtype: float64
95163 95170    479.0
Name: new_cases, dtype: float64
95164 95171    339.0
Name: new_cases, dtype: float64
95165 95172    121.0
Name: new_cases, dtype: float64
95166 95173    476.0
Name: new_cases, dtype: float64
95167 95174    508.0
Name: new_cases, dtype: float64
95168 95175    477.0
Name: new_cases, dtype: float64
95169 95176    448.0
Name: new_cases, dtype: float64
95170 95177    444.0
Name: new_cases, dtype: float64
95171 95178    207.0
Name: new_cases, dtype: float64
95172 95179    108.0
Name: new_cases, dtype: float64
95173 95180    446.0
Name: new_cases, dtype: float64
95174 95181    419.0
Name: new_cases, dtype: float64
95175 95182    386.0
Name: new_cases, dtype: float64
95176 95183    480.0
Name: new_cases, dtype: float64
95177 95184    416.0
Name: new_cases, dtype: float64
95178 95185    244.0
Name: new_cases, dtype: float64
95179 95186    112.0
Name: new_cases, dtype: float64
95180 95187    393.0
Name: new_cases, dtype: float64
95181 95188    594.0
Name: new_cases, dtype: float64
95182 95189    394.0
Name: new_cases, dtype: float64
95183 95190    420.0
Name: new_cases, dtype: float64
95184 95191    407.0
Name: new_cases, dtype: float64
95185 95192    249.0
Name: new_cases, dtype: float64
95186 95193    102.0
Name: new_cases, dtype: float64
95187 95194    508.0
Name: new_cases, dtype: float64
95188 95195    453.0
Name: new_cases, dtype: float64
95189 95196    464.0
Name: new_cases, dtype: float64
95190 95197    431.0
Name: new_cases, dtype: float64
95191 95198    451.0
Name: new_cases, dtype: float64
95192 95199    305.0
Name: new_cases, dtype: float64
95193 95200    159.0
Name: new_cases, dtype: float64
95194 95201    526.0
Name: new_cases, dtype: float64
95195 95202    466.0
Name: new_cases, dtype: float64
95196 95203    487.0
Name: new_cases, dtype: float64
95197 95204    444.0
Name: new_cases, dtype: float64
95198 95205    444.0
Name: new_cases, dtype: float64
95199 95206    246.0
Name: new_cases, dtype: float64
95200 95207    125.0
Name: new_cases, dtype: float64
95201 95208    569.0
Name: new_cases, dtype: float64
95202 95209    439.0
Name: new_cases, dtype: float64
95203 95210    511.0
Name: new_cases, dtype: float64
95204 95211    514.0
Name: new_cases, dtype: float64
95205 95212    491.0
Name: new_cases, dtype: float64
95206 95213    301.0
Name: new_cases, dtype: float64
95207 95214    97.0
Name: new_cases, dtype: float64
95208 95215    665.0
Name: new_cases, dtype: float64
95209 95216    676.0
Name: new_cases, dtype: float64
95210 95217    579.0
Name: new_cases, dtype: float64
95211 95218    581.0
Name: new_cases, dtype: float64
95212 95219    575.0
Name: new_cases, dtype: float64
95213 95220    365.0
Name: new_cases, dtype: float64
95214 95221    132.0
Name: new_cases, dtype: float64
95215 95222    696.0
Name: new_cases, dtype: float64
95216 95223    663.0
Name: new_cases, dtype: float64
95217 95224    635.0
Name: new_cases, dtype: float64
95218 95225    625.0
Name: new_cases, dtype: float64

95219 95226    740.0
Name: new_cases, dtype: float64
95220 95227    414.0
Name: new_cases, dtype: float64
95221 95228    175.0
Name: new_cases, dtype: float64
95222 95229    684.0
Name: new_cases, dtype: float64
95223 95230    703.0
Name: new_cases, dtype: float64
95224 95231    596.0
Name: new_cases, dtype: float64
95225 95232    587.0
Name: new_cases, dtype: float64
95226 95233    600.0
Name: new_cases, dtype: float64
95227 95234    364.0
Name: new_cases, dtype: float64
95228 95235    138.0
Name: new_cases, dtype: float64
95229 95236    720.0
Name: new_cases, dtype: float64
95230 95237    669.0
Name: new_cases, dtype: float64
95231 95238    600.0
Name: new_cases, dtype: float64
95232 95239    592.0
Name: new_cases, dtype: float64
95233 95240    507.0
Name: new_cases, dtype: float64
95234 95241    326.0
Name: new_cases, dtype: float64
95235 95242    102.0
Name: new_cases, dtype: float64
95236 95243    507.0
Name: new_cases, dtype: float64
95237 95244    493.0
Name: new_cases, dtype: float64
95238 95245    421.0
Name: new_cases, dtype: float64
95239 95246    363.0
Name: new_cases, dtype: float64
95240 95247    313.0
Name: new_cases, dtype: float64
95241 95248    294.0
Name: new_cases, dtype: float64
95242 95249    56.0
Name: new_cases, dtype: float64
95243 95250    373.0
Name: new_cases, dtype: float64
95244 95251    371.0
Name: new_cases, dtype: float64
95245 95252    360.0
Name: new_cases, dtype: float64
95246 95253    298.0
Name: new_cases, dtype: float64
95247 95254    314.0
Name: new_cases, dtype: float64
95248 95255    236.0
Name: new_cases, dtype: float64
95249 95256    58.0
Name: new_cases, dtype: float64
95250 95257    242.0
Name: new_cases, dtype: float64
95251 95258    268.0
Name: new_cases, dtype: float64
95252 95259    238.0
Name: new_cases, dtype: float64
95253 95260    35.0
Name: new_cases, dtype: float64
95254 95261    112.0
Name: new_cases, dtype: float64
95255 95262    127.0
Name: new_cases, dtype: float64
95256 95263    79.0
Name: new_cases, dtype: float64
95257 95264    397.0
Name: new_cases, dtype: float64
95258 95265    338.0
Name: new_cases, dtype: float64
95259 95266    333.0
Name: new_cases, dtype: float64
95260 95267    358.0
Name: new_cases, dtype: float64
95261 95268    363.0
Name: new_cases, dtype: float64
95262 95269    211.0
Name: new_cases, dtype: float64
95263 95270    90.0
Name: new_cases, dtype: float64
95264 95271    310.0
Name: new_cases, dtype: float64
95265 95272    385.0
Name: new_cases, dtype: float64
95266 95273    314.0
Name: new_cases, dtype: float64
95267 95274    336.0
Name: new_cases, dtype: float64
95268 95275    410.0
Name: new_cases, dtype: float64
95269 95276    240.0
Name: new_cases, dtype: float64
95270 95277    108.0
Name: new_cases, dtype: float64
95271 95278    394.0
Name: new_cases, dtype: float64
95272 95279    418.0
Name: new_cases, dtype: float64
95273 95280    395.0
Name: new_cases, dtype: float64
95274 95281    346.0
Name: new_cases, dtype: float64
95275 95282    426.0
Name: new_cases, dtype: float64
95276 95283    231.0
Name: new_cases, dtype: float64
95277 95284    104.0
Name: new_cases, dtype: float64
95278 95285    473.0
Name: new_cases, dtype: float64
95279 95286    386.0
Name: new_cases, dtype: float64
95280 95287    376.0
Name: new_cases, dtype: float64
95281 95288    400.0
Name: new_cases, dtype: float64
95282 95289    455.0
Name: new_cases, dtype: float64
95283 95290    270.0
Name: new_cases, dtype: float64
95284 95291    109.0
Name: new_cases, dtype: float64
95285 95292    476.0
Name: new_cases, dtype: float64
95286 95293    500.0
Name: new_cases, dtype: float64
95287 95294    468.0
Name: new_cases, dtype: float64
95288 95295    481.0
Name: new_cases, dtype: float64
95289 95296    439.0
Name: new_cases, dtype: float64
95290 95297    288.0
Name: new_cases, dtype: float64
95291 95298    86.0
Name: new_cases, dtype: float64
95292 95299    437.0
Name: new_cases, dtype: float64
95293 95300    522.0
Name: new_cases, dtype: float64
95294 95301    484.0
Name: new_cases, dtype: float64
95295 95302    551.0
Name: new_cases, dtype: float64
95296 95303    493.0
Name: new_cases, dtype: float64
95297 95304    452.0
Name: new_cases, dtype: float64
95298 95305    219.0
Name: new_cases, dtype: float64
95299 95306    690.0
Name: new_cases, dtype: float64
95300 95307    776.0
Name: new_cases, dtype: float64
95301 95308    789.0
Name: new_cases, dtype: float64
95302 95309    844.0
Name: new_cases, dtype: float64
95303 95310    951.0
Name: new_cases, dtype: float64
95304 95311    605.0
Name: new_cases, dtype: float64
95305 95312    247.0
Name: new_cases, dtype: float64
95306 95313    1177.0
Name: new_cases, dtype: float64
95307 95314    1279.0
Name: new_cases, dtype: float64
95308 95315    1336.0
Name: new_cases, dtype: float64
95309 95316    1250.0
Name: new_cases, dtype: float64
95310 95317    1566.0
Name: new_cases, dtype: float64
95311 95318    1057.0
Name: new_cases, dtype: float64
95312 95319    657.0
Name: new_cases, dtype: float64
95313 95320    1897.0
Name: new_cases, dtype: float64
95314 95321    2257.0
Name: new_cases, dtype: float64
95315 95322    2571.0
Name: new_cases, dtype: float64
95316 95323    2791.0
Name: new_cases, dtype: float64
95317 95324    2853.0
Name: new_cases, dtype: float64
95318 95325    2144.0
Name: new_cases, dtype: float64
95319 95326    1153.0
Name: new_cases, dtype: float64
95320 95327    3631.0
Name: new_cases, dtype: float64
95321 95328    3940.0
Name: new_cases, dtype: float64
95322 95329    1402.0
Name: new_cases, dtype: float64
95323 95330    1910.0
Name: new_cases, dtype: float64
95324 95331    5494.0
Name: new_cases, dtype: float64
95325 95332    4110.0
Name: new_cases, dtype: float64
95326 95333    2205.0
Name: new_cases, dtype: float64
95327 95334    6971.0
Name: new_cases, dtype: float64
95328 95335    9428.0
Name: new_cases, dtype: float64
95329 95336    8995.0
Name: new_cases, dtype: float64
95330 95337    9128.0
Name: new_cases, dtype: float64
95331 95338    7529.0
Name: new_cases, dtype: float64
95332 95339    6189.0
Name: new_cases, dtype: float64
95333 95340    4206.0
Name: new_cases, dtype: float64
95334 95341    8760.0
Name: new_cases, dtype: float64
95335 95342    10603.0
Name: new_cases, dtype: float64
95336 95343    12039.0
Name: new_cases, dtype: float64
95337 95344    11358.0
Name: new_cases, dtype: float64
95338 95345    10609.0
Name: new_cases, dtype: float64
95339 95346    8990.0
Name: new_cases, dtype: float64
95340 95347    5043.0
Name: new_cases, dtype: float64
95341 95348    9778.0
Name: new_cases, dtype: float64
95342 95349    9153.0
Name: new_cases, dtype: float64
95343 95350    10828.0
Name: new_cases, dtype: float64
95344 95351    10752.0
Name: new_cases, dtype: float64
95345 95352    10240.0
Name: new_cases, dtype: float64
95346 95353    7380.0
Name: new_cases, dtype: float64
95347 95354    3897.0
Name: new_cases, dtype: float64
95348 95355    9041.0
Name: new_cases, dtype: float64
95349 95356    9703.0
Name: new_cases, dtype: float64
95350 95357    9462.0
Name: new_cases, dtype: float64
95351 95358    8216.0
Name: new_cases, dtype: float64
95352 95359    6513.0
Name: new_cases, dtype: float64
95353 95360    4661.0
Name: new_cases, dtype: float64
95354 95361    2996.0
Name: new_cases, dtype: float64
95355 95362    7184.0
Name: new_cases, dtype: float64
95356 95363    8008.0
Name: new_cases, dtype: float64
95357 95364    7357.0
Name: new_cases, dtype: float64
95358 95365    6863.0
Name: new_cases, dtype: float64
95359 95366    6175.0
Name: new_cases, dtype: float64
95360 95367    3841.0
Name: new_cases, dtype: float64
95361 95368    2676.0
Name: new_cases, dtype: float64
95362 95369    4899.0
Name: new_cases, dtype: float64
95363 95370    6020.0
Name: new_cases, dtype: float64
95364 95371    5383.0
Name: new_cases, dtype: float64
95365 95372    4381.0
Name: new_cases, dtype: float64
95366 95373    4310.0
Name: new_cases, dtype: float64
95367 95374    3043.0
Name: new_cases, dtype: float64
95368 95375    1923.0
Name: new_cases, dtype: float64
95369 95376    3524.0
Name: new_cases, dtype: float64
95370 95377    3930.0
Name: new_cases, dtype: float64
95371 95378    3451.0
Name: new_cases, dtype: float64
95372 95379    2668.0
Name: new_cases, dtype: float64
95373 95380    3113.0
Name: new_cases, dtype: float64
95374 95381    1953.0
Name: new_cases, dtype: float64
95375 95382    917.0
Name: new_cases, dtype: float64
95376 95383    2785.0
Name: new_cases, dtype: float64
95377 95384    2642.0
Name: new_cases, dtype: float64
95378 95385    2432.0
Name: new_cases, dtype: float64
95379 95386    2412.0
Name: new_cases, dtype: float64
95380 95387    2291.0
Name: new_cases, dtype: float64
95381 95388    1555.0
Name: new_cases, dtype: float64
95382 95389    693.0
Name: new_cases, dtype: float64
95383 95390    1848.0
Name: new_cases, dtype: float64
95384 95391    1702.0
Name: new_cases, dtype: float64
95385 95392    1583.0
Name: new_cases, dtype: float64
95386 95393    1620.0
Name: new_cases, dtype: float64
95387 95394    1444.0
Name: new_cases, dtype: float64
95388 95395    734.0
Name: new_cases, dtype: float64
95389 95396    394.0
Name: new_cases, dtype: float64
95390 95397    1192.0
Name: new_cases, dtype: float64

95391 95398    1082.0
Name: new_cases, dtype: float64
95392 95399    1098.0
Name: new_cases, dtype: float64
95393 95400    936.0
Name: new_cases, dtype: float64
95394 95401    821.0
Name: new_cases, dtype: float64
95395 95402    504.0
Name: new_cases, dtype: float64
95396 95403    228.0
Name: new_cases, dtype: float64
95397 95404    676.0
Name: new_cases, dtype: float64
95398 95405    727.0
Name: new_cases, dtype: float64
95399 95406    668.0
Name: new_cases, dtype: float64
95400 95407    655.0
Name: new_cases, dtype: float64
95401 95408    515.0
Name: new_cases, dtype: float64
95402 95409    386.0
Name: new_cases, dtype: float64
95403 95410    169.0
Name: new_cases, dtype: float64
95404 95411    566.0
Name: new_cases, dtype: float64
95405 95412    581.0
Name: new_cases, dtype: float64
95406 95413    506.0
Name: new_cases, dtype: float64
95407 95414    437.0
Name: new_cases, dtype: float64
95408 95415    417.0
Name: new_cases, dtype: float64
95409 95416    269.0
Name: new_cases, dtype: float64
95410 95417    148.0
Name: new_cases, dtype: float64
95411 95418    499.0
Name: new_cases, dtype: float64
95412 95419    188.0
Name: new_cases, dtype: float64
95413 95420    255.0
Name: new_cases, dtype: float64
95414 95421    430.0
Name: new_cases, dtype: float64
95415 95422    424.0
Name: new_cases, dtype: float64
95416 95423    201.0
Name: new_cases, dtype: float64
95417 95424    101.0
Name: new_cases, dtype: float64
95418 95425    425.0
Name: new_cases, dtype: float64
95419 95426    398.0
Name: new_cases, dtype: float64
95420 95427    303.0
Name: new_cases, dtype: float64
95421 95428    216.0
Name: new_cases, dtype: float64
95422 95429    240.0
Name: new_cases, dtype: float64
95423 95430    185.0
Name: new_cases, dtype: float64
95424 95431    138.0
Name: new_cases, dtype: float64
95425 95432    260.0
Name: new_cases, dtype: float64
95426 95433    223.0
Name: new_cases, dtype: float64
95427 95434    191.0
Name: new_cases, dtype: float64
95428 95435    182.0
Name: new_cases, dtype: float64
95429 95436    168.0
Name: new_cases, dtype: float64
95430 95437    89.0
Name: new_cases, dtype: float64
95431 95438    55.0
Name: new_cases, dtype: float64
95432 95439    159.0
Name: new_cases, dtype: float64
95433 95440    151.0
Name: new_cases, dtype: float64
95434 95441    141.0
Name: new_cases, dtype: float64
95435 95442    123.0
Name: new_cases, dtype: float64
95436 95443    132.0
Name: new_cases, dtype: float64
95437 95444    69.0
Name: new_cases, dtype: float64
95438 95445    45.0
Name: new_cases, dtype: float64
95439 95446    120.0
Name: new_cases, dtype: float64
95440 95447    148.0
Name: new_cases, dtype: float64
95441 95448    94.0
Name: new_cases, dtype: float64
95442 95449    72.0
Name: new_cases, dtype: float64
95443 95450    125.0
Name: new_cases, dtype: float64
95444 95451    93.0
Name: new_cases, dtype: float64
95445 95452    53.0
Name: new_cases, dtype: float64
95446 95453    157.0
Name: new_cases, dtype: float64
95447 95454    130.0
Name: new_cases, dtype: float64
95448 95455    115.0
Name: new_cases, dtype: float64
95449 95456    154.0
Name: new_cases, dtype: float64
95450 95457    116.0
Name: new_cases, dtype: float64
95451 95458    84.0
Name: new_cases, dtype: float64
95452 95459    53.0
Name: new_cases, dtype: float64
95453 95460    132.0
Name: new_cases, dtype: float64
95454 95461    171.0
Name: new_cases, dtype: float64
95455 95462    135.0
Name: new_cases, dtype: float64
95456 95463    151.0
Name: new_cases, dtype: float64
95457 95464    127.0
Name: new_cases, dtype: float64
95458 95465    90.0
Name: new_cases, dtype: float64
95459 95466    52.0
Name: new_cases, dtype: float64
95460 95467    158.0
Name: new_cases, dtype: float64
95461 95468    145.0
Name: new_cases, dtype: float64
95462 95469    146.0
Name: new_cases, dtype: float64
95463 95470    175.0
Name: new_cases, dtype: float64
95464 95471    113.0
Name: new_cases, dtype: float64
95465 95472    102.0
Name: new_cases, dtype: float64
95466 95473    62.0
Name: new_cases, dtype: float64
95467 95474    219.0
Name: new_cases, dtype: float64
95468 95475    221.0
Name: new_cases, dtype: float64
95469 95476    205.0
Name: new_cases, dtype: float64
95470 95477    209.0
Name: new_cases, dtype: float64
95471 95478    230.0
Name: new_cases, dtype: float64
95472 95479    186.0
Name: new_cases, dtype: float64
95473 95480    102.0
Name: new_cases, dtype: float64
95474 95481    381.0
Name: new_cases, dtype: float64
95475 95482    427.0
Name: new_cases, dtype: float64
95476 95483    475.0
Name: new_cases, dtype: float64
95477 95484    654.0
Name: new_cases, dtype: float64
95478 95485    734.0
Name: new_cases, dtype: float64
95479 95486    532.0
Name: new_cases, dtype: float64
95480 95487    291.0
Name: new_cases, dtype: float64
95481 95488    1184.0
Name: new_cases, dtype: float64
95482 95489    1504.0
Name: new_cases, dtype: float64
95483 95490    1960.0
Name: new_cases, dtype: float64
95484 95491    2034.0
Name: new_cases, dtype: float64
95485 95492    2328.0
Name: new_cases, dtype: float64
95486 95493    1357.0
Name: new_cases, dtype: float64
95487 95494    885.0
Name: new_cases, dtype: float64
95488 95495    4299.0
Name: new_cases, dtype: float64
95489 95496    5618.0
Name: new_cases, dtype: float64
95490 95497    6050.0
Name: new_cases, dtype: float64
95491 95498    6428.0
Name: new_cases, dtype: float64
95492 95499    7064.0
Name: new_cases, dtype: float64
95493 Series([], Name: new_cases, dtype: float64)
95494 Series([], Name: new_cases, dtype: float64)
95495 Series([], Name: new_cases, dtype: float64)
95496 Series([], Name: new_cases, dtype: float64)
95497 94822    1.0
Name: new_cases, dtype: float64
95498 94823    0.0
Name: new_cases, dtype: float64
95499 94824    0.0
Name: new_cases, dtype: float64
98338 98345    44.0
Name: new_cases, dtype: float64
98339 98346    46.0
Name: new_cases, dtype: float64
98340 98347    60.0
Name: new_cases, dtype: float64
98341 98348    77.0
Name: new_cases, dtype: float64
98342 98349    56.0
Name: new_cases, dtype: float64
98343 98350    61.0
Name: new_cases, dtype: float64
98344 98351    121.0
Name: new_cases, dtype: float64
98345 98352    0.0
Name: new_cases, dtype: float64
98346 98353    301.0
Name: new_cases, dtype: float64
98347 98354    155.0
Name: new_cases, dtype: float64
98348 98355    176.0
Name: new_cases, dtype: float64
98349 98356    278.0
Name: new_cases, dtype: float64
98350 98357    292.0
Name: new_cases, dtype: float64
98351 98358    346.0
Name: new_cases, dtype: float64
98352 98359    409.0
Name: new_cases, dtype: float64
98353 98360    535.0
Name: new_cases, dtype: float64
98354 98361    637.0
Name: new_cases, dtype: float64
98355 98362    573.0
Name: new_cases, dtype: float64
98356 98363    546.0
Name: new_cases, dtype: float64
98357 98364    811.0
Name: new_cases, dtype: float64
98358 98365    853.0
Name: new_cases, dtype: float64
98359 98366    1019.0
Name: new_cases, dtype: float64
98360 98367    1172.0
Name: new_cases, dtype: float64
98361 98368    1159.0
Name: new_cases, dtype: float64
98362 98369    1107.0
Name: new_cases, dtype: float64
98363 98370    884.0
Name: new_cases, dtype: float64
98364 98371    845.0
Name: new_cases, dtype: float64
98365 98372    1029.0
Name: new_cases, dtype: float64
98366 98373    1085.0
Name: new_cases, dtype: float64
98367 98374    1031.0
Name: new_cases, dtype: float64
98368 98375    904.0
Name: new_cases, dtype: float64
98369 98376    1226.0
Name: new_cases, dtype: float64
98370 98377    964.0
Name: new_cases, dtype: float64
98371 98378    780.0
Name: new_cases, dtype: float64
98372 98379    969.0
Name: new_cases, dtype: float64
98373 98380    1216.0
Name: new_cases, dtype: float64
98374 98381    1342.0
Name: new_cases, dtype: float64
98375 98382    1316.0
Name: new_cases, dtype: float64
98376 98383    1174.0
Name: new_cases, dtype: float64
98377 98384    964.0
Name: new_cases, dtype: float64
98378 98385    870.0
Name: new_cases, dtype: float64
98379 98386    735.0
Name: new_cases, dtype: float64
98380 98387    1065.0
Name: new_cases, dtype: float64
98381 98388    1235.0
Name: new_cases, dtype: float64
98382 98389    1147.0
Name: new_cases, dtype: float64
98383 98390    1069.0
Name: new_cases, dtype: float64
98384 98391    750.0
Name: new_cases, dtype: float64
98385 98392    729.0
Name: new_cases, dtype: float64
98386 98393    712.0
Name: new_cases, dtype: float64
98387 98394    889.0
Name: new_cases, dtype: float64
98388 98395    806.0
Name: new_cases, dtype: float64
98389 98396    655.0
Name: new_cases, dtype: float64
98390 98397    656.0
Name: new_cases, dtype: float64
98391 98398    400.0
Name: new_cases, dtype: float64
98392 98399    172.0
Name: new_cases, dtype: float64
98393 98400    386.0
Name: new_cases, dtype: float64
98394 98401    514.0
Name: new_cases, dtype: float64
98395 98402    476.0
Name: new_cases, dtype: float64
98396 98403    445.0
Name: new_cases, dtype: float64
98397 98404    335.0
Name: new_cases, dtype: float64
98398 98405    199.0
Name: new_cases, dtype: float64
98399 98406    317.0
Name: new_cases, dtype: float64
98400 98407    232.0
Name: new_cases, dtype: float64
98401 98408    455.0
Name: new_cases, dtype: float64
98402 98409    319.0
Name: new_cases, dtype: float64

98403 98410    289.0
Name: new_cases, dtype: float64
98404 98411    245.0
Name: new_cases, dtype: float64
98405 98412    161.0
Name: new_cases, dtype: float64
98406 98413    196.0
Name: new_cases, dtype: float64
98407 98414    227.0
Name: new_cases, dtype: float64
98408 98415    270.0
Name: new_cases, dtype: float64
98409 98416    200.0
Name: new_cases, dtype: float64
98410 98417    190.0
Name: new_cases, dtype: float64
98411 98418    125.0
Name: new_cases, dtype: float64
98412 98419    146.0
Name: new_cases, dtype: float64
98413 98420    108.0
Name: new_cases, dtype: float64
98414 98421    198.0
Name: new_cases, dtype: float64
98415 98422    253.0
Name: new_cases, dtype: float64
98416 98423    188.0
Name: new_cases, dtype: float64
98417 98424    176.0
Name: new_cases, dtype: float64
98418 98425    172.0
Name: new_cases, dtype: float64
98419 98426    209.0
Name: new_cases, dtype: float64
98420 98427    133.0
Name: new_cases, dtype: float64
98421 98428    190.0
Name: new_cases, dtype: float64
98422 98429    182.0
Name: new_cases, dtype: float64
98423 98430    176.0
Name: new_cases, dtype: float64
98424 98431    131.0
Name: new_cases, dtype: float64
98425 98432    185.0
Name: new_cases, dtype: float64
98426 98433    103.0
Name: new_cases, dtype: float64
98427 98434    102.0
Name: new_cases, dtype: float64
98428 98435    86.0
Name: new_cases, dtype: float64
98429 98436    209.0
Name: new_cases, dtype: float64
98430 98437    210.0
Name: new_cases, dtype: float64
98431 98438    183.0
Name: new_cases, dtype: float64
98432 98439    239.0
Name: new_cases, dtype: float64
98433 98440    165.0
Name: new_cases, dtype: float64
98434 98441    164.0
Name: new_cases, dtype: float64
98435 98442    184.0
Name: new_cases, dtype: float64
98436 98443    164.0
Name: new_cases, dtype: float64
98437 98444    210.0
Name: new_cases, dtype: float64
98438 98445    179.0
Name: new_cases, dtype: float64
98439 98446    143.0
Name: new_cases, dtype: float64
98440 98447    165.0
Name: new_cases, dtype: float64
98441 98448    139.0
Name: new_cases, dtype: float64
98442 98449    117.0
Name: new_cases, dtype: float64
98443 98450    115.0
Name: new_cases, dtype: float64
98444 98451    107.0
Name: new_cases, dtype: float64
98445 98452    76.0
Name: new_cases, dtype: float64
98446 98453    91.0
Name: new_cases, dtype: float64
98447 98454    65.0
Name: new_cases, dtype: float64
98448 98455    64.0
Name: new_cases, dtype: float64
98449 98456    82.0
Name: new_cases, dtype: float64
98450 98457    110.0
Name: new_cases, dtype: float64
98451 98458    91.0
Name: new_cases, dtype: float64
98452 98459    69.0
Name: new_cases, dtype: float64
98453 98460    73.0
Name: new_cases, dtype: float64
98454 98461    76.0
Name: new_cases, dtype: float64
98455 98462    50.0
Name: new_cases, dtype: float64
98456 98463    62.0
Name: new_cases, dtype: float64
98457 98464    77.0
Name: new_cases, dtype: float64
98458 98465    75.0
Name: new_cases, dtype: float64
98459 98466    62.0
Name: new_cases, dtype: float64
98460 98467    73.0
Name: new_cases, dtype: float64
98461 98468    36.0
Name: new_cases, dtype: float64
98462 98469    37.0
Name: new_cases, dtype: float64
98463 98470    52.0
Name: new_cases, dtype: float64
98464 98471    52.0
Name: new_cases, dtype: float64
98465 98472    42.0
Name: new_cases, dtype: float64
98466 98473    81.0
Name: new_cases, dtype: float64
98467 98474    101.0
Name: new_cases, dtype: float64
98468 98475    71.0
Name: new_cases, dtype: float64
98469 98476    53.0
Name: new_cases, dtype: float64
98470 98477    106.0
Name: new_cases, dtype: float64
98471 98478    99.0
Name: new_cases, dtype: float64
98472 98479    104.0
Name: new_cases, dtype: float64
98473 98480    127.0
Name: new_cases, dtype: float64
98474 98481    144.0
Name: new_cases, dtype: float64
98475 98482    185.0
Name: new_cases, dtype: float64
98476 98483    163.0
Name: new_cases, dtype: float64
98477 98484    168.0
Name: new_cases, dtype: float64
98478 98485    165.0
Name: new_cases, dtype: float64
98479 98486    194.0
Name: new_cases, dtype: float64
98480 98487    146.0
Name: new_cases, dtype: float64
98481 98488    294.0
Name: new_cases, dtype: float64
98482 98489    146.0
Name: new_cases, dtype: float64
98483 98490    223.0
Name: new_cases, dtype: float64
98484 98491    248.0
Name: new_cases, dtype: float64
98485 98492    353.0
Name: new_cases, dtype: float64
98486 98493    340.0
Name: new_cases, dtype: float64
98487 98494    431.0
Name: new_cases, dtype: float64
98488 98495    384.0
Name: new_cases, dtype: float64
98489 98496    376.0
Name: new_cases, dtype: float64
98490 98497    485.0
Name: new_cases, dtype: float64
98491 98498    432.0
Name: new_cases, dtype: float64
98492 98499    621.0
Name: new_cases, dtype: float64
98493 98500    519.0
Name: new_cases, dtype: float64
98494 98501    487.0
Name: new_cases, dtype: float64
98495 98502    589.0
Name: new_cases, dtype: float64
98496 98503    630.0
Name: new_cases, dtype: float64
98497 98504    246.0
Name: new_cases, dtype: float64
98498 98505    1246.0
Name: new_cases, dtype: float64
98499 98506    592.0
Name: new_cases, dtype: float64
98500 98507    642.0
Name: new_cases, dtype: float64
98501 98508    686.0
Name: new_cases, dtype: float64
98502 98509    524.0
Name: new_cases, dtype: float64
98503 98510    491.0
Name: new_cases, dtype: float64
98504 98511    496.0
Name: new_cases, dtype: float64
98505 98512    567.0
Name: new_cases, dtype: float64
98506 98513    534.0
Name: new_cases, dtype: float64
98507 98514    535.0
Name: new_cases, dtype: float64
98508 98515    523.0
Name: new_cases, dtype: float64
98509 98516    485.0
Name: new_cases, dtype: float64
98510 98517    586.0
Name: new_cases, dtype: float64
98511 98518    415.0
Name: new_cases, dtype: float64
98512 98519    605.0
Name: new_cases, dtype: float64
98513 98520    512.0
Name: new_cases, dtype: float64
98514 98521    507.0
Name: new_cases, dtype: float64
98515 98522    501.0
Name: new_cases, dtype: float64
98516 98523    524.0
Name: new_cases, dtype: float64
98517 98524    543.0
Name: new_cases, dtype: float64
98518 98525    468.0
Name: new_cases, dtype: float64
98519 98526    747.0
Name: new_cases, dtype: float64
98520 98527    610.0
Name: new_cases, dtype: float64
98521 98528    751.0
Name: new_cases, dtype: float64
98522 98529    654.0
Name: new_cases, dtype: float64
98523 98530    925.0
Name: new_cases, dtype: float64
98524 98531    802.0
Name: new_cases, dtype: float64
98525 98532    975.0
Name: new_cases, dtype: float64
98526 98533    1143.0
Name: new_cases, dtype: float64
98527 98534    823.0
Name: new_cases, dtype: float64
98528 98535    1271.0
Name: new_cases, dtype: float64
98529 98536    1233.0
Name: new_cases, dtype: float64
98530 98537    1103.0
Name: new_cases, dtype: float64
98531 98538    1300.0
Name: new_cases, dtype: float64
98532 98539    1379.0
Name: new_cases, dtype: float64
98533 98540    1550.0
Name: new_cases, dtype: float64
98534 98541    1761.0
Name: new_cases, dtype: float64
98535 98542    1983.0
Name: new_cases, dtype: float64
98536 98543    1897.0
Name: new_cases, dtype: float64
98537 98544    1844.0
Name: new_cases, dtype: float64
98538 98545    2224.0
Name: new_cases, dtype: float64
98539 98546    2248.0
Name: new_cases, dtype: float64
98540 98547    2379.0
Name: new_cases, dtype: float64
98541 98548    2546.0
Name: new_cases, dtype: float64
98542 98549    2786.0
Name: new_cases, dtype: float64
98543 98550    2719.0
Name: new_cases, dtype: float64
98544 98551    3006.0
Name: new_cases, dtype: float64
98545 98552    2915.0
Name: new_cases, dtype: float64
98546 98553    3025.0
Name: new_cases, dtype: float64
98547 98554    3302.0
Name: new_cases, dtype: float64
98548 98555    3253.0
Name: new_cases, dtype: float64
98549 98556    3831.0
Name: new_cases, dtype: float64
98550 98557    3971.0
Name: new_cases, dtype: float64
98551 98558    4004.0
Name: new_cases, dtype: float64
98552 98559    4586.0
Name: new_cases, dtype: float64
98553 98560    4531.0
Name: new_cases, dtype: float64
98554 98561    4998.0
Name: new_cases, dtype: float64
98555 98562    5823.0
Name: new_cases, dtype: float64
98556 98563    5975.0
Name: new_cases, dtype: float64
98557 98564    6503.0
Name: new_cases, dtype: float64
98558 98565    6376.0
Name: new_cases, dtype: float64
98559 98566    6845.0
Name: new_cases, dtype: float64
98560 98567    7387.0
Name: new_cases, dtype: float64
98561 98568    7297.0
Name: new_cases, dtype: float64
98562 98569    7799.0
Name: new_cases, dtype: float64

98563 98570    7993.0
Name: new_cases, dtype: float64
98564 98571    8117.0
Name: new_cases, dtype: float64
98565 98572    8186.0
Name: new_cases, dtype: float64
98566 98573    7995.0
Name: new_cases, dtype: float64
98567 98574    8165.0
Name: new_cases, dtype: float64
98568 98575    8756.0
Name: new_cases, dtype: float64
98569 98576    9271.0
Name: new_cases, dtype: float64
98570 98577    10003.0
Name: new_cases, dtype: float64
98571 98578    8655.0
Name: new_cases, dtype: float64
98572 98579    10206.0
Name: new_cases, dtype: float64
98573 98580    10348.0
Name: new_cases, dtype: float64
98574 98581    10295.0
Name: new_cases, dtype: float64
98575 98582    8115.0
Name: new_cases, dtype: float64
98576 98583    10264.0
Name: new_cases, dtype: float64
98577 98584    11136.0
Name: new_cases, dtype: float64
98578 98585    9808.0
Name: new_cases, dtype: float64
98579 98586    8688.0
Name: new_cases, dtype: float64
98580 98587    8299.0
Name: new_cases, dtype: float64
98581 98588    7758.0
Name: new_cases, dtype: float64
98582 98589    7644.0
Name: new_cases, dtype: float64
98583 98590    6972.0
Name: new_cases, dtype: float64
98584 98591    7242.0
Name: new_cases, dtype: float64
98585 98592    6680.0
Name: new_cases, dtype: float64
98586 98593    5668.0
Name: new_cases, dtype: float64
98587 98594    4686.0
Name: new_cases, dtype: float64
98588 98595    4679.0
Name: new_cases, dtype: float64
98589 98596    5409.0
Name: new_cases, dtype: float64
98590 98597    5638.0
Name: new_cases, dtype: float64
98591 98598    6100.0
Name: new_cases, dtype: float64
98592 98599    5914.0
Name: new_cases, dtype: float64
98593 98600    5423.0
Name: new_cases, dtype: float64
98594 98601    4836.0
Name: new_cases, dtype: float64
98595 98602    4317.0
Name: new_cases, dtype: float64
98596 98603    4619.0
Name: new_cases, dtype: float64
98597 98604    5654.0
Name: new_cases, dtype: float64
98598 98605    5943.0
Name: new_cases, dtype: float64
98599 98606    6083.0
Name: new_cases, dtype: float64
98600 98607    5399.0
Name: new_cases, dtype: float64
98601 98608    5175.0
Name: new_cases, dtype: float64
98602 98609    3934.0
Name: new_cases, dtype: float64
98603 98610    4925.0
Name: new_cases, dtype: float64
98604 98611    4475.0
Name: new_cases, dtype: float64
98605 98612    5755.0
Name: new_cases, dtype: float64
98606 98613    4468.0
Name: new_cases, dtype: float64
98607 98614    5585.0
Name: new_cases, dtype: float64
98608 98615    4572.0
Name: new_cases, dtype: float64
98609 98616    4048.0
Name: new_cases, dtype: float64
98610 98617    4924.0
Name: new_cases, dtype: float64
98611 98618    5639.0
Name: new_cases, dtype: float64
98612 98619    5889.0
Name: new_cases, dtype: float64
98613 98620    6540.0
Name: new_cases, dtype: float64
98614 98621    6779.0
Name: new_cases, dtype: float64
98615 98622    7083.0
Name: new_cases, dtype: float64
98616 98623    6152.0
Name: new_cases, dtype: float64
98617 98624    6552.0
Name: new_cases, dtype: float64
98618 98625    8736.0
Name: new_cases, dtype: float64
98619 98626    8862.0
Name: new_cases, dtype: float64
98620 98627    9087.0
Name: new_cases, dtype: float64
98621 98628    9884.0
Name: new_cases, dtype: float64
98622 98629    8474.0
Name: new_cases, dtype: float64
98623 98630    6653.0
Name: new_cases, dtype: float64
98624 98631    11176.0
Name: new_cases, dtype: float64
98625 98632    12797.0
Name: new_cases, dtype: float64
98626 98633    11952.0
Name: new_cases, dtype: float64
98627 98634    12225.0
Name: new_cases, dtype: float64
98628 98635    13037.0
Name: new_cases, dtype: float64
98629 98636    11178.0
Name: new_cases, dtype: float64
98630 98637    9834.0
Name: new_cases, dtype: float64
98631 98638    10396.0
Name: new_cases, dtype: float64
98632 98639    11514.0
Name: new_cases, dtype: float64
98633 98640    11495.0
Name: new_cases, dtype: float64
98634 98641    9848.0
Name: new_cases, dtype: float64
98635 98642    9080.0
Name: new_cases, dtype: float64
98636 98643    7433.0
Name: new_cases, dtype: float64
98637 98644    7514.0
Name: new_cases, dtype: float64
98638 98645    9409.0
Name: new_cases, dtype: float64
98639 98646    9703.0
Name: new_cases, dtype: float64
98640 98647    8185.0
Name: new_cases, dtype: float64
98641 98648    8605.0
Name: new_cases, dtype: float64
98642 98649    7398.0
Name: new_cases, dtype: float64
98643 98650    6566.0
Name: new_cases, dtype: float64
98644 98651    6377.0
Name: new_cases, dtype: float64
98645 98652    7107.0
Name: new_cases, dtype: float64
98646 98653    9646.0
Name: new_cases, dtype: float64
98647 98654    8147.0
Name: new_cases, dtype: float64
98648 98655    7321.0
Name: new_cases, dtype: float64
98649 98656    6613.0
Name: new_cases, dtype: float64
98650 98657    5436.0
Name: new_cases, dtype: float64
98651 98658    4886.0
Name: new_cases, dtype: float64
98652 98659    6104.0
Name: new_cases, dtype: float64
98653 98660    6488.0
Name: new_cases, dtype: float64
98654 98661    6021.0
Name: new_cases, dtype: float64
98655 98662    5260.0
Name: new_cases, dtype: float64
98656 98663    5613.0
Name: new_cases, dtype: float64
98657 98664    4767.0
Name: new_cases, dtype: float64
98658 98665    4280.0
Name: new_cases, dtype: float64
98659 98666    5556.0
Name: new_cases, dtype: float64
98660 98667    5779.0
Name: new_cases, dtype: float64
98661 98668    5760.0
Name: new_cases, dtype: float64
98662 98669    5414.0
Name: new_cases, dtype: float64
98663 98670    4920.0
Name: new_cases, dtype: float64
98664 98671    4022.0
Name: new_cases, dtype: float64
98665 98672    3926.0
Name: new_cases, dtype: float64
98666 98673    4766.0
Name: new_cases, dtype: float64
98667 98674    4674.0
Name: new_cases, dtype: float64
98668 98675    4375.0
Name: new_cases, dtype: float64
98669 98676    4179.0
Name: new_cases, dtype: float64
98670 98677    3700.0
Name: new_cases, dtype: float64
98671 98678    3205.0
Name: new_cases, dtype: float64
98672 98679    3576.0
Name: new_cases, dtype: float64
98673 98680    4027.0
Name: new_cases, dtype: float64
98674 98681    4205.0
Name: new_cases, dtype: float64
98675 98682    4331.0
Name: new_cases, dtype: float64
98676 98683    4082.0
Name: new_cases, dtype: float64
98677 98684    3934.0
Name: new_cases, dtype: float64
98678 98685    2231.0
Name: new_cases, dtype: float64
98679 98686    1758.0
Name: new_cases, dtype: float64
98680 98687    3203.0
Name: new_cases, dtype: float64
98681 98688    4407.0
Name: new_cases, dtype: float64
98682 98689    4347.0
Name: new_cases, dtype: float64
98683 98690    4197.0
Name: new_cases, dtype: float64
98684 98691    3451.0
Name: new_cases, dtype: float64
98685 98692    2813.0
Name: new_cases, dtype: float64
98686 98693    2713.0
Name: new_cases, dtype: float64
98687 98694    3369.0
Name: new_cases, dtype: float64
98688 98695    4524.0
Name: new_cases, dtype: float64
98689 98696    4732.0
Name: new_cases, dtype: float64
98690 98697    4565.0
Name: new_cases, dtype: float64
98691 98698    4674.0
Name: new_cases, dtype: float64
98692 98699    4171.0
Name: new_cases, dtype: float64
98693 98700    3802.0
Name: new_cases, dtype: float64
98694 98701    4365.0
Name: new_cases, dtype: float64
98695 98702    5012.0
Name: new_cases, dtype: float64
98696 98703    5115.0
Name: new_cases, dtype: float64
98697 98704    4939.0
Name: new_cases, dtype: float64
98698 98705    4671.0
Name: new_cases, dtype: float64
98699 98706    3765.0
Name: new_cases, dtype: float64
98700 98707    3982.0
Name: new_cases, dtype: float64
98701 98708    5001.0
Name: new_cases, dtype: float64
98702 98709    4115.0
Name: new_cases, dtype: float64
98703 98710    4670.0
Name: new_cases, dtype: float64
98704 98711    5339.0
Name: new_cases, dtype: float64
98705 98712    4526.0
Name: new_cases, dtype: float64
98706 98713    3838.0
Name: new_cases, dtype: float64
98707 98714    4295.0
Name: new_cases, dtype: float64
98708 98715    5273.0
Name: new_cases, dtype: float64
98709 98716    5323.0
Name: new_cases, dtype: float64
98710 98717    6030.0
Name: new_cases, dtype: float64
98711 98718    6396.0
Name: new_cases, dtype: float64
98712 98719    5974.0
Name: new_cases, dtype: float64
98713 98720    5472.0
Name: new_cases, dtype: float64
98714 98721    4905.0
Name: new_cases, dtype: float64
98715 98722    5929.0
Name: new_cases, dtype: float64
98716 98723    6125.0
Name: new_cases, dtype: float64
98717 98724    7381.0
Name: new_cases, dtype: float64
98718 98725    7595.0
Name: new_cases, dtype: float64
98719 98726    6965.0
Name: new_cases, dtype: float64
98720 98727    6264.0
Name: new_cases, dtype: float64
98721 98728    5564.0
Name: new_cases, dtype: float64
98722 98729    7585.0
Name: new_cases, dtype: float64
98723 98730    7706.0
Name: new_cases, dtype: float64
98724 98731    7562.0
Name: new_cases, dtype: float64
98725 98732    8810.0
Name: new_cases, dtype: float64
98726 98733    7430.0
Name: new_cases, dtype: float64
98727 98734    6722.0
Name: new_cases, dtype: float64
98728 98735    5828.0
Name: new_cases, dtype: float64
98729 98736    7646.0
Name: new_cases, dtype: float64
98730 98737    7831.0
Name: new_cases, dtype: float64
98731 98738    7253.0
Name: new_cases, dtype: float64
98732 98739    7628.0
Name: new_cases, dtype: float64
98733 98740    6822.0
Name: new_cases, dtype: float64
98734 98741    5320.0
Name: new_cases, dtype: float64

98735 98742    5554.0
Name: new_cases, dtype: float64
98736 98743    6356.0
Name: new_cases, dtype: float64
98737 98744    7783.0
Name: new_cases, dtype: float64
98738 98745    7643.0
Name: new_cases, dtype: float64
98739 98746    7679.0
Name: new_cases, dtype: float64
98740 98747    8218.0
Name: new_cases, dtype: float64
98741 98748    6675.0
Name: new_cases, dtype: float64
98742 98749    6688.0
Name: new_cases, dtype: float64
98743 98750    5394.0
Name: new_cases, dtype: float64
98744 98751    8737.0
Name: new_cases, dtype: float64
98745 98752    8901.0
Name: new_cases, dtype: float64
98746 98753    8288.0
Name: new_cases, dtype: float64
98747 98754    8505.0
Name: new_cases, dtype: float64
98748 98755    7119.0
Name: new_cases, dtype: float64
98749 98756    6826.0
Name: new_cases, dtype: float64
98750 98757    8472.0
Name: new_cases, dtype: float64
98751 98758    9611.0
Name: new_cases, dtype: float64
98752 98759    9212.0
Name: new_cases, dtype: float64
98753 98760    8061.0
Name: new_cases, dtype: float64
98754 98761    8013.0
Name: new_cases, dtype: float64
98755 98762    6205.0
Name: new_cases, dtype: float64
98756 98763    5337.0
Name: new_cases, dtype: float64
98757 98764    8655.0
Name: new_cases, dtype: float64
98758 98765    7271.0
Name: new_cases, dtype: float64
98759 98766    7762.0
Name: new_cases, dtype: float64
98760 98767    5755.0
Name: new_cases, dtype: float64
98761 98768    5508.0
Name: new_cases, dtype: float64
98762 98769    9197.0
Name: new_cases, dtype: float64
98763 98770    7725.0
Name: new_cases, dtype: float64
98764 98771    7276.0
Name: new_cases, dtype: float64
98765 98772    6793.0
Name: new_cases, dtype: float64
98766 98773    7484.0
Name: new_cases, dtype: float64
98767 98774    7409.0
Name: new_cases, dtype: float64
98768 98775    6553.0
Name: new_cases, dtype: float64
98769 98776    5861.0
Name: new_cases, dtype: float64
98770 98777    5523.0
Name: new_cases, dtype: float64
98771 98778    6360.0
Name: new_cases, dtype: float64
98772 98779    6013.0
Name: new_cases, dtype: float64
98773 98780    5520.0
Name: new_cases, dtype: float64
98774 98781    4451.0
Name: new_cases, dtype: float64
98775 98782    4436.0
Name: new_cases, dtype: float64
98776 98783    2839.0
Name: new_cases, dtype: float64
98777 98784    5341.0
Name: new_cases, dtype: float64
98778 98785    4568.0
Name: new_cases, dtype: float64
98779 98786    4652.0
Name: new_cases, dtype: float64
98780 98787    4158.0
Name: new_cases, dtype: float64
98781 98788    3162.0
Name: new_cases, dtype: float64
98782 98789    3432.0
Name: new_cases, dtype: float64
98783 98790    2690.0
Name: new_cases, dtype: float64
98784 98791    2482.0
Name: new_cases, dtype: float64
98785 98792    2762.0
Name: new_cases, dtype: float64
98786 98793    3338.0
Name: new_cases, dtype: float64
98787 98794    3859.0
Name: new_cases, dtype: float64
98788 98795    3381.0
Name: new_cases, dtype: float64
98789 98796    2722.0
Name: new_cases, dtype: float64
98790 98797    2042.0
Name: new_cases, dtype: float64
98791 98798    2339.0
Name: new_cases, dtype: float64
98792 98799    2502.0
Name: new_cases, dtype: float64
98793 98800    2750.0
Name: new_cases, dtype: float64
98794 98801    2388.0
Name: new_cases, dtype: float64
98795 98802    2138.0
Name: new_cases, dtype: float64
98796 98803    1538.0
Name: new_cases, dtype: float64
98797 98804    1382.0
Name: new_cases, dtype: float64
98798 98805    1430.0
Name: new_cases, dtype: float64
98799 98806    1722.0
Name: new_cases, dtype: float64
98800 98807    1569.0
Name: new_cases, dtype: float64
98801 98808    1384.0
Name: new_cases, dtype: float64
98802 98809    1209.0
Name: new_cases, dtype: float64
98803 98810    1041.0
Name: new_cases, dtype: float64
98804 98811    862.0
Name: new_cases, dtype: float64
98805 98812    1043.0
Name: new_cases, dtype: float64
98806 98813    1027.0
Name: new_cases, dtype: float64
98807 98814    1071.0
Name: new_cases, dtype: float64
98808 98815    891.0
Name: new_cases, dtype: float64
98809 98816    692.0
Name: new_cases, dtype: float64
98810 98817    701.0
Name: new_cases, dtype: float64
98811 98818    564.0
Name: new_cases, dtype: float64
98812 98819    693.0
Name: new_cases, dtype: float64
98813 98820    655.0
Name: new_cases, dtype: float64
98814 98821    709.0
Name: new_cases, dtype: float64
98815 98822    648.0
Name: new_cases, dtype: float64
98816 98823    552.0
Name: new_cases, dtype: float64
98817 98824    498.0
Name: new_cases, dtype: float64
98818 98825    569.0
Name: new_cases, dtype: float64
98819 98826    539.0
Name: new_cases, dtype: float64
98820 98827    638.0
Name: new_cases, dtype: float64
98821 98828    825.0
Name: new_cases, dtype: float64
98822 98829    941.0
Name: new_cases, dtype: float64
98823 98830    1127.0
Name: new_cases, dtype: float64
98824 98831    1215.0
Name: new_cases, dtype: float64
98825 98832    1526.0
Name: new_cases, dtype: float64
98826 98833    2212.0
Name: new_cases, dtype: float64
98827 98834    3648.0
Name: new_cases, dtype: float64
98828 98835    5432.0
Name: new_cases, dtype: float64
98829 98836    6926.0
Name: new_cases, dtype: float64
98830 98837    10288.0
Name: new_cases, dtype: float64
98831 98838    9318.0
Name: new_cases, dtype: float64
98832 98839    8444.0
Name: new_cases, dtype: float64
98833 98840    7830.0
Name: new_cases, dtype: float64
98834 98841    10432.0
Name: new_cases, dtype: float64
98835 98842    10979.0
Name: new_cases, dtype: float64
98836 98843    11297.0
Name: new_cases, dtype: float64
98837 98844    11041.0
Name: new_cases, dtype: float64
98838 98845    10135.0
Name: new_cases, dtype: float64
98839 98846    8887.0
Name: new_cases, dtype: float64
98840 98847    6709.0
Name: new_cases, dtype: float64
98841 98848    6905.0
Name: new_cases, dtype: float64
98842 98849    6236.0
Name: new_cases, dtype: float64
98843 98850    6395.0
Name: new_cases, dtype: float64
98844 98851    5278.0
Name: new_cases, dtype: float64
98845 98852    4584.0
Name: new_cases, dtype: float64
98846 98853    3867.0
Name: new_cases, dtype: float64
98847 98854    3963.0
Name: new_cases, dtype: float64
98848 98855    3469.0
Name: new_cases, dtype: float64
98849 98856    4432.0
Name: new_cases, dtype: float64
98850 98857    3397.0
Name: new_cases, dtype: float64
98851 98858    2925.0
Name: new_cases, dtype: float64
98852 98859    2304.0
Name: new_cases, dtype: float64
98853 98860    2094.0
Name: new_cases, dtype: float64
98854 98861    2238.0
Name: new_cases, dtype: float64
98855 98862    2787.0
Name: new_cases, dtype: float64
98856 98863    3401.0
Name: new_cases, dtype: float64
98857 98864    2940.0
Name: new_cases, dtype: float64
98858 98865    2418.0
Name: new_cases, dtype: float64
98859 98866    2292.0
Name: new_cases, dtype: float64
98860 98867    2026.0
Name: new_cases, dtype: float64
98861 98868    2212.0
Name: new_cases, dtype: float64
98862 98869    2156.0
Name: new_cases, dtype: float64
98863 98870    2606.0
Name: new_cases, dtype: float64
98864 98871    2717.0
Name: new_cases, dtype: float64
98865 98872    2339.0
Name: new_cases, dtype: float64
98866 98873    2274.0
Name: new_cases, dtype: float64
98867 98874    2228.0
Name: new_cases, dtype: float64
98868 98875    2348.0
Name: new_cases, dtype: float64
98869 98876    2863.0
Name: new_cases, dtype: float64
98870 98877    2541.0
Name: new_cases, dtype: float64
98871 98878    2237.0
Name: new_cases, dtype: float64
98872 98879    2408.0
Name: new_cases, dtype: float64
98873 98880    2453.0
Name: new_cases, dtype: float64
98874 98881    2390.0
Name: new_cases, dtype: float64
98875 98882    2515.0
Name: new_cases, dtype: float64
98876 98883    2876.0
Name: new_cases, dtype: float64
98877 98884    2654.0
Name: new_cases, dtype: float64
98878 98885    2815.0
Name: new_cases, dtype: float64
98879 98886    2486.0
Name: new_cases, dtype: float64
98880 98887    2314.0
Name: new_cases, dtype: float64
98881 98888    2209.0
Name: new_cases, dtype: float64
98882 98889    2352.0
Name: new_cases, dtype: float64
98883 98890    2854.0
Name: new_cases, dtype: float64
98884 98891    2802.0
Name: new_cases, dtype: float64
98885 98892    2562.0
Name: new_cases, dtype: float64
98886 98893    2718.0
Name: new_cases, dtype: float64
98887 98894    2347.0
Name: new_cases, dtype: float64
98888 98895    2140.0
Name: new_cases, dtype: float64
98889 98896    2495.0
Name: new_cases, dtype: float64
98890 98897    2814.0
Name: new_cases, dtype: float64
98891 98898    2388.0
Name: new_cases, dtype: float64
98892 98899    2687.0
Name: new_cases, dtype: float64
98893 98900    2220.0
Name: new_cases, dtype: float64
98894 98901    10.0
Name: new_cases, dtype: float64
98895 98902    3841.0
Name: new_cases, dtype: float64

98896 98903    2031.0
Name: new_cases, dtype: float64
98897 98904    2354.0
Name: new_cases, dtype: float64
98898 98905    2130.0
Name: new_cases, dtype: float64
98899 98906    2155.0
Name: new_cases, dtype: float64
98900 98907    2000.0
Name: new_cases, dtype: float64
98901 98908    1684.0
Name: new_cases, dtype: float64
98902 98909    1352.0
Name: new_cases, dtype: float64
98903 98910    1693.0
Name: new_cases, dtype: float64
98904 98911    1915.0
Name: new_cases, dtype: float64
98905 98912    1840.0
Name: new_cases, dtype: float64
98906 98913    1700.0
Name: new_cases, dtype: float64
98907 98914    1608.0
Name: new_cases, dtype: float64
98908 98915    1597.0
Name: new_cases, dtype: float64
98909 98916    1409.0
Name: new_cases, dtype: float64
98910 98917    1735.0
Name: new_cases, dtype: float64
98911 98918    1755.0
Name: new_cases, dtype: float64
98912 98919    1723.0
Name: new_cases, dtype: float64
98913 98920    1721.0
Name: new_cases, dtype: float64
98914 98921    1674.0
Name: new_cases, dtype: float64
98915 98922    1617.0
Name: new_cases, dtype: float64
98916 98923    1645.0
Name: new_cases, dtype: float64
98917 98924    1882.0
Name: new_cases, dtype: float64
98918 98925    1908.0
Name: new_cases, dtype: float64
98919 98926    2777.0
Name: new_cases, dtype: float64
98920 98927    2770.0
Name: new_cases, dtype: float64
98921 98928    2501.0
Name: new_cases, dtype: float64
98922 98929    2266.0
Name: new_cases, dtype: float64
98923 98930    2711.0
Name: new_cases, dtype: float64
98924 98931    2904.0
Name: new_cases, dtype: float64
98925 98932    3727.0
Name: new_cases, dtype: float64
98926 98933    3630.0
Name: new_cases, dtype: float64
98927 98934    3710.0
Name: new_cases, dtype: float64
98928 98935    3707.0
Name: new_cases, dtype: float64
98929 98936    3672.0
Name: new_cases, dtype: float64
98930 98937    3358.0
Name: new_cases, dtype: float64
98931 98938    3903.0
Name: new_cases, dtype: float64
98932 98939    4585.0
Name: new_cases, dtype: float64
98933 98940    5196.0
Name: new_cases, dtype: float64
98934 98941    5872.0
Name: new_cases, dtype: float64
98935 98942    5682.0
Name: new_cases, dtype: float64
98936 98943    6290.0
Name: new_cases, dtype: float64
98937 98944    5298.0
Name: new_cases, dtype: float64
98938 98945    5751.0
Name: new_cases, dtype: float64
98939 98946    7262.0
Name: new_cases, dtype: float64
98940 98947    7685.0
Name: new_cases, dtype: float64
98941 98948    7393.0
Name: new_cases, dtype: float64
98942 98949    7944.0
Name: new_cases, dtype: float64
98943 98950    8172.0
Name: new_cases, dtype: float64
98944 98951    7698.0
Name: new_cases, dtype: float64
98945 98952    7730.0
Name: new_cases, dtype: float64
98946 98953    9109.0
Name: new_cases, dtype: float64
98947 98954    10214.0
Name: new_cases, dtype: float64
98948 98955    10919.0
Name: new_cases, dtype: float64
98949 98956    11954.0
Name: new_cases, dtype: float64
98950 98957    11350.0
Name: new_cases, dtype: float64
98951 98958    11811.0
Name: new_cases, dtype: float64
98952 98959    11282.0
Name: new_cases, dtype: float64
98953 98960    12657.0
Name: new_cases, dtype: float64
98954 98961    16287.0
Name: new_cases, dtype: float64
98955 98962    16204.0
Name: new_cases, dtype: float64
98956 98963    13854.0
Name: new_cases, dtype: float64
98957 98964    12024.0
Name: new_cases, dtype: float64
98958 98965    19207.0
Name: new_cases, dtype: float64
98959 98966    20172.0
Name: new_cases, dtype: float64
98960 98967    20762.0
Name: new_cases, dtype: float64
98961 98968    23597.0
Name: new_cases, dtype: float64
98962 98969    21030.0
Name: new_cases, dtype: float64
98963 98970    21797.0
Name: new_cases, dtype: float64
98964 98971    20643.0
Name: new_cases, dtype: float64
98965 98972    23002.0
Name: new_cases, dtype: float64
98966 98973    22960.0
Name: new_cases, dtype: float64
98967 98974    23714.0
Name: new_cases, dtype: float64
98968 98975    22187.0
Name: new_cases, dtype: float64
98969 98976    21278.0
Name: new_cases, dtype: float64
98970 98977    22033.0
Name: new_cases, dtype: float64
98971 98978    22133.0
Name: new_cases, dtype: float64
98972 98979    21452.0
Name: new_cases, dtype: float64
98973 98980    22158.0
Name: new_cases, dtype: float64
98974 98981    18520.0
Name: new_cases, dtype: float64
98975 98982    23043.0
Name: new_cases, dtype: float64
98976 98983    21530.0
Name: new_cases, dtype: float64
98977 98984    22617.0
Name: new_cases, dtype: float64
98978 98985    23078.0
Name: new_cases, dtype: float64
98979 98986    20975.0
Name: new_cases, dtype: float64
98980 98987    17916.0
Name: new_cases, dtype: float64
98981 98988    18066.0
Name: new_cases, dtype: float64
98982 98989    19770.0
Name: new_cases, dtype: float64
98983 98990    17475.0
Name: new_cases, dtype: float64
98984 98991    17712.0
Name: new_cases, dtype: float64
98985 98992    16592.0
Name: new_cases, dtype: float64
98986 98993    13783.0
Name: new_cases, dtype: float64
98987 98994    12784.0
Name: new_cases, dtype: float64
98988 98995    13475.0
Name: new_cases, dtype: float64
98989 98996    16325.0
Name: new_cases, dtype: float64
98990 98997    15367.0
Name: new_cases, dtype: float64
98991 98998    14636.0
Name: new_cases, dtype: float64
98992 98999    13259.0
Name: new_cases, dtype: float64
98993 99000    12166.0
Name: new_cases, dtype: float64
98994 99001    9313.0
Name: new_cases, dtype: float64
98995 99002    13374.0
Name: new_cases, dtype: float64
98996 99003    13345.0
Name: new_cases, dtype: float64
98997 99004    12449.0
Name: new_cases, dtype: float64
98998 99005    12564.0
Name: new_cases, dtype: float64
98999 99006    11886.0
Name: new_cases, dtype: float64
99000 99007    11496.0
Name: new_cases, dtype: float64
99001 99008    9220.0
Name: new_cases, dtype: float64
99002 99009    15708.0
Name: new_cases, dtype: float64
99003 99010    14885.0
Name: new_cases, dtype: float64
99004 99011    16849.0
Name: new_cases, dtype: float64
99005 99012    15674.0
Name: new_cases, dtype: float64
99006 99013    17478.0
Name: new_cases, dtype: float64
99007 99014    14536.0
Name: new_cases, dtype: float64
99008 99015    18913.0
Name: new_cases, dtype: float64
99009 99016    24727.0
Name: new_cases, dtype: float64
99010 99017    24575.0
Name: new_cases, dtype: float64
99011 99018    35339.0
Name: new_cases, dtype: float64
99012 99019    27890.0
Name: new_cases, dtype: float64
99013 98339    0.0
Name: new_cases, dtype: float64
99014 98340    5.0
Name: new_cases, dtype: float64
99015 98341    4.0
Name: new_cases, dtype: float64
99016 98342    8.0
Name: new_cases, dtype: float64
99017 98343    6.0
Name: new_cases, dtype: float64
99018 98344    14.0
Name: new_cases, dtype: float64
99019 98345    44.0
Name: new_cases, dtype: float64
99681 99688    1.0
Name: new_cases, dtype: float64
99682 99689    1.0
Name: new_cases, dtype: float64
99683 99690    0.0
Name: new_cases, dtype: float64
99684 99691    0.0
Name: new_cases, dtype: float64
99685 99692    0.0
Name: new_cases, dtype: float64
99686 99693    0.0
Name: new_cases, dtype: float64
99687 99694    0.0
Name: new_cases, dtype: float64
99688 99695    0.0
Name: new_cases, dtype: float64
99689 99696    1.0
Name: new_cases, dtype: float64
99690 99697    2.0
Name: new_cases, dtype: float64
99691 99698    0.0
Name: new_cases, dtype: float64
99692 99699    4.0
Name: new_cases, dtype: float64
99693 99700    8.0
Name: new_cases, dtype: float64
99694 99701    8.0
Name: new_cases, dtype: float64
99695 99702    11.0
Name: new_cases, dtype: float64
99696 99703    13.0
Name: new_cases, dtype: float64
99697 99704    50.0
Name: new_cases, dtype: float64
99698 99705    0.0
Name: new_cases, dtype: float64
99699 99706    53.0
Name: new_cases, dtype: float64
99700 99707    50.0
Name: new_cases, dtype: float64
99701 99708    78.0
Name: new_cases, dtype: float64
99702 99709    85.0
Name: new_cases, dtype: float64
99703 99710    83.0
Name: new_cases, dtype: float64
99704 99711    63.0
Name: new_cases, dtype: float64
99705 99712    75.0
Name: new_cases, dtype: float64
99706 99713    58.0
Name: new_cases, dtype: float64
99707 99714    61.0
Name: new_cases, dtype: float64
99708 99715    89.0
Name: new_cases, dtype: float64
99709 99716    71.0
Name: new_cases, dtype: float64
99710 99717    82.0
Name: new_cases, dtype: float64
99711 99718    89.0
Name: new_cases, dtype: float64
99712 99719    67.0
Name: new_cases, dtype: float64
99713 99720    54.0
Name: new_cases, dtype: float64
99714 99721    50.0
Name: new_cases, dtype: float64
99715 99722    29.0
Name: new_cases, dtype: float64
99716 99723    44.0
Name: new_cases, dtype: float64
99717 99724    29.0
Name: new_cases, dtype: float64
99718 99725    18.0
Name: new_cases, dtype: float64
99719 99726    19.0
Name: new_cases, dtype: float64

99720 99727    17.0
Name: new_cases, dtype: float64
99721 99728    20.0
Name: new_cases, dtype: float64
99722 99729    15.0
Name: new_cases, dtype: float64
99723 99730    8.0
Name: new_cases, dtype: float64
99724 99731    13.0
Name: new_cases, dtype: float64
99725 99732    9.0
Name: new_cases, dtype: float64
99726 99733    9.0
Name: new_cases, dtype: float64
99727 99734    5.0
Name: new_cases, dtype: float64
99728 99735    6.0
Name: new_cases, dtype: float64
99729 99736    5.0
Name: new_cases, dtype: float64
99730 99737    5.0
Name: new_cases, dtype: float64
99731 99738    9.0
Name: new_cases, dtype: float64
99732 99739   -1.0
Name: new_cases, dtype: float64
99733 99740    3.0
Name: new_cases, dtype: float64
99734 99741    2.0
Name: new_cases, dtype: float64
99735 99742    2.0
Name: new_cases, dtype: float64
99736 99743    3.0
Name: new_cases, dtype: float64
99737 99744    6.0
Name: new_cases, dtype: float64
99738 99745    2.0
Name: new_cases, dtype: float64
99739 99746    0.0
Name: new_cases, dtype: float64
99740 99747   -1.0
Name: new_cases, dtype: float64
99741 99748    2.0
Name: new_cases, dtype: float64
99742 99749    1.0
Name: new_cases, dtype: float64
99743 99750    1.0
Name: new_cases, dtype: float64
99744 99751    2.0
Name: new_cases, dtype: float64
99745 99752    2.0
Name: new_cases, dtype: float64
99746 99753    3.0
Name: new_cases, dtype: float64
99747 99754    0.0
Name: new_cases, dtype: float64
99748 99755    0.0
Name: new_cases, dtype: float64
99749 99756    0.0
Name: new_cases, dtype: float64
99750 99757    1.0
Name: new_cases, dtype: float64
99751 99758    0.0
Name: new_cases, dtype: float64
99752 99759    1.0
Name: new_cases, dtype: float64
99753 99760    0.0
Name: new_cases, dtype: float64
99754 99761    0.0
Name: new_cases, dtype: float64
99755 99762    4.0
Name: new_cases, dtype: float64
99756 99763    0.0
Name: new_cases, dtype: float64
99757 99764    1.0
Name: new_cases, dtype: float64
99758 99765    0.0
Name: new_cases, dtype: float64
99759 99766    0.0
Name: new_cases, dtype: float64
99760 99767    0.0
Name: new_cases, dtype: float64
99761 99768    0.0
Name: new_cases, dtype: float64
99762 99769    0.0
Name: new_cases, dtype: float64
99763 99770    0.0
Name: new_cases, dtype: float64
99764 99771    0.0
Name: new_cases, dtype: float64
99765 99772    0.0
Name: new_cases, dtype: float64
99766 99773    0.0
Name: new_cases, dtype: float64
99767 99774    0.0
Name: new_cases, dtype: float64
99768 99775    0.0
Name: new_cases, dtype: float64
99769 99776    0.0
Name: new_cases, dtype: float64
99770 99777    0.0
Name: new_cases, dtype: float64
99771 99778    0.0
Name: new_cases, dtype: float64
99772 99779    0.0
Name: new_cases, dtype: float64
99773 99780    0.0
Name: new_cases, dtype: float64
99774 99781    0.0
Name: new_cases, dtype: float64
99775 99782    0.0
Name: new_cases, dtype: float64
99776 99783    0.0
Name: new_cases, dtype: float64
99777 99784    0.0
Name: new_cases, dtype: float64
99778 99785    0.0
Name: new_cases, dtype: float64
99779 99786    0.0
Name: new_cases, dtype: float64
99780 99787    0.0
Name: new_cases, dtype: float64
99781 99788    0.0
Name: new_cases, dtype: float64
99782 99789    2.0
Name: new_cases, dtype: float64
99783 99790    0.0
Name: new_cases, dtype: float64
99784 99791    1.0
Name: new_cases, dtype: float64
99785 99792    0.0
Name: new_cases, dtype: float64
99786 99793    2.0
Name: new_cases, dtype: float64
99787 99794    2.0
Name: new_cases, dtype: float64
99788 99795    2.0
Name: new_cases, dtype: float64
99789 99796    2.0
Name: new_cases, dtype: float64
99790 99797    1.0
Name: new_cases, dtype: float64
99791 99798    3.0
Name: new_cases, dtype: float64
99792 99799    1.0
Name: new_cases, dtype: float64
99793 99800    2.0
Name: new_cases, dtype: float64
99794 99801    4.0
Name: new_cases, dtype: float64
99795 99802    2.0
Name: new_cases, dtype: float64
99796 99803    0.0
Name: new_cases, dtype: float64
99797 99804    0.0
Name: new_cases, dtype: float64
99798 99805    2.0
Name: new_cases, dtype: float64
99799 99806    0.0
Name: new_cases, dtype: float64
99800 99807    0.0
Name: new_cases, dtype: float64
99801 99808    3.0
Name: new_cases, dtype: float64
99802 99809    1.0
Name: new_cases, dtype: float64
99803 99810    2.0
Name: new_cases, dtype: float64
99804 99811    1.0
Name: new_cases, dtype: float64
99805 99812    3.0
Name: new_cases, dtype: float64
99806 99813    2.0
Name: new_cases, dtype: float64
99807 99814    1.0
Name: new_cases, dtype: float64
99808 99815    1.0
Name: new_cases, dtype: float64
99809 99816    0.0
Name: new_cases, dtype: float64
99810 99817    1.0
Name: new_cases, dtype: float64
99811 99818    2.0
Name: new_cases, dtype: float64
99812 99819    1.0
Name: new_cases, dtype: float64
99813 99820    1.0
Name: new_cases, dtype: float64
99814 99821    1.0
Name: new_cases, dtype: float64
99815 99822    3.0
Name: new_cases, dtype: float64
99816 99823    1.0
Name: new_cases, dtype: float64
99817 99824    1.0
Name: new_cases, dtype: float64
99818 99825    0.0
Name: new_cases, dtype: float64
99819 99826    0.0
Name: new_cases, dtype: float64
99820 99827    1.0
Name: new_cases, dtype: float64
99821 99828    0.0
Name: new_cases, dtype: float64
99822 99829    0.0
Name: new_cases, dtype: float64
99823 99830    0.0
Name: new_cases, dtype: float64
99824 99831    1.0
Name: new_cases, dtype: float64
99825 99832    2.0
Name: new_cases, dtype: float64
99826 99833    1.0
Name: new_cases, dtype: float64
99827 99834    0.0
Name: new_cases, dtype: float64
99828 99835    2.0
Name: new_cases, dtype: float64
99829 99836    3.0
Name: new_cases, dtype: float64
99830 99837    2.0
Name: new_cases, dtype: float64
99831 99838    0.0
Name: new_cases, dtype: float64
99832 99839    2.0
Name: new_cases, dtype: float64
99833 99840    0.0
Name: new_cases, dtype: float64
99834 99841    0.0
Name: new_cases, dtype: float64
99835 99842    0.0
Name: new_cases, dtype: float64
99836 99843    0.0
Name: new_cases, dtype: float64
99837 99844    0.0
Name: new_cases, dtype: float64
99838 99845    1.0
Name: new_cases, dtype: float64
99839 99846    0.0
Name: new_cases, dtype: float64
99840 99847    19.0
Name: new_cases, dtype: float64
99841 99848    13.0
Name: new_cases, dtype: float64
99842 99849    7.0
Name: new_cases, dtype: float64
99843 99850    13.0
Name: new_cases, dtype: float64
99844 99851    9.0
Name: new_cases, dtype: float64
99845 99852    12.0
Name: new_cases, dtype: float64
99846 99853    6.0
Name: new_cases, dtype: float64
99847 99854    5.0
Name: new_cases, dtype: float64
99848 99855    11.0
Name: new_cases, dtype: float64
99849 99856    6.0
Name: new_cases, dtype: float64
99850 99857    3.0
Name: new_cases, dtype: float64
99851 99858    9.0
Name: new_cases, dtype: float64
99852 99859    7.0
Name: new_cases, dtype: float64
99853 99860    5.0
Name: new_cases, dtype: float64
99854 99861    7.0
Name: new_cases, dtype: float64
99855 99862    12.0
Name: new_cases, dtype: float64
99856 99863    13.0
Name: new_cases, dtype: float64
99857 99864    2.0
Name: new_cases, dtype: float64
99858 99865    9.0
Name: new_cases, dtype: float64
99859 99866    14.0
Name: new_cases, dtype: float64
99860 99867    5.0
Name: new_cases, dtype: float64
99861 99868    2.0
Name: new_cases, dtype: float64
99862 99869    5.0
Name: new_cases, dtype: float64
99863 99870    3.0
Name: new_cases, dtype: float64
99864 99871    5.0
Name: new_cases, dtype: float64
99865 99872    4.0
Name: new_cases, dtype: float64
99866 99873    6.0
Name: new_cases, dtype: float64
99867 99874    6.0
Name: new_cases, dtype: float64
99868 99875    4.0
Name: new_cases, dtype: float64
99869 99876    1.0
Name: new_cases, dtype: float64
99870 99877    2.0
Name: new_cases, dtype: float64
99871 99878    2.0
Name: new_cases, dtype: float64
99872 99879    1.0
Name: new_cases, dtype: float64
99873 99880    3.0
Name: new_cases, dtype: float64
99874 99881    1.0
Name: new_cases, dtype: float64
99875 99882    7.0
Name: new_cases, dtype: float64
99876 99883    0.0
Name: new_cases, dtype: float64
99877 99884    2.0
Name: new_cases, dtype: float64
99878 99885    4.0
Name: new_cases, dtype: float64
99879 99886    0.0
Name: new_cases, dtype: float64
99880 99887    0.0
Name: new_cases, dtype: float64
99881 99888    9.0
Name: new_cases, dtype: float64
99882 99889    3.0
Name: new_cases, dtype: float64
99883 99890    2.0
Name: new_cases, dtype: float64
99884 99891    2.0
Name: new_cases, dtype: float64
99885 99892    2.0
Name: new_cases, dtype: float64
99886 99893    0.0
Name: new_cases, dtype: float64
99887 99894    2.0
Name: new_cases, dtype: float64
99888 99895    1.0
Name: new_cases, dtype: float64

99889 99896    12.0
Name: new_cases, dtype: float64
99890 99897    0.0
Name: new_cases, dtype: float64
99891 99898    1.0
Name: new_cases, dtype: float64
99892 99899    5.0
Name: new_cases, dtype: float64
99893 99900    1.0
Name: new_cases, dtype: float64
99894 99901    3.0
Name: new_cases, dtype: float64
99895 99902    3.0
Name: new_cases, dtype: float64
99896 99903    3.0
Name: new_cases, dtype: float64
99897 99904    2.0
Name: new_cases, dtype: float64
99898 99905    4.0
Name: new_cases, dtype: float64
99899 99906    1.0
Name: new_cases, dtype: float64
99900 99907    0.0
Name: new_cases, dtype: float64
99901 99908    1.0
Name: new_cases, dtype: float64
99902 99909    2.0
Name: new_cases, dtype: float64
99903 99910    2.0
Name: new_cases, dtype: float64
99904 99911    4.0
Name: new_cases, dtype: float64
99905 99912    3.0
Name: new_cases, dtype: float64
99906 99913    3.0
Name: new_cases, dtype: float64
99907 99914    0.0
Name: new_cases, dtype: float64
99908 99915    1.0
Name: new_cases, dtype: float64
99909 99916    25.0
Name: new_cases, dtype: float64
99910 99917    2.0
Name: new_cases, dtype: float64
99911 99918    9.0
Name: new_cases, dtype: float64
99912 99919    11.0
Name: new_cases, dtype: float64
99913 99920    1.0
Name: new_cases, dtype: float64
99914 99921    5.0
Name: new_cases, dtype: float64
99915 99922    1.0
Name: new_cases, dtype: float64
99916 99923    2.0
Name: new_cases, dtype: float64
99917 99924    6.0
Name: new_cases, dtype: float64
99918 99925    1.0
Name: new_cases, dtype: float64
99919 99926    7.0
Name: new_cases, dtype: float64
99920 99927    2.0
Name: new_cases, dtype: float64
99921 99928    4.0
Name: new_cases, dtype: float64
99922 99929    5.0
Name: new_cases, dtype: float64
99923 99930    3.0
Name: new_cases, dtype: float64
99924 99931    2.0
Name: new_cases, dtype: float64
99925 99932    1.0
Name: new_cases, dtype: float64
99926 99933    2.0
Name: new_cases, dtype: float64
99927 99934    6.0
Name: new_cases, dtype: float64
99928 99935    4.0
Name: new_cases, dtype: float64
99929 99936    1.0
Name: new_cases, dtype: float64
99930 99937    1.0
Name: new_cases, dtype: float64
99931 99938    3.0
Name: new_cases, dtype: float64
99932 99939    4.0
Name: new_cases, dtype: float64
99933 99940    3.0
Name: new_cases, dtype: float64
99934 99941    3.0
Name: new_cases, dtype: float64
99935 99942    0.0
Name: new_cases, dtype: float64
99936 99943    4.0
Name: new_cases, dtype: float64
99937 99944    3.0
Name: new_cases, dtype: float64
99938 99945    2.0
Name: new_cases, dtype: float64
99939 99946    3.0
Name: new_cases, dtype: float64
99940 99947    6.0
Name: new_cases, dtype: float64
99941 99948    9.0
Name: new_cases, dtype: float64
99942 99949    2.0
Name: new_cases, dtype: float64
99943 99950    1.0
Name: new_cases, dtype: float64
99944 99951    8.0
Name: new_cases, dtype: float64
99945 99952    1.0
Name: new_cases, dtype: float64
99946 99953    7.0
Name: new_cases, dtype: float64
99947 99954    3.0
Name: new_cases, dtype: float64
99948 99955    0.0
Name: new_cases, dtype: float64
99949 99956    6.0
Name: new_cases, dtype: float64
99950 99957    3.0
Name: new_cases, dtype: float64
99951 99958    1.0
Name: new_cases, dtype: float64
99952 99959    9.0
Name: new_cases, dtype: float64
99953 99960    0.0
Name: new_cases, dtype: float64
99954 99961    9.0
Name: new_cases, dtype: float64
99955 99962    0.0
Name: new_cases, dtype: float64
99956 99963    1.0
Name: new_cases, dtype: float64
99957 99964    6.0
Name: new_cases, dtype: float64
99958 99965    3.0
Name: new_cases, dtype: float64
99959 99966    0.0
Name: new_cases, dtype: float64
99960 99967    4.0
Name: new_cases, dtype: float64
99961 99968    0.0
Name: new_cases, dtype: float64
99962 99969    4.0
Name: new_cases, dtype: float64
99963 99970    0.0
Name: new_cases, dtype: float64
99964 99971    0.0
Name: new_cases, dtype: float64
99965 99972    4.0
Name: new_cases, dtype: float64
99966 99973    0.0
Name: new_cases, dtype: float64
99967 99974    10.0
Name: new_cases, dtype: float64
99968 99975    0.0
Name: new_cases, dtype: float64
99969 99976    6.0
Name: new_cases, dtype: float64
99970 99977    5.0
Name: new_cases, dtype: float64
99971 99978    0.0
Name: new_cases, dtype: float64
99972 99979    7.0
Name: new_cases, dtype: float64
99973 99980    0.0
Name: new_cases, dtype: float64
99974 99981    0.0
Name: new_cases, dtype: float64
99975 99982    0.0
Name: new_cases, dtype: float64
99976 99983    16.0
Name: new_cases, dtype: float64
99977 99984    0.0
Name: new_cases, dtype: float64
99978 99985    7.0
Name: new_cases, dtype: float64
99979 99986    0.0
Name: new_cases, dtype: float64
99980 99987    11.0
Name: new_cases, dtype: float64
99981 99988    0.0
Name: new_cases, dtype: float64
99982 99989    0.0
Name: new_cases, dtype: float64
99983 99990    19.0
Name: new_cases, dtype: float64
99984 99991    0.0
Name: new_cases, dtype: float64
99985 99992    5.0
Name: new_cases, dtype: float64
99986 99993    0.0
Name: new_cases, dtype: float64
99987 99994    2.0
Name: new_cases, dtype: float64
99988 99995    0.0
Name: new_cases, dtype: float64
99989 99996    0.0
Name: new_cases, dtype: float64
99990 99997    31.0
Name: new_cases, dtype: float64
99991 99998    3.0
Name: new_cases, dtype: float64
99992 99999    0.0
Name: new_cases, dtype: float64
99993 100000    6.0
Name: new_cases, dtype: float64
99994 100001    0.0
Name: new_cases, dtype: float64
99995 100002    18.0
Name: new_cases, dtype: float64
99996 100003    0.0
Name: new_cases, dtype: float64
99997 100004    10.0
Name: new_cases, dtype: float64
99998 100005    6.0
Name: new_cases, dtype: float64
99999 100006    0.0
Name: new_cases, dtype: float64
100000 100007    5.0
Name: new_cases, dtype: float64
100001 100008    0.0
Name: new_cases, dtype: float64
100002 100009    9.0
Name: new_cases, dtype: float64
100003 100010    0.0
Name: new_cases, dtype: float64
100004 100011    7.0
Name: new_cases, dtype: float64
100005 100012    5.0
Name: new_cases, dtype: float64
100006 100013    2.0
Name: new_cases, dtype: float64
100007 100014    5.0
Name: new_cases, dtype: float64
100008 100015    4.0
Name: new_cases, dtype: float64
100009 100016    6.0
Name: new_cases, dtype: float64
100010 100017   -2.0
Name: new_cases, dtype: float64
100011 100018    1.0
Name: new_cases, dtype: float64
100012 100019    0.0
Name: new_cases, dtype: float64
100013 100020    3.0
Name: new_cases, dtype: float64
100014 100021    1.0
Name: new_cases, dtype: float64
100015 100022    5.0
Name: new_cases, dtype: float64
100016 100023    2.0
Name: new_cases, dtype: float64
100017 100024    0.0
Name: new_cases, dtype: float64
100018 100025    5.0
Name: new_cases, dtype: float64
100019 100026    0.0
Name: new_cases, dtype: float64
100020 100027    2.0
Name: new_cases, dtype: float64
100021 100028    2.0
Name: new_cases, dtype: float64
100022 100029    0.0
Name: new_cases, dtype: float64
100023 100030    2.0
Name: new_cases, dtype: float64
100024 100031    2.0
Name: new_cases, dtype: float64
100025 100032    2.0
Name: new_cases, dtype: float64
100026 100033    6.0
Name: new_cases, dtype: float64
100027 100034    1.0
Name: new_cases, dtype: float64
100028 100035    3.0
Name: new_cases, dtype: float64
100029 100036    4.0
Name: new_cases, dtype: float64
100030 100037    4.0
Name: new_cases, dtype: float64
100031 100038    2.0
Name: new_cases, dtype: float64
100032 100039    0.0
Name: new_cases, dtype: float64
100033 100040    7.0
Name: new_cases, dtype: float64
100034 100041    6.0
Name: new_cases, dtype: float64
100035 100042    2.0
Name: new_cases, dtype: float64
100036 100043    3.0
Name: new_cases, dtype: float64
100037 100044    3.0
Name: new_cases, dtype: float64
100038 100045    1.0
Name: new_cases, dtype: float64
100039 100046    4.0
Name: new_cases, dtype: float64
100040 100047    2.0
Name: new_cases, dtype: float64
100041 100048    4.0
Name: new_cases, dtype: float64
100042 100049    2.0
Name: new_cases, dtype: float64
100043 100050    5.0
Name: new_cases, dtype: float64
100044 100051    0.0
Name: new_cases, dtype: float64
100045 100052    9.0
Name: new_cases, dtype: float64
100046 100053    1.0
Name: new_cases, dtype: float64
100047 100054    6.0
Name: new_cases, dtype: float64
100048 100055    4.0
Name: new_cases, dtype: float64
100049 100056    1.0
Name: new_cases, dtype: float64
100050 100057    6.0
Name: new_cases, dtype: float64
100051 100058    1.0
Name: new_cases, dtype: float64
100052 100059    5.0
Name: new_cases, dtype: float64
100053 100060    1.0
Name: new_cases, dtype: float64
100054 100061    7.0
Name: new_cases, dtype: float64
100055 100062    2.0
Name: new_cases, dtype: float64

100056 100063    2.0
Name: new_cases, dtype: float64
100057 100064    0.0
Name: new_cases, dtype: float64
100058 100065    10.0
Name: new_cases, dtype: float64
100059 100066    0.0
Name: new_cases, dtype: float64
100060 100067    9.0
Name: new_cases, dtype: float64
100061 100068    9.0
Name: new_cases, dtype: float64
100062 100069    0.0
Name: new_cases, dtype: float64
100063 100070    8.0
Name: new_cases, dtype: float64
100064 100071    6.0
Name: new_cases, dtype: float64
100065 100072    3.0
Name: new_cases, dtype: float64
100066 100073    2.0
Name: new_cases, dtype: float64
100067 100074    1.0
Name: new_cases, dtype: float64
100068 100075    11.0
Name: new_cases, dtype: float64
100069 100076    2.0
Name: new_cases, dtype: float64
100070 100077    2.0
Name: new_cases, dtype: float64
100071 100078    4.0
Name: new_cases, dtype: float64
100072 100079    0.0
Name: new_cases, dtype: float64
100073 100080    0.0
Name: new_cases, dtype: float64
100074 100081    0.0
Name: new_cases, dtype: float64
100075 100082    6.0
Name: new_cases, dtype: float64
100076 100083    17.0
Name: new_cases, dtype: float64
100077 100084    7.0
Name: new_cases, dtype: float64
100078 100085    24.0
Name: new_cases, dtype: float64
100079 100086    6.0
Name: new_cases, dtype: float64
100080 100087    10.0
Name: new_cases, dtype: float64
100081 100088    3.0
Name: new_cases, dtype: float64
100082 100089    9.0
Name: new_cases, dtype: float64
100083 100090    4.0
Name: new_cases, dtype: float64
100084 100091    2.0
Name: new_cases, dtype: float64
100085 100092    2.0
Name: new_cases, dtype: float64
100086 100093    0.0
Name: new_cases, dtype: float64
100087 100094    0.0
Name: new_cases, dtype: float64
100088 100095    4.0
Name: new_cases, dtype: float64
100089 100096    1.0
Name: new_cases, dtype: float64
100090 100097    1.0
Name: new_cases, dtype: float64
100091 100098    2.0
Name: new_cases, dtype: float64
100092 100099    1.0
Name: new_cases, dtype: float64
100093 100100    0.0
Name: new_cases, dtype: float64
100094 100101    0.0
Name: new_cases, dtype: float64
100095 100102    1.0
Name: new_cases, dtype: float64
100096 100103    0.0
Name: new_cases, dtype: float64
100097 100104    8.0
Name: new_cases, dtype: float64
100098 100105    0.0
Name: new_cases, dtype: float64
100099 100106    4.0
Name: new_cases, dtype: float64
100100 100107    0.0
Name: new_cases, dtype: float64
100101 100108    0.0
Name: new_cases, dtype: float64
100102 100109    5.0
Name: new_cases, dtype: float64
100103 100110    4.0
Name: new_cases, dtype: float64
100104 100111    1.0
Name: new_cases, dtype: float64
100105 100112    6.0
Name: new_cases, dtype: float64
100106 100113    4.0
Name: new_cases, dtype: float64
100107 100114    1.0
Name: new_cases, dtype: float64
100108 100115    0.0
Name: new_cases, dtype: float64
100109 100116    8.0
Name: new_cases, dtype: float64
100110 100117    2.0
Name: new_cases, dtype: float64
100111 100118    0.0
Name: new_cases, dtype: float64
100112 100119   -1.0
Name: new_cases, dtype: float64
100113 100120    1.0
Name: new_cases, dtype: float64
100114 100121    1.0
Name: new_cases, dtype: float64
100115 100122    0.0
Name: new_cases, dtype: float64
100116 100123    1.0
Name: new_cases, dtype: float64
100117 100124    5.0
Name: new_cases, dtype: float64
100118 100125    2.0
Name: new_cases, dtype: float64
100119 100126    5.0
Name: new_cases, dtype: float64
100120 100127    1.0
Name: new_cases, dtype: float64
100121 100128    3.0
Name: new_cases, dtype: float64
100122 100129    0.0
Name: new_cases, dtype: float64
100123 100130    6.0
Name: new_cases, dtype: float64
100124 100131    0.0
Name: new_cases, dtype: float64
100125 100132    1.0
Name: new_cases, dtype: float64
100126 100133    0.0
Name: new_cases, dtype: float64
100127 100134    1.0
Name: new_cases, dtype: float64
100128 100135    0.0
Name: new_cases, dtype: float64
100129 100136    0.0
Name: new_cases, dtype: float64
100130 100137    2.0
Name: new_cases, dtype: float64
100131 100138    1.0
Name: new_cases, dtype: float64
100132 100139    0.0
Name: new_cases, dtype: float64
100133 100140    6.0
Name: new_cases, dtype: float64
100134 100141    2.0
Name: new_cases, dtype: float64
100135 100142    1.0
Name: new_cases, dtype: float64
100136 100143    0.0
Name: new_cases, dtype: float64
100137 100144    0.0
Name: new_cases, dtype: float64
100138 100145    0.0
Name: new_cases, dtype: float64
100139 100146    10.0
Name: new_cases, dtype: float64
100140 100147    4.0
Name: new_cases, dtype: float64
100141 100148    1.0
Name: new_cases, dtype: float64
100142 100149    5.0
Name: new_cases, dtype: float64
100143 100150    0.0
Name: new_cases, dtype: float64
100144 100151    6.0
Name: new_cases, dtype: float64
100145 100152    1.0
Name: new_cases, dtype: float64
100146 100153    0.0
Name: new_cases, dtype: float64
100147 100154    2.0
Name: new_cases, dtype: float64
100148 100155    2.0
Name: new_cases, dtype: float64
100149 100156    1.0
Name: new_cases, dtype: float64
100150 100157    0.0
Name: new_cases, dtype: float64
100151 100158    4.0
Name: new_cases, dtype: float64
100152 100159    2.0
Name: new_cases, dtype: float64
100153 100160    0.0
Name: new_cases, dtype: float64
100154 100161    3.0
Name: new_cases, dtype: float64
100155 100162    0.0
Name: new_cases, dtype: float64
100156 100163    2.0
Name: new_cases, dtype: float64
100157 100164    4.0
Name: new_cases, dtype: float64
100158 100165    0.0
Name: new_cases, dtype: float64
100159 100166    9.0
Name: new_cases, dtype: float64
100160 100167    3.0
Name: new_cases, dtype: float64
100161 100168    1.0
Name: new_cases, dtype: float64
100162 100169    0.0
Name: new_cases, dtype: float64
100163 100170    0.0
Name: new_cases, dtype: float64
100164 100171    0.0
Name: new_cases, dtype: float64
100165 100172    9.0
Name: new_cases, dtype: float64
100166 100173    7.0
Name: new_cases, dtype: float64
100167 100174    0.0
Name: new_cases, dtype: float64
100168 100175    5.0
Name: new_cases, dtype: float64
100169 100176    1.0
Name: new_cases, dtype: float64
100170 100177    1.0
Name: new_cases, dtype: float64
100171 100178    0.0
Name: new_cases, dtype: float64
100172 100179    2.0
Name: new_cases, dtype: float64
100173 100180    1.0
Name: new_cases, dtype: float64
100174 100181    18.0
Name: new_cases, dtype: float64
100175 100182    4.0
Name: new_cases, dtype: float64
100176 100183    4.0
Name: new_cases, dtype: float64
100177 100184    9.0
Name: new_cases, dtype: float64
100178 100185    0.0
Name: new_cases, dtype: float64
100179 100186    11.0
Name: new_cases, dtype: float64
100180 100187    3.0
Name: new_cases, dtype: float64
100181 100188    5.0
Name: new_cases, dtype: float64
100182 100189    6.0
Name: new_cases, dtype: float64
100183 100190    7.0
Name: new_cases, dtype: float64
100184 100191    20.0
Name: new_cases, dtype: float64
100185 100192    0.0
Name: new_cases, dtype: float64
100186 100193    7.0
Name: new_cases, dtype: float64
100187 100194    1.0
Name: new_cases, dtype: float64
100188 100195    0.0
Name: new_cases, dtype: float64
100189 100196    1.0
Name: new_cases, dtype: float64
100190 100197    3.0
Name: new_cases, dtype: float64
100191 100198    3.0
Name: new_cases, dtype: float64
100192 100199    0.0
Name: new_cases, dtype: float64
100193 100200    3.0
Name: new_cases, dtype: float64
100194 100201    4.0
Name: new_cases, dtype: float64
100195 100202    0.0
Name: new_cases, dtype: float64
100196 100203    2.0
Name: new_cases, dtype: float64
100197 100204    1.0
Name: new_cases, dtype: float64
100198 100205    0.0
Name: new_cases, dtype: float64
100199 100206    0.0
Name: new_cases, dtype: float64
100200 100207    6.0
Name: new_cases, dtype: float64
100201 100208    4.0
Name: new_cases, dtype: float64
100202 100209    12.0
Name: new_cases, dtype: float64
100203 100210    2.0
Name: new_cases, dtype: float64
100204 100211    9.0
Name: new_cases, dtype: float64
100205 100212    1.0
Name: new_cases, dtype: float64
100206 100213    0.0
Name: new_cases, dtype: float64
100207 100214    5.0
Name: new_cases, dtype: float64
100208 100215    7.0
Name: new_cases, dtype: float64
100209 100216    0.0
Name: new_cases, dtype: float64
100210 100217    10.0
Name: new_cases, dtype: float64
100211 100218    0.0
Name: new_cases, dtype: float64
100212 100219    32.0
Name: new_cases, dtype: float64
100213 100220    24.0
Name: new_cases, dtype: float64
100214 100221    24.0
Name: new_cases, dtype: float64
100215 100222    38.0
Name: new_cases, dtype: float64

100216 100223    42.0
Name: new_cases, dtype: float64
100217 100224    63.0
Name: new_cases, dtype: float64
100218 100225    68.0
Name: new_cases, dtype: float64
100219 100226    70.0
Name: new_cases, dtype: float64
100220 100227    83.0
Name: new_cases, dtype: float64
100221 100228    84.0
Name: new_cases, dtype: float64
100222 100229    55.0
Name: new_cases, dtype: float64
100223 100230    0.0
Name: new_cases, dtype: float64
100224 100231    50.0
Name: new_cases, dtype: float64
100225 100232    76.0
Name: new_cases, dtype: float64
100226 100233    84.0
Name: new_cases, dtype: float64
100227 100234    19.0
Name: new_cases, dtype: float64
100228 100235    20.0
Name: new_cases, dtype: float64
100229 100236    24.0
Name: new_cases, dtype: float64
100230 100237    21.0
Name: new_cases, dtype: float64
100231 100238    16.0
Name: new_cases, dtype: float64
100232 100239    18.0
Name: new_cases, dtype: float64
100233 100240    19.0
Name: new_cases, dtype: float64
100234 100241    24.0
Name: new_cases, dtype: float64
100235 100242    23.0
Name: new_cases, dtype: float64
100236 100243    36.0
Name: new_cases, dtype: float64
100237 100244    17.0
Name: new_cases, dtype: float64
100238 100245    15.0
Name: new_cases, dtype: float64
100239 100246    18.0
Name: new_cases, dtype: float64
100240 100247    15.0
Name: new_cases, dtype: float64
100241 100248    24.0
Name: new_cases, dtype: float64
100242 100249    22.0
Name: new_cases, dtype: float64
100243 100250    22.0
Name: new_cases, dtype: float64
100244 100251    13.0
Name: new_cases, dtype: float64
100245 100252    24.0
Name: new_cases, dtype: float64
100246 100253    16.0
Name: new_cases, dtype: float64
100247 100254    9.0
Name: new_cases, dtype: float64
100248 100255    18.0
Name: new_cases, dtype: float64
100249 100256    21.0
Name: new_cases, dtype: float64
100250 100257    11.0
Name: new_cases, dtype: float64
100251 100258    10.0
Name: new_cases, dtype: float64
100252 100259    44.0
Name: new_cases, dtype: float64
100253 100260    25.0
Name: new_cases, dtype: float64
100254 100261    18.0
Name: new_cases, dtype: float64
100255 100262    28.0
Name: new_cases, dtype: float64
100256 100263    33.0
Name: new_cases, dtype: float64
100257 100264    30.0
Name: new_cases, dtype: float64
100258 100265    26.0
Name: new_cases, dtype: float64
100259 100266    42.0
Name: new_cases, dtype: float64
100260 100267    30.0
Name: new_cases, dtype: float64
100261 100268    47.0
Name: new_cases, dtype: float64
100262 100269    36.0
Name: new_cases, dtype: float64
100263 100270    61.0
Name: new_cases, dtype: float64
100264 100271    35.0
Name: new_cases, dtype: float64
100265 100272    45.0
Name: new_cases, dtype: float64
100266 100273    55.0
Name: new_cases, dtype: float64
100267 100274    72.0
Name: new_cases, dtype: float64
100268 100275    66.0
Name: new_cases, dtype: float64
100269 100276    42.0
Name: new_cases, dtype: float64
100270 100277    52.0
Name: new_cases, dtype: float64
100271 100278    64.0
Name: new_cases, dtype: float64
100272 100279    98.0
Name: new_cases, dtype: float64
100273 100280    60.0
Name: new_cases, dtype: float64
100274 100281    102.0
Name: new_cases, dtype: float64
100275 100282    134.0
Name: new_cases, dtype: float64
100276 100283    105.0
Name: new_cases, dtype: float64
100277 100284    84.0
Name: new_cases, dtype: float64
100278 100285    111.0
Name: new_cases, dtype: float64
100279 100286    73.0
Name: new_cases, dtype: float64
100280 100287    77.0
Name: new_cases, dtype: float64
100281 100288    96.0
Name: new_cases, dtype: float64
100282 100289    129.0
Name: new_cases, dtype: float64
100283 100290    161.0
Name: new_cases, dtype: float64
100284 100291    143.0
Name: new_cases, dtype: float64
100285 100292    166.0
Name: new_cases, dtype: float64
100286 100293    129.0
Name: new_cases, dtype: float64
100287 100294    109.0
Name: new_cases, dtype: float64
100288 100295    140.0
Name: new_cases, dtype: float64
100289 100296    166.0
Name: new_cases, dtype: float64
100290 100297    204.0
Name: new_cases, dtype: float64
100291 100298    114.0
Name: new_cases, dtype: float64
100292 100299    192.0
Name: new_cases, dtype: float64
100293 100300    127.0
Name: new_cases, dtype: float64
100294 100301    147.0
Name: new_cases, dtype: float64
100295 100302    185.0
Name: new_cases, dtype: float64
100296 100303    199.0
Name: new_cases, dtype: float64
100297 100304    176.0
Name: new_cases, dtype: float64
100298 100305    210.0
Name: new_cases, dtype: float64
100299 100306    174.0
Name: new_cases, dtype: float64
100300 100307    222.0
Name: new_cases, dtype: float64
100301 100308    197.0
Name: new_cases, dtype: float64
100302 100309    167.0
Name: new_cases, dtype: float64
100303 100310    200.0
Name: new_cases, dtype: float64
100304 100311    171.0
Name: new_cases, dtype: float64
100305 100312    149.0
Name: new_cases, dtype: float64
100306 100313    204.0
Name: new_cases, dtype: float64
100307 100314    217.0
Name: new_cases, dtype: float64
100308 100315    216.0
Name: new_cases, dtype: float64
100309 100316    180.0
Name: new_cases, dtype: float64
100310 100317    177.0
Name: new_cases, dtype: float64
100311 100318    148.0
Name: new_cases, dtype: float64
100312 100319    146.0
Name: new_cases, dtype: float64
100313 100320    184.0
Name: new_cases, dtype: float64
100314 100321    132.0
Name: new_cases, dtype: float64
100315 100322    147.0
Name: new_cases, dtype: float64
100316 100323    172.0
Name: new_cases, dtype: float64
100317 100324    97.0
Name: new_cases, dtype: float64
100318 100325    95.0
Name: new_cases, dtype: float64
100319 100326    108.0
Name: new_cases, dtype: float64
100320 100327    136.0
Name: new_cases, dtype: float64
100321 100328    97.0
Name: new_cases, dtype: float64
100322 100329    88.0
Name: new_cases, dtype: float64
100323 100330    105.0
Name: new_cases, dtype: float64
100324 100331    0.0
Name: new_cases, dtype: float64
100325 100332    160.0
Name: new_cases, dtype: float64
100326 100333    103.0
Name: new_cases, dtype: float64
100327 100334    102.0
Name: new_cases, dtype: float64
100328 100335    81.0
Name: new_cases, dtype: float64
100329 100336    76.0
Name: new_cases, dtype: float64
100330 100337    95.0
Name: new_cases, dtype: float64
100331 100338    79.0
Name: new_cases, dtype: float64
100332 100339    49.0
Name: new_cases, dtype: float64
100333 100340    59.0
Name: new_cases, dtype: float64
100334 100341    70.0
Name: new_cases, dtype: float64
100335 100342    36.0
Name: new_cases, dtype: float64
100336 100343    58.0
Name: new_cases, dtype: float64
100337 100344    59.0
Name: new_cases, dtype: float64
100338 100345    71.0
Name: new_cases, dtype: float64
100339 100346    0.0
Name: new_cases, dtype: float64
100340 100347    136.0
Name: new_cases, dtype: float64
100341 100348    44.0
Name: new_cases, dtype: float64
100342 100349    33.0
Name: new_cases, dtype: float64
100343 100350    54.0
Name: new_cases, dtype: float64
100344 100351    71.0
Name: new_cases, dtype: float64
100345 100352    61.0
Name: new_cases, dtype: float64
100346 100353    0.0
Name: new_cases, dtype: float64
100347 100354    137.0
Name: new_cases, dtype: float64
100348 100355    51.0
Name: new_cases, dtype: float64
100349 100356    59.0
Name: new_cases, dtype: float64
100350 100357    40.0
Name: new_cases, dtype: float64
100351 100358    62.0
Name: new_cases, dtype: float64
100352 100359    58.0
Name: new_cases, dtype: float64
100353 100360    0.0
Name: new_cases, dtype: float64
100354 100361    148.0
Name: new_cases, dtype: float64
100355 99701    8.0
Name: new_cases, dtype: float64
100356 99702    11.0
Name: new_cases, dtype: float64
100357 99703    13.0
Name: new_cases, dtype: float64
100358 99704    50.0
Name: new_cases, dtype: float64
100359 99705    0.0
Name: new_cases, dtype: float64
100360 99706    53.0
Name: new_cases, dtype: float64
100361 99707    50.0
Name: new_cases, dtype: float64
100362 100369    0.0
Name: new_cases, dtype: float64
100363 100370    0.0
Name: new_cases, dtype: float64
100364 100371    2.0
Name: new_cases, dtype: float64
100365 100372    0.0
Name: new_cases, dtype: float64
100366 100373    0.0
Name: new_cases, dtype: float64
100367 100374    1.0
Name: new_cases, dtype: float64
100368 100375    0.0
Name: new_cases, dtype: float64
100369 100376    0.0
Name: new_cases, dtype: float64
100370 100377    0.0
Name: new_cases, dtype: float64
100371 100378    0.0
Name: new_cases, dtype: float64

100372 100379    1.0
Name: new_cases, dtype: float64
100373 100380    0.0
Name: new_cases, dtype: float64
100374 100381    0.0
Name: new_cases, dtype: float64
100375 100382    0.0
Name: new_cases, dtype: float64
100376 100383    1.0
Name: new_cases, dtype: float64
100377 100384    0.0
Name: new_cases, dtype: float64
100378 100385    1.0
Name: new_cases, dtype: float64
100379 100386    1.0
Name: new_cases, dtype: float64
100380 100387    0.0
Name: new_cases, dtype: float64
100381 100388    0.0
Name: new_cases, dtype: float64
100382 100389    0.0
Name: new_cases, dtype: float64
100383 100390    0.0
Name: new_cases, dtype: float64
100384 100391    0.0
Name: new_cases, dtype: float64
100385 100392    0.0
Name: new_cases, dtype: float64
100386 100393    1.0
Name: new_cases, dtype: float64
100387 100394    0.0
Name: new_cases, dtype: float64
100388 100395    0.0
Name: new_cases, dtype: float64
100389 100396    0.0
Name: new_cases, dtype: float64
100390 100397    1.0
Name: new_cases, dtype: float64
100391 100398    0.0
Name: new_cases, dtype: float64
100392 100399    1.0
Name: new_cases, dtype: float64
100393 100400    1.0
Name: new_cases, dtype: float64
100394 100401    0.0
Name: new_cases, dtype: float64
100395 100402    0.0
Name: new_cases, dtype: float64
100396 100403    0.0
Name: new_cases, dtype: float64
100397 100404    1.0
Name: new_cases, dtype: float64
100398 100405    0.0
Name: new_cases, dtype: float64
100399 100406    0.0
Name: new_cases, dtype: float64
100400 100407    1.0
Name: new_cases, dtype: float64
100401 100408    0.0
Name: new_cases, dtype: float64
100402 100409    1.0
Name: new_cases, dtype: float64
100403 100410    0.0
Name: new_cases, dtype: float64
100404 100411    0.0
Name: new_cases, dtype: float64
100405 100412    0.0
Name: new_cases, dtype: float64
100406 100413    0.0
Name: new_cases, dtype: float64
100407 100414    0.0
Name: new_cases, dtype: float64
100408 100415    0.0
Name: new_cases, dtype: float64
100409 100416    9.0
Name: new_cases, dtype: float64
100410 100417    0.0
Name: new_cases, dtype: float64
100411 100418    0.0
Name: new_cases, dtype: float64
100412 100419    0.0
Name: new_cases, dtype: float64
100413 100420    0.0
Name: new_cases, dtype: float64
100414 100421    0.0
Name: new_cases, dtype: float64
100415 100422    0.0
Name: new_cases, dtype: float64
100416 100423    229.0
Name: new_cases, dtype: float64
100417 100424    0.0
Name: new_cases, dtype: float64
100418 100425    25.0
Name: new_cases, dtype: float64
100419 100426    0.0
Name: new_cases, dtype: float64
100420 100427    0.0
Name: new_cases, dtype: float64
100421 100428    0.0
Name: new_cases, dtype: float64
100422 100429    0.0
Name: new_cases, dtype: float64
100423 100430    480.0
Name: new_cases, dtype: float64
100424 100431    0.0
Name: new_cases, dtype: float64
100425 100432    0.0
Name: new_cases, dtype: float64
100426 100433    0.0
Name: new_cases, dtype: float64
100427 100434    0.0
Name: new_cases, dtype: float64
100428 100435    0.0
Name: new_cases, dtype: float64
100429 100436    0.0
Name: new_cases, dtype: float64
100430 100437    359.0
Name: new_cases, dtype: float64
100431 100438    0.0
Name: new_cases, dtype: float64
100432 100439    0.0
Name: new_cases, dtype: float64
100433 100440    0.0
Name: new_cases, dtype: float64
100434 100441    0.0
Name: new_cases, dtype: float64
100435 100442    0.0
Name: new_cases, dtype: float64
100436 100443    0.0
Name: new_cases, dtype: float64
100437 100444    346.0
Name: new_cases, dtype: float64
100438 100445    0.0
Name: new_cases, dtype: float64
100439 100446    0.0
Name: new_cases, dtype: float64
100440 100447    0.0
Name: new_cases, dtype: float64
100441 100448    0.0
Name: new_cases, dtype: float64
100442 100449    0.0
Name: new_cases, dtype: float64
100443 100450    0.0
Name: new_cases, dtype: float64
100444 100451    359.0
Name: new_cases, dtype: float64
100445 100452    0.0
Name: new_cases, dtype: float64
100446 100453    0.0
Name: new_cases, dtype: float64
100447 100454    0.0
Name: new_cases, dtype: float64
100448 100455    0.0
Name: new_cases, dtype: float64
100449 100456    0.0
Name: new_cases, dtype: float64
100450 100457    0.0
Name: new_cases, dtype: float64
100451 100458    347.0
Name: new_cases, dtype: float64
100452 100459    0.0
Name: new_cases, dtype: float64
100453 100460    0.0
Name: new_cases, dtype: float64
100454 100461    0.0
Name: new_cases, dtype: float64
100455 100462    0.0
Name: new_cases, dtype: float64
100456 100463    0.0
Name: new_cases, dtype: float64
100457 100464    0.0
Name: new_cases, dtype: float64
100458 100465    349.0
Name: new_cases, dtype: float64
100459 100466    0.0
Name: new_cases, dtype: float64
100460 100467    0.0
Name: new_cases, dtype: float64
100461 100468    0.0
Name: new_cases, dtype: float64
100462 100469    0.0
Name: new_cases, dtype: float64
100463 100470    0.0
Name: new_cases, dtype: float64
100464 100471    0.0
Name: new_cases, dtype: float64
100465 100472    327.0
Name: new_cases, dtype: float64
100466 100473    0.0
Name: new_cases, dtype: float64
100467 100474    0.0
Name: new_cases, dtype: float64
100468 100475    0.0
Name: new_cases, dtype: float64
100469 100476    0.0
Name: new_cases, dtype: float64
100470 100477    0.0
Name: new_cases, dtype: float64
100471 100478    0.0
Name: new_cases, dtype: float64
100472 100479    301.0
Name: new_cases, dtype: float64
100473 100480    0.0
Name: new_cases, dtype: float64
100474 100481    0.0
Name: new_cases, dtype: float64
100475 100482    0.0
Name: new_cases, dtype: float64
100476 100483    0.0
Name: new_cases, dtype: float64
100477 100484    0.0
Name: new_cases, dtype: float64
100478 100485    0.0
Name: new_cases, dtype: float64
100479 100486    292.0
Name: new_cases, dtype: float64
100480 100487    0.0
Name: new_cases, dtype: float64
100481 100488    0.0
Name: new_cases, dtype: float64
100482 100489    0.0
Name: new_cases, dtype: float64
100483 100490    0.0
Name: new_cases, dtype: float64
100484 100491    0.0
Name: new_cases, dtype: float64
100485 100492    0.0
Name: new_cases, dtype: float64
100486 100493    233.0
Name: new_cases, dtype: float64
100487 100494    0.0
Name: new_cases, dtype: float64
100488 100495    0.0
Name: new_cases, dtype: float64
100489 100496    0.0
Name: new_cases, dtype: float64
100490 100497    0.0
Name: new_cases, dtype: float64
100491 100498    0.0
Name: new_cases, dtype: float64
100492 100499    0.0
Name: new_cases, dtype: float64
100493 100500    230.0
Name: new_cases, dtype: float64
100494 100501    0.0
Name: new_cases, dtype: float64
100495 100502    0.0
Name: new_cases, dtype: float64
100496 100503    0.0
Name: new_cases, dtype: float64
100497 100504    0.0
Name: new_cases, dtype: float64
100498 100505    0.0
Name: new_cases, dtype: float64
100499 100506    0.0
Name: new_cases, dtype: float64
100500 100507    213.0
Name: new_cases, dtype: float64
100501 100508    0.0
Name: new_cases, dtype: float64
100502 100509    0.0
Name: new_cases, dtype: float64
100503 100510    0.0
Name: new_cases, dtype: float64
100504 100511    0.0
Name: new_cases, dtype: float64
100505 100512    0.0
Name: new_cases, dtype: float64
100506 100513    0.0
Name: new_cases, dtype: float64
100507 100514    196.0
Name: new_cases, dtype: float64
100508 100515    0.0
Name: new_cases, dtype: float64
100509 100516    0.0
Name: new_cases, dtype: float64
100510 100517    0.0
Name: new_cases, dtype: float64
100511 100518    0.0
Name: new_cases, dtype: float64
100512 100519    0.0
Name: new_cases, dtype: float64
100513 100520    0.0
Name: new_cases, dtype: float64
100514 100521    183.0
Name: new_cases, dtype: float64
100515 100522    0.0
Name: new_cases, dtype: float64
100516 100523    0.0
Name: new_cases, dtype: float64
100517 100524    0.0
Name: new_cases, dtype: float64
100518 100525    0.0
Name: new_cases, dtype: float64
100519 100526    0.0
Name: new_cases, dtype: float64
100520 100527    0.0
Name: new_cases, dtype: float64
100521 100528    174.0
Name: new_cases, dtype: float64
100522 100529    0.0
Name: new_cases, dtype: float64
100523 100530    0.0
Name: new_cases, dtype: float64
100524 100531    0.0
Name: new_cases, dtype: float64
100525 100532    0.0
Name: new_cases, dtype: float64
100526 100533    0.0
Name: new_cases, dtype: float64
100527 100534    0.0
Name: new_cases, dtype: float64
100528 100535    150.0
Name: new_cases, dtype: float64
100529 100536    0.0
Name: new_cases, dtype: float64
100530 100537    0.0
Name: new_cases, dtype: float64
100531 100538    0.0
Name: new_cases, dtype: float64
100532 100539    0.0
Name: new_cases, dtype: float64
100533 100540    0.0
Name: new_cases, dtype: float64
100534 100541    0.0
Name: new_cases, dtype: float64
100535 100542    143.0
Name: new_cases, dtype: float64
100536 100543    0.0
Name: new_cases, dtype: float64
100537 100544    0.0
Name: new_cases, dtype: float64
100538 100545    0.0
Name: new_cases, dtype: float64
100539 100546    0.0
Name: new_cases, dtype: float64
100540 100547    0.0
Name: new_cases, dtype: float64
100541 100548    0.0
Name: new_cases, dtype: float64
100542 100549    112.0
Name: new_cases, dtype: float64
100543 100550    0.0
Name: new_cases, dtype: float64

100544 100551    0.0
Name: new_cases, dtype: float64
100545 100552    0.0
Name: new_cases, dtype: float64
100546 100553    0.0
Name: new_cases, dtype: float64
100547 100554    0.0
Name: new_cases, dtype: float64
100548 100555    0.0
Name: new_cases, dtype: float64
100549 100556    97.0
Name: new_cases, dtype: float64
100550 100557    0.0
Name: new_cases, dtype: float64
100551 100558    0.0
Name: new_cases, dtype: float64
100552 100559    0.0
Name: new_cases, dtype: float64
100553 100560    0.0
Name: new_cases, dtype: float64
100554 100561    0.0
Name: new_cases, dtype: float64
100555 100562    0.0
Name: new_cases, dtype: float64
100556 100563    94.0
Name: new_cases, dtype: float64
100557 100564    0.0
Name: new_cases, dtype: float64
100558 100565    0.0
Name: new_cases, dtype: float64
100559 100566    0.0
Name: new_cases, dtype: float64
100560 100567    0.0
Name: new_cases, dtype: float64
100561 100568    0.0
Name: new_cases, dtype: float64
100562 100569    0.0
Name: new_cases, dtype: float64
100563 100570    89.0
Name: new_cases, dtype: float64
100564 100571    0.0
Name: new_cases, dtype: float64
100565 100572    0.0
Name: new_cases, dtype: float64
100566 100573    0.0
Name: new_cases, dtype: float64
100567 100574    0.0
Name: new_cases, dtype: float64
100568 100575    0.0
Name: new_cases, dtype: float64
100569 100576    0.0
Name: new_cases, dtype: float64
100570 100577    81.0
Name: new_cases, dtype: float64
100571 100578    0.0
Name: new_cases, dtype: float64
100572 100579    0.0
Name: new_cases, dtype: float64
100573 100580    0.0
Name: new_cases, dtype: float64
100574 100581    0.0
Name: new_cases, dtype: float64
100575 100582    0.0
Name: new_cases, dtype: float64
100576 100583    0.0
Name: new_cases, dtype: float64
100577 100584    80.0
Name: new_cases, dtype: float64
100578 100585    0.0
Name: new_cases, dtype: float64
100579 100586    0.0
Name: new_cases, dtype: float64
100580 100587    0.0
Name: new_cases, dtype: float64
100581 100588    0.0
Name: new_cases, dtype: float64
100582 100589    0.0
Name: new_cases, dtype: float64
100583 100590    0.0
Name: new_cases, dtype: float64
100584 100591    0.0
Name: new_cases, dtype: float64
100585 100592    0.0
Name: new_cases, dtype: float64
100586 100593    77.0
Name: new_cases, dtype: float64
100587 100594    0.0
Name: new_cases, dtype: float64
100588 100595    0.0
Name: new_cases, dtype: float64
100589 100596    0.0
Name: new_cases, dtype: float64
100590 100597    0.0
Name: new_cases, dtype: float64
100591 100598    70.0
Name: new_cases, dtype: float64
100592 100599    0.0
Name: new_cases, dtype: float64
100593 100600    0.0
Name: new_cases, dtype: float64
100594 100601    0.0
Name: new_cases, dtype: float64
100595 100602    0.0
Name: new_cases, dtype: float64
100596 100603    0.0
Name: new_cases, dtype: float64
100597 100604    0.0
Name: new_cases, dtype: float64
100598 100605    64.0
Name: new_cases, dtype: float64
100599 100606    0.0
Name: new_cases, dtype: float64
100600 100607    0.0
Name: new_cases, dtype: float64
100601 100608    0.0
Name: new_cases, dtype: float64
100602 100609    0.0
Name: new_cases, dtype: float64
100603 100610    0.0
Name: new_cases, dtype: float64
100604 100611    0.0
Name: new_cases, dtype: float64
100605 100612    59.0
Name: new_cases, dtype: float64
100606 100613    0.0
Name: new_cases, dtype: float64
100607 100614    0.0
Name: new_cases, dtype: float64
100608 100615    0.0
Name: new_cases, dtype: float64
100609 100616    0.0
Name: new_cases, dtype: float64
100610 100617    0.0
Name: new_cases, dtype: float64
100611 100618    0.0
Name: new_cases, dtype: float64
100612 100619    54.0
Name: new_cases, dtype: float64
100613 100620    0.0
Name: new_cases, dtype: float64
100614 100621    0.0
Name: new_cases, dtype: float64
100615 100622    0.0
Name: new_cases, dtype: float64
100616 100623    0.0
Name: new_cases, dtype: float64
100617 100624    0.0
Name: new_cases, dtype: float64
100618 100625    0.0
Name: new_cases, dtype: float64
100619 100626    49.0
Name: new_cases, dtype: float64
100620 100627    0.0
Name: new_cases, dtype: float64
100621 100628    0.0
Name: new_cases, dtype: float64
100622 100629    0.0
Name: new_cases, dtype: float64
100623 100630    0.0
Name: new_cases, dtype: float64
100624 100631    0.0
Name: new_cases, dtype: float64
100625 100632    0.0
Name: new_cases, dtype: float64
100626 100633    0.0
Name: new_cases, dtype: float64
100627 100634    51.0
Name: new_cases, dtype: float64
100628 100635    0.0
Name: new_cases, dtype: float64
100629 100636    0.0
Name: new_cases, dtype: float64
100630 100637    0.0
Name: new_cases, dtype: float64
100631 100638    0.0
Name: new_cases, dtype: float64
100632 100639    0.0
Name: new_cases, dtype: float64
100633 100640    0.0
Name: new_cases, dtype: float64
100634 100641    53.0
Name: new_cases, dtype: float64
100635 100642    0.0
Name: new_cases, dtype: float64
100636 100643    0.0
Name: new_cases, dtype: float64
100637 100644    0.0
Name: new_cases, dtype: float64
100638 100645    0.0
Name: new_cases, dtype: float64
100639 100646    0.0
Name: new_cases, dtype: float64
100640 100647    55.0
Name: new_cases, dtype: float64
100641 100648    0.0
Name: new_cases, dtype: float64
100642 100649    0.0
Name: new_cases, dtype: float64
100643 100650    0.0
Name: new_cases, dtype: float64
100644 100651    0.0
Name: new_cases, dtype: float64
100645 100652    0.0
Name: new_cases, dtype: float64
100646 100653    0.0
Name: new_cases, dtype: float64
100647 100654    51.0
Name: new_cases, dtype: float64
100648 100655    0.0
Name: new_cases, dtype: float64
100649 100656    0.0
Name: new_cases, dtype: float64
100650 100657    0.0
Name: new_cases, dtype: float64
100651 100658    0.0
Name: new_cases, dtype: float64
100652 100659    0.0
Name: new_cases, dtype: float64
100653 100660    0.0
Name: new_cases, dtype: float64
100654 100661    55.0
Name: new_cases, dtype: float64
100655 100662    0.0
Name: new_cases, dtype: float64
100656 100663    0.0
Name: new_cases, dtype: float64
100657 100664    0.0
Name: new_cases, dtype: float64
100658 100665    0.0
Name: new_cases, dtype: float64
100659 100666    0.0
Name: new_cases, dtype: float64
100660 100667    0.0
Name: new_cases, dtype: float64
100661 100668    52.0
Name: new_cases, dtype: float64
100662 100669    0.0
Name: new_cases, dtype: float64
100663 100670    0.0
Name: new_cases, dtype: float64
100664 100671    0.0
Name: new_cases, dtype: float64
100665 100672    0.0
Name: new_cases, dtype: float64
100666 100673    0.0
Name: new_cases, dtype: float64
100667 100674    0.0
Name: new_cases, dtype: float64
100668 100675    49.0
Name: new_cases, dtype: float64
100669 100676    0.0
Name: new_cases, dtype: float64
100670 100677    0.0
Name: new_cases, dtype: float64
100671 100678    0.0
Name: new_cases, dtype: float64
100672 100679    0.0
Name: new_cases, dtype: float64
100673 100680    0.0
Name: new_cases, dtype: float64
100674 100681    0.0
Name: new_cases, dtype: float64
100675 100682    46.0
Name: new_cases, dtype: float64
100676 100683    0.0
Name: new_cases, dtype: float64
100677 100684    0.0
Name: new_cases, dtype: float64
100678 100685    0.0
Name: new_cases, dtype: float64
100679 100686    0.0
Name: new_cases, dtype: float64
100680 100687    0.0
Name: new_cases, dtype: float64
100681 100688    0.0
Name: new_cases, dtype: float64
100682 100689    48.0
Name: new_cases, dtype: float64
100683 100690    0.0
Name: new_cases, dtype: float64
100684 100691    0.0
Name: new_cases, dtype: float64
100685 100692    0.0
Name: new_cases, dtype: float64
100686 100693    0.0
Name: new_cases, dtype: float64
100687 100694    0.0
Name: new_cases, dtype: float64
100688 100695    0.0
Name: new_cases, dtype: float64
100689 100696    51.0
Name: new_cases, dtype: float64
100690 100697    0.0
Name: new_cases, dtype: float64
100691 100698    0.0
Name: new_cases, dtype: float64
100692 100699    0.0
Name: new_cases, dtype: float64
100693 100700    0.0
Name: new_cases, dtype: float64
100694 100701    0.0
Name: new_cases, dtype: float64
100695 100702    0.0
Name: new_cases, dtype: float64
100696 100703    47.0
Name: new_cases, dtype: float64
100697 100704    0.0
Name: new_cases, dtype: float64
100698 100705    0.0
Name: new_cases, dtype: float64
100699 100706    0.0
Name: new_cases, dtype: float64
100700 100707    0.0
Name: new_cases, dtype: float64

100701 100708    0.0
Name: new_cases, dtype: float64
100702 100709    0.0
Name: new_cases, dtype: float64
100703 100710    44.0
Name: new_cases, dtype: float64
100704 100711    0.0
Name: new_cases, dtype: float64
100705 100712    0.0
Name: new_cases, dtype: float64
100706 100713    0.0
Name: new_cases, dtype: float64
100707 100714    0.0
Name: new_cases, dtype: float64
100708 100715    0.0
Name: new_cases, dtype: float64
100709 100716    0.0
Name: new_cases, dtype: float64
100710 100717    48.0
Name: new_cases, dtype: float64
100711 100718    0.0
Name: new_cases, dtype: float64
100712 100719    0.0
Name: new_cases, dtype: float64
100713 100720    0.0
Name: new_cases, dtype: float64
100714 100721    0.0
Name: new_cases, dtype: float64
100715 100722    0.0
Name: new_cases, dtype: float64
100716 100723    0.0
Name: new_cases, dtype: float64
100717 100724    45.0
Name: new_cases, dtype: float64
100718 100725    0.0
Name: new_cases, dtype: float64
100719 100726    0.0
Name: new_cases, dtype: float64
100720 100727    0.0
Name: new_cases, dtype: float64
100721 100728    0.0
Name: new_cases, dtype: float64
100722 100729    0.0
Name: new_cases, dtype: float64
100723 100730    0.0
Name: new_cases, dtype: float64
100724 100731    47.0
Name: new_cases, dtype: float64
100725 100732    0.0
Name: new_cases, dtype: float64
100726 100733    0.0
Name: new_cases, dtype: float64
100727 100734    0.0
Name: new_cases, dtype: float64
100728 100735    0.0
Name: new_cases, dtype: float64
100729 100736    0.0
Name: new_cases, dtype: float64
100730 100737    0.0
Name: new_cases, dtype: float64
100731 100738    48.0
Name: new_cases, dtype: float64
100732 100739    0.0
Name: new_cases, dtype: float64
100733 100740    0.0
Name: new_cases, dtype: float64
100734 100741    0.0
Name: new_cases, dtype: float64
100735 100742    0.0
Name: new_cases, dtype: float64
100736 100743    0.0
Name: new_cases, dtype: float64
100737 100744    0.0
Name: new_cases, dtype: float64
100738 100745    50.0
Name: new_cases, dtype: float64
100739 100746    0.0
Name: new_cases, dtype: float64
100740 100747    0.0
Name: new_cases, dtype: float64
100741 100748    0.0
Name: new_cases, dtype: float64
100742 100749    0.0
Name: new_cases, dtype: float64
100743 100750    0.0
Name: new_cases, dtype: float64
100744 100751    0.0
Name: new_cases, dtype: float64
100745 100752    51.0
Name: new_cases, dtype: float64
100746 100753    0.0
Name: new_cases, dtype: float64
100747 100754    0.0
Name: new_cases, dtype: float64
100748 100755    0.0
Name: new_cases, dtype: float64
100749 100756    0.0
Name: new_cases, dtype: float64
100750 100757    0.0
Name: new_cases, dtype: float64
100751 100758    0.0
Name: new_cases, dtype: float64
100752 100759    57.0
Name: new_cases, dtype: float64
100753 100760    0.0
Name: new_cases, dtype: float64
100754 100761    0.0
Name: new_cases, dtype: float64
100755 100762    0.0
Name: new_cases, dtype: float64
100756 100763    0.0
Name: new_cases, dtype: float64
100757 100764    0.0
Name: new_cases, dtype: float64
100758 100765    0.0
Name: new_cases, dtype: float64
100759 100766    63.0
Name: new_cases, dtype: float64
100760 100767    0.0
Name: new_cases, dtype: float64
100761 100768    0.0
Name: new_cases, dtype: float64
100762 100769    0.0
Name: new_cases, dtype: float64
100763 100770    0.0
Name: new_cases, dtype: float64
100764 100771    0.0
Name: new_cases, dtype: float64
100765 100772    0.0
Name: new_cases, dtype: float64
100766 100773    91.0
Name: new_cases, dtype: float64
100767 100774    0.0
Name: new_cases, dtype: float64
100768 100775    0.0
Name: new_cases, dtype: float64
100769 100776    0.0
Name: new_cases, dtype: float64
100770 100777    0.0
Name: new_cases, dtype: float64
100771 100778    0.0
Name: new_cases, dtype: float64
100772 100779    0.0
Name: new_cases, dtype: float64
100773 100780    97.0
Name: new_cases, dtype: float64
100774 100781    0.0
Name: new_cases, dtype: float64
100775 100782    0.0
Name: new_cases, dtype: float64
100776 100783    0.0
Name: new_cases, dtype: float64
100777 100784    0.0
Name: new_cases, dtype: float64
100778 100785    0.0
Name: new_cases, dtype: float64
100779 100786    0.0
Name: new_cases, dtype: float64
100780 100787    107.0
Name: new_cases, dtype: float64
100781 100788    0.0
Name: new_cases, dtype: float64
100782 100789    0.0
Name: new_cases, dtype: float64
100783 100790    0.0
Name: new_cases, dtype: float64
100784 100791    0.0
Name: new_cases, dtype: float64
100785 100792    0.0
Name: new_cases, dtype: float64
100786 100793    0.0
Name: new_cases, dtype: float64
100787 100794    131.0
Name: new_cases, dtype: float64
100788 100795    0.0
Name: new_cases, dtype: float64
100789 100796    0.0
Name: new_cases, dtype: float64
100790 100797    0.0
Name: new_cases, dtype: float64
100791 100798    0.0
Name: new_cases, dtype: float64
100792 100799    0.0
Name: new_cases, dtype: float64
100793 100800    0.0
Name: new_cases, dtype: float64
100794 100801    157.0
Name: new_cases, dtype: float64
100795 100802    0.0
Name: new_cases, dtype: float64
100796 100803    0.0
Name: new_cases, dtype: float64
100797 100804    0.0
Name: new_cases, dtype: float64
100798 100805    0.0
Name: new_cases, dtype: float64
100799 100806    0.0
Name: new_cases, dtype: float64
100800 100807    0.0
Name: new_cases, dtype: float64
100801 100808    181.0
Name: new_cases, dtype: float64
100802 100809    0.0
Name: new_cases, dtype: float64
100803 100810    0.0
Name: new_cases, dtype: float64
100804 100811    0.0
Name: new_cases, dtype: float64
100805 100812    0.0
Name: new_cases, dtype: float64
100806 100813    0.0
Name: new_cases, dtype: float64
100807 100814    0.0
Name: new_cases, dtype: float64
100808 100815    34.0
Name: new_cases, dtype: float64
100809 100816    0.0
Name: new_cases, dtype: float64
100810 100817    0.0
Name: new_cases, dtype: float64
100811 100818    0.0
Name: new_cases, dtype: float64
100812 100819    0.0
Name: new_cases, dtype: float64
100813 100820    0.0
Name: new_cases, dtype: float64
100814 100821    0.0
Name: new_cases, dtype: float64
100815 100822    224.0
Name: new_cases, dtype: float64
100816 100823    0.0
Name: new_cases, dtype: float64
100817 100824    0.0
Name: new_cases, dtype: float64
100818 100825    0.0
Name: new_cases, dtype: float64
100819 100826    0.0
Name: new_cases, dtype: float64
100820 100827    0.0
Name: new_cases, dtype: float64
100821 100828    0.0
Name: new_cases, dtype: float64
100822 100829    258.0
Name: new_cases, dtype: float64
100823 100830    0.0
Name: new_cases, dtype: float64
100824 100831    0.0
Name: new_cases, dtype: float64
100825 100832    0.0
Name: new_cases, dtype: float64
100826 100833    0.0
Name: new_cases, dtype: float64
100827 100834    0.0
Name: new_cases, dtype: float64
100828 100835    0.0
Name: new_cases, dtype: float64
100829 100836    283.0
Name: new_cases, dtype: float64
100830 100837    0.0
Name: new_cases, dtype: float64
100831 100838    0.0
Name: new_cases, dtype: float64
100832 100839    0.0
Name: new_cases, dtype: float64
100833 100840    0.0
Name: new_cases, dtype: float64
100834 100841    0.0
Name: new_cases, dtype: float64
100835 100842    0.0
Name: new_cases, dtype: float64
100836 100843    306.0
Name: new_cases, dtype: float64
100837 100844    0.0
Name: new_cases, dtype: float64
100838 100845    0.0
Name: new_cases, dtype: float64
100839 100846    0.0
Name: new_cases, dtype: float64
100840 100847    0.0
Name: new_cases, dtype: float64
100841 100848    0.0
Name: new_cases, dtype: float64
100842 100849    0.0
Name: new_cases, dtype: float64
100843 100850    341.0
Name: new_cases, dtype: float64
100844 100851    0.0
Name: new_cases, dtype: float64
100845 100852    0.0
Name: new_cases, dtype: float64
100846 100853    0.0
Name: new_cases, dtype: float64
100847 100854    0.0
Name: new_cases, dtype: float64
100848 100855    0.0
Name: new_cases, dtype: float64
100849 100856    0.0
Name: new_cases, dtype: float64
100850 100857    362.0
Name: new_cases, dtype: float64
100851 100858    0.0
Name: new_cases, dtype: float64
100852 100859    0.0
Name: new_cases, dtype: float64
100853 100860    0.0
Name: new_cases, dtype: float64
100854 100861    0.0
Name: new_cases, dtype: float64
100855 100862    0.0
Name: new_cases, dtype: float64
100856 100863    0.0
Name: new_cases, dtype: float64
100857 100864    383.0
Name: new_cases, dtype: float64
100858 100865    0.0
Name: new_cases, dtype: float64
100859 100866    0.0
Name: new_cases, dtype: float64
100860 100867    0.0
Name: new_cases, dtype: float64
100861 100868    0.0
Name: new_cases, dtype: float64

100862 100869    0.0
Name: new_cases, dtype: float64
100863 100870    0.0
Name: new_cases, dtype: float64
100864 100871    398.0
Name: new_cases, dtype: float64
100865 100872    0.0
Name: new_cases, dtype: float64
100866 100873    0.0
Name: new_cases, dtype: float64
100867 100874    0.0
Name: new_cases, dtype: float64
100868 100875    0.0
Name: new_cases, dtype: float64
100869 100876    0.0
Name: new_cases, dtype: float64
100870 100877    0.0
Name: new_cases, dtype: float64
100871 100878    0.0
Name: new_cases, dtype: float64
100872 100879    0.0
Name: new_cases, dtype: float64
100873 100880    421.0
Name: new_cases, dtype: float64
100874 100881    0.0
Name: new_cases, dtype: float64
100875 100882    0.0
Name: new_cases, dtype: float64
100876 100883    0.0
Name: new_cases, dtype: float64
100877 100884    0.0
Name: new_cases, dtype: float64
100878 100885    495.0
Name: new_cases, dtype: float64
100879 100886    0.0
Name: new_cases, dtype: float64
100880 100887    0.0
Name: new_cases, dtype: float64
100881 100888    0.0
Name: new_cases, dtype: float64
100882 100889    0.0
Name: new_cases, dtype: float64
100883 100890    0.0
Name: new_cases, dtype: float64
100884 100891    0.0
Name: new_cases, dtype: float64
100885 100892    568.0
Name: new_cases, dtype: float64
100886 100893    0.0
Name: new_cases, dtype: float64
100887 100894    0.0
Name: new_cases, dtype: float64
100888 100895    0.0
Name: new_cases, dtype: float64
100889 100896    0.0
Name: new_cases, dtype: float64
100890 100897    0.0
Name: new_cases, dtype: float64
100891 100898    0.0
Name: new_cases, dtype: float64
100892 100899    615.0
Name: new_cases, dtype: float64
100893 100900    0.0
Name: new_cases, dtype: float64
100894 100901    0.0
Name: new_cases, dtype: float64
100895 100902    0.0
Name: new_cases, dtype: float64
100896 100903    0.0
Name: new_cases, dtype: float64
100897 100904    0.0
Name: new_cases, dtype: float64
100898 100905    0.0
Name: new_cases, dtype: float64
100899 100906    675.0
Name: new_cases, dtype: float64
100900 100907    0.0
Name: new_cases, dtype: float64
100901 100908    0.0
Name: new_cases, dtype: float64
100902 100909    0.0
Name: new_cases, dtype: float64
100903 100910    0.0
Name: new_cases, dtype: float64
100904 100911    0.0
Name: new_cases, dtype: float64
100905 100912    0.0
Name: new_cases, dtype: float64
100906 100913    705.0
Name: new_cases, dtype: float64
100907 100914    0.0
Name: new_cases, dtype: float64
100908 100915    0.0
Name: new_cases, dtype: float64
100909 100916    0.0
Name: new_cases, dtype: float64
100910 100917    0.0
Name: new_cases, dtype: float64
100911 100918    0.0
Name: new_cases, dtype: float64
100912 100919    0.0
Name: new_cases, dtype: float64
100913 100920    718.0
Name: new_cases, dtype: float64
100914 100921    0.0
Name: new_cases, dtype: float64
100915 100922    0.0
Name: new_cases, dtype: float64
100916 100923    0.0
Name: new_cases, dtype: float64
100917 100924    0.0
Name: new_cases, dtype: float64
100918 100925    0.0
Name: new_cases, dtype: float64
100919 100926    0.0
Name: new_cases, dtype: float64
100920 100927    686.0
Name: new_cases, dtype: float64
100921 100928    0.0
Name: new_cases, dtype: float64
100922 100929    0.0
Name: new_cases, dtype: float64
100923 100930    0.0
Name: new_cases, dtype: float64
100924 100931    0.0
Name: new_cases, dtype: float64
100925 100932    0.0
Name: new_cases, dtype: float64
100926 100933    0.0
Name: new_cases, dtype: float64
100927 100934    603.0
Name: new_cases, dtype: float64
100928 100935    0.0
Name: new_cases, dtype: float64
100929 100936    0.0
Name: new_cases, dtype: float64
100930 100937    0.0
Name: new_cases, dtype: float64
100931 100938    0.0
Name: new_cases, dtype: float64
100932 100939    0.0
Name: new_cases, dtype: float64
100933 100940    0.0
Name: new_cases, dtype: float64
100934 100941    504.0
Name: new_cases, dtype: float64
100935 100942    0.0
Name: new_cases, dtype: float64
100936 100943    0.0
Name: new_cases, dtype: float64
100937 100944    0.0
Name: new_cases, dtype: float64
100938 100945    0.0
Name: new_cases, dtype: float64
100939 100946    0.0
Name: new_cases, dtype: float64
100940 100947    0.0
Name: new_cases, dtype: float64
100941 100948    181.0
Name: new_cases, dtype: float64
100942 100949    0.0
Name: new_cases, dtype: float64
100943 100950    0.0
Name: new_cases, dtype: float64
100944 100951    0.0
Name: new_cases, dtype: float64
100945 100952    0.0
Name: new_cases, dtype: float64
100946 100953    0.0
Name: new_cases, dtype: float64
100947 100954    0.0
Name: new_cases, dtype: float64
100948 100955    277.0
Name: new_cases, dtype: float64
100949 100956    0.0
Name: new_cases, dtype: float64
100950 100957    0.0
Name: new_cases, dtype: float64
100951 100958    0.0
Name: new_cases, dtype: float64
100952 100959    0.0
Name: new_cases, dtype: float64
100953 100960    0.0
Name: new_cases, dtype: float64
100954 100961    0.0
Name: new_cases, dtype: float64
100955 100962    0.0
Name: new_cases, dtype: float64
100956 100963    178.0
Name: new_cases, dtype: float64
100957 100964    0.0
Name: new_cases, dtype: float64
100958 100965    0.0
Name: new_cases, dtype: float64
100959 100966    0.0
Name: new_cases, dtype: float64
100960 100967    0.0
Name: new_cases, dtype: float64
100961 100968    0.0
Name: new_cases, dtype: float64
100962 100969    146.0
Name: new_cases, dtype: float64
100963 100970    0.0
Name: new_cases, dtype: float64
100964 100971    0.0
Name: new_cases, dtype: float64
100965 100972    0.0
Name: new_cases, dtype: float64
100966 100973    0.0
Name: new_cases, dtype: float64
100967 100974    0.0
Name: new_cases, dtype: float64
100968 100975    0.0
Name: new_cases, dtype: float64
100969 100976    129.0
Name: new_cases, dtype: float64
100970 100977    0.0
Name: new_cases, dtype: float64
100971 100978    0.0
Name: new_cases, dtype: float64
100972 100979    0.0
Name: new_cases, dtype: float64
100973 100980    0.0
Name: new_cases, dtype: float64
100974 100981    0.0
Name: new_cases, dtype: float64
100975 100982    0.0
Name: new_cases, dtype: float64
100976 100983    102.0
Name: new_cases, dtype: float64
100977 100984    0.0
Name: new_cases, dtype: float64
100978 100985    0.0
Name: new_cases, dtype: float64
100979 100986    0.0
Name: new_cases, dtype: float64
100980 100987    0.0
Name: new_cases, dtype: float64
100981 100988    0.0
Name: new_cases, dtype: float64
100982 100989    0.0
Name: new_cases, dtype: float64
100983 100990    74.0
Name: new_cases, dtype: float64
100984 100991    0.0
Name: new_cases, dtype: float64
100985 100992    0.0
Name: new_cases, dtype: float64
100986 100993    0.0
Name: new_cases, dtype: float64
100987 100994    0.0
Name: new_cases, dtype: float64
100988 100995    0.0
Name: new_cases, dtype: float64
100989 100996    0.0
Name: new_cases, dtype: float64
100990 100997    63.0
Name: new_cases, dtype: float64
100991 100998    0.0
Name: new_cases, dtype: float64
100992 100999    0.0
Name: new_cases, dtype: float64
100993 101000    0.0
Name: new_cases, dtype: float64
100994 101001    0.0
Name: new_cases, dtype: float64
100995 101002    0.0
Name: new_cases, dtype: float64
100996 101003    0.0
Name: new_cases, dtype: float64
100997 101004    51.0
Name: new_cases, dtype: float64
100998 101005    0.0
Name: new_cases, dtype: float64
100999 101006    0.0
Name: new_cases, dtype: float64
101000 101007    0.0
Name: new_cases, dtype: float64
101001 101008    0.0
Name: new_cases, dtype: float64
101002 101009    0.0
Name: new_cases, dtype: float64
101003 101010    0.0
Name: new_cases, dtype: float64
101004 101011    45.0
Name: new_cases, dtype: float64
101005 101012    0.0
Name: new_cases, dtype: float64
101006 101013    0.0
Name: new_cases, dtype: float64
101007 101014    0.0
Name: new_cases, dtype: float64
101008 101015    0.0
Name: new_cases, dtype: float64
101009 101016    0.0
Name: new_cases, dtype: float64
101010 101017    0.0
Name: new_cases, dtype: float64
101011 101018    39.0
Name: new_cases, dtype: float64
101012 101019    0.0
Name: new_cases, dtype: float64
101013 101020    0.0
Name: new_cases, dtype: float64
101014 101021    0.0
Name: new_cases, dtype: float64
101015 101022    0.0
Name: new_cases, dtype: float64
101016 Series([], Name: new_cases, dtype: float64)
101017 Series([], Name: new_cases, dtype: float64)
101018 Series([], Name: new_cases, dtype: float64)
101019 Series([], Name: new_cases, dtype: float64)
101020 Series([], Name: new_cases, dtype: float64)
101021 Series([], Name: new_cases, dtype: float64)
101022 Series([], Name: new_cases, dtype: float64)
101683 101690    0.0
Name: new_cases, dtype: float64
101684 101691    0.0
Name: new_cases, dtype: float64
101685 101692    0.0
Name: new_cases, dtype: float64
101686 101693    1.0
Name: new_cases, dtype: float64

101687 101694    0.0
Name: new_cases, dtype: float64
101688 101695    0.0
Name: new_cases, dtype: float64
101689 101696    0.0
Name: new_cases, dtype: float64
101690 101697    0.0
Name: new_cases, dtype: float64
101691 101698    0.0
Name: new_cases, dtype: float64
101692 101699    0.0
Name: new_cases, dtype: float64
101693 101700    0.0
Name: new_cases, dtype: float64
101694 101701    1.0
Name: new_cases, dtype: float64
101695 101702    5.0
Name: new_cases, dtype: float64
101696 101703    0.0
Name: new_cases, dtype: float64
101697 101704    4.0
Name: new_cases, dtype: float64
101698 101705    10.0
Name: new_cases, dtype: float64
101699 101706    8.0
Name: new_cases, dtype: float64
101700 101707    10.0
Name: new_cases, dtype: float64
101701 101708    4.0
Name: new_cases, dtype: float64
101702 101709    7.0
Name: new_cases, dtype: float64
101703 101710    14.0
Name: new_cases, dtype: float64
101704 101711    5.0
Name: new_cases, dtype: float64
101705 101712    19.0
Name: new_cases, dtype: float64
101706 101713    22.0
Name: new_cases, dtype: float64
101707 101714    20.0
Name: new_cases, dtype: float64
101708 101715    4.0
Name: new_cases, dtype: float64
101709 101716    39.0
Name: new_cases, dtype: float64
101710 101717    10.0
Name: new_cases, dtype: float64
101711 101718    26.0
Name: new_cases, dtype: float64
101712 101719    4.0
Name: new_cases, dtype: float64
101713 101720    18.0
Name: new_cases, dtype: float64
101714 101721    6.0
Name: new_cases, dtype: float64
101715 101722    16.0
Name: new_cases, dtype: float64
101716 101723    22.0
Name: new_cases, dtype: float64
101717 101724    12.0
Name: new_cases, dtype: float64
101718 101725    17.0
Name: new_cases, dtype: float64
101719 101726    13.0
Name: new_cases, dtype: float64
101720 101727    5.0
Name: new_cases, dtype: float64
101721 101728    20.0
Name: new_cases, dtype: float64
101722 101729    30.0
Name: new_cases, dtype: float64
101723 101730    34.0
Name: new_cases, dtype: float64
101724 101731    35.0
Name: new_cases, dtype: float64
101725 101732    51.0
Name: new_cases, dtype: float64
101726 101733    49.0
Name: new_cases, dtype: float64
101727 101734    85.0
Name: new_cases, dtype: float64
101728 101735    38.0
Name: new_cases, dtype: float64
101729 101736    0.0
Name: new_cases, dtype: float64
101730 101737    208.0
Name: new_cases, dtype: float64
101731 101738    108.0
Name: new_cases, dtype: float64
101732 101739    114.0
Name: new_cases, dtype: float64
101733 101740    87.0
Name: new_cases, dtype: float64
101734 101741    91.0
Name: new_cases, dtype: float64
101735 101742    64.0
Name: new_cases, dtype: float64
101736 101743    195.0
Name: new_cases, dtype: float64
101737 101744    196.0
Name: new_cases, dtype: float64
101738 101745    204.0
Name: new_cases, dtype: float64
101739 101746    238.0
Name: new_cases, dtype: float64
101740 101747    218.0
Name: new_cases, dtype: float64
101741 101748    170.0
Name: new_cases, dtype: float64
101742 101749    244.0
Name: new_cases, dtype: float64
101743 101750    148.0
Name: new_cases, dtype: float64
101744 101751    195.0
Name: new_cases, dtype: float64
101745 101752    381.0
Name: new_cases, dtype: float64
101746 101753    386.0
Name: new_cases, dtype: float64
101747 101754    239.0
Name: new_cases, dtype: float64
101748 101755    248.0
Name: new_cases, dtype: float64
101749 101756    242.0
Name: new_cases, dtype: float64
101750 101757    146.0
Name: new_cases, dtype: float64
101751 101758    184.0
Name: new_cases, dtype: float64
101752 101759    191.0
Name: new_cases, dtype: float64
101753 101760    288.0
Name: new_cases, dtype: float64
101754 101761    171.0
Name: new_cases, dtype: float64
101755 101762    338.0
Name: new_cases, dtype: float64
101756 101763    216.0
Name: new_cases, dtype: float64
101757 101764    226.0
Name: new_cases, dtype: float64
101758 101765    276.0
Name: new_cases, dtype: float64
101759 101766    339.0
Name: new_cases, dtype: float64
101760 101767    245.0
Name: new_cases, dtype: float64
101761 101768    265.0
Name: new_cases, dtype: float64
101762 101769    313.0
Name: new_cases, dtype: float64
101763 101770    229.0
Name: new_cases, dtype: float64
101764 101771    276.0
Name: new_cases, dtype: float64
101765 101772    389.0
Name: new_cases, dtype: float64
101766 101773    182.0
Name: new_cases, dtype: float64
101767 101774    387.0
Name: new_cases, dtype: float64
101768 101775    553.0
Name: new_cases, dtype: float64
101769 101776    307.0
Name: new_cases, dtype: float64
101770 101777    416.0
Name: new_cases, dtype: float64
101771 101778    241.0
Name: new_cases, dtype: float64
101772 101779    347.0
Name: new_cases, dtype: float64
101773 101780    350.0
Name: new_cases, dtype: float64
101774 101781    328.0
Name: new_cases, dtype: float64
101775 101782    389.0
Name: new_cases, dtype: float64
101776 101783    253.0
Name: new_cases, dtype: float64
101777 101784    315.0
Name: new_cases, dtype: float64
101778 101785    663.0
Name: new_cases, dtype: float64
101779 101786    409.0
Name: new_cases, dtype: float64
101780 101787    681.0
Name: new_cases, dtype: float64
101781 101788    627.0
Name: new_cases, dtype: float64
101782 101789    501.0
Name: new_cases, dtype: float64
101783 101790    403.0
Name: new_cases, dtype: float64
101784 101791    573.0
Name: new_cases, dtype: float64
101785 101792    490.0
Name: new_cases, dtype: float64
101786 101793    587.0
Name: new_cases, dtype: float64
101787 101794    745.0
Name: new_cases, dtype: float64
101788 101795    667.0
Name: new_cases, dtype: float64
101789 101796    661.0
Name: new_cases, dtype: float64
101790 101797    436.0
Name: new_cases, dtype: float64
101791 101798    675.0
Name: new_cases, dtype: float64
101792 101799    452.0
Name: new_cases, dtype: float64
101793 101800    649.0
Name: new_cases, dtype: float64
101794 101801    594.0
Name: new_cases, dtype: float64
101795 101802    684.0
Name: new_cases, dtype: float64
101796 101803    779.0
Name: new_cases, dtype: float64
101797 101804    490.0
Name: new_cases, dtype: float64
101798 101805    566.0
Name: new_cases, dtype: float64
101799 101806    561.0
Name: new_cases, dtype: float64
101800 101807    790.0
Name: new_cases, dtype: float64
101801 101808    626.0
Name: new_cases, dtype: float64
101802 101809    454.0
Name: new_cases, dtype: float64
101803 101810    603.0
Name: new_cases, dtype: float64
101804 101811    544.0
Name: new_cases, dtype: float64
101805 101812    575.0
Name: new_cases, dtype: float64
101806 101813    503.0
Name: new_cases, dtype: float64
101807 101814    460.0
Name: new_cases, dtype: float64
101808 101815    499.0
Name: new_cases, dtype: float64
101809 101816    575.0
Name: new_cases, dtype: float64
101810 101817    664.0
Name: new_cases, dtype: float64
101811 101818    571.0
Name: new_cases, dtype: float64
101812 101819    595.0
Name: new_cases, dtype: float64
101813 101820    463.0
Name: new_cases, dtype: float64
101814 101821    643.0
Name: new_cases, dtype: float64
101815 101822    595.0
Name: new_cases, dtype: float64
101816 101823    600.0
Name: new_cases, dtype: float64
101817 101824    653.0
Name: new_cases, dtype: float64
101818 101825    556.0
Name: new_cases, dtype: float64
101819 101826    562.0
Name: new_cases, dtype: float64
101820 101827    576.0
Name: new_cases, dtype: float64
101821 101828    543.0
Name: new_cases, dtype: float64
101822 101829    604.0
Name: new_cases, dtype: float64
101823 101830    591.0
Name: new_cases, dtype: float64
101824 101831    438.0
Name: new_cases, dtype: float64
101825 101832    555.0
Name: new_cases, dtype: float64
101826 101833    648.0
Name: new_cases, dtype: float64
101827 101834    624.0
Name: new_cases, dtype: float64
101828 101835    404.0
Name: new_cases, dtype: float64
101829 101836    481.0
Name: new_cases, dtype: float64
101830 101837    462.0
Name: new_cases, dtype: float64
101831 101838    386.0
Name: new_cases, dtype: float64
101832 101839    304.0
Name: new_cases, dtype: float64
101833 101840    288.0
Name: new_cases, dtype: float64
101834 101841    304.0
Name: new_cases, dtype: float64
101835 101842    457.0
Name: new_cases, dtype: float64
101836 101843    354.0
Name: new_cases, dtype: float64
101837 101844    443.0
Name: new_cases, dtype: float64
101838 101845    453.0
Name: new_cases, dtype: float64
101839 101846    437.0
Name: new_cases, dtype: float64
101840 101847    290.0
Name: new_cases, dtype: float64
101841 101848    423.0
Name: new_cases, dtype: float64
101842 101849    453.0
Name: new_cases, dtype: float64
101843 101850    373.0
Name: new_cases, dtype: float64
101844 101851    329.0
Name: new_cases, dtype: float64
101845 101852    325.0
Name: new_cases, dtype: float64
101846 101853    298.0
Name: new_cases, dtype: float64
101847 101854    417.0
Name: new_cases, dtype: float64
101848 101855    410.0
Name: new_cases, dtype: float64
101849 101856    593.0
Name: new_cases, dtype: float64
101850 101857    476.0
Name: new_cases, dtype: float64
101851 101858    340.0
Name: new_cases, dtype: float64
101852 101859    601.0
Name: new_cases, dtype: float64
101853 101860    322.0
Name: new_cases, dtype: float64
101854 101861    321.0
Name: new_cases, dtype: float64
101855 101862    252.0
Name: new_cases, dtype: float64
101856 101863    221.0
Name: new_cases, dtype: float64
101857 101864    296.0
Name: new_cases, dtype: float64

101858 101865    160.0
Name: new_cases, dtype: float64
101859 101866    250.0
Name: new_cases, dtype: float64
101860 101867    138.0
Name: new_cases, dtype: float64
101861 101868    143.0
Name: new_cases, dtype: float64
101862 101869    239.0
Name: new_cases, dtype: float64
101863 101870    216.0
Name: new_cases, dtype: float64
101864 101871    125.0
Name: new_cases, dtype: float64
101865 101872    155.0
Name: new_cases, dtype: float64
101866 101873    162.0
Name: new_cases, dtype: float64
101867 101874    100.0
Name: new_cases, dtype: float64
101868 101875    155.0
Name: new_cases, dtype: float64
101869 101876    296.0
Name: new_cases, dtype: float64
101870 101877    176.0
Name: new_cases, dtype: float64
101871 101878    197.0
Name: new_cases, dtype: float64
101872 101879    188.0
Name: new_cases, dtype: float64
101873 101880    160.0
Name: new_cases, dtype: float64
101874 101881    79.0
Name: new_cases, dtype: float64
101875 101882    132.0
Name: new_cases, dtype: float64
101876 101883    90.0
Name: new_cases, dtype: float64
101877 101884    126.0
Name: new_cases, dtype: float64
101878 101885    131.0
Name: new_cases, dtype: float64
101879 101886    221.0
Name: new_cases, dtype: float64
101880 101887    189.0
Name: new_cases, dtype: float64
101881 101888    97.0
Name: new_cases, dtype: float64
101882 101889    195.0
Name: new_cases, dtype: float64
101883 101890    176.0
Name: new_cases, dtype: float64
101884 101891    111.0
Name: new_cases, dtype: float64
101885 101892    125.0
Name: new_cases, dtype: float64
101886 101893    213.0
Name: new_cases, dtype: float64
101887 101894    136.0
Name: new_cases, dtype: float64
101888 101895    126.0
Name: new_cases, dtype: float64
101889 101896    136.0
Name: new_cases, dtype: float64
101890 101897    187.0
Name: new_cases, dtype: float64
101891 101898    201.0
Name: new_cases, dtype: float64
101892 101899    153.0
Name: new_cases, dtype: float64
101893 101900    126.0
Name: new_cases, dtype: float64
101894 101901    160.0
Name: new_cases, dtype: float64
101895 101902    58.0
Name: new_cases, dtype: float64
101896 101903    120.0
Name: new_cases, dtype: float64
101897 101904    118.0
Name: new_cases, dtype: float64
101898 101905    155.0
Name: new_cases, dtype: float64
101899 101906    103.0
Name: new_cases, dtype: float64
101900 101907    151.0
Name: new_cases, dtype: float64
101901 101908    111.0
Name: new_cases, dtype: float64
101902 101909    163.0
Name: new_cases, dtype: float64
101903 101910    164.0
Name: new_cases, dtype: float64
101904 101911    225.0
Name: new_cases, dtype: float64
101905 101912    179.0
Name: new_cases, dtype: float64
101906 101913    148.0
Name: new_cases, dtype: float64
101907 101914    212.0
Name: new_cases, dtype: float64
101908 101915    113.0
Name: new_cases, dtype: float64
101909 101916    133.0
Name: new_cases, dtype: float64
101910 101917    118.0
Name: new_cases, dtype: float64
101911 101918    72.0
Name: new_cases, dtype: float64
101912 101919    37.0
Name: new_cases, dtype: float64
101913 101920    138.0
Name: new_cases, dtype: float64
101914 101921    77.0
Name: new_cases, dtype: float64
101915 101922    48.0
Name: new_cases, dtype: float64
101916 101923    62.0
Name: new_cases, dtype: float64
101917 101924    119.0
Name: new_cases, dtype: float64
101918 101925    113.0
Name: new_cases, dtype: float64
101919 101926    147.0
Name: new_cases, dtype: float64
101920 101927    150.0
Name: new_cases, dtype: float64
101921 101928    170.0
Name: new_cases, dtype: float64
101922 101929    162.0
Name: new_cases, dtype: float64
101923 101930    111.0
Name: new_cases, dtype: float64
101924 101931    72.0
Name: new_cases, dtype: float64
101925 101932    137.0
Name: new_cases, dtype: float64
101926 101933    155.0
Name: new_cases, dtype: float64
101927 101934    180.0
Name: new_cases, dtype: float64
101928 101935    223.0
Name: new_cases, dtype: float64
101929 101936    59.0
Name: new_cases, dtype: float64
101930 101937    300.0
Name: new_cases, dtype: float64
101931 101938    94.0
Name: new_cases, dtype: float64
101932 101939    152.0
Name: new_cases, dtype: float64
101933 101940    180.0
Name: new_cases, dtype: float64
101934 101941    212.0
Name: new_cases, dtype: float64
101935 101942    156.0
Name: new_cases, dtype: float64
101936 101943    112.0
Name: new_cases, dtype: float64
101937 101944    152.0
Name: new_cases, dtype: float64
101938 101945    157.0
Name: new_cases, dtype: float64
101939 101946    152.0
Name: new_cases, dtype: float64
101940 101947    236.0
Name: new_cases, dtype: float64
101941 101948    146.0
Name: new_cases, dtype: float64
101942 101949    143.0
Name: new_cases, dtype: float64
101943 101950    246.0
Name: new_cases, dtype: float64
101944 101951    155.0
Name: new_cases, dtype: float64
101945 101952    56.0
Name: new_cases, dtype: float64
101946 101953    168.0
Name: new_cases, dtype: float64
101947 101954    198.0
Name: new_cases, dtype: float64
101948 101955    169.0
Name: new_cases, dtype: float64
101949 101956    246.0
Name: new_cases, dtype: float64
101950 101957    110.0
Name: new_cases, dtype: float64
101951 101958    82.0
Name: new_cases, dtype: float64
101952 101959    145.0
Name: new_cases, dtype: float64
101953 101960    281.0
Name: new_cases, dtype: float64
101954 101961    122.0
Name: new_cases, dtype: float64
101955 101962    343.0
Name: new_cases, dtype: float64
101956 101963    324.0
Name: new_cases, dtype: float64
101957 101964    310.0
Name: new_cases, dtype: float64
101958 101965    318.0
Name: new_cases, dtype: float64
101959 101966    390.0
Name: new_cases, dtype: float64
101960 101967    550.0
Name: new_cases, dtype: float64
101961 101968    474.0
Name: new_cases, dtype: float64
101962 101969    675.0
Name: new_cases, dtype: float64
101963 101970    796.0
Name: new_cases, dtype: float64
101964 101971    617.0
Name: new_cases, dtype: float64
101965 101972    418.0
Name: new_cases, dtype: float64
101966 101973    199.0
Name: new_cases, dtype: float64
101967 101974    758.0
Name: new_cases, dtype: float64
101968 101975    930.0
Name: new_cases, dtype: float64
101969 101976    1145.0
Name: new_cases, dtype: float64
101970 101977    806.0
Name: new_cases, dtype: float64
101971 101978    920.0
Name: new_cases, dtype: float64
101972 101979    501.0
Name: new_cases, dtype: float64
101973 101980    356.0
Name: new_cases, dtype: float64
101974 101981    999.0
Name: new_cases, dtype: float64
101975 101982    1133.0
Name: new_cases, dtype: float64
101976 101983    1041.0
Name: new_cases, dtype: float64
101977 101984    784.0
Name: new_cases, dtype: float64
101978 101985    829.0
Name: new_cases, dtype: float64
101979 101986    838.0
Name: new_cases, dtype: float64
101980 101987    397.0
Name: new_cases, dtype: float64
101981 101988    749.0
Name: new_cases, dtype: float64
101982 101989    1016.0
Name: new_cases, dtype: float64
101983 101990    1031.0
Name: new_cases, dtype: float64
101984 101991    980.0
Name: new_cases, dtype: float64
101985 101992    576.0
Name: new_cases, dtype: float64
101986 101993    917.0
Name: new_cases, dtype: float64
101987 101994    1271.0
Name: new_cases, dtype: float64
101988 101995    1354.0
Name: new_cases, dtype: float64
101989 101996    1664.0
Name: new_cases, dtype: float64
101990 101997    1565.0
Name: new_cases, dtype: float64
101991 101998    1544.0
Name: new_cases, dtype: float64
101992 101999    1585.0
Name: new_cases, dtype: float64
101993 102000    1024.0
Name: new_cases, dtype: float64
101994 102001    1244.0
Name: new_cases, dtype: float64
101995 102002    1270.0
Name: new_cases, dtype: float64
101996 102003    1398.0
Name: new_cases, dtype: float64
101997 102004    1479.0
Name: new_cases, dtype: float64
101998 102005    1867.0
Name: new_cases, dtype: float64
101999 102006    1598.0
Name: new_cases, dtype: float64
102000 102007    1444.0
Name: new_cases, dtype: float64
102001 102008    1617.0
Name: new_cases, dtype: float64
102002 102009    1301.0
Name: new_cases, dtype: float64
102003 102010    1386.0
Name: new_cases, dtype: float64
102004 102011    1964.0
Name: new_cases, dtype: float64
102005 102012    1483.0
Name: new_cases, dtype: float64
102006 102013    2464.0
Name: new_cases, dtype: float64
102007 102014    964.0
Name: new_cases, dtype: float64
102008 102015    1430.0
Name: new_cases, dtype: float64
102009 102016    1303.0
Name: new_cases, dtype: float64
102010 102017    1861.0
Name: new_cases, dtype: float64
102011 102018    864.0
Name: new_cases, dtype: float64
102012 102019    1650.0
Name: new_cases, dtype: float64
102013 102020    1883.0
Name: new_cases, dtype: float64
102014 102021    685.0
Name: new_cases, dtype: float64
102015 102022    676.0
Name: new_cases, dtype: float64
102016 102023    1634.0
Name: new_cases, dtype: float64
102017 102024    1138.0
Name: new_cases, dtype: float64
102018 102025    1340.0
Name: new_cases, dtype: float64
102019 102026    1624.0
Name: new_cases, dtype: float64
102020 102027    1588.0
Name: new_cases, dtype: float64
102021 102028    506.0
Name: new_cases, dtype: float64
102022 102029    643.0
Name: new_cases, dtype: float64
102023 102030    1056.0
Name: new_cases, dtype: float64

102024 102031    1131.0
Name: new_cases, dtype: float64
102025 102032    938.0
Name: new_cases, dtype: float64
102026 102033    1005.0
Name: new_cases, dtype: float64
102027 102034    1143.0
Name: new_cases, dtype: float64
102028 102035    520.0
Name: new_cases, dtype: float64
102029 102036    744.0
Name: new_cases, dtype: float64
102030 102037    1368.0
Name: new_cases, dtype: float64
102031 102038    1073.0
Name: new_cases, dtype: float64
102032 102039    877.0
Name: new_cases, dtype: float64
102033 102040    662.0
Name: new_cases, dtype: float64
102034 102041    645.0
Name: new_cases, dtype: float64
102035 102042    521.0
Name: new_cases, dtype: float64
102036 102043    542.0
Name: new_cases, dtype: float64
102037 102044    571.0
Name: new_cases, dtype: float64
102038 102045    655.0
Name: new_cases, dtype: float64
102039 102046    634.0
Name: new_cases, dtype: float64
102040 102047    600.0
Name: new_cases, dtype: float64
102041 102048    341.0
Name: new_cases, dtype: float64
102042 102049    240.0
Name: new_cases, dtype: float64
102043 102050    360.0
Name: new_cases, dtype: float64
102044 102051    479.0
Name: new_cases, dtype: float64
102045 102052    464.0
Name: new_cases, dtype: float64
102046 102053    711.0
Name: new_cases, dtype: float64
102047 102054    371.0
Name: new_cases, dtype: float64
102048 102055    195.0
Name: new_cases, dtype: float64
102049 102056    269.0
Name: new_cases, dtype: float64
102050 102057    400.0
Name: new_cases, dtype: float64
102051 102058    346.0
Name: new_cases, dtype: float64
102052 102059    394.0
Name: new_cases, dtype: float64
102053 102060    287.0
Name: new_cases, dtype: float64
102054 102061    399.0
Name: new_cases, dtype: float64
102055 102062    205.0
Name: new_cases, dtype: float64
102056 102063    120.0
Name: new_cases, dtype: float64
102057 102064    238.0
Name: new_cases, dtype: float64
102058 102065    179.0
Name: new_cases, dtype: float64
102059 102066    187.0
Name: new_cases, dtype: float64
102060 102067    148.0
Name: new_cases, dtype: float64
102061 102068    130.0
Name: new_cases, dtype: float64
102062 102069    112.0
Name: new_cases, dtype: float64
102063 102070    86.0
Name: new_cases, dtype: float64
102064 102071    131.0
Name: new_cases, dtype: float64
102065 102072    208.0
Name: new_cases, dtype: float64
102066 102073    102.0
Name: new_cases, dtype: float64
102067 102074    97.0
Name: new_cases, dtype: float64
102068 102075    113.0
Name: new_cases, dtype: float64
102069 102076    101.0
Name: new_cases, dtype: float64
102070 102077    104.0
Name: new_cases, dtype: float64
102071 102078    48.0
Name: new_cases, dtype: float64
102072 102079    121.0
Name: new_cases, dtype: float64
102073 102080    129.0
Name: new_cases, dtype: float64
102074 102081    106.0
Name: new_cases, dtype: float64
102075 102082    66.0
Name: new_cases, dtype: float64
102076 102083    50.0
Name: new_cases, dtype: float64
102077 102084    82.0
Name: new_cases, dtype: float64
102078 102085    135.0
Name: new_cases, dtype: float64
102079 102086    58.0
Name: new_cases, dtype: float64
102080 102087    110.0
Name: new_cases, dtype: float64
102081 102088    83.0
Name: new_cases, dtype: float64
102082 102089    71.0
Name: new_cases, dtype: float64
102083 102090    84.0
Name: new_cases, dtype: float64
102084 102091    63.0
Name: new_cases, dtype: float64
102085 102092    38.0
Name: new_cases, dtype: float64
102086 102093    74.0
Name: new_cases, dtype: float64
102087 102094    89.0
Name: new_cases, dtype: float64
102088 102095    80.0
Name: new_cases, dtype: float64
102089 102096    67.0
Name: new_cases, dtype: float64
102090 102097    60.0
Name: new_cases, dtype: float64
102091 102098    26.0
Name: new_cases, dtype: float64
102092 102099    70.0
Name: new_cases, dtype: float64
102093 102100    120.0
Name: new_cases, dtype: float64
102094 102101    65.0
Name: new_cases, dtype: float64
102095 102102    100.0
Name: new_cases, dtype: float64
102096 102103    45.0
Name: new_cases, dtype: float64
102097 102104    51.0
Name: new_cases, dtype: float64
102098 102105    35.0
Name: new_cases, dtype: float64
102099 102106    37.0
Name: new_cases, dtype: float64
102100 102107    156.0
Name: new_cases, dtype: float64
102101 102108    81.0
Name: new_cases, dtype: float64
102102 102109    62.0
Name: new_cases, dtype: float64
102103 102110    55.0
Name: new_cases, dtype: float64
102104 102111    0.0
Name: new_cases, dtype: float64
102105 102112    43.0
Name: new_cases, dtype: float64
102106 102113    46.0
Name: new_cases, dtype: float64
102107 102114    16.0
Name: new_cases, dtype: float64
102108 102115    58.0
Name: new_cases, dtype: float64
102109 102116    28.0
Name: new_cases, dtype: float64
102110 102117    39.0
Name: new_cases, dtype: float64
102111 102118    30.0
Name: new_cases, dtype: float64
102112 102119    49.0
Name: new_cases, dtype: float64
102113 102120    49.0
Name: new_cases, dtype: float64
102114 102121    47.0
Name: new_cases, dtype: float64
102115 102122    44.0
Name: new_cases, dtype: float64
102116 102123    53.0
Name: new_cases, dtype: float64
102117 102124    49.0
Name: new_cases, dtype: float64
102118 102125    41.0
Name: new_cases, dtype: float64
102119 102126    7.0
Name: new_cases, dtype: float64
102120 102127    69.0
Name: new_cases, dtype: float64
102121 102128    0.0
Name: new_cases, dtype: float64
102122 102129    74.0
Name: new_cases, dtype: float64
102123 102130    49.0
Name: new_cases, dtype: float64
102124 102131    43.0
Name: new_cases, dtype: float64
102125 102132    35.0
Name: new_cases, dtype: float64
102126 102133    40.0
Name: new_cases, dtype: float64
102127 102134    42.0
Name: new_cases, dtype: float64
102128 102135    37.0
Name: new_cases, dtype: float64
102129 102136    48.0
Name: new_cases, dtype: float64
102130 102137    45.0
Name: new_cases, dtype: float64
102131 102138    63.0
Name: new_cases, dtype: float64
102132 102139    31.0
Name: new_cases, dtype: float64
102133 102140    30.0
Name: new_cases, dtype: float64
102134 102141    203.0
Name: new_cases, dtype: float64
102135 102142    16.0
Name: new_cases, dtype: float64
102136 102143    26.0
Name: new_cases, dtype: float64
102137 102144    122.0
Name: new_cases, dtype: float64
102138 102145    48.0
Name: new_cases, dtype: float64
102139 102146    26.0
Name: new_cases, dtype: float64
102140 102147    11.0
Name: new_cases, dtype: float64
102141 102148    49.0
Name: new_cases, dtype: float64
102142 102149    102.0
Name: new_cases, dtype: float64
102143 102150    64.0
Name: new_cases, dtype: float64
102144 102151    0.0
Name: new_cases, dtype: float64
102145 102152    69.0
Name: new_cases, dtype: float64
102146 102153    8.0
Name: new_cases, dtype: float64
102147 102154    7.0
Name: new_cases, dtype: float64
102148 102155    12.0
Name: new_cases, dtype: float64
102149 102156    17.0
Name: new_cases, dtype: float64
102150 102157    8.0
Name: new_cases, dtype: float64
102151 102158    39.0
Name: new_cases, dtype: float64
102152 102159    13.0
Name: new_cases, dtype: float64
102153 102160    51.0
Name: new_cases, dtype: float64
102154 102161    0.0
Name: new_cases, dtype: float64
102155 102162    86.0
Name: new_cases, dtype: float64
102156 102163    39.0
Name: new_cases, dtype: float64
102157 102164    44.0
Name: new_cases, dtype: float64
102158 102165    26.0
Name: new_cases, dtype: float64
102159 102166    29.0
Name: new_cases, dtype: float64
102160 102167    35.0
Name: new_cases, dtype: float64
102161 102168    2.0
Name: new_cases, dtype: float64
102162 102169    65.0
Name: new_cases, dtype: float64
102163 102170    11.0
Name: new_cases, dtype: float64
102164 102171    75.0
Name: new_cases, dtype: float64
102165 102172    74.0
Name: new_cases, dtype: float64
102166 102173    40.0
Name: new_cases, dtype: float64
102167 102174    71.0
Name: new_cases, dtype: float64
102168 102175    56.0
Name: new_cases, dtype: float64
102169 102176    50.0
Name: new_cases, dtype: float64
102170 102177    91.0
Name: new_cases, dtype: float64
102171 102178    110.0
Name: new_cases, dtype: float64
102172 102179    146.0
Name: new_cases, dtype: float64
102173 102180    186.0
Name: new_cases, dtype: float64
102174 102181    98.0
Name: new_cases, dtype: float64
102175 102182    12.0
Name: new_cases, dtype: float64
102176 102183    161.0
Name: new_cases, dtype: float64
102177 102184    154.0
Name: new_cases, dtype: float64
102178 102185    48.0
Name: new_cases, dtype: float64
102179 102186    159.0
Name: new_cases, dtype: float64
102180 102187    132.0
Name: new_cases, dtype: float64
102181 102188    123.0
Name: new_cases, dtype: float64
102182 102189    203.0
Name: new_cases, dtype: float64
102183 102190    146.0
Name: new_cases, dtype: float64

102184 102191    206.0
Name: new_cases, dtype: float64
102185 102192    0.0
Name: new_cases, dtype: float64
102186 102193    422.0
Name: new_cases, dtype: float64
102187 102194    0.0
Name: new_cases, dtype: float64
102188 102195    589.0
Name: new_cases, dtype: float64
102189 102196    216.0
Name: new_cases, dtype: float64
102190 102197    213.0
Name: new_cases, dtype: float64
102191 102198    404.0
Name: new_cases, dtype: float64
102192 102199    535.0
Name: new_cases, dtype: float64
102193 102200    558.0
Name: new_cases, dtype: float64
102194 102201    590.0
Name: new_cases, dtype: float64
102195 102202    497.0
Name: new_cases, dtype: float64
102196 102203    407.0
Name: new_cases, dtype: float64
102197 102204    444.0
Name: new_cases, dtype: float64
102198 102205    505.0
Name: new_cases, dtype: float64
102199 102206    747.0
Name: new_cases, dtype: float64
102200 102207    566.0
Name: new_cases, dtype: float64
102201 102208    565.0
Name: new_cases, dtype: float64
102202 102209    473.0
Name: new_cases, dtype: float64
102203 102210    471.0
Name: new_cases, dtype: float64
102204 102211    422.0
Name: new_cases, dtype: float64
102205 102212    610.0
Name: new_cases, dtype: float64
102206 102213    790.0
Name: new_cases, dtype: float64
102207 102214    753.0
Name: new_cases, dtype: float64
102208 102215    636.0
Name: new_cases, dtype: float64
102209 102216    665.0
Name: new_cases, dtype: float64
102210 102217    541.0
Name: new_cases, dtype: float64
102211 102218    584.0
Name: new_cases, dtype: float64
102212 102219    357.0
Name: new_cases, dtype: float64
102213 102220    0.0
Name: new_cases, dtype: float64
102214 102221    1823.0
Name: new_cases, dtype: float64
102215 102222    304.0
Name: new_cases, dtype: float64
102216 102223    0.0
Name: new_cases, dtype: float64
102217 102224    1452.0
Name: new_cases, dtype: float64
102218 102225    565.0
Name: new_cases, dtype: float64
102219 102226    655.0
Name: new_cases, dtype: float64
102220 102227    637.0
Name: new_cases, dtype: float64
102221 102228    835.0
Name: new_cases, dtype: float64
102222 102229    618.0
Name: new_cases, dtype: float64
102223 102230    650.0
Name: new_cases, dtype: float64
102224 102231    362.0
Name: new_cases, dtype: float64
102225 102232    460.0
Name: new_cases, dtype: float64
102226 102233    626.0
Name: new_cases, dtype: float64
102227 102234    582.0
Name: new_cases, dtype: float64
102228 102235    631.0
Name: new_cases, dtype: float64
102229 102236    444.0
Name: new_cases, dtype: float64
102230 102237    964.0
Name: new_cases, dtype: float64
102231 102238    459.0
Name: new_cases, dtype: float64
102232 102239    379.0
Name: new_cases, dtype: float64
102233 102240    597.0
Name: new_cases, dtype: float64
102234 102241    559.0
Name: new_cases, dtype: float64
102235 102242    727.0
Name: new_cases, dtype: float64
102236 102243    466.0
Name: new_cases, dtype: float64
102237 102244    547.0
Name: new_cases, dtype: float64
102238 102245    365.0
Name: new_cases, dtype: float64
102239 102246    387.0
Name: new_cases, dtype: float64
102240 102247    519.0
Name: new_cases, dtype: float64
102241 102248    299.0
Name: new_cases, dtype: float64
102242 102249    0.0
Name: new_cases, dtype: float64
102243 102250    938.0
Name: new_cases, dtype: float64
102244 102251    336.0
Name: new_cases, dtype: float64
102245 102252    168.0
Name: new_cases, dtype: float64
102246 102253    393.0
Name: new_cases, dtype: float64
102247 102254    513.0
Name: new_cases, dtype: float64
102248 102255    377.0
Name: new_cases, dtype: float64
102249 102256    433.0
Name: new_cases, dtype: float64
102250 102257    477.0
Name: new_cases, dtype: float64
102251 102258    210.0
Name: new_cases, dtype: float64
102252 102259    255.0
Name: new_cases, dtype: float64
102253 102260    296.0
Name: new_cases, dtype: float64
102254 102261    295.0
Name: new_cases, dtype: float64
102255 102262    437.0
Name: new_cases, dtype: float64
102256 102263    295.0
Name: new_cases, dtype: float64
102257 102264    161.0
Name: new_cases, dtype: float64
102258 102265    124.0
Name: new_cases, dtype: float64
102259 102266    74.0
Name: new_cases, dtype: float64
102260 102267    141.0
Name: new_cases, dtype: float64
102261 102268    282.0
Name: new_cases, dtype: float64
102262 102269    0.0
Name: new_cases, dtype: float64
102263 102270    606.0
Name: new_cases, dtype: float64
102264 102271    312.0
Name: new_cases, dtype: float64
102265 102272    139.0
Name: new_cases, dtype: float64
102266 102273    76.0
Name: new_cases, dtype: float64
102267 102274    284.0
Name: new_cases, dtype: float64
102268 102275    1.0
Name: new_cases, dtype: float64
102269 102276    425.0
Name: new_cases, dtype: float64
102270 102277    0.0
Name: new_cases, dtype: float64
102271 102278    393.0
Name: new_cases, dtype: float64
102272 102279    376.0
Name: new_cases, dtype: float64
102273 102280    125.0
Name: new_cases, dtype: float64
102274 102281    89.0
Name: new_cases, dtype: float64
102275 102282    159.0
Name: new_cases, dtype: float64
102276 102283    167.0
Name: new_cases, dtype: float64
102277 102284    247.0
Name: new_cases, dtype: float64
102278 102285    176.0
Name: new_cases, dtype: float64
102279 102286    159.0
Name: new_cases, dtype: float64
102280 102287    165.0
Name: new_cases, dtype: float64
102281 102288    711.0
Name: new_cases, dtype: float64
102282 102289    159.0
Name: new_cases, dtype: float64
102283 102290    166.0
Name: new_cases, dtype: float64
102284 102291    182.0
Name: new_cases, dtype: float64
102285 102292    120.0
Name: new_cases, dtype: float64
102286 102293    89.0
Name: new_cases, dtype: float64
102287 102294    74.0
Name: new_cases, dtype: float64
102288 102295    90.0
Name: new_cases, dtype: float64
102289 102296    99.0
Name: new_cases, dtype: float64
102290 102297    209.0
Name: new_cases, dtype: float64
102291 102298    87.0
Name: new_cases, dtype: float64
102292 102299    65.0
Name: new_cases, dtype: float64
102293 102300    116.0
Name: new_cases, dtype: float64
102294 102301    86.0
Name: new_cases, dtype: float64
102295 102302    52.0
Name: new_cases, dtype: float64
102296 102303    64.0
Name: new_cases, dtype: float64
102297 102304    65.0
Name: new_cases, dtype: float64
102298 102305    53.0
Name: new_cases, dtype: float64
102299 102306    129.0
Name: new_cases, dtype: float64
102300 102307    51.0
Name: new_cases, dtype: float64
102301 102308    20.0
Name: new_cases, dtype: float64
102302 102309    30.0
Name: new_cases, dtype: float64
102303 102310    0.0
Name: new_cases, dtype: float64
102304 102311    226.0
Name: new_cases, dtype: float64
102305 102312    61.0
Name: new_cases, dtype: float64
102306 102313    23.0
Name: new_cases, dtype: float64
102307 102314    45.0
Name: new_cases, dtype: float64
102308 102315    57.0
Name: new_cases, dtype: float64
102309 102316    0.0
Name: new_cases, dtype: float64
102310 102317    88.0
Name: new_cases, dtype: float64
102311 102318    0.0
Name: new_cases, dtype: float64
102312 102319    206.0
Name: new_cases, dtype: float64
102313 102320    0.0
Name: new_cases, dtype: float64
102314 102321    41.0
Name: new_cases, dtype: float64
102315 102322    58.0
Name: new_cases, dtype: float64
102316 102323    131.0
Name: new_cases, dtype: float64
102317 102324    105.0
Name: new_cases, dtype: float64
102318 102325    52.0
Name: new_cases, dtype: float64
102319 102326    0.0
Name: new_cases, dtype: float64
102320 102327    243.0
Name: new_cases, dtype: float64
102321 102328    54.0
Name: new_cases, dtype: float64
102322 102329    55.0
Name: new_cases, dtype: float64
102323 102330    167.0
Name: new_cases, dtype: float64
102324 102331    107.0
Name: new_cases, dtype: float64
102325 102332    268.0
Name: new_cases, dtype: float64
102326 102333    0.0
Name: new_cases, dtype: float64
102327 102334    1287.0
Name: new_cases, dtype: float64
102328 102335    612.0
Name: new_cases, dtype: float64
102329 102336    418.0
Name: new_cases, dtype: float64
102330 102337    0.0
Name: new_cases, dtype: float64
102331 102338    1115.0
Name: new_cases, dtype: float64
102332 102339    1424.0
Name: new_cases, dtype: float64
102333 102340    1051.0
Name: new_cases, dtype: float64
102334 102341    1584.0
Name: new_cases, dtype: float64
102335 102342    0.0
Name: new_cases, dtype: float64
102336 102343    828.0
Name: new_cases, dtype: float64

102337 102344    1772.0
Name: new_cases, dtype: float64
102338 102345    0.0
Name: new_cases, dtype: float64
102339 102346    6158.0
Name: new_cases, dtype: float64
102340 102347    1940.0
Name: new_cases, dtype: float64
102341 102348    1356.0
Name: new_cases, dtype: float64
102342 102349    1305.0
Name: new_cases, dtype: float64
102343 102350    1547.0
Name: new_cases, dtype: float64
102344 102351    859.0
Name: new_cases, dtype: float64
102345 102352    599.0
Name: new_cases, dtype: float64
102346 102353    1368.0
Name: new_cases, dtype: float64
102347 102354    1126.0
Name: new_cases, dtype: float64
102348 102355    0.0
Name: new_cases, dtype: float64
102349 102356    1364.0
Name: new_cases, dtype: float64
102350 102357    0.0
Name: new_cases, dtype: float64
102351 102358    1243.0
Name: new_cases, dtype: float64
102352 102359    428.0
Name: new_cases, dtype: float64
102353 102360    856.0
Name: new_cases, dtype: float64
102354 102361    791.0
Name: new_cases, dtype: float64
102355 102362    814.0
Name: new_cases, dtype: float64
102356 102363    766.0
Name: new_cases, dtype: float64
102357 Series([], Name: new_cases, dtype: float64)
102358 Series([], Name: new_cases, dtype: float64)
102359 101683    1.0
Name: new_cases, dtype: float64
102360 101684    0.0
Name: new_cases, dtype: float64
102361 101685    0.0
Name: new_cases, dtype: float64
102362 101686    0.0
Name: new_cases, dtype: float64
102363 101687    0.0
Name: new_cases, dtype: float64
104125 104132    24.0
Name: new_cases, dtype: float64
104126 104133    31.0
Name: new_cases, dtype: float64
104127 104134    21.0
Name: new_cases, dtype: float64
104128 104135    39.0
Name: new_cases, dtype: float64
104129 104136    29.0
Name: new_cases, dtype: float64
104130 104137    29.0
Name: new_cases, dtype: float64
104131 104138    195.0
Name: new_cases, dtype: float64
104132 104139    198.0
Name: new_cases, dtype: float64
104133 104140    104.0
Name: new_cases, dtype: float64
104134 104141    294.0
Name: new_cases, dtype: float64
104135 104142    94.0
Name: new_cases, dtype: float64
104136 104143    131.0
Name: new_cases, dtype: float64
104137 104144    112.0
Name: new_cases, dtype: float64
104138 104145    130.0
Name: new_cases, dtype: float64
104139 104146    87.0
Name: new_cases, dtype: float64
104140 104147    196.0
Name: new_cases, dtype: float64
104141 104148    168.0
Name: new_cases, dtype: float64
104142 104149    204.0
Name: new_cases, dtype: float64
104143 104150    267.0
Name: new_cases, dtype: float64
104144 104151    236.0
Name: new_cases, dtype: float64
104145 104152    242.0
Name: new_cases, dtype: float64
104146 104153    221.0
Name: new_cases, dtype: float64
104147 104154    285.0
Name: new_cases, dtype: float64
104148 104155    386.0
Name: new_cases, dtype: float64
104149 104156    260.0
Name: new_cases, dtype: float64
104150 104157    269.0
Name: new_cases, dtype: float64
104151 104158    161.0
Name: new_cases, dtype: float64
104152 104159    196.0
Name: new_cases, dtype: float64
104153 104160    222.0
Name: new_cases, dtype: float64
104154 104161    284.0
Name: new_cases, dtype: float64
104155 104162    223.0
Name: new_cases, dtype: float64
104156 104163    180.0
Name: new_cases, dtype: float64
104157 104164    137.0
Name: new_cases, dtype: float64
104158 104165    178.0
Name: new_cases, dtype: float64
104159 104166    221.0
Name: new_cases, dtype: float64
104160 104167    0.0
Name: new_cases, dtype: float64
104161 104168    125.0
Name: new_cases, dtype: float64
104162 104169    103.0
Name: new_cases, dtype: float64
104163 104170    95.0
Name: new_cases, dtype: float64
104164 104171    116.0
Name: new_cases, dtype: float64
104165 104172    78.0
Name: new_cases, dtype: float64
104166 104173    20.0
Name: new_cases, dtype: float64
104167 104174    117.0
Name: new_cases, dtype: float64
104168 104175    156.0
Name: new_cases, dtype: float64
104169 104176    41.0
Name: new_cases, dtype: float64
104170 104177    99.0
Name: new_cases, dtype: float64
104171 104178    42.0
Name: new_cases, dtype: float64
104172 104179    78.0
Name: new_cases, dtype: float64
104173 104180    35.0
Name: new_cases, dtype: float64
104174 104181    147.0
Name: new_cases, dtype: float64
104175 104182    63.0
Name: new_cases, dtype: float64
104176 104183    62.0
Name: new_cases, dtype: float64
104177 104184    36.0
Name: new_cases, dtype: float64
104178 104185    28.0
Name: new_cases, dtype: float64
104179 104186    72.0
Name: new_cases, dtype: float64
104180 104187    61.0
Name: new_cases, dtype: float64
104181 104188    50.0
Name: new_cases, dtype: float64
104182 104189    28.0
Name: new_cases, dtype: float64
104183 104190    45.0
Name: new_cases, dtype: float64
104184 104191    26.0
Name: new_cases, dtype: float64
104185 104192    38.0
Name: new_cases, dtype: float64
104186 104193    57.0
Name: new_cases, dtype: float64
104187 104194    51.0
Name: new_cases, dtype: float64
104188 104195    41.0
Name: new_cases, dtype: float64
104189 104196    38.0
Name: new_cases, dtype: float64
104190 104197    36.0
Name: new_cases, dtype: float64
104191 104198    29.0
Name: new_cases, dtype: float64
104192 104199    6.0
Name: new_cases, dtype: float64
104193 104200    27.0
Name: new_cases, dtype: float64
104194 104201    25.0
Name: new_cases, dtype: float64
104195 104202    18.0
Name: new_cases, dtype: float64
104196 104203    21.0
Name: new_cases, dtype: float64
104197 104204    23.0
Name: new_cases, dtype: float64
104198 104205    18.0
Name: new_cases, dtype: float64
104199 104206    12.0
Name: new_cases, dtype: float64
104200 104207    8.0
Name: new_cases, dtype: float64
104201 104208    10.0
Name: new_cases, dtype: float64
104202 104209    14.0
Name: new_cases, dtype: float64
104203 104210    28.0
Name: new_cases, dtype: float64
104204 104211    23.0
Name: new_cases, dtype: float64
104205 104212    14.0
Name: new_cases, dtype: float64
104206 104213    6.0
Name: new_cases, dtype: float64
104207 104214    12.0
Name: new_cases, dtype: float64
104208 104215    19.0
Name: new_cases, dtype: float64
104209 104216    18.0
Name: new_cases, dtype: float64
104210 104217    10.0
Name: new_cases, dtype: float64
104211 104218    11.0
Name: new_cases, dtype: float64
104212 104219    15.0
Name: new_cases, dtype: float64
104213 104220    3.0
Name: new_cases, dtype: float64
104214 104221    6.0
Name: new_cases, dtype: float64
104215 104222    9.0
Name: new_cases, dtype: float64
104216 104223    22.0
Name: new_cases, dtype: float64
104217 104224    27.0
Name: new_cases, dtype: float64
104218 104225    18.0
Name: new_cases, dtype: float64
104219 104226    9.0
Name: new_cases, dtype: float64
104220 104227    16.0
Name: new_cases, dtype: float64
104221 104228    14.0
Name: new_cases, dtype: float64
104222 104229    15.0
Name: new_cases, dtype: float64
104223 104230    18.0
Name: new_cases, dtype: float64
104224 104231    14.0
Name: new_cases, dtype: float64
104225 104232    12.0
Name: new_cases, dtype: float64
104226 104233    8.0
Name: new_cases, dtype: float64
104227 104234    3.0
Name: new_cases, dtype: float64
104228 104235    16.0
Name: new_cases, dtype: float64
104229 104236    13.0
Name: new_cases, dtype: float64
104230 104237    32.0
Name: new_cases, dtype: float64
104231 104238    16.0
Name: new_cases, dtype: float64
104232 104239    18.0
Name: new_cases, dtype: float64
104233 104240    16.0
Name: new_cases, dtype: float64
104234 104241    3.0
Name: new_cases, dtype: float64
104235 104242    6.0
Name: new_cases, dtype: float64
104236 104243    21.0
Name: new_cases, dtype: float64
104237 104244    16.0
Name: new_cases, dtype: float64
104238 104245    0.0
Name: new_cases, dtype: float64
104239 104246    44.0
Name: new_cases, dtype: float64
104240 104247    14.0
Name: new_cases, dtype: float64
104241 104248    9.0
Name: new_cases, dtype: float64
104242 104249    7.0
Name: new_cases, dtype: float64
104243 104250    17.0
Name: new_cases, dtype: float64
104244 104251    17.0
Name: new_cases, dtype: float64
104245 104252    6.0
Name: new_cases, dtype: float64
104246 104253    19.0
Name: new_cases, dtype: float64
104247 104254    5.0
Name: new_cases, dtype: float64
104248 104255    4.0
Name: new_cases, dtype: float64
104249 104256    6.0
Name: new_cases, dtype: float64
104250 104257    11.0
Name: new_cases, dtype: float64
104251 104258    3.0
Name: new_cases, dtype: float64
104252 104259    15.0
Name: new_cases, dtype: float64
104253 104260    9.0
Name: new_cases, dtype: float64
104254 104261    3.0
Name: new_cases, dtype: float64

104255 104262    4.0
Name: new_cases, dtype: float64
104256 104263    3.0
Name: new_cases, dtype: float64
104257 104264    17.0
Name: new_cases, dtype: float64
104258 104265    10.0
Name: new_cases, dtype: float64
104259 104266    4.0
Name: new_cases, dtype: float64
104260 104267    10.0
Name: new_cases, dtype: float64
104261 104268    3.0
Name: new_cases, dtype: float64
104262 104269    0.0
Name: new_cases, dtype: float64
104263 104270    6.0
Name: new_cases, dtype: float64
104264 104271    19.0
Name: new_cases, dtype: float64
104265 104272    6.0
Name: new_cases, dtype: float64
104266 104273    26.0
Name: new_cases, dtype: float64
104267 104274    7.0
Name: new_cases, dtype: float64
104268 104275    19.0
Name: new_cases, dtype: float64
104269 104276    6.0
Name: new_cases, dtype: float64
104270 104277    15.0
Name: new_cases, dtype: float64
104271 104278    18.0
Name: new_cases, dtype: float64
104272 104279    22.0
Name: new_cases, dtype: float64
104273 104280    36.0
Name: new_cases, dtype: float64
104274 104281    32.0
Name: new_cases, dtype: float64
104275 104282    13.0
Name: new_cases, dtype: float64
104276 104283    15.0
Name: new_cases, dtype: float64
104277 104284    66.0
Name: new_cases, dtype: float64
104278 104285    28.0
Name: new_cases, dtype: float64
104279 104286    47.0
Name: new_cases, dtype: float64
104280 104287    59.0
Name: new_cases, dtype: float64
104281 104288    83.0
Name: new_cases, dtype: float64
104282 104289    48.0
Name: new_cases, dtype: float64
104283 104290    39.0
Name: new_cases, dtype: float64
104284 104291    46.0
Name: new_cases, dtype: float64
104285 104292    67.0
Name: new_cases, dtype: float64
104286 104293    32.0
Name: new_cases, dtype: float64
104287 104294    68.0
Name: new_cases, dtype: float64
104288 104295    57.0
Name: new_cases, dtype: float64
104289 104296    57.0
Name: new_cases, dtype: float64
104290 104297    40.0
Name: new_cases, dtype: float64
104291 104298    55.0
Name: new_cases, dtype: float64
104292 104299    51.0
Name: new_cases, dtype: float64
104293 104300    51.0
Name: new_cases, dtype: float64
104294 104301    35.0
Name: new_cases, dtype: float64
104295 104302    78.0
Name: new_cases, dtype: float64
104296 104303    24.0
Name: new_cases, dtype: float64
104297 104304    24.0
Name: new_cases, dtype: float64
104298 104305    72.0
Name: new_cases, dtype: float64
104299 104306    59.0
Name: new_cases, dtype: float64
104300 104307    50.0
Name: new_cases, dtype: float64
104301 104308    38.0
Name: new_cases, dtype: float64
104302 104309    40.0
Name: new_cases, dtype: float64
104303 104310    29.0
Name: new_cases, dtype: float64
104304 104311    32.0
Name: new_cases, dtype: float64
104305 104312    139.0
Name: new_cases, dtype: float64
104306 104313    89.0
Name: new_cases, dtype: float64
104307 104314    163.0
Name: new_cases, dtype: float64
104308 104315    86.0
Name: new_cases, dtype: float64
104309 104316    111.0
Name: new_cases, dtype: float64
104310 104317    65.0
Name: new_cases, dtype: float64
104311 104318    92.0
Name: new_cases, dtype: float64
104312 104319    133.0
Name: new_cases, dtype: float64
104313 104320    102.0
Name: new_cases, dtype: float64
104314 104321    123.0
Name: new_cases, dtype: float64
104315 104322    121.0
Name: new_cases, dtype: float64
104316 104323    136.0
Name: new_cases, dtype: float64
104317 104324    76.0
Name: new_cases, dtype: float64
104318 104325    75.0
Name: new_cases, dtype: float64
104319 104326    122.0
Name: new_cases, dtype: float64
104320 104327    117.0
Name: new_cases, dtype: float64
104321 104328    105.0
Name: new_cases, dtype: float64
104322 104329    146.0
Name: new_cases, dtype: float64
104323 104330    125.0
Name: new_cases, dtype: float64
104324 104331    89.0
Name: new_cases, dtype: float64
104325 104332    39.0
Name: new_cases, dtype: float64
104326 104333    108.0
Name: new_cases, dtype: float64
104327 104334    148.0
Name: new_cases, dtype: float64
104328 104335    124.0
Name: new_cases, dtype: float64
104329 104336    129.0
Name: new_cases, dtype: float64
104330 104337    139.0
Name: new_cases, dtype: float64
104331 104338    82.0
Name: new_cases, dtype: float64
104332 104339    71.0
Name: new_cases, dtype: float64
104333 104340    90.0
Name: new_cases, dtype: float64
104334 104341    127.0
Name: new_cases, dtype: float64
104335 104342    112.0
Name: new_cases, dtype: float64
104336 104343    122.0
Name: new_cases, dtype: float64
104337 104344    135.0
Name: new_cases, dtype: float64
104338 104345    78.0
Name: new_cases, dtype: float64
104339 104346    95.0
Name: new_cases, dtype: float64
104340 104347    148.0
Name: new_cases, dtype: float64
104341 104348    179.0
Name: new_cases, dtype: float64
104342 104349    229.0
Name: new_cases, dtype: float64
104343 104350    208.0
Name: new_cases, dtype: float64
104344 104351    167.0
Name: new_cases, dtype: float64
104345 104352    78.0
Name: new_cases, dtype: float64
104346 104353    58.0
Name: new_cases, dtype: float64
104347 104354    115.0
Name: new_cases, dtype: float64
104348 104355    154.0
Name: new_cases, dtype: float64
104349 104356    160.0
Name: new_cases, dtype: float64
104350 104357    184.0
Name: new_cases, dtype: float64
104351 104358    135.0
Name: new_cases, dtype: float64
104352 104359    97.0
Name: new_cases, dtype: float64
104353 104360    88.0
Name: new_cases, dtype: float64
104354 104361    146.0
Name: new_cases, dtype: float64
104355 104362    169.0
Name: new_cases, dtype: float64
104356 104363    192.0
Name: new_cases, dtype: float64
104357 104364    270.0
Name: new_cases, dtype: float64
104358 104365    298.0
Name: new_cases, dtype: float64
104359 104366    217.0
Name: new_cases, dtype: float64
104360 104367    160.0
Name: new_cases, dtype: float64
104361 104368    433.0
Name: new_cases, dtype: float64
104362 104369    324.0
Name: new_cases, dtype: float64
104363 104370    403.0
Name: new_cases, dtype: float64
104364 104371    495.0
Name: new_cases, dtype: float64
104365 104372    498.0
Name: new_cases, dtype: float64
104366 104373    269.0
Name: new_cases, dtype: float64
104367 104374    304.0
Name: new_cases, dtype: float64
104368 104375    704.0
Name: new_cases, dtype: float64
104369 104376    617.0
Name: new_cases, dtype: float64
104370 104377    622.0
Name: new_cases, dtype: float64
104371 104378    651.0
Name: new_cases, dtype: float64
104372 104379    606.0
Name: new_cases, dtype: float64
104373 104380    408.0
Name: new_cases, dtype: float64
104374 104381    489.0
Name: new_cases, dtype: float64
104375 104382    593.0
Name: new_cases, dtype: float64
104376 104383    562.0
Name: new_cases, dtype: float64
104377 104384    624.0
Name: new_cases, dtype: float64
104378 104385    717.0
Name: new_cases, dtype: float64
104379 104386    688.0
Name: new_cases, dtype: float64
104380 104387    518.0
Name: new_cases, dtype: float64
104381 104388    0.0
Name: new_cases, dtype: float64
104382 104389    0.0
Name: new_cases, dtype: float64
104383 104390    1680.0
Name: new_cases, dtype: float64
104384 104391    656.0
Name: new_cases, dtype: float64
104385 104392    671.0
Name: new_cases, dtype: float64
104386 104393    573.0
Name: new_cases, dtype: float64
104387 104394    338.0
Name: new_cases, dtype: float64
104388 104395    413.0
Name: new_cases, dtype: float64
104389 104396    418.0
Name: new_cases, dtype: float64
104390 104397    534.0
Name: new_cases, dtype: float64
104391 104398    551.0
Name: new_cases, dtype: float64
104392 104399    480.0
Name: new_cases, dtype: float64
104393 104400    445.0
Name: new_cases, dtype: float64
104394 104401    353.0
Name: new_cases, dtype: float64
104395 104402    282.0
Name: new_cases, dtype: float64
104396 104403    322.0
Name: new_cases, dtype: float64
104397 104404    441.0
Name: new_cases, dtype: float64
104398 104405    378.0
Name: new_cases, dtype: float64
104399 104406    402.0
Name: new_cases, dtype: float64
104400 104407    430.0
Name: new_cases, dtype: float64
104401 104408    272.0
Name: new_cases, dtype: float64
104402 104409    250.0
Name: new_cases, dtype: float64
104403 104410    380.0
Name: new_cases, dtype: float64
104404 104411    460.0
Name: new_cases, dtype: float64
104405 104412    362.0
Name: new_cases, dtype: float64
104406 104413    498.0
Name: new_cases, dtype: float64
104407 104414    416.0
Name: new_cases, dtype: float64

104408 104415    364.0
Name: new_cases, dtype: float64
104409 104416    200.0
Name: new_cases, dtype: float64
104410 104417    331.0
Name: new_cases, dtype: float64
104411 104418    518.0
Name: new_cases, dtype: float64
104412 104419    460.0
Name: new_cases, dtype: float64
104413 104420    464.0
Name: new_cases, dtype: float64
104414 104421    431.0
Name: new_cases, dtype: float64
104415 104422    375.0
Name: new_cases, dtype: float64
104416 104423    323.0
Name: new_cases, dtype: float64
104417 104424    431.0
Name: new_cases, dtype: float64
104418 104425    596.0
Name: new_cases, dtype: float64
104419 104426    523.0
Name: new_cases, dtype: float64
104420 104427    476.0
Name: new_cases, dtype: float64
104421 104428    317.0
Name: new_cases, dtype: float64
104422 104429    430.0
Name: new_cases, dtype: float64
104423 104430    381.0
Name: new_cases, dtype: float64
104424 104431    526.0
Name: new_cases, dtype: float64
104425 104432    693.0
Name: new_cases, dtype: float64
104426 104433    732.0
Name: new_cases, dtype: float64
104427 104434    557.0
Name: new_cases, dtype: float64
104428 104435    236.0
Name: new_cases, dtype: float64
104429 104436    463.0
Name: new_cases, dtype: float64
104430 104437    450.0
Name: new_cases, dtype: float64
104431 104438    529.0
Name: new_cases, dtype: float64
104432 104439    935.0
Name: new_cases, dtype: float64
104433 104440    787.0
Name: new_cases, dtype: float64
104434 104441    825.0
Name: new_cases, dtype: float64
104435 104442    684.0
Name: new_cases, dtype: float64
104436 104443    443.0
Name: new_cases, dtype: float64
104437 104444    555.0
Name: new_cases, dtype: float64
104438 104445    429.0
Name: new_cases, dtype: float64
104439 104446    712.0
Name: new_cases, dtype: float64
104440 104447    667.0
Name: new_cases, dtype: float64
104441 104448    454.0
Name: new_cases, dtype: float64
104442 104449    466.0
Name: new_cases, dtype: float64
104443 104450    243.0
Name: new_cases, dtype: float64
104444 104451    206.0
Name: new_cases, dtype: float64
104445 104452    383.0
Name: new_cases, dtype: float64
104446 104453    422.0
Name: new_cases, dtype: float64
104447 104454    431.0
Name: new_cases, dtype: float64
104448 104455    372.0
Name: new_cases, dtype: float64
104449 104456    306.0
Name: new_cases, dtype: float64
104450 104457    238.0
Name: new_cases, dtype: float64
104451 104458    279.0
Name: new_cases, dtype: float64
104452 104459    233.0
Name: new_cases, dtype: float64
104453 104460    279.0
Name: new_cases, dtype: float64
104454 104461    367.0
Name: new_cases, dtype: float64
104455 104462    315.0
Name: new_cases, dtype: float64
104456 104463    299.0
Name: new_cases, dtype: float64
104457 104464    218.0
Name: new_cases, dtype: float64
104458 104465    173.0
Name: new_cases, dtype: float64
104459 104466    296.0
Name: new_cases, dtype: float64
104460 104467    291.0
Name: new_cases, dtype: float64
104461 104468    286.0
Name: new_cases, dtype: float64
104462 104469    373.0
Name: new_cases, dtype: float64
104463 104470    271.0
Name: new_cases, dtype: float64
104464 104471    170.0
Name: new_cases, dtype: float64
104465 104472    119.0
Name: new_cases, dtype: float64
104466 104473    346.0
Name: new_cases, dtype: float64
104467 104474    220.0
Name: new_cases, dtype: float64
104468 104475    209.0
Name: new_cases, dtype: float64
104469 104476    264.0
Name: new_cases, dtype: float64
104470 104477    425.0
Name: new_cases, dtype: float64
104471 104478    156.0
Name: new_cases, dtype: float64
104472 104479    109.0
Name: new_cases, dtype: float64
104473 104480    353.0
Name: new_cases, dtype: float64
104474 104481    286.0
Name: new_cases, dtype: float64
104475 104482    358.0
Name: new_cases, dtype: float64
104476 104483    326.0
Name: new_cases, dtype: float64
104477 104484    283.0
Name: new_cases, dtype: float64
104478 104485    208.0
Name: new_cases, dtype: float64
104479 104486    217.0
Name: new_cases, dtype: float64
104480 104487    226.0
Name: new_cases, dtype: float64
104481 104488    390.0
Name: new_cases, dtype: float64
104482 104489    341.0
Name: new_cases, dtype: float64
104483 104490    551.0
Name: new_cases, dtype: float64
104484 104491    524.0
Name: new_cases, dtype: float64
104485 104492    262.0
Name: new_cases, dtype: float64
104486 104493    180.0
Name: new_cases, dtype: float64
104487 104494    729.0
Name: new_cases, dtype: float64
104488 104495    499.0
Name: new_cases, dtype: float64
104489 104496    689.0
Name: new_cases, dtype: float64
104490 104497    570.0
Name: new_cases, dtype: float64
104491 104498    690.0
Name: new_cases, dtype: float64
104492 104499    363.0
Name: new_cases, dtype: float64
104493 104500    396.0
Name: new_cases, dtype: float64
104494 104501    828.0
Name: new_cases, dtype: float64
104495 104502    714.0
Name: new_cases, dtype: float64
104496 104503    685.0
Name: new_cases, dtype: float64
104497 104504    872.0
Name: new_cases, dtype: float64
104498 104505    905.0
Name: new_cases, dtype: float64
104499 104506    854.0
Name: new_cases, dtype: float64
104500 104507    640.0
Name: new_cases, dtype: float64
104501 104508    865.0
Name: new_cases, dtype: float64
104502 104509    1150.0
Name: new_cases, dtype: float64
104503 104510    1064.0
Name: new_cases, dtype: float64
104504 104511    1034.0
Name: new_cases, dtype: float64
104505 104512    989.0
Name: new_cases, dtype: float64
104506 104513    820.0
Name: new_cases, dtype: float64
104507 104514    577.0
Name: new_cases, dtype: float64
104508 104515    1096.0
Name: new_cases, dtype: float64
104509 104516    1085.0
Name: new_cases, dtype: float64
104510 104517    984.0
Name: new_cases, dtype: float64
104511 104518    831.0
Name: new_cases, dtype: float64
104512 104519    1072.0
Name: new_cases, dtype: float64
104513 104520    462.0
Name: new_cases, dtype: float64
104514 104521    681.0
Name: new_cases, dtype: float64
104515 104522    989.0
Name: new_cases, dtype: float64
104516 104523    1069.0
Name: new_cases, dtype: float64
104517 104524    871.0
Name: new_cases, dtype: float64
104518 104525    691.0
Name: new_cases, dtype: float64
104519 104526    640.0
Name: new_cases, dtype: float64
104520 104527    692.0
Name: new_cases, dtype: float64
104521 104528    574.0
Name: new_cases, dtype: float64
104522 104529    573.0
Name: new_cases, dtype: float64
104523 104530    900.0
Name: new_cases, dtype: float64
104524 104531    933.0
Name: new_cases, dtype: float64
104525 104532    878.0
Name: new_cases, dtype: float64
104526 104533    759.0
Name: new_cases, dtype: float64
104527 104534    255.0
Name: new_cases, dtype: float64
104528 104535    647.0
Name: new_cases, dtype: float64
104529 104536    648.0
Name: new_cases, dtype: float64
104530 104537    739.0
Name: new_cases, dtype: float64
104531 104538    599.0
Name: new_cases, dtype: float64
104532 104539    617.0
Name: new_cases, dtype: float64
104533 104540    503.0
Name: new_cases, dtype: float64
104534 104541    417.0
Name: new_cases, dtype: float64
104535 104542    366.0
Name: new_cases, dtype: float64
104536 104543    518.0
Name: new_cases, dtype: float64
104537 104544    314.0
Name: new_cases, dtype: float64
104538 104545    795.0
Name: new_cases, dtype: float64
104539 104546    444.0
Name: new_cases, dtype: float64
104540 104547    480.0
Name: new_cases, dtype: float64
104541 104548    329.0
Name: new_cases, dtype: float64
104542 104549    222.0
Name: new_cases, dtype: float64
104543 104550    550.0
Name: new_cases, dtype: float64
104544 104551    524.0
Name: new_cases, dtype: float64
104545 104552    470.0
Name: new_cases, dtype: float64
104546 104553    385.0
Name: new_cases, dtype: float64
104547 104554    429.0
Name: new_cases, dtype: float64
104548 104555    289.0
Name: new_cases, dtype: float64
104549 104556    210.0
Name: new_cases, dtype: float64
104550 104557    483.0
Name: new_cases, dtype: float64
104551 104558    484.0
Name: new_cases, dtype: float64
104552 104559    469.0
Name: new_cases, dtype: float64
104553 104560    506.0
Name: new_cases, dtype: float64
104554 104561    407.0
Name: new_cases, dtype: float64
104555 104562    316.0
Name: new_cases, dtype: float64
104556 104563    231.0
Name: new_cases, dtype: float64
104557 104564    657.0
Name: new_cases, dtype: float64
104558 104565    473.0
Name: new_cases, dtype: float64
104559 104566    500.0
Name: new_cases, dtype: float64
104560 104567    320.0
Name: new_cases, dtype: float64
104561 104568    425.0
Name: new_cases, dtype: float64
104562 104569    312.0
Name: new_cases, dtype: float64
104563 104570    247.0
Name: new_cases, dtype: float64
104564 104571    201.0
Name: new_cases, dtype: float64
104565 104572    314.0
Name: new_cases, dtype: float64
104566 104573    478.0
Name: new_cases, dtype: float64

104567 104574    505.0
Name: new_cases, dtype: float64
104568 104575    714.0
Name: new_cases, dtype: float64
104569 104576    452.0
Name: new_cases, dtype: float64
104570 104577    451.0
Name: new_cases, dtype: float64
104571 104578    238.0
Name: new_cases, dtype: float64
104572 104579    511.0
Name: new_cases, dtype: float64
104573 104580    499.0
Name: new_cases, dtype: float64
104574 104581    409.0
Name: new_cases, dtype: float64
104575 104582    339.0
Name: new_cases, dtype: float64
104576 104583    245.0
Name: new_cases, dtype: float64
104577 104584    169.0
Name: new_cases, dtype: float64
104578 104585    292.0
Name: new_cases, dtype: float64
104579 104586    460.0
Name: new_cases, dtype: float64
104580 104587    353.0
Name: new_cases, dtype: float64
104581 104588    289.0
Name: new_cases, dtype: float64
104582 104589    303.0
Name: new_cases, dtype: float64
104583 104590    168.0
Name: new_cases, dtype: float64
104584 104591    128.0
Name: new_cases, dtype: float64
104585 104592    249.0
Name: new_cases, dtype: float64
104586 104593    188.0
Name: new_cases, dtype: float64
104587 104594    212.0
Name: new_cases, dtype: float64
104588 104595    210.0
Name: new_cases, dtype: float64
104589 104596    198.0
Name: new_cases, dtype: float64
104590 104597    112.0
Name: new_cases, dtype: float64
104591 104598    60.0
Name: new_cases, dtype: float64
104592 104599    231.0
Name: new_cases, dtype: float64
104593 104600    222.0
Name: new_cases, dtype: float64
104594 104601    180.0
Name: new_cases, dtype: float64
104595 104602    219.0
Name: new_cases, dtype: float64
104596 104603    197.0
Name: new_cases, dtype: float64
104597 104604    130.0
Name: new_cases, dtype: float64
104598 104605    108.0
Name: new_cases, dtype: float64
104599 104606    212.0
Name: new_cases, dtype: float64
104600 104607    221.0
Name: new_cases, dtype: float64
104601 104608    178.0
Name: new_cases, dtype: float64
104602 104609    326.0
Name: new_cases, dtype: float64
104603 104610    72.0
Name: new_cases, dtype: float64
104604 104611    149.0
Name: new_cases, dtype: float64
104605 104612    97.0
Name: new_cases, dtype: float64
104606 104613    156.0
Name: new_cases, dtype: float64
104607 104614    293.0
Name: new_cases, dtype: float64
104608 104615    279.0
Name: new_cases, dtype: float64
104609 104616    193.0
Name: new_cases, dtype: float64
104610 104617    240.0
Name: new_cases, dtype: float64
104611 104618    112.0
Name: new_cases, dtype: float64
104612 104619    88.0
Name: new_cases, dtype: float64
104613 104620    187.0
Name: new_cases, dtype: float64
104614 104621    227.0
Name: new_cases, dtype: float64
104615 104622    211.0
Name: new_cases, dtype: float64
104616 104623    99.0
Name: new_cases, dtype: float64
104617 104624    293.0
Name: new_cases, dtype: float64
104618 104625    134.0
Name: new_cases, dtype: float64
104619 104626    97.0
Name: new_cases, dtype: float64
104620 104627    170.0
Name: new_cases, dtype: float64
104621 104628    182.0
Name: new_cases, dtype: float64
104622 104629    171.0
Name: new_cases, dtype: float64
104623 104630    156.0
Name: new_cases, dtype: float64
104624 104631    216.0
Name: new_cases, dtype: float64
104625 104632    138.0
Name: new_cases, dtype: float64
104626 104633    109.0
Name: new_cases, dtype: float64
104627 104634    195.0
Name: new_cases, dtype: float64
104628 104635    246.0
Name: new_cases, dtype: float64
104629 104636    189.0
Name: new_cases, dtype: float64
104630 104637    266.0
Name: new_cases, dtype: float64
104631 104638    228.0
Name: new_cases, dtype: float64
104632 104639    168.0
Name: new_cases, dtype: float64
104633 104640    136.0
Name: new_cases, dtype: float64
104634 104641    330.0
Name: new_cases, dtype: float64
104635 104642    273.0
Name: new_cases, dtype: float64
104636 104643    171.0
Name: new_cases, dtype: float64
104637 104644    586.0
Name: new_cases, dtype: float64
104638 104645    344.0
Name: new_cases, dtype: float64
104639 104646    156.0
Name: new_cases, dtype: float64
104640 104647    226.0
Name: new_cases, dtype: float64
104641 104648    412.0
Name: new_cases, dtype: float64
104642 104649    475.0
Name: new_cases, dtype: float64
104643 104650    478.0
Name: new_cases, dtype: float64
104644 104651    560.0
Name: new_cases, dtype: float64
104645 104652    426.0
Name: new_cases, dtype: float64
104646 104653    262.0
Name: new_cases, dtype: float64
104647 104654    370.0
Name: new_cases, dtype: float64
104648 104655    497.0
Name: new_cases, dtype: float64
104649 104656    666.0
Name: new_cases, dtype: float64
104650 104657    322.0
Name: new_cases, dtype: float64
104651 104658    574.0
Name: new_cases, dtype: float64
104652 104659    872.0
Name: new_cases, dtype: float64
104653 104660    268.0
Name: new_cases, dtype: float64
104654 104661    449.0
Name: new_cases, dtype: float64
104655 104662    530.0
Name: new_cases, dtype: float64
104656 104663    747.0
Name: new_cases, dtype: float64
104657 104664    612.0
Name: new_cases, dtype: float64
104658 104665    685.0
Name: new_cases, dtype: float64
104659 104666    720.0
Name: new_cases, dtype: float64
104660 104667    277.0
Name: new_cases, dtype: float64
104661 104668    553.0
Name: new_cases, dtype: float64
104662 104669    1124.0
Name: new_cases, dtype: float64
104663 104670    1093.0
Name: new_cases, dtype: float64
104664 104671    1294.0
Name: new_cases, dtype: float64
104665 104672    1415.0
Name: new_cases, dtype: float64
104666 104673    1552.0
Name: new_cases, dtype: float64
104667 104674    1047.0
Name: new_cases, dtype: float64
104668 104675    907.0
Name: new_cases, dtype: float64
104669 104676    1349.0
Name: new_cases, dtype: float64
104670 104677    1785.0
Name: new_cases, dtype: float64
104671 104678    1640.0
Name: new_cases, dtype: float64
104672 104679    1550.0
Name: new_cases, dtype: float64
104673 104680    1687.0
Name: new_cases, dtype: float64
104674 104681    1149.0
Name: new_cases, dtype: float64
104675 104682    1065.0
Name: new_cases, dtype: float64
104676 104683    1204.0
Name: new_cases, dtype: float64
104677 104684    1704.0
Name: new_cases, dtype: float64
104678 104685    1546.0
Name: new_cases, dtype: float64
104679 104686    1629.0
Name: new_cases, dtype: float64
104680 104687    1301.0
Name: new_cases, dtype: float64
104681 104688    840.0
Name: new_cases, dtype: float64
104682 104689    653.0
Name: new_cases, dtype: float64
104683 104690    1120.0
Name: new_cases, dtype: float64
104684 104691    1219.0
Name: new_cases, dtype: float64
104685 104692    969.0
Name: new_cases, dtype: float64
104686 104693    982.0
Name: new_cases, dtype: float64
104687 104694    763.0
Name: new_cases, dtype: float64
104688 104695    570.0
Name: new_cases, dtype: float64
104689 104696    474.0
Name: new_cases, dtype: float64
104690 104697    679.0
Name: new_cases, dtype: float64
104691 104698    484.0
Name: new_cases, dtype: float64
104692 104699    1207.0
Name: new_cases, dtype: float64
104693 104700    721.0
Name: new_cases, dtype: float64
104694 104701    705.0
Name: new_cases, dtype: float64
104695 104702    519.0
Name: new_cases, dtype: float64
104696 104703    381.0
Name: new_cases, dtype: float64
104697 104704    658.0
Name: new_cases, dtype: float64
104698 104705    702.0
Name: new_cases, dtype: float64
104699 104706    555.0
Name: new_cases, dtype: float64
104700 104707    581.0
Name: new_cases, dtype: float64
104701 104708    484.0
Name: new_cases, dtype: float64
104702 104709    309.0
Name: new_cases, dtype: float64
104703 104710    309.0
Name: new_cases, dtype: float64
104704 104711    484.0
Name: new_cases, dtype: float64
104705 104712    582.0
Name: new_cases, dtype: float64
104706 104713    480.0
Name: new_cases, dtype: float64
104707 104714    508.0
Name: new_cases, dtype: float64
104708 104715    467.0
Name: new_cases, dtype: float64
104709 104716    221.0
Name: new_cases, dtype: float64
104710 104717    287.0
Name: new_cases, dtype: float64
104711 104718    172.0
Name: new_cases, dtype: float64
104712 104719    896.0
Name: new_cases, dtype: float64
104713 104720    399.0
Name: new_cases, dtype: float64
104714 104721    356.0
Name: new_cases, dtype: float64
104715 104722    423.0
Name: new_cases, dtype: float64
104716 104723    334.0
Name: new_cases, dtype: float64
104717 104724    209.0
Name: new_cases, dtype: float64
104718 104725    545.0
Name: new_cases, dtype: float64
104719 104726    608.0
Name: new_cases, dtype: float64
104720 104727    657.0
Name: new_cases, dtype: float64
104721 104728    748.0
Name: new_cases, dtype: float64
104722 104729    641.0
Name: new_cases, dtype: float64
104723 104730    543.0
Name: new_cases, dtype: float64
104724 104731    424.0
Name: new_cases, dtype: float64
104725 104732    893.0
Name: new_cases, dtype: float64
104726 104733    1144.0
Name: new_cases, dtype: float64
104727 104734    1180.0
Name: new_cases, dtype: float64
104728 104735    996.0
Name: new_cases, dtype: float64
104729 104736    1125.0
Name: new_cases, dtype: float64
104730 104737    798.0
Name: new_cases, dtype: float64
104731 104738    627.0
Name: new_cases, dtype: float64
104732 104739    1335.0
Name: new_cases, dtype: float64
104733 104740    1626.0
Name: new_cases, dtype: float64
104734 104741    1514.0
Name: new_cases, dtype: float64
104735 104742    1534.0
Name: new_cases, dtype: float64

104736 104743    1506.0
Name: new_cases, dtype: float64
104737 104744    1062.0
Name: new_cases, dtype: float64
104738 104745    998.0
Name: new_cases, dtype: float64
104739 104746    1532.0
Name: new_cases, dtype: float64
104740 104747    2126.0
Name: new_cases, dtype: float64
104741 104748    1783.0
Name: new_cases, dtype: float64
104742 104749    2006.0
Name: new_cases, dtype: float64
104743 104750    1762.0
Name: new_cases, dtype: float64
104744 104751    1306.0
Name: new_cases, dtype: float64
104745 104752    1156.0
Name: new_cases, dtype: float64
104746 104753    783.0
Name: new_cases, dtype: float64
104747 104754    3530.0
Name: new_cases, dtype: float64
104748 104755    2475.0
Name: new_cases, dtype: float64
104749 104756    2425.0
Name: new_cases, dtype: float64
104750 104757    2364.0
Name: new_cases, dtype: float64
104751 104758    1338.0
Name: new_cases, dtype: float64
104752 104759    1470.0
Name: new_cases, dtype: float64
104753 104760    2391.0
Name: new_cases, dtype: float64
104754 104761    1520.0
Name: new_cases, dtype: float64
104755 104762    4575.0
Name: new_cases, dtype: float64
104756 104763    2970.0
Name: new_cases, dtype: float64
104757 104764    2942.0
Name: new_cases, dtype: float64
104758 104765    1891.0
Name: new_cases, dtype: float64
104759 104766    1721.0
Name: new_cases, dtype: float64
104760 104767    2877.0
Name: new_cases, dtype: float64
104761 104768    4045.0
Name: new_cases, dtype: float64
104762 104769    3780.0
Name: new_cases, dtype: float64
104763 104770    4140.0
Name: new_cases, dtype: float64
104764 104771    4191.0
Name: new_cases, dtype: float64
104765 104772    2964.0
Name: new_cases, dtype: float64
104766 104773    1530.0
Name: new_cases, dtype: float64
104767 104774    2675.0
Name: new_cases, dtype: float64
104768 104775    7631.0
Name: new_cases, dtype: float64
104769 104776    5259.0
Name: new_cases, dtype: float64
104770 104777    5355.0
Name: new_cases, dtype: float64
104771 104778    5413.0
Name: new_cases, dtype: float64
104772 104779    3477.0
Name: new_cases, dtype: float64
104773 104780    3622.0
Name: new_cases, dtype: float64
104774 104781    0.0
Name: new_cases, dtype: float64
104775 104782    10867.0
Name: new_cases, dtype: float64
104776 104783    5741.0
Name: new_cases, dtype: float64
104777 104784    4520.0
Name: new_cases, dtype: float64
104778 104785    4689.0
Name: new_cases, dtype: float64
104779 104786    3705.0
Name: new_cases, dtype: float64
104780 104787    3022.0
Name: new_cases, dtype: float64
104781 104788    4041.0
Name: new_cases, dtype: float64
104782 104789    4799.0
Name: new_cases, dtype: float64
104783 104790    4290.0
Name: new_cases, dtype: float64
104784 104791    4312.0
Name: new_cases, dtype: float64
104785 104792    2268.0
Name: new_cases, dtype: float64
104786 104793    1989.0
Name: new_cases, dtype: float64
104787 104794    2214.0
Name: new_cases, dtype: float64
104788 104795    3750.0
Name: new_cases, dtype: float64
104789 104796    4702.0
Name: new_cases, dtype: float64
104790 104797    4407.0
Name: new_cases, dtype: float64
104791 104798    4018.0
Name: new_cases, dtype: float64
104792 104799    3045.0
Name: new_cases, dtype: float64
104793 104800    2156.0
Name: new_cases, dtype: float64
104794 104801    2903.0
Name: new_cases, dtype: float64
104795 104802    5233.0
Name: new_cases, dtype: float64
104796 104803    7921.0
Name: new_cases, dtype: float64
104797 104804    8385.0
Name: new_cases, dtype: float64
104798 104805    7879.0
Name: new_cases, dtype: float64
104799 104806    6160.0
Name: new_cases, dtype: float64
104800 104807    5288.0
Name: new_cases, dtype: float64
104801 Series([], Name: new_cases, dtype: float64)
104802 104125    1.0
Name: new_cases, dtype: float64
104803 104126    0.0
Name: new_cases, dtype: float64
104804 104127    5.0
Name: new_cases, dtype: float64
104805 104128    9.0
Name: new_cases, dtype: float64
104806 104129    4.0
Name: new_cases, dtype: float64
104807 104130    6.0
Name: new_cases, dtype: float64
106208 106215    0.0
Name: new_cases, dtype: float64
106209 106216    0.0
Name: new_cases, dtype: float64
106210 106217    1.0
Name: new_cases, dtype: float64
106211 106218    0.0
Name: new_cases, dtype: float64
106212 106219    0.0
Name: new_cases, dtype: float64
106213 106220    0.0
Name: new_cases, dtype: float64
106214 106221    10.0
Name: new_cases, dtype: float64
106215 106222    3.0
Name: new_cases, dtype: float64
106216 106223    1.0
Name: new_cases, dtype: float64
106217 106224    8.0
Name: new_cases, dtype: float64
106218 106225    3.0
Name: new_cases, dtype: float64
106219 106226    22.0
Name: new_cases, dtype: float64
106220 106227    83.0
Name: new_cases, dtype: float64
106221 106228    100.0
Name: new_cases, dtype: float64
106222 106229    63.0
Name: new_cases, dtype: float64
106223 106230    155.0
Name: new_cases, dtype: float64
106224 106231    47.0
Name: new_cases, dtype: float64
106225 106232    229.0
Name: new_cases, dtype: float64
106226 106233    46.0
Name: new_cases, dtype: float64
106227 106234    99.0
Name: new_cases, dtype: float64
106228 106235    97.0
Name: new_cases, dtype: float64
106229 106236    91.0
Name: new_cases, dtype: float64
106230 106237    138.0
Name: new_cases, dtype: float64
106231 106238    172.0
Name: new_cases, dtype: float64
106232 106239    122.0
Name: new_cases, dtype: float64
106233 106240    102.0
Name: new_cases, dtype: float64
106234 106241    120.0
Name: new_cases, dtype: float64
106235 106242    221.0
Name: new_cases, dtype: float64
106236 106243    180.0
Name: new_cases, dtype: float64
106237 106244    303.0
Name: new_cases, dtype: float64
106238 106245    265.0
Name: new_cases, dtype: float64
106239 106246    132.0
Name: new_cases, dtype: float64
106240 106247    339.0
Name: new_cases, dtype: float64
106241 106248    609.0
Name: new_cases, dtype: float64
106242 106249    269.0
Name: new_cases, dtype: float64
106243 106250    228.0
Name: new_cases, dtype: float64
106244 106251    226.0
Name: new_cases, dtype: float64
106245 106252    206.0
Name: new_cases, dtype: float64
106246 106253    316.0
Name: new_cases, dtype: float64
106247 106254    219.0
Name: new_cases, dtype: float64
106248 106255    266.0
Name: new_cases, dtype: float64
106249 106256    341.0
Name: new_cases, dtype: float64
106250 106257    546.0
Name: new_cases, dtype: float64
106251 106258    536.0
Name: new_cases, dtype: float64
106252 106259    106.0
Name: new_cases, dtype: float64
106253 106260    613.0
Name: new_cases, dtype: float64
106254 106261    710.0
Name: new_cases, dtype: float64
106255 106262    70.0
Name: new_cases, dtype: float64
106256 106263    1147.0
Name: new_cases, dtype: float64
106257 106264    511.0
Name: new_cases, dtype: float64
106258 106265    1079.0
Name: new_cases, dtype: float64
106259 106266    785.0
Name: new_cases, dtype: float64
106260 106267    783.0
Name: new_cases, dtype: float64
106261 106268    605.0
Name: new_cases, dtype: float64
106262 106269    587.0
Name: new_cases, dtype: float64
106263 106270    697.0
Name: new_cases, dtype: float64
106264 106271    913.0
Name: new_cases, dtype: float64
106265 106272    1292.0
Name: new_cases, dtype: float64
106266 106273    1297.0
Name: new_cases, dtype: float64
106267 106274    989.0
Name: new_cases, dtype: float64
106268 106275    981.0
Name: new_cases, dtype: float64
106269 106276    857.0
Name: new_cases, dtype: float64
106270 106277    1108.0
Name: new_cases, dtype: float64
106271 106278    2024.0
Name: new_cases, dtype: float64
106272 106279    571.0
Name: new_cases, dtype: float64
106273 106280    1791.0
Name: new_cases, dtype: float64
106274 106281    2301.0
Name: new_cases, dtype: float64
106275 106282    1598.0
Name: new_cases, dtype: float64
106276 106283    1747.0
Name: new_cases, dtype: float64
106277 106284    2255.0
Name: new_cases, dtype: float64
106278 106285    962.0
Name: new_cases, dtype: float64
106279 106286    490.0
Name: new_cases, dtype: float64
106280 106287    3011.0
Name: new_cases, dtype: float64
106281 106288    0.0
Name: new_cases, dtype: float64
106282 106289    1352.0
Name: new_cases, dtype: float64
106283 106290    1974.0
Name: new_cases, dtype: float64
106284 106291    1841.0
Name: new_cases, dtype: float64
106285 106292    1932.0
Name: new_cases, dtype: float64
106286 106293    2193.0
Name: new_cases, dtype: float64
106287 106294    2603.0
Name: new_cases, dtype: float64
106288 106295    1743.0
Name: new_cases, dtype: float64
106289 106296    2164.0
Name: new_cases, dtype: float64
106290 106297    1748.0
Name: new_cases, dtype: float64
106291 106298    1356.0
Name: new_cases, dtype: float64
106292 106299    1446.0
Name: new_cases, dtype: float64
106293 106300    2076.0
Name: new_cases, dtype: float64
106294 106301    2801.0
Name: new_cases, dtype: float64
106295 106302    2429.0
Name: new_cases, dtype: float64
106296 106303    3039.0
Name: new_cases, dtype: float64
106297 106304    2964.0
Name: new_cases, dtype: float64

106298 106305    3938.0
Name: new_cases, dtype: float64
106299 106306    4065.0
Name: new_cases, dtype: float64
106300 106307    4801.0
Name: new_cases, dtype: float64
106301 106308    3985.0
Name: new_cases, dtype: float64
106302 106309    4734.0
Name: new_cases, dtype: float64
106303 106310    4960.0
Name: new_cases, dtype: float64
106304 106311    4728.0
Name: new_cases, dtype: float64
106305 106312    4646.0
Name: new_cases, dtype: float64
106306 106313    5385.0
Name: new_cases, dtype: float64
106307 106314    5834.0
Name: new_cases, dtype: float64
106308 106315    6397.0
Name: new_cases, dtype: float64
106309 106316    0.0
Name: new_cases, dtype: float64
106310 106317    6472.0
Name: new_cases, dtype: float64
106311 106318    12073.0
Name: new_cases, dtype: float64
106312 106319    4443.0
Name: new_cases, dtype: float64
106313 106320    5839.0
Name: new_cases, dtype: float64
106314 106321    5358.0
Name: new_cases, dtype: float64
106315 106322    4944.0
Name: new_cases, dtype: float64
106316 106323    6604.0
Name: new_cases, dtype: float64
106317 106324    4951.0
Name: new_cases, dtype: float64
106318 106325    4471.0
Name: new_cases, dtype: float64
106319 106326    3946.0
Name: new_cases, dtype: float64
106320 106327    3892.0
Name: new_cases, dtype: float64
106321 106328    4044.0
Name: new_cases, dtype: float64
106322 106329    2775.0
Name: new_cases, dtype: float64
106323 106330    3138.0
Name: new_cases, dtype: float64
106324 106331    4072.0
Name: new_cases, dtype: float64
106325 106332    3557.0
Name: new_cases, dtype: float64
106326 106333    2825.0
Name: new_cases, dtype: float64
106327 106334    4133.0
Name: new_cases, dtype: float64
106328 106335    4339.0
Name: new_cases, dtype: float64
106329 106336    4087.0
Name: new_cases, dtype: float64
106330 106337    0.0
Name: new_cases, dtype: float64
106331 106338    3387.0
Name: new_cases, dtype: float64
106332 106339    6535.0
Name: new_cases, dtype: float64
106333 106340    2691.0
Name: new_cases, dtype: float64
106334 106341    2980.0
Name: new_cases, dtype: float64
106335 106342    3359.0
Name: new_cases, dtype: float64
106336 106343    2751.0
Name: new_cases, dtype: float64
106337 106344    2752.0
Name: new_cases, dtype: float64
106338 106345    2521.0
Name: new_cases, dtype: float64
106339 106346    2753.0
Name: new_cases, dtype: float64
106340 106347    1979.0
Name: new_cases, dtype: float64
106341 106348    2165.0
Name: new_cases, dtype: float64
106342 106349    2145.0
Name: new_cases, dtype: float64
106343 106350    0.0
Name: new_cases, dtype: float64
106344 106351    4003.0
Name: new_cases, dtype: float64
106345 106352    1579.0
Name: new_cases, dtype: float64
106346 106353    1587.0
Name: new_cases, dtype: float64
106347 106354    1013.0
Name: new_cases, dtype: float64
106348 106355    1332.0
Name: new_cases, dtype: float64
106349 106356    1763.0
Name: new_cases, dtype: float64
106350 106357    1209.0
Name: new_cases, dtype: float64
106351 106358    1487.0
Name: new_cases, dtype: float64
106352 106359    1226.0
Name: new_cases, dtype: float64
106353 106360    0.0
Name: new_cases, dtype: float64
106354 106361    1176.0
Name: new_cases, dtype: float64
106355 106362    936.0
Name: new_cases, dtype: float64
106356 106363    1063.0
Name: new_cases, dtype: float64
106357 106364    1114.0
Name: new_cases, dtype: float64
106358 106365    903.0
Name: new_cases, dtype: float64
106359 106366    0.0
Name: new_cases, dtype: float64
106360 106367    1394.0
Name: new_cases, dtype: float64
106361 106368    762.0
Name: new_cases, dtype: float64
106362 106369    0.0
Name: new_cases, dtype: float64
106363 106370    675.0
Name: new_cases, dtype: float64
106364 106371    727.0
Name: new_cases, dtype: float64
106365 106372    782.0
Name: new_cases, dtype: float64
106366 106373    842.0
Name: new_cases, dtype: float64
106367 106374    634.0
Name: new_cases, dtype: float64
106368 106375    539.0
Name: new_cases, dtype: float64
106369 106376    531.0
Name: new_cases, dtype: float64
106370 106377    730.0
Name: new_cases, dtype: float64
106371 106378    753.0
Name: new_cases, dtype: float64
106372 106379    626.0
Name: new_cases, dtype: float64
106373 106380    747.0
Name: new_cases, dtype: float64
106374 106381    1168.0
Name: new_cases, dtype: float64
106375 106382    0.0
Name: new_cases, dtype: float64
106376 106383    617.0
Name: new_cases, dtype: float64
106377 106384    613.0
Name: new_cases, dtype: float64
106378 106385    513.0
Name: new_cases, dtype: float64
106379 106386    630.0
Name: new_cases, dtype: float64
106380 106387    586.0
Name: new_cases, dtype: float64
106381 106388    1087.0
Name: new_cases, dtype: float64
106382 106389    0.0
Name: new_cases, dtype: float64
106383 106390    450.0
Name: new_cases, dtype: float64
106384 106391    482.0
Name: new_cases, dtype: float64
106385 106392    445.0
Name: new_cases, dtype: float64
106386 106393    415.0
Name: new_cases, dtype: float64
106387 106394    319.0
Name: new_cases, dtype: float64
106388 106395    264.0
Name: new_cases, dtype: float64
106389 106396    213.0
Name: new_cases, dtype: float64
106390 106397    300.0
Name: new_cases, dtype: float64
106391 106398    865.0
Name: new_cases, dtype: float64
106392 106399    498.0
Name: new_cases, dtype: float64
106393 106400    513.0
Name: new_cases, dtype: float64
106394 106401    0.0
Name: new_cases, dtype: float64
106395 106402    878.0
Name: new_cases, dtype: float64
106396 106403    330.0
Name: new_cases, dtype: float64
106397 106404    426.0
Name: new_cases, dtype: float64
106398 106405    371.0
Name: new_cases, dtype: float64
106399 106406    341.0
Name: new_cases, dtype: float64
106400 106407    584.0
Name: new_cases, dtype: float64
106401 106408    526.0
Name: new_cases, dtype: float64
106402 106409    539.0
Name: new_cases, dtype: float64
106403 106410    404.0
Name: new_cases, dtype: float64
106404 106411    665.0
Name: new_cases, dtype: float64
106405 106412    545.0
Name: new_cases, dtype: float64
106406 106413    752.0
Name: new_cases, dtype: float64
106407 106414    645.0
Name: new_cases, dtype: float64
106408 106415    640.0
Name: new_cases, dtype: float64
106409 106416    633.0
Name: new_cases, dtype: float64
106410 106417    582.0
Name: new_cases, dtype: float64
106411 106418    532.0
Name: new_cases, dtype: float64
106412 106419    799.0
Name: new_cases, dtype: float64
106413 106420    798.0
Name: new_cases, dtype: float64
106414 106421    566.0
Name: new_cases, dtype: float64
106415 106422    694.0
Name: new_cases, dtype: float64
106416 106423    566.0
Name: new_cases, dtype: float64
106417 106424    675.0
Name: new_cases, dtype: float64
106418 106425    747.0
Name: new_cases, dtype: float64
106419 106426    543.0
Name: new_cases, dtype: float64
106420 106427    625.0
Name: new_cases, dtype: float64
106421 106428    553.0
Name: new_cases, dtype: float64
106422 106429    632.0
Name: new_cases, dtype: float64
106423 106430    0.0
Name: new_cases, dtype: float64
106424 106431    1111.0
Name: new_cases, dtype: float64
106425 106432    624.0
Name: new_cases, dtype: float64
106426 106433    583.0
Name: new_cases, dtype: float64
106427 106434    661.0
Name: new_cases, dtype: float64
106428 106435    671.0
Name: new_cases, dtype: float64
106429 106436    666.0
Name: new_cases, dtype: float64
106430 106437    385.0
Name: new_cases, dtype: float64
106431 106438    531.0
Name: new_cases, dtype: float64
106432 106439    615.0
Name: new_cases, dtype: float64
106433 106440    755.0
Name: new_cases, dtype: float64
106434 106441    659.0
Name: new_cases, dtype: float64
106435 106442    575.0
Name: new_cases, dtype: float64
106436 106443    567.0
Name: new_cases, dtype: float64
106437 106444    433.0
Name: new_cases, dtype: float64
106438 106445    582.0
Name: new_cases, dtype: float64
106439 106446    710.0
Name: new_cases, dtype: float64
106440 106447    736.0
Name: new_cases, dtype: float64
106441 106448    736.0
Name: new_cases, dtype: float64
106442 106449    847.0
Name: new_cases, dtype: float64
106443 106450    832.0
Name: new_cases, dtype: float64
106444 106451    707.0
Name: new_cases, dtype: float64
106445 106452    773.0
Name: new_cases, dtype: float64
106446 106453    825.0
Name: new_cases, dtype: float64
106447 106454    908.0
Name: new_cases, dtype: float64
106448 106455    1078.0
Name: new_cases, dtype: float64
106449 106456    807.0
Name: new_cases, dtype: float64
106450 106457    977.0
Name: new_cases, dtype: float64
106451 106458    1123.0
Name: new_cases, dtype: float64
106452 106459    1167.0
Name: new_cases, dtype: float64
106453 106460    1313.0
Name: new_cases, dtype: float64
106454 106461    1302.0
Name: new_cases, dtype: float64
106455 106462    1376.0
Name: new_cases, dtype: float64
106456 106463    1502.0
Name: new_cases, dtype: float64

106457 106464    1436.0
Name: new_cases, dtype: float64
106458 106465    1650.0
Name: new_cases, dtype: float64
106459 106466    1637.0
Name: new_cases, dtype: float64
106460 106467    1708.0
Name: new_cases, dtype: float64
106461 106468    1808.0
Name: new_cases, dtype: float64
106462 106469    2304.0
Name: new_cases, dtype: float64
106463 106470    2165.0
Name: new_cases, dtype: float64
106464 106471    2443.0
Name: new_cases, dtype: float64
106465 106472    2128.0
Name: new_cases, dtype: float64
106466 106473    2050.0
Name: new_cases, dtype: float64
106467 106474    2298.0
Name: new_cases, dtype: float64
106468 106475    2547.0
Name: new_cases, dtype: float64
106469 106476    2738.0
Name: new_cases, dtype: float64
106470 106477    2843.0
Name: new_cases, dtype: float64
106471 106478    2665.0
Name: new_cases, dtype: float64
106472 106479    2756.0
Name: new_cases, dtype: float64
106473 106480    2954.0
Name: new_cases, dtype: float64
106474 106481    3009.0
Name: new_cases, dtype: float64
106475 106482    3306.0
Name: new_cases, dtype: float64
106476 106483    3113.0
Name: new_cases, dtype: float64
106477 106484    3045.0
Name: new_cases, dtype: float64
106478 106485    2829.0
Name: new_cases, dtype: float64
106479 106486    2839.0
Name: new_cases, dtype: float64
106480 106487    2458.0
Name: new_cases, dtype: float64
106481 106488    2829.0
Name: new_cases, dtype: float64
106482 106489    3499.0
Name: new_cases, dtype: float64
106483 106490    3262.0
Name: new_cases, dtype: float64
106484 106491    3119.0
Name: new_cases, dtype: float64
106485 106492    3308.0
Name: new_cases, dtype: float64
106486 106493    3795.0
Name: new_cases, dtype: float64
106487 106494    2885.0
Name: new_cases, dtype: float64
106488 106495    2963.0
Name: new_cases, dtype: float64
106489 106496    3138.0
Name: new_cases, dtype: float64
106490 106497    3047.0
Name: new_cases, dtype: float64
106491 106498    2729.0
Name: new_cases, dtype: float64
106492 106499    3369.0
Name: new_cases, dtype: float64
106493 106500    2362.0
Name: new_cases, dtype: float64
106494 106501    2459.0
Name: new_cases, dtype: float64
106495 106502    2731.0
Name: new_cases, dtype: float64
106496 106503    2545.0
Name: new_cases, dtype: float64
106497 106504    2972.0
Name: new_cases, dtype: float64
106498 106505    3179.0
Name: new_cases, dtype: float64
106499 106506    2615.0
Name: new_cases, dtype: float64
106500 106507    1680.0
Name: new_cases, dtype: float64
106501 106508    1704.0
Name: new_cases, dtype: float64
106502 106509    2142.0
Name: new_cases, dtype: float64
106503 106510    2256.0
Name: new_cases, dtype: float64
106504 106511    2152.0
Name: new_cases, dtype: float64
106505 106512    2260.0
Name: new_cases, dtype: float64
106506 106513    1853.0
Name: new_cases, dtype: float64
106507 106514    1974.0
Name: new_cases, dtype: float64
106508 106515    1776.0
Name: new_cases, dtype: float64
106509 106516    2155.0
Name: new_cases, dtype: float64
106510 106517    2475.0
Name: new_cases, dtype: float64
106511 106518    2463.0
Name: new_cases, dtype: float64
106512 106519    2184.0
Name: new_cases, dtype: float64
106513 106520    2272.0
Name: new_cases, dtype: float64
106514 106521    1895.0
Name: new_cases, dtype: float64
106515 106522    1947.0
Name: new_cases, dtype: float64
106516 106523    2118.0
Name: new_cases, dtype: float64
106517 106524    2481.0
Name: new_cases, dtype: float64
106518 106525    2435.0
Name: new_cases, dtype: float64
106519 106526    2007.0
Name: new_cases, dtype: float64
106520 106527    2899.0
Name: new_cases, dtype: float64
106521 106528    1877.0
Name: new_cases, dtype: float64
106522 106529    2408.0
Name: new_cases, dtype: float64
106523 106530    2123.0
Name: new_cases, dtype: float64
106524 106531    3097.0
Name: new_cases, dtype: float64
106525 106532    2417.0
Name: new_cases, dtype: float64
106526 106533    2432.0
Name: new_cases, dtype: float64
106527 106534    2521.0
Name: new_cases, dtype: float64
106528 106535    1920.0
Name: new_cases, dtype: float64
106529 106536    1800.0
Name: new_cases, dtype: float64
106530 106537    1772.0
Name: new_cases, dtype: float64
106531 106538    2363.0
Name: new_cases, dtype: float64
106532 106539    1745.0
Name: new_cases, dtype: float64
106533 106540    1927.0
Name: new_cases, dtype: float64
106534 106541    1594.0
Name: new_cases, dtype: float64
106535 106542    1629.0
Name: new_cases, dtype: float64
106536 106543    1873.0
Name: new_cases, dtype: float64
106537 106544    1563.0
Name: new_cases, dtype: float64
106538 106545    1910.0
Name: new_cases, dtype: float64
106539 106546    1644.0
Name: new_cases, dtype: float64
106540 106547    2183.0
Name: new_cases, dtype: float64
106541 106548    1599.0
Name: new_cases, dtype: float64
106542 106549    1615.0
Name: new_cases, dtype: float64
106543 106550    1220.0
Name: new_cases, dtype: float64
106544 106551    1384.0
Name: new_cases, dtype: float64
106545 106552    1508.0
Name: new_cases, dtype: float64
106546 106553    1302.0
Name: new_cases, dtype: float64
106547 106554    1286.0
Name: new_cases, dtype: float64
106548 106555    1346.0
Name: new_cases, dtype: float64
106549 106556    1037.0
Name: new_cases, dtype: float64
106550 106557    1008.0
Name: new_cases, dtype: float64
106551 106558    1072.0
Name: new_cases, dtype: float64
106552 106559    1502.0
Name: new_cases, dtype: float64
106553 106560    1270.0
Name: new_cases, dtype: float64
106554 106561    1262.0
Name: new_cases, dtype: float64
106555 106562    1404.0
Name: new_cases, dtype: float64
106556 106563    1048.0
Name: new_cases, dtype: float64
106557 106564    0.0
Name: new_cases, dtype: float64
106558 106565    1912.0
Name: new_cases, dtype: float64
106559 106566    1272.0
Name: new_cases, dtype: float64
106560 106567    1245.0
Name: new_cases, dtype: float64
106561 106568    1340.0
Name: new_cases, dtype: float64
106562 106569    1328.0
Name: new_cases, dtype: float64
106563 106570    1160.0
Name: new_cases, dtype: float64
106564 106571    1050.0
Name: new_cases, dtype: float64
106565 106572    1196.0
Name: new_cases, dtype: float64
106566 106573    1361.0
Name: new_cases, dtype: float64
106567 106574    1541.0
Name: new_cases, dtype: float64
106568 106575    1315.0
Name: new_cases, dtype: float64
106569 106576    1176.0
Name: new_cases, dtype: float64
106570 106577    1392.0
Name: new_cases, dtype: float64
106571 106578    1163.0
Name: new_cases, dtype: float64
106572 106579    1388.0
Name: new_cases, dtype: float64
106573 106580    1519.0
Name: new_cases, dtype: float64
106574 106581    1579.0
Name: new_cases, dtype: float64
106575 106582    1714.0
Name: new_cases, dtype: float64
106576 106583    1780.0
Name: new_cases, dtype: float64
106577 106584    1592.0
Name: new_cases, dtype: float64
106578 106585    1353.0
Name: new_cases, dtype: float64
106579 106586    1786.0
Name: new_cases, dtype: float64
106580 106587    2258.0
Name: new_cases, dtype: float64
106581 106588    2701.0
Name: new_cases, dtype: float64
106582 106589    2338.0
Name: new_cases, dtype: float64
106583 106590    2664.0
Name: new_cases, dtype: float64
106584 106591    2253.0
Name: new_cases, dtype: float64
106585 106592    2511.0
Name: new_cases, dtype: float64
106586 106593    2351.0
Name: new_cases, dtype: float64
106587 106594    3495.0
Name: new_cases, dtype: float64
106588 106595    3449.0
Name: new_cases, dtype: float64
106589 106596    3876.0
Name: new_cases, dtype: float64
106590 106597    3667.0
Name: new_cases, dtype: float64
106591 106598    3669.0
Name: new_cases, dtype: float64
106592 106599    3270.0
Name: new_cases, dtype: float64
106593 106600    3301.0
Name: new_cases, dtype: float64
106594 106601    3946.0
Name: new_cases, dtype: float64
106595 106602    4368.0
Name: new_cases, dtype: float64
106596 106603    4468.0
Name: new_cases, dtype: float64
106597 106604    4767.0
Name: new_cases, dtype: float64
106598 106605    4525.0
Name: new_cases, dtype: float64
106599 106606    4084.0
Name: new_cases, dtype: float64
106600 106607    4757.0
Name: new_cases, dtype: float64
106601 106608    4974.0
Name: new_cases, dtype: float64
106602 106609    5234.0
Name: new_cases, dtype: float64
106603 106610    4723.0
Name: new_cases, dtype: float64

106604 106611    5020.0
Name: new_cases, dtype: float64
106605 106612    4323.0
Name: new_cases, dtype: float64
106606 106613    3953.0
Name: new_cases, dtype: float64
106607 106614    4004.0
Name: new_cases, dtype: float64
106608 106615    5329.0
Name: new_cases, dtype: float64
106609 106616    5312.0
Name: new_cases, dtype: float64
106610 106617    5139.0
Name: new_cases, dtype: float64
106611 106618    5050.0
Name: new_cases, dtype: float64
106612 106619    4584.0
Name: new_cases, dtype: float64
106613 106620    4318.0
Name: new_cases, dtype: float64
106614 106621    4503.0
Name: new_cases, dtype: float64
106615 106622    5395.0
Name: new_cases, dtype: float64
106616 106623    5364.0
Name: new_cases, dtype: float64
106617 106624    4976.0
Name: new_cases, dtype: float64
106618 106625    6127.0
Name: new_cases, dtype: float64
106619 106626    5152.0
Name: new_cases, dtype: float64
106620 106627    5445.0
Name: new_cases, dtype: float64
106621 106628    5499.0
Name: new_cases, dtype: float64
106622 106629    5857.0
Name: new_cases, dtype: float64
106623 106630    5870.0
Name: new_cases, dtype: float64
106624 106631    5908.0
Name: new_cases, dtype: float64
106625 106632    5611.0
Name: new_cases, dtype: float64
106626 106633    4825.0
Name: new_cases, dtype: float64
106627 106634    4487.0
Name: new_cases, dtype: float64
106628 106635    5292.0
Name: new_cases, dtype: float64
106629 106636    5480.0
Name: new_cases, dtype: float64
106630 106637    5112.0
Name: new_cases, dtype: float64
106631 106638    4696.0
Name: new_cases, dtype: float64
106632 106639    4414.0
Name: new_cases, dtype: float64
106633 106640    4213.0
Name: new_cases, dtype: float64
106634 106641    3377.0
Name: new_cases, dtype: float64
106635 106642    0.0
Name: new_cases, dtype: float64
106636 106643    4113.0
Name: new_cases, dtype: float64
106637 106644    8495.0
Name: new_cases, dtype: float64
106638 106645    4109.0
Name: new_cases, dtype: float64
106639 106646    3786.0
Name: new_cases, dtype: float64
106640 106647    3447.0
Name: new_cases, dtype: float64
106641 106648    3084.0
Name: new_cases, dtype: float64
106642 106649    2881.0
Name: new_cases, dtype: float64
106643 106650    3265.0
Name: new_cases, dtype: float64
106644 106651    2517.0
Name: new_cases, dtype: float64
106645 106652    1531.0
Name: new_cases, dtype: float64
106646 106653    2379.0
Name: new_cases, dtype: float64
106647 106654    3232.0
Name: new_cases, dtype: float64
106648 106655    2566.0
Name: new_cases, dtype: float64
106649 106656    3256.0
Name: new_cases, dtype: float64
106650 106657    4207.0
Name: new_cases, dtype: float64
106651 106658    3070.0
Name: new_cases, dtype: float64
106652 106659    4007.0
Name: new_cases, dtype: float64
106653 106660    3084.0
Name: new_cases, dtype: float64
106654 106661    3047.0
Name: new_cases, dtype: float64
106655 106662    2253.0
Name: new_cases, dtype: float64
106656 106663    2724.0
Name: new_cases, dtype: float64
106657 106664    2726.0
Name: new_cases, dtype: float64
106658 106665    2482.0
Name: new_cases, dtype: float64
106659 106666    2455.0
Name: new_cases, dtype: float64
106660 106667    2697.0
Name: new_cases, dtype: float64
106661 106668    2117.0
Name: new_cases, dtype: float64
106662 106669    1771.0
Name: new_cases, dtype: float64
106663 106670    1843.0
Name: new_cases, dtype: float64
106664 106671    2028.0
Name: new_cases, dtype: float64
106665 106672    1893.0
Name: new_cases, dtype: float64
106666 106673    1923.0
Name: new_cases, dtype: float64
106667 106674    1629.0
Name: new_cases, dtype: float64
106668 106675    1490.0
Name: new_cases, dtype: float64
106669 106676    1383.0
Name: new_cases, dtype: float64
106670 106677    1118.0
Name: new_cases, dtype: float64
106671 106678    1303.0
Name: new_cases, dtype: float64
106672 106679    1303.0
Name: new_cases, dtype: float64
106673 106680    1194.0
Name: new_cases, dtype: float64
106674 106681    1239.0
Name: new_cases, dtype: float64
106675 106682    1019.0
Name: new_cases, dtype: float64
106676 106683    838.0
Name: new_cases, dtype: float64
106677 106684    1038.0
Name: new_cases, dtype: float64
106678 106685    1119.0
Name: new_cases, dtype: float64
106679 106686    1043.0
Name: new_cases, dtype: float64
106680 106687    991.0
Name: new_cases, dtype: float64
106681 106688    0.0
Name: new_cases, dtype: float64
106682 106689    1957.0
Name: new_cases, dtype: float64
106683 106690    663.0
Name: new_cases, dtype: float64
106684 106691    930.0
Name: new_cases, dtype: float64
106685 106692    1097.0
Name: new_cases, dtype: float64
106686 106693    1042.0
Name: new_cases, dtype: float64
106687 106694    935.0
Name: new_cases, dtype: float64
106688 106695    901.0
Name: new_cases, dtype: float64
106689 106696    914.0
Name: new_cases, dtype: float64
106690 106697    735.0
Name: new_cases, dtype: float64
106691 106698    979.0
Name: new_cases, dtype: float64
106692 106699    1037.0
Name: new_cases, dtype: float64
106693 106700    1277.0
Name: new_cases, dtype: float64
106694 106701    1400.0
Name: new_cases, dtype: float64
106695 106702    1228.0
Name: new_cases, dtype: float64
106696 106703    1347.0
Name: new_cases, dtype: float64
106697 106704    830.0
Name: new_cases, dtype: float64
106698 106705    1517.0
Name: new_cases, dtype: float64
106699 106706    1626.0
Name: new_cases, dtype: float64
106700 106707    1843.0
Name: new_cases, dtype: float64
106701 106708    1828.0
Name: new_cases, dtype: float64
106702 106709    1980.0
Name: new_cases, dtype: float64
106703 106710    1808.0
Name: new_cases, dtype: float64
106704 106711    1775.0
Name: new_cases, dtype: float64
106705 106712    1980.0
Name: new_cases, dtype: float64
106706 106713    2545.0
Name: new_cases, dtype: float64
106707 106714    2327.0
Name: new_cases, dtype: float64
106708 106715    2949.0
Name: new_cases, dtype: float64
106709 106716    2607.0
Name: new_cases, dtype: float64
106710 106717    2452.0
Name: new_cases, dtype: float64
106711 106718    2145.0
Name: new_cases, dtype: float64
106712 106719    2579.0
Name: new_cases, dtype: float64
106713 106720    2158.0
Name: new_cases, dtype: float64
106714 106721    1425.0
Name: new_cases, dtype: float64
106715 106722    0.0
Name: new_cases, dtype: float64
106716 106723    4660.0
Name: new_cases, dtype: float64
106717 106724    3752.0
Name: new_cases, dtype: float64
106718 106725    3262.0
Name: new_cases, dtype: float64
106719 106726    4119.0
Name: new_cases, dtype: float64
106720 106727    4497.0
Name: new_cases, dtype: float64
106721 106728    4537.0
Name: new_cases, dtype: float64
106722 106729    4950.0
Name: new_cases, dtype: float64
106723 106730    5026.0
Name: new_cases, dtype: float64
106724 106731    4858.0
Name: new_cases, dtype: float64
106725 106732    3582.0
Name: new_cases, dtype: float64
106726 106733    4722.0
Name: new_cases, dtype: float64
106727 106734    5661.0
Name: new_cases, dtype: float64
106728 106735    4745.0
Name: new_cases, dtype: float64
106729 106736    4720.0
Name: new_cases, dtype: float64
106730 106737    4455.0
Name: new_cases, dtype: float64
106731 106738    4040.0
Name: new_cases, dtype: float64
106732 106739    3884.0
Name: new_cases, dtype: float64
106733 106740    4856.0
Name: new_cases, dtype: float64
106734 106741    4934.0
Name: new_cases, dtype: float64
106735 106742    4619.0
Name: new_cases, dtype: float64
106736 106743    4786.0
Name: new_cases, dtype: float64
106737 106744    3711.0
Name: new_cases, dtype: float64
106738 106745    3669.0
Name: new_cases, dtype: float64
106739 106746    3221.0
Name: new_cases, dtype: float64
106740 106747    3974.0
Name: new_cases, dtype: float64
106741 106748    4373.0
Name: new_cases, dtype: float64
106742 106749    3239.0
Name: new_cases, dtype: float64
106743 106750    3084.0
Name: new_cases, dtype: float64
106744 106751    3842.0
Name: new_cases, dtype: float64
106745 106752    3772.0
Name: new_cases, dtype: float64
106746 106753    4075.0
Name: new_cases, dtype: float64
106747 106754    4199.0
Name: new_cases, dtype: float64
106748 106755    4553.0
Name: new_cases, dtype: float64
106749 106756    3930.0
Name: new_cases, dtype: float64
106750 106757    4231.0
Name: new_cases, dtype: float64
106751 106758    3909.0
Name: new_cases, dtype: float64
106752 106759    3800.0
Name: new_cases, dtype: float64
106753 106760    3838.0
Name: new_cases, dtype: float64
106754 106761    3569.0
Name: new_cases, dtype: float64
106755 106762    4069.0
Name: new_cases, dtype: float64
106756 106763    3821.0
Name: new_cases, dtype: float64
106757 106764    0.0
Name: new_cases, dtype: float64
106758 106765    7727.0
Name: new_cases, dtype: float64
106759 106766    3613.0
Name: new_cases, dtype: float64
106760 106767    3316.0
Name: new_cases, dtype: float64
106761 106768    3902.0
Name: new_cases, dtype: float64

106762 106769    4062.0
Name: new_cases, dtype: float64
106763 106770    3689.0
Name: new_cases, dtype: float64
106764 106771    3480.0
Name: new_cases, dtype: float64
106765 106772    3153.0
Name: new_cases, dtype: float64
106766 106773    2988.0
Name: new_cases, dtype: float64
106767 106774    2574.0
Name: new_cases, dtype: float64
106768 106775    2727.0
Name: new_cases, dtype: float64
106769 106776    3012.0
Name: new_cases, dtype: float64
106770 106777    2928.0
Name: new_cases, dtype: float64
106771 106778    2512.0
Name: new_cases, dtype: float64
106772 106779    2580.0
Name: new_cases, dtype: float64
106773 106780    2167.0
Name: new_cases, dtype: float64
106774 106781    1897.0
Name: new_cases, dtype: float64
106775 106782    2333.0
Name: new_cases, dtype: float64
106776 106783    2357.0
Name: new_cases, dtype: float64
106777 106784    2233.0
Name: new_cases, dtype: float64
106778 106785    2060.0
Name: new_cases, dtype: float64
106779 106786    1780.0
Name: new_cases, dtype: float64
106780 106787    1757.0
Name: new_cases, dtype: float64
106781 106788    1400.0
Name: new_cases, dtype: float64
106782 106789    1560.0
Name: new_cases, dtype: float64
106783 106790    1742.0
Name: new_cases, dtype: float64
106784 106791    1411.0
Name: new_cases, dtype: float64
106785 106792    1664.0
Name: new_cases, dtype: float64
106786 106793    1656.0
Name: new_cases, dtype: float64
106787 106794    1490.0
Name: new_cases, dtype: float64
106788 106795    1308.0
Name: new_cases, dtype: float64
106789 106796    1212.0
Name: new_cases, dtype: float64
106790 106797    1453.0
Name: new_cases, dtype: float64
106791 106798    912.0
Name: new_cases, dtype: float64
106792 106799    955.0
Name: new_cases, dtype: float64
106793 106800    827.0
Name: new_cases, dtype: float64
106794 106801    944.0
Name: new_cases, dtype: float64
106795 106802    689.0
Name: new_cases, dtype: float64
106796 106803    1021.0
Name: new_cases, dtype: float64
106797 106804    1016.0
Name: new_cases, dtype: float64
106798 106805    1086.0
Name: new_cases, dtype: float64
106799 106806    893.0
Name: new_cases, dtype: float64
106800 106807    720.0
Name: new_cases, dtype: float64
106801 106808    663.0
Name: new_cases, dtype: float64
106802 106809    603.0
Name: new_cases, dtype: float64
106803 106810    554.0
Name: new_cases, dtype: float64
106804 106811    622.0
Name: new_cases, dtype: float64
106805 106812    567.0
Name: new_cases, dtype: float64
106806 106813    552.0
Name: new_cases, dtype: float64
106807 106814    591.0
Name: new_cases, dtype: float64
106808 106815    698.0
Name: new_cases, dtype: float64
106809 106816    572.0
Name: new_cases, dtype: float64
106810 106817    516.0
Name: new_cases, dtype: float64
106811 106818    705.0
Name: new_cases, dtype: float64
106812 106819    660.0
Name: new_cases, dtype: float64
106813 106820    658.0
Name: new_cases, dtype: float64
106814 106821    733.0
Name: new_cases, dtype: float64
106815 106822    482.0
Name: new_cases, dtype: float64
106816 106823    457.0
Name: new_cases, dtype: float64
106817 106824    561.0
Name: new_cases, dtype: float64
106818 106825    580.0
Name: new_cases, dtype: float64
106819 106826    515.0
Name: new_cases, dtype: float64
106820 106827    567.0
Name: new_cases, dtype: float64
106821 106828    471.0
Name: new_cases, dtype: float64
106822 106829    449.0
Name: new_cases, dtype: float64
106823 106830    400.0
Name: new_cases, dtype: float64
106824 106831    554.0
Name: new_cases, dtype: float64
106825 106832    637.0
Name: new_cases, dtype: float64
106826 106833    391.0
Name: new_cases, dtype: float64
106827 106834    231.0
Name: new_cases, dtype: float64
106828 106835    0.0
Name: new_cases, dtype: float64
106829 106836    503.0
Name: new_cases, dtype: float64
106830 106837    216.0
Name: new_cases, dtype: float64
106831 106838    270.0
Name: new_cases, dtype: float64
106832 106839    460.0
Name: new_cases, dtype: float64
106833 106840    418.0
Name: new_cases, dtype: float64
106834 106841    319.0
Name: new_cases, dtype: float64
106835 106842    313.0
Name: new_cases, dtype: float64
106836 106843    323.0
Name: new_cases, dtype: float64
106837 106844    315.0
Name: new_cases, dtype: float64
106838 106845    350.0
Name: new_cases, dtype: float64
106839 106846    363.0
Name: new_cases, dtype: float64
106840 106847    252.0
Name: new_cases, dtype: float64
106841 106848    411.0
Name: new_cases, dtype: float64
106842 106849    303.0
Name: new_cases, dtype: float64
106843 106850    176.0
Name: new_cases, dtype: float64
106844 106851    475.0
Name: new_cases, dtype: float64
106845 106852    414.0
Name: new_cases, dtype: float64
106846 106853    377.0
Name: new_cases, dtype: float64
106847 106854    391.0
Name: new_cases, dtype: float64
106848 106855    431.0
Name: new_cases, dtype: float64
106849 106856    372.0
Name: new_cases, dtype: float64
106850 106857    336.0
Name: new_cases, dtype: float64
106851 106858    232.0
Name: new_cases, dtype: float64
106852 106859    310.0
Name: new_cases, dtype: float64
106853 106860    350.0
Name: new_cases, dtype: float64
106854 106861    313.0
Name: new_cases, dtype: float64
106855 106862    395.0
Name: new_cases, dtype: float64
106856 106863    288.0
Name: new_cases, dtype: float64
106857 106864    244.0
Name: new_cases, dtype: float64
106858 106865    250.0
Name: new_cases, dtype: float64
106859 106866    370.0
Name: new_cases, dtype: float64
106860 106867    301.0
Name: new_cases, dtype: float64
106861 106868    277.0
Name: new_cases, dtype: float64
106862 106869    0.0
Name: new_cases, dtype: float64
106863 106870    617.0
Name: new_cases, dtype: float64
106864 106871    359.0
Name: new_cases, dtype: float64
106865 106872    270.0
Name: new_cases, dtype: float64
106866 106873    310.0
Name: new_cases, dtype: float64
106867 106874    359.0
Name: new_cases, dtype: float64
106868 106875    322.0
Name: new_cases, dtype: float64
106869 106876    353.0
Name: new_cases, dtype: float64
106870 106877    359.0
Name: new_cases, dtype: float64
106871 106878    275.0
Name: new_cases, dtype: float64
106872 106879    316.0
Name: new_cases, dtype: float64
106873 106880    348.0
Name: new_cases, dtype: float64
106874 106881    482.0
Name: new_cases, dtype: float64
106875 106882    515.0
Name: new_cases, dtype: float64
106876 106883    557.0
Name: new_cases, dtype: float64
106877 106884    594.0
Name: new_cases, dtype: float64
106878 106885    708.0
Name: new_cases, dtype: float64
106879 106886    630.0
Name: new_cases, dtype: float64
106880 106887    898.0
Name: new_cases, dtype: float64
106881 106888    1085.0
Name: new_cases, dtype: float64
106882 106889    1293.0
Name: new_cases, dtype: float64
106883 106890    1345.0
Name: new_cases, dtype: float64
106884 106891    1572.0
Name: new_cases, dtype: float64
106885 106220    0.0
Name: new_cases, dtype: float64
106886 106221    10.0
Name: new_cases, dtype: float64
106887 106222    3.0
Name: new_cases, dtype: float64
106888 106223    1.0
Name: new_cases, dtype: float64
106889 106224    8.0
Name: new_cases, dtype: float64
106890 106225    3.0
Name: new_cases, dtype: float64
106891 106226    22.0
Name: new_cases, dtype: float64
109039 109046    1.0
Name: new_cases, dtype: float64
109040 109047    1.0
Name: new_cases, dtype: float64
109041 109048    2.0
Name: new_cases, dtype: float64
109042 109049    0.0
Name: new_cases, dtype: float64
109043 109050    2.0
Name: new_cases, dtype: float64
109044 109051    5.0
Name: new_cases, dtype: float64
109045 109052    4.0
Name: new_cases, dtype: float64
109046 109053    0.0
Name: new_cases, dtype: float64
109047 109054    5.0
Name: new_cases, dtype: float64
109048 109055    10.0
Name: new_cases, dtype: float64
109049 109056    4.0
Name: new_cases, dtype: float64
109050 109057    11.0
Name: new_cases, dtype: float64
109051 109058    4.0
Name: new_cases, dtype: float64
109052 109059    3.0
Name: new_cases, dtype: float64
109053 109060    5.0
Name: new_cases, dtype: float64
109054 109061    1.0
Name: new_cases, dtype: float64
109055 109062    4.0
Name: new_cases, dtype: float64
109056 109063    8.0
Name: new_cases, dtype: float64
109057 109064    15.0
Name: new_cases, dtype: float64
109058 109065    4.0
Name: new_cases, dtype: float64
109059 109066    8.0
Name: new_cases, dtype: float64
109060 109067    9.0
Name: new_cases, dtype: float64
109061 109068    2.0
Name: new_cases, dtype: float64
109062 109069    4.0
Name: new_cases, dtype: float64

109063 109070    5.0
Name: new_cases, dtype: float64
109064 109071    5.0
Name: new_cases, dtype: float64
109065 109072    4.0
Name: new_cases, dtype: float64
109066 109073    1.0
Name: new_cases, dtype: float64
109067 109074    13.0
Name: new_cases, dtype: float64
109068 109075    12.0
Name: new_cases, dtype: float64
109069 109076    2.0
Name: new_cases, dtype: float64
109070 109077    13.0
Name: new_cases, dtype: float64
109071 109078    25.0
Name: new_cases, dtype: float64
109072 109079    3.0
Name: new_cases, dtype: float64
109073 109080    4.0
Name: new_cases, dtype: float64
109074 109081    2.0
Name: new_cases, dtype: float64
109075 109082    0.0
Name: new_cases, dtype: float64
109076 109083    5.0
Name: new_cases, dtype: float64
109077 109084    0.0
Name: new_cases, dtype: float64
109078 109085    7.0
Name: new_cases, dtype: float64
109079 109086    3.0
Name: new_cases, dtype: float64
109080 109087    5.0
Name: new_cases, dtype: float64
109081 109088    0.0
Name: new_cases, dtype: float64
109082 109089    2.0
Name: new_cases, dtype: float64
109083 109090    9.0
Name: new_cases, dtype: float64
109084 109091    10.0
Name: new_cases, dtype: float64
109085 109092    17.0
Name: new_cases, dtype: float64
109086 109093    67.0
Name: new_cases, dtype: float64
109087 109094    37.0
Name: new_cases, dtype: float64
109088 109095    26.0
Name: new_cases, dtype: float64
109089 109096    19.0
Name: new_cases, dtype: float64
109090 109097    16.0
Name: new_cases, dtype: float64
109091 109098    9.0
Name: new_cases, dtype: float64
109092 109099    22.0
Name: new_cases, dtype: float64
109093 109100    101.0
Name: new_cases, dtype: float64
109094 109101    126.0
Name: new_cases, dtype: float64
109095 109102    24.0
Name: new_cases, dtype: float64
109096 109103    11.0
Name: new_cases, dtype: float64
109097 109104    13.0
Name: new_cases, dtype: float64
109098 109105    3.0
Name: new_cases, dtype: float64
109099 109106    14.0
Name: new_cases, dtype: float64
109100 109107    5.0
Name: new_cases, dtype: float64
109101 109108    19.0
Name: new_cases, dtype: float64
109102 109109    8.0
Name: new_cases, dtype: float64
109103 109110    2.0
Name: new_cases, dtype: float64
109104 109111    41.0
Name: new_cases, dtype: float64
109105 109112    4.0
Name: new_cases, dtype: float64
109106 109113    3.0
Name: new_cases, dtype: float64
109107 109114    2.0
Name: new_cases, dtype: float64
109108 109115    12.0
Name: new_cases, dtype: float64
109109 109116    12.0
Name: new_cases, dtype: float64
109110 109117    3.0
Name: new_cases, dtype: float64
109111 109118    12.0
Name: new_cases, dtype: float64
109112 109119    7.0
Name: new_cases, dtype: float64
109113 109120    16.0
Name: new_cases, dtype: float64
109114 109121    17.0
Name: new_cases, dtype: float64
109115 109122    47.0
Name: new_cases, dtype: float64
109116 109123    22.0
Name: new_cases, dtype: float64
109117 109124    9.0
Name: new_cases, dtype: float64
109118 109125    18.0
Name: new_cases, dtype: float64
109119 109126    57.0
Name: new_cases, dtype: float64
109120 109127    16.0
Name: new_cases, dtype: float64
109121 109128    1.0
Name: new_cases, dtype: float64
109122 109129    3.0
Name: new_cases, dtype: float64
109123 109130    45.0
Name: new_cases, dtype: float64
109124 109131    10.0
Name: new_cases, dtype: float64
109125 109132    42.0
Name: new_cases, dtype: float64
109126 109133    15.0
Name: new_cases, dtype: float64
109127 109134    28.0
Name: new_cases, dtype: float64
109128 109135    24.0
Name: new_cases, dtype: float64
109129 109136    7.0
Name: new_cases, dtype: float64
109130 109137    28.0
Name: new_cases, dtype: float64
109131 109138    7.0
Name: new_cases, dtype: float64
109132 109139    7.0
Name: new_cases, dtype: float64
109133 109140    5.0
Name: new_cases, dtype: float64
109134 109141    22.0
Name: new_cases, dtype: float64
109135 109142    6.0
Name: new_cases, dtype: float64
109136 109143    26.0
Name: new_cases, dtype: float64
109137 109144    17.0
Name: new_cases, dtype: float64
109138 109145    13.0
Name: new_cases, dtype: float64
109139 109146    30.0
Name: new_cases, dtype: float64
109140 109147    106.0
Name: new_cases, dtype: float64
109141 109148    41.0
Name: new_cases, dtype: float64
109142 109149    142.0
Name: new_cases, dtype: float64
109143 109150    231.0
Name: new_cases, dtype: float64
109144 109151    185.0
Name: new_cases, dtype: float64
109145 109152    64.0
Name: new_cases, dtype: float64
109146 109153    30.0
Name: new_cases, dtype: float64
109147 109154    39.0
Name: new_cases, dtype: float64
109148 109155    43.0
Name: new_cases, dtype: float64
109149 109156    46.0
Name: new_cases, dtype: float64
109150 109157    36.0
Name: new_cases, dtype: float64
109151 109158    42.0
Name: new_cases, dtype: float64
109152 109159    29.0
Name: new_cases, dtype: float64
109153 109160    46.0
Name: new_cases, dtype: float64
109154 109161    52.0
Name: new_cases, dtype: float64
109155 109162    84.0
Name: new_cases, dtype: float64
109156 109163    98.0
Name: new_cases, dtype: float64
109157 109164    84.0
Name: new_cases, dtype: float64
109158 109165    128.0
Name: new_cases, dtype: float64
109159 109166    32.0
Name: new_cases, dtype: float64
109160 109167    94.0
Name: new_cases, dtype: float64
109161 109168    124.0
Name: new_cases, dtype: float64
109162 109169    144.0
Name: new_cases, dtype: float64
109163 109170    115.0
Name: new_cases, dtype: float64
109164 109171    172.0
Name: new_cases, dtype: float64
109165 109172    92.0
Name: new_cases, dtype: float64
109166 109173    27.0
Name: new_cases, dtype: float64
109167 109174    69.0
Name: new_cases, dtype: float64
109168 109175    183.0
Name: new_cases, dtype: float64
109169 109176    113.0
Name: new_cases, dtype: float64
109170 109177    111.0
Name: new_cases, dtype: float64
109171 109178    104.0
Name: new_cases, dtype: float64
109172 109179    116.0
Name: new_cases, dtype: float64
109173 109180    104.0
Name: new_cases, dtype: float64
109174 109181    126.0
Name: new_cases, dtype: float64
109175 109182    192.0
Name: new_cases, dtype: float64
109176 109183    341.0
Name: new_cases, dtype: float64
109177 109184    131.0
Name: new_cases, dtype: float64
109178 109185    147.0
Name: new_cases, dtype: float64
109179 109186    159.0
Name: new_cases, dtype: float64
109180 109187    80.0
Name: new_cases, dtype: float64
109181 109188    128.0
Name: new_cases, dtype: float64
109182 109189    208.0
Name: new_cases, dtype: float64
109183 109190    315.0
Name: new_cases, dtype: float64
109184 109191    133.0
Name: new_cases, dtype: float64
109185 109192    197.0
Name: new_cases, dtype: float64
109186 109193    202.0
Name: new_cases, dtype: float64
109187 109194    327.0
Name: new_cases, dtype: float64
109188 109195    285.0
Name: new_cases, dtype: float64
109189 109196    499.0
Name: new_cases, dtype: float64
109190 109197    371.0
Name: new_cases, dtype: float64
109191 109198    633.0
Name: new_cases, dtype: float64
109192 109199    359.0
Name: new_cases, dtype: float64
109193 109200    410.0
Name: new_cases, dtype: float64
109194 109201    344.0
Name: new_cases, dtype: float64
109195 109202    471.0
Name: new_cases, dtype: float64
109196 109203    527.0
Name: new_cases, dtype: float64
109197 109204    684.0
Name: new_cases, dtype: float64
109198 109205    719.0
Name: new_cases, dtype: float64
109199 109206    438.0
Name: new_cases, dtype: float64
109200 109207    259.0
Name: new_cases, dtype: float64
109201 109208    369.0
Name: new_cases, dtype: float64
109202 109209    626.0
Name: new_cases, dtype: float64
109203 109210    644.0
Name: new_cases, dtype: float64
109204 109211    418.0
Name: new_cases, dtype: float64
109205 109212    583.0
Name: new_cases, dtype: float64
109206 109213    601.0
Name: new_cases, dtype: float64
109207 109214    631.0
Name: new_cases, dtype: float64
109208 109215    557.0
Name: new_cases, dtype: float64
109209 109216    676.0
Name: new_cases, dtype: float64
109210 109217    800.0
Name: new_cases, dtype: float64
109211 109218    821.0
Name: new_cases, dtype: float64
109212 109219    695.0
Name: new_cases, dtype: float64
109213 109220    1217.0
Name: new_cases, dtype: float64
109214 109221    615.0
Name: new_cases, dtype: float64
109215 109222    867.0
Name: new_cases, dtype: float64
109216 109223    861.0
Name: new_cases, dtype: float64
109217 109224    812.0
Name: new_cases, dtype: float64
109218 109225    605.0
Name: new_cases, dtype: float64
109219 109226    881.0
Name: new_cases, dtype: float64
109220 109227    813.0
Name: new_cases, dtype: float64
109221 109228    493.0
Name: new_cases, dtype: float64
109222 109229    669.0
Name: new_cases, dtype: float64
109223 109230    811.0
Name: new_cases, dtype: float64
109224 109231    1121.0
Name: new_cases, dtype: float64
109225 109232    694.0
Name: new_cases, dtype: float64
109226 109233    1014.0
Name: new_cases, dtype: float64
109227 109234    888.0
Name: new_cases, dtype: float64
109228 109235    505.0
Name: new_cases, dtype: float64
109229 109236    740.0
Name: new_cases, dtype: float64
109230 109237    568.0
Name: new_cases, dtype: float64
109231 109238    743.0
Name: new_cases, dtype: float64
109232 109239    833.0
Name: new_cases, dtype: float64
109233 109240    822.0
Name: new_cases, dtype: float64
109234 109241    696.0
Name: new_cases, dtype: float64
109235 109242    762.0
Name: new_cases, dtype: float64

109236 109243    748.0
Name: new_cases, dtype: float64
109237 109244    669.0
Name: new_cases, dtype: float64
109238 109245    657.0
Name: new_cases, dtype: float64
109239 109246    1041.0
Name: new_cases, dtype: float64
109240 109247    885.0
Name: new_cases, dtype: float64
109241 109248    768.0
Name: new_cases, dtype: float64
109242 109249    730.0
Name: new_cases, dtype: float64
109243 109250    533.0
Name: new_cases, dtype: float64
109244 109251    932.0
Name: new_cases, dtype: float64
109245 109252    788.0
Name: new_cases, dtype: float64
109246 109253    881.0
Name: new_cases, dtype: float64
109247 109254    959.0
Name: new_cases, dtype: float64
109248 109255    703.0
Name: new_cases, dtype: float64
109249 109256    697.0
Name: new_cases, dtype: float64
109250 109257    669.0
Name: new_cases, dtype: float64
109251 109258    853.0
Name: new_cases, dtype: float64
109252 109259    648.0
Name: new_cases, dtype: float64
109253 109260    751.0
Name: new_cases, dtype: float64
109254 109261    886.0
Name: new_cases, dtype: float64
109255 109262    533.0
Name: new_cases, dtype: float64
109256 109263    709.0
Name: new_cases, dtype: float64
109257 109264    728.0
Name: new_cases, dtype: float64
109258 109265    621.0
Name: new_cases, dtype: float64
109259 109266    746.0
Name: new_cases, dtype: float64
109260 109267    707.0
Name: new_cases, dtype: float64
109261 109268    733.0
Name: new_cases, dtype: float64
109262 109269    784.0
Name: new_cases, dtype: float64
109263 109270    551.0
Name: new_cases, dtype: float64
109264 109271    515.0
Name: new_cases, dtype: float64
109265 109272    448.0
Name: new_cases, dtype: float64
109266 109273    733.0
Name: new_cases, dtype: float64
109267 109274    760.0
Name: new_cases, dtype: float64
109268 109275    546.0
Name: new_cases, dtype: float64
109269 109276    589.0
Name: new_cases, dtype: float64
109270 109277    546.0
Name: new_cases, dtype: float64
109271 109278    425.0
Name: new_cases, dtype: float64
109272 109279    472.0
Name: new_cases, dtype: float64
109273 109280    630.0
Name: new_cases, dtype: float64
109274 109281    520.0
Name: new_cases, dtype: float64
109275 109282    703.0
Name: new_cases, dtype: float64
109276 109283    460.0
Name: new_cases, dtype: float64
109277 109284    648.0
Name: new_cases, dtype: float64
109278 109285    359.0
Name: new_cases, dtype: float64
109279 109286    549.0
Name: new_cases, dtype: float64
109280 109287    609.0
Name: new_cases, dtype: float64
109281 109288    547.0
Name: new_cases, dtype: float64
109282 109289    739.0
Name: new_cases, dtype: float64
109283 109290    673.0
Name: new_cases, dtype: float64
109284 109291    509.0
Name: new_cases, dtype: float64
109285 109292    525.0
Name: new_cases, dtype: float64
109286 109293    758.0
Name: new_cases, dtype: float64
109287 109294    782.0
Name: new_cases, dtype: float64
109288 109295    856.0
Name: new_cases, dtype: float64
109289 109296    563.0
Name: new_cases, dtype: float64
109290 109297    799.0
Name: new_cases, dtype: float64
109291 109298    619.0
Name: new_cases, dtype: float64
109292 109299    596.0
Name: new_cases, dtype: float64
109293 109300    819.0
Name: new_cases, dtype: float64
109294 109301    987.0
Name: new_cases, dtype: float64
109295 109302    639.0
Name: new_cases, dtype: float64
109296 109303    919.0
Name: new_cases, dtype: float64
109297 109304    695.0
Name: new_cases, dtype: float64
109298 109305    775.0
Name: new_cases, dtype: float64
109299 109306    518.0
Name: new_cases, dtype: float64
109300 109307    1055.0
Name: new_cases, dtype: float64
109301 109308    1003.0
Name: new_cases, dtype: float64
109302 109309    995.0
Name: new_cases, dtype: float64
109303 109310    1022.0
Name: new_cases, dtype: float64
109304 109311    714.0
Name: new_cases, dtype: float64
109305 109312    707.0
Name: new_cases, dtype: float64
109306 109313    803.0
Name: new_cases, dtype: float64
109307 109314    698.0
Name: new_cases, dtype: float64
109308 109315    725.0
Name: new_cases, dtype: float64
109309 109316    812.0
Name: new_cases, dtype: float64
109310 109317    1155.0
Name: new_cases, dtype: float64
109311 109318    800.0
Name: new_cases, dtype: float64
109312 109319    669.0
Name: new_cases, dtype: float64
109313 109320    641.0
Name: new_cases, dtype: float64
109314 109321    1130.0
Name: new_cases, dtype: float64
109315 109322    856.0
Name: new_cases, dtype: float64
109316 109323    819.0
Name: new_cases, dtype: float64
109317 109324    1268.0
Name: new_cases, dtype: float64
109318 109325    861.0
Name: new_cases, dtype: float64
109319 109326    632.0
Name: new_cases, dtype: float64
109320 109327    823.0
Name: new_cases, dtype: float64
109321 109328    932.0
Name: new_cases, dtype: float64
109322 109329    827.0
Name: new_cases, dtype: float64
109323 109330    958.0
Name: new_cases, dtype: float64
109324 109331    559.0
Name: new_cases, dtype: float64
109325 109332    274.0
Name: new_cases, dtype: float64
109326 109333    260.0
Name: new_cases, dtype: float64
109327 109334    952.0
Name: new_cases, dtype: float64
109328 109335    762.0
Name: new_cases, dtype: float64
109329 109336    822.0
Name: new_cases, dtype: float64
109330 109337    974.0
Name: new_cases, dtype: float64
109331 109338    417.0
Name: new_cases, dtype: float64
109332 109339    369.0
Name: new_cases, dtype: float64
109333 109340    355.0
Name: new_cases, dtype: float64
109334 109341    764.0
Name: new_cases, dtype: float64
109335 109342    959.0
Name: new_cases, dtype: float64
109336 109343    898.0
Name: new_cases, dtype: float64
109337 109344    1162.0
Name: new_cases, dtype: float64
109338 109345    1138.0
Name: new_cases, dtype: float64
109339 109346    1032.0
Name: new_cases, dtype: float64
109340 109347    707.0
Name: new_cases, dtype: float64
109341 109348    802.0
Name: new_cases, dtype: float64
109342 109349    1055.0
Name: new_cases, dtype: float64
109343 109350    1002.0
Name: new_cases, dtype: float64
109344 109351    1048.0
Name: new_cases, dtype: float64
109345 109352    1149.0
Name: new_cases, dtype: float64
109346 109353    859.0
Name: new_cases, dtype: float64
109347 109354    512.0
Name: new_cases, dtype: float64
109348 109355    428.0
Name: new_cases, dtype: float64
109349 109356    771.0
Name: new_cases, dtype: float64
109350 109357    1088.0
Name: new_cases, dtype: float64
109351 109358    1071.0
Name: new_cases, dtype: float64
109352 109359    852.0
Name: new_cases, dtype: float64
109353 109360    711.0
Name: new_cases, dtype: float64
109354 109361    571.0
Name: new_cases, dtype: float64
109355 109362    714.0
Name: new_cases, dtype: float64
109356 109363    1028.0
Name: new_cases, dtype: float64
109357 109364    769.0
Name: new_cases, dtype: float64
109358 109365    754.0
Name: new_cases, dtype: float64
109359 109366    969.0
Name: new_cases, dtype: float64
109360 109367    662.0
Name: new_cases, dtype: float64
109361 109368    679.0
Name: new_cases, dtype: float64
109362 109369    554.0
Name: new_cases, dtype: float64
109363 109370    701.0
Name: new_cases, dtype: float64
109364 109371    747.0
Name: new_cases, dtype: float64
109365 109372    794.0
Name: new_cases, dtype: float64
109366 109373    867.0
Name: new_cases, dtype: float64
109367 109374    713.0
Name: new_cases, dtype: float64
109368 109375    515.0
Name: new_cases, dtype: float64
109369 109376    827.0
Name: new_cases, dtype: float64
109370 109377    874.0
Name: new_cases, dtype: float64
109371 109378    978.0
Name: new_cases, dtype: float64
109372 109379    978.0
Name: new_cases, dtype: float64
109373 109380    823.0
Name: new_cases, dtype: float64
109374 109381    845.0
Name: new_cases, dtype: float64
109375 109382    599.0
Name: new_cases, dtype: float64
109376 109383    1053.0
Name: new_cases, dtype: float64
109377 109384    1121.0
Name: new_cases, dtype: float64
109378 109385    1037.0
Name: new_cases, dtype: float64
109379 109386    1369.0
Name: new_cases, dtype: float64
109380 109387    1062.0
Name: new_cases, dtype: float64
109381 109388    1047.0
Name: new_cases, dtype: float64
109382 109389    987.0
Name: new_cases, dtype: float64
109383 109390    940.0
Name: new_cases, dtype: float64
109384 109391    1132.0
Name: new_cases, dtype: float64
109385 109392    1114.0
Name: new_cases, dtype: float64
109386 109393    1285.0
Name: new_cases, dtype: float64
109387 109394    1414.0
Name: new_cases, dtype: float64
109388 109395    934.0
Name: new_cases, dtype: float64
109389 109396    937.0
Name: new_cases, dtype: float64
109390 109397    974.0
Name: new_cases, dtype: float64
109391 109398    1082.0
Name: new_cases, dtype: float64
109392 109399    1341.0
Name: new_cases, dtype: float64
109393 109400    1439.0
Name: new_cases, dtype: float64
109394 109401    1501.0
Name: new_cases, dtype: float64
109395 109402    1158.0
Name: new_cases, dtype: float64
109396 109403    1074.0
Name: new_cases, dtype: float64
109397 109404    1817.0
Name: new_cases, dtype: float64

109398 109405    2125.0
Name: new_cases, dtype: float64
109399 109406    2028.0
Name: new_cases, dtype: float64
109400 109407    1814.0
Name: new_cases, dtype: float64
109401 109408    1766.0
Name: new_cases, dtype: float64
109402 109409    1479.0
Name: new_cases, dtype: float64
109403 109410    942.0
Name: new_cases, dtype: float64
109404 109411    1400.0
Name: new_cases, dtype: float64
109405 109412    1934.0
Name: new_cases, dtype: float64
109406 109413    2540.0
Name: new_cases, dtype: float64
109407 109414    2605.0
Name: new_cases, dtype: float64
109408 109415    2006.0
Name: new_cases, dtype: float64
109409 109416    2100.0
Name: new_cases, dtype: float64
109410 109417    1523.0
Name: new_cases, dtype: float64
109411 109418    1990.0
Name: new_cases, dtype: float64
109412 109419    2023.0
Name: new_cases, dtype: float64
109413 109420    2688.0
Name: new_cases, dtype: float64
109414 109421    1877.0
Name: new_cases, dtype: float64
109415 109422    2004.0
Name: new_cases, dtype: float64
109416 109423    1893.0
Name: new_cases, dtype: float64
109417 109424    2058.0
Name: new_cases, dtype: float64
109418 109425    1770.0
Name: new_cases, dtype: float64
109419 109426    2266.0
Name: new_cases, dtype: float64
109420 109427    1976.0
Name: new_cases, dtype: float64
109421 109428    1611.0
Name: new_cases, dtype: float64
109422 109429    1608.0
Name: new_cases, dtype: float64
109423 109430    1507.0
Name: new_cases, dtype: float64
109424 109431    1814.0
Name: new_cases, dtype: float64
109425 109432    1456.0
Name: new_cases, dtype: float64
109426 109433    2073.0
Name: new_cases, dtype: float64
109427 109434    2380.0
Name: new_cases, dtype: float64
109428 109435    2479.0
Name: new_cases, dtype: float64
109429 109436    2547.0
Name: new_cases, dtype: float64
109430 109437    1603.0
Name: new_cases, dtype: float64
109431 109438    1547.0
Name: new_cases, dtype: float64
109432 109439    2250.0
Name: new_cases, dtype: float64
109433 109440    2599.0
Name: new_cases, dtype: float64
109434 109441    2020.0
Name: new_cases, dtype: float64
109435 109442    2367.0
Name: new_cases, dtype: float64
109436 109443    2278.0
Name: new_cases, dtype: float64
109437 109444    1558.0
Name: new_cases, dtype: float64
109438 109445    1801.0
Name: new_cases, dtype: float64
109439 109446    2278.0
Name: new_cases, dtype: float64
109440 109447    2603.0
Name: new_cases, dtype: float64
109441 109448    2660.0
Name: new_cases, dtype: float64
109442 109449    2676.0
Name: new_cases, dtype: float64
109443 109450    2752.0
Name: new_cases, dtype: float64
109444 109451    2162.0
Name: new_cases, dtype: float64
109445 109452    1786.0
Name: new_cases, dtype: float64
109446 109453    2271.0
Name: new_cases, dtype: float64
109447 109454    2461.0
Name: new_cases, dtype: float64
109448 109455    2356.0
Name: new_cases, dtype: float64
109449 109456    2695.0
Name: new_cases, dtype: float64
109450 109457    2212.0
Name: new_cases, dtype: float64
109451 109458    1946.0
Name: new_cases, dtype: float64
109452 109459    1520.0
Name: new_cases, dtype: float64
109453 109460    1910.0
Name: new_cases, dtype: float64
109454 109461    2214.0
Name: new_cases, dtype: float64
109455 109462    2307.0
Name: new_cases, dtype: float64
109456 109463    2566.0
Name: new_cases, dtype: float64
109457 109464    2693.0
Name: new_cases, dtype: float64
109458 109465    2073.0
Name: new_cases, dtype: float64
109459 109466    1483.0
Name: new_cases, dtype: float64
109460 109467    1895.0
Name: new_cases, dtype: float64
109461 109468    2377.0
Name: new_cases, dtype: float64
109462 109469    2828.0
Name: new_cases, dtype: float64
109463 109470    2568.0
Name: new_cases, dtype: float64
109464 109471    2181.0
Name: new_cases, dtype: float64
109465 109472    2108.0
Name: new_cases, dtype: float64
109466 109473    1781.0
Name: new_cases, dtype: float64
109467 109474    2020.0
Name: new_cases, dtype: float64
109468 109475    2704.0
Name: new_cases, dtype: float64
109469 109476    2781.0
Name: new_cases, dtype: float64
109470 109477    3031.0
Name: new_cases, dtype: float64
109471 109478    3166.0
Name: new_cases, dtype: float64
109472 109479    3228.0
Name: new_cases, dtype: float64
109473 109480    2514.0
Name: new_cases, dtype: float64
109474 109481    2720.0
Name: new_cases, dtype: float64
109475 109482    3223.0
Name: new_cases, dtype: float64
109476 109483    3307.0
Name: new_cases, dtype: float64
109477 109484    3136.0
Name: new_cases, dtype: float64
109478 109485    2827.0
Name: new_cases, dtype: float64
109479 109486    2429.0
Name: new_cases, dtype: float64
109480 109487    2075.0
Name: new_cases, dtype: float64
109481 109488    2696.0
Name: new_cases, dtype: float64
109482 109489    2860.0
Name: new_cases, dtype: float64
109483 109490    3196.0
Name: new_cases, dtype: float64
109484 109491    3262.0
Name: new_cases, dtype: float64
109485 109492    3481.0
Name: new_cases, dtype: float64
109486 109493    2838.0
Name: new_cases, dtype: float64
109487 109494    2144.0
Name: new_cases, dtype: float64
109488 109495    2833.0
Name: new_cases, dtype: float64
109489 109496    3135.0
Name: new_cases, dtype: float64
109490 109497    3098.0
Name: new_cases, dtype: float64
109491 109498    2758.0
Name: new_cases, dtype: float64
109492 109499    2698.0
Name: new_cases, dtype: float64
109493 109500    1963.0
Name: new_cases, dtype: float64
109494 109501    1786.0
Name: new_cases, dtype: float64
109495 109502    2046.0
Name: new_cases, dtype: float64
109496 109503    2667.0
Name: new_cases, dtype: float64
109497 109504    2612.0
Name: new_cases, dtype: float64
109498 109505    2482.0
Name: new_cases, dtype: float64
109499 109506    2149.0
Name: new_cases, dtype: float64
109500 109507    1683.0
Name: new_cases, dtype: float64
109501 109508    1145.0
Name: new_cases, dtype: float64
109502 109509    1501.0
Name: new_cases, dtype: float64
109503 109510    1746.0
Name: new_cases, dtype: float64
109504 109511    2148.0
Name: new_cases, dtype: float64
109505 109512    1842.0
Name: new_cases, dtype: float64
109506 109513    1863.0
Name: new_cases, dtype: float64
109507 109514    1523.0
Name: new_cases, dtype: float64
109508 109515    1487.0
Name: new_cases, dtype: float64
109509 109516    1434.0
Name: new_cases, dtype: float64
109510 109517    1825.0
Name: new_cases, dtype: float64
109511 109518    1693.0
Name: new_cases, dtype: float64
109512 109519    1716.0
Name: new_cases, dtype: float64
109513 109520    1320.0
Name: new_cases, dtype: float64
109514 109521    1224.0
Name: new_cases, dtype: float64
109515 109522    1201.0
Name: new_cases, dtype: float64
109516 109523    1141.0
Name: new_cases, dtype: float64
109517 109524    1483.0
Name: new_cases, dtype: float64
109518 109525    1434.0
Name: new_cases, dtype: float64
109519 109526    1463.0
Name: new_cases, dtype: float64
109520 109527    1258.0
Name: new_cases, dtype: float64
109521 109528    1102.0
Name: new_cases, dtype: float64
109522 109529    1095.0
Name: new_cases, dtype: float64
109523 109530    1045.0
Name: new_cases, dtype: float64
109524 109531    1133.0
Name: new_cases, dtype: float64
109525 109532    1159.0
Name: new_cases, dtype: float64
109526 109533    1151.0
Name: new_cases, dtype: float64
109527 109534    1171.0
Name: new_cases, dtype: float64
109528 109535    1049.0
Name: new_cases, dtype: float64
109529 109536    565.0
Name: new_cases, dtype: float64
109530 109537    573.0
Name: new_cases, dtype: float64
109531 109538    702.0
Name: new_cases, dtype: float64
109532 109539    879.0
Name: new_cases, dtype: float64
109533 109540    718.0
Name: new_cases, dtype: float64
109534 109541    644.0
Name: new_cases, dtype: float64
109535 109542    410.0
Name: new_cases, dtype: float64
109536 109543    423.0
Name: new_cases, dtype: float64
109537 109544    561.0
Name: new_cases, dtype: float64
109538 109545    592.0
Name: new_cases, dtype: float64
109539 109546    664.0
Name: new_cases, dtype: float64
109540 109547    537.0
Name: new_cases, dtype: float64
109541 109548    390.0
Name: new_cases, dtype: float64
109542 109549    303.0
Name: new_cases, dtype: float64
109543 109550    310.0
Name: new_cases, dtype: float64
109544 109551    333.0
Name: new_cases, dtype: float64
109545 109552    336.0
Name: new_cases, dtype: float64
109546 109553    427.0
Name: new_cases, dtype: float64
109547 109554    400.0
Name: new_cases, dtype: float64
109548 109555    348.0
Name: new_cases, dtype: float64
109549 109556    323.0
Name: new_cases, dtype: float64
109550 109557    255.0
Name: new_cases, dtype: float64
109551 109558    269.0
Name: new_cases, dtype: float64
109552 109559    291.0
Name: new_cases, dtype: float64
109553 109560    384.0
Name: new_cases, dtype: float64
109554 109561    227.0
Name: new_cases, dtype: float64
109555 109562    193.0
Name: new_cases, dtype: float64
109556 109563    105.0
Name: new_cases, dtype: float64
109557 109564    106.0
Name: new_cases, dtype: float64
109558 109565    147.0
Name: new_cases, dtype: float64
109559 109566    181.0
Name: new_cases, dtype: float64
109560 109567    199.0
Name: new_cases, dtype: float64
109561 109568    127.0
Name: new_cases, dtype: float64

109562 109569    123.0
Name: new_cases, dtype: float64
109563 109570    140.0
Name: new_cases, dtype: float64
109564 109571    113.0
Name: new_cases, dtype: float64
109565 109572    113.0
Name: new_cases, dtype: float64
109566 109573    133.0
Name: new_cases, dtype: float64
109567 109574    145.0
Name: new_cases, dtype: float64
109568 109575    91.0
Name: new_cases, dtype: float64
109569 109576    92.0
Name: new_cases, dtype: float64
109570 109577    62.0
Name: new_cases, dtype: float64
109571 109578    43.0
Name: new_cases, dtype: float64
109572 109579    51.0
Name: new_cases, dtype: float64
109573 109580    73.0
Name: new_cases, dtype: float64
109574 109581    86.0
Name: new_cases, dtype: float64
109575 109582    102.0
Name: new_cases, dtype: float64
109576 109583    83.0
Name: new_cases, dtype: float64
109577 109584    45.0
Name: new_cases, dtype: float64
109578 109585    40.0
Name: new_cases, dtype: float64
109579 109586    38.0
Name: new_cases, dtype: float64
109580 109587    55.0
Name: new_cases, dtype: float64
109581 109588    85.0
Name: new_cases, dtype: float64
109582 109589    71.0
Name: new_cases, dtype: float64
109583 109590    0.0
Name: new_cases, dtype: float64
109584 109591    74.0
Name: new_cases, dtype: float64
109585 109592    50.0
Name: new_cases, dtype: float64
109586 109593    83.0
Name: new_cases, dtype: float64
109587 109594    51.0
Name: new_cases, dtype: float64
109588 109595    0.0
Name: new_cases, dtype: float64
109589 109596    133.0
Name: new_cases, dtype: float64
109590 109597    0.0
Name: new_cases, dtype: float64
109591 109598    56.0
Name: new_cases, dtype: float64
109592 109599    42.0
Name: new_cases, dtype: float64
109593 109600    43.0
Name: new_cases, dtype: float64
109594 109601    0.0
Name: new_cases, dtype: float64
109595 109602    55.0
Name: new_cases, dtype: float64
109596 109603    31.0
Name: new_cases, dtype: float64
109597 109604    28.0
Name: new_cases, dtype: float64
109598 109605    0.0
Name: new_cases, dtype: float64
109599 109606    25.0
Name: new_cases, dtype: float64
109600 109607    24.0
Name: new_cases, dtype: float64
109601 109608    71.0
Name: new_cases, dtype: float64
109602 109609    49.0
Name: new_cases, dtype: float64
109603 109610    19.0
Name: new_cases, dtype: float64
109604 109611    0.0
Name: new_cases, dtype: float64
109605 109612    30.0
Name: new_cases, dtype: float64
109606 109613    25.0
Name: new_cases, dtype: float64
109607 109614    39.0
Name: new_cases, dtype: float64
109608 109615    0.0
Name: new_cases, dtype: float64
109609 109616    52.0
Name: new_cases, dtype: float64
109610 109617    0.0
Name: new_cases, dtype: float64
109611 109618    58.0
Name: new_cases, dtype: float64
109612 109619    0.0
Name: new_cases, dtype: float64
109613 109620    19.0
Name: new_cases, dtype: float64
109614 109621    28.0
Name: new_cases, dtype: float64
109615 109622    26.0
Name: new_cases, dtype: float64
109616 109623    33.0
Name: new_cases, dtype: float64
109617 109624    24.0
Name: new_cases, dtype: float64
109618 109625    21.0
Name: new_cases, dtype: float64
109619 109626    0.0
Name: new_cases, dtype: float64
109620 109627    0.0
Name: new_cases, dtype: float64
109621 109628    231.0
Name: new_cases, dtype: float64
109622 109629    29.0
Name: new_cases, dtype: float64
109623 109630    33.0
Name: new_cases, dtype: float64
109624 109631    31.0
Name: new_cases, dtype: float64
109625 109632    33.0
Name: new_cases, dtype: float64
109626 109633    0.0
Name: new_cases, dtype: float64
109627 109634    22.0
Name: new_cases, dtype: float64
109628 109635    53.0
Name: new_cases, dtype: float64
109629 109636    61.0
Name: new_cases, dtype: float64
109630 109637    79.0
Name: new_cases, dtype: float64
109631 109638    50.0
Name: new_cases, dtype: float64
109632 109639    0.0
Name: new_cases, dtype: float64
109633 109640    30.0
Name: new_cases, dtype: float64
109634 109641    32.0
Name: new_cases, dtype: float64
109635 109642    80.0
Name: new_cases, dtype: float64
109636 109643    46.0
Name: new_cases, dtype: float64
109637 109644    52.0
Name: new_cases, dtype: float64
109638 109645    41.0
Name: new_cases, dtype: float64
109639 109646    50.0
Name: new_cases, dtype: float64
109640 109647    0.0
Name: new_cases, dtype: float64
109641 109648    38.0
Name: new_cases, dtype: float64
109642 109649    100.0
Name: new_cases, dtype: float64
109643 109650    0.0
Name: new_cases, dtype: float64
109644 109651    53.0
Name: new_cases, dtype: float64
109645 109652    108.0
Name: new_cases, dtype: float64
109646 109653    50.0
Name: new_cases, dtype: float64
109647 109654    0.0
Name: new_cases, dtype: float64
109648 109655    0.0
Name: new_cases, dtype: float64
109649 109656    379.0
Name: new_cases, dtype: float64
109650 109657    56.0
Name: new_cases, dtype: float64
109651 109658    50.0
Name: new_cases, dtype: float64
109652 109659    37.0
Name: new_cases, dtype: float64
109653 109660    52.0
Name: new_cases, dtype: float64
109654 109661    0.0
Name: new_cases, dtype: float64
109655 109662    0.0
Name: new_cases, dtype: float64
109656 109663    133.0
Name: new_cases, dtype: float64
109657 109664    58.0
Name: new_cases, dtype: float64
109658 109665    64.0
Name: new_cases, dtype: float64
109659 109666    80.0
Name: new_cases, dtype: float64
109660 109667    72.0
Name: new_cases, dtype: float64
109661 109668    0.0
Name: new_cases, dtype: float64
109662 109669    0.0
Name: new_cases, dtype: float64
109663 109670    396.0
Name: new_cases, dtype: float64
109664 109671    57.0
Name: new_cases, dtype: float64
109665 109672    63.0
Name: new_cases, dtype: float64
109666 109673    78.0
Name: new_cases, dtype: float64
109667 109674    0.0
Name: new_cases, dtype: float64
109668 109675    61.0
Name: new_cases, dtype: float64
109669 109676    0.0
Name: new_cases, dtype: float64
109670 109677    167.0
Name: new_cases, dtype: float64
109671 109678    52.0
Name: new_cases, dtype: float64
109672 109679    0.0
Name: new_cases, dtype: float64
109673 109680    101.0
Name: new_cases, dtype: float64
109674 109681    70.0
Name: new_cases, dtype: float64
109675 109682    0.0
Name: new_cases, dtype: float64
109676 109683    0.0
Name: new_cases, dtype: float64
109677 109684    178.0
Name: new_cases, dtype: float64
109678 109685    98.0
Name: new_cases, dtype: float64
109679 109686    78.0
Name: new_cases, dtype: float64
109680 109687    0.0
Name: new_cases, dtype: float64
109681 109688    92.0
Name: new_cases, dtype: float64
109682 109689    0.0
Name: new_cases, dtype: float64
109683 109690    0.0
Name: new_cases, dtype: float64
109684 109691    607.0
Name: new_cases, dtype: float64
109685 109692    90.0
Name: new_cases, dtype: float64
109686 109693    0.0
Name: new_cases, dtype: float64
109687 109694    235.0
Name: new_cases, dtype: float64
109688 109695    0.0
Name: new_cases, dtype: float64
109689 109696    0.0
Name: new_cases, dtype: float64
109690 109697    0.0
Name: new_cases, dtype: float64
109691 109698    536.0
Name: new_cases, dtype: float64
109692 109699    0.0
Name: new_cases, dtype: float64
109693 109700    260.0
Name: new_cases, dtype: float64
109694 109701    277.0
Name: new_cases, dtype: float64
109695 109702    0.0
Name: new_cases, dtype: float64
109696 109703    0.0
Name: new_cases, dtype: float64
109697 109704    0.0
Name: new_cases, dtype: float64
109698 109705    3422.0
Name: new_cases, dtype: float64
109699 109706    937.0
Name: new_cases, dtype: float64
109700 109707    974.0
Name: new_cases, dtype: float64
109701 109708    1239.0
Name: new_cases, dtype: float64
109702 Series([], Name: new_cases, dtype: float64)
109703 Series([], Name: new_cases, dtype: float64)
109704 109039    1.0
Name: new_cases, dtype: float64
109705 109040    0.0
Name: new_cases, dtype: float64
109706 109041    4.0
Name: new_cases, dtype: float64
109707 109042    0.0
Name: new_cases, dtype: float64
109708 109043    1.0
Name: new_cases, dtype: float64
109776 109783    13.0
Name: new_cases, dtype: float64
109777 109784    10.0
Name: new_cases, dtype: float64
109778 109785    5.0
Name: new_cases, dtype: float64
109779 109786    43.0
Name: new_cases, dtype: float64
109780 109787    31.0
Name: new_cases, dtype: float64
109781 109788    28.0
Name: new_cases, dtype: float64
109782 109789    89.0
Name: new_cases, dtype: float64
109783 109790    0.0
Name: new_cases, dtype: float64
109784 109791    84.0
Name: new_cases, dtype: float64
109785 109792    45.0
Name: new_cases, dtype: float64
109786 109793    32.0
Name: new_cases, dtype: float64
109787 109794    21.0
Name: new_cases, dtype: float64
109788 109795    64.0
Name: new_cases, dtype: float64
109789 109796    100.0
Name: new_cases, dtype: float64
109790 109797    55.0
Name: new_cases, dtype: float64
109791 109798    36.0
Name: new_cases, dtype: float64
109792 109799    181.0
Name: new_cases, dtype: float64
109793 109800    98.0
Name: new_cases, dtype: float64

109794 109801    115.0
Name: new_cases, dtype: float64
109795 109802    258.0
Name: new_cases, dtype: float64
109796 109803    91.0
Name: new_cases, dtype: float64
109797 109804    181.0
Name: new_cases, dtype: float64
109798 109805    151.0
Name: new_cases, dtype: float64
109799 109806    535.0
Name: new_cases, dtype: float64
109800 109807    280.0
Name: new_cases, dtype: float64
109801 109808    393.0
Name: new_cases, dtype: float64
109802 109809    1388.0
Name: new_cases, dtype: float64
109803 109810    914.0
Name: new_cases, dtype: float64
109804 109811    641.0
Name: new_cases, dtype: float64
109805 109812    951.0
Name: new_cases, dtype: float64
109806 109813    671.0
Name: new_cases, dtype: float64
109807 109814    2265.0
Name: new_cases, dtype: float64
109808 109815    519.0
Name: new_cases, dtype: float64
109809 109816    1172.0
Name: new_cases, dtype: float64
109810 109817    1016.0
Name: new_cases, dtype: float64
109811 109818    998.0
Name: new_cases, dtype: float64
109812 109819    931.0
Name: new_cases, dtype: float64
109813 109820    1208.0
Name: new_cases, dtype: float64
109814 109821    697.0
Name: new_cases, dtype: float64
109815 109822    1512.0
Name: new_cases, dtype: float64
109816 109823    1413.0
Name: new_cases, dtype: float64
109817 109824    1664.0
Name: new_cases, dtype: float64
109818 109825    734.0
Name: new_cases, dtype: float64
109819 109826    3683.0
Name: new_cases, dtype: float64
109820 109827    2186.0
Name: new_cases, dtype: float64
109821 109828    1182.0
Name: new_cases, dtype: float64
109822 109829    2491.0
Name: new_cases, dtype: float64
109823 109830    2741.0
Name: new_cases, dtype: float64
109824 109831    3045.0
Name: new_cases, dtype: float64
109825 109832    3483.0
Name: new_cases, dtype: float64
109826 109833    2075.0
Name: new_cases, dtype: float64
109827 109834    3394.0
Name: new_cases, dtype: float64
109828 109835    1444.0
Name: new_cases, dtype: float64
109829 109836    3817.0
Name: new_cases, dtype: float64
109830 109837    3628.0
Name: new_cases, dtype: float64
109831 109838    3709.0
Name: new_cases, dtype: float64
109832 109839    3321.0
Name: new_cases, dtype: float64
109833 109840    3168.0
Name: new_cases, dtype: float64
109834 109841    2292.0
Name: new_cases, dtype: float64
109835 109842    1515.0
Name: new_cases, dtype: float64
109836 109843    3237.0
Name: new_cases, dtype: float64
109837 109844    4247.0
Name: new_cases, dtype: float64
109838 109845    4298.0
Name: new_cases, dtype: float64
109839 109846    3891.0
Name: new_cases, dtype: float64
109840 109847    4046.0
Name: new_cases, dtype: float64
109841 109848    3732.0
Name: new_cases, dtype: float64
109842 109849    2660.0
Name: new_cases, dtype: float64
109843 109850    4550.0
Name: new_cases, dtype: float64
109844 109851    4537.0
Name: new_cases, dtype: float64
109845 109852    4749.0
Name: new_cases, dtype: float64
109846 109853    2929.0
Name: new_cases, dtype: float64
109847 109854    4056.0
Name: new_cases, dtype: float64
109848 109855    4205.0
Name: new_cases, dtype: float64
109849 109856    4020.0
Name: new_cases, dtype: float64
109850 109857    5772.0
Name: new_cases, dtype: float64
109851 109858    6154.0
Name: new_cases, dtype: float64
109852 109859    5874.0
Name: new_cases, dtype: float64
109853 109860    6506.0
Name: new_cases, dtype: float64
109854 109861    7386.0
Name: new_cases, dtype: float64
109855 109862    8805.0
Name: new_cases, dtype: float64
109856 109863    5563.0
Name: new_cases, dtype: float64
109857 109864    8126.0
Name: new_cases, dtype: float64
109858 109865    749.0
Name: new_cases, dtype: float64
109859 109866    4284.0
Name: new_cases, dtype: float64
109860 109867    4202.0
Name: new_cases, dtype: float64
109861 109868    4358.0
Name: new_cases, dtype: float64
109862 109869    4757.0
Name: new_cases, dtype: float64
109863 109870    3181.0
Name: new_cases, dtype: float64
109864 109871    4040.0
Name: new_cases, dtype: float64
109865 109872    5087.0
Name: new_cases, dtype: float64
109866 109873    5965.0
Name: new_cases, dtype: float64
109867 109874    0.0
Name: new_cases, dtype: float64
109868 109875    5961.0
Name: new_cases, dtype: float64
109869 109876    8987.0
Name: new_cases, dtype: float64
109870 109877    3256.0
Name: new_cases, dtype: float64
109871 109878    4164.0
Name: new_cases, dtype: float64
109872 109879    3752.0
Name: new_cases, dtype: float64
109873 109880    3480.0
Name: new_cases, dtype: float64
109874 109881    3537.0
Name: new_cases, dtype: float64
109875 109882    3413.0
Name: new_cases, dtype: float64
109876 109883    3598.0
Name: new_cases, dtype: float64
109877 109884    2511.0
Name: new_cases, dtype: float64
109878 109885    3363.0
Name: new_cases, dtype: float64
109879 109886    3879.0
Name: new_cases, dtype: float64
109880 109887    3913.0
Name: new_cases, dtype: float64
109881 109888    3762.0
Name: new_cases, dtype: float64
109882 109889    3625.0
Name: new_cases, dtype: float64
109883 109890    3430.0
Name: new_cases, dtype: float64
109884 109891    2946.0
Name: new_cases, dtype: float64
109885 109892    2848.0
Name: new_cases, dtype: float64
109886 109893    3264.0
Name: new_cases, dtype: float64
109887 109894    3527.0
Name: new_cases, dtype: float64
109888 109895    3595.0
Name: new_cases, dtype: float64
109889 109896    3481.0
Name: new_cases, dtype: float64
109890 109897    3638.0
Name: new_cases, dtype: float64
109891 109898    2985.0
Name: new_cases, dtype: float64
109892 109899    3575.0
Name: new_cases, dtype: float64
109893 109900    3633.0
Name: new_cases, dtype: float64
109894 109901    3537.0
Name: new_cases, dtype: float64
109895 109902    3198.0
Name: new_cases, dtype: float64
109896 109903    3064.0
Name: new_cases, dtype: float64
109897 109904    3616.0
Name: new_cases, dtype: float64
109898 109905    3797.0
Name: new_cases, dtype: float64
109899 109906    3744.0
Name: new_cases, dtype: float64
109900 109907    3884.0
Name: new_cases, dtype: float64
109901 109908    3835.0
Name: new_cases, dtype: float64
109902 109909    3951.0
Name: new_cases, dtype: float64
109903 109910    3963.0
Name: new_cases, dtype: float64
109904 109911    4090.0
Name: new_cases, dtype: float64
109905 109912    4091.0
Name: new_cases, dtype: float64
109906 109913    4406.0
Name: new_cases, dtype: float64
109907 109914    4463.0
Name: new_cases, dtype: float64
109908 109915    4546.0
Name: new_cases, dtype: float64
109909 109916    4865.0
Name: new_cases, dtype: float64
109910 109917    0.0
Name: new_cases, dtype: float64
109911 109918    0.0
Name: new_cases, dtype: float64
109912 109919    13756.0
Name: new_cases, dtype: float64
109913 109920    5288.0
Name: new_cases, dtype: float64
109914 109921    5678.0
Name: new_cases, dtype: float64
109915 109922    0.0
Name: new_cases, dtype: float64
109916 109923    6809.0
Name: new_cases, dtype: float64
109917 109924    0.0
Name: new_cases, dtype: float64
109918 109925    21358.0
Name: new_cases, dtype: float64
109919 109926    4250.0
Name: new_cases, dtype: float64
109920 109927    6790.0
Name: new_cases, dtype: float64
109921 109928    7734.0
Name: new_cases, dtype: float64
109922 109929    7785.0
Name: new_cases, dtype: float64
109923 109930    8466.0
Name: new_cases, dtype: float64
109924 109931    0.0
Name: new_cases, dtype: float64
109925 109932    14149.0
Name: new_cases, dtype: float64
109926 109933    5109.0
Name: new_cases, dtype: float64
109927 109934    6547.0
Name: new_cases, dtype: float64
109928 109935    0.0
Name: new_cases, dtype: float64
109929 109936    8875.0
Name: new_cases, dtype: float64
109930 109937    17741.0
Name: new_cases, dtype: float64
109931 109938    0.0
Name: new_cases, dtype: float64
109932 109939    9507.0
Name: new_cases, dtype: float64
109933 109940    10143.0
Name: new_cases, dtype: float64
109934 109941    5547.0
Name: new_cases, dtype: float64
109935 109942    7828.0
Name: new_cases, dtype: float64
109936 109943    9099.0
Name: new_cases, dtype: float64
109937 109944    8639.0
Name: new_cases, dtype: float64
109938 109945    9008.0
Name: new_cases, dtype: float64
109939 109946    9169.0
Name: new_cases, dtype: float64
109940 109947    9090.0
Name: new_cases, dtype: float64
109941 109948    6112.0
Name: new_cases, dtype: float64
109942 109949    6944.0
Name: new_cases, dtype: float64
109943 109950    5996.0
Name: new_cases, dtype: float64
109944 109951    8619.0
Name: new_cases, dtype: float64
109945 109952    7964.0
Name: new_cases, dtype: float64
109946 109953    9474.0
Name: new_cases, dtype: float64
109947 109954    7731.0
Name: new_cases, dtype: float64
109948 109955    4871.0
Name: new_cases, dtype: float64
109949 109956    5092.0
Name: new_cases, dtype: float64
109950 109957    0.0
Name: new_cases, dtype: float64
109951 109958    13016.0
Name: new_cases, dtype: float64
109952 109959    6703.0
Name: new_cases, dtype: float64
109953 109960    6854.0
Name: new_cases, dtype: float64
109954 109961    6275.0
Name: new_cases, dtype: float64
109955 109962    1598.0
Name: new_cases, dtype: float64
109956 109963    4615.0
Name: new_cases, dtype: float64
109957 109964    6586.0
Name: new_cases, dtype: float64
109958 109965    7291.0
Name: new_cases, dtype: float64

109959 109966    6603.0
Name: new_cases, dtype: float64
109960 109967    6162.0
Name: new_cases, dtype: float64
109961 109968    6787.0
Name: new_cases, dtype: float64
109962 109969    4241.0
Name: new_cases, dtype: float64
109963 109970    4160.0
Name: new_cases, dtype: float64
109964 109971    6380.0
Name: new_cases, dtype: float64
109965 109972    5698.0
Name: new_cases, dtype: float64
109966 109973    6314.0
Name: new_cases, dtype: float64
109967 109974    6453.0
Name: new_cases, dtype: float64
109968 109975    6030.0
Name: new_cases, dtype: float64
109969 109976    0.0
Name: new_cases, dtype: float64
109970 109977    7651.0
Name: new_cases, dtype: float64
109971 109978    6149.0
Name: new_cases, dtype: float64
109972 109979    11889.0
Name: new_cases, dtype: float64
109973 109980    0.0
Name: new_cases, dtype: float64
109974 109981    5558.0
Name: new_cases, dtype: float64
109975 109982    5160.0
Name: new_cases, dtype: float64
109976 109983    3412.0
Name: new_cases, dtype: float64
109977 109984    3054.0
Name: new_cases, dtype: float64
109978 109985    3061.0
Name: new_cases, dtype: float64
109979 109986    3468.0
Name: new_cases, dtype: float64
109980 109987    3267.0
Name: new_cases, dtype: float64
109981 109988    0.0
Name: new_cases, dtype: float64
109982 109989    6605.0
Name: new_cases, dtype: float64
109983 109990    1830.0
Name: new_cases, dtype: float64
109984 109991    2930.0
Name: new_cases, dtype: float64
109985 109992    2733.0
Name: new_cases, dtype: float64
109986 109993    2952.0
Name: new_cases, dtype: float64
109987 109994    7474.0
Name: new_cases, dtype: float64
109988 109995    3283.0
Name: new_cases, dtype: float64
109989 109996    1800.0
Name: new_cases, dtype: float64
109990 109997    2803.0
Name: new_cases, dtype: float64
109991 109998    0.0
Name: new_cases, dtype: float64
109992 109999    5766.0
Name: new_cases, dtype: float64
109993 110000    0.0
Name: new_cases, dtype: float64
109994 110001    2677.0
Name: new_cases, dtype: float64
109995 110002    3132.0
Name: new_cases, dtype: float64
109996 110003    3126.0
Name: new_cases, dtype: float64
109997 110004    2201.0
Name: new_cases, dtype: float64
109998 110005    3242.0
Name: new_cases, dtype: float64
109999 110006    5758.0
Name: new_cases, dtype: float64
110000 110007    0.0
Name: new_cases, dtype: float64
110001 110008    3240.0
Name: new_cases, dtype: float64
110002 110009    5599.0
Name: new_cases, dtype: float64
110003 110010    0.0
Name: new_cases, dtype: float64
110004 110011    1859.0
Name: new_cases, dtype: float64
110005 110012    1923.0
Name: new_cases, dtype: float64
110006 110013    2431.0
Name: new_cases, dtype: float64
110007 110014    2666.0
Name: new_cases, dtype: float64
110008 110015    2586.0
Name: new_cases, dtype: float64
110009 110016    2323.0
Name: new_cases, dtype: float64
110010 110017    0.0
Name: new_cases, dtype: float64
110011 110018    0.0
Name: new_cases, dtype: float64
110012 110019    9284.0
Name: new_cases, dtype: float64
110013 110020    2935.0
Name: new_cases, dtype: float64
110014 110021    0.0
Name: new_cases, dtype: float64
110015 110022    2781.0
Name: new_cases, dtype: float64
110016 110023    2507.0
Name: new_cases, dtype: float64
110017 110024    2323.0
Name: new_cases, dtype: float64
110018 110025    1194.0
Name: new_cases, dtype: float64
110019 110026    1904.0
Name: new_cases, dtype: float64
110020 110027    2575.0
Name: new_cases, dtype: float64
110021 110028    2231.0
Name: new_cases, dtype: float64
110022 110029    2413.0
Name: new_cases, dtype: float64
110023 110030    2249.0
Name: new_cases, dtype: float64
110024 110031    2112.0
Name: new_cases, dtype: float64
110025 110032    1257.0
Name: new_cases, dtype: float64
110026 110033    1663.0
Name: new_cases, dtype: float64
110027 110034    0.0
Name: new_cases, dtype: float64
110028 110035    3986.0
Name: new_cases, dtype: float64
110029 110036    4164.0
Name: new_cases, dtype: float64
110030 110037    0.0
Name: new_cases, dtype: float64
110031 110038    1589.0
Name: new_cases, dtype: float64
110032 110039    887.0
Name: new_cases, dtype: float64
110033 110040    1882.0
Name: new_cases, dtype: float64
110034 110041    0.0
Name: new_cases, dtype: float64
110035 110042    3908.0
Name: new_cases, dtype: float64
110036 110043    4021.0
Name: new_cases, dtype: float64
110037 110044    2162.0
Name: new_cases, dtype: float64
110038 110045    0.0
Name: new_cases, dtype: float64
110039 110046    1075.0
Name: new_cases, dtype: float64
110040 110047    0.0
Name: new_cases, dtype: float64
110041 110048    3470.0
Name: new_cases, dtype: float64
110042 110049    0.0
Name: new_cases, dtype: float64
110043 110050    3785.0
Name: new_cases, dtype: float64
110044 110051    1828.0
Name: new_cases, dtype: float64
110045 110052    1224.0
Name: new_cases, dtype: float64
110046 110053    0.0
Name: new_cases, dtype: float64
110047 110054    2709.0
Name: new_cases, dtype: float64
110048 110055    2490.0
Name: new_cases, dtype: float64
110049 110056    0.0
Name: new_cases, dtype: float64
110050 110057    1832.0
Name: new_cases, dtype: float64
110051 110058    0.0
Name: new_cases, dtype: float64
110052 110059    4030.0
Name: new_cases, dtype: float64
110053 110060    1157.0
Name: new_cases, dtype: float64
110054 110061    0.0
Name: new_cases, dtype: float64
110055 110062    3327.0
Name: new_cases, dtype: float64
110056 110063    0.0
Name: new_cases, dtype: float64
110057 110064    0.0
Name: new_cases, dtype: float64
110058 110065    6442.0
Name: new_cases, dtype: float64
110059 110066    1618.0
Name: new_cases, dtype: float64
110060 110067    958.0
Name: new_cases, dtype: float64
110061 110068    1678.0
Name: new_cases, dtype: float64
110062 110069    0.0
Name: new_cases, dtype: float64
110063 110070    3829.0
Name: new_cases, dtype: float64
110064 110071    1564.0
Name: new_cases, dtype: float64
110065 110072    0.0
Name: new_cases, dtype: float64
110066 110073    2111.0
Name: new_cases, dtype: float64
110067 110074    1251.0
Name: new_cases, dtype: float64
110068 110075    1588.0
Name: new_cases, dtype: float64
110069 110076    4641.0
Name: new_cases, dtype: float64
110070 110077    0.0
Name: new_cases, dtype: float64
110071 110078    0.0
Name: new_cases, dtype: float64
110072 110079    2962.0
Name: new_cases, dtype: float64
110073 110080    1376.0
Name: new_cases, dtype: float64
110074 110081    0.0
Name: new_cases, dtype: float64
110075 110082    2543.0
Name: new_cases, dtype: float64
110076 110083    0.0
Name: new_cases, dtype: float64
110077 110084    4162.0
Name: new_cases, dtype: float64
110078 110085    0.0
Name: new_cases, dtype: float64
110079 110086    0.0
Name: new_cases, dtype: float64
110080 110087    9004.0
Name: new_cases, dtype: float64
110081 110088    2166.0
Name: new_cases, dtype: float64
110082 110089    2881.0
Name: new_cases, dtype: float64
110083 110090    0.0
Name: new_cases, dtype: float64
110084 110091    15792.0
Name: new_cases, dtype: float64
110085 110092    0.0
Name: new_cases, dtype: float64
110086 110093    4544.0
Name: new_cases, dtype: float64
110087 110094    0.0
Name: new_cases, dtype: float64
110088 110095    0.0
Name: new_cases, dtype: float64
110089 110096    12647.0
Name: new_cases, dtype: float64
110090 110097    0.0
Name: new_cases, dtype: float64
110091 110098    9693.0
Name: new_cases, dtype: float64
110092 110099    0.0
Name: new_cases, dtype: float64
110093 110100    11031.0
Name: new_cases, dtype: float64
110094 110101    0.0
Name: new_cases, dtype: float64
110095 110102    13301.0
Name: new_cases, dtype: float64
110096 110103    0.0
Name: new_cases, dtype: float64
110097 110104    6731.0
Name: new_cases, dtype: float64
110098 110105    5715.0
Name: new_cases, dtype: float64
110099 110106    13337.0
Name: new_cases, dtype: float64
110100 110107    5217.0
Name: new_cases, dtype: float64
110101 110108    0.0
Name: new_cases, dtype: float64
110102 110109    4477.0
Name: new_cases, dtype: float64
110103 110110    15621.0
Name: new_cases, dtype: float64
110104 110111    0.0
Name: new_cases, dtype: float64
110105 110112    6715.0
Name: new_cases, dtype: float64
110106 110113    7993.0
Name: new_cases, dtype: float64
110107 110114    13653.0
Name: new_cases, dtype: float64
110108 110115    0.0
Name: new_cases, dtype: float64
110109 110116    10080.0
Name: new_cases, dtype: float64
110110 110117    0.0
Name: new_cases, dtype: float64
110111 110118    6724.0
Name: new_cases, dtype: float64
110112 110119    8807.0
Name: new_cases, dtype: float64
110113 110120    8439.0
Name: new_cases, dtype: float64
110114 110121    14550.0
Name: new_cases, dtype: float64
110115 110122    3203.0
Name: new_cases, dtype: float64
110116 110123    0.0
Name: new_cases, dtype: float64
110117 110124    6228.0
Name: new_cases, dtype: float64
110118 110125    7408.0
Name: new_cases, dtype: float64
110119 110126    9667.0
Name: new_cases, dtype: float64
110120 110127    7719.0
Name: new_cases, dtype: float64
110121 110128    13786.0
Name: new_cases, dtype: float64
110122 110129    0.0
Name: new_cases, dtype: float64

110123 110130    3448.0
Name: new_cases, dtype: float64
110124 110131    6740.0
Name: new_cases, dtype: float64
110125 110132    7302.0
Name: new_cases, dtype: float64
110126 110133    15564.0
Name: new_cases, dtype: float64
110127 110134    7500.0
Name: new_cases, dtype: float64
110128 110135    0.0
Name: new_cases, dtype: float64
110129 110136    5942.0
Name: new_cases, dtype: float64
110130 110137    8492.0
Name: new_cases, dtype: float64
110131 110138    0.0
Name: new_cases, dtype: float64
110132 110139    6672.0
Name: new_cases, dtype: float64
110133 110140    4878.0
Name: new_cases, dtype: float64
110134 110141    8447.0
Name: new_cases, dtype: float64
110135 110142    6670.0
Name: new_cases, dtype: float64
110136 110143    6212.0
Name: new_cases, dtype: float64
110137 110144    8847.0
Name: new_cases, dtype: float64
110138 110145    0.0
Name: new_cases, dtype: float64
110139 110146    7434.0
Name: new_cases, dtype: float64
110140 110147    7114.0
Name: new_cases, dtype: float64
110141 110148    8039.0
Name: new_cases, dtype: float64
110142 110149    5353.0
Name: new_cases, dtype: float64
110143 110150    4443.0
Name: new_cases, dtype: float64
110144 110151    6568.0
Name: new_cases, dtype: float64
110145 110152    16624.0
Name: new_cases, dtype: float64
110146 110153    0.0
Name: new_cases, dtype: float64
110147 110154    16047.0
Name: new_cases, dtype: float64
110148 110155    0.0
Name: new_cases, dtype: float64
110149 110156    14681.0
Name: new_cases, dtype: float64
110150 110157    0.0
Name: new_cases, dtype: float64
110151 110158    14933.0
Name: new_cases, dtype: float64
110152 110159    0.0
Name: new_cases, dtype: float64
110153 110160    19206.0
Name: new_cases, dtype: float64
110154 110161    11919.0
Name: new_cases, dtype: float64
110155 110162    8589.0
Name: new_cases, dtype: float64
110156 110163    8909.0
Name: new_cases, dtype: float64
110157 110164    3239.0
Name: new_cases, dtype: float64
110158 110165    0.0
Name: new_cases, dtype: float64
110159 110166    15686.0
Name: new_cases, dtype: float64
110160 110167    12916.0
Name: new_cases, dtype: float64
110161 110168    6622.0
Name: new_cases, dtype: float64
110162 110169    5616.0
Name: new_cases, dtype: float64
110163 110170    8406.0
Name: new_cases, dtype: float64
110164 110171    7842.0
Name: new_cases, dtype: float64
110165 110172    0.0
Name: new_cases, dtype: float64
110166 110173    8384.0
Name: new_cases, dtype: float64
110167 110174    19271.0
Name: new_cases, dtype: float64
110168 110175    10655.0
Name: new_cases, dtype: float64
110169 110176    11248.0
Name: new_cases, dtype: float64
110170 110177    7927.0
Name: new_cases, dtype: float64
110171 110178    5626.0
Name: new_cases, dtype: float64
110172 110179    6387.0
Name: new_cases, dtype: float64
110173 110180    8030.0
Name: new_cases, dtype: float64
110174 110181    0.0
Name: new_cases, dtype: float64
110175 110182    13326.0
Name: new_cases, dtype: float64
110176 110183    16563.0
Name: new_cases, dtype: float64
110177 110184    0.0
Name: new_cases, dtype: float64
110178 110185    10161.0
Name: new_cases, dtype: float64
110179 110186    11301.0
Name: new_cases, dtype: float64
110180 110187    0.0
Name: new_cases, dtype: float64
110181 110188    15518.0
Name: new_cases, dtype: float64
110182 110189    11049.0
Name: new_cases, dtype: float64
110183 110190    8495.0
Name: new_cases, dtype: float64
110184 110191    7425.0
Name: new_cases, dtype: float64
110185 110192    6611.0
Name: new_cases, dtype: float64
110186 110193    0.0
Name: new_cases, dtype: float64
110187 110194    15153.0
Name: new_cases, dtype: float64
110188 110195    0.0
Name: new_cases, dtype: float64
110189 110196    16106.0
Name: new_cases, dtype: float64
110190 110197    0.0
Name: new_cases, dtype: float64
110191 110198    11553.0
Name: new_cases, dtype: float64
110192 110199    3129.0
Name: new_cases, dtype: float64
110193 110200    4562.0
Name: new_cases, dtype: float64
110194 110201    0.0
Name: new_cases, dtype: float64
110195 110202    5768.0
Name: new_cases, dtype: float64
110196 110203    0.0
Name: new_cases, dtype: float64
110197 110204    20599.0
Name: new_cases, dtype: float64
110198 110205    5234.0
Name: new_cases, dtype: float64
110199 110206    0.0
Name: new_cases, dtype: float64
110200 110207    3080.0
Name: new_cases, dtype: float64
110201 110208    12269.0
Name: new_cases, dtype: float64
110202 110209    0.0
Name: new_cases, dtype: float64
110203 110210    13410.0
Name: new_cases, dtype: float64
110204 110211    0.0
Name: new_cases, dtype: float64
110205 110212    10003.0
Name: new_cases, dtype: float64
110206 110213    0.0
Name: new_cases, dtype: float64
110207 110214    4282.0
Name: new_cases, dtype: float64
110208 110215    10281.0
Name: new_cases, dtype: float64
110209 110216    0.0
Name: new_cases, dtype: float64
110210 110217    6745.0
Name: new_cases, dtype: float64
110211 110218    10491.0
Name: new_cases, dtype: float64
110212 110219    4438.0
Name: new_cases, dtype: float64
110213 110220    0.0
Name: new_cases, dtype: float64
110214 110221    6966.0
Name: new_cases, dtype: float64
110215 110222    4990.0
Name: new_cases, dtype: float64
110216 110223    4809.0
Name: new_cases, dtype: float64
110217 110224    0.0
Name: new_cases, dtype: float64
110218 110225    5501.0
Name: new_cases, dtype: float64
110219 110226    0.0
Name: new_cases, dtype: float64
110220 110227    7914.0
Name: new_cases, dtype: float64
110221 110228    0.0
Name: new_cases, dtype: float64
110222 110229    9963.0
Name: new_cases, dtype: float64
110223 110230    0.0
Name: new_cases, dtype: float64
110224 110231    10734.0
Name: new_cases, dtype: float64
110225 110232    4225.0
Name: new_cases, dtype: float64
110226 110233    0.0
Name: new_cases, dtype: float64
110227 110234    3179.0
Name: new_cases, dtype: float64
110228 110235    1429.0
Name: new_cases, dtype: float64
110229 110236    2934.0
Name: new_cases, dtype: float64
110230 110237    7324.0
Name: new_cases, dtype: float64
110231 110238    2799.0
Name: new_cases, dtype: float64
110232 110239    0.0
Name: new_cases, dtype: float64
110233 110240    5569.0
Name: new_cases, dtype: float64
110234 110241    0.0
Name: new_cases, dtype: float64
110235 110242    3852.0
Name: new_cases, dtype: float64
110236 110243    0.0
Name: new_cases, dtype: float64
110237 110244    12239.0
Name: new_cases, dtype: float64
110238 110245    3463.0
Name: new_cases, dtype: float64
110239 110246    0.0
Name: new_cases, dtype: float64
110240 110247    3550.0
Name: new_cases, dtype: float64
110241 110248    3882.0
Name: new_cases, dtype: float64
110242 110249    0.0
Name: new_cases, dtype: float64
110243 110250    2995.0
Name: new_cases, dtype: float64
110244 110251    2843.0
Name: new_cases, dtype: float64
110245 110252    6813.0
Name: new_cases, dtype: float64
110246 110253    0.0
Name: new_cases, dtype: float64
110247 110254    2795.0
Name: new_cases, dtype: float64
110248 110255    2058.0
Name: new_cases, dtype: float64
110249 110256    0.0
Name: new_cases, dtype: float64
110250 110257    3950.0
Name: new_cases, dtype: float64
110251 110258    5489.0
Name: new_cases, dtype: float64
110252 110259    0.0
Name: new_cases, dtype: float64
110253 110260    0.0
Name: new_cases, dtype: float64
110254 110261    7559.0
Name: new_cases, dtype: float64
110255 110262    1564.0
Name: new_cases, dtype: float64
110256 110263    2374.0
Name: new_cases, dtype: float64
110257 110264    2586.0
Name: new_cases, dtype: float64
110258 110265    2549.0
Name: new_cases, dtype: float64
110259 110266    0.0
Name: new_cases, dtype: float64
110260 110267    4629.0
Name: new_cases, dtype: float64
110261 110268    1962.0
Name: new_cases, dtype: float64
110262 110269    780.0
Name: new_cases, dtype: float64
110263 110270    2010.0
Name: new_cases, dtype: float64
110264 110271    2316.0
Name: new_cases, dtype: float64
110265 110272    2260.0
Name: new_cases, dtype: float64
110266 110273    2032.0
Name: new_cases, dtype: float64
110267 110274    1950.0
Name: new_cases, dtype: float64
110268 110275    1629.0
Name: new_cases, dtype: float64
110269 110276    691.0
Name: new_cases, dtype: float64
110270 110277    1568.0
Name: new_cases, dtype: float64
110271 110278    1798.0
Name: new_cases, dtype: float64
110272 110279    1711.0
Name: new_cases, dtype: float64
110273 110280    1617.0
Name: new_cases, dtype: float64
110274 110281    1765.0
Name: new_cases, dtype: float64
110275 110282    1490.0
Name: new_cases, dtype: float64
110276 110283    611.0
Name: new_cases, dtype: float64
110277 110284    1366.0
Name: new_cases, dtype: float64
110278 110285    1502.0
Name: new_cases, dtype: float64
110279 110286    722.0
Name: new_cases, dtype: float64
110280 110287    0.0
Name: new_cases, dtype: float64
110281 110288    2798.0
Name: new_cases, dtype: float64
110282 110289    1808.0
Name: new_cases, dtype: float64
110283 110290    1244.0
Name: new_cases, dtype: float64
110284 110291    2207.0
Name: new_cases, dtype: float64
110285 110292    2416.0
Name: new_cases, dtype: float64
110286 110293    1993.0
Name: new_cases, dtype: float64

110287 110294    1496.0
Name: new_cases, dtype: float64
110288 110295    1571.0
Name: new_cases, dtype: float64
110289 110296    1217.0
Name: new_cases, dtype: float64
110290 110297    503.0
Name: new_cases, dtype: float64
110291 110298    1186.0
Name: new_cases, dtype: float64
110292 110299    1482.0
Name: new_cases, dtype: float64
110293 110300    1502.0
Name: new_cases, dtype: float64
110294 110301    1319.0
Name: new_cases, dtype: float64
110295 110302    1497.0
Name: new_cases, dtype: float64
110296 110303    978.0
Name: new_cases, dtype: float64
110297 110304    0.0
Name: new_cases, dtype: float64
110298 110305    2015.0
Name: new_cases, dtype: float64
110299 110306    1468.0
Name: new_cases, dtype: float64
110300 110307    1371.0
Name: new_cases, dtype: float64
110301 110308    1396.0
Name: new_cases, dtype: float64
110302 110309    1173.0
Name: new_cases, dtype: float64
110303 110310    918.0
Name: new_cases, dtype: float64
110304 110311    0.0
Name: new_cases, dtype: float64
110305 110312    1538.0
Name: new_cases, dtype: float64
110306 110313    1360.0
Name: new_cases, dtype: float64
110307 110314    1118.0
Name: new_cases, dtype: float64
110308 110315    1116.0
Name: new_cases, dtype: float64
110309 110316    0.0
Name: new_cases, dtype: float64
110310 110317    0.0
Name: new_cases, dtype: float64
110311 110318    2306.0
Name: new_cases, dtype: float64
110312 110319    0.0
Name: new_cases, dtype: float64
110313 110320    415.0
Name: new_cases, dtype: float64
110314 110321    2112.0
Name: new_cases, dtype: float64
110315 110322    974.0
Name: new_cases, dtype: float64
110316 110323    1040.0
Name: new_cases, dtype: float64
110317 110324    902.0
Name: new_cases, dtype: float64
110318 110325    474.0
Name: new_cases, dtype: float64
110319 110326    943.0
Name: new_cases, dtype: float64
110320 110327    1085.0
Name: new_cases, dtype: float64
110321 110328    957.0
Name: new_cases, dtype: float64
110322 110329    813.0
Name: new_cases, dtype: float64
110323 110330    1021.0
Name: new_cases, dtype: float64
110324 110331    759.0
Name: new_cases, dtype: float64
110325 110332    272.0
Name: new_cases, dtype: float64
110326 110333    936.0
Name: new_cases, dtype: float64
110327 110334    1018.0
Name: new_cases, dtype: float64
110328 110335    1068.0
Name: new_cases, dtype: float64
110329 110336    0.0
Name: new_cases, dtype: float64
110330 110337    2039.0
Name: new_cases, dtype: float64
110331 110338    589.0
Name: new_cases, dtype: float64
110332 110339    644.0
Name: new_cases, dtype: float64
110333 110340    779.0
Name: new_cases, dtype: float64
110334 110341    996.0
Name: new_cases, dtype: float64
110335 110342    1048.0
Name: new_cases, dtype: float64
110336 110343    899.0
Name: new_cases, dtype: float64
110337 110344    887.0
Name: new_cases, dtype: float64
110338 110345    773.0
Name: new_cases, dtype: float64
110339 110346    320.0
Name: new_cases, dtype: float64
110340 110347    865.0
Name: new_cases, dtype: float64
110341 110348    1086.0
Name: new_cases, dtype: float64
110342 110349    0.0
Name: new_cases, dtype: float64
110343 110350    1978.0
Name: new_cases, dtype: float64
110344 110351    864.0
Name: new_cases, dtype: float64
110345 110352    792.0
Name: new_cases, dtype: float64
110346 110353    0.0
Name: new_cases, dtype: float64
110347 110354    1210.0
Name: new_cases, dtype: float64
110348 110355    1034.0
Name: new_cases, dtype: float64
110349 110356    923.0
Name: new_cases, dtype: float64
110350 110357    876.0
Name: new_cases, dtype: float64
110351 110358    607.0
Name: new_cases, dtype: float64
110352 110359    634.0
Name: new_cases, dtype: float64
110353 110360    453.0
Name: new_cases, dtype: float64
110354 110361    679.0
Name: new_cases, dtype: float64
110355 110362    891.0
Name: new_cases, dtype: float64
110356 110363    1122.0
Name: new_cases, dtype: float64
110357 110364    983.0
Name: new_cases, dtype: float64
110358 110365    814.0
Name: new_cases, dtype: float64
110359 110366    844.0
Name: new_cases, dtype: float64
110360 110367    387.0
Name: new_cases, dtype: float64
110361 110368    775.0
Name: new_cases, dtype: float64
110362 110369    1034.0
Name: new_cases, dtype: float64
110363 110370    0.0
Name: new_cases, dtype: float64
110364 110371    1927.0
Name: new_cases, dtype: float64
110365 110372    969.0
Name: new_cases, dtype: float64
110366 110373    758.0
Name: new_cases, dtype: float64
110367 110374    400.0
Name: new_cases, dtype: float64
110368 110375    793.0
Name: new_cases, dtype: float64
110369 110376    986.0
Name: new_cases, dtype: float64
110370 110377    998.0
Name: new_cases, dtype: float64
110371 110378    840.0
Name: new_cases, dtype: float64
110372 110379    1032.0
Name: new_cases, dtype: float64
110373 110380    888.0
Name: new_cases, dtype: float64
110374 110381    393.0
Name: new_cases, dtype: float64
110375 110382    0.0
Name: new_cases, dtype: float64
110376 110383    1121.0
Name: new_cases, dtype: float64
110377 110384    1114.0
Name: new_cases, dtype: float64
110378 110385    1062.0
Name: new_cases, dtype: float64
110379 110386    1070.0
Name: new_cases, dtype: float64
110380 110387    994.0
Name: new_cases, dtype: float64
110381 110388    340.0
Name: new_cases, dtype: float64
110382 110389    0.0
Name: new_cases, dtype: float64
110383 110390    2239.0
Name: new_cases, dtype: float64
110384 110391    1237.0
Name: new_cases, dtype: float64
110385 110392    1148.0
Name: new_cases, dtype: float64
110386 110393    1034.0
Name: new_cases, dtype: float64
110387 110394    995.0
Name: new_cases, dtype: float64
110388 110395    830.0
Name: new_cases, dtype: float64
110389 110396    1459.0
Name: new_cases, dtype: float64
110390 110397    1370.0
Name: new_cases, dtype: float64
110391 110398    1415.0
Name: new_cases, dtype: float64
110392 110399    1537.0
Name: new_cases, dtype: float64
110393 110400    1725.0
Name: new_cases, dtype: float64
110394 110401    1465.0
Name: new_cases, dtype: float64
110395 110402    773.0
Name: new_cases, dtype: float64
110396 110403    1539.0
Name: new_cases, dtype: float64
110397 110404    1556.0
Name: new_cases, dtype: float64
110398 110405    1529.0
Name: new_cases, dtype: float64
110399 110406    1434.0
Name: new_cases, dtype: float64
110400 110407    1574.0
Name: new_cases, dtype: float64
110401 110408    1326.0
Name: new_cases, dtype: float64
110402 110409    895.0
Name: new_cases, dtype: float64
110403 110410    1381.0
Name: new_cases, dtype: float64
110404 110411    1491.0
Name: new_cases, dtype: float64
110405 110412    1579.0
Name: new_cases, dtype: float64
110406 110413    1606.0
Name: new_cases, dtype: float64
110407 110414    1619.0
Name: new_cases, dtype: float64
110408 110415    769.0
Name: new_cases, dtype: float64
110409 110416    0.0
Name: new_cases, dtype: float64
110410 110417    3218.0
Name: new_cases, dtype: float64
110411 110418    0.0
Name: new_cases, dtype: float64
110412 110419    3038.0
Name: new_cases, dtype: float64
110413 110420    1356.0
Name: new_cases, dtype: float64
110414 110421    1819.0
Name: new_cases, dtype: float64
110415 110422    1527.0
Name: new_cases, dtype: float64
110416 110423    0.0
Name: new_cases, dtype: float64
110417 110424    945.0
Name: new_cases, dtype: float64
110418 110425    1478.0
Name: new_cases, dtype: float64
110419 110426    1660.0
Name: new_cases, dtype: float64
110420 110427    1724.0
Name: new_cases, dtype: float64
110421 110428    3559.0
Name: new_cases, dtype: float64
110422 110429    1581.0
Name: new_cases, dtype: float64
110423 110430    0.0
Name: new_cases, dtype: float64
110424 110431    2395.0
Name: new_cases, dtype: float64
110425 110432    1782.0
Name: new_cases, dtype: float64
110426 110433    2052.0
Name: new_cases, dtype: float64
110427 110434    1336.0
Name: new_cases, dtype: float64
110428 110435    5922.0
Name: new_cases, dtype: float64
110429 110436    492.0
Name: new_cases, dtype: float64
110430 110437    2063.0
Name: new_cases, dtype: float64
110431 110438    2112.0
Name: new_cases, dtype: float64
110432 110439    4020.0
Name: new_cases, dtype: float64
110433 110440    4760.0
Name: new_cases, dtype: float64
110434 110441    4577.0
Name: new_cases, dtype: float64
110435 110442    4346.0
Name: new_cases, dtype: float64
110436 110443    1501.0
Name: new_cases, dtype: float64
110437 110444    1996.0
Name: new_cases, dtype: float64
110438 110445    5182.0
Name: new_cases, dtype: float64
110439 110446    8687.0
Name: new_cases, dtype: float64
110440 110447    11174.0
Name: new_cases, dtype: float64
110441 110448    12833.0
Name: new_cases, dtype: float64
110442 110449    16135.0
Name: new_cases, dtype: float64
110443 Series([], Name: new_cases, dtype: float64)
110444 Series([], Name: new_cases, dtype: float64)
110445 Series([], Name: new_cases, dtype: float64)
110446 Series([], Name: new_cases, dtype: float64)
110447 Series([], Name: new_cases, dtype: float64)
110448 Series([], Name: new_cases, dtype: float64)
110449 Series([], Name: new_cases, dtype: float64)
110450 110457    0.0
Name: new_cases, dtype: float64
110451 110458    1.0
Name: new_cases, dtype: float64

110452 110459    0.0
Name: new_cases, dtype: float64
110453 110460    0.0
Name: new_cases, dtype: float64
110454 110461    0.0
Name: new_cases, dtype: float64
110455 110462    0.0
Name: new_cases, dtype: float64
110456 110463    0.0
Name: new_cases, dtype: float64
110457 110464    0.0
Name: new_cases, dtype: float64
110458 110465    0.0
Name: new_cases, dtype: float64
110459 110466    0.0
Name: new_cases, dtype: float64
110460 110467    0.0
Name: new_cases, dtype: float64
110461 110468    0.0
Name: new_cases, dtype: float64
110462 110469    0.0
Name: new_cases, dtype: float64
110463 110470    0.0
Name: new_cases, dtype: float64
110464 110471    0.0
Name: new_cases, dtype: float64
110465 110472    0.0
Name: new_cases, dtype: float64
110466 110473    0.0
Name: new_cases, dtype: float64
110467 110474    0.0
Name: new_cases, dtype: float64
110468 110475    0.0
Name: new_cases, dtype: float64
110469 110476    0.0
Name: new_cases, dtype: float64
110470 110477    0.0
Name: new_cases, dtype: float64
110471 110478    0.0
Name: new_cases, dtype: float64
110472 110479    0.0
Name: new_cases, dtype: float64
110473 110480    0.0
Name: new_cases, dtype: float64
110474 110481    0.0
Name: new_cases, dtype: float64
110475 110482    0.0
Name: new_cases, dtype: float64
110476 110483    0.0
Name: new_cases, dtype: float64
110477 110484    0.0
Name: new_cases, dtype: float64
110478 110485    0.0
Name: new_cases, dtype: float64
110479 110486    2.0
Name: new_cases, dtype: float64
110480 110487    1.0
Name: new_cases, dtype: float64
110481 110488    4.0
Name: new_cases, dtype: float64
110482 110489    10.0
Name: new_cases, dtype: float64
110483 110490    13.0
Name: new_cases, dtype: float64
110484 110491    16.0
Name: new_cases, dtype: float64
110485 110492    3.0
Name: new_cases, dtype: float64
110486 110493    12.0
Name: new_cases, dtype: float64
110487 110494    47.0
Name: new_cases, dtype: float64
110488 110495    29.0
Name: new_cases, dtype: float64
110489 110496    2.0
Name: new_cases, dtype: float64
110490 110497    45.0
Name: new_cases, dtype: float64
110491 110498    15.0
Name: new_cases, dtype: float64
110492 110499    15.0
Name: new_cases, dtype: float64
110493 110500    13.0
Name: new_cases, dtype: float64
110494 110501    77.0
Name: new_cases, dtype: float64
110495 110502    73.0
Name: new_cases, dtype: float64
110496 110503    82.0
Name: new_cases, dtype: float64
110497 110504    90.0
Name: new_cases, dtype: float64
110498 110505    84.0
Name: new_cases, dtype: float64
110499 110506    71.0
Name: new_cases, dtype: float64
110500 110507    96.0
Name: new_cases, dtype: float64
110501 110508    272.0
Name: new_cases, dtype: float64
110502 110509    343.0
Name: new_cases, dtype: float64
110503 110510    128.0
Name: new_cases, dtype: float64
110504 110511    538.0
Name: new_cases, dtype: float64
110505 110512    227.0
Name: new_cases, dtype: float64
110506 110513    322.0
Name: new_cases, dtype: float64
110507 110514    385.0
Name: new_cases, dtype: float64
110508 110515    76.0
Name: new_cases, dtype: float64
110509 110516    152.0
Name: new_cases, dtype: float64
110510 110517    414.0
Name: new_cases, dtype: float64
110511 110518    104.0
Name: new_cases, dtype: float64
110512 110519    106.0
Name: new_cases, dtype: float64
110513 110520    206.0
110521    206.0
Name: new_cases, dtype: float64
110514 110520    206.0
110521    206.0
Name: new_cases, dtype: float64
110515 110522    119.0
Name: new_cases, dtype: float64
110516 110523    233.0
Name: new_cases, dtype: float64
110517 110524    220.0
Name: new_cases, dtype: float64
110518 110525    284.0
Name: new_cases, dtype: float64
110519 110526    291.0
Name: new_cases, dtype: float64
110520 110527    230.0
Name: new_cases, dtype: float64
110521 110528    207.0
Name: new_cases, dtype: float64
110522 110529    218.0
Name: new_cases, dtype: float64
110523 110530    209.0
Name: new_cases, dtype: float64
110524 110531    172.0
Name: new_cases, dtype: float64
110525 110532    200.0
Name: new_cases, dtype: float64
110526 110533    140.0
Name: new_cases, dtype: float64
110527 110534    111.0
Name: new_cases, dtype: float64
110528 110535    271.0
Name: new_cases, dtype: float64
110529 110536    211.0
Name: new_cases, dtype: float64
110530 110537    102.0
Name: new_cases, dtype: float64
110531 110538    285.0
Name: new_cases, dtype: float64
110532 110539    198.0
Name: new_cases, dtype: float64
110533 110540    181.0
Name: new_cases, dtype: float64
110534 110541    254.0
Name: new_cases, dtype: float64
110535 110542    276.0
Name: new_cases, dtype: float64
110536 110543    284.0
Name: new_cases, dtype: float64
110537 110544    156.0
Name: new_cases, dtype: float64
110538 110545    295.0
Name: new_cases, dtype: float64
110539 110546    262.0
Name: new_cases, dtype: float64
110540 110547    199.0
Name: new_cases, dtype: float64
110541 110548    320.0
Name: new_cases, dtype: float64
110542 110549    339.0
Name: new_cases, dtype: float64
110543 110550    120.0
Name: new_cases, dtype: float64
110544 110551    147.0
Name: new_cases, dtype: float64
110545 110552    184.0
Name: new_cases, dtype: float64
110546 110553    292.0
Name: new_cases, dtype: float64
110547 110554    264.0
Name: new_cases, dtype: float64
110548 110555    268.0
Name: new_cases, dtype: float64
110549 110556    258.0
Name: new_cases, dtype: float64
110550 110557    215.0
Name: new_cases, dtype: float64
110551 110558    214.0
Name: new_cases, dtype: float64
110552 110559    208.0
Name: new_cases, dtype: float64
110553 110560    205.0
Name: new_cases, dtype: float64
110554 110561    224.0
Name: new_cases, dtype: float64
110555 110562    279.0
Name: new_cases, dtype: float64
110556 110563    213.0
Name: new_cases, dtype: float64
110557 110564    163.0
Name: new_cases, dtype: float64
110558 110565    180.0
Name: new_cases, dtype: float64
110559 110566    258.0
Name: new_cases, dtype: float64
110560 110567    284.0
Name: new_cases, dtype: float64
110561 110568    350.0
Name: new_cases, dtype: float64
110562 110569    380.0
Name: new_cases, dtype: float64
110563 110570    539.0
Name: new_cases, dtype: float64
110564 110571    1046.0
Name: new_cases, dtype: float64
110565 110572    590.0
Name: new_cases, dtype: float64
110566 110573    862.0
Name: new_cases, dtype: float64
110567 110574    552.0
Name: new_cases, dtype: float64
110568 110575    359.0
Name: new_cases, dtype: float64
110569 110576    751.0
Name: new_cases, dtype: float64
110570 110577    634.0
Name: new_cases, dtype: float64
110571 110578    244.0
Name: new_cases, dtype: float64
110572 110579    714.0
Name: new_cases, dtype: float64
110573 110580    555.0
Name: new_cases, dtype: float64
110574 110581    579.0
Name: new_cases, dtype: float64
110575 110582    518.0
Name: new_cases, dtype: float64
110576 110583    740.0
Name: new_cases, dtype: float64
110577 110584    443.0
Name: new_cases, dtype: float64
110578 110585    612.0
Name: new_cases, dtype: float64
110579 110586    605.0
Name: new_cases, dtype: float64
110580 110587    538.0
Name: new_cases, dtype: float64
110581 110588    490.0
Name: new_cases, dtype: float64
110582 110589    361.0
Name: new_cases, dtype: float64
110583 110590    457.0
Name: new_cases, dtype: float64
110584 110591    561.0
Name: new_cases, dtype: float64
110585 110592    660.0
Name: new_cases, dtype: float64
110586 110593    941.0
Name: new_cases, dtype: float64
110587 110594    652.0
Name: new_cases, dtype: float64
110588 110595    630.0
Name: new_cases, dtype: float64
110589 110596    1143.0
Name: new_cases, dtype: float64
110590 110597    470.0
Name: new_cases, dtype: float64
110591 110598    774.0
Name: new_cases, dtype: float64
110592 110599    1004.0
Name: new_cases, dtype: float64
110593 110600    730.0
Name: new_cases, dtype: float64
110594 110601    652.0
Name: new_cases, dtype: float64
110595 110602    983.0
Name: new_cases, dtype: float64
110596 110603    1076.0
Name: new_cases, dtype: float64
110597 110604    997.0
Name: new_cases, dtype: float64
110598 110605    294.0
Name: new_cases, dtype: float64
110599 110606    1531.0
Name: new_cases, dtype: float64
110600 110607    1494.0
Name: new_cases, dtype: float64
110601 110608    2424.0
Name: new_cases, dtype: float64
110602 110609    2079.0
Name: new_cases, dtype: float64
110603 110610    1540.0
Name: new_cases, dtype: float64
110604 110611    2486.0
Name: new_cases, dtype: float64
110605 110612    1395.0
Name: new_cases, dtype: float64
110606 110613    1160.0
Name: new_cases, dtype: float64
110607 110614    1308.0
Name: new_cases, dtype: float64
110608 110615    2037.0
Name: new_cases, dtype: float64
110609 110616    747.0
Name: new_cases, dtype: float64
110610 110617    539.0
Name: new_cases, dtype: float64
110611 110618    1305.0
Name: new_cases, dtype: float64
110612 110619    2416.0
Name: new_cases, dtype: float64
110613 110620    1735.0
Name: new_cases, dtype: float64
110614 110621    2303.0
Name: new_cases, dtype: float64

110615 110622    2152.0
Name: new_cases, dtype: float64
110616 110623    1442.0
Name: new_cases, dtype: float64
110617 110624    1866.0
Name: new_cases, dtype: float64
110618 110625    1505.0
Name: new_cases, dtype: float64
110619 110626    2121.0
Name: new_cases, dtype: float64
110620 110627    2054.0
Name: new_cases, dtype: float64
110621 110628    1968.0
Name: new_cases, dtype: float64
110622 110629    2036.0
Name: new_cases, dtype: float64
110623 110630    1592.0
Name: new_cases, dtype: float64
110624 110631    1633.0
Name: new_cases, dtype: float64
110625 110632    1813.0
Name: new_cases, dtype: float64
110626 110633    3888.0
Name: new_cases, dtype: float64
110627 110634    3980.0
Name: new_cases, dtype: float64
110628 110635    4878.0
Name: new_cases, dtype: float64
110629 110636    4953.0
Name: new_cases, dtype: float64
110630 110637    3145.0
Name: new_cases, dtype: float64
110631 110638    6263.0
Name: new_cases, dtype: float64
110632 110639    3387.0
Name: new_cases, dtype: float64
110633 110640    3480.0
Name: new_cases, dtype: float64
110634 110641    3294.0
Name: new_cases, dtype: float64
110635 110642    4131.0
Name: new_cases, dtype: float64
110636 110643    3028.0
Name: new_cases, dtype: float64
110637 110644    6725.0
Name: new_cases, dtype: float64
110638 110645    2900.0
Name: new_cases, dtype: float64
110639 110646    4211.0
Name: new_cases, dtype: float64
110640 110647    3777.0
Name: new_cases, dtype: float64
110641 110648    6134.0
Name: new_cases, dtype: float64
110642 110649    4258.0
Name: new_cases, dtype: float64
110643 110650    3335.0
Name: new_cases, dtype: float64
110644 110651    3221.0
Name: new_cases, dtype: float64
110645 110652    4739.0
Name: new_cases, dtype: float64
110646 110653    4561.0
Name: new_cases, dtype: float64
110647 110654    4248.0
Name: new_cases, dtype: float64
110648 110655    4343.0
Name: new_cases, dtype: float64
110649 110656    4884.0
Name: new_cases, dtype: float64
110650 110657    2352.0
Name: new_cases, dtype: float64
110651 110658    4651.0
Name: new_cases, dtype: float64
110652 110659    2912.0
Name: new_cases, dtype: float64
110653 110660    5197.0
Name: new_cases, dtype: float64
110654 110661    3220.0
Name: new_cases, dtype: float64
110655 110662    3963.0
Name: new_cases, dtype: float64
110656 110663    3587.0
Name: new_cases, dtype: float64
110657 110664    4265.0
Name: new_cases, dtype: float64
110658 110665    3423.0
Name: new_cases, dtype: float64
110659 110666    3445.0
Name: new_cases, dtype: float64
110660 110667    2176.0
Name: new_cases, dtype: float64
110661 110668    1963.0
Name: new_cases, dtype: float64
110662 110669    3669.0
Name: new_cases, dtype: float64
110663 110670    2498.0
Name: new_cases, dtype: float64
110664 110671    2795.0
Name: new_cases, dtype: float64
110665 110672    1362.0
Name: new_cases, dtype: float64
110666 110673    3260.0
Name: new_cases, dtype: float64
110667 110674    3156.0
Name: new_cases, dtype: float64
110668 110675    3804.0
Name: new_cases, dtype: float64
110669 110676    4017.0
Name: new_cases, dtype: float64
110670 110677    4899.0
Name: new_cases, dtype: float64
110671 110678    3353.0
Name: new_cases, dtype: float64
110672 110679    4672.0
Name: new_cases, dtype: float64
110673 110680    3519.0
Name: new_cases, dtype: float64
110674 110681    3527.0
Name: new_cases, dtype: float64
110675 110682    3355.0
Name: new_cases, dtype: float64
110676 110683    3237.0
Name: new_cases, dtype: float64
110677 110684    3934.0
Name: new_cases, dtype: float64
110678 110685    3283.0
Name: new_cases, dtype: float64
110679 110686    3447.0
Name: new_cases, dtype: float64
110680 110687    1599.0
Name: new_cases, dtype: float64
110681 110688    2802.0
Name: new_cases, dtype: float64
110682 110689    2164.0
Name: new_cases, dtype: float64
110683 110690    2606.0
Name: new_cases, dtype: float64
110684 110691    1895.0
Name: new_cases, dtype: float64
110685 110692    2970.0
Name: new_cases, dtype: float64
110686 110693    3062.0
Name: new_cases, dtype: float64
110687 110694    2015.0
Name: new_cases, dtype: float64
110688 110695    2391.0
Name: new_cases, dtype: float64
110689 110696    2385.0
Name: new_cases, dtype: float64
110690 110697    2599.0
Name: new_cases, dtype: float64
110691 110698    2652.0
Name: new_cases, dtype: float64
110692 110699    3167.0
Name: new_cases, dtype: float64
110693 110700    2265.0
Name: new_cases, dtype: float64
110694 110701    2071.0
Name: new_cases, dtype: float64
110695 110702    2804.0
Name: new_cases, dtype: float64
110696 110703    2232.0
Name: new_cases, dtype: float64
110697 110704    2901.0
Name: new_cases, dtype: float64
110698 110705    2156.0
Name: new_cases, dtype: float64
110699 110706    2415.0
Name: new_cases, dtype: float64
110700 110707    3475.0
Name: new_cases, dtype: float64
110701 110708    1897.0
Name: new_cases, dtype: float64
110702 110709    1823.0
Name: new_cases, dtype: float64
110703 110710    2162.0
Name: new_cases, dtype: float64
110704 110711    3052.0
Name: new_cases, dtype: float64
110705 110712    2588.0
Name: new_cases, dtype: float64
110706 110713    2280.0
Name: new_cases, dtype: float64
110707 110714    2551.0
Name: new_cases, dtype: float64
110708 110715    1606.0
Name: new_cases, dtype: float64
110709 110716    1468.0
Name: new_cases, dtype: float64
110710 110717    1645.0
Name: new_cases, dtype: float64
110711 110718    1911.0
Name: new_cases, dtype: float64
110712 110719    2020.0
Name: new_cases, dtype: float64
110713 110720    2209.0
Name: new_cases, dtype: float64
110714 110721    1602.0
Name: new_cases, dtype: float64
110715 110722    1514.0
Name: new_cases, dtype: float64
110716 110723    2036.0
Name: new_cases, dtype: float64
110717 110724    1755.0
Name: new_cases, dtype: float64
110718 110725    1998.0
Name: new_cases, dtype: float64
110719 110726    1796.0
Name: new_cases, dtype: float64
110720 110727    2384.0
Name: new_cases, dtype: float64
110721 110728    2287.0
Name: new_cases, dtype: float64
110722 110729    1761.0
Name: new_cases, dtype: float64
110723 110730    976.0
Name: new_cases, dtype: float64
110724 110731    1588.0
Name: new_cases, dtype: float64
110725 110732    2084.0
Name: new_cases, dtype: float64
110726 110733    2152.0
Name: new_cases, dtype: float64
110727 110734    2434.0
Name: new_cases, dtype: float64
110728 110735    2054.0
Name: new_cases, dtype: float64
110729 110736    1300.0
Name: new_cases, dtype: float64
110730 110737    1667.0
Name: new_cases, dtype: float64
110731 110738    1404.0
Name: new_cases, dtype: float64
110732 110739    1893.0
Name: new_cases, dtype: float64
110733 110740    1624.0
Name: new_cases, dtype: float64
110734 110741    1501.0
Name: new_cases, dtype: float64
110735 110742    1736.0
Name: new_cases, dtype: float64
110736 110743    1144.0
Name: new_cases, dtype: float64
110737 110744    1379.0
Name: new_cases, dtype: float64
110738 110745    1333.0
Name: new_cases, dtype: float64
110739 110746    1637.0
Name: new_cases, dtype: float64
110740 110747    1785.0
Name: new_cases, dtype: float64
110741 110748    1966.0
Name: new_cases, dtype: float64
110742 110749    1796.0
Name: new_cases, dtype: float64
110743 110750    1108.0
Name: new_cases, dtype: float64
110744 110751    1193.0
Name: new_cases, dtype: float64
110745 110752    1382.0
Name: new_cases, dtype: float64
110746 110753    1621.0
Name: new_cases, dtype: float64
110747 110754    1879.0
Name: new_cases, dtype: float64
110748 110755    2067.0
Name: new_cases, dtype: float64
110749 110756    1766.0
Name: new_cases, dtype: float64
110750 110757    1295.0
Name: new_cases, dtype: float64
110751 110758    1432.0
Name: new_cases, dtype: float64
110752 110759    1056.0
Name: new_cases, dtype: float64
110753 110760    932.0
Name: new_cases, dtype: float64
110754 110761    1724.0
Name: new_cases, dtype: float64
110755 110762    1765.0
Name: new_cases, dtype: float64
110756 110763    1565.0
Name: new_cases, dtype: float64
110757 110764    1386.0
Name: new_cases, dtype: float64
110758 110765    1379.0
Name: new_cases, dtype: float64
110759 110766    1376.0
Name: new_cases, dtype: float64
110760 110767    1499.0
Name: new_cases, dtype: float64
110761 110768    1292.0
Name: new_cases, dtype: float64
110762 110769    1069.0
Name: new_cases, dtype: float64
110763 110770    1333.0
Name: new_cases, dtype: float64
110764 110771    1106.0
Name: new_cases, dtype: float64
110765 110772    1149.0
Name: new_cases, dtype: float64
110766 110773    1459.0
Name: new_cases, dtype: float64
110767 110774    2115.0
Name: new_cases, dtype: float64
110768 110775    1482.0
Name: new_cases, dtype: float64
110769 110776    1745.0
Name: new_cases, dtype: float64
110770 110777    1716.0
Name: new_cases, dtype: float64
110771 110778    1310.0
Name: new_cases, dtype: float64
110772 110779    1189.0
Name: new_cases, dtype: float64
110773 110780    1720.0
Name: new_cases, dtype: float64
110774 110781    1877.0
Name: new_cases, dtype: float64
110775 110782    1404.0
Name: new_cases, dtype: float64
110776 110783    881.0
Name: new_cases, dtype: float64
110777 110784    764.0
Name: new_cases, dtype: float64
110778 110785    876.0
Name: new_cases, dtype: float64

110779 110786    1006.0
Name: new_cases, dtype: float64
110780 110787    1532.0
Name: new_cases, dtype: float64
110781 110788    1756.0
Name: new_cases, dtype: float64
110782 110789    1096.0
Name: new_cases, dtype: float64
110783 110790    891.0
Name: new_cases, dtype: float64
110784 110791    954.0
Name: new_cases, dtype: float64
110785 110792    932.0
Name: new_cases, dtype: float64
110786 110793    1044.0
Name: new_cases, dtype: float64
110787 110794    1346.0
Name: new_cases, dtype: float64
110788 110795    1769.0
Name: new_cases, dtype: float64
110789 110796    1945.0
Name: new_cases, dtype: float64
110790 110797    1893.0
Name: new_cases, dtype: float64
110791 110798    2046.0
Name: new_cases, dtype: float64
110792 110799    1522.0
Name: new_cases, dtype: float64
110793 110800    1442.0
Name: new_cases, dtype: float64
110794 110801    1905.0
Name: new_cases, dtype: float64
110795 110802    2041.0
Name: new_cases, dtype: float64
110796 110803    2045.0
Name: new_cases, dtype: float64
110797 110804    1886.0
Name: new_cases, dtype: float64
110798 110805    2159.0
Name: new_cases, dtype: float64
110799 110806    1348.0
Name: new_cases, dtype: float64
110800 110807    1855.0
Name: new_cases, dtype: float64
110801 110808    1778.0
Name: new_cases, dtype: float64
110802 110809    2170.0
Name: new_cases, dtype: float64
110803 110810    1792.0
Name: new_cases, dtype: float64
110804 110811    1940.0
Name: new_cases, dtype: float64
110805 110812    1377.0
Name: new_cases, dtype: float64
110806 110813    1170.0
Name: new_cases, dtype: float64
110807 110814    2241.0
Name: new_cases, dtype: float64
110808 110815    1168.0
Name: new_cases, dtype: float64
110809 110816    1838.0
Name: new_cases, dtype: float64
110810 110817    2103.0
Name: new_cases, dtype: float64
110811 110818    2102.0
Name: new_cases, dtype: float64
110812 110819    1654.0
Name: new_cases, dtype: float64
110813 110820    1581.0
Name: new_cases, dtype: float64
110814 110821    1265.0
Name: new_cases, dtype: float64
110815 110822    1581.0
Name: new_cases, dtype: float64
110816 110823    1888.0
Name: new_cases, dtype: float64
110817 110824    1934.0
Name: new_cases, dtype: float64
110818 110825    1789.0
Name: new_cases, dtype: float64
110819 110826    1685.0
Name: new_cases, dtype: float64
110820 110827    1232.0
Name: new_cases, dtype: float64
110821 110828    1333.0
Name: new_cases, dtype: float64
110822 110829    1722.0
Name: new_cases, dtype: float64
110823 110830    2018.0
Name: new_cases, dtype: float64
110824 110831    1955.0
Name: new_cases, dtype: float64
110825 110832    1921.0
Name: new_cases, dtype: float64
110826 110833    1684.0
Name: new_cases, dtype: float64
110827 110834    1386.0
Name: new_cases, dtype: float64
110828 110835    1178.0
Name: new_cases, dtype: float64
110829 110836    1739.0
Name: new_cases, dtype: float64
110830 110837    1895.0
Name: new_cases, dtype: float64
110831 110838    2230.0
Name: new_cases, dtype: float64
110832 110839    1881.0
Name: new_cases, dtype: float64
110833 110840    2287.0
Name: new_cases, dtype: float64
110834 110841    1409.0
Name: new_cases, dtype: float64
110835 110842    1555.0
Name: new_cases, dtype: float64
110836 110843    2260.0
Name: new_cases, dtype: float64
110837 110844    2647.0
Name: new_cases, dtype: float64
110838 110845    2920.0
Name: new_cases, dtype: float64
110839 110846    2105.0
Name: new_cases, dtype: float64
110840 110847    2029.0
Name: new_cases, dtype: float64
110841 110848    2061.0
Name: new_cases, dtype: float64
110842 110849    1781.0
Name: new_cases, dtype: float64
110843 110850    2444.0
Name: new_cases, dtype: float64
110844 110851    3037.0
Name: new_cases, dtype: float64
110845 110852    3434.0
Name: new_cases, dtype: float64
110846 110853    3274.0
Name: new_cases, dtype: float64
110847 110854    3351.0
Name: new_cases, dtype: float64
110848 110855    2665.0
Name: new_cases, dtype: float64
110849 110856    2880.0
Name: new_cases, dtype: float64
110850 110857    3740.0
Name: new_cases, dtype: float64
110851 110858    4570.0
Name: new_cases, dtype: float64
110852 110859    4993.0
Name: new_cases, dtype: float64
110853 110860    4887.0
Name: new_cases, dtype: float64
110854 110861    5395.0
Name: new_cases, dtype: float64
110855 110862    4427.0
Name: new_cases, dtype: float64
110856 110863    4378.0
Name: new_cases, dtype: float64
110857 110864    5286.0
Name: new_cases, dtype: float64
110858 110865    7082.0
Name: new_cases, dtype: float64
110859 110866    7990.0
Name: new_cases, dtype: float64
110860 110867    7738.0
Name: new_cases, dtype: float64
110861 110868    7998.0
Name: new_cases, dtype: float64
110862 110869    5861.0
Name: new_cases, dtype: float64
110863 110870    6658.0
Name: new_cases, dtype: float64
110864 110871    8737.0
Name: new_cases, dtype: float64
110865 110872    9808.0
Name: new_cases, dtype: float64
110866 110873    9586.0
Name: new_cases, dtype: float64
110867 110874    9450.0
Name: new_cases, dtype: float64
110868 110875    10002.0
Name: new_cases, dtype: float64
110869 110876    9287.0
Name: new_cases, dtype: float64
110870 110877    6107.0
Name: new_cases, dtype: float64
110871 110878    8911.0
Name: new_cases, dtype: float64
110872 110879    15298.0
Name: new_cases, dtype: float64
110873 110880    12546.0
Name: new_cases, dtype: float64
110874 110881    11008.0
Name: new_cases, dtype: float64
110875 110882    8347.0
Name: new_cases, dtype: float64
110876 110883    9362.0
Name: new_cases, dtype: float64
110877 110884    6404.0
Name: new_cases, dtype: float64
110878 110885    9202.0
Name: new_cases, dtype: float64
110879 110886    12188.0
Name: new_cases, dtype: float64
110880 110887    12655.0
Name: new_cases, dtype: float64
110881 110888    11659.0
Name: new_cases, dtype: float64
110882 110889    11357.0
Name: new_cases, dtype: float64
110883 110890    8558.0
Name: new_cases, dtype: float64
110884 110891    8097.0
Name: new_cases, dtype: float64
110885 110892    11405.0
Name: new_cases, dtype: float64
110886 110893    10686.0
Name: new_cases, dtype: float64
110887 110894    11081.0
Name: new_cases, dtype: float64
110888 110895    10081.0
Name: new_cases, dtype: float64
110889 110896    9612.0
Name: new_cases, dtype: float64
110890 110897    7361.0
Name: new_cases, dtype: float64
110891 110898    9201.0
Name: new_cases, dtype: float64
110892 110899    8742.0
Name: new_cases, dtype: float64
110893 110900    8691.0
Name: new_cases, dtype: float64
110894 110901    9640.0
Name: new_cases, dtype: float64
110895 110902    8143.0
Name: new_cases, dtype: float64
110896 110903    8905.0
Name: new_cases, dtype: float64
110897 110904    7190.0
Name: new_cases, dtype: float64
110898 110905    6877.0
Name: new_cases, dtype: float64
110899 110906    8243.0
Name: new_cases, dtype: float64
110900 110907    8722.0
Name: new_cases, dtype: float64
110901 110908    9193.0
Name: new_cases, dtype: float64
110902 110909    8330.0
Name: new_cases, dtype: float64
110903 110910    7242.0
Name: new_cases, dtype: float64
110904 110911    5667.0
Name: new_cases, dtype: float64
110905 110912    5663.0
Name: new_cases, dtype: float64
110906 110913    6617.0
Name: new_cases, dtype: float64
110907 110914    7713.0
Name: new_cases, dtype: float64
110908 110915    6964.0
Name: new_cases, dtype: float64
110909 110916    7141.0
Name: new_cases, dtype: float64
110910 110917    6836.0
Name: new_cases, dtype: float64
110911 110918    4721.0
Name: new_cases, dtype: float64
110912 110919    4812.0
Name: new_cases, dtype: float64
110913 110920    6365.0
Name: new_cases, dtype: float64
110914 110921    6743.0
Name: new_cases, dtype: float64
110915 110922    6720.0
Name: new_cases, dtype: float64
110916 110923    5776.0
Name: new_cases, dtype: float64
110917 110924    5962.0
Name: new_cases, dtype: float64
110918 110925    4463.0
Name: new_cases, dtype: float64
110919 110926    4683.0
Name: new_cases, dtype: float64
110920 110927    6084.0
Name: new_cases, dtype: float64
110921 110928    6248.0
Name: new_cases, dtype: float64
110922 110929    6814.0
Name: new_cases, dtype: float64
110923 110930    1595.0
Name: new_cases, dtype: float64
110924 110931    4894.0
Name: new_cases, dtype: float64
110925 110932    3966.0
Name: new_cases, dtype: float64
110926 110933    5304.0
Name: new_cases, dtype: float64
110927 110934    6454.0
Name: new_cases, dtype: float64
110928 110935    8724.0
Name: new_cases, dtype: float64
110929 110936    7428.0
Name: new_cases, dtype: float64
110930 110937    7045.0
Name: new_cases, dtype: float64
110931 110938    6674.0
Name: new_cases, dtype: float64
110932 110939    5166.0
Name: new_cases, dtype: float64
110933 110940    5249.0
Name: new_cases, dtype: float64
110934 110941    7183.0
Name: new_cases, dtype: float64
110935 110942    7438.0
Name: new_cases, dtype: float64

110936 110943    6936.0
Name: new_cases, dtype: float64
110937 110944    7205.0
Name: new_cases, dtype: float64
110938 110945    6526.0
Name: new_cases, dtype: float64
110939 110946    4769.0
Name: new_cases, dtype: float64
110940 110947    5444.0
Name: new_cases, dtype: float64
110941 110948    7470.0
Name: new_cases, dtype: float64
110942 110949    6662.0
Name: new_cases, dtype: float64
110943 110950    8003.0
Name: new_cases, dtype: float64
110944 110951    7287.0
Name: new_cases, dtype: float64
110945 110952    6414.0
Name: new_cases, dtype: float64
110946 110953    5378.0
Name: new_cases, dtype: float64
110947 110954    5401.0
Name: new_cases, dtype: float64
110948 110955    6625.0
Name: new_cases, dtype: float64
110949 110956    6819.0
Name: new_cases, dtype: float64
110950 110957    6944.0
Name: new_cases, dtype: float64
110951 110958    5795.0
Name: new_cases, dtype: float64
110952 110959    5224.0
Name: new_cases, dtype: float64
110953 110960    3655.0
Name: new_cases, dtype: float64
110954 110961    4338.0
Name: new_cases, dtype: float64
110955 110962    6028.0
Name: new_cases, dtype: float64
110956 110963    6793.0
Name: new_cases, dtype: float64
110957 110964    6858.0
Name: new_cases, dtype: float64
110958 110965    6081.0
Name: new_cases, dtype: float64
110959 110966    5596.0
Name: new_cases, dtype: float64
110960 110967    4470.0
Name: new_cases, dtype: float64
110961 110968    4501.0
Name: new_cases, dtype: float64
110962 110969    5778.0
Name: new_cases, dtype: float64
110963 110970    6181.0
Name: new_cases, dtype: float64
110964 110971    5901.0
Name: new_cases, dtype: float64
110965 110972    5950.0
Name: new_cases, dtype: float64
110966 110973    5377.0
Name: new_cases, dtype: float64
110967 110974    4086.0
Name: new_cases, dtype: float64
110968 110975    4278.0
Name: new_cases, dtype: float64
110969 110976    5475.0
Name: new_cases, dtype: float64
110970 110977    5870.0
Name: new_cases, dtype: float64
110971 110978    5664.0
Name: new_cases, dtype: float64
110972 110979    5906.0
Name: new_cases, dtype: float64
110973 110980    5036.0
Name: new_cases, dtype: float64
110974 110981    3599.0
Name: new_cases, dtype: float64
110975 110982    3797.0
Name: new_cases, dtype: float64
110976 110983    5208.0
Name: new_cases, dtype: float64
110977 110984    5663.0
Name: new_cases, dtype: float64
110978 110985    6031.0
Name: new_cases, dtype: float64
110979 110986    5396.0
Name: new_cases, dtype: float64
110980 110987    5641.0
Name: new_cases, dtype: float64
110981 110988    4507.0
Name: new_cases, dtype: float64
110982 110989    6546.0
Name: new_cases, dtype: float64
110983 110990    5817.0
Name: new_cases, dtype: float64
110984 110991    6831.0
Name: new_cases, dtype: float64
110985 110992    6184.0
Name: new_cases, dtype: float64
110986 110993    5474.0
Name: new_cases, dtype: float64
110987 110994    6641.0
Name: new_cases, dtype: float64
110988 110995    7024.0
Name: new_cases, dtype: float64
110989 110996    4247.0
Name: new_cases, dtype: float64
110990 110997    5620.0
Name: new_cases, dtype: float64
110991 110998    8537.0
Name: new_cases, dtype: float64
110992 110999    8141.0
Name: new_cases, dtype: float64
110993 111000    8724.0
Name: new_cases, dtype: float64
110994 111001    8073.0
Name: new_cases, dtype: float64
110995 111002    6779.0
Name: new_cases, dtype: float64
110996 111003    7283.0
Name: new_cases, dtype: float64
110997 111004    7992.0
Name: new_cases, dtype: float64
110998 111005    10529.0
Name: new_cases, dtype: float64
110999 111006    10996.0
Name: new_cases, dtype: float64
111000 111007    9575.0
Name: new_cases, dtype: float64
111001 111008    8798.0
Name: new_cases, dtype: float64
111002 111009    8442.0
Name: new_cases, dtype: float64
111003 111010    11884.0
Name: new_cases, dtype: float64
111004 111011    12323.0
Name: new_cases, dtype: float64
111005 111012    12939.0
Name: new_cases, dtype: float64
111006 111013    13929.0
Name: new_cases, dtype: float64
111007 111014    14385.0
Name: new_cases, dtype: float64
111008 111015    14230.0
Name: new_cases, dtype: float64
111009 111016    9829.0
Name: new_cases, dtype: float64
111010 111017    10820.0
Name: new_cases, dtype: float64
111011 111018    14508.0
Name: new_cases, dtype: float64
111012 111019    16797.0
Name: new_cases, dtype: float64
111013 111020    16251.0
Name: new_cases, dtype: float64
111014 111021    15584.0
Name: new_cases, dtype: float64
111015 111022    18011.0
Name: new_cases, dtype: float64
111016 111023    12045.0
Name: new_cases, dtype: float64
111017 111024    13397.0
Name: new_cases, dtype: float64
111018 111025    16112.0
Name: new_cases, dtype: float64
111019 111026    17261.0
Name: new_cases, dtype: float64
111020 111027    19239.0
Name: new_cases, dtype: float64
111021 111028    18323.0
Name: new_cases, dtype: float64
111022 111029    22179.0
Name: new_cases, dtype: float64
111023 111030    13655.0
Name: new_cases, dtype: float64
111024 111031    14098.0
Name: new_cases, dtype: float64
111025 111032    16529.0
Name: new_cases, dtype: float64
111026 111033    20084.0
Name: new_cases, dtype: float64
111027 111034    20516.0
Name: new_cases, dtype: float64
111028 111035    19900.0
Name: new_cases, dtype: float64
111029 111036    22347.0
Name: new_cases, dtype: float64
111030 111037    17977.0
Name: new_cases, dtype: float64
111031 111038    12697.0
Name: new_cases, dtype: float64
111032 111039    27887.0
Name: new_cases, dtype: float64
111033 111040    17878.0
Name: new_cases, dtype: float64
111034 111041    26251.0
Name: new_cases, dtype: float64
111035 111042    21346.0
Name: new_cases, dtype: float64
111036 111043    20704.0
Name: new_cases, dtype: float64
111037 111044    17995.0
Name: new_cases, dtype: float64
111038 111045    16945.0
Name: new_cases, dtype: float64
111039 111046    21181.0
Name: new_cases, dtype: float64
111040 111047    20283.0
Name: new_cases, dtype: float64
111041 111048    23075.0
Name: new_cases, dtype: float64
111042 111049    19199.0
Name: new_cases, dtype: float64
111043 111050    18867.0
Name: new_cases, dtype: float64
111044 111051    16300.0
Name: new_cases, dtype: float64
111045 111052    15503.0
Name: new_cases, dtype: float64
111046 111053    17334.0
Name: new_cases, dtype: float64
111047 111054    18575.0
Name: new_cases, dtype: float64
111048 111055    16847.0
Name: new_cases, dtype: float64
111049 111056    20683.0
Name: new_cases, dtype: float64
111050 111057    0.0
Name: new_cases, dtype: float64
111051 111058    18319.0
Name: new_cases, dtype: float64
111052 111059    26555.0
Name: new_cases, dtype: float64
111053 111060    14234.0
Name: new_cases, dtype: float64
111054 111061    15521.0
Name: new_cases, dtype: float64
111055 111062    14686.0
Name: new_cases, dtype: float64
111056 111063    13226.0
Name: new_cases, dtype: float64
111057 111064    10641.0
Name: new_cases, dtype: float64
111058 111065    9030.0
Name: new_cases, dtype: float64
111059 111066    9847.0
Name: new_cases, dtype: float64
111060 111067    0.0
Name: new_cases, dtype: float64
111061 111068    20577.0
Name: new_cases, dtype: float64
111062 111069    10956.0
Name: new_cases, dtype: float64
111063 111070    12112.0
Name: new_cases, dtype: float64
111064 111071    8252.0
Name: new_cases, dtype: float64
111065 111072    8558.0
Name: new_cases, dtype: float64
111066 111073    7083.0
Name: new_cases, dtype: float64
111067 111074    7777.0
Name: new_cases, dtype: float64
111068 111075    7560.0
Name: new_cases, dtype: float64
111069 111076    7717.0
Name: new_cases, dtype: float64
111070 111077    6859.0
Name: new_cases, dtype: float64
111071 111078    6918.0
Name: new_cases, dtype: float64
111072 111079    4449.0
Name: new_cases, dtype: float64
111073 111080    3634.0
Name: new_cases, dtype: float64
111074 111081    4742.0
Name: new_cases, dtype: float64
111075 111082    5778.0
Name: new_cases, dtype: float64
111076 111083    5778.0
Name: new_cases, dtype: float64
111077 111084    5256.0
Name: new_cases, dtype: float64
111078 111085    4384.0
Name: new_cases, dtype: float64
111079 111086    4365.0
Name: new_cases, dtype: float64
111080 111087    3177.0
Name: new_cases, dtype: float64
111081 111088    0.0
Name: new_cases, dtype: float64
111082 111089    11094.0
Name: new_cases, dtype: float64
111083 111090    3953.0
Name: new_cases, dtype: float64
111084 111091    3380.0
Name: new_cases, dtype: float64
111085 111092    3099.0
Name: new_cases, dtype: float64
111086 111093    2281.0
Name: new_cases, dtype: float64
111087 111094    1242.0
Name: new_cases, dtype: float64
111088 111095    1744.0
Name: new_cases, dtype: float64
111089 111096    2344.0
Name: new_cases, dtype: float64
111090 111097    2635.0
Name: new_cases, dtype: float64
111091 111098    2592.0
Name: new_cases, dtype: float64
111092 111099    2081.0
Name: new_cases, dtype: float64
111093 111100    1400.0
Name: new_cases, dtype: float64
111094 111101    0.0
Name: new_cases, dtype: float64
111095 111102    4554.0
Name: new_cases, dtype: float64
111096 111103    1867.0
Name: new_cases, dtype: float64
111097 111104    1965.0
Name: new_cases, dtype: float64
111098 111105    1900.0
Name: new_cases, dtype: float64
111099 111106    1531.0
Name: new_cases, dtype: float64
111100 111107    830.0
Name: new_cases, dtype: float64
111101 111108    1153.0
Name: new_cases, dtype: float64

111102 111109    1259.0
Name: new_cases, dtype: float64
111103 111110    1457.0
Name: new_cases, dtype: float64
111104 111111    1289.0
Name: new_cases, dtype: float64
111105 111112    1911.0
Name: new_cases, dtype: float64
111106 111113    443.0
Name: new_cases, dtype: float64
111107 111114    967.0
Name: new_cases, dtype: float64
111108 111115    840.0
Name: new_cases, dtype: float64
111109 111116    958.0
Name: new_cases, dtype: float64
111110 111117    769.0
Name: new_cases, dtype: float64
111111 111118    790.0
Name: new_cases, dtype: float64
111112 111119    630.0
Name: new_cases, dtype: float64
111113 111120    568.0
Name: new_cases, dtype: float64
111114 111121    359.0
Name: new_cases, dtype: float64
111115 111122    304.0
Name: new_cases, dtype: float64
111116 111123    435.0
Name: new_cases, dtype: float64
111117 111124    405.0
Name: new_cases, dtype: float64
111118 111125    416.0
Name: new_cases, dtype: float64
111119 111126    481.0
Name: new_cases, dtype: float64
111120 111127    379.0
Name: new_cases, dtype: float64
111121 111128    0.0
Name: new_cases, dtype: float64
111122 111129    439.0
Name: new_cases, dtype: float64
111123 111130    403.0
Name: new_cases, dtype: float64
111124 111131    204.0
Name: new_cases, dtype: float64
111125 111132    160.0
Name: new_cases, dtype: float64
111126 111133    232.0
Name: new_cases, dtype: float64
111127 111134    211.0
Name: new_cases, dtype: float64
111128 111135    65.0
Name: new_cases, dtype: float64
111129 111136    47.0
Name: new_cases, dtype: float64
111130 111137    101.0
Name: new_cases, dtype: float64
111131 111138    448.0
Name: new_cases, dtype: float64
111132 111139    91.0
Name: new_cases, dtype: float64
111133 111140    22.0
Name: new_cases, dtype: float64
111134 111141    153.0
Name: new_cases, dtype: float64
111135 111142   -11.0
Name: new_cases, dtype: float64
111136 111143    65.0
Name: new_cases, dtype: float64
111137 111144    119.0
Name: new_cases, dtype: float64
111138 111145    129.0
Name: new_cases, dtype: float64
111139 111146    349.0
Name: new_cases, dtype: float64
111140 111147    259.0
Name: new_cases, dtype: float64
111141 111148    152.0
Name: new_cases, dtype: float64
111142 111149    319.0
Name: new_cases, dtype: float64
111143 111150    679.0
Name: new_cases, dtype: float64
111144 111151    1470.0
Name: new_cases, dtype: float64
111145 111152    2719.0
Name: new_cases, dtype: float64
111146 111153    3507.0
Name: new_cases, dtype: float64
111147 111154    4445.0
Name: new_cases, dtype: float64
111148 111155    3888.0
Name: new_cases, dtype: float64
111149 111156    5300.0
Name: new_cases, dtype: float64
111150 111157    10626.0
Name: new_cases, dtype: float64
111151 111158    17172.0
Name: new_cases, dtype: float64
111152 111159    21747.0
Name: new_cases, dtype: float64
111153 111160    26211.0
Name: new_cases, dtype: float64
111154 110484    0.0
Name: new_cases, dtype: float64
111155 110485    0.0
Name: new_cases, dtype: float64
111156 110486    2.0
Name: new_cases, dtype: float64
111157 110487    1.0
Name: new_cases, dtype: float64
111158 110488    4.0
Name: new_cases, dtype: float64
111159 110489    10.0
Name: new_cases, dtype: float64
111160 110490    13.0
Name: new_cases, dtype: float64
111246 111253    9.0
Name: new_cases, dtype: float64
111247 111254    18.0
Name: new_cases, dtype: float64
111248 111255    19.0
Name: new_cases, dtype: float64
111249 111256    35.0
Name: new_cases, dtype: float64
111250 111257    16.0
Name: new_cases, dtype: float64
111251 111258    58.0
Name: new_cases, dtype: float64
111252 111259    61.0
Name: new_cases, dtype: float64
111253 111260    13.0
Name: new_cases, dtype: float64
111254 111261    104.0
Name: new_cases, dtype: float64
111255 111262    70.0
Name: new_cases, dtype: float64
111256 111263    111.0
Name: new_cases, dtype: float64
111257 111264    98.0
Name: new_cases, dtype: float64
111258 111265    115.0
Name: new_cases, dtype: float64
111259 111266    152.0
Name: new_cases, dtype: float64
111260 111267    150.0
Name: new_cases, dtype: float64
111261 111268    170.0
Name: new_cases, dtype: float64
111262 111269    168.0
Name: new_cases, dtype: float64
111263 111270    249.0
Name: new_cases, dtype: float64
111264 111271    224.0
Name: new_cases, dtype: float64
111265 111272    193.0
Name: new_cases, dtype: float64
111266 111273    256.0
Name: new_cases, dtype: float64
111267 111274    243.0
Name: new_cases, dtype: float64
111268 111275    392.0
Name: new_cases, dtype: float64
111269 111276    437.0
Name: new_cases, dtype: float64
111270 111277    244.0
Name: new_cases, dtype: float64
111271 111278    475.0
Name: new_cases, dtype: float64
111272 111279    311.0
Name: new_cases, dtype: float64
111273 111280    435.0
Name: new_cases, dtype: float64
111274 111281    357.0
Name: new_cases, dtype: float64
111275 111282    370.0
Name: new_cases, dtype: float64
111276 111283    380.0
Name: new_cases, dtype: float64
111277 111284    401.0
Name: new_cases, dtype: float64
111278 111285    318.0
Name: new_cases, dtype: float64
111279 111286    260.0
Name: new_cases, dtype: float64
111280 111287    268.0
Name: new_cases, dtype: float64
111281 111288    380.0
Name: new_cases, dtype: float64
111282 111289    336.0
Name: new_cases, dtype: float64
111283 111290    461.0
Name: new_cases, dtype: float64
111284 111291    363.0
Name: new_cases, dtype: float64
111285 111292    545.0
Name: new_cases, dtype: float64
111286 111293    306.0
Name: new_cases, dtype: float64
111287 111294    263.0
Name: new_cases, dtype: float64
111288 111295    313.0
Name: new_cases, dtype: float64
111289 111296    342.0
Name: new_cases, dtype: float64
111290 111297    381.0
Name: new_cases, dtype: float64
111291 111298    381.0
Name: new_cases, dtype: float64
111292 111299    344.0
Name: new_cases, dtype: float64
111293 111300    285.0
Name: new_cases, dtype: float64
111294 111301    316.0
Name: new_cases, dtype: float64
111295 111302    422.0
Name: new_cases, dtype: float64
111296 111303    237.0
Name: new_cases, dtype: float64
111297 111304    228.0
Name: new_cases, dtype: float64
111298 111305    270.0
Name: new_cases, dtype: float64
111299 111306    318.0
Name: new_cases, dtype: float64
111300 111307    313.0
Name: new_cases, dtype: float64
111301 111308    425.0
Name: new_cases, dtype: float64
111302 111309    309.0
Name: new_cases, dtype: float64
111303 111310    307.0
Name: new_cases, dtype: float64
111304 111311    319.0
Name: new_cases, dtype: float64
111305 111312    285.0
Name: new_cases, dtype: float64
111306 111313    345.0
Name: new_cases, dtype: float64
111307 111314    330.0
Name: new_cases, dtype: float64
111308 111315    595.0
Name: new_cases, dtype: float64
111309 111316    283.0
Name: new_cases, dtype: float64
111310 111317    411.0
Name: new_cases, dtype: float64
111311 111318    401.0
Name: new_cases, dtype: float64
111312 111319    241.0
Name: new_cases, dtype: float64
111313 111320    272.0
Name: new_cases, dtype: float64
111314 111321    356.0
Name: new_cases, dtype: float64
111315 111322    383.0
Name: new_cases, dtype: float64
111316 111323    471.0
Name: new_cases, dtype: float64
111317 111324    404.0
Name: new_cases, dtype: float64
111318 111325    476.0
Name: new_cases, dtype: float64
111319 111326    312.0
Name: new_cases, dtype: float64
111320 111327    395.0
Name: new_cases, dtype: float64
111321 111328    305.0
Name: new_cases, dtype: float64
111322 111329    443.0
Name: new_cases, dtype: float64
111323 111330    399.0
Name: new_cases, dtype: float64
111324 111331    352.0
Name: new_cases, dtype: float64
111325 111332    330.0
Name: new_cases, dtype: float64
111326 111333    416.0
Name: new_cases, dtype: float64
111327 111334    215.0
Name: new_cases, dtype: float64
111328 111335    379.0
Name: new_cases, dtype: float64
111329 111336    230.0
Name: new_cases, dtype: float64
111330 111337    292.0
Name: new_cases, dtype: float64
111331 111338    361.0
Name: new_cases, dtype: float64
111332 111339    362.0
Name: new_cases, dtype: float64
111333 111340    576.0
Name: new_cases, dtype: float64
111334 111341    575.0
Name: new_cases, dtype: float64
111335 111342    599.0
Name: new_cases, dtype: float64
111336 111343    400.0
Name: new_cases, dtype: float64
111337 111344    282.0
Name: new_cases, dtype: float64
111338 111345    359.0
Name: new_cases, dtype: float64
111339 111346    376.0
Name: new_cases, dtype: float64
111340 111347    440.0
Name: new_cases, dtype: float64
111341 111348    375.0
Name: new_cases, dtype: float64
111342 111349    396.0
Name: new_cases, dtype: float64
111343 111350    407.0
Name: new_cases, dtype: float64
111344 111351    506.0
Name: new_cases, dtype: float64
111345 111352    314.0
Name: new_cases, dtype: float64
111346 111353    301.0
Name: new_cases, dtype: float64
111347 111354    304.0
Name: new_cases, dtype: float64
111348 111355    311.0
Name: new_cases, dtype: float64
111349 111356    296.0
Name: new_cases, dtype: float64
111350 111357    300.0
Name: new_cases, dtype: float64
111351 111358    294.0
Name: new_cases, dtype: float64
111352 111359    298.0
Name: new_cases, dtype: float64
111353 111360    276.0
Name: new_cases, dtype: float64
111354 111361    319.0
Name: new_cases, dtype: float64
111355 111362    193.0
Name: new_cases, dtype: float64

111356 111363    247.0
Name: new_cases, dtype: float64
111357 111364    239.0
Name: new_cases, dtype: float64
111358 111365    382.0
Name: new_cases, dtype: float64
111359 111366    371.0
Name: new_cases, dtype: float64
111360 111367    259.0
Name: new_cases, dtype: float64
111361 111368    314.0
Name: new_cases, dtype: float64
111362 111369    231.0
Name: new_cases, dtype: float64
111363 111370    205.0
Name: new_cases, dtype: float64
111364 111371    257.0
Name: new_cases, dtype: float64
111365 111372    277.0
Name: new_cases, dtype: float64
111366 111373    262.0
Name: new_cases, dtype: float64
111367 111374    265.0
Name: new_cases, dtype: float64
111368 111375    305.0
Name: new_cases, dtype: float64
111369 111376    370.0
Name: new_cases, dtype: float64
111370 111377    299.0
Name: new_cases, dtype: float64
111371 111378    267.0
Name: new_cases, dtype: float64
111372 111379    264.0
Name: new_cases, dtype: float64
111373 111380    333.0
Name: new_cases, dtype: float64
111374 111381    353.0
Name: new_cases, dtype: float64
111375 111382    339.0
Name: new_cases, dtype: float64
111376 111383    358.0
Name: new_cases, dtype: float64
111377 111384    279.0
Name: new_cases, dtype: float64
111378 111385    399.0
Name: new_cases, dtype: float64
111379 111386    380.0
Name: new_cases, dtype: float64
111380 111387    418.0
Name: new_cases, dtype: float64
111381 111388    458.0
Name: new_cases, dtype: float64
111382 111389    584.0
Name: new_cases, dtype: float64
111383 111390    443.0
Name: new_cases, dtype: float64
111384 111391    337.0
Name: new_cases, dtype: float64
111385 111392    502.0
Name: new_cases, dtype: float64
111386 111393    512.0
Name: new_cases, dtype: float64
111387 111394    615.0
Name: new_cases, dtype: float64
111388 111395    657.0
Name: new_cases, dtype: float64
111389 111396    658.0
Name: new_cases, dtype: float64
111390 111397    548.0
Name: new_cases, dtype: float64
111391 111398    575.0
Name: new_cases, dtype: float64
111392 111399    680.0
Name: new_cases, dtype: float64
111393 111400    640.0
Name: new_cases, dtype: float64
111394 111401    726.0
Name: new_cases, dtype: float64
111395 111402    809.0
Name: new_cases, dtype: float64
111396 111403    843.0
Name: new_cases, dtype: float64
111397 111404    624.0
Name: new_cases, dtype: float64
111398 111405    619.0
Name: new_cases, dtype: float64
111399 111406    551.0
Name: new_cases, dtype: float64
111400 111407    715.0
Name: new_cases, dtype: float64
111401 111408    811.0
Name: new_cases, dtype: float64
111402 111409    832.0
Name: new_cases, dtype: float64
111403 111410    771.0
Name: new_cases, dtype: float64
111404 111411    594.0
Name: new_cases, dtype: float64
111405 111412    595.0
Name: new_cases, dtype: float64
111406 111413    597.0
Name: new_cases, dtype: float64
111407 111414    735.0
Name: new_cases, dtype: float64
111408 111415    767.0
Name: new_cases, dtype: float64
111409 111416    903.0
Name: new_cases, dtype: float64
111410 111417    900.0
Name: new_cases, dtype: float64
111411 111418    581.0
Name: new_cases, dtype: float64
111412 111419    548.0
Name: new_cases, dtype: float64
111413 111420    763.0
Name: new_cases, dtype: float64
111414 111421    729.0
Name: new_cases, dtype: float64
111415 111422    887.0
Name: new_cases, dtype: float64
111416 111423    791.0
Name: new_cases, dtype: float64
111417 111424    759.0
Name: new_cases, dtype: float64
111418 111425    631.0
Name: new_cases, dtype: float64
111419 111426    502.0
Name: new_cases, dtype: float64
111420 111427    550.0
Name: new_cases, dtype: float64
111421 111428    595.0
Name: new_cases, dtype: float64
111422 111429    612.0
Name: new_cases, dtype: float64
111423 111430    691.0
Name: new_cases, dtype: float64
111424 111431    567.0
Name: new_cases, dtype: float64
111425 111432    437.0
Name: new_cases, dtype: float64
111426 111433    302.0
Name: new_cases, dtype: float64
111427 111434    400.0
Name: new_cases, dtype: float64
111428 111435    421.0
Name: new_cases, dtype: float64
111429 111436    506.0
Name: new_cases, dtype: float64
111430 111437    594.0
Name: new_cases, dtype: float64
111431 111438    603.0
Name: new_cases, dtype: float64
111432 111439    502.0
Name: new_cases, dtype: float64
111433 111440    377.0
Name: new_cases, dtype: float64
111434 111441    605.0
Name: new_cases, dtype: float64
111435 111442    600.0
Name: new_cases, dtype: float64
111436 111443    837.0
Name: new_cases, dtype: float64
111437 111444    757.0
Name: new_cases, dtype: float64
111438 111445    1002.0
Name: new_cases, dtype: float64
111439 111446    910.0
Name: new_cases, dtype: float64
111440 111447    748.0
Name: new_cases, dtype: float64
111441 111448    711.0
Name: new_cases, dtype: float64
111442 111449    974.0
Name: new_cases, dtype: float64
111443 111450    1136.0
Name: new_cases, dtype: float64
111444 111451    1587.0
Name: new_cases, dtype: float64
111445 111452    1584.0
Name: new_cases, dtype: float64
111446 111453    1350.0
Name: new_cases, dtype: float64
111447 111454    1306.0
Name: new_cases, dtype: float64
111448 111455    1326.0
Name: new_cases, dtype: float64
111449 111456    1552.0
Name: new_cases, dtype: float64
111450 111457    1967.0
Name: new_cases, dtype: float64
111451 111458    2292.0
Name: new_cases, dtype: float64
111452 111459    2367.0
Name: new_cases, dtype: float64
111453 111460    1934.0
Name: new_cases, dtype: float64
111454 111461    2006.0
Name: new_cases, dtype: float64
111455 111462    2236.0
Name: new_cases, dtype: float64
111456 111463    3003.0
Name: new_cases, dtype: float64
111457 111464    4280.0
Name: new_cases, dtype: float64
111458 111465    4739.0
Name: new_cases, dtype: float64
111459 111466    5300.0
Name: new_cases, dtype: float64
111460 111467    4178.0
Name: new_cases, dtype: float64
111461 111468    4394.0
Name: new_cases, dtype: float64
111462 111469    5068.0
Name: new_cases, dtype: float64
111463 111470    6526.0
Name: new_cases, dtype: float64
111464 111471    8099.0
Name: new_cases, dtype: float64
111465 111472    7705.0
Name: new_cases, dtype: float64
111466 111473    9622.0
Name: new_cases, dtype: float64
111467 111474    8536.0
Name: new_cases, dtype: float64
111468 111475    7482.0
Name: new_cases, dtype: float64
111469 111476    9291.0
Name: new_cases, dtype: float64
111470 111477    10040.0
Name: new_cases, dtype: float64
111471 111478    12107.0
Name: new_cases, dtype: float64
111472 111479    13632.0
Name: new_cases, dtype: float64
111473 111480    13628.0
Name: new_cases, dtype: float64
111474 111481    11742.0
Name: new_cases, dtype: float64
111475 111482    10241.0
Name: new_cases, dtype: float64
111476 111483    16300.0
Name: new_cases, dtype: float64
111477 111484    18820.0
Name: new_cases, dtype: float64
111478 111485    20156.0
Name: new_cases, dtype: float64
111479 111486    21629.0
Name: new_cases, dtype: float64
111480 111487    21897.0
Name: new_cases, dtype: float64
111481 111488    17171.0
Name: new_cases, dtype: float64
111482 111489    15578.0
Name: new_cases, dtype: float64
111483 111490    19364.0
Name: new_cases, dtype: float64
111484 111491    24692.0
Name: new_cases, dtype: float64
111485 111492    27143.0
Name: new_cases, dtype: float64
111486 111493    27086.0
Name: new_cases, dtype: float64
111487 111494    27875.0
Name: new_cases, dtype: float64
111488 111495    24785.0
Name: new_cases, dtype: float64
111489 111496    21713.0
Name: new_cases, dtype: float64
111490 111497    25454.0
Name: new_cases, dtype: float64
111491 111498    25221.0
Name: new_cases, dtype: float64
111492 111499    22683.0
Name: new_cases, dtype: float64
111493 111500    24051.0
Name: new_cases, dtype: float64
111494 111501    25571.0
Name: new_cases, dtype: float64
111495 111502    21854.0
Name: new_cases, dtype: float64
111496 111503    20816.0
Name: new_cases, dtype: float64
111497 111504    19152.0
Name: new_cases, dtype: float64
111498 111505    19883.0
Name: new_cases, dtype: float64
111499 111506    23975.0
Name: new_cases, dtype: float64
111500 111507    22464.0
Name: new_cases, dtype: float64
111501 111508    24213.0
Name: new_cases, dtype: float64
111502 111509    17856.0
Name: new_cases, dtype: float64
111503 111510    15002.0
Name: new_cases, dtype: float64
111504 111511    32733.0
Name: new_cases, dtype: float64
111505 111512    15356.0
Name: new_cases, dtype: float64
111506 111513    16690.0
Name: new_cases, dtype: float64
111507 111514    17304.0
Name: new_cases, dtype: float64
111508 111515    15177.0
Name: new_cases, dtype: float64
111509 111516    11482.0
Name: new_cases, dtype: float64
111510 111517    5736.0
Name: new_cases, dtype: float64
111511 111518    9113.0
Name: new_cases, dtype: float64
111512 111519    13823.0
Name: new_cases, dtype: float64
111513 111520    14863.0
Name: new_cases, dtype: float64
111514 111521    13236.0
Name: new_cases, dtype: float64
111515 111522    12427.0
Name: new_cases, dtype: float64
111516 111523    9176.0
Name: new_cases, dtype: float64
111517 111524    4421.0
Name: new_cases, dtype: float64
111518 111525    8310.0
Name: new_cases, dtype: float64
111519 111526    12166.0
Name: new_cases, dtype: float64
111520 111527    13750.0
Name: new_cases, dtype: float64
111521 111528    13105.0
Name: new_cases, dtype: float64

111522 111529    11499.0
Name: new_cases, dtype: float64
111523 111530    8976.0
Name: new_cases, dtype: float64
111524 111531    4896.0
Name: new_cases, dtype: float64
111525 111532    6874.0
Name: new_cases, dtype: float64
111526 111533    12455.0
Name: new_cases, dtype: float64
111527 111534    11953.0
Name: new_cases, dtype: float64
111528 111535    11010.0
Name: new_cases, dtype: float64
111529 111536    11246.0
Name: new_cases, dtype: float64
111530 111537    8590.0
Name: new_cases, dtype: float64
111531 111538    4633.0
Name: new_cases, dtype: float64
111532 111539    7192.0
Name: new_cases, dtype: float64
111533 111540    12358.0
Name: new_cases, dtype: float64
111534 111541    13115.0
Name: new_cases, dtype: float64
111535 111542    9081.0
Name: new_cases, dtype: float64
111536 111543    4878.0
Name: new_cases, dtype: float64
111537 111544    3842.0
Name: new_cases, dtype: float64
111538 111545    3211.0
Name: new_cases, dtype: float64
111539 111546    7624.0
Name: new_cases, dtype: float64
111540 111547    12780.0
Name: new_cases, dtype: float64
111541 111548    13464.0
Name: new_cases, dtype: float64
111542 111549    10896.0
Name: new_cases, dtype: float64
111543 111550    7006.0
Name: new_cases, dtype: float64
111544 111551    5782.0
Name: new_cases, dtype: float64
111545 111552    4385.0
Name: new_cases, dtype: float64
111546 111553    7596.0
Name: new_cases, dtype: float64
111547 111554    14220.0
Name: new_cases, dtype: float64
111548 111555    12119.0
Name: new_cases, dtype: float64
111549 111556    8763.0
Name: new_cases, dtype: float64
111550 111557    10744.0
Name: new_cases, dtype: float64
111551 111558    9133.0
Name: new_cases, dtype: float64
111552 111559    4863.0
Name: new_cases, dtype: float64
111553 111560    5394.0
Name: new_cases, dtype: float64
111554 111561    9126.0
Name: new_cases, dtype: float64
111555 111562    9457.0
Name: new_cases, dtype: float64
111556 111563    7958.0
Name: new_cases, dtype: float64
111557 111564    7292.0
Name: new_cases, dtype: float64
111558 111565    5970.0
Name: new_cases, dtype: float64
111559 111566    3332.0
Name: new_cases, dtype: float64
111560 111567    4890.0
Name: new_cases, dtype: float64
111561 111568    6943.0
Name: new_cases, dtype: float64
111562 111569    7008.0
Name: new_cases, dtype: float64
111563 111570    6693.0
Name: new_cases, dtype: float64
111564 111571    6431.0
Name: new_cases, dtype: float64
111565 111572    4566.0
Name: new_cases, dtype: float64
111566 111573    2674.0
Name: new_cases, dtype: float64
111567 111574    4603.0
Name: new_cases, dtype: float64
111568 111575    6790.0
Name: new_cases, dtype: float64
111569 111576    7153.0
Name: new_cases, dtype: float64
111570 111577    6145.0
Name: new_cases, dtype: float64
111571 111578    5864.0
Name: new_cases, dtype: float64
111572 111579    4711.0
Name: new_cases, dtype: float64
111573 111580    2504.0
Name: new_cases, dtype: float64
111574 111581    4326.0
Name: new_cases, dtype: float64
111575 111582    6801.0
Name: new_cases, dtype: float64
111576 111583    6495.0
Name: new_cases, dtype: float64
111577 111584    6053.0
Name: new_cases, dtype: float64
111578 111585    5966.0
Name: new_cases, dtype: float64
111579 111586    4725.0
Name: new_cases, dtype: float64
111580 111587    2431.0
Name: new_cases, dtype: float64
111581 111588    3999.0
Name: new_cases, dtype: float64
111582 111589    6960.0
Name: new_cases, dtype: float64
111583 111590    7013.0
Name: new_cases, dtype: float64
111584 111591    6378.0
Name: new_cases, dtype: float64
111585 111592    6585.0
Name: new_cases, dtype: float64
111586 111593    5334.0
Name: new_cases, dtype: float64
111587 111594    2542.0
Name: new_cases, dtype: float64
111588 111595    5176.0
Name: new_cases, dtype: float64
111589 111596    8699.0
Name: new_cases, dtype: float64
111590 111597    9074.0
Name: new_cases, dtype: float64
111591 111598    8772.0
Name: new_cases, dtype: float64
111592 111599    8509.0
Name: new_cases, dtype: float64
111593 111600    7040.0
Name: new_cases, dtype: float64
111594 111601    3891.0
Name: new_cases, dtype: float64
111595 111602    6304.0
Name: new_cases, dtype: float64
111596 111603    12147.0
Name: new_cases, dtype: float64
111597 111604    12143.0
Name: new_cases, dtype: float64
111598 111605    11536.0
Name: new_cases, dtype: float64
111599 111606    12097.0
Name: new_cases, dtype: float64
111600 111607    10101.0
Name: new_cases, dtype: float64
111601 111608    4786.0
Name: new_cases, dtype: float64
111602 111609    7936.0
Name: new_cases, dtype: float64
111603 111610    15698.0
Name: new_cases, dtype: float64
111604 111611    15253.0
Name: new_cases, dtype: float64
111605 111612    15831.0
Name: new_cases, dtype: float64
111606 111613    14855.0
Name: new_cases, dtype: float64
111607 111614    13569.0
Name: new_cases, dtype: float64
111608 111615    6169.0
Name: new_cases, dtype: float64
111609 111616    9953.0
Name: new_cases, dtype: float64
111610 111617    17277.0
Name: new_cases, dtype: float64
111611 111618    21111.0
Name: new_cases, dtype: float64
111612 111619    18873.0
Name: new_cases, dtype: float64
111613 111620    21063.0
Name: new_cases, dtype: float64
111614 111621    17272.0
Name: new_cases, dtype: float64
111615 111622    10895.0
Name: new_cases, dtype: float64
111616 111623    14394.0
Name: new_cases, dtype: float64
111617 111624    25053.0
Name: new_cases, dtype: float64
111618 111625    27274.0
Name: new_cases, dtype: float64
111619 111626    25996.0
Name: new_cases, dtype: float64
111620 111627    26456.0
Name: new_cases, dtype: float64
111621 111628    21850.0
Name: new_cases, dtype: float64
111622 111629    14579.0
Name: new_cases, dtype: float64
111623 111630    16740.0
Name: new_cases, dtype: float64
111624 111631    30802.0
Name: new_cases, dtype: float64
111625 111632    34150.0
Name: new_cases, dtype: float64
111626 111633    35145.0
Name: new_cases, dtype: float64
111627 111634    31759.0
Name: new_cases, dtype: float64
111628 111635    29266.0
Name: new_cases, dtype: float64
111629 111636    16973.0
Name: new_cases, dtype: float64
111630 111637    20862.0
Name: new_cases, dtype: float64
111631 111638    32891.0
Name: new_cases, dtype: float64
111632 111639    35253.0
Name: new_cases, dtype: float64
111633 111640    30541.0
Name: new_cases, dtype: float64
111634 111641    28073.0
Name: new_cases, dtype: float64
111635 111642    22958.0
Name: new_cases, dtype: float64
111636 111643    9921.0
Name: new_cases, dtype: float64
111637 111644    8246.0
Name: new_cases, dtype: float64
111638 111645    14908.0
Name: new_cases, dtype: float64
111639 111646    27890.0
Name: new_cases, dtype: float64
111640 111647    28499.0
Name: new_cases, dtype: float64
111641 111648    24892.0
Name: new_cases, dtype: float64
111642 111649    21733.0
Name: new_cases, dtype: float64
111643 111650    12016.0
Name: new_cases, dtype: float64
111644 111651    13203.0
Name: new_cases, dtype: float64
111645 111652    21266.0
Name: new_cases, dtype: float64
111646 111653    21126.0
Name: new_cases, dtype: float64
111647 111654    17846.0
Name: new_cases, dtype: float64
111648 111655    15786.0
Name: new_cases, dtype: float64
111649 111656    12151.0
Name: new_cases, dtype: float64
111650 111657    7302.0
Name: new_cases, dtype: float64
111651 111658    9244.0
Name: new_cases, dtype: float64
111652 111659    13922.0
Name: new_cases, dtype: float64
111653 111660    12763.0
Name: new_cases, dtype: float64
111654 111661    10866.0
Name: new_cases, dtype: float64
111655 111662    9510.0
Name: new_cases, dtype: float64
111656 111663    7224.0
Name: new_cases, dtype: float64
111657 111664    3467.0
Name: new_cases, dtype: float64
111658 111665    5711.0
Name: new_cases, dtype: float64
111659 111666    8893.0
Name: new_cases, dtype: float64
111660 111667    8426.0
Name: new_cases, dtype: float64
111661 111668    6789.0
Name: new_cases, dtype: float64
111662 111669    6475.0
Name: new_cases, dtype: float64
111663 111670    4616.0
Name: new_cases, dtype: float64
111664 111671    2523.0
Name: new_cases, dtype: float64
111665 111672    2296.0
Name: new_cases, dtype: float64
111666 111673    3899.0
Name: new_cases, dtype: float64
111667 111674    6427.0
Name: new_cases, dtype: float64
111668 111675    6047.0
Name: new_cases, dtype: float64
111669 111676    4771.0
Name: new_cases, dtype: float64
111670 111677    3856.0
Name: new_cases, dtype: float64
111671 111678    2031.0
Name: new_cases, dtype: float64
111672 111679    3097.0
Name: new_cases, dtype: float64
111673 111680    4159.0
Name: new_cases, dtype: float64
111674 111681    3423.0
Name: new_cases, dtype: float64
111675 111682    3252.0
Name: new_cases, dtype: float64
111676 111683    2897.0
Name: new_cases, dtype: float64
111677 111684    2168.0
Name: new_cases, dtype: float64
111678 111685    1111.0
Name: new_cases, dtype: float64
111679 111686    1734.0
Name: new_cases, dtype: float64
111680 111687    2337.0
Name: new_cases, dtype: float64
111681 111688    2090.0
Name: new_cases, dtype: float64
111682 111689    1680.0
Name: new_cases, dtype: float64
111683 111690    1515.0
Name: new_cases, dtype: float64
111684 111691    1076.0
Name: new_cases, dtype: float64
111685 111692    559.0
Name: new_cases, dtype: float64
111686 111693    1006.0
Name: new_cases, dtype: float64
111687 111694    1263.0
Name: new_cases, dtype: float64

111688 111695    1202.0
Name: new_cases, dtype: float64
111689 111696    943.0
Name: new_cases, dtype: float64
111690 111697    776.0
Name: new_cases, dtype: float64
111691 111698    579.0
Name: new_cases, dtype: float64
111692 111699    333.0
Name: new_cases, dtype: float64
111693 111700    585.0
Name: new_cases, dtype: float64
111694 111701    659.0
Name: new_cases, dtype: float64
111695 111702    565.0
Name: new_cases, dtype: float64
111696 111703    319.0
Name: new_cases, dtype: float64
111697 111704    413.0
Name: new_cases, dtype: float64
111698 111705    312.0
Name: new_cases, dtype: float64
111699 111706    192.0
Name: new_cases, dtype: float64
111700 111707    401.0
Name: new_cases, dtype: float64
111701 111708    560.0
Name: new_cases, dtype: float64
111702 111709    378.0
Name: new_cases, dtype: float64
111703 111710    340.0
Name: new_cases, dtype: float64
111704 111711    236.0
Name: new_cases, dtype: float64
111705 111712    226.0
Name: new_cases, dtype: float64
111706 111713    139.0
Name: new_cases, dtype: float64
111707 111714    211.0
Name: new_cases, dtype: float64
111708 111715    242.0
Name: new_cases, dtype: float64
111709 111716    215.0
Name: new_cases, dtype: float64
111710 111717    190.0
Name: new_cases, dtype: float64
111711 111718    168.0
Name: new_cases, dtype: float64
111712 111719    133.0
Name: new_cases, dtype: float64
111713 111720    73.0
Name: new_cases, dtype: float64
111714 111721    190.0
Name: new_cases, dtype: float64
111715 111722    162.0
Name: new_cases, dtype: float64
111716 111723    144.0
Name: new_cases, dtype: float64
111717 111724    134.0
Name: new_cases, dtype: float64
111718 111725    99.0
Name: new_cases, dtype: float64
111719 111726    69.0
Name: new_cases, dtype: float64
111720 111727    51.0
Name: new_cases, dtype: float64
111721 111728    122.0
Name: new_cases, dtype: float64
111722 111729    101.0
Name: new_cases, dtype: float64
111723 111730    98.0
Name: new_cases, dtype: float64
111724 111731    97.0
Name: new_cases, dtype: float64
111725 111732    108.0
Name: new_cases, dtype: float64
111726 111733    55.0
Name: new_cases, dtype: float64
111727 111734    38.0
Name: new_cases, dtype: float64
111728 111735    95.0
Name: new_cases, dtype: float64
111729 111736    100.0
Name: new_cases, dtype: float64
111730 111737    93.0
Name: new_cases, dtype: float64
111731 111738    74.0
Name: new_cases, dtype: float64
111732 111739    85.0
Name: new_cases, dtype: float64
111733 111740    66.0
Name: new_cases, dtype: float64
111734 111741    44.0
Name: new_cases, dtype: float64
111735 111742    94.0
Name: new_cases, dtype: float64
111736 111743    87.0
Name: new_cases, dtype: float64
111737 111744    105.0
Name: new_cases, dtype: float64
111738 111745    90.0
Name: new_cases, dtype: float64
111739 111746    114.0
Name: new_cases, dtype: float64
111740 111747    69.0
Name: new_cases, dtype: float64
111741 111748    67.0
Name: new_cases, dtype: float64
111742 111749    103.0
Name: new_cases, dtype: float64
111743 111750    124.0
Name: new_cases, dtype: float64
111744 111751    122.0
Name: new_cases, dtype: float64
111745 111752    108.0
Name: new_cases, dtype: float64
111746 111753    118.0
Name: new_cases, dtype: float64
111747 111754    80.0
Name: new_cases, dtype: float64
111748 111755    74.0
Name: new_cases, dtype: float64
111749 111756    107.0
Name: new_cases, dtype: float64
111750 111757    138.0
Name: new_cases, dtype: float64
111751 111758    165.0
Name: new_cases, dtype: float64
111752 111759    156.0
Name: new_cases, dtype: float64
111753 111760    153.0
Name: new_cases, dtype: float64
111754 111761    90.0
Name: new_cases, dtype: float64
111755 111762    91.0
Name: new_cases, dtype: float64
111756 111763    164.0
Name: new_cases, dtype: float64
111757 111764    164.0
Name: new_cases, dtype: float64
111758 111765    176.0
Name: new_cases, dtype: float64
111759 111766    172.0
Name: new_cases, dtype: float64
111760 111767    180.0
Name: new_cases, dtype: float64
111761 111768    122.0
Name: new_cases, dtype: float64
111762 111769    64.0
Name: new_cases, dtype: float64
111763 111770    199.0
Name: new_cases, dtype: float64
111764 111771    196.0
Name: new_cases, dtype: float64
111765 111772    223.0
Name: new_cases, dtype: float64
111766 111773    194.0
Name: new_cases, dtype: float64
111767 111774    211.0
Name: new_cases, dtype: float64
111768 111775    148.0
Name: new_cases, dtype: float64
111769 111776    128.0
Name: new_cases, dtype: float64
111770 111777    215.0
Name: new_cases, dtype: float64
111771 111778    207.0
Name: new_cases, dtype: float64
111772 111779    196.0
Name: new_cases, dtype: float64
111773 111780    212.0
Name: new_cases, dtype: float64
111774 111781    222.0
Name: new_cases, dtype: float64
111775 111782    185.0
Name: new_cases, dtype: float64
111776 111783    107.0
Name: new_cases, dtype: float64
111777 111784    232.0
Name: new_cases, dtype: float64
111778 111785    233.0
Name: new_cases, dtype: float64
111779 111786    215.0
Name: new_cases, dtype: float64
111780 111787    254.0
Name: new_cases, dtype: float64
111781 111788    289.0
Name: new_cases, dtype: float64
111782 111789    203.0
Name: new_cases, dtype: float64
111783 111790    154.0
Name: new_cases, dtype: float64
111784 111791    285.0
Name: new_cases, dtype: float64
111785 111792    366.0
Name: new_cases, dtype: float64
111786 111793    376.0
Name: new_cases, dtype: float64
111787 111794    361.0
Name: new_cases, dtype: float64
111788 111795    388.0
Name: new_cases, dtype: float64
111789 111796    323.0
Name: new_cases, dtype: float64
111790 111797    182.0
Name: new_cases, dtype: float64
111791 111798    405.0
Name: new_cases, dtype: float64
111792 111799    531.0
Name: new_cases, dtype: float64
111793 111800    511.0
Name: new_cases, dtype: float64
111794 111801    529.0
Name: new_cases, dtype: float64
111795 111802    531.0
Name: new_cases, dtype: float64
111796 111803    476.0
Name: new_cases, dtype: float64
111797 111804    270.0
Name: new_cases, dtype: float64
111798 111805    536.0
Name: new_cases, dtype: float64
111799 111806    768.0
Name: new_cases, dtype: float64
111800 111807    724.0
Name: new_cases, dtype: float64
111801 111808    652.0
Name: new_cases, dtype: float64
111802 111809    796.0
Name: new_cases, dtype: float64
111803 111810    540.0
Name: new_cases, dtype: float64
111804 111811    364.0
Name: new_cases, dtype: float64
111805 111812    709.0
Name: new_cases, dtype: float64
111806 111813    880.0
Name: new_cases, dtype: float64
111807 111814    974.0
Name: new_cases, dtype: float64
111808 111815    812.0
Name: new_cases, dtype: float64
111809 111816    917.0
Name: new_cases, dtype: float64
111810 111817    643.0
Name: new_cases, dtype: float64
111811 111818    421.0
Name: new_cases, dtype: float64
111812 111819    976.0
Name: new_cases, dtype: float64
111813 111820    1235.0
Name: new_cases, dtype: float64
111814 111821    1205.0
Name: new_cases, dtype: float64
111815 111822    1361.0
Name: new_cases, dtype: float64
111816 111823    1344.0
Name: new_cases, dtype: float64
111817 111824    1090.0
Name: new_cases, dtype: float64
111818 111825    683.0
Name: new_cases, dtype: float64
111819 111826    1327.0
Name: new_cases, dtype: float64
111820 111827    2086.0
Name: new_cases, dtype: float64
111821 111828    2007.0
Name: new_cases, dtype: float64
111822 111829    1894.0
Name: new_cases, dtype: float64
111823 111830    2011.0
Name: new_cases, dtype: float64
111824 111831    1527.0
Name: new_cases, dtype: float64
111825 111832    903.0
Name: new_cases, dtype: float64
111826 111833    2121.0
Name: new_cases, dtype: float64
111827 111834    2640.0
Name: new_cases, dtype: float64
111828 111835    2999.0
Name: new_cases, dtype: float64
111829 111836    2770.0
Name: new_cases, dtype: float64
111830 111837    3235.0
Name: new_cases, dtype: float64
111831 111838    2521.0
Name: new_cases, dtype: float64
111832 111839    1536.0
Name: new_cases, dtype: float64
111833 111840    3930.0
Name: new_cases, dtype: float64
111834 111841    5560.0
Name: new_cases, dtype: float64
111835 111842    5591.0
Name: new_cases, dtype: float64
111836 111843    5716.0
Name: new_cases, dtype: float64
111837 111844    6277.0
Name: new_cases, dtype: float64
111838 111845    4727.0
Name: new_cases, dtype: float64
111839 111846    2953.0
Name: new_cases, dtype: float64
111840 111847    6263.0
Name: new_cases, dtype: float64
111841 111848    8366.0
Name: new_cases, dtype: float64
111842 111849    8382.0
Name: new_cases, dtype: float64
111843 111850    9403.0
Name: new_cases, dtype: float64
111844 111851    9806.0
Name: new_cases, dtype: float64
111845 111852    7147.0
Name: new_cases, dtype: float64
111846 111853    4904.0
Name: new_cases, dtype: float64
111847 111854    4517.0
Name: new_cases, dtype: float64
111848 111855    10434.0
Name: new_cases, dtype: float64

111849 111856    15511.0
Name: new_cases, dtype: float64
111850 111857    15905.0
Name: new_cases, dtype: float64
111851 111858    15195.0
Name: new_cases, dtype: float64
111852 111859    12507.0
Name: new_cases, dtype: float64
111853 111860    7314.0
Name: new_cases, dtype: float64
111854 111861    13645.0
Name: new_cases, dtype: float64
111855 111862    18546.0
Name: new_cases, dtype: float64
111856 111863    19079.0
Name: new_cases, dtype: float64
111857 111864    12965.0
Name: new_cases, dtype: float64
111858 111865    14298.0
Name: new_cases, dtype: float64
111859 111866    14448.0
Name: new_cases, dtype: float64
111860 111867    9508.0
Name: new_cases, dtype: float64
111861 111868    16611.0
Name: new_cases, dtype: float64
111862 111869    24241.0
Name: new_cases, dtype: float64
111863 111870    24912.0
Name: new_cases, dtype: float64
111864 111871    23259.0
Name: new_cases, dtype: float64
111865 111872    23418.0
Name: new_cases, dtype: float64
111866 111873    18924.0
Name: new_cases, dtype: float64
111867 111874    12375.0
Name: new_cases, dtype: float64
111868 111875    19935.0
Name: new_cases, dtype: float64
111869 111876    28431.0
Name: new_cases, dtype: float64
111870 111877    28143.0
Name: new_cases, dtype: float64
111871 111878    26794.0
Name: new_cases, dtype: float64
111872 111879    26188.0
Name: new_cases, dtype: float64
111873 111880    20574.0
Name: new_cases, dtype: float64
111874 111881    13133.0
Name: new_cases, dtype: float64
111875 111882    19100.0
Name: new_cases, dtype: float64
111876 111883    29076.0
Name: new_cases, dtype: float64
111877 111884    27354.0
Name: new_cases, dtype: float64
111878 111885    26961.0
Name: new_cases, dtype: float64
111879 111886    25575.0
Name: new_cases, dtype: float64
111880 111887    22394.0
Name: new_cases, dtype: float64
111881 111888    13250.0
Name: new_cases, dtype: float64
111882 111889    19369.0
Name: new_cases, dtype: float64
111883 111890    28549.0
Name: new_cases, dtype: float64
111884 111891    27459.0
Name: new_cases, dtype: float64
111885 111892    24988.0
Name: new_cases, dtype: float64
111886 111893    23762.0
Name: new_cases, dtype: float64
111887 111894    19450.0
Name: new_cases, dtype: float64
111888 111895    11377.0
Name: new_cases, dtype: float64
111889 111896    17460.0
Name: new_cases, dtype: float64
111890 111897    24264.0
Name: new_cases, dtype: float64
111891 111898    22096.0
Name: new_cases, dtype: float64
111892 111899    20027.0
Name: new_cases, dtype: float64
111893 111900    19392.0
Name: new_cases, dtype: float64
111894 111901    15976.0
Name: new_cases, dtype: float64
111895 111902    9610.0
Name: new_cases, dtype: float64
111896 111903    13807.0
Name: new_cases, dtype: float64
111897 111904    18013.0
Name: new_cases, dtype: float64
111898 111905    17150.0
Name: new_cases, dtype: float64
111899 111906    15376.0
Name: new_cases, dtype: float64
111900 111907    10789.0
Name: new_cases, dtype: float64
111901 111908    6253.0
Name: new_cases, dtype: float64
111902 111909    5027.0
Name: new_cases, dtype: float64
111903 111910    9850.0
Name: new_cases, dtype: float64
111904 111911    15567.0
Name: new_cases, dtype: float64
111905 111912    14326.0
Name: new_cases, dtype: float64
111906 111913    13607.0
Name: new_cases, dtype: float64
111907 111914    12033.0
Name: new_cases, dtype: float64
111908 111915    7180.0
Name: new_cases, dtype: float64
111909 111916    6423.0
Name: new_cases, dtype: float64
111910 111917    11667.0
Name: new_cases, dtype: float64
111911 111918    17197.0
Name: new_cases, dtype: float64
111912 111919    16577.0
Name: new_cases, dtype: float64
111913 111920    11901.0
Name: new_cases, dtype: float64
111914 111921    10897.0
Name: new_cases, dtype: float64
111915 Series([], Name: new_cases, dtype: float64)
111916 Series([], Name: new_cases, dtype: float64)
111917 111246    1.0
Name: new_cases, dtype: float64
111918 111247    0.0
Name: new_cases, dtype: float64
111919 111248    4.0
Name: new_cases, dtype: float64
111920 111249    0.0
Name: new_cases, dtype: float64
111921 111250    6.0
Name: new_cases, dtype: float64
111930 111937    0.0
Name: new_cases, dtype: float64
111931 111938    11.0
Name: new_cases, dtype: float64
111932 111939    18.0
Name: new_cases, dtype: float64
111933 111940    0.0
Name: new_cases, dtype: float64
111934 111941    53.0
Name: new_cases, dtype: float64
111935 111942    57.0
Name: new_cases, dtype: float64
111936 111943    76.0
Name: new_cases, dtype: float64
111937 111944    86.0
Name: new_cases, dtype: float64
111938 111945    117.0
Name: new_cases, dtype: float64
111939 111946    0.0
Name: new_cases, dtype: float64
111940 111947    337.0
Name: new_cases, dtype: float64
111941 111948    235.0
Name: new_cases, dtype: float64
111942 111949    260.0
Name: new_cases, dtype: float64
111943 111950    320.0
Name: new_cases, dtype: float64
111944 111951    460.0
Name: new_cases, dtype: float64
111945 111952    302.0
Name: new_cases, dtype: float64
111946 111953    633.0
Name: new_cases, dtype: float64
111947 111954    549.0
Name: new_cases, dtype: float64
111948 111955    724.0
Name: new_cases, dtype: float64
111949 111956    902.0
Name: new_cases, dtype: float64
111950 111957    792.0
Name: new_cases, dtype: float64
111951 111958    446.0
Name: new_cases, dtype: float64
111952 111959    1035.0
Name: new_cases, dtype: float64
111953 111960    808.0
Name: new_cases, dtype: float64
111954 111961    783.0
Name: new_cases, dtype: float64
111955 111962    852.0
Name: new_cases, dtype: float64
111956 111963    638.0
Name: new_cases, dtype: float64
111957 111964    754.0
Name: new_cases, dtype: float64
111958 111965    452.0
Name: new_cases, dtype: float64
111959 111966    712.0
Name: new_cases, dtype: float64
111960 111967    699.0
Name: new_cases, dtype: float64
111961 111968    815.0
Name: new_cases, dtype: float64
111962 111969    1516.0
Name: new_cases, dtype: float64
111963 111970    515.0
Name: new_cases, dtype: float64
111964 111971    598.0
Name: new_cases, dtype: float64
111965 111972    349.0
Name: new_cases, dtype: float64
111966 111973    514.0
Name: new_cases, dtype: float64
111967 111974    643.0
Name: new_cases, dtype: float64
111968 111975    750.0
Name: new_cases, dtype: float64
111969 111976    181.0
Name: new_cases, dtype: float64
111970 111977    663.0
Name: new_cases, dtype: float64
111971 111978    521.0
Name: new_cases, dtype: float64
111972 111979    657.0
Name: new_cases, dtype: float64
111973 111980    516.0
Name: new_cases, dtype: float64
111974 111981    603.0
Name: new_cases, dtype: float64
111975 111982    371.0
Name: new_cases, dtype: float64
111976 111983    444.0
Name: new_cases, dtype: float64
111977 111984    595.0
Name: new_cases, dtype: float64
111978 111985    472.0
Name: new_cases, dtype: float64
111979 111986    163.0
Name: new_cases, dtype: float64
111980 111987    295.0
Name: new_cases, dtype: float64
111981 111988    183.0
Name: new_cases, dtype: float64
111982 111989    540.0
Name: new_cases, dtype: float64
111983 111990    306.0
Name: new_cases, dtype: float64
111984 111991   -161.0
Name: new_cases, dtype: float64
111985 111992    92.0
Name: new_cases, dtype: float64
111986 111993    242.0
Name: new_cases, dtype: float64
111987 111994    178.0
Name: new_cases, dtype: float64
111988 111995    480.0
Name: new_cases, dtype: float64
111989 111996    533.0
Name: new_cases, dtype: float64
111990 111997    553.0
Name: new_cases, dtype: float64
111991 111998    138.0
Name: new_cases, dtype: float64
111992 111999    175.0
Name: new_cases, dtype: float64
111993 112000    98.0
Name: new_cases, dtype: float64
111994 112001    234.0
Name: new_cases, dtype: float64
111995 112002    219.0
Name: new_cases, dtype: float64
111996 112003    187.0
Name: new_cases, dtype: float64
111997 112004    264.0
Name: new_cases, dtype: float64
111998 112005    227.0
Name: new_cases, dtype: float64
111999 112006    226.0
Name: new_cases, dtype: float64
112000 112007    173.0
Name: new_cases, dtype: float64
112001 112008    223.0
Name: new_cases, dtype: float64
112002 112009    228.0
Name: new_cases, dtype: float64
112003 112010    252.0
Name: new_cases, dtype: float64
112004 112011    288.0
Name: new_cases, dtype: float64
112005 112012    271.0
Name: new_cases, dtype: float64
112006 112013    152.0
Name: new_cases, dtype: float64
112007 112014    165.0
Name: new_cases, dtype: float64
112008 112015    219.0
Name: new_cases, dtype: float64
112009 112016    285.0
Name: new_cases, dtype: float64
112010 112017    304.0
Name: new_cases, dtype: float64
112011 112018    350.0
Name: new_cases, dtype: float64
112012 112019    257.0
Name: new_cases, dtype: float64
112013 112020    297.0
Name: new_cases, dtype: float64
112014 112021    200.0
Name: new_cases, dtype: float64
112015 112022    195.0
Name: new_cases, dtype: float64
112016 112023    366.0
Name: new_cases, dtype: float64
112017 112024    331.0
Name: new_cases, dtype: float64
112018 112025    377.0
Name: new_cases, dtype: float64
112019 112026    382.0
Name: new_cases, dtype: float64
112020 112027    342.0
Name: new_cases, dtype: float64
112021 112028    192.0
Name: new_cases, dtype: float64
112022 112029    421.0
Name: new_cases, dtype: float64

112023 112030    294.0
Name: new_cases, dtype: float64
112024 112031    310.0
Name: new_cases, dtype: float64
112025 112032    270.0
Name: new_cases, dtype: float64
112026 112033    283.0
Name: new_cases, dtype: float64
112027 112034    227.0
Name: new_cases, dtype: float64
112028 112035    346.0
Name: new_cases, dtype: float64
112029 112036    300.0
Name: new_cases, dtype: float64
112030 112037    336.0
Name: new_cases, dtype: float64
112031 112038    417.0
Name: new_cases, dtype: float64
112032 112039    375.0
Name: new_cases, dtype: float64
112033 112040    377.0
Name: new_cases, dtype: float64
112034 112041    292.0
Name: new_cases, dtype: float64
112035 112042    259.0
Name: new_cases, dtype: float64
112036 112043    345.0
Name: new_cases, dtype: float64
112037 112044    367.0
Name: new_cases, dtype: float64
112038 112045    311.0
Name: new_cases, dtype: float64
112039 112046    451.0
Name: new_cases, dtype: float64
112040 112047    323.0
Name: new_cases, dtype: float64
112041 112048    457.0
Name: new_cases, dtype: float64
112042 112049    266.0
Name: new_cases, dtype: float64
112043 112050    229.0
Name: new_cases, dtype: float64
112044 112051    313.0
Name: new_cases, dtype: float64
112045 112052    328.0
Name: new_cases, dtype: float64
112046 112053    374.0
Name: new_cases, dtype: float64
112047 112054    413.0
Name: new_cases, dtype: float64
112048 112055    328.0
Name: new_cases, dtype: float64
112049 112056    232.0
Name: new_cases, dtype: float64
112050 112057    287.0
Name: new_cases, dtype: float64
112051 112058    443.0
Name: new_cases, dtype: float64
112052 112059    418.0
Name: new_cases, dtype: float64
112053 112060    402.0
Name: new_cases, dtype: float64
112054 112061    542.0
Name: new_cases, dtype: float64
112055 112062    291.0
Name: new_cases, dtype: float64
112056 112063    306.0
Name: new_cases, dtype: float64
112057 112064    233.0
Name: new_cases, dtype: float64
112058 112065    375.0
Name: new_cases, dtype: float64
112059 112066    339.0
Name: new_cases, dtype: float64
112060 112067    312.0
Name: new_cases, dtype: float64
112061 112068    313.0
Name: new_cases, dtype: float64
112062 112069    246.0
Name: new_cases, dtype: float64
112063 112070    135.0
Name: new_cases, dtype: float64
112064 112071    127.0
Name: new_cases, dtype: float64
112065 112072    252.0
Name: new_cases, dtype: float64
112066 112073    229.0
Name: new_cases, dtype: float64
112067 112074    313.0
Name: new_cases, dtype: float64
112068 112075    263.0
Name: new_cases, dtype: float64
112069 112076    209.0
Name: new_cases, dtype: float64
112070 112077    135.0
Name: new_cases, dtype: float64
112071 112078    111.0
Name: new_cases, dtype: float64
112072 112079    203.0
Name: new_cases, dtype: float64
112073 112080    255.0
Name: new_cases, dtype: float64
112074 112081    204.0
Name: new_cases, dtype: float64
112075 112082    238.0
Name: new_cases, dtype: float64
112076 112083    153.0
Name: new_cases, dtype: float64
112077 112084    106.0
Name: new_cases, dtype: float64
112078 112085    112.0
Name: new_cases, dtype: float64
112079 112086    167.0
Name: new_cases, dtype: float64
112080 112087    213.0
Name: new_cases, dtype: float64
112081 112088    290.0
Name: new_cases, dtype: float64
112082 112089    186.0
Name: new_cases, dtype: float64
112083 112090    131.0
Name: new_cases, dtype: float64
112084 112091    157.0
Name: new_cases, dtype: float64
112085 112092    120.0
Name: new_cases, dtype: float64
112086 112093    278.0
Name: new_cases, dtype: float64
112087 112094    325.0
Name: new_cases, dtype: float64
112088 112095    235.0
Name: new_cases, dtype: float64
112089 112096    198.0
Name: new_cases, dtype: float64
112090 112097    121.0
Name: new_cases, dtype: float64
112091 112098    132.0
Name: new_cases, dtype: float64
112092 112099    214.0
Name: new_cases, dtype: float64
112093 112100    253.0
Name: new_cases, dtype: float64
112094 112101    291.0
Name: new_cases, dtype: float64
112095 112102    219.0
Name: new_cases, dtype: float64
112096 112103    241.0
Name: new_cases, dtype: float64
112097 112104    145.0
Name: new_cases, dtype: float64
112098 112105    123.0
Name: new_cases, dtype: float64
112099 112106    192.0
Name: new_cases, dtype: float64
112100 112107    362.0
Name: new_cases, dtype: float64
112101 112108    399.0
Name: new_cases, dtype: float64
112102 112109    401.0
Name: new_cases, dtype: float64
112103 112110    374.0
Name: new_cases, dtype: float64
112104 112111    320.0
Name: new_cases, dtype: float64
112105 112112    244.0
Name: new_cases, dtype: float64
112106 112113    231.0
Name: new_cases, dtype: float64
112107 112114    390.0
Name: new_cases, dtype: float64
112108 112115    418.0
Name: new_cases, dtype: float64
112109 112116    406.0
Name: new_cases, dtype: float64
112110 112117    486.0
Name: new_cases, dtype: float64
112111 112118    315.0
Name: new_cases, dtype: float64
112112 112119    249.0
Name: new_cases, dtype: float64
112113 112120    388.0
Name: new_cases, dtype: float64
112114 112121    646.0
Name: new_cases, dtype: float64
112115 112122    585.0
Name: new_cases, dtype: float64
112116 112123    687.0
Name: new_cases, dtype: float64
112117 112124    497.0
Name: new_cases, dtype: float64
112118 112125    673.0
Name: new_cases, dtype: float64
112119 112126    613.0
Name: new_cases, dtype: float64
112120 112127    425.0
Name: new_cases, dtype: float64
112121 112128    605.0
Name: new_cases, dtype: float64
112122 112129    770.0
Name: new_cases, dtype: float64
112123 112130    780.0
Name: new_cases, dtype: float64
112124 112131    849.0
Name: new_cases, dtype: float64
112125 112132    552.0
Name: new_cases, dtype: float64
112126 112133    623.0
Name: new_cases, dtype: float64
112127 112134    463.0
Name: new_cases, dtype: float64
112128 112135    802.0
Name: new_cases, dtype: float64
112129 112136    691.0
Name: new_cases, dtype: float64
112130 112137    899.0
Name: new_cases, dtype: float64
112131 112138    884.0
Name: new_cases, dtype: float64
112132 112139    665.0
Name: new_cases, dtype: float64
112133 112140    425.0
Name: new_cases, dtype: float64
112134 112141    688.0
Name: new_cases, dtype: float64
112135 112142    825.0
Name: new_cases, dtype: float64
112136 112143    854.0
Name: new_cases, dtype: float64
112137 112144    888.0
Name: new_cases, dtype: float64
112138 112145    963.0
Name: new_cases, dtype: float64
112139 112146    904.0
Name: new_cases, dtype: float64
112140 112147    734.0
Name: new_cases, dtype: float64
112141 112148    427.0
Name: new_cases, dtype: float64
112142 112149    944.0
Name: new_cases, dtype: float64
112143 112150    1278.0
Name: new_cases, dtype: float64
112144 112151    1394.0
Name: new_cases, dtype: float64
112145 112152    1646.0
Name: new_cases, dtype: float64
112146 112153    1090.0
Name: new_cases, dtype: float64
112147 112154    1249.0
Name: new_cases, dtype: float64
112148 112155    1208.0
Name: new_cases, dtype: float64
112149 112156    2072.0
Name: new_cases, dtype: float64
112150 112157    2101.0
Name: new_cases, dtype: float64
112151 112158    2608.0
Name: new_cases, dtype: float64
112152 112159    2153.0
Name: new_cases, dtype: float64
112153 112160    1856.0
Name: new_cases, dtype: float64
112154 112161    1949.0
Name: new_cases, dtype: float64
112155 112162    1876.0
Name: new_cases, dtype: float64
112156 112163    2535.0
Name: new_cases, dtype: float64
112157 112164    3270.0
Name: new_cases, dtype: float64
112158 112165    2899.0
Name: new_cases, dtype: float64
112159 112166    3669.0
Name: new_cases, dtype: float64
112160 112167    2577.0
Name: new_cases, dtype: float64
112161 112168    2447.0
Name: new_cases, dtype: float64
112162 112169    3299.0
Name: new_cases, dtype: float64
112163 112170    3960.0
Name: new_cases, dtype: float64
112164 112171    4224.0
Name: new_cases, dtype: float64
112165 112172    4656.0
Name: new_cases, dtype: float64
112166 112173    4007.0
Name: new_cases, dtype: float64
112167 112174    3062.0
Name: new_cases, dtype: float64
112168 112175    2506.0
Name: new_cases, dtype: float64
112169 112176    2596.0
Name: new_cases, dtype: float64
112170 112177    7497.0
Name: new_cases, dtype: float64
112171 112178    4410.0
Name: new_cases, dtype: float64
112172 112179    5550.0
Name: new_cases, dtype: float64
112173 112180    6640.0
Name: new_cases, dtype: float64
112174 112181    5784.0
Name: new_cases, dtype: float64
112175 112182    4096.0
Name: new_cases, dtype: float64
112176 112183    3817.0
Name: new_cases, dtype: float64
112177 112184    4935.0
Name: new_cases, dtype: float64
112178 112185    5839.0
Name: new_cases, dtype: float64
112179 112186    6653.0
Name: new_cases, dtype: float64
112180 112187    6602.0
Name: new_cases, dtype: float64
112181 112188    6035.0
Name: new_cases, dtype: float64
112182 112189    8371.0
Name: new_cases, dtype: float64
112183 112190    4452.0
Name: new_cases, dtype: float64
112184 112191    5891.0
Name: new_cases, dtype: float64
112185 112192    6994.0
Name: new_cases, dtype: float64
112186 112193    6489.0
Name: new_cases, dtype: float64
112187 112194    6472.0
Name: new_cases, dtype: float64
112188 112195    4788.0
Name: new_cases, dtype: float64

112189 112196    4044.0
Name: new_cases, dtype: float64
112190 112197    3919.0
Name: new_cases, dtype: float64
112191 112198    5290.0
Name: new_cases, dtype: float64
112192 112199    6383.0
Name: new_cases, dtype: float64
112193 112200    5444.0
Name: new_cases, dtype: float64
112194 112201    4868.0
Name: new_cases, dtype: float64
112195 112202    4093.0
Name: new_cases, dtype: float64
112196 112203    3262.0
Name: new_cases, dtype: float64
112197 112204    2401.0
Name: new_cases, dtype: float64
112198 112205    3384.0
Name: new_cases, dtype: float64
112199 112206    3772.0
Name: new_cases, dtype: float64
112200 112207    4935.0
Name: new_cases, dtype: float64
112201 112208    6087.0
Name: new_cases, dtype: float64
112202 112209    3834.0
Name: new_cases, dtype: float64
112203 112210    2597.0
Name: new_cases, dtype: float64
112204 112211    2905.0
Name: new_cases, dtype: float64
112205 112212    4097.0
Name: new_cases, dtype: float64
112206 112213    3134.0
Name: new_cases, dtype: float64
112207 112214    5080.0
Name: new_cases, dtype: float64
112208 112215    4413.0
Name: new_cases, dtype: float64
112209 112216    4044.0
Name: new_cases, dtype: float64
112210 112217    2194.0
Name: new_cases, dtype: float64
112211 112218    2638.0
Name: new_cases, dtype: float64
112212 112219    4720.0
Name: new_cases, dtype: float64
112213 112220    4320.0
Name: new_cases, dtype: float64
112214 112221    4336.0
Name: new_cases, dtype: float64
112215 112222    3835.0
Name: new_cases, dtype: float64
112216 112223    3334.0
Name: new_cases, dtype: float64
112217 112224    2099.0
Name: new_cases, dtype: float64
112218 112225    2436.0
Name: new_cases, dtype: float64
112219 112226    4602.0
Name: new_cases, dtype: float64
112220 112227    4378.0
Name: new_cases, dtype: float64
112221 112228    4146.0
Name: new_cases, dtype: float64
112222 112229    1214.0
Name: new_cases, dtype: float64
112223 112230    1577.0
Name: new_cases, dtype: float64
112224 112231    2093.0
Name: new_cases, dtype: float64
112225 112232    3336.0
Name: new_cases, dtype: float64
112226 112233    6049.0
Name: new_cases, dtype: float64
112227 112234    7627.0
Name: new_cases, dtype: float64
112228 112235    6951.0
Name: new_cases, dtype: float64
112229 112236    3241.0
Name: new_cases, dtype: float64
112230 112237    3384.0
Name: new_cases, dtype: float64
112231 112238    4369.0
Name: new_cases, dtype: float64
112232 112239    4956.0
Name: new_cases, dtype: float64
112233 112240    10027.0
Name: new_cases, dtype: float64
112234 112241    9927.0
Name: new_cases, dtype: float64
112235 112242    10176.0
Name: new_cases, dtype: float64
112236 112243    9478.0
Name: new_cases, dtype: float64
112237 112244    7502.0
Name: new_cases, dtype: float64
112238 112245    5604.0
Name: new_cases, dtype: float64
112239 112246    7259.0
Name: new_cases, dtype: float64
112240 112247    10556.0
Name: new_cases, dtype: float64
112241 112248    10698.0
Name: new_cases, dtype: float64
112242 112249    10663.0
Name: new_cases, dtype: float64
112243 112250    10947.0
Name: new_cases, dtype: float64
112244 112251    10385.0
Name: new_cases, dtype: float64
112245 112252    6702.0
Name: new_cases, dtype: float64
112246 112253    10455.0
Name: new_cases, dtype: float64
112247 112254    14647.0
Name: new_cases, dtype: float64
112248 112255    13544.0
Name: new_cases, dtype: float64
112249 112256    13987.0
Name: new_cases, dtype: float64
112250 112257    15333.0
Name: new_cases, dtype: float64
112251 112258    11721.0
Name: new_cases, dtype: float64
112252 112259    6923.0
Name: new_cases, dtype: float64
112253 112260    10765.0
Name: new_cases, dtype: float64
112254 112261    15073.0
Name: new_cases, dtype: float64
112255 112262    16432.0
Name: new_cases, dtype: float64
112256 112263    13200.0
Name: new_cases, dtype: float64
112257 112264    12435.0
Name: new_cases, dtype: float64
112258 112265    9498.0
Name: new_cases, dtype: float64
112259 112266    5805.0
Name: new_cases, dtype: float64
112260 112267    5540.0
Name: new_cases, dtype: float64
112261 112268    9083.0
Name: new_cases, dtype: float64
112262 112269    7914.0
Name: new_cases, dtype: float64
112263 112270    6916.0
Name: new_cases, dtype: float64
112264 112271    6132.0
Name: new_cases, dtype: float64
112265 112272    3508.0
Name: new_cases, dtype: float64
112266 112273    2505.0
Name: new_cases, dtype: float64
112267 112274    2583.0
Name: new_cases, dtype: float64
112268 112275    4387.0
Name: new_cases, dtype: float64
112269 112276    3480.0
Name: new_cases, dtype: float64
112270 112277    2854.0
Name: new_cases, dtype: float64
112271 112278    2856.0
Name: new_cases, dtype: float64
112272 112279    1677.0
Name: new_cases, dtype: float64
112273 112280    1303.0
Name: new_cases, dtype: float64
112274 112281    1502.0
Name: new_cases, dtype: float64
112275 112282    2324.0
Name: new_cases, dtype: float64
112276 112283    1944.0
Name: new_cases, dtype: float64
112277 112284    1940.0
Name: new_cases, dtype: float64
112278 112285    1570.0
Name: new_cases, dtype: float64
112279 112286    1186.0
Name: new_cases, dtype: float64
112280 112287    549.0
Name: new_cases, dtype: float64
112281 112288    1032.0
Name: new_cases, dtype: float64
112282 112289    1480.0
Name: new_cases, dtype: float64
112283 112290    1160.0
Name: new_cases, dtype: float64
112284 112291    1027.0
Name: new_cases, dtype: float64
112285 112292    1071.0
Name: new_cases, dtype: float64
112286 112293    718.0
Name: new_cases, dtype: float64
112287 112294    394.0
Name: new_cases, dtype: float64
112288 112295    691.0
Name: new_cases, dtype: float64
112289 112296    979.0
Name: new_cases, dtype: float64
112290 112297    830.0
Name: new_cases, dtype: float64
112291 112298    949.0
Name: new_cases, dtype: float64
112292 112299    1007.0
Name: new_cases, dtype: float64
112293 112300    682.0
Name: new_cases, dtype: float64
112294 112301    365.0
Name: new_cases, dtype: float64
112295 112302    847.0
Name: new_cases, dtype: float64
112296 112303    642.0
Name: new_cases, dtype: float64
112297 112304    627.0
Name: new_cases, dtype: float64
112298 112305    577.0
Name: new_cases, dtype: float64
112299 112306    564.0
Name: new_cases, dtype: float64
112300 112307    541.0
Name: new_cases, dtype: float64
112301 112308    256.0
Name: new_cases, dtype: float64
112302 112309    384.0
Name: new_cases, dtype: float64
112303 112310    673.0
Name: new_cases, dtype: float64
112304 112311    485.0
Name: new_cases, dtype: float64
112305 112312    568.0
Name: new_cases, dtype: float64
112306 112313    457.0
Name: new_cases, dtype: float64
112307 112314    450.0
Name: new_cases, dtype: float64
112308 112315    248.0
Name: new_cases, dtype: float64
112309 112316    434.0
Name: new_cases, dtype: float64
112310 112317    575.0
Name: new_cases, dtype: float64
112311 112318    423.0
Name: new_cases, dtype: float64
112312 112319    488.0
Name: new_cases, dtype: float64
112313 112320    344.0
Name: new_cases, dtype: float64
112314 112321    365.0
Name: new_cases, dtype: float64
112315 112322    309.0
Name: new_cases, dtype: float64
112316 112323    388.0
Name: new_cases, dtype: float64
112317 112324    618.0
Name: new_cases, dtype: float64
112318 112325    592.0
Name: new_cases, dtype: float64
112319 112326    548.0
Name: new_cases, dtype: float64
112320 112327    280.0
Name: new_cases, dtype: float64
112321 112328    193.0
Name: new_cases, dtype: float64
112322 112329    159.0
Name: new_cases, dtype: float64
112323 112330    874.0
Name: new_cases, dtype: float64
112324 112331    663.0
Name: new_cases, dtype: float64
112325 112332    602.0
Name: new_cases, dtype: float64
112326 112333    694.0
Name: new_cases, dtype: float64
112327 112334    601.0
Name: new_cases, dtype: float64
112328 112335    566.0
Name: new_cases, dtype: float64
112329 112336    271.0
Name: new_cases, dtype: float64
112330 112337    408.0
Name: new_cases, dtype: float64
112331 112338    684.0
Name: new_cases, dtype: float64
112332 112339    501.0
Name: new_cases, dtype: float64
112333 112340    553.0
Name: new_cases, dtype: float64
112334 112341    649.0
Name: new_cases, dtype: float64
112335 112342    441.0
Name: new_cases, dtype: float64
112336 112343    220.0
Name: new_cases, dtype: float64
112337 112344    424.0
Name: new_cases, dtype: float64
112338 112345    610.0
Name: new_cases, dtype: float64
112339 112346    636.0
Name: new_cases, dtype: float64
112340 112347    506.0
Name: new_cases, dtype: float64
112341 112348    567.0
Name: new_cases, dtype: float64
112342 112349    478.0
Name: new_cases, dtype: float64
112343 112350    196.0
Name: new_cases, dtype: float64
112344 112351    353.0
Name: new_cases, dtype: float64
112345 112352    572.0
Name: new_cases, dtype: float64
112346 112353    470.0
Name: new_cases, dtype: float64
112347 112354    460.0
Name: new_cases, dtype: float64
112348 112355    454.0
Name: new_cases, dtype: float64
112349 112356    330.0
Name: new_cases, dtype: float64
112350 112357    180.0
Name: new_cases, dtype: float64
112351 112358    258.0
Name: new_cases, dtype: float64
112352 112359    387.0
Name: new_cases, dtype: float64
112353 112360    373.0
Name: new_cases, dtype: float64

112354 112361    377.0
Name: new_cases, dtype: float64
112355 112362    406.0
Name: new_cases, dtype: float64
112356 112363    324.0
Name: new_cases, dtype: float64
112357 112364    158.0
Name: new_cases, dtype: float64
112358 112365    268.0
Name: new_cases, dtype: float64
112359 112366    485.0
Name: new_cases, dtype: float64
112360 112367    436.0
Name: new_cases, dtype: float64
112361 112368    450.0
Name: new_cases, dtype: float64
112362 112369    469.0
Name: new_cases, dtype: float64
112363 112370    334.0
Name: new_cases, dtype: float64
112364 112371    199.0
Name: new_cases, dtype: float64
112365 112372    386.0
Name: new_cases, dtype: float64
112366 112373    511.0
Name: new_cases, dtype: float64
112367 112374    451.0
Name: new_cases, dtype: float64
112368 112375    559.0
Name: new_cases, dtype: float64
112369 112376    523.0
Name: new_cases, dtype: float64
112370 112377    413.0
Name: new_cases, dtype: float64
112371 112378    241.0
Name: new_cases, dtype: float64
112372 112379    375.0
Name: new_cases, dtype: float64
112373 112380    594.0
Name: new_cases, dtype: float64
112374 112381    572.0
Name: new_cases, dtype: float64
112375 112382    598.0
Name: new_cases, dtype: float64
112376 112383    609.0
Name: new_cases, dtype: float64
112377 112384    445.0
Name: new_cases, dtype: float64
112378 112385    435.0
Name: new_cases, dtype: float64
112379 112386    445.0
Name: new_cases, dtype: float64
112380 112387    724.0
Name: new_cases, dtype: float64
112381 112388    769.0
Name: new_cases, dtype: float64
112382 112389    430.0
Name: new_cases, dtype: float64
112383 112390    573.0
Name: new_cases, dtype: float64
112384 112391    612.0
Name: new_cases, dtype: float64
112385 112392    388.0
Name: new_cases, dtype: float64
112386 112393    598.0
Name: new_cases, dtype: float64
112387 112394    890.0
Name: new_cases, dtype: float64
112388 112395    910.0
Name: new_cases, dtype: float64
112389 112396    519.0
Name: new_cases, dtype: float64
112390 112397    789.0
Name: new_cases, dtype: float64
112391 112398    707.0
Name: new_cases, dtype: float64
112392 112399    625.0
Name: new_cases, dtype: float64
112393 112400    973.0
Name: new_cases, dtype: float64
112394 112401    1350.0
Name: new_cases, dtype: float64
112395 112402    1233.0
Name: new_cases, dtype: float64
112396 112403    1298.0
Name: new_cases, dtype: float64
112397 112404    1183.0
Name: new_cases, dtype: float64
112398 112405    941.0
Name: new_cases, dtype: float64
112399 112406    756.0
Name: new_cases, dtype: float64
112400 112407    1020.0
Name: new_cases, dtype: float64
112401 112408    1497.0
Name: new_cases, dtype: float64
112402 112409    1556.0
Name: new_cases, dtype: float64
112403 112410    1604.0
Name: new_cases, dtype: float64
112404 112411    1568.0
Name: new_cases, dtype: float64
112405 112412    1496.0
Name: new_cases, dtype: float64
112406 112413    902.0
Name: new_cases, dtype: float64
112407 112414    1746.0
Name: new_cases, dtype: float64
112408 112415    2362.0
Name: new_cases, dtype: float64
112409 112416    2449.0
Name: new_cases, dtype: float64
112410 112417    2436.0
Name: new_cases, dtype: float64
112411 112418    2605.0
Name: new_cases, dtype: float64
112412 112419    2041.0
Name: new_cases, dtype: float64
112413 112420    1483.0
Name: new_cases, dtype: float64
112414 112421    2170.0
Name: new_cases, dtype: float64
112415 112422    3285.0
Name: new_cases, dtype: float64
112416 112423    3269.0
Name: new_cases, dtype: float64
112417 112424    3194.0
Name: new_cases, dtype: float64
112418 112425    3162.0
Name: new_cases, dtype: float64
112419 112426    2323.0
Name: new_cases, dtype: float64
112420 112427    1782.0
Name: new_cases, dtype: float64
112421 112428    2650.0
Name: new_cases, dtype: float64
112422 112429    4153.0
Name: new_cases, dtype: float64
112423 112430    3641.0
Name: new_cases, dtype: float64
112424 112431    3547.0
Name: new_cases, dtype: float64
112425 112432    3677.0
Name: new_cases, dtype: float64
112426 112433    3261.0
Name: new_cases, dtype: float64
112427 112434    1855.0
Name: new_cases, dtype: float64
112428 112435    2706.0
Name: new_cases, dtype: float64
112429 112436    4376.0
Name: new_cases, dtype: float64
112430 112437    3622.0
Name: new_cases, dtype: float64
112431 112438    3794.0
Name: new_cases, dtype: float64
112432 112439    3396.0
Name: new_cases, dtype: float64
112433 112440    2625.0
Name: new_cases, dtype: float64
112434 112441    1610.0
Name: new_cases, dtype: float64
112435 112442    2316.0
Name: new_cases, dtype: float64
112436 112443    3452.0
Name: new_cases, dtype: float64
112437 112444    3009.0
Name: new_cases, dtype: float64
112438 112445    2595.0
Name: new_cases, dtype: float64
112439 112446    2590.0
Name: new_cases, dtype: float64
112440 112447    2306.0
Name: new_cases, dtype: float64
112441 112448    1190.0
Name: new_cases, dtype: float64
112442 112449    2076.0
Name: new_cases, dtype: float64
112443 112450    3203.0
Name: new_cases, dtype: float64
112444 112451    2581.0
Name: new_cases, dtype: float64
112445 112452    2377.0
Name: new_cases, dtype: float64
112446 112453    2621.0
Name: new_cases, dtype: float64
112447 112454    1982.0
Name: new_cases, dtype: float64
112448 112455    1094.0
Name: new_cases, dtype: float64
112449 112456    2232.0
Name: new_cases, dtype: float64
112450 112457    2948.0
Name: new_cases, dtype: float64
112451 112458    2708.0
Name: new_cases, dtype: float64
112452 112459    2598.0
Name: new_cases, dtype: float64
112453 112460    2571.0
Name: new_cases, dtype: float64
112454 112461    2217.0
Name: new_cases, dtype: float64
112455 112462    1135.0
Name: new_cases, dtype: float64
112456 112463    2118.0
Name: new_cases, dtype: float64
112457 112464    2983.0
Name: new_cases, dtype: float64
112458 112465    2554.0
Name: new_cases, dtype: float64
112459 112466    2507.0
Name: new_cases, dtype: float64
112460 112467    2676.0
Name: new_cases, dtype: float64
112461 112468    2112.0
Name: new_cases, dtype: float64
112462 112469    1126.0
Name: new_cases, dtype: float64
112463 112470    2261.0
Name: new_cases, dtype: float64
112464 112471    3062.0
Name: new_cases, dtype: float64
112465 112472    2552.0
Name: new_cases, dtype: float64
112466 112473    2370.0
Name: new_cases, dtype: float64
112467 112474    2374.0
Name: new_cases, dtype: float64
112468 112475    1782.0
Name: new_cases, dtype: float64
112469 112476    1072.0
Name: new_cases, dtype: float64
112470 112477    1908.0
Name: new_cases, dtype: float64
112471 112478    1565.0
Name: new_cases, dtype: float64
112472 112479    2830.0
Name: new_cases, dtype: float64
112473 112480    1822.0
Name: new_cases, dtype: float64
112474 112481    1713.0
Name: new_cases, dtype: float64
112475 112482    1190.0
Name: new_cases, dtype: float64
112476 112483    663.0
Name: new_cases, dtype: float64
112477 112484    1231.0
Name: new_cases, dtype: float64
112478 112485    1778.0
Name: new_cases, dtype: float64
112479 112486    1408.0
Name: new_cases, dtype: float64
112480 112487    1323.0
Name: new_cases, dtype: float64
112481 112488    1223.0
Name: new_cases, dtype: float64
112482 112489    911.0
Name: new_cases, dtype: float64
112483 112490    458.0
Name: new_cases, dtype: float64
112484 112491    1058.0
Name: new_cases, dtype: float64
112485 112492    1247.0
Name: new_cases, dtype: float64
112486 112493    1062.0
Name: new_cases, dtype: float64
112487 112494    1023.0
Name: new_cases, dtype: float64
112488 112495    939.0
Name: new_cases, dtype: float64
112489 112496    677.0
Name: new_cases, dtype: float64
112490 112497    272.0
Name: new_cases, dtype: float64
112491 112498    780.0
Name: new_cases, dtype: float64
112492 112499    891.0
Name: new_cases, dtype: float64
112493 112500    885.0
Name: new_cases, dtype: float64
112494 112501    757.0
Name: new_cases, dtype: float64
112495 112502    713.0
Name: new_cases, dtype: float64
112496 112503    599.0
Name: new_cases, dtype: float64
112497 112504    230.0
Name: new_cases, dtype: float64
112498 112505    600.0
Name: new_cases, dtype: float64
112499 112506    755.0
Name: new_cases, dtype: float64
112500 112507    749.0
Name: new_cases, dtype: float64
112501 112508    696.0
Name: new_cases, dtype: float64
112502 112509    690.0
Name: new_cases, dtype: float64
112503 112510    449.0
Name: new_cases, dtype: float64
112504 112511    193.0
Name: new_cases, dtype: float64
112505 112512    730.0
Name: new_cases, dtype: float64
112506 112513    500.0
Name: new_cases, dtype: float64
112507 112514    731.0
Name: new_cases, dtype: float64
112508 112515    841.0
Name: new_cases, dtype: float64
112509 112516    704.0
Name: new_cases, dtype: float64
112510 112517    499.0
Name: new_cases, dtype: float64
112511 112518    327.0
Name: new_cases, dtype: float64
112512 112519    719.0
Name: new_cases, dtype: float64
112513 112520    828.0
Name: new_cases, dtype: float64
112514 112521    777.0
Name: new_cases, dtype: float64
112515 112522    766.0
Name: new_cases, dtype: float64

112516 112523    612.0
Name: new_cases, dtype: float64
112517 112524    465.0
Name: new_cases, dtype: float64
112518 112525    291.0
Name: new_cases, dtype: float64
112519 112526    832.0
Name: new_cases, dtype: float64
112520 112527    927.0
Name: new_cases, dtype: float64
112521 112528    865.0
Name: new_cases, dtype: float64
112522 112529    930.0
Name: new_cases, dtype: float64
112523 112530    883.0
Name: new_cases, dtype: float64
112524 112531    604.0
Name: new_cases, dtype: float64
112525 112532    313.0
Name: new_cases, dtype: float64
112526 112533    829.0
Name: new_cases, dtype: float64
112527 112534    965.0
Name: new_cases, dtype: float64
112528 112535    888.0
Name: new_cases, dtype: float64
112529 112536    844.0
Name: new_cases, dtype: float64
112530 112537    911.0
Name: new_cases, dtype: float64
112531 112538    763.0
Name: new_cases, dtype: float64
112532 112539    491.0
Name: new_cases, dtype: float64
112533 112540    450.0
Name: new_cases, dtype: float64
112534 112541    1074.0
Name: new_cases, dtype: float64
112535 112542    1382.0
Name: new_cases, dtype: float64
112536 112543    1289.0
Name: new_cases, dtype: float64
112537 112544    1197.0
Name: new_cases, dtype: float64
112538 112545    1023.0
Name: new_cases, dtype: float64
112539 112546    568.0
Name: new_cases, dtype: float64
112540 112547    1182.0
Name: new_cases, dtype: float64
112541 112548    1654.0
Name: new_cases, dtype: float64
112542 112549    1477.0
Name: new_cases, dtype: float64
112543 112550    1751.0
Name: new_cases, dtype: float64
112544 112551    1816.0
Name: new_cases, dtype: float64
112545 112552    1483.0
Name: new_cases, dtype: float64
112546 112553    974.0
Name: new_cases, dtype: float64
112547 112554    1693.0
Name: new_cases, dtype: float64
112548 112555    2527.0
Name: new_cases, dtype: float64
112549 112556    2398.0
Name: new_cases, dtype: float64
112550 112557    2371.0
Name: new_cases, dtype: float64
112551 112558    2333.0
Name: new_cases, dtype: float64
112552 112559    2499.0
Name: new_cases, dtype: float64
112553 112560    1475.0
Name: new_cases, dtype: float64
112554 112561    2560.0
Name: new_cases, dtype: float64
112555 112562    3773.0
Name: new_cases, dtype: float64
112556 112563    3150.0
Name: new_cases, dtype: float64
112557 112564    3205.0
Name: new_cases, dtype: float64
112558 112565    3364.0
Name: new_cases, dtype: float64
112559 112566    2897.0
Name: new_cases, dtype: float64
112560 112567    1635.0
Name: new_cases, dtype: float64
112561 112568    2907.0
Name: new_cases, dtype: float64
112562 112569    4670.0
Name: new_cases, dtype: float64
112563 112570    2898.0
Name: new_cases, dtype: float64
112564 112571    2535.0
Name: new_cases, dtype: float64
112565 112572    5649.0
Name: new_cases, dtype: float64
112566 112573    3786.0
Name: new_cases, dtype: float64
112567 112574    2216.0
Name: new_cases, dtype: float64
112568 112575    3417.0
Name: new_cases, dtype: float64
112569 112576    5286.0
Name: new_cases, dtype: float64
112570 112577    3588.0
Name: new_cases, dtype: float64
112571 112578    3742.0
Name: new_cases, dtype: float64
112572 112579    5373.0
Name: new_cases, dtype: float64
112573 112580    3879.0
Name: new_cases, dtype: float64
112574 112581    2314.0
Name: new_cases, dtype: float64
112575 112582    3591.0
Name: new_cases, dtype: float64
112576 112583    5800.0
Name: new_cases, dtype: float64
112577 112584    5137.0
Name: new_cases, dtype: float64
112578 112585    4644.0
Name: new_cases, dtype: float64
112579 112586    5062.0
Name: new_cases, dtype: float64
112580 112587    4266.0
Name: new_cases, dtype: float64
112581 112588    2752.0
Name: new_cases, dtype: float64
112582 112589    5754.0
Name: new_cases, dtype: float64
112583 112590    8937.0
Name: new_cases, dtype: float64
112584 112591    10549.0
Name: new_cases, dtype: float64
112585 112592    12943.0
Name: new_cases, dtype: float64
112586 112593    10016.0
Name: new_cases, dtype: float64
112587 112594    3732.0
Name: new_cases, dtype: float64
112588 112595    6334.0
Name: new_cases, dtype: float64
112589 112596    17172.0
Name: new_cases, dtype: float64
112590 112597    26867.0
Name: new_cases, dtype: float64
112591 112598    28659.0
Name: new_cases, dtype: float64
112592 112599    30829.0
Name: new_cases, dtype: float64
112593 112600    23290.0
Name: new_cases, dtype: float64
112594 112601    11080.0
Name: new_cases, dtype: float64
112595 112602    10554.0
Name: new_cases, dtype: float64
112596 112603    25836.0
Name: new_cases, dtype: float64
112597 112604    39570.0
Name: new_cases, dtype: float64
112598 Series([], Name: new_cases, dtype: float64)
112599 Series([], Name: new_cases, dtype: float64)
112600 Series([], Name: new_cases, dtype: float64)
112601 Series([], Name: new_cases, dtype: float64)
112602 Series([], Name: new_cases, dtype: float64)
112603 111930    2.0
Name: new_cases, dtype: float64
112604 111931    0.0
Name: new_cases, dtype: float64
113288 113295    1.0
Name: new_cases, dtype: float64
113289 113296    2.0
Name: new_cases, dtype: float64
113290 113297    3.0
Name: new_cases, dtype: float64
113291 113298    0.0
Name: new_cases, dtype: float64
113292 113299    6.0
Name: new_cases, dtype: float64
113293 113300    0.0
Name: new_cases, dtype: float64
113294 113301    10.0
Name: new_cases, dtype: float64
113295 113302    20.0
Name: new_cases, dtype: float64
113296 113303    4.0
Name: new_cases, dtype: float64
113297 113304    40.0
Name: new_cases, dtype: float64
113298 113305    34.0
Name: new_cases, dtype: float64
113299 113306    8.0
Name: new_cases, dtype: float64
113300 113307    27.0
Name: new_cases, dtype: float64
113301 113308    26.0
Name: new_cases, dtype: float64
113302 113309    76.0
Name: new_cases, dtype: float64
113303 113310    17.0
Name: new_cases, dtype: float64
113304 113311    31.0
Name: new_cases, dtype: float64
113305 113312    59.0
Name: new_cases, dtype: float64
113306 113313    66.0
Name: new_cases, dtype: float64
113307 113314    143.0
Name: new_cases, dtype: float64
113308 113315    218.0
Name: new_cases, dtype: float64
113309 113316    112.0
Name: new_cases, dtype: float64
113310 113317    123.0
Name: new_cases, dtype: float64
113311 113318    263.0
Name: new_cases, dtype: float64
113312 113319    160.0
Name: new_cases, dtype: float64
113313 113320    363.0
Name: new_cases, dtype: float64
113314 113321    294.0
Name: new_cases, dtype: float64
113315 113322    136.0
Name: new_cases, dtype: float64
113316 113323    215.0
Name: new_cases, dtype: float64
113317 113324    278.0
Name: new_cases, dtype: float64
113318 113325    445.0
Name: new_cases, dtype: float64
113319 113326    430.0
Name: new_cases, dtype: float64
113320 113327    251.0
Name: new_cases, dtype: float64
113321 113328    193.0
Name: new_cases, dtype: float64
113322 113329    360.0
Name: new_cases, dtype: float64
113323 113330    344.0
Name: new_cases, dtype: float64
113324 113331    441.0
Name: new_cases, dtype: float64
113325 113332    265.0
Name: new_cases, dtype: float64
113326 113333    523.0
Name: new_cases, dtype: float64
113327 113334    310.0
Name: new_cases, dtype: float64
113328 113335    333.0
Name: new_cases, dtype: float64
113329 113336    246.0
Name: new_cases, dtype: float64
113330 113337    337.0
Name: new_cases, dtype: float64
113331 113338    491.0
Name: new_cases, dtype: float64
113332 113339    360.0
Name: new_cases, dtype: float64
113333 113340    351.0
Name: new_cases, dtype: float64
113334 113341    328.0
Name: new_cases, dtype: float64
113335 113342    190.0
Name: new_cases, dtype: float64
113336 113343    306.0
Name: new_cases, dtype: float64
113337 113344    468.0
Name: new_cases, dtype: float64
113338 113345    386.0
Name: new_cases, dtype: float64
113339 113346    321.0
Name: new_cases, dtype: float64
113340 113347    218.0
Name: new_cases, dtype: float64
113341 113348    401.0
Name: new_cases, dtype: float64
113342 113349    303.0
Name: new_cases, dtype: float64
113343 113350    277.0
Name: new_cases, dtype: float64
113344 113351    362.0
Name: new_cases, dtype: float64
113345 113352    262.0
Name: new_cases, dtype: float64
113346 113353    327.0
Name: new_cases, dtype: float64
113347 113354    165.0
Name: new_cases, dtype: float64
113348 113355    431.0
Name: new_cases, dtype: float64
113349 113356    349.0
Name: new_cases, dtype: float64
113350 113357    325.0
Name: new_cases, dtype: float64
113351 113358    270.0
Name: new_cases, dtype: float64
113352 113359    392.0
Name: new_cases, dtype: float64
113353 113360    312.0
Name: new_cases, dtype: float64
113354 113361    320.0
Name: new_cases, dtype: float64
113355 113362    231.0
Name: new_cases, dtype: float64
113356 113363    226.0
Name: new_cases, dtype: float64
113357 113364    190.0
Name: new_cases, dtype: float64
113358 113365    224.0
Name: new_cases, dtype: float64
113359 113366    245.0
Name: new_cases, dtype: float64
113360 113367    190.0
Name: new_cases, dtype: float64
113361 113368    267.0
Name: new_cases, dtype: float64
113362 113369    167.0
Name: new_cases, dtype: float64
113363 113370    165.0
Name: new_cases, dtype: float64
113364 113371    155.0
Name: new_cases, dtype: float64
113365 113372    196.0
Name: new_cases, dtype: float64

113366 113373    198.0
Name: new_cases, dtype: float64
113367 113374    127.0
Name: new_cases, dtype: float64
113368 113375    145.0
Name: new_cases, dtype: float64
113369 113376    213.0
Name: new_cases, dtype: float64
113370 113377    213.0
Name: new_cases, dtype: float64
113371 113378    146.0
Name: new_cases, dtype: float64
113372 113379    165.0
Name: new_cases, dtype: float64
113373 113380    197.0
Name: new_cases, dtype: float64
113374 113381    191.0
Name: new_cases, dtype: float64
113375 113382    151.0
Name: new_cases, dtype: float64
113376 113383    124.0
Name: new_cases, dtype: float64
113377 113384    141.0
Name: new_cases, dtype: float64
113378 113385    119.0
Name: new_cases, dtype: float64
113379 113386    152.0
Name: new_cases, dtype: float64
113380 113387    238.0
Name: new_cases, dtype: float64
113381 113388    196.0
Name: new_cases, dtype: float64
113382 113389    187.0
Name: new_cases, dtype: float64
113383 113390    189.0
Name: new_cases, dtype: float64
113384 113391    125.0
Name: new_cases, dtype: float64
113385 113392    145.0
Name: new_cases, dtype: float64
113386 113393    196.0
Name: new_cases, dtype: float64
113387 113394    237.0
Name: new_cases, dtype: float64
113388 113395    222.0
Name: new_cases, dtype: float64
113389 113396    275.0
Name: new_cases, dtype: float64
113390 113397    320.0
Name: new_cases, dtype: float64
113391 113398    166.0
Name: new_cases, dtype: float64
113392 113399    250.0
Name: new_cases, dtype: float64
113393 113400    345.0
Name: new_cases, dtype: float64
113394 113401    320.0
Name: new_cases, dtype: float64
113395 113402    320.0
Name: new_cases, dtype: float64
113396 113403    330.0
Name: new_cases, dtype: float64
113397 113404    315.0
Name: new_cases, dtype: float64
113398 113405    246.0
Name: new_cases, dtype: float64
113399 113406    214.0
Name: new_cases, dtype: float64
113400 113407    321.0
Name: new_cases, dtype: float64
113401 113408    460.0
Name: new_cases, dtype: float64
113402 113409    411.0
Name: new_cases, dtype: float64
113403 113410    325.0
Name: new_cases, dtype: float64
113404 113411    291.0
Name: new_cases, dtype: float64
113405 113412    269.0
Name: new_cases, dtype: float64
113406 113413    388.0
Name: new_cases, dtype: float64
113407 113414    326.0
Name: new_cases, dtype: float64
113408 113415    450.0
Name: new_cases, dtype: float64
113409 113416    420.0
Name: new_cases, dtype: float64
113410 113417    416.0
Name: new_cases, dtype: float64
113411 113418    391.0
Name: new_cases, dtype: float64
113412 113419    250.0
Name: new_cases, dtype: float64
113413 113420    397.0
Name: new_cases, dtype: float64
113414 113421    555.0
Name: new_cases, dtype: float64
113415 113422    614.0
Name: new_cases, dtype: float64
113416 113423    592.0
Name: new_cases, dtype: float64
113417 113424    698.0
Name: new_cases, dtype: float64
113418 113425    456.0
Name: new_cases, dtype: float64
113419 113426    413.0
Name: new_cases, dtype: float64
113420 113427    637.0
Name: new_cases, dtype: float64
113421 113428    641.0
Name: new_cases, dtype: float64
113422 113429    777.0
Name: new_cases, dtype: float64
113423 113430    799.0
Name: new_cases, dtype: float64
113424 113431    889.0
Name: new_cases, dtype: float64
113425 113432    767.0
Name: new_cases, dtype: float64
113426 113433    681.0
Name: new_cases, dtype: float64
113427 113434    994.0
Name: new_cases, dtype: float64
113428 113435    1030.0
Name: new_cases, dtype: float64
113429 113436    1112.0
Name: new_cases, dtype: float64
113430 113437    1119.0
Name: new_cases, dtype: float64
113431 113438    1284.0
Name: new_cases, dtype: float64
113432 113439    1120.0
Name: new_cases, dtype: float64
113433 113440    1104.0
Name: new_cases, dtype: float64
113434 113441    1151.0
Name: new_cases, dtype: float64
113435 113442    1182.0
Name: new_cases, dtype: float64
113436 113443    1356.0
Name: new_cases, dtype: float64
113437 113444    1295.0
Name: new_cases, dtype: float64
113438 113445    1225.0
Name: new_cases, dtype: float64
113439 113446    1075.0
Name: new_cases, dtype: float64
113440 113447    823.0
Name: new_cases, dtype: float64
113441 113448    1232.0
Name: new_cases, dtype: float64
113442 113449    1309.0
Name: new_cases, dtype: float64
113443 113450    1345.0
Name: new_cases, dtype: float64
113444 113451    1378.0
Name: new_cases, dtype: float64
113445 113452    1350.0
Name: new_cases, dtype: float64
113446 113453    1145.0
Name: new_cases, dtype: float64
113447 113454    779.0
Name: new_cases, dtype: float64
113448 113455    1215.0
Name: new_cases, dtype: float64
113449 113456    1415.0
Name: new_cases, dtype: float64
113450 113457    1454.0
Name: new_cases, dtype: float64
113451 113458    1415.0
Name: new_cases, dtype: float64
113452 113459    1328.0
Name: new_cases, dtype: float64
113453 113460    1087.0
Name: new_cases, dtype: float64
113454 113461    733.0
Name: new_cases, dtype: float64
113455 113462    1014.0
Name: new_cases, dtype: float64
113456 113463    1409.0
Name: new_cases, dtype: float64
113457 113464    1346.0
Name: new_cases, dtype: float64
113458 113465    1392.0
Name: new_cases, dtype: float64
113459 113466    1189.0
Name: new_cases, dtype: float64
113460 113467    961.0
Name: new_cases, dtype: float64
113461 113468    825.0
Name: new_cases, dtype: float64
113462 113469    1060.0
Name: new_cases, dtype: float64
113463 113470    1256.0
Name: new_cases, dtype: float64
113464 113471    1504.0
Name: new_cases, dtype: float64
113465 113472    1318.0
Name: new_cases, dtype: float64
113466 113473    1365.0
Name: new_cases, dtype: float64
113467 113474    952.0
Name: new_cases, dtype: float64
113468 113475    755.0
Name: new_cases, dtype: float64
113469 113476    1053.0
Name: new_cases, dtype: float64
113470 113477    1298.0
Name: new_cases, dtype: float64
113471 113478    1365.0
Name: new_cases, dtype: float64
113472 113479    1339.0
Name: new_cases, dtype: float64
113473 113480    1269.0
Name: new_cases, dtype: float64
113474 113481    1150.0
Name: new_cases, dtype: float64
113475 113482    883.0
Name: new_cases, dtype: float64
113476 113483    1136.0
Name: new_cases, dtype: float64
113477 113484    1271.0
Name: new_cases, dtype: float64
113478 113485    1380.0
Name: new_cases, dtype: float64
113479 113486    1391.0
Name: new_cases, dtype: float64
113480 113487    1311.0
Name: new_cases, dtype: float64
113481 113488    1109.0
Name: new_cases, dtype: float64
113482 113489    692.0
Name: new_cases, dtype: float64
113483 113490    1111.0
Name: new_cases, dtype: float64
113484 113491    1713.0
Name: new_cases, dtype: float64
113485 113492    1679.0
Name: new_cases, dtype: float64
113486 113493    1527.0
Name: new_cases, dtype: float64
113487 113494    1333.0
Name: new_cases, dtype: float64
113488 113495    1231.0
Name: new_cases, dtype: float64
113489 113496    808.0
Name: new_cases, dtype: float64
113490 113497    1059.0
Name: new_cases, dtype: float64
113491 113498    1767.0
Name: new_cases, dtype: float64
113492 113499    1639.0
Name: new_cases, dtype: float64
113493 113500    1629.0
Name: new_cases, dtype: float64
113494 113501    1552.0
Name: new_cases, dtype: float64
113495 113502    1438.0
Name: new_cases, dtype: float64
113496 113503    1271.0
Name: new_cases, dtype: float64
113497 113504    1470.0
Name: new_cases, dtype: float64
113498 113505    2158.0
Name: new_cases, dtype: float64
113499 113506    2086.0
Name: new_cases, dtype: float64
113500 113507    2343.0
Name: new_cases, dtype: float64
113501 113508    2064.0
Name: new_cases, dtype: float64
113502 113509    1835.0
Name: new_cases, dtype: float64
113503 113510    1591.0
Name: new_cases, dtype: float64
113504 113511    2121.0
Name: new_cases, dtype: float64
113505 113512    2958.0
Name: new_cases, dtype: float64
113506 113513    3130.0
Name: new_cases, dtype: float64
113507 113514    3186.0
Name: new_cases, dtype: float64
113508 113515    3517.0
Name: new_cases, dtype: float64
113509 113516    2880.0
Name: new_cases, dtype: float64
113510 113517    2069.0
Name: new_cases, dtype: float64
113511 113518    3109.0
Name: new_cases, dtype: float64
113512 113519    4016.0
Name: new_cases, dtype: float64
113513 113520    4013.0
Name: new_cases, dtype: float64
113514 113521    4026.0
Name: new_cases, dtype: float64
113515 113522    3952.0
Name: new_cases, dtype: float64
113516 113523    3920.0
Name: new_cases, dtype: float64
113517 113524    2466.0
Name: new_cases, dtype: float64
113518 113525    3400.0
Name: new_cases, dtype: float64
113519 113526    4848.0
Name: new_cases, dtype: float64
113520 113527    4902.0
Name: new_cases, dtype: float64
113521 113528    5028.0
Name: new_cases, dtype: float64
113522 113529    4761.0
Name: new_cases, dtype: float64
113523 113530    3855.0
Name: new_cases, dtype: float64
113524 113531    2844.0
Name: new_cases, dtype: float64
113525 113532    4724.0
Name: new_cases, dtype: float64
113526 113533    5343.0
Name: new_cases, dtype: float64
113527 113534    6481.0
Name: new_cases, dtype: float64
113528 113535    6546.0
Name: new_cases, dtype: float64
113529 113536    5753.0
Name: new_cases, dtype: float64
113530 113537    5324.0
Name: new_cases, dtype: float64
113531 113538    4041.0
Name: new_cases, dtype: float64
113532 113539    7733.0
Name: new_cases, dtype: float64

113533 113540    8651.0
Name: new_cases, dtype: float64
113534 113541    9714.0
Name: new_cases, dtype: float64
113535 113542    10260.0
Name: new_cases, dtype: float64
113536 113543    9937.0
Name: new_cases, dtype: float64
113537 113544    6752.0
Name: new_cases, dtype: float64
113538 113545    3240.0
Name: new_cases, dtype: float64
113539 113546    7304.0
Name: new_cases, dtype: float64
113540 113547    9799.0
Name: new_cases, dtype: float64
113541 113548    10142.0
Name: new_cases, dtype: float64
113542 113549    9489.0
Name: new_cases, dtype: float64
113543 113550    9460.0
Name: new_cases, dtype: float64
113544 113551    7096.0
Name: new_cases, dtype: float64
113545 113552    4931.0
Name: new_cases, dtype: float64
113546 113553    8262.0
Name: new_cases, dtype: float64
113547 113554    10269.0
Name: new_cases, dtype: float64
113548 113555    10108.0
Name: new_cases, dtype: float64
113549 113556    9272.0
Name: new_cases, dtype: float64
113550 113557    9685.0
Name: new_cases, dtype: float64
113551 113558    5837.0
Name: new_cases, dtype: float64
113552 113559    4207.0
Name: new_cases, dtype: float64
113553 113560    7753.0
Name: new_cases, dtype: float64
113554 113561    9739.0
Name: new_cases, dtype: float64
113555 113562    9005.0
Name: new_cases, dtype: float64
113556 113563    8499.0
Name: new_cases, dtype: float64
113557 113564    8134.0
Name: new_cases, dtype: float64
113558 113565    5554.0
Name: new_cases, dtype: float64
113559 113566    3826.0
Name: new_cases, dtype: float64
113560 113567    4272.0
Name: new_cases, dtype: float64
113561 113568    4916.0
Name: new_cases, dtype: float64
113562 113569    7661.0
Name: new_cases, dtype: float64
113563 113570    8062.0
Name: new_cases, dtype: float64
113564 113571    8072.0
Name: new_cases, dtype: float64
113565 113572    5231.0
Name: new_cases, dtype: float64
113566 113573    3660.0
Name: new_cases, dtype: float64
113567 113574    7439.0
Name: new_cases, dtype: float64
113568 113575    7365.0
Name: new_cases, dtype: float64
113569 113576    7067.0
Name: new_cases, dtype: float64
113570 113577    6460.0
Name: new_cases, dtype: float64
113571 113578    6333.0
Name: new_cases, dtype: float64
113572 113579    4435.0
Name: new_cases, dtype: float64
113573 113580    3252.0
Name: new_cases, dtype: float64
113574 113581    6171.0
Name: new_cases, dtype: float64
113575 113582    5991.0
Name: new_cases, dtype: float64
113576 113583    5697.0
Name: new_cases, dtype: float64
113577 113584    5340.0
Name: new_cases, dtype: float64
113578 113585    5158.0
Name: new_cases, dtype: float64
113579 113586    3350.0
Name: new_cases, dtype: float64
113580 113587    2489.0
Name: new_cases, dtype: float64
113581 113588    5009.0
Name: new_cases, dtype: float64
113582 113589    5459.0
Name: new_cases, dtype: float64
113583 113590    4310.0
Name: new_cases, dtype: float64
113584 113591    3812.0
Name: new_cases, dtype: float64
113585 113592    1387.0
Name: new_cases, dtype: float64
113586 113593    2049.0
Name: new_cases, dtype: float64
113587 113594    2620.0
Name: new_cases, dtype: float64
113588 113595    4637.0
Name: new_cases, dtype: float64
113589 113596    4875.0
Name: new_cases, dtype: float64
113590 113597    4322.0
Name: new_cases, dtype: float64
113591 113598    3938.0
Name: new_cases, dtype: float64
113592 113599    1194.0
Name: new_cases, dtype: float64
113593 113600    3034.0
Name: new_cases, dtype: float64
113594 113601    3130.0
Name: new_cases, dtype: float64
113595 113602    4729.0
Name: new_cases, dtype: float64
113596 113603    5719.0
Name: new_cases, dtype: float64
113597 113604    4951.0
Name: new_cases, dtype: float64
113598 113605    4841.0
Name: new_cases, dtype: float64
113599 113606    4403.0
Name: new_cases, dtype: float64
113600 113607    3082.0
Name: new_cases, dtype: float64
113601 113608    1987.0
Name: new_cases, dtype: float64
113602 113609    3697.0
Name: new_cases, dtype: float64
113603 113610    4424.0
Name: new_cases, dtype: float64
113604 113611    3525.0
Name: new_cases, dtype: float64
113605 113612    3353.0
Name: new_cases, dtype: float64
113606 113613    3218.0
Name: new_cases, dtype: float64
113607 113614    2156.0
Name: new_cases, dtype: float64
113608 113615    1509.0
Name: new_cases, dtype: float64
113609 113616    2745.0
Name: new_cases, dtype: float64
113610 113617    3000.0
Name: new_cases, dtype: float64
113611 113618    2878.0
Name: new_cases, dtype: float64
113612 113619    2699.0
Name: new_cases, dtype: float64
113613 113620    2719.0
Name: new_cases, dtype: float64
113614 113621    1816.0
Name: new_cases, dtype: float64
113615 113622    1551.0
Name: new_cases, dtype: float64
113616 113623    2877.0
Name: new_cases, dtype: float64
113617 113624    3174.0
Name: new_cases, dtype: float64
113618 113625    2901.0
Name: new_cases, dtype: float64
113619 113626    2737.0
Name: new_cases, dtype: float64
113620 113627    2668.0
Name: new_cases, dtype: float64
113621 113628    1825.0
Name: new_cases, dtype: float64
113622 113629    1313.0
Name: new_cases, dtype: float64
113623 113630    2676.0
Name: new_cases, dtype: float64
113624 113631    2752.0
Name: new_cases, dtype: float64
113625 113632    2668.0
Name: new_cases, dtype: float64
113626 113633    2580.0
Name: new_cases, dtype: float64
113627 113634    2611.0
Name: new_cases, dtype: float64
113628 113635    1975.0
Name: new_cases, dtype: float64
113629 113636    1319.0
Name: new_cases, dtype: float64
113630 113637    2797.0
Name: new_cases, dtype: float64
113631 113638    3048.0
Name: new_cases, dtype: float64
113632 113639    2644.0
Name: new_cases, dtype: float64
113633 113640    2550.0
Name: new_cases, dtype: float64
113634 113641    2415.0
Name: new_cases, dtype: float64
113635 113642    1872.0
Name: new_cases, dtype: float64
113636 113643    1331.0
Name: new_cases, dtype: float64
113637 113644    2676.0
Name: new_cases, dtype: float64
113638 113645    2815.0
Name: new_cases, dtype: float64
113639 113646    3058.0
Name: new_cases, dtype: float64
113640 113647    2712.0
Name: new_cases, dtype: float64
113641 113648    2721.0
Name: new_cases, dtype: float64
113642 113649    2419.0
Name: new_cases, dtype: float64
113643 113650    1634.0
Name: new_cases, dtype: float64
113644 113651    3382.0
Name: new_cases, dtype: float64
113645 113652    3337.0
Name: new_cases, dtype: float64
113646 113653    3923.0
Name: new_cases, dtype: float64
113647 113654    3761.0
Name: new_cases, dtype: float64
113648 113655    3432.0
Name: new_cases, dtype: float64
113649 113656    2830.0
Name: new_cases, dtype: float64
113650 113657    2096.0
Name: new_cases, dtype: float64
113651 113658    3950.0
Name: new_cases, dtype: float64
113652 113659    4278.0
Name: new_cases, dtype: float64
113653 113660    4271.0
Name: new_cases, dtype: float64
113654 113661    4342.0
Name: new_cases, dtype: float64
113655 113662    4064.0
Name: new_cases, dtype: float64
113656 113663    3288.0
Name: new_cases, dtype: float64
113657 113664    2280.0
Name: new_cases, dtype: float64
113658 113665    4989.0
Name: new_cases, dtype: float64
113659 113666    4564.0
Name: new_cases, dtype: float64
113660 113667    5236.0
Name: new_cases, dtype: float64
113661 113668    5010.0
Name: new_cases, dtype: float64
113662 113669    4964.0
Name: new_cases, dtype: float64
113663 113670    4383.0
Name: new_cases, dtype: float64
113664 113671    2972.0
Name: new_cases, dtype: float64
113665 113672    6118.0
Name: new_cases, dtype: float64
113666 113673    6186.0
Name: new_cases, dtype: float64
113667 113674    6174.0
Name: new_cases, dtype: float64
113668 113675    5593.0
Name: new_cases, dtype: float64
113669 113676    6096.0
Name: new_cases, dtype: float64
113670 113677    4267.0
Name: new_cases, dtype: float64
113671 113678    3743.0
Name: new_cases, dtype: float64
113672 113679    6149.0
Name: new_cases, dtype: float64
113673 113680    6136.0
Name: new_cases, dtype: float64
113674 113681    6651.0
Name: new_cases, dtype: float64
113675 113682    6516.0
Name: new_cases, dtype: float64
113676 113683    5869.0
Name: new_cases, dtype: float64
113677 113684    4439.0
Name: new_cases, dtype: float64
113678 113685    3825.0
Name: new_cases, dtype: float64
113679 113686    6204.0
Name: new_cases, dtype: float64
113680 113687    6156.0
Name: new_cases, dtype: float64
113681 113688    6115.0
Name: new_cases, dtype: float64
113682 113689    5808.0
Name: new_cases, dtype: float64
113683 113690    5498.0
Name: new_cases, dtype: float64
113684 113691    4151.0
Name: new_cases, dtype: float64
113685 113692    3611.0
Name: new_cases, dtype: float64
113686 113693    5231.0
Name: new_cases, dtype: float64
113687 113694    5407.0
Name: new_cases, dtype: float64
113688 113695    4989.0
Name: new_cases, dtype: float64
113689 113696    4942.0
Name: new_cases, dtype: float64
113690 113697    4310.0
Name: new_cases, dtype: float64
113691 113698    3302.0
Name: new_cases, dtype: float64
113692 113699    2323.0
Name: new_cases, dtype: float64
113693 113700    3883.0
Name: new_cases, dtype: float64
113694 113701    4076.0
Name: new_cases, dtype: float64
113695 113702    3852.0
Name: new_cases, dtype: float64
113696 113703    3264.0
Name: new_cases, dtype: float64
113697 113704    3474.0
Name: new_cases, dtype: float64

113698 113705    2265.0
Name: new_cases, dtype: float64
113699 113706    1768.0
Name: new_cases, dtype: float64
113700 113707    2931.0
Name: new_cases, dtype: float64
113701 113708    3006.0
Name: new_cases, dtype: float64
113702 113709    2989.0
Name: new_cases, dtype: float64
113703 113710    2523.0
Name: new_cases, dtype: float64
113704 113711    2201.0
Name: new_cases, dtype: float64
113705 113712    1542.0
Name: new_cases, dtype: float64
113706 113713    1256.0
Name: new_cases, dtype: float64
113707 113714    2019.0
Name: new_cases, dtype: float64
113708 113715    2240.0
Name: new_cases, dtype: float64
113709 113716    1850.0
Name: new_cases, dtype: float64
113710 113717    1636.0
Name: new_cases, dtype: float64
113711 113718    1307.0
Name: new_cases, dtype: float64
113712 113719    1083.0
Name: new_cases, dtype: float64
113713 113720    682.0
Name: new_cases, dtype: float64
113714 113721    994.0
Name: new_cases, dtype: float64
113715 113722    1564.0
Name: new_cases, dtype: float64
113716 113723    1632.0
Name: new_cases, dtype: float64
113717 113724    1422.0
Name: new_cases, dtype: float64
113718 113725    1305.0
Name: new_cases, dtype: float64
113719 113726    857.0
Name: new_cases, dtype: float64
113720 113727    620.0
Name: new_cases, dtype: float64
113721 113728    1156.0
Name: new_cases, dtype: float64
113722 113729    930.0
Name: new_cases, dtype: float64
113723 113730    953.0
Name: new_cases, dtype: float64
113724 113731    835.0
Name: new_cases, dtype: float64
113725 113732    729.0
Name: new_cases, dtype: float64
113726 113733    565.0
Name: new_cases, dtype: float64
113727 113734    392.0
Name: new_cases, dtype: float64
113728 113735    681.0
Name: new_cases, dtype: float64
113729 113736    707.0
Name: new_cases, dtype: float64
113730 113737    618.0
Name: new_cases, dtype: float64
113731 113738    484.0
Name: new_cases, dtype: float64
113732 113739    455.0
Name: new_cases, dtype: float64
113733 113740    307.0
Name: new_cases, dtype: float64
113734 113741    230.0
Name: new_cases, dtype: float64
113735 113742    381.0
Name: new_cases, dtype: float64
113736 113743    379.0
Name: new_cases, dtype: float64
113737 113744    307.0
Name: new_cases, dtype: float64
113738 113745    321.0
Name: new_cases, dtype: float64
113739 113746    265.0
Name: new_cases, dtype: float64
113740 113747    158.0
Name: new_cases, dtype: float64
113741 113748    153.0
Name: new_cases, dtype: float64
113742 113749    241.0
Name: new_cases, dtype: float64
113743 113750    164.0
Name: new_cases, dtype: float64
113744 113751    196.0
Name: new_cases, dtype: float64
113745 113752    225.0
Name: new_cases, dtype: float64
113746 113753    179.0
Name: new_cases, dtype: float64
113747 113754    121.0
Name: new_cases, dtype: float64
113748 113755    89.0
Name: new_cases, dtype: float64
113749 113756    202.0
Name: new_cases, dtype: float64
113750 113757    140.0
Name: new_cases, dtype: float64
113751 113758    133.0
Name: new_cases, dtype: float64
113752 113759    103.0
Name: new_cases, dtype: float64
113753 113760    127.0
Name: new_cases, dtype: float64
113754 113761    69.0
Name: new_cases, dtype: float64
113755 113762    50.0
Name: new_cases, dtype: float64
113756 113763    103.0
Name: new_cases, dtype: float64
113757 113764    104.0
Name: new_cases, dtype: float64
113758 113765    87.0
Name: new_cases, dtype: float64
113759 113766    70.0
Name: new_cases, dtype: float64
113760 113767    63.0
Name: new_cases, dtype: float64
113761 113768    53.0
Name: new_cases, dtype: float64
113762 113769    26.0
Name: new_cases, dtype: float64
113763 113770    41.0
Name: new_cases, dtype: float64
113764 113771    66.0
Name: new_cases, dtype: float64
113765 113772    68.0
Name: new_cases, dtype: float64
113766 113773    65.0
Name: new_cases, dtype: float64
113767 113774    62.0
Name: new_cases, dtype: float64
113768 113775    46.0
Name: new_cases, dtype: float64
113769 113776    37.0
Name: new_cases, dtype: float64
113770 113777    73.0
Name: new_cases, dtype: float64
113771 113778    52.0
Name: new_cases, dtype: float64
113772 113779    31.0
Name: new_cases, dtype: float64
113773 113780    37.0
Name: new_cases, dtype: float64
113774 113781    58.0
Name: new_cases, dtype: float64
113775 113782    33.0
Name: new_cases, dtype: float64
113776 113783    28.0
Name: new_cases, dtype: float64
113777 113784    51.0
Name: new_cases, dtype: float64
113778 113785    60.0
Name: new_cases, dtype: float64
113779 113786    30.0
Name: new_cases, dtype: float64
113780 113787    54.0
Name: new_cases, dtype: float64
113781 113788    36.0
Name: new_cases, dtype: float64
113782 113789    26.0
Name: new_cases, dtype: float64
113783 113790    39.0
Name: new_cases, dtype: float64
113784 113791    51.0
Name: new_cases, dtype: float64
113785 113792    79.0
Name: new_cases, dtype: float64
113786 113793    62.0
Name: new_cases, dtype: float64
113787 113794    72.0
Name: new_cases, dtype: float64
113788 113795    49.0
Name: new_cases, dtype: float64
113789 113796    44.0
Name: new_cases, dtype: float64
113790 113797    46.0
Name: new_cases, dtype: float64
113791 113798    95.0
Name: new_cases, dtype: float64
113792 113799    102.0
Name: new_cases, dtype: float64
113793 113800    78.0
Name: new_cases, dtype: float64
113794 113801    104.0
Name: new_cases, dtype: float64
113795 113802    126.0
Name: new_cases, dtype: float64
113796 113803    109.0
Name: new_cases, dtype: float64
113797 113804    84.0
Name: new_cases, dtype: float64
113798 113805    175.0
Name: new_cases, dtype: float64
113799 113806    159.0
Name: new_cases, dtype: float64
113800 113807    170.0
Name: new_cases, dtype: float64
113801 113808    153.0
Name: new_cases, dtype: float64
113802 113809    156.0
Name: new_cases, dtype: float64
113803 113810    152.0
Name: new_cases, dtype: float64
113804 113811    137.0
Name: new_cases, dtype: float64
113805 113812    233.0
Name: new_cases, dtype: float64
113806 113813    271.0
Name: new_cases, dtype: float64
113807 113814    244.0
Name: new_cases, dtype: float64
113808 113815    230.0
Name: new_cases, dtype: float64
113809 113816    255.0
Name: new_cases, dtype: float64
113810 113817    208.0
Name: new_cases, dtype: float64
113811 113818    181.0
Name: new_cases, dtype: float64
113812 113819    312.0
Name: new_cases, dtype: float64
113813 113820    326.0
Name: new_cases, dtype: float64
113814 113821    371.0
Name: new_cases, dtype: float64
113815 113822    383.0
Name: new_cases, dtype: float64
113816 113823    408.0
Name: new_cases, dtype: float64
113817 113824    323.0
Name: new_cases, dtype: float64
113818 113825    286.0
Name: new_cases, dtype: float64
113819 113826    544.0
Name: new_cases, dtype: float64
113820 113827    541.0
Name: new_cases, dtype: float64
113821 113828    595.0
Name: new_cases, dtype: float64
113822 113829    628.0
Name: new_cases, dtype: float64
113823 113830    591.0
Name: new_cases, dtype: float64
113824 113831    517.0
Name: new_cases, dtype: float64
113825 113832    415.0
Name: new_cases, dtype: float64
113826 113833    782.0
Name: new_cases, dtype: float64
113827 113834    849.0
Name: new_cases, dtype: float64
113828 113835    953.0
Name: new_cases, dtype: float64
113829 113836    946.0
Name: new_cases, dtype: float64
113830 113837    1015.0
Name: new_cases, dtype: float64
113831 113838    868.0
Name: new_cases, dtype: float64
113832 113839    699.0
Name: new_cases, dtype: float64
113833 113840    1313.0
Name: new_cases, dtype: float64
113834 113841    1443.0
Name: new_cases, dtype: float64
113835 113842    1470.0
Name: new_cases, dtype: float64
113836 113843    1520.0
Name: new_cases, dtype: float64
113837 113844    1568.0
Name: new_cases, dtype: float64
113838 113845    1242.0
Name: new_cases, dtype: float64
113839 113846    1035.0
Name: new_cases, dtype: float64
113840 113847    2033.0
Name: new_cases, dtype: float64
113841 113848    2079.0
Name: new_cases, dtype: float64
113842 113849    2226.0
Name: new_cases, dtype: float64
113843 113850    2520.0
Name: new_cases, dtype: float64
113844 113851    2648.0
Name: new_cases, dtype: float64
113845 113852    2255.0
Name: new_cases, dtype: float64
113846 113853    1849.0
Name: new_cases, dtype: float64
113847 113854    3929.0
Name: new_cases, dtype: float64
113848 113855    4004.0
Name: new_cases, dtype: float64
113849 113856    4441.0
Name: new_cases, dtype: float64
113850 113857    4478.0
Name: new_cases, dtype: float64
113851 113858    5388.0
Name: new_cases, dtype: float64
113852 113859    3817.0
Name: new_cases, dtype: float64
113853 113860    3342.0
Name: new_cases, dtype: float64
113854 113861    6789.0
Name: new_cases, dtype: float64
113855 113862    7045.0
Name: new_cases, dtype: float64
113856 113863    7095.0
Name: new_cases, dtype: float64
113857 113864    7116.0
Name: new_cases, dtype: float64
113858 113865    7676.0
Name: new_cases, dtype: float64
113859 113866    6333.0
Name: new_cases, dtype: float64
113860 113867    5655.0
Name: new_cases, dtype: float64
113861 113868    11049.0
Name: new_cases, dtype: float64
113862 113869    10826.0
Name: new_cases, dtype: float64
113863 113870    12032.0
Name: new_cases, dtype: float64
113864 113871    10887.0
Name: new_cases, dtype: float64
113865 113872    12590.0
Name: new_cases, dtype: float64

113866 113873    8682.0
Name: new_cases, dtype: float64
113867 113874    8292.0
Name: new_cases, dtype: float64
113868 113875    15037.0
Name: new_cases, dtype: float64
113869 113876    14744.0
Name: new_cases, dtype: float64
113870 113877    14467.0
Name: new_cases, dtype: float64
113871 113878    13854.0
Name: new_cases, dtype: float64
113872 113879    14019.0
Name: new_cases, dtype: float64
113873 113880    10400.0
Name: new_cases, dtype: float64
113874 113881    9148.0
Name: new_cases, dtype: float64
113875 113882    16743.0
Name: new_cases, dtype: float64
113876 113883    15733.0
Name: new_cases, dtype: float64
113877 113884    16383.0
Name: new_cases, dtype: float64
113878 113885    15828.0
Name: new_cases, dtype: float64
113879 113886    15239.0
Name: new_cases, dtype: float64
113880 113887    11546.0
Name: new_cases, dtype: float64
113881 113888    10141.0
Name: new_cases, dtype: float64
113882 113889    18863.0
Name: new_cases, dtype: float64
113883 113890    17158.0
Name: new_cases, dtype: float64
113884 113891    16110.0
Name: new_cases, dtype: float64
113885 113892    15410.0
Name: new_cases, dtype: float64
113886 113893    15261.0
Name: new_cases, dtype: float64
113887 113894    11725.0
Name: new_cases, dtype: float64
113888 113895    9187.0
Name: new_cases, dtype: float64
113889 113896    16765.0
Name: new_cases, dtype: float64
113890 113897    14950.0
Name: new_cases, dtype: float64
113891 113898    13197.0
Name: new_cases, dtype: float64
113892 113899    12474.0
Name: new_cases, dtype: float64
113893 113900    12106.0
Name: new_cases, dtype: float64
113894 113901    7424.0
Name: new_cases, dtype: float64
113895 113902    6993.0
Name: new_cases, dtype: float64
113896 113903    11073.0
Name: new_cases, dtype: float64
113897 113904    10196.0
Name: new_cases, dtype: float64
113898 113905    8971.0
Name: new_cases, dtype: float64
113899 113906    8268.0
Name: new_cases, dtype: float64
113900 113907    8057.0
Name: new_cases, dtype: float64
113901 113908    5293.0
Name: new_cases, dtype: float64
113902 113909    4255.0
Name: new_cases, dtype: float64
113903 113910    7589.0
Name: new_cases, dtype: float64
113904 113911    6291.0
Name: new_cases, dtype: float64
113905 113912    5416.0
Name: new_cases, dtype: float64
113906 113913    4844.0
Name: new_cases, dtype: float64
113907 113914    4006.0
Name: new_cases, dtype: float64
113908 113915    3021.0
Name: new_cases, dtype: float64
113909 113916    2136.0
Name: new_cases, dtype: float64
113910 113917    4128.0
Name: new_cases, dtype: float64
113911 113918    3535.0
Name: new_cases, dtype: float64
113912 113919    3076.0
Name: new_cases, dtype: float64
113913 113920    2889.0
Name: new_cases, dtype: float64
113914 113921    2697.0
Name: new_cases, dtype: float64
113915 113922    1936.0
Name: new_cases, dtype: float64
113916 113923    1550.0
Name: new_cases, dtype: float64
113917 113924    2736.0
Name: new_cases, dtype: float64
113918 113925    2796.0
Name: new_cases, dtype: float64
113919 113926    2104.0
Name: new_cases, dtype: float64
113920 113927    1958.0
Name: new_cases, dtype: float64
113921 113928    1727.0
Name: new_cases, dtype: float64
113922 113929    1377.0
Name: new_cases, dtype: float64
113923 113930    1096.0
Name: new_cases, dtype: float64
113924 113931    1622.0
Name: new_cases, dtype: float64
113925 113932    1141.0
Name: new_cases, dtype: float64
113926 113933    1149.0
Name: new_cases, dtype: float64
113927 113934    1673.0
Name: new_cases, dtype: float64
113928 113935    1490.0
Name: new_cases, dtype: float64
113929 113936    916.0
Name: new_cases, dtype: float64
113930 113937    803.0
Name: new_cases, dtype: float64
113931 113938    1421.0
Name: new_cases, dtype: float64
113932 113939    1279.0
Name: new_cases, dtype: float64
113933 113940    1032.0
Name: new_cases, dtype: float64
113934 113941    931.0
Name: new_cases, dtype: float64
113935 113942    0.0
Name: new_cases, dtype: float64
113936 113943    1647.0
Name: new_cases, dtype: float64
113937 113944    494.0
Name: new_cases, dtype: float64
113938 113945    946.0
Name: new_cases, dtype: float64
113939 113946    829.0
Name: new_cases, dtype: float64
113940 113947    812.0
Name: new_cases, dtype: float64
113941 113948    743.0
Name: new_cases, dtype: float64
113942 113949    733.0
Name: new_cases, dtype: float64
113943 113950    499.0
Name: new_cases, dtype: float64
113944 113951    424.0
Name: new_cases, dtype: float64
113945 113952    826.0
Name: new_cases, dtype: float64
113946 113953    851.0
Name: new_cases, dtype: float64
113947 113954    775.0
Name: new_cases, dtype: float64
113948 113955    717.0
Name: new_cases, dtype: float64
113949 113956    598.0
Name: new_cases, dtype: float64
113950 113957    349.0
Name: new_cases, dtype: float64
113951 113958    566.0
Name: new_cases, dtype: float64
113952 113959    1144.0
Name: new_cases, dtype: float64
113953 113960    1271.0
Name: new_cases, dtype: float64
113954 113961    1497.0
Name: new_cases, dtype: float64
113955 113962    1668.0
Name: new_cases, dtype: float64
113956 113963    1451.0
Name: new_cases, dtype: float64
113957 113964    958.0
Name: new_cases, dtype: float64
113958 113965    1756.0
Name: new_cases, dtype: float64
113959 113966    3900.0
Name: new_cases, dtype: float64
113960 113967    4893.0
Name: new_cases, dtype: float64
113961 113968    6018.0
Name: new_cases, dtype: float64
113962 113969    5922.0
Name: new_cases, dtype: float64
113963 113970    6036.0
Name: new_cases, dtype: float64
113964 113297    3.0
Name: new_cases, dtype: float64
113965 113298    0.0
Name: new_cases, dtype: float64
113966 113299    6.0
Name: new_cases, dtype: float64
113967 113300    0.0
Name: new_cases, dtype: float64
113968 113301    10.0
Name: new_cases, dtype: float64
113969 113302    20.0
Name: new_cases, dtype: float64
113970 113303    4.0
Name: new_cases, dtype: float64
121574 121581    16.0
Name: new_cases, dtype: float64
121575 121582    11.0
Name: new_cases, dtype: float64
121576 121583    2.0
Name: new_cases, dtype: float64
121577 121584    7.0
Name: new_cases, dtype: float64
121578 121585    10.0
Name: new_cases, dtype: float64
121579 121586    18.0
Name: new_cases, dtype: float64
121580 121587    20.0
Name: new_cases, dtype: float64
121581 121588    32.0
Name: new_cases, dtype: float64
121582 121589    36.0
Name: new_cases, dtype: float64
121583 121590    51.0
Name: new_cases, dtype: float64
121584 121591    27.0
Name: new_cases, dtype: float64
121585 121592    54.0
Name: new_cases, dtype: float64
121586 121593    81.0
Name: new_cases, dtype: float64
121587 121594    0.0
Name: new_cases, dtype: float64
121588 121595    73.0
Name: new_cases, dtype: float64
121589 121596    202.0
Name: new_cases, dtype: float64
121590 121597    82.0
Name: new_cases, dtype: float64
121591 121598    44.0
Name: new_cases, dtype: float64
121592 121599    115.0
Name: new_cases, dtype: float64
121593 121600    160.0
Name: new_cases, dtype: float64
121594 121601    111.0
Name: new_cases, dtype: float64
121595 121602    305.0
Name: new_cases, dtype: float64
121596 121603    148.0
Name: new_cases, dtype: float64
121597 121604    284.0
Name: new_cases, dtype: float64
121598 121605    292.0
Name: new_cases, dtype: float64
121599 121606    247.0
Name: new_cases, dtype: float64
121600 121607    219.0
Name: new_cases, dtype: float64
121601 121608    201.0
Name: new_cases, dtype: float64
121602 121609    238.0
Name: new_cases, dtype: float64
121603 121610    275.0
Name: new_cases, dtype: float64
121604 121611    250.0
Name: new_cases, dtype: float64
121605 121612    424.0
Name: new_cases, dtype: float64
121606 121613    411.0
Name: new_cases, dtype: float64
121607 121614    408.0
Name: new_cases, dtype: float64
121608 121615    445.0
Name: new_cases, dtype: float64
121609 121616    372.0
Name: new_cases, dtype: float64
121610 121617    304.0
Name: new_cases, dtype: float64
121611 121618    324.0
Name: new_cases, dtype: float64
121612 121619    312.0
Name: new_cases, dtype: float64
121613 121620    260.0
Name: new_cases, dtype: float64
121614 121621    254.0
Name: new_cases, dtype: float64
121615 121622    132.0
Name: new_cases, dtype: float64
121616 121623    207.0
Name: new_cases, dtype: float64
121617 121624    296.0
Name: new_cases, dtype: float64
121618 121625    263.0
Name: new_cases, dtype: float64
121619 121626    233.0
Name: new_cases, dtype: float64
121620 121627    222.0
Name: new_cases, dtype: float64
121621 121628    227.0
Name: new_cases, dtype: float64
121622 121629    285.0
Name: new_cases, dtype: float64
121623 121630    0.0
Name: new_cases, dtype: float64
121624 121631    353.0
Name: new_cases, dtype: float64
121625 121632    102.0
Name: new_cases, dtype: float64
121626 121633    93.0
Name: new_cases, dtype: float64
121627 121634    120.0
Name: new_cases, dtype: float64
121628 121635    114.0
Name: new_cases, dtype: float64
121629 121636    57.0
Name: new_cases, dtype: float64
121630 121637    95.0
Name: new_cases, dtype: float64
121631 121638    89.0
Name: new_cases, dtype: float64
121632 121639    0.0
Name: new_cases, dtype: float64
121633 121640    144.0
Name: new_cases, dtype: float64
121634 121641    67.0
Name: new_cases, dtype: float64
121635 121642    52.0
Name: new_cases, dtype: float64

121636 121643    79.0
Name: new_cases, dtype: float64
121637 121644    64.0
Name: new_cases, dtype: float64
121638 121645    58.0
Name: new_cases, dtype: float64
121639 121646    114.0
Name: new_cases, dtype: float64
121640 121647    89.0
Name: new_cases, dtype: float64
121641 121648    34.0
Name: new_cases, dtype: float64
121642 121649    100.0
Name: new_cases, dtype: float64
121643 121650    86.0
Name: new_cases, dtype: float64
121644 121651    105.0
Name: new_cases, dtype: float64
121645 121652    68.0
Name: new_cases, dtype: float64
121646 121653    67.0
Name: new_cases, dtype: float64
121647 121654    34.0
Name: new_cases, dtype: float64
121648 121655    34.0
Name: new_cases, dtype: float64
121649 121656    48.0
Name: new_cases, dtype: float64
121650 121657    25.0
Name: new_cases, dtype: float64
121651 121658    54.0
Name: new_cases, dtype: float64
121652 121659    27.0
Name: new_cases, dtype: float64
121653 121660    31.0
Name: new_cases, dtype: float64
121654 121661    18.0
Name: new_cases, dtype: float64
121655 121662    24.0
Name: new_cases, dtype: float64
121656 121663    69.0
Name: new_cases, dtype: float64
121657 121664    48.0
Name: new_cases, dtype: float64
121658 121665    96.0
Name: new_cases, dtype: float64
121659 121666    74.0
Name: new_cases, dtype: float64
121660 121667    82.0
Name: new_cases, dtype: float64
121661 121668    73.0
Name: new_cases, dtype: float64
121662 121669    69.0
Name: new_cases, dtype: float64
121663 121670    66.0
Name: new_cases, dtype: float64
121664 121671    71.0
Name: new_cases, dtype: float64
121665 121672    73.0
Name: new_cases, dtype: float64
121666 121673    76.0
Name: new_cases, dtype: float64
121667 121674    59.0
Name: new_cases, dtype: float64
121668 121675    57.0
Name: new_cases, dtype: float64
121669 121676    59.0
Name: new_cases, dtype: float64
121670 121677    96.0
Name: new_cases, dtype: float64
121671 121678    94.0
Name: new_cases, dtype: float64
121672 121679    93.0
Name: new_cases, dtype: float64
121673 121680    94.0
Name: new_cases, dtype: float64
121674 121681    91.0
Name: new_cases, dtype: float64
121675 121682    96.0
Name: new_cases, dtype: float64
121676 121683    102.0
Name: new_cases, dtype: float64
121677 121684    143.0
Name: new_cases, dtype: float64
121678 121685    137.0
Name: new_cases, dtype: float64
121679 121686    193.0
Name: new_cases, dtype: float64
121680 121687    227.0
Name: new_cases, dtype: float64
121681 121688    254.0
Name: new_cases, dtype: float64
121682 121689    242.0
Name: new_cases, dtype: float64
121683 121690    276.0
Name: new_cases, dtype: float64
121684 121691    272.0
Name: new_cases, dtype: float64
121685 121692    359.0
Name: new_cases, dtype: float64
121686 121693    309.0
Name: new_cases, dtype: float64
121687 121694    325.0
Name: new_cases, dtype: float64
121688 121695    302.0
Name: new_cases, dtype: float64
121689 121696    289.0
Name: new_cases, dtype: float64
121690 121697    299.0
Name: new_cases, dtype: float64
121691 121698    357.0
Name: new_cases, dtype: float64
121692 121699    266.0
Name: new_cases, dtype: float64
121693 121700    386.0
Name: new_cases, dtype: float64
121694 121701    345.0
Name: new_cases, dtype: float64
121695 121702    287.0
Name: new_cases, dtype: float64
121696 121703    279.0
Name: new_cases, dtype: float64
121697 121704    344.0
Name: new_cases, dtype: float64
121698 121705    351.0
Name: new_cases, dtype: float64
121699 121706    383.0
Name: new_cases, dtype: float64
121700 121707    392.0
Name: new_cases, dtype: float64
121701 121708    389.0
Name: new_cases, dtype: float64
121702 121709    396.0
Name: new_cases, dtype: float64
121703 121710    359.0
Name: new_cases, dtype: float64
121704 121711    352.0
Name: new_cases, dtype: float64
121705 121712    426.0
Name: new_cases, dtype: float64
121706 121713    412.0
Name: new_cases, dtype: float64
121707 121714    409.0
Name: new_cases, dtype: float64
121708 121715    0.0
Name: new_cases, dtype: float64
121709 121716    878.0
Name: new_cases, dtype: float64
121710 121717    411.0
Name: new_cases, dtype: float64
121711 121718    379.0
Name: new_cases, dtype: float64
121712 121719    372.0
Name: new_cases, dtype: float64
121713 121720    321.0
Name: new_cases, dtype: float64
121714 121721    339.0
Name: new_cases, dtype: float64
121715 121722    330.0
Name: new_cases, dtype: float64
121716 121723    311.0
Name: new_cases, dtype: float64
121717 121724    258.0
Name: new_cases, dtype: float64
121718 121725    287.0
Name: new_cases, dtype: float64
121719 121726    295.0
Name: new_cases, dtype: float64
121720 121727    299.0
Name: new_cases, dtype: float64
121721 121728    276.0
Name: new_cases, dtype: float64
121722 121729    255.0
Name: new_cases, dtype: float64
121723 121730    236.0
Name: new_cases, dtype: float64
121724 121731    163.0
Name: new_cases, dtype: float64
121725 121732    235.0
Name: new_cases, dtype: float64
121726 121733    254.0
Name: new_cases, dtype: float64
121727 121734    247.0
Name: new_cases, dtype: float64
121728 121735    235.0
Name: new_cases, dtype: float64
121729 121736    238.0
Name: new_cases, dtype: float64
121730 121737    211.0
Name: new_cases, dtype: float64
121731 121738    100.0
Name: new_cases, dtype: float64
121732 121739    108.0
Name: new_cases, dtype: float64
121733 121740    158.0
Name: new_cases, dtype: float64
121734 121741    161.0
Name: new_cases, dtype: float64
121735 121742    169.0
Name: new_cases, dtype: float64
121736 121743    170.0
Name: new_cases, dtype: float64
121737 121744    109.0
Name: new_cases, dtype: float64
121738 121745    57.0
Name: new_cases, dtype: float64
121739 121746    106.0
Name: new_cases, dtype: float64
121740 121747    154.0
Name: new_cases, dtype: float64
121741 121748    125.0
Name: new_cases, dtype: float64
121742 121749    108.0
Name: new_cases, dtype: float64
121743 121750    75.0
Name: new_cases, dtype: float64
121744 121751    83.0
Name: new_cases, dtype: float64
121745 121752    41.0
Name: new_cases, dtype: float64
121746 121753    76.0
Name: new_cases, dtype: float64
121747 121754    99.0
Name: new_cases, dtype: float64
121748 121755    95.0
Name: new_cases, dtype: float64
121749 121756    96.0
Name: new_cases, dtype: float64
121750 121757    77.0
Name: new_cases, dtype: float64
121751 121758    56.0
Name: new_cases, dtype: float64
121752 121759    36.0
Name: new_cases, dtype: float64
121753 121760    53.0
Name: new_cases, dtype: float64
121754 121761    84.0
Name: new_cases, dtype: float64
121755 121762    58.0
Name: new_cases, dtype: float64
121756 121763    92.0
Name: new_cases, dtype: float64
121757 121764    72.0
Name: new_cases, dtype: float64
121758 121765    108.0
Name: new_cases, dtype: float64
121759 121766    29.0
Name: new_cases, dtype: float64
121760 121767    74.0
Name: new_cases, dtype: float64
121761 121768    102.0
Name: new_cases, dtype: float64
121762 121769    82.0
Name: new_cases, dtype: float64
121763 121770    62.0
Name: new_cases, dtype: float64
121764 121771    83.0
Name: new_cases, dtype: float64
121765 121772    68.0
Name: new_cases, dtype: float64
121766 121773    30.0
Name: new_cases, dtype: float64
121767 121774    61.0
Name: new_cases, dtype: float64
121768 121775    81.0
Name: new_cases, dtype: float64
121769 121776    83.0
Name: new_cases, dtype: float64
121770 121777    75.0
Name: new_cases, dtype: float64
121771 121778    74.0
Name: new_cases, dtype: float64
121772 121779    72.0
Name: new_cases, dtype: float64
121773 121780    30.0
Name: new_cases, dtype: float64
121774 121781    65.0
Name: new_cases, dtype: float64
121775 121782    72.0
Name: new_cases, dtype: float64
121776 121783    111.0
Name: new_cases, dtype: float64
121777 121784    73.0
Name: new_cases, dtype: float64
121778 121785    107.0
Name: new_cases, dtype: float64
121779 121786    59.0
Name: new_cases, dtype: float64
121780 121787    51.0
Name: new_cases, dtype: float64
121781 121788    120.0
Name: new_cases, dtype: float64
121782 121789    121.0
Name: new_cases, dtype: float64
121783 121790    151.0
Name: new_cases, dtype: float64
121784 121791    173.0
Name: new_cases, dtype: float64
121785 121792    168.0
Name: new_cases, dtype: float64
121786 121793    102.0
Name: new_cases, dtype: float64
121787 121794    67.0
Name: new_cases, dtype: float64
121788 121795    152.0
Name: new_cases, dtype: float64
121789 121796    245.0
Name: new_cases, dtype: float64
121790 121797    203.0
Name: new_cases, dtype: float64
121791 121798    265.0
Name: new_cases, dtype: float64
121792 121799    227.0
Name: new_cases, dtype: float64
121793 121800    214.0
Name: new_cases, dtype: float64
121794 121801    122.0
Name: new_cases, dtype: float64
121795 121802    326.0
Name: new_cases, dtype: float64
121796 121803    512.0
Name: new_cases, dtype: float64

121797 121804    416.0
Name: new_cases, dtype: float64
121798 121805    579.0
Name: new_cases, dtype: float64
121799 121806    757.0
Name: new_cases, dtype: float64
121800 121807    614.0
Name: new_cases, dtype: float64
121801 121808    341.0
Name: new_cases, dtype: float64
121802 121809    1053.0
Name: new_cases, dtype: float64
121803 121810    1328.0
Name: new_cases, dtype: float64
121804 121811    1384.0
Name: new_cases, dtype: float64
121805 121812    1545.0
Name: new_cases, dtype: float64
121806 121813    1817.0
Name: new_cases, dtype: float64
121807 121814    1449.0
Name: new_cases, dtype: float64
121808 121815    802.0
Name: new_cases, dtype: float64
121809 121816    1878.0
Name: new_cases, dtype: float64
121810 121817    2412.0
Name: new_cases, dtype: float64
121811 121818    2181.0
Name: new_cases, dtype: float64
121812 121819    2282.0
Name: new_cases, dtype: float64
121813 121820    2677.0
Name: new_cases, dtype: float64
121814 121821    2112.0
Name: new_cases, dtype: float64
121815 121822    1318.0
Name: new_cases, dtype: float64
121816 121823    2823.0
Name: new_cases, dtype: float64
121817 121824    3536.0
Name: new_cases, dtype: float64
121818 121825    3341.0
Name: new_cases, dtype: float64
121819 121826    3499.0
Name: new_cases, dtype: float64
121820 121827    3822.0
Name: new_cases, dtype: float64
121821 121828    3482.0
Name: new_cases, dtype: float64
121822 121829    2813.0
Name: new_cases, dtype: float64
121823 121830    4994.0
Name: new_cases, dtype: float64
121824 121831    5613.0
Name: new_cases, dtype: float64
121825 121832    6109.0
Name: new_cases, dtype: float64
121826 121833    6254.0
Name: new_cases, dtype: float64
121827 121834    5774.0
Name: new_cases, dtype: float64
121828 121835    4995.0
Name: new_cases, dtype: float64
121829 121836    5067.0
Name: new_cases, dtype: float64
121830 121837    6842.0
Name: new_cases, dtype: float64
121831 121838    7579.0
Name: new_cases, dtype: float64
121832 121839    7606.0
Name: new_cases, dtype: float64
121833 121840    7780.0
Name: new_cases, dtype: float64
121834 121841    7041.0
Name: new_cases, dtype: float64
121835 121842    6179.0
Name: new_cases, dtype: float64
121836 121843    6224.0
Name: new_cases, dtype: float64
121837 121844    7999.0
Name: new_cases, dtype: float64
121838 121845    7919.0
Name: new_cases, dtype: float64
121839 121846    7802.0
Name: new_cases, dtype: float64
121840 121847    7782.0
Name: new_cases, dtype: float64
121841 121848    6903.0
Name: new_cases, dtype: float64
121842 121849    5809.0
Name: new_cases, dtype: float64
121843 121850    6557.0
Name: new_cases, dtype: float64
121844 121851    7818.0
Name: new_cases, dtype: float64
121845 121852    7804.0
Name: new_cases, dtype: float64
121846 121853    7393.0
Name: new_cases, dtype: float64
121847 121854    6534.0
Name: new_cases, dtype: float64
121848 121855    5679.0
Name: new_cases, dtype: float64
121849 121856    4995.0
Name: new_cases, dtype: float64
121850 121857    4932.0
Name: new_cases, dtype: float64
121851 121858    5884.0
Name: new_cases, dtype: float64
121852 121859    5353.0
Name: new_cases, dtype: float64
121853 121860    5129.0
Name: new_cases, dtype: float64
121854 121861    4910.0
Name: new_cases, dtype: float64
121855 121862    3888.0
Name: new_cases, dtype: float64
121856 121863    3534.0
Name: new_cases, dtype: float64
121857 121864    3685.0
Name: new_cases, dtype: float64
121858 121865    4080.0
Name: new_cases, dtype: float64
121859 121866    4426.0
Name: new_cases, dtype: float64
121860 121867    4091.0
Name: new_cases, dtype: float64
121861 121868    3823.0
Name: new_cases, dtype: float64
121862 121869    3200.0
Name: new_cases, dtype: float64
121863 121870    2693.0
Name: new_cases, dtype: float64
121864 121871    2559.0
Name: new_cases, dtype: float64
121865 121872    3136.0
Name: new_cases, dtype: float64
121866 121873    3236.0
Name: new_cases, dtype: float64
121867 121874    2932.0
Name: new_cases, dtype: float64
121868 121875    2074.0
Name: new_cases, dtype: float64
121869 121876    1907.0
Name: new_cases, dtype: float64
121870 121877    1966.0
Name: new_cases, dtype: float64
121871 121878    2715.0
Name: new_cases, dtype: float64
121872 121879    2653.0
Name: new_cases, dtype: float64
121873 121880    2882.0
Name: new_cases, dtype: float64
121874 121881    1787.0
Name: new_cases, dtype: float64
121875 121882    2218.0
Name: new_cases, dtype: float64
121876 121883    0.0
Name: new_cases, dtype: float64
121877 121884    3564.0
Name: new_cases, dtype: float64
121878 121885    2093.0
Name: new_cases, dtype: float64
121879 121886    2142.0
Name: new_cases, dtype: float64
121880 121887    2267.0
Name: new_cases, dtype: float64
121881 121888    1881.0
Name: new_cases, dtype: float64
121882 121889    1751.0
Name: new_cases, dtype: float64
121883 121890    1393.0
Name: new_cases, dtype: float64
121884 121891    1317.0
Name: new_cases, dtype: float64
121885 121892    1578.0
Name: new_cases, dtype: float64
121886 121893    1688.0
Name: new_cases, dtype: float64
121887 121894    1646.0
Name: new_cases, dtype: float64
121888 121895    1648.0
Name: new_cases, dtype: float64
121889 121896    1709.0
Name: new_cases, dtype: float64
121890 121897    1483.0
Name: new_cases, dtype: float64
121891 121898    1318.0
Name: new_cases, dtype: float64
121892 121899    1523.0
Name: new_cases, dtype: float64
121893 121900    2080.0
Name: new_cases, dtype: float64
121894 121901    1839.0
Name: new_cases, dtype: float64
121895 121902    1592.0
Name: new_cases, dtype: float64
121896 121903    1717.0
Name: new_cases, dtype: float64
121897 121904    1543.0
Name: new_cases, dtype: float64
121898 121905    1366.0
Name: new_cases, dtype: float64
121899 121906    1739.0
Name: new_cases, dtype: float64
121900 121907    1903.0
Name: new_cases, dtype: float64
121901 121908    1932.0
Name: new_cases, dtype: float64
121902 121909    1863.0
Name: new_cases, dtype: float64
121903 121910    1968.0
Name: new_cases, dtype: float64
121904 121911    1684.0
Name: new_cases, dtype: float64
121905 121912    1529.0
Name: new_cases, dtype: float64
121906 121913    1960.0
Name: new_cases, dtype: float64
121907 121914    2014.0
Name: new_cases, dtype: float64
121908 121915    2088.0
Name: new_cases, dtype: float64
121909 121916    2000.0
Name: new_cases, dtype: float64
121910 121917    1928.0
Name: new_cases, dtype: float64
121911 121918    1622.0
Name: new_cases, dtype: float64
121912 121919    1386.0
Name: new_cases, dtype: float64
121913 121920    1331.0
Name: new_cases, dtype: float64
121914 121921    1810.0
Name: new_cases, dtype: float64
121915 121922    2467.0
Name: new_cases, dtype: float64
121916 121923    2561.0
Name: new_cases, dtype: float64
121917 121924    2632.0
Name: new_cases, dtype: float64
121918 121925    2442.0
Name: new_cases, dtype: float64
121919 121926    2518.0
Name: new_cases, dtype: float64
121920 121927    2956.0
Name: new_cases, dtype: float64
121921 121928    3257.0
Name: new_cases, dtype: float64
121922 121929    3460.0
Name: new_cases, dtype: float64
121923 121930    3588.0
Name: new_cases, dtype: float64
121924 121931    3339.0
Name: new_cases, dtype: float64
121925 121932    3210.0
Name: new_cases, dtype: float64
121926 121933    2809.0
Name: new_cases, dtype: float64
121927 121934    3469.0
Name: new_cases, dtype: float64
121928 121935    4157.0
Name: new_cases, dtype: float64
121929 121936    4056.0
Name: new_cases, dtype: float64
121930 121937    3866.0
Name: new_cases, dtype: float64
121931 121938    4071.0
Name: new_cases, dtype: float64
121932 121939    3519.0
Name: new_cases, dtype: float64
121933 121940    3042.0
Name: new_cases, dtype: float64
121934 121941    4091.0
Name: new_cases, dtype: float64
121935 121942    4576.0
Name: new_cases, dtype: float64
121936 121943    4590.0
Name: new_cases, dtype: float64
121937 121944    4595.0
Name: new_cases, dtype: float64
121938 121945    4668.0
Name: new_cases, dtype: float64
121939 121946    4092.0
Name: new_cases, dtype: float64
121940 121947    4226.0
Name: new_cases, dtype: float64
121941 121948    4634.0
Name: new_cases, dtype: float64
121942 121949    5201.0
Name: new_cases, dtype: float64
121943 121950    5446.0
Name: new_cases, dtype: float64
121944 121951    5346.0
Name: new_cases, dtype: float64
121945 121952    5305.0
Name: new_cases, dtype: float64
121946 121953    4687.0
Name: new_cases, dtype: float64
121947 121954    4232.0
Name: new_cases, dtype: float64
121948 121955    4769.0
Name: new_cases, dtype: float64
121949 121956    5475.0
Name: new_cases, dtype: float64
121950 121957    5297.0
Name: new_cases, dtype: float64
121951 121958    5226.0
Name: new_cases, dtype: float64
121952 121959    0.0
Name: new_cases, dtype: float64
121953 121960    9722.0
Name: new_cases, dtype: float64
121954 121961    3889.0
Name: new_cases, dtype: float64
121955 121962    0.0
Name: new_cases, dtype: float64
121956 121963    9983.0
Name: new_cases, dtype: float64
121957 121964    5107.0
Name: new_cases, dtype: float64
121958 121965    4810.0
Name: new_cases, dtype: float64
121959 121966    4826.0
Name: new_cases, dtype: float64
121960 121967    4133.0
Name: new_cases, dtype: float64
121961 121968    3304.0
Name: new_cases, dtype: float64
121962 121969    3706.0
Name: new_cases, dtype: float64
121963 121970    4398.0
Name: new_cases, dtype: float64
121964 121971    3615.0
Name: new_cases, dtype: float64

121965 121972    3625.0
Name: new_cases, dtype: float64
121966 121973    3405.0
Name: new_cases, dtype: float64
121967 121974    3058.0
Name: new_cases, dtype: float64
121968 121975    2732.0
Name: new_cases, dtype: float64
121969 121976    2965.0
Name: new_cases, dtype: float64
121970 121977    3572.0
Name: new_cases, dtype: float64
121971 121978    3154.0
Name: new_cases, dtype: float64
121972 121979    2971.0
Name: new_cases, dtype: float64
121973 121980    2846.0
Name: new_cases, dtype: float64
121974 121981    2583.0
Name: new_cases, dtype: float64
121975 121982    2069.0
Name: new_cases, dtype: float64
121976 121983    2604.0
Name: new_cases, dtype: float64
121977 121984    2965.0
Name: new_cases, dtype: float64
121978 121985    2864.0
Name: new_cases, dtype: float64
121979 121986    2719.0
Name: new_cases, dtype: float64
121980 121987    2384.0
Name: new_cases, dtype: float64
121981 121988    2068.0
Name: new_cases, dtype: float64
121982 121989    1695.0
Name: new_cases, dtype: float64
121983 121990    1987.0
Name: new_cases, dtype: float64
121984 121991    2145.0
Name: new_cases, dtype: float64
121985 121992    2138.0
Name: new_cases, dtype: float64
121986 121993    2007.0
Name: new_cases, dtype: float64
121987 121994    1613.0
Name: new_cases, dtype: float64
121988 121995    1374.0
Name: new_cases, dtype: float64
121989 121996    989.0
Name: new_cases, dtype: float64
121990 121997    1249.0
Name: new_cases, dtype: float64
121991 121998    1304.0
Name: new_cases, dtype: float64
121992 121999    1402.0
Name: new_cases, dtype: float64
121993 122000    1366.0
Name: new_cases, dtype: float64
121994 122001    1277.0
Name: new_cases, dtype: float64
121995 122002    0.0
Name: new_cases, dtype: float64
121996 122003    1890.0
Name: new_cases, dtype: float64
121997 122004    918.0
Name: new_cases, dtype: float64
121998 122005    1125.0
Name: new_cases, dtype: float64
121999 122006    1046.0
Name: new_cases, dtype: float64
122000 122007    0.0
Name: new_cases, dtype: float64
122001 122008    1688.0
Name: new_cases, dtype: float64
122002 122009    705.0
Name: new_cases, dtype: float64
122003 122010    568.0
Name: new_cases, dtype: float64
122004 122011    575.0
Name: new_cases, dtype: float64
122005 122012    686.0
Name: new_cases, dtype: float64
122006 122013    609.0
Name: new_cases, dtype: float64
122007 122014    550.0
Name: new_cases, dtype: float64
122008 122015    391.0
Name: new_cases, dtype: float64
122009 122016    404.0
Name: new_cases, dtype: float64
122010 122017    266.0
Name: new_cases, dtype: float64
122011 122018    376.0
Name: new_cases, dtype: float64
122012 122019    414.0
Name: new_cases, dtype: float64
122013 122020    387.0
Name: new_cases, dtype: float64
122014 122021    326.0
Name: new_cases, dtype: float64
122015 122022    330.0
Name: new_cases, dtype: float64
122016 122023    274.0
Name: new_cases, dtype: float64
122017 122024    178.0
Name: new_cases, dtype: float64
122018 122025    248.0
Name: new_cases, dtype: float64
122019 122026    230.0
Name: new_cases, dtype: float64
122020 122027    287.0
Name: new_cases, dtype: float64
122021 122028    218.0
Name: new_cases, dtype: float64
122022 122029    210.0
Name: new_cases, dtype: float64
122023 122030    145.0
Name: new_cases, dtype: float64
122024 122031    116.0
Name: new_cases, dtype: float64
122025 122032    162.0
Name: new_cases, dtype: float64
122026 122033    214.0
Name: new_cases, dtype: float64
122027 122034    198.0
Name: new_cases, dtype: float64
122028 122035    210.0
Name: new_cases, dtype: float64
122029 122036    172.0
Name: new_cases, dtype: float64
122030 122037    119.0
Name: new_cases, dtype: float64
122031 122038    138.0
Name: new_cases, dtype: float64
122032 122039    124.0
Name: new_cases, dtype: float64
122033 122040    132.0
Name: new_cases, dtype: float64
122034 122041    160.0
Name: new_cases, dtype: float64
122035 122042    135.0
Name: new_cases, dtype: float64
122036 122043    162.0
Name: new_cases, dtype: float64
122037 122044    89.0
Name: new_cases, dtype: float64
122038 122045    60.0
Name: new_cases, dtype: float64
122039 122046    88.0
Name: new_cases, dtype: float64
122040 122047    72.0
Name: new_cases, dtype: float64
122041 122048    103.0
Name: new_cases, dtype: float64
122042 122049    80.0
Name: new_cases, dtype: float64
122043 122050    76.0
Name: new_cases, dtype: float64
122044 122051    66.0
Name: new_cases, dtype: float64
122045 122052    63.0
Name: new_cases, dtype: float64
122046 122053    84.0
Name: new_cases, dtype: float64
122047 122054    73.0
Name: new_cases, dtype: float64
122048 122055    104.0
Name: new_cases, dtype: float64
122049 122056    81.0
Name: new_cases, dtype: float64
122050 122057    74.0
Name: new_cases, dtype: float64
122051 122058    79.0
Name: new_cases, dtype: float64
122052 122059    77.0
Name: new_cases, dtype: float64
122053 122060    110.0
Name: new_cases, dtype: float64
122054 122061    110.0
Name: new_cases, dtype: float64
122055 122062    103.0
Name: new_cases, dtype: float64
122056 122063    97.0
Name: new_cases, dtype: float64
122057 122064    110.0
Name: new_cases, dtype: float64
122058 122065    77.0
Name: new_cases, dtype: float64
122059 122066    69.0
Name: new_cases, dtype: float64
122060 122067    118.0
Name: new_cases, dtype: float64
122061 122068    145.0
Name: new_cases, dtype: float64
122062 122069    125.0
Name: new_cases, dtype: float64
122063 122070    156.0
Name: new_cases, dtype: float64
122064 122071    206.0
Name: new_cases, dtype: float64
122065 122072    166.0
Name: new_cases, dtype: float64
122066 122073    125.0
Name: new_cases, dtype: float64
122067 122074    227.0
Name: new_cases, dtype: float64
122068 122075    189.0
Name: new_cases, dtype: float64
122069 122076    228.0
Name: new_cases, dtype: float64
122070 122077    228.0
Name: new_cases, dtype: float64
122071 122078    202.0
Name: new_cases, dtype: float64
122072 122079    249.0
Name: new_cases, dtype: float64
122073 122080    199.0
Name: new_cases, dtype: float64
122074 122081    241.0
Name: new_cases, dtype: float64
122075 122082    290.0
Name: new_cases, dtype: float64
122076 122083    332.0
Name: new_cases, dtype: float64
122077 122084    292.0
Name: new_cases, dtype: float64
122078 122085    353.0
Name: new_cases, dtype: float64
122079 122086    298.0
Name: new_cases, dtype: float64
122080 122087    303.0
Name: new_cases, dtype: float64
122081 122088    386.0
Name: new_cases, dtype: float64
122082 122089    424.0
Name: new_cases, dtype: float64
122083 122090    487.0
Name: new_cases, dtype: float64
122084 122091    579.0
Name: new_cases, dtype: float64
122085 122092    564.0
Name: new_cases, dtype: float64
122086 122093    584.0
Name: new_cases, dtype: float64
122087 122094    457.0
Name: new_cases, dtype: float64
122088 122095    752.0
Name: new_cases, dtype: float64
122089 122096    792.0
Name: new_cases, dtype: float64
122090 122097    921.0
Name: new_cases, dtype: float64
122091 122098    983.0
Name: new_cases, dtype: float64
122092 122099    1072.0
Name: new_cases, dtype: float64
122093 122100    1005.0
Name: new_cases, dtype: float64
122094 122101    817.0
Name: new_cases, dtype: float64
122095 122102    1288.0
Name: new_cases, dtype: float64
122096 122103    1484.0
Name: new_cases, dtype: float64
122097 122104    1497.0
Name: new_cases, dtype: float64
122098 122105    1656.0
Name: new_cases, dtype: float64
122099 122106    1592.0
Name: new_cases, dtype: float64
122100 122107    1510.0
Name: new_cases, dtype: float64
122101 122108    1242.0
Name: new_cases, dtype: float64
122102 122109    1837.0
Name: new_cases, dtype: float64
122103 122110    2216.0
Name: new_cases, dtype: float64
122104 122111    2327.0
Name: new_cases, dtype: float64
122105 122112    2454.0
Name: new_cases, dtype: float64
122106 122113    2434.0
Name: new_cases, dtype: float64
122107 122114    2314.0
Name: new_cases, dtype: float64
122108 122115    1722.0
Name: new_cases, dtype: float64
122109 122116    2335.0
Name: new_cases, dtype: float64
122110 122117    2981.0
Name: new_cases, dtype: float64
122111 122118    3346.0
Name: new_cases, dtype: float64
122112 122119    3524.0
Name: new_cases, dtype: float64
122113 122120    3623.0
Name: new_cases, dtype: float64
122114 122121    3497.0
Name: new_cases, dtype: float64
122115 122122    2800.0
Name: new_cases, dtype: float64
122116 122123    4103.0
Name: new_cases, dtype: float64
122117 122124    5069.0
Name: new_cases, dtype: float64
122118 122125    5633.0
Name: new_cases, dtype: float64

122119 122126    5831.0
Name: new_cases, dtype: float64
122120 122127    6089.0
Name: new_cases, dtype: float64
122121 122128    5461.0
Name: new_cases, dtype: float64
122122 122129    5003.0
Name: new_cases, dtype: float64
122123 122130    6249.0
Name: new_cases, dtype: float64
122124 122131    7723.0
Name: new_cases, dtype: float64
122125 122132    7628.0
Name: new_cases, dtype: float64
122126 122133    7602.0
Name: new_cases, dtype: float64
122127 122134    7572.0
Name: new_cases, dtype: float64
122128 122135    6745.0
Name: new_cases, dtype: float64
122129 122136    5255.0
Name: new_cases, dtype: float64
122130 122137    6424.0
Name: new_cases, dtype: float64
122131 122138    7232.0
Name: new_cases, dtype: float64
122132 122139    7201.0
Name: new_cases, dtype: float64
122133 122140    6480.0
Name: new_cases, dtype: float64
122134 122141    6462.0
Name: new_cases, dtype: float64
122135 122142    6192.0
Name: new_cases, dtype: float64
122136 122143    5389.0
Name: new_cases, dtype: float64
122137 122144    6736.0
Name: new_cases, dtype: float64
122138 122145    8467.0
Name: new_cases, dtype: float64
122139 122146    8171.0
Name: new_cases, dtype: float64
122140 122147    7549.0
Name: new_cases, dtype: float64
122141 122148    7271.0
Name: new_cases, dtype: float64
122142 122149    6412.0
Name: new_cases, dtype: float64
122143 122150    5334.0
Name: new_cases, dtype: float64
122144 122151    5983.0
Name: new_cases, dtype: float64
122145 122152    7190.0
Name: new_cases, dtype: float64
122146 122153    7150.0
Name: new_cases, dtype: float64
122147 122154    6978.0
Name: new_cases, dtype: float64
122148 122155    6401.0
Name: new_cases, dtype: float64
122149 122156    5657.0
Name: new_cases, dtype: float64
122150 122157    4803.0
Name: new_cases, dtype: float64
122151 122158    5700.0
Name: new_cases, dtype: float64
122152 122159    6930.0
Name: new_cases, dtype: float64
122153 122160    6699.0
Name: new_cases, dtype: float64
122154 122161    6786.0
Name: new_cases, dtype: float64
122155 122162    6424.0
Name: new_cases, dtype: float64
122156 122163    6051.0
Name: new_cases, dtype: float64
122157 122164    5077.0
Name: new_cases, dtype: float64
122158 122165    6461.0
Name: new_cases, dtype: float64
122159 122166    7664.0
Name: new_cases, dtype: float64
122160 122167    7745.0
Name: new_cases, dtype: float64
122161 122168    7327.0
Name: new_cases, dtype: float64
122162 122169    7696.0
Name: new_cases, dtype: float64
122163 122170    6748.0
Name: new_cases, dtype: float64
122164 122171    5733.0
Name: new_cases, dtype: float64
122165 122172    5908.0
Name: new_cases, dtype: float64
122166 122173    7840.0
Name: new_cases, dtype: float64
122167 122174    6948.0
Name: new_cases, dtype: float64
122168 122175    6697.0
Name: new_cases, dtype: float64
122169 122176    6217.0
Name: new_cases, dtype: float64
122170 122177    6001.0
Name: new_cases, dtype: float64
122171 122178    4929.0
Name: new_cases, dtype: float64
122172 122179    5896.0
Name: new_cases, dtype: float64
122173 122180    7111.0
Name: new_cases, dtype: float64
122174 122181    6726.0
Name: new_cases, dtype: float64
122175 122182    6126.0
Name: new_cases, dtype: float64
122176 122183    5725.0
Name: new_cases, dtype: float64
122177 122184    4804.0
Name: new_cases, dtype: float64
122178 122185    3888.0
Name: new_cases, dtype: float64
122179 122186    4348.0
Name: new_cases, dtype: float64
122180 122187    5103.0
Name: new_cases, dtype: float64
122181 122188    4606.0
Name: new_cases, dtype: float64
122182 122189    3998.0
Name: new_cases, dtype: float64
122183 122190    3822.0
Name: new_cases, dtype: float64
122184 122191    3484.0
Name: new_cases, dtype: float64
122185 122192    2777.0
Name: new_cases, dtype: float64
122186 122193    3487.0
Name: new_cases, dtype: float64
122187 122194    3773.0
Name: new_cases, dtype: float64
122188 122195    3600.0
Name: new_cases, dtype: float64
122189 122196    3219.0
Name: new_cases, dtype: float64
122190 122197    3086.0
Name: new_cases, dtype: float64
122191 122198    2648.0
Name: new_cases, dtype: float64
122192 122199    2081.0
Name: new_cases, dtype: float64
122193 122200    2771.0
Name: new_cases, dtype: float64
122194 122201    3033.0
Name: new_cases, dtype: float64
122195 122202    2631.0
Name: new_cases, dtype: float64
122196 122203    2677.0
Name: new_cases, dtype: float64
122197 122204    2339.0
Name: new_cases, dtype: float64
122198 122205    2211.0
Name: new_cases, dtype: float64
122199 122206    1674.0
Name: new_cases, dtype: float64
122200 122207    2180.0
Name: new_cases, dtype: float64
122201 122208    2272.0
Name: new_cases, dtype: float64
122202 122209    2180.0
Name: new_cases, dtype: float64
122203 122210    1980.0
Name: new_cases, dtype: float64
122204 122211    1801.0
Name: new_cases, dtype: float64
122205 122212    1613.0
Name: new_cases, dtype: float64
122206 122213    1244.0
Name: new_cases, dtype: float64
122207 122214    1565.0
Name: new_cases, dtype: float64
122208 122215    1884.0
Name: new_cases, dtype: float64
122209 122216    1675.0
Name: new_cases, dtype: float64
122210 122217    1620.0
Name: new_cases, dtype: float64
122211 122218    1387.0
Name: new_cases, dtype: float64
122212 122219    1309.0
Name: new_cases, dtype: float64
122213 122220    944.0
Name: new_cases, dtype: float64
122214 122221    1167.0
Name: new_cases, dtype: float64
122215 122222    1547.0
Name: new_cases, dtype: float64
122216 122223    1359.0
Name: new_cases, dtype: float64
122217 122224    1325.0
Name: new_cases, dtype: float64
122218 122225    1199.0
Name: new_cases, dtype: float64
122219 122226    1015.0
Name: new_cases, dtype: float64
122220 122227    802.0
Name: new_cases, dtype: float64
122221 122228    0.0
Name: new_cases, dtype: float64
122222 122229    2296.0
Name: new_cases, dtype: float64
122223 122230    1268.0
Name: new_cases, dtype: float64
122224 122231    1177.0
Name: new_cases, dtype: float64
122225 122232    1193.0
Name: new_cases, dtype: float64
122226 122233    1098.0
Name: new_cases, dtype: float64
122227 122234    976.0
Name: new_cases, dtype: float64
122228 122235    1249.0
Name: new_cases, dtype: float64
122229 122236    1676.0
Name: new_cases, dtype: float64
122230 122237    1804.0
Name: new_cases, dtype: float64
122231 122238    1949.0
Name: new_cases, dtype: float64
122232 122239    2192.0
Name: new_cases, dtype: float64
122233 122240    1610.0
Name: new_cases, dtype: float64
122234 122241    1907.0
Name: new_cases, dtype: float64
122235 122242    2765.0
Name: new_cases, dtype: float64
122236 122243    5224.0
Name: new_cases, dtype: float64
122237 122244    7488.0
Name: new_cases, dtype: float64
122238 122245    9122.0
Name: new_cases, dtype: float64
122239 122246    7539.0
Name: new_cases, dtype: float64
122240 122247    7652.0
Name: new_cases, dtype: float64
122241 Series([], Name: new_cases, dtype: float64)
122242 Series([], Name: new_cases, dtype: float64)
122243 Series([], Name: new_cases, dtype: float64)
122244 Series([], Name: new_cases, dtype: float64)
122245 Series([], Name: new_cases, dtype: float64)
122246 Series([], Name: new_cases, dtype: float64)
122247 Series([], Name: new_cases, dtype: float64)
123562 123569    3.0
Name: new_cases, dtype: float64
123563 123570    3.0
Name: new_cases, dtype: float64
123564 123571    3.0
Name: new_cases, dtype: float64
123565 123572    2.0
Name: new_cases, dtype: float64
123566 123573    0.0
Name: new_cases, dtype: float64
123567 123574    6.0
Name: new_cases, dtype: float64
123568 123575    4.0
Name: new_cases, dtype: float64
123569 123576    0.0
Name: new_cases, dtype: float64
123570 123577    2.0
Name: new_cases, dtype: float64
123571 123578    3.0
Name: new_cases, dtype: float64
123572 123579    7.0
Name: new_cases, dtype: float64
123573 123580    5.0
Name: new_cases, dtype: float64
123574 123581    2.0
Name: new_cases, dtype: float64
123575 123582    3.0
Name: new_cases, dtype: float64
123576 123583    8.0
Name: new_cases, dtype: float64
123577 123584    9.0
Name: new_cases, dtype: float64
123578 123585    5.0
Name: new_cases, dtype: float64
123579 123586    3.0
Name: new_cases, dtype: float64
123580 123587    2.0
Name: new_cases, dtype: float64
123581 123588    4.0
Name: new_cases, dtype: float64
123582 123589    3.0
Name: new_cases, dtype: float64
123583 123590    0.0
Name: new_cases, dtype: float64
123584 123591    1.0
Name: new_cases, dtype: float64
123585 123592    0.0
Name: new_cases, dtype: float64
123586 123593    4.0
Name: new_cases, dtype: float64
123587 123594    0.0
Name: new_cases, dtype: float64
123588 123595    2.0
Name: new_cases, dtype: float64
123589 123596    2.0
Name: new_cases, dtype: float64
123590 123597    0.0
Name: new_cases, dtype: float64
123591 123598    0.0
Name: new_cases, dtype: float64
123592 123599    9.0
Name: new_cases, dtype: float64
123593 123600    4.0
Name: new_cases, dtype: float64
123594 123601    2.0
Name: new_cases, dtype: float64
123595 123602    2.0
Name: new_cases, dtype: float64
123596 123603    0.0
Name: new_cases, dtype: float64
123597 123604    7.0
Name: new_cases, dtype: float64
123598 123605    13.0
Name: new_cases, dtype: float64
123599 123606    8.0
Name: new_cases, dtype: float64
123600 123607    12.0
Name: new_cases, dtype: float64
123601 123608    0.0
Name: new_cases, dtype: float64
123602 123609    10.0
Name: new_cases, dtype: float64
123603 123610    18.0
Name: new_cases, dtype: float64
123604 123611    0.0
Name: new_cases, dtype: float64

123605 123612    22.0
Name: new_cases, dtype: float64
123606 123613    12.0
Name: new_cases, dtype: float64
123607 123614    14.0
Name: new_cases, dtype: float64
123608 123615    17.0
Name: new_cases, dtype: float64
123609 123616    23.0
Name: new_cases, dtype: float64
123610 123617    47.0
Name: new_cases, dtype: float64
123611 123618    32.0
Name: new_cases, dtype: float64
123612 123619    40.0
Name: new_cases, dtype: float64
123613 123620    47.0
Name: new_cases, dtype: float64
123614 123621    23.0
Name: new_cases, dtype: float64
123615 123622    54.0
Name: new_cases, dtype: float64
123616 123623    49.0
Name: new_cases, dtype: float64
123617 123624    73.0
Name: new_cases, dtype: float64
123618 123625    52.0
Name: new_cases, dtype: float64
123619 123626    49.0
Name: new_cases, dtype: float64
123620 123627    70.0
Name: new_cases, dtype: float64
123621 123628    42.0
Name: new_cases, dtype: float64
123622 123629    35.0
Name: new_cases, dtype: float64
123623 123630    47.0
Name: new_cases, dtype: float64
123624 123631    74.0
Name: new_cases, dtype: float64
123625 123632    49.0
Name: new_cases, dtype: float64
123626 123633    65.0
Name: new_cases, dtype: float64
123627 123634    75.0
Name: new_cases, dtype: float64
123628 123635    120.0
Name: new_cases, dtype: float64
123629 123636    66.0
Name: new_cases, dtype: float64
123630 123637    106.0
Name: new_cases, dtype: float64
123631 123638    142.0
Name: new_cases, dtype: float64
123632 123639    287.0
Name: new_cases, dtype: float64
123633 123640    198.0
Name: new_cases, dtype: float64
123634 123641    191.0
Name: new_cases, dtype: float64
123635 123642    233.0
Name: new_cases, dtype: float64
123636 123643    386.0
Name: new_cases, dtype: float64
123637 123644    334.0
Name: new_cases, dtype: float64
123638 123645    447.0
Name: new_cases, dtype: float64
123639 123646    728.0
Name: new_cases, dtype: float64
123640 123647    623.0
Name: new_cases, dtype: float64
123641 123648    942.0
Name: new_cases, dtype: float64
123642 123649    596.0
Name: new_cases, dtype: float64
123643 123650    1426.0
Name: new_cases, dtype: float64
123644 123651    1111.0
Name: new_cases, dtype: float64
123645 123652    1016.0
Name: new_cases, dtype: float64
123646 123653    1037.0
Name: new_cases, dtype: float64
123647 123654    897.0
Name: new_cases, dtype: float64
123648 123655    618.0
Name: new_cases, dtype: float64
123649 123656    931.0
Name: new_cases, dtype: float64
123650 123657    799.0
Name: new_cases, dtype: float64
123651 123658    528.0
Name: new_cases, dtype: float64
123652 123659    690.0
Name: new_cases, dtype: float64
123653 123660    528.0
Name: new_cases, dtype: float64
123654 123661    932.0
Name: new_cases, dtype: float64
123655 123662    447.0
Name: new_cases, dtype: float64
123656 123663    657.0
Name: new_cases, dtype: float64
123657 123664    573.0
Name: new_cases, dtype: float64
123658 123665    632.0
Name: new_cases, dtype: float64
123659 123666    788.0
Name: new_cases, dtype: float64
123660 123667    741.0
Name: new_cases, dtype: float64
123661 123668    768.0
Name: new_cases, dtype: float64
123662 123669    753.0
Name: new_cases, dtype: float64
123663 123670    876.0
Name: new_cases, dtype: float64
123664 123671    486.0
Name: new_cases, dtype: float64
123665 123672    849.0
Name: new_cases, dtype: float64
123666 123673    675.0
Name: new_cases, dtype: float64
123667 123674    752.0
Name: new_cases, dtype: float64
123668 123675    793.0
Name: new_cases, dtype: float64
123669 123676    465.0
Name: new_cases, dtype: float64
123670 123677    682.0
Name: new_cases, dtype: float64
123671 123678    305.0
Name: new_cases, dtype: float64
123672 123679    451.0
Name: new_cases, dtype: float64
123673 123680    570.0
Name: new_cases, dtype: float64
123674 123681    448.0
Name: new_cases, dtype: float64
123675 123682    614.0
Name: new_cases, dtype: float64
123676 123683    642.0
Name: new_cases, dtype: float64
123677 123684    548.0
Name: new_cases, dtype: float64
123678 123685    344.0
Name: new_cases, dtype: float64
123679 123686    383.0
Name: new_cases, dtype: float64
123680 123687    533.0
Name: new_cases, dtype: float64
123681 123688    373.0
Name: new_cases, dtype: float64
123682 123689    611.0
Name: new_cases, dtype: float64
123683 123690    506.0
Name: new_cases, dtype: float64
123684 123691    518.0
Name: new_cases, dtype: float64
123685 123692    408.0
Name: new_cases, dtype: float64
123686 123693    544.0
Name: new_cases, dtype: float64
123687 123694    569.0
Name: new_cases, dtype: float64
123688 123695    517.0
Name: new_cases, dtype: float64
123689 123696    261.0
Name: new_cases, dtype: float64
123690 123697    344.0
Name: new_cases, dtype: float64
123691 123698    383.0
Name: new_cases, dtype: float64
123692 123699    386.0
Name: new_cases, dtype: float64
123693 123700    218.0
Name: new_cases, dtype: float64
123694 123701    451.0
Name: new_cases, dtype: float64
123695 123702    422.0
Name: new_cases, dtype: float64
123696 123703    463.0
Name: new_cases, dtype: float64
123697 123704    347.0
Name: new_cases, dtype: float64
123698 123705    407.0
Name: new_cases, dtype: float64
123699 123706    214.0
Name: new_cases, dtype: float64
123700 123707    151.0
Name: new_cases, dtype: float64
123701 123708    247.0
Name: new_cases, dtype: float64
123702 123709    257.0
Name: new_cases, dtype: float64
123703 123710    142.0
Name: new_cases, dtype: float64
123704 123711    218.0
Name: new_cases, dtype: float64
123705 123712    262.0
Name: new_cases, dtype: float64
123706 123713    218.0
Name: new_cases, dtype: float64
123707 123714    119.0
Name: new_cases, dtype: float64
123708 123715    191.0
Name: new_cases, dtype: float64
123709 123716    113.0
Name: new_cases, dtype: float64
123710 123717    219.0
Name: new_cases, dtype: float64
123711 123718    291.0
Name: new_cases, dtype: float64
123712 123719    213.0
Name: new_cases, dtype: float64
123713 123720    202.0
Name: new_cases, dtype: float64
123714 123721    246.0
Name: new_cases, dtype: float64
123715 123722    215.0
Name: new_cases, dtype: float64
123716 123723    188.0
Name: new_cases, dtype: float64
123717 123724    169.0
Name: new_cases, dtype: float64
123718 123725    185.0
Name: new_cases, dtype: float64
123719 123726    136.0
Name: new_cases, dtype: float64
123720 123727    183.0
Name: new_cases, dtype: float64
123721 123728    157.0
Name: new_cases, dtype: float64
123722 123729    158.0
Name: new_cases, dtype: float64
123723 123730    125.0
Name: new_cases, dtype: float64
123724 123731    191.0
Name: new_cases, dtype: float64
123725 123732    169.0
Name: new_cases, dtype: float64
123726 123733    178.0
Name: new_cases, dtype: float64
123727 123734    322.0
Name: new_cases, dtype: float64
123728 123735    347.0
Name: new_cases, dtype: float64
123729 123736    248.0
Name: new_cases, dtype: float64
123730 123737    248.0
Name: new_cases, dtype: float64
123731 123738    327.0
Name: new_cases, dtype: float64
123732 123739    202.0
Name: new_cases, dtype: float64
123733 123740    257.0
Name: new_cases, dtype: float64
123734 123741    123.0
Name: new_cases, dtype: float64
123735 123742    399.0
Name: new_cases, dtype: float64
123736 123743    310.0
Name: new_cases, dtype: float64
123737 123744    354.0
Name: new_cases, dtype: float64
123738 123745    277.0
Name: new_cases, dtype: float64
123739 123746    513.0
Name: new_cases, dtype: float64
123740 123747    481.0
Name: new_cases, dtype: float64
123741 123748    469.0
Name: new_cases, dtype: float64
123742 123749    359.0
Name: new_cases, dtype: float64
123743 123750    334.0
Name: new_cases, dtype: float64
123744 123751    278.0
Name: new_cases, dtype: float64
123745 123752    396.0
Name: new_cases, dtype: float64
123746 123753    307.0
Name: new_cases, dtype: float64
123747 123754    313.0
Name: new_cases, dtype: float64
123748 123755    226.0
Name: new_cases, dtype: float64
123749 123756    295.0
Name: new_cases, dtype: float64
123750 123757    908.0
Name: new_cases, dtype: float64
123751 123758    301.0
Name: new_cases, dtype: float64
123752 123759    242.0
Name: new_cases, dtype: float64
123753 123760    132.0
Name: new_cases, dtype: float64
123754 123761    175.0
Name: new_cases, dtype: float64
123755 123762    188.0
Name: new_cases, dtype: float64
123756 123763    61.0
Name: new_cases, dtype: float64
123757 123764    42.0
Name: new_cases, dtype: float64
123758 123765    102.0
Name: new_cases, dtype: float64
123759 123766    83.0
Name: new_cases, dtype: float64
123760 123767    81.0
Name: new_cases, dtype: float64
123761 123768    86.0
Name: new_cases, dtype: float64
123762 123769    91.0
Name: new_cases, dtype: float64
123763 123770    100.0
Name: new_cases, dtype: float64
123764 123771    93.0
Name: new_cases, dtype: float64
123765 123772    68.0
Name: new_cases, dtype: float64
123766 123773    117.0
Name: new_cases, dtype: float64
123767 123774    50.0
Name: new_cases, dtype: float64
123768 123775    87.0
Name: new_cases, dtype: float64
123769 123776    51.0
Name: new_cases, dtype: float64
123770 123777    31.0
Name: new_cases, dtype: float64

123771 123778    60.0
Name: new_cases, dtype: float64
123772 123779    77.0
Name: new_cases, dtype: float64
123773 123780    94.0
Name: new_cases, dtype: float64
123774 123781    51.0
Name: new_cases, dtype: float64
123775 123782    54.0
Name: new_cases, dtype: float64
123776 123783    41.0
Name: new_cases, dtype: float64
123777 123784    40.0
Name: new_cases, dtype: float64
123778 123785    8.0
Name: new_cases, dtype: float64
123779 123786    48.0
Name: new_cases, dtype: float64
123780 123787    40.0
Name: new_cases, dtype: float64
123781 123788    34.0
Name: new_cases, dtype: float64
123782 123789    40.0
Name: new_cases, dtype: float64
123783 123790    22.0
Name: new_cases, dtype: float64
123784 123791    47.0
Name: new_cases, dtype: float64
123785 123792    75.0
Name: new_cases, dtype: float64
123786 123793    63.0
Name: new_cases, dtype: float64
123787 123794    86.0
Name: new_cases, dtype: float64
123788 123795    42.0
Name: new_cases, dtype: float64
123789 123796    49.0
Name: new_cases, dtype: float64
123790 123797    48.0
Name: new_cases, dtype: float64
123791 123798    34.0
Name: new_cases, dtype: float64
123792 123799    26.0
Name: new_cases, dtype: float64
123793 123800    18.0
Name: new_cases, dtype: float64
123794 123801    11.0
Name: new_cases, dtype: float64
123795 123802    15.0
Name: new_cases, dtype: float64
123796 123803    18.0
Name: new_cases, dtype: float64
123797 123804    30.0
Name: new_cases, dtype: float64
123798 123805    21.0
Name: new_cases, dtype: float64
123799 123806    12.0
Name: new_cases, dtype: float64
123800 123807    15.0
Name: new_cases, dtype: float64
123801 123808    11.0
Name: new_cases, dtype: float64
123802 123809    20.0
Name: new_cases, dtype: float64
123803 123810    15.0
Name: new_cases, dtype: float64
123804 123811    15.0
Name: new_cases, dtype: float64
123805 123812    27.0
Name: new_cases, dtype: float64
123806 123813    23.0
Name: new_cases, dtype: float64
123807 123814    19.0
Name: new_cases, dtype: float64
123808 123815    10.0
Name: new_cases, dtype: float64
123809 123816    6.0
Name: new_cases, dtype: float64
123810 123817    12.0
Name: new_cases, dtype: float64
123811 123818    7.0
Name: new_cases, dtype: float64
123812 123819    11.0
Name: new_cases, dtype: float64
123813 123820    10.0
Name: new_cases, dtype: float64
123814 123821    9.0
Name: new_cases, dtype: float64
123815 123822    10.0
Name: new_cases, dtype: float64
123816 123823    7.0
Name: new_cases, dtype: float64
123817 123824    10.0
Name: new_cases, dtype: float64
123818 123825    4.0
Name: new_cases, dtype: float64
123819 123826    4.0
Name: new_cases, dtype: float64
123820 123827    5.0
Name: new_cases, dtype: float64
123821 123828    3.0
Name: new_cases, dtype: float64
123822 123829    9.0
Name: new_cases, dtype: float64
123823 123830    3.0
Name: new_cases, dtype: float64
123824 123831    7.0
Name: new_cases, dtype: float64
123825 123832    4.0
Name: new_cases, dtype: float64
123826 123833    6.0
Name: new_cases, dtype: float64
123827 123834    12.0
Name: new_cases, dtype: float64
123828 123835    8.0
Name: new_cases, dtype: float64
123829 123836    10.0
Name: new_cases, dtype: float64
123830 123837    14.0
Name: new_cases, dtype: float64
123831 123838    5.0
Name: new_cases, dtype: float64
123832 123839    3.0
Name: new_cases, dtype: float64
123833 123840    7.0
Name: new_cases, dtype: float64
123834 123841    7.0
Name: new_cases, dtype: float64
123835 123842    7.0
Name: new_cases, dtype: float64
123836 123843    9.0
Name: new_cases, dtype: float64
123837 123844    12.0
Name: new_cases, dtype: float64
123838 123845    4.0
Name: new_cases, dtype: float64
123839 123846    1.0
Name: new_cases, dtype: float64
123840 123847    9.0
Name: new_cases, dtype: float64
123841 123848    7.0
Name: new_cases, dtype: float64
123842 123849    7.0
Name: new_cases, dtype: float64
123843 123850    4.0
Name: new_cases, dtype: float64
123844 123851    7.0
Name: new_cases, dtype: float64
123845 123852    2.0
Name: new_cases, dtype: float64
123846 123853    8.0
Name: new_cases, dtype: float64
123847 123854    9.0
Name: new_cases, dtype: float64
123848 123855    18.0
Name: new_cases, dtype: float64
123849 123856    11.0
Name: new_cases, dtype: float64
123850 123857    12.0
Name: new_cases, dtype: float64
123851 123858    2.0
Name: new_cases, dtype: float64
123852 123859    3.0
Name: new_cases, dtype: float64
123853 123860    5.0
Name: new_cases, dtype: float64
123854 123861    6.0
Name: new_cases, dtype: float64
123855 123862    5.0
Name: new_cases, dtype: float64
123856 123863    4.0
Name: new_cases, dtype: float64
123857 123864    4.0
Name: new_cases, dtype: float64
123858 123865    5.0
Name: new_cases, dtype: float64
123859 123866    12.0
Name: new_cases, dtype: float64
123860 123867    5.0
Name: new_cases, dtype: float64
123861 123868    18.0
Name: new_cases, dtype: float64
123862 123869    7.0
Name: new_cases, dtype: float64
123863 123870    5.0
Name: new_cases, dtype: float64
123864 123871    4.0
Name: new_cases, dtype: float64
123865 123872    6.0
Name: new_cases, dtype: float64
123866 123873    8.0
Name: new_cases, dtype: float64
123867 123874    5.0
Name: new_cases, dtype: float64
123868 123875    10.0
Name: new_cases, dtype: float64
123869 123876    2.0
Name: new_cases, dtype: float64
123870 123877    9.0
Name: new_cases, dtype: float64
123871 123878    3.0
Name: new_cases, dtype: float64
123872 123879    13.0
Name: new_cases, dtype: float64
123873 123880    5.0
Name: new_cases, dtype: float64
123874 123881    13.0
Name: new_cases, dtype: float64
123875 123882    12.0
Name: new_cases, dtype: float64
123876 123883    6.0
Name: new_cases, dtype: float64
123877 123884    6.0
Name: new_cases, dtype: float64
123878 123885    8.0
Name: new_cases, dtype: float64
123879 123886    8.0
Name: new_cases, dtype: float64
123880 123887    7.0
Name: new_cases, dtype: float64
123881 123888    5.0
Name: new_cases, dtype: float64
123882 123889    16.0
Name: new_cases, dtype: float64
123883 123890    12.0
Name: new_cases, dtype: float64
123884 123891    24.0
Name: new_cases, dtype: float64
123885 123892    9.0
Name: new_cases, dtype: float64
123886 123893    17.0
Name: new_cases, dtype: float64
123887 123894    19.0
Name: new_cases, dtype: float64
123888 123895    10.0
Name: new_cases, dtype: float64
123889 123896    29.0
Name: new_cases, dtype: float64
123890 123897    21.0
Name: new_cases, dtype: float64
123891 123898    13.0
Name: new_cases, dtype: float64
123892 123899    14.0
Name: new_cases, dtype: float64
123893 123900    10.0
Name: new_cases, dtype: float64
123894 123901    5.0
Name: new_cases, dtype: float64
123895 123902    5.0
Name: new_cases, dtype: float64
123896 123903    13.0
Name: new_cases, dtype: float64
123897 123904    27.0
Name: new_cases, dtype: float64
123898 123905    30.0
Name: new_cases, dtype: float64
123899 123906    30.0
Name: new_cases, dtype: float64
123900 123907    33.0
Name: new_cases, dtype: float64
123901 123908    35.0
Name: new_cases, dtype: float64
123902 123909    24.0
Name: new_cases, dtype: float64
123903 123910    28.0
Name: new_cases, dtype: float64
123904 123911    31.0
Name: new_cases, dtype: float64
123905 123912    33.0
Name: new_cases, dtype: float64
123906 123913    23.0
Name: new_cases, dtype: float64
123907 123914    29.0
Name: new_cases, dtype: float64
123908 123915    42.0
Name: new_cases, dtype: float64
123909 123916    22.0
Name: new_cases, dtype: float64
123910 123917    17.0
Name: new_cases, dtype: float64
123911 123918    38.0
Name: new_cases, dtype: float64
123912 123919    45.0
Name: new_cases, dtype: float64
123913 123920    30.0
Name: new_cases, dtype: float64
123914 123921    24.0
Name: new_cases, dtype: float64
123915 123922    30.0
Name: new_cases, dtype: float64
123916 123923    14.0
Name: new_cases, dtype: float64
123917 123924    30.0
Name: new_cases, dtype: float64
123918 123925    40.0
Name: new_cases, dtype: float64
123919 123926    38.0
Name: new_cases, dtype: float64
123920 123927    15.0
Name: new_cases, dtype: float64
123921 123928    10.0
Name: new_cases, dtype: float64
123922 123929    48.0
Name: new_cases, dtype: float64
123923 123930    44.0
Name: new_cases, dtype: float64
123924 123931    14.0
Name: new_cases, dtype: float64
123925 123932    25.0
Name: new_cases, dtype: float64
123926 123933    34.0
Name: new_cases, dtype: float64
123927 123934    24.0
Name: new_cases, dtype: float64
123928 123935    58.0
Name: new_cases, dtype: float64
123929 123936    29.0
Name: new_cases, dtype: float64
123930 123937    29.0
Name: new_cases, dtype: float64
123931 123938    19.0
Name: new_cases, dtype: float64
123932 123939    18.0
Name: new_cases, dtype: float64

123933 123940    22.0
Name: new_cases, dtype: float64
123934 123941    25.0
Name: new_cases, dtype: float64
123935 123942    26.0
Name: new_cases, dtype: float64
123936 123943    24.0
Name: new_cases, dtype: float64
123937 123944    22.0
Name: new_cases, dtype: float64
123938 123945    11.0
Name: new_cases, dtype: float64
123939 123946    15.0
Name: new_cases, dtype: float64
123940 123947    12.0
Name: new_cases, dtype: float64
123941 123948    18.0
Name: new_cases, dtype: float64
123942 123949    9.0
Name: new_cases, dtype: float64
123943 123950    14.0
Name: new_cases, dtype: float64
123944 123951    9.0
Name: new_cases, dtype: float64
123945 123952    1.0
Name: new_cases, dtype: float64
123946 123953    11.0
Name: new_cases, dtype: float64
123947 123954    11.0
Name: new_cases, dtype: float64
123948 123955    14.0
Name: new_cases, dtype: float64
123949 123956    12.0
Name: new_cases, dtype: float64
123950 123957    11.0
Name: new_cases, dtype: float64
123951 123958    10.0
Name: new_cases, dtype: float64
123952 123959    4.0
Name: new_cases, dtype: float64
123953 123960    7.0
Name: new_cases, dtype: float64
123954 123961    10.0
Name: new_cases, dtype: float64
123955 123962    13.0
Name: new_cases, dtype: float64
123956 123963    12.0
Name: new_cases, dtype: float64
123957 123964    11.0
Name: new_cases, dtype: float64
123958 123965    12.0
Name: new_cases, dtype: float64
123959 123966    8.0
Name: new_cases, dtype: float64
123960 123967    23.0
Name: new_cases, dtype: float64
123961 123968    19.0
Name: new_cases, dtype: float64
123962 123969    9.0
Name: new_cases, dtype: float64
123963 123970    13.0
Name: new_cases, dtype: float64
123964 123971    13.0
Name: new_cases, dtype: float64
123965 123972    13.0
Name: new_cases, dtype: float64
123966 123973    6.0
Name: new_cases, dtype: float64
123967 123974    10.0
Name: new_cases, dtype: float64
123968 123975    8.0
Name: new_cases, dtype: float64
123969 123976    10.0
Name: new_cases, dtype: float64
123970 123977    8.0
Name: new_cases, dtype: float64
123971 123978    17.0
Name: new_cases, dtype: float64
123972 123979    12.0
Name: new_cases, dtype: float64
123973 123980    11.0
Name: new_cases, dtype: float64
123974 123981    9.0
Name: new_cases, dtype: float64
123975 123982    15.0
Name: new_cases, dtype: float64
123976 123983    15.0
Name: new_cases, dtype: float64
123977 123984    17.0
Name: new_cases, dtype: float64
123978 123985    12.0
Name: new_cases, dtype: float64
123979 123986    12.0
Name: new_cases, dtype: float64
123980 123987    13.0
Name: new_cases, dtype: float64
123981 123988    15.0
Name: new_cases, dtype: float64
123982 123989    17.0
Name: new_cases, dtype: float64
123983 123990    12.0
Name: new_cases, dtype: float64
123984 123991    23.0
Name: new_cases, dtype: float64
123985 123992    12.0
Name: new_cases, dtype: float64
123986 123993    21.0
Name: new_cases, dtype: float64
123987 123994    26.0
Name: new_cases, dtype: float64
123988 123995    34.0
Name: new_cases, dtype: float64
123989 123996    26.0
Name: new_cases, dtype: float64
123990 123997    43.0
Name: new_cases, dtype: float64
123991 123998    18.0
Name: new_cases, dtype: float64
123992 123999    10.0
Name: new_cases, dtype: float64
123993 124000    17.0
Name: new_cases, dtype: float64
123994 124001    24.0
Name: new_cases, dtype: float64
123995 124002    35.0
Name: new_cases, dtype: float64
123996 124003    21.0
Name: new_cases, dtype: float64
123997 124004    26.0
Name: new_cases, dtype: float64
123998 124005    32.0
Name: new_cases, dtype: float64
123999 124006    20.0
Name: new_cases, dtype: float64
124000 124007    25.0
Name: new_cases, dtype: float64
124001 124008    14.0
Name: new_cases, dtype: float64
124002 124009    27.0
Name: new_cases, dtype: float64
124003 124010    16.0
Name: new_cases, dtype: float64
124004 124011    34.0
Name: new_cases, dtype: float64
124005 124012    39.0
Name: new_cases, dtype: float64
124006 124013    23.0
Name: new_cases, dtype: float64
124007 124014    20.0
Name: new_cases, dtype: float64
124008 124015    14.0
Name: new_cases, dtype: float64
124009 124016    15.0
Name: new_cases, dtype: float64
124010 124017    24.0
Name: new_cases, dtype: float64
124011 124018    39.0
Name: new_cases, dtype: float64
124012 124019    23.0
Name: new_cases, dtype: float64
124013 124020    40.0
Name: new_cases, dtype: float64
124014 124021    45.0
Name: new_cases, dtype: float64
124015 124022    12.0
Name: new_cases, dtype: float64
124016 124023    23.0
Name: new_cases, dtype: float64
124017 124024    35.0
Name: new_cases, dtype: float64
124018 124025    24.0
Name: new_cases, dtype: float64
124019 124026    34.0
Name: new_cases, dtype: float64
124020 124027    39.0
Name: new_cases, dtype: float64
124021 124028    17.0
Name: new_cases, dtype: float64
124022 124029    17.0
Name: new_cases, dtype: float64
124023 124030    16.0
Name: new_cases, dtype: float64
124024 124031    18.0
Name: new_cases, dtype: float64
124025 124032    25.0
Name: new_cases, dtype: float64
124026 124033    20.0
Name: new_cases, dtype: float64
124027 124034    28.0
Name: new_cases, dtype: float64
124028 124035    19.0
Name: new_cases, dtype: float64
124029 124036    25.0
Name: new_cases, dtype: float64
124030 124037    16.0
Name: new_cases, dtype: float64
124031 124038    34.0
Name: new_cases, dtype: float64
124032 124039    52.0
Name: new_cases, dtype: float64
124033 124040    31.0
Name: new_cases, dtype: float64
124034 124041    49.0
Name: new_cases, dtype: float64
124035 124042    28.0
Name: new_cases, dtype: float64
124036 124043    38.0
Name: new_cases, dtype: float64
124037 124044    38.0
Name: new_cases, dtype: float64
124038 124045    41.0
Name: new_cases, dtype: float64
124039 124046    40.0
Name: new_cases, dtype: float64
124040 124047    29.0
Name: new_cases, dtype: float64
124041 124048    25.0
Name: new_cases, dtype: float64
124042 124049    36.0
Name: new_cases, dtype: float64
124043 124050    30.0
Name: new_cases, dtype: float64
124044 124051    26.0
Name: new_cases, dtype: float64
124045 124052    24.0
Name: new_cases, dtype: float64
124046 124053    30.0
Name: new_cases, dtype: float64
124047 124054    33.0
Name: new_cases, dtype: float64
124048 124055    25.0
Name: new_cases, dtype: float64
124049 124056    23.0
Name: new_cases, dtype: float64
124050 124057    18.0
Name: new_cases, dtype: float64
124051 124058    31.0
Name: new_cases, dtype: float64
124052 124059    45.0
Name: new_cases, dtype: float64
124053 124060    13.0
Name: new_cases, dtype: float64
124054 124061    18.0
Name: new_cases, dtype: float64
124055 124062    20.0
Name: new_cases, dtype: float64
124056 124063    14.0
Name: new_cases, dtype: float64
124057 124064    9.0
Name: new_cases, dtype: float64
124058 124065    4.0
Name: new_cases, dtype: float64
124059 124066    13.0
Name: new_cases, dtype: float64
124060 124067    9.0
Name: new_cases, dtype: float64
124061 124068    18.0
Name: new_cases, dtype: float64
124062 124069    13.0
Name: new_cases, dtype: float64
124063 124070    25.0
Name: new_cases, dtype: float64
124064 124071    14.0
Name: new_cases, dtype: float64
124065 124072    24.0
Name: new_cases, dtype: float64
124066 124073    27.0
Name: new_cases, dtype: float64
124067 124074    16.0
Name: new_cases, dtype: float64
124068 124075    21.0
Name: new_cases, dtype: float64
124069 124076    11.0
Name: new_cases, dtype: float64
124070 124077    16.0
Name: new_cases, dtype: float64
124071 124078    18.0
Name: new_cases, dtype: float64
124072 124079    22.0
Name: new_cases, dtype: float64
124073 124080    23.0
Name: new_cases, dtype: float64
124074 124081    20.0
Name: new_cases, dtype: float64
124075 124082    17.0
Name: new_cases, dtype: float64
124076 124083    14.0
Name: new_cases, dtype: float64
124077 124084    9.0
Name: new_cases, dtype: float64
124078 124085    10.0
Name: new_cases, dtype: float64
124079 124086    16.0
Name: new_cases, dtype: float64
124080 124087    10.0
Name: new_cases, dtype: float64
124081 124088    10.0
Name: new_cases, dtype: float64
124082 124089    7.0
Name: new_cases, dtype: float64
124083 124090    11.0
Name: new_cases, dtype: float64
124084 124091    13.0
Name: new_cases, dtype: float64
124085 124092    10.0
Name: new_cases, dtype: float64
124086 124093    12.0
Name: new_cases, dtype: float64
124087 124094    16.0
Name: new_cases, dtype: float64
124088 124095    10.0
Name: new_cases, dtype: float64
124089 124096    6.0
Name: new_cases, dtype: float64
124090 124097    8.0
Name: new_cases, dtype: float64
124091 124098    26.0
Name: new_cases, dtype: float64
124092 124099    26.0
Name: new_cases, dtype: float64
124093 124100    60.0
Name: new_cases, dtype: float64
124094 124101    48.0
Name: new_cases, dtype: float64

124095 124102    61.0
Name: new_cases, dtype: float64
124096 124103    68.0
Name: new_cases, dtype: float64
124097 124104    92.0
Name: new_cases, dtype: float64
124098 124105    172.0
Name: new_cases, dtype: float64
124099 124106    195.0
Name: new_cases, dtype: float64
124100 124107    181.0
Name: new_cases, dtype: float64
124101 124108    170.0
Name: new_cases, dtype: float64
124102 124109    133.0
Name: new_cases, dtype: float64
124103 124110    130.0
Name: new_cases, dtype: float64
124104 124111    125.0
Name: new_cases, dtype: float64
124105 124112    135.0
Name: new_cases, dtype: float64
124106 124113    139.0
Name: new_cases, dtype: float64
124107 124114    136.0
Name: new_cases, dtype: float64
124108 124115    133.0
Name: new_cases, dtype: float64
124109 124116    139.0
Name: new_cases, dtype: float64
124110 124117    120.0
Name: new_cases, dtype: float64
124111 124118    121.0
Name: new_cases, dtype: float64
124112 124119    111.0
Name: new_cases, dtype: float64
124113 124120    102.0
Name: new_cases, dtype: float64
124114 124121    95.0
Name: new_cases, dtype: float64
124115 124122    98.0
Name: new_cases, dtype: float64
124116 124123    97.0
Name: new_cases, dtype: float64
124117 124124    81.0
Name: new_cases, dtype: float64
124118 124125    78.0
Name: new_cases, dtype: float64
124119 124126    72.0
Name: new_cases, dtype: float64
124120 124127    0.0
Name: new_cases, dtype: float64
124121 124128    117.0
Name: new_cases, dtype: float64
124122 124129    59.0
Name: new_cases, dtype: float64
124123 124130    49.0
Name: new_cases, dtype: float64
124124 124131    58.0
Name: new_cases, dtype: float64
124125 124132    53.0
Name: new_cases, dtype: float64
124126 124133    53.0
Name: new_cases, dtype: float64
124127 124134    56.0
Name: new_cases, dtype: float64
124128 124135    53.0
Name: new_cases, dtype: float64
124129 124136    32.0
Name: new_cases, dtype: float64
124130 124137    40.0
Name: new_cases, dtype: float64
124131 124138    37.0
Name: new_cases, dtype: float64
124132 124139    35.0
Name: new_cases, dtype: float64
124133 124140    98.0
Name: new_cases, dtype: float64
124134 124141    116.0
Name: new_cases, dtype: float64
124135 124142    120.0
Name: new_cases, dtype: float64
124136 124143    116.0
Name: new_cases, dtype: float64
124137 124144    0.0
Name: new_cases, dtype: float64
124138 124145    243.0
Name: new_cases, dtype: float64
124139 124146    0.0
Name: new_cases, dtype: float64
124140 124147    288.0
Name: new_cases, dtype: float64
124141 124148    161.0
Name: new_cases, dtype: float64
124142 124149    180.0
Name: new_cases, dtype: float64
124143 124150    191.0
Name: new_cases, dtype: float64
124144 124151    219.0
Name: new_cases, dtype: float64
124145 124152    259.0
Name: new_cases, dtype: float64
124146 124153    191.0
Name: new_cases, dtype: float64
124147 124154    241.0
Name: new_cases, dtype: float64
124148 124155    332.0
Name: new_cases, dtype: float64
124149 124156    349.0
Name: new_cases, dtype: float64
124150 124157    457.0
Name: new_cases, dtype: float64
124151 124158    573.0
Name: new_cases, dtype: float64
124152 124159    555.0
Name: new_cases, dtype: float64
124153 124160    520.0
Name: new_cases, dtype: float64
124154 124161    607.0
Name: new_cases, dtype: float64
124155 124162    837.0
Name: new_cases, dtype: float64
124156 124163    807.0
Name: new_cases, dtype: float64
124157 124164    910.0
Name: new_cases, dtype: float64
124158 124165    935.0
Name: new_cases, dtype: float64
124159 124166    1009.0
Name: new_cases, dtype: float64
124160 124167    1012.0
Name: new_cases, dtype: float64
124161 124168    917.0
Name: new_cases, dtype: float64
124162 124169    1178.0
Name: new_cases, dtype: float64
124163 124170    1457.0
Name: new_cases, dtype: float64
124164 124171    1504.0
Name: new_cases, dtype: float64
124165 124172    1650.0
Name: new_cases, dtype: float64
124166 124173    1443.0
Name: new_cases, dtype: float64
124167 124174    1939.0
Name: new_cases, dtype: float64
124168 124175    1647.0
Name: new_cases, dtype: float64
124169 124176    2236.0
Name: new_cases, dtype: float64
124170 124177    2268.0
Name: new_cases, dtype: float64
124171 124178    2478.0
Name: new_cases, dtype: float64
124172 124179    2909.0
Name: new_cases, dtype: float64
124173 124180    2356.0
Name: new_cases, dtype: float64
124174 124181    2057.0
Name: new_cases, dtype: float64
124175 124182    2475.0
Name: new_cases, dtype: float64
124176 124183    3486.0
Name: new_cases, dtype: float64
124177 124184    3577.0
Name: new_cases, dtype: float64
124178 124185    3483.0
Name: new_cases, dtype: float64
124179 124186    3590.0
Name: new_cases, dtype: float64
124180 124187    3703.0
Name: new_cases, dtype: float64
124181 124188    2809.0
Name: new_cases, dtype: float64
124182 124189    2263.0
Name: new_cases, dtype: float64
124183 124190    2976.0
Name: new_cases, dtype: float64
124184 124191    3190.0
Name: new_cases, dtype: float64
124185 124192    2932.0
Name: new_cases, dtype: float64
124186 124193    3445.0
Name: new_cases, dtype: float64
124187 124194    3348.0
Name: new_cases, dtype: float64
124188 124195    3058.0
Name: new_cases, dtype: float64
124189 124196    2553.0
Name: new_cases, dtype: float64
124190 124197    3994.0
Name: new_cases, dtype: float64
124191 124198    3862.0
Name: new_cases, dtype: float64
124192 124199    3439.0
Name: new_cases, dtype: float64
124193 124200    3637.0
Name: new_cases, dtype: float64
124194 124201    3598.0
Name: new_cases, dtype: float64
124195 124202    3383.0
Name: new_cases, dtype: float64
124196 124203    3174.0
Name: new_cases, dtype: float64
124197 124204    3277.0
Name: new_cases, dtype: float64
124198 124205    5324.0
Name: new_cases, dtype: float64
124199 124206    3432.0
Name: new_cases, dtype: float64
124200 124207    4248.0
Name: new_cases, dtype: float64
124201 124208    3112.0
Name: new_cases, dtype: float64
124202 124209    3163.0
Name: new_cases, dtype: float64
124203 124210    2470.0
Name: new_cases, dtype: float64
124204 124211    3496.0
Name: new_cases, dtype: float64
124205 124212    3635.0
Name: new_cases, dtype: float64
124206 124213    3003.0
Name: new_cases, dtype: float64
124207 124214    1767.0
Name: new_cases, dtype: float64
124208 124215    3035.0
Name: new_cases, dtype: float64
124209 124216    2553.0
Name: new_cases, dtype: float64
124210 124217    2470.0
Name: new_cases, dtype: float64
124211 124218    3397.0
Name: new_cases, dtype: float64
124212 124219    3481.0
Name: new_cases, dtype: float64
124213 124220    2396.0
Name: new_cases, dtype: float64
124214 124221    3099.0
Name: new_cases, dtype: float64
124215 124222    2304.0
Name: new_cases, dtype: float64
124216 124223    1723.0
Name: new_cases, dtype: float64
124217 124224    2069.0
Name: new_cases, dtype: float64
124218 124225    2069.0
Name: new_cases, dtype: float64
124219 124226    3474.0
Name: new_cases, dtype: float64
124220 124227    0.0
Name: new_cases, dtype: float64
124221 124228    3772.0
Name: new_cases, dtype: float64
124222 124229    1931.0
Name: new_cases, dtype: float64
124223 124230    1670.0
Name: new_cases, dtype: float64
124224 124231    1461.0
Name: new_cases, dtype: float64
124225 124232    1782.0
Name: new_cases, dtype: float64
124226 124233    2079.0
Name: new_cases, dtype: float64
124227 124234    1275.0
Name: new_cases, dtype: float64
124228 124235    1090.0
Name: new_cases, dtype: float64
124229 124236    1761.0
Name: new_cases, dtype: float64
124230 124237    747.0
Name: new_cases, dtype: float64
124231 124238    1103.0
Name: new_cases, dtype: float64
124232 124239    1239.0
Name: new_cases, dtype: float64
124233 124240    1324.0
Name: new_cases, dtype: float64
124234 124241    1101.0
Name: new_cases, dtype: float64
124235 124242    766.0
Name: new_cases, dtype: float64
124236 124243    743.0
Name: new_cases, dtype: float64
124237 124244    552.0
Name: new_cases, dtype: float64
124238 124245    662.0
Name: new_cases, dtype: float64
124239 124246    715.0
Name: new_cases, dtype: float64
124240 124247    709.0
Name: new_cases, dtype: float64
124241 124248    682.0
Name: new_cases, dtype: float64
124242 124249    454.0
Name: new_cases, dtype: float64
124243 124250    559.0
Name: new_cases, dtype: float64
124244 124251    370.0
Name: new_cases, dtype: float64
124245 124252    339.0
Name: new_cases, dtype: float64
124246 124253    442.0
Name: new_cases, dtype: float64
124247 124254    474.0
Name: new_cases, dtype: float64
124248 124255    355.0
Name: new_cases, dtype: float64
124249 124256    412.0
Name: new_cases, dtype: float64
124250 124257    271.0
Name: new_cases, dtype: float64
124251 124258    255.0
Name: new_cases, dtype: float64
124252 124259    195.0
Name: new_cases, dtype: float64
124253 124260    280.0
Name: new_cases, dtype: float64
124254 124261    335.0
Name: new_cases, dtype: float64
124255 124262    322.0
Name: new_cases, dtype: float64

124256 124263    265.0
Name: new_cases, dtype: float64
124257 124264    248.0
Name: new_cases, dtype: float64
124258 124265    209.0
Name: new_cases, dtype: float64
124259 124266    280.0
Name: new_cases, dtype: float64
124260 124267    365.0
Name: new_cases, dtype: float64
124261 124268    341.0
Name: new_cases, dtype: float64
124262 124269    311.0
Name: new_cases, dtype: float64
124263 124270    344.0
Name: new_cases, dtype: float64
124264 124271    456.0
Name: new_cases, dtype: float64
124265 124272    429.0
Name: new_cases, dtype: float64
124266 124273    464.0
Name: new_cases, dtype: float64
124267 124274    842.0
Name: new_cases, dtype: float64
124268 124275    805.0
Name: new_cases, dtype: float64
124269 124276    813.0
Name: new_cases, dtype: float64
124270 124277    0.0
Name: new_cases, dtype: float64
124271 124278    1588.0
Name: new_cases, dtype: float64
124272 123605    13.0
Name: new_cases, dtype: float64
124273 123606    8.0
Name: new_cases, dtype: float64
124274 123607    12.0
Name: new_cases, dtype: float64
124275 123608    0.0
Name: new_cases, dtype: float64
124276 123609    10.0
Name: new_cases, dtype: float64
124277 123610    18.0
Name: new_cases, dtype: float64
124278 123611    0.0
Name: new_cases, dtype: float64
124510 124517    11.0
Name: new_cases, dtype: float64
124511 124518    11.0
Name: new_cases, dtype: float64
124512 124519    12.0
Name: new_cases, dtype: float64
124513 124520    17.0
Name: new_cases, dtype: float64
124514 124521    11.0
Name: new_cases, dtype: float64
124515 124522    24.0
Name: new_cases, dtype: float64
124516 124523    8.0
Name: new_cases, dtype: float64
124517 124524    19.0
Name: new_cases, dtype: float64
124518 124525    14.0
Name: new_cases, dtype: float64
124519 124526    41.0
Name: new_cases, dtype: float64
124520 124527    7.0
Name: new_cases, dtype: float64
124521 124528    19.0
Name: new_cases, dtype: float64
124522 124529    12.0
Name: new_cases, dtype: float64
124523 124530    10.0
Name: new_cases, dtype: float64
124524 124531    43.0
Name: new_cases, dtype: float64
124525 124532    23.0
Name: new_cases, dtype: float64
124526 124533    22.0
Name: new_cases, dtype: float64
124527 124534    22.0
Name: new_cases, dtype: float64
124528 124535    27.0
Name: new_cases, dtype: float64
124529 124536    37.0
Name: new_cases, dtype: float64
124530 124537    26.0
Name: new_cases, dtype: float64
124531 124538    24.0
Name: new_cases, dtype: float64
124532 124539    21.0
Name: new_cases, dtype: float64
124533 124540    14.0
Name: new_cases, dtype: float64
124534 124541    49.0
Name: new_cases, dtype: float64
124535 124542    47.0
Name: new_cases, dtype: float64
124536 124543    101.0
Name: new_cases, dtype: float64
124537 124544    19.0
Name: new_cases, dtype: float64
124538 124545    14.0
Name: new_cases, dtype: float64
124539 124546    13.0
Name: new_cases, dtype: float64
124540 124547    14.0
Name: new_cases, dtype: float64
124541 124548    27.0
Name: new_cases, dtype: float64
124542 124549    66.0
Name: new_cases, dtype: float64
124543 124550    28.0
Name: new_cases, dtype: float64
124544 124551    114.0
Name: new_cases, dtype: float64
124545 124552    72.0
Name: new_cases, dtype: float64
124546 124553    40.0
Name: new_cases, dtype: float64
124547 124554    72.0
Name: new_cases, dtype: float64
124548 124555    12.0
Name: new_cases, dtype: float64
124549 124556    26.0
Name: new_cases, dtype: float64
124550 124557    45.0
Name: new_cases, dtype: float64
124551 124558    81.0
Name: new_cases, dtype: float64
124552 124559    35.0
Name: new_cases, dtype: float64
124553 124560    13.0
Name: new_cases, dtype: float64
124554 124561    6.0
Name: new_cases, dtype: float64
124555 124562    2.0
Name: new_cases, dtype: float64
124556 124563    3.0
Name: new_cases, dtype: float64
124557 124564    7.0
Name: new_cases, dtype: float64
124558 124565    5.0
Name: new_cases, dtype: float64
124559 124566    7.0
Name: new_cases, dtype: float64
124560 124567    4.0
Name: new_cases, dtype: float64
124561 124568    1.0
Name: new_cases, dtype: float64
124562 124569    5.0
Name: new_cases, dtype: float64
124563 124570    8.0
Name: new_cases, dtype: float64
124564 124571    8.0
Name: new_cases, dtype: float64
124565 124572    16.0
Name: new_cases, dtype: float64
124566 124573    10.0
Name: new_cases, dtype: float64
124567 124574    0.0
Name: new_cases, dtype: float64
124568 124575    2.0
Name: new_cases, dtype: float64
124569 124576    0.0
Name: new_cases, dtype: float64
124570 124577    8.0
Name: new_cases, dtype: float64
124571 124578    4.0
Name: new_cases, dtype: float64
124572 124579    8.0
Name: new_cases, dtype: float64
124573 124580    3.0
Name: new_cases, dtype: float64
124574 124581    13.0
Name: new_cases, dtype: float64
124575 124582    1.0
Name: new_cases, dtype: float64
124576 124583    1.0
Name: new_cases, dtype: float64
124577 124584    0.0
Name: new_cases, dtype: float64
124578 124585    1.0
Name: new_cases, dtype: float64
124579 124586    6.0
Name: new_cases, dtype: float64
124580 124587    1.0
Name: new_cases, dtype: float64
124581 124588    1.0
Name: new_cases, dtype: float64
124582 124589    5.0
Name: new_cases, dtype: float64
124583 124590    2.0
Name: new_cases, dtype: float64
124584 124591    2.0
Name: new_cases, dtype: float64
124585 124592    2.0
Name: new_cases, dtype: float64
124586 124593    5.0
Name: new_cases, dtype: float64
124587 124594    0.0
Name: new_cases, dtype: float64
124588 124595    1.0
Name: new_cases, dtype: float64
124589 124596    0.0
Name: new_cases, dtype: float64
124590 124597    1.0
Name: new_cases, dtype: float64
124591 124598    0.0
Name: new_cases, dtype: float64
124592 124599    3.0
Name: new_cases, dtype: float64
124593 124600    1.0
Name: new_cases, dtype: float64
124594 124601    0.0
Name: new_cases, dtype: float64
124595 124602    2.0
Name: new_cases, dtype: float64
124596 124603    0.0
Name: new_cases, dtype: float64
124597 124604    2.0
Name: new_cases, dtype: float64
124598 124605    1.0
Name: new_cases, dtype: float64
124599 124606    2.0
Name: new_cases, dtype: float64
124600 124607    8.0
Name: new_cases, dtype: float64
124601 124608    1.0
Name: new_cases, dtype: float64
124602 124609    3.0
Name: new_cases, dtype: float64
124603 124610    3.0
Name: new_cases, dtype: float64
124604 124611    4.0
Name: new_cases, dtype: float64
124605 124612    0.0
Name: new_cases, dtype: float64
124606 124613    9.0
Name: new_cases, dtype: float64
124607 124614    1.0
Name: new_cases, dtype: float64
124608 124615    14.0
Name: new_cases, dtype: float64
124609 124616    10.0
Name: new_cases, dtype: float64
124610 124617    1.0
Name: new_cases, dtype: float64
124611 124618    1.0
Name: new_cases, dtype: float64
124612 124619    1.0
Name: new_cases, dtype: float64
124613 124620    18.0
Name: new_cases, dtype: float64
124614 124621    23.0
Name: new_cases, dtype: float64
124615 124622    13.0
Name: new_cases, dtype: float64
124616 124623    14.0
Name: new_cases, dtype: float64
124617 124624    7.0
Name: new_cases, dtype: float64
124618 124625    1.0
Name: new_cases, dtype: float64
124619 124626    2.0
Name: new_cases, dtype: float64
124620 124627    20.0
Name: new_cases, dtype: float64
124621 124628    13.0
Name: new_cases, dtype: float64
124622 124629    20.0
Name: new_cases, dtype: float64
124623 124630    29.0
Name: new_cases, dtype: float64
124624 124631    15.0
Name: new_cases, dtype: float64
124625 124632    1.0
Name: new_cases, dtype: float64
124626 124633    2.0
Name: new_cases, dtype: float64
124627 124634    31.0
Name: new_cases, dtype: float64
124628 124635    53.0
Name: new_cases, dtype: float64
124629 124636    19.0
Name: new_cases, dtype: float64
124630 124637    23.0
Name: new_cases, dtype: float64
124631 124638    8.0
Name: new_cases, dtype: float64
124632 124639    1.0
Name: new_cases, dtype: float64
124633 124640    6.0
Name: new_cases, dtype: float64
124634 124641    19.0
Name: new_cases, dtype: float64
124635 124642    24.0
Name: new_cases, dtype: float64
124636 124643    14.0
Name: new_cases, dtype: float64
124637 124644    11.0
Name: new_cases, dtype: float64
124638 124645    3.0
Name: new_cases, dtype: float64
124639 124646    1.0
Name: new_cases, dtype: float64
124640 124647    41.0
Name: new_cases, dtype: float64
124641 124648    37.0
Name: new_cases, dtype: float64
124642 124649    31.0
Name: new_cases, dtype: float64

124643 124650    29.0
Name: new_cases, dtype: float64
124644 124651    23.0
Name: new_cases, dtype: float64
124645 124652    38.0
Name: new_cases, dtype: float64
124646 124653    2.0
Name: new_cases, dtype: float64
124647 124654    23.0
Name: new_cases, dtype: float64
124648 124655    41.0
Name: new_cases, dtype: float64
124649 124656    20.0
Name: new_cases, dtype: float64
124650 124657    27.0
Name: new_cases, dtype: float64
124651 124658    45.0
Name: new_cases, dtype: float64
124652 124659    7.0
Name: new_cases, dtype: float64
124653 124660    10.0
Name: new_cases, dtype: float64
124654 124661    14.0
Name: new_cases, dtype: float64
124655 124662    49.0
Name: new_cases, dtype: float64
124656 124663    63.0
Name: new_cases, dtype: float64
124657 124664    43.0
Name: new_cases, dtype: float64
124658 124665    43.0
Name: new_cases, dtype: float64
124659 124666    30.0
Name: new_cases, dtype: float64
124660 124667    3.0
Name: new_cases, dtype: float64
124661 124668    16.0
Name: new_cases, dtype: float64
124662 124669    75.0
Name: new_cases, dtype: float64
124663 124670    49.0
Name: new_cases, dtype: float64
124664 124671    62.0
Name: new_cases, dtype: float64
124665 124672    54.0
Name: new_cases, dtype: float64
124666 124673    47.0
Name: new_cases, dtype: float64
124667 124674    5.0
Name: new_cases, dtype: float64
124668 124675    15.0
Name: new_cases, dtype: float64
124669 124676    100.0
Name: new_cases, dtype: float64
124670 124677    80.0
Name: new_cases, dtype: float64
124671 124678    123.0
Name: new_cases, dtype: float64
124672 124679    91.0
Name: new_cases, dtype: float64
124673 124680    40.0
Name: new_cases, dtype: float64
124674 124681    68.0
Name: new_cases, dtype: float64
124675 124682    28.0
Name: new_cases, dtype: float64
124676 124683    84.0
Name: new_cases, dtype: float64
124677 124684    90.0
Name: new_cases, dtype: float64
124678 124685    102.0
Name: new_cases, dtype: float64
124679 124686    114.0
Name: new_cases, dtype: float64
124680 124687    34.0
Name: new_cases, dtype: float64
124681 124688    41.0
Name: new_cases, dtype: float64
124682 124689    72.0
Name: new_cases, dtype: float64
124683 124690    53.0
Name: new_cases, dtype: float64
124684 124691    121.0
Name: new_cases, dtype: float64
124685 124692    137.0
Name: new_cases, dtype: float64
124686 124693    226.0
Name: new_cases, dtype: float64
124687 124694    88.0
Name: new_cases, dtype: float64
124688 124695    22.0
Name: new_cases, dtype: float64
124689 124696    91.0
Name: new_cases, dtype: float64
124690 124697    161.0
Name: new_cases, dtype: float64
124691 124698    178.0
Name: new_cases, dtype: float64
124692 124699    186.0
Name: new_cases, dtype: float64
124693 124700    201.0
Name: new_cases, dtype: float64
124694 124701    79.0
Name: new_cases, dtype: float64
124695 124702    48.0
Name: new_cases, dtype: float64
124696 124703    188.0
Name: new_cases, dtype: float64
124697 124704    92.0
Name: new_cases, dtype: float64
124698 124705    161.0
Name: new_cases, dtype: float64
124699 124706    235.0
Name: new_cases, dtype: float64
124700 124707    290.0
Name: new_cases, dtype: float64
124701 124708    131.0
Name: new_cases, dtype: float64
124702 124709    79.0
Name: new_cases, dtype: float64
124703 124710    175.0
Name: new_cases, dtype: float64
124704 124711    338.0
Name: new_cases, dtype: float64
124705 124712    360.0
Name: new_cases, dtype: float64
124706 124713    419.0
Name: new_cases, dtype: float64
124707 124714    552.0
Name: new_cases, dtype: float64
124708 124715    478.0
Name: new_cases, dtype: float64
124709 124716    265.0
Name: new_cases, dtype: float64
124710 124717    231.0
Name: new_cases, dtype: float64
124711 124718    567.0
Name: new_cases, dtype: float64
124712 124719    797.0
Name: new_cases, dtype: float64
124713 124720    679.0
Name: new_cases, dtype: float64
124714 124721    704.0
Name: new_cases, dtype: float64
124715 124722    818.0
Name: new_cases, dtype: float64
124716 124723    353.0
Name: new_cases, dtype: float64
124717 124724    320.0
Name: new_cases, dtype: float64
124718 124725    877.0
Name: new_cases, dtype: float64
124719 124726    1037.0
Name: new_cases, dtype: float64
124720 124727    1184.0
Name: new_cases, dtype: float64
124721 124728    1887.0
Name: new_cases, dtype: float64
124722 124729    1054.0
Name: new_cases, dtype: float64
124723 124730    504.0
Name: new_cases, dtype: float64
124724 124731    571.0
Name: new_cases, dtype: float64
124725 124732    1494.0
Name: new_cases, dtype: float64
124726 124733    1960.0
Name: new_cases, dtype: float64
124727 124734    2111.0
Name: new_cases, dtype: float64
124728 124735    1995.0
Name: new_cases, dtype: float64
124729 124736    1567.0
Name: new_cases, dtype: float64
124730 124737    860.0
Name: new_cases, dtype: float64
124731 124738    774.0
Name: new_cases, dtype: float64
124732 124739    2240.0
Name: new_cases, dtype: float64
124733 124740    1776.0
Name: new_cases, dtype: float64
124734 124741    2722.0
Name: new_cases, dtype: float64
124735 124742    3009.0
Name: new_cases, dtype: float64
124736 124743    3107.0
Name: new_cases, dtype: float64
124737 124744    1352.0
Name: new_cases, dtype: float64
124738 124745    1132.0
Name: new_cases, dtype: float64
124739 124746    3121.0
Name: new_cases, dtype: float64
124740 124747    3010.0
Name: new_cases, dtype: float64
124741 124748    3602.0
Name: new_cases, dtype: float64
124742 124749    3065.0
Name: new_cases, dtype: float64
124743 124750    3257.0
Name: new_cases, dtype: float64
124744 124751    2259.0
Name: new_cases, dtype: float64
124745 124752    3058.0
Name: new_cases, dtype: float64
124746 124753    3314.0
Name: new_cases, dtype: float64
124747 124754    2044.0
Name: new_cases, dtype: float64
124748 124755    2494.0
Name: new_cases, dtype: float64
124749 124756    2906.0
Name: new_cases, dtype: float64
124750 124757    2267.0
Name: new_cases, dtype: float64
124751 124758    720.0
Name: new_cases, dtype: float64
124752 124759    2205.0
Name: new_cases, dtype: float64
124753 124760    2198.0
Name: new_cases, dtype: float64
124754 124761    2692.0
Name: new_cases, dtype: float64
124755 124762    2197.0
Name: new_cases, dtype: float64
124756 124763    1929.0
Name: new_cases, dtype: float64
124757 124764    1299.0
Name: new_cases, dtype: float64
124758 124765    542.0
Name: new_cases, dtype: float64
124759 124766    1612.0
Name: new_cases, dtype: float64
124760 124767    1535.0
Name: new_cases, dtype: float64
124761 124768    2107.0
Name: new_cases, dtype: float64
124762 124769    2588.0
Name: new_cases, dtype: float64
124763 124770    2472.0
Name: new_cases, dtype: float64
124764 124771    1306.0
Name: new_cases, dtype: float64
124765 124772    288.0
Name: new_cases, dtype: float64
124766 124773    1905.0
Name: new_cases, dtype: float64
124767 124774    2705.0
Name: new_cases, dtype: float64
124768 124775    2686.0
Name: new_cases, dtype: float64
124769 124776    2716.0
Name: new_cases, dtype: float64
124770 124777    2314.0
Name: new_cases, dtype: float64
124771 124778    1533.0
Name: new_cases, dtype: float64
124772 124779    376.0
Name: new_cases, dtype: float64
124773 124780    2971.0
Name: new_cases, dtype: float64
124774 124781    3640.0
Name: new_cases, dtype: float64
124775 124782    3645.0
Name: new_cases, dtype: float64
124776 124783    3458.0
Name: new_cases, dtype: float64
124777 124784    3330.0
Name: new_cases, dtype: float64
124778 124785    1636.0
Name: new_cases, dtype: float64
124779 124786    681.0
Name: new_cases, dtype: float64
124780 124787    4113.0
Name: new_cases, dtype: float64
124781 124788    5524.0
Name: new_cases, dtype: float64
124782 124789    5431.0
Name: new_cases, dtype: float64
124783 124790    5274.0
Name: new_cases, dtype: float64
124784 124791    6267.0
Name: new_cases, dtype: float64
124785 124792    3190.0
Name: new_cases, dtype: float64
124786 124793    604.0
Name: new_cases, dtype: float64
124787 124794    5206.0
Name: new_cases, dtype: float64
124788 124795    7703.0
Name: new_cases, dtype: float64
124789 124796    6596.0
Name: new_cases, dtype: float64
124790 124797    7835.0
Name: new_cases, dtype: float64
124791 124798    6522.0
Name: new_cases, dtype: float64
124792 124799    3082.0
Name: new_cases, dtype: float64
124793 124800    1715.0
Name: new_cases, dtype: float64
124794 124801    9753.0
Name: new_cases, dtype: float64
124795 124802    9215.0
Name: new_cases, dtype: float64
124796 124803    7354.0
Name: new_cases, dtype: float64
124797 124804    5064.0
Name: new_cases, dtype: float64
124798 124805    1182.0
Name: new_cases, dtype: float64
124799 124806    1086.0
Name: new_cases, dtype: float64
124800 124807    873.0
Name: new_cases, dtype: float64
124801 124808    8648.0
Name: new_cases, dtype: float64
124802 124809    9743.0
Name: new_cases, dtype: float64
124803 124810    11915.0
Name: new_cases, dtype: float64
124804 124811    10476.0
Name: new_cases, dtype: float64

124805 124812    2326.0
Name: new_cases, dtype: float64
124806 124813    1745.0
Name: new_cases, dtype: float64
124807 124814    908.0
Name: new_cases, dtype: float64
124808 124815    10347.0
Name: new_cases, dtype: float64
124809 124816    11080.0
Name: new_cases, dtype: float64
124810 124817    3165.0
Name: new_cases, dtype: float64
124811 124818    8291.0
Name: new_cases, dtype: float64
124812 124819    8003.0
Name: new_cases, dtype: float64
124813 124820    4860.0
Name: new_cases, dtype: float64
124814 124821    1785.0
Name: new_cases, dtype: float64
124815 124822    5704.0
Name: new_cases, dtype: float64
124816 124823    6605.0
Name: new_cases, dtype: float64
124817 124824    5553.0
Name: new_cases, dtype: float64
124818 124825    5022.0
Name: new_cases, dtype: float64
124819 124826    4221.0
Name: new_cases, dtype: float64
124820 124827    1701.0
Name: new_cases, dtype: float64
124821 124828    2694.0
Name: new_cases, dtype: float64
124822 124829    5294.0
Name: new_cases, dtype: float64
124823 124830    5154.0
Name: new_cases, dtype: float64
124824 124831    4792.0
Name: new_cases, dtype: float64
124825 124832    4888.0
Name: new_cases, dtype: float64
124826 124833    4392.0
Name: new_cases, dtype: float64
124827 124834    8420.0
Name: new_cases, dtype: float64
124828 124835    4344.0
Name: new_cases, dtype: float64
124829 124836    4328.0
Name: new_cases, dtype: float64
124830 124837    5442.0
Name: new_cases, dtype: float64
124831 124838    3762.0
Name: new_cases, dtype: float64
124832 124839    4671.0
Name: new_cases, dtype: float64
124833 124840    4898.0
Name: new_cases, dtype: float64
124834 124841    6542.0
Name: new_cases, dtype: float64
124835 124842    3309.0
Name: new_cases, dtype: float64
124836 124843    5237.0
Name: new_cases, dtype: float64
124837 124844    6481.0
Name: new_cases, dtype: float64
124838 124845    4650.0
Name: new_cases, dtype: float64
124839 124846    5553.0
Name: new_cases, dtype: float64
124840 124847    5289.0
Name: new_cases, dtype: float64
124841 124848    7040.0
Name: new_cases, dtype: float64
124842 124849    4072.0
Name: new_cases, dtype: float64
124843 124850    5355.0
Name: new_cases, dtype: float64
124844 124851    6216.0
Name: new_cases, dtype: float64
124845 124852    5470.0
Name: new_cases, dtype: float64
124846 124853    4905.0
Name: new_cases, dtype: float64
124847 124854    5673.0
Name: new_cases, dtype: float64
124848 124855    6281.0
Name: new_cases, dtype: float64
124849 124856    3491.0
Name: new_cases, dtype: float64
124850 124857    4725.0
Name: new_cases, dtype: float64
124851 124858    5929.0
Name: new_cases, dtype: float64
124852 124859    5351.0
Name: new_cases, dtype: float64
124853 124860    5130.0
Name: new_cases, dtype: float64
124854 124861    6279.0
Name: new_cases, dtype: float64
124855 124862    6982.0
Name: new_cases, dtype: float64
124856 124863    3538.0
Name: new_cases, dtype: float64
124857 124864    5435.0
Name: new_cases, dtype: float64
124858 124865    6432.0
Name: new_cases, dtype: float64
124859 124866    5448.0
Name: new_cases, dtype: float64
124860 124867    5255.0
Name: new_cases, dtype: float64
124861 124868    6182.0
Name: new_cases, dtype: float64
124862 124869    6947.0
Name: new_cases, dtype: float64
124863 124870    3464.0
Name: new_cases, dtype: float64
124864 124871    5262.0
Name: new_cases, dtype: float64
124865 124872    6103.0
Name: new_cases, dtype: float64
124866 124873    5290.0
Name: new_cases, dtype: float64
124867 124874    4823.0
Name: new_cases, dtype: float64
124868 124875    5365.0
Name: new_cases, dtype: float64
124869 124876    5210.0
Name: new_cases, dtype: float64
124870 124877    2694.0
Name: new_cases, dtype: float64
124871 124878    4818.0
Name: new_cases, dtype: float64
124872 124879    5644.0
Name: new_cases, dtype: float64
124873 124880    3951.0
Name: new_cases, dtype: float64
124874 124881    4162.0
Name: new_cases, dtype: float64
124875 124882    4752.0
Name: new_cases, dtype: float64
124876 124883    4703.0
Name: new_cases, dtype: float64
124877 124884    2302.0
Name: new_cases, dtype: float64
124878 124885    3811.0
Name: new_cases, dtype: float64
124879 124886    4721.0
Name: new_cases, dtype: float64
124880 124887    3591.0
Name: new_cases, dtype: float64
124881 124888    3294.0
Name: new_cases, dtype: float64
124882 124889    3829.0
Name: new_cases, dtype: float64
124883 124890    3616.0
Name: new_cases, dtype: float64
124884 124891    1966.0
Name: new_cases, dtype: float64
124885 124892    3052.0
Name: new_cases, dtype: float64
124886 124893    3493.0
Name: new_cases, dtype: float64
124887 124894    3061.0
Name: new_cases, dtype: float64
124888 124895    2636.0
Name: new_cases, dtype: float64
124889 124896    3195.0
Name: new_cases, dtype: float64
124890 124897    3128.0
Name: new_cases, dtype: float64
124891 124898    1510.0
Name: new_cases, dtype: float64
124892 124899    2694.0
Name: new_cases, dtype: float64
124893 124900    3065.0
Name: new_cases, dtype: float64
124894 124901    2546.0
Name: new_cases, dtype: float64
124895 124902    2628.0
Name: new_cases, dtype: float64
124896 124903    1371.0
Name: new_cases, dtype: float64
124897 124904    2576.0
Name: new_cases, dtype: float64
124898 124905    707.0
Name: new_cases, dtype: float64
124899 124906    972.0
Name: new_cases, dtype: float64
124900 124907    2640.0
Name: new_cases, dtype: float64
124901 124908    2544.0
Name: new_cases, dtype: float64
124902 124909    1729.0
Name: new_cases, dtype: float64
124903 124910    2017.0
Name: new_cases, dtype: float64
124904 124911    1981.0
Name: new_cases, dtype: float64
124905 124912    841.0
Name: new_cases, dtype: float64
124906 124913    1784.0
Name: new_cases, dtype: float64
124907 124914    1762.0
Name: new_cases, dtype: float64
124908 124915    1523.0
Name: new_cases, dtype: float64
124909 124916    1310.0
Name: new_cases, dtype: float64
124910 124917    1586.0
Name: new_cases, dtype: float64
124911 124918    1645.0
Name: new_cases, dtype: float64
124912 124919    728.0
Name: new_cases, dtype: float64
124913 124920    1470.0
Name: new_cases, dtype: float64
124914 124921    1411.0
Name: new_cases, dtype: float64
124915 124922    1335.0
Name: new_cases, dtype: float64
124916 124923    1048.0
Name: new_cases, dtype: float64
124917 124924    1536.0
Name: new_cases, dtype: float64
124918 124925    1369.0
Name: new_cases, dtype: float64
124919 124926    692.0
Name: new_cases, dtype: float64
124920 124927    1190.0
Name: new_cases, dtype: float64
124921 124928    1192.0
Name: new_cases, dtype: float64
124922 124929    1066.0
Name: new_cases, dtype: float64
124923 124930    1003.0
Name: new_cases, dtype: float64
124924 124931    1155.0
Name: new_cases, dtype: float64
124925 124932    1016.0
Name: new_cases, dtype: float64
124926 124933    627.0
Name: new_cases, dtype: float64
124927 124934    930.0
Name: new_cases, dtype: float64
124928 124935    1090.0
Name: new_cases, dtype: float64
124929 124936    715.0
Name: new_cases, dtype: float64
124930 124937    751.0
Name: new_cases, dtype: float64
124931 124938    832.0
Name: new_cases, dtype: float64
124932 124939    352.0
Name: new_cases, dtype: float64
124933 124940    711.0
Name: new_cases, dtype: float64
124934 124941    784.0
Name: new_cases, dtype: float64
124935 124942    673.0
Name: new_cases, dtype: float64
124936 124943    607.0
Name: new_cases, dtype: float64
124937 124944    560.0
Name: new_cases, dtype: float64
124938 124945    611.0
Name: new_cases, dtype: float64
124939 124946    375.0
Name: new_cases, dtype: float64
124940 124947    386.0
Name: new_cases, dtype: float64
124941 124948    551.0
Name: new_cases, dtype: float64
124942 124949    472.0
Name: new_cases, dtype: float64
124943 124950    455.0
Name: new_cases, dtype: float64
124944 124951    310.0
Name: new_cases, dtype: float64
124945 124952    398.0
Name: new_cases, dtype: float64
124946 124953    308.0
Name: new_cases, dtype: float64
124947 124954    208.0
Name: new_cases, dtype: float64
124948 124955    396.0
Name: new_cases, dtype: float64
124949 124956    397.0
Name: new_cases, dtype: float64
124950 124957    310.0
Name: new_cases, dtype: float64
124951 124958    253.0
Name: new_cases, dtype: float64

124952 124959    318.0
Name: new_cases, dtype: float64
124953 124960    222.0
Name: new_cases, dtype: float64
124954 124961    157.0
Name: new_cases, dtype: float64
124955 124962    355.0
Name: new_cases, dtype: float64
124956 124963    258.0
Name: new_cases, dtype: float64
124957 124964    258.0
Name: new_cases, dtype: float64
124958 124965    227.0
Name: new_cases, dtype: float64
124959 124966    252.0
Name: new_cases, dtype: float64
124960 124967    170.0
Name: new_cases, dtype: float64
124961 124968    102.0
Name: new_cases, dtype: float64
124962 124969    243.0
Name: new_cases, dtype: float64
124963 124970    241.0
Name: new_cases, dtype: float64
124964 124971    166.0
Name: new_cases, dtype: float64
124965 124972    156.0
Name: new_cases, dtype: float64
124966 124973    175.0
Name: new_cases, dtype: float64
124967 124974    99.0
Name: new_cases, dtype: float64
124968 124975    69.0
Name: new_cases, dtype: float64
124969 124976    127.0
Name: new_cases, dtype: float64
124970 124977    109.0
Name: new_cases, dtype: float64
124971 124978    100.0
Name: new_cases, dtype: float64
124972 124979    81.0
Name: new_cases, dtype: float64
124973 124980    103.0
Name: new_cases, dtype: float64
124974 124981    51.0
Name: new_cases, dtype: float64
124975 124982    42.0
Name: new_cases, dtype: float64
124976 124983    118.0
Name: new_cases, dtype: float64
124977 124984    65.0
Name: new_cases, dtype: float64
124978 124985    67.0
Name: new_cases, dtype: float64
124979 124986    70.0
Name: new_cases, dtype: float64
124980 124987    74.0
Name: new_cases, dtype: float64
124981 124988    52.0
Name: new_cases, dtype: float64
124982 124989    37.0
Name: new_cases, dtype: float64
124983 124990    79.0
Name: new_cases, dtype: float64
124984 124991    57.0
Name: new_cases, dtype: float64
124985 124992    55.0
Name: new_cases, dtype: float64
124986 124993    28.0
Name: new_cases, dtype: float64
124987 124994    34.0
Name: new_cases, dtype: float64
124988 124995    29.0
Name: new_cases, dtype: float64
124989 124996    12.0
Name: new_cases, dtype: float64
124990 124997    24.0
Name: new_cases, dtype: float64
124991 124998    56.0
Name: new_cases, dtype: float64
124992 124999    48.0
Name: new_cases, dtype: float64
124993 125000    50.0
Name: new_cases, dtype: float64
124994 125001    58.0
Name: new_cases, dtype: float64
124995 125002    34.0
Name: new_cases, dtype: float64
124996 125003    15.0
Name: new_cases, dtype: float64
124997 125004    41.0
Name: new_cases, dtype: float64
124998 125005    32.0
Name: new_cases, dtype: float64
124999 125006    39.0
Name: new_cases, dtype: float64
125000 125007    43.0
Name: new_cases, dtype: float64
125001 125008    48.0
Name: new_cases, dtype: float64
125002 125009    37.0
Name: new_cases, dtype: float64
125003 125010    11.0
Name: new_cases, dtype: float64
125004 125011    52.0
Name: new_cases, dtype: float64
125005 125012    52.0
Name: new_cases, dtype: float64
125006 125013    50.0
Name: new_cases, dtype: float64
125007 125014    67.0
Name: new_cases, dtype: float64
125008 125015    53.0
Name: new_cases, dtype: float64
125009 125016    58.0
Name: new_cases, dtype: float64
125010 125017    19.0
Name: new_cases, dtype: float64
125011 125018    73.0
Name: new_cases, dtype: float64
125012 125019    100.0
Name: new_cases, dtype: float64
125013 125020    69.0
Name: new_cases, dtype: float64
125014 125021    60.0
Name: new_cases, dtype: float64
125015 125022    86.0
Name: new_cases, dtype: float64
125016 125023    68.0
Name: new_cases, dtype: float64
125017 125024    22.0
Name: new_cases, dtype: float64
125018 125025    74.0
Name: new_cases, dtype: float64
125019 125026    108.0
Name: new_cases, dtype: float64
125020 125027    65.0
Name: new_cases, dtype: float64
125021 125028    86.0
Name: new_cases, dtype: float64
125022 125029    67.0
Name: new_cases, dtype: float64
125023 125030    54.0
Name: new_cases, dtype: float64
125024 125031    33.0
Name: new_cases, dtype: float64
125025 125032    119.0
Name: new_cases, dtype: float64
125026 125033    97.0
Name: new_cases, dtype: float64
125027 125034    95.0
Name: new_cases, dtype: float64
125028 125035    85.0
Name: new_cases, dtype: float64
125029 125036    128.0
Name: new_cases, dtype: float64
125030 125037    95.0
Name: new_cases, dtype: float64
125031 125038    28.0
Name: new_cases, dtype: float64
125032 125039    119.0
Name: new_cases, dtype: float64
125033 125040    137.0
Name: new_cases, dtype: float64
125034 125041    131.0
Name: new_cases, dtype: float64
125035 125042    122.0
Name: new_cases, dtype: float64
125036 125043    145.0
Name: new_cases, dtype: float64
125037 125044    128.0
Name: new_cases, dtype: float64
125038 125045    51.0
Name: new_cases, dtype: float64
125039 125046    163.0
Name: new_cases, dtype: float64
125040 125047    110.0
Name: new_cases, dtype: float64
125041 125048    209.0
Name: new_cases, dtype: float64
125042 125049    153.0
Name: new_cases, dtype: float64
125043 125050    188.0
Name: new_cases, dtype: float64
125044 125051    136.0
Name: new_cases, dtype: float64
125045 125052    80.0
Name: new_cases, dtype: float64
125046 125053    227.0
Name: new_cases, dtype: float64
125047 125054    308.0
Name: new_cases, dtype: float64
125048 125055    230.0
Name: new_cases, dtype: float64
125049 125056    384.0
Name: new_cases, dtype: float64
125050 125057    475.0
Name: new_cases, dtype: float64
125051 125058    291.0
Name: new_cases, dtype: float64
125052 125059    189.0
Name: new_cases, dtype: float64
125053 125060    504.0
Name: new_cases, dtype: float64
125054 125061    592.0
Name: new_cases, dtype: float64
125055 125062    657.0
Name: new_cases, dtype: float64
125056 125063    562.0
Name: new_cases, dtype: float64
125057 125064    703.0
Name: new_cases, dtype: float64
125058 125065    522.0
Name: new_cases, dtype: float64
125059 125066    203.0
Name: new_cases, dtype: float64
125060 125067    766.0
Name: new_cases, dtype: float64
125061 125068    1031.0
Name: new_cases, dtype: float64
125062 125069    462.0
Name: new_cases, dtype: float64
125063 125070    1295.0
Name: new_cases, dtype: float64
125064 125071    1100.0
Name: new_cases, dtype: float64
125065 125072    916.0
Name: new_cases, dtype: float64
125066 125073    311.0
Name: new_cases, dtype: float64
125067 125074    1248.0
Name: new_cases, dtype: float64
125068 125075    1502.0
Name: new_cases, dtype: float64
125069 125076    1268.0
Name: new_cases, dtype: float64
125070 125077    1125.0
Name: new_cases, dtype: float64
125071 125078    1397.0
Name: new_cases, dtype: float64
125072 125079    914.0
Name: new_cases, dtype: float64
125073 125080    399.0
Name: new_cases, dtype: float64
125074 125081    1609.0
Name: new_cases, dtype: float64
125075 125082    1859.0
Name: new_cases, dtype: float64
125076 125083    1783.0
Name: new_cases, dtype: float64
125077 125084    1611.0
Name: new_cases, dtype: float64
125078 125085    1726.0
Name: new_cases, dtype: float64
125079 125086    1251.0
Name: new_cases, dtype: float64
125080 125087    592.0
Name: new_cases, dtype: float64
125081 125088    1886.0
Name: new_cases, dtype: float64
125082 125089    2488.0
Name: new_cases, dtype: float64
125083 125090    1932.0
Name: new_cases, dtype: float64
125084 125091    2164.0
Name: new_cases, dtype: float64
125085 125092    2281.0
Name: new_cases, dtype: float64
125086 125093    1411.0
Name: new_cases, dtype: float64
125087 125094    761.0
Name: new_cases, dtype: float64
125088 125095    2212.0
Name: new_cases, dtype: float64
125089 125096    2961.0
Name: new_cases, dtype: float64
125090 125097    2383.0
Name: new_cases, dtype: float64
125091 125098    2426.0
Name: new_cases, dtype: float64
125092 125099    2518.0
Name: new_cases, dtype: float64
125093 125100    2171.0
Name: new_cases, dtype: float64
125094 125101    1185.0
Name: new_cases, dtype: float64
125095 125102    2991.0
Name: new_cases, dtype: float64
125096 125103    4297.0
Name: new_cases, dtype: float64
125097 125104    3992.0
Name: new_cases, dtype: float64
125098 125105    4413.0
Name: new_cases, dtype: float64
125099 125106    4411.0
Name: new_cases, dtype: float64
125100 125107    3913.0
Name: new_cases, dtype: float64
125101 125108    1865.0
Name: new_cases, dtype: float64
125102 125109    4525.0
Name: new_cases, dtype: float64
125103 125110    6078.0
Name: new_cases, dtype: float64
125104 125111    6271.0
Name: new_cases, dtype: float64
125105 125112    6110.0
Name: new_cases, dtype: float64
125106 125113    6669.0
Name: new_cases, dtype: float64
125107 125114    5060.0
Name: new_cases, dtype: float64
125108 125115    3118.0
Name: new_cases, dtype: float64
125109 125116    3240.0
Name: new_cases, dtype: float64
125110 125117    8252.0
Name: new_cases, dtype: float64
125111 125118    8867.0
Name: new_cases, dtype: float64
125112 125119    8726.0
Name: new_cases, dtype: float64
125113 125120    8626.0
Name: new_cases, dtype: float64
125114 125121    6765.0
Name: new_cases, dtype: float64
125115 125122    4897.0
Name: new_cases, dtype: float64

125116 125123    8282.0
Name: new_cases, dtype: float64
125117 125124    9400.0
Name: new_cases, dtype: float64
125118 125125    9104.0
Name: new_cases, dtype: float64
125119 125126    9420.0
Name: new_cases, dtype: float64
125120 125127    9891.0
Name: new_cases, dtype: float64
125121 125128    7668.0
Name: new_cases, dtype: float64
125122 125129    5675.0
Name: new_cases, dtype: float64
125123 125130    10416.0
Name: new_cases, dtype: float64
125124 125131    10967.0
Name: new_cases, dtype: float64
125125 125132    8756.0
Name: new_cases, dtype: float64
125126 125133    10749.0
Name: new_cases, dtype: float64
125127 125134    12935.0
Name: new_cases, dtype: float64
125128 125135    9584.0
Name: new_cases, dtype: float64
125129 125136    7362.0
Name: new_cases, dtype: float64
125130 125137    11078.0
Name: new_cases, dtype: float64
125131 125138    13266.0
Name: new_cases, dtype: float64
125132 125139    13141.0
Name: new_cases, dtype: float64
125133 125140    12095.0
Name: new_cases, dtype: float64
125134 125141    11862.0
Name: new_cases, dtype: float64
125135 125142    9057.0
Name: new_cases, dtype: float64
125136 125143    7642.0
Name: new_cases, dtype: float64
125137 125144    10433.0
Name: new_cases, dtype: float64
125138 125145    12362.0
Name: new_cases, dtype: float64
125139 125146    9877.0
Name: new_cases, dtype: float64
125140 125147    17538.0
Name: new_cases, dtype: float64
125141 125148    11794.0
Name: new_cases, dtype: float64
125142 125149    8572.0
Name: new_cases, dtype: float64
125143 125150    4639.0
Name: new_cases, dtype: float64
125144 125151    9380.0
Name: new_cases, dtype: float64
125145 125152    10724.0
Name: new_cases, dtype: float64
125146 125153    9970.0
Name: new_cases, dtype: float64
125147 125154    7935.0
Name: new_cases, dtype: float64
125148 125155    7379.0
Name: new_cases, dtype: float64
125149 125156    5966.0
Name: new_cases, dtype: float64
125150 125157    2916.0
Name: new_cases, dtype: float64
125151 125158    6657.0
Name: new_cases, dtype: float64
125152 125159    6550.0
Name: new_cases, dtype: float64
125153 125160    8129.0
Name: new_cases, dtype: float64
125154 125161    5584.0
Name: new_cases, dtype: float64
125155 125162    4919.0
Name: new_cases, dtype: float64
125156 125163    4062.0
Name: new_cases, dtype: float64
125157 125164    1878.0
Name: new_cases, dtype: float64
125158 125165    5167.0
Name: new_cases, dtype: float64
125159 125166    2708.0
Name: new_cases, dtype: float64
125160 125167    7418.0
Name: new_cases, dtype: float64
125161 125168    5550.0
Name: new_cases, dtype: float64
125162 125169    1272.0
Name: new_cases, dtype: float64
125163 125170    660.0
Name: new_cases, dtype: float64
125164 125171    1644.0
Name: new_cases, dtype: float64
125165 125172    5715.0
Name: new_cases, dtype: float64
125166 125173    6313.0
Name: new_cases, dtype: float64
125167 125174    3883.0
Name: new_cases, dtype: float64
125168 125175    3721.0
Name: new_cases, dtype: float64
125169 125176    3272.0
Name: new_cases, dtype: float64
125170 125177    496.0
Name: new_cases, dtype: float64
125171 125178    1709.0
Name: new_cases, dtype: float64
125172 125179    4616.0
Name: new_cases, dtype: float64
125173 125180    4585.0
Name: new_cases, dtype: float64
125174 125181    3786.0
Name: new_cases, dtype: float64
125175 125182    1515.0
Name: new_cases, dtype: float64
125176 125183    3624.0
Name: new_cases, dtype: float64
125177 Series([], Name: new_cases, dtype: float64)
125178 124510    1.0
Name: new_cases, dtype: float64
125179 124511    0.0
Name: new_cases, dtype: float64
125180 124512    2.0
Name: new_cases, dtype: float64
125181 124513    2.0
Name: new_cases, dtype: float64
125182 124514    2.0
Name: new_cases, dtype: float64
125183 124515    0.0
Name: new_cases, dtype: float64
125216 125223    32.0
Name: new_cases, dtype: float64
125217 125224    52.0
Name: new_cases, dtype: float64
125218 125225    40.0
Name: new_cases, dtype: float64
125219 125226    38.0
Name: new_cases, dtype: float64
125220 125227    34.0
Name: new_cases, dtype: float64
125221 125228    22.0
Name: new_cases, dtype: float64
125222 125229    0.0
Name: new_cases, dtype: float64
125223 125230    11.0
Name: new_cases, dtype: float64
125224 125231    55.0
Name: new_cases, dtype: float64
125225 125232    42.0
Name: new_cases, dtype: float64
125226 125233    31.0
Name: new_cases, dtype: float64
125227 125234    28.0
Name: new_cases, dtype: float64
125228 125235    38.0
Name: new_cases, dtype: float64
125229 125236    48.0
Name: new_cases, dtype: float64
125230 125237    34.0
Name: new_cases, dtype: float64
125231 125238    70.0
Name: new_cases, dtype: float64
125232 125239    52.0
Name: new_cases, dtype: float64
125233 125240    46.0
Name: new_cases, dtype: float64
125234 125241    26.0
Name: new_cases, dtype: float64
125235 125242    46.0
Name: new_cases, dtype: float64
125236 125243    39.0
Name: new_cases, dtype: float64
125237 125244    56.0
Name: new_cases, dtype: float64
125238 125245    37.0
Name: new_cases, dtype: float64
125239 125246    43.0
Name: new_cases, dtype: float64
125240 125247    20.0
Name: new_cases, dtype: float64
125241 125248    24.0
Name: new_cases, dtype: float64
125242 125249    38.0
Name: new_cases, dtype: float64
125243 125250    32.0
Name: new_cases, dtype: float64
125244 125251    33.0
Name: new_cases, dtype: float64
125245 125252    36.0
Name: new_cases, dtype: float64
125246 125253    28.0
Name: new_cases, dtype: float64
125247 125254    17.0
Name: new_cases, dtype: float64
125248 125255    7.0
Name: new_cases, dtype: float64
125249 125256    8.0
Name: new_cases, dtype: float64
125250 125257    28.0
Name: new_cases, dtype: float64
125251 125258    20.0
Name: new_cases, dtype: float64
125252 125259    36.0
Name: new_cases, dtype: float64
125253 125260    13.0
Name: new_cases, dtype: float64
125254 125261    13.0
Name: new_cases, dtype: float64
125255 125262    5.0
Name: new_cases, dtype: float64
125256 125263    9.0
Name: new_cases, dtype: float64
125257 125264    9.0
Name: new_cases, dtype: float64
125258 125265    13.0
Name: new_cases, dtype: float64
125259 125266    7.0
Name: new_cases, dtype: float64
125260 125267    15.0
Name: new_cases, dtype: float64
125261 125268    8.0
Name: new_cases, dtype: float64
125262 125269    6.0
Name: new_cases, dtype: float64
125263 125270    6.0
Name: new_cases, dtype: float64
125264 125271    10.0
Name: new_cases, dtype: float64
125265 125272    11.0
Name: new_cases, dtype: float64
125266 125273    5.0
Name: new_cases, dtype: float64
125267 125274    5.0
Name: new_cases, dtype: float64
125268 125275    0.0
Name: new_cases, dtype: float64
125269 125276    0.0
Name: new_cases, dtype: float64
125270 125277    6.0
Name: new_cases, dtype: float64
125271 125278    3.0
Name: new_cases, dtype: float64
125272 125279    1.0
Name: new_cases, dtype: float64
125273 125280    1.0
Name: new_cases, dtype: float64
125274 125281    4.0
Name: new_cases, dtype: float64
125275 125282    3.0
Name: new_cases, dtype: float64
125276 125283    3.0
Name: new_cases, dtype: float64
125277 125284    1.0
Name: new_cases, dtype: float64
125278 125285    2.0
Name: new_cases, dtype: float64
125279 125286    1.0
Name: new_cases, dtype: float64
125280 125287    1.0
Name: new_cases, dtype: float64
125281 125288    0.0
Name: new_cases, dtype: float64
125282 125289    1.0
Name: new_cases, dtype: float64
125283 125290    0.0
Name: new_cases, dtype: float64
125284 125291    1.0
Name: new_cases, dtype: float64
125285 125292    1.0
Name: new_cases, dtype: float64
125286 125293    0.0
Name: new_cases, dtype: float64
125287 125294    0.0
Name: new_cases, dtype: float64
125288 125295    0.0
Name: new_cases, dtype: float64
125289 125296    0.0
Name: new_cases, dtype: float64
125290 125297    1.0
Name: new_cases, dtype: float64
125291 125298    0.0
Name: new_cases, dtype: float64
125292 125299    2.0
Name: new_cases, dtype: float64
125293 125300    2.0
Name: new_cases, dtype: float64
125294 125301    0.0
Name: new_cases, dtype: float64
125295 125302    0.0
Name: new_cases, dtype: float64
125296 125303    0.0
Name: new_cases, dtype: float64
125297 125304    0.0
Name: new_cases, dtype: float64
125298 125305    2.0
Name: new_cases, dtype: float64
125299 125306    2.0
Name: new_cases, dtype: float64
125300 125307    0.0
Name: new_cases, dtype: float64
125301 125308    2.0
Name: new_cases, dtype: float64
125302 125309    5.0
Name: new_cases, dtype: float64
125303 125310    1.0
Name: new_cases, dtype: float64

125304 125311    0.0
Name: new_cases, dtype: float64
125305 125312    1.0
Name: new_cases, dtype: float64
125306 125313    2.0
Name: new_cases, dtype: float64
125307 125314    0.0
Name: new_cases, dtype: float64
125308 125315    2.0
Name: new_cases, dtype: float64
125309 125316    2.0
Name: new_cases, dtype: float64
125310 125317    3.0
Name: new_cases, dtype: float64
125311 125318    1.0
Name: new_cases, dtype: float64
125312 125319    3.0
Name: new_cases, dtype: float64
125313 125320    4.0
Name: new_cases, dtype: float64
125314 125321    8.0
Name: new_cases, dtype: float64
125315 125322    2.0
Name: new_cases, dtype: float64
125316 125323    6.0
Name: new_cases, dtype: float64
125317 125324    1.0
Name: new_cases, dtype: float64
125318 125325    1.0
Name: new_cases, dtype: float64
125319 125326    13.0
Name: new_cases, dtype: float64
125320 125327    7.0
Name: new_cases, dtype: float64
125321 125328    6.0
Name: new_cases, dtype: float64
125322 125329    11.0
Name: new_cases, dtype: float64
125323 125330    14.0
Name: new_cases, dtype: float64
125324 125331    9.0
Name: new_cases, dtype: float64
125325 125332    4.0
Name: new_cases, dtype: float64
125326 125333    15.0
Name: new_cases, dtype: float64
125327 125334    13.0
Name: new_cases, dtype: float64
125328 125335    21.0
Name: new_cases, dtype: float64
125329 125336    16.0
Name: new_cases, dtype: float64
125330 125337    29.0
Name: new_cases, dtype: float64
125331 125338    21.0
Name: new_cases, dtype: float64
125332 125339    16.0
Name: new_cases, dtype: float64
125333 125340    23.0
Name: new_cases, dtype: float64
125334 125341    24.0
Name: new_cases, dtype: float64
125335 125342    13.0
Name: new_cases, dtype: float64
125336 125343    17.0
Name: new_cases, dtype: float64
125337 125344    34.0
Name: new_cases, dtype: float64
125338 125345    14.0
Name: new_cases, dtype: float64
125339 125346    8.0
Name: new_cases, dtype: float64
125340 125347    10.0
Name: new_cases, dtype: float64
125341 125348    19.0
Name: new_cases, dtype: float64
125342 125349    19.0
Name: new_cases, dtype: float64
125343 125350    19.0
Name: new_cases, dtype: float64
125344 125351    24.0
Name: new_cases, dtype: float64
125345 125352    6.0
Name: new_cases, dtype: float64
125346 125353    7.0
Name: new_cases, dtype: float64
125347 125354    24.0
Name: new_cases, dtype: float64
125348 125355    29.0
Name: new_cases, dtype: float64
125349 125356    27.0
Name: new_cases, dtype: float64
125350 125357    19.0
Name: new_cases, dtype: float64
125351 125358    14.0
Name: new_cases, dtype: float64
125352 125359    16.0
Name: new_cases, dtype: float64
125353 125360    5.0
Name: new_cases, dtype: float64
125354 125361    14.0
Name: new_cases, dtype: float64
125355 125362    14.0
Name: new_cases, dtype: float64
125356 125363    24.0
Name: new_cases, dtype: float64
125357 125364    17.0
Name: new_cases, dtype: float64
125358 125365    15.0
Name: new_cases, dtype: float64
125359 125366    9.0
Name: new_cases, dtype: float64
125360 125367    1.0
Name: new_cases, dtype: float64
125361 125368    9.0
Name: new_cases, dtype: float64
125362 125369    18.0
Name: new_cases, dtype: float64
125363 125370    15.0
Name: new_cases, dtype: float64
125364 125371    10.0
Name: new_cases, dtype: float64
125365 125372    14.0
Name: new_cases, dtype: float64
125366 125373    2.0
Name: new_cases, dtype: float64
125367 125374    6.0
Name: new_cases, dtype: float64
125368 125375    17.0
Name: new_cases, dtype: float64
125369 125376    31.0
Name: new_cases, dtype: float64
125370 125377    29.0
Name: new_cases, dtype: float64
125371 125378    37.0
Name: new_cases, dtype: float64
125372 125379    32.0
Name: new_cases, dtype: float64
125373 125380    15.0
Name: new_cases, dtype: float64
125374 125381    13.0
Name: new_cases, dtype: float64
125375 125382    27.0
Name: new_cases, dtype: float64
125376 125383    37.0
Name: new_cases, dtype: float64
125377 125384    43.0
Name: new_cases, dtype: float64
125378 125385    38.0
Name: new_cases, dtype: float64
125379 125386    43.0
Name: new_cases, dtype: float64
125380 125387    34.0
Name: new_cases, dtype: float64
125381 125388    14.0
Name: new_cases, dtype: float64
125382 125389    21.0
Name: new_cases, dtype: float64
125383 125390    36.0
Name: new_cases, dtype: float64
125384 125391    33.0
Name: new_cases, dtype: float64
125385 125392    42.0
Name: new_cases, dtype: float64
125386 125393    37.0
Name: new_cases, dtype: float64
125387 125394    31.0
Name: new_cases, dtype: float64
125388 125395    18.0
Name: new_cases, dtype: float64
125389 125396    41.0
Name: new_cases, dtype: float64
125390 125397    55.0
Name: new_cases, dtype: float64
125391 125398    53.0
Name: new_cases, dtype: float64
125392 125399    47.0
Name: new_cases, dtype: float64
125393 125400    43.0
Name: new_cases, dtype: float64
125394 125401    43.0
Name: new_cases, dtype: float64
125395 125402    25.0
Name: new_cases, dtype: float64
125396 125403    42.0
Name: new_cases, dtype: float64
125397 125404    80.0
Name: new_cases, dtype: float64
125398 125405    77.0
Name: new_cases, dtype: float64
125399 125406    108.0
Name: new_cases, dtype: float64
125400 125407    106.0
Name: new_cases, dtype: float64
125401 125408    99.0
Name: new_cases, dtype: float64
125402 125409    47.0
Name: new_cases, dtype: float64
125403 125410    82.0
Name: new_cases, dtype: float64
125404 125411    123.0
Name: new_cases, dtype: float64
125405 125412    104.0
Name: new_cases, dtype: float64
125406 125413    137.0
Name: new_cases, dtype: float64
125407 125414    114.0
Name: new_cases, dtype: float64
125408 125415    111.0
Name: new_cases, dtype: float64
125409 125416    50.0
Name: new_cases, dtype: float64
125410 125417    88.0
Name: new_cases, dtype: float64
125411 125418    136.0
Name: new_cases, dtype: float64
125412 125419    122.0
Name: new_cases, dtype: float64
125413 125420    191.0
Name: new_cases, dtype: float64
125414 125421    184.0
Name: new_cases, dtype: float64
125415 125422    159.0
Name: new_cases, dtype: float64
125416 125423    38.0
Name: new_cases, dtype: float64
125417 125424    99.0
Name: new_cases, dtype: float64
125418 125425    203.0
Name: new_cases, dtype: float64
125419 125426    175.0
Name: new_cases, dtype: float64
125420 125427    238.0
Name: new_cases, dtype: float64
125421 125428    227.0
Name: new_cases, dtype: float64
125422 125429    168.0
Name: new_cases, dtype: float64
125423 125430    175.0
Name: new_cases, dtype: float64
125424 125431    91.0
Name: new_cases, dtype: float64
125425 125432    356.0
Name: new_cases, dtype: float64
125426 125433    387.0
Name: new_cases, dtype: float64
125427 125434    365.0
Name: new_cases, dtype: float64
125428 125435    380.0
Name: new_cases, dtype: float64
125429 125436    411.0
Name: new_cases, dtype: float64
125430 125437    169.0
Name: new_cases, dtype: float64
125431 125438    399.0
Name: new_cases, dtype: float64
125432 125439    707.0
Name: new_cases, dtype: float64
125433 125440    745.0
Name: new_cases, dtype: float64
125434 125441    834.0
Name: new_cases, dtype: float64
125435 125442    899.0
Name: new_cases, dtype: float64
125436 125443    726.0
Name: new_cases, dtype: float64
125437 125444    537.0
Name: new_cases, dtype: float64
125438 125445    794.0
Name: new_cases, dtype: float64
125439 125446    1509.0
Name: new_cases, dtype: float64
125440 125447    1664.0
Name: new_cases, dtype: float64
125441 125448    1661.0
Name: new_cases, dtype: float64
125442 125449    1967.0
Name: new_cases, dtype: float64
125443 125450    1676.0
Name: new_cases, dtype: float64
125444 125451    1130.0
Name: new_cases, dtype: float64
125445 125452    1523.0
Name: new_cases, dtype: float64
125446 125453    2612.0
Name: new_cases, dtype: float64
125447 125454    2490.0
Name: new_cases, dtype: float64
125448 125455    1798.0
Name: new_cases, dtype: float64
125449 125456    1804.0
Name: new_cases, dtype: float64
125450 125457    1342.0
Name: new_cases, dtype: float64
125451 125458    557.0
Name: new_cases, dtype: float64
125452 125459    1176.0
Name: new_cases, dtype: float64
125453 125460    2026.0
Name: new_cases, dtype: float64
125454 125461    1686.0
Name: new_cases, dtype: float64
125455 125462    1564.0
Name: new_cases, dtype: float64
125456 125463    1612.0
Name: new_cases, dtype: float64
125457 125464    891.0
Name: new_cases, dtype: float64
125458 125465    464.0
Name: new_cases, dtype: float64
125459 125466    1092.0
Name: new_cases, dtype: float64
125460 125467    2222.0
Name: new_cases, dtype: float64
125461 125468    1931.0
Name: new_cases, dtype: float64

125462 125469    1515.0
Name: new_cases, dtype: float64
125463 125470    1737.0
Name: new_cases, dtype: float64
125464 125471    920.0
Name: new_cases, dtype: float64
125465 125472    502.0
Name: new_cases, dtype: float64
125466 125473    1393.0
Name: new_cases, dtype: float64
125467 125474    2027.0
Name: new_cases, dtype: float64
125468 125475    2070.0
Name: new_cases, dtype: float64
125469 125476    1546.0
Name: new_cases, dtype: float64
125470 125477    1704.0
Name: new_cases, dtype: float64
125471 125478    1024.0
Name: new_cases, dtype: float64
125472 125479    470.0
Name: new_cases, dtype: float64
125473 125480    1302.0
Name: new_cases, dtype: float64
125474 125481    2226.0
Name: new_cases, dtype: float64
125475 125482    1767.0
Name: new_cases, dtype: float64
125476 125483    1601.0
Name: new_cases, dtype: float64
125477 125484    1583.0
Name: new_cases, dtype: float64
125478 125485    1124.0
Name: new_cases, dtype: float64
125479 125486    433.0
Name: new_cases, dtype: float64
125480 125487    1321.0
Name: new_cases, dtype: float64
125481 125488    2431.0
Name: new_cases, dtype: float64
125482 125489    1783.0
Name: new_cases, dtype: float64
125483 125490    1784.0
Name: new_cases, dtype: float64
125484 125491    1642.0
Name: new_cases, dtype: float64
125485 125492    1030.0
Name: new_cases, dtype: float64
125486 125493    483.0
Name: new_cases, dtype: float64
125487 125494    1648.0
Name: new_cases, dtype: float64
125488 125495    2139.0
Name: new_cases, dtype: float64
125489 125496    1847.0
Name: new_cases, dtype: float64
125490 125497    1815.0
Name: new_cases, dtype: float64
125491 125498    1744.0
Name: new_cases, dtype: float64
125492 125499    833.0
Name: new_cases, dtype: float64
125493 125500    431.0
Name: new_cases, dtype: float64
125494 125501    1536.0
Name: new_cases, dtype: float64
125495 125502    2120.0
Name: new_cases, dtype: float64
125496 125503    1642.0
Name: new_cases, dtype: float64
125497 125504    1512.0
Name: new_cases, dtype: float64
125498 125505    1458.0
Name: new_cases, dtype: float64
125499 125506    886.0
Name: new_cases, dtype: float64
125500 125507    395.0
Name: new_cases, dtype: float64
125501 125508    1511.0
Name: new_cases, dtype: float64
125502 125509    2129.0
Name: new_cases, dtype: float64
125503 125510    2087.0
Name: new_cases, dtype: float64
125504 125511    1794.0
Name: new_cases, dtype: float64
125505 125512    369.0
Name: new_cases, dtype: float64
125506 125513    622.0
Name: new_cases, dtype: float64
125507 125514    521.0
Name: new_cases, dtype: float64
125508 125515    1978.0
Name: new_cases, dtype: float64
125509 125516    2435.0
Name: new_cases, dtype: float64
125510 125517    2412.0
Name: new_cases, dtype: float64
125511 125518    1798.0
Name: new_cases, dtype: float64
125512 125519    393.0
Name: new_cases, dtype: float64
125513 125520    743.0
Name: new_cases, dtype: float64
125514 125521    772.0
Name: new_cases, dtype: float64
125515 125522    2512.0
Name: new_cases, dtype: float64
125516 125523    3354.0
Name: new_cases, dtype: float64
125517 125524    2821.0
Name: new_cases, dtype: float64
125518 125525    2084.0
Name: new_cases, dtype: float64
125519 125526    1889.0
Name: new_cases, dtype: float64
125520 125527    763.0
Name: new_cases, dtype: float64
125521 125528    432.0
Name: new_cases, dtype: float64
125522 125529    1874.0
Name: new_cases, dtype: float64
125523 125530    2092.0
Name: new_cases, dtype: float64
125524 125531    1793.0
Name: new_cases, dtype: float64
125525 125532    1544.0
Name: new_cases, dtype: float64
125526 125533    1540.0
Name: new_cases, dtype: float64
125527 125534    569.0
Name: new_cases, dtype: float64
125528 125535    299.0
Name: new_cases, dtype: float64
125529 125536    1713.0
Name: new_cases, dtype: float64
125530 125537    1714.0
Name: new_cases, dtype: float64
125531 125538    1455.0
Name: new_cases, dtype: float64
125532 125539    1446.0
Name: new_cases, dtype: float64
125533 125540    1541.0
Name: new_cases, dtype: float64
125534 125541    537.0
Name: new_cases, dtype: float64
125535 125542    301.0
Name: new_cases, dtype: float64
125536 125543    1681.0
Name: new_cases, dtype: float64
125537 125544    1850.0
Name: new_cases, dtype: float64
125538 125545    1573.0
Name: new_cases, dtype: float64
125539 125546    1294.0
Name: new_cases, dtype: float64
125540 125547    1358.0
Name: new_cases, dtype: float64
125541 125548    586.0
Name: new_cases, dtype: float64
125542 125549    363.0
Name: new_cases, dtype: float64
125543 125550    1650.0
Name: new_cases, dtype: float64
125544 125551    1615.0
Name: new_cases, dtype: float64
125545 125552    1239.0
Name: new_cases, dtype: float64
125546 125553    959.0
Name: new_cases, dtype: float64
125547 125554    902.0
Name: new_cases, dtype: float64
125548 125555    501.0
Name: new_cases, dtype: float64
125549 125556    298.0
Name: new_cases, dtype: float64
125550 125557    364.0
Name: new_cases, dtype: float64
125551 125558    1431.0
Name: new_cases, dtype: float64
125552 125559    1345.0
Name: new_cases, dtype: float64
125553 125560    993.0
Name: new_cases, dtype: float64
125554 125561    1015.0
Name: new_cases, dtype: float64
125555 125562    329.0
Name: new_cases, dtype: float64
125556 125563    303.0
Name: new_cases, dtype: float64
125557 125564    740.0
Name: new_cases, dtype: float64
125558 125565    1086.0
Name: new_cases, dtype: float64
125559 125566    878.0
Name: new_cases, dtype: float64
125560 125567    912.0
Name: new_cases, dtype: float64
125561 125568    956.0
Name: new_cases, dtype: float64
125562 125569    415.0
Name: new_cases, dtype: float64
125563 125570    247.0
Name: new_cases, dtype: float64
125564 125571    902.0
Name: new_cases, dtype: float64
125565 125572    1089.0
Name: new_cases, dtype: float64
125566 125573    757.0
Name: new_cases, dtype: float64
125567 125574    914.0
Name: new_cases, dtype: float64
125568 125575    951.0
Name: new_cases, dtype: float64
125569 125576    454.0
Name: new_cases, dtype: float64
125570 125577    243.0
Name: new_cases, dtype: float64
125571 125578    732.0
Name: new_cases, dtype: float64
125572 125579    1210.0
Name: new_cases, dtype: float64
125573 125580    1019.0
Name: new_cases, dtype: float64
125574 125581    880.0
Name: new_cases, dtype: float64
125575 125582    921.0
Name: new_cases, dtype: float64
125576 125583    382.0
Name: new_cases, dtype: float64
125577 125584    210.0
Name: new_cases, dtype: float64
125578 125585    743.0
Name: new_cases, dtype: float64
125579 125586    953.0
Name: new_cases, dtype: float64
125580 125587    860.0
Name: new_cases, dtype: float64
125581 125588    770.0
Name: new_cases, dtype: float64
125582 125589    850.0
Name: new_cases, dtype: float64
125583 125590    520.0
Name: new_cases, dtype: float64
125584 125591    205.0
Name: new_cases, dtype: float64
125585 125592    918.0
Name: new_cases, dtype: float64
125586 125593    1076.0
Name: new_cases, dtype: float64
125587 125594    971.0
Name: new_cases, dtype: float64
125588 125595    938.0
Name: new_cases, dtype: float64
125589 125596    1027.0
Name: new_cases, dtype: float64
125590 125597    517.0
Name: new_cases, dtype: float64
125591 125598    291.0
Name: new_cases, dtype: float64
125592 125599    981.0
Name: new_cases, dtype: float64
125593 125600    1290.0
Name: new_cases, dtype: float64
125594 125601    1165.0
Name: new_cases, dtype: float64
125595 125602    1032.0
Name: new_cases, dtype: float64
125596 125603    1255.0
Name: new_cases, dtype: float64
125597 125604    638.0
Name: new_cases, dtype: float64
125598 125605    288.0
Name: new_cases, dtype: float64
125599 125606    1079.0
Name: new_cases, dtype: float64
125600 125607    1557.0
Name: new_cases, dtype: float64
125601 125608    1337.0
Name: new_cases, dtype: float64
125602 125609    1175.0
Name: new_cases, dtype: float64
125603 125610    1306.0
Name: new_cases, dtype: float64
125604 125611    721.0
Name: new_cases, dtype: float64
125605 125612    284.0
Name: new_cases, dtype: float64
125606 125613    273.0
Name: new_cases, dtype: float64
125607 125614    1192.0
Name: new_cases, dtype: float64
125608 125615    1526.0
Name: new_cases, dtype: float64
125609 125616    1283.0
Name: new_cases, dtype: float64
125610 125617    1251.0
Name: new_cases, dtype: float64
125611 125618    549.0
Name: new_cases, dtype: float64
125612 125619    287.0
Name: new_cases, dtype: float64
125613 125620    1050.0
Name: new_cases, dtype: float64
125614 125621    1240.0
Name: new_cases, dtype: float64
125615 125622    891.0
Name: new_cases, dtype: float64
125616 125623    859.0
Name: new_cases, dtype: float64
125617 125624    767.0
Name: new_cases, dtype: float64
125618 125625    478.0
Name: new_cases, dtype: float64
125619 125626    240.0
Name: new_cases, dtype: float64
125620 125627    720.0
Name: new_cases, dtype: float64
125621 125628    1036.0
Name: new_cases, dtype: float64
125622 125629    744.0
Name: new_cases, dtype: float64
125623 125630    900.0
Name: new_cases, dtype: float64
125624 125631    902.0
Name: new_cases, dtype: float64
125625 125632    415.0
Name: new_cases, dtype: float64
125626 125633    191.0
Name: new_cases, dtype: float64
125627 125634    804.0
Name: new_cases, dtype: float64
125628 125635    398.0
Name: new_cases, dtype: float64
125629 125636    918.0
Name: new_cases, dtype: float64
125630 125637    953.0
Name: new_cases, dtype: float64
125631 125638    1017.0
Name: new_cases, dtype: float64

125632 125639    363.0
Name: new_cases, dtype: float64
125633 125640    211.0
Name: new_cases, dtype: float64
125634 125641    894.0
Name: new_cases, dtype: float64
125635 125642    942.0
Name: new_cases, dtype: float64
125636 125643    837.0
Name: new_cases, dtype: float64
125637 125644    603.0
Name: new_cases, dtype: float64
125638 125645    634.0
Name: new_cases, dtype: float64
125639 125646    289.0
Name: new_cases, dtype: float64
125640 125647    149.0
Name: new_cases, dtype: float64
125641 125648    494.0
Name: new_cases, dtype: float64
125642 125649    724.0
Name: new_cases, dtype: float64
125643 125650    597.0
Name: new_cases, dtype: float64
125644 125651    474.0
Name: new_cases, dtype: float64
125645 125652    494.0
Name: new_cases, dtype: float64
125646 125653    296.0
Name: new_cases, dtype: float64
125647 125654    114.0
Name: new_cases, dtype: float64
125648 125655    497.0
Name: new_cases, dtype: float64
125649 125656    532.0
Name: new_cases, dtype: float64
125650 125657    358.0
Name: new_cases, dtype: float64
125651 125658    337.0
Name: new_cases, dtype: float64
125652 125659    383.0
Name: new_cases, dtype: float64
125653 125660    159.0
Name: new_cases, dtype: float64
125654 125661    83.0
Name: new_cases, dtype: float64
125655 125662    325.0
Name: new_cases, dtype: float64
125656 125663    388.0
Name: new_cases, dtype: float64
125657 125664    362.0
Name: new_cases, dtype: float64
125658 125665    292.0
Name: new_cases, dtype: float64
125659 125666    353.0
Name: new_cases, dtype: float64
125660 125667    138.0
Name: new_cases, dtype: float64
125661 125668    91.0
Name: new_cases, dtype: float64
125662 125669    323.0
Name: new_cases, dtype: float64
125663 125670    374.0
Name: new_cases, dtype: float64
125664 125671    273.0
Name: new_cases, dtype: float64
125665 125672    281.0
Name: new_cases, dtype: float64
125666 125673    245.0
Name: new_cases, dtype: float64
125667 125674    157.0
Name: new_cases, dtype: float64
125668 125675    57.0
Name: new_cases, dtype: float64
125669 125676    220.0
Name: new_cases, dtype: float64
125670 125677    255.0
Name: new_cases, dtype: float64
125671 125678    196.0
Name: new_cases, dtype: float64
125672 125679    121.0
Name: new_cases, dtype: float64
125673 125680    128.0
Name: new_cases, dtype: float64
125674 125681    91.0
Name: new_cases, dtype: float64
125675 125682    24.0
Name: new_cases, dtype: float64
125676 125683    114.0
Name: new_cases, dtype: float64
125677 125684    120.0
Name: new_cases, dtype: float64
125678 125685    83.0
Name: new_cases, dtype: float64
125679 125686    87.0
Name: new_cases, dtype: float64
125680 125687    85.0
Name: new_cases, dtype: float64
125681 125688    26.0
Name: new_cases, dtype: float64
125682 125689    19.0
Name: new_cases, dtype: float64
125683 125690    65.0
Name: new_cases, dtype: float64
125684 125691    50.0
Name: new_cases, dtype: float64
125685 125692    48.0
Name: new_cases, dtype: float64
125686 125693    46.0
Name: new_cases, dtype: float64
125687 125694    11.0
Name: new_cases, dtype: float64
125688 125695    19.0
Name: new_cases, dtype: float64
125689 125696    12.0
Name: new_cases, dtype: float64
125690 125697    35.0
Name: new_cases, dtype: float64
125691 125698    48.0
Name: new_cases, dtype: float64
125692 125699    23.0
Name: new_cases, dtype: float64
125693 125700    25.0
Name: new_cases, dtype: float64
125694 125701    30.0
Name: new_cases, dtype: float64
125695 125702    8.0
Name: new_cases, dtype: float64
125696 125703    8.0
Name: new_cases, dtype: float64
125697 125704    48.0
Name: new_cases, dtype: float64
125698 125705    73.0
Name: new_cases, dtype: float64
125699 125706    69.0
Name: new_cases, dtype: float64
125700 125707    84.0
Name: new_cases, dtype: float64
125701 125708    135.0
Name: new_cases, dtype: float64
125702 125709    25.0
Name: new_cases, dtype: float64
125703 125710    12.0
Name: new_cases, dtype: float64
125704 125711    84.0
Name: new_cases, dtype: float64
125705 125712    30.0
Name: new_cases, dtype: float64
125706 125713    56.0
Name: new_cases, dtype: float64
125707 125714    63.0
Name: new_cases, dtype: float64
125708 125715    61.0
Name: new_cases, dtype: float64
125709 125716    21.0
Name: new_cases, dtype: float64
125710 125717    9.0
Name: new_cases, dtype: float64
125711 125718    88.0
Name: new_cases, dtype: float64
125712 125719    110.0
Name: new_cases, dtype: float64
125713 125720    71.0
Name: new_cases, dtype: float64
125714 125721    57.0
Name: new_cases, dtype: float64
125715 125722    94.0
Name: new_cases, dtype: float64
125716 125723    32.0
Name: new_cases, dtype: float64
125717 125724    23.0
Name: new_cases, dtype: float64
125718 125725    106.0
Name: new_cases, dtype: float64
125719 125726    84.0
Name: new_cases, dtype: float64
125720 125727    99.0
Name: new_cases, dtype: float64
125721 125728    116.0
Name: new_cases, dtype: float64
125722 125729    136.0
Name: new_cases, dtype: float64
125723 125730    58.0
Name: new_cases, dtype: float64
125724 125731    31.0
Name: new_cases, dtype: float64
125725 125732    182.0
Name: new_cases, dtype: float64
125726 125733    139.0
Name: new_cases, dtype: float64
125727 125734    139.0
Name: new_cases, dtype: float64
125728 125735    145.0
Name: new_cases, dtype: float64
125729 125736    132.0
Name: new_cases, dtype: float64
125730 125737    68.0
Name: new_cases, dtype: float64
125731 125738    47.0
Name: new_cases, dtype: float64
125732 125739    216.0
Name: new_cases, dtype: float64
125733 125740    247.0
Name: new_cases, dtype: float64
125734 125741    248.0
Name: new_cases, dtype: float64
125735 125742    201.0
Name: new_cases, dtype: float64
125736 125743    265.0
Name: new_cases, dtype: float64
125737 125744    95.0
Name: new_cases, dtype: float64
125738 125745    56.0
Name: new_cases, dtype: float64
125739 125746    320.0
Name: new_cases, dtype: float64
125740 125747    385.0
Name: new_cases, dtype: float64
125741 125748    382.0
Name: new_cases, dtype: float64
125742 125749    333.0
Name: new_cases, dtype: float64
125743 125750    399.0
Name: new_cases, dtype: float64
125744 125751    244.0
Name: new_cases, dtype: float64
125745 125752    117.0
Name: new_cases, dtype: float64
125746 125753    477.0
Name: new_cases, dtype: float64
125747 125754    508.0
Name: new_cases, dtype: float64
125748 125755    510.0
Name: new_cases, dtype: float64
125749 125756    544.0
Name: new_cases, dtype: float64
125750 125757    538.0
Name: new_cases, dtype: float64
125751 125758    273.0
Name: new_cases, dtype: float64
125752 125759    143.0
Name: new_cases, dtype: float64
125753 125760    541.0
Name: new_cases, dtype: float64
125754 125761    764.0
Name: new_cases, dtype: float64
125755 125762    674.0
Name: new_cases, dtype: float64
125756 125763    612.0
Name: new_cases, dtype: float64
125757 125764    742.0
Name: new_cases, dtype: float64
125758 125765    317.0
Name: new_cases, dtype: float64
125759 125766    234.0
Name: new_cases, dtype: float64
125760 125767    877.0
Name: new_cases, dtype: float64
125761 125768    1094.0
Name: new_cases, dtype: float64
125762 125769    1017.0
Name: new_cases, dtype: float64
125763 125770    999.0
Name: new_cases, dtype: float64
125764 125771    1087.0
Name: new_cases, dtype: float64
125765 125772    559.0
Name: new_cases, dtype: float64
125766 125773    283.0
Name: new_cases, dtype: float64
125767 125774    1396.0
Name: new_cases, dtype: float64
125768 125775    1364.0
Name: new_cases, dtype: float64
125769 125776    1327.0
Name: new_cases, dtype: float64
125770 125777    1143.0
Name: new_cases, dtype: float64
125771 125778    1248.0
Name: new_cases, dtype: float64
125772 125779    544.0
Name: new_cases, dtype: float64
125773 125780    291.0
Name: new_cases, dtype: float64
125774 125781    1309.0
Name: new_cases, dtype: float64
125775 125782    1188.0
Name: new_cases, dtype: float64
125776 125783    1011.0
Name: new_cases, dtype: float64
125777 125784    941.0
Name: new_cases, dtype: float64
125778 125785    1006.0
Name: new_cases, dtype: float64
125779 125786    445.0
Name: new_cases, dtype: float64
125780 125787    285.0
Name: new_cases, dtype: float64
125781 125788    1039.0
Name: new_cases, dtype: float64
125782 125789    1339.0
Name: new_cases, dtype: float64
125783 125790    1031.0
Name: new_cases, dtype: float64

125784 125791    971.0
Name: new_cases, dtype: float64
125785 125792    993.0
Name: new_cases, dtype: float64
125786 125793    530.0
Name: new_cases, dtype: float64
125787 125794    225.0
Name: new_cases, dtype: float64
125788 125795    979.0
Name: new_cases, dtype: float64
125789 125796    1212.0
Name: new_cases, dtype: float64
125790 125797    969.0
Name: new_cases, dtype: float64
125791 125798    841.0
Name: new_cases, dtype: float64
125792 125799    885.0
Name: new_cases, dtype: float64
125793 125800    489.0
Name: new_cases, dtype: float64
125794 125801    186.0
Name: new_cases, dtype: float64
125795 125802    1010.0
Name: new_cases, dtype: float64
125796 125803    1228.0
Name: new_cases, dtype: float64
125797 125804    1081.0
Name: new_cases, dtype: float64
125798 125805    1101.0
Name: new_cases, dtype: float64
125799 125806    1439.0
Name: new_cases, dtype: float64
125800 125807    633.0
Name: new_cases, dtype: float64
125801 125808    365.0
Name: new_cases, dtype: float64
125802 125809    1669.0
Name: new_cases, dtype: float64
125803 125810    2146.0
Name: new_cases, dtype: float64
125804 125811    1846.0
Name: new_cases, dtype: float64
125805 125812    1976.0
Name: new_cases, dtype: float64
125806 125813    2274.0
Name: new_cases, dtype: float64
125807 125814    1501.0
Name: new_cases, dtype: float64
125808 125815    707.0
Name: new_cases, dtype: float64
125809 125816    2294.0
Name: new_cases, dtype: float64
125810 125817    3169.0
Name: new_cases, dtype: float64
125811 125818    2646.0
Name: new_cases, dtype: float64
125812 125819    2477.0
Name: new_cases, dtype: float64
125813 125820    2982.0
Name: new_cases, dtype: float64
125814 125821    1662.0
Name: new_cases, dtype: float64
125815 125822    1258.0
Name: new_cases, dtype: float64
125816 125823    1138.0
Name: new_cases, dtype: float64
125817 125824    3453.0
Name: new_cases, dtype: float64
125818 125825    4521.0
Name: new_cases, dtype: float64
125819 125826    3776.0
Name: new_cases, dtype: float64
125820 125827    3664.0
Name: new_cases, dtype: float64
125821 125828    2319.0
Name: new_cases, dtype: float64
125822 125829    1283.0
Name: new_cases, dtype: float64
125823 125830    3352.0
Name: new_cases, dtype: float64
125824 125831    4481.0
Name: new_cases, dtype: float64
125825 125832    3574.0
Name: new_cases, dtype: float64
125826 125833    3440.0
Name: new_cases, dtype: float64
125827 125834    3666.0
Name: new_cases, dtype: float64
125828 125835    2367.0
Name: new_cases, dtype: float64
125829 125836    1822.0
Name: new_cases, dtype: float64
125830 125837    3770.0
Name: new_cases, dtype: float64
125831 125838    4277.0
Name: new_cases, dtype: float64
125832 125839    3666.0
Name: new_cases, dtype: float64
125833 125840    3526.0
Name: new_cases, dtype: float64
125834 125841    3236.0
Name: new_cases, dtype: float64
125835 125842    2246.0
Name: new_cases, dtype: float64
125836 125843    1398.0
Name: new_cases, dtype: float64
125837 125844    3394.0
Name: new_cases, dtype: float64
125838 125845    3146.0
Name: new_cases, dtype: float64
125839 125846    2678.0
Name: new_cases, dtype: float64
125840 125847    2363.0
Name: new_cases, dtype: float64
125841 125848    2234.0
Name: new_cases, dtype: float64
125842 125849    1478.0
Name: new_cases, dtype: float64
125843 125850    1037.0
Name: new_cases, dtype: float64
125844 125851    2485.0
Name: new_cases, dtype: float64
125845 125852    2264.0
Name: new_cases, dtype: float64
125846 125853    2126.0
Name: new_cases, dtype: float64
125847 125854    1747.0
Name: new_cases, dtype: float64
125848 125855    1910.0
Name: new_cases, dtype: float64
125849 125856    1119.0
Name: new_cases, dtype: float64
125850 125857    775.0
Name: new_cases, dtype: float64
125851 125858    1954.0
Name: new_cases, dtype: float64
125852 125859    1886.0
Name: new_cases, dtype: float64
125853 125860    1687.0
Name: new_cases, dtype: float64
125854 125861    1323.0
Name: new_cases, dtype: float64
125855 125862    1480.0
Name: new_cases, dtype: float64
125856 125863    783.0
Name: new_cases, dtype: float64
125857 125864    681.0
Name: new_cases, dtype: float64
125858 125865    1714.0
Name: new_cases, dtype: float64
125859 125866    1526.0
Name: new_cases, dtype: float64
125860 125867    1355.0
Name: new_cases, dtype: float64
125861 125868    1278.0
Name: new_cases, dtype: float64
125862 125869    1288.0
Name: new_cases, dtype: float64
125863 125870    768.0
Name: new_cases, dtype: float64
125864 125871    587.0
Name: new_cases, dtype: float64
125865 125872    1554.0
Name: new_cases, dtype: float64
125866 125873    1263.0
Name: new_cases, dtype: float64
125867 125874    1127.0
Name: new_cases, dtype: float64
125868 125875    1205.0
Name: new_cases, dtype: float64
125869 125876    1088.0
Name: new_cases, dtype: float64
125870 125877    671.0
Name: new_cases, dtype: float64
125871 125878    698.0
Name: new_cases, dtype: float64
125872 125879    1813.0
Name: new_cases, dtype: float64
125873 125880    1867.0
Name: new_cases, dtype: float64
125874 125881    1717.0
Name: new_cases, dtype: float64
125875 125882    1896.0
Name: new_cases, dtype: float64
125876 125883    1663.0
Name: new_cases, dtype: float64
125877 125884    843.0
Name: new_cases, dtype: float64
125878 125885    1011.0
Name: new_cases, dtype: float64
125879 125886    3395.0
Name: new_cases, dtype: float64
125880 125887    4067.0
Name: new_cases, dtype: float64
125881 125888    3833.0
Name: new_cases, dtype: float64
125882 125889    4067.0
Name: new_cases, dtype: float64
125883 125890    4510.0
Name: new_cases, dtype: float64
125884 125216    2.0
Name: new_cases, dtype: float64
125885 125217    5.0
Name: new_cases, dtype: float64
125886 125218    0.0
Name: new_cases, dtype: float64
125887 125219    9.0
Name: new_cases, dtype: float64
125888 125220    0.0
Name: new_cases, dtype: float64
125889 125221    15.0
Name: new_cases, dtype: float64
125890 125222    26.0
Name: new_cases, dtype: float64
127036 127043    4.0
Name: new_cases, dtype: float64
127037 127044    7.0
Name: new_cases, dtype: float64
127038 127045    14.0
Name: new_cases, dtype: float64
127039 127046    13.0
Name: new_cases, dtype: float64
127040 127047    11.0
Name: new_cases, dtype: float64
127041 127048    0.0
Name: new_cases, dtype: float64
127042 127049    54.0
Name: new_cases, dtype: float64
127043 127050    34.0
Name: new_cases, dtype: float64
127044 127051    52.0
Name: new_cases, dtype: float64
127045 127052    38.0
Name: new_cases, dtype: float64
127046 127053    34.0
Name: new_cases, dtype: float64
127047 127054    128.0
Name: new_cases, dtype: float64
127048 127055    152.0
Name: new_cases, dtype: float64
127049 127056    155.0
Name: new_cases, dtype: float64
127050 127057    218.0
Name: new_cases, dtype: float64
127051 127058    243.0
Name: new_cases, dtype: float64
127052 127059    17.0
Name: new_cases, dtype: float64
127053 127060    93.0
Name: new_cases, dtype: float64
127054 127061    46.0
Name: new_cases, dtype: float64
127055 127062    27.0
Name: new_cases, dtype: float64
127056 127063    27.0
Name: new_cases, dtype: float64
127057 127064    82.0
Name: new_cases, dtype: float64
127058 127065    43.0
Name: new_cases, dtype: float64
127059 127066    80.0
Name: new_cases, dtype: float64
127060 127067    70.0
Name: new_cases, dtype: float64
127061 127068    31.0
Name: new_cases, dtype: float64
127062 127069    63.0
Name: new_cases, dtype: float64
127063 127070    96.0
Name: new_cases, dtype: float64
127064 127071    89.0
Name: new_cases, dtype: float64
127065 127072    69.0
Name: new_cases, dtype: float64
127066 127073    25.0
Name: new_cases, dtype: float64
127067 127074    145.0
Name: new_cases, dtype: float64
127068 127075    99.0
Name: new_cases, dtype: float64
127069 127076    143.0
Name: new_cases, dtype: float64
127070 127077    91.0
Name: new_cases, dtype: float64
127071 127078    99.0
Name: new_cases, dtype: float64
127072 127079    178.0
Name: new_cases, dtype: float64
127073 127080    251.0
Name: new_cases, dtype: float64
127074 127081    124.0
Name: new_cases, dtype: float64
127075 127082    142.0
Name: new_cases, dtype: float64
127076 127083    165.0
Name: new_cases, dtype: float64
127077 127084    170.0
Name: new_cases, dtype: float64
127078 127085    318.0
Name: new_cases, dtype: float64
127079 127086    267.0
Name: new_cases, dtype: float64
127080 127087    141.0
Name: new_cases, dtype: float64
127081 127088    185.0
Name: new_cases, dtype: float64
127082 127089    247.0
Name: new_cases, dtype: float64
127083 127090    203.0
Name: new_cases, dtype: float64
127084 127091    354.0
Name: new_cases, dtype: float64
127085 127092    297.0
Name: new_cases, dtype: float64
127086 127093    304.0
Name: new_cases, dtype: float64
127087 127094    385.0
Name: new_cases, dtype: float64

127088 127095    447.0
Name: new_cases, dtype: float64
127089 127096    437.0
Name: new_cases, dtype: float64
127090 127097    352.0
Name: new_cases, dtype: float64
127091 127098    236.0
Name: new_cases, dtype: float64
127092 127099    424.0
Name: new_cases, dtype: float64
127093 127100    663.0
Name: new_cases, dtype: float64
127094 127101    525.0
Name: new_cases, dtype: float64
127095 127102    595.0
Name: new_cases, dtype: float64
127096 127103    637.0
Name: new_cases, dtype: float64
127097 127104    698.0
Name: new_cases, dtype: float64
127098 127105    724.0
Name: new_cases, dtype: float64
127099 127106    665.0
Name: new_cases, dtype: float64
127100 127107    785.0
Name: new_cases, dtype: float64
127101 127108    831.0
Name: new_cases, dtype: float64
127102 127109    1160.0
Name: new_cases, dtype: float64
127103 127110    918.0
Name: new_cases, dtype: float64
127104 127111    767.0
Name: new_cases, dtype: float64
127105 127112    803.0
Name: new_cases, dtype: float64
127106 127113    1134.0
Name: new_cases, dtype: float64
127107 127114    988.0
Name: new_cases, dtype: float64
127108 127115    1218.0
Name: new_cases, dtype: float64
127109 127116    1240.0
Name: new_cases, dtype: float64
127110 127117    1032.0
Name: new_cases, dtype: float64
127111 127118    649.0
Name: new_cases, dtype: float64
127112 127119    1673.0
Name: new_cases, dtype: float64
127113 127120    1466.0
Name: new_cases, dtype: float64
127114 127121    1837.0
Name: new_cases, dtype: float64
127115 127122    1727.0
Name: new_cases, dtype: float64
127116 127123    1716.0
Name: new_cases, dtype: float64
127117 127124    1674.0
Name: new_cases, dtype: float64
127118 127125    1455.0
Name: new_cases, dtype: float64
127119 127126    1713.0
Name: new_cases, dtype: float64
127120 127127    3267.0
Name: new_cases, dtype: float64
127121 127128    2642.0
Name: new_cases, dtype: float64
127122 127129    2539.0
Name: new_cases, dtype: float64
127123 127130    2312.0
Name: new_cases, dtype: float64
127124 127131    2594.0
Name: new_cases, dtype: float64
127125 127132    2112.0
Name: new_cases, dtype: float64
127126 127133    2430.0
Name: new_cases, dtype: float64
127127 127134    3147.0
Name: new_cases, dtype: float64
127128 127135    3359.0
Name: new_cases, dtype: float64
127129 127136    3809.0
Name: new_cases, dtype: float64
127130 127137    4302.0
Name: new_cases, dtype: float64
127131 127138    3495.0
Name: new_cases, dtype: float64
127132 127139    2801.0
Name: new_cases, dtype: float64
127133 127140    4078.0
Name: new_cases, dtype: float64
127134 127141    3478.0
Name: new_cases, dtype: float64
127135 127142    3825.0
Name: new_cases, dtype: float64
127136 127143    4966.0
Name: new_cases, dtype: float64
127137 127144    4621.0
Name: new_cases, dtype: float64
127138 127145    4288.0
Name: new_cases, dtype: float64
127139 127146    4518.0
Name: new_cases, dtype: float64
127140 127147    5688.0
Name: new_cases, dtype: float64
127141 127148    6579.0
Name: new_cases, dtype: float64
127142 127149    6215.0
Name: new_cases, dtype: float64
127143 127150    7210.0
Name: new_cases, dtype: float64
127144 127151    6334.0
Name: new_cases, dtype: float64
127145 127152    6130.0
Name: new_cases, dtype: float64
127146 127153    6945.0
Name: new_cases, dtype: float64
127147 127154    8124.0
Name: new_cases, dtype: float64
127148 127155    8728.0
Name: new_cases, dtype: float64
127149 127156    9063.0
Name: new_cases, dtype: float64
127150 127157    10853.0
Name: new_cases, dtype: float64
127151 127158    8773.0
Name: new_cases, dtype: float64
127152 127159    8971.0
Name: new_cases, dtype: float64
127153 127160    10134.0
Name: new_cases, dtype: float64
127154 127161    8810.0
Name: new_cases, dtype: float64
127155 127162    13674.0
Name: new_cases, dtype: float64
127156 127163    12348.0
Name: new_cases, dtype: float64
127157 127164    13497.0
Name: new_cases, dtype: float64
127158 127165    12058.0
Name: new_cases, dtype: float64
127159 127166    11554.0
Name: new_cases, dtype: float64
127160 127167    10496.0
Name: new_cases, dtype: float64
127161 127168    12757.0
Name: new_cases, dtype: float64
127162 127169    13172.0
Name: new_cases, dtype: float64
127163 127170    13373.0
Name: new_cases, dtype: float64
127164 127171    13285.0
Name: new_cases, dtype: float64
127165 127172    13449.0
Name: new_cases, dtype: float64
127166 127173    9300.0
Name: new_cases, dtype: float64
127167 127174    8170.0
Name: new_cases, dtype: float64
127168 127175    13150.0
Name: new_cases, dtype: float64
127169 127176    13104.0
Name: new_cases, dtype: float64
127170 127177    13944.0
Name: new_cases, dtype: float64
127171 127178    12204.0
Name: new_cases, dtype: float64
127172 127179    11233.0
Name: new_cases, dtype: float64
127173 127180    7096.0
Name: new_cases, dtype: float64
127174 127181    7232.0
Name: new_cases, dtype: float64
127175 127182    11362.0
Name: new_cases, dtype: float64
127176 127183    11046.0
Name: new_cases, dtype: float64
127177 127184    11014.0
Name: new_cases, dtype: float64
127178 127185    10107.0
Name: new_cases, dtype: float64
127179 127186    8195.0
Name: new_cases, dtype: float64
127180 127187    5377.0
Name: new_cases, dtype: float64
127181 127188    4456.0
Name: new_cases, dtype: float64
127182 127189    8559.0
Name: new_cases, dtype: float64
127183 127190    8307.0
Name: new_cases, dtype: float64
127184 127191    7292.0
Name: new_cases, dtype: float64
127185 127192    7712.0
Name: new_cases, dtype: float64
127186 127193    6671.0
Name: new_cases, dtype: float64
127187 127194    3739.0
Name: new_cases, dtype: float64
127188 127195    2511.0
Name: new_cases, dtype: float64
127189 127196    2810.0
Name: new_cases, dtype: float64
127190 127197    3946.0
Name: new_cases, dtype: float64
127191 127198    6275.0
Name: new_cases, dtype: float64
127192 127199    4513.0
Name: new_cases, dtype: float64
127193 127200    3692.0
Name: new_cases, dtype: float64
127194 127201    2541.0
Name: new_cases, dtype: float64
127195 127202    2258.0
Name: new_cases, dtype: float64
127196 127203    3916.0
Name: new_cases, dtype: float64
127197 127204    3880.0
Name: new_cases, dtype: float64
127198 127205    3398.0
Name: new_cases, dtype: float64
127199 127206    3707.0
Name: new_cases, dtype: float64
127200 127207    2728.0
Name: new_cases, dtype: float64
127201 127208    1677.0
Name: new_cases, dtype: float64
127202 127209    1567.0
Name: new_cases, dtype: float64
127203 127210    2684.0
Name: new_cases, dtype: float64
127204 127211    2585.0
Name: new_cases, dtype: float64
127205 127212    1846.0
Name: new_cases, dtype: float64
127206 127213    2419.0
Name: new_cases, dtype: float64
127207 127214    2505.0
Name: new_cases, dtype: float64
127208 127215    1985.0
Name: new_cases, dtype: float64
127209 127216    1218.0
Name: new_cases, dtype: float64
127210 127217    2336.0
Name: new_cases, dtype: float64
127211 127218    2420.0
Name: new_cases, dtype: float64
127212 127219    2063.0
Name: new_cases, dtype: float64
127213 127220    1806.0
Name: new_cases, dtype: float64
127214 127221    1633.0
Name: new_cases, dtype: float64
127215 127222    845.0
Name: new_cases, dtype: float64
127216 127223    1079.0
Name: new_cases, dtype: float64
127217 127224    1990.0
Name: new_cases, dtype: float64
127218 127225    2007.0
Name: new_cases, dtype: float64
127219 127226    1960.0
Name: new_cases, dtype: float64
127220 127227    1816.0
Name: new_cases, dtype: float64
127221 127228    1579.0
Name: new_cases, dtype: float64
127222 127229    956.0
Name: new_cases, dtype: float64
127223 127230    772.0
Name: new_cases, dtype: float64
127224 127231    1923.0
Name: new_cases, dtype: float64
127225 127232    2128.0
Name: new_cases, dtype: float64
127226 127233    2055.0
Name: new_cases, dtype: float64
127227 127234    2029.0
Name: new_cases, dtype: float64
127228 127235    1555.0
Name: new_cases, dtype: float64
127229 127236    725.0
Name: new_cases, dtype: float64
127230 127237    1346.0
Name: new_cases, dtype: float64
127231 127238    1906.0
Name: new_cases, dtype: float64
127232 127239    1861.0
Name: new_cases, dtype: float64
127233 127240    1480.0
Name: new_cases, dtype: float64
127234 127241    969.0
Name: new_cases, dtype: float64
127235 127242    1268.0
Name: new_cases, dtype: float64
127236 127243    903.0
Name: new_cases, dtype: float64
127237 127244    903.0
Name: new_cases, dtype: float64
127238 127245    1767.0
Name: new_cases, dtype: float64
127239 127246    1745.0
Name: new_cases, dtype: float64
127240 127247    1749.0
Name: new_cases, dtype: float64
127241 127248    1883.0
Name: new_cases, dtype: float64
127242 127249    1573.0
Name: new_cases, dtype: float64
127243 127250    926.0
Name: new_cases, dtype: float64
127244 127251    1027.0
Name: new_cases, dtype: float64
127245 127252    1913.0
Name: new_cases, dtype: float64
127246 127253    1736.0
Name: new_cases, dtype: float64
127247 127254    1461.0
Name: new_cases, dtype: float64
127248 127255    2544.0
Name: new_cases, dtype: float64
127249 127256    1575.0
Name: new_cases, dtype: float64
127250 127257    888.0
Name: new_cases, dtype: float64
127251 127258    1178.0
Name: new_cases, dtype: float64
127252 127259    1877.0
Name: new_cases, dtype: float64

127253 127260    1770.0
Name: new_cases, dtype: float64
127254 127261    2019.0
Name: new_cases, dtype: float64
127255 127262    1928.0
Name: new_cases, dtype: float64
127256 127263    1662.0
Name: new_cases, dtype: float64
127257 127264    1461.0
Name: new_cases, dtype: float64
127258 127265    1050.0
Name: new_cases, dtype: float64
127259 127266    2055.0
Name: new_cases, dtype: float64
127260 127267    2156.0
Name: new_cases, dtype: float64
127261 127268    1897.0
Name: new_cases, dtype: float64
127262 127269    1834.0
Name: new_cases, dtype: float64
127263 127270    1622.0
Name: new_cases, dtype: float64
127264 127271    891.0
Name: new_cases, dtype: float64
127265 127272    1092.0
Name: new_cases, dtype: float64
127266 127273    1863.0
Name: new_cases, dtype: float64
127267 127274    2056.0
Name: new_cases, dtype: float64
127268 127275    1912.0
Name: new_cases, dtype: float64
127269 127276    1770.0
Name: new_cases, dtype: float64
127270 127277    1371.0
Name: new_cases, dtype: float64
127271 127278    772.0
Name: new_cases, dtype: float64
127272 127279    1241.0
Name: new_cases, dtype: float64
127273 127280    1712.0
Name: new_cases, dtype: float64
127274 127281    1866.0
Name: new_cases, dtype: float64
127275 127282    1761.0
Name: new_cases, dtype: float64
127276 127283    1731.0
Name: new_cases, dtype: float64
127277 127284    1372.0
Name: new_cases, dtype: float64
127278 127285    1247.0
Name: new_cases, dtype: float64
127279 127286    1729.0
Name: new_cases, dtype: float64
127280 127287    2140.0
Name: new_cases, dtype: float64
127281 127288    2338.0
Name: new_cases, dtype: float64
127282 127289    2213.0
Name: new_cases, dtype: float64
127283 127290    2237.0
Name: new_cases, dtype: float64
127284 127291    1842.0
Name: new_cases, dtype: float64
127285 127292    1245.0
Name: new_cases, dtype: float64
127286 127293    1987.0
Name: new_cases, dtype: float64
127287 127294    2888.0
Name: new_cases, dtype: float64
127288 127295    2514.0
Name: new_cases, dtype: float64
127289 127296    3105.0
Name: new_cases, dtype: float64
127290 127297    2646.0
Name: new_cases, dtype: float64
127291 127298    2270.0
Name: new_cases, dtype: float64
127292 127299    2080.0
Name: new_cases, dtype: float64
127293 127300    2493.0
Name: new_cases, dtype: float64
127294 127301    3250.0
Name: new_cases, dtype: float64
127295 127302    3069.0
Name: new_cases, dtype: float64
127296 127303    3370.0
Name: new_cases, dtype: float64
127297 127304    3198.0
Name: new_cases, dtype: float64
127298 127305    2563.0
Name: new_cases, dtype: float64
127299 127306    2302.0
Name: new_cases, dtype: float64
127300 127307    2295.0
Name: new_cases, dtype: float64
127301 127308    4173.0
Name: new_cases, dtype: float64
127302 127309    4400.0
Name: new_cases, dtype: float64
127303 127310    4932.0
Name: new_cases, dtype: float64
127304 127311    4645.0
Name: new_cases, dtype: float64
127305 127312    4116.0
Name: new_cases, dtype: float64
127306 127313    3313.0
Name: new_cases, dtype: float64
127307 127314    4011.0
Name: new_cases, dtype: float64
127308 127315    6709.0
Name: new_cases, dtype: float64
127309 127316    8166.0
Name: new_cases, dtype: float64
127310 127317    8319.0
Name: new_cases, dtype: float64
127311 127318    7882.0
Name: new_cases, dtype: float64
127312 127319    7999.0
Name: new_cases, dtype: float64
127313 127320    5163.0
Name: new_cases, dtype: float64
127314 127321    7552.0
Name: new_cases, dtype: float64
127315 127322    10008.0
Name: new_cases, dtype: float64
127316 127323    9126.0
Name: new_cases, dtype: float64
127317 127324    8725.0
Name: new_cases, dtype: float64
127318 127325    10939.0
Name: new_cases, dtype: float64
127319 127326    9445.0
Name: new_cases, dtype: float64
127320 127327    8789.0
Name: new_cases, dtype: float64
127321 127328    9501.0
Name: new_cases, dtype: float64
127322 127329    14046.0
Name: new_cases, dtype: float64
127323 127330    14305.0
Name: new_cases, dtype: float64
127324 127331    14796.0
Name: new_cases, dtype: float64
127325 127332    11552.0
Name: new_cases, dtype: float64
127326 127333    9502.0
Name: new_cases, dtype: float64
127327 127334    7458.0
Name: new_cases, dtype: float64
127328 127335    9580.0
Name: new_cases, dtype: float64
127329 127336    17710.0
Name: new_cases, dtype: float64
127330 127337    18000.0
Name: new_cases, dtype: float64
127331 127338    16726.0
Name: new_cases, dtype: float64
127332 127339    15002.0
Name: new_cases, dtype: float64
127333 127340    11859.0
Name: new_cases, dtype: float64
127334 127341    12601.0
Name: new_cases, dtype: float64
127335 127342    14410.0
Name: new_cases, dtype: float64
127336 127343    21832.0
Name: new_cases, dtype: float64
127337 127344    20999.0
Name: new_cases, dtype: float64
127338 127345    21980.0
Name: new_cases, dtype: float64
127339 127346    21606.0
Name: new_cases, dtype: float64
127340 127347    17421.0
Name: new_cases, dtype: float64
127341 127348    15046.0
Name: new_cases, dtype: float64
127342 127349    13105.0
Name: new_cases, dtype: float64
127343 127350    18555.0
Name: new_cases, dtype: float64
127344 127351    18503.0
Name: new_cases, dtype: float64
127345 127352    14880.0
Name: new_cases, dtype: float64
127346 127353    13973.0
Name: new_cases, dtype: float64
127347 127354    12267.0
Name: new_cases, dtype: float64
127348 127355    9010.0
Name: new_cases, dtype: float64
127349 127356    9780.0
Name: new_cases, dtype: float64
127350 127357    12710.0
Name: new_cases, dtype: float64
127351 127358    11381.0
Name: new_cases, dtype: float64
127352 127359    11761.0
Name: new_cases, dtype: float64
127353 127360    12271.0
Name: new_cases, dtype: float64
127354 127361    8147.0
Name: new_cases, dtype: float64
127355 127362    4551.0
Name: new_cases, dtype: float64
127356 127363    6041.0
Name: new_cases, dtype: float64
127357 127364    7070.0
Name: new_cases, dtype: float64
127358 127365    7150.0
Name: new_cases, dtype: float64
127359 127366    6141.0
Name: new_cases, dtype: float64
127360 127367    5297.0
Name: new_cases, dtype: float64
127361 127368    4525.0
Name: new_cases, dtype: float64
127362 127369    2548.0
Name: new_cases, dtype: float64
127363 127370    2649.0
Name: new_cases, dtype: float64
127364 127371    4058.0
Name: new_cases, dtype: float64
127365 127372    3751.0
Name: new_cases, dtype: float64
127366 127373    3749.0
Name: new_cases, dtype: float64
127367 127374    3184.0
Name: new_cases, dtype: float64
127368 127375    2435.0
Name: new_cases, dtype: float64
127369 127376    1376.0
Name: new_cases, dtype: float64
127370 127377    1742.0
Name: new_cases, dtype: float64
127371 127378    3159.0
Name: new_cases, dtype: float64
127372 127379    2488.0
Name: new_cases, dtype: float64
127373 127380    2781.0
Name: new_cases, dtype: float64
127374 127381    2382.0
Name: new_cases, dtype: float64
127375 127382    1744.0
Name: new_cases, dtype: float64
127376 127383    1102.0
Name: new_cases, dtype: float64
127377 127384    1210.0
Name: new_cases, dtype: float64
127378 127385    2320.0
Name: new_cases, dtype: float64
127379 127386    2327.0
Name: new_cases, dtype: float64
127380 127387    1911.0
Name: new_cases, dtype: float64
127381 127388    1690.0
Name: new_cases, dtype: float64
127382 127389    1429.0
Name: new_cases, dtype: float64
127383 127390    792.0
Name: new_cases, dtype: float64
127384 127391    998.0
Name: new_cases, dtype: float64
127385 127392    1862.0
Name: new_cases, dtype: float64
127386 127393    1676.0
Name: new_cases, dtype: float64
127387 127394    1654.0
Name: new_cases, dtype: float64
127388 127395    1447.0
Name: new_cases, dtype: float64
127389 127396    1168.0
Name: new_cases, dtype: float64
127390 127397    566.0
Name: new_cases, dtype: float64
127391 127398    856.0
Name: new_cases, dtype: float64
127392 127399    1447.0
Name: new_cases, dtype: float64
127393 127400    1404.0
Name: new_cases, dtype: float64
127394 127401    1313.0
Name: new_cases, dtype: float64
127395 127402    1227.0
Name: new_cases, dtype: float64
127396 127403    862.0
Name: new_cases, dtype: float64
127397 127404    638.0
Name: new_cases, dtype: float64
127398 127405    991.0
Name: new_cases, dtype: float64
127399 127406    1477.0
Name: new_cases, dtype: float64
127400 127407    1474.0
Name: new_cases, dtype: float64
127401 127408    1225.0
Name: new_cases, dtype: float64
127402 127409    1541.0
Name: new_cases, dtype: float64
127403 127410    1006.0
Name: new_cases, dtype: float64
127404 127411    613.0
Name: new_cases, dtype: float64
127405 127412    933.0
Name: new_cases, dtype: float64
127406 127413    1531.0
Name: new_cases, dtype: float64
127407 127414    1464.0
Name: new_cases, dtype: float64
127408 127415    1462.0
Name: new_cases, dtype: float64
127409 127416    1378.0
Name: new_cases, dtype: float64
127410 127417    1051.0
Name: new_cases, dtype: float64
127411 127418    599.0
Name: new_cases, dtype: float64
127412 127419    510.0
Name: new_cases, dtype: float64
127413 127420    1048.0
Name: new_cases, dtype: float64

127414 127421    1554.0
Name: new_cases, dtype: float64
127415 127422    1516.0
Name: new_cases, dtype: float64
127416 127423    1387.0
Name: new_cases, dtype: float64
127417 127424    965.0
Name: new_cases, dtype: float64
127418 127425    548.0
Name: new_cases, dtype: float64
127419 127426    756.0
Name: new_cases, dtype: float64
127420 127427    1422.0
Name: new_cases, dtype: float64
127421 127428    1294.0
Name: new_cases, dtype: float64
127422 127429    1273.0
Name: new_cases, dtype: float64
127423 127430    777.0
Name: new_cases, dtype: float64
127424 127431    463.0
Name: new_cases, dtype: float64
127425 127432    452.0
Name: new_cases, dtype: float64
127426 127433    437.0
Name: new_cases, dtype: float64
127427 127434    756.0
Name: new_cases, dtype: float64
127428 127435    1366.0
Name: new_cases, dtype: float64
127429 127436    1267.0
Name: new_cases, dtype: float64
127430 127437    1285.0
Name: new_cases, dtype: float64
127431 127438    931.0
Name: new_cases, dtype: float64
127432 127439    655.0
Name: new_cases, dtype: float64
127433 127440    847.0
Name: new_cases, dtype: float64
127434 127441    1599.0
Name: new_cases, dtype: float64
127435 127442    1372.0
Name: new_cases, dtype: float64
127436 127443    1424.0
Name: new_cases, dtype: float64
127437 127444    1325.0
Name: new_cases, dtype: float64
127438 127445    1089.0
Name: new_cases, dtype: float64
127439 127446    744.0
Name: new_cases, dtype: float64
127440 127447    853.0
Name: new_cases, dtype: float64
127441 127448    1569.0
Name: new_cases, dtype: float64
127442 127449    1413.0
Name: new_cases, dtype: float64
127443 127450    1637.0
Name: new_cases, dtype: float64
127444 127451    1385.0
Name: new_cases, dtype: float64
127445 127452    1101.0
Name: new_cases, dtype: float64
127446 127453    849.0
Name: new_cases, dtype: float64
127447 127454    880.0
Name: new_cases, dtype: float64
127448 127455    1250.0
Name: new_cases, dtype: float64
127449 127456    1086.0
Name: new_cases, dtype: float64
127450 127457    1674.0
Name: new_cases, dtype: float64
127451 127458    1632.0
Name: new_cases, dtype: float64
127452 127459    1222.0
Name: new_cases, dtype: float64
127453 127460    897.0
Name: new_cases, dtype: float64
127454 127461    1187.0
Name: new_cases, dtype: float64
127455 127462    2073.0
Name: new_cases, dtype: float64
127456 127463    2149.0
Name: new_cases, dtype: float64
127457 127464    2256.0
Name: new_cases, dtype: float64
127458 127465    0.0
Name: new_cases, dtype: float64
127459 127466    3969.0
Name: new_cases, dtype: float64
127460 127467    1129.0
Name: new_cases, dtype: float64
127461 127468    1548.0
Name: new_cases, dtype: float64
127462 127469    2759.0
Name: new_cases, dtype: float64
127463 127470    3221.0
Name: new_cases, dtype: float64
127464 127471    3141.0
Name: new_cases, dtype: float64
127465 127472    2750.0
Name: new_cases, dtype: float64
127466 127473    2585.0
Name: new_cases, dtype: float64
127467 127474    1757.0
Name: new_cases, dtype: float64
127468 127475    2355.0
Name: new_cases, dtype: float64
127469 127476    3522.0
Name: new_cases, dtype: float64
127470 127477    3641.0
Name: new_cases, dtype: float64
127471 127478    3332.0
Name: new_cases, dtype: float64
127472 127479    4236.0
Name: new_cases, dtype: float64
127473 127480    2894.0
Name: new_cases, dtype: float64
127474 127481    2383.0
Name: new_cases, dtype: float64
127475 127482    0.0
Name: new_cases, dtype: float64
127476 127483    7707.0
Name: new_cases, dtype: float64
127477 127484    4422.0
Name: new_cases, dtype: float64
127478 127485    4574.0
Name: new_cases, dtype: float64
127479 127486    4519.0
Name: new_cases, dtype: float64
127480 127487    0.0
Name: new_cases, dtype: float64
127481 127488    6547.0
Name: new_cases, dtype: float64
127482 127489    3614.0
Name: new_cases, dtype: float64
127483 127490    5782.0
Name: new_cases, dtype: float64
127484 127491    5360.0
Name: new_cases, dtype: float64
127485 127492    5668.0
Name: new_cases, dtype: float64
127486 127493    5450.0
Name: new_cases, dtype: float64
127487 127494    5073.0
Name: new_cases, dtype: float64
127488 127495    3285.0
Name: new_cases, dtype: float64
127489 127496    4209.0
Name: new_cases, dtype: float64
127490 127497    8881.0
Name: new_cases, dtype: float64
127491 127498    9147.0
Name: new_cases, dtype: float64
127492 127499    8020.0
Name: new_cases, dtype: float64
127493 127500    9319.0
Name: new_cases, dtype: float64
127494 127501    7657.0
Name: new_cases, dtype: float64
127495 127502    5548.0
Name: new_cases, dtype: float64
127496 127503    8436.0
Name: new_cases, dtype: float64
127497 127504    13246.0
Name: new_cases, dtype: float64
127498 127505    11767.0
Name: new_cases, dtype: float64
127499 127506    10510.0
Name: new_cases, dtype: float64
127500 127507    13575.0
Name: new_cases, dtype: float64
127501 127508    13155.0
Name: new_cases, dtype: float64
127502 127509    9160.0
Name: new_cases, dtype: float64
127503 127510    11093.0
Name: new_cases, dtype: float64
127504 127511    17493.0
Name: new_cases, dtype: float64
127505 127512    16078.0
Name: new_cases, dtype: float64
127506 127513    18762.0
Name: new_cases, dtype: float64
127507 127514    17956.0
Name: new_cases, dtype: float64
127508 127515    15036.0
Name: new_cases, dtype: float64
127509 127516    12222.0
Name: new_cases, dtype: float64
127510 127517    13347.0
Name: new_cases, dtype: float64
127511 127518    19506.0
Name: new_cases, dtype: float64
127512 127519    21584.0
Name: new_cases, dtype: float64
127513 127520    24270.0
Name: new_cases, dtype: float64
127514 127521    26485.0
Name: new_cases, dtype: float64
127515 127522    16585.0
Name: new_cases, dtype: float64
127516 127523    12513.0
Name: new_cases, dtype: float64
127517 127524    15500.0
Name: new_cases, dtype: float64
127518 127525    21427.0
Name: new_cases, dtype: float64
127519 127526    22910.0
Name: new_cases, dtype: float64
127520 127527    22441.0
Name: new_cases, dtype: float64
127521 127528    21610.0
Name: new_cases, dtype: float64
127522 127529    16302.0
Name: new_cases, dtype: float64
127523 127530    11182.0
Name: new_cases, dtype: float64
127524 127531    12535.0
Name: new_cases, dtype: float64
127525 127532    17489.0
Name: new_cases, dtype: float64
127526 127533    16435.0
Name: new_cases, dtype: float64
127527 127534    15939.0
Name: new_cases, dtype: float64
127528 127535    14701.0
Name: new_cases, dtype: float64
127529 127536    11215.0
Name: new_cases, dtype: float64
127530 127537    7209.0
Name: new_cases, dtype: float64
127531 127538    8928.0
Name: new_cases, dtype: float64
127532 127539    16240.0
Name: new_cases, dtype: float64
127533 127540    14858.0
Name: new_cases, dtype: float64
127534 127541    13719.0
Name: new_cases, dtype: float64
127535 127542    12056.0
Name: new_cases, dtype: float64
127536 127543    9718.0
Name: new_cases, dtype: float64
127537 127544    5667.0
Name: new_cases, dtype: float64
127538 127545    7733.0
Name: new_cases, dtype: float64
127539 127546    17302.0
Name: new_cases, dtype: float64
127540 127547    13626.0
Name: new_cases, dtype: float64
127541 127548    12885.0
Name: new_cases, dtype: float64
127542 127549    12418.0
Name: new_cases, dtype: float64
127543 127550    8730.0
Name: new_cases, dtype: float64
127544 127551    5574.0
Name: new_cases, dtype: float64
127545 127552    8988.0
Name: new_cases, dtype: float64
127546 127553    13263.0
Name: new_cases, dtype: float64
127547 127554    13646.0
Name: new_cases, dtype: float64
127548 127555    13523.0
Name: new_cases, dtype: float64
127549 127556    12310.0
Name: new_cases, dtype: float64
127550 127557    9978.0
Name: new_cases, dtype: float64
127551 127558    6756.0
Name: new_cases, dtype: float64
127552 127559    6540.0
Name: new_cases, dtype: float64
127553 127560    7478.0
Name: new_cases, dtype: float64
127554 127561    14271.0
Name: new_cases, dtype: float64
127555 127562    13916.0
Name: new_cases, dtype: float64
127556 127563    13020.0
Name: new_cases, dtype: float64
127557 127564    10139.0
Name: new_cases, dtype: float64
127558 127565    7983.0
Name: new_cases, dtype: float64
127559 127566    10685.0
Name: new_cases, dtype: float64
127560 127567    14727.0
Name: new_cases, dtype: float64
127561 127568    13671.0
Name: new_cases, dtype: float64
127562 127569    14312.0
Name: new_cases, dtype: float64
127563 127570    13261.0
Name: new_cases, dtype: float64
127564 127571    10748.0
Name: new_cases, dtype: float64
127565 127572    7632.0
Name: new_cases, dtype: float64
127566 127573    10346.0
Name: new_cases, dtype: float64
127567 127574    13251.0
Name: new_cases, dtype: float64
127568 127575    12771.0
Name: new_cases, dtype: float64
127569 127576    12045.0
Name: new_cases, dtype: float64
127570 127577    10173.0
Name: new_cases, dtype: float64
127571 127578    7740.0
Name: new_cases, dtype: float64
127572 127579    5644.0
Name: new_cases, dtype: float64
127573 127580    7084.0
Name: new_cases, dtype: float64
127574 127581    9544.0
Name: new_cases, dtype: float64
127575 127582    9202.0
Name: new_cases, dtype: float64
127576 127583    9199.0
Name: new_cases, dtype: float64
127577 127584    8410.0
Name: new_cases, dtype: float64

127578 127585    5931.0
Name: new_cases, dtype: float64
127579 127586    4118.0
Name: new_cases, dtype: float64
127580 127587    5771.0
Name: new_cases, dtype: float64
127581 127588    6939.0
Name: new_cases, dtype: float64
127582 127589    6269.0
Name: new_cases, dtype: float64
127583 127590    5883.0
Name: new_cases, dtype: float64
127584 127591    5309.0
Name: new_cases, dtype: float64
127585 127592    3961.0
Name: new_cases, dtype: float64
127586 127593    2640.0
Name: new_cases, dtype: float64
127587 127594    3699.0
Name: new_cases, dtype: float64
127588 127595    4667.0
Name: new_cases, dtype: float64
127589 127596    4214.0
Name: new_cases, dtype: float64
127590 127597    3648.0
Name: new_cases, dtype: float64
127591 127598    3286.0
Name: new_cases, dtype: float64
127592 127599    2281.0
Name: new_cases, dtype: float64
127593 127600    1504.0
Name: new_cases, dtype: float64
127594 127601    2197.0
Name: new_cases, dtype: float64
127595 127602    2967.0
Name: new_cases, dtype: float64
127596 127603    2783.0
Name: new_cases, dtype: float64
127597 127604    2261.0
Name: new_cases, dtype: float64
127598 127605    1634.0
Name: new_cases, dtype: float64
127599 127606    967.0
Name: new_cases, dtype: float64
127600 127607    578.0
Name: new_cases, dtype: float64
127601 127608    1367.0
Name: new_cases, dtype: float64
127602 127609    0.0
Name: new_cases, dtype: float64
127603 127610    3784.0
Name: new_cases, dtype: float64
127604 127611    1635.0
Name: new_cases, dtype: float64
127605 127612    1306.0
Name: new_cases, dtype: float64
127606 127613    809.0
Name: new_cases, dtype: float64
127607 127614    429.0
Name: new_cases, dtype: float64
127608 127615    768.0
Name: new_cases, dtype: float64
127609 127616    1149.0
Name: new_cases, dtype: float64
127610 127617    989.0
Name: new_cases, dtype: float64
127611 127618    924.0
Name: new_cases, dtype: float64
127612 127619    816.0
Name: new_cases, dtype: float64
127613 127620    648.0
Name: new_cases, dtype: float64
127614 127621    201.0
Name: new_cases, dtype: float64
127615 127622    592.0
Name: new_cases, dtype: float64
127616 127623    942.0
Name: new_cases, dtype: float64
127617 127624    947.0
Name: new_cases, dtype: float64
127618 127625    733.0
Name: new_cases, dtype: float64
127619 127626    619.0
Name: new_cases, dtype: float64
127620 127627    414.0
Name: new_cases, dtype: float64
127621 127628    210.0
Name: new_cases, dtype: float64
127622 127629    452.0
Name: new_cases, dtype: float64
127623 127630    591.0
Name: new_cases, dtype: float64
127624 127631    520.0
Name: new_cases, dtype: float64
127625 127632    517.0
Name: new_cases, dtype: float64
127626 127633    449.0
Name: new_cases, dtype: float64
127627 127634    300.0
Name: new_cases, dtype: float64
127628 127635    146.0
Name: new_cases, dtype: float64
127629 127636    331.0
Name: new_cases, dtype: float64
127630 127637    472.0
Name: new_cases, dtype: float64
127631 127638    533.0
Name: new_cases, dtype: float64
127632 127639    475.0
Name: new_cases, dtype: float64
127633 127640    297.0
Name: new_cases, dtype: float64
127634 127641    230.0
Name: new_cases, dtype: float64
127635 127642    106.0
Name: new_cases, dtype: float64
127636 127643    169.0
Name: new_cases, dtype: float64
127637 127644    344.0
Name: new_cases, dtype: float64
127638 127645    319.0
Name: new_cases, dtype: float64
127639 127646    339.0
Name: new_cases, dtype: float64
127640 127647    358.0
Name: new_cases, dtype: float64
127641 127648    205.0
Name: new_cases, dtype: float64
127642 127649    116.0
Name: new_cases, dtype: float64
127643 127650    245.0
Name: new_cases, dtype: float64
127644 127651    305.0
Name: new_cases, dtype: float64
127645 127652    356.0
Name: new_cases, dtype: float64
127646 127653    393.0
Name: new_cases, dtype: float64
127647 127654    306.0
Name: new_cases, dtype: float64
127648 127655    262.0
Name: new_cases, dtype: float64
127649 127656    136.0
Name: new_cases, dtype: float64
127650 127657    273.0
Name: new_cases, dtype: float64
127651 127658    566.0
Name: new_cases, dtype: float64
127652 127659    585.0
Name: new_cases, dtype: float64
127653 127660    789.0
Name: new_cases, dtype: float64
127654 127661    887.0
Name: new_cases, dtype: float64
127655 127662    687.0
Name: new_cases, dtype: float64
127656 127663    312.0
Name: new_cases, dtype: float64
127657 127665    1275.0
Name: new_cases, dtype: float64
127658 127666    2465.0
Name: new_cases, dtype: float64
127659 127667    2828.0
Name: new_cases, dtype: float64
127660 127668    3220.0
Name: new_cases, dtype: float64
127661 127669    2858.0
Name: new_cases, dtype: float64
127662 127670    2273.0
Name: new_cases, dtype: float64
127663 127671    4373.0
Name: new_cases, dtype: float64
127665 127672    8561.0
Name: new_cases, dtype: float64
127666 127673    11535.0
Name: new_cases, dtype: float64
127667 127674    16055.0
Name: new_cases, dtype: float64
127668 127675    16366.0
Name: new_cases, dtype: float64
127669 127676    11125.0
Name: new_cases, dtype: float64
127670 127677    6381.0
Name: new_cases, dtype: float64
127671 127678    13147.0
Name: new_cases, dtype: float64
127672 127679    19842.0
Name: new_cases, dtype: float64
127673 127680    22388.0
Name: new_cases, dtype: float64
127674 127681    19017.0
Name: new_cases, dtype: float64
127675 127682    17153.0
Name: new_cases, dtype: float64
127676 127683    37875.0
Name: new_cases, dtype: float64
127677 127684    13288.0
Name: new_cases, dtype: float64
127678 127685    23857.0
Name: new_cases, dtype: float64
127679 127686    26389.0
Name: new_cases, dtype: float64
127680 127687    24785.0
Name: new_cases, dtype: float64
127681 127688    20713.0
Name: new_cases, dtype: float64
127682 127689    16080.0
Name: new_cases, dtype: float64
127683 127690    15465.0
Name: new_cases, dtype: float64
127684 127691    8511.0
Name: new_cases, dtype: float64
127685 127692    15423.0
Name: new_cases, dtype: float64
127686 127693    21098.0
Name: new_cases, dtype: float64
127687 127694    21156.0
Name: new_cases, dtype: float64
127688 127695    18847.0
Name: new_cases, dtype: float64
127689 127696    14828.0
Name: new_cases, dtype: float64
127690 127697    5603.0
Name: new_cases, dtype: float64
127691 127698    3778.0
Name: new_cases, dtype: float64
127692 127699    7216.0
Name: new_cases, dtype: float64
127693 127700    9020.0
Name: new_cases, dtype: float64
127694 127701    12978.0
Name: new_cases, dtype: float64
127695 127702    11754.0
Name: new_cases, dtype: float64
127696 127703    9793.0
Name: new_cases, dtype: float64
127697 127704    4357.0
Name: new_cases, dtype: float64
127698 127705    3076.0
Name: new_cases, dtype: float64
127699 127706    8078.0
Name: new_cases, dtype: float64
127700 127707    11106.0
Name: new_cases, dtype: float64
127701 127708    9858.0
Name: new_cases, dtype: float64
127702 127709    9259.0
Name: new_cases, dtype: float64
127703 127710    7759.0
Name: new_cases, dtype: float64
127704 Series([], Name: new_cases, dtype: float64)
127705 Series([], Name: new_cases, dtype: float64)
127706 Series([], Name: new_cases, dtype: float64)
127707 Series([], Name: new_cases, dtype: float64)
127708 Series([], Name: new_cases, dtype: float64)
127709 Series([], Name: new_cases, dtype: float64)
127710 Series([], Name: new_cases, dtype: float64)
129761 129768    0.0
Name: new_cases, dtype: float64
129762 129769    1.0
Name: new_cases, dtype: float64
129763 129770    0.0
Name: new_cases, dtype: float64
129764 129771    0.0
Name: new_cases, dtype: float64
129765 129772    0.0
Name: new_cases, dtype: float64
129766 129773    0.0
Name: new_cases, dtype: float64
129767 129774    0.0
Name: new_cases, dtype: float64
129768 129775    0.0
Name: new_cases, dtype: float64
129769 129776    0.0
Name: new_cases, dtype: float64
129770 129777    0.0
Name: new_cases, dtype: float64
129771 129778    0.0
Name: new_cases, dtype: float64
129772 129779    0.0
Name: new_cases, dtype: float64
129773 129780    0.0
Name: new_cases, dtype: float64
129774 129781    0.0
Name: new_cases, dtype: float64
129775 129782    0.0
Name: new_cases, dtype: float64
129776 129783    0.0
Name: new_cases, dtype: float64
129777 129784    0.0
Name: new_cases, dtype: float64
129778 129785    4.0
Name: new_cases, dtype: float64
129779 129786    7.0
Name: new_cases, dtype: float64
129780 129787    2.0
Name: new_cases, dtype: float64
129781 129788    17.0
Name: new_cases, dtype: float64
129782 129789    13.0
Name: new_cases, dtype: float64
129783 129790    39.0
Name: new_cases, dtype: float64
129784 129791    36.0
Name: new_cases, dtype: float64
129785 129792    45.0
Name: new_cases, dtype: float64
129786 129793    57.0
Name: new_cases, dtype: float64
129787 129794    37.0
Name: new_cases, dtype: float64
129788 129795    141.0
Name: new_cases, dtype: float64

129789 129796    100.0
Name: new_cases, dtype: float64
129790 129797    173.0
Name: new_cases, dtype: float64
129791 129798    400.0
Name: new_cases, dtype: float64
129792 129799    622.0
Name: new_cases, dtype: float64
129793 129800    582.0
Name: new_cases, dtype: float64
129794 129801    0.0
Name: new_cases, dtype: float64
129795 129802    2955.0
Name: new_cases, dtype: float64
129796 129803    1159.0
Name: new_cases, dtype: float64
129797 129804    1407.0
Name: new_cases, dtype: float64
129798 129805    2144.0
Name: new_cases, dtype: float64
129799 129806    1806.0
Name: new_cases, dtype: float64
129800 129807    2162.0
Name: new_cases, dtype: float64
129801 129808    4053.0
Name: new_cases, dtype: float64
129802 129809    2447.0
Name: new_cases, dtype: float64
129803 129810    4964.0
Name: new_cases, dtype: float64
129804 129811    3394.0
Name: new_cases, dtype: float64
129805 129812    6368.0
Name: new_cases, dtype: float64
129806 129813    4749.0
Name: new_cases, dtype: float64
129807 129814    9630.0
Name: new_cases, dtype: float64
129808 129815    8271.0
Name: new_cases, dtype: float64
129809 129816    7933.0
Name: new_cases, dtype: float64
129810 129817    7516.0
Name: new_cases, dtype: float64
129811 129818    6875.0
Name: new_cases, dtype: float64
129812 129819    7846.0
Name: new_cases, dtype: float64
129813 129820    7967.0
Name: new_cases, dtype: float64
129814 129821    8195.0
Name: new_cases, dtype: float64
129815 129822    7947.0
Name: new_cases, dtype: float64
129816 129823    7134.0
Name: new_cases, dtype: float64
129817 129824    6969.0
Name: new_cases, dtype: float64
129818 129825    5478.0
Name: new_cases, dtype: float64
129819 129826    5029.0
Name: new_cases, dtype: float64
129820 129827    5267.0
Name: new_cases, dtype: float64
129821 129828    6278.0
Name: new_cases, dtype: float64
129822 129829    5002.0
Name: new_cases, dtype: float64
129823 129830    5051.0
Name: new_cases, dtype: float64
129824 129831    4754.0
Name: new_cases, dtype: float64
129825 129832    3804.0
Name: new_cases, dtype: float64
129826 129833    3268.0
Name: new_cases, dtype: float64
129827 129834    2442.0
Name: new_cases, dtype: float64
129828 129835    5103.0
Name: new_cases, dtype: float64
129829 129836    7304.0
Name: new_cases, dtype: float64
129830 129837    5891.0
Name: new_cases, dtype: float64
129831 129838    887.0
Name: new_cases, dtype: float64
129832 129839    6948.0
Name: new_cases, dtype: float64
129833 129840    1536.0
Name: new_cases, dtype: float64
129834 129841    3968.0
Name: new_cases, dtype: float64
129835 129842    4211.0
Name: new_cases, dtype: float64
129836 129843    4635.0
Name: new_cases, dtype: float64
129837 129844   -10034.0
Name: new_cases, dtype: float64
129838 129845    2915.0
Name: new_cases, dtype: float64
129839 129846    1729.0
Name: new_cases, dtype: float64
129840 129847    1831.0
Name: new_cases, dtype: float64
129841 129848    1308.0
Name: new_cases, dtype: float64
129842 129849    2144.0
Name: new_cases, dtype: float64
129843 129850    518.0
Name: new_cases, dtype: float64
129844 129851    1781.0
Name: new_cases, dtype: float64
129845 129852    1366.0
Name: new_cases, dtype: float64
129846 129853    884.0
Name: new_cases, dtype: float64
129847 129854    545.0
Name: new_cases, dtype: float64
129848 129855    1318.0
Name: new_cases, dtype: float64
129849 129856    996.0
Name: new_cases, dtype: float64
129850 129857    1122.0
Name: new_cases, dtype: float64
129851 129858    1410.0
Name: new_cases, dtype: float64
129852 129859    721.0
Name: new_cases, dtype: float64
129853 129860    772.0
Name: new_cases, dtype: float64
129854 129861    3086.0
Name: new_cases, dtype: float64
129855 129862    594.0
Name: new_cases, dtype: float64
129856 129863    661.0
Name: new_cases, dtype: float64
129857 129864    849.0
Name: new_cases, dtype: float64
129858 129865    643.0
Name: new_cases, dtype: float64
129859 129866    515.0
Name: new_cases, dtype: float64
129860 129867    0.0
Name: new_cases, dtype: float64
129861 129868    908.0
Name: new_cases, dtype: float64
129862 129869    431.0
Name: new_cases, dtype: float64
129863 129870    518.0
Name: new_cases, dtype: float64
129864 129871    482.0
Name: new_cases, dtype: float64
129865 129872    1787.0
Name: new_cases, dtype: float64
129866 129873    466.0
Name: new_cases, dtype: float64
129867 129874    482.0
Name: new_cases, dtype: float64
129868 129875   -372.0
Name: new_cases, dtype: float64
129869 129876    859.0
Name: new_cases, dtype: float64
129870 129877    0.0
Name: new_cases, dtype: float64
129871 129878    1647.0
Name: new_cases, dtype: float64
129872 129879    658.0
Name: new_cases, dtype: float64
129873 129880    664.0
Name: new_cases, dtype: float64
129874 129881    251.0
Name: new_cases, dtype: float64
129875 129882    159.0
Name: new_cases, dtype: float64
129876 129883    294.0
Name: new_cases, dtype: float64
129877 129884    394.0
Name: new_cases, dtype: float64
129878 129885    334.0
Name: new_cases, dtype: float64
129879 129886    318.0
Name: new_cases, dtype: float64
129880 129887    332.0
Name: new_cases, dtype: float64
129881 129888    240.0
Name: new_cases, dtype: float64
129882 129889    167.0
Name: new_cases, dtype: float64
129883 129890    249.0
Name: new_cases, dtype: float64
129884 129891    314.0
Name: new_cases, dtype: float64
129885 129892    427.0
Name: new_cases, dtype: float64
129886 129893    502.0
Name: new_cases, dtype: float64
129887 129894    396.0
Name: new_cases, dtype: float64
129888 129895    323.0
Name: new_cases, dtype: float64
129889 129896    181.0
Name: new_cases, dtype: float64
129890 129897    219.0
Name: new_cases, dtype: float64
129891 129898    355.0
Name: new_cases, dtype: float64
129892 129899    585.0
Name: new_cases, dtype: float64
129893 129900    307.0
Name: new_cases, dtype: float64
129894 129901    363.0
Name: new_cases, dtype: float64
129895 129902    334.0
Name: new_cases, dtype: float64
129896 129903    232.0
Name: new_cases, dtype: float64
129897 129904    248.0
Name: new_cases, dtype: float64
129898 129905    334.0
Name: new_cases, dtype: float64
129899 129906    400.0
Name: new_cases, dtype: float64
129900 129907    419.0
Name: new_cases, dtype: float64
129901 129908    564.0
Name: new_cases, dtype: float64
129902 129909    301.0
Name: new_cases, dtype: float64
129903 129910    200.0
Name: new_cases, dtype: float64
129904 129911    301.0
Name: new_cases, dtype: float64
129905 129912    388.0
Name: new_cases, dtype: float64
129906 129913    444.0
Name: new_cases, dtype: float64
129907 129914    442.0
Name: new_cases, dtype: float64
129908 129915    0.0
Name: new_cases, dtype: float64
129909 129916    0.0
Name: new_cases, dtype: float64
129910 129917    1244.0
Name: new_cases, dtype: float64
129911 129918    341.0
Name: new_cases, dtype: float64
129912 129919    383.0
Name: new_cases, dtype: float64
129913 129920    543.0
Name: new_cases, dtype: float64
129914 129921    852.0
Name: new_cases, dtype: float64
129915 129922    0.0
Name: new_cases, dtype: float64
129916 129923    0.0
Name: new_cases, dtype: float64
129917 129924    2045.0
Name: new_cases, dtype: float64
129918 129925    666.0
Name: new_cases, dtype: float64
129919 129926    875.0
Name: new_cases, dtype: float64
129920 129927    1361.0
Name: new_cases, dtype: float64
129921 129928    1400.0
Name: new_cases, dtype: float64
129922 129929    0.0
Name: new_cases, dtype: float64
129923 129930    0.0
Name: new_cases, dtype: float64
129924 129931    4581.0
Name: new_cases, dtype: float64
129925 129932    1358.0
Name: new_cases, dtype: float64
129926 129933    1357.0
Name: new_cases, dtype: float64
129927 129934    2615.0
Name: new_cases, dtype: float64
129928 129935    2255.0
Name: new_cases, dtype: float64
129929 129936    0.0
Name: new_cases, dtype: float64
129930 129937    0.0
Name: new_cases, dtype: float64
129931 129938    6361.0
Name: new_cases, dtype: float64
129932 129939    1828.0
Name: new_cases, dtype: float64
129933 129940    2031.0
Name: new_cases, dtype: float64
129934 129941    2789.0
Name: new_cases, dtype: float64
129935 129942    3092.0
Name: new_cases, dtype: float64
129936 129943    0.0
Name: new_cases, dtype: float64
129937 129944    0.0
Name: new_cases, dtype: float64
129938 129945    8532.0
Name: new_cases, dtype: float64
129939 129946    5760.0
Name: new_cases, dtype: float64
129940 129947    2953.0
Name: new_cases, dtype: float64
129941 129948    4088.0
Name: new_cases, dtype: float64
129942 129949    4507.0
Name: new_cases, dtype: float64
129943 129950    0.0
Name: new_cases, dtype: float64
129944 129951    0.0
Name: new_cases, dtype: float64

129945 129952    8618.0
Name: new_cases, dtype: float64
129946 129953    3632.0
Name: new_cases, dtype: float64
129947 129954    3172.0
Name: new_cases, dtype: float64
129948 129955    7550.0
Name: new_cases, dtype: float64
129949 129956    5479.0
Name: new_cases, dtype: float64
129950 129957    0.0
Name: new_cases, dtype: float64
129951 129958    0.0
Name: new_cases, dtype: float64
129952 129959    16269.0
Name: new_cases, dtype: float64
129953 129960    5114.0
Name: new_cases, dtype: float64
129954 129961    6671.0
Name: new_cases, dtype: float64
129955 129962    7039.0
Name: new_cases, dtype: float64
129956 129963    8148.0
Name: new_cases, dtype: float64
129957 129964    0.0
Name: new_cases, dtype: float64
129958 129965    0.0
Name: new_cases, dtype: float64
129959 129966    19382.0
Name: new_cases, dtype: float64
129960 129967    7117.0
Name: new_cases, dtype: float64
129961 129968    7296.0
Name: new_cases, dtype: float64
129962 129969    9658.0
Name: new_cases, dtype: float64
129963 129970    9779.0
Name: new_cases, dtype: float64
129964 129971    0.0
Name: new_cases, dtype: float64
129965 129972    0.0
Name: new_cases, dtype: float64
129966 129973    23572.0
Name: new_cases, dtype: float64
129967 129974    8115.0
Name: new_cases, dtype: float64
129968 129975    8581.0
Name: new_cases, dtype: float64
129969 129976    8959.0
Name: new_cases, dtype: float64
129970 129977    10476.0
Name: new_cases, dtype: float64
129971 129978    0.0
Name: new_cases, dtype: float64
129972 129979    0.0
Name: new_cases, dtype: float64
129973 129980    26560.0
Name: new_cases, dtype: float64
129974 129981    8964.0
Name: new_cases, dtype: float64
129975 129982    8866.0
Name: new_cases, dtype: float64
129976 129983    10764.0
Name: new_cases, dtype: float64
129977 129984    12183.0
Name: new_cases, dtype: float64
129978 129985    0.0
Name: new_cases, dtype: float64
129979 129986    0.0
Name: new_cases, dtype: float64
129980 129987    27404.0
Name: new_cases, dtype: float64
129981 129988    9437.0
Name: new_cases, dtype: float64
129982 129989    11193.0
Name: new_cases, dtype: float64
129983 129990    11291.0
Name: new_cases, dtype: float64
129984 129991    14389.0
Name: new_cases, dtype: float64
129985 129992    0.0
Name: new_cases, dtype: float64
129986 129993    0.0
Name: new_cases, dtype: float64
129987 129994    31428.0
Name: new_cases, dtype: float64
129988 129995    10799.0
Name: new_cases, dtype: float64
129989 129996    11289.0
Name: new_cases, dtype: float64
129990 129997    10653.0
Name: new_cases, dtype: float64
129991 129998    12272.0
Name: new_cases, dtype: float64
129992 129999    0.0
Name: new_cases, dtype: float64
129993 130000    0.0
Name: new_cases, dtype: float64
129994 130001    31785.0
Name: new_cases, dtype: float64
129995 130002    0.0
Name: new_cases, dtype: float64
129996 130003    20922.0
Name: new_cases, dtype: float64
129997 130004    9419.0
Name: new_cases, dtype: float64
129998 130005    11325.0
Name: new_cases, dtype: float64
129999 130006    0.0
Name: new_cases, dtype: float64
130000 130007    0.0
Name: new_cases, dtype: float64
130001 130008    23480.0
Name: new_cases, dtype: float64
130002 130009    11998.0
Name: new_cases, dtype: float64
130003 130010    10491.0
Name: new_cases, dtype: float64
130004 130011    12423.0
Name: new_cases, dtype: float64
130005 130012    12788.0
Name: new_cases, dtype: float64
130006 130013    0.0
Name: new_cases, dtype: float64
130007 130014    0.0
Name: new_cases, dtype: float64
130008 130015    27856.0
Name: new_cases, dtype: float64
130009 130016    7118.0
Name: new_cases, dtype: float64
130010 130017    11970.0
Name: new_cases, dtype: float64
130011 130018    13318.0
Name: new_cases, dtype: float64
130012 130019    15186.0
Name: new_cases, dtype: float64
130013 130020    0.0
Name: new_cases, dtype: float64
130014 130021    0.0
Name: new_cases, dtype: float64
130015 130022    37889.0
Name: new_cases, dtype: float64
130016 130023    13873.0
Name: new_cases, dtype: float64
130017 130024    16973.0
Name: new_cases, dtype: float64
130018 130025    20986.0
Name: new_cases, dtype: float64
130019 130026    19851.0
Name: new_cases, dtype: float64
130020 130027    0.0
Name: new_cases, dtype: float64
130021 130028    0.0
Name: new_cases, dtype: float64
130022 130029    52188.0
Name: new_cases, dtype: float64
130023 130030    18418.0
Name: new_cases, dtype: float64
130024 130031    19765.0
Name: new_cases, dtype: float64
130025 130032    23580.0
Name: new_cases, dtype: float64
130026 130033    25595.0
Name: new_cases, dtype: float64
130027 130034    0.0
Name: new_cases, dtype: float64
130028 130035    0.0
Name: new_cases, dtype: float64
130029 130036    55019.0
Name: new_cases, dtype: float64
130030 130037    18669.0
Name: new_cases, dtype: float64
130031 130038    25042.0
Name: new_cases, dtype: float64
130032 130039    21908.0
Name: new_cases, dtype: float64
130033 130040    22516.0
Name: new_cases, dtype: float64
130034 130041    0.0
Name: new_cases, dtype: float64
130035 130042    0.0
Name: new_cases, dtype: float64
130036 130043    52386.0
Name: new_cases, dtype: float64
130037 130044    0.0
Name: new_cases, dtype: float64
130038 130045    36491.0
Name: new_cases, dtype: float64
130039 130046    19511.0
Name: new_cases, dtype: float64
130040 130047    21371.0
Name: new_cases, dtype: float64
130041 130048    0.0
Name: new_cases, dtype: float64
130042 130049    0.0
Name: new_cases, dtype: float64
130043 130050    38273.0
Name: new_cases, dtype: float64
130044 130051    13159.0
Name: new_cases, dtype: float64
130045 130052    15318.0
Name: new_cases, dtype: float64
130046 130053    16233.0
Name: new_cases, dtype: float64
130047 130054    15156.0
Name: new_cases, dtype: float64
130048 130055    0.0
Name: new_cases, dtype: float64
130049 130056    0.0
Name: new_cases, dtype: float64
130050 130057    25886.0
Name: new_cases, dtype: float64
130051 130058    12228.0
Name: new_cases, dtype: float64
130052 130059    10222.0
Name: new_cases, dtype: float64
130053 130060    12289.0
Name: new_cases, dtype: float64
130054 130061    10853.0
Name: new_cases, dtype: float64
130055 130062    0.0
Name: new_cases, dtype: float64
130056 130063    0.0
Name: new_cases, dtype: float64
130057 130064    19979.0
Name: new_cases, dtype: float64
130058 130065    8257.0
Name: new_cases, dtype: float64
130059 130066    9331.0
Name: new_cases, dtype: float64
130060 130067    10127.0
Name: new_cases, dtype: float64
130061 130068    8745.0
Name: new_cases, dtype: float64
130062 130069    0.0
Name: new_cases, dtype: float64
130063 130070    0.0
Name: new_cases, dtype: float64
130064 130071    17681.0
Name: new_cases, dtype: float64
130065 130072    0.0
Name: new_cases, dtype: float64
130066 130073    9773.0
Name: new_cases, dtype: float64
130067 130074    7955.0
Name: new_cases, dtype: float64
130068 130075    10519.0
Name: new_cases, dtype: float64
130069 130076    0.0
Name: new_cases, dtype: float64
130070 130077    0.0
Name: new_cases, dtype: float64
130071 130078    21309.0
Name: new_cases, dtype: float64
130072 130079    10328.0
Name: new_cases, dtype: float64
130073 130080    11078.0
Name: new_cases, dtype: float64
130074 130081    12131.0
Name: new_cases, dtype: float64
130075 130082    11815.0
Name: new_cases, dtype: float64
130076 130083    0.0
Name: new_cases, dtype: float64
130077 130084    0.0
Name: new_cases, dtype: float64
130078 130085    22013.0
Name: new_cases, dtype: float64
130079 130086    10654.0
Name: new_cases, dtype: float64
130080 130087    12386.0
Name: new_cases, dtype: float64
130081 130088    12662.0
Name: new_cases, dtype: float64
130082 130089    0.0
Name: new_cases, dtype: float64
130083 130090    0.0
Name: new_cases, dtype: float64
130084 130091    0.0
Name: new_cases, dtype: float64
130085 130092    24462.0
Name: new_cases, dtype: float64
130086 130093    14089.0
Name: new_cases, dtype: float64
130087 130094    16716.0
Name: new_cases, dtype: float64
130088 130095    18047.0
Name: new_cases, dtype: float64
130089 130096    0.0
Name: new_cases, dtype: float64
130090 130097    0.0
Name: new_cases, dtype: float64
130091 130098    0.0
Name: new_cases, dtype: float64
130092 130099    30579.0
Name: new_cases, dtype: float64
130093 130100    23700.0
Name: new_cases, dtype: float64
130094 130101    0.0
Name: new_cases, dtype: float64
130095 130102    42360.0
Name: new_cases, dtype: float64
130096 130103    25456.0
Name: new_cases, dtype: float64
130097 130104    0.0
Name: new_cases, dtype: float64
130098 130105    0.0
Name: new_cases, dtype: float64
130099 130106    61422.0
Name: new_cases, dtype: float64
130100 130107    25438.0
Name: new_cases, dtype: float64
130101 130108    38869.0
Name: new_cases, dtype: float64
130102 130109    35878.0
Name: new_cases, dtype: float64
130103 130110    40197.0
Name: new_cases, dtype: float64
130104 130111    0.0
Name: new_cases, dtype: float64
130105 130112    0.0
Name: new_cases, dtype: float64
130106 130113    84287.0
Name: new_cases, dtype: float64
130107 130114    34291.0
Name: new_cases, dtype: float64
130108 130115    41576.0
Name: new_cases, dtype: float64
130109 130116    44357.0
Name: new_cases, dtype: float64
130110 130117    42885.0
Name: new_cases, dtype: float64
130111 130118    0.0
Name: new_cases, dtype: float64
130112 130119    0.0
Name: new_cases, dtype: float64
130113 130120    93822.0
Name: new_cases, dtype: float64

130114 130121    36435.0
Name: new_cases, dtype: float64
130115 130122    40285.0
Name: new_cases, dtype: float64
130116 130123    34899.0
Name: new_cases, dtype: float64
130117 130124    38118.0
Name: new_cases, dtype: float64
130118 130125    0.0
Name: new_cases, dtype: float64
130119 130126    0.0
Name: new_cases, dtype: float64
130120 130127    79686.0
Name: new_cases, dtype: float64
130121 130128    29064.0
Name: new_cases, dtype: float64
130122 130129    31596.0
Name: new_cases, dtype: float64
130123 130130    29960.0
Name: new_cases, dtype: float64
130124 130131    28565.0
Name: new_cases, dtype: float64
130125 130132    0.0
Name: new_cases, dtype: float64
130126 130133    0.0
Name: new_cases, dtype: float64
130127 130134    47095.0
Name: new_cases, dtype: float64
130128 130135    16402.0
Name: new_cases, dtype: float64
130129 130136    18114.0
Name: new_cases, dtype: float64
130130 130137    17853.0
Name: new_cases, dtype: float64
130131 130138    14581.0
Name: new_cases, dtype: float64
130132 130139    0.0
Name: new_cases, dtype: float64
130133 130140    0.0
Name: new_cases, dtype: float64
130134 130141    30251.0
Name: new_cases, dtype: float64
130135 130142    10057.0
Name: new_cases, dtype: float64
130136 130143    10829.0
Name: new_cases, dtype: float64
130137 130144    14515.0
Name: new_cases, dtype: float64
130138 130145    11435.0
Name: new_cases, dtype: float64
130139 130146    0.0
Name: new_cases, dtype: float64
130140 130147    0.0
Name: new_cases, dtype: float64
130141 130148    20849.0
Name: new_cases, dtype: float64
130142 130149    7461.0
Name: new_cases, dtype: float64
130143 130150    9212.0
Name: new_cases, dtype: float64
130144 130151    9568.0
Name: new_cases, dtype: float64
130145 130152    8341.0
Name: new_cases, dtype: float64
130146 130153    0.0
Name: new_cases, dtype: float64
130147 130154    0.0
Name: new_cases, dtype: float64
130148 130155    15978.0
Name: new_cases, dtype: float64
130149 130156   -74347.0
Name: new_cases, dtype: float64
130150 130157    6137.0
Name: new_cases, dtype: float64
130151 130158    6037.0
Name: new_cases, dtype: float64
130152 130159    6654.0
Name: new_cases, dtype: float64
130153 130160    0.0
Name: new_cases, dtype: float64
130154 130161    0.0
Name: new_cases, dtype: float64
130155 130162    11958.0
Name: new_cases, dtype: float64
130156 130163    4012.0
Name: new_cases, dtype: float64
130157 130164    7119.0
Name: new_cases, dtype: float64
130158 130165    6255.0
Name: new_cases, dtype: float64
130159 130166    5348.0
Name: new_cases, dtype: float64
130160 130167    0.0
Name: new_cases, dtype: float64
130161 130168    0.0
Name: new_cases, dtype: float64
130162 130169    11358.0
Name: new_cases, dtype: float64
130163 130170    4962.0
Name: new_cases, dtype: float64
130164 130171    6092.0
Name: new_cases, dtype: float64
130165 130172    6216.0
Name: new_cases, dtype: float64
130166 130173    0.0
Name: new_cases, dtype: float64
130167 130174    0.0
Name: new_cases, dtype: float64
130168 130175    0.0
Name: new_cases, dtype: float64
130169 130176    16471.0
Name: new_cases, dtype: float64
130170 130177    5516.0
Name: new_cases, dtype: float64
130171 130178    0.0
Name: new_cases, dtype: float64
130172 130179    13419.0
Name: new_cases, dtype: float64
130173 130180    7586.0
Name: new_cases, dtype: float64
130174 130181    0.0
Name: new_cases, dtype: float64
130175 130182    0.0
Name: new_cases, dtype: float64
130176 130183    15501.0
Name: new_cases, dtype: float64
130177 130184    4994.0
Name: new_cases, dtype: float64
130178 130185    8534.0
Name: new_cases, dtype: float64
130179 130186    7041.0
Name: new_cases, dtype: float64
130180 130187    0.0
Name: new_cases, dtype: float64
130181 130188    9571.0
Name: new_cases, dtype: float64
130182 130189    0.0
Name: new_cases, dtype: float64
130183 130190    10360.0
Name: new_cases, dtype: float64
130184 130191    6623.0
Name: new_cases, dtype: float64
130185 130192    8788.0
Name: new_cases, dtype: float64
130186 130193    9901.0
Name: new_cases, dtype: float64
130187 130194    10875.0
Name: new_cases, dtype: float64
130188 130195    0.0
Name: new_cases, dtype: float64
130189 130196    0.0
Name: new_cases, dtype: float64
130190 130197    22744.0
Name: new_cases, dtype: float64
130191 130198    6292.0
Name: new_cases, dtype: float64
130192 130199    10474.0
Name: new_cases, dtype: float64
130193 130200    9663.0
Name: new_cases, dtype: float64
130194 130201    10598.0
Name: new_cases, dtype: float64
130195 130202    0.0
Name: new_cases, dtype: float64
130196 130203    0.0
Name: new_cases, dtype: float64
130197 130204    21071.0
Name: new_cases, dtype: float64
130198 130205    0.0
Name: new_cases, dtype: float64
130199 130206    17718.0
Name: new_cases, dtype: float64
130200 130207    10814.0
Name: new_cases, dtype: float64
130201 130208    11731.0
Name: new_cases, dtype: float64
130202 130209    0.0
Name: new_cases, dtype: float64
130203 130210    0.0
Name: new_cases, dtype: float64
130204 130211    19852.0
Name: new_cases, dtype: float64
130205 130212    7665.0
Name: new_cases, dtype: float64
130206 130213    8665.0
Name: new_cases, dtype: float64
130207 130214    10143.0
Name: new_cases, dtype: float64
130208 130215    9135.0
Name: new_cases, dtype: float64
130209 130216    0.0
Name: new_cases, dtype: float64
130210 130217    0.0
Name: new_cases, dtype: float64
130211 130218    16353.0
Name: new_cases, dtype: float64
130212 130219    4515.0
Name: new_cases, dtype: float64
130213 130220    6317.0
Name: new_cases, dtype: float64
130214 130221    7960.0
Name: new_cases, dtype: float64
130215 130222    8186.0
Name: new_cases, dtype: float64
130216 130223    0.0
Name: new_cases, dtype: float64
130217 130224    0.0
Name: new_cases, dtype: float64
130218 130225    13984.0
Name: new_cases, dtype: float64
130219 130226    4941.0
Name: new_cases, dtype: float64
130220 130227    6418.0
Name: new_cases, dtype: float64
130221 130228    5701.0
Name: new_cases, dtype: float64
130222 130229    6347.0
Name: new_cases, dtype: float64
130223 130230    0.0
Name: new_cases, dtype: float64
130224 130231    0.0
Name: new_cases, dtype: float64
130225 130232    11061.0
Name: new_cases, dtype: float64
130226 130233    3988.0
Name: new_cases, dtype: float64
130227 130234    6080.0
Name: new_cases, dtype: float64
130228 130235    5733.0
Name: new_cases, dtype: float64
130229 130236    4792.0
Name: new_cases, dtype: float64
130230 130237    0.0
Name: new_cases, dtype: float64
130231 130238    0.0
Name: new_cases, dtype: float64
130232 130239    11067.0
Name: new_cases, dtype: float64
130233 130240    5359.0
Name: new_cases, dtype: float64
130234 130241    5007.0
Name: new_cases, dtype: float64
130235 130242    5290.0
Name: new_cases, dtype: float64
130236 130243    5482.0
Name: new_cases, dtype: float64
130237 130244    0.0
Name: new_cases, dtype: float64
130238 130245    0.0
Name: new_cases, dtype: float64
130239 130246    9732.0
Name: new_cases, dtype: float64
130240 130247    4388.0
Name: new_cases, dtype: float64
130241 130248    4984.0
Name: new_cases, dtype: float64
130242 130249    5250.0
Name: new_cases, dtype: float64
130243 130250    4969.0
Name: new_cases, dtype: float64
130244 130251    0.0
Name: new_cases, dtype: float64
130245 130252    0.0
Name: new_cases, dtype: float64
130246 130253    9542.0
Name: new_cases, dtype: float64
130247 130254    3504.0
Name: new_cases, dtype: float64
130248 130255    4427.0
Name: new_cases, dtype: float64
130249 130256    14004.0
Name: new_cases, dtype: float64
130250 130257    4142.0
Name: new_cases, dtype: float64
130251 130258    0.0
Name: new_cases, dtype: float64
130252 130259    0.0
Name: new_cases, dtype: float64
130253 130260    8167.0
Name: new_cases, dtype: float64
130254 130261    3432.0
Name: new_cases, dtype: float64
130255 130262    3832.0
Name: new_cases, dtype: float64
130256 130263    4197.0
Name: new_cases, dtype: float64
130257 130264    4214.0
Name: new_cases, dtype: float64
130258 130265    0.0
Name: new_cases, dtype: float64
130259 130266    0.0
Name: new_cases, dtype: float64
130260 130267    7209.0
Name: new_cases, dtype: float64
130261 130268    4040.0
Name: new_cases, dtype: float64
130262 130269    4341.0
Name: new_cases, dtype: float64
130263 130270    4507.0
Name: new_cases, dtype: float64
130264 130271    4924.0
Name: new_cases, dtype: float64
130265 130272    0.0
Name: new_cases, dtype: float64
130266 130273    0.0
Name: new_cases, dtype: float64
130267 130274    10179.0
Name: new_cases, dtype: float64
130268 130275    7091.0
Name: new_cases, dtype: float64
130269 130276    9227.0
Name: new_cases, dtype: float64
130270 130277    12345.0
Name: new_cases, dtype: float64

130271 130278    12563.0
Name: new_cases, dtype: float64
130272 130279    0.0
Name: new_cases, dtype: float64
130273 130280    0.0
Name: new_cases, dtype: float64
130274 130281    32607.0
Name: new_cases, dtype: float64
130275 130282    14137.0
Name: new_cases, dtype: float64
130276 130283    17384.0
Name: new_cases, dtype: float64
130277 130284    17317.0
Name: new_cases, dtype: float64
130278 130285    21879.0
Name: new_cases, dtype: float64
130279 130286    0.0
Name: new_cases, dtype: float64
130280 130287    0.0
Name: new_cases, dtype: float64
130281 130288    33932.0
Name: new_cases, dtype: float64
130282 130289    43960.0
Name: new_cases, dtype: float64
130283 130290    26390.0
Name: new_cases, dtype: float64
130284 130291    27688.0
Name: new_cases, dtype: float64
130285 130292    31060.0
Name: new_cases, dtype: float64
130286 130293    0.0
Name: new_cases, dtype: float64
130287 130294    0.0
Name: new_cases, dtype: float64
130288 130295    61628.0
Name: new_cases, dtype: float64
130289 130296    27286.0
Name: new_cases, dtype: float64
130290 130297    30587.0
Name: new_cases, dtype: float64
130291 130298    29535.0
Name: new_cases, dtype: float64
130292 130299    31171.0
Name: new_cases, dtype: float64
130293 130300    0.0
Name: new_cases, dtype: float64
130294 130301    0.0
Name: new_cases, dtype: float64
130295 130302    61625.0
Name: new_cases, dtype: float64
130296 130303    26399.0
Name: new_cases, dtype: float64
130297 130304    27149.0
Name: new_cases, dtype: float64
130298 130305    26689.0
Name: new_cases, dtype: float64
130299 130306    24753.0
Name: new_cases, dtype: float64
130300 130307    0.0
Name: new_cases, dtype: float64
130301 130308    0.0
Name: new_cases, dtype: float64
130302 130309    55939.0
Name: new_cases, dtype: float64
130303 130310    20327.0
Name: new_cases, dtype: float64
130304 130311    21874.0
Name: new_cases, dtype: float64
130305 130312    21387.0
Name: new_cases, dtype: float64
130306 130313    21561.0
Name: new_cases, dtype: float64
130307 130314    0.0
Name: new_cases, dtype: float64
130308 130315    0.0
Name: new_cases, dtype: float64
130309 130316    39638.0
Name: new_cases, dtype: float64
130310 130317    15680.0
Name: new_cases, dtype: float64
130311 130318    17023.0
Name: new_cases, dtype: float64
130312 130319    17410.0
Name: new_cases, dtype: float64
130313 130320    15657.0
Name: new_cases, dtype: float64
130314 130321    0.0
Name: new_cases, dtype: float64
130315 130322    0.0
Name: new_cases, dtype: float64
130316 130323    25726.0
Name: new_cases, dtype: float64
130317 130324    14336.0
Name: new_cases, dtype: float64
130318 130325    11956.0
Name: new_cases, dtype: float64
130319 130326    12445.0
Name: new_cases, dtype: float64
130320 130327    12450.0
Name: new_cases, dtype: float64
130321 130328    0.0
Name: new_cases, dtype: float64
130322 130329    0.0
Name: new_cases, dtype: float64
130323 130330    23899.0
Name: new_cases, dtype: float64
130324 130331    10072.0
Name: new_cases, dtype: float64
130325 130332    10781.0
Name: new_cases, dtype: float64
130326 130333    7115.0
Name: new_cases, dtype: float64
130327 130334    9489.0
Name: new_cases, dtype: float64
130328 130335    0.0
Name: new_cases, dtype: float64
130329 130336    0.0
Name: new_cases, dtype: float64
130330 130337    15489.0
Name: new_cases, dtype: float64
130331 130338    7767.0
Name: new_cases, dtype: float64
130332 130339    6818.0
Name: new_cases, dtype: float64
130333 130340    9561.0
Name: new_cases, dtype: float64
130334 130341    6311.0
Name: new_cases, dtype: float64
130335 130342    0.0
Name: new_cases, dtype: float64
130336 130343    0.0
Name: new_cases, dtype: float64
130337 130344    9357.0
Name: new_cases, dtype: float64
130338 130345    5528.0
Name: new_cases, dtype: float64
130339 130346    5618.0
Name: new_cases, dtype: float64
130340 130347    4763.0
Name: new_cases, dtype: float64
130341 130348    4440.0
Name: new_cases, dtype: float64
130342 130349    0.0
Name: new_cases, dtype: float64
130343 130350    0.0
Name: new_cases, dtype: float64
130344 130351    7804.0
Name: new_cases, dtype: float64
130345 130352    3261.0
Name: new_cases, dtype: float64
130346 130353    3723.0
Name: new_cases, dtype: float64
130347 130354    4075.0
Name: new_cases, dtype: float64
130348 130355    3222.0
Name: new_cases, dtype: float64
130349 130356    0.0
Name: new_cases, dtype: float64
130350 130357    0.0
Name: new_cases, dtype: float64
130351 130358    5988.0
Name: new_cases, dtype: float64
130352 130359    2450.0
Name: new_cases, dtype: float64
130353 130360    2840.0
Name: new_cases, dtype: float64
130354 130361    3031.0
Name: new_cases, dtype: float64
130355 130362    2746.0
Name: new_cases, dtype: float64
130356 130363    0.0
Name: new_cases, dtype: float64
130357 130364    0.0
Name: new_cases, dtype: float64
130358 130365    5039.0
Name: new_cases, dtype: float64
130359 130366    2290.0
Name: new_cases, dtype: float64
130360 130367    2761.0
Name: new_cases, dtype: float64
130361 130368    2400.0
Name: new_cases, dtype: float64
130362 130369    2037.0
Name: new_cases, dtype: float64
130363 130370    0.0
Name: new_cases, dtype: float64
130364 130371    0.0
Name: new_cases, dtype: float64
130365 130372    4271.0
Name: new_cases, dtype: float64
130366 130373    1801.0
Name: new_cases, dtype: float64
130367 130374    2303.0
Name: new_cases, dtype: float64
130368 130375    1807.0
Name: new_cases, dtype: float64
130369 130376    2309.0
Name: new_cases, dtype: float64
130370 130377    0.0
Name: new_cases, dtype: float64
130371 130378    0.0
Name: new_cases, dtype: float64
130372 130379    3829.0
Name: new_cases, dtype: float64
130373 130380    0.0
Name: new_cases, dtype: float64
130374 130381    2758.0
Name: new_cases, dtype: float64
130375 130382    1932.0
Name: new_cases, dtype: float64
130376 130383    2248.0
Name: new_cases, dtype: float64
130377 130384    0.0
Name: new_cases, dtype: float64
130378 130385    0.0
Name: new_cases, dtype: float64
130379 130386    4492.0
Name: new_cases, dtype: float64
130380 130387    1889.0
Name: new_cases, dtype: float64
130381 130388    2528.0
Name: new_cases, dtype: float64
130382 130389    1881.0
Name: new_cases, dtype: float64
130383 130390    2556.0
Name: new_cases, dtype: float64
130384 130391    0.0
Name: new_cases, dtype: float64
130385 130392    0.0
Name: new_cases, dtype: float64
130386 130393    4485.0
Name: new_cases, dtype: float64
130387 130394    1926.0
Name: new_cases, dtype: float64
130388 130395    2532.0
Name: new_cases, dtype: float64
130389 130396    2212.0
Name: new_cases, dtype: float64
130390 130397    2261.0
Name: new_cases, dtype: float64
130391 130398    0.0
Name: new_cases, dtype: float64
130392 130399    0.0
Name: new_cases, dtype: float64
130393 130400    0.0
Name: new_cases, dtype: float64
130394 130401    5820.0
Name: new_cases, dtype: float64
130395 130402    2287.0
Name: new_cases, dtype: float64
130396 130403    3291.0
Name: new_cases, dtype: float64
130397 130404    3093.0
Name: new_cases, dtype: float64
130398 130405    0.0
Name: new_cases, dtype: float64
130399 130406    0.0
Name: new_cases, dtype: float64
130400 130407    6417.0
Name: new_cases, dtype: float64
130401 130408    0.0
Name: new_cases, dtype: float64
130402 130409    6461.0
Name: new_cases, dtype: float64
130403 130410    4286.0
Name: new_cases, dtype: float64
130404 130411    4353.0
Name: new_cases, dtype: float64
130405 130412    0.0
Name: new_cases, dtype: float64
130406 130413    0.0
Name: new_cases, dtype: float64
130407 130414    9798.0
Name: new_cases, dtype: float64
130408 130415    4091.0
Name: new_cases, dtype: float64
130409 130416    6667.0
Name: new_cases, dtype: float64
130410 130417    6315.0
Name: new_cases, dtype: float64
130411 130418    6636.0
Name: new_cases, dtype: float64
130412 130419    0.0
Name: new_cases, dtype: float64
130413 130420    0.0
Name: new_cases, dtype: float64
130414 130421    15875.0
Name: new_cases, dtype: float64
130415 130422    6777.0
Name: new_cases, dtype: float64
130416 130423    8527.0
Name: new_cases, dtype: float64
130417 130424    9258.0
Name: new_cases, dtype: float64
130418 130425    9912.0
Name: new_cases, dtype: float64
130419 130426    0.0
Name: new_cases, dtype: float64
130420 130427    0.0
Name: new_cases, dtype: float64
130421 130428    22911.0
Name: new_cases, dtype: float64
130422 130429    10261.0
Name: new_cases, dtype: float64
130423 130430    10536.0
Name: new_cases, dtype: float64
130424 130431    14500.0
Name: new_cases, dtype: float64
130425 130432    13738.0
Name: new_cases, dtype: float64
130426 130433    0.0
Name: new_cases, dtype: float64
130427 130434    0.0
Name: new_cases, dtype: float64
130428 130435    0.0
Name: new_cases, dtype: float64
130429 130436    43808.0
Name: new_cases, dtype: float64

130430 130437    0.0
Name: new_cases, dtype: float64
130431 130438    26412.0
Name: new_cases, dtype: float64
130432 130439    17095.0
Name: new_cases, dtype: float64
130433 130440   -83.0
Name: new_cases, dtype: float64
130434 130441    0.0
Name: new_cases, dtype: float64
130435 130442    49802.0
Name: new_cases, dtype: float64
130436 130443    26136.0
Name: new_cases, dtype: float64
130437 130444    27140.0
Name: new_cases, dtype: float64
130438 130445    28900.0
Name: new_cases, dtype: float64
130439 130446    33359.0
Name: new_cases, dtype: float64
130440 130447    0.0
Name: new_cases, dtype: float64
130441 130448    0.0
Name: new_cases, dtype: float64
130442 130449    79704.0
Name: new_cases, dtype: float64
130443 130450    49823.0
Name: new_cases, dtype: float64
130444 130451    60041.0
Name: new_cases, dtype: float64
130445 130452    72912.0
Name: new_cases, dtype: float64
130446 130453    0.0
Name: new_cases, dtype: float64
130447 130454    0.0
Name: new_cases, dtype: float64
130448 130455    0.0
Name: new_cases, dtype: float64
130449 130456    214619.0
Name: new_cases, dtype: float64
130450 130457    99671.0
Name: new_cases, dtype: float64
130451 130458    100760.0
Name: new_cases, dtype: float64
130452 130459    161688.0
Name: new_cases, dtype: float64
130453 130460    0.0
Name: new_cases, dtype: float64
130454 130461    0.0
Name: new_cases, dtype: float64
130455 130462    0.0
Name: new_cases, dtype: float64
130456 130463    372766.0
Name: new_cases, dtype: float64
130457 130464    117775.0
Name: new_cases, dtype: float64
130458 130465    137180.0
Name: new_cases, dtype: float64
130459 130466    0.0
Name: new_cases, dtype: float64
130460 130467    242440.0
Name: new_cases, dtype: float64
130461 129761    1.0
Name: new_cases, dtype: float64
130462 129762    0.0
Name: new_cases, dtype: float64
130463 129763    0.0
Name: new_cases, dtype: float64
130464 129764    0.0
Name: new_cases, dtype: float64
130465 129765    0.0
Name: new_cases, dtype: float64
130466 129766    0.0
Name: new_cases, dtype: float64
130467 129767    0.0
Name: new_cases, dtype: float64
132515 132522    0.0
Name: new_cases, dtype: float64
132516 132523    0.0
Name: new_cases, dtype: float64
132517 132524    0.0
Name: new_cases, dtype: float64
132518 132525    0.0
Name: new_cases, dtype: float64
132519 132526    0.0
Name: new_cases, dtype: float64
132520 132527    0.0
Name: new_cases, dtype: float64
132521 132528    0.0
Name: new_cases, dtype: float64
132522 132529    0.0
Name: new_cases, dtype: float64
132523 132530    0.0
Name: new_cases, dtype: float64
132524 132531    0.0
Name: new_cases, dtype: float64
132525 132532    0.0
Name: new_cases, dtype: float64
132526 132533    0.0
Name: new_cases, dtype: float64
132527 132534    0.0
Name: new_cases, dtype: float64
132528 132535    0.0
Name: new_cases, dtype: float64
132529 132536    0.0
Name: new_cases, dtype: float64
132530 132537    0.0
Name: new_cases, dtype: float64
132531 132538    0.0
Name: new_cases, dtype: float64
132532 132539    0.0
Name: new_cases, dtype: float64
132533 132540    1.0
Name: new_cases, dtype: float64
132534 132541    1.0
Name: new_cases, dtype: float64
132535 132542    8.0
Name: new_cases, dtype: float64
132536 132543    3.0
Name: new_cases, dtype: float64
132537 132544    0.0
Name: new_cases, dtype: float64
132538 132545    5.0
Name: new_cases, dtype: float64
132539 132546    13.0
Name: new_cases, dtype: float64
132540 132547    30.0
Name: new_cases, dtype: float64
132541 132548    25.0
Name: new_cases, dtype: float64
132542 132549    59.0
Name: new_cases, dtype: float64
132543 132550    33.0
Name: new_cases, dtype: float64
132544 132551    46.0
Name: new_cases, dtype: float64
132545 132552    101.0
Name: new_cases, dtype: float64
132546 132553    98.0
Name: new_cases, dtype: float64
132547 132554    196.0
Name: new_cases, dtype: float64
132548 132555    151.0
Name: new_cases, dtype: float64
132549 132556    152.0
Name: new_cases, dtype: float64
132550 132557    71.0
Name: new_cases, dtype: float64
132551 132558    69.0
Name: new_cases, dtype: float64
132552 132559    83.0
Name: new_cases, dtype: float64
132553 132560    119.0
Name: new_cases, dtype: float64
132554 132561    145.0
Name: new_cases, dtype: float64
132555 132562    143.0
Name: new_cases, dtype: float64
132556 132563    180.0
Name: new_cases, dtype: float64
132557 132564    135.0
Name: new_cases, dtype: float64
132558 132565    118.0
Name: new_cases, dtype: float64
132559 132566    182.0
Name: new_cases, dtype: float64
132560 132567    230.0
Name: new_cases, dtype: float64
132561 132568    314.0
Name: new_cases, dtype: float64
132562 132569    286.0
Name: new_cases, dtype: float64
132563 132570    365.0
Name: new_cases, dtype: float64
132564 132571    300.0
Name: new_cases, dtype: float64
132565 132572    280.0
Name: new_cases, dtype: float64
132566 132573    416.0
Name: new_cases, dtype: float64
132567 132574    475.0
Name: new_cases, dtype: float64
132568 132575    486.0
Name: new_cases, dtype: float64
132569 132576    554.0
Name: new_cases, dtype: float64
132570 132577    601.0
Name: new_cases, dtype: float64
132571 132578    357.0
Name: new_cases, dtype: float64
132572 132579    340.0
Name: new_cases, dtype: float64
132573 132580    389.0
Name: new_cases, dtype: float64
132574 132581    738.0
Name: new_cases, dtype: float64
132575 132582    655.0
Name: new_cases, dtype: float64
132576 132583    645.0
Name: new_cases, dtype: float64
132577 132584    454.0
Name: new_cases, dtype: float64
132578 132585    395.0
Name: new_cases, dtype: float64
132579 132586    464.0
Name: new_cases, dtype: float64
132580 132587    437.0
Name: new_cases, dtype: float64
132581 132588    479.0
Name: new_cases, dtype: float64
132582 132589    604.0
Name: new_cases, dtype: float64
132583 132590    623.0
Name: new_cases, dtype: float64
132584 132591    688.0
Name: new_cases, dtype: float64
132585 132592    532.0
Name: new_cases, dtype: float64
132586 132593    388.0
Name: new_cases, dtype: float64
132587 132594    461.0
Name: new_cases, dtype: float64
132588 132595    707.0
Name: new_cases, dtype: float64
132589 132596    722.0
Name: new_cases, dtype: float64
132590 132597    758.0
Name: new_cases, dtype: float64
132591 132598    779.0
Name: new_cases, dtype: float64
132592 132599    473.0
Name: new_cases, dtype: float64
132593 132600    300.0
Name: new_cases, dtype: float64
132594 132601    563.0
Name: new_cases, dtype: float64
132595 132602    742.0
Name: new_cases, dtype: float64
132596 132603    798.0
Name: new_cases, dtype: float64
132597 132604    635.0
Name: new_cases, dtype: float64
132598 132605    532.0
Name: new_cases, dtype: float64
132599 132606    299.0
Name: new_cases, dtype: float64
132600 132607    261.0
Name: new_cases, dtype: float64
132601 132608    476.0
Name: new_cases, dtype: float64
132602 132609    657.0
Name: new_cases, dtype: float64
132603 132610    746.0
Name: new_cases, dtype: float64
132604 132611    787.0
Name: new_cases, dtype: float64
132605 132612    700.0
Name: new_cases, dtype: float64
132606 132613    509.0
Name: new_cases, dtype: float64
132607 132614    278.0
Name: new_cases, dtype: float64
132608 132615    455.0
Name: new_cases, dtype: float64
132609 132616    754.0
Name: new_cases, dtype: float64
132610 132617    700.0
Name: new_cases, dtype: float64
132611 132618    660.0
Name: new_cases, dtype: float64
132612 132619    688.0
Name: new_cases, dtype: float64
132613 132620    358.0
Name: new_cases, dtype: float64
132614 132621    259.0
Name: new_cases, dtype: float64
132615 132622    431.0
Name: new_cases, dtype: float64
132616 132623    667.0
Name: new_cases, dtype: float64
132617 132624    808.0
Name: new_cases, dtype: float64
132618 132625    610.0
Name: new_cases, dtype: float64
132619 132626    532.0
Name: new_cases, dtype: float64
132620 132627    403.0
Name: new_cases, dtype: float64
132621 132628    210.0
Name: new_cases, dtype: float64
132622 132629    490.0
Name: new_cases, dtype: float64
132623 132630    746.0
Name: new_cases, dtype: float64
132624 132631    800.0
Name: new_cases, dtype: float64
132625 132632    774.0
Name: new_cases, dtype: float64
132626 132633    773.0
Name: new_cases, dtype: float64
132627 132634    432.0
Name: new_cases, dtype: float64
132628 132635    265.0
Name: new_cases, dtype: float64
132629 132636    648.0
Name: new_cases, dtype: float64
132630 132637    901.0
Name: new_cases, dtype: float64
132631 132638    1046.0
Name: new_cases, dtype: float64
132632 132639    1039.0
Name: new_cases, dtype: float64
132633 132640    1146.0
Name: new_cases, dtype: float64
132634 132641    783.0
Name: new_cases, dtype: float64
132635 132642    462.0
Name: new_cases, dtype: float64
132636 132643    677.0
Name: new_cases, dtype: float64

132637 132644    936.0
Name: new_cases, dtype: float64
132638 132645    1437.0
Name: new_cases, dtype: float64
132639 132646    1294.0
Name: new_cases, dtype: float64
132640 132647    1337.0
Name: new_cases, dtype: float64
132641 132648    1042.0
Name: new_cases, dtype: float64
132642 132649    418.0
Name: new_cases, dtype: float64
132643 132650    684.0
Name: new_cases, dtype: float64
132644 132651    1218.0
Name: new_cases, dtype: float64
132645 132652    1457.0
Name: new_cases, dtype: float64
132646 132653    1496.0
Name: new_cases, dtype: float64
132647 132654    1213.0
Name: new_cases, dtype: float64
132648 132655    702.0
Name: new_cases, dtype: float64
132649 132656    321.0
Name: new_cases, dtype: float64
132650 132657    800.0
Name: new_cases, dtype: float64
132651 132658    1312.0
Name: new_cases, dtype: float64
132652 132659    1698.0
Name: new_cases, dtype: float64
132653 132660    1281.0
Name: new_cases, dtype: float64
132654 132661    1203.0
Name: new_cases, dtype: float64
132655 132662    760.0
Name: new_cases, dtype: float64
132656 132663    420.0
Name: new_cases, dtype: float64
132657 132664    727.0
Name: new_cases, dtype: float64
132658 132665    805.0
Name: new_cases, dtype: float64
132659 132666    684.0
Name: new_cases, dtype: float64
132660 132667    689.0
Name: new_cases, dtype: float64
132661 132668    699.0
Name: new_cases, dtype: float64
132662 132669    370.0
Name: new_cases, dtype: float64
132663 132670    315.0
Name: new_cases, dtype: float64
132664 132671    251.0
Name: new_cases, dtype: float64
132665 132672    278.0
Name: new_cases, dtype: float64
132666 132673    537.0
Name: new_cases, dtype: float64
132667 132674    335.0
Name: new_cases, dtype: float64
132668 132675    377.0
Name: new_cases, dtype: float64
132669 132676    314.0
Name: new_cases, dtype: float64
132670 132677    106.0
Name: new_cases, dtype: float64
132671 132678    170.0
Name: new_cases, dtype: float64
132672 132679    315.0
Name: new_cases, dtype: float64
132673 132680    299.0
Name: new_cases, dtype: float64
132674 132681    273.0
Name: new_cases, dtype: float64
132675 132682    299.0
Name: new_cases, dtype: float64
132676 132683    200.0
Name: new_cases, dtype: float64
132677 132684    110.0
Name: new_cases, dtype: float64
132678 132685    131.0
Name: new_cases, dtype: float64
132679 132686    226.0
Name: new_cases, dtype: float64
132680 132687    297.0
Name: new_cases, dtype: float64
132681 132688    220.0
Name: new_cases, dtype: float64
132682 132689    262.0
Name: new_cases, dtype: float64
132683 132690    138.0
Name: new_cases, dtype: float64
132684 132691    42.0
Name: new_cases, dtype: float64
132685 132692    71.0
Name: new_cases, dtype: float64
132686 132693    283.0
Name: new_cases, dtype: float64
132687 132694    301.0
Name: new_cases, dtype: float64
132688 132695    302.0
Name: new_cases, dtype: float64
132689 132696    258.0
Name: new_cases, dtype: float64
132690 132697    303.0
Name: new_cases, dtype: float64
132691 132698    38.0
Name: new_cases, dtype: float64
132692 132699    165.0
Name: new_cases, dtype: float64
132693 132700    334.0
Name: new_cases, dtype: float64
132694 132701    425.0
Name: new_cases, dtype: float64
132695 132702    378.0
Name: new_cases, dtype: float64
132696 132703    380.0
Name: new_cases, dtype: float64
132697 132704    260.0
Name: new_cases, dtype: float64
132698 132705    73.0
Name: new_cases, dtype: float64
132699 132706    196.0
Name: new_cases, dtype: float64
132700 132707    417.0
Name: new_cases, dtype: float64
132701 132708    444.0
Name: new_cases, dtype: float64
132702 132709    362.0
Name: new_cases, dtype: float64
132703 132710    344.0
Name: new_cases, dtype: float64
132704 132711    226.0
Name: new_cases, dtype: float64
132705 132712    63.0
Name: new_cases, dtype: float64
132706 132713    174.0
Name: new_cases, dtype: float64
132707 132714    314.0
Name: new_cases, dtype: float64
132708 132715    351.0
Name: new_cases, dtype: float64
132709 132716    333.0
Name: new_cases, dtype: float64
132710 132717    298.0
Name: new_cases, dtype: float64
132711 132718    160.0
Name: new_cases, dtype: float64
132712 132719    57.0
Name: new_cases, dtype: float64
132713 132720    182.0
Name: new_cases, dtype: float64
132714 132721    225.0
Name: new_cases, dtype: float64
132715 132722    246.0
Name: new_cases, dtype: float64
132716 132723    134.0
Name: new_cases, dtype: float64
132717 132724    0.0
Name: new_cases, dtype: float64
132718 132725    0.0
Name: new_cases, dtype: float64
132719 132726    0.0
Name: new_cases, dtype: float64
132720 132727    421.0
Name: new_cases, dtype: float64
132721 132728    142.0
Name: new_cases, dtype: float64
132722 132729    11.0
Name: new_cases, dtype: float64
132723 132730    197.0
Name: new_cases, dtype: float64
132724 132731    256.0
Name: new_cases, dtype: float64
132725 132732    0.0
Name: new_cases, dtype: float64
132726 132733    0.0
Name: new_cases, dtype: float64
132727 132734    573.0
Name: new_cases, dtype: float64
132728 132735    149.0
Name: new_cases, dtype: float64
132729 132736    173.0
Name: new_cases, dtype: float64
132730 132737    314.0
Name: new_cases, dtype: float64
132731 132738    311.0
Name: new_cases, dtype: float64
132732 132739    0.0
Name: new_cases, dtype: float64
132733 132740    0.0
Name: new_cases, dtype: float64
132734 132741    0.0
Name: new_cases, dtype: float64
132735 132742    840.0
Name: new_cases, dtype: float64
132736 132743    230.0
Name: new_cases, dtype: float64
132737 132744    310.0
Name: new_cases, dtype: float64
132738 132745    352.0
Name: new_cases, dtype: float64
132739 132746    0.0
Name: new_cases, dtype: float64
132740 132747    0.0
Name: new_cases, dtype: float64
132741 132748    0.0
Name: new_cases, dtype: float64
132742 132749    1199.0
Name: new_cases, dtype: float64
132743 132750    320.0
Name: new_cases, dtype: float64
132744 132751    533.0
Name: new_cases, dtype: float64
132745 132752    634.0
Name: new_cases, dtype: float64
132746 132753    0.0
Name: new_cases, dtype: float64
132747 132754    0.0
Name: new_cases, dtype: float64
132748 132755    0.0
Name: new_cases, dtype: float64
132749 132756    1543.0
Name: new_cases, dtype: float64
132750 132757    397.0
Name: new_cases, dtype: float64
132751 132758    752.0
Name: new_cases, dtype: float64
132752 132759    668.0
Name: new_cases, dtype: float64
132753 132760    0.0
Name: new_cases, dtype: float64
132754 132761    0.0
Name: new_cases, dtype: float64
132755 132762    0.0
Name: new_cases, dtype: float64
132756 132763    1862.0
Name: new_cases, dtype: float64
132757 132764    532.0
Name: new_cases, dtype: float64
132758 132765    855.0
Name: new_cases, dtype: float64
132759 132766    919.0
Name: new_cases, dtype: float64
132760 132767    0.0
Name: new_cases, dtype: float64
132761 132768    0.0
Name: new_cases, dtype: float64
132762 132769    0.0
Name: new_cases, dtype: float64
132763 132770    2203.0
Name: new_cases, dtype: float64
132764 132771    678.0
Name: new_cases, dtype: float64
132765 132772    1075.0
Name: new_cases, dtype: float64
132766 132773    793.0
Name: new_cases, dtype: float64
132767 132774    0.0
Name: new_cases, dtype: float64
132768 132775    0.0
Name: new_cases, dtype: float64
132769 132776    0.0
Name: new_cases, dtype: float64
132770 132777    3180.0
Name: new_cases, dtype: float64
132771 132778    975.0
Name: new_cases, dtype: float64
132772 132779    1614.0
Name: new_cases, dtype: float64
132773 132780    1625.0
Name: new_cases, dtype: float64
132774 132781    0.0
Name: new_cases, dtype: float64
132775 132782    0.0
Name: new_cases, dtype: float64
132776 132783    0.0
Name: new_cases, dtype: float64
132777 132784    5191.0
Name: new_cases, dtype: float64
132778 132785    2128.0
Name: new_cases, dtype: float64
132779 132786    3254.0
Name: new_cases, dtype: float64
132780 132787    3188.0
Name: new_cases, dtype: float64
132781 132788    0.0
Name: new_cases, dtype: float64
132782 132789    0.0
Name: new_cases, dtype: float64
132783 132790    0.0
Name: new_cases, dtype: float64
132784 132791    10177.0
Name: new_cases, dtype: float64
132785 132792    3198.0
Name: new_cases, dtype: float64
132786 132793    4034.0
Name: new_cases, dtype: float64
132787 132794    4697.0
Name: new_cases, dtype: float64
132788 132795    0.0
Name: new_cases, dtype: float64
132789 132796    0.0
Name: new_cases, dtype: float64
132790 132797    0.0
Name: new_cases, dtype: float64
132791 132798    15779.0
Name: new_cases, dtype: float64
132792 132799    4467.0
Name: new_cases, dtype: float64
132793 132800    4658.0
Name: new_cases, dtype: float64
132794 132801    5990.0
Name: new_cases, dtype: float64
132795 132802    0.0
Name: new_cases, dtype: float64
132796 132803    0.0
Name: new_cases, dtype: float64
132797 132804    0.0
Name: new_cases, dtype: float64
132798 132805    15084.0
Name: new_cases, dtype: float64
132799 132806    4007.0
Name: new_cases, dtype: float64
132800 132807    4609.0
Name: new_cases, dtype: float64
132801 132808    7240.0
Name: new_cases, dtype: float64
132802 132809    0.0
Name: new_cases, dtype: float64
132803 132810    0.0
Name: new_cases, dtype: float64

132804 132811    0.0
Name: new_cases, dtype: float64
132805 132812    17265.0
Name: new_cases, dtype: float64
132806 132813    4954.0
Name: new_cases, dtype: float64
132807 132814    5841.0
Name: new_cases, dtype: float64
132808 132815    6774.0
Name: new_cases, dtype: float64
132809 132816    0.0
Name: new_cases, dtype: float64
132810 132817    0.0
Name: new_cases, dtype: float64
132811 132818    0.0
Name: new_cases, dtype: float64
132812 132819    17629.0
Name: new_cases, dtype: float64
132813 132820    5400.0
Name: new_cases, dtype: float64
132814 132821    6485.0
Name: new_cases, dtype: float64
132815 132822    6269.0
Name: new_cases, dtype: float64
132816 132823    0.0
Name: new_cases, dtype: float64
132817 132824    0.0
Name: new_cases, dtype: float64
132818 132825    0.0
Name: new_cases, dtype: float64
132819 132826    18820.0
Name: new_cases, dtype: float64
132820 132827    7061.0
Name: new_cases, dtype: float64
132821 132828    7935.0
Name: new_cases, dtype: float64
132822 132829    7370.0
Name: new_cases, dtype: float64
132823 132830    0.0
Name: new_cases, dtype: float64
132824 132831    0.0
Name: new_cases, dtype: float64
132825 132832    0.0
Name: new_cases, dtype: float64
132826 132833    20931.0
Name: new_cases, dtype: float64
132827 132834    7556.0
Name: new_cases, dtype: float64
132828 132835    8881.0
Name: new_cases, dtype: float64
132829 132836    9654.0
Name: new_cases, dtype: float64
132830 132837    0.0
Name: new_cases, dtype: float64
132831 132838    0.0
Name: new_cases, dtype: float64
132832 132839    0.0
Name: new_cases, dtype: float64
132833 132840    22319.0
Name: new_cases, dtype: float64
132834 132841    6609.0
Name: new_cases, dtype: float64
132835 132842    0.0
Name: new_cases, dtype: float64
132836 132843    0.0
Name: new_cases, dtype: float64
132837 132844    0.0
Name: new_cases, dtype: float64
132838 132845    0.0
Name: new_cases, dtype: float64
132839 132846    0.0
Name: new_cases, dtype: float64
132840 132847    32485.0
Name: new_cases, dtype: float64
132841 132848    8846.0
Name: new_cases, dtype: float64
132842 132849    0.0
Name: new_cases, dtype: float64
132843 132850    0.0
Name: new_cases, dtype: float64
132844 132851    0.0
Name: new_cases, dtype: float64
132845 132852    0.0
Name: new_cases, dtype: float64
132846 132853    0.0
Name: new_cases, dtype: float64
132847 132854    32369.0
Name: new_cases, dtype: float64
132848 132855    0.0
Name: new_cases, dtype: float64
132849 132856    12536.0
Name: new_cases, dtype: float64
132850 132857    7187.0
Name: new_cases, dtype: float64
132851 132858    0.0
Name: new_cases, dtype: float64
132852 132859    0.0
Name: new_cases, dtype: float64
132853 132860    0.0
Name: new_cases, dtype: float64
132854 132861    17395.0
Name: new_cases, dtype: float64
132855 132862    5337.0
Name: new_cases, dtype: float64
132856 132863    6580.0
Name: new_cases, dtype: float64
132857 132864    4703.0
Name: new_cases, dtype: float64
132858 132865    0.0
Name: new_cases, dtype: float64
132859 132866    0.0
Name: new_cases, dtype: float64
132860 132867    0.0
Name: new_cases, dtype: float64
132861 132868    9779.0
Name: new_cases, dtype: float64
132862 132869    4702.0
Name: new_cases, dtype: float64
132863 132870    4985.0
Name: new_cases, dtype: float64
132864 132871    4214.0
Name: new_cases, dtype: float64
132865 132872    0.0
Name: new_cases, dtype: float64
132866 132873    0.0
Name: new_cases, dtype: float64
132867 132874    0.0
Name: new_cases, dtype: float64
132868 132875    9123.0
Name: new_cases, dtype: float64
132869 132876    4183.0
Name: new_cases, dtype: float64
132870 132877    4085.0
Name: new_cases, dtype: float64
132871 132878    2400.0
Name: new_cases, dtype: float64
132872 132879    0.0
Name: new_cases, dtype: float64
132873 132880    0.0
Name: new_cases, dtype: float64
132874 132881    0.0
Name: new_cases, dtype: float64
132875 132882    9649.0
Name: new_cases, dtype: float64
132876 132883    4310.0
Name: new_cases, dtype: float64
132877 132884    3758.0
Name: new_cases, dtype: float64
132878 132885    3388.0
Name: new_cases, dtype: float64
132879 132886    0.0
Name: new_cases, dtype: float64
132880 132887    0.0
Name: new_cases, dtype: float64
132881 132888    0.0
Name: new_cases, dtype: float64
132882 132889    8112.0
Name: new_cases, dtype: float64
132883 132890    4070.0
Name: new_cases, dtype: float64
132884 132891    4333.0
Name: new_cases, dtype: float64
132885 132892    3834.0
Name: new_cases, dtype: float64
132886 132893    0.0
Name: new_cases, dtype: float64
132887 132894    0.0
Name: new_cases, dtype: float64
132888 132895    0.0
Name: new_cases, dtype: float64
132889 132896    9458.0
Name: new_cases, dtype: float64
132890 132897    4233.0
Name: new_cases, dtype: float64
132891 132898    4920.0
Name: new_cases, dtype: float64
132892 132899    4144.0
Name: new_cases, dtype: float64
132893 132900    0.0
Name: new_cases, dtype: float64
132894 132901    0.0
Name: new_cases, dtype: float64
132895 132902    0.0
Name: new_cases, dtype: float64
132896 132903    10933.0
Name: new_cases, dtype: float64
132897 132904    5371.0
Name: new_cases, dtype: float64
132898 132905    4995.0
Name: new_cases, dtype: float64
132899 132906    4844.0
Name: new_cases, dtype: float64
132900 132907    0.0
Name: new_cases, dtype: float64
132901 132908    0.0
Name: new_cases, dtype: float64
132902 132909    0.0
Name: new_cases, dtype: float64
132903 132910    11804.0
Name: new_cases, dtype: float64
132904 132911    6179.0
Name: new_cases, dtype: float64
132905 132912    4838.0
Name: new_cases, dtype: float64
132906 132913    4831.0
Name: new_cases, dtype: float64
132907 132914    0.0
Name: new_cases, dtype: float64
132908 132915    0.0
Name: new_cases, dtype: float64
132909 132916    0.0
Name: new_cases, dtype: float64
132910 132917    11014.0
Name: new_cases, dtype: float64
132911 132918    5917.0
Name: new_cases, dtype: float64
132912 132919    5300.0
Name: new_cases, dtype: float64
132913 132920    5335.0
Name: new_cases, dtype: float64
132914 132921    0.0
Name: new_cases, dtype: float64
132915 132922    0.0
Name: new_cases, dtype: float64
132916 132923    0.0
Name: new_cases, dtype: float64
132917 132924    12762.0
Name: new_cases, dtype: float64
132918 132925    6781.0
Name: new_cases, dtype: float64
132919 132926    6467.0
Name: new_cases, dtype: float64
132920 132927    5735.0
Name: new_cases, dtype: float64
132921 132928    0.0
Name: new_cases, dtype: float64
132922 132929    0.0
Name: new_cases, dtype: float64
132923 132930    0.0
Name: new_cases, dtype: float64
132924 132931    14063.0
Name: new_cases, dtype: float64
132925 132932    7649.0
Name: new_cases, dtype: float64
132926 132933    7706.0
Name: new_cases, dtype: float64
132927 132934    6328.0
Name: new_cases, dtype: float64
132928 132935    0.0
Name: new_cases, dtype: float64
132929 132936    0.0
Name: new_cases, dtype: float64
132930 132937    0.0
Name: new_cases, dtype: float64
132931 132938    16427.0
Name: new_cases, dtype: float64
132932 132939    8441.0
Name: new_cases, dtype: float64
132933 132940    8305.0
Name: new_cases, dtype: float64
132934 132941    0.0
Name: new_cases, dtype: float64
132935 132942    0.0
Name: new_cases, dtype: float64
132936 132943    0.0
Name: new_cases, dtype: float64
132937 132944    0.0
Name: new_cases, dtype: float64
132938 132945    21802.0
Name: new_cases, dtype: float64
132939 132946    6814.0
Name: new_cases, dtype: float64
132940 132947    7822.0
Name: new_cases, dtype: float64
132941 132948    7772.0
Name: new_cases, dtype: float64
132942 132949    0.0
Name: new_cases, dtype: float64
132943 132950    0.0
Name: new_cases, dtype: float64
132944 132951    0.0
Name: new_cases, dtype: float64
132945 132952    19105.0
Name: new_cases, dtype: float64
132946 132953    8879.0
Name: new_cases, dtype: float64
132947 132954    7095.0
Name: new_cases, dtype: float64
132948 132955    7658.0
Name: new_cases, dtype: float64
132949 132956    0.0
Name: new_cases, dtype: float64
132950 132957    0.0
Name: new_cases, dtype: float64
132951 132958    0.0
Name: new_cases, dtype: float64
132952 132959    16692.0
Name: new_cases, dtype: float64
132953 132960    7510.0
Name: new_cases, dtype: float64
132954 132961    7736.0
Name: new_cases, dtype: float64
132955 132962    6267.0
Name: new_cases, dtype: float64
132956 132963    0.0
Name: new_cases, dtype: float64
132957 132964    0.0
Name: new_cases, dtype: float64
132958 132965    0.0
Name: new_cases, dtype: float64
132959 132966    14911.0
Name: new_cases, dtype: float64
132960 132967    7266.0
Name: new_cases, dtype: float64
132961 132968    7158.0
Name: new_cases, dtype: float64
132962 132969    5926.0
Name: new_cases, dtype: float64
132963 132970    0.0
Name: new_cases, dtype: float64
132964 132971    0.0
Name: new_cases, dtype: float64
132965 132972    0.0
Name: new_cases, dtype: float64
132966 132973    14950.0
Name: new_cases, dtype: float64

132967 132974    7041.0
Name: new_cases, dtype: float64
132968 132975    6526.0
Name: new_cases, dtype: float64
132969 132976    5671.0
Name: new_cases, dtype: float64
132970 132977    0.0
Name: new_cases, dtype: float64
132971 132978    0.0
Name: new_cases, dtype: float64
132972 132979    0.0
Name: new_cases, dtype: float64
132973 132980    13812.0
Name: new_cases, dtype: float64
132974 132981    6330.0
Name: new_cases, dtype: float64
132975 132982    0.0
Name: new_cases, dtype: float64
132976 132983    9192.0
Name: new_cases, dtype: float64
132977 132984    0.0
Name: new_cases, dtype: float64
132978 132985    0.0
Name: new_cases, dtype: float64
132979 132986    0.0
Name: new_cases, dtype: float64
132980 132987    10017.0
Name: new_cases, dtype: float64
132981 132988    4619.0
Name: new_cases, dtype: float64
132982 132989    3411.0
Name: new_cases, dtype: float64
132983 132990    3168.0
Name: new_cases, dtype: float64
132984 132991    0.0
Name: new_cases, dtype: float64
132985 132992    0.0
Name: new_cases, dtype: float64
132986 132993    0.0
Name: new_cases, dtype: float64
132987 132994    6034.0
Name: new_cases, dtype: float64
132988 132995    2732.0
Name: new_cases, dtype: float64
132989 132996    1366.0
Name: new_cases, dtype: float64
132990 132997    0.0
Name: new_cases, dtype: float64
132991 132998    0.0
Name: new_cases, dtype: float64
132992 132999    0.0
Name: new_cases, dtype: float64
132993 133000    0.0
Name: new_cases, dtype: float64
132994 133001    0.0
Name: new_cases, dtype: float64
132995 133002    0.0
Name: new_cases, dtype: float64
132996 133003    8520.0
Name: new_cases, dtype: float64
132997 133004    1069.0
Name: new_cases, dtype: float64
132998 133005    0.0
Name: new_cases, dtype: float64
132999 133006    0.0
Name: new_cases, dtype: float64
133000 133007    0.0
Name: new_cases, dtype: float64
133001 133008    2671.0
Name: new_cases, dtype: float64
133002 133009    1165.0
Name: new_cases, dtype: float64
133003 133010    831.0
Name: new_cases, dtype: float64
133004 133011    727.0
Name: new_cases, dtype: float64
133005 133012    0.0
Name: new_cases, dtype: float64
133006 133013    0.0
Name: new_cases, dtype: float64
133007 133014    0.0
Name: new_cases, dtype: float64
133008 133015    1180.0
Name: new_cases, dtype: float64
133009 133016    0.0
Name: new_cases, dtype: float64
133010 133017    0.0
Name: new_cases, dtype: float64
133011 133018    0.0
Name: new_cases, dtype: float64
133012 133019    0.0
Name: new_cases, dtype: float64
133013 133020    0.0
Name: new_cases, dtype: float64
133014 133021    0.0
Name: new_cases, dtype: float64
133015 133022    3378.0
Name: new_cases, dtype: float64
133016 133023    504.0
Name: new_cases, dtype: float64
133017 133024    378.0
Name: new_cases, dtype: float64
133018 133025    0.0
Name: new_cases, dtype: float64
133019 133026    0.0
Name: new_cases, dtype: float64
133020 133027    0.0
Name: new_cases, dtype: float64
133021 133028    0.0
Name: new_cases, dtype: float64
133022 133029    847.0
Name: new_cases, dtype: float64
133023 133030    247.0
Name: new_cases, dtype: float64
133024 133031    563.0
Name: new_cases, dtype: float64
133025 133032    327.0
Name: new_cases, dtype: float64
133026 133033    0.0
Name: new_cases, dtype: float64
133027 133034    0.0
Name: new_cases, dtype: float64
133028 133035    0.0
Name: new_cases, dtype: float64
133029 133036    850.0
Name: new_cases, dtype: float64
133030 133037    353.0
Name: new_cases, dtype: float64
133031 133038    225.0
Name: new_cases, dtype: float64
133032 133039    232.0
Name: new_cases, dtype: float64
133033 133040    0.0
Name: new_cases, dtype: float64
133034 133041    0.0
Name: new_cases, dtype: float64
133035 133042    0.0
Name: new_cases, dtype: float64
133036 133043    669.0
Name: new_cases, dtype: float64
133037 133044    367.0
Name: new_cases, dtype: float64
133038 133045    347.0
Name: new_cases, dtype: float64
133039 133046    364.0
Name: new_cases, dtype: float64
133040 133047    0.0
Name: new_cases, dtype: float64
133041 133048    0.0
Name: new_cases, dtype: float64
133042 133049    0.0
Name: new_cases, dtype: float64
133043 133050    992.0
Name: new_cases, dtype: float64
133044 133051    479.0
Name: new_cases, dtype: float64
133045 133052    583.0
Name: new_cases, dtype: float64
133046 133053    458.0
Name: new_cases, dtype: float64
133047 133054    0.0
Name: new_cases, dtype: float64
133048 133055    0.0
Name: new_cases, dtype: float64
133049 133056    0.0
Name: new_cases, dtype: float64
133050 133057    1355.0
Name: new_cases, dtype: float64
133051 133058    641.0
Name: new_cases, dtype: float64
133052 133059    619.0
Name: new_cases, dtype: float64
133053 133060    626.0
Name: new_cases, dtype: float64
133054 133061    0.0
Name: new_cases, dtype: float64
133055 133062    0.0
Name: new_cases, dtype: float64
133056 133063    0.0
Name: new_cases, dtype: float64
133057 133064    1860.0
Name: new_cases, dtype: float64
133058 133065    929.0
Name: new_cases, dtype: float64
133059 133066    864.0
Name: new_cases, dtype: float64
133060 133067    845.0
Name: new_cases, dtype: float64
133061 133068    0.0
Name: new_cases, dtype: float64
133062 133069    0.0
Name: new_cases, dtype: float64
133063 133070    0.0
Name: new_cases, dtype: float64
133064 133071    2283.0
Name: new_cases, dtype: float64
133065 133072    1236.0
Name: new_cases, dtype: float64
133066 133073    1055.0
Name: new_cases, dtype: float64
133067 133074    1035.0
Name: new_cases, dtype: float64
133068 133075    0.0
Name: new_cases, dtype: float64
133069 133076    0.0
Name: new_cases, dtype: float64
133070 133077    0.0
Name: new_cases, dtype: float64
133071 133078    2811.0
Name: new_cases, dtype: float64
133072 133079    1320.0
Name: new_cases, dtype: float64
133073 133080    1288.0
Name: new_cases, dtype: float64
133074 133081    1018.0
Name: new_cases, dtype: float64
133075 133082    0.0
Name: new_cases, dtype: float64
133076 133083    0.0
Name: new_cases, dtype: float64
133077 133084    0.0
Name: new_cases, dtype: float64
133078 133085    2774.0
Name: new_cases, dtype: float64
133079 133086    1270.0
Name: new_cases, dtype: float64
133080 133087    1511.0
Name: new_cases, dtype: float64
133081 133088    1274.0
Name: new_cases, dtype: float64
133082 133089    0.0
Name: new_cases, dtype: float64
133083 133090    0.0
Name: new_cases, dtype: float64
133084 133091    0.0
Name: new_cases, dtype: float64
133085 133092    3400.0
Name: new_cases, dtype: float64
133086 133093    1104.0
Name: new_cases, dtype: float64
133087 133094    1214.0
Name: new_cases, dtype: float64
133088 133095    1394.0
Name: new_cases, dtype: float64
133089 133096    0.0
Name: new_cases, dtype: float64
133090 133097    0.0
Name: new_cases, dtype: float64
133091 133098    0.0
Name: new_cases, dtype: float64
133092 133099    2924.0
Name: new_cases, dtype: float64
133093 133100    1711.0
Name: new_cases, dtype: float64
133094 133101    1375.0
Name: new_cases, dtype: float64
133095 133102    1482.0
Name: new_cases, dtype: float64
133096 133103    0.0
Name: new_cases, dtype: float64
133097 133104    0.0
Name: new_cases, dtype: float64
133098 133105    0.0
Name: new_cases, dtype: float64
133099 133106    3656.0
Name: new_cases, dtype: float64
133100 133107    1097.0
Name: new_cases, dtype: float64
133101 133108    1203.0
Name: new_cases, dtype: float64
133102 133109    1009.0
Name: new_cases, dtype: float64
133103 133110    0.0
Name: new_cases, dtype: float64
133104 133111    0.0
Name: new_cases, dtype: float64
133105 133112    0.0
Name: new_cases, dtype: float64
133106 133113    1986.0
Name: new_cases, dtype: float64
133107 133114    911.0
Name: new_cases, dtype: float64
133108 133115    762.0
Name: new_cases, dtype: float64
133109 133116    766.0
Name: new_cases, dtype: float64
133110 133117    0.0
Name: new_cases, dtype: float64
133111 133118    0.0
Name: new_cases, dtype: float64
133112 133119    0.0
Name: new_cases, dtype: float64
133113 133120    1766.0
Name: new_cases, dtype: float64
133114 133121    854.0
Name: new_cases, dtype: float64
133115 133122    859.0
Name: new_cases, dtype: float64
133116 133123    769.0
Name: new_cases, dtype: float64
133117 133124    0.0
Name: new_cases, dtype: float64
133118 133125    0.0
Name: new_cases, dtype: float64
133119 133126    0.0
Name: new_cases, dtype: float64
133120 133127    1879.0
Name: new_cases, dtype: float64
133121 133128    714.0
Name: new_cases, dtype: float64
133122 133129    835.0
Name: new_cases, dtype: float64
133123 133130    739.0
Name: new_cases, dtype: float64
133124 133131    0.0
Name: new_cases, dtype: float64
133125 133132    0.0
Name: new_cases, dtype: float64
133126 133133    0.0
Name: new_cases, dtype: float64

133127 133134    1738.0
Name: new_cases, dtype: float64
133128 133135    905.0
Name: new_cases, dtype: float64
133129 133136    799.0
Name: new_cases, dtype: float64
133130 133137    669.0
Name: new_cases, dtype: float64
133131 133138    0.0
Name: new_cases, dtype: float64
133132 133139    0.0
Name: new_cases, dtype: float64
133133 133140    0.0
Name: new_cases, dtype: float64
133134 133141    1662.0
Name: new_cases, dtype: float64
133135 133142    807.0
Name: new_cases, dtype: float64
133136 133143    792.0
Name: new_cases, dtype: float64
133137 133144    802.0
Name: new_cases, dtype: float64
133138 133145    0.0
Name: new_cases, dtype: float64
133139 133146    0.0
Name: new_cases, dtype: float64
133140 133147    0.0
Name: new_cases, dtype: float64
133141 133148    2275.0
Name: new_cases, dtype: float64
133142 133149    1259.0
Name: new_cases, dtype: float64
133143 133150    892.0
Name: new_cases, dtype: float64
133144 133151    1090.0
Name: new_cases, dtype: float64
133145 133152    0.0
Name: new_cases, dtype: float64
133146 133153    0.0
Name: new_cases, dtype: float64
133147 133154    0.0
Name: new_cases, dtype: float64
133148 133155    2761.0
Name: new_cases, dtype: float64
133149 133156    1152.0
Name: new_cases, dtype: float64
133150 133157    844.0
Name: new_cases, dtype: float64
133151 133158    825.0
Name: new_cases, dtype: float64
133152 133159    0.0
Name: new_cases, dtype: float64
133153 133160    0.0
Name: new_cases, dtype: float64
133154 133161    0.0
Name: new_cases, dtype: float64
133155 133162    2098.0
Name: new_cases, dtype: float64
133156 133163    1326.0
Name: new_cases, dtype: float64
133157 133164    1014.0
Name: new_cases, dtype: float64
133158 133165    939.0
Name: new_cases, dtype: float64
133159 133166    0.0
Name: new_cases, dtype: float64
133160 133167    0.0
Name: new_cases, dtype: float64
133161 133168    0.0
Name: new_cases, dtype: float64
133162 133169    2622.0
Name: new_cases, dtype: float64
133163 133170    1294.0
Name: new_cases, dtype: float64
133164 133171    1220.0
Name: new_cases, dtype: float64
133165 133172    1128.0
Name: new_cases, dtype: float64
133166 133173    0.0
Name: new_cases, dtype: float64
133167 133174    0.0
Name: new_cases, dtype: float64
133168 133175    0.0
Name: new_cases, dtype: float64
133169 133176    3825.0
Name: new_cases, dtype: float64
133170 133177    2076.0
Name: new_cases, dtype: float64
133171 133178    2052.0
Name: new_cases, dtype: float64
133172 133179    2160.0
Name: new_cases, dtype: float64
133173 133180    0.0
Name: new_cases, dtype: float64
133174 133181    0.0
Name: new_cases, dtype: float64
133175 133182    0.0
Name: new_cases, dtype: float64
133176 133183    6011.0
Name: new_cases, dtype: float64
133177 133184    2639.0
Name: new_cases, dtype: float64
133178 133185    2437.0
Name: new_cases, dtype: float64
133179 133186    2210.0
Name: new_cases, dtype: float64
133180 133187    0.0
Name: new_cases, dtype: float64
133181 133188    0.0
Name: new_cases, dtype: float64
133182 133189    0.0
Name: new_cases, dtype: float64
133183 133190    7412.0
Name: new_cases, dtype: float64
133184 133191    3335.0
Name: new_cases, dtype: float64
133185 133192    3163.0
Name: new_cases, dtype: float64
133186 133193    3162.0
Name: new_cases, dtype: float64
133187 133194    0.0
Name: new_cases, dtype: float64
133188 133195    0.0
Name: new_cases, dtype: float64
133189 133196    0.0
Name: new_cases, dtype: float64
133190 133197    9472.0
Name: new_cases, dtype: float64
133191 133198    4044.0
Name: new_cases, dtype: float64
133192 133199    4022.0
Name: new_cases, dtype: float64
133193 133200    4130.0
Name: new_cases, dtype: float64
133194 133201    0.0
Name: new_cases, dtype: float64
133195 133202    0.0
Name: new_cases, dtype: float64
133196 133203    0.0
Name: new_cases, dtype: float64
133197 133204    12681.0
Name: new_cases, dtype: float64
133198 133205    4688.0
Name: new_cases, dtype: float64
133199 133206    5059.0
Name: new_cases, dtype: float64
133200 133207    0.0
Name: new_cases, dtype: float64
133201 133208    0.0
Name: new_cases, dtype: float64
133202 133209    0.0
Name: new_cases, dtype: float64
133203 133210    0.0
Name: new_cases, dtype: float64
133204 133211    21247.0
Name: new_cases, dtype: float64
133205 133212    9103.0
Name: new_cases, dtype: float64
133206 133213    11121.0
Name: new_cases, dtype: float64
133207 133214    0.0
Name: new_cases, dtype: float64
133208 133215    0.0
Name: new_cases, dtype: float64
133209 133216    0.0
Name: new_cases, dtype: float64
133210 133217    0.0
Name: new_cases, dtype: float64
133211 133218    42969.0
Name: new_cases, dtype: float64
133212 133219    17514.0
Name: new_cases, dtype: float64
133213 133220    0.0
Name: new_cases, dtype: float64
133214 133221    41383.0
Name: new_cases, dtype: float64
133215 132539    0.0
Name: new_cases, dtype: float64
133216 132540    1.0
Name: new_cases, dtype: float64
133217 132541    1.0
Name: new_cases, dtype: float64
133218 132542    8.0
Name: new_cases, dtype: float64
133219 132543    3.0
Name: new_cases, dtype: float64
133220 132544    0.0
Name: new_cases, dtype: float64
133221 132545    5.0
Name: new_cases, dtype: float64
133223 133230    14.0
Name: new_cases, dtype: float64
133224 133231    34.0
Name: new_cases, dtype: float64
133225 133232    24.0
Name: new_cases, dtype: float64
133226 133233    100.0
Name: new_cases, dtype: float64
133227 133234    54.0
Name: new_cases, dtype: float64
133228 133235    69.0
Name: new_cases, dtype: float64
133229 133236    37.0
Name: new_cases, dtype: float64
133230 133237    117.0
Name: new_cases, dtype: float64
133231 133238    161.0
Name: new_cases, dtype: float64
133232 133239    0.0
Name: new_cases, dtype: float64
133233 133240    487.0
Name: new_cases, dtype: float64
133234 133241    220.0
Name: new_cases, dtype: float64
133235 133242    841.0
Name: new_cases, dtype: float64
133236 133243    0.0
Name: new_cases, dtype: float64
133237 133244    500.0
Name: new_cases, dtype: float64
133238 133245    328.0
Name: new_cases, dtype: float64
133239 133246    1047.0
Name: new_cases, dtype: float64
133240 133247    1219.0
Name: new_cases, dtype: float64
133241 133248    1281.0
Name: new_cases, dtype: float64
133242 133249    899.0
Name: new_cases, dtype: float64
133243 133250    1321.0
Name: new_cases, dtype: float64
133244 133251    1082.0
Name: new_cases, dtype: float64
133245 133252    1020.0
Name: new_cases, dtype: float64
133246 133253    914.0
Name: new_cases, dtype: float64
133247 133254    1117.0
Name: new_cases, dtype: float64
133248 133255    1148.0
Name: new_cases, dtype: float64
133249 133256    753.0
Name: new_cases, dtype: float64
133250 133257    1093.0
Name: new_cases, dtype: float64
133251 133258    683.0
Name: new_cases, dtype: float64
133252 133259    1163.0
Name: new_cases, dtype: float64
133253 133260    1059.0
Name: new_cases, dtype: float64
133254 133261    779.0
Name: new_cases, dtype: float64
133255 133262    899.0
Name: new_cases, dtype: float64
133256 133263    595.0
Name: new_cases, dtype: float64
133257 133264    557.0
Name: new_cases, dtype: float64
133258 133265    596.0
Name: new_cases, dtype: float64
133259 133266    1027.0
Name: new_cases, dtype: float64
133260 133267    771.0
Name: new_cases, dtype: float64
133261 133268    500.0
Name: new_cases, dtype: float64
133262 133269    556.0
Name: new_cases, dtype: float64
133263 133270    308.0
Name: new_cases, dtype: float64
133264 133271    273.0
Name: new_cases, dtype: float64
133265 133272    248.0
Name: new_cases, dtype: float64
133266 133273    400.0
Name: new_cases, dtype: float64
133267 133274    396.0
Name: new_cases, dtype: float64
133268 133275    346.0
Name: new_cases, dtype: float64
133269 133276    326.0
Name: new_cases, dtype: float64
133270 133277    336.0
Name: new_cases, dtype: float64
133271 133278    204.0
Name: new_cases, dtype: float64
133272 133279    119.0
Name: new_cases, dtype: float64
133273 133280    205.0
Name: new_cases, dtype: float64
133274 133281    228.0
Name: new_cases, dtype: float64
133275 133282    181.0
Name: new_cases, dtype: float64
133276 133283    217.0
Name: new_cases, dtype: float64
133277 133284    167.0
Name: new_cases, dtype: float64
133278 133285    103.0
Name: new_cases, dtype: float64
133279 133286    100.0
Name: new_cases, dtype: float64
133280 133287    143.0
Name: new_cases, dtype: float64
133281 133288    179.0
Name: new_cases, dtype: float64
133282 133289    119.0
Name: new_cases, dtype: float64
133283 133290    112.0
Name: new_cases, dtype: float64
133284 133291    88.0
Name: new_cases, dtype: float64

133285 133292    76.0
Name: new_cases, dtype: float64
133286 133293    28.0
Name: new_cases, dtype: float64
133287 133294    51.0
Name: new_cases, dtype: float64
133288 133295    66.0
Name: new_cases, dtype: float64
133289 133296    81.0
Name: new_cases, dtype: float64
133290 133297    44.0
Name: new_cases, dtype: float64
133291 133298    54.0
Name: new_cases, dtype: float64
133292 133299    39.0
Name: new_cases, dtype: float64
133293 133300    36.0
Name: new_cases, dtype: float64
133294 133301    33.0
Name: new_cases, dtype: float64
133295 133302    50.0
Name: new_cases, dtype: float64
133296 133303    51.0
Name: new_cases, dtype: float64
133297 133304    58.0
Name: new_cases, dtype: float64
133298 133305    15.0
Name: new_cases, dtype: float64
133299 133306    10.0
Name: new_cases, dtype: float64
133300 133307    21.0
Name: new_cases, dtype: float64
133301 133308    40.0
Name: new_cases, dtype: float64
133302 133309    36.0
Name: new_cases, dtype: float64
133303 133310    13.0
Name: new_cases, dtype: float64
133304 133311    18.0
Name: new_cases, dtype: float64
133305 133312    11.0
Name: new_cases, dtype: float64
133306 133313    10.0
Name: new_cases, dtype: float64
133307 133314    15.0
Name: new_cases, dtype: float64
133308 133315    15.0
Name: new_cases, dtype: float64
133309 133316    20.0
Name: new_cases, dtype: float64
133310 133317    32.0
Name: new_cases, dtype: float64
133311 133318    17.0
Name: new_cases, dtype: float64
133312 133319    17.0
Name: new_cases, dtype: float64
133313 133320    9.0
Name: new_cases, dtype: float64
133314 133321    3.0
Name: new_cases, dtype: float64
133315 133322    19.0
Name: new_cases, dtype: float64
133316 133323    20.0
Name: new_cases, dtype: float64
133317 133324    23.0
Name: new_cases, dtype: float64
133318 133325    20.0
Name: new_cases, dtype: float64
133319 133326    9.0
Name: new_cases, dtype: float64
133320 133327    7.0
Name: new_cases, dtype: float64
133321 133328    16.0
Name: new_cases, dtype: float64
133322 133329    23.0
Name: new_cases, dtype: float64
133323 133330    33.0
Name: new_cases, dtype: float64
133324 133331    19.0
Name: new_cases, dtype: float64
133325 133332    31.0
Name: new_cases, dtype: float64
133326 133333    23.0
Name: new_cases, dtype: float64
133327 133334    14.0
Name: new_cases, dtype: float64
133328 133335    23.0
Name: new_cases, dtype: float64
133329 133336    33.0
Name: new_cases, dtype: float64
133330 133337    13.0
Name: new_cases, dtype: float64
133331 133338    35.0
Name: new_cases, dtype: float64
133332 133339    8.0
Name: new_cases, dtype: float64
133333 133340    49.0
Name: new_cases, dtype: float64
133334 133341    18.0
Name: new_cases, dtype: float64
133335 133342    22.0
Name: new_cases, dtype: float64
133336 133343    44.0
Name: new_cases, dtype: float64
133337 133344    52.0
Name: new_cases, dtype: float64
133338 133345    58.0
Name: new_cases, dtype: float64
133339 133346    69.0
Name: new_cases, dtype: float64
133340 133347    62.0
Name: new_cases, dtype: float64
133341 133348    35.0
Name: new_cases, dtype: float64
133342 133349    62.0
Name: new_cases, dtype: float64
133343 133350    137.0
Name: new_cases, dtype: float64
133344 133351    116.0
Name: new_cases, dtype: float64
133345 133352    134.0
Name: new_cases, dtype: float64
133346 133353    97.0
Name: new_cases, dtype: float64
133347 133354    70.0
Name: new_cases, dtype: float64
133348 133355    47.0
Name: new_cases, dtype: float64
133349 133356    54.0
Name: new_cases, dtype: float64
133350 133357    129.0
Name: new_cases, dtype: float64
133351 133358    88.0
Name: new_cases, dtype: float64
133352 133359    104.0
Name: new_cases, dtype: float64
133353 133360    127.0
Name: new_cases, dtype: float64
133354 133361    66.0
Name: new_cases, dtype: float64
133355 133362    63.0
Name: new_cases, dtype: float64
133356 133363    70.0
Name: new_cases, dtype: float64
133357 133364    132.0
Name: new_cases, dtype: float64
133358 133365    142.0
Name: new_cases, dtype: float64
133359 133366    92.0
Name: new_cases, dtype: float64
133360 133367    110.0
Name: new_cases, dtype: float64
133361 133368    99.0
Name: new_cases, dtype: float64
133362 133369    43.0
Name: new_cases, dtype: float64
133363 133370    108.0
Name: new_cases, dtype: float64
133364 133371    141.0
Name: new_cases, dtype: float64
133365 133372    117.0
Name: new_cases, dtype: float64
133366 133373    154.0
Name: new_cases, dtype: float64
133367 133374    148.0
Name: new_cases, dtype: float64
133368 133375    110.0
Name: new_cases, dtype: float64
133369 133376    65.0
Name: new_cases, dtype: float64
133370 133377    132.0
Name: new_cases, dtype: float64
133371 133378    193.0
Name: new_cases, dtype: float64
133372 133379    220.0
Name: new_cases, dtype: float64
133373 133380    210.0
Name: new_cases, dtype: float64
133374 133381    180.0
Name: new_cases, dtype: float64
133375 133382    138.0
Name: new_cases, dtype: float64
133376 133383    66.0
Name: new_cases, dtype: float64
133377 133384    130.0
Name: new_cases, dtype: float64
133378 133385    181.0
Name: new_cases, dtype: float64
133379 133386    181.0
Name: new_cases, dtype: float64
133380 133387    161.0
Name: new_cases, dtype: float64
133381 133388    182.0
Name: new_cases, dtype: float64
133382 133389    152.0
Name: new_cases, dtype: float64
133383 133390    105.0
Name: new_cases, dtype: float64
133384 133391    187.0
Name: new_cases, dtype: float64
133385 133392    274.0
Name: new_cases, dtype: float64
133386 133393    234.0
Name: new_cases, dtype: float64
133387 133394    268.0
Name: new_cases, dtype: float64
133388 133395    253.0
Name: new_cases, dtype: float64
133389 133396    200.0
Name: new_cases, dtype: float64
133390 133397    128.0
Name: new_cases, dtype: float64
133391 133398    197.0
Name: new_cases, dtype: float64
133392 133399    311.0
Name: new_cases, dtype: float64
133393 133400    266.0
Name: new_cases, dtype: float64
133394 133401    306.0
Name: new_cases, dtype: float64
133395 133402    295.0
Name: new_cases, dtype: float64
133396 133403    276.0
Name: new_cases, dtype: float64
133397 133404    157.0
Name: new_cases, dtype: float64
133398 133405    202.0
Name: new_cases, dtype: float64
133399 133406    383.0
Name: new_cases, dtype: float64
133400 133407    361.0
Name: new_cases, dtype: float64
133401 133408    340.0
Name: new_cases, dtype: float64
133402 133409    376.0
Name: new_cases, dtype: float64
133403 133410    292.0
Name: new_cases, dtype: float64
133404 133411    163.0
Name: new_cases, dtype: float64
133405 133412    216.0
Name: new_cases, dtype: float64
133406 133413    370.0
Name: new_cases, dtype: float64
133407 133414    364.0
Name: new_cases, dtype: float64
133408 133415    405.0
Name: new_cases, dtype: float64
133409 133416    425.0
Name: new_cases, dtype: float64
133410 133417    444.0
Name: new_cases, dtype: float64
133411 133418    191.0
Name: new_cases, dtype: float64
133412 133419    245.0
Name: new_cases, dtype: float64
133413 133420    469.0
Name: new_cases, dtype: float64
133414 133421    405.0
Name: new_cases, dtype: float64
133415 133422    528.0
Name: new_cases, dtype: float64
133416 133423    465.0
Name: new_cases, dtype: float64
133417 133424    475.0
Name: new_cases, dtype: float64
133418 133425    257.0
Name: new_cases, dtype: float64
133419 133426    315.0
Name: new_cases, dtype: float64
133420 133427    514.0
Name: new_cases, dtype: float64
133421 133428    530.0
Name: new_cases, dtype: float64
133422 133429    488.0
Name: new_cases, dtype: float64
133423 133430    0.0
Name: new_cases, dtype: float64
133424 133431    0.0
Name: new_cases, dtype: float64
133425 133432    1095.0
Name: new_cases, dtype: float64
133426 133433    286.0
Name: new_cases, dtype: float64
133427 133434    437.0
Name: new_cases, dtype: float64
133428 133435    391.0
Name: new_cases, dtype: float64
133429 133436    372.0
Name: new_cases, dtype: float64
133430 133437    0.0
Name: new_cases, dtype: float64
133431 133438    0.0
Name: new_cases, dtype: float64
133432 133439    782.0
Name: new_cases, dtype: float64
133433 133440    225.0
Name: new_cases, dtype: float64
133434 133441    411.0
Name: new_cases, dtype: float64
133435 133442    550.0
Name: new_cases, dtype: float64
133436 133443    552.0
Name: new_cases, dtype: float64
133437 133444    0.0
Name: new_cases, dtype: float64
133438 133445    0.0
Name: new_cases, dtype: float64
133439 133446    1548.0
Name: new_cases, dtype: float64
133440 133447    700.0
Name: new_cases, dtype: float64
133441 133448    1077.0
Name: new_cases, dtype: float64
133442 133449    1172.0
Name: new_cases, dtype: float64
133443 133450    1487.0
Name: new_cases, dtype: float64
133444 133451    0.0
Name: new_cases, dtype: float64
133445 133452    0.0
Name: new_cases, dtype: float64
133446 133453    4068.0
Name: new_cases, dtype: float64

133447 133454    1445.0
Name: new_cases, dtype: float64
133448 133455    2823.0
Name: new_cases, dtype: float64
133449 133456    2613.0
Name: new_cases, dtype: float64
133450 133457    3105.0
Name: new_cases, dtype: float64
133451 133458    0.0
Name: new_cases, dtype: float64
133452 133459    0.0
Name: new_cases, dtype: float64
133453 133460    8737.0
Name: new_cases, dtype: float64
133454 133461    3008.0
Name: new_cases, dtype: float64
133455 133462    5596.0
Name: new_cases, dtype: float64
133456 133463    5256.0
Name: new_cases, dtype: float64
133457 133464    6634.0
Name: new_cases, dtype: float64
133458 133465    0.0
Name: new_cases, dtype: float64
133459 133466    0.0
Name: new_cases, dtype: float64
133460 133467    17440.0
Name: new_cases, dtype: float64
133461 133468    5949.0
Name: new_cases, dtype: float64
133462 133469    8616.0
Name: new_cases, dtype: float64
133463 133470    9386.0
Name: new_cases, dtype: float64
133464 133471    9207.0
Name: new_cases, dtype: float64
133465 133472    0.0
Name: new_cases, dtype: float64
133466 133473    0.0
Name: new_cases, dtype: float64
133467 133474    21926.0
Name: new_cases, dtype: float64
133468 133475    6126.0
Name: new_cases, dtype: float64
133469 133476    10073.0
Name: new_cases, dtype: float64
133470 133477    10128.0
Name: new_cases, dtype: float64
133471 133478    9409.0
Name: new_cases, dtype: float64
133472 133479    0.0
Name: new_cases, dtype: float64
133473 133480    0.0
Name: new_cases, dtype: float64
133474 133481    17309.0
Name: new_cases, dtype: float64
133475 133482    5980.0
Name: new_cases, dtype: float64
133476 133483    8270.0
Name: new_cases, dtype: float64
133477 133484    6924.0
Name: new_cases, dtype: float64
133478 133485    6739.0
Name: new_cases, dtype: float64
133479 133486    0.0
Name: new_cases, dtype: float64
133480 133487    0.0
Name: new_cases, dtype: float64
133481 133488    12839.0
Name: new_cases, dtype: float64
133482 133489    4560.0
Name: new_cases, dtype: float64
133483 133490    6114.0
Name: new_cases, dtype: float64
133484 133491    5007.0
Name: new_cases, dtype: float64
133485 133492    4946.0
Name: new_cases, dtype: float64
133486 133493    0.0
Name: new_cases, dtype: float64
133487 133494    0.0
Name: new_cases, dtype: float64
133488 133495    9751.0
Name: new_cases, dtype: float64
133489 133496    4241.0
Name: new_cases, dtype: float64
133490 133497    4876.0
Name: new_cases, dtype: float64
133491 133498    4509.0
Name: new_cases, dtype: float64
133492 133499    4312.0
Name: new_cases, dtype: float64
133493 133500    0.0
Name: new_cases, dtype: float64
133494 133501    0.0
Name: new_cases, dtype: float64
133495 133502    8782.0
Name: new_cases, dtype: float64
133496 133503    3802.0
Name: new_cases, dtype: float64
133497 133504    4786.0
Name: new_cases, dtype: float64
133498 133505    4455.0
Name: new_cases, dtype: float64
133499 133506    4382.0
Name: new_cases, dtype: float64
133500 133507    0.0
Name: new_cases, dtype: float64
133501 133508    0.0
Name: new_cases, dtype: float64
133502 133509    9809.0
Name: new_cases, dtype: float64
133503 133510    4262.0
Name: new_cases, dtype: float64
133504 133511    5086.0
Name: new_cases, dtype: float64
133505 133512    5041.0
Name: new_cases, dtype: float64
133506 133513    5136.0
Name: new_cases, dtype: float64
133507 133514    0.0
Name: new_cases, dtype: float64
133508 133515    0.0
Name: new_cases, dtype: float64
133509 133516    10726.0
Name: new_cases, dtype: float64
133510 133517    4271.0
Name: new_cases, dtype: float64
133511 133518    5625.0
Name: new_cases, dtype: float64
133512 133519    5058.0
Name: new_cases, dtype: float64
133513 133520    4478.0
Name: new_cases, dtype: float64
133514 133521    0.0
Name: new_cases, dtype: float64
133515 133522    0.0
Name: new_cases, dtype: float64
133516 133523    10002.0
Name: new_cases, dtype: float64
133517 133524    4275.0
Name: new_cases, dtype: float64
133518 133525    5033.0
Name: new_cases, dtype: float64
133519 133526    4898.0
Name: new_cases, dtype: float64
133520 133527    0.0
Name: new_cases, dtype: float64
133521 133528    0.0
Name: new_cases, dtype: float64
133522 133529    0.0
Name: new_cases, dtype: float64
133523 133530    10087.0
Name: new_cases, dtype: float64
133524 133531    4197.0
Name: new_cases, dtype: float64
133525 133532    5424.0
Name: new_cases, dtype: float64
133526 133533    4391.0
Name: new_cases, dtype: float64
133527 133534    0.0
Name: new_cases, dtype: float64
133528 133535    0.0
Name: new_cases, dtype: float64
133529 133536    0.0
Name: new_cases, dtype: float64
133530 133537    9665.0
Name: new_cases, dtype: float64
133531 133538    4020.0
Name: new_cases, dtype: float64
133532 133539    4808.0
Name: new_cases, dtype: float64
133533 133540    3975.0
Name: new_cases, dtype: float64
133534 133541    3219.0
Name: new_cases, dtype: float64
133535 133542    0.0
Name: new_cases, dtype: float64
133536 133543    0.0
Name: new_cases, dtype: float64
133537 133544    6523.0
Name: new_cases, dtype: float64
133538 133545    2851.0
Name: new_cases, dtype: float64
133539 133546    3001.0
Name: new_cases, dtype: float64
133540 133547    2474.0
Name: new_cases, dtype: float64
133541 133548    2396.0
Name: new_cases, dtype: float64
133542 133549    0.0
Name: new_cases, dtype: float64
133543 133550    0.0
Name: new_cases, dtype: float64
133544 133551    4703.0
Name: new_cases, dtype: float64
133545 133552    2260.0
Name: new_cases, dtype: float64
133546 133553    2727.0
Name: new_cases, dtype: float64
133547 133554    2205.0
Name: new_cases, dtype: float64
133548 133555    2156.0
Name: new_cases, dtype: float64
133549 133556    0.0
Name: new_cases, dtype: float64
133550 133557    0.0
Name: new_cases, dtype: float64
133551 133558    4320.0
Name: new_cases, dtype: float64
133552 133559    1884.0
Name: new_cases, dtype: float64
133553 133560    2222.0
Name: new_cases, dtype: float64
133554 133561    1699.0
Name: new_cases, dtype: float64
133555 133562    1916.0
Name: new_cases, dtype: float64
133556 133563    0.0
Name: new_cases, dtype: float64
133557 133564    0.0
Name: new_cases, dtype: float64
133558 133565    3775.0
Name: new_cases, dtype: float64
133559 133566    1633.0
Name: new_cases, dtype: float64
133560 133567    1796.0
Name: new_cases, dtype: float64
133561 133568    1765.0
Name: new_cases, dtype: float64
133562 133569    1584.0
Name: new_cases, dtype: float64
133563 133570    0.0
Name: new_cases, dtype: float64
133564 133571    0.0
Name: new_cases, dtype: float64
133565 133572    3280.0
Name: new_cases, dtype: float64
133566 133573    1363.0
Name: new_cases, dtype: float64
133567 133574    1602.0
Name: new_cases, dtype: float64
133568 133575    1356.0
Name: new_cases, dtype: float64
133569 133576    1253.0
Name: new_cases, dtype: float64
133570 133577    0.0
Name: new_cases, dtype: float64
133571 133578    0.0
Name: new_cases, dtype: float64
133572 133579    2480.0
Name: new_cases, dtype: float64
133573 133580    1075.0
Name: new_cases, dtype: float64
133574 133581    1253.0
Name: new_cases, dtype: float64
133575 133582    1219.0
Name: new_cases, dtype: float64
133576 133583    1021.0
Name: new_cases, dtype: float64
133577 133584    0.0
Name: new_cases, dtype: float64
133578 133585    0.0
Name: new_cases, dtype: float64
133579 133586    2449.0
Name: new_cases, dtype: float64
133580 133587    1131.0
Name: new_cases, dtype: float64
133581 133588    1343.0
Name: new_cases, dtype: float64
133582 133589    1169.0
Name: new_cases, dtype: float64
133583 133590    1065.0
Name: new_cases, dtype: float64
133584 133591    0.0
Name: new_cases, dtype: float64
133585 133592    0.0
Name: new_cases, dtype: float64
133586 133593    2560.0
Name: new_cases, dtype: float64
133587 133594    1130.0
Name: new_cases, dtype: float64
133588 133595    1223.0
Name: new_cases, dtype: float64
133589 133596    1223.0
Name: new_cases, dtype: float64
133590 133597    1222.0
Name: new_cases, dtype: float64
133591 133598    0.0
Name: new_cases, dtype: float64
133592 133599    0.0
Name: new_cases, dtype: float64
133593 133600    2744.0
Name: new_cases, dtype: float64
133594 133601    1378.0
Name: new_cases, dtype: float64
133595 133602    1491.0
Name: new_cases, dtype: float64
133596 133603    1409.0
Name: new_cases, dtype: float64
133597 133604    1333.0
Name: new_cases, dtype: float64
133598 133605    0.0
Name: new_cases, dtype: float64
133599 133606    0.0
Name: new_cases, dtype: float64
133600 133607    3170.0
Name: new_cases, dtype: float64
133601 133608    1438.0
Name: new_cases, dtype: float64
133602 133609    1858.0
Name: new_cases, dtype: float64
133603 133610    1750.0
Name: new_cases, dtype: float64
133604 133611    1748.0
Name: new_cases, dtype: float64
133605 133612    0.0
Name: new_cases, dtype: float64
133606 133613    0.0
Name: new_cases, dtype: float64
133607 133614    3643.0
Name: new_cases, dtype: float64
133608 133615    1844.0
Name: new_cases, dtype: float64
133609 133616    2022.0
Name: new_cases, dtype: float64
133610 133617    2046.0
Name: new_cases, dtype: float64

133611 133618    2053.0
Name: new_cases, dtype: float64
133612 133619    0.0
Name: new_cases, dtype: float64
133613 133620    0.0
Name: new_cases, dtype: float64
133614 133621    4573.0
Name: new_cases, dtype: float64
133615 133622    1923.0
Name: new_cases, dtype: float64
133616 133623    2411.0
Name: new_cases, dtype: float64
133617 133624    1968.0
Name: new_cases, dtype: float64
133618 133625    2250.0
Name: new_cases, dtype: float64
133619 133626    0.0
Name: new_cases, dtype: float64
133620 133627    0.0
Name: new_cases, dtype: float64
133621 133628    0.0
Name: new_cases, dtype: float64
133622 133629    4932.0
Name: new_cases, dtype: float64
133623 133630    2301.0
Name: new_cases, dtype: float64
133624 133631    2449.0
Name: new_cases, dtype: float64
133625 133632    2519.0
Name: new_cases, dtype: float64
133626 133633    0.0
Name: new_cases, dtype: float64
133627 133634    0.0
Name: new_cases, dtype: float64
133628 133635    5583.0
Name: new_cases, dtype: float64
133629 133636    2241.0
Name: new_cases, dtype: float64
133630 133637    2601.0
Name: new_cases, dtype: float64
133631 133638    2226.0
Name: new_cases, dtype: float64
133632 133639    2205.0
Name: new_cases, dtype: float64
133633 133640    0.0
Name: new_cases, dtype: float64
133634 133641    0.0
Name: new_cases, dtype: float64
133635 133642    4905.0
Name: new_cases, dtype: float64
133636 133643    2141.0
Name: new_cases, dtype: float64
133637 133644    2686.0
Name: new_cases, dtype: float64
133638 133645    2265.0
Name: new_cases, dtype: float64
133639 133646    2113.0
Name: new_cases, dtype: float64
133640 133647    0.0
Name: new_cases, dtype: float64
133641 133648    0.0
Name: new_cases, dtype: float64
133642 133649    5313.0
Name: new_cases, dtype: float64
133643 133650    2135.0
Name: new_cases, dtype: float64
133644 133651    2120.0
Name: new_cases, dtype: float64
133645 133652    2066.0
Name: new_cases, dtype: float64
133646 133653    1831.0
Name: new_cases, dtype: float64
133647 133654    0.0
Name: new_cases, dtype: float64
133648 133655    0.0
Name: new_cases, dtype: float64
133649 133656    3978.0
Name: new_cases, dtype: float64
133650 133657    1633.0
Name: new_cases, dtype: float64
133651 133658    1795.0
Name: new_cases, dtype: float64
133652 133659    1687.0
Name: new_cases, dtype: float64
133653 133660    1546.0
Name: new_cases, dtype: float64
133654 133661    0.0
Name: new_cases, dtype: float64
133655 133662    0.0
Name: new_cases, dtype: float64
133656 133663    3683.0
Name: new_cases, dtype: float64
133657 133664    1375.0
Name: new_cases, dtype: float64
133658 133665    1539.0
Name: new_cases, dtype: float64
133659 133666    0.0
Name: new_cases, dtype: float64
133660 133667    2300.0
Name: new_cases, dtype: float64
133661 133668    0.0
Name: new_cases, dtype: float64
133662 133669    0.0
Name: new_cases, dtype: float64
133663 133670    2650.0
Name: new_cases, dtype: float64
133664 133671    1240.0
Name: new_cases, dtype: float64
133665 133672    1554.0
Name: new_cases, dtype: float64
133666 133673    1198.0
Name: new_cases, dtype: float64
133667 133674    0.0
Name: new_cases, dtype: float64
133668 133675    1201.0
Name: new_cases, dtype: float64
133669 133676    0.0
Name: new_cases, dtype: float64
133670 133677    0.0
Name: new_cases, dtype: float64
133671 133678    2770.0
Name: new_cases, dtype: float64
133672 133679    996.0
Name: new_cases, dtype: float64
133673 133680    992.0
Name: new_cases, dtype: float64
133674 133681    912.0
Name: new_cases, dtype: float64
133675 133682    0.0
Name: new_cases, dtype: float64
133676 133683    0.0
Name: new_cases, dtype: float64
133677 133684    1717.0
Name: new_cases, dtype: float64
133678 133685    756.0
Name: new_cases, dtype: float64
133679 133686    717.0
Name: new_cases, dtype: float64
133680 133687    588.0
Name: new_cases, dtype: float64
133681 133688    491.0
Name: new_cases, dtype: float64
133682 133689    0.0
Name: new_cases, dtype: float64
133683 133690    0.0
Name: new_cases, dtype: float64
133684 133691    1077.0
Name: new_cases, dtype: float64
133685 133692    429.0
Name: new_cases, dtype: float64
133686 133693    0.0
Name: new_cases, dtype: float64
133687 133694    899.0
Name: new_cases, dtype: float64
133688 133695    354.0
Name: new_cases, dtype: float64
133689 133696    0.0
Name: new_cases, dtype: float64
133690 133697    0.0
Name: new_cases, dtype: float64
133691 133698    684.0
Name: new_cases, dtype: float64
133692 133699    243.0
Name: new_cases, dtype: float64
133693 133700    282.0
Name: new_cases, dtype: float64
133694 133701    194.0
Name: new_cases, dtype: float64
133695 133702    173.0
Name: new_cases, dtype: float64
133696 133703    0.0
Name: new_cases, dtype: float64
133697 133704    0.0
Name: new_cases, dtype: float64
133698 133705    367.0
Name: new_cases, dtype: float64
133699 133706    130.0
Name: new_cases, dtype: float64
133700 133707    154.0
Name: new_cases, dtype: float64
133701 133708    120.0
Name: new_cases, dtype: float64
133702 133709    109.0
Name: new_cases, dtype: float64
133703 133710    0.0
Name: new_cases, dtype: float64
133704 133711    0.0
Name: new_cases, dtype: float64
133705 133712    239.0
Name: new_cases, dtype: float64
133706 133713    129.0
Name: new_cases, dtype: float64
133707 133714    129.0
Name: new_cases, dtype: float64
133708 133715    172.0
Name: new_cases, dtype: float64
133709 133716    158.0
Name: new_cases, dtype: float64
133710 133717    0.0
Name: new_cases, dtype: float64
133711 133718    0.0
Name: new_cases, dtype: float64
133712 133719    449.0
Name: new_cases, dtype: float64
133713 133720    274.0
Name: new_cases, dtype: float64
133714 133721    295.0
Name: new_cases, dtype: float64
133715 133722    268.0
Name: new_cases, dtype: float64
133716 133723    323.0
Name: new_cases, dtype: float64
133717 133724    0.0
Name: new_cases, dtype: float64
133718 133725    0.0
Name: new_cases, dtype: float64
133719 133726    822.0
Name: new_cases, dtype: float64
133720 133727    483.0
Name: new_cases, dtype: float64
133721 133728    527.0
Name: new_cases, dtype: float64
133722 133729    582.0
Name: new_cases, dtype: float64
133723 133730    0.0
Name: new_cases, dtype: float64
133724 133731    619.0
Name: new_cases, dtype: float64
133725 133732    0.0
Name: new_cases, dtype: float64
133726 133733    1560.0
Name: new_cases, dtype: float64
133727 133734    707.0
Name: new_cases, dtype: float64
133728 133735    773.0
Name: new_cases, dtype: float64
133729 133736    861.0
Name: new_cases, dtype: float64
133730 133737    791.0
Name: new_cases, dtype: float64
133731 133738    0.0
Name: new_cases, dtype: float64
133732 133739    0.0
Name: new_cases, dtype: float64
133733 133740    1746.0
Name: new_cases, dtype: float64
133734 133741    853.0
Name: new_cases, dtype: float64
133735 133742    771.0
Name: new_cases, dtype: float64
133736 133743    827.0
Name: new_cases, dtype: float64
133737 133744    800.0
Name: new_cases, dtype: float64
133738 133745    0.0
Name: new_cases, dtype: float64
133739 133746    0.0
Name: new_cases, dtype: float64
133740 133747    2019.0
Name: new_cases, dtype: float64
133741 133748    1059.0
Name: new_cases, dtype: float64
133742 133749    1033.0
Name: new_cases, dtype: float64
133743 133750    1025.0
Name: new_cases, dtype: float64
133744 133751    1167.0
Name: new_cases, dtype: float64
133745 133752    0.0
Name: new_cases, dtype: float64
133746 133753    0.0
Name: new_cases, dtype: float64
133747 133754    3145.0
Name: new_cases, dtype: float64
133748 133755    1911.0
Name: new_cases, dtype: float64
133749 133756    2124.0
Name: new_cases, dtype: float64
133750 133757    2127.0
Name: new_cases, dtype: float64
133751 133758    2100.0
Name: new_cases, dtype: float64
133752 133759    0.0
Name: new_cases, dtype: float64
133753 133760    0.0
Name: new_cases, dtype: float64
133754 133761    5579.0
Name: new_cases, dtype: float64
133755 133762    3152.0
Name: new_cases, dtype: float64
133756 133763    3290.0
Name: new_cases, dtype: float64
133757 133764    2790.0
Name: new_cases, dtype: float64
133758 133765    2575.0
Name: new_cases, dtype: float64
133759 133766    0.0
Name: new_cases, dtype: float64
133760 133767    0.0
Name: new_cases, dtype: float64
133761 133768    6223.0
Name: new_cases, dtype: float64
133762 133769    2994.0
Name: new_cases, dtype: float64
133763 133770    3212.0
Name: new_cases, dtype: float64
133764 133771    2811.0
Name: new_cases, dtype: float64
133765 133772    2764.0
Name: new_cases, dtype: float64
133766 133773    0.0
Name: new_cases, dtype: float64
133767 133774    0.0
Name: new_cases, dtype: float64
133768 133775    6197.0
Name: new_cases, dtype: float64
133769 133776    2704.0
Name: new_cases, dtype: float64
133770 133777    3203.0
Name: new_cases, dtype: float64
133771 133778    2827.0
Name: new_cases, dtype: float64
133772 133779    0.0
Name: new_cases, dtype: float64
133773 133780    0.0
Name: new_cases, dtype: float64
133774 133781    0.0
Name: new_cases, dtype: float64

133775 133782    0.0
Name: new_cases, dtype: float64
133776 133783    12801.0
Name: new_cases, dtype: float64
133777 133784    3551.0
Name: new_cases, dtype: float64
133778 133785    3116.0
Name: new_cases, dtype: float64
133779 133786    2894.0
Name: new_cases, dtype: float64
133780 133787    0.0
Name: new_cases, dtype: float64
133781 133788    0.0
Name: new_cases, dtype: float64
133782 133789    6060.0
Name: new_cases, dtype: float64
133783 133790    1992.0
Name: new_cases, dtype: float64
133784 133791    2605.0
Name: new_cases, dtype: float64
133785 133792    2267.0
Name: new_cases, dtype: float64
133786 133793    2096.0
Name: new_cases, dtype: float64
133787 133794    0.0
Name: new_cases, dtype: float64
133788 133795    0.0
Name: new_cases, dtype: float64
133789 133796    4033.0
Name: new_cases, dtype: float64
133790 133797    1236.0
Name: new_cases, dtype: float64
133791 133798    1904.0
Name: new_cases, dtype: float64
133792 133799    1630.0
Name: new_cases, dtype: float64
133793 133800    1504.0
Name: new_cases, dtype: float64
133794 133801    0.0
Name: new_cases, dtype: float64
133795 133802    0.0
Name: new_cases, dtype: float64
133796 133803    3098.0
Name: new_cases, dtype: float64
133797 133804    1286.0
Name: new_cases, dtype: float64
133798 133805    1450.0
Name: new_cases, dtype: float64
133799 133806    1144.0
Name: new_cases, dtype: float64
133800 133807    1210.0
Name: new_cases, dtype: float64
133801 133808    0.0
Name: new_cases, dtype: float64
133802 133809    0.0
Name: new_cases, dtype: float64
133803 133810    2636.0
Name: new_cases, dtype: float64
133804 133811    1025.0
Name: new_cases, dtype: float64
133805 133812    1093.0
Name: new_cases, dtype: float64
133806 133813    1125.0
Name: new_cases, dtype: float64
133807 133814    966.0
Name: new_cases, dtype: float64
133808 133815    0.0
Name: new_cases, dtype: float64
133809 133816    0.0
Name: new_cases, dtype: float64
133810 133817    2266.0
Name: new_cases, dtype: float64
133811 133818    926.0
Name: new_cases, dtype: float64
133812 133819    1048.0
Name: new_cases, dtype: float64
133813 133820    979.0
Name: new_cases, dtype: float64
133814 133821    954.0
Name: new_cases, dtype: float64
133815 133822    0.0
Name: new_cases, dtype: float64
133816 133823    0.0
Name: new_cases, dtype: float64
133817 133824    2366.0
Name: new_cases, dtype: float64
133818 133825    1241.0
Name: new_cases, dtype: float64
133819 133826    1448.0
Name: new_cases, dtype: float64
133820 133827    1477.0
Name: new_cases, dtype: float64
133821 133828    1288.0
Name: new_cases, dtype: float64
133822 133829    0.0
Name: new_cases, dtype: float64
133823 133830    0.0
Name: new_cases, dtype: float64
133824 133831    3297.0
Name: new_cases, dtype: float64
133825 133832    0.0
Name: new_cases, dtype: float64
133826 133833    3336.0
Name: new_cases, dtype: float64
133827 133834    1793.0
Name: new_cases, dtype: float64
133828 133835    1721.0
Name: new_cases, dtype: float64
133829 133836    0.0
Name: new_cases, dtype: float64
133830 133837    0.0
Name: new_cases, dtype: float64
133831 133838    4540.0
Name: new_cases, dtype: float64
133832 133839    1953.0
Name: new_cases, dtype: float64
133833 133840    2609.0
Name: new_cases, dtype: float64
133834 133841    2937.0
Name: new_cases, dtype: float64
133835 133842    2849.0
Name: new_cases, dtype: float64
133836 133843    0.0
Name: new_cases, dtype: float64
133837 133844    0.0
Name: new_cases, dtype: float64
133838 133845    6647.0
Name: new_cases, dtype: float64
133839 133846    2985.0
Name: new_cases, dtype: float64
133840 133847    4150.0
Name: new_cases, dtype: float64
133841 133848    3884.0
Name: new_cases, dtype: float64
133842 133849    3926.0
Name: new_cases, dtype: float64
133843 133850    0.0
Name: new_cases, dtype: float64
133844 133851    0.0
Name: new_cases, dtype: float64
133845 133852    9712.0
Name: new_cases, dtype: float64
133846 133853    4297.0
Name: new_cases, dtype: float64
133847 133854    5984.0
Name: new_cases, dtype: float64
133848 133855    6016.0
Name: new_cases, dtype: float64
133849 133856    6171.0
Name: new_cases, dtype: float64
133850 133857    0.0
Name: new_cases, dtype: float64
133851 133858    0.0
Name: new_cases, dtype: float64
133852 133859    14592.0
Name: new_cases, dtype: float64
133853 133860    6355.0
Name: new_cases, dtype: float64
133854 133861    8588.0
Name: new_cases, dtype: float64
133855 133862    8048.0
Name: new_cases, dtype: float64
133856 133863    8033.0
Name: new_cases, dtype: float64
133857 133864    0.0
Name: new_cases, dtype: float64
133858 133865    0.0
Name: new_cases, dtype: float64
133859 133866    19405.0
Name: new_cases, dtype: float64
133860 133867    8423.0
Name: new_cases, dtype: float64
133861 133868    10467.0
Name: new_cases, dtype: float64
133862 133869    9546.0
Name: new_cases, dtype: float64
133863 133870    9958.0
Name: new_cases, dtype: float64
133864 133871    0.0
Name: new_cases, dtype: float64
133865 133872    0.0
Name: new_cases, dtype: float64
133866 133873    23895.0
Name: new_cases, dtype: float64
133867 133874    9975.0
Name: new_cases, dtype: float64
133868 133875    12425.0
Name: new_cases, dtype: float64
133869 133876    10861.0
Name: new_cases, dtype: float64
133870 133877    10134.0
Name: new_cases, dtype: float64
133871 133878    0.0
Name: new_cases, dtype: float64
133872 133879    0.0
Name: new_cases, dtype: float64
133873 133880    23440.0
Name: new_cases, dtype: float64
133874 133881    8171.0
Name: new_cases, dtype: float64
133875 133882    11167.0
Name: new_cases, dtype: float64
133876 133883    11077.0
Name: new_cases, dtype: float64
133877 133884    9943.0
Name: new_cases, dtype: float64
133878 133885    0.0
Name: new_cases, dtype: float64
133879 133886    0.0
Name: new_cases, dtype: float64
133880 133887    20487.0
Name: new_cases, dtype: float64
133881 133888    8171.0
Name: new_cases, dtype: float64
133882 133889    11565.0
Name: new_cases, dtype: float64
133883 133890    11451.0
Name: new_cases, dtype: float64
133884 133891    0.0
Name: new_cases, dtype: float64
133885 133892    0.0
Name: new_cases, dtype: float64
133886 133893    0.0
Name: new_cases, dtype: float64
133887 133894    36193.0
Name: new_cases, dtype: float64
133888 133895    13368.0
Name: new_cases, dtype: float64
133889 133896    17636.0
Name: new_cases, dtype: float64
133890 133897    19036.0
Name: new_cases, dtype: float64
133891 133898    18987.0
Name: new_cases, dtype: float64
133892 133899    0.0
Name: new_cases, dtype: float64
133893 133900    0.0
Name: new_cases, dtype: float64
133894 133901    38447.0
Name: new_cases, dtype: float64
133895 133902    20752.0
Name: new_cases, dtype: float64
133896 133903    31118.0
Name: new_cases, dtype: float64
133897 133904    32242.0
Name: new_cases, dtype: float64
133898 133905    28038.0
Name: new_cases, dtype: float64
133899 Series([], Name: new_cases, dtype: float64)
133900 Series([], Name: new_cases, dtype: float64)
133901 Series([], Name: new_cases, dtype: float64)
133902 Series([], Name: new_cases, dtype: float64)
133903 Series([], Name: new_cases, dtype: float64)
133904 Series([], Name: new_cases, dtype: float64)
133905 Series([], Name: new_cases, dtype: float64)
136590 136597    0.0
Name: new_cases, dtype: float64
136591 136598    5.0
Name: new_cases, dtype: float64
136592 136599    0.0
Name: new_cases, dtype: float64
136593 136600    0.0
Name: new_cases, dtype: float64
136594 136601    0.0
Name: new_cases, dtype: float64
136595 136602    6.0
Name: new_cases, dtype: float64
136596 136603    0.0
Name: new_cases, dtype: float64
136597 136604    0.0
Name: new_cases, dtype: float64
136598 136605    0.0
Name: new_cases, dtype: float64
136599 136606    7.0
Name: new_cases, dtype: float64
136600 136607    0.0
Name: new_cases, dtype: float64
136601 136608    0.0
Name: new_cases, dtype: float64
136602 136609    1.0
Name: new_cases, dtype: float64
136603 136610    0.0
Name: new_cases, dtype: float64
136604 136611    0.0
Name: new_cases, dtype: float64
136605 136612    0.0
Name: new_cases, dtype: float64
136606 136613    1.0
Name: new_cases, dtype: float64
136607 136614    0.0
Name: new_cases, dtype: float64
136608 136615    1.0
Name: new_cases, dtype: float64
136609 136616    0.0
Name: new_cases, dtype: float64
136610 136617    0.0
Name: new_cases, dtype: float64
136611 136618    0.0
Name: new_cases, dtype: float64
136612 136619    0.0
Name: new_cases, dtype: float64
136613 136620    0.0
Name: new_cases, dtype: float64
136614 136621    0.0
Name: new_cases, dtype: float64
136615 136622    0.0
Name: new_cases, dtype: float64
136616 136623    2.0
Name: new_cases, dtype: float64
136617 136624    3.0
Name: new_cases, dtype: float64
136618 136625    0.0
Name: new_cases, dtype: float64
136619 136626    1.0
Name: new_cases, dtype: float64
136620 136627    1.0
Name: new_cases, dtype: float64
136621 136628    0.0
Name: new_cases, dtype: float64
136622 136629    1.0
Name: new_cases, dtype: float64

136623 136630    0.0
Name: new_cases, dtype: float64
136624 136631    0.0
Name: new_cases, dtype: float64
136625 136632    4.0
Name: new_cases, dtype: float64
136626 136633    1.0
Name: new_cases, dtype: float64
136627 136634    2.0
Name: new_cases, dtype: float64
136628 136635    0.0
Name: new_cases, dtype: float64
136629 136636    0.0
Name: new_cases, dtype: float64
136630 136637    3.0
Name: new_cases, dtype: float64
136631 136638    6.0
Name: new_cases, dtype: float64
136632 136639    11.0
Name: new_cases, dtype: float64
136633 136640    5.0
Name: new_cases, dtype: float64
136634 136641    7.0
Name: new_cases, dtype: float64
136635 136642    32.0
Name: new_cases, dtype: float64
136636 136643    33.0
Name: new_cases, dtype: float64
136637 136644    30.0
Name: new_cases, dtype: float64
136638 136645    35.0
Name: new_cases, dtype: float64
136639 136646    60.0
Name: new_cases, dtype: float64
136640 136647    50.0
Name: new_cases, dtype: float64
136641 136648    89.0
Name: new_cases, dtype: float64
136642 136649    188.0
Name: new_cases, dtype: float64
136643 136650    122.0
Name: new_cases, dtype: float64
136644 136651    106.0
Name: new_cases, dtype: float64
136645 136652    107.0
Name: new_cases, dtype: float64
136646 136653    111.0
Name: new_cases, dtype: float64
136647 136654    91.0
Name: new_cases, dtype: float64
136648 136655    109.0
Name: new_cases, dtype: float64
136649 136656    143.0
Name: new_cases, dtype: float64
136650 136657    136.0
Name: new_cases, dtype: float64
136651 136658    127.0
Name: new_cases, dtype: float64
136652 136659    120.0
Name: new_cases, dtype: float64
136653 136660    104.0
Name: new_cases, dtype: float64
136654 136661    103.0
Name: new_cases, dtype: float64
136655 136662    89.0
Name: new_cases, dtype: float64
136656 136663    102.0
Name: new_cases, dtype: float64
136657 136664    51.0
Name: new_cases, dtype: float64
136658 136665    38.0
Name: new_cases, dtype: float64
136659 136666    111.0
Name: new_cases, dtype: float64
136660 136667    54.0
Name: new_cases, dtype: float64
136661 136668    50.0
Name: new_cases, dtype: float64
136662 136669    45.0
Name: new_cases, dtype: float64
136663 136670    33.0
Name: new_cases, dtype: float64
136664 136671    28.0
Name: new_cases, dtype: float64
136665 136672    34.0
Name: new_cases, dtype: float64
136666 136673    30.0
Name: new_cases, dtype: float64
136667 136674    29.0
Name: new_cases, dtype: float64
136668 136675    28.0
Name: new_cases, dtype: float64
136669 136676    33.0
Name: new_cases, dtype: float64
136670 136677    32.0
Name: new_cases, dtype: float64
136671 136678    27.0
Name: new_cases, dtype: float64
136672 136679    19.0
Name: new_cases, dtype: float64
136673 136680    15.0
Name: new_cases, dtype: float64
136674 136681    13.0
Name: new_cases, dtype: float64
136675 136682    15.0
Name: new_cases, dtype: float64
136676 136683    53.0
Name: new_cases, dtype: float64
136677 136684    15.0
Name: new_cases, dtype: float64
136678 136685    9.0
Name: new_cases, dtype: float64
136679 136686    7.0
Name: new_cases, dtype: float64
136680 136687    9.0
Name: new_cases, dtype: float64
136681 136688    7.0
Name: new_cases, dtype: float64
136682 136689    6.0
Name: new_cases, dtype: float64
136683 136690    6.0
Name: new_cases, dtype: float64
136684 136691    3.0
Name: new_cases, dtype: float64
136685 136692    18.0
Name: new_cases, dtype: float64
136686 136693    1.0
Name: new_cases, dtype: float64
136687 136694    1.0
Name: new_cases, dtype: float64
136688 136695    3.0
Name: new_cases, dtype: float64
136689 136696    8.0
Name: new_cases, dtype: float64
136690 136697    4.0
Name: new_cases, dtype: float64
136691 136698    5.0
Name: new_cases, dtype: float64
136692 136699    6.0
Name: new_cases, dtype: float64
136693 136700    2.0
Name: new_cases, dtype: float64
136694 136701    0.0
Name: new_cases, dtype: float64
136695 136702    1.0
Name: new_cases, dtype: float64
136696 136703    7.0
Name: new_cases, dtype: float64
136697 136704    0.0
Name: new_cases, dtype: float64
136698 136705    3.0
Name: new_cases, dtype: float64
136699 136706    3.0
Name: new_cases, dtype: float64
136700 136707    2.0
Name: new_cases, dtype: float64
136701 136708    1.0
Name: new_cases, dtype: float64
136702 136709    3.0
Name: new_cases, dtype: float64
136703 136710    0.0
Name: new_cases, dtype: float64
136704 136711    3.0
Name: new_cases, dtype: float64
136705 136712    0.0
Name: new_cases, dtype: float64
136706 136713    2.0
Name: new_cases, dtype: float64
136707 136714    3.0
Name: new_cases, dtype: float64
136708 136715    9.0
Name: new_cases, dtype: float64
136709 136716    11.0
Name: new_cases, dtype: float64
136710 136717    11.0
Name: new_cases, dtype: float64
136711 136718    1.0
Name: new_cases, dtype: float64
136712 136719    4.0
Name: new_cases, dtype: float64
136713 136720    1.0
Name: new_cases, dtype: float64
136714 136721    1.0
Name: new_cases, dtype: float64
136715 136722    1.0
Name: new_cases, dtype: float64
136716 136723    17.0
Name: new_cases, dtype: float64
136717 136724    1.0
Name: new_cases, dtype: float64
136718 136725    2.0
Name: new_cases, dtype: float64
136719 136726    8.0
Name: new_cases, dtype: float64
136720 136727    7.0
Name: new_cases, dtype: float64
136721 136728    2.0
Name: new_cases, dtype: float64
136722 136729    4.0
Name: new_cases, dtype: float64
136723 136730    0.0
Name: new_cases, dtype: float64
136724 136731    4.0
Name: new_cases, dtype: float64
136725 136732    5.0
Name: new_cases, dtype: float64
136726 136733    1.0
Name: new_cases, dtype: float64
136727 136734    0.0
Name: new_cases, dtype: float64
136728 136735    0.0
Name: new_cases, dtype: float64
136729 136736    0.0
Name: new_cases, dtype: float64
136730 136737    6.0
Name: new_cases, dtype: float64
136731 136738    5.0
Name: new_cases, dtype: float64
136732 136739    1.0
Name: new_cases, dtype: float64
136733 136740    1.0
Name: new_cases, dtype: float64
136734 136741    3.0
Name: new_cases, dtype: float64
136735 136742    5.0
Name: new_cases, dtype: float64
136736 136743    1.0
Name: new_cases, dtype: float64
136737 136744    1.0
Name: new_cases, dtype: float64
136738 136745    4.0
Name: new_cases, dtype: float64
136739 136746    0.0
Name: new_cases, dtype: float64
136740 136747    0.0
Name: new_cases, dtype: float64
136741 136748    7.0
Name: new_cases, dtype: float64
136742 136749    2.0
Name: new_cases, dtype: float64
136743 136750    2.0
Name: new_cases, dtype: float64
136744 136751    6.0
Name: new_cases, dtype: float64
136745 136752    1.0
Name: new_cases, dtype: float64
136746 136753    5.0
Name: new_cases, dtype: float64
136747 136754    5.0
Name: new_cases, dtype: float64
136748 136755    5.0
Name: new_cases, dtype: float64
136749 136756    0.0
Name: new_cases, dtype: float64
136750 136757    2.0
Name: new_cases, dtype: float64
136751 136758    5.0
Name: new_cases, dtype: float64
136752 136759    0.0
Name: new_cases, dtype: float64
136753 136760    14.0
Name: new_cases, dtype: float64
136754 136761    1.0
Name: new_cases, dtype: float64
136755 136762    3.0
Name: new_cases, dtype: float64
136756 136763    7.0
Name: new_cases, dtype: float64
136757 136764    5.0
Name: new_cases, dtype: float64
136758 136765    4.0
Name: new_cases, dtype: float64
136759 136766    3.0
Name: new_cases, dtype: float64
136760 136767    7.0
Name: new_cases, dtype: float64
136761 136768    3.0
Name: new_cases, dtype: float64
136762 136769    1.0
Name: new_cases, dtype: float64
136763 136770    5.0
Name: new_cases, dtype: float64
136764 136771   -2.0
Name: new_cases, dtype: float64
136765 136772    16.0
Name: new_cases, dtype: float64
136766 136773    10.0
Name: new_cases, dtype: float64
136767 136774    3.0
Name: new_cases, dtype: float64
136768 136775    9.0
Name: new_cases, dtype: float64
136769 136776    4.0
Name: new_cases, dtype: float64
136770 136777    2.0
Name: new_cases, dtype: float64
136771 136778    1.0
Name: new_cases, dtype: float64
136772 136779    6.0
Name: new_cases, dtype: float64
136773 136780    6.0
Name: new_cases, dtype: float64
136774 136781    2.0
Name: new_cases, dtype: float64
136775 136782    5.0
Name: new_cases, dtype: float64
136776 136783    3.0
Name: new_cases, dtype: float64
136777 136784    1.0
Name: new_cases, dtype: float64
136778 136785    7.0
Name: new_cases, dtype: float64
136779 136786    2.0
Name: new_cases, dtype: float64
136780 136787    15.0
Name: new_cases, dtype: float64
136781 136788    3.0
Name: new_cases, dtype: float64
136782 136789    3.0
Name: new_cases, dtype: float64
136783 136790    0.0
Name: new_cases, dtype: float64
136784 136791    0.0
Name: new_cases, dtype: float64
136785 136792    5.0
Name: new_cases, dtype: float64
136786 136793    3.0
Name: new_cases, dtype: float64
136787 136794    17.0
Name: new_cases, dtype: float64

136788 136795    0.0
Name: new_cases, dtype: float64
136789 136796    1.0
Name: new_cases, dtype: float64
136790 136797    1.0
Name: new_cases, dtype: float64
136791 136798    3.0
Name: new_cases, dtype: float64
136792 136799    1.0
Name: new_cases, dtype: float64
136793 136800    7.0
Name: new_cases, dtype: float64
136794 136801    1.0
Name: new_cases, dtype: float64
136795 136802    0.0
Name: new_cases, dtype: float64
136796 136803    5.0
Name: new_cases, dtype: float64
136797 136804    2.0
Name: new_cases, dtype: float64
136798 136805    5.0
Name: new_cases, dtype: float64
136799 136806    1.0
Name: new_cases, dtype: float64
136800 136807    1.0
Name: new_cases, dtype: float64
136801 136808    6.0
Name: new_cases, dtype: float64
136802 136809    1.0
Name: new_cases, dtype: float64
136803 136810    0.0
Name: new_cases, dtype: float64
136804 136811    1.0
Name: new_cases, dtype: float64
136805 136812    5.0
Name: new_cases, dtype: float64
136806 136813    8.0
Name: new_cases, dtype: float64
136807 136814    2.0
Name: new_cases, dtype: float64
136808 136815    4.0
Name: new_cases, dtype: float64
136809 136816    7.0
Name: new_cases, dtype: float64
136810 136817    6.0
Name: new_cases, dtype: float64
136811 136818    1.0
Name: new_cases, dtype: float64
136812 136819    1.0
Name: new_cases, dtype: float64
136813 136820    1.0
Name: new_cases, dtype: float64
136814 136821    7.0
Name: new_cases, dtype: float64
136815 136822    7.0
Name: new_cases, dtype: float64
136816 136823    5.0
Name: new_cases, dtype: float64
136817 136824    7.0
Name: new_cases, dtype: float64
136818 136825    2.0
Name: new_cases, dtype: float64
136819 136826    5.0
Name: new_cases, dtype: float64
136820 136827    10.0
Name: new_cases, dtype: float64
136821 136828    0.0
Name: new_cases, dtype: float64
136822 136829    7.0
Name: new_cases, dtype: float64
136823 136830    3.0
Name: new_cases, dtype: float64
136824 136831    6.0
Name: new_cases, dtype: float64
136825 136832    5.0
Name: new_cases, dtype: float64
136826 136833    3.0
Name: new_cases, dtype: float64
136827 136834    2.0
Name: new_cases, dtype: float64
136828 136835    3.0
Name: new_cases, dtype: float64
136829 136836    3.0
Name: new_cases, dtype: float64
136830 136837    1.0
Name: new_cases, dtype: float64
136831 136838    22.0
Name: new_cases, dtype: float64
136832 136839    14.0
Name: new_cases, dtype: float64
136833 136840    5.0
Name: new_cases, dtype: float64
136834 136841    5.0
Name: new_cases, dtype: float64
136835 136842    6.0
Name: new_cases, dtype: float64
136836 136843    8.0
Name: new_cases, dtype: float64
136837 136844    2.0
Name: new_cases, dtype: float64
136838 136845    5.0
Name: new_cases, dtype: float64
136839 136846    10.0
Name: new_cases, dtype: float64
136840 136847    15.0
Name: new_cases, dtype: float64
136841 136848    7.0
Name: new_cases, dtype: float64
136842 136849    6.0
Name: new_cases, dtype: float64
136843 136850    6.0
Name: new_cases, dtype: float64
136844 136851    2.0
Name: new_cases, dtype: float64
136845 136852    5.0
Name: new_cases, dtype: float64
136846 136853    2.0
Name: new_cases, dtype: float64
136847 136854    9.0
Name: new_cases, dtype: float64
136848 136855    13.0
Name: new_cases, dtype: float64
136849 136856    10.0
Name: new_cases, dtype: float64
136850 136857    11.0
Name: new_cases, dtype: float64
136851 136858   -7.0
Name: new_cases, dtype: float64
136852 136859    12.0
Name: new_cases, dtype: float64
136853 136860    9.0
Name: new_cases, dtype: float64
136854 136861    9.0
Name: new_cases, dtype: float64
136855 136862    10.0
Name: new_cases, dtype: float64
136856 136863    8.0
Name: new_cases, dtype: float64
136857 136864    4.0
Name: new_cases, dtype: float64
136858 136865    5.0
Name: new_cases, dtype: float64
136859 136866    7.0
Name: new_cases, dtype: float64
136860 136867    3.0
Name: new_cases, dtype: float64
136861 136868    13.0
Name: new_cases, dtype: float64
136862 136869    4.0
Name: new_cases, dtype: float64
136863 136870    12.0
Name: new_cases, dtype: float64
136864 136871    5.0
Name: new_cases, dtype: float64
136865 136872    4.0
Name: new_cases, dtype: float64
136866 136873    3.0
Name: new_cases, dtype: float64
136867 136874    10.0
Name: new_cases, dtype: float64
136868 136875    7.0
Name: new_cases, dtype: float64
136869 136876    6.0
Name: new_cases, dtype: float64
136870 136877    8.0
Name: new_cases, dtype: float64
136871 136878    12.0
Name: new_cases, dtype: float64
136872 136879    7.0
Name: new_cases, dtype: float64
136873 136880    3.0
Name: new_cases, dtype: float64
136874 136881    4.0
Name: new_cases, dtype: float64
136875 136882    3.0
Name: new_cases, dtype: float64
136876 136883    5.0
Name: new_cases, dtype: float64
136877 136884    9.0
Name: new_cases, dtype: float64
136878 136885    5.0
Name: new_cases, dtype: float64
136879 136886    8.0
Name: new_cases, dtype: float64
136880 136887    1.0
Name: new_cases, dtype: float64
136881 136888    3.0
Name: new_cases, dtype: float64
136882 136889    2.0
Name: new_cases, dtype: float64
136883 136890    8.0
Name: new_cases, dtype: float64
136884 136891    4.0
Name: new_cases, dtype: float64
136885 136892    7.0
Name: new_cases, dtype: float64
136886 136893    23.0
Name: new_cases, dtype: float64
136887 136894   -2.0
Name: new_cases, dtype: float64
136888 136895   -10.0
Name: new_cases, dtype: float64
136889 136896    16.0
Name: new_cases, dtype: float64
136890 136897    16.0
Name: new_cases, dtype: float64
136891 136898    19.0
Name: new_cases, dtype: float64
136892 136899    5.0
Name: new_cases, dtype: float64
136893 136900    11.0
Name: new_cases, dtype: float64
136894 136901    21.0
Name: new_cases, dtype: float64
136895 136902    10.0
Name: new_cases, dtype: float64
136896 136903    18.0
Name: new_cases, dtype: float64
136897 136904    13.0
Name: new_cases, dtype: float64
136898 136905    14.0
Name: new_cases, dtype: float64
136899 136906    19.0
Name: new_cases, dtype: float64
136900 136907    14.0
Name: new_cases, dtype: float64
136901 136908    21.0
Name: new_cases, dtype: float64
136902 136909    19.0
Name: new_cases, dtype: float64
136903 136910    25.0
Name: new_cases, dtype: float64
136904 136911    18.0
Name: new_cases, dtype: float64
136905 136912    11.0
Name: new_cases, dtype: float64
136906 136913    12.0
Name: new_cases, dtype: float64
136907 136914    17.0
Name: new_cases, dtype: float64
136908 136915    28.0
Name: new_cases, dtype: float64
136909 136916    9.0
Name: new_cases, dtype: float64
136910 136917    15.0
Name: new_cases, dtype: float64
136911 136918    20.0
Name: new_cases, dtype: float64
136912 136919    16.0
Name: new_cases, dtype: float64
136913 136920    34.0
Name: new_cases, dtype: float64
136914 136921    576.0
Name: new_cases, dtype: float64
136915 136922    382.0
Name: new_cases, dtype: float64
136916 136923    427.0
Name: new_cases, dtype: float64
136917 136924    46.0
Name: new_cases, dtype: float64
136918 136925    67.0
Name: new_cases, dtype: float64
136919 136926    81.0
Name: new_cases, dtype: float64
136920 136927    110.0
Name: new_cases, dtype: float64
136921 136928    121.0
Name: new_cases, dtype: float64
136922 136929    144.0
Name: new_cases, dtype: float64
136923 136930    155.0
Name: new_cases, dtype: float64
136924 136931    250.0
Name: new_cases, dtype: float64
136925 136932    194.0
Name: new_cases, dtype: float64
136926 136933    279.0
Name: new_cases, dtype: float64
136927 136934    216.0
Name: new_cases, dtype: float64
136928 136935    315.0
Name: new_cases, dtype: float64
136929 136936    745.0
Name: new_cases, dtype: float64
136930 136937    527.0
Name: new_cases, dtype: float64
136931 136938    365.0
Name: new_cases, dtype: float64
136932 136939    305.0
Name: new_cases, dtype: float64
136933 136940    205.0
Name: new_cases, dtype: float64
136934 136941    212.0
Name: new_cases, dtype: float64
136935 136942    245.0
Name: new_cases, dtype: float64
136936 136943    249.0
Name: new_cases, dtype: float64
136937 136944    287.0
Name: new_cases, dtype: float64
136938 136945    157.0
Name: new_cases, dtype: float64
136939 136946    0.0
Name: new_cases, dtype: float64
136940 136947    459.0
Name: new_cases, dtype: float64
136941 136948    230.0
Name: new_cases, dtype: float64
136942 136949    374.0
Name: new_cases, dtype: float64
136943 136950    369.0
Name: new_cases, dtype: float64
136944 136951    171.0
Name: new_cases, dtype: float64
136945 136952    59.0
Name: new_cases, dtype: float64
136946 136953    142.0
Name: new_cases, dtype: float64
136947 136954    0.0
Name: new_cases, dtype: float64
136948 136955    309.0
Name: new_cases, dtype: float64
136949 136956    198.0
Name: new_cases, dtype: float64
136950 136957    198.0
Name: new_cases, dtype: float64
136951 136958    1146.0
Name: new_cases, dtype: float64

136952 136959    0.0
Name: new_cases, dtype: float64
136953 136960    819.0
Name: new_cases, dtype: float64
136954 136961    756.0
Name: new_cases, dtype: float64
136955 136962    1732.0
Name: new_cases, dtype: float64
136956 136963    829.0
Name: new_cases, dtype: float64
136957 136964    836.0
Name: new_cases, dtype: float64
136958 136965    836.0
Name: new_cases, dtype: float64
136959 136966    795.0
Name: new_cases, dtype: float64
136960 136967    0.0
Name: new_cases, dtype: float64
136961 136968    809.0
Name: new_cases, dtype: float64
136962 136969    1076.0
Name: new_cases, dtype: float64
136963 136970    237.0
Name: new_cases, dtype: float64
136964 136971    186.0
Name: new_cases, dtype: float64
136965 136972    0.0
Name: new_cases, dtype: float64
136966 136973    189.0
Name: new_cases, dtype: float64
136967 136974    358.0
Name: new_cases, dtype: float64
136968 136975    175.0
Name: new_cases, dtype: float64
136969 136976    0.0
Name: new_cases, dtype: float64
136970 136977    126.0
Name: new_cases, dtype: float64
136971 136978    166.0
Name: new_cases, dtype: float64
136972 136979    143.0
Name: new_cases, dtype: float64
136973 136980    72.0
Name: new_cases, dtype: float64
136974 136981    175.0
Name: new_cases, dtype: float64
136975 136982    150.0
Name: new_cases, dtype: float64
136976 136983    130.0
Name: new_cases, dtype: float64
136977 136984    82.0
Name: new_cases, dtype: float64
136978 136985    181.0
Name: new_cases, dtype: float64
136979 136986    0.0
Name: new_cases, dtype: float64
136980 136987    188.0
Name: new_cases, dtype: float64
136981 136988    0.0
Name: new_cases, dtype: float64
136982 136989    72.0
Name: new_cases, dtype: float64
136983 136990    45.0
Name: new_cases, dtype: float64
136984 136991    142.0
Name: new_cases, dtype: float64
136985 136992    80.0
Name: new_cases, dtype: float64
136986 136993    0.0
Name: new_cases, dtype: float64
136987 136994    42.0
Name: new_cases, dtype: float64
136988 136995    35.0
Name: new_cases, dtype: float64
136989 136996    54.0
Name: new_cases, dtype: float64
136990 136997    79.0
Name: new_cases, dtype: float64
136991 136998    64.0
Name: new_cases, dtype: float64
136992 136999    136.0
Name: new_cases, dtype: float64
136993 137000    0.0
Name: new_cases, dtype: float64
136994 137001    60.0
Name: new_cases, dtype: float64
136995 137002    39.0
Name: new_cases, dtype: float64
136996 137003    58.0
Name: new_cases, dtype: float64
136997 137004    81.0
Name: new_cases, dtype: float64
136998 137005    78.0
Name: new_cases, dtype: float64
136999 137006    170.0
Name: new_cases, dtype: float64
137000 137007    78.0
Name: new_cases, dtype: float64
137001 137008    149.0
Name: new_cases, dtype: float64
137002 137009    248.0
Name: new_cases, dtype: float64
137003 137010    92.0
Name: new_cases, dtype: float64
137004 137011    100.0
Name: new_cases, dtype: float64
137005 137012    119.0
Name: new_cases, dtype: float64
137006 137013    90.0
Name: new_cases, dtype: float64
137007 137014    73.0
Name: new_cases, dtype: float64
137008 137015    470.0
Name: new_cases, dtype: float64
137009 137016    97.0
Name: new_cases, dtype: float64
137010 137017    0.0
Name: new_cases, dtype: float64
137011 137018    134.0
Name: new_cases, dtype: float64
137012 137019    80.0
Name: new_cases, dtype: float64
137013 137020    77.0
Name: new_cases, dtype: float64
137014 137021    39.0
Name: new_cases, dtype: float64
137015 137022    48.0
Name: new_cases, dtype: float64
137016 137023    42.0
Name: new_cases, dtype: float64
137017 137024    26.0
Name: new_cases, dtype: float64
137018 137025    58.0
Name: new_cases, dtype: float64
137019 137026    84.0
Name: new_cases, dtype: float64
137020 137027    96.0
Name: new_cases, dtype: float64
137021 137028    194.0
Name: new_cases, dtype: float64
137022 137029    250.0
Name: new_cases, dtype: float64
137023 137030    334.0
Name: new_cases, dtype: float64
137024 137031    405.0
Name: new_cases, dtype: float64
137025 137032    559.0
Name: new_cases, dtype: float64
137026 137033    789.0
Name: new_cases, dtype: float64
137027 137034    967.0
Name: new_cases, dtype: float64
137028 137035    985.0
Name: new_cases, dtype: float64
137029 137036    965.0
Name: new_cases, dtype: float64
137030 137037    1335.0
Name: new_cases, dtype: float64
137031 137038    1543.0
Name: new_cases, dtype: float64
137032 137039    1585.0
Name: new_cases, dtype: float64
137033 137040    1547.0
Name: new_cases, dtype: float64
137034 137041    1767.0
Name: new_cases, dtype: float64
137035 137042    1390.0
Name: new_cases, dtype: float64
137036 137043    1443.0
Name: new_cases, dtype: float64
137037 137044    1458.0
Name: new_cases, dtype: float64
137038 137045    1470.0
Name: new_cases, dtype: float64
137039 137046    2070.0
Name: new_cases, dtype: float64
137040 137047    2839.0
Name: new_cases, dtype: float64
137041 137048    2438.0
Name: new_cases, dtype: float64
137042 137049    2048.0
Name: new_cases, dtype: float64
137043 137050    2180.0
Name: new_cases, dtype: float64
137044 137051    2011.0
Name: new_cases, dtype: float64
137045 137052    1871.0
Name: new_cases, dtype: float64
137046 137053    1583.0
Name: new_cases, dtype: float64
137047 137054    1891.0
Name: new_cases, dtype: float64
137048 137055    1940.0
Name: new_cases, dtype: float64
137049 137056    2041.0
Name: new_cases, dtype: float64
137050 137057    1763.0
Name: new_cases, dtype: float64
137051 137058    2112.0
Name: new_cases, dtype: float64
137052 137059    1911.0
Name: new_cases, dtype: float64
137053 137060    2044.0
Name: new_cases, dtype: float64
137054 137061    2419.0
Name: new_cases, dtype: float64
137055 137062    2101.0
Name: new_cases, dtype: float64
137056 137063    1630.0
Name: new_cases, dtype: float64
137057 137064    1919.0
Name: new_cases, dtype: float64
137058 137065    1983.0
Name: new_cases, dtype: float64
137059 137066    4887.0
Name: new_cases, dtype: float64
137060 137067    2256.0
Name: new_cases, dtype: float64
137061 137068    3095.0
Name: new_cases, dtype: float64
137062 137069    2302.0
Name: new_cases, dtype: float64
137063 137070    9635.0
Name: new_cases, dtype: float64
137064 137071    2473.0
Name: new_cases, dtype: float64
137065 137072    3394.0
Name: new_cases, dtype: float64
137066 137073    2636.0
Name: new_cases, dtype: float64
137067 137074    3481.0
Name: new_cases, dtype: float64
137068 137075    3052.0
Name: new_cases, dtype: float64
137069 137076    3382.0
Name: new_cases, dtype: float64
137070 137077    2713.0
Name: new_cases, dtype: float64
137071 137078    3226.0
Name: new_cases, dtype: float64
137072 137079    2455.0
Name: new_cases, dtype: float64
137073 137080    5386.0
Name: new_cases, dtype: float64
137074 137081    3759.0
Name: new_cases, dtype: float64
137075 137082    4803.0
Name: new_cases, dtype: float64
137076 137083    4528.0
Name: new_cases, dtype: float64
137077 137084    3422.0
Name: new_cases, dtype: float64
137078 137085    2230.0
Name: new_cases, dtype: float64
137079 137086    3440.0
Name: new_cases, dtype: float64
137080 137087    3886.0
Name: new_cases, dtype: float64
137081 137088    2630.0
Name: new_cases, dtype: float64
137082 137089    2818.0
Name: new_cases, dtype: float64
137083 137090    2671.0
Name: new_cases, dtype: float64
137084 137091    2419.0
Name: new_cases, dtype: float64
137085 137092    2662.0
Name: new_cases, dtype: float64
137086 137093    2680.0
Name: new_cases, dtype: float64
137087 137094    2310.0
Name: new_cases, dtype: float64
137088 137095    2290.0
Name: new_cases, dtype: float64
137089 137096    3277.0
Name: new_cases, dtype: float64
137090 137097    2804.0
Name: new_cases, dtype: float64
137091 137098    3355.0
Name: new_cases, dtype: float64
137092 137099    3000.0
Name: new_cases, dtype: float64
137093 137100    2331.0
Name: new_cases, dtype: float64
137094 137101    3129.0
Name: new_cases, dtype: float64
137095 137102    3058.0
Name: new_cases, dtype: float64
137096 137103    3667.0
Name: new_cases, dtype: float64
137097 137104    3682.0
Name: new_cases, dtype: float64
137098 137105    3175.0
Name: new_cases, dtype: float64
137099 137106    4059.0
Name: new_cases, dtype: float64
137100 137107    3174.0
Name: new_cases, dtype: float64
137101 137108    4108.0
Name: new_cases, dtype: float64
137102 137109    3644.0
Name: new_cases, dtype: float64
137103 137110    4161.0
Name: new_cases, dtype: float64
137104 137111    3995.0
Name: new_cases, dtype: float64
137105 137112    5406.0
Name: new_cases, dtype: float64
137106 137113    4662.0
Name: new_cases, dtype: float64
137107 137114    4786.0
Name: new_cases, dtype: float64
137108 137115    5533.0
Name: new_cases, dtype: float64
137109 137116    6087.0
Name: new_cases, dtype: float64
137110 137117    6230.0
Name: new_cases, dtype: float64
137111 137118    5916.0
Name: new_cases, dtype: float64
137112 137119    6166.0
Name: new_cases, dtype: float64
137113 137120    5420.0
Name: new_cases, dtype: float64
137114 137121    6519.0
Name: new_cases, dtype: float64

137115 137122    7058.0
Name: new_cases, dtype: float64
137116 137123    9276.0
Name: new_cases, dtype: float64
137117 137124    9326.0
Name: new_cases, dtype: float64
137118 137125    9539.0
Name: new_cases, dtype: float64
137119 137126    8656.0
Name: new_cases, dtype: float64
137120 137127    8685.0
Name: new_cases, dtype: float64
137121 137128    9317.0
Name: new_cases, dtype: float64
137122 137129    9186.0
Name: new_cases, dtype: float64
137123 137130    9692.0
Name: new_cases, dtype: float64
137124 137131    10082.0
Name: new_cases, dtype: float64
137125 137132    11397.0
Name: new_cases, dtype: float64
137126 137133    11784.0
Name: new_cases, dtype: float64
137127 137134    11305.0
Name: new_cases, dtype: float64
137128 137135    13002.0
Name: new_cases, dtype: float64
137129 137136    13655.0
Name: new_cases, dtype: float64
137130 137137    14575.0
Name: new_cases, dtype: float64
137131 137138    14260.0
Name: new_cases, dtype: float64
137132 137139    15335.0
Name: new_cases, dtype: float64
137133 137140    15376.0
Name: new_cases, dtype: float64
137134 137141    14150.0
Name: new_cases, dtype: float64
137135 137142    16533.0
Name: new_cases, dtype: float64
137136 137143    17669.0
Name: new_cases, dtype: float64
137137 137144    17345.0
Name: new_cases, dtype: float64
137138 137145    18912.0
Name: new_cases, dtype: float64
137139 137146    18027.0
Name: new_cases, dtype: float64
137140 137147    17970.0
Name: new_cases, dtype: float64
137141 137148    18901.0
Name: new_cases, dtype: float64
137142 137149    20200.0
Name: new_cases, dtype: float64
137143 137150    20920.0
Name: new_cases, dtype: float64
137144 137151    21379.0
Name: new_cases, dtype: float64
137145 137152    21838.0
Name: new_cases, dtype: float64
137146 137153    19983.0
Name: new_cases, dtype: float64
137147 137154    19603.0
Name: new_cases, dtype: float64
137148 137155    19843.0
Name: new_cases, dtype: float64
137149 137156    21038.0
Name: new_cases, dtype: float64
137150 137157    22782.0
Name: new_cases, dtype: float64
137151 137158    23418.0
Name: new_cases, dtype: float64
137152 137159    22086.0
Name: new_cases, dtype: float64
137153 137160    21882.0
Name: new_cases, dtype: float64
137154 137161    21157.0
Name: new_cases, dtype: float64
137155 137162    20128.0
Name: new_cases, dtype: float64
137156 137163    20515.0
Name: new_cases, dtype: float64
137157 137164    20902.0
Name: new_cases, dtype: float64
137158 137165    19851.0
Name: new_cases, dtype: float64
137159 137166    20571.0
Name: new_cases, dtype: float64
137160 137167    19014.0
Name: new_cases, dtype: float64
137161 137168    17491.0
Name: new_cases, dtype: float64
137162 137169    17165.0
Name: new_cases, dtype: float64
137163 137170    18417.0
Name: new_cases, dtype: float64
137164 137171    18501.0
Name: new_cases, dtype: float64
137165 137172    18702.0
Name: new_cases, dtype: float64
137166 137173    17984.0
Name: new_cases, dtype: float64
137167 137174    16536.0
Name: new_cases, dtype: float64
137168 137175    15972.0
Name: new_cases, dtype: float64
137169 137176    14666.0
Name: new_cases, dtype: float64
137170 137177    9225.0
Name: new_cases, dtype: float64
137171 137178    20533.0
Name: new_cases, dtype: float64
137172 137179    14653.0
Name: new_cases, dtype: float64
137173 137180    15942.0
Name: new_cases, dtype: float64
137174 137181    15452.0
Name: new_cases, dtype: float64
137175 137182    13988.0
Name: new_cases, dtype: float64
137176 137183    13821.0
Name: new_cases, dtype: float64
137177 137184    14176.0
Name: new_cases, dtype: float64
137178 137185    16031.0
Name: new_cases, dtype: float64
137179 137186    14403.0
Name: new_cases, dtype: float64
137180 137187    15191.0
Name: new_cases, dtype: float64
137181 137188    14029.0
Name: new_cases, dtype: float64
137182 137189    12583.0
Name: new_cases, dtype: float64
137183 137190    11786.0
Name: new_cases, dtype: float64
137184 137191    13801.0
Name: new_cases, dtype: float64
137185 137192    13894.0
Name: new_cases, dtype: float64
137186 137193    14555.0
Name: new_cases, dtype: float64
137187 137194    14109.0
Name: new_cases, dtype: float64
137188 137195    13576.0
Name: new_cases, dtype: float64
137189 137196    12709.0
Name: new_cases, dtype: float64
137190 137197    10919.0
Name: new_cases, dtype: float64
137191 137198    11252.0
Name: new_cases, dtype: float64
137192 137199    13256.0
Name: new_cases, dtype: float64
137193 137200    12697.0
Name: new_cases, dtype: float64
137194 137201    11975.0
Name: new_cases, dtype: float64
137195 137202    12353.0
Name: new_cases, dtype: float64
137196 137203    10288.0
Name: new_cases, dtype: float64
137197 137204    9489.0
Name: new_cases, dtype: float64
137198 137205    10414.0
Name: new_cases, dtype: float64
137199 137206    11646.0
Name: new_cases, dtype: float64
137200 137207    11754.0
Name: new_cases, dtype: float64
137201 137208    11375.0
Name: new_cases, dtype: float64
137202 137209    10828.0
Name: new_cases, dtype: float64
137203 137210    9930.0
Name: new_cases, dtype: float64
137204 137211    9869.0
Name: new_cases, dtype: float64
137205 137212    21066.0
Name: new_cases, dtype: float64
137206 137213    0.0
Name: new_cases, dtype: float64
137207 137214    11140.0
Name: new_cases, dtype: float64
137208 137215    10630.0
Name: new_cases, dtype: float64
137209 137216    10817.0
Name: new_cases, dtype: float64
137210 137217    10035.0
Name: new_cases, dtype: float64
137211 137218    9445.0
Name: new_cases, dtype: float64
137212 137219    10064.0
Name: new_cases, dtype: float64
137213 137220    11276.0
Name: new_cases, dtype: float64
137214 137221    10486.0
Name: new_cases, dtype: float64
137215 137222    10648.0
Name: new_cases, dtype: float64
137216 137223    10863.0
Name: new_cases, dtype: float64
137217 137224    10111.0
Name: new_cases, dtype: float64
137218 137225    9122.0
Name: new_cases, dtype: float64
137219 137226    8918.0
Name: new_cases, dtype: float64
137220 137227    9727.0
Name: new_cases, dtype: float64
137221 137228    9810.0
Name: new_cases, dtype: float64
137222 137229    9742.0
Name: new_cases, dtype: float64
137223 137230    9351.0
Name: new_cases, dtype: float64
137224 137231    8675.0
Name: new_cases, dtype: float64
137225 137232    7706.0
Name: new_cases, dtype: float64
137226 137233    8452.0
Name: new_cases, dtype: float64
137227 137234    9658.0
Name: new_cases, dtype: float64
137228 137235    8968.0
Name: new_cases, dtype: float64
137229 137236    9224.0
Name: new_cases, dtype: float64
137230 137237    8859.0
Name: new_cases, dtype: float64
137231 137238    8165.0
Name: new_cases, dtype: float64
137232 137239    15253.0
Name: new_cases, dtype: float64
137233 137240    0.0
Name: new_cases, dtype: float64
137234 137241    16130.0
Name: new_cases, dtype: float64
137235 137242    8467.0
Name: new_cases, dtype: float64
137236 137243    0.0
Name: new_cases, dtype: float64
137237 137244    7960.0
Name: new_cases, dtype: float64
137238 137245    7592.0
Name: new_cases, dtype: float64
137239 137246    6904.0
Name: new_cases, dtype: float64
137240 137247    6978.0
Name: new_cases, dtype: float64
137241 137248    7496.0
Name: new_cases, dtype: float64
137242 137249    7305.0
Name: new_cases, dtype: float64
137243 137250    7057.0
Name: new_cases, dtype: float64
137244 137251    7079.0
Name: new_cases, dtype: float64
137245 137252    6343.0
Name: new_cases, dtype: float64
137246 137253    5947.0
Name: new_cases, dtype: float64
137247 137254    6524.0
Name: new_cases, dtype: float64
137248 137255    6901.0
Name: new_cases, dtype: float64
137249 137256    6855.0
Name: new_cases, dtype: float64
137250 137257    6595.0
Name: new_cases, dtype: float64
137251 137258    7006.0
Name: new_cases, dtype: float64
137252 137259    6428.0
Name: new_cases, dtype: float64
137253 137260    5126.0
Name: new_cases, dtype: float64
137254 137261    5857.0
Name: new_cases, dtype: float64
137255 137262    12894.0
Name: new_cases, dtype: float64
137256 137263    6073.0
Name: new_cases, dtype: float64
137257 137264    0.0
Name: new_cases, dtype: float64
137258 137265    5854.0
Name: new_cases, dtype: float64
137259 137266    4753.0
Name: new_cases, dtype: float64
137260 137267    4306.0
Name: new_cases, dtype: float64
137261 137268    4886.0
Name: new_cases, dtype: float64
137262 137269    4971.0
Name: new_cases, dtype: float64
137263 137270    4912.0
Name: new_cases, dtype: float64
137264 137271    5896.0
Name: new_cases, dtype: float64
137265 137272    8704.0
Name: new_cases, dtype: float64
137266 137273    3525.0
Name: new_cases, dtype: float64
137267 137274    0.0
Name: new_cases, dtype: float64
137268 137275    7821.0
Name: new_cases, dtype: float64
137269 137276    4193.0
Name: new_cases, dtype: float64
137270 137277    4079.0
Name: new_cases, dtype: float64
137271 137278    3787.0
Name: new_cases, dtype: float64
137272 137279    0.0
Name: new_cases, dtype: float64

137273 137280    3398.0
Name: new_cases, dtype: float64
137274 137281    2862.0
Name: new_cases, dtype: float64
137275 137282    3370.0
Name: new_cases, dtype: float64
137276 137283    7221.0
Name: new_cases, dtype: float64
137277 137284    0.0
Name: new_cases, dtype: float64
137278 137285    3132.0
Name: new_cases, dtype: float64
137279 137286    2899.0
Name: new_cases, dtype: float64
137280 137287    2525.0
Name: new_cases, dtype: float64
137281 137288    2476.0
Name: new_cases, dtype: float64
137282 137289    2532.0
Name: new_cases, dtype: float64
137283 137290    2940.0
Name: new_cases, dtype: float64
137284 137291    2671.0
Name: new_cases, dtype: float64
137285 137292    2766.0
Name: new_cases, dtype: float64
137286 137293    4969.0
Name: new_cases, dtype: float64
137287 137294    0.0
Name: new_cases, dtype: float64
137288 137295    2305.0
Name: new_cases, dtype: float64
137289 137296    2575.0
Name: new_cases, dtype: float64
137290 137297    3037.0
Name: new_cases, dtype: float64
137291 137298    3111.0
Name: new_cases, dtype: float64
137292 137299    3011.0
Name: new_cases, dtype: float64
137293 137300    3112.0
Name: new_cases, dtype: float64
137294 137301    2927.0
Name: new_cases, dtype: float64
137295 137302    3091.0
Name: new_cases, dtype: float64
137296 137303    0.0
Name: new_cases, dtype: float64
137297 137304    9674.0
Name: new_cases, dtype: float64
137298 137305    7526.0
Name: new_cases, dtype: float64
137299 137306    8263.0
Name: new_cases, dtype: float64
137300 136638    6.0
Name: new_cases, dtype: float64
137301 136639    11.0
Name: new_cases, dtype: float64
137302 136640    5.0
Name: new_cases, dtype: float64
137303 136641    7.0
Name: new_cases, dtype: float64
137304 136642    32.0
Name: new_cases, dtype: float64
137305 136643    33.0
Name: new_cases, dtype: float64
137306 136644    30.0
Name: new_cases, dtype: float64
140361 140368    51.0
Name: new_cases, dtype: float64
140362 140369    94.0
Name: new_cases, dtype: float64
140363 140370    167.0
Name: new_cases, dtype: float64
140364 140371    311.0
Name: new_cases, dtype: float64
140365 140372    566.0
Name: new_cases, dtype: float64
140366 140373    293.0
Name: new_cases, dtype: float64
140367 140374    343.0
Name: new_cases, dtype: float64
140368 140375    561.0
Name: new_cases, dtype: float64
140369 140376    1196.0
Name: new_cases, dtype: float64
140370 140377    2069.0
Name: new_cases, dtype: float64
140371 140378    1704.0
Name: new_cases, dtype: float64
140372 140379    1815.0
Name: new_cases, dtype: float64
140373 140380    1610.0
Name: new_cases, dtype: float64
140374 140381    2704.0
Name: new_cases, dtype: float64
140375 140382    2148.0
Name: new_cases, dtype: float64
140376 140383    2456.0
Name: new_cases, dtype: float64
140377 140384    2786.0
Name: new_cases, dtype: float64
140378 140385    3013.0
Name: new_cases, dtype: float64
140379 140386    3135.0
Name: new_cases, dtype: float64
140380 140387    3148.0
Name: new_cases, dtype: float64
140381 140388    3892.0
Name: new_cases, dtype: float64
140382 140389    4117.0
Name: new_cases, dtype: float64
140383 140390    4056.0
Name: new_cases, dtype: float64
140384 140391    4747.0
Name: new_cases, dtype: float64
140385 140392    5138.0
Name: new_cases, dtype: float64
140386 140393    4789.0
Name: new_cases, dtype: float64
140387 140394    4093.0
Name: new_cases, dtype: float64
140388 140395    4062.0
Name: new_cases, dtype: float64
140389 140396    4281.0
Name: new_cases, dtype: float64
140390 140397    4801.0
Name: new_cases, dtype: float64
140391 140398    4353.0
Name: new_cases, dtype: float64
140392 140399    3783.0
Name: new_cases, dtype: float64
140393 140400    3977.0
Name: new_cases, dtype: float64
140394 140401    4674.0
Name: new_cases, dtype: float64
140395 140402    4611.0
Name: new_cases, dtype: float64
140396 140403    3083.0
Name: new_cases, dtype: float64
140397 140404    3116.0
Name: new_cases, dtype: float64
140398 140405    3122.0
Name: new_cases, dtype: float64
140399 140406    2861.0
Name: new_cases, dtype: float64
140400 140407    2357.0
Name: new_cases, dtype: float64
140401 140408    2131.0
Name: new_cases, dtype: float64
140402 140409    2392.0
Name: new_cases, dtype: float64
140403 140410    2936.0
Name: new_cases, dtype: float64
140404 140411    2615.0
Name: new_cases, dtype: float64
140405 140412    2188.0
Name: new_cases, dtype: float64
140406 140413    1983.0
Name: new_cases, dtype: float64
140407 140414    1670.0
Name: new_cases, dtype: float64
140408 140415    1614.0
Name: new_cases, dtype: float64
140409 140416    1832.0
Name: new_cases, dtype: float64
140410 140417    2253.0
Name: new_cases, dtype: float64
140411 140418    1977.0
Name: new_cases, dtype: float64
140412 140419    1848.0
Name: new_cases, dtype: float64
140413 140420    1546.0
Name: new_cases, dtype: float64
140414 140421    1542.0
Name: new_cases, dtype: float64
140415 140422    1114.0
Name: new_cases, dtype: float64
140416 140423    1704.0
Name: new_cases, dtype: float64
140417 140424    1639.0
Name: new_cases, dtype: float64
140418 140425    1635.0
Name: new_cases, dtype: float64
140419 140426    1708.0
Name: new_cases, dtype: float64
140420 140427    1610.0
Name: new_cases, dtype: float64
140421 140428    1368.0
Name: new_cases, dtype: float64
140422 140429    1158.0
Name: new_cases, dtype: float64
140423 140430    1022.0
140431    1022.0
Name: new_cases, dtype: float64
140424 140430    1022.0
140431    1022.0
Name: new_cases, dtype: float64
140425 140432    972.0
Name: new_cases, dtype: float64
140426 140433    961.0
Name: new_cases, dtype: float64
140427 140434    952.0
Name: new_cases, dtype: float64
140428 140435    1186.0
Name: new_cases, dtype: float64
140429 140436    1141.0
Name: new_cases, dtype: float64
140430 140437    987.0
Name: new_cases, dtype: float64
140431 140438    948.0
Name: new_cases, dtype: float64
140432 140439    1035.0
Name: new_cases, dtype: float64
140433 140440    1182.0
Name: new_cases, dtype: float64
140434 140441    1141.0
Name: new_cases, dtype: float64
140435 140442    983.0
Name: new_cases, dtype: float64
140436 140443    839.0
Name: new_cases, dtype: float64
140437 140444    827.0
Name: new_cases, dtype: float64
140438 140445    786.0
Name: new_cases, dtype: float64
140439 140446    867.0
Name: new_cases, dtype: float64
140440 140447    988.0
Name: new_cases, dtype: float64
140441 140448    930.0
Name: new_cases, dtype: float64
140442 140449    878.0
Name: new_cases, dtype: float64
140443 140450    914.0
Name: new_cases, dtype: float64
140444 140451    989.0
Name: new_cases, dtype: float64
140445 140452    993.0
Name: new_cases, dtype: float64
140446 140453    922.0
Name: new_cases, dtype: float64
140447 140454    987.0
Name: new_cases, dtype: float64
140448 140455    1195.0
Name: new_cases, dtype: float64
140449 140456    1459.0
Name: new_cases, dtype: float64
140450 140457    1562.0
Name: new_cases, dtype: float64
140451 140458    1592.0
Name: new_cases, dtype: float64
140452 140459    1467.0
Name: new_cases, dtype: float64
140453 140460    1429.0
Name: new_cases, dtype: float64
140454 140461    1304.0
Name: new_cases, dtype: float64
140455 140462    1214.0
Name: new_cases, dtype: float64
140456 140463    1248.0
Name: new_cases, dtype: float64
140457 140464    1192.0
Name: new_cases, dtype: float64
140458 140465    1212.0
Name: new_cases, dtype: float64
140459 140466    1268.0
Name: new_cases, dtype: float64
140460 140467    1492.0
Name: new_cases, dtype: float64
140461 140468    1458.0
Name: new_cases, dtype: float64
140462 140469    1396.0
Name: new_cases, dtype: float64
140463 140470    1372.0
Name: new_cases, dtype: float64
140464 140471    1356.0
Name: new_cases, dtype: float64
140465 140472    1374.0
Name: new_cases, dtype: float64
140466 140473    1293.0
Name: new_cases, dtype: float64
140467 140474    1192.0
Name: new_cases, dtype: float64
140468 140475    1186.0
Name: new_cases, dtype: float64
140469 140476    1172.0
Name: new_cases, dtype: float64
140470 140477    1154.0
Name: new_cases, dtype: float64
140471 140478    1148.0
Name: new_cases, dtype: float64
140472 140479    1086.0
Name: new_cases, dtype: float64
140473 140480    1053.0
Name: new_cases, dtype: float64
140474 140481    1041.0
Name: new_cases, dtype: float64
140475 140482    1024.0
Name: new_cases, dtype: float64
140476 140483    1003.0
Name: new_cases, dtype: float64
140477 140484    1016.0
Name: new_cases, dtype: float64
140478 140485    1012.0
Name: new_cases, dtype: float64
140479 140486    1008.0
Name: new_cases, dtype: float64
140480 140487    992.0
Name: new_cases, dtype: float64
140481 140488    947.0
Name: new_cases, dtype: float64
140482 140489    933.0
Name: new_cases, dtype: float64
140483 140490    926.0
Name: new_cases, dtype: float64
140484 140491    918.0
Name: new_cases, dtype: float64
140485 140492    924.0
Name: new_cases, dtype: float64
140486 140493    931.0
Name: new_cases, dtype: float64
140487 140494    928.0
Name: new_cases, dtype: float64
140488 140495    902.0
Name: new_cases, dtype: float64
140489 140496    913.0
Name: new_cases, dtype: float64
140490 140497    937.0
Name: new_cases, dtype: float64

140491 140498    921.0
Name: new_cases, dtype: float64
140492 140499    927.0
Name: new_cases, dtype: float64
140493 140500    919.0
Name: new_cases, dtype: float64
140494 140501    963.0
Name: new_cases, dtype: float64
140495 140502    942.0
Name: new_cases, dtype: float64
140496 140503    967.0
Name: new_cases, dtype: float64
140497 140504    982.0
Name: new_cases, dtype: float64
140498 140505    996.0
Name: new_cases, dtype: float64
140499 140506    987.0
Name: new_cases, dtype: float64
140500 140507    995.0
Name: new_cases, dtype: float64
140501 140508    1083.0
Name: new_cases, dtype: float64
140502 140509    1178.0
Name: new_cases, dtype: float64
140503 140510    1153.0
Name: new_cases, dtype: float64
140504 140511    1185.0
Name: new_cases, dtype: float64
140505 140512    1172.0
Name: new_cases, dtype: float64
140506 140513    1182.0
Name: new_cases, dtype: float64
140507 140514    1193.0
Name: new_cases, dtype: float64
140508 140515    1183.0
Name: new_cases, dtype: float64
140509 140516    1212.0
Name: new_cases, dtype: float64
140510 140517    1243.0
Name: new_cases, dtype: float64
140511 140518    1226.0
Name: new_cases, dtype: float64
140512 140519    1256.0
Name: new_cases, dtype: float64
140513 140520    1192.0
Name: new_cases, dtype: float64
140514 140521    1233.0
Name: new_cases, dtype: float64
140515 140522    1263.0
Name: new_cases, dtype: float64
140516 140523    1303.0
Name: new_cases, dtype: float64
140517 140524    1412.0
Name: new_cases, dtype: float64
140518 140525    1203.0
Name: new_cases, dtype: float64
140519 140526    1309.0
Name: new_cases, dtype: float64
140520 140527    1217.0
Name: new_cases, dtype: float64
140521 140528    1443.0
Name: new_cases, dtype: float64
140522 140529    1502.0
Name: new_cases, dtype: float64
140523 140530    1313.0
Name: new_cases, dtype: float64
140524 140531    1491.0
Name: new_cases, dtype: float64
140525 140532    1517.0
Name: new_cases, dtype: float64
140526 140533    1549.0
Name: new_cases, dtype: float64
140527 140534    1482.0
Name: new_cases, dtype: float64
140528 140535    1587.0
Name: new_cases, dtype: float64
140529 140536    1572.0
Name: new_cases, dtype: float64
140530 140537    1596.0
Name: new_cases, dtype: float64
140531 140538    1642.0
Name: new_cases, dtype: float64
140532 140539    1612.0
Name: new_cases, dtype: float64
140533 140540    1673.0
Name: new_cases, dtype: float64
140534 140541    1578.0
Name: new_cases, dtype: float64
140535 140542    1703.0
Name: new_cases, dtype: float64
140536 140543    1761.0
Name: new_cases, dtype: float64
140537 140544    1673.0
Name: new_cases, dtype: float64
140538 140545    1512.0
Name: new_cases, dtype: float64
140539 140546    1671.0
Name: new_cases, dtype: float64
140540 140547    1509.0
Name: new_cases, dtype: float64
140541 140548    1527.0
Name: new_cases, dtype: float64
140542 140549    1716.0
Name: new_cases, dtype: float64
140543 140550    1742.0
Name: new_cases, dtype: float64
140544 140551    1771.0
Name: new_cases, dtype: float64
140545 140552    1648.0
Name: new_cases, dtype: float64
140546 140553    1771.0
Name: new_cases, dtype: float64
140547 140554    1538.0
Name: new_cases, dtype: float64
140548 140555    1519.0
Name: new_cases, dtype: float64
140549 140556    1743.0
Name: new_cases, dtype: float64
140550 140557    1692.0
Name: new_cases, dtype: float64
140551 140558    1767.0
Name: new_cases, dtype: float64
140552 140559    1721.0
Name: new_cases, dtype: float64
140553 140560    1665.0
Name: new_cases, dtype: float64
140554 140561    1511.0
Name: new_cases, dtype: float64
140555 140562    1467.0
Name: new_cases, dtype: float64
140556 140563    1412.0
Name: new_cases, dtype: float64
140557 140564    1427.0
Name: new_cases, dtype: float64
140558 140565    1391.0
Name: new_cases, dtype: float64
140559 140566    1407.0
Name: new_cases, dtype: float64
140560 140567    1442.0
Name: new_cases, dtype: float64
140561 140568    1502.0
Name: new_cases, dtype: float64
140562 140569    1429.0
Name: new_cases, dtype: float64
140563 140570    1603.0
Name: new_cases, dtype: float64
140564 140571    1511.0
Name: new_cases, dtype: float64
140565 140572    1581.0
Name: new_cases, dtype: float64
140566 140573    1615.0
Name: new_cases, dtype: float64
140567 140574    1629.0
Name: new_cases, dtype: float64
140568 140575    1649.0
Name: new_cases, dtype: float64
140569 140576    1502.0
Name: new_cases, dtype: float64
140570 140577    1614.0
Name: new_cases, dtype: float64
140571 140578    1632.0
Name: new_cases, dtype: float64
140572 140579    1671.0
Name: new_cases, dtype: float64
140573 140580    1693.0
Name: new_cases, dtype: float64
140574 140581    1812.0
Name: new_cases, dtype: float64
140575 140582    1723.0
Name: new_cases, dtype: float64
140576 140583    1815.0
Name: new_cases, dtype: float64
140577 140584    2026.0
Name: new_cases, dtype: float64
140578 140585    1894.0
Name: new_cases, dtype: float64
140579 140586    2013.0
Name: new_cases, dtype: float64
140580 140587    2102.0
Name: new_cases, dtype: float64
140581 140588    2165.0
Name: new_cases, dtype: float64
140582 140589    2091.0
Name: new_cases, dtype: float64
140583 140590    2017.0
Name: new_cases, dtype: float64
140584 140591    2198.0
Name: new_cases, dtype: float64
140585 140592    2209.0
Name: new_cases, dtype: float64
140586 140593    2305.0
Name: new_cases, dtype: float64
140587 140594    2319.0
Name: new_cases, dtype: float64
140588 140595    2322.0
Name: new_cases, dtype: float64
140589 140596    2213.0
Name: new_cases, dtype: float64
140590 140597    2106.0
Name: new_cases, dtype: float64
140591 140598    2302.0
Name: new_cases, dtype: float64
140592 140599    2343.0
Name: new_cases, dtype: float64
140593 140600    2391.0
Name: new_cases, dtype: float64
140594 140601    2311.0
Name: new_cases, dtype: float64
140595 140602    2436.0
Name: new_cases, dtype: float64
140596 140603    2483.0
Name: new_cases, dtype: float64
140597 140604    2516.0
Name: new_cases, dtype: float64
140598 140605    2576.0
Name: new_cases, dtype: float64
140599 140606    2529.0
Name: new_cases, dtype: float64
140600 140607    2693.0
Name: new_cases, dtype: float64
140601 140608    2841.0
Name: new_cases, dtype: float64
140602 140609    3045.0
Name: new_cases, dtype: float64
140603 140610    3116.0
Name: new_cases, dtype: float64
140604 140611    3223.0
Name: new_cases, dtype: float64
140605 140612    3316.0
Name: new_cases, dtype: float64
140606 140613    3819.0
Name: new_cases, dtype: float64
140607 140614    4215.0
Name: new_cases, dtype: float64
140608 140615    4542.0
Name: new_cases, dtype: float64
140609 140616    5103.0
Name: new_cases, dtype: float64
140610 140617    5532.0
Name: new_cases, dtype: float64
140611 140618    6017.0
Name: new_cases, dtype: float64
140612 140619    6713.0
Name: new_cases, dtype: float64
140613 140620    7381.0
Name: new_cases, dtype: float64
140614 140621    6814.0
Name: new_cases, dtype: float64
140615 140622    36008.0
Name: new_cases, dtype: float64
140616 140623    44506.0
Name: new_cases, dtype: float64
140617 140624    30103.0
Name: new_cases, dtype: float64
140618 140625    29281.0
Name: new_cases, dtype: float64
140619 140626    31219.0
Name: new_cases, dtype: float64
140620 140627    30110.0
Name: new_cases, dtype: float64
140621 140628    31923.0
Name: new_cases, dtype: float64
140622 140629    32381.0
Name: new_cases, dtype: float64
140623 140630    32736.0
Name: new_cases, dtype: float64
140624 140631    31896.0
Name: new_cases, dtype: float64
140625 140632    30402.0
Name: new_cases, dtype: float64
140626 140633    32137.0
Name: new_cases, dtype: float64
140627 140634    33198.0
Name: new_cases, dtype: float64
140628 140635    31712.0
Name: new_cases, dtype: float64
140629 140637    32106.0
Name: new_cases, dtype: float64
140630 140638    29136.0
Name: new_cases, dtype: float64
140631 140639    26919.0
Name: new_cases, dtype: float64
140632 140640    29617.0
Name: new_cases, dtype: float64
140633 140641    32102.0
Name: new_cases, dtype: float64
140634 140642    29718.0
Name: new_cases, dtype: float64
140635 140643    27515.0
Name: new_cases, dtype: float64
140637 140644    26410.0
Name: new_cases, dtype: float64
140638 140645    22195.0
Name: new_cases, dtype: float64
140639 140646    20316.0
Name: new_cases, dtype: float64
140640 140647    19103.0
Name: new_cases, dtype: float64
140641 140648    19256.0
Name: new_cases, dtype: float64
140642 140649    19650.0
Name: new_cases, dtype: float64
140643 140650    18102.0
Name: new_cases, dtype: float64
140644 140651    17543.0
Name: new_cases, dtype: float64
140645 140652    15118.0
Name: new_cases, dtype: float64
140646 140653    14205.0
Name: new_cases, dtype: float64
140647 140654    15197.0
Name: new_cases, dtype: float64
140648 140655    15805.0
Name: new_cases, dtype: float64
140649 140656    15692.0
Name: new_cases, dtype: float64
140650 140657    14380.0
Name: new_cases, dtype: float64
140651 140658    12203.0
Name: new_cases, dtype: float64
140652 140659    11180.0
Name: new_cases, dtype: float64
140653 140660    9877.0
Name: new_cases, dtype: float64
140654 140661    13695.0
Name: new_cases, dtype: float64
140655 140662    14494.0
Name: new_cases, dtype: float64

140656 140663    13830.0
Name: new_cases, dtype: float64
140657 140664    12171.0
Name: new_cases, dtype: float64
140658 140665    11479.0
Name: new_cases, dtype: float64
140659 140666    9537.0
Name: new_cases, dtype: float64
140660 140667    9138.0
Name: new_cases, dtype: float64
140661 140668    10220.0
Name: new_cases, dtype: float64
140662 140669    9809.0
Name: new_cases, dtype: float64
140663 140670    9554.0
Name: new_cases, dtype: float64
140664 140671    8962.0
Name: new_cases, dtype: float64
140665 140672    8314.0
Name: new_cases, dtype: float64
140666 140673    7550.0
Name: new_cases, dtype: float64
140667 140674    6436.0
Name: new_cases, dtype: float64
140668 140675    5862.0
Name: new_cases, dtype: float64
140669 140676    6818.0
Name: new_cases, dtype: float64
140670 140677    6435.0
Name: new_cases, dtype: float64
140671 140678    6289.0
Name: new_cases, dtype: float64
140672 140679    5967.0
Name: new_cases, dtype: float64
140673 140680    5856.0
Name: new_cases, dtype: float64
140674 140681    5277.0
Name: new_cases, dtype: float64
140675 140682    5642.0
Name: new_cases, dtype: float64
140676 140683    7103.0
Name: new_cases, dtype: float64
140677 140684    7489.0
Name: new_cases, dtype: float64
140678 140685    7279.0
Name: new_cases, dtype: float64
140679 140686    6912.0
Name: new_cases, dtype: float64
140680 140687    6871.0
Name: new_cases, dtype: float64
140681 140688    6562.0
Name: new_cases, dtype: float64
140682 140689    7719.0
Name: new_cases, dtype: float64
140683 140690    7795.0
Name: new_cases, dtype: float64
140684 140691    8102.0
Name: new_cases, dtype: float64
140685 140692    7909.0
Name: new_cases, dtype: float64
140686 140693    7901.0
Name: new_cases, dtype: float64
140687 140694    7897.0
Name: new_cases, dtype: float64
140688 140695    6670.0
Name: new_cases, dtype: float64
140689 140696    8103.0
Name: new_cases, dtype: float64
140690 140697    8636.0
Name: new_cases, dtype: float64
140691 140698    8642.0
Name: new_cases, dtype: float64
140692 140699    7590.0
Name: new_cases, dtype: float64
140693 140700    7763.0
Name: new_cases, dtype: float64
140694 140701    7706.0
Name: new_cases, dtype: float64
140695 140702    6287.0
Name: new_cases, dtype: float64
140696 140703    7945.0
Name: new_cases, dtype: float64
140697 140704    7906.0
Name: new_cases, dtype: float64
140698 140705    7325.0
Name: new_cases, dtype: float64
140699 140706    7241.0
Name: new_cases, dtype: float64
140700 140707    7419.0
Name: new_cases, dtype: float64
140701 140708    7857.0
Name: new_cases, dtype: float64
140702 140709    6546.0
Name: new_cases, dtype: float64
140703 140710    8104.0
Name: new_cases, dtype: float64
140704 140711    9107.0
Name: new_cases, dtype: float64
140705 140712    9561.0
Name: new_cases, dtype: float64
140706 140713    9572.0
Name: new_cases, dtype: float64
140707 140714    9205.0
Name: new_cases, dtype: float64
140708 140715    9193.0
Name: new_cases, dtype: float64
140709 140716    8424.0
Name: new_cases, dtype: float64
140710 140717    9891.0
Name: new_cases, dtype: float64
140711 140718    11837.0
Name: new_cases, dtype: float64
140712 140719    11520.0
Name: new_cases, dtype: float64
140713 140720    11322.0
Name: new_cases, dtype: float64
140714 140721    11302.0
Name: new_cases, dtype: float64
140715 140722    11770.0
Name: new_cases, dtype: float64
140716 140723    11187.0
Name: new_cases, dtype: float64
140717 140724    13215.0
Name: new_cases, dtype: float64
140718 140725    13755.0
Name: new_cases, dtype: float64
140719 140726    14556.0
Name: new_cases, dtype: float64
140720 140727    14046.0
Name: new_cases, dtype: float64
140721 140728    14941.0
Name: new_cases, dtype: float64
140722 140729    15082.0
Name: new_cases, dtype: float64
140723 140730    13378.0
Name: new_cases, dtype: float64
140724 140731    15503.0
Name: new_cases, dtype: float64
140725 140732    16749.0
Name: new_cases, dtype: float64
140726 140733    18912.0
Name: new_cases, dtype: float64
140727 140734    20049.0
Name: new_cases, dtype: float64
140728 140735    21030.0
Name: new_cases, dtype: float64
140729 140736    21061.0
Name: new_cases, dtype: float64
140730 140737    20428.0
Name: new_cases, dtype: float64
140731 140738    22216.0
Name: new_cases, dtype: float64
140732 140739    26182.0
Name: new_cases, dtype: float64
140733 140740    29762.0
Name: new_cases, dtype: float64
140734 140741    28731.0
Name: new_cases, dtype: float64
140735 140742    29081.0
Name: new_cases, dtype: float64
140736 140743    30021.0
Name: new_cases, dtype: float64
140737 140744    29058.0
Name: new_cases, dtype: float64
140738 140745    32404.0
Name: new_cases, dtype: float64
140739 140746    37303.0
Name: new_cases, dtype: float64
140740 140747    39302.0
Name: new_cases, dtype: float64
140741 140748    40806.0
Name: new_cases, dtype: float64
140742 140749    42308.0
Name: new_cases, dtype: float64
140743 140750    44756.0
Name: new_cases, dtype: float64
140744 140751    41998.0
Name: new_cases, dtype: float64
140745 140752    42551.0
Name: new_cases, dtype: float64
140746 140753    49584.0
Name: new_cases, dtype: float64
140747 140754    54740.0
Name: new_cases, dtype: float64
140748 140755    55941.0
Name: new_cases, dtype: float64
140749 140756    55791.0
Name: new_cases, dtype: float64
140750 140757    52676.0
Name: new_cases, dtype: float64
140751 140758    50678.0
Name: new_cases, dtype: float64
140752 140759    54562.0
Name: new_cases, dtype: float64
140753 140760    59187.0
Name: new_cases, dtype: float64
140754 140761    62797.0
Name: new_cases, dtype: float64
140755 140762    61400.0
Name: new_cases, dtype: float64
140756 140763    63082.0
Name: new_cases, dtype: float64
140757 140764    62606.0
Name: new_cases, dtype: float64
140758 140765    55802.0
Name: new_cases, dtype: float64
140759 140766    55149.0
Name: new_cases, dtype: float64
140760 140767    61028.0
Name: new_cases, dtype: float64
140761 140768    61967.0
Name: new_cases, dtype: float64
140762 140769    54791.0
Name: new_cases, dtype: float64
140763 140770    49438.0
Name: new_cases, dtype: float64
140764 140771    40596.0
Name: new_cases, dtype: float64
140765 140772    38553.0
Name: new_cases, dtype: float64
140766 140773    37312.0
Name: new_cases, dtype: float64
140767 140774    43301.0
Name: new_cases, dtype: float64
140768 140775    40444.0
Name: new_cases, dtype: float64
140769 140776    37674.0
Name: new_cases, dtype: float64
140770 140777    31891.0
Name: new_cases, dtype: float64
140771 140778    28817.0
Name: new_cases, dtype: float64
140772 140779    25980.0
Name: new_cases, dtype: float64
140773 140780    24733.0
Name: new_cases, dtype: float64
140774 140781    28997.0
Name: new_cases, dtype: float64
140775 140782    26476.0
Name: new_cases, dtype: float64
140776 140783    22388.0
Name: new_cases, dtype: float64
140777 140784    20107.0
Name: new_cases, dtype: float64
140778 140785    18052.0
Name: new_cases, dtype: float64
140779 140786    15191.0
Name: new_cases, dtype: float64
140780 140787    13604.0
Name: new_cases, dtype: float64
140781 140788    14497.0
Name: new_cases, dtype: float64
140782 140789    13029.0
Name: new_cases, dtype: float64
140783 140790    11534.0
Name: new_cases, dtype: float64
140784 140791    11394.0
Name: new_cases, dtype: float64
140785 140792    11472.0
Name: new_cases, dtype: float64
140786 140793    10512.0
Name: new_cases, dtype: float64
140787 140794    10174.0
Name: new_cases, dtype: float64
140788 140795    11937.0
Name: new_cases, dtype: float64
140789 140796    11553.0
Name: new_cases, dtype: float64
140790 140797    9385.0
Name: new_cases, dtype: float64
140791 140798    9528.0
Name: new_cases, dtype: float64
140792 140799    8697.0
Name: new_cases, dtype: float64
140793 140800    7839.0
Name: new_cases, dtype: float64
140794 140801    7523.0
Name: new_cases, dtype: float64
140795 140802    9375.0
Name: new_cases, dtype: float64
140796 140803    8738.0
Name: new_cases, dtype: float64
140797 140804    8426.0
Name: new_cases, dtype: float64
140798 140805    7773.0
Name: new_cases, dtype: float64
140799 140806    7656.0
Name: new_cases, dtype: float64
140800 140807    6933.0
Name: new_cases, dtype: float64
140801 140808    6493.0
Name: new_cases, dtype: float64
140802 140809    7112.0
Name: new_cases, dtype: float64
140803 140810    7181.0
Name: new_cases, dtype: float64
140804 140811    6602.0
Name: new_cases, dtype: float64
140805 140812    6169.0
Name: new_cases, dtype: float64
140806 140813    6126.0
Name: new_cases, dtype: float64
140807 140814    5386.0
Name: new_cases, dtype: float64
140808 140815    5647.0
Name: new_cases, dtype: float64
140809 140816    6609.0
Name: new_cases, dtype: float64
140810 140817    6454.0
Name: new_cases, dtype: float64
140811 140818    6408.0
Name: new_cases, dtype: float64
140812 140819    6261.0
Name: new_cases, dtype: float64
140813 140820    6076.0
Name: new_cases, dtype: float64
140814 140821    5012.0
Name: new_cases, dtype: float64
140815 140822    5626.0
Name: new_cases, dtype: float64
140816 140823    5955.0
Name: new_cases, dtype: float64
140817 140824    6221.0
Name: new_cases, dtype: float64
140818 140825    5904.0
Name: new_cases, dtype: float64
140819 140826    5575.0
Name: new_cases, dtype: float64
140820 140827    5480.0
Name: new_cases, dtype: float64

140821 140828    5091.0
Name: new_cases, dtype: float64
140822 140829    5294.0
Name: new_cases, dtype: float64
140823 140830    6143.0
Name: new_cases, dtype: float64
140824 140831    5809.0
Name: new_cases, dtype: float64
140825 140832    5703.0
Name: new_cases, dtype: float64
140826 140833    5630.0
Name: new_cases, dtype: float64
140827 140834    5266.0
Name: new_cases, dtype: float64
140828 140835    4883.0
Name: new_cases, dtype: float64
140829 140836    5283.0
Name: new_cases, dtype: float64
140830 140837    5846.0
Name: new_cases, dtype: float64
140831 140838    5496.0
Name: new_cases, dtype: float64
140832 140839    5288.0
Name: new_cases, dtype: float64
140833 140840    4891.0
Name: new_cases, dtype: float64
140834 140841    4537.0
Name: new_cases, dtype: float64
140835 140842    4418.0
Name: new_cases, dtype: float64
140836 140843    4678.0
Name: new_cases, dtype: float64
140837 140844    5299.0
Name: new_cases, dtype: float64
140838 140845    5160.0
Name: new_cases, dtype: float64
140839 140846    5171.0
Name: new_cases, dtype: float64
140840 140847    5670.0
Name: new_cases, dtype: float64
140841 140848    5530.0
Name: new_cases, dtype: float64
140842 140849    5261.0
Name: new_cases, dtype: float64
140843 140850    5404.0
Name: new_cases, dtype: float64
140844 140851    6285.0
Name: new_cases, dtype: float64
140845 140852    6907.0
Name: new_cases, dtype: float64
140846 140853    7304.0
Name: new_cases, dtype: float64
140847 140854    6918.0
Name: new_cases, dtype: float64
140848 140855    7666.0
Name: new_cases, dtype: float64
140849 140856    0.0
Name: new_cases, dtype: float64
140850 140857    15347.0
Name: new_cases, dtype: float64
140851 140858    8780.0
Name: new_cases, dtype: float64
140852 140859    8151.0
Name: new_cases, dtype: float64
140853 140860    9586.0
Name: new_cases, dtype: float64
140854 140861    11094.0
Name: new_cases, dtype: float64
140855 140862    12381.0
Name: new_cases, dtype: float64
140856 140863    14230.0
Name: new_cases, dtype: float64
140857 140864    16809.0
Name: new_cases, dtype: float64
140858 140865    19761.0
Name: new_cases, dtype: float64
140859 140866    22291.0
Name: new_cases, dtype: float64
140860 140867    22161.0
Name: new_cases, dtype: float64
140861 140868    22083.0
Name: new_cases, dtype: float64
140862 140869    22332.0
Name: new_cases, dtype: float64
140863 140870    20890.0
Name: new_cases, dtype: float64
140864 140871    22898.0
Name: new_cases, dtype: float64
140865 140872    24832.0
Name: new_cases, dtype: float64
140866 140873    26822.0
Name: new_cases, dtype: float64
140867 140874    24297.0
Name: new_cases, dtype: float64
140868 140875    23957.0
Name: new_cases, dtype: float64
140869 140876    25100.0
Name: new_cases, dtype: float64
140870 140877    0.0
Name: new_cases, dtype: float64
140871 140878    46400.0
Name: new_cases, dtype: float64
140872 140879    26597.0
Name: new_cases, dtype: float64
140873 140880    27356.0
Name: new_cases, dtype: float64
140874 140881    22261.0
Name: new_cases, dtype: float64
140875 140882    21372.0
Name: new_cases, dtype: float64
140876 140883    19949.0
Name: new_cases, dtype: float64
140877 140884    18847.0
Name: new_cases, dtype: float64
140878 140885    18163.0
Name: new_cases, dtype: float64
140879 140886    21692.0
Name: new_cases, dtype: float64
140880 140887    19944.0
Name: new_cases, dtype: float64
140881 140888    19320.0
Name: new_cases, dtype: float64
140882 140889    19918.0
Name: new_cases, dtype: float64
140883 140890    19351.0
Name: new_cases, dtype: float64
140884 140891    18622.0
Name: new_cases, dtype: float64
140885 140892    18857.0
Name: new_cases, dtype: float64
140886 140893    19191.0
Name: new_cases, dtype: float64
140887 140894    19970.0
Name: new_cases, dtype: float64
140888 140895    19616.0
Name: new_cases, dtype: float64
140889 140896    18340.0
Name: new_cases, dtype: float64
140890 140897    17912.0
Name: new_cases, dtype: float64
140891 140898    17332.0
Name: new_cases, dtype: float64
140892 140899    19557.0
Name: new_cases, dtype: float64
140893 140900    21893.0
Name: new_cases, dtype: float64
140894 140901    23946.0
Name: new_cases, dtype: float64
140895 140902    23496.0
Name: new_cases, dtype: float64
140896 140903    22857.0
Name: new_cases, dtype: float64
140897 140904    20033.0
Name: new_cases, dtype: float64
140898 140905    19391.0
Name: new_cases, dtype: float64
140899 140906    20962.0
Name: new_cases, dtype: float64
140900 140907    23638.0
Name: new_cases, dtype: float64
140901 140908    23914.0
Name: new_cases, dtype: float64
140902 140909    23846.0
Name: new_cases, dtype: float64
140903 140910    23562.0
Name: new_cases, dtype: float64
140904 140911    22923.0
Name: new_cases, dtype: float64
140905 140912    21352.0
Name: new_cases, dtype: float64
140906 140913    24613.0
Name: new_cases, dtype: float64
140907 140914    27802.0
Name: new_cases, dtype: float64
140908 140915    28224.0
Name: new_cases, dtype: float64
140909 140916    28118.0
Name: new_cases, dtype: float64
140910 140917    27692.0
Name: new_cases, dtype: float64
140911 140918    26161.0
Name: new_cases, dtype: float64
140912 140919    26398.0
Name: new_cases, dtype: float64
140913 140920    27688.0
Name: new_cases, dtype: float64
140914 140921    29338.0
Name: new_cases, dtype: float64
140915 140922    28168.0
Name: new_cases, dtype: float64
140916 140923    27844.0
Name: new_cases, dtype: float64
140917 140924    27197.0
Name: new_cases, dtype: float64
140918 140925    26145.0
Name: new_cases, dtype: float64
140919 140926    25861.0
Name: new_cases, dtype: float64
140920 140927    27188.0
Name: new_cases, dtype: float64
140921 140928    28892.0
Name: new_cases, dtype: float64
140922 140929    29386.0
Name: new_cases, dtype: float64
140923 140930    29104.0
Name: new_cases, dtype: float64
140924 140931    28873.0
Name: new_cases, dtype: float64
140925 140932    27973.0
Name: new_cases, dtype: float64
140926 140933    27351.0
Name: new_cases, dtype: float64
140927 140934    28810.0
Name: new_cases, dtype: float64
140928 140935    29802.0
Name: new_cases, dtype: float64
140929 140936    30468.0
Name: new_cases, dtype: float64
140930 140937    29989.0
Name: new_cases, dtype: float64
140931 140938    30201.0
Name: new_cases, dtype: float64
140932 140939    28645.0
Name: new_cases, dtype: float64
140933 140940    28370.0
Name: new_cases, dtype: float64
140934 140941    30563.0
Name: new_cases, dtype: float64
140935 140942    33860.0
Name: new_cases, dtype: float64
140936 140943    31248.0
Name: new_cases, dtype: float64
140937 140944    30709.0
Name: new_cases, dtype: float64
140938 140945    30694.0
Name: new_cases, dtype: float64
140939 140946    28537.0
Name: new_cases, dtype: float64
140940 140947    24114.0
Name: new_cases, dtype: float64
140941 140948    29240.0
Name: new_cases, dtype: float64
140942 140949    30862.0
Name: new_cases, dtype: float64
140943 140950    29760.0
Name: new_cases, dtype: float64
140944 140951    28465.0
Name: new_cases, dtype: float64
140945 140952    28192.0
Name: new_cases, dtype: float64
140946 140953    26217.0
Name: new_cases, dtype: float64
140947 140954    24792.0
Name: new_cases, dtype: float64
140948 140955    27663.0
Name: new_cases, dtype: float64
140949 140956    29643.0
Name: new_cases, dtype: float64
140950 140957    26896.0
Name: new_cases, dtype: float64
140951 140958    25528.0
Name: new_cases, dtype: float64
140952 140959    24409.0
Name: new_cases, dtype: float64
140953 140960    23096.0
Name: new_cases, dtype: float64
140954 140961    23948.0
Name: new_cases, dtype: float64
140955 140962    28678.0
Name: new_cases, dtype: float64
140956 140963    29796.0
Name: new_cases, dtype: float64
140957 140964    29764.0
Name: new_cases, dtype: float64
140958 140965    29482.0
Name: new_cases, dtype: float64
140959 140966    28193.0
Name: new_cases, dtype: float64
140960 140967    27474.0
Name: new_cases, dtype: float64
140961 140968    27304.0
Name: new_cases, dtype: float64
140962 140969    27824.0
Name: new_cases, dtype: float64
140963 140970    28662.0
Name: new_cases, dtype: float64
140964 140971    27259.0
Name: new_cases, dtype: float64
140965 140972    24898.0
Name: new_cases, dtype: float64
140966 140973    23637.0
Name: new_cases, dtype: float64
140967 140974    22583.0
Name: new_cases, dtype: float64
140968 140975    21624.0
Name: new_cases, dtype: float64
140969 140976    23852.0
Name: new_cases, dtype: float64
140970 140977    25101.0
Name: new_cases, dtype: float64
140971 140978    23867.0
Name: new_cases, dtype: float64
140972 140979    22234.0
Name: new_cases, dtype: float64
140973 140980    23810.0
Name: new_cases, dtype: float64
140974 140981    23347.0
Name: new_cases, dtype: float64
140975 140982    21177.0
Name: new_cases, dtype: float64
140976 140983    24856.0
Name: new_cases, dtype: float64
140977 140984    28170.0
Name: new_cases, dtype: float64
140978 140985    27592.0
Name: new_cases, dtype: float64
140979 140986    24467.0
Name: new_cases, dtype: float64
140980 140987    24002.0
Name: new_cases, dtype: float64
140981 140988    23759.0
Name: new_cases, dtype: float64
140982 140989    21655.0
Name: new_cases, dtype: float64
140983 140990    24317.0
Name: new_cases, dtype: float64
140984 140991    25216.0
Name: new_cases, dtype: float64

140985 140992    22556.0
Name: new_cases, dtype: float64
140986 140993    21747.0
Name: new_cases, dtype: float64
140987 140994    21495.0
Name: new_cases, dtype: float64
140988 140995    20374.0
Name: new_cases, dtype: float64
140989 140996    19357.0
Name: new_cases, dtype: float64
140990 140997    20033.0
Name: new_cases, dtype: float64
140991 140998    22687.0
Name: new_cases, dtype: float64
140992 140999    20874.0
Name: new_cases, dtype: float64
140993 141000    19696.0
Name: new_cases, dtype: float64
140994 141001    18561.0
Name: new_cases, dtype: float64
140995 141002    19255.0
Name: new_cases, dtype: float64
140996 141003    17956.0
Name: new_cases, dtype: float64
140997 141004    18796.0
Name: new_cases, dtype: float64
140998 141005    21477.0
Name: new_cases, dtype: float64
140999 141006    19872.0
Name: new_cases, dtype: float64
141000 141007    18100.0
Name: new_cases, dtype: float64
141001 141008    18141.0
Name: new_cases, dtype: float64
141002 141009    17644.0
Name: new_cases, dtype: float64
141003 141010    16910.0
Name: new_cases, dtype: float64
141004 141011    18762.0
Name: new_cases, dtype: float64
141005 141012    19859.0
Name: new_cases, dtype: float64
141006 141013    19095.0
Name: new_cases, dtype: float64
141007 141014    18771.0
Name: new_cases, dtype: float64
141008 141015    18910.0
Name: new_cases, dtype: float64
141009 141016    0.0
Name: new_cases, dtype: float64
141010 141017    40608.0
Name: new_cases, dtype: float64
141011 141018    26099.0
Name: new_cases, dtype: float64
141012 141019    32176.0
Name: new_cases, dtype: float64
141013 141020    0.0
Name: new_cases, dtype: float64
141014 141021    76365.0
Name: new_cases, dtype: float64
141015 141022    40786.0
Name: new_cases, dtype: float64
141016 141023    36731.0
Name: new_cases, dtype: float64
141017 141024    33520.0
Name: new_cases, dtype: float64
141018 141025    44869.0
Name: new_cases, dtype: float64
141019 141026    54724.0
Name: new_cases, dtype: float64
141020 141027    66467.0
Name: new_cases, dtype: float64
141021 141028    68413.0
Name: new_cases, dtype: float64
141022 141029    63214.0
Name: new_cases, dtype: float64
141023 141030    66237.0
Name: new_cases, dtype: float64
141024 Series([], Name: new_cases, dtype: float64)
141025 Series([], Name: new_cases, dtype: float64)
141026 Series([], Name: new_cases, dtype: float64)
141027 Series([], Name: new_cases, dtype: float64)
141028 Series([], Name: new_cases, dtype: float64)
141029 Series([], Name: new_cases, dtype: float64)
141030 Series([], Name: new_cases, dtype: float64)
142704 142711    0.0
Name: new_cases, dtype: float64
142705 142712    0.0
Name: new_cases, dtype: float64
142706 142713    0.0
Name: new_cases, dtype: float64
142707 142714    2.0
Name: new_cases, dtype: float64
142708 142715    0.0
Name: new_cases, dtype: float64
142709 142716    0.0
Name: new_cases, dtype: float64
142710 142717    4.0
Name: new_cases, dtype: float64
142711 142718    7.0
Name: new_cases, dtype: float64
142712 142719    0.0
Name: new_cases, dtype: float64
142713 142720    2.0
Name: new_cases, dtype: float64
142714 142721    13.0
Name: new_cases, dtype: float64
142715 142722    18.0
Name: new_cases, dtype: float64
142716 142723    26.0
Name: new_cases, dtype: float64
142717 142724    0.0
Name: new_cases, dtype: float64
142718 142725    24.0
Name: new_cases, dtype: float64
142719 142726    48.0
Name: new_cases, dtype: float64
142720 142727    51.0
Name: new_cases, dtype: float64
142721 142728    114.0
Name: new_cases, dtype: float64
142722 142729    46.0
Name: new_cases, dtype: float64
142723 142730    119.0
Name: new_cases, dtype: float64
142724 142731    73.0
Name: new_cases, dtype: float64
142725 142732    97.0
Name: new_cases, dtype: float64
142726 142733    149.0
Name: new_cases, dtype: float64
142727 142734    103.0
Name: new_cases, dtype: float64
142728 142735    175.0
Name: new_cases, dtype: float64
142729 142736    153.0
Name: new_cases, dtype: float64
142730 142737    83.0
Name: new_cases, dtype: float64
142731 142738    11.0
Name: new_cases, dtype: float64
142732 142739    143.0
Name: new_cases, dtype: float64
142733 142740    206.0
Name: new_cases, dtype: float64
142734 142741    224.0
Name: new_cases, dtype: float64
142735 142742    311.0
Name: new_cases, dtype: float64
142736 142743    308.0
Name: new_cases, dtype: float64
142737 142744    266.0
Name: new_cases, dtype: float64
142738 142745    325.0
Name: new_cases, dtype: float64
142739 142746    270.0
Name: new_cases, dtype: float64
142740 142747    392.0
Name: new_cases, dtype: float64
142741 142748    397.0
Name: new_cases, dtype: float64
142742 142749    501.0
Name: new_cases, dtype: float64
142743 142750    444.0
Name: new_cases, dtype: float64
142744 142751    343.0
Name: new_cases, dtype: float64
142745 142752    261.0
Name: new_cases, dtype: float64
142746 142753    415.0
Name: new_cases, dtype: float64
142747 142754    467.0
Name: new_cases, dtype: float64
142748 142755    578.0
Name: new_cases, dtype: float64
142749 142756    477.0
Name: new_cases, dtype: float64
142750 142757    478.0
Name: new_cases, dtype: float64
142751 142758    492.0
Name: new_cases, dtype: float64
142752 142759    392.0
Name: new_cases, dtype: float64
142753 142760    401.0
Name: new_cases, dtype: float64
142754 142761    456.0
Name: new_cases, dtype: float64
142755 142762    540.0
Name: new_cases, dtype: float64
142756 142763    455.0
Name: new_cases, dtype: float64
142757 142764    550.0
Name: new_cases, dtype: float64
142758 142765    502.0
Name: new_cases, dtype: float64
142759 142766    418.0
Name: new_cases, dtype: float64
142760 142767    366.0
Name: new_cases, dtype: float64
142761 142768    487.0
Name: new_cases, dtype: float64
142762 142769    507.0
Name: new_cases, dtype: float64
142763 142770    504.0
Name: new_cases, dtype: float64
142764 142771    515.0
Name: new_cases, dtype: float64
142765 142772    522.0
Name: new_cases, dtype: float64
142766 142773    416.0
Name: new_cases, dtype: float64
142767 142774    375.0
Name: new_cases, dtype: float64
142768 142775    402.0
Name: new_cases, dtype: float64
142769 142776    422.0
Name: new_cases, dtype: float64
142770 142777    483.0
Name: new_cases, dtype: float64
142771 142778    528.0
Name: new_cases, dtype: float64
142772 142779    433.0
Name: new_cases, dtype: float64
142773 142780    325.0
Name: new_cases, dtype: float64
142774 142781    260.0
Name: new_cases, dtype: float64
142775 142782    354.0
Name: new_cases, dtype: float64
142776 142783    476.0
Name: new_cases, dtype: float64
142777 142784    442.0
Name: new_cases, dtype: float64
142778 142785    432.0
Name: new_cases, dtype: float64
142779 142786    406.0
Name: new_cases, dtype: float64
142780 142787    259.0
Name: new_cases, dtype: float64
142781 142788    339.0
Name: new_cases, dtype: float64
142782 142789    321.0
Name: new_cases, dtype: float64
142783 142790    477.0
Name: new_cases, dtype: float64
142784 142791    429.0
Name: new_cases, dtype: float64
142785 142792    393.0
Name: new_cases, dtype: float64
142786 142793    468.0
Name: new_cases, dtype: float64
142787 142794    890.0
Name: new_cases, dtype: float64
142788 142795    333.0
Name: new_cases, dtype: float64
142789 142796    490.0
Name: new_cases, dtype: float64
142790 142797    596.0
Name: new_cases, dtype: float64
142791 142798    561.0
Name: new_cases, dtype: float64
142792 142799    559.0
Name: new_cases, dtype: float64
142793 142800    498.0
Name: new_cases, dtype: float64
142794 142801    478.0
Name: new_cases, dtype: float64
142795 142802    402.0
Name: new_cases, dtype: float64
142796 142803    536.0
Name: new_cases, dtype: float64
142797 142804    691.0
Name: new_cases, dtype: float64
142798 142805    709.0
Name: new_cases, dtype: float64
142799 142806    762.0
Name: new_cases, dtype: float64
142800 142807    674.0
Name: new_cases, dtype: float64
142801 142808    685.0
Name: new_cases, dtype: float64
142802 142809    673.0
Name: new_cases, dtype: float64
142803 142810    777.0
Name: new_cases, dtype: float64
142804 142811    847.0
Name: new_cases, dtype: float64
142805 142812    922.0
Name: new_cases, dtype: float64
142806 142813    860.0
Name: new_cases, dtype: float64
142807 142814    746.0
Name: new_cases, dtype: float64
142808 142815    695.0
Name: new_cases, dtype: float64
142809 142816    845.0
Name: new_cases, dtype: float64
142810 142817    951.0
Name: new_cases, dtype: float64
142811 142818    1002.0
Name: new_cases, dtype: float64
142812 142819    1121.0
Name: new_cases, dtype: float64
142813 142820    957.0
Name: new_cases, dtype: float64
142814 142821    924.0
Name: new_cases, dtype: float64
142815 142822    682.0
Name: new_cases, dtype: float64
142816 142823    716.0
Name: new_cases, dtype: float64
142817 142824    670.0
Name: new_cases, dtype: float64
142818 142825    897.0
Name: new_cases, dtype: float64

142819 142826    884.0
Name: new_cases, dtype: float64
142820 142827    923.0
Name: new_cases, dtype: float64
142821 142828    840.0
Name: new_cases, dtype: float64
142822 142829    585.0
Name: new_cases, dtype: float64
142823 142830    569.0
Name: new_cases, dtype: float64
142824 142831    835.0
Name: new_cases, dtype: float64
142825 142832    828.0
Name: new_cases, dtype: float64
142826 142833    831.0
Name: new_cases, dtype: float64
142827 142834    825.0
Name: new_cases, dtype: float64
142828 142835    706.0
Name: new_cases, dtype: float64
142829 142836    638.0
Name: new_cases, dtype: float64
142830 142837    646.0
Name: new_cases, dtype: float64
142831 142838    848.0
Name: new_cases, dtype: float64
142832 142839    861.0
Name: new_cases, dtype: float64
142833 142840    826.0
Name: new_cases, dtype: float64
142834 142841    867.0
Name: new_cases, dtype: float64
142835 142842    744.0
Name: new_cases, dtype: float64
142836 142843    690.0
Name: new_cases, dtype: float64
142837 142844    687.0
Name: new_cases, dtype: float64
142838 142845    841.0
Name: new_cases, dtype: float64
142839 142846    874.0
Name: new_cases, dtype: float64
142840 142847    1004.0
Name: new_cases, dtype: float64
142841 142848    1144.0
Name: new_cases, dtype: float64
142842 142849    944.0
Name: new_cases, dtype: float64
142843 142850    835.0
Name: new_cases, dtype: float64
142844 142851    934.0
Name: new_cases, dtype: float64
142845 142852    1048.0
Name: new_cases, dtype: float64
142846 142853    1222.0
Name: new_cases, dtype: float64
142847 142854    1104.0
Name: new_cases, dtype: float64
142848 142855    1205.0
Name: new_cases, dtype: float64
142849 142856    1152.0
Name: new_cases, dtype: float64
142850 142857    1020.0
Name: new_cases, dtype: float64
142851 142858    1099.0
Name: new_cases, dtype: float64
142852 142859    1289.0
Name: new_cases, dtype: float64
142853 142860    1346.0
Name: new_cases, dtype: float64
142854 142861    1503.0
Name: new_cases, dtype: float64
142855 142862    1516.0
Name: new_cases, dtype: float64
142856 142863    1233.0
Name: new_cases, dtype: float64
142857 142864    1045.0
Name: new_cases, dtype: float64
142858 142865    1211.0
Name: new_cases, dtype: float64
142859 142866    1481.0
Name: new_cases, dtype: float64
142860 142867    1632.0
Name: new_cases, dtype: float64
142861 142868    1781.0
Name: new_cases, dtype: float64
142862 142869    1878.0
Name: new_cases, dtype: float64
142863 142870    1695.0
Name: new_cases, dtype: float64
142864 142871    1517.0
Name: new_cases, dtype: float64
142865 142872    1646.0
Name: new_cases, dtype: float64
142866 142873    2005.0
Name: new_cases, dtype: float64
142867 142874    2152.0
Name: new_cases, dtype: float64
142868 142875    2138.0
Name: new_cases, dtype: float64
142869 142876    2389.0
Name: new_cases, dtype: float64
142870 142877    2042.0
Name: new_cases, dtype: float64
142871 142878    1855.0
Name: new_cases, dtype: float64
142872 142879    1715.0
Name: new_cases, dtype: float64
142873 142880    1704.0
Name: new_cases, dtype: float64
142874 142881    2010.0
Name: new_cases, dtype: float64
142875 142882    2509.0
Name: new_cases, dtype: float64
142876 142883    2579.0
Name: new_cases, dtype: float64
142877 142884    2179.0
Name: new_cases, dtype: float64
142878 142885    2202.0
Name: new_cases, dtype: float64
142879 142886    2147.0
Name: new_cases, dtype: float64
142880 142887    2554.0
Name: new_cases, dtype: float64
142881 142888    2467.0
Name: new_cases, dtype: float64
142882 142889    2769.0
Name: new_cases, dtype: float64
142883 142890    2897.0
Name: new_cases, dtype: float64
142884 142891    2205.0
Name: new_cases, dtype: float64
142885 142892    2253.0
Name: new_cases, dtype: float64
142886 142893    2490.0
Name: new_cases, dtype: float64
142887 142894    2597.0
Name: new_cases, dtype: float64
142888 142895    2635.0
Name: new_cases, dtype: float64
142889 142896    3227.0
Name: new_cases, dtype: float64
142890 142897    3185.0
Name: new_cases, dtype: float64
142891 142898    2564.0
Name: new_cases, dtype: float64
142892 142899    2557.0
Name: new_cases, dtype: float64
142893 142900    2999.0
Name: new_cases, dtype: float64
142894 142901    3016.0
Name: new_cases, dtype: float64
142895 142902    3679.0
Name: new_cases, dtype: float64
142896 142903    3330.0
Name: new_cases, dtype: float64
142897 142904    3345.0
Name: new_cases, dtype: float64
142898 142905    3071.0
Name: new_cases, dtype: float64
142899 142906    2781.0
Name: new_cases, dtype: float64
142900 142907    2990.0
Name: new_cases, dtype: float64
142901 142908    3598.0
Name: new_cases, dtype: float64
142902 142909    3478.0
Name: new_cases, dtype: float64
142903 142910    3665.0
Name: new_cases, dtype: float64
142904 142911    3935.0
Name: new_cases, dtype: float64
142905 142912    3233.0
Name: new_cases, dtype: float64
142906 142913    2780.0
Name: new_cases, dtype: float64
142907 142914    3730.0
Name: new_cases, dtype: float64
142908 142915    4137.0
Name: new_cases, dtype: float64
142909 142916    4179.0
Name: new_cases, dtype: float64
142910 142917    4751.0
Name: new_cases, dtype: float64
142911 142918    4785.0
Name: new_cases, dtype: float64
142912 142919    4263.0
Name: new_cases, dtype: float64
142913 142920    3905.0
Name: new_cases, dtype: float64
142914 142921    4482.0
Name: new_cases, dtype: float64
142915 142922    4887.0
Name: new_cases, dtype: float64
142916 142923    5545.0
Name: new_cases, dtype: float64
142917 142924    5961.0
Name: new_cases, dtype: float64
142918 142925    5901.0
Name: new_cases, dtype: float64
142919 142926    4960.0
Name: new_cases, dtype: float64
142920 142927    4606.0
Name: new_cases, dtype: float64
142921 142928    5311.0
Name: new_cases, dtype: float64
142922 142929    5780.0
Name: new_cases, dtype: float64
142923 142930    5260.0
Name: new_cases, dtype: float64
142924 142931    6205.0
Name: new_cases, dtype: float64
142925 142932    6629.0
Name: new_cases, dtype: float64
142926 142933    5445.0
Name: new_cases, dtype: float64
142927 142934    4986.0
Name: new_cases, dtype: float64
142928 142935    5680.0
Name: new_cases, dtype: float64
142929 142936    6975.0
Name: new_cases, dtype: float64
142930 142937    7320.0
Name: new_cases, dtype: float64
142931 142938    7780.0
Name: new_cases, dtype: float64
142932 142939    7275.0
Name: new_cases, dtype: float64
142933 142940    6406.0
Name: new_cases, dtype: float64
142934 142941    5625.0
Name: new_cases, dtype: float64
142935 142942    6885.0
Name: new_cases, dtype: float64
142936 142943    7790.0
Name: new_cases, dtype: float64
142937 142944    7641.0
Name: new_cases, dtype: float64
142938 142945    8608.0
Name: new_cases, dtype: float64
142939 142946    9058.0
Name: new_cases, dtype: float64
142940 142947    8243.0
Name: new_cases, dtype: float64
142941 142948    6994.0
Name: new_cases, dtype: float64
142942 142949    9116.0
Name: new_cases, dtype: float64
142943 142950    9809.0
Name: new_cases, dtype: float64
142944 142951    10138.0
Name: new_cases, dtype: float64
142945 142952    9935.0
Name: new_cases, dtype: float64
142946 142953    11033.0
Name: new_cases, dtype: float64
142947 142954    9647.0
Name: new_cases, dtype: float64
142948 142955    8908.0
Name: new_cases, dtype: float64
142949 142956    10391.0
Name: new_cases, dtype: float64
142950 142957    10879.0
Name: new_cases, dtype: float64
142951 142958    11332.0
Name: new_cases, dtype: float64
142952 142959    12053.0
Name: new_cases, dtype: float64
142953 142960    12785.0
Name: new_cases, dtype: float64
142954 142961    10940.0
Name: new_cases, dtype: float64
142955 142962    10048.0
Name: new_cases, dtype: float64
142956 142963    12177.0
Name: new_cases, dtype: float64
142957 142964    12764.0
Name: new_cases, dtype: float64
142958 142965    13630.0
Name: new_cases, dtype: float64
142959 142966    14834.0
Name: new_cases, dtype: float64
142960 142967    14864.0
Name: new_cases, dtype: float64
142961 142968    12365.0
Name: new_cases, dtype: float64
142962 142969    11227.0
Name: new_cases, dtype: float64
142963 142970    12526.0
Name: new_cases, dtype: float64
142964 142971    14164.0
Name: new_cases, dtype: float64
142965 142972    15623.0
Name: new_cases, dtype: float64
142966 142973    16494.0
Name: new_cases, dtype: float64
142967 142974    16585.0
Name: new_cases, dtype: float64
142968 142975    13271.0
Name: new_cases, dtype: float64
142969 142976    10238.0
Name: new_cases, dtype: float64
142970 142977    12774.0
Name: new_cases, dtype: float64
142971 142978    13443.0
Name: new_cases, dtype: float64
142972 142979    14812.0
Name: new_cases, dtype: float64
142973 142980    15456.0
Name: new_cases, dtype: float64
142974 142981    14157.0
Name: new_cases, dtype: float64
142975 142982    11928.0
Name: new_cases, dtype: float64
142976 142983    8985.0
Name: new_cases, dtype: float64

142977 142984    11156.0
Name: new_cases, dtype: float64
142978 142985    12937.0
Name: new_cases, dtype: float64
142979 142986    13736.0
Name: new_cases, dtype: float64
142980 142987    13893.0
Name: new_cases, dtype: float64
142981 142988    13219.0
Name: new_cases, dtype: float64
142982 142989    9605.0
Name: new_cases, dtype: float64
142983 142990    6877.0
Name: new_cases, dtype: float64
142984 142991    8840.0
Name: new_cases, dtype: float64
142985 142992    11057.0
Name: new_cases, dtype: float64
142986 142993    12474.0
Name: new_cases, dtype: float64
142987 142994    13066.0
Name: new_cases, dtype: float64
142988 142995    12179.0
Name: new_cases, dtype: float64
142989 142996    8763.0
Name: new_cases, dtype: float64
142990 142997    6978.0
Name: new_cases, dtype: float64
142991 142998    8949.0
Name: new_cases, dtype: float64
142992 142999    10572.0
Name: new_cases, dtype: float64
142993 143000    11926.0
Name: new_cases, dtype: float64
142994 143001    11458.0
Name: new_cases, dtype: float64
142995 143002    8134.0
Name: new_cases, dtype: float64
142996 143003    6548.0
Name: new_cases, dtype: float64
142997 143004    4809.0
Name: new_cases, dtype: float64
142998 143005    7402.0
Name: new_cases, dtype: float64
142999 143006    8404.0
Name: new_cases, dtype: float64
143000 143007    10117.0
Name: new_cases, dtype: float64
143001 143008    9858.0
Name: new_cases, dtype: float64
143002 143009    5401.0
Name: new_cases, dtype: float64
143003 143010    4881.0
Name: new_cases, dtype: float64
143004 143011    4494.0
Name: new_cases, dtype: float64
143005 143012    5625.0
Name: new_cases, dtype: float64
143006 143013    7226.0
Name: new_cases, dtype: float64
143007 143014    9320.0
Name: new_cases, dtype: float64
143008 143015    5998.0
Name: new_cases, dtype: float64
143009 143016    5143.0
Name: new_cases, dtype: float64
143010 143017    5322.0
Name: new_cases, dtype: float64
143011 143018    4585.0
Name: new_cases, dtype: float64
143012 143019    5393.0
Name: new_cases, dtype: float64
143013 143020    6715.0
Name: new_cases, dtype: float64
143014 143021    8385.0
Name: new_cases, dtype: float64
143015 143022    8620.0
Name: new_cases, dtype: float64
143016 143023    8151.0
Name: new_cases, dtype: float64
143017 143024    6398.0
Name: new_cases, dtype: float64
143018 143025    3382.0
Name: new_cases, dtype: float64
143019 143026    4231.0
Name: new_cases, dtype: float64
143020 143027    4729.0
Name: new_cases, dtype: float64
143021 143028    5926.0
Name: new_cases, dtype: float64
143022 143029    5679.0
Name: new_cases, dtype: float64
143023 143030    5264.0
Name: new_cases, dtype: float64
143024 143031    4242.0
Name: new_cases, dtype: float64
143025 143032    2807.0
Name: new_cases, dtype: float64
143026 143033    3038.0
Name: new_cases, dtype: float64
143027 143034    4053.0
Name: new_cases, dtype: float64
143028 143035    5811.0
Name: new_cases, dtype: float64
143029 143036    5453.0
Name: new_cases, dtype: float64
143030 143037    4966.0
Name: new_cases, dtype: float64
143031 143038    3453.0
Name: new_cases, dtype: float64
143032 143039    2287.0
Name: new_cases, dtype: float64
143033 143040    2631.0
Name: new_cases, dtype: float64
143034 143041    3537.0
Name: new_cases, dtype: float64
143035 143042    5333.0
Name: new_cases, dtype: float64
143036 143043    5167.0
Name: new_cases, dtype: float64
143037 143044    4558.0
Name: new_cases, dtype: float64
143038 143045    3610.0
Name: new_cases, dtype: float64
143039 143046    2356.0
Name: new_cases, dtype: float64
143040 143047    2867.0
Name: new_cases, dtype: float64
143041 143048    3645.0
Name: new_cases, dtype: float64
143042 143049    5274.0
Name: new_cases, dtype: float64
143043 143050    4995.0
Name: new_cases, dtype: float64
143044 143051    5403.0
Name: new_cases, dtype: float64
143045 143052    3311.0
Name: new_cases, dtype: float64
143046 143053    2540.0
Name: new_cases, dtype: float64
143047 143054    3346.0
Name: new_cases, dtype: float64
143048 143055    4485.0
Name: new_cases, dtype: float64
143049 143056    6441.0
Name: new_cases, dtype: float64
143050 143057    6722.0
Name: new_cases, dtype: float64
143051 143058    6473.0
Name: new_cases, dtype: float64
143052 143059    4663.0
Name: new_cases, dtype: float64
143053 143060    3355.0
Name: new_cases, dtype: float64
143054 143061    4326.0
Name: new_cases, dtype: float64
143055 143062    5990.0
Name: new_cases, dtype: float64
143056 143063    8278.0
Name: new_cases, dtype: float64
143057 143064    8134.0
Name: new_cases, dtype: float64
143058 143065    8297.0
Name: new_cases, dtype: float64
143059 143066    5958.0
Name: new_cases, dtype: float64
143060 143067    4406.0
Name: new_cases, dtype: float64
143061 143068    5460.0
Name: new_cases, dtype: float64
143062 143069    7354.0
Name: new_cases, dtype: float64
143063 143070    10179.0
Name: new_cases, dtype: float64
143064 143071    10273.0
Name: new_cases, dtype: float64
143065 143072    9257.0
Name: new_cases, dtype: float64
143066 143073    7284.0
Name: new_cases, dtype: float64
143067 143074    5680.0
Name: new_cases, dtype: float64
143068 143075    3364.0
Name: new_cases, dtype: float64
143069 143076    6480.0
Name: new_cases, dtype: float64
143070 143077    9187.0
Name: new_cases, dtype: float64
143071 143078    13045.0
Name: new_cases, dtype: float64
143072 143079    13376.0
Name: new_cases, dtype: float64
143073 143080    9110.0
Name: new_cases, dtype: float64
143074 143081    6882.0
Name: new_cases, dtype: float64
143075 143082    9730.0
Name: new_cases, dtype: float64
143076 143083    11921.0
Name: new_cases, dtype: float64
143077 143084    15143.0
Name: new_cases, dtype: float64
143078 143085    15937.0
Name: new_cases, dtype: float64
143079 143086    15376.0
Name: new_cases, dtype: float64
143080 143087    11229.0
Name: new_cases, dtype: float64
143081 143088    7982.0
Name: new_cases, dtype: float64
143082 143089    11564.0
Name: new_cases, dtype: float64
143083 143090    14266.0
Name: new_cases, dtype: float64
143084 143091    16762.0
Name: new_cases, dtype: float64
143085 143092    18226.0
Name: new_cases, dtype: float64
143086 143093    17526.0
Name: new_cases, dtype: float64
143087 143094    12041.0
Name: new_cases, dtype: float64
143088 143095    8468.0
Name: new_cases, dtype: float64
143089 143096    10648.0
Name: new_cases, dtype: float64
143090 143097    11345.0
Name: new_cases, dtype: float64
143091 143098    17681.0
Name: new_cases, dtype: float64
143092 143099    20003.0
Name: new_cases, dtype: float64
143093 143100    20456.0
Name: new_cases, dtype: float64
143094 143101    13858.0
Name: new_cases, dtype: float64
143095 143102    10300.0
Name: new_cases, dtype: float64
143096 143103    13398.0
Name: new_cases, dtype: float64
143097 143104    15535.0
Name: new_cases, dtype: float64
143098 143105    19546.0
Name: new_cases, dtype: float64
143099 143106    19799.0
Name: new_cases, dtype: float64
143100 143107    17587.0
Name: new_cases, dtype: float64
143101 143108    12238.0
Name: new_cases, dtype: float64
143102 143109    7985.0
Name: new_cases, dtype: float64
143103 143110    11809.0
Name: new_cases, dtype: float64
143104 143111    14677.0
Name: new_cases, dtype: float64
143105 143112    16553.0
Name: new_cases, dtype: float64
143106 143113    17602.0
Name: new_cases, dtype: float64
143107 143114    15104.0
Name: new_cases, dtype: float64
143108 143115    10407.0
Name: new_cases, dtype: float64
143109 143116    6630.0
Name: new_cases, dtype: float64
143110 143117    9060.0
Name: new_cases, dtype: float64
143111 143118    12287.0
Name: new_cases, dtype: float64
143112 143119    16357.0
Name: new_cases, dtype: float64
143113 143120    14400.0
Name: new_cases, dtype: float64
143114 143121    12841.0
Name: new_cases, dtype: float64
143115 143122    8058.0
Name: new_cases, dtype: float64
143116 143123    5184.0
Name: new_cases, dtype: float64
143117 143124    8037.0
Name: new_cases, dtype: float64
143118 143125    9709.0
Name: new_cases, dtype: float64
143119 143126    11750.0
Name: new_cases, dtype: float64
143120 143127    10190.0
Name: new_cases, dtype: float64
143121 143128    8672.0
Name: new_cases, dtype: float64
143122 143129    5217.0
Name: new_cases, dtype: float64
143123 143130    2879.0
Name: new_cases, dtype: float64
143124 143131    2589.0
Name: new_cases, dtype: float64
143125 143132    2694.0
Name: new_cases, dtype: float64
143126 143133    6159.0
Name: new_cases, dtype: float64
143127 143134    8529.0
Name: new_cases, dtype: float64
143128 143135    8841.0
Name: new_cases, dtype: float64
143129 143136    5501.0
Name: new_cases, dtype: float64
143130 143137    2944.0
Name: new_cases, dtype: float64
143131 143138    2334.0
Name: new_cases, dtype: float64
143132 143139    4659.0
Name: new_cases, dtype: float64
143133 143140    6934.0
Name: new_cases, dtype: float64
143134 143141    7686.0
Name: new_cases, dtype: float64
143135 143142    6919.0
Name: new_cases, dtype: float64
143136 143143    3748.0
Name: new_cases, dtype: float64
143137 143144    2260.0
Name: new_cases, dtype: float64
143138 143145    4221.0
Name: new_cases, dtype: float64
143139 143146    5259.0
Name: new_cases, dtype: float64
143140 143147    5285.0
Name: new_cases, dtype: float64

143141 143148    5110.0
Name: new_cases, dtype: float64
143142 143149    4730.0
Name: new_cases, dtype: float64
143143 143150    2657.0
Name: new_cases, dtype: float64
143144 143151    1457.0
Name: new_cases, dtype: float64
143145 143152    2730.0
Name: new_cases, dtype: float64
143146 143153    3521.0
Name: new_cases, dtype: float64
143147 143154    3637.0
Name: new_cases, dtype: float64
143148 143155    3432.0
Name: new_cases, dtype: float64
143149 143156    3230.0
Name: new_cases, dtype: float64
143150 143157    1839.0
Name: new_cases, dtype: float64
143151 143158    1156.0
Name: new_cases, dtype: float64
143152 143159    2268.0
Name: new_cases, dtype: float64
143153 143160    2335.0
Name: new_cases, dtype: float64
143154 143161    2707.0
Name: new_cases, dtype: float64
143155 143162    2393.0
Name: new_cases, dtype: float64
143156 143163    2031.0
Name: new_cases, dtype: float64
143157 143164    1075.0
Name: new_cases, dtype: float64
143158 143165    667.0
Name: new_cases, dtype: float64
143159 143166    1736.0
Name: new_cases, dtype: float64
143160 143167    1521.0
Name: new_cases, dtype: float64
143161 143168    1924.0
Name: new_cases, dtype: float64
143162 143169    1747.0
Name: new_cases, dtype: float64
143163 143170    1424.0
Name: new_cases, dtype: float64
143164 143171    1019.0
Name: new_cases, dtype: float64
143165 143172    591.0
Name: new_cases, dtype: float64
143166 143173    1197.0
Name: new_cases, dtype: float64
143167 143174    1233.0
Name: new_cases, dtype: float64
143168 143175    1388.0
Name: new_cases, dtype: float64
143169 143176    1178.0
Name: new_cases, dtype: float64
143170 143177    1079.0
Name: new_cases, dtype: float64
143171 143178    723.0
Name: new_cases, dtype: float64
143172 143179    587.0
Name: new_cases, dtype: float64
143173 143180    573.0
Name: new_cases, dtype: float64
143174 143181    1126.0
Name: new_cases, dtype: float64
143175 143182    1248.0
Name: new_cases, dtype: float64
143176 143183    1204.0
Name: new_cases, dtype: float64
143177 143184    1109.0
Name: new_cases, dtype: float64
143178 143185    819.0
Name: new_cases, dtype: float64
143179 143186    677.0
Name: new_cases, dtype: float64
143180 143187    581.0
Name: new_cases, dtype: float64
143181 143188    1042.0
Name: new_cases, dtype: float64
143182 143189    1120.0
Name: new_cases, dtype: float64
143183 143190    1123.0
Name: new_cases, dtype: float64
143184 143191    1141.0
Name: new_cases, dtype: float64
143185 143192    826.0
Name: new_cases, dtype: float64
143186 143193    702.0
Name: new_cases, dtype: float64
143187 143194    993.0
Name: new_cases, dtype: float64
143188 143195    1062.0
Name: new_cases, dtype: float64
143189 143196    1074.0
Name: new_cases, dtype: float64
143190 143197    1122.0
Name: new_cases, dtype: float64
143191 143198    982.0
Name: new_cases, dtype: float64
143192 143199    779.0
Name: new_cases, dtype: float64
143193 143200    665.0
Name: new_cases, dtype: float64
143194 143201    972.0
Name: new_cases, dtype: float64
143195 143202    1043.0
Name: new_cases, dtype: float64
143196 143203    1123.0
Name: new_cases, dtype: float64
143197 143204    1253.0
Name: new_cases, dtype: float64
143198 143205    1117.0
Name: new_cases, dtype: float64
143199 143206    837.0
Name: new_cases, dtype: float64
143200 143207    717.0
Name: new_cases, dtype: float64
143201 143208    1134.0
Name: new_cases, dtype: float64
143202 143209    1195.0
Name: new_cases, dtype: float64
143203 143210    1259.0
Name: new_cases, dtype: float64
143204 143211    1298.0
Name: new_cases, dtype: float64
143205 143212    1297.0
Name: new_cases, dtype: float64
143206 143213    841.0
Name: new_cases, dtype: float64
143207 143214    774.0
Name: new_cases, dtype: float64
143208 143215    1227.0
Name: new_cases, dtype: float64
143209 143216    1267.0
Name: new_cases, dtype: float64
143210 143217    1396.0
Name: new_cases, dtype: float64
143211 143218    1510.0
Name: new_cases, dtype: float64
143212 143219    1459.0
Name: new_cases, dtype: float64
143213 143220    1024.0
Name: new_cases, dtype: float64
143214 143221    804.0
Name: new_cases, dtype: float64
143215 143222    1366.0
Name: new_cases, dtype: float64
143216 143223    1520.0
Name: new_cases, dtype: float64
143217 143224    1608.0
Name: new_cases, dtype: float64
143218 143225    1668.0
Name: new_cases, dtype: float64
143219 143226    1647.0
Name: new_cases, dtype: float64
143220 143227    1214.0
Name: new_cases, dtype: float64
143221 143228    906.0
Name: new_cases, dtype: float64
143222 143229    1394.0
Name: new_cases, dtype: float64
143223 143230    1735.0
Name: new_cases, dtype: float64
143224 143231    1868.0
Name: new_cases, dtype: float64
143225 143232    1879.0
Name: new_cases, dtype: float64
143226 143233    1966.0
Name: new_cases, dtype: float64
143227 143234    1309.0
Name: new_cases, dtype: float64
143228 143235    1028.0
Name: new_cases, dtype: float64
143229 143236    1499.0
Name: new_cases, dtype: float64
143230 143237    2049.0
Name: new_cases, dtype: float64
143231 143238    2159.0
Name: new_cases, dtype: float64
143232 143239    2190.0
Name: new_cases, dtype: float64
143233 143240    2318.0
Name: new_cases, dtype: float64
143234 143241    1590.0
Name: new_cases, dtype: float64
143235 143242    1189.0
Name: new_cases, dtype: float64
143236 143243    1265.0
Name: new_cases, dtype: float64
143237 143244    1291.0
Name: new_cases, dtype: float64
143238 143245    2117.0
Name: new_cases, dtype: float64
143239 143246    2559.0
Name: new_cases, dtype: float64
143240 143247    2588.0
Name: new_cases, dtype: float64
143241 143248    2394.0
Name: new_cases, dtype: float64
143242 143249    1216.0
Name: new_cases, dtype: float64
143243 143250    1795.0
Name: new_cases, dtype: float64
143244 143251    2488.0
Name: new_cases, dtype: float64
143245 143252    2871.0
Name: new_cases, dtype: float64
143246 143253    3079.0
Name: new_cases, dtype: float64
143247 143254    2614.0
Name: new_cases, dtype: float64
143248 143255    2142.0
Name: new_cases, dtype: float64
143249 143256    1142.0
Name: new_cases, dtype: float64
143250 143257    2562.0
Name: new_cases, dtype: float64
143251 143258    3123.0
Name: new_cases, dtype: float64
143252 143259    4010.0
Name: new_cases, dtype: float64
143253 143260    3948.0
Name: new_cases, dtype: float64
143254 143261    4196.0
Name: new_cases, dtype: float64
143255 143262    2515.0
Name: new_cases, dtype: float64
143256 143263    1522.0
Name: new_cases, dtype: float64
143257 143264    3640.0
Name: new_cases, dtype: float64
143258 143265    4938.0
Name: new_cases, dtype: float64
143259 143266    6050.0
Name: new_cases, dtype: float64
143260 143267    6940.0
Name: new_cases, dtype: float64
143261 143268    6564.0
Name: new_cases, dtype: float64
143262 143269    4332.0
Name: new_cases, dtype: float64
143263 143270    2633.0
Name: new_cases, dtype: float64
143264 143271    5542.0
Name: new_cases, dtype: float64
143265 143272    7152.0
Name: new_cases, dtype: float64
143266 143273    8281.0
Name: new_cases, dtype: float64
143267 143274    9495.0
Name: new_cases, dtype: float64
143268 143275    8725.0
Name: new_cases, dtype: float64
143269 143276    5130.0
Name: new_cases, dtype: float64
143270 143277    3512.0
Name: new_cases, dtype: float64
143271 143278    7071.0
Name: new_cases, dtype: float64
143272 143279    10205.0
Name: new_cases, dtype: float64
143273 143280    12315.0
Name: new_cases, dtype: float64
143274 143281    12603.0
Name: new_cases, dtype: float64
143275 143282    12396.0
Name: new_cases, dtype: float64
143276 143283    8575.0
Name: new_cases, dtype: float64
143277 143284    5452.0
Name: new_cases, dtype: float64
143278 143285    10491.0
Name: new_cases, dtype: float64
143279 143286    13316.0
Name: new_cases, dtype: float64
143280 143287    15794.0
Name: new_cases, dtype: float64
143281 143288    17047.0
Name: new_cases, dtype: float64
143282 143289    16622.0
Name: new_cases, dtype: float64
143283 143290    12102.0
Name: new_cases, dtype: float64
143284 143291    9605.0
Name: new_cases, dtype: float64
143285 143292    12772.0
Name: new_cases, dtype: float64
143286 143293    17100.0
Name: new_cases, dtype: float64
143287 143294    19691.0
Name: new_cases, dtype: float64
143288 143295    14458.0
Name: new_cases, dtype: float64
143289 143296    13840.0
Name: new_cases, dtype: float64
143290 143297    12163.0
Name: new_cases, dtype: float64
143291 143298    10415.0
Name: new_cases, dtype: float64
143292 143299    16484.0
Name: new_cases, dtype: float64
143293 143300    19823.0
Name: new_cases, dtype: float64
143294 143301    23338.0
Name: new_cases, dtype: float64
143295 143302    24721.0
Name: new_cases, dtype: float64
143296 143303    24179.0
Name: new_cases, dtype: float64
143297 143304    21761.0
Name: new_cases, dtype: float64
143298 143305    15617.0
Name: new_cases, dtype: float64
143299 143306    20112.0
Name: new_cases, dtype: float64
143300 143307    23581.0
Name: new_cases, dtype: float64
143301 143308    27097.0
Name: new_cases, dtype: float64
143302 143309    27914.0
Name: new_cases, dtype: float64
143303 143310    27246.0
Name: new_cases, dtype: float64

143304 143311    18492.0
Name: new_cases, dtype: float64
143305 143312    15017.0
Name: new_cases, dtype: float64
143306 143313    20536.0
Name: new_cases, dtype: float64
143307 143314    24479.0
Name: new_cases, dtype: float64
143308 143315    28477.0
Name: new_cases, dtype: float64
143309 143316    27606.0
Name: new_cases, dtype: float64
143310 143317    26188.0
Name: new_cases, dtype: float64
143311 143318    18556.0
Name: new_cases, dtype: float64
143312 143319    14211.0
Name: new_cases, dtype: float64
143313 143320    20149.0
Name: new_cases, dtype: float64
143314 143321    24445.0
Name: new_cases, dtype: float64
143315 143322    25922.0
Name: new_cases, dtype: float64
143316 143323    25240.0
Name: new_cases, dtype: float64
143317 143324    24760.0
Name: new_cases, dtype: float64
143318 143325    15693.0
Name: new_cases, dtype: float64
143319 143326    12012.0
Name: new_cases, dtype: float64
143320 143327    17514.0
Name: new_cases, dtype: float64
143321 143328    19879.0
Name: new_cases, dtype: float64
143322 143329    21810.0
Name: new_cases, dtype: float64
143323 143330    21271.0
Name: new_cases, dtype: float64
143324 143331    19474.0
Name: new_cases, dtype: float64
143325 143332    11856.0
Name: new_cases, dtype: float64
143326 143333    8612.0
Name: new_cases, dtype: float64
143327 143334    13826.0
Name: new_cases, dtype: float64
143328 143335    15328.0
Name: new_cases, dtype: float64
143329 143336    17873.0
Name: new_cases, dtype: float64
143330 143337    16802.0
Name: new_cases, dtype: float64
143331 143338    15027.0
Name: new_cases, dtype: float64
143332 143339    8245.0
Name: new_cases, dtype: float64
143333 143340    6494.0
Name: new_cases, dtype: float64
143334 143341    11212.0
Name: new_cases, dtype: float64
143335 143342    12601.0
Name: new_cases, dtype: float64
143336 143343    14163.0
Name: new_cases, dtype: float64
143337 143344    14391.0
Name: new_cases, dtype: float64
143338 143345    13806.0
Name: new_cases, dtype: float64
143339 143346    7211.0
Name: new_cases, dtype: float64
143340 143347    5045.0
Name: new_cases, dtype: float64
143341 143348    9205.0
Name: new_cases, dtype: float64
143342 143349    9895.0
Name: new_cases, dtype: float64
143343 143350    12884.0
Name: new_cases, dtype: float64
143344 143351    11817.0
Name: new_cases, dtype: float64
143345 143352    10606.0
Name: new_cases, dtype: float64
143346 143353    5721.0
Name: new_cases, dtype: float64
143347 143354    4423.0
Name: new_cases, dtype: float64
143348 143355    7716.0
Name: new_cases, dtype: float64
143349 143356    8461.0
Name: new_cases, dtype: float64
143350 143357    9918.0
Name: new_cases, dtype: float64
143351 143358    9215.0
Name: new_cases, dtype: float64
143352 143359    7806.0
Name: new_cases, dtype: float64
143353 143360    3889.0
Name: new_cases, dtype: float64
143354 143361    2814.0
Name: new_cases, dtype: float64
143355 143362    6281.0
Name: new_cases, dtype: float64
143356 143363    6589.0
Name: new_cases, dtype: float64
143357 143364    7533.0
Name: new_cases, dtype: float64
143358 143365    6828.0
Name: new_cases, dtype: float64
143359 143366    5451.0
Name: new_cases, dtype: float64
143360 143367    2988.0
Name: new_cases, dtype: float64
143361 143368    2038.0
Name: new_cases, dtype: float64
143362 143369    2419.0
Name: new_cases, dtype: float64
143363 143370    5616.0
Name: new_cases, dtype: float64
143364 143371    6089.0
Name: new_cases, dtype: float64
143365 143372    7185.0
Name: new_cases, dtype: float64
143366 143373    5171.0
Name: new_cases, dtype: float64
143367 143374    2008.0
Name: new_cases, dtype: float64
143368 143375    1954.0
Name: new_cases, dtype: float64
143369 143376    1889.0
Name: new_cases, dtype: float64
143370 143377    4711.0
Name: new_cases, dtype: float64
143371 143378    6769.0
Name: new_cases, dtype: float64
143372 143379    7304.0
Name: new_cases, dtype: float64
143373 143380    3339.0
Name: new_cases, dtype: float64
143374 Series([], Name: new_cases, dtype: float64)
143375 Series([], Name: new_cases, dtype: float64)
143376 Series([], Name: new_cases, dtype: float64)
143377 Series([], Name: new_cases, dtype: float64)
143378 Series([], Name: new_cases, dtype: float64)
143379 Series([], Name: new_cases, dtype: float64)
143380 Series([], Name: new_cases, dtype: float64)
144092 144099    0.0
Name: new_cases, dtype: float64
144093 144100    4.0
Name: new_cases, dtype: float64
144094 144101    1.0
Name: new_cases, dtype: float64
144095 144102    0.0
Name: new_cases, dtype: float64
144096 144103    1.0
Name: new_cases, dtype: float64
144097 144104    1.0
Name: new_cases, dtype: float64
144098 144105    1.0
Name: new_cases, dtype: float64
144099 144106    1.0
Name: new_cases, dtype: float64
144100 144107    0.0
Name: new_cases, dtype: float64
144101 144108    0.0
Name: new_cases, dtype: float64
144102 144109    1.0
Name: new_cases, dtype: float64
144103 144110    0.0
Name: new_cases, dtype: float64
144104 144111    1.0
Name: new_cases, dtype: float64
144105 144112    2.0
Name: new_cases, dtype: float64
144106 144113    1.0
Name: new_cases, dtype: float64
144107 144114    0.0
Name: new_cases, dtype: float64
144108 144115    5.0
Name: new_cases, dtype: float64
144109 144116    2.0
Name: new_cases, dtype: float64
144110 144117    4.0
Name: new_cases, dtype: float64
144111 144118    3.0
Name: new_cases, dtype: float64
144112 144119    7.0
Name: new_cases, dtype: float64
144113 144120    12.0
Name: new_cases, dtype: float64
144114 144121    5.0
Name: new_cases, dtype: float64
144115 144122    33.0
Name: new_cases, dtype: float64
144116 144123    40.0
Name: new_cases, dtype: float64
144117 144124    55.0
Name: new_cases, dtype: float64
144118 144125    56.0
Name: new_cases, dtype: float64
144119 144126    49.0
Name: new_cases, dtype: float64
144120 144127    79.0
Name: new_cases, dtype: float64
144121 144128    55.0
Name: new_cases, dtype: float64
144122 144129    54.0
Name: new_cases, dtype: float64
144123 144130    147.0
Name: new_cases, dtype: float64
144124 144131    259.0
Name: new_cases, dtype: float64
144125 144132    412.0
Name: new_cases, dtype: float64
144126 144133    489.0
Name: new_cases, dtype: float64
144127 144134    479.0
Name: new_cases, dtype: float64
144128 144135    364.0
Name: new_cases, dtype: float64
144129 144136    443.0
Name: new_cases, dtype: float64
144130 144137    615.0
Name: new_cases, dtype: float64
144131 144138    768.0
Name: new_cases, dtype: float64
144132 144139    999.0
Name: new_cases, dtype: float64
144133 144140    1060.0
Name: new_cases, dtype: float64
144134 144141    1257.0
Name: new_cases, dtype: float64
144135 144142    1215.0
Name: new_cases, dtype: float64
144136 144143    1376.0
Name: new_cases, dtype: float64
144137 144144    2339.0
Name: new_cases, dtype: float64
144138 144145    2371.0
Name: new_cases, dtype: float64
144139 144146    2703.0
Name: new_cases, dtype: float64
144140 144147    3104.0
Name: new_cases, dtype: float64
144141 144148    3223.0
Name: new_cases, dtype: float64
144142 144149    2831.0
Name: new_cases, dtype: float64
144143 144150    2868.0
Name: new_cases, dtype: float64
144144 144151    4306.0
Name: new_cases, dtype: float64
144145 144152    4515.0
Name: new_cases, dtype: float64
144146 144153    4945.0
Name: new_cases, dtype: float64
144147 144154    4886.0
Name: new_cases, dtype: float64
144148 144155    4954.0
Name: new_cases, dtype: float64
144149 144156    4050.0
Name: new_cases, dtype: float64
144150 144157    3641.0
Name: new_cases, dtype: float64
144151 144158    5289.0
Name: new_cases, dtype: float64
144152 144159    5462.0
Name: new_cases, dtype: float64
144153 144160    5145.0
Name: new_cases, dtype: float64
144154 144161    4862.0
Name: new_cases, dtype: float64
144155 144162    4352.0
Name: new_cases, dtype: float64
144156 144163    3586.0
Name: new_cases, dtype: float64
144157 144164    3519.0
Name: new_cases, dtype: float64
144158 144165    4188.0
144166    4188.0
144167    4188.0
Name: new_cases, dtype: float64
144159 144165    4188.0
144166    4188.0
144167    4188.0
Name: new_cases, dtype: float64
144160 144165    4188.0
144166    4188.0
144167    4188.0
Name: new_cases, dtype: float64
144161 144168    4329.0
Name: new_cases, dtype: float64
144162 144169    5072.0
Name: new_cases, dtype: float64
144163 144170    5308.0
Name: new_cases, dtype: float64
144164 144171    4978.0
Name: new_cases, dtype: float64
144165 144172    4730.0
Name: new_cases, dtype: float64
144166 144173    3856.0
Name: new_cases, dtype: float64
144167 144174    4858.0
Name: new_cases, dtype: float64
144168 144175    4768.0
Name: new_cases, dtype: float64
144169 144176    5492.0
Name: new_cases, dtype: float64
144170 144177    5166.0
Name: new_cases, dtype: float64
144171 144178    4975.0
Name: new_cases, dtype: float64
144172 144179    3750.0
Name: new_cases, dtype: float64
144173 144180    3468.0
Name: new_cases, dtype: float64
144174 144181    4702.0
Name: new_cases, dtype: float64
144175 144182    4726.0
Name: new_cases, dtype: float64
144176 144183    5442.0
Name: new_cases, dtype: float64
144177 144184    4956.0
Name: new_cases, dtype: float64
144178 144185    4728.0
Name: new_cases, dtype: float64
144179 144186    3226.0
Name: new_cases, dtype: float64

144180 144187    2975.0
Name: new_cases, dtype: float64
144181 144188    3378.0
Name: new_cases, dtype: float64
144182 144189    3685.0
Name: new_cases, dtype: float64
144183 144190    3831.0
Name: new_cases, dtype: float64
144184 144191    3767.0
Name: new_cases, dtype: float64
144185 144192    3049.0
Name: new_cases, dtype: float64
144186 144193    2150.0
Name: new_cases, dtype: float64
144187 144194    2321.0
Name: new_cases, dtype: float64
144188 144195    3584.0
Name: new_cases, dtype: float64
144189 144196    3390.0
Name: new_cases, dtype: float64
144190 144197    3299.0
Name: new_cases, dtype: float64
144191 144198    2610.0
Name: new_cases, dtype: float64
144192 144199    2517.0
Name: new_cases, dtype: float64
144193 144200    2070.0
Name: new_cases, dtype: float64
144194 144201    1826.0
Name: new_cases, dtype: float64
144195 144202    2575.0
Name: new_cases, dtype: float64
144196 144203    3041.0
Name: new_cases, dtype: float64
144197 144204    2709.0
Name: new_cases, dtype: float64
144198 144205    2542.0
Name: new_cases, dtype: float64
144199 144206    2030.0
Name: new_cases, dtype: float64
144200 144207    1507.0
Name: new_cases, dtype: float64
144201 144208    1348.0
Name: new_cases, dtype: float64
144202 144209    1608.0
Name: new_cases, dtype: float64
144203 144210    1650.0
Name: new_cases, dtype: float64
144204 144211    1803.0
Name: new_cases, dtype: float64
144205 144212    1734.0
Name: new_cases, dtype: float64
144206 144213    1504.0
Name: new_cases, dtype: float64
144207 144214    1099.0
Name: new_cases, dtype: float64
144208 144215    1069.0
Name: new_cases, dtype: float64
144209 144216    1434.0
Name: new_cases, dtype: float64
144210 144217    1467.0
Name: new_cases, dtype: float64
144211 144218    1343.0
Name: new_cases, dtype: float64
144212 144219    1234.0
Name: new_cases, dtype: float64
144213 144220    1105.0
Name: new_cases, dtype: float64
144214 144221    793.0
Name: new_cases, dtype: float64
144215 144222    717.0
Name: new_cases, dtype: float64
144216 144223    1087.0
Name: new_cases, dtype: float64
144217 144224    1154.0
Name: new_cases, dtype: float64
144218 144225    1182.0
Name: new_cases, dtype: float64
144219 144226    1001.0
Name: new_cases, dtype: float64
144220 144227    1053.0
Name: new_cases, dtype: float64
144221 144228    887.0
Name: new_cases, dtype: float64
144222 144229    807.0
Name: new_cases, dtype: float64
144223 144230    1029.0
Name: new_cases, dtype: float64
144224 144231    1077.0
Name: new_cases, dtype: float64
144225 144232    999.0
Name: new_cases, dtype: float64
144226 144233    1020.0
Name: new_cases, dtype: float64
144227 144234    980.0
Name: new_cases, dtype: float64
144228 144235    666.0
Name: new_cases, dtype: float64
144229 144236    622.0
Name: new_cases, dtype: float64
144230 144237    892.0
Name: new_cases, dtype: float64
144231 144238    882.0
Name: new_cases, dtype: float64
144232 144239    775.0
Name: new_cases, dtype: float64
144233 144240    697.0
Name: new_cases, dtype: float64
144234 144241    638.0
Name: new_cases, dtype: float64
144235 144242    633.0
Name: new_cases, dtype: float64
144236 144243    395.0
Name: new_cases, dtype: float64
144237 144244    604.0
Name: new_cases, dtype: float64
144238 144245    403.0
Name: new_cases, dtype: float64
144239 144246    60.0
Name: new_cases, dtype: float64
144240 144247    4.0
Name: new_cases, dtype: float64
144241 144248    502.0
Name: new_cases, dtype: float64
144242 144249    624.0
Name: new_cases, dtype: float64
144243 144250    516.0
Name: new_cases, dtype: float64
144244 144251    358.0
Name: new_cases, dtype: float64
144245 144252    581.0
Name: new_cases, dtype: float64
144246 144253    630.0
Name: new_cases, dtype: float64
144247 144254    642.0
Name: new_cases, dtype: float64
144248 144255    512.0
Name: new_cases, dtype: float64
144249 144256    820.0
Name: new_cases, dtype: float64
144250 144257    650.0
Name: new_cases, dtype: float64
144251 144258    534.0
Name: new_cases, dtype: float64
144252 144259    1240.0
Name: new_cases, dtype: float64
144253 144260    538.0
Name: new_cases, dtype: float64
144254 144261    643.0
Name: new_cases, dtype: float64
144255 144262    687.0
Name: new_cases, dtype: float64
144256 144263    827.0
Name: new_cases, dtype: float64
144257 144264    726.0
Name: new_cases, dtype: float64
144258 144265    580.0
Name: new_cases, dtype: float64
144259 144266    445.0
Name: new_cases, dtype: float64
144260 144267    560.0
Name: new_cases, dtype: float64
144261 144268    769.0
Name: new_cases, dtype: float64
144262 144269    769.0
Name: new_cases, dtype: float64
144263 144270    767.0
Name: new_cases, dtype: float64
144264 144271    745.0
Name: new_cases, dtype: float64
144265 144272    685.0
Name: new_cases, dtype: float64
144266 144273    550.0
Name: new_cases, dtype: float64
144267 144274    797.0
Name: new_cases, dtype: float64
144268 144275    846.0
Name: new_cases, dtype: float64
144269 144276    880.0
Name: new_cases, dtype: float64
144270 144277    761.0
Name: new_cases, dtype: float64
144271 144278    743.0
Name: new_cases, dtype: float64
144272 144279    942.0
Name: new_cases, dtype: float64
144273 144280    674.0
Name: new_cases, dtype: float64
144274 144281    892.0
Name: new_cases, dtype: float64
144275 144282    951.0
Name: new_cases, dtype: float64
144276 144283    871.0
Name: new_cases, dtype: float64
144277 144284    758.0
Name: new_cases, dtype: float64
144278 144285    1062.0
Name: new_cases, dtype: float64
144279 144286    818.0
Name: new_cases, dtype: float64
144280 144287    1148.0
Name: new_cases, dtype: float64
144281 144288    1013.0
Name: new_cases, dtype: float64
144282 144289    1129.0
Name: new_cases, dtype: float64
144283 144290    1444.0
Name: new_cases, dtype: float64
144284 144291    1012.0
Name: new_cases, dtype: float64
144285 144292    1105.0
Name: new_cases, dtype: float64
144286 144293    715.0
Name: new_cases, dtype: float64
144287 144294    1089.0
Name: new_cases, dtype: float64
144288 144295    816.0
Name: new_cases, dtype: float64
144289 144296    1182.0
Name: new_cases, dtype: float64
144290 144297    1034.0
Name: new_cases, dtype: float64
144291 144298    1288.0
Name: new_cases, dtype: float64
144292 144299    1041.0
Name: new_cases, dtype: float64
144293 144300    974.0
Name: new_cases, dtype: float64
144294 144301    1188.0
Name: new_cases, dtype: float64
144295 144302    1051.0
Name: new_cases, dtype: float64
144296 144303    1522.0
Name: new_cases, dtype: float64
144297 144304    1278.0
Name: new_cases, dtype: float64
144298 144305    1108.0
Name: new_cases, dtype: float64
144299 144306    1715.0
Name: new_cases, dtype: float64
144300 144307    1406.0
144308    1406.0
144309    1406.0
Name: new_cases, dtype: float64
144301 144307    1406.0
144308    1406.0
144309    1406.0
Name: new_cases, dtype: float64
144302 144307    1406.0
144308    1406.0
144309    1406.0
Name: new_cases, dtype: float64
144303 144310    1300.0
Name: new_cases, dtype: float64
144304 144311    1509.0
Name: new_cases, dtype: float64
144305 144312    1735.0
Name: new_cases, dtype: float64
144306 144313    1940.0
Name: new_cases, dtype: float64
144307 144314    1813.0
Name: new_cases, dtype: float64
144308 144315    2983.0
Name: new_cases, dtype: float64
144309 144316    2950.0
Name: new_cases, dtype: float64
144310 144317    2461.0
Name: new_cases, dtype: float64
144311 144318    2661.0
Name: new_cases, dtype: float64
144312 144319    2919.0
Name: new_cases, dtype: float64
144313 144320    3541.0
Name: new_cases, dtype: float64
144314 144321    3497.0
Name: new_cases, dtype: float64
144315 144322    3330.0
Name: new_cases, dtype: float64
144316 144323    2621.0
Name: new_cases, dtype: float64
144317 144324    3109.0
Name: new_cases, dtype: float64
144318 144325    3991.0
Name: new_cases, dtype: float64
144319 144326    3400.0
Name: new_cases, dtype: float64
144320 144327    4322.0
Name: new_cases, dtype: float64
144321 144328    4422.0
Name: new_cases, dtype: float64
144322 144329    3899.0
Name: new_cases, dtype: float64
144323 144330    4376.0
Name: new_cases, dtype: float64
144324 144331    4926.0
Name: new_cases, dtype: float64
144325 144332    6180.0
Name: new_cases, dtype: float64
144326 144333    6635.0
Name: new_cases, dtype: float64
144327 144334    6874.0
Name: new_cases, dtype: float64
144328 144335    6041.0
Name: new_cases, dtype: float64
144329 144336    5692.0
Name: new_cases, dtype: float64
144330 144337    4052.0
Name: new_cases, dtype: float64
144331 144338    7143.0
Name: new_cases, dtype: float64
144332 144339    7109.0
Name: new_cases, dtype: float64
144333 144340    6914.0
Name: new_cases, dtype: float64
144334 144341    6980.0
Name: new_cases, dtype: float64
144335 144342    12872.0
Name: new_cases, dtype: float64
144336 144343    22961.0
Name: new_cases, dtype: float64
144337 144344    12601.0
Name: new_cases, dtype: float64
144338 144345    14551.0
Name: new_cases, dtype: float64
144339 144346    14165.0
Name: new_cases, dtype: float64
144340 144347    17541.0
Name: new_cases, dtype: float64
144341 144348    13864.0
Name: new_cases, dtype: float64
144342 144349    15165.0
Name: new_cases, dtype: float64
144343 144350    12872.0
Name: new_cases, dtype: float64
144344 144351    14010.0
Name: new_cases, dtype: float64

144345 144352    17236.0
Name: new_cases, dtype: float64
144346 144353    19728.0
Name: new_cases, dtype: float64
144347 144354    18981.0
Name: new_cases, dtype: float64
144348 144355    15635.0
Name: new_cases, dtype: float64
144349 144356    16171.0
Name: new_cases, dtype: float64
144350 144357    16981.0
Name: new_cases, dtype: float64
144351 144358    18822.0
Name: new_cases, dtype: float64
144352 144359    21331.0
Name: new_cases, dtype: float64
144353 144360    26694.0
Name: new_cases, dtype: float64
144354 144361    21247.0
Name: new_cases, dtype: float64
144355 144362    20542.0
Name: new_cases, dtype: float64
144356 144363    23012.0
Name: new_cases, dtype: float64
144357 144364    19790.0
Name: new_cases, dtype: float64
144358 144365    20891.0
Name: new_cases, dtype: float64
144359 144366    22911.0
Name: new_cases, dtype: float64
144360 144367    24711.0
Name: new_cases, dtype: float64
144361 144368    23068.0
Name: new_cases, dtype: float64
144362 144369    24410.0
Name: new_cases, dtype: float64
144363 144370    21915.0
Name: new_cases, dtype: float64
144364 144371    23254.0
Name: new_cases, dtype: float64
144365 144372    18954.0
Name: new_cases, dtype: float64
144366 144373    20052.0
Name: new_cases, dtype: float64
144367 144374    25191.0
Name: new_cases, dtype: float64
144368 144375    24150.0
Name: new_cases, dtype: float64
144369 144376    23303.0
Name: new_cases, dtype: float64
144370 144377    24957.0
Name: new_cases, dtype: float64
144371 144378    20572.0
Name: new_cases, dtype: float64
144372 144379    21380.0
Name: new_cases, dtype: float64
144373 144380    20433.0
Name: new_cases, dtype: float64
144374 144381    22964.0
Name: new_cases, dtype: float64
144375 144382    33487.0
Name: new_cases, dtype: float64
144376 144383    27301.0
Name: new_cases, dtype: float64
144377 144384    26860.0
Name: new_cases, dtype: float64
144378 144385    24962.0
Name: new_cases, dtype: float64
144379 144386    21406.0
Name: new_cases, dtype: float64
144380 144387    20051.0
Name: new_cases, dtype: float64
144381 144388    19631.0
Name: new_cases, dtype: float64
144382 144389    22926.0
Name: new_cases, dtype: float64
144383 144390    20253.0
Name: new_cases, dtype: float64
144384 144391    19889.0
Name: new_cases, dtype: float64
144385 144392    18662.0
Name: new_cases, dtype: float64
144386 144393    15450.0
Name: new_cases, dtype: float64
144387 144394    11329.0
Name: new_cases, dtype: float64
144388 144395    18236.0
Name: new_cases, dtype: float64
144389 144396    17555.0
Name: new_cases, dtype: float64
144390 144397    14810.0
Name: new_cases, dtype: float64
144391 144398    15871.0
Name: new_cases, dtype: float64
144392 144399    12155.0
Name: new_cases, dtype: float64
144393 144400    12411.0
Name: new_cases, dtype: float64
144394 144401    13471.0
Name: new_cases, dtype: float64
144395 144402    16226.0
Name: new_cases, dtype: float64
144396 144403    14939.0
Name: new_cases, dtype: float64
144397 144404    16366.0
Name: new_cases, dtype: float64
144398 144405    15562.0
Name: new_cases, dtype: float64
144399 144406    17367.0
Name: new_cases, dtype: float64
144400 144407    14749.0
Name: new_cases, dtype: float64
144401 144408    12353.0
Name: new_cases, dtype: float64
144402 144409    16616.0
Name: new_cases, dtype: float64
144403 144410    21022.0
Name: new_cases, dtype: float64
144404 144411    21754.0
Name: new_cases, dtype: float64
144405 144412    21552.0
Name: new_cases, dtype: float64
144406 144413    18538.0
Name: new_cases, dtype: float64
144407 144414    20327.0
Name: new_cases, dtype: float64
144408 144415    18510.0
Name: new_cases, dtype: float64
144409 144416    25261.0
Name: new_cases, dtype: float64
144410 144417    35480.0
Name: new_cases, dtype: float64
144411 144418    28507.0
Name: new_cases, dtype: float64
144412 144419    27189.0
Name: new_cases, dtype: float64
144413 144420    36031.0
Name: new_cases, dtype: float64
144414 144421    33473.0
Name: new_cases, dtype: float64
144415 144422    36841.0
Name: new_cases, dtype: float64
144416 144423    39318.0
Name: new_cases, dtype: float64
144417 144424    39059.0
Name: new_cases, dtype: float64
144418 144425    32725.0
Name: new_cases, dtype: float64
144419 144426    34693.0
Name: new_cases, dtype: float64
144420 144427    32420.0
Name: new_cases, dtype: float64
144421 144428    41414.0
Name: new_cases, dtype: float64
144422 144429    53150.0
Name: new_cases, dtype: float64
144423 144430    50043.0
Name: new_cases, dtype: float64
144424 144431    55926.0
Name: new_cases, dtype: float64
144425 144432    53286.0
Name: new_cases, dtype: float64
144426 144433    57724.0
Name: new_cases, dtype: float64
144427 144434    55052.0
Name: new_cases, dtype: float64
144428 144435    58805.0
Name: new_cases, dtype: float64
144429 144436    60938.0
Name: new_cases, dtype: float64
144430 144437    62352.0
Name: new_cases, dtype: float64
144431 144438    52634.0
Name: new_cases, dtype: float64
144432 144439    68066.0
Name: new_cases, dtype: float64
144433 144440    59974.0
Name: new_cases, dtype: float64
144434 144441    54957.0
Name: new_cases, dtype: float64
144435 144442    46191.0
Name: new_cases, dtype: float64
144436 144443    45544.0
Name: new_cases, dtype: float64
144437 144444    47539.0
Name: new_cases, dtype: float64
144438 144445    48695.0
Name: new_cases, dtype: float64
144439 144446    55777.0
Name: new_cases, dtype: float64
144440 144447    41345.0
Name: new_cases, dtype: float64
144441 144448    38605.0
Name: new_cases, dtype: float64
144442 144449    37542.0
Name: new_cases, dtype: float64
144443 144450    33371.0
Name: new_cases, dtype: float64
144444 144451    38917.0
Name: new_cases, dtype: float64
144445 144452    37901.0
Name: new_cases, dtype: float64
144446 144453    40268.0
Name: new_cases, dtype: float64
144447 144454    33568.0
Name: new_cases, dtype: float64
144448 144455    30037.0
Name: new_cases, dtype: float64
144449 144456    22218.0
Name: new_cases, dtype: float64
144450 144457    20101.0
Name: new_cases, dtype: float64
144451 144458    25334.0
Name: new_cases, dtype: float64
144452 144459    28709.0
Name: new_cases, dtype: float64
144453 144460    29079.0
Name: new_cases, dtype: float64
144454 144461    23360.0
Name: new_cases, dtype: float64
144455 144462    21140.0
Name: new_cases, dtype: float64
144456 144463    18653.0
Name: new_cases, dtype: float64
144457 144464    16879.0
Name: new_cases, dtype: float64
144458 144465    19202.0
Name: new_cases, dtype: float64
144459 144466    20674.0
Name: new_cases, dtype: float64
144460 144467    19160.0
Name: new_cases, dtype: float64
144461 144468    18285.0
Name: new_cases, dtype: float64
144462 144469    15856.0
Name: new_cases, dtype: float64
144463 144470    14126.0
Name: new_cases, dtype: float64
144464 144471    12385.0
Name: new_cases, dtype: float64
144465 144472    13024.0
Name: new_cases, dtype: float64
144466 144473    13505.0
Name: new_cases, dtype: float64
144467 144474    15163.0
Name: new_cases, dtype: float64
144468 144475    13316.0
Name: new_cases, dtype: float64
144469 144476    10982.0
Name: new_cases, dtype: float64
144470 144477    9770.0
Name: new_cases, dtype: float64
144471 144478    10630.0
Name: new_cases, dtype: float64
144472 144479    12721.0
Name: new_cases, dtype: float64
144473 144480    12060.0
Name: new_cases, dtype: float64
144474 144481    12034.0
Name: new_cases, dtype: float64
144475 144482    10408.0
Name: new_cases, dtype: float64
144476 144483    9835.0
Name: new_cases, dtype: float64
144477 144484    10645.0
Name: new_cases, dtype: float64
144478 144485    8489.0
Name: new_cases, dtype: float64
144479 144486    9939.0
Name: new_cases, dtype: float64
144480 144487    9986.0
Name: new_cases, dtype: float64
144481 144488    8524.0
Name: new_cases, dtype: float64
144482 144489    7435.0
Name: new_cases, dtype: float64
144483 144490    6039.0
Name: new_cases, dtype: float64
144484 144491    5455.0
Name: new_cases, dtype: float64
144485 144492    6392.0
Name: new_cases, dtype: float64
144486 144493    6386.0
Name: new_cases, dtype: float64
144487 144494    6574.0
Name: new_cases, dtype: float64
144488 144495    5946.0
Name: new_cases, dtype: float64
144489 144496    6039.0
Name: new_cases, dtype: float64
144490 144497    5177.0
Name: new_cases, dtype: float64
144491 144498    4713.0
Name: new_cases, dtype: float64
144492 144499    5767.0
Name: new_cases, dtype: float64
144493 144500    5926.0
Name: new_cases, dtype: float64
144494 144501    6753.0
Name: new_cases, dtype: float64
144495 144502    6609.0
Name: new_cases, dtype: float64
144496 144503    5534.0
Name: new_cases, dtype: float64
144497 144504    4618.0
Name: new_cases, dtype: float64
144498 144505    5090.0
Name: new_cases, dtype: float64
144499 144506    5295.0
Name: new_cases, dtype: float64
144500 144507    5758.0
Name: new_cases, dtype: float64
144501 144508    6303.0
Name: new_cases, dtype: float64
144502 144509    4802.0
Name: new_cases, dtype: float64
144503 144510    5587.0
Name: new_cases, dtype: float64
144504 144511    5312.0
Name: new_cases, dtype: float64
144505 144512    5342.0
Name: new_cases, dtype: float64

144506 144513    5380.0
Name: new_cases, dtype: float64
144507 144514    5604.0
Name: new_cases, dtype: float64
144508 144515    6220.0
Name: new_cases, dtype: float64
144509 144516    6187.0
Name: new_cases, dtype: float64
144510 144517    3865.0
Name: new_cases, dtype: float64
144511 144518    3862.0
Name: new_cases, dtype: float64
144512 144519    4654.0
Name: new_cases, dtype: float64
144513 144520    4043.0
Name: new_cases, dtype: float64
144514 144521    4052.0
Name: new_cases, dtype: float64
144515 144522    4479.0
Name: new_cases, dtype: float64
144516 144523    3402.0
Name: new_cases, dtype: float64
144517 144524    3423.0
Name: new_cases, dtype: float64
144518 144525    2297.0
Name: new_cases, dtype: float64
144519 144526    2762.0
Name: new_cases, dtype: float64
144520 144527    2380.0
Name: new_cases, dtype: float64
144521 144528    2762.0
Name: new_cases, dtype: float64
144522 144529    3030.0
Name: new_cases, dtype: float64
144523 144530   -4860.0
Name: new_cases, dtype: float64
144524 144531    2584.0
Name: new_cases, dtype: float64
144525 144532    1730.0
Name: new_cases, dtype: float64
144526 144533    3568.0
Name: new_cases, dtype: float64
144527 144534    2473.0
Name: new_cases, dtype: float64
144528 144535    2491.0
Name: new_cases, dtype: float64
144529 144536    2671.0
Name: new_cases, dtype: float64
144530 144537    2756.0
Name: new_cases, dtype: float64
144531 144538    2206.0
Name: new_cases, dtype: float64
144532 144539    1882.0
Name: new_cases, dtype: float64
144533 144540    2963.0
Name: new_cases, dtype: float64
144534 144541    2524.0
Name: new_cases, dtype: float64
144535 144542    2398.0
Name: new_cases, dtype: float64
144536 144543    2728.0
Name: new_cases, dtype: float64
144537 144544    2734.0
Name: new_cases, dtype: float64
144538 144545    2061.0
Name: new_cases, dtype: float64
144539 144546    1712.0
Name: new_cases, dtype: float64
144540 144547    2064.0
Name: new_cases, dtype: float64
144541 144548    2685.0
Name: new_cases, dtype: float64
144542 144549    2110.0
Name: new_cases, dtype: float64
144543 144550    2445.0
Name: new_cases, dtype: float64
144544 144551    2381.0
Name: new_cases, dtype: float64
144545 144552    1907.0
Name: new_cases, dtype: float64
144546 144553    1671.0
Name: new_cases, dtype: float64
144547 144554    1649.0
Name: new_cases, dtype: float64
144548 144555    1947.0
Name: new_cases, dtype: float64
144549 144556    2144.0
Name: new_cases, dtype: float64
144550 144557    2613.0
Name: new_cases, dtype: float64
144551 144558    2490.0
Name: new_cases, dtype: float64
144552 144559    2047.0
Name: new_cases, dtype: float64
144553 144560    1770.0
Name: new_cases, dtype: float64
144554 144561    2358.0
Name: new_cases, dtype: float64
144555 144562    2474.0
Name: new_cases, dtype: float64
144556 144563    2284.0
Name: new_cases, dtype: float64
144557 144564    2656.0
Name: new_cases, dtype: float64
144558 144565    2193.0
Name: new_cases, dtype: float64
144559 144566    2027.0
Name: new_cases, dtype: float64
144560 144567    1926.0
Name: new_cases, dtype: float64
144561 144568    1981.0
Name: new_cases, dtype: float64
144562 144569   -2364.0
Name: new_cases, dtype: float64
144563 144570    2135.0
Name: new_cases, dtype: float64
144564 144571    2694.0
Name: new_cases, dtype: float64
144565 144572    2702.0
Name: new_cases, dtype: float64
144566 144573    2523.0
Name: new_cases, dtype: float64
144567 144574    2092.0
Name: new_cases, dtype: float64
144568 144575    2368.0
Name: new_cases, dtype: float64
144569 144576    2410.0
Name: new_cases, dtype: float64
144570 144577    2987.0
Name: new_cases, dtype: float64
144571 144578    3380.0
Name: new_cases, dtype: float64
144572 144579    4028.0
Name: new_cases, dtype: float64
144573 144580    3240.0
Name: new_cases, dtype: float64
144574 144581    3111.0
Name: new_cases, dtype: float64
144575 144582    3284.0
Name: new_cases, dtype: float64
144576 144583    3099.0
Name: new_cases, dtype: float64
144577 144584    4261.0
Name: new_cases, dtype: float64
144578 144585    5179.0
Name: new_cases, dtype: float64
144579 144586    6140.0
Name: new_cases, dtype: float64
144580 144587    5651.0
Name: new_cases, dtype: float64
144581 144588    5223.0
Name: new_cases, dtype: float64
144582 144589    5594.0
Name: new_cases, dtype: float64
144583 144590    5966.0
Name: new_cases, dtype: float64
144584 144591    7319.0
Name: new_cases, dtype: float64
144585 144592    7237.0
Name: new_cases, dtype: float64
144586 144593    7958.0
Name: new_cases, dtype: float64
144587 144594    7550.0
Name: new_cases, dtype: float64
144588 144595    7330.0
Name: new_cases, dtype: float64
144589 144596    7619.0
Name: new_cases, dtype: float64
144590 144597    7587.0
Name: new_cases, dtype: float64
144591 144598    8808.0
Name: new_cases, dtype: float64
144592 144599    10821.0
Name: new_cases, dtype: float64
144593 144600    10272.0
Name: new_cases, dtype: float64
144594 144601    10075.0
Name: new_cases, dtype: float64
144595 144602    9074.0
Name: new_cases, dtype: float64
144596 144603    10467.0
Name: new_cases, dtype: float64
144597 144604    11503.0
Name: new_cases, dtype: float64
144598 144605    15882.0
Name: new_cases, dtype: float64
144599 144606    16702.0
Name: new_cases, dtype: float64
144600 144607    15364.0
Name: new_cases, dtype: float64
144601 144608    17944.0
Name: new_cases, dtype: float64
144602 144609    14624.0
Name: new_cases, dtype: float64
144603 144610    22717.0
Name: new_cases, dtype: float64
144604 144611    20252.0
Name: new_cases, dtype: float64
144605 144612    25667.0
Name: new_cases, dtype: float64
144606 144613    27621.0
Name: new_cases, dtype: float64
144607 144614    26773.0
Name: new_cases, dtype: float64
144608 144615    24447.0
Name: new_cases, dtype: float64
144609 144616    23824.0
Name: new_cases, dtype: float64
144610 144617    27100.0
Name: new_cases, dtype: float64
144611 144618    28611.0
Name: new_cases, dtype: float64
144612 144619    32048.0
Name: new_cases, dtype: float64
144613 144620    32080.0
Name: new_cases, dtype: float64
144614 144621    35504.0
Name: new_cases, dtype: float64
144615 144622    31800.0
Name: new_cases, dtype: float64
144616 144623    31352.0
Name: new_cases, dtype: float64
144617 144624    34455.0
Name: new_cases, dtype: float64
144618 144625    36443.0
Name: new_cases, dtype: float64
144619 144626    41960.0
Name: new_cases, dtype: float64
144620 144627    48173.0
Name: new_cases, dtype: float64
144621 144628    51485.0
Name: new_cases, dtype: float64
144622 144629    53980.0
Name: new_cases, dtype: float64
144623 144630    47599.0
Name: new_cases, dtype: float64
144624 144631    40394.0
Name: new_cases, dtype: float64
144625 144632    46429.0
Name: new_cases, dtype: float64
144626 144633    43623.0
Name: new_cases, dtype: float64
144627 144634    39570.0
Name: new_cases, dtype: float64
144628 144635    35841.0
Name: new_cases, dtype: float64
144629 144636    31291.0
Name: new_cases, dtype: float64
144630 144637    28656.0
Name: new_cases, dtype: float64
144631 144638    24741.0
Name: new_cases, dtype: float64
144632 144639    23362.0
Name: new_cases, dtype: float64
144633 144640    25512.0
Name: new_cases, dtype: float64
144634 144641    30724.0
Name: new_cases, dtype: float64
144635 144642    29294.0
Name: new_cases, dtype: float64
144636 144643    25760.0
Name: new_cases, dtype: float64
144637 144644    24141.0
Name: new_cases, dtype: float64
144638 144645    21687.0
Name: new_cases, dtype: float64
144639 144646    21693.0
Name: new_cases, dtype: float64
144640 144647    29000.0
Name: new_cases, dtype: float64
144641 144648    29873.0
Name: new_cases, dtype: float64
144642 144649    31482.0
Name: new_cases, dtype: float64
144643 144650    28233.0
Name: new_cases, dtype: float64
144644 144651    27117.0
Name: new_cases, dtype: float64
144645 144652    24962.0
Name: new_cases, dtype: float64
144646 144653    23339.0
Name: new_cases, dtype: float64
144647 144654    29289.0
Name: new_cases, dtype: float64
144648 144655    32763.0
Name: new_cases, dtype: float64
144649 144656    32426.0
Name: new_cases, dtype: float64
144650 144657    29153.0
Name: new_cases, dtype: float64
144651 144658    26440.0
Name: new_cases, dtype: float64
144652 144659    28278.0
Name: new_cases, dtype: float64
144653 144660    26628.0
Name: new_cases, dtype: float64
144654 144661    33646.0
Name: new_cases, dtype: float64
144655 144662    36421.0
Name: new_cases, dtype: float64
144656 144663    37038.0
Name: new_cases, dtype: float64
144657 144664    31783.0
Name: new_cases, dtype: float64
144658 144665    31976.0
Name: new_cases, dtype: float64
144659 144666    31798.0
Name: new_cases, dtype: float64
144660 144667    30653.0
Name: new_cases, dtype: float64
144661 144668    35584.0
Name: new_cases, dtype: float64
144662 144669    38002.0
Name: new_cases, dtype: float64
144663 144670    37738.0
Name: new_cases, dtype: float64
144664 144671    32087.0
Name: new_cases, dtype: float64
144665 144672    32937.0
Name: new_cases, dtype: float64
144666 144673    26227.0
Name: new_cases, dtype: float64

144667 144674    32053.0
Name: new_cases, dtype: float64
144668 144675    35534.0
Name: new_cases, dtype: float64
144669 144676    37870.0
Name: new_cases, dtype: float64
144670 144677    42114.0
Name: new_cases, dtype: float64
144671 144678    36642.0
Name: new_cases, dtype: float64
144672 144679    36515.0
Name: new_cases, dtype: float64
144673 144680    40938.0
Name: new_cases, dtype: float64
144674 144681    37225.0
Name: new_cases, dtype: float64
144675 144682    38510.0
Name: new_cases, dtype: float64
144676 144683    37521.0
Name: new_cases, dtype: float64
144677 144684    36777.0
Name: new_cases, dtype: float64
144678 144685    28856.0
Name: new_cases, dtype: float64
144679 144686    28614.0
Name: new_cases, dtype: float64
144680 144687    30385.0
Name: new_cases, dtype: float64
144681 144688    26288.0
Name: new_cases, dtype: float64
144682 144689    29879.0
Name: new_cases, dtype: float64
144683 144690    26375.0
Name: new_cases, dtype: float64
144684 144691    32338.0
Name: new_cases, dtype: float64
144685 144692    29438.0
Name: new_cases, dtype: float64
144686 144693    29007.0
Name: new_cases, dtype: float64
144687 144694    35768.0
Name: new_cases, dtype: float64
144688 144695    31128.0
Name: new_cases, dtype: float64
144689 144696    33585.0
Name: new_cases, dtype: float64
144690 144697    35798.0
Name: new_cases, dtype: float64
144691 144698    35659.0
Name: new_cases, dtype: float64
144692 144699    29746.0
Name: new_cases, dtype: float64
144693 144700    32997.0
Name: new_cases, dtype: float64
144694 144701    37510.0
Name: new_cases, dtype: float64
144695 144702    34604.0
Name: new_cases, dtype: float64
144696 144703    35089.0
Name: new_cases, dtype: float64
144697 144704    35773.0
Name: new_cases, dtype: float64
144698 144705    34610.0
Name: new_cases, dtype: float64
144699 144706    29389.0
Name: new_cases, dtype: float64
144700 144707    29666.0
Name: new_cases, dtype: float64
144701 144708    34306.0
Name: new_cases, dtype: float64
144702 144709    33079.0
Name: new_cases, dtype: float64
144703 144710    38713.0
Name: new_cases, dtype: float64
144704 144711    39767.0
Name: new_cases, dtype: float64
144705 144712    34941.0
Name: new_cases, dtype: float64
144706 144713    39413.0
Name: new_cases, dtype: float64
144707 144714    33593.0
Name: new_cases, dtype: float64
144708 144715    39588.0
Name: new_cases, dtype: float64
144709 144716    37717.0
Name: new_cases, dtype: float64
144710 144717    41501.0
Name: new_cases, dtype: float64
144711 144718    44619.0
Name: new_cases, dtype: float64
144712 144719    44251.0
Name: new_cases, dtype: float64
144713 144720    42818.0
Name: new_cases, dtype: float64
144714 144721    44696.0
Name: new_cases, dtype: float64
144715 144722    48855.0
Name: new_cases, dtype: float64
144716 144723    43411.0
Name: new_cases, dtype: float64
144717 144724    48599.0
Name: new_cases, dtype: float64
144718 144725    51548.0
Name: new_cases, dtype: float64
144719 144726    48791.0
Name: new_cases, dtype: float64
144720 144727    44985.0
Name: new_cases, dtype: float64
144721 144728    38740.0
Name: new_cases, dtype: float64
144722 144729    36283.0
Name: new_cases, dtype: float64
144723 144730    43503.0
Name: new_cases, dtype: float64
144724 144731    44000.0
Name: new_cases, dtype: float64
144725 144732    39091.0
Name: new_cases, dtype: float64
144726 144733    43161.0
Name: new_cases, dtype: float64
144727 144734    40726.0
Name: new_cases, dtype: float64
144728 144735    37667.0
Name: new_cases, dtype: float64
144729 144736    39935.0
Name: new_cases, dtype: float64
144730 144737    33615.0
Name: new_cases, dtype: float64
144731 144738    40803.0
Name: new_cases, dtype: float64
144732 144739    36738.0
Name: new_cases, dtype: float64
144733 144740    33810.0
Name: new_cases, dtype: float64
144734 144741    30150.0
Name: new_cases, dtype: float64
144735 144742    29843.0
Name: new_cases, dtype: float64
144736 144743    32266.0
Name: new_cases, dtype: float64
144737 144744    32785.0
Name: new_cases, dtype: float64
144738 144745    39547.0
Name: new_cases, dtype: float64
144739 144746    42590.0
Name: new_cases, dtype: float64
144740 144747    39040.0
Name: new_cases, dtype: float64
144741 144748    37669.0
Name: new_cases, dtype: float64
144742 144749    36128.0
Name: new_cases, dtype: float64
144743 144750    39796.0
Name: new_cases, dtype: float64
144744 144751    36956.0
Name: new_cases, dtype: float64
144745 144752    38073.0
Name: new_cases, dtype: float64
144746 144753    46991.0
Name: new_cases, dtype: float64
144747 144754    44411.0
Name: new_cases, dtype: float64
144748 144755    39881.0
Name: new_cases, dtype: float64
144749 144756    39458.0
Name: new_cases, dtype: float64
144750 144757    45021.0
Name: new_cases, dtype: float64
144751 144758    42832.0
Name: new_cases, dtype: float64
144752 144759    42621.0
Name: new_cases, dtype: float64
144753 144760    46955.0
Name: new_cases, dtype: float64
144754 144761    49554.0
Name: new_cases, dtype: float64
144755 144762    39567.0
Name: new_cases, dtype: float64
144756 144763    36507.0
Name: new_cases, dtype: float64
144757 144764    42702.0
Name: new_cases, dtype: float64
144758 144765    40011.0
Name: new_cases, dtype: float64
144759 144766    47454.0
Name: new_cases, dtype: float64
144760 144767    53322.0
Name: new_cases, dtype: float64
144761 144768    50810.0
Name: new_cases, dtype: float64
144762 144769    41457.0
Name: new_cases, dtype: float64
144763 144770    43285.0
Name: new_cases, dtype: float64
144764 144771    51432.0
Name: new_cases, dtype: float64
144765 144772    45333.0
Name: new_cases, dtype: float64
144766 144773    50811.0
Name: new_cases, dtype: float64
144767 144774    50282.0
Name: new_cases, dtype: float64
144768 144775    58352.0
Name: new_cases, dtype: float64
144769 144776    52279.0
Name: new_cases, dtype: float64
144770 144777    48071.0
Name: new_cases, dtype: float64
144771 144778    53953.0
Name: new_cases, dtype: float64
144772 144779    59746.0
Name: new_cases, dtype: float64
144773 144780    77966.0
Name: new_cases, dtype: float64
144774 144781    87801.0
Name: new_cases, dtype: float64
144775 144782    92713.0
Name: new_cases, dtype: float64
144776 144783    89074.0
Name: new_cases, dtype: float64
144777 144784    81959.0
Name: new_cases, dtype: float64
144778 144785    92371.0
Name: new_cases, dtype: float64
144779 144786    89298.0
Name: new_cases, dtype: float64
144780 144787    105626.0
Name: new_cases, dtype: float64
144781 144788    122760.0
Name: new_cases, dtype: float64
144782 144789    121810.0
Name: new_cases, dtype: float64
144783 144790    121861.0
Name: new_cases, dtype: float64
144784 144791    118945.0
Name: new_cases, dtype: float64
144785 144792    107699.0
Name: new_cases, dtype: float64
144786 144793    138025.0
Name: new_cases, dtype: float64
144787 144794    184475.0
Name: new_cases, dtype: float64
144788 144795    188925.0
Name: new_cases, dtype: float64
144789 144796    190544.0
Name: new_cases, dtype: float64
144790 144797    162572.0
Name: new_cases, dtype: float64
144791 144798    134943.0
Name: new_cases, dtype: float64
144792 144799    187414.0
Name: new_cases, dtype: float64
144793 144800    221222.0
Name: new_cases, dtype: float64
144794 144801    194615.0
Name: new_cases, dtype: float64
144795 144802    180610.0
Name: new_cases, dtype: float64
144796 144803    178868.0
Name: new_cases, dtype: float64
144797 144804    140566.0
Name: new_cases, dtype: float64
144798 Series([], Name: new_cases, dtype: float64)
144799 Series([], Name: new_cases, dtype: float64)
144800 Series([], Name: new_cases, dtype: float64)
144801 Series([], Name: new_cases, dtype: float64)
144802 Series([], Name: new_cases, dtype: float64)
144803 Series([], Name: new_cases, dtype: float64)
144804 Series([], Name: new_cases, dtype: float64)
144806 144813    0.0
Name: new_cases, dtype: float64
144807 144814    2.0
Name: new_cases, dtype: float64
144808 144815    0.0
Name: new_cases, dtype: float64
144809 144816    0.0
Name: new_cases, dtype: float64
144810 144817    3.0
Name: new_cases, dtype: float64
144811 144818    0.0
Name: new_cases, dtype: float64
144812 144819    0.0
Name: new_cases, dtype: float64
144813 144820    1.0
Name: new_cases, dtype: float64
144814 144821    0.0
Name: new_cases, dtype: float64
144815 144822    0.0
Name: new_cases, dtype: float64
144816 144823    0.0
Name: new_cases, dtype: float64
144817 144824    0.0
Name: new_cases, dtype: float64
144818 144825    1.0
Name: new_cases, dtype: float64
144819 144826    0.0
Name: new_cases, dtype: float64
144820 144827    1.0
Name: new_cases, dtype: float64
144821 144828    0.0
Name: new_cases, dtype: float64
144822 144829    0.0
Name: new_cases, dtype: float64
144823 144830    0.0
Name: new_cases, dtype: float64
144824 144831    0.0
Name: new_cases, dtype: float64
144825 144832    0.0
Name: new_cases, dtype: float64
144826 144833    0.0
Name: new_cases, dtype: float64
144827 144834    0.0
Name: new_cases, dtype: float64
144828 144835    2.0
Name: new_cases, dtype: float64
144829 144836    0.0
Name: new_cases, dtype: float64
144830 144837    0.0
Name: new_cases, dtype: float64
144831 144838    0.0
Name: new_cases, dtype: float64

144832 144839    0.0
Name: new_cases, dtype: float64
144833 144840    0.0
Name: new_cases, dtype: float64
144834 144841    1.0
Name: new_cases, dtype: float64
144835 144842    0.0
Name: new_cases, dtype: float64
144836 144843    8.0
Name: new_cases, dtype: float64
144837 144844    7.0
Name: new_cases, dtype: float64
144838 144845    23.0
Name: new_cases, dtype: float64
144839 144846    19.0
Name: new_cases, dtype: float64
144840 144847    33.0
Name: new_cases, dtype: float64
144841 144848    77.0
Name: new_cases, dtype: float64
144842 144849    53.0
Name: new_cases, dtype: float64
144843 144850    166.0
Name: new_cases, dtype: float64
144844 144851    116.0
Name: new_cases, dtype: float64
144845 144852    75.0
Name: new_cases, dtype: float64
144846 144853    188.0
Name: new_cases, dtype: float64
144847 144854    365.0
Name: new_cases, dtype: float64
144848 144855    439.0
Name: new_cases, dtype: float64
144849 144856    633.0
Name: new_cases, dtype: float64
144850 144857    759.0
Name: new_cases, dtype: float64
144851 144858    234.0
Name: new_cases, dtype: float64
144852 144859    1467.0
Name: new_cases, dtype: float64
144853 144860    1833.0
Name: new_cases, dtype: float64
144854 144861    2657.0
Name: new_cases, dtype: float64
144855 144862    4494.0
Name: new_cases, dtype: float64
144856 144863    6367.0
Name: new_cases, dtype: float64
144857 144864    5995.0
Name: new_cases, dtype: float64
144858 144865    8919.0
Name: new_cases, dtype: float64
144859 144866    11152.0
Name: new_cases, dtype: float64
144860 144867    10618.0
Name: new_cases, dtype: float64
144861 144868    12127.0
Name: new_cases, dtype: float64
144862 144869    17821.0
Name: new_cases, dtype: float64
144863 144870    18591.0
Name: new_cases, dtype: float64
144864 144871    22164.0
Name: new_cases, dtype: float64
144865 144872    16127.0
Name: new_cases, dtype: float64
144866 144873    22154.0
Name: new_cases, dtype: float64
144867 144874    26381.0
Name: new_cases, dtype: float64
144868 144875    32232.0
Name: new_cases, dtype: float64
144869 144876    32230.0
Name: new_cases, dtype: float64
144870 144877    32482.0
Name: new_cases, dtype: float64
144871 144878    32176.0
Name: new_cases, dtype: float64
144872 144879    29604.0
Name: new_cases, dtype: float64
144873 144880    31858.0
Name: new_cases, dtype: float64
144874 144881    30343.0
Name: new_cases, dtype: float64
144875 144882    31149.0
Name: new_cases, dtype: float64
144876 144883    36443.0
Name: new_cases, dtype: float64
144877 144884    34347.0
Name: new_cases, dtype: float64
144878 144885    29278.0
Name: new_cases, dtype: float64
144879 144886    26872.0
Name: new_cases, dtype: float64
144880 144887    26924.0
Name: new_cases, dtype: float64
144881 144888    28395.0
Name: new_cases, dtype: float64
144882 144889    25900.0
Name: new_cases, dtype: float64
144883 144890    29956.0
Name: new_cases, dtype: float64
144884 144891    33157.0
Name: new_cases, dtype: float64
144885 144892    27994.0
Name: new_cases, dtype: float64
144886 144893    25923.0
Name: new_cases, dtype: float64
144887 144894    29680.0
Name: new_cases, dtype: float64
144888 144895    26170.0
Name: new_cases, dtype: float64
144889 144896    29419.0
Name: new_cases, dtype: float64
144890 144897    32768.0
Name: new_cases, dtype: float64
144891 144898    32152.0
Name: new_cases, dtype: float64
144892 144899    30994.0
Name: new_cases, dtype: float64
144893 144900    26547.0
Name: new_cases, dtype: float64
144894 144901    23750.0
Name: new_cases, dtype: float64
144895 144902    24690.0
Name: new_cases, dtype: float64
144896 144903    26220.0
Name: new_cases, dtype: float64
144897 144904    29242.0
Name: new_cases, dtype: float64
144898 144905    35021.0
Name: new_cases, dtype: float64
144899 144906    27824.0
Name: new_cases, dtype: float64
144900 144907    24492.0
Name: new_cases, dtype: float64
144901 144908    23713.0
Name: new_cases, dtype: float64
144902 144909    24329.0
Name: new_cases, dtype: float64
144903 144910    24263.0
Name: new_cases, dtype: float64
144904 144911    27657.0
Name: new_cases, dtype: float64
144905 144912    27273.0
Name: new_cases, dtype: float64
144906 144913    24446.0
Name: new_cases, dtype: float64
144907 144914    19148.0
Name: new_cases, dtype: float64
144908 144915    19034.0
Name: new_cases, dtype: float64
144909 144916    22843.0
Name: new_cases, dtype: float64
144910 144917    20576.0
Name: new_cases, dtype: float64
144911 144918    26532.0
Name: new_cases, dtype: float64
144912 144919    24821.0
Name: new_cases, dtype: float64
144913 144920    24233.0
Name: new_cases, dtype: float64
144914 144921    18798.0
Name: new_cases, dtype: float64
144915 144922    22134.0
Name: new_cases, dtype: float64
144916 144923    20761.0
Name: new_cases, dtype: float64
144917 144924    22723.0
Name: new_cases, dtype: float64
144918 144925    25806.0
Name: new_cases, dtype: float64
144919 144926    23619.0
Name: new_cases, dtype: float64
144920 144927    20979.0
Name: new_cases, dtype: float64
144921 144928    20591.0
Name: new_cases, dtype: float64
144922 144929    18653.0
Name: new_cases, dtype: float64
144923 144930    18576.0
Name: new_cases, dtype: float64
144924 144931    19407.0
Name: new_cases, dtype: float64
144925 144932    21646.0
Name: new_cases, dtype: float64
144926 144933    24735.0
Name: new_cases, dtype: float64
144927 144934    24084.0
Name: new_cases, dtype: float64
144928 144935    19454.0
Name: new_cases, dtype: float64
144929 144936    16965.0
Name: new_cases, dtype: float64
144930 144937    21283.0
Name: new_cases, dtype: float64
144931 144938    19771.0
Name: new_cases, dtype: float64
144932 144939    21723.0
Name: new_cases, dtype: float64
144933 144940    25001.0
Name: new_cases, dtype: float64
144934 144941    21298.0
Name: new_cases, dtype: float64
144935 144942    18413.0
Name: new_cases, dtype: float64
144936 144943    16504.0
Name: new_cases, dtype: float64
144937 144944    18092.0
Name: new_cases, dtype: float64
144938 144945    21068.0
Name: new_cases, dtype: float64
144939 144946    22383.0
Name: new_cases, dtype: float64
144940 144947    25326.0
Name: new_cases, dtype: float64
144941 144948    24972.0
Name: new_cases, dtype: float64
144942 144949    19420.0
Name: new_cases, dtype: float64
144943 144950    18522.0
Name: new_cases, dtype: float64
144944 144951    23839.0
Name: new_cases, dtype: float64
144945 144952    27389.0
Name: new_cases, dtype: float64
144946 144953    28315.0
Name: new_cases, dtype: float64
144947 144954    31697.0
Name: new_cases, dtype: float64
144948 144955    32613.0
Name: new_cases, dtype: float64
144949 144956    26189.0
Name: new_cases, dtype: float64
144950 144957    30973.0
Name: new_cases, dtype: float64
144951 144958    37222.0
Name: new_cases, dtype: float64
144952 144959    36232.0
Name: new_cases, dtype: float64
144953 144960    40369.0
Name: new_cases, dtype: float64
144954 144961    46210.0
Name: new_cases, dtype: float64
144955 144962    41737.0
Name: new_cases, dtype: float64
144956 144963    41862.0
Name: new_cases, dtype: float64
144957 144964    39642.0
Name: new_cases, dtype: float64
144958 144965    48312.0
Name: new_cases, dtype: float64
144959 144966    51567.0
Name: new_cases, dtype: float64
144960 144967    56348.0
Name: new_cases, dtype: float64
144961 144968    52620.0
Name: new_cases, dtype: float64
144962 144969    48946.0
Name: new_cases, dtype: float64
144963 144970    50438.0
Name: new_cases, dtype: float64
144964 144971    42801.0
Name: new_cases, dtype: float64
144965 144972    58857.0
Name: new_cases, dtype: float64
144966 144973    59723.0
Name: new_cases, dtype: float64
144967 144974    60875.0
Name: new_cases, dtype: float64
144968 144975    67778.0
Name: new_cases, dtype: float64
144969 144976    61371.0
Name: new_cases, dtype: float64
144970 144977    60684.0
Name: new_cases, dtype: float64
144971 144978    57560.0
Name: new_cases, dtype: float64
144972 144979    66439.0
Name: new_cases, dtype: float64
144973 144980    67966.0
Name: new_cases, dtype: float64
144974 144981    76039.0
Name: new_cases, dtype: float64
144975 144982    72251.0
Name: new_cases, dtype: float64
144976 144983    63797.0
Name: new_cases, dtype: float64
144977 144984    61449.0
Name: new_cases, dtype: float64
144978 144985    60212.0
Name: new_cases, dtype: float64
144979 144986    65582.0
Name: new_cases, dtype: float64
144980 144987    70385.0
Name: new_cases, dtype: float64
144981 144988    68257.0
Name: new_cases, dtype: float64
144982 144989    74149.0
Name: new_cases, dtype: float64
144983 144990    66999.0
Name: new_cases, dtype: float64
144984 144991    56156.0
Name: new_cases, dtype: float64
144985 144992    56170.0
Name: new_cases, dtype: float64
144986 144993    63694.0
Name: new_cases, dtype: float64
144987 144994    68375.0
Name: new_cases, dtype: float64
144988 144995    67966.0
Name: new_cases, dtype: float64
144989 144996    68468.0
Name: new_cases, dtype: float64
144990 144997    59132.0
Name: new_cases, dtype: float64
144991 144998    46006.0
Name: new_cases, dtype: float64

144992 144999    45284.0
Name: new_cases, dtype: float64
144993 145000    54974.0
Name: new_cases, dtype: float64
144994 145001    55883.0
Name: new_cases, dtype: float64
144995 145002    57231.0
Name: new_cases, dtype: float64
144996 145003    61063.0
Name: new_cases, dtype: float64
144997 145004    55176.0
Name: new_cases, dtype: float64
144998 145005    48137.0
Name: new_cases, dtype: float64
144999 145006    45221.0
Name: new_cases, dtype: float64
145000 145007    52600.0
Name: new_cases, dtype: float64
145001 145008    52802.0
Name: new_cases, dtype: float64
145002 145009    51529.0
Name: new_cases, dtype: float64
145003 145010    65073.0
Name: new_cases, dtype: float64
145004 145011    49656.0
Name: new_cases, dtype: float64
145005 145012    40104.0
Name: new_cases, dtype: float64
145006 145013    35662.0
Name: new_cases, dtype: float64
145007 145014    42905.0
Name: new_cases, dtype: float64
145008 145015    44263.0
Name: new_cases, dtype: float64
145009 145016    44589.0
Name: new_cases, dtype: float64
145010 145017    48789.0
Name: new_cases, dtype: float64
145011 145018    44404.0
Name: new_cases, dtype: float64
145012 145019    34566.0
Name: new_cases, dtype: float64
145013 145020    34881.0
Name: new_cases, dtype: float64
145014 145021    40927.0
Name: new_cases, dtype: float64
145015 145022    43956.0
Name: new_cases, dtype: float64
145016 145023    45988.0
Name: new_cases, dtype: float64
145017 145024    46535.0
Name: new_cases, dtype: float64
145018 145025    44241.0
Name: new_cases, dtype: float64
145019 145026    34928.0
Name: new_cases, dtype: float64
145020 145027    32614.0
Name: new_cases, dtype: float64
145021 145028    42943.0
Name: new_cases, dtype: float64
145022 145029    40642.0
Name: new_cases, dtype: float64
145023 145030    44353.0
Name: new_cases, dtype: float64
145024 145031    50689.0
Name: new_cases, dtype: float64
145025 145032    43509.0
Name: new_cases, dtype: float64
145026 145033    31050.0
Name: new_cases, dtype: float64
145027 145034    23898.0
Name: new_cases, dtype: float64
145028 145035    25689.0
Name: new_cases, dtype: float64
145029 145036    34537.0
Name: new_cases, dtype: float64
145030 145037    35898.0
Name: new_cases, dtype: float64
145031 145038    48020.0
Name: new_cases, dtype: float64
145032 145039    41688.0
Name: new_cases, dtype: float64
145033 145040    34533.0
Name: new_cases, dtype: float64
145034 145041    33167.0
Name: new_cases, dtype: float64
145035 145042    39543.0
Name: new_cases, dtype: float64
145036 145043    38874.0
Name: new_cases, dtype: float64
145037 145044    45251.0
Name: new_cases, dtype: float64
145038 145045    49222.0
Name: new_cases, dtype: float64
145039 145046    42739.0
Name: new_cases, dtype: float64
145040 145047    38917.0
Name: new_cases, dtype: float64
145041 145048    50594.0
Name: new_cases, dtype: float64
145042 145049    40161.0
Name: new_cases, dtype: float64
145043 145050    38852.0
Name: new_cases, dtype: float64
145044 145051    47475.0
Name: new_cases, dtype: float64
145045 145052    48548.0
Name: new_cases, dtype: float64
145046 145053    44930.0
Name: new_cases, dtype: float64
145047 145054    38154.0
Name: new_cases, dtype: float64
145048 145055    32449.0
Name: new_cases, dtype: float64
145049 145056    43514.0
Name: new_cases, dtype: float64
145050 145057    39079.0
Name: new_cases, dtype: float64
145051 145058    46096.0
Name: new_cases, dtype: float64
145052 145059    55130.0
Name: new_cases, dtype: float64
145053 145060    50659.0
Name: new_cases, dtype: float64
145054 145061    34632.0
Name: new_cases, dtype: float64
145055 145062    38231.0
Name: new_cases, dtype: float64
145056 145063    45219.0
Name: new_cases, dtype: float64
145057 145064    51217.0
Name: new_cases, dtype: float64
145058 145065    58915.0
Name: new_cases, dtype: float64
145059 145066    56750.0
Name: new_cases, dtype: float64
145060 145067    55740.0
Name: new_cases, dtype: float64
145061 145068    46832.0
Name: new_cases, dtype: float64
145062 145069    41732.0
Name: new_cases, dtype: float64
145063 145070    51091.0
Name: new_cases, dtype: float64
145064 145071    59302.0
Name: new_cases, dtype: float64
145065 145072    65114.0
Name: new_cases, dtype: float64
145066 145073    69122.0
Name: new_cases, dtype: float64
145067 145074    57692.0
Name: new_cases, dtype: float64
145068 145075    50990.0
Name: new_cases, dtype: float64
145069 145076    66739.0
Name: new_cases, dtype: float64
145070 145077    61697.0
Name: new_cases, dtype: float64
145071 145078    63321.0
Name: new_cases, dtype: float64
145072 145079    76225.0
Name: new_cases, dtype: float64
145073 145080    82478.0
Name: new_cases, dtype: float64
145074 145081    83728.0
Name: new_cases, dtype: float64
145075 145082    62667.0
Name: new_cases, dtype: float64
145076 145083    65976.0
Name: new_cases, dtype: float64
145077 145084    77161.0
Name: new_cases, dtype: float64
145078 145085    79268.0
Name: new_cases, dtype: float64
145079 145086    91219.0
Name: new_cases, dtype: float64
145080 145087    100091.0
Name: new_cases, dtype: float64
145081 145088    90736.0
Name: new_cases, dtype: float64
145082 145089    105645.0
Name: new_cases, dtype: float64
145083 145090    83333.0
Name: new_cases, dtype: float64
145084 145091    127834.0
Name: new_cases, dtype: float64
145085 145092    104175.0
Name: new_cases, dtype: float64
145086 145093    130016.0
Name: new_cases, dtype: float64
145087 145094    127812.0
Name: new_cases, dtype: float64
145088 145095    132124.0
Name: new_cases, dtype: float64
145089 145096    115355.0
Name: new_cases, dtype: float64
145090 145097    118046.0
Name: new_cases, dtype: float64
145091 145098    140271.0
Name: new_cases, dtype: float64
145092 145099    149488.0
Name: new_cases, dtype: float64
145093 145100    161766.0
Name: new_cases, dtype: float64
145094 145101    181126.0
Name: new_cases, dtype: float64
145095 145102    172284.0
Name: new_cases, dtype: float64
145096 145103    137913.0
Name: new_cases, dtype: float64
145097 145104    159178.0
Name: new_cases, dtype: float64
145098 145105    164163.0
Name: new_cases, dtype: float64
145099 145106    173413.0
Name: new_cases, dtype: float64
145100 145107    191899.0
Name: new_cases, dtype: float64
145101 145108    201436.0
Name: new_cases, dtype: float64
145102 145109    182034.0
Name: new_cases, dtype: float64
145103 145110    146647.0
Name: new_cases, dtype: float64
145104 145111    171946.0
Name: new_cases, dtype: float64
145105 145112    177235.0
Name: new_cases, dtype: float64
145106 145113    184893.0
Name: new_cases, dtype: float64
145107 145114    118386.0
Name: new_cases, dtype: float64
145108 145115    203021.0
Name: new_cases, dtype: float64
145109 145116    158756.0
Name: new_cases, dtype: float64
145110 145117    140840.0
Name: new_cases, dtype: float64
145111 145118    155690.0
Name: new_cases, dtype: float64
145112 145119    194035.0
Name: new_cases, dtype: float64
145113 145120    204501.0
Name: new_cases, dtype: float64
145114 145121    224156.0
Name: new_cases, dtype: float64
145115 145122    235313.0
Name: new_cases, dtype: float64
145116 145123    221907.0
Name: new_cases, dtype: float64
145117 145124    179217.0
Name: new_cases, dtype: float64
145118 145125    190149.0
Name: new_cases, dtype: float64
145119 145126    230948.0
Name: new_cases, dtype: float64
145120 145127    221135.0
Name: new_cases, dtype: float64
145121 145128    234673.0
Name: new_cases, dtype: float64
145122 145129    240256.0
Name: new_cases, dtype: float64
145123 145130    222163.0
Name: new_cases, dtype: float64
145124 145131    186699.0
Name: new_cases, dtype: float64
145125 145132    200627.0
Name: new_cases, dtype: float64
145126 145133    222046.0
Name: new_cases, dtype: float64
145127 145134    240685.0
Name: new_cases, dtype: float64
145128 145135    237223.0
Name: new_cases, dtype: float64
145129 145136    248954.0
Name: new_cases, dtype: float64
145130 145137    202570.0
Name: new_cases, dtype: float64
145131 145138    185344.0
Name: new_cases, dtype: float64
145132 145139    189716.0
Name: new_cases, dtype: float64
145133 145140    201963.0
Name: new_cases, dtype: float64
145134 145141    225778.0
Name: new_cases, dtype: float64
145135 145142    204883.0
Name: new_cases, dtype: float64
145136 145143    108685.0
Name: new_cases, dtype: float64
145137 145144    218991.0
Name: new_cases, dtype: float64
145138 145145    154991.0
Name: new_cases, dtype: float64
145139 145146    166683.0
Name: new_cases, dtype: float64
145140 145147    201693.0
Name: new_cases, dtype: float64
145141 145148    222936.0
Name: new_cases, dtype: float64
145142 145149    258109.0
Name: new_cases, dtype: float64
145143 145150    166257.0
Name: new_cases, dtype: float64
145144 145151    295875.0
Name: new_cases, dtype: float64
145145 145152    203648.0
Name: new_cases, dtype: float64
145146 145153    181645.0
Name: new_cases, dtype: float64
145147 145154    231242.0
Name: new_cases, dtype: float64
145148 145155    256866.0
Name: new_cases, dtype: float64
145149 145156    288608.0
Name: new_cases, dtype: float64
145150 145157    303459.0
Name: new_cases, dtype: float64
145151 145158    259530.0
Name: new_cases, dtype: float64
145152 145159    213373.0
Name: new_cases, dtype: float64
145153 145160    210834.0
Name: new_cases, dtype: float64
145154 145161    218900.0
Name: new_cases, dtype: float64
145155 145162    229840.0
Name: new_cases, dtype: float64
145156 145163    238040.0
Name: new_cases, dtype: float64

145157 145164    247026.0
Name: new_cases, dtype: float64
145158 145165    208632.0
Name: new_cases, dtype: float64
145159 145166    176592.0
Name: new_cases, dtype: float64
145160 145167    141080.0
Name: new_cases, dtype: float64
145161 145168    164285.0
Name: new_cases, dtype: float64
145162 145169    185390.0
Name: new_cases, dtype: float64
145163 145170    192326.0
Name: new_cases, dtype: float64
145164 145171    189527.0
Name: new_cases, dtype: float64
145165 145172    174863.0
Name: new_cases, dtype: float64
145166 145173    137834.0
Name: new_cases, dtype: float64
145167 145174    142117.0
Name: new_cases, dtype: float64
145168 145175    144780.0
Name: new_cases, dtype: float64
145169 145176    155135.0
Name: new_cases, dtype: float64
145170 145177    167435.0
Name: new_cases, dtype: float64
145171 145178    165847.0
Name: new_cases, dtype: float64
145172 145179    145683.0
Name: new_cases, dtype: float64
145173 145180    115429.0
Name: new_cases, dtype: float64
145174 145181    129367.0
Name: new_cases, dtype: float64
145175 145182    113872.0
Name: new_cases, dtype: float64
145176 145183    123111.0
Name: new_cases, dtype: float64
145177 145184    123925.0
Name: new_cases, dtype: float64
145178 145185    131659.0
Name: new_cases, dtype: float64
145179 145186    110953.0
Name: new_cases, dtype: float64
145180 145187    91883.0
Name: new_cases, dtype: float64
145181 145188    85008.0
Name: new_cases, dtype: float64
145182 145189    94595.0
Name: new_cases, dtype: float64
145183 145190    95832.0
Name: new_cases, dtype: float64
145184 145191    106303.0
Name: new_cases, dtype: float64
145185 145192    100029.0
Name: new_cases, dtype: float64
145186 145193    88854.0
Name: new_cases, dtype: float64
145187 145194    66349.0
Name: new_cases, dtype: float64
145188 145195    54643.0
Name: new_cases, dtype: float64
145189 145196    58604.0
Name: new_cases, dtype: float64
145190 145197    70068.0
Name: new_cases, dtype: float64
145191 145198    71356.0
Name: new_cases, dtype: float64
145192 145199    78185.0
Name: new_cases, dtype: float64
145193 145200    73407.0
Name: new_cases, dtype: float64
145194 145201    57896.0
Name: new_cases, dtype: float64
145195 145202    54837.0
Name: new_cases, dtype: float64
145196 145203    72013.0
Name: new_cases, dtype: float64
145197 145204    75011.0
Name: new_cases, dtype: float64
145198 145205    78057.0
Name: new_cases, dtype: float64
145199 145206    78734.0
Name: new_cases, dtype: float64
145200 145207    66065.0
Name: new_cases, dtype: float64
145201 145208    51867.0
Name: new_cases, dtype: float64
145202 145209    54488.0
Name: new_cases, dtype: float64
145203 145210    57066.0
Name: new_cases, dtype: float64
145204 145211    67149.0
Name: new_cases, dtype: float64
145205 145212    68532.0
Name: new_cases, dtype: float64
145206 145213    66865.0
Name: new_cases, dtype: float64
145207 145214    59295.0
Name: new_cases, dtype: float64
145208 145215    42066.0
Name: new_cases, dtype: float64
145209 145216    44313.0
Name: new_cases, dtype: float64
145210 145217    55806.0
Name: new_cases, dtype: float64
145211 145218    58233.0
Name: new_cases, dtype: float64
145212 145219    62896.0
Name: new_cases, dtype: float64
145213 145220    62073.0
Name: new_cases, dtype: float64
145214 145221    53592.0
Name: new_cases, dtype: float64
145215 145222    38852.0
Name: new_cases, dtype: float64
145216 145223    54767.0
Name: new_cases, dtype: float64
145217 145224    54381.0
Name: new_cases, dtype: float64
145218 145225    59488.0
Name: new_cases, dtype: float64
145219 145226    60525.0
Name: new_cases, dtype: float64
145220 145227    62065.0
Name: new_cases, dtype: float64
145221 145228    57021.0
Name: new_cases, dtype: float64
145222 145229    34978.0
Name: new_cases, dtype: float64
145223 145230    49480.0
Name: new_cases, dtype: float64
145224 145231    53298.0
Name: new_cases, dtype: float64
145225 145232    87120.0
Name: new_cases, dtype: float64
145226 145233    67976.0
Name: new_cases, dtype: float64
145227 145234    77536.0
Name: new_cases, dtype: float64
145228 145235    62223.0
Name: new_cases, dtype: float64
145229 145236    46354.0
Name: new_cases, dtype: float64
145230 145237    67297.0
Name: new_cases, dtype: float64
145231 145238    61437.0
Name: new_cases, dtype: float64
145232 145239    66971.0
Name: new_cases, dtype: float64
145233 145240    79186.0
Name: new_cases, dtype: float64
145234 145241    71849.0
Name: new_cases, dtype: float64
145235 145242    64246.0
Name: new_cases, dtype: float64
145236 145243    36649.0
Name: new_cases, dtype: float64
145237 145244    73153.0
Name: new_cases, dtype: float64
145238 145245    61143.0
Name: new_cases, dtype: float64
145239 145246    74986.0
Name: new_cases, dtype: float64
145240 145247    80252.0
Name: new_cases, dtype: float64
145241 145248    84337.0
Name: new_cases, dtype: float64
145242 145249    69294.0
Name: new_cases, dtype: float64
145243 145250    46443.0
Name: new_cases, dtype: float64
145244 145251    66957.0
Name: new_cases, dtype: float64
145245 145252    79144.0
Name: new_cases, dtype: float64
145246 145253    75316.0
Name: new_cases, dtype: float64
145247 145254    73910.0
Name: new_cases, dtype: float64
145248 145255    80377.0
Name: new_cases, dtype: float64
145249 145256    54161.0
Name: new_cases, dtype: float64
145250 145257    42882.0
Name: new_cases, dtype: float64
145251 145258    66174.0
Name: new_cases, dtype: float64
145252 145259    60920.0
Name: new_cases, dtype: float64
145253 145260    63824.0
Name: new_cases, dtype: float64
145254 145261    66990.0
Name: new_cases, dtype: float64
145255 145262    62379.0
Name: new_cases, dtype: float64
145256 145263    54193.0
Name: new_cases, dtype: float64
145257 145264    33974.0
Name: new_cases, dtype: float64
145258 145265    45660.0
Name: new_cases, dtype: float64
145259 145266    50733.0
Name: new_cases, dtype: float64
145260 145267    55093.0
Name: new_cases, dtype: float64
145261 145268    58913.0
Name: new_cases, dtype: float64
145262 145269    58159.0
Name: new_cases, dtype: float64
145263 145270    46660.0
Name: new_cases, dtype: float64
145264 145271    30062.0
Name: new_cases, dtype: float64
145265 145272    48771.0
Name: new_cases, dtype: float64
145266 145273    40799.0
Name: new_cases, dtype: float64
145267 145274    45704.0
Name: new_cases, dtype: float64
145268 145275    46955.0
Name: new_cases, dtype: float64
145269 145276    48106.0
Name: new_cases, dtype: float64
145270 145277    34519.0
Name: new_cases, dtype: float64
145271 145278    22100.0
Name: new_cases, dtype: float64
145272 145279    35152.0
Name: new_cases, dtype: float64
145273 145280    34061.0
Name: new_cases, dtype: float64
145274 145281    36193.0
Name: new_cases, dtype: float64
145275 145282    38529.0
Name: new_cases, dtype: float64
145276 145283    41863.0
Name: new_cases, dtype: float64
145277 145284    29610.0
Name: new_cases, dtype: float64
145278 145285    17441.0
Name: new_cases, dtype: float64
145279 145286    27771.0
Name: new_cases, dtype: float64
145280 145287    27797.0
Name: new_cases, dtype: float64
145281 145288    29508.0
Name: new_cases, dtype: float64
145282 145289    29844.0
Name: new_cases, dtype: float64
145283 145290    28552.0
Name: new_cases, dtype: float64
145284 145291    20574.0
Name: new_cases, dtype: float64
145285 145292    13472.0
Name: new_cases, dtype: float64
145286 145293    24444.0
Name: new_cases, dtype: float64
145287 145294    23090.0
Name: new_cases, dtype: float64
145288 145295    24533.0
Name: new_cases, dtype: float64
145289 145296    27149.0
Name: new_cases, dtype: float64
145290 145297    21923.0
Name: new_cases, dtype: float64
145291 145298    12618.0
Name: new_cases, dtype: float64
145292 145299    7176.0
Name: new_cases, dtype: float64
145293 145300    6111.0
Name: new_cases, dtype: float64
145294 145301    21496.0
Name: new_cases, dtype: float64
145295 145302    17195.0
Name: new_cases, dtype: float64
145296 145303    19104.0
Name: new_cases, dtype: float64
145297 145304    17134.0
Name: new_cases, dtype: float64
145298 145305    14605.0
Name: new_cases, dtype: float64
145299 145306    5825.0
Name: new_cases, dtype: float64
145300 145307    14829.0
Name: new_cases, dtype: float64
145301 145308    13081.0
Name: new_cases, dtype: float64
145302 145309    18989.0
Name: new_cases, dtype: float64
145303 145310    14364.0
Name: new_cases, dtype: float64
145304 145311    24834.0
Name: new_cases, dtype: float64
145305 145312    8764.0
Name: new_cases, dtype: float64
145306 145313    5264.0
Name: new_cases, dtype: float64
145307 145314    12146.0
Name: new_cases, dtype: float64
145308 145315    10900.0
Name: new_cases, dtype: float64
145309 145316    12577.0
Name: new_cases, dtype: float64
145310 145317    10623.0
Name: new_cases, dtype: float64
145311 145318    21365.0
Name: new_cases, dtype: float64
145312 145319    8681.0
Name: new_cases, dtype: float64
145313 145320    4585.0
Name: new_cases, dtype: float64
145314 145321    11336.0
Name: new_cases, dtype: float64
145315 145322    10865.0
Name: new_cases, dtype: float64

145316 145323    13158.0
Name: new_cases, dtype: float64
145317 145324    13662.0
Name: new_cases, dtype: float64
145318 145325    24335.0
Name: new_cases, dtype: float64
145319 145326    8872.0
Name: new_cases, dtype: float64
145320 145327    4382.0
Name: new_cases, dtype: float64
145321 145328    14307.0
Name: new_cases, dtype: float64
145322 145329    6783.0
Name: new_cases, dtype: float64
145323 145330    16323.0
Name: new_cases, dtype: float64
145324 145331    14377.0
Name: new_cases, dtype: float64
145325 145332    29379.0
Name: new_cases, dtype: float64
145326 145333    4899.0
Name: new_cases, dtype: float64
145327 145334    3900.0
Name: new_cases, dtype: float64
145328 145335    8909.0
Name: new_cases, dtype: float64
145329 145336    23074.0
Name: new_cases, dtype: float64
145330 145337    22633.0
Name: new_cases, dtype: float64
145331 145338    19028.0
Name: new_cases, dtype: float64
145332 145339    47491.0
Name: new_cases, dtype: float64
145333 145340    8782.0
Name: new_cases, dtype: float64
145334 145341    11355.0
Name: new_cases, dtype: float64
145335 145342    33051.0
Name: new_cases, dtype: float64
145336 145343    26391.0
Name: new_cases, dtype: float64
145337 145344    33169.0
Name: new_cases, dtype: float64
145338 145345    29908.0
Name: new_cases, dtype: float64
145339 145346    77479.0
Name: new_cases, dtype: float64
145340 145347    12394.0
Name: new_cases, dtype: float64
145341 145348    20195.0
Name: new_cases, dtype: float64
145342 145349    51392.0
Name: new_cases, dtype: float64
145343 145350    40569.0
Name: new_cases, dtype: float64
145344 145351    50584.0
Name: new_cases, dtype: float64
145345 145352    54665.0
Name: new_cases, dtype: float64
145346 145353    119395.0
Name: new_cases, dtype: float64
145347 145354    26111.0
Name: new_cases, dtype: float64
145348 145355    26138.0
Name: new_cases, dtype: float64
145349 145356    85089.0
Name: new_cases, dtype: float64
145350 145357    68739.0
Name: new_cases, dtype: float64
145351 145358    69439.0
Name: new_cases, dtype: float64
145352 145359    79290.0
Name: new_cases, dtype: float64
145353 145360    188071.0
Name: new_cases, dtype: float64
145354 145361    34220.0
Name: new_cases, dtype: float64
145355 145362    43840.0
Name: new_cases, dtype: float64
145356 145363    117751.0
Name: new_cases, dtype: float64
145357 145364    103201.0
Name: new_cases, dtype: float64
145358 145365    96672.0
Name: new_cases, dtype: float64
145359 145366    110923.0
Name: new_cases, dtype: float64
145360 145367    255297.0
Name: new_cases, dtype: float64
145361 145368    51473.0
Name: new_cases, dtype: float64
145362 145369    29324.0
Name: new_cases, dtype: float64
145363 145370    175901.0
Name: new_cases, dtype: float64
145364 145371    121210.0
Name: new_cases, dtype: float64
145365 145372    156258.0
Name: new_cases, dtype: float64
145366 145373    142197.0
Name: new_cases, dtype: float64
145367 145374    229847.0
Name: new_cases, dtype: float64
145368 145375    51829.0
Name: new_cases, dtype: float64
145369 145376    44355.0
Name: new_cases, dtype: float64
145370 145377    214770.0
Name: new_cases, dtype: float64
145371 145378    152821.0
Name: new_cases, dtype: float64
145372 145379    158628.0
Name: new_cases, dtype: float64
145373 145380    157239.0
Name: new_cases, dtype: float64
145374 145381    245686.0
Name: new_cases, dtype: float64
145375 145382    69918.0
Name: new_cases, dtype: float64
145376 145383    39009.0
Name: new_cases, dtype: float64
145377 145384    231409.0
Name: new_cases, dtype: float64
145378 145385    157127.0
Name: new_cases, dtype: float64
145379 145386    169433.0
Name: new_cases, dtype: float64
145380 145387    184447.0
Name: new_cases, dtype: float64
145381 145388    243579.0
Name: new_cases, dtype: float64
145382 145389    65317.0
Name: new_cases, dtype: float64
145383 145390    45551.0
Name: new_cases, dtype: float64
145384 145391    252008.0
Name: new_cases, dtype: float64
145385 145392    171278.0
Name: new_cases, dtype: float64
145386 145393    202253.0
Name: new_cases, dtype: float64
145387 145394    175083.0
Name: new_cases, dtype: float64
145388 145395    235593.0
Name: new_cases, dtype: float64
145389 145396    74105.0
Name: new_cases, dtype: float64
145390 145397    47335.0
Name: new_cases, dtype: float64
145391 145398    80599.0
Name: new_cases, dtype: float64
145392 145399    254798.0
Name: new_cases, dtype: float64
145393 145400    183031.0
Name: new_cases, dtype: float64
145394 145401    160119.0
Name: new_cases, dtype: float64
145395 145402    228209.0
Name: new_cases, dtype: float64
145396 145403    73627.0
Name: new_cases, dtype: float64
145397 145404    42905.0
Name: new_cases, dtype: float64
145398 145405    244526.0
Name: new_cases, dtype: float64
145399 145406    146190.0
Name: new_cases, dtype: float64
145400 145407    170585.0
Name: new_cases, dtype: float64
145401 145408    155514.0
Name: new_cases, dtype: float64
145402 145409    208874.0
Name: new_cases, dtype: float64
145403 145410    64282.0
Name: new_cases, dtype: float64
145404 145411    42201.0
Name: new_cases, dtype: float64
145405 145412    188409.0
Name: new_cases, dtype: float64
145406 145413    121659.0
Name: new_cases, dtype: float64
145407 145414    133133.0
Name: new_cases, dtype: float64
145408 145415    126474.0
Name: new_cases, dtype: float64
145409 145416    176908.0
Name: new_cases, dtype: float64
145410 145417    54030.0
Name: new_cases, dtype: float64
145411 145418    49630.0
Name: new_cases, dtype: float64
145412 145419    164666.0
Name: new_cases, dtype: float64
145413 145420    111379.0
Name: new_cases, dtype: float64
145414 145421    123419.0
Name: new_cases, dtype: float64
145415 145422    109956.0
Name: new_cases, dtype: float64
145416 145423    152877.0
Name: new_cases, dtype: float64
145417 145424    44987.0
Name: new_cases, dtype: float64
145418 145425    41778.0
Name: new_cases, dtype: float64
145419 145426    151269.0
Name: new_cases, dtype: float64
145420 145427    97379.0
Name: new_cases, dtype: float64
145421 145428    110591.0
Name: new_cases, dtype: float64
145422 145429    100546.0
Name: new_cases, dtype: float64
145423 145430    126477.0
Name: new_cases, dtype: float64
145424 145431    32838.0
Name: new_cases, dtype: float64
145425 145432    37627.0
Name: new_cases, dtype: float64
145426 145433    100641.0
Name: new_cases, dtype: float64
145427 145434    106375.0
Name: new_cases, dtype: float64
145428 145435    121576.0
Name: new_cases, dtype: float64
145429 145436    86378.0
Name: new_cases, dtype: float64
145430 145437    109796.0
Name: new_cases, dtype: float64
145431 145438    36361.0
Name: new_cases, dtype: float64
145432 145439    31932.0
Name: new_cases, dtype: float64
145433 145440    102200.0
Name: new_cases, dtype: float64
145434 145441    80948.0
Name: new_cases, dtype: float64
145435 145442    91456.0
Name: new_cases, dtype: float64
145436 145443    78899.0
Name: new_cases, dtype: float64
145437 145444    95152.0
Name: new_cases, dtype: float64
145438 145445    30141.0
Name: new_cases, dtype: float64
145439 145446    18225.0
Name: new_cases, dtype: float64
145440 145447    114302.0
Name: new_cases, dtype: float64
145441 145448    68711.0
Name: new_cases, dtype: float64
145442 145449    100901.0
Name: new_cases, dtype: float64
145443 145450    77552.0
Name: new_cases, dtype: float64
145444 145451    93585.0
Name: new_cases, dtype: float64
145445 145452    32572.0
Name: new_cases, dtype: float64
145446 145453    31700.0
Name: new_cases, dtype: float64
145447 145454    113983.0
Name: new_cases, dtype: float64
145448 145455    71117.0
Name: new_cases, dtype: float64
145449 145456    84577.0
Name: new_cases, dtype: float64
145450 145457    81830.0
Name: new_cases, dtype: float64
145451 145458    96087.0
Name: new_cases, dtype: float64
145452 145459    34058.0
Name: new_cases, dtype: float64
145453 145460    35896.0
Name: new_cases, dtype: float64
145454 145461    110605.0
Name: new_cases, dtype: float64
145455 145462    80323.0
Name: new_cases, dtype: float64
145456 145463    95021.0
Name: new_cases, dtype: float64
145457 145464    57164.0
Name: new_cases, dtype: float64
145458 145465    144899.0
Name: new_cases, dtype: float64
145459 145466    42556.0
Name: new_cases, dtype: float64
145460 145467    31093.0
Name: new_cases, dtype: float64
145461 145468    136847.0
Name: new_cases, dtype: float64
145462 145469    87845.0
Name: new_cases, dtype: float64
145463 145470    111732.0
Name: new_cases, dtype: float64
145464 145471    110350.0
Name: new_cases, dtype: float64
145465 145472    125867.0
Name: new_cases, dtype: float64
145466 145473    43702.0
Name: new_cases, dtype: float64
145467 145474    38931.0
Name: new_cases, dtype: float64
145468 145475    147706.0
Name: new_cases, dtype: float64
145469 145476    92722.0
Name: new_cases, dtype: float64
145470 145477    111648.0
Name: new_cases, dtype: float64
145471 145478    34805.0
Name: new_cases, dtype: float64
145472 145479    52090.0
Name: new_cases, dtype: float64
145473 145480    25493.0
Name: new_cases, dtype: float64
145474 145481    42148.0
Name: new_cases, dtype: float64
145475 145482    192793.0
Name: new_cases, dtype: float64
145476 145483    117485.0
Name: new_cases, dtype: float64
145477 145484    138611.0
Name: new_cases, dtype: float64
145478 145485    138440.0
Name: new_cases, dtype: float64

145479 145486    153659.0
Name: new_cases, dtype: float64
145480 145487    63622.0
Name: new_cases, dtype: float64
145481 145488    49801.0
Name: new_cases, dtype: float64
145482 145489    179786.0
Name: new_cases, dtype: float64
145483 145490    113304.0
Name: new_cases, dtype: float64
145484 145491    150872.0
Name: new_cases, dtype: float64
145485 145492    122214.0
Name: new_cases, dtype: float64
145486 145493    170738.0
Name: new_cases, dtype: float64
145487 145494    54763.0
Name: new_cases, dtype: float64
145488 145495    50568.0
Name: new_cases, dtype: float64
145489 145496    187285.0
Name: new_cases, dtype: float64
145490 145497    116071.0
Name: new_cases, dtype: float64
145491 145498    144097.0
Name: new_cases, dtype: float64
145492 145499    141707.0
Name: new_cases, dtype: float64
145493 145500    192903.0
Name: new_cases, dtype: float64
145494 145501    76429.0
Name: new_cases, dtype: float64
145495 145502    86859.0
Name: new_cases, dtype: float64
145496 145503    242086.0
Name: new_cases, dtype: float64
145497 145504    178982.0
Name: new_cases, dtype: float64
145498 145505    241681.0
Name: new_cases, dtype: float64
145499 145506    269233.0
Name: new_cases, dtype: float64
145500 145507    219462.0
Name: new_cases, dtype: float64
145501 145508    57054.0
Name: new_cases, dtype: float64
145502 145509    182566.0
Name: new_cases, dtype: float64
145503 145510    544329.0
Name: new_cases, dtype: float64
145504 145511    354683.0
Name: new_cases, dtype: float64
145505 145512    497002.0
Name: new_cases, dtype: float64
145506 145513    590547.0
Name: new_cases, dtype: float64
145507 145514    472515.0
Name: new_cases, dtype: float64
145508 145515    116442.0
Name: new_cases, dtype: float64
145509 145516    248174.0
Name: new_cases, dtype: float64
145510 145517    1171378.0
Name: new_cases, dtype: float64
145511 145518    799189.0
Name: new_cases, dtype: float64
145512 145519    623308.0
Name: new_cases, dtype: float64
145513 145520    786824.0
Name: new_cases, dtype: float64
145514 145521    900832.0
Name: new_cases, dtype: float64
145515 145522    378692.0
Name: new_cases, dtype: float64
145516 Series([], Name: new_cases, dtype: float64)
145517 Series([], Name: new_cases, dtype: float64)
145518 Series([], Name: new_cases, dtype: float64)
145519 Series([], Name: new_cases, dtype: float64)
145520 Series([], Name: new_cases, dtype: float64)
145521 Series([], Name: new_cases, dtype: float64)
145522 Series([], Name: new_cases, dtype: float64)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,total_cases_per_million,...,ds,country,code,country_official_name,lower_window,upper_window,prior_scale,source,7_days_later,7_days_later_cases
1394,ALB,Europe,Albania,2020-03-09,2.0,2.0,NaN,NaN,NaN,0.696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-16,9.0
1395,ALB,Europe,Albania,2020-03-10,10.0,8.0,NaN,NaN,NaN,3.481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-17,4.0
1396,ALB,Europe,Albania,2020-03-11,12.0,2.0,NaN,1.0,1.0,4.177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-18,4.0
1397,ALB,Europe,Albania,2020-03-12,23.0,11.0,NaN,1.0,0.0,8.006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-19,5.0
1398,ALB,Europe,Albania,2020-03-13,33.0,10.0,NaN,1.0,0.0,11.487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-20,6.0
1399,ALB,Europe,Albania,2020-03-14,38.0,5.0,5.429,1.0,0.0,13.227,...,2020-03-21,Albania,AL,Republic of Albania,-3.0,3.0,10.0,https://en.wikipedia.org/wiki/Public_holidays_...,2020-03-21,6.0
1400,ALB,Europe,Albania,2020-03-15,42.0,4.0,6.000,1.0,0.0,14.619,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-22,13.0
1401,ALB,Europe,Albania,2020-03-16,51.0,9.0,7.000,1.0,0.0,17.752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-23,15.0
1402,ALB,Europe,Albania,2020-03-17,55.0,4.0,6.429,1.0,0.0,19.144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-24,19.0
1403,ALB,Europe,Albania,2020-03-18,59.0,4.0,6.714,2.0,1.0,20.536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-25,23.0
1404,ALB,Europe,Albania,2020-03-19,64.0,5.0,5.857,2.0,0.0,22.277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-26,28.0
1405,ALB,Europe,Albania,2020-03-20,70.0,6.0,5.286,2.0,0.0,24.365,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-27,12.0
1406,ALB,Europe,Albania,2020-03-21,76.0,6.0,5.429,2.0,0.0,26.454,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-28,11.0
1407,ALB,Europe,Albania,2020-03-22,89.0,13.0,6.714,2.0,0.0,30.979,...,2020-03-29,Albania,AL,Republic of Albania,-3.0,3.0,10.0,https://en.wikipedia.org/wiki/Public_holidays_...,2020-03-29,15.0
1408,ALB,Europe,Albania,2020-03-23,104.0,15.0,7.571,4.0,2.0,36.200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-30,11.0